### ISSUE TITLE
'Architectural overview' page wrong about Navigator using InheritedWidget?

### ISSUE THREAD

**Issue by wujek-srujek** [flutter/website#10005]
The documentation as of right now (https://github.com/flutter/website/blob/a286db4452b98d84909029f04d7ffbb88779b114/src/resources/architectural-overview.md?plain=1#L505-L506) claims that `Navigator` is implemented using `InheritedWidget`. This seems not to be the case, as can be seen here: https://github.com/flutter/flutter/blob/95dfde836918eb10259e780be3cb381e396259f1/packages/flutter/lib/src/widgets/navigator.dart#L2686-L2690 - the lookup doesn't use `InheritedWidget`, it walks the tree and looks for the state instead.

As a side question - wouldn't it be beneficial for `Navigator.of` to be implemented using `InheritedWidget` (at least when `rootNavigator` is `false`), and not an `O(N)` tree walk? It probably happens very often that deep widget tree leaves (like buttons) look it up to perform navigation?

**Comment by atsansone** [comment]
@craiglabenz : Before we try to tackle this, do you have any insight to offer?

**Comment by craiglabenz** [comment]
OP is correct; `Navigator` does not use `InheritedWidget`. It implements the `InheritedWidget`'s most important API, but differently. Toward that end, given the low frequency of navigation events (surely < 1 / second), this is unlikely to be a performance issue in most apps. The Navigator could be refactored to use `InheritedWidget`, but performance measurements indicating a problem should probably come first.

Regarding the documentation, we could either:

a) replace mention of `Navigator` with a widget that uses `InheritedWidget`, or
b) clarify that `Navigator` implements the same API

**Comment by atsansone** [comment]
@craiglabenz : How is this the same? The `of` method? I'm unsure.

**Comment by craiglabenz** [comment]
Yes, the static `of` method is the most important aspect of an `InheritedWidget`.

**Comment by atsansone** [comment]
Change this:

This approach is also used for ~~[Navigator](https://api.flutter.dev/flutter/widgets/Navigator-class.html), which provides page routing; and~~ [MediaQuery](https://api.flutter.dev/flutter/widgets/MediaQuery-class.html), which provides access to screen metrics such as orientation, dimensions, and brightness.
