### ISSUE TITLE
Packages & Plugins - Federated Plugins - Medium examples linked are missing data

### ISSUE THREAD

**Issue by AlanJereb** [flutter/website#10006]
### Page URL

https://docs.flutter.dev/packages-and-plugins/developing-packages#federated-plugins

### Describe the problem

At the bottom of the Federated Plugins section, there is a link to a Medium article containing an example of how to write one.
The linked Medium article is missing some code examples - empty space where the code should be. (the same goes for the Part 1 of this article)

![image](https://github.com/flutter/website/assets/24469472/d2c77a9c-506a-4f71-9ca9-93625a95d019)

### Expected fix

Re-add code examples inside the article.

**Comment by huycozy** [comment]
Kindly cc @harryterkelsen (article's author). Could you please give help here?

**Comment by atsansone** [comment]
@harryterkelsen : Any chance you would be able to replace the missing images? Thanks!

**Comment by harryterkelsen** [comment]
Fixed
