### ISSUE TITLE
[PAGE ISSUE]: 'Start building Flutter Android apps on Windows'

### ISSUE THREAD

**Issue by dhvlc** [flutter/website#10002]
### Page URL

https://docs.flutter.dev/get-started/install/windows/mobile/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/windows/mobile.md

### Describe the problem

Problem consists inside the "Install the Flutter SDK" section. While clicking on download and install button the page doesn't provide that section, i mean while clicking the button no change or movement in the section. Actually I want to download Flutter SDK zip file but I am not able to find it under Download and Install option. While clicking on the button only URL changes but the page is stuck there.

### Expected fix

When you click the download and install button, it should show the contents of it properly with files including flutter sdk zip file.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by atsansone** [comment]
@dhvlc : My apologies, but I don't experience the same issue. 

![image](https://github.com/flutter/website/assets/706219/30375651-64e5-4a9f-8f40-c9e5f016e108)

Does this occur if you try this URL? https://docs.flutter.dev/get-started/install/windows/mobile?tab=download
