### ISSUE TITLE
[PAGE ISSUE]: 'Start building Flutter native desktop apps on macOS'

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/website#10016]
### Page URL

https://docs.flutter.dev/get-started/install/macos/desktop/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/macos/desktop.md

### Describe the problem

The "Download and install" steps do not mention the need to add Flutter's bin folder to the path.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by atsansone** [comment]
This duplicates #9351. Closing this issue.

**Comment by TheCarpetMerchant** [comment]
I do not think this is a duplicate. The instructions I saw do not make mention of any command to add the path.
