### ISSUE TITLE
Adjust provenance download link texts on 'Flutter SDK archive' page

### ISSUE THREAD

**Issue by TheCarpetMerchant** [flutter/website#10014]
### Page URL

https://docs.flutter.dev/release/archive/

### Page source

https://github.com/flutter/website/tree/main/src/release/archive.md

### Describe the problem

On macOS 13.5 with Firefox, links to the different archives do not work and just opne the json content. Additionally, it seems to arm archives actually lead to the x64 archives.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by TheCarpetMerchant** [comment]
Ah, my bad. Wasn't clear at all for me, as usually such download links are not shown on the same importance level as the actual page subject.

**Comment by parlough** [comment]
I think that's a great point and we should probably rename the provenance download link text to make it more obvious.

I'd like to completely overhaul the page, but we should at least fix this in the mean time.
