### ISSUE TITLE
apres installation de flutter

### ISSUE THREAD

**Issue by zambo2** [flutter/website#10020]
### Page URL

This crash may already be reported. Check GitHub for similar crashes. https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Exists+failed%2C+path+%3D+%27D%3A%5C Plugin%5Cflutter_2_2_3%5Cflutter_2_2_3%5Cflutter%5C.pub-cache%5Chosted%5Cpub.dartlang.org%5C_fe_analyzer_shared-21 .0.0%5Clib%5C%27+%28OS+Error%3A+Le+p%C3%A9riph%C3%A9rique+n%E2%80%99est+pas+pr%C3%AAt.%0D%0A%2C+errno+%3D+21%29

### Page source

This crash may already be reported. Check GitHub for similar crashes. https://github.com/flutter/flutter/issues?q=is%3Aissue+FileSystemException%3A+Exists+failed%2C+path+%3D+%27D%3A%5C Plugin%5Cflutter_2_2_3%5Cflutter_2_2_3%5Cflutter%5C.pub-cache%5Chosted%5Cpub.dartlang.org%5C_fe_analyzer_shared-21 .0.0%5Clib%5C%27+%28OS+Error%3A+Le+p%C3%A9riph%C3%A9rique+n%E2%80%99est+pas+pr%C3%AAt.%0D%0A%2C+errno+%3D+21%29

### Describe the problem

depuis que j'ai installer flutter  ca refuse le commade comme doctor et ca renoie le message ci dessous
https://github.com/flutter/flutter/issues/new?title=%5Btool_crash%5D+FileSystemException%3A+Exists+failed%2C+OS+Er
ror%3A+Le+p%C3%A9riph%C3%A9rique+n%E2%80%99est+pas+pr%C3%AAt.%0D%0A%2C+errno+%3D+21&body=%23%23+Command%0A%60%60%6
0%0Aflutter+create+bugmain.dart%0A%60%60%60%0A%0A%23%23+Steps+to+Reproduce%0A1.+...%0A2.+...%0A3.+...%0A%0A%23%23+
Logs%0AFileSystemException%3A+Exists+failed%2C+OS+Error%3A+Le+p%C3%A9riph%C3%A9rique+n%E2%80%99est+pas+pr%C3%AAt.%
0D%0A%2C+errno+%3D+21%0A%60%60%60%0A%230++++++_Directory.existsSync+%28dart%3Aio%2Fdirectory_impl.dart%3A94%3A7%29
%0A%231++++++ForwardingFileSystemEntity.existsSync+%28package%3Afile%2Fsrc%2Fforwarding%2Fforwarding_file_system_e
ntity.dart%3A43%3A33%29%0A%232++++++ErrorHandlingDirectory.existsSync.%3Canonymous+closure%3E+%28package%3Aflutter
_tools%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A479%3A22%29%0A%233++++++_runSync+%28package%3Aflutter_tools%2Fsrc%2
Fbase%2Ferror_handling_io.dart%3A573%3A14%29%0A%234++++++ErrorHandlingDirectory.existsSync+%28package%3Aflutter_to
ols%2Fsrc%2Fbase%2Ferror_handling_io.dart%3A478%3A12%29%0A%235++++++PubDependencies.isUpToDate+%28package%3Aflutte
r_tools%2Fsrc%2Fflutter_cache.dart%3A104%3A57%29%0A%3Casynchronous+suspension%3E%0A%236++++++Cache.updateAll+%28pa
ckage%3Aflutter_tools%2Fsrc%2Fcache.dart%3A542%3A11%29%0A%3Casynchronous+suspension%3E%0A%237++++++FlutterCommand.
verifyThenRunCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command.dart%3A1143%3A7%29%0A%3Casynchron
ous+suspension%3E%0A%238++++++FlutterCommand.run.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner
%2Fflutter_command.dart%3A1043%3A27%29%0A%3Casynchronous+suspension%3E%0A%239++++++AppContext.run.%3Canonymous+clo
sure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0A%23
10+++++CommandRunner.runCommand+%28package%3Aargs%2Fcommand_runner.dart%3A196%3A13%29%0A%3Casynchronous+suspension
%3E%0A%2311+++++FlutterCommandRunner.runCommand.%3Canonymous+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Frunner%
2Fflutter_command_runner.dart%3A284%3A9%29%0A%3Casynchronous+suspension%3E%0A%2312+++++AppContext.run.%3Canonymous
+closure%3E+%28package%3Aflutter_tools%2Fsrc%2Fbase%2Fcontext.dart%3A150%3A19%29%0A%3Casynchronous+suspension%3E%0
A%2313+++++FlutterCommandRunner.runCommand+%28package%3Aflutter_tools%2Fsrc%2Frunner%2Fflutter_command_runner.dart
%3A232%3A5%29%0A%3Casynchronous+suspension%3E%0A%2314+++++run.%3Canonymous+closure%3E.%3Canonymous+closure%3E+%28p
ackage%3Aflutter_tools%2Frunner.dart%3A62%3A9%29%0A%3Casynchronous+suspension%3E%0A%60%60%60%0A%60%60%60%0A%5B%E2%
9C%93%5D+Flutter+%28Channel+stable%2C+2.2.3%2C+on+Microsoft+Windows+%5Bversion+10.0.17763.134%5D%2C+locale+fr-CD%2
9%0A++++%E2%80%A2+Flutter+version+2.2.3+at+F%3A%5Cflutter_2_2_3%5Cflutter_2_2_3%5Cflutter%0A++++%E2%80%A2+Framewor
k+revision+f4abaa0735+%282+years%2C+6+months+ago%29%2C+2021-07-01+12%3A46%3A11+-0700%0A++++%E2%80%A2+Engine+revisi
on+241c87ad80%0A++++%E2%80%A2+Dart+version+2.13.4%0A%0A%5B%E2%9C%97%5D+Android+toolchain+-+develop+for+Android+dev
ices%0A++++%E2%9C%97+Unable+to+locate+Android+SDK.%0A++++++Install+Android+Studio+from%3A+https%3A%2F%2Fdeveloper.
android.com%2Fstudio%2Findex.html%0A++++++On+first+launch+it+will+assist+you+in+installing+the+Android+SDK+compone
nts.%0A++++++%28or+visit+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall%2Fwindows%23android-setup+for+de
tailed+instructions%29.%0A++++++If+the+Android+SDK+has+been+installed+to+a+custom+location%2C+please+use%0A++++++%
60flutter+config+--android-sdk%60+to+update+to+that+location.%0A%0A%0A%5B%E2%9C%93%5D+Chrome+-+develop+for+the+web
%0A++++%E2%80%A2+Chrome+at+C%3A%5CProgram+Files%5CGoogle%5CChrome%5CApplication%5Cchrome.exe%0A%0A%5B%21%5D+Androi
d+Studio+%28not+installed%29%0A++++%E2%80%A2+Android+Studio+not+found%3B+download+from+https%3A%2F%2Fdeveloper.and
roid.com%2Fstudio%2Findex.html%0A++++++%28or+visit+https%3A%2F%2Fflutter.dev%2Fdocs%2Fget-started%2Finstall%2Fwind
ows%23android-setup+for+detailed+instructions%29.%0A%0A%5B%E2%9C%93%5D+VS+Code+%28version+1.85.1%29%0A++++%E2%80%A
2+VS+Code+at+C%3A%5CUsers%5CI+AM+ZAMBO+LEFILS%5CAppData%5CLocal%5CPrograms%5CMicrosoft+VS+Code%0A++++%E2%80%A2+Flu
tter+extension+version+3.80.0%0A%0A%5B%E2%9C%93%5D+Connected+device+%282+available%29%0A++++%E2%80%A2+Chrome+%28we
b%29+%E2%80%A2+chrome+%E2%80%A2+web-javascript+%E2%80%A2+Google+Chrome+119.0.6045.124%0A++++%E2%80%A2+Edge+%28web%
29+++%E2%80%A2+edge+++%E2%80%A2+web-javascript+%E2%80%A2+Microsoft+Edge+120.0.2210.91%0A%0A%21+Doctor+found+issues
+in+2+categories.%0A%0A%60%60%60%0A%0A%23%23+Flutter+Application+Metadata%0ANo+pubspec+in+working+directory.%0A&la
bels=tool%2Csevere%3A+crash

### Expected fix

aucunne idee

### Additional context

aucunne

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment]
Hi @zambo2 
This issue seems to be suited to [Flutter repository](https://github.com/flutter/flutter) than here, so please open a new issue there for better support. 

Please try provide all information indicated in the [bug](https://github.com/flutter/flutter/issues/new?assignees=&labels=&projects=&template=2_bug.yml) issue template. Or you may just click on the url from the output console that will open web browser.

Closing this as it's not a website issue.
