### ISSUE TITLE
'--no-shrink' flag documentation is out of date

### ISSUE THREAD

**Issue by gmackall** [flutter/website#10032]
### Page URL

https://docs.flutter.dev/deployment/android#shrinking-your-code-with-r8

### Describe the problem

Our documentation doesn't note that the `--no-shrink` flag has no effect on release builds. Running `flutter build apk --help --verbose` provides the following
```
--[no-]shrink                                            This flag has no effect. Code shrinking is always enabled in release builds. To learn more, see:
                                                             https://developer.android.com/studio/build/shrink-code
```

We should update the page to reflect this.

This was initially reported in https://github.com/flutter/flutter/issues/141164, so I'm making this issue to track it as a website issue instead. Thanks @yanshouwang for the issue report.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by Martins100-Tmd** [comment]
Can I work on this?

**Comment by atsansone** [comment]
@Martins100-Tmd : Sure! Sorry that we missed your volunteering!

**Comment by atsansone** [comment]
@Martins100-Tmd : Did you still want to work on this issue?
