### ISSUE TITLE
Install page issues for developing on iOS

### ISSUE THREAD

**Issue by leighajarett** [flutter/website#10036]
### Page URL

https://docs.flutter.dev/get-started/install/macos/mobile-ios?tab=vscode

### Describe the problem

I ran into a few issues with the install page when setting up my new computer. 

First, users need to install the VSCode extension before being able to navigate to the start a new flutter project - I don't think that was clear from this document. Next, it says "Git for Windows" even though this is the macOS page

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by atsansone** [comment]
@leighajarett : Part of this will be fixed in https://github.com/flutter/website/pull/10031. I can fix the "Git for Windows" in that PR, too.
