### ISSUE TITLE
macOS hardware requirements mention x86-64 cpu cores?

### ISSUE THREAD

**Issue by parlough** [flutter/website#10040]
### Page URL

https://docs.flutter.dev/get-started/install/macos/mobile-ios/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/macos/mobile-ios.md

### Describe the problem

The hardware requirements on this page mention "x86_64" CPU cores. It's not clear to me why the x86_64 specifier is there, as it could lead users to thinking ARM Mac laptops aren't supported, or just confuse them in general.

I've also never heard of this core count requirement. Where did these numbers come from?

### Expected fix

I guess drop the x86_64 specifier? Or just the core count requirement completely.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by atsansone** [comment]
The CPU requirements came from the associated tools, like Android Studio. That said, I'll update the CPU types.
