### ISSUE TITLE
Add excerpts for snippets on 'Navigation and routing' page

### ISSUE THREAD

**Issue by parlough** [flutter/website#10057]
### Page URL

https://docs.flutter.dev/ui/navigation/

### Page source

https://github.com/flutter/website/tree/main/src/ui/navigation/index.md

### Describe the problem

The code snippets on this page don't have excerpts and therefore can easily get out of date or fail analysis in the first place.

### Expected fix

Add [code excerpts](https://github.com/dart-lang/site-shared/blob/main/doc/code-excerpts.md) to this page.

**Comment by antfitch** [comment]
I added the fully functional code samples, but I realized that they essentially repeat what is in the other sections under `Navigation & routing`.  I am holding off on pushing a PR until we take another look at this section. I took a closer look at other overviews and noticed a preference to show visuals instead of code.

My thoughts: we remove the code samples and use illustrations and animated gifs to provide a high-level overview for the navigator, named routes, and router. Then, we make sure to link to the recipes and reference documentation. Links have generally already been done.

**Comment by parlough** [comment]
> sfshaza2 and parlough how would you feel about this?

Illustrations, images, and animations are always great and I do love the idea of more visual overviews of sections as well a repeating ourselves less :D

I'm just personally having trouble visualizing how the basics of the APIs can be explained without some code snippets to put them in context. I don't want to lose that information as the recipes don't cover them and the API reference docs are too dense for developers just wanting to know what API to use before learning the rest in their IDE.

Perhaps those contextualized basics aren't best located in the overview though, and should be covered in a new section of the in-progress [Fundamentals/FWE docs](https://docs.flutter.dev/get-started/fundamentals)?

I'd love to see what you have in mind and even if we can't fully drop the snippets yet, whatever you come up with could live side by side with reduced versions of the snippets.

**Comment by parlough** [comment]
I just realized I'm not sure what you meant was repeating the other sections. Do you mean the existing code snippets on the page or the entire "fully functional code samples" you mentioned?

I do think we should make the changes you propose, but I think it'd be beneficial to first open and land the PR adding the excerpts. As that work is separate and beneficial, even if we end up dropping them soon.

**Comment by antfitch** [comment]
Will do so, but essentially, I will be adding the same code snippets from existing sections that already exist.

**Comment by parlough** [comment]
> Will do so, but essentially, I will be adding the same code snippets from existing sections that already exist.

Can you clarify? The original intention of this issue was to add [code excerpts](https://github.com/dart-lang/site-shared/tree/main/pkgs/excerpter#markdown-code-block-excerpt-updater) for the snippets already on the page. So the contents of the page wouldn't need to change at all. Code excerpts just allow us to to specify analyzed and formatted code as backing code blocks, so we know their contents are valid code.

If there are snippets on other pages that are similar, they could even share the same backing code, or be made the same if necessary.
