### ISSUE TITLE
Submitting Additional Resources (Articles) for building various Flutter desktop distributions (`.dmg`, `.exe`, `.deb`, `.rpm`)

### ISSUE THREAD

**Issue by ashitaprasad** [flutter/website#10084]
### Page URL

https://docs.flutter.dev/platform-integration

### Describe the problem

I recently published a 3-articles series which provides step-by-step process for creating various distribution builds (`.dmg`, `.exe`, `.deb`, `.rpm`) that can be distributed the indie way or open source way via GitHub or self-hosting. Distribution via official stores has been extensively documented in the Flutter docs, and these articles will complement the existing docs and provide Flutter developers with resources to learn how to distribute their Flutter desktop apps via distribution methods followed by the open source community.

The articles are not behind any membership wall/paywall and are free to read.

Link to all the articles:

1. Series Introduction and Creating macOS .app & .dmg - [Link](https://medium.com/@fluttergems/packaging-and-distributing-flutter-desktop-apps-the-missing-guide-part-1-macos-b36438269285)
2. Creating Windows .exe installer - [Link](https://medium.com/@fluttergems/packaging-and-distributing-flutter-desktop-apps-the-missing-guide-part-2-windows-0b468d5e9e70 )
3. Creating Linux Debian (.deb) & RPM (.rpm) builds - [Link](https://medium.com/@fluttergems/packaging-and-distributing-flutter-desktop-apps-the-missing-guide-part-3-linux-24ef8d30a5b4 )

Can I submit a PR to add the links to these articles to the relevant pages of the docs as it would greatly benefit the Flutter community. 

So far, the entire article series has been very well received and appreciated by the community ([Ref 1](https://codewithandrea.com/newsletter/january-2024/), [Ref 2](https://fluttertap.com/archive/issue-196-flutter-tap-weekly-newsletter/), [Ref 3](https://www.alvinashcraft.com/2024/01/16/)).

### Expected fix

Adding Article links to the **Other resources** section of the desktop platforms (Windows, macOS & Linux) inside [Platform integration](https://docs.flutter.dev/platform-integration).

They can also go inside the [Deployment](https://docs.flutter.dev/deployment) section, but this section covers the official channels in detail and adding these articles here felt a little out of place to me. 

Please do let me know the most relevant section where adding them would benefit Flutter developers the most.

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment]
Hi @ashitaprasad 
I think this is best suited to [Deployment](https://docs.flutter.dev/deployment) sections rather than putting them to [Platform integration](https://docs.flutter.dev/platform-integration). Let's wait for other other's opinions.

**Comment by ashitaprasad** [comment]
Sure @huycozy 
It was definitely a bit tricky when I was deciding. To further elaborate on my chain of thought:
- For macOS: The article goes well in the [`Deployment > macOS`](https://docs.flutter.dev/deployment/macos)

- For Windows:
If one takes a look at page [`Platform integration > Windows > Windows development`](https://docs.flutter.dev/platform-integration/windows/building) section [`Distributing Windows apps > Building your own zip file for Windows`](https://docs.flutter.dev/platform-integration/windows/building#building-your-own-zip-file-for-windows), the section ends with 
```At this point if desired it would be relatively simple to add this folder to a Windows installer such as Inno Setup, WiX, etc.```
The [Creating Windows .exe installer article](https://medium.com/@fluttergems/packaging-and-distributing-flutter-desktop-apps-the-missing-guide-part-2-windows-0b468d5e9e70) actually picks up from here and shows the step by step process of creating the `.exe` file for distribution.

- For Linux:
[`Platform integration > Linux > Linux development`](https://docs.flutter.dev/platform-integration/linux/building) talks about [Preparing Linux apps for distribution](https://docs.flutter.dev/platform-integration/linux/building#preparing-linux-apps-for-distribution). The penultimate paragraph of this section reads 
```To wrap up this application for distribution you need to include everything in the bundle directory, and make sure the Linux system you are installing it on has all of the system libraries required.``` 
and ends with
```For information on publishing a Linux application to the Snap Store, see Build and release a Linux application to the Snap Store.```
The [Creating Linux Debian (.deb) & RPM (.rpm) builds](https://medium.com/@fluttergems/packaging-and-distributing-flutter-desktop-apps-the-missing-guide-part-3-linux-24ef8d30a5b4) article builds up on this section and helps provide the route that can be taken by developers who want to package and distribute via `.rpm`& `.deb` builds instead of snap store.
Whereas, [`Deployment > Linux`](https://docs.flutter.dev/deployment/linux) covers `Build and release a Linux app to the Snap Store` in detail including the `Additional resources` which include snapcraft.io links.

I hope the above points will help in better deciding the relevant sections. Eagerly waiting for everyone's opinion. 
Thank you!

**Comment by atsansone** [comment]
@dnfield : I think these are good resources. Can we discuss?

**Comment by ashitaprasad** [comment]
Hi @dnfield Can you kindly take a took at the resources and provide your feedback.
Thanks!

**Comment by sfshaza2** [comment]
Hi, @ashitaprasad! These resources do look good and I am ok with your placement of these docs. Please go ahead and submit a PR. thx!

**Comment by ashitaprasad** [comment]
Thank you @sfshaza2 
I have raised the PR #10406
