### ISSUE TITLE
`super.initState()` should come first in the override of `initState()` in code sample on `Deferred components` page

### ISSUE THREAD

**Issue by RandalSchwartz** [flutter/website#10100]
### Page URL

https://docs.flutter.dev/perf/deferred-components/

### Page source

https://github.com/flutter/website/tree/main/src/perf/deferred-components.md

### Describe the problem

`super.initState()` should come first in the override of `initState()`.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment]
Thanks for the report. Quoting this from [initState](https://api.flutter.dev/flutter/widgets/State/initState.html) doc as well:

>Implementations of this method should start with a call to the inherited method, as in super.initState().
