### ISSUE TITLE
Fix unzip command for macOS install page

### ISSUE THREAD

**Issue by PierreJanineh** [flutter/website#10117]
### Page URL

https://docs.flutter.dev/get-started/install/macos/mobile-android?tab=download#download

### Page source

https://github.com/flutter/website/blob/main/src/_includes/docs/install/flutter/download.md

### Describe the problem

The command
```terminal
$ unzip ~/development/flutter_sdk_v1.0.0.zip ~/development/
```
provided under

> 3. Extract the zip file into the directory you want to store the Flutter SDK.

returns an error and does not work
```terminal
Archive: ~/development/flutter_macos_arm64_3.16.9-stable.zip
caution: filename not matched:  ~/development
```

### Expected fix

To unzip an archive with the `unzip` command in a Unix-like terminal (aka, macOS), we don't specify the target directory as a direct argument. Instead, we use the `-d` option followed by the path to the directory where we want to extract the files.
If the target directory doesn't exist, unzip will attempt to create it.

So the value of `{{uz}}` under

> 3. Extract the zip file into the directory you want to store the Flutter SDK.

must be:
```terminal
$ unzip ~/development/flutter_sdk_v1.0.0.zip -d ~/development/
```

Also, we might want to consider removing this redundant step

> 2. Create a folder where you can install Flutter.

### Additional context

I've tried fixing the issue myself but I'm unable to locate where these template variables (like `{{uz}}`) are defined or how they are managed within the project.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by atsansone** [comment]
Thank you for raising this issue!

Your change is correct. I will update soon. Thanks again!

**Comment by VardyNg** [comment]
I have the same issue and found this issue, hope the fix is coming up soon.

**Comment by rafaeIpereira** [comment]
this command is not working for me, it's saying "cannot find or open: "

This line code is on https://docs.flutter.dev/get-started/install/macos/mobile-ios

`unzip ~/Downloads/flutter_macos_arm64_3.24.0-stable.zip \ -d ~/development/`
