### ISSUE TITLE
[PAGE ISSUE]: 'Deprecated imperative apply of Flutter's Gradle plugins'

### ISSUE THREAD

**Issue by under3415** [flutter/website#10114]
### Page URL

https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply/

### Page source

https://github.com/flutter/website/tree/main/src/release/breaking-changes/flutter-gradle-plugin-apply.md

### Describe the problem

[firebase_crashlytics install instructions](https://pub.dev/packages/firebase_crashlytics/install) do not mention adding a plugin to Gradle config. I am successfully using Crashlytics in my Flutter project without this. Should below two lines be removed?

```
 plugins {
 +    id "com.google.firebase.crashlytics" version "2.9.9" apply false
 }
```

```
plugins {
+    id "com.google.firebase.crashlytics"
}
```

### Expected fix

Remove Crashlytics plugin from config

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment]
It could be an issue with Firebase docs. But I think this section should be kept. For instance, some old projects still use Groovy and devs need to migrate, they will look for the migration guideline. 

Since you said you don't need to add Crashlytics Gradle plugin to your app and it's still working, could you please share all steps you did on a new project? Thanks!

**Comment by under3415** [comment]
Hi
There's nothing special about my project. I just followed firebase installation instructions:
https://firebase.google.com/docs/crashlytics/get-started?platform=flutter

**Comment by huycozy** [comment]
I just checked this again on my old project that uses Groovy. Flutterfire CLI completes plugin Gradle configuration. When you run `flutterfire configure`, `FlutterFire Configuration` for gradle will be added to your project, see:

- android/app/build.gradle:
```gradle
// START: FlutterFire Configuration
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
// END: FlutterFire Configuration
```

- android/build.gradle:
```gradle
dependencies {
    classpath 'com.android.tools.build:gradle:8.2.0'
    // START: FlutterFire Configuration
    classpath 'com.google.gms:google-services:4.4.0'
    classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
    // END: FlutterFire Configuration
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
}
```

So once we need to do migration, still need to follow the guideline and those lines are not redundant. 

I'm going to close this issue. If you disagree, please write in the comments and I will reopen it.
