### ISSUE TITLE
Add documentation for wasm, dual-compile, and new `FlutterLoader.load` APIs

### ISSUE THREAD

**Issue by eyebrowsoffire** [flutter/website#10126]
For the dart2wasm+skwasm effort, there are a number of thing's I will need to write some documentation on and publish including:
* The `--wasm` flag, and how it produces a dual-compiled application bundle
* Templating of the .html file to inject build configuration in for dual compiled builds
* Use of the `FlutterLoader.load` API which is the new canonical way to load your app
* How to serve your files with `COOP` and `COEP` headers in order to get `crossOriginIsolated` so users can get multi-threaded rendering via skwasm

**Comment by eyebrowsoffire** [comment]
Some stuff is in a draft here: https://github.com/flutter/website/pull/10256

**Comment by felipecastrosales** [comment]
whey, stable version was released yesterday and this looks like confusing. any expectations about it?

**Comment by eyebrowsoffire** [comment]
We added documentation here: https://docs.flutter.dev/platform-integration/web/wasm

And here: https://docs.flutter.dev/platform-integration/web/bootstrapping

Closing this as completed.
