### ISSUE TITLE
[PAGE ISSUE]: 'Choose your development platform to get started'

### ISSUE THREAD

**Issue by y4h2** [flutter/website#10142]
### Page URL

https://docs.flutter.dev/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/index.md

### Describe the problem

There are some weird UI rendering issues on almost all web pages, I saw the same issue on both mac and windows **chrome**. But Safari and  Edge browsers work fine. I am using the latest chrome version (121.0.6167.185).

For example in this page, I can see "chevron_right" which I don't think is expected.
<img width="607" alt="image" src="https://github.com/flutter/website/assets/5662692/d74e37fe-4424-4922-877c-2eb5eb59b7a9">

Also same thing happens on sidebar.
<img width="327" alt="image" src="https://github.com/flutter/website/assets/5662692/19e5db4d-e46f-40d5-afc4-2a8860af72c7">

### Expected fix

Chrome's webpage should be same with Safari and Edge.

### Additional context

I saw the same issue on both mac and windows **chrome**. But Safari and  Edge browsers work fine. 
I am using the latest chrome version (121.0.6167.185).

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by danagbemava-nc** [comment]
Hi @y4h2, if you see that, it likely means that the icon font has not loaded for you yet. Do you see any errors in your console? Are you using any extensions that may be blocking loading the fonts?

**Comment by y4h2** [comment]
@danagbemava-nc Thanks, you're right. Looks like some extensions block the icon font.
I can see this error in console. `GET chrome-extension://mjdbhokoopacimoekfgkcoogikbfgngb/assets/fonts/material-symbols-outlined.woff2 net::ERR_FILE_NOT_FOUND`
It works fine with Chrome incognito mode which doesn't load any extensions.
