### ISSUE TITLE
Flutter install pages 404 Not found

### ISSUE THREAD

**Issue by frankcheng2020** [flutter/website#10160]
### Page URL

https://docs.flutter.dev/release/whats-new

### Describe the problem

Flutter install](https://github.com/get-started/install) pages

404 Not  found.

Just let you know.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment]
Thanks for the report! Closing this as a duplicate of https://github.com/flutter/website/issues/10158. Please follow up on it for further updates.
