### ISSUE TITLE
[PAGE ISSUE]: 'Start building Flutter iOS apps on macOS'

### ISSUE THREAD

**Issue by caoquyenis** [flutter/website#10207]
### Page URL

https://docs.flutter.dev/get-started/install/macos/mobile-ios/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/macos/mobile-ios.md

### Describe the problem

sudo gem install cocoapods
It doesn't work. The system raises issue:
`ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.
`

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment]
>ERROR:  While executing gem ... (Gem::FilePermissionError) You don't have write permissions for the

Could you try [Sudo-less installation](https://guides.cocoapods.org/using/getting-started.html#sudo-less-installation) to see if it works?

**Comment by atsansone** [comment]
This would be a CocoaPods issue. Their support page points to this solution: https://guides.cocoapods.org/using/troubleshooting.html#im-getting-permission-errors-while-running-pod-commands
