### ISSUE TITLE
[PAGE ISSUE]: 'Developing packages 

### ISSUE THREAD

**Issue by dariocavada** [flutter/website#10218]
### Page URL

https://docs.flutter.dev/packages-and-plugins/developing-packages/

### Page source

https://github.com/flutter/website/tree/main/src/packages-and-plugins/developing-packages.md

### Describe the problem

If I type: flutter create --template=package hello
have this error...
The requested template type 'package' doesn't match the existing template type of 'plugin'.

### Expected fix

Shoud create a new plugin ...

### Additional context

Flutter 3.19.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision abb292a07e (8 days ago) • 2024-02-20 14:35:05 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment]
Hi @dariocavada 
I tried the command but didn't see the error:
```console
➜  Desktop flutter create --template=package hello
Creating project hello...
Resolving dependencies in hello... (1.6s)
Got dependencies in hello.
Wrote 13 files.

All done!
Your package code is in hello/lib/hello.dart
```

Could you share the entire console output (include commands and error)?

**Comment by dariocavada** [comment]
Now I upgraded to the latest version of flutter and it works.
Thank you for your time.
