### ISSUE TITLE
Missing value for variable `{{v-target}}` on `Start building Flutter native desktop apps on Windows` page

### ISSUE THREAD

**Issue by sputtering** [flutter/website#10219]
### Page URL

https://docs.flutter.dev/get-started/install/windows/desktop/

### Page source

https://github.com/flutter/website/blob/main/src/_includes/docs/install/flutter-sdk.md

### Describe the problem

- Go to the page https://docs.flutter.dev/get-started/install/windows/desktop/
- Under the section "Install the Flutter SDK" is a subsection "Use VS Code to Install"
- Under that subsection is the section "Download the Flutter SDK"
- The very last line of the section currently says "If you have installed all prerequisites and the Flutter SDK, you should be able to start developing Flutter on Windows for ."
- That sentence comes from the page https://github.com/flutter/website/blob/main/src/_includes/docs/install/flutter-sdk.md
- There is a variable {{v-target}} that isn't being properly replaced

### Expected fix

Other OS pages seem to work properly, For example, I checked MacOS and it says "....developing Flutter on macOS for desktop." as expected. I'm not sure why the Windows version is not working properly.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/10245. Thanks!
