### ISSUE TITLE
"This isn't exactly true" opens a massive question that I'm unsure this page is going to close.

### ISSUE THREAD

**Issue by domesticmouse** [flutter/website#10228]
> "This isn't exactly true" opens a massive question that I'm unsure this page is going to close. I'd vote to eliminate the confusion this early in the process, and leave revealing the whole story until later. The person using this page to learn Flutter has plenty of questions already, and adding a nagging extra doubt of "what's this falsehood about everything is a widget?" to that list

_Originally posted by @domesticmouse in https://github.com/flutter/website/pull/10210#discussion_r1508289051_

**Comment by sfshaza2** [comment]
Pinged @ericwindmill about this.
