### ISSUE TITLE
[PAGE ISSUE]: 'Set up app links for Android'

### ISSUE THREAD

**Issue by lukas-pierce** [flutter/website#10258]
### Page URL

https://docs.flutter.dev/cookbook/navigation/set-up-app-links/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/navigation/set-up-app-links.md

### Describe the problem

Code panel is too narrow, and there no option to resize it

<img width="945" alt="image" src="https://github.com/flutter/website/assets/4938316/ad7f9608-384d-4445-adab-9a35126f9f97">

### Expected fix

Resizable code area

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by atsansone** [comment]
@lukas-pierce : DartPad has resizable sections:

![Image](https://github.com/flutter/website/assets/706219/3a0c1802-bdcd-46b6-b048-b7813121c999)

Hover your cursor over the divider between code and preview, then drag left or right.

Thanks for reaching out!

**Comment by lukas-pierce** [comment]
@atsansone Yes, I have been using Flutter documentation for a long time, and I know about the possibility of resizing. But for some reason he didn’t work that day. But now I double-checked and now it works. I think the problem was an error loading some js-files
