### ISSUE TITLE
Deploying GoogleGKE on skykube.io

### ISSUE THREAD

**Issue by Cirruslucent** [flutter/website#10261]
Deploying GoogleGKE on skykube.io 

_Originally posted by @ghost in https://github.com/Cirruslucent/Skykube.io/issues/1_

**Comment by parlough** [comment]
Thanks for opening an issue!

However, please note this repository is for the [Flutter documentation website](https://docs.flutter.dev/), which is unrelated to Kubernetes or whatever the original issue is discussing.

I'm going to close this, but if you have more information about the issue you're facing that's relevant to Flutter or its documentation, please reply here or open a new issue. Thanks so much!
