### ISSUE TITLE
VS Code links to docs pages that seem to no longer resolve

### ISSUE THREAD

**Issue by mit-mit** [flutter/website#10271]
As part of the getting stated install flow, our VS Code plugins link to instructions in our docs for setting path using Urls like `https://docs.flutter.dev/get-started/install/windows#update-your-path`:
https://github.com/Dart-Code/Dart-Code/blob/master/src/shared/constants.ts#L96

Did these Urls change recently? It looks like they no longer resolve. If so, we should put redirects in place.

**Comment by atsansone** [comment]
Redirects:

- https://docs.flutter.dev/get-started/install/windows/desktop?tab=download#update-your-windows-path-variable
- https://docs.flutter.dev/get-started/install/macos/desktop?tab=download#add-flutter-to-your-path

Linux will change after #10302 merges.

**Comment by mit-mit** [comment]
@atsansone was this resolved?

**Comment by atsansone** [comment]
@mit-mit : I may need to create a hidden page that covers this. I checked with @kenzieschmoll about changing this in future DevTool versions.

**Comment by mit-mit** [comment]
We still need older releases to work though. Can you just add redirects for the old Urls?

**Comment by atsansone** [comment]
Unfortunately, no. The Firebase JSON redirects can't point from URL fragment to URL fragment. (See https://github.com/angular/angular/issues/45861.)

So, this redirect can't be made:
```json
{ "source": "/get-started/install/:platform#update-your-path",
"destination":
/get-started/install/:platform/desktop?tab=download#add-flutter-to-your-path", "type": 301 },
```

This is why I'm thinking about a hidden page. That way I can link to a whole page, rather than a URL fragment.

**Comment by sfshaza2** [comment]
Oh, about the hidden page idea. Would it require documenting how to set the path for ALL platforms and ALL shells? If so, that seems pretty icky

**Comment by sfshaza2** [comment]
Actually, I think aa better solution is to create a "go" link, such as "docs.flutter.dev/go/set-path" and that link can be changed without any issues, I think. Once again, this requires changing the VSCode plugin, as well as the site, but it feels much cleaner than the hidden page.

**Comment by kenzieschmoll** [comment]
CC @DanTup

**Comment by parlough** [comment]
> We still need older releases to work though. Can you just add redirects for the old Urls?

Not in the traditional way with the setup chosen for the new pages. To support the old links, I added a JS based redirector in https://github.com/flutter/website/pull/10115. I accounted for some fragments from the framework, but not all of them. I can update those scripts and add one for Linux to account for more fragments.

> Actually, I think a better solution is to create a "go" link, such as "docs.flutter.dev/go/set-flutter-path" and that link can be changed without any issues, I think. 

For the future, yes please. This is what we do on the Dart site for destinations that pub wants to link to. Since we reserve `/go/...` for design docs on flutter.dev, we should consider a different prefix to standardize on. Any preferences or ideas?

**Comment by DanTup** [comment]
> I think a better solution is to create a "go" link, such as "docs.flutter.dev/go/set-flutter-path" and that link can be changed without any issues

I agree, creating stable URLs not tied to the specific structure of the site would be better. I can update the VS Code extension and push out a patch if new URLs are available.

People tend to update the VS Code extension fairly quick, so old plugins hopefully aren't a bit problem for a long time - however I wonder if we could just put the javascript inside the patch to read the fragment and redirect client-side if a "legacy fragment" is there?

**Comment by DanTup** [comment]
Should I update the links in the VS Code extension too?

If there may be shorter `go/`-style links in future maybe we should wait for them, but otherwise it might be worth updating to the current redirect targets?

**Comment by parlough** [comment]
@DanTup I'd hold off on updating. I'll start some discussion on what path we're going for the `/go/` style links and create some initial ones. I'll post updates to https://github.com/flutter/website/issues/10363 as I have them.

If you have a chance, could you comment on that issue with the various destinations/topics that VS Code currently needs or might need links to?  Thanks :D
