### ISSUE TITLE
Rework the adaptive/responsive apps

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#10304]
### What information needs to be added?

Make them more complete (by covering best practices, design for large screens, accessibility, etc.

### Where should this new content appear?

Under /ui/layout/responsive. Mebbe. It's really more than just layout.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by mariamhas** [comment]
completed this https://github.com/flutter/website/issues/9896
