### ISSUE TITLE
Fix DartPad links on 'Flutter for React Native developers' page

### ISSUE THREAD

**Issue by timborino** [flutter/website#10306]
### Page URL

https://docs.flutter.dev/get-started/flutter-for/react-native-devs/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/flutter-for/react-native-devs.md

### Describe the problem

There are six instances on this page with links to "Try it out in DartPad." All of those links are broken, displaying "Page Not Found - GoException: no routes for location"

### Expected fix

Links should be fixed or removed.

### Additional context

Broken Links
1. https://dartpad.dev/0df636e00f348bdec2bc1c8ebc7daeb1
2. https://dartpad.dev/cf9e652f77636224d3e37d96dcf238e5
3. https://dartpad.dev/3f4625c16e05eec396d6046883739612
4. https://dartpad.dev/57ec21faa8b6fe2326ffd74e9781a2c7
5. https://dartpad.dev/c85038ad677963cb6dc943eb1a0b72e6
6. https://dartpad.dev/5454e8bfadf3000179d19b9bc6be9918

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by RedBrogdon** [comment]
@johnpryan and or @devoncarew, did the /[gist id] route get removed as part of the deploy of the new version? If so, is there a README anywhere that lists how to reconfigure the URL?

**Comment by johnpryan** [comment]
We weren't able to redirect these URLs, so the best practice is to follow the [Embedding guide](https://github.com/dart-lang/dart-pad/wiki/Embedding-guide).

So these links:

```
[DartPadA]: {{site.dartpad}}/0df636e00f348bdec2bc1c8ebc7daeb1
[DartPadB]: {{site.dartpad}}/cf9e652f77636224d3e37d96dcf238e5
[DartPadC]: {{site.dartpad}}/3f4625c16e05eec396d6046883739612
[DartPadD]: {{site.dartpad}}/57ec21faa8b6fe2326ffd74e9781a2c7
[DartPadE]: {{site.dartpad}}/c85038ad677963cb6dc943eb1a0b72e6
[DartPadF]: {{site.dartpad}}/5454e8bfadf3000179d19b9bc6be9918
```

Should be:

```
[DartPadA]: {{site.dartpad}}/?id=0df636e00f348bdec2bc1c8ebc7daeb1
[DartPadB]: {{site.dartpad}}/?id=cf9e652f77636224d3e37d96dcf238e5
[DartPadC]: {{site.dartpad}}/?id=3f4625c16e05eec396d6046883739612
[DartPadD]: {{site.dartpad}}/?id=57ec21faa8b6fe2326ffd74e9781a2c7
[DartPadE]: {{site.dartpad}}/?id=c85038ad677963cb6dc943eb1a0b72e6
[DartPadF]: {{site.dartpad}}/?id=5454e8bfadf3000179d19b9bc6be9918
```

FYI @parlough
