### ISSUE TITLE
Explain necessary headers in Wasm discussion

### ISSUE THREAD

**Issue by kevmoo** [flutter/website#10341]
### Page URL

https://docs.flutter.dev/platform-integration/web/wasm/

### Page source

https://github.com/flutter/website/tree/main/src/platform-integration/web/wasm.md

### Describe the problem

![image](https://github.com/flutter/website/assets/17034/18383edd-c983-4420-8c52-cb497a2a9207)

The headers are REALLY hard to read here. We also don't explain why they are needed or general ways to think about defining them outside of dhttp.

### Expected fix

List both required headers and ideally point to docs explaining why they are needed.

### Additional context

Maybe https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy ?

Need to talk to @eyebrowsoffire 

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by MaryaBelanger** [comment]
An explanation of the headers was added in #10546 in the new "Serve the output with an HTTP server" [section](https://docs.flutter.dev/platform-integration/web/wasm#serve-the-output-with-an-http-server).

Can we close this?

**Comment by kevmoo** [comment]
Yep!
