### ISSUE TITLE
Flutter Discord Link links to "React Native Dev" 

### ISSUE THREAD

**Issue by IchordeDionysos** [flutter/website#10347]
### Page URL

https://flutter.dev/community

### Describe the problem

1. Click on Discord
2. You'd be redirected to this page: https://discord.com/invite/N7Yshp4
![image](https://github.com/flutter/website/assets/10195482/e4237a14-f66a-4bd5-be15-84888ca8c25a)
3. Where it mentions "React Native Dev" which is suuuper confusing :D 

Same happens for this Discord link, which appears from time to time: https://discord.com/invite/rflutterdev

### Expected fix

I should link to the Flutter community Discord?!

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Thanks for the issue, sorry that I laughed a bit when seeing it.

As part of an April Fools (April 1st) joke, the Flutter Discord community did a rebranding to everyone’s other favorite framework.

Perhaps it’s permanent, but we’ll have to wait until tomorrow to see ;)

**Comment by IchordeDionysos** [comment]
I was so fuuuckking confused 😂😂

**Comment by IchordeDionysos** [comment]
The issue is now fixed 🌝
