### ISSUE TITLE
Wasm docs - Update the `Modify index.html` bits for latest beta

### ISSUE THREAD

**Issue by kevmoo** [flutter/website#10356]
### Page URL

https://docs.flutter.dev/platform-integration/web/wasm/

### Page source

https://github.com/flutter/website/tree/main/src/platform-integration/web/wasm.md

### Describe the problem

Replace the bootstrap logic with the latest bits!

### Expected fix

Steal from https://github.com/flutter/website/pull/10256/files#diff-08bd7b888bfd0cced4adcfa76e89f8705eec92fe13d273b51232af7a2afa6dd9R17-R23

```html
<html>
  <body>
    <script src="flutter_bootstrap.js" async></script>
  </body>
<html>
```

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by eyebrowsoffire** [comment]
Yep this looks right. The bigger change I'd actually like to make is to have:
* A separate page for the new bootstrapping logic, with a warning in the documentation that it only works on 3.22 or higher
* Links back and forth between the pages for the old and new bootstrapping logic
* Wasm page should link to the new bootstrapping logic page.

**Comment by sfshaza2** [comment]
Fixed by PR https://github.com/flutter/website/pull/10546.
