### ISSUE TITLE
Search regression: dart:ui classes appear last

### ISSUE THREAD

**Issue by justinmc** [flutter/website#10369]
### Describe the problem

Search for a class in dart:ui, like "Offset". Most users will want the `Offset` class in dart:ui, but it doesn't appear on the first search results.

<img width="400" src="https://github.com/flutter/website/assets/389558/62d879cc-bca1-4959-ba0e-3cb008448583" />

I have to press enter and scroll halfway down the page to find it.

<img width="400" src="https://github.com/flutter/website/assets/389558/34560ea3-707a-47e3-8ca4-0265fd3743a0" />

### Expected fix

Show `Offset` as the first result.

### On which browser(s) did you experience this issue?

Chrome

### Additional context

This used to work, so the reordering of the search results is a regression.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Thanks for the report. It seems some similar cases were recently discussed in https://github.com/dart-lang/dartdoc/issues/3636, so I'll close this in favor of that issue :D
