### ISSUE TITLE
Review use of "devtools" in Getting Started

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#10389]
### Page URL

https://docs.flutter.dev/platform-integration/android/install-android/install-android-from-linux?tab=virtual

### Page source

/src/content/platform-integration/android/install-android/install-android-from-linux.md

### Describe the problem

This issue applies to this page and many other pages. Recently some pages were updated/added that don't use the terms "DevTools" or "web" correctly.

First, it's either Flutter DevTools, Dart DevTools (both refer to the same suite of tools), or Chrome DevTools. So far as I know, none of these DevTools run on any other browsers besides Chrome, so "web DevTools" is incorrect.

Also, check the Google word list. Unless it's the start of a sentence, it's "web", not "Web".

Finally, "devtools" is not a word. We are talking about two specific sets of tooling. We don't want to weaken the meaning of that term by devolving into a generic short word that could apply to any tooling that is developer related.

Also, regarding the pages that are titled as follows: "Add Android devtools for Flutter from Linux start". I don't even know what this title means (nor any of those pages titled similarly). You don't install DevTools, you get it when you download Flutter/Dart. So you launch it or open it. You do install the Flutter/Dart plugins in your IDE, and maybe you meant that but what is "from a Linux start"? (Another experienced Flutter user told me that they don't understand these titles either).

Also, what are "Android devtools"?

cc @kenzieschmoll 

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
There's still cases of this on the site.
