### ISSUE TITLE
Flutter refreshExcerpts util won't work on macOS

### ISSUE THREAD

**Issue by atsansone** [flutter/website#10446]
The code in [refresh_excerpts.dart](https://github.com/flutter/website/blob/main/tool/flutter_site/lib/src/commands/refresh_excerpts.dart#L54-L61) looks for `diff --version` to return a version number starting with `3`. The default `diff` utility on macOS returns the following:

```terminal
$ diff --version
Apple diff (based on FreeBSD diff)
```

This returns no version number at all, so `dart run flutter_site refresh-excerpts` always returns an error on macOS.

```terminal
$ dart run flutter_site refresh-excerpts
Building package executable... 
Built flutter_site:flutter_site.
  Error: diffutils must be installed to refresh code excerpts!
```

**Comment by sfshaza2** [comment]
I guess it depends on your environment. It works for me:

```
$ diff --version
diff (GNU diffutils) 3.10
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Paul Eggert, Mike Haertel, David Hayes,
Richard Stallman, and Len Tower.
```

**Comment by sfshaza2** [comment]
@parlough, gently pinging. :D

**Comment by parlough** [comment]
We rely on features from newer diffutils versions for now. I'll update the command feedback to make that more clear :)

**Comment by atsansone** [comment]
@parlough : This doesn't help anyone who can't get non-Apple diffutils to install and work correctly. That would be an addition to the README at the least. No searches came up with an obvious solution, though it was a simple one (making sure Homebrew came early in your PATH). Maybe we can expand the information in the README and link to it if the `diff` command fails?

**Comment by parlough** [comment]
I'd rather not be too prescriptive about how to install non-Dart/Flutter related CLI tools if it can be avoided. 

Either way, we will no longer require diffutils soon with https://github.com/flutter/website/issues/10384, as it's not a cross-platform solution and requires this extra step. Are you ok with closing this in favor of that issue to avoid soon to be unnecessary work? If contributors raise issues/concerns before that lands, I'm happy to help them as needed.

**Comment by parlough** [comment]
Closing this as I don't plan to spend time to document the best way to install diffutils. With https://github.com/flutter/website/issues/10384 the requirement will be gone soon.

If anyone comes across this issue, you can install a newer version of diffutils with homebrew or at https://ftp.gnu.org/gnu/diffutils/. If you install it manually, you'll need to add it to the end of your `PATH`.

Sorry about the temporary confusion and extra step!
