### ISSUE TITLE
The deploy docs for Android still use the deprecated `Version` suffix for compileSdk / targetSdk / minSdk

### ISSUE THREAD

**Issue by navaronbracke** [flutter/website#10458]
### Page URL

https://docs.flutter.dev/deployment/android#review-the-gradle-build-configuration

### Describe the problem

The `compileSdkVersion` / `minSdkVersion` / `targetSdkVersion` properties have been deprecated and replaced by 
`compileSdk` / `minSdk` / `targetSdk`.

### Expected fix

The documentation should be updated to reflect the new property names, and perhaps include a reference to the old names for people that still need to migrate to the new names.

The `flutter.compileSdkVersion` / `flutter.minSdkVersion` / `flutter.targetSdkVersion` references should remain unchanged, as this is part of the Flutter tool.

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Fixed in https://github.com/flutter/website/pull/10459. Thanks, @navaronbracke!
