### ISSUE TITLE
Clarify which versions should be used in 'Deprecated imperative apply of Flutter's Gradle plugins' page

### ISSUE THREAD

**Issue by escamoteur** [flutter/website#10463]
### Page URL

https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply/

### Page source

https://github.com/flutter/website/tree/main/src/content/release/breaking-changes/flutter-gradle-plugin-apply.md

### Describe the problem

concerning `Google Mobile Services and Crashlytics` it would be helpful to add there a sentence advising to use the versions that are already in the project and not just copy the examples because that let to disaster in my project

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
@parlough, it looks like you created this page. Can you handle this?
