### ISSUE TITLE
The Test drive page in getting started doesn't mention the IDE plugins for Flutter/Dart

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#10465]
### Page URL

https://docs.flutter.dev/get-started/test-drive

### Describe the problem

This was brought to my attention by PR https://github.com/flutter/website/pull/10457. But, I'd like to see this fixed in a more wholistic way. The step of adding/updating/whatever the Dart/Flutter plugins should be mentioned as a separate step in each relevant tab.

Also, there are some other issues I noticed on this page:

- The header "Guide depends on your IDE" is ungrammatical. I suggest removing that header entirely. Then under "Choose your IDE", _that's_ where  you list the 3 tabs. I wouldn't even list them as bolded "options", but as tabs.
- Add the bit about installing the plugins/extensions (already mentioned above)
- The header "Create your sample Flutter app" isn't good. Just "Create **a** sample Flutter app" is better. 
- You write "Enter test_drive into the Project name field. This follows best practices for naming Flutter projects."  What does that mean? Why is `test_drive` a best practice? This only raises questions for me.
- Changing the organization to "example.flutter.test_drive" seems VERY odd to me. It shouldn't be named after the sample app. I'd just delete this for now. Address it elsewhere.
- The last screenshot on the page is confusing and pretty much useless. (Not to mention HUGE.) The second screenshot, if any, should show the count as a non-zero value. Two screenshots with a zero value doesn't really show anything.

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/10466
