### ISSUE TITLE
Flamingo 

### ISSUE THREAD

**Issue by GHAMDANdev** [flutter/website#10493]
install Flamingo  in intellij idea

**Comment by sfshaza2** [comment]
Hi @GHAMDANdev! What are you suggesting, exactly? Flamingo was released in April 2023. We don't generally list Android releases, unless it's really needed. It would help if you could explain the point of your issue.

**Comment by parlough** [comment]
Flamingo is a release of Android Studio, a separate IDE from IntelliJ. You can install it at https://developer.android.com/studio or using [JetBrains Toolbox](https://www.jetbrains.com/toolbox-app/).

However, do note that Android Studio Flamingo is not supported by the latest releases of Flutter or the [Flutter plugin for Android Studio](https://plugins.jetbrains.com/plugin/9212-flutter). If possible, consider using a newer release such as Jellyfish or Iguana. https://docs.flutter.dev/get-started/editor?tab=androidstudio has some more details relevant to Flutter. Let us know if you are having trouble with the Flutter plugin or our docs for it. Thanks!

**Comment by GHAMDANdev** [comment]
Thank you, guys.
