### ISSUE TITLE
A Pen by Naji Mustafa

### ISSUE THREAD

**Issue by Nagikhalid** [flutter/website#10495]
https://codepen.io/najimustafa/full/vYMqxrP

**Comment by sfshaza2** [comment]
Hi @Nagikhalid! Can you explain the point of filing this issue? I don't have a codepen account. Please explain in more detail. I'm not assigning effort or time tags until I understand.

**Comment by Nagikhalid** [comment]
![Screenshot_20240503_040220_Chrome.jpg](https://github.com/flutter/website/assets/154850828/77b4951e-c736-41e9-8cd1-e0648a293ade)

**Comment by Nagikhalid** [comment]
This login page 
Tools Html , CSS
