### ISSUE TITLE
Update wasm page for stable

### ISSUE THREAD

**Issue by kevmoo** [flutter/website#10519]
### Page URL

https://docs.flutter.dev/platform-integration/web/wasm

### Describe the problem

We should update this page to mention that this is now stable

### Expected fix

- [ ]  Mention it's stable.
- [ ] Update details on hosting wasm. Should include the headers we mention in dhttpd – but for any host. Including details for firebase would be good.
- [ ] Explain that some hosters (GitHub) WON'T work because they can't set custom headers. but Firebase DOES!
- [ ] Mention that you NEED to update to the latest bootstrap logic - https://docs.flutter.dev/platform-integration/web/bootstrapping

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
@kevmoo, wasm is now stable?

**Comment by kevmoo** [comment]
It will be very soon 😁
