### ISSUE TITLE
[PAGE ISSUE]: 'Building user interfaces with Flutter'

### ISSUE THREAD

**Issue by ddahoo** [flutter/website#10555]
### Page URL

https://docs.flutter.dev/ui/

### Page source

https://github.com/flutter/website/tree/main/src/content/ui/index.md

### Describe the problem

Previews for examples don't work when attempting to run.

### Additional context

Inspecting the console, it appears that WASM code for dartpad is not being downloaded because a CORS header is missing.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Ack, @parlough, has something changed?

**Comment by parlough** [comment]
Thanks for reporting and investigating the issue!

Should be fixed by https://github.com/dart-lang/dart-pad/pull/2965 after refreshing your cache, but please let us know if you're still seeing issues. Thanks!
