### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by TheAmniel** [flutter/website#10569]
### Page URL

https://flutter.dev/

### Describe the problem

I've been checking but I don't see anything about the website not being available currently, it's been like this for a couple of days. I'm sorry if you don't go here but I couldn't find where else to report this

![Imgur](https://i.imgur.com/r78phrM.png)

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Hi, @TheAmniel! I'm sorry you're having problems. Unfortunately, the site is working ok. It probably has more to do with your environment. Have you tried accessing it from different browsers? Have you tried going directly to our docs site at docs.flutter.dev? Have you tried from another computer? At another residence or a library? We have been working hard on the website recently, and I know it's working, at least here in CA. I'm not an IT person, but can you investigate other approaches to access it?  Closing.
