### ISSUE TITLE
[PAGE ISSUE]: 'Support for WebAssembly (Wasm)' is about 3.22 but current stable is 3.19.6

### ISSUE THREAD

**Issue by gitslav** [flutter/website#10576]
### Page URL

https://docs.flutter.dev/platform-integration/web/wasm/

### Page source

https://github.com/flutter/website/tree/main/src/content/platform-integration/web/wasm.md

### Describe the problem

Currently the wasm documentation shows "Last updated May 14, 2024". This is a date in the future. Also it show release 3.22 as current stable release. Flutter 3.22 is not in stable yet. wasm.md has been released containing wrong information.
<img width="753" alt="Screenshot 2024-05-13 at 15 46 13" src="https://github.com/flutter/website/assets/3044045/91ea3049-5c23-4b32-aa20-b96eeb5f02f4">

### Expected fix

Documentation related to 3.22 should wait until the release.

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
This is close enough, @gitslav. Closing.
