### ISSUE TITLE
[PAGE ISSUE]: 'Delete data on the internet'

### ISSUE THREAD

**Issue by mindeng** [flutter/website#10577]
### Page URL

https://docs.flutter.dev/cookbook/networking/delete-data/

### Page source

https://github.com/flutter/website/tree/main/src/content/cookbook/networking/delete-data.md

### Describe the problem

After clicking the "Delete Data" button, the following error occurs:

![image](https://github.com/flutter/website/assets/921932/d71e010b-d559-46df-9731-5f24af7df163)

This is because the `Album.fromJson` factory method throws an `FormatException` exception while parsing an empty json map.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by johnpryan** [comment]
I created https://github.com/flutter/website/pull/10585 to address this, thanks for filing an issue!
