### ISSUE TITLE
[PAGE ISSUE]: 'Support for WebAssembly (Wasm)'

### ISSUE THREAD

**Issue by MananGandhi1810** [flutter/website#10570]
### Page URL

https://docs.flutter.dev/platform-integration/web/wasm/

### Page source

https://github.com/flutter/website/tree/main/src/content/platform-integration/web/wasm.md

### Describe the problem

The date of last update on this page seems wrong, as I am writing this issue on 11th may 2024, but the article states it was last updated on May 14, 2024, which is not possible (unless the flutter team developed a time machine 🤣)
![image](https://github.com/flutter/website/assets/67302570/01de0335-eda3-4f1b-80d8-31676078e3fb)

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Yeah, but it IS true as OF May 14th.  :). Thanks for pointing this out, but I am going to close this issue.
