### ISSUE TITLE
dexter - Android Code Search

### ISSUE THREAD

**Issue by illuminated-shade** [flutter/website#10587]
https://cs.android.com/android/platform/superproject/main/+/cdf982fb22202920406dd309775a89ca1c14d28a:tools/dexter/;bpv=1

**Comment by parlough** [comment]
Hi! This is the repository for the [Flutter documentation website](https://docs.flutter.dev/).

If you'd like to use the Google code search for Flutter, you can find it at https://cs.opensource.google/flutter and the one for Dart at https://cs.opensource.google/dart.

Let us know if you have any issues or need any help, thanks!
