### ISSUE TITLE
Fix shell command for extracting Flutter binaries in Linux

### ISSUE THREAD

**Issue by HicaroD** [flutter/website#10607]
### Page URL

https://docs.flutter.dev/get-started/install/linux/android?tab=download#download-then-install-flutter

### Describe the problem

In the third instruction, we have the following command for extracting the "zip" archive (it is not a zip archive):

```bash
~/Downloads/flutter_linux_3.22.0-stable.tar.xz /usr/bin/
```

By running it on your command line, it won't work.

### Expected fix

The following command works as expected:

```bash
tar -xf ~/Downloads/flutter_linux_3.22.0-stable.tar.xz -C /usr/bin/
```

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Fixed by https://github.com/flutter/website/pull/10610
