### ISSUE TITLE
[PAGE ISSUE]: 'What's new'

### ISSUE THREAD

**Issue by robert-virkus** [flutter/website#10602]
### Page URL

https://docs.flutter.dev/release/whats-new/

### Page source

https://github.com/flutter/website/tree/main/src/content/release/whats-new.md

### Describe the problem

Wrong links in the 3.22 section: Flutter 3.22 is live! For more information, check out the [Flutter 3.22 umbrella blog post](https://medium.com/flutter/starting-2024-strong-with-flutter-and-dart-cae9845264fe) and the [Flutter 3.22 technical blog post](https://medium.com/flutter/whats-new-in-flutter-3-19-58b1aae242d2).

### Expected fix

Flutter 3.22 is live! For more information, check out the [Flutter 3.22 umbrella blog post](https://medium.com/flutter/io24-5e211f708a37) and the [Flutter 3.22 technical blog post](https://medium.com/flutter/whats-new-in-flutter-3-22-fbde6c164fe3).

### Additional context

Links were made to the Flutter 3.19 posts instead of the new 3.22 posts

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Fixed by https://github.com/flutter/website/pull/10611
