### ISSUE TITLE
[PAGE ISSUE]: 'Start building Flutter iOS apps on macOS' - unzip instructions not functioning

### ISSUE THREAD

**Issue by sethladd** [flutter/website#10614]
### Page URL

https://docs.flutter.dev/get-started/install/macos/mobile-ios/

### Page source

https://github.com/flutter/website/tree/main/src/content/get-started/install/macos/mobile-ios.md

### Describe the problem

I downloaded Flutter's zip, I created a destination directory as instructed, and then I copied the unzip command from the website.

```
sethladd-macbookpro:~ sethladd$ mkdir ~/foo
sethladd-macbookpro:~ sethladd$ unzip ~/Downloads/flutter_macos_arm64_3.22.0-stable.zip ~/foo
Archive:  /Users/sethladd/Downloads/flutter_macos_arm64_3.22.0-stable.zip
caution: filename not matched:  /Users/sethladd/foo
```

Error:

```
caution: filename not matched:  /Users/sethladd/foo
```

Expected: the archive to unzip into destination directory.

### Expected fix

The workaround is this:

```
mkdir ~/foo
cd ~/foo
unzip flutter-version.zip
```

### Additional context

If it helps, this is the version of unzip that I'm using:

```
sethladd-macbookpro:foo sethladd$ unzip --help
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.
```

which AFAIK is whatever is default on my Mac.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by atsansone** [comment]
There is a known error here that a community member has fixed in https://github.com/flutter/website/pull/10610. When I merge that, this should be good to go.

**Comment by atsansone** [comment]
Command fixed in https://github.com/flutter/website/pull/10610.

**Comment by sethladd** [comment]
Thank you!
