### ISSUE TITLE
Embed "Step by step on how to add Flutter to an existing iOS app" into "Integrate a Flutter module into your iOS project" page

### ISSUE THREAD

**Issue by jmagman** [flutter/website#10655]
### What information needs to be added?

"Step by step on how to add Flutter to an existing iOS app" [YouTube tutorial](https://www.youtube.com/watch?v=IIcrfrTshTs) was made as part of https://github.com/flutter/website/issues/7790#issuecomment-2103044641.

Embed it to the top of [Integrate a Flutter module into your iOS project](https://docs.flutter.dev/add-to-app/ios/project-setup).

### Where should this new content appear?

Embedded at the top of https://docs.flutter.dev/add-to-app/ios/project-setup

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by loic-sharma** [comment]
+1. We might want to put that video in [option A's section](https://docs.flutter.dev/add-to-app/ios/project-setup#option-a-embed-with-cocoapods-and-the-flutter-sdk) as the other two options are different from what's described in the video.
