### ISSUE TITLE
[PAGE ISSUE]: 'Internationalizing Flutter apps'

### ISSUE THREAD

**Issue by LabGecko** [flutter/website#10651]
### Page URL

https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization/

### Page source

https://github.com/flutter/website/tree/main/src/content/ui/accessibility-and-internationalization/internationalization.md

### Describe the problem

I don't have time or money to fix all your bugs right now, but this page is rife with them.

### Expected fix

See problem

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Hey @LabGecko, thanks for opening an issue. Sorry to hear you encountered a lot of bugs with the page, however without more specific details it will be hard to resolve them. If you could provide a few examples though, we'd be happy to help. Thanks so much!

**Comment by LabGecko** [comment]
I said I don't have time. Walk through the examples on that and see if they work on your system. Most of them didn't work on mine - AMD Ryzen 7 7735HS with Radeon Graphics 3.20 GHz, 32 GB RAM, Win 11 Pro 64 bit ver 23H2, VSCode IDE with flutter and dart plugins up-to-date, no errors on imports or pubspec.yaml

**Comment by atsansone** [comment]
This duplicates #2280. Closing.
