### ISSUE TITLE
Resolve difference between install and PATH instructions for Linux

### ISSUE THREAD

**Issue by asmrtfm** [flutter/website#10662]
### Page URL

https://docs.flutter.dev/get-started/install/linux/desktop

### Describe the problem

["Download then install flutter - Step 3"](https://docs.flutter.dev/get-started/install/linux/desktop?tab=download#download-then-install-flutter)
> Extract the file into the directory you want to store the Flutter SDK.
> `tar -xf ~/Downloads/flutter_linux_3.22.1-stable.tar.xz -C /usr/bin/`
> When finished, the Flutter SDK should be in the /usr/bin/flutter directory.

The next step:
["Add Flutter to your PATH"](https://docs.flutter.dev/get-started/install/linux/desktop?tab=download#add-flutter-to-your-path)
> To run Flutter commands in a shell, add Flutter to the PATH environment variable.
> ...
> To add Flutter to your PATH, expand the entry for your default shell, then choose the command.
> `echo 'export PATH="$HOME/development/flutter/bin:$PATH"' >> ~/.bash_profile`

### Expected fix

Update the instructions to use the same installation location.

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by AbhayJha24** [comment]
I can fix this problem if no one is assigned to this
