### ISSUE TITLE
[PAGE ISSUE]: Codelabs uses wrong link to plugin codelab

### ISSUE THREAD

**Issue by orestesgaolin** [flutter/website#10664]
### Page URL

https://docs.flutter.dev/codelabs/

### Page source

https://github.com/flutter/website/tree/main/src/content/codelabs/index.md

### Describe the problem

Link to [How to write a Flutter plugin](https://codelabs.developers.google.com/codelabs/write-flutter-plugin) leads to [Using FFI in a Flutter plugin](https://codelabs.developers.google.com/codelabs/flutter-ffigen) and the plugin codelab cannot be find on https://codelabs.developers.google.com/?product=flutter&text=plugin.

### Expected fix

Please provide a codelab on using plugins with Flutter, ideally one that uses both Method and Event channels.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
@domesticmouse, can you comment?

**Comment by domesticmouse** [comment]
If memory serves, that was John's web plugin codelab that was deleted due becoming obsolete. 

The FFI plugin codelab shows event channel integration. I'm unsure what Plugin with method channel is.
