### ISSUE TITLE
Return back data from screens if not popped with Navigator.pop(context) 

### ISSUE THREAD

**Issue by irshad1998** [flutter/website#10671]
### What information needs to be added?

Currently, our Flutter application requires that data be returned from a screen using Navigator.pop(context, result). However, there are scenarios where a screen might not be popped using this method, and we still need to return data. This enhancement request is to enable screens to return data even if they are not popped using Navigator.pop(context).

### Where should this new content appear?

[https://docs.flutter.dev/cookbook/navigation/returning-data](https://docs.flutter.dev/cookbook/navigation/returning-data)

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Thanks for the issue @irshad1998! Are you suggesting a change to the linked cookbook recipe documentation or the Flutter framework itself?

If to the Flutter framework, could you create an issue on the Flutter framework repository (https://github.com/flutter/flutter/issues) and provide some more details? Thanks so much!

**Comment by sfshaza2** [comment]
I just came here to say the same thing as @parlough.  :). This sounds like a s/w feature request, in which case, this issue should be moved to the flutter/flutter repo.

**Comment by irshad1998** [comment]
Thank you @parlough and @sfshaza2  for your guidance. I have created a new issue in the Flutter framework repository as suggested. Here is the link to the new issue: [https://github.com/flutter/flutter/issues/149382](https://github.com/flutter/flutter/issues/149382)
