### ISSUE TITLE
[PAGE ISSUE]: 'Start building Flutter iOS apps on macOS'

### ISSUE THREAD

**Issue by KonradKarimi** [flutter/website#10677]
### Page URL

https://docs.flutter.dev/get-started/install/macos/mobile-ios/

### Page source

https://github.com/flutter/website/tree/main/src/content/get-started/install/macos/mobile-ios.md

### Describe the problem

Command provided in documentation leads to wrong/non-existing file.
> 3. Extract the file into the directory you want to store the Flutter SDK.
```
unzip ~/Downloads/flutter_macos_3.22.1-stable.zip -d ~/development/
```
Flutter artifact is actually named:
```
Flutter 3.22.1 stable.zip
```

### Expected fix

Command should be changed to:
```
unzip ~/Downloads/Flutter\ 3.22.1\ stable.zip -d ~/development/
```

Or artifact should be named as it should be:
```
flutter_macos_3.22.1-stable.zip
```

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by KonradKarimi** [comment]
Added proposition for fix #10679

**Comment by atsansone** [comment]
The artifact is named correctly. Thank you for your submission, but this content is correct as given.

![image](https://github.com/flutter/website/assets/706219/4e0ec031-3990-4da8-8835-cca47597c9fe)

**Comment by KonradKarimi** [comment]
Just checked on other browsers and filename is correct. I'll have to figure out why downloading via Arc browser does that.

![image](https://github.com/flutter/website/assets/29106212/8bca3ad6-a35a-44a1-a703-77cbdf98c2e5)
