### ISSUE TITLE
Explain where "importantState" came from on 'Flutter architectural overview' page

### ISSUE THREAD

**Issue by sethladd** [flutter/website#10683]
### Page URL

https://docs.flutter.dev/resources/architectural-overview/

### Page source

https://github.com/flutter/website/tree/main/src/content/resources/architectural-overview.md

### Describe the problem

Over at https://docs.flutter.dev/resources/architectural-overview#state-management

We see a code snippet, with reference to a `importantState` inside the code snippet.

It's not clear where that importantState came from? For example, is the idea that importantState is an instance variable of the class that contains the build method?

maybe I missed it, but I couldn't find what or where importantState is from. By showing that, it can remove some of the mystery from this section in the docs.

Thanks for considering!

### Expected fix

Idea: show where `importantState` came from.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
From my read, "importantState" is a placeholder name. From the example that follows, I think that `StudentState` IS the important state. @domesticmouse @craiglabenz @parlough , can you confirm? If that is correct, then "importantState" should be italicized and given a brief description.

**Comment by domesticmouse** [comment]
This code sample needs more context. 

This is referring to an effect known as [prop drilling](https://www.freecodecamp.org/news/prop-drilling-in-react-explained-with-examples/) in the react community.

**Comment by sfshaza2** [comment]
@domesticmouse, OK, I read through prop drilling and I think I get it. However, that implies that "importantState" IS a property that is being passed down from some ancestor class. Right? However, if you search the Flutter API docs, `importantState` is nowhere to be found, which is why I assumed it was a placeholder.

**Comment by domesticmouse** [comment]
Yup, it's a placeholder
