### ISSUE TITLE
headerBuilder - please add a note that this widget is only shown on narrow screens.

### ISSUE THREAD

**Issue by newskylabs** [flutter/website#10691]
### Page URL

https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#4

### Describe the problem

Hi,

When testing on a wide screen the headerBuilder widget is not displayed.  Therefore the reader very probably will spend some time to debug the code in order to find the "bug" - which will be in vain as it is not a bug at all:  the headerBuilder widget is only shown on narrow screens...

The sideBuilder widget has the opposite behaviour:  it is only shown on wide screens.  However, in the 'Side Builder' paragraph the following can be read: "The widget that sideBuilder returns will be displayed to the left of the sign in form, and only on wide screens."  So the reader will expect to not see the widget on small screens.

A similar not in the "headerBuilder" paragraph would be very helpful.

### Expected fix

Change the text: "Using the SignInScreen.headerBuilder argument, you can add whatever widgets you want above the sign-in form."

to something like: "Using the SignInScreen.headerBuilder argument, you can add whatever widgets you want above the sign-in form. It will be shown, however, only on narrow screens.  On wide screens you can use a sideBuilder widget (see later on this page) which will be displayed only on wide screens to the left of the sign in form."

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
A very valid point, @newskylabs. However, can you open this issue against the Firebase docs? That's a different team, a different set of docs, and a different process.  thx

**Comment by parlough** [comment]
@sfshaza2 I'll reopen this as the codelab links to here for "Report a mistake" and it's maintained by Eric, covering Flutter too.

**Comment by sfshaza2** [comment]
@parlough, Eric no longer supports Firebase.

**Comment by newskylabs** [comment]
Thank you, @sfshaza2 and  @parlough :)

As you said, I just followed the "Report a mistake" link and added the issue.  Maybe the link should be redirected as well?

@sfshaza2: ... can you open this issue against the Firebase docs? That's a different team, a different set of docs, and a different process. thx

I reposted the issue on the Firebase docs issue tracker:

  headerBuilder - please add a note that this widget is only shown on narrow screens. 29:
  https://github.com/firebase/firebase-docs/issues/29

@parlough: Eric no longer supports Firebase.

I also asked to correct the "Report a mistake" link:

  The "Report a mistake" link points to the flutter website issues tracker - but should point to firebase-docs issue tracer 30:
  https://github.com/firebase/firebase-docs/issues/30

Thanks for your comments, 
best wishes...

**Comment by parlough** [comment]
@domesticmouse @ericwindmill Can you clarify the status of this codelab? Is it still maintained? If so, should we manage issues on this repository or not? It currently links to this issue tracker.

**Comment by ericwindmill** [comment]
I can fix this. As much as I love deleting things, this is still a popular codelab :)

**Comment by ericwindmill** [comment]
Fixed by CL #640158830
