### ISSUE TITLE
Update required packages on 'Start building Flutter Android apps on Linux' page

### ISSUE THREAD

**Issue by diegum** [flutter/website#10696]
### Page URL

https://docs.flutter.dev/get-started/install/linux/android/

### Page source

https://github.com/flutter/website/tree/main/src/content/get-started/install/linux/android.md

### Describe the problem

In section "Development Tools", the third step request some packages that, at least on Ubuntu 24.10 LTS, aren't available as such. These are:

* libc6:i386
* libncurses5:i386
* libstdc++6:i386
* lib32z1
* libbz2-1.0:i386

In some cases, removing the `:i386` or even replacing it with `:amd64` unlocked it. But I don't know if that's the proper dependency. In the case of `libncurses5`, my OS actually has `libncurses6` (again, I don't know if that would work.)

It seems like this page is falling behind.

### Expected fix

I propose to list alternatives to the packages (namely, `libncurses5` or later) where appropriate.

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
@domesticmouse, do you know what is current? Or do you know who would know?

**Comment by atsansone** [comment]
Awaiting validation from the Android Studio team.
