### ISSUE TITLE
iOS add-to-app instructions are missing caveat that static `FlutterPluginRegistrant` should be linked against, but not embedded

### ISSUE THREAD

**Issue by jmagman** [flutter/website#10707]
During iOS add-to-app the static `FlutterPluginRegistrant.xcframework` should be linked against, but not embedded, or it app will have archive/App Store validation failures.  We just received a report from a customer that they were getting App Store submission errors due to this problem.

I added this warning in https://github.com/flutter/website/pull/3544, but it since looks like it was removed.  

> For example, you can drag the frameworks (except for FlutterPluginRegistrant and any other static frameworks) from your application's Frameworks group into your targets' build settings > Build Phases > Embed Frameworks. Then, select "Embed & Sign" from the drop-down list.

The `FlutterPluginRegistrant` should be specifically called out in https://docs.flutter.dev/add-to-app/ios/project-setup#embed-the-frameworks.

**Comment by jmagman** [comment]
cc @atsansone who is editing these instructions now.

**Comment by atsansone** [comment]
Adding this to PR #10699

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/10699
