### ISSUE TITLE
Title was removed and the new link 404s.  Added comments.

### ISSUE THREAD

**Issue by ehsanalizade** [flutter/website#10705]
Title was removed and the new link 404s.  Added comments.

_Originally posted by @jmeridth in https://github.com/github/opensource.guide/pull/3231#pullrequestreview-2096344331_

**Comment by jmeridth** [comment]
I'm not sure how this relates.  Pretty sure this is spam.  Sorry folks.  Reported.

**Comment by parlough** [comment]
Thanks for opening an issue, however as jmeridth said, this doesn't relate to this repository which hosts the [documentation website for the Flutter framework](https://docs.flutter.dev/).

I'm going to close this, but if you are experiencing an issue with our site or Flutter, please respond here or open a new issue. Thanks!
