### ISSUE TITLE
[PAGE ISSUE]: 'Start building Flutter native desktop apps on macOS'

### ISSUE THREAD

**Issue by Megatronicus** [flutter/website#10719]
### Page URL

https://docs.flutter.dev/get-started/install/macos/desktop/

### Page source

https://github.com/flutter/website/tree/main/src/content/get-started/install/macos/desktop.md

### Describe the problem

On windows Android Studio I have Dart SDK version 3.5.0.-226.0.dev however on macbook air m1 I cant seem to upgrade to version newer than 3.4.3

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by anderdobo** [comment]
Could you confirm what channels you're on, on each OS? Share the outputs of `flutter --version` and `flutter doctor` on each OS.

**Comment by Megatronicus** [comment]
On Windows I have this version 
Flutter 3.23.0-13.0.pre.168 • channel master • https://github.com/flutter/flutter.git
Framework • revision 32081aab69 (3 days ago) • 2024-06-08 10:35:21 -0700
Engine • revision 1cdbebee19
Tools • Dart 3.5.0 (build 3.5.0-236.0.dev) • DevTools 2.36.0

Flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.23.0-13.0.pre.168, on Microsoft Windows [Version 10.0.19045.4412], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.3)
[√] Android Studio (version 2024.1)
[√] VS Code (version 1.89.1)
[√] Connected device (3 available)
[√] Network resources


On Macbook Air M1 I have this version 

Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (6 days ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

Flutter doctor 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by anderdobo** [comment]
@Megatronicus you would need to switch to `channel master` on your Macbook. The latest version available in `channel stable` is Dart 3.4.3 atm
