### ISSUE TITLE
[PAGE ISSUE]: 'Choose your development platform to get started'

### ISSUE THREAD

**Issue by kickra** [flutter/website#10712]
### Page URL

https://docs.flutter.dev/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/content/get-started/install/index.md

### Describe the problem

unable to download flutter

### Expected fix

link to download flutter

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Hi, @kickra! This could be very serious. Can you give me more information? Is it still happening? What platform are you on? What happens when you try to download? Do you get an error of some kind? What is the behavior?

**Comment by sfshaza2** [comment]
I suspect this is a user-error or a problem with his environment. Please re-open if you can share more info.
