### ISSUE TITLE
Fix alignment on Dart snippets on first lines of "Flutter for SwiftUI Developers" page

### ISSUE THREAD

**Issue by jmagman** [flutter/website#10725]
### Page URL

https://docs.flutter.dev/get-started/flutter-for/swiftui-devs

### Describe the problem

Some of the dart snippets have incorrect whitespace on the first lines:

<img width="364" alt="Screenshot 2024-06-07 at 12 07 40 PM" src="https://github.com/flutter/website/assets/682784/327a2092-a31b-4b54-82c9-373f1aaac5b9">
<img width="457" alt="Screenshot 2024-06-07 at 12 07 36 PM" src="https://github.com/flutter/website/assets/682784/a807fa09-1241-4f78-a312-a1458531d9c2">

### Expected fix

Indentation should be formatted.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sagarhedaoo** [comment]
Hi! Can I try fixing this?

**Comment by atsansone** [comment]
@sagarhedaoo : Sure! Make sure to check the Dart files referenced in this page, too.
