### ISSUE TITLE
Update dependent library requirements on 'Start building Flutter Android apps on Linux' page

### ISSUE THREAD

**Issue by jdobbin-hsahealthplan** [flutter/website#10729]
### Page URL

https://docs.flutter.dev/get-started/install/linux/android/

### Page source

https://github.com/flutter/website/tree/main/src/content/get-started/install/linux/android.md

### Describe the problem

On Development Tools instrucions, step 3, substep 1, the `i386` version of some packages need to be installed. On some versions of Ubuntu it's required to enable multi-architecture for those packages to be available.

Here's the command: 
```
sudo dpkg --add-architecture i386
sudo apt update
```

### Expected fix

Change the documentation to include something like 

If your Ubuntu distribution can't find these packages, you might need to enable multi-architecture support using these commands
```
sudo dpkg --add-architecture i386
sudo apt update
```

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by atsansone** [comment]
Relates to #10696
