### ISSUE TITLE
UI issue at https://docs.flutter.dev/ui/widgets/scrolling

### ISSUE THREAD

**Issue by rajukani100** [flutter/website#10727]
### Describe the problem

1) Title and Image icon are overlapping.
2)  Title is not properly visible due to use of same type color
![edit](https://github.com/flutter/website/assets/140141712/f509b3eb-22b8-4771-875e-dc6a72c83b7b)

### Expected fix

Edit the image and choose colors accordingly.

### On which browser(s) did you experience this issue?

Firefox, Chrome, Microsoft Edge, Other

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
ok, @rajukani100, go ahead!
