### ISSUE TITLE
Reinsert Command, Control key on Get Started/Test Drive pages

### ISSUE THREAD

**Issue by kimtaejin3** [flutter/website#10720]
### Page URL

https://docs.flutter.dev/get-started/test-drive?tab=vscode

### Page source

https://github.com/flutter/website/blob/main/src/_includes/docs/install/test-drive/vscode.md

### Describe the problem

<img width="483" alt="image" src="https://github.com/flutter/website/assets/60560836/93fbb385-700d-4c79-a550-f560da19a4cb">

  
As you can see, the Command (Mac) / Control (Other platforms) key is omitted in the Create a sample Flutter app section.
  

<img width="483" alt="image" src="https://github.com/flutter/website/assets/60560836/e3a5c100-6d09-40d9-819c-4d7221ec710a">

  
  
It is also omitted in the Run your sample Flutter app section.
  

### mac
<img width="483" alt="image" src="https://github.com/flutter/website/assets/60560836/af45763c-c4f3-4b2e-bfce-29186fc8a3a2">

### Other platforms
<img width="483" alt="image" src="https://github.com/flutter/website/assets/60560836/dee91c9b-c310-46fc-b3d4-1703eb881e0b">

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Fixed by https://github.com/flutter/website/pull/10721. Thanks, @kimtaejin3!
