### ISSUE TITLE
[PAGE ISSUE]: 'Continuous delivery with Flutter' has weird images

### ISSUE THREAD

**Issue by filiph** [flutter/website#10736]
### Page URL

https://docs.flutter.dev/deployment/cd/

### Page source

https://github.com/flutter/website/tree/main/src/content/deployment/cd.md

### Describe the problem

I see this next to individual steps:

![Screenshot 2024-06-11 at 13 53 35](https://github.com/flutter/website/assets/919717/a8e0c7b2-bee3-4622-9ac2-af984e3b2080)

Maybe it's just a CSS error that makes some small icon huge?

### Expected fix

Images / icons are either scaled to their original size or removed.

### Additional context

I see this on Firefox and Chrome, macOS.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Fixed by https://github.com/flutter/website/commit/70c3a3800e7dc714f2d2883d1d11813f73ae56fe
