### ISSUE TITLE
DartPad autorun generates an incorrect UI on 'Building user interfaces with Flutter' page

### ISSUE THREAD

**Issue by syedaniq** [flutter/website#10740]
### Page URL

https://docs.flutter.dev/ui/

### Page source

https://github.com/flutter/website/tree/main/src/content/ui/index.md

### Describe the problem

When visiting this page, the code runner output window displays a "hello $i" loop printing 10 times, even though the code on the left side is a centered text widget. However, when the "Run" button is pressed, the correct output is displayed.

<img width="927" alt="image" src="https://github.com/flutter/website/assets/105786499/7d064d52-55e3-4bda-805c-97b1d39f33f7">

### Expected fix

Output window should be empty like the other ones below.

### Additional context

I'm on macOS 14.5, this behavior occured in Firefox and Microsoft Edge.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by johnpryan** [comment]
This is an issue with the auto-run feature (https://github.com/dart-lang/dart-pad/issues/2985). It works if you press "Run" again.

**Comment by sfshaza2** [comment]
For me, there IS no run button. @RedBrogdon says: "That's fascinating. It only affects the frame that's onscreen when loaded. There must be some kind of race going on with firing off the compilation request and injecting the code into the editor."

@parlough, can you look into this?

**Comment by johnpryan** [comment]
> For me, there IS no run button.

That's... concerning. Could you post a screenshot?

**Comment by sfshaza2** [comment]
@johnpryan, I thought I posted a screenshot. But here it is:
<img width="848" alt="Screenshot 2024-06-12 at 11 00 15 AM" src="https://github.com/flutter/website/assets/44418985/9f6699b9-b939-4de7-9e6b-7a24e7ee9559">

**Comment by johnpryan** [comment]
Ah, thanks. The Run button will only show when you select the "Code" tab. Filed an issue to track: https://github.com/dart-lang/dart-pad/issues/2998
