### ISSUE TITLE
[flutter web] document multi-view

### ISSUE THREAD

**Issue by kevmoo** [flutter/website#10773]
### Page URL

https://docs.flutter.dev/deployment/web/

### Page source

https://github.com/flutter/website/tree/main/src/content/deployment/web.md

### Describe the problem

Per this (now closed) issue https://github.com/flutter/flutter/issues/118481

Flutter web supports multi-view. Need to document it.

### Expected fix

Document how to embed multiple Flutter web views on one page

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by yjbanov** [comment]
I think when documenting this feature we should not refer to it as "multi-view". The feature is more like "embedding Flutter apps and widgets into HTML pages" (or maybe into "other web frameworks"). When all is said and done this feature will look so obvious that we'll be musing how in early days we "didn't even support multiple views" (then cheer 🍻  for good old days). So instead, we should just update whatever "embedding" docs we already have to talk about CRUD-ing views and placing them onto web pages.

**Comment by sfshaza2** [comment]
Are you planning to add this documentation, @ditman?

**Comment by ditman** [comment]
@sfshaza2 Yes!

**Comment by ditman** [comment]
Posted the PR for this: https://github.com/flutter/website/pull/10977
