### ISSUE TITLE
Fix `ci_post_clone.sh` example on CI deployment page

### ISSUE THREAD

**Issue by lukehutch** [flutter/website#10807]
### Page URL

https://docs.flutter.dev/deployment/cd

### Describe the problem

`$(FLUTTER_BUILD_NAME)` in `Info.plist` not being expanded

I added `ci_post_clone.sh` (the script by @Diizzayy) to my Flutter project, and set up the Xcode cloud deployment workflow as shown in the Flutter docs at the above URL.

I get the following CI build errors:

* Error: This bundle is invalid. The value for key CFBundleShortVersionString '$(FLUTTER_BUILD_NAME)' in the Info.plist file at 'Payload/Runner.app/Frameworks/App.framework' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring
* Error: This bundle is invalid. The value for key CFBundleVersion [$(FLUTTER_BUILD_NUMBER)] in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion
* Error: This bundle Payload/Runner.app/Frameworks/App.framework is invalid. The value for key CFBundleVersion [$(FLUTTER_BUILD_NUMBER)] in the Info.plist file must be no longer than 18 characters. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion

However `flutter run` works locally. So there seems to be some step missing from the `ci_post_clone.sh` script (something that is run by `flutter run` but not by the script, to replace these variables with the actual correct values before the Xcode Cloud build is started).

After a local run of `flutter run`, my `Generated.xcconfig` (which is not checked into git) does include the following (these numbers are correctly picked up from `pubspec.yaml` when I run `flutter run`):

```
FLUTTER_BUILD_NAME=0.0.1
FLUTTER_BUILD_NUMBER=378
```

`Runner/Info.plist` and `Flutter/AppFrameworkInfo.plist` both contain:

```xml
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
```

My `Runner.xcodeproj/project.pbxproj` file contains the following for each target:

```
				MARKETING_VERSION = "$(FLUTTER_BUILD_NAME)";
				CURRENT_PROJECT_VERSION = "$(FLUTTER_BUILD_NUMBER)";
```

@jmagman asked me in #7259 to file this separate bug report, and include:

* Q: when you `flutter run` locally can you see the right values in the app's Info.plist?
  A: No, `Info.plist` doesn't change.

* Q: are you using flavors?
  A: I don't even know what flavors are, so probably no.

```
[✓] Flutter (Channel beta, 3.23.0-0.1.pre, on Fedora Linux 40 (Workstation Edition) 6.8.10-300.fc40.x86_64, locale en_US.utf8)
    • Flutter version 3.23.0-0.1.pre on channel beta at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2feea7a407 (3 weeks ago), 2024-06-06 10:19:10 +0700
    • Engine revision bb10c54666
    • Dart version 3.5.0 (build 3.5.0-180.3.beta)
    • DevTools version 2.36.0
```

### Expected fix

As far as I can tell, Xcode Cloud is simply not generating `Generated.xcconfig`, so maybe it is not calling `flutter build`, but rather is relying only on Xcode to build the ipa?

I tried adding this to the end of `ci_post_clone.sh`, but it does not seem to have fixed the problem:

```
flutter build ios --release --no-codesign
```

**Comment by lukehutch** [comment]
I tried adding this to the end of `ci_post_clone.sh`, but it does not seem to have fixed the problem:

flutter build ios --release --no-codesign

**Comment by jmagman** [comment]
> No, Info.plist doesn't change.

I meant, is `CFBundleShortVersionString` in the generated app literally `$(FLUTTER_BUILD_NAME)` (incorrect) or is it `0.0.1` (correct)?  If it's the FLUTTER_BUILD_NAME variable name, this error has to do with your Xcode setup and xcconfig, and wouldn't be related to the Xcode Cloud setup--it's something you should fix in your project.

**Comment by lukehutch** [comment]
I found the issue: I had assumed that both `Runner/Info.plist` and `Flutter/AppFrameworkInfo.plist` should contain:

```
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
```

However I noticed that when I create a new Flutter project, `Flutter/AppFrameworkInfo.plist` has the value `1.0` in place of both of these variables. I put the `1.0` values back, and now Xcode Cloud can build the app.

I don't understand what these `1.0` values in `Flutter/AppFrameworkInfo.plist` are used for though -- are they just placeholders, given that they are not updated based on the Flutter build version strings? They have to be present, or the build fails, but they are not updated automatically from the Flutter build number, and apparently the `FLUTTER_*` variables are not expanded in `AppFrameworkInfo.plist`.

Should Flutter be manually keeping these version numbers up to date in `AppFrameworkInfo.plist`? Obviously it doesn't make sense to do it manually. Are these version numbers even used anywhere?

**Comment by sfshaza2** [comment]
@jmagman, on a careful reading of this issue, I'm not completely sure what's needed to change in the docs. Perhaps we should mention to leave the values in `Flutter/AppFrameworkInfo.plist` alone? Not to change them?

**Comment by lukehutch** [comment]
I now have a better understanding of what is going on. The values `$(FLUTTER_BUILD_NAME)` and `$(FLUTTER_BUILD_NUMBER)` are only defined if you add to your deployment config files ('Debug.xcconfig`, `Profile.xcconfig`, and `Release.xcconfig`) the directive `#include "Generated.xcconfig"` (this is the file where Flutter places the definition of these variables). Then you have to make sure your project uses these profiles, in `Project > Runner > Info > Configurations`.

(If you have any extensions, they also need to have their own `xcconfig` files that include a directive like `#include "../Flutter/Generated.xcconfig"`.)

I also had to go through my `Runner.xcodeproj/project.pbxproj` file and ensure that every mention of `CURRENT_PROJECT_VERSION` was defined as `CURRENT_PROJECT_VERSION = "$(FLUTTER_BUILD_NUMBER)";`, and every mention of `MARKETING_VERSION` was defined as `MARKETING_VERSION = "$(FLUTTER_BUILD_NAME)";`.

With these changes, everything builds fine, and the version numbers are correctly defined everywhere, based on the `pubspec.yaml` versions.

Why Flutter doesn't automatically set all this up correctly is beyond me. This is basic stuff that is fundamental to the app building successfully.

**Comment by jmagman** [comment]
> I don't understand what these `1.0` values in `Flutter/AppFrameworkInfo.plist` are used for though -- are they just placeholders, given that they are not updated based on the Flutter build version strings

Essentially.  This is the plist that's used for the generated framework that contains your compiled dart app code. You should never need to change that.  It's kind of confusing that we expose that in the Xcode project, but it's so you can set `FLTAssetsPath` to a different asset path than the default (a very niche use-case).

> Why Flutter doesn't automatically set all this up correctly is beyond me.

Going off your list, these are all set up correctly by default, and as you said `flutter run` works?  I'm not sure what happened to your project.  You can run `flutter create` and see:

> if you add to your deployment config files (`Flutter/Debug.xcconfig`, `Flutter/Profile.xcconfig`, and `Flutter/Release.xcconfig`) the directive `#include "Generated.xcconfig"`

The `#include` is done for you:
https://github.com/flutter/flutter/blob/46cb56d313c07eba302da375ff0d9cacb043a0ea/packages/flutter_tools/templates/app_shared/ios.tmpl/Flutter/Debug.xcconfig
https://github.com/flutter/flutter/blob/46cb56d313c07eba302da375ff0d9cacb043a0ea/packages/flutter_tools/templates/app_shared/ios.tmpl/Flutter/Release.xcconfig

> Then you have to make sure your project uses the build configurations that include this directive

Debug.xcconfig and Release.xcconfig are generated, contain the include, and are hooked up for you in the build configuration:
<img width="493" alt="Screenshot 2024-07-17 at 9 55 16 AM" src="https://github.com/user-attachments/assets/c0c8b9a6-358b-43ae-b23a-5db816fbb24d">


> (If you have any extensions in their own directories alongside the `Flutter` and `Runner` directories, such as a notification service extension, then they also need to have their own `xcconfig` files that include a directive like `#include "../Flutter/Generated.xcconfig"`.)

This is trickier and requires manual configuration.  We have [documentation with instructions](https://docs.flutter.dev/platform-integration/ios/app-extensions#creating-app-extension-uis-with-flutter) for how to do this though:
<img width="927" alt="Screenshot 2024-07-17 at 9 57 25 AM" src="https://github.com/user-attachments/assets/02e64f84-f3cf-454b-b049-a9769290240c">




> I also had to go through my `Runner.xcodeproj/project.pbxproj` file and ensure that every mention of `CURRENT_PROJECT_VERSION` was defined as `CURRENT_PROJECT_VERSION = "$(FLUTTER_BUILD_NUMBER)";`, and every mention of `MARKETING_VERSION` was defined as `MARKETING_VERSION = "$(FLUTTER_BUILD_NAME)";`

This is also done for you (for the app target, it's unnecessary for the test targets):
https://github.com/flutter/flutter/blob/46cb56d313c07eba302da375ff0d9cacb043a0ea/packages/flutter_tools/templates/app_shared/ios-objc.tmpl/Runner.xcodeproj/project.pbxproj.tmpl#L567
For some reason we have `MARKETING_VERSION` set for the test targets, we should remove that... but it shouldn't impact your ability to deploy.

I think I'm going to close this, this sounds like something specific you changed about your Xcode project.  Please let us know if there are improvements that can be made to the generated Xcode project or documentation based on a default `flutter create`d project.  Thanks!
