### ISSUE TITLE
Update supported platforms page for Q3 release

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#10812]
### Page URL

https://docs.flutter.dev/reference/supported-platforms

### Describe the problem

As it says
See: https://github.com/orgs/flutter/projects/82/views/3?pane=issue&itemId=28843275
and: https://github.com/orgs/flutter/projects/82/views/3?pane=issue&itemId=65859466

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
@yjbanov Are the minimum browser versions on https://docs.flutter.dev/reference/supported-platforms still correct for the upcoming stable release? Or should any be adjusted?
