### ISSUE TITLE
Update M3 demo on Material page

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#10813]
### Page URL

https://docs.flutter.dev/ui/design/material

### Describe the problem

@QuncCccccc will be updating the M3 demo for the Q3 release. Make sure that the page is up to date once it's ready. @QuncCccccc, please let us know when it's ready!

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Spoke to @QuncCccccc. This demo relies on the features being in a stable release, so this update will occur right after the stable Q3 release.

**Comment by QuncCccccc** [comment]
> This demo relies on the features being in a stable release, so this update will occur right after the stable Q3 release.

Created a PR to include the ["uncontained" Carousel](https://m3.material.io/components/carousel/specs#477de3a1-c9df-4742-baf3-bcd5eeb3764c) update: https://github.com/flutter/samples/pull/2377

**Comment by sfshaza2** [comment]
@QuncCccccc's PR has landed. Closing as fixed.
