### ISSUE TITLE
Regression: Slash no longer works to focus the search field

### ISSUE THREAD

**Issue by justinmc** [flutter/website#10826]
### Describe the problem

Go to any docs page on [https://api.flutter.dev/](https://api.flutter.dev/). Press slash on the keyboard. The search field will be focused.

This no longer works on https://main-api.flutter.dev/.

### Expected fix

Pressing slash should focus the search bar. I love this feature and use it all the time! Originally added in https://github.com/flutter/website/issues/8996.

### On which browser(s) did you experience this issue?

Chrome

### Additional context

I'm on Mac.

FYI @parlough 

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
@justinmc, THANK YOU for teaching me this GREAT short cut! Yes, it doesn't work for me on flutter.dev OR main-api.flutter.dev. I will let marketing know (as they own this site).

**Comment by sfshaza2** [comment]
I've let marketing know. I guess we leave this open for now, as they don't have a separate bug tracker.

**Comment by parlough** [comment]
@sfshaza2 This issue is actually for the API docs, not marketing website.

I'll investigate and fix this, so I'll track this here for now.

**Comment by sfshaza2** [comment]
It doesn't work for the marketing site, either.

**Comment by justinmc** [comment]
Thanks everyone!
