### ISSUE TITLE
Fix command location for 'Start building Flutter Android apps on Windows'

### ISSUE THREAD

**Issue by AMDphreak** [flutter/website#10841]
### Page URL

https://docs.flutter.dev/get-started/install/windows/mobile/

### Page source

https://github.com/flutter/website/tree/main/src/content/get-started/install/windows/mobile.md

### Describe the problem

https://docs.flutter.dev/get-started/install/windows/mobile#configure-the-android-toolchain-in-android-studio
Under "Configure Android Toolchain in Android Studio" section, in the instructions for "Current Android Studio User" the instructions are wrong: it says to go to **Tools > SDK Manager**. This settings page does not exist in Tools. In fact it does not exist at all. Please keep this stuff updated haha. OMG it gets old having to constantly correct documentation other people wrote.

Android Studio Koala | 2024.1.1
Build #AI-241.15989.150.2411.11948838, built on June 10, 2024

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by atsansone** [comment]
The command exists in the location specified both for Windows and macOS.

![image](https://github.com/flutter/website/assets/706219/dfad3fd6-a692-4f7d-b2bf-6e2549e6547d)

**Comment by atsansone** [comment]
Thank you for raising this issue. Can confirm that the command is correct in the documentation as shown in the comments for existing projects. Closing this issue.
