### ISSUE TITLE
Add IDX and a mention of Discord under "how to get involved" in FAQ page

### ISSUE THREAD

**Issue by sethladd** [flutter/website#10862]
### Page URL

https://docs.flutter.dev/resources/faq

### Describe the problem

We seem to be missing two small things in our FAQ:

* A link to Discord under "How do I get involved?"

* A mention and link to IDX from "Does Flutter work with any editors or IDEs?"

* We also might want to mention DartPad from "Does Flutter work with any editors or IDEs?"

### Expected fix

A quick mention and context of Discord in "how to get started", and a quick mention and context of IDX and DartPad in the editors/IDEs faq should be sufficient.

Thank you!

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by atsansone** [comment]
@sethladd : Would this issue replace https://github.com/flutter/website/issues/9215?
