### ISSUE TITLE
Add a job opening for China Devrel 

### ISSUE THREAD

**Issue by zoeyfan** [flutter/website#10866]
### Page URL

https://docs.flutter.dev/jobs/

### Page source

https://github.com/flutter/website/tree/main/src/content/jobs/index.md

### Describe the problem

Our current China devrel's contract is expiring, and I am looking for a new vendor/supplier to fill in this role. Can I post a job posting?

### Expected fix

Here is the job description: 

Job Title: Flutter Developer Relations Engineer - China (Contractor) 
Location: Mainland China

**Responsibilities:**

Managing relationships with large Chinese customers
- Actively manage relationships with existing P1 Chinese customers to understand their needs, provide technical support, escalate top issues to the Flutter eng team, deliver technical presentations, and enhance Flutter usage within these companies.
- Develop new Chinese Flutter customers who hold strategic importance to Google. 

Bridging between Chinese contributors and the Flutter eng team
- Act as a zeroth customer, help Flutter team understand how large Chinese customers are using Flutter, and if new features are meeting their needs. 
- Help Flutter be more accessible for Chinese customers (e.g. understand  customer pain points in contributing to Flutter repo, identify the ideal communication channel, tooling and platforms for Chinese customers to engage with Flutter eng team.)
- Mentor Chinese contributors (especially large enterprise customers) to submit quality PRs to the Flutter repo. 
- Review PRs, provide feedback, and sponsor contribution access to quality PR contributors.   

Community support
- Deliver Flutter presentation at technical events in China (E.g, Google Developer Summit). 
- Coordinate with Flutter DevRel and marketing in launching Flutter-related events in China.
- Overview the localization process of Flutter learning content, sample projects, video tutorials for Chinese-speaking developers, etc
- Support and grow China GDEs. 

Minimum qualifications
- 3 years of software engineering experience, including at least 1-year experience coding in Flutter and Dart.
- Experience with the Android and iOS platform and ecosystem.

Language requirements:
- Chinese verbal and written communication: Native level
- English written communication: Advanced level
- English verbal communication: Medium level

Preferred qualifications
- Experience working with, and contributing to open-source software repo. 
- Experience working in a support or consulting relationship with customers.
- Experience delivering public speech, writing blogs and articles, or interacting with developer communities.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
I have a PR ready to go, but need the info on how they might apply. Waiting for that info.
