### ISSUE TITLE
Clarify that an Apple Developer account is not required

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#10879]
The [Make iOS Apps](https://docs.flutter.dev/get-started/install/macos/mobile-ios) page says "If you haven't enrolled in the [Apple Developer](https://developer.apple.com/programs/) program, enroll now.". But this is not the case, you can develop apps for an iOS device with XCode with an Apple ID, an Apple Developer account is not required.

**Comment by sfshaza2** [comment]
Good point. You don't need that until you are ready to deploy.
