### ISSUE TITLE
Remove "skipping steps" warning at top of install page

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#10878]
When I open one of our [install instructions](https://docs.flutter.dev/get-started/install/macos/mobile-ios), we show a warning at the top of the screen saying "Skipping steps can cause errors". This is condescending to most readers, since by definition step-by-step instructions must be done in order without skipping steps (unless they are marked as optional). 

<img width="963" alt="Screenshot 2024-07-11 at 3 37 44 PM" src="https://github.com/user-attachments/assets/f7e147d5-6c0d-445b-b878-3137addd5e29">

**Comment by sfshaza2** [comment]
I agree.

**Comment by atsansone** [comment]
This was requested when the initial UX research and work with product management was done. This warning was to be explicit on the order.

@anderdobo : Correct me if I'm misremembering.

**Comment by johnpryan** [comment]
I'm not sure I understand what you mean, are you saying we have UX research that found that users skipped steps during the install process, or that showing a banner like this reduced the number of users that were skipping steps?

**Comment by anderdobo** [comment]
The banner wasn't a requirement. Perhaps the banner was added as an alternative to what I recommended, which was:

> Label each major section as a step so it’s clear not to skip any of these major tasks:

> - Step 1 System requirements

> - Step 2 Configure editor or integrated development environment

> - Step 3 Install Flutter SDK

> - Step 4 Configure for [Android/iOS/Web/Desktop] development 

> - Step 5 Check your development setup

**Comment by sfshaza2** [comment]
@johnpryan, this issue is something of a mess. Has it been handled?

**Comment by johnpryan** [comment]
The banner has been taken out, but we might still want to label each section as a step. Filing this issue to track:
- https://github.com/flutter/website/issues/10957
