### ISSUE TITLE
Website doesn't provide links to source code and issue template

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#10883]
The Flutter website used to display a link to the source file that the page was created from, in the top-right corner, like the dart.dev site does:

<img width="988" alt="Screenshot 2024-07-11 at 3 56 37 PM" src="https://github.com/user-attachments/assets/8bb5b9ed-e707-4caa-8602-25b2360ecf87">

Were these removed intentionally? Can we add these back?

**Comment by sfshaza2** [comment]
OMG, I hadn't noticed that! Yes, we want that back!

**Comment by parlough** [comment]
I moved this to the bottom of each page, as it will make some other design and accessibility work I'm doing easier to complete and review. Once that is done, I could look at other ways to make it more prominent again.

**Comment by johnpryan** [comment]
Sounds good, I didn't realize they had moved to the bottom.
