### ISSUE TITLE
Reduce usage of includes throughout the site

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#10886]
I see a lot of usage of "include" tags in our website. I don't like this pattern, because it causes unnecessary redirection to other source files that exist elsewhere (as a maintainer, you need to jump around between `src/_includes` and `src/content`). This is especially prevelent in our getting started pages, which is written [almost entire as includes](https://github.com/flutter/website/tree/main/src/_includes/docs/install/reqs/macos). This makes it harder for contributers and maintainers, and the benefit is hard to understand. Why not just have a single file for each installation platform? Are we really getting the benefits we think we are by using so many includes?

**Comment by sfshaza2** [comment]
I completely agree, @johnpryan. Much work for minimal benfit.

**Comment by atsansone** [comment]
There is a great deal of opportunity for content reuse which is the use case for includes. Rather than repeatedly write the same content, these includes are used. I think we should take under advisement the frequency with which these are used, but I don't believe reduction would be advisable at this time.

**Comment by johnpryan** [comment]
> Rather than repeatedly write the same content, these includes are used.

The question is, why are we repeating content throughout the site? I think the maintenance burden is rather high, without much benefit for maintainers or new contributors. If there's something that needs to be referenced in multiple places, it's better IMO to include a link. The other benefit is that the content on our site can be indexed properly and searching for that content doesn't link you to multiple pages.

**Comment by sfshaza2** [comment]
The bottom line is that this VERY impactful change was made to the website without gathering feedback and without getting consensus. I find this part of the website very difficult to understand and maintain at this point. I feel very frustrated that it was done without my involvement, consent, or feedback.

**Comment by sfshaza2** [comment]
@johnpryan, as you peruse the site in future, feel free to start a list of things we should clean up. Perhaps do that in a new bug, as I plan to close this one.
