### ISSUE TITLE
Write V2 'Networking' first week experience page

### ISSUE THREAD

**Issue by ericwindmill** [flutter/website#10897]
### Page URL

https://docs.flutter.dev/get-started/fwe/networking

### Describe the problem

The current page is a list a links, which was the goal for V1 of FWE. The goal of V2 is to have more of the concepts are explained on the page directly.

### Expected fix

Ideally the examples suggested below would be related to each other, but it isn't required. This page does not need to be super in depth at this time.

- Expand "Intro to retrieving data over the network" with code examples and explanations.
- Expand the JSON ser/des section with code examples and explanations of parsing JSON into Dart objects via Freezed and/or by using patterns and records. These examples and explanation  can stay high-level, because we intend on having a separate page for JSON.
- Add an example of sending data in the "Going both ways" section.
-  Bring it all together with an example of using FutureBuilder.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by domesticmouse** [comment]
I spent a while thinking through what code I could write, but I consistently hit the issue that I was either building something too simplistic, short changing the linked material, or something overly complex. I'm at a loss of what to write here that isn't just aping the linked tutorials and codelabs.

Halp?
