### ISSUE TITLE
[ios]Make "Flutter for SwiftUI developers" up to date with iOS 18

### ISSUE THREAD

**Issue by hellohuanlin** [flutter/website#10902]
### Page URL

https://docs.flutter.dev/get-started/flutter-for/swiftui-devs

### Describe the problem

it was still iOS 16 when we wrote it. The SwiftUI part is 2 years outdated.

Similar to https://github.com/flutter/flutter/issues/150945

### I would like to fix this problem.

- [x] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
@hellohuanlin, let me know if I can help

**Comment by hellohuanlin** [comment]
Looks like the sample code in the website is pretty update, as it doesn't include any advanced SwiftUI usage that's been updated over the years. 
I am closing this as complete (nothing to do), and opened https://github.com/flutter/website/issues/11413 for future contribution.
