### ISSUE TITLE
Simplify stable channel warning at the bottom of the page

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#10907]
Right now, every page has this warning at the bottom:

```
Unless stated otherwise, the documentation on this site reflects the latest stable version of Flutter.  Page last updated on 2024-07-07. View source or report an issue.
```

I'm not sure what value is provided by saying "this site reflects the latest stable version of Flutter". Isn't that implied?

**Comment by sfshaza2** [comment]
Actually, no. This can really confuse folks. The statement has been on the bottom of the docs.flutter.dev page for awhile, but I absolutely do NOT mind having it as part of the footer.

**Comment by sfshaza2** [comment]
Thoughts, @parlough?

**Comment by johnpryan** [comment]
Happy to keep it if it avoids confusion - Now I'm wondering we could be more specific here, maybe by including the SDK version.
