### ISSUE TITLE
Messed up superscripts and footnotes

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#10919]
### Page URL

https://docs.flutter.dev/platform-integration/ios/apple-frameworks

### Describe the problem

The superscripts and footnotes on this page are quite messed up:  https://docs.flutter.dev/platform-integration/ios/apple-frameworks

Also, the page title should be "Leverage Apple.." not "Leveraging Apple..."

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Fixed in https://github.com/flutter/website/pull/10900
