### ISSUE TITLE
hotfix changelog link is 404

### ISSUE THREAD

**Issue by utamori** [flutter/website#10934]
### Page URL

https://docs.flutter.dev/release/release-notes/

### Page source

https://github.com/flutter/website/tree/main/src/content/release/release-notes/index.md

### Describe the problem

'Hotfixes to the Stable Channel' link is 404

https://github.com/flutter/flutter/blob/master/docs/releases/Hotfixes-to-the-Stable-Channel.md

### Expected fix

https://github.com/flutter/flutter/blob/main/CHANGELOG.md

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
This link was broken when we moved the Flutter wiki. Thanks for catching this!
