### ISSUE TITLE
Slack link is broken

### ISSUE THREAD

**Issue by lebeshev** [flutter/website#10945]
### Page URL

https://flutter.dev/community

### Describe the problem

The slack community link (https://fluttercommunity.dev/joinslack) leads to a "This link is no longer active" page

### Expected fix

Should send to a slack community

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
I passed this along to marketing, who passed it along to @slightfoot.

**Comment by slightfoot** [comment]
Sorry been sick and didn't get this fixed sooner. All sorted now. Thanks Shams. 

Just so you and others are aware of the situation with Slack. They let you create invite links that "don't expire" (within a time-frame) however they will always expired after being used X amount of times. This is just how there system works. Slack still don't want to give us API access so we can automate this unless we pay. Which I guess is fair enough, but the community can't afford Slack costs for ~20K users 🤯 So we have no way to determine when the link fails. 

Discussed this issue with @ScottS2017 and we will refresh the link weekly. This will hopefully mean that the chances of it "expiring" become that of more than X users sign-up within 1 week. Best I can offer at the moment.

P.S The X I believe here is 2000, but its a number that slack choose and we have no control over.
