### ISSUE TITLE
Add "The Flutter Foundation - A Comprehensive Guide for Technical Interviews and Beyond" to books page

### ISSUE THREAD

**Issue by chetankumar-cms** [flutter/website#10978]
The **Flutter Foundation - A Comprehensive Guide for Technical Interviews and Beyond** is **_the book available free to download_**, Book will take you on a journey through the fundamentals of Flutter, covering everything you need to know to ace technical interviews and excel as a Flutter developer. From basic concepts to advanced topics, each question is carefully crafted to provide a comprehensive understanding of Flutter development principles and best practices.

**Page URL**
https://docs.flutter.dev/resources/books/

**Page source**
https://github.com/flutter/website/tree/main/src/content/resources/books.md

**Expected fix**
Add book new book @ Books about Flutter

**Resource**
**Title -** Flutter Foundation - A Comprehensive Guide for Technical Interviews and Beyond
**Author -** Chetankumar Akarte
**Website/Download link:** [https://chetanakarte.gumroad.com/l/the_flutter_foundation](https://chetanakarte.gumroad.com/l/the_flutter_foundation)
**Book cover:** ![The-Flutter-Foundation-A-Comprehensive-Guide-for-Technical-Interviews-and-Beyond](https://github.com/user-attachments/assets/de8ac198-d15c-4b9b-b3a1-d4735f1b441e)

**Additional context**
Whether you're aiming to land your dream job as a Flutter developer, enhance your existing skills, or build innovative cross-platform applications, "The Flutter Foundation" equips you with the knowledge, tools, and confidence to succeed in today's competitive tech industry. Get ready to unleash your creativity, build exceptional Flutter apps, and embark on an exciting journey of learning and growth. Let's dive in and master The Flutter Foundation together!
(**First Edition** - 23 May 2024)
(**Flutter 3.10 - Dart 3**)

Please help to add this book to Books about Flutter page on flutter doc website.
Thanks
Chetankumar Akarte

**Comment by sfshaza2** [comment]
Hi, @chetankumar-cms, thanks for this info! I will do this, but if you are in a rush, feel free to submit a PR.

**Comment by sfshaza2** [comment]
Actually, @chetankumar-cms, I have a question. The subtitle for the book is "A Comprehensive Guide for Technical Interviews and Beyond." Is this book more about learning Flutter or preparing for a technical interview when looking for a Flutter job?

**Comment by chetankumar-cms** [comment]
Dear @sfshaza2 Yes! This Comprehensive Guide will help developer to learn conceptual implementation of flutter with the examples and brush up there technical knowledge so that they can excel their technical flutter interviews. It will be great if you take some of your busy time and have a look around this book. I have kept Flutter Foundation book Free so that everyone will explore it. I am not in much hurry. Please take this in consideration as per your convenience.
Thank you!
Chetankumar Akarte
LinkedIn - [https://www.linkedin.com/in/chetanakarte](https://www.linkedin.com/in/chetanakarte)

**Comment by chetankumar-cms** [comment]
Dear Shams @sfshaza2 where it will be possible for you to take this consideration?

**Comment by sfshaza2** [comment]
@chetankumar-cms, this sounds fine. Can you create the PR? Or find someone who can? I'm pretty swamped at the moment.

**Comment by chetankumar-cms** [comment]
This has been done through PR https://github.com/flutter/website/pull/11086
So closing this!
