### ISSUE TITLE
Code diffs don't show correct indentation

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#11028]
### Describe the problem

Code snippets that use [diff2html](https://diff2html.xyz/) are not indented correctly. 

### Expected fix

I'm not sure how to fix this, or what could be causing this, but perhaps there is something we are doing wrong in our tooling.

### On which platform(s) did you experience this issue?

macOS

### Additional context

For example, see the [Implicit animations](https://docs.flutter.dev/codelabs/implicit-animations) page.

Screenshot:
![Screenshot 2024-08-08 at 1 08 23 PM](https://github.com/user-attachments/assets/9a0d53d3-2c93-4e4f-9d43-6be3e3be97a1)

**Comment by johnpryan** [comment]
cc: @parlough

**Comment by parlough** [comment]
I want to get rid of diff2html very soon, so perhaps with this issue I'll prioritize that.
