### ISSUE TITLE
Raster stats feature has been removed from Flutter DevTools

### ISSUE THREAD

**Issue by elliette** [flutter/website#11026]
### Page URL

https://docs.flutter.dev/tools/devtools/performance

### Describe the problem

The Raster stats feature has been removed from DevTools, therefore references to it in the Performance view documentation should be removed. 

### Expected fix

Remove all references to "Raster stats tab"

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by elliette** [comment]
FYI @kenzieschmoll

**Comment by antfitch** [comment]
PR that deleted the feature: https://github.com/flutter/devtools/pull/7981
