### ISSUE TITLE
Image used in the 404 page for docs.flutter.dev is out of date

### ISSUE THREAD

**Issue by sethladd** [flutter/website#11051]
### Page URL

docs.flutter.dev/2982hf39238hf9238hf

### Describe the problem

The image of the bird is out of date. We have a new style/look for Dash.

### Expected fix

Use the 404 image from flutter.dev

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sethladd** [comment]
cc @kkboateng

**Comment by kkboateng** [comment]
Let's update this to be the same as the one on flutter.dev's 404 page. 

[Here](https://drive.google.com/file/d/1BwzaCJqwZM3TC5ujbzCsTbJRm5aDd0Gd/view?usp=sharing) is a link to that asset.

**Comment by sethladd** [comment]
Thanks for the help!
