### ISSUE TITLE
Add information about Flutter Code Push to the FAQ

### ISSUE THREAD

**Issue by ulusoyca** [flutter/website#11062]
### Page URL

https://docs.flutter.dev/resources/faq

### Describe the problem

The current FAQ section on the Flutter documentation does not include information about code push. This feature has become more relevant with the introduction of [Shorebird](https://shorebird.dev/)'s code push capability for Flutter, and it would be beneficial to include this in the FAQ.

### Expected fix

Add a section in the Flutter FAQ that explains code push, its importance, and mentions the tools, such as Shorebird, that facilitate it.

### Additional context

This issue was raised in a conversation on X, where it was agreed that adding this information would be valuable for Flutter developers. The discussion can be referenced [here](https://x.com/sethladd/status/1825019629083013235).

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sethladd** [comment]
Thanks for creating this! Happy to review a PR if someone is interested.

The key thing is to make it clear that Shorebird is _a_ option if someone is interested in learning more, but not an _official_ option.
