### ISSUE TITLE
Add FWE to the sidebar

### ISSUE THREAD

**Issue by ericwindmill** [flutter/website#11066]
### Describe the problem

FWE is nearly "v2 complete", and it would be more useful if it's easy to navigate. 

### Expected fix

Add FWE Pages to sidebar under "Getting Started". The "Learn More" link should be a drop down that lists each page. 

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Yes, I very much want to add these to the sidenav, but when I asked last week, you weren't quite ready.

**Comment by ericwindmill** [comment]
> Yes, I very much want to add these to the sidenav, but when I asked last week, you weren't quite ready.

@sfshaza2 I would like to wait until Khanh's PR (#11072) is ready. Do you have an idea for how this will fit into the side nav?

**Comment by sfshaza2** [comment]
Yes, I'd probably work it into Get started->Learn more. Overhaul and maybe rename that page.
