### ISSUE TITLE
Custom Interactive ink feature

### ISSUE THREAD

**Issue by Prithviraj639** [flutter/website#11085]
### What information needs to be added?

There is no documentation to create own custom interativeink feature (Splash factory)

### I would like to fix this problem.

- [x] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Thanks for the issue @Prithviraj639! Could you provide some more details on what "custom interactive ink feature" is?

**Comment by Prithviraj639** [comment]
When we click on a object we will get a ripple effect that is called interactive ink feature or splash factory, > Thanks for the issue @Prithviraj639! Could you provide some more details on what "custom interactive ink feature" is?

**Comment by sfshaza2** [comment]
@Prithviraj639, it looks like there are [several packages on pub.dev](https://pub.dev/packages?q=ripple) that you can use.

Meanwhile, maybe we could mention this on the fwe pages, @ericwindmill, or perhaps mentioning somewhere about the existence of packages.

**Comment by Prithviraj639** [comment]
> @Prithviraj639, it looks like there are [several packages on pub.dev](https://pub.dev/packages?q=ripple) that you can use.
> 
> Meanwhile, maybe we could mention this on the fwe pages, @ericwindmill, or perhaps mentioning somewhere about the existence of packages.

No there are no related packages, let me try to create it and submit it to resources.
