### ISSUE TITLE
Update status of iOS 18 across the docs after iOS 18 stable ships

### ISSUE THREAD

**Issue by sethladd** [flutter/website#11083]
Once iOS 18 ships, we need to audit the site for any mentions of "iOS18 is coming soon!" or the like, and update them.

One instance is on this page:

https://docs.flutter.dev/platform-integration/ios/app-extensions

**Comment by jmagman** [comment]
@sfshaza2 I think this is done?

**Comment by sfshaza2** [comment]
Yes!
