### ISSUE TITLE
List of Apple frameworks exposed by plugins has incorrect implementation detail

### ISSUE THREAD

**Issue by sethladd** [flutter/website#11088]
### Page URL

https://docs.flutter.dev/platform-integration/ios/apple-frameworks

### Describe the problem

The row for "Embed maps" incorrectly states that it wraps MapKit. In fact, this row's implementation wraps google maps.

### Expected fix

The row for "Embed maps" should be removed. I believe the intention of this page is to show which plugins surface Apple-provided APIs.

We might want to point to https://pub.dev/packages/apple_maps_flutter but we'd have to try it first.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sethladd** [comment]
cc @jmagman

**Comment by jmagman** [comment]
This `MapKit` unused import may have been the source of confusion: https://github.com/flutter/packages/pull/7522
