### ISSUE TITLE
Fonts and Typography page is sparse on details on how to use fonts

### ISSUE THREAD

**Issue by jwill** [flutter/website#11099]
### Describe the problem

The fonts and typography page has a large of space devoted to images and discussion of variable fonts, an advanced feature, with very little discussion of how to use common features like setting styles, changing colors, or what's contained in TextTheme.

### Expected fix

Reduce the discussion of variable fonts and explicitly discuss the typography scale provided in default themes (TextTheme on Material/ Cupertino, etc)

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
This is very very true (this page has a long and varied history). I welcome your edits, @jwill!!!
