### ISSUE TITLE
docs: add note that you should use proper indentation when specifying assets in `pubspec.yaml`

### ISSUE THREAD

**Issue by Luckey-Elijah** [flutter/website#11104]
### Page URL

https://docs.flutter.dev/ui/assets/assets-and-images/

### Page source

https://github.com/flutter/website/tree/main/src/content/ui/assets/assets-and-images.md

### Describe the problem

A common issue I see when developers follow a guide or even this document is when adding assets they do not specify the _correct_ indentation for the `assets` key. For example

```yaml
flutter:
assets:
  - directory/
```

### Expected fix

I think a `:::note` call-out (like for the sub-directory caveat https://github.com/flutter/website/blob/main/src/content/ui/assets/assets-and-images.md?plain=1#L42-L46) would be a helpful piece of information for those trying to resolve errors like `Error: unable to find directory entry in pubspec.yaml: ...`

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
@domesticmouse, is this related to the new code formatting?

**Comment by domesticmouse** [comment]
It's YAML formatting, not Dart code formatting

**Comment by Luckey-Elijah** [comment]
Yes. Sorry for any confusion. This is just about specifying the yaml configuration. Not related to any bug in the framework or language tooling.

**Comment by sfshaza2** [comment]
Right. I knew that. Brain freeze moment.
