### ISSUE TITLE
I'm not in China

### ISSUE THREAD

**Issue by EnTusPupilas** [flutter/website#11158]
### Page URL

https://docs.flutter.dev/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/content/get-started/install/index.md

### Describe the problem

There is an advise "If you develop apps in China, check out [using Flutter in China](https://docs.flutter.dev/community/china)."

### Expected fix

It should be the respective SDK

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Thanks for opening an issue @EnTusPupilas! However, I'm not sure what you mean by "the respective SDK"?

The note is for developers that may be developing in China, as they might need to follow special setup instructions. Developers outside of China can just ignore the note and choose their development platform on the page.

**Comment by EnTusPupilas** [comment]
@parlough 
Thank you, now I understand. The screen confused me a bit. I was referring to the Flutter SDK, now I know where it is. Thanks.


![Screenshot](https://github.com/user-attachments/assets/f593c885-7228-4d31-a5c0-bc19ffed81e1)
