### ISSUE TITLE
Correction to https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply

### ISSUE THREAD

**Issue by codeframeuk** [flutter/website#11170]
### Page URL

https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply/

### Page source

https://github.com/flutter/website/tree/main/src/content/release/breaking-changes/flutter-gradle-plugin-apply.md

### Describe the problem

Notes state: Most changes have to be made in the <app-src>/android/app/build.gradle.

### Expected fix

Notes should state: Most changes have to be made in the <app-src>/android/app/settings.gradle.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Thanks for opening an issue!

Could you clarify though? The section this sentence is in proceeds to discuss changes that generally need to be made to the `app/build.gradle` file. Do you think we should just drop the "Most changes have to be made in" portion?

**Comment by codeframeuk** [comment]
Hi there,
No problem, and apologies if I've got it wrong but, the issue (as I see it) is that the code changes the page suggests (eg def flutterRoot = localProperties.getProperty('flutter.sdk')) are not in build.gradle - I found them in settings.gradle. So, I felt it was a typo because those specific code changes should be undertaken in settings,gradle rather than build.gradle.
If I've got this wrong please feel free to close this and accept my apologies.
