### ISSUE TITLE
Flutter fundamentals page/docs needs a fun image

### ISSUE THREAD

**Issue by parlough** [flutter/website#11194]
### Page URL

https://docs.flutter.dev/get-started/fundamentals/

### Page source

https://github.com/flutter/website/tree/main/src/content/get-started/fundamentals/index.md

### Describe the problem

The Flutter Fundamentals docs need a fun, new image/logo (perhaps with Dash) like many pages on the marketing website have. This will make the page more attractive and give us some media to reference it with.

It should be an image that will work well in both dark and light mode, or have two different versions.

**Comment by parlough** [comment]
@ericwindmill I'm assigning this to you, as I believe a request will need to be made to someone (that I do not know). This is just a nice to have, but will make the root fundamentals page more appealing.

**Comment by sfshaza2** [comment]
Yes, I totally agree!

**Comment by ericwindmill** [comment]
I'm working on an image, but I'm going to wait until the re-design lands so I can make sure to match the ~ vibe ~

**Comment by sfshaza2** [comment]
It now has a fun image! Thx, @ericwindmill! Closing.
