### ISSUE TITLE
Updated clarification on Supported Platforms

### ISSUE THREAD

**Issue by sethladd** [flutter/website#11206]
### What information needs to be added?

This is a tracking issue to take a look at our Supported Platforms page https://docs.flutter.dev/reference/supported-platforms and see if there are opportunities to communicate levels (tiers?) of support in addition to how much we're automatically testing.

Some prior art is here for study: https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html (I'm sure there are plenty more prior arts out there)

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sethladd** [comment]
cc @jmagman

**Comment by sfshaza2** [comment]
FYI, @parlough.

**Comment by sfshaza2** [comment]
Once this has landed, I can publish Seth's blog post.
