### ISSUE TITLE
升级flutter3.24.1 提交Google警告错误

### ISSUE THREAD

**Issue by 528564233** [flutter/website#11202]
### Page URL

https://docs.flutter.dev/reference/supported-platforms/

### Page source

https://github.com/flutter/website/tree/main/src/content/reference/supported-platforms.md

### Describe the problem

This release will cause a significant drop in the number of devices yourapps supports on the following form factors
Car
Chromebook
Phone
Tablet
Reviewand confirm the changes to your supported devices before proceeding.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Hi there! My colleague (@parlough) and I are trying to understand your issue. Did you try to publish an app to the Google Play Console and you got this message?

Did you switch to a Flutter that required Android SDK 21? If so, you might be running into Flutters minimum supported Android version:  https://docs.flutter.dev/release/breaking-changes/android-kitkat-deprecation

**Comment by sfshaza2** [comment]
Haven't heard back from customer. I believe they are frustrating that we dropped support for Android SDK 21. That is something that the docs team has zero control over. Closing.
