### ISSUE TITLE
Where is the source code for alien-hawaii-2024.web.app?

### ISSUE THREAD

**Issue by jaredsburrows** [flutter/website#11204]
Where is the source code for https://alien-hawaii-2024.web.app/?

Can you post the Gtihub link to the source of https://github.com/flutter/website/commit/7196971e6915472756caba1f2f5ac7aac99646bd#diff-630d4c38be44e126f18b3a7aa570dbefa22abdc44e8315e2140d6cd2a49807daR173?

**Comment by parlough** [comment]
@yjbanov Is this something you'd be able to share? Or are there any updates to the experiment you could edit the text with?

\cc @kevmoo

**Comment by yjbanov** [comment]
The sources are [here](https://github.com/yjbanov/alien-hawaii) but I think this link outlived its usefulness. I'm going to remove it.

**Comment by yjbanov** [comment]
https://github.com/flutter/website/pull/11215

**Comment by jaredsburrows** [comment]
@yjbanov Are you saying the latest flutter version supports the same functionality as your demo app?

**Comment by yjbanov** [comment]
The demo app is built from the vanilla master channel some time this summer, so I'd say it's _likely_ that everything is already in the 3.24.x releases, but I haven't been keeping track, sorry. But what I was saying above is just that we don't need this link in the FAQ anymore.

**Comment by jtkeyva** [comment]
It seems like an example that SEO with Flutter is actually possible? Can this be confirmed? Did something change? Why did you remove the link from the FAQ?
Thanks
