### ISSUE TITLE
Slugify function returns same slug for both C and C++

### ISSUE THREAD

**Issue by gamelaster** [flutter/website#11225]
### Describe the problem

On page [Platform Channels page - Codec page](https://docs.flutter.dev/platform-integration/platform-channels#codec), there is table with data types support. Although, when C is clicked, C++ page is opened.
Those are differences between the tab buttons:
```html
<a class="nav-link" data-tab-save-id="c" id="10-tab" href="#10-tab-panel" role="tab" aria-controls="10-tab-panel" aria-selected="true">C++</a>
```
```html
<a class="nav-link" data-tab-save-id="c" id="11-tab" href="#11-tab-panel" role="tab" aria-controls="11-tab-panel" aria-selected="false">C</a>
```
We can notice that `data-tab-save-id` is same, resulting in collision.
It's because `slugify` function used in [shortcodes.js](https://github.com/flutter/website/blob/c95f360f67112efdca095bc52a77a2c521c3eb1e/src/_11ty/shortcodes.js#L49) just removes all `+` characters, since they cannot be in the slug. 

### Expected fix

One of solutions which comes on my mind is just to replace `+` character with `plus` in `slugify` function.

**Comment by sfshaza2** [comment]
Routing this to @parlough.
