### ISSUE TITLE
Mistakes in firebase docs

### ISSUE THREAD

**Issue by PrimeTheFirst** [flutter/website#11233]
### Page URL

https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#6

### Describe the problem

The page gives incomplete code. By the end, it mentions that google sign in/up works, but it doesnt. They forgot to add sha1 and sha256 fingerprints to the firebase project settings, due to which it says "An unknown error has occurred". 

### Expected fix

Please mention the instructions to generate and save the fingerprints and make the app work.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
@RedBrogdon, I'm escalating this. How to roite errors in the Flutter firebase docs?

**Comment by ericwindmill** [comment]
Hey @PrimeTheFirst -- I updated this codelab earlier this week to fix some configuration with Firebase, so it should work as expected.

Feel free to reopen this if you continue having issues.

**Comment by PrimeTheFirst** [comment]
Where are the corrections? I dont see any

**Comment by PrimeTheFirst** [comment]
Bump

**Comment by ericwindmill** [comment]
@PrimeTheFirst, Which OS/device are you targeting?
