### ISSUE TITLE
same video show in Two times in a website 

### ISSUE THREAD

**Issue by priyanshukumar624** [flutter/website#11288]
### Page URL

https://docs.flutter.dev/ui/widgets/

### Page source

https://github.com/flutter/website/tree/main/src/content/ui/widgets/index.md

### Describe the problem

same video show in two times in website 
title- flutter rating bar video from youtube
![Screenshot (166)](https://github.com/user-attachments/assets/0d1cb99c-addc-4fb4-9823-ea67e2a1880f)

### Expected fix

`
![Screenshot (167)](https://github.com/user-attachments/assets/511da70c-2e65-4383-a310-dc1f299f4348)
`

Both are same video from YouTube - flutter rating bar

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Fixed by https://github.com/flutter/website/pull/11420 (https://github.com/flutter/website/commit/5f26e5defdf93e6dd75cd27147ee6bc5732780ae)

Thanks for catching and reporting this!
