### ISSUE TITLE
Traducción de carpeta get started

### ISSUE THREAD

**Issue by Arkangel12** [flutter/website#1129]
Se realizara la traduccion de toda la carpeta, esta contiene la instalación para Windows, macOS y Linux y de igual manera contiene la primera prueba de Flutter y su primer laboratorio.

**Comment by Arkangel12** [comment]
Please remove this issue it was a mistake between original and new Spanish website.

**Comment by Sfshaza** [comment]
@Arkangel12, can you share the URL for the Spanish site?

**Comment by Arkangel12** [comment]
Of course, we just start working on the translation, we have been using this [Flurrer-es](https://flutter-es.firebaseapp.com/) and here is our github repo [Flutter-es Repo](https://github.com/flutter-es/website).

We hope next week have flutter-es.org website on, still working on the name although. 👍

**Comment by Sfshaza** [comment]
Thanks! Is keeping it in sync with ours an issue?

I must apologize in advance, as we are in the process of re-doing our website and things will be changing.

**Comment by Arkangel12** [comment]
oh ok, if you want to we can contribute in your work in progress, whenever you want to, that way it could be easier for us too, we are start growing as a LATAM group in Flutter so much of us want to be part of this work.

Thank you for keep things changing that is always good and for been in touch with the people. About your question a will have  to ask Daniel, who did all that configuration between repos and i will let you know.
