### ISSUE TITLE
Testing page: add mention of "see `flutter test --help` for more options"

### ISSUE THREAD

**Issue by chalin** [flutter/website#1131]
Regarding https://flutter.io/testing/. Followup to https://github.com/flutter/website/pull/1125#issuecomment-409618465 where @Sfshaza wrote:

> The text you've added is very straightforward, but I tend to agree with @zoechi and @chalin that the Flutter doc should explain that it's based on dart-lang/test and also that they should consult the --help option.

**Comment by manhluong** [comment]
Thanks!

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/4451
