### ISSUE TITLE
Update "Embedding web content into a Flutter web app"

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#11322]
- [ ] Remove note that package:webview_flutter_web as "not endorsed", since it's an official package

cc @ditman do you know this package is listed as not endorsed?

**Comment by ditman** [comment]
> cc @ditman do you know this package is listed as not endorsed?

Yes, it is not endorsed because the web implementation *lacks* most of the functionality of the mobile one (and most of the missing functionality cannot be implemented anyways).

From the README:

> [...] It is currently severely limited and doesn't implement most of the available functionality. The following functionality is currently available:
>
> * `loadRequest`
> * `loadHtmlString` (Without baseUrl)
>
> Nothing else is currently supported.

See: https://pub.dev/packages/webview_flutter_web

**Comment by ditman** [comment]
We can remove the note about the package being not endorsed, but I'd keep a link to the package in pub, so people have a chance of reading the README.
