### ISSUE TITLE
Update "Web FAQ" page

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#11326]
https://docs.flutter.dev/platform-integration/web/faq

- [x] Remove "How do I create an app that also runs on the web"
- [x] Move hot restart question to "build a web app" page
- [x] Remove "How do I embed a Flutter web app in a web page?"
- [x] Remove "How do I embed web content in a Flutter web app?"
- [x] Move "How do I debug a web app?" into "Build a web app with flutter"
- [x] Move "How do I test a web app" into the "Build a web app with Flutter" page

**Comment by Dhruv80576** [comment]
Can i work on it?
