### ISSUE TITLE
Google one is a native app not flutter. (android)

### ISSUE THREAD

**Issue by DurgaPrasadAG** [flutter/website#11372]
### Page URL

https://flutter.dev/showcase

### Describe the problem

The showcase says google one uses flutter. I checked the licences in android version of the app. It is a native app not Flutter.

### Expected fix

Google One should be excluded if it is not Flutter

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Passed this on to marketing.

**Comment by kkboateng** [comment]
Google One continues to use Flutter on iOS! Thank you for keeping us honest though!

**Comment by DurgaPrasadAG** [comment]
Just checked on ios device. Its a Flutter version. 
Android: Native
ios: Flutter
Weird but it is cross-platform ready.
