### ISSUE TITLE
Missing note: The file should be recompiled using `Visual Studio` for the changes to take effect.

### ISSUE THREAD

**Issue by AbdeMohlbi** [flutter/website#11390]
### Page URL

https://docs.flutter.dev/platform-integration/platform-channels/

### Page source

https://github.com/flutter/website/tree/main/src/content/platform-integration/platform-channels.md

### Describe the problem

After completing [Step 5 in the Flutter documentation](https://docs.flutter.dev/platform-integration/platform-channels#step-5-add-a-windows-platform-specific-implementation), replace the code with the following:

```cpp
channel.SetMethodCallHandler(
    [](const flutter::MethodCall<>& call,
       std::unique_ptr<flutter::MethodResult<>> result) {
      if (call.method_name() == "getBatteryLevel") {
        int battery_level = GetBatteryLevel();
        if (battery_level != -1) {
          result->Success(battery_level);
        } else {
          result->Error("UNAVAILABLE", "Battery level not available.");
        }
      } else {
        result->NotImplemented();
      }
    });
```
You should now be able to run the application on Windows. If your device doesn't have a battery, it will display 'Battery level not available'.

### Expected fix

i suggest adding at the end :
`Note: To ensure the changes take effect, the project should be recompiled with Visual Studio. Otherwise, you may encounter an error saying: Failed to get battery level: Memory leak.`
it's not mention that the `exe` should be recompiled using `Visual studio ` again.
also the error message of the leaking is very confusing.

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by AbdeMohlbi** [comment]
> > To ensure the changes take effect, the project should be recompiled with Visual Studio.
> 
> There is no such requirement given the way Flutter builds are structured; `flutter run`/`flutter build` will rebuild native code.
> 
> If you have a case where `flutter run` does not pick up changes to native code in your project, please file an issue in flutter/flutter with detailed reproduction steps.

Should i report the issue on flutter/flutter or flutter/website

**Comment by sfshaza2** [comment]
Closing.
