### ISSUE TITLE
Dead link to example repo

### ISSUE THREAD

**Issue by itsJimothy** [flutter/website#11428]
### Page URL

https://docs.flutter.dev/cookbook/architecture/key-value-data/

### Page source

https://github.com/flutter/website/tree/main/src/content/cookbook/architecture/key-value-data.md

### Describe the problem

The link to the "full runnable source-code" example near the top of the article is dead and currently leads to a 404 GitHub page:
https://github.com/flutter/flutter/tree/main/examples/cookbook/architecture/todo_data_service/

### Expected fix

Link to the correct repo.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by miquelbeltran** [comment]
Fixed in #11435
