### ISSUE TITLE
Link /examples/cookbook/architecture/todo_data_service/ is broken

### ISSUE THREAD

**Issue by andrew-qa** [flutter/website#11433]
### Page URL

https://docs.flutter.dev/cookbook/architecture/key-value-data/

### Page source

https://github.com/flutter/website/tree/main/src/content/cookbook/architecture/key-value-data.md

### Describe the problem

Link specified in note 
```
Note
The full, runnable source-code for this example is available in [/examples/cookbook/architecture/todo_data_service/](https://github.com/flutter/flutter/tree/main/examples/cookbook/architecture/todo_data_service/).
```
is leading to absent folder

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by miquelbeltran** [comment]
Thanks for the report. The correct URL should point to https://github.com/flutter/website/tree/main/examples/cookbook/architecture/todo_data_service/

A PR with the fix has been submitted.
