### ISSUE TITLE
The ViewModel resides in the Logic layer

### ISSUE THREAD

**Issue by KyoheiG3** [flutter/website#11432]
### Page URL

https://docs.flutter.dev/app-architecture/guide#optional-domain-layer

### Page source

https://github.com/flutter/website/tree/main/src/content/app-architecture/guide.md#optional-domain-layer

### Describe the problem

In the image, there are ViewModel in both the UI layer and the Logic layer, but isn't the Logic layer actually a UseCase?

### Expected fix

The ViewModel of the Logic layer is a UseCase.

### Additional context

In the image at the URL below, the Logic layer is labeled UseCase instead of ViewModel.
https://docs.flutter.dev/app-architecture/guide#data-access-with-use-cases

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by miquelbeltran** [comment]
This looks like a mistake indeed, the diagram shows:

![image](https://github.com/user-attachments/assets/e80a6a10-b112-4705-afa0-3535040436b1)

while the diagram below is correct:

![image](https://github.com/user-attachments/assets/56d18844-a23f-4e74-9c33-e360c9f2bf5a)
