### ISSUE TITLE
Need to explain the existence of `flutter update-packages`

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/website#1143]
One of the available commands for the flutter CLI tool is `flutter update-packages`. After talking with @amirh, I've learned it's intended for people working on Flutter itself, rather than apps built with Flutter. We should document its existence somewhere near here:

https://flutter.io/using-packages/#updating-package-dependencies

In a "use this, not that" sort of way, so that no one gets confused.

**Comment by Sfshaza** [comment]
It's also mentioned in the wiki, as it should be:
https://github.com/flutter/flutter/wiki/Upgrading-dependencies
