### ISSUE TITLE
No details shows

### ISSUE THREAD

**Issue by Angela24260** [flutter/website#11474]
### Page URL

https://docs.flutter.dev/get-started/install/macos/

### Page source

https://github.com/flutter/website/tree/main/src/content/get-started/install/macos/index.md

### Describe the problem

i dont want to use flutter in china and It wont show the detail

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Hi, @Angela24260! I'm sorry, we don't provide tech support on this channel. Please refer to the flutter.dev/community page for advice on support.

Also, here is our advice for Flutter developers in China:
<img width="1175" alt="Screenshot 2024-12-14 at 10 47 57 AM" src="https://github.com/user-attachments/assets/a52afb16-9ed2-470d-b6e2-55aa852600e5" />

Good luck!  Closing.
