### ISSUE TITLE
Support for WebAssembly page is outdated (Safari now supports WasmGC)

### ISSUE THREAD

**Issue by gitslav** [flutter/website#11484]
### Page URL

https://docs.flutter.dev/platform-integration/web/wasm

### Describe the problem

Support for WebAssembly page is outdated as Safari now supports WasmGC.

### Expected fix

The page needs to be updated.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by kevmoo** [comment]
Yep! Needs to be updated to the latest blocking issue: https://bugs.webkit.org/show_bug.cgi?id=267291

**Comment by kevmoo** [comment]
CC @johnpryan and or @parlough ?

**Comment by gitslav** [comment]
@kevmoo I hope this gets more attention than the Firefox bug 🤞

**Comment by johnpryan** [comment]
Here's a PR that updates the link: https://github.com/flutter/website/pull/11488
