### ISSUE TITLE
Problema creazione progetto flutter

### ISSUE THREAD

**Issue by ghost** [flutter/website#11482]
### Page URL

https://docs.flutter.dev/resources/support/

### Page source

https://github.com/flutter/website/tree/main/src/content/resources/support.md

### Describe the problem

Quando creo un progetto flutter,mi si blocca android studio,interrompo il task dalla gestione acttività,riapro AS e vedo che la parte java/kotlin del progetto è un disastro,mancanza di parentesi,librerie ed altro,come risolvo??

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
Google translate yields this result:
When I create a flutter project, if I block android studio, I interrupt the task of managing activity, I see that the java/kotlin part of the project is a disaster, parentesi problems, libraries and others, come risolvo??

Hi, @ghost! I'm sorry, but we don't provide developer support on this channel. Please refer to the flutter.dev/community page for advice on where you can get Flutter support.

Closing
