### ISSUE TITLE
more broken links by Apple

### ISSUE THREAD

**Issue by Twinber** [flutter/website#1149]
- ./_site/setup-macos/index.html
  *  External link https://itunes.apple.com/us/app/xcode/id497799835 failed: 403 No error
- ./_site/showcase/index.html
  *  External link https://itunes.apple.com/br/app/vivabem-medita%C3%A7%C3%A3o/id1376295130 failed: 403 No error
  *  External link https://itunes.apple.com/us/app/betabubs-play-emojis/id1363316057 failed: 403 No error
  *  External link https://itunes.apple.com/us/app/coach-yourself/id1372759980 failed: 403 No error
  *  External link https://itunes.apple.com/us/app/hookle/id1330557977 failed: 403 No error

error 403.... boicot???? 👎

**Comment by Sfshaza** [comment]
All of these URLs are fine but, for some reason, a 403 (forbidden) is being produced. Not sure what is going on here. @chalin, any idea?

**Comment by Twinber** [comment]
today it works...

**Comment by Sfshaza** [comment]
It was a glitch. Closing.
