### ISSUE TITLE
Wrong float to int calculation in migration guide wide gamut Color

### ISSUE THREAD

**Issue by Peetee06** [flutter/website#11504]
### Page URL

https://docs.flutter.dev/release/breaking-changes/wide-gamut-framework/

### Page source

https://github.com/flutter/website/tree/main/src/content/release/breaking-changes/wide-gamut-framework.md

### Describe the problem

The calculations in the suggested extension [IntColorComponents](https://docs.flutter.dev/release/breaking-changes/wide-gamut-framework#access-color-components) in the 3.27.0 wide gamut Color migration guide seem to be wrong.

This is the suggested extension:
```dart
extension IntColorComponents on Color {
  int get intAlpha => this.a ~/ 255;
  int get intRed => this.r ~/ 255;
  int get intGreen => this.g ~/ 255;
  int get intBlue => this.b ~/ 255;
}
```

The remainder of a double floating-point component with values between 0 and 1 will either be 0 or 1. We want values between 0 and 255.

### Expected fix

In the `Color` class I found this private method which seems to have the correct calculation:
```dart
static int _floatToInt8(double x) {
  return (x * 255.0).round() & 0xff;
}
```

A possible fix could be:
```dart
extension IntColorComponents on Color {
  int get intAlpha => _floatToInt8(this.a);
  int get intRed => _floatToInt8(this.r);
  int get intGreen => _floatToInt8(this.g);
  int get intBlue => _floatToInt8(this.b);

  int _floatToInt8(double x) {
    return (x * 255.0).round() & 0xff;
  }
}
```

I'd be happy to update the documentation, if someone can confirm this.

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
@gaaclarke, can you confirm?

**Comment by gaaclarke** [comment]
> @gaaclarke, can you confirm?

Yep, what @Peetee06 has mentioned is correct.  Thanks @Peetee06.

**Comment by sfshaza2** [comment]
@Peetee06, go ahead and submit a PR! :D
