### ISSUE TITLE
Share links preview show markdown 

### ISSUE THREAD

**Issue by Twinber** [flutter/website#1155]
![89e11d33-5c32-431e-8d27-980b4a9a234a](https://user-images.githubusercontent.com/5513621/44094473-2c1c5a00-9fce-11e8-9afa-fbdd4f195788.jpeg)

**Comment by chalin** [comment]
Is that a screen shot of https://flutter.io/faq/? Curious, it's ok for me: 
<img width="546" alt="screen shot 2018-08-14 at 10 13 35" src="https://user-images.githubusercontent.com/4140793/44097002-bb8e9816-9faa-11e8-8d20-ca02b2249802.png">
Could you try emptying the cache of your browser and reloading?

**Comment by Twinber** [comment]
It is a screenshot of the result of sharing the url by whatsapp or telegram
