### ISSUE TITLE
The website breaks when viewing on certain devices. 

### ISSUE THREAD

**Issue by Samaritan1011001** [flutter/website#1159]
Certain parts of the website break when viewed on a mobile device. 
![img_51baec6e0f47-1](https://user-images.githubusercontent.com/10944487/44211110-dcaf5300-a185-11e8-945b-3327e2224aee.jpeg)

As one of the contributors to this section of the website, I was not happy seeing this so I started digging into the issue and found that this happened due to certain words (like function names etc) having more than a certain character count. 

Splitting up those words (since some of these are functions so it does not actually make sense to split them) like `debugDumpApp()` to `debug Dump App()` under the `Debugging` section seemed to solve the issue.

As @Sfshaza suggested, I have opened this issue so this can be of some help.

**Comment by Sfshaza** [comment]
@filiph, @chalin, we need to keep this in mind for the updated website.

**Comment by chalin** [comment]
Totally agree, checking site rendering on mobile should be integrated into our workflow.

**Comment by Sfshaza** [comment]
The work on the new website is well underway. I just checked this page in the mobile format and it looks great. We aren't fixing bugs on master unless they are P0.  Thanks for reporting, @Samaritan1011001!
