### ISSUE TITLE
Add check to ensure images are optimally compressed

### ISSUE THREAD

**Issue by chalin** [flutter/website#1162]
From https://github.com/flutter/flutter/issues/20548:

> Yes, we have scripts for the *.dartlang sites that sweep over all images, but had decided to not  integrate them into the build checks / or set them up via hooks. IMHO, it is probably enough to setup a **cron job** to check this offline, outside of the main site-update workflow.

**Comment by sfshaza2** [comment]
I think you've done this, @chalin?

**Comment by sfshaza2** [comment]
(Oops, didn't mean to close. Please reopen if still an issue.)
