### ISSUE TITLE
[website] images should have padding by default

### ISSUE THREAD

**Issue by chalin** [flutter/website#1171]
_From @chalin on July 25, 2018 13:11_

Otherwise we get this:

> <img width="675" alt="screen shot 2018-07-25 at 09 10 45" src="https://user-images.githubusercontent.com/4140793/43202887-a9d201fa-8fea-11e8-95a9-8cb61a7c4252.png">

cc @Sfshaza @filiph 

_Copied from original issue: flutter/flutter#19762_

**Comment by Sfshaza** [comment]
Another YES from me!

**Comment by sfshaza2** [comment]
I just checked some pages and this is no longer an issue. Closing.
