### ISSUE TITLE
Add timestamps to all pages

### ISSUE THREAD

**Issue by chalin** [flutter/website#1174]
_From @chalin on July 25, 2018 9:44_

Site-www and -webdev use this: e.g., Site build #3887 (2018/07/24 03:56 PDT). This makes it easier to identify which build of the site is actually deployed.

cc @Sfshaza @filiph 

_Copied from original issue: flutter/flutter#19753_

**Comment by chalin** [comment]
_From @Sfshaza on July 25, 2018 13:15_

Nice.

**Comment by sfshaza2** [comment]
Nice but I don't consider it essential.

**Comment by chalin** [comment]
Right, it isn't essential, but it is very useful when "debugging" site deploys (which has happened more than once for www in particular). That said, p3 is a good priority level.

**Comment by atsansone** [comment]
Investigate using https://github.com/gjtorikian/jekyll-last-modified-at
