### ISSUE TITLE
Ruby Sass gem has reached EOL and should no longer be used

### ISSUE THREAD

**Issue by chalin** [flutter/website#1175]
Attempting to install the `sass` gem results in the warning: _Ruby Sass has reached end-of-life and should no longer be used._

- [x] Replace our direct dependency on the `sass` gem by `sassc`
- [ ] Upgrade to Jekyll 4 and the latest jekyll-assets
- Bootstrap 4 and font-awesome-sass are already using `sassc`

---

_From @chalin on July 24, 2018 15:13_

From [this Travis log](https://travis-ci.org/flutter/website/builds/407652791):

> Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.
> * If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install
> * If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme
> * For more details, please refer to the Sass blog:

cc @Sfshaza @filiph 

_Copied from original issue: flutter/flutter#19715_

**Comment by chalin** [comment]
_From @filiph on July 24, 2018 18:13_

Oooh, using Dart Sass would be great.

**Comment by Sfshaza** [comment]
Sounds good to me!

**Comment by sfshaza2** [comment]
Where are we on this, @chalin?

**Comment by parlough** [comment]
Closing as updating to Jekyll 4 with the infrastructure updates no longer uses Ruby Sass.
