### ISSUE TITLE
Fix page descriptions

### ISSUE THREAD

**Issue by chalin** [flutter/website#1176]
_From @chalin on July 24, 2018 19:30_

The meta properties `description` and `og:description` use `page.description` or the initial text from the page. In some cases, the latter isn't very pretty; e.g. from `_site/web-analogs/index.html`:

> \<meta name="description" content="Contents:* TOC Placeholder{:toc}This page is for users who are familiar with the HTML and CSS syntax forarranging components of an application's UI. It maps HTML/CSS code snippets totheir Flutter/Dart code equivalents.The examples assume:* The HTML document starts with a modern HTML DOCTYPE, and the CSS box model for all HTML...">

Maybe all pages should be required to have a description attribute in the Jekyll front matter, or the description could be dropped otherwise.

cc @Sfshaza @filiph 

_Copied from original issue: flutter/flutter#19723_

**Comment by chalin** [comment]
_From @Sfshaza on July 25, 2018 13:16_

Yes, we should add that and be consistent. The lawless days of chaos will soon be over.  ;)

**Comment by Sfshaza** [comment]
Just want to confirm I support adding a sensible description to the front jekyll matter. I can do this as part of the content migrations.
