### ISSUE TITLE
External link checking in builds is flakey

### ISSUE THREAD

**Issue by chalin** [flutter/website#1177]
_From @devoncarew on June 1, 2018 18:31_

See:

```
https://travis-ci.org/flutter/website/builds/386776246#L977
```

They flake when trying to validate external links, which can occasionally 404.

_Copied from original issue: flutter/flutter#18118_

**Comment by chalin** [comment]
_From @Sfshaza on June 6, 2018 9:44_

Truth. The *.dartlang sites check only for broken internal links on a commit. But they have a cron job, I believe, that tests external links weekly. @kwalrath?

**Comment by chalin** [comment]
_From @kwalrath on June 6, 2018 23:32_

I don't think we have such a cron job, but we probably should.

/cc @chalin

**Comment by chalin** [comment]
Right, this is still WIP for both sites (https://github.com/dart-lang/site-www/issues/240, https://github.com/dart-lang/site-webdev/issues/784). In the meantime I check external links by hand now and again.

**Comment by Sfshaza** [comment]
@kwalrath, I thought the weekly report of broken links on www.dartlang that we receive in email was a cron job.

**Comment by chalin** [comment]
We are now using @filiph's linkcheck tool configured to report connection failures as warnings rather than errors. So far, it seem to be working well.
