### ISSUE TITLE
README file needs some love

### ISSUE THREAD

**Issue by Sfshaza** [flutter/website#1185]
For the Flutter FLUTTER repo.

**Comment by jamesderlin** [comment]
Did you intend to self-assign this?  If not, are there specific things in mind that need to be corrected/improved?

**Comment by Sfshaza** [comment]
Nope, @jamesderlin. Actually, I'm going to close it.

**Comment by Sfshaza** [comment]
OK, I re-opened and clarified.  The flutter/flutter repo README needs some updating.

@maguinis, do you care to weigh in on what you'd like to see on this page? Here are some ideas:

* For example, the hot reload animated GIF should be updated. (Update iPhone version.)
* Much of the marketing info should probably be updated.

Let us know your thoughts, Martin.

**Comment by Sfshaza** [comment]
@mit-mit updated the README on flutter/flutter. Closing.
