### ISSUE TITLE
page using-packages mistakes

### ISSUE THREAD

**Issue by Twinber** [flutter/website#1188]
https://flutter.io/using-packages/

In the first example the paragraph: 
"Run the app. When you click the ‘Show Flutter homepage’ you should see the phone’s default browser open, and the Flutter homepage appear."

This phrase refers to the following example and is also not well indexed

**Comment by Twinber** [comment]
The second code example code also not well indexed

**Comment by sfshaza2** [comment]
I think @Twinber is referring to the fact that the numbered lists aren't working properly. When this happens in markdown, I generally drop into HTML.

**Comment by sfshaza2** [comment]
I just checked and this has been fixed. Closing.
