### ISSUE TITLE
[Container image] Use Ruby 2.4.3

### ISSUE THREAD

**Issue by chalin** [flutter/website#1200]
The Cirrus container image is currently setup with Ruby 2.3.3; from a Cirrus log:

```console
> rvm current && ruby -v
system
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
```

It should be using Ruby 2.4.3 instead.

I believe that the Dockerfile is missing:

```dockerfile
RUN rvm use 2.4.3
```

cc @Sfshaza

**Comment by gspencergoog** [comment]
Closing, since Patrice moved things back to Travis for the moment, and we're likely to not use Docker when going back to Cirrus.
