### ISSUE TITLE
Cirrus builds are failing: "INVALID_ARGUMENT: No tasks found to start!"

### ISSUE THREAD

**Issue by chalin** [flutter/website#1201]
For example see: https://cirrus-ci.com/build/6391154123735040

The issue seems to be because of this contional: https://github.com/flutter/website/blob/568fc345160ed88c21ee2a52b706a4e58d0c994d/.cirrus.yml#L4-L6

As I'd mentioned [elsewhere](https://github.com/flutter/website/pull/1197/files#r213567319), AFAICT, there is no `CIRRUS_PR` environment variable defined for PR builds that originate from a branch on the website repo (see below for an example list of variables), and it would seem that `$CIRRUS_PR != ''` isn't true in that case.

```nocode
CIRRUS_BRANCH=chalin-jekyll-assets-0828
CIRRUS_BUILD_ID=6358354465128448
CIRRUS_CHANGE_IN_REPO=d1b309d7e8a23dd89c21bf3c3d5c32bbc7199c8a
CIRRUS_CI=true
CIRRUS_DEFAULT_BRANCH=master
CIRRUS_HTTP_CACHE_HOST=127.0.0.1:12321
CIRRUS_OS=linux
CIRRUS_REPO_CLONE_HOST=github.com
CIRRUS_REPO_CLONE_URL=https://github.com/flutter/website.git
CIRRUS_REPO_FULL_NAME=flutter/website
CIRRUS_REPO_NAME=website
CIRRUS_REPO_OWNER=flutter
CIRRUS_TASK_ID=6616932836966400
CIRRUS_TASK_NAME=website
CIRRUS_WORKING_DIR=/opt/website
```

Maybe the conditional should instead be:

```yaml
website_task:
  # Only run this task on non-master or PR builds.
  only_if: $CIRRUS_BRANCH != master || $CIRRUS_PR != ''
```

cc @Sfshaza

**Comment by gspencergoog** [comment]
No, the CIRRUS_PR variable is defined only for PR builds, and the idea was to prevent the secrets from being defined for PR builds, because someone could use them that way without having to have permission to commit a PR.

Closing this, since Patrice has switched us back to Travis for the moment anyhow.
