### ISSUE TITLE
Linter error travis

### ISSUE THREAD

**Issue by Twinber** [flutter/website#1206]
Your friends and followers of flutter-es/website, we receive the following error, after the last changes of the new beta version:

info • Avoid using unnecessary statements • example/key_value_md_1.dart:51:7
https://travis-ci.org/flutter-es/website/builds/422064739

Any help or suggestion will be greatly appreciated

**Comment by chalin** [comment]
Hola! Try upgrading flutter. Let me know if that works.

**Comment by Twinber** [comment]
We are using the same scripts as you, for CI with Travis, as you can see [here](https://github.com/flutter-es/website/tree/master/tool), how should flutter upgrade, modifying the file before_install.sh?

**Comment by chalin** [comment]
Oh, I read too quickly, sorry! I saw a similar error locally, and upgrading flutter solved that issue. I'll have to investigate further but it might not be until tomorrow.

**Comment by chalin** [comment]
The current build of master seems to be fine: https://travis-ci.org/flutter-es/website/builds/422487805. Maybe try rebasing, and let me know if you still have an issue.

**Comment by Twinber** [comment]
Yes, provisionally we have disabled code checking. I have to review your last commits and try again. 
Thank you.

**Comment by sfshaza2** [comment]
Did you resolve this, @Twinber?

**Comment by sfshaza2** [comment]
Assuming this is good. Closing.
