### ISSUE TITLE
makdown code in meta description

### ISSUE THREAD

**Issue by Twinber** [flutter/website#1207]
`<meta name="description" content="* Placeholder for TOC{:toc}## Introduction### What is Flutter?Flutter is Google’s mobile app SDK for crafting high-qualitynative experiences on iOS and Android in record time.Flutter works with existing code, is used by developersand organizations around the world, and is free and open source.### What does Flutter do?For users, Flutter makes beautiful...">`

from  https://flutter.io/faq/

**Comment by chalin** [comment]
Yes, thanks, this has been reported in #1176.
