### ISSUE TITLE
[dash] Delete catalog/samples/tabbed_app_bar.md?

### ISSUE THREAD

**Issue by chalin** [flutter/website#1208]
The site has the following redirect rule:

```json
      {
        "source": "/catalog/samples/tabbed-app-bar/",
        "destination": "/cookbook/design/tabs/",
        "type": 301
      },
```

Hence the page `flutter/website/src/catalog/samples/tabbed_app_bar.md` is inaccessible. Can we delete the markdown source @Sfshaza?

**Comment by Sfshaza** [comment]
I'm trying to figure out what to do with those 4 UI samples. I'd prefer to move them off-site and incorporate them into the Flutter samples repo. Then we could remove that page entirely.

**Comment by sfshaza2** [comment]
I looked and the old samples seem to have been removed, which is fine. Closing.
