### ISSUE TITLE
[dash] Place all/most images under asset management

### ISSUE THREAD

**Issue by chalin** [flutter/website#1213]
- [x] Create `src/_assets/image`.
- [ ] Move images to `src/_assets/image`.
- [ ] Replace in-doc references to images by `jekyll-assets` image elements.

**Comment by sfshaza2** [comment]
Are we pretty close to this, @chalin?

**Comment by chalin** [comment]
My guesstimate is that we're about 65% there. I work on this, time permitting, whenever I edit a page that has a local images folder.

**Comment by parlough** [comment]
I just went through and confirmed that where it makes sense, images are within `src/assets/image`.
