### ISSUE TITLE
Issue from website page Animations in Flutter

### ISSUE THREAD

**Issue by gggustafson** [flutter/website#1216]
From URL: https://flutter.io/animations/

Under Physics-based animation, I read:

In physics-based animation, motion is modeled to resemble real-world behavior. When you toss a ball, for example, where and when it lands depends on how fast it was tossed, how heavy it is, and how far off the ground. Similarly, dropping a ball attached to a spring falls (and bounces) differently than dropping a ball attached to a string.

The phrase "how heavy it is" should be deleted. "Heaviness" has nothing to do with trajectory.

**Comment by Sfshaza** [comment]
Fixed on the dash branch. (Not fixed on master, because it's not a P0.)

Thanks, @gggustafson!
