### ISSUE TITLE
Issue from website page Upgrading Flutter

### ISSUE THREAD

**Issue by zackdorward** [flutter/website#1219]
From URL: https://flutter.io/upgrading/

I have an issue running my project on an emulator and running flutter doctor.
ERROR: Could not connect to lockdownd, error code -8

Here is what I get when I run flutter doctor: 
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.6.0, on Mac OS X 10.13.6 17G65, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
Unhandled exception:
Exception: idevice_id returned an error:
ERROR: Could not connect to lockdownd, error code -8

#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:74:9)

**Comment by Sfshaza** [comment]
I don't see an issue with the docs. If you are still experiencing problems installing or upgrading Flutter, please file a bug against the flutter/flutter repo. (This is the website repo, for docs.)  Thanks.
