### ISSUE TITLE
Add 'Boostrap into Dart' menu item in sidebar menu

### ISSUE THREAD

**Issue by divyadeepsawhney** [flutter/website#1222]
A menu item having a hyperlink to the following URL should be added to the sidebar menu on the homepage & other pages.

https://flutter.io/bootstrap-into-dart/

**Comment by Sfshaza** [comment]
Thanks, @divyadeepsawhney. We are reworking the website and, back when I found this page, you could have knocked me over. It saved me from writing another one.  ;)  In the new website, this file is linked to. We're not fixing master unless it's a P0, but thanks for reporting it!

**Comment by fluttercorner** [comment]
[How to Create SideBar Menu In Flutter](https://fluttercorner.com/how-to-create-sidebar-menu-in-flutter/)
