### ISSUE TITLE
Make dash the default branch

### ISSUE THREAD

**Issue by chalin** [flutter/website#1228]
cc @Sfshaza @fertolg

**Comment by mit-mit** [comment]
Sorry, I'm not sure what this is asking for

**Comment by chalin** [comment]
I believe that @Sfshaza now has the rights to do this, so we'll address it, thanks.

**Comment by Sfshaza** [comment]
Done.

**Comment by chalin** [comment]
Thanks.

You'll want to keep `master` as a protected branch. Can you reinstate that?

**Comment by Sfshaza** [comment]
Master is protected.
