### ISSUE TITLE
"Get the Flutter SDK" MacOS Link Failed

### ISSUE THREAD

**Issue by AskYous** [flutter/website#1241]
Page: https://flutter.io/setup-macos/

This link goes nowhere:

![image](https://user-images.githubusercontent.com/791996/45187448-80b87700-b1e5-11e8-80ec-9ef7fe3ec007.png)

**Comment by AskYous** [comment]
SDK Archive page:
![image](https://user-images.githubusercontent.com/791996/45187508-bf4e3180-b1e5-11e8-8518-302c5de8f5b7.png)

**Comment by chalin** [comment]
It may likely have been a temporary issue; It seems to be working now, at least for me:

> <img width="306" alt="screen shot 2018-09-06 at 20 32 25" src="https://user-images.githubusercontent.com/4140793/45192004-005d3a80-b214-11e8-8ac5-1c6c91992955.png">

**Comment by AskYous** [comment]
Works for me now. Thanks.
