### ISSUE TITLE
Building Layouts in Flutter: duplicate "Row with 3 children" image

### ISSUE THREAD

**Issue by darrencole** [flutter/website#1250]
From URL: https://flutter.io/tutorials/layout/

Good Day,
In step 1, the image of the Title Section is repeated for no apparent reason. Perhaps this was an oversight.
Regards,

**Comment by chalin** [comment]
Thanks for pointing that out. The source of the problem is that https://flutter.io/tutorials/layout/images/lakes-diagram.png contains essentially two images. My guess is that it shouldn't, but I'll let @Sfshaza confirm whether this was intentional or not.

**Comment by Sfshaza** [comment]
Definitely not intentional. I (or someone) needs to crop that image.  :)

**Comment by chalin** [comment]
Reassigning to self, given that I'm editing this same image for another issue.
