### ISSUE TITLE
Building Layouts in Flutter: code in step 5 doesn't match actual starter app 

### ISSUE THREAD

**Issue by darrencole** [flutter/website#1252]
From URL: https://flutter.io/tutorials/layout/

Hi,
Perhaps the demo app generated by Android Studio has changed since this codelab was written but step 5 could be a bit confusing for a novice developer unless he/ she checks the final code in the GitHub link. The code in the demo app (generated by Android Studio) doesn't line up with what is being shown in step 5.
Regards,

**Comment by Sfshaza** [comment]
That's an Oops. Thx!

**Comment by JosephineAkello** [comment]
I second @darrencole for this opinion, step 5 would be so challenging to a novice and the idea of nesting widgets would also be tricky for a first time Flutterer.

**Comment by micpap25** [comment]
Hi, it looks like Step 5 was removed. I think this can be closed safely.

**Comment by amanv8060** [comment]
@chalin this could be closed

**Comment by MrBirb** [comment]
@Sfshaza Step 5 was indeed removed. Nothing can be done here.

**Comment by MiraMarshall** [comment]
Closed. The issue has been fixed, there is no Step 5.
