### ISSUE TITLE
Issue from website page JSON and serialization

### ISSUE THREAD

**Issue by GiulioIzzo** [flutter/website#1255]
From URL: https://flutter.io/json/

Hello,
I admit, I'm a little noob, but I was following this guide and, in the end, intellij complains about `_$UserSerializerMixin` (its complains are: Classes can only mixin other classes/ Undefined class '_$UserSerializerMixin'). So I went in the **user.g.dart** file generated using the ` flutter packages pub run build_runner watch` command and I've not found any  `_$UserSerializerMixin`. So did the library changed and I don't need `_$UserSerializerMixin` anymore  or should I implement it manually in user.g.dart file?

**Comment by Sfshaza** [comment]
Could you take a look, @RedBrogdon?

**Comment by RedBrogdon** [comment]
Ooh, yeah, this snippet looks to be using the pre-1.0 version on `json_serializable`. There's a new one that was released a week or two ago that uses a different method of wiring the generated code into the original class:

https://pub.dartlang.org/packages/json_serializable#-changelog-tab-

You can see an example of the new approach here:

https://github.com/flutter/samples/blob/master/jsonexample/lib/json_serializable/serializable_simple_object.dart

There's no mixin involved.

**Comment by kevmoo** [comment]
@RedBrogdon @Sfshaza – we know have 4 reports of folks stumbling on this. Need to get the site fixed!

**Comment by Sfshaza** [comment]
Since we are close to launching the new website, we aren't fixing non P0 bugs. @RedBrogdon, can you possibly create a PR for the dash branch?  Or give me the text that needs fixing and I'll do it?  Thx

**Comment by kevmoo** [comment]
@Sfshaza @chalin – I'm looking to fix this. Should I send a PR to `dash` or `master` branch?

**Comment by chalin** [comment]
The `dash` branch.

**Comment by chalin** [comment]
Hmm, given that folks (rightly) keep opening issues over this, maybe it should be fixed on master too? @kevmoo WDYT?

**Comment by kevmoo** [comment]
I support cherry-picking into master!
