### ISSUE TITLE
[dash] Navbar and sidebar styling followup

### ISSUE THREAD

**Issue by chalin** [flutter/website#1269]
From https://github.com/flutter/website/pull/1267#issuecomment-420776252:

- [x] The main nav:
  - [x] Font size seems a bit small.
  - [x] Hamburger seems a bit small.
- [x] Sidenav:
  - [x] There is some strange subitem text overlap during the transition of the sidenav entry opening up. Have you noticed that?
  - [x] The caret overlaps with the text.
  - [x] The side nav is always showing at the top of the page on narrow displays. (I suppose that is temporary)?
- [x] The page GH buttons aren't formatted yet (so I suspect that you didn't have time to address those in this round -- which is fine, I just wanted to mention it).

**Comment by fertolg** [comment]
I think this issue can be closed now, the nav has gone through several iterations since this PR was merged and all the points mentioned here have been addressed already.
