### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#1273]
We should have a file for people who want to contribute to the docs. It might cover docs.flutter.io, as well (or at least refer to info about contributing to the API docs).

Here's an example flutter/website might copy: https://github.com/dart-lang/site-www/blob/master/CONTRIBUTING.md.

Other related files:
* https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md
* https://github.com/flutter/flutter/blob/master/README.md (because it serves as the docs.flutter.io homepage)

**Comment by sfshaza2** [comment]
Done. PR https://github.com/flutter/website/pull/1605
