### ISSUE TITLE
Answer to "Who uses Flutter?" question in FAQ should link to Showcase page

### ISSUE THREAD

**Issue by alanrussian** [flutter/website#1277]
The answer to ["Who uses Flutter?" in the FAQ](https://flutter.io/faq/#who-uses-flutter) is out of date. The [Showcase](https://flutter.io/showcase/) page seems to contain a more updated list of production Flutter apps.

**Comment by Sfshaza** [comment]
I just checked and the faq does have a link to the showcase. Closing.

**Comment by alanrussian** [comment]
It does, but "Who uses Flutter?" does not. I think that if someone looks up "Who uses Flutter?", they would be very interested in sample apps.

**Comment by Sfshaza** [comment]
You must be looking at master, which is frozen. The dash branch *does* have a link to the showcase from "Who uses Flutter" in the faq. We aren't touching master unless it's a P0. Closing.

**Comment by alanrussian** [comment]
I was just looking at the public site. I'm guessing that's master. Thanks for the clarification!

**Comment by Sfshaza** [comment]
Yes, that's master. Thx!
