### ISSUE TITLE
Usage of Websocket, STOMP in flutter application

### ISSUE THREAD

**Issue by srivanigorthi** [flutter/website#1289]
While trying to work with STOMP, websockets, facing issue for "packages get" after updating pubspec with required stomp/websocket details. I have tried for stomp, stompdart, websocket none of them worked.
Error observed while running "packages get" is 
"The current Dart SDK version is 2.1.0-dev.4.0.flutter-4eb879133a.

Because project_name depends on stompdart >=0.0.2 which requires SDK version >=1.5.0 <2.0.0, version solving failed.
pub upgrade failed (1)"

If I try to downgrade flutter version then it has thrown exception informing 'current project needs SDK version > 2.0.0

Please help to clear the issue or suggest some other way as I am using STOMP at server end.

**Comment by Sfshaza** [comment]
Hi, @srivanigorthi! Did you figure out how to resolve this?

**Comment by srivanigorthi** [comment]
@Sfshaza No. Do you have idea to resolve this ? Or do you have any idea how to connect to websockets from flutter(flutter acts as client, spring application acts as server)  to get broadcasted messages from server

**Comment by srivanigorthi** [comment]
@Sfshaza No. I am still working on it to clear the issue. Do you have idea to clear the issue? Do you have any idea how to connect from flutter(acting as client) to spring websockets ( acting as server) to receive the messages broadcasted from server?

**Comment by srivanigorthi** [comment]
@Sfshaza .. No, My issue is not yet cleared.Do you have idea to clear the issue? Do you have any idea how to connect from flutter(acting as client) to spring websockets ( acting as server) to receive the messages broadcasted from server?

**Comment by srivanigorthi** [comment]
@Sfshaza .. No, My issue is not yet cleared.Do you have idea to clear the issue? Do you have any idea how to connect from flutter(acting as client) to spring websockets ( acting as server) to receive the messages broadcasted from server?

**Comment by smm13344331** [comment]
> @Sfshaza No. Do you have idea to resolve this ? Or do you have any idea how to connect to websockets from flutter(flutter acts as client, spring application acts as server) to get broadcasted messages from server

I have exactly the same issue, did you make this work?

**Comment by sfshaza2** [comment]
@srivanigorthi, did you try this solution? https://stackoverflow.com/questions/52440301/usage-of-websocket-stomp-in-flutter-application

Also, I found this video, which might be helpful:  https://www.youtube.com/watch?v=69Ul8bAahQY

**Comment by atsansone** [comment]
This is a support question. No doc request has been made. It references very old versions of Dart and Flutter. Closing this issue.
