### ISSUE TITLE
Set $PATH Instructions show Security Vulnerability

### ISSUE THREAD

**Issue by MggMuggins** [flutter/website#1295]
I'm talking specifically about [this page](https://flutter.io/setup-linux/#update-your-path), I noticed that it instructs users to do this in their `~/.bash_profile`:
```sh
export PATH=[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin:$PATH
```
This is VERY BAD. In linux, `execv` (the syscall that executes an executable) first checks if the file that the user passed to it exists, and if it is not, then goes through the user's `$PATH` _in order_, looking for a binary by that name (I'm sure this is optimized, but this is effectively what happens).

As shown by the website, the flutter bins path is put _in front_ of the existing `$PATH`. Some implications of doing this:
A program could plop an executable in the flutter bins called `sudo`, which could imitate sudo, store the user's password in plaintext, and execute `/bin/sudo` behind the scenes, all while the user is completely unaware. 

In any case, this should be changed to:
```sh
export PATH=$PATH:[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin
```
Any other cases should receive the same treatment.

**Comment by Adityanandsingh** [comment]
Type: export PATH=$PWD/flutter/bin:$PATH 
This will  add  flutter tool to your path

**Comment by Sfshaza** [comment]
Thanks for the heads up, @MggMuggins. I've fixed this in the new branch of the website.

**Comment by MggMuggins** [comment]
I appreciate that, thanks!

**Comment by MggMuggins** [comment]
I appreciate that, thanks!
