### ISSUE TITLE
[dash] Drop `/get-started` page which has no active links into it

### ISSUE THREAD

**Issue by chalin** [flutter/website#1299]
The https://flutter.io/get-started/ **page isn't linked from anywhere on the site**. In particular, you can't get to it using the sidenav.

This is what the page currently contains:

> Welcome to the Flutter Get Started Experience. We will help you:
> 
> * Install the Flutter framework
> * Install the dependencies of the Flutter framework
> * Create, run, and make changes to your first Flutter app
> * Learn core Flutter concepts through a small step-by-step lesson
> * Suggest some next steps
> 
> ## Next step
> 
> [Next step: Install Flutter](/get-started/install/)

So essentially, this page is just a manually created TOC for the other Get Started pages.

I'd suggest that we drop this page. Any objections?

cc @fertolg

**Comment by Sfshaza** [comment]
Well, yes, I object. I don't want the src directory to contain many markdown files. I prefer a cleaner directory structure. 

What are you suggesting, exactly?

**Comment by filiph** [comment]
I understand this is just about deleting `website/src/get-started/index.md` and adding a redirect rule that takes people directly to https://flutter.io/get-started/install/ (when they try to access https://flutter.io/get-started). Correct?

I'd be okay with this.

**Comment by chalin** [comment]
Correct. Shams, is that ok with you?

**Comment by chalin** [comment]
No, sorry if that was unclear. Not the directory, just the page that doesn't appear to be used (and isn't even linked to from the sidenav).

**Comment by Sfshaza** [comment]
Oh, then that's fine.
