### ISSUE TITLE
[dash] Replace temporary Rouge highlighting CSS with GH CSS

### ISSUE THREAD

**Issue by chalin** [flutter/website#1316]
Related:
- https://github.com/dart-lang/pub-dartlang-dart/issues/871
- https://github.com/primer/primer/tree/master/modules/primer-markdown
- #1312

**Comment by atsansone** [comment]
Appears to have been resolved with:
https://github.com/dart-lang/site-shared/pull/107
https://github.com/dart-lang/site-shared/commit/dbf83e10fe3d60d102def1bdf987dcd140c7d9db
https://github.com/dart-lang/site-shared/commit/8f783bfa10019afb023d4917f9cd8e614227bd3d
https://github.com/dart-lang/site-shared/commit/a9b4ae7a4ee2090bcc67944afdca0cb240d617e4

See [code](https://github.com/dart-lang/site-shared/blob/main/src/_assets/css/_code_shared.scss#L34-L86).

Closing.
