### ISSUE TITLE
[dash] Integrate cheatsheets into site

### ISSUE THREAD

**Issue by chalin** [flutter/website#1317]
The site has two cheatsheets (`Flutter-IntelliJ-cheat-sheet-MacOS.pdf` and `Flutter-IntelliJ-cheat-sheet-WindowsLinux.pdf`), both as PDFs. It would be better to integrate these as (markup/markdown) pages in the site. That would make it easer to keep them up-to-date (by us or the community).

cc @Sfshaza @filiph @fertolg

**Comment by Sfshaza** [comment]
Good point. I wonder where these came from.

**Comment by Sfshaza** [comment]
@Hixie,  @jwren, Do we have the source for these PDF files? Where did they come from? Keeping them up to date will be tricky if we don't have the source.

**Comment by Hixie** [comment]
No idea. Check the git history?

**Comment by chalin** [comment]
The PDFs were last updated 2 years ago by @mit-mit via #494. They were first added by @mit-mit via #428. No sources are mentioned in those PRs. Maybe @mit-mit has the sources?

**Comment by jwren** [comment]
Not sure what the history context is here.  @devoncarew 
Having them as PDFs do make it easier to print.

**Comment by mit-mit** [comment]
Yes, I have the source for these (as Google Docs), and I'm happy to share them with anyone interested in porting them to markdown

**Comment by chalin** [comment]
Could you share it with Shams and me?

**Comment by mit-mit** [comment]
Certainly, done!

**Comment by chalin** [comment]
Thanks!

**Comment by homerstrong** [comment]
Always use help

**Comment by sfshaza2** [comment]
I decided to go another way. It would be an involved and thankless task to convert this Google Doc to markdown. Instead, I copied the two Doc files to our shared team drive under "Documentation." These docs will always be available to the team.

@mit-mit 

Closing.
