### ISSUE TITLE
Issue from website page Developing Flutter apps in an IDE - VS Code

### ISSUE THREAD

**Issue by mattkj** [flutter/website#1321]
The assists shortcut listed for VS Code is incorrect. Should be `Ctrl` + `.` instead of `Ctrl` + `Enter`.

From URL: https://flutter.io/using-ide-vscode/

**Comment by Sfshaza** [comment]
@chalin, the current page on the new branch doesn't include all of the text of the original. This text is missing, for example. (I went to correct it.)
