### ISSUE TITLE
[dash] Add support for page navigation via previous-page, next-page links.

### ISSUE THREAD

**Issue by chalin** [flutter/website#1322]
Add support for page navigation (when a collection of pages are related), via previous-page, next-page links. On site-www and -webdev we have previous/next-page links at the top and bottom of pages, something like this:

> <img width="403" alt="screen shot 2018-09-26 at 15 24 24" src="https://user-images.githubusercontent.com/4140793/46104078-6ea47580-c1a0-11e8-92c2-f157de3d18e3.png">

On webdev, we also have support for (auto-)eliding of headings on narrow displays:

> <img width="428" alt="screen shot 2018-09-26 at 15 25 21" src="https://user-images.githubusercontent.com/4140793/46104115-8aa81700-c1a0-11e8-9b23-cb58efae90d7.png">

**Comment by Sfshaza** [comment]
I could use this immediately in the cookbook.  @brianegan

**Comment by chalin** [comment]
Also as mentioned during our meeting, we'd like to improve on the www/webdev implementation so that we don't have to repeat page titles across pages, but rather just identify page sequences and have Jekyll weave the prev/next links.

**Comment by chalin** [comment]
Prev/next would be useful for the Get Started pages.
