### ISSUE TITLE
[dash] Consider computing the current flutter bundle version at site compile time

### ISSUE THREAD

**Issue by chalin** [flutter/website#1324]
As discussed during the 2018-09-26 standup, we'd like to generate the current flutter bundle file path (e.g. https://storage.googleapis.com/flutter_infra/releases/beta/linux/flutter_linux_v0.8.2-beta.tar.xz) when Jekyll builds the site, rather than use JS. The site is updated regularly (whenever we merge a PR or push to master), and a cron job runs every day, so the statically-generated path should be fresh enough while avoiding unnecessary use of JS.

**Comment by parlough** [comment]
Since this has sat for 5 years without further interest, I think I'll close it. The JS has been updated to be simpler and we use the JS to replace the filenames depending on what a user clicks, so we'll need some anyway for now. 

If anyone feels strongly about this, I'm happy to reopen. Thanks!
