### ISSUE TITLE
Issue from website page Handling changes to a text field

### ISSUE THREAD

**Issue by haarts** [flutter/website#1336]
From URL: https://flutter.io/cookbook/forms/text-field-changes/

In the section 'Listen to the controller for changes' the method `dispose` is overridden. In it there's an explicit call to the `myController.removeListener` method. This call is redundant as the subsequent `myController.dispose()` removes all listeners. I understand that you might want write this for clarity in a tutorial but I would consider it cargo culting in production code at best. A small comment would clarify this.

**Comment by brianegan** [comment]
Fair point. I'll put up a PR against the new site!
