### ISSUE TITLE
[dash] Placement of page TOC?

### ISSUE THREAD

**Issue by chalin** [flutter/website#1337]
Any preference as to the positioning of the autogenerated TOC?

The mock page illustrated below has two inlined TOCs:

1. The top-most TOC is the one from the (default dash) page layout/template; it always appears immediately after the title (you can ignore the "Contents" entry, that appears because of the 2nd TOC).
2. The second TOC illustrates a typical in-page placement as used in the current site mater; it is manually positioned in the page using special syntax.

<img width="1070" alt="screen shot 2018-09-27 at 09 32 15" src="https://user-images.githubusercontent.com/4140793/46151924-dc52af00-c23d-11e8-9215-bad84429259a.png">

Option (1) is simple, already implemented, has the advantage of being uniformly applied, and being a bit easier to maintain than in-page TOCs. (2) can be implemented with a bit of extra Liquid programming. Let me know what you prefer.

cc @fertolg

**Comment by Sfshaza** [comment]
I'm ok with (1), where the TOC is at the top on narrow windows.
