### ISSUE TITLE
Technical Overview page has a diagram claiming that Material widgets are built on top of Cupertino widgets

### ISSUE THREAD

**Issue by jamesderlin** [flutter/website#1340]
https://flutter.io/technical-overview/ has this diagram: https://flutter.io/images/whatisflutter/diagram-layercake.svg

This diagram implies that Material widgets are built upon Cupertino widgets.  What?

[A similar diagram](https://raw.githubusercontent.com/flutter/engine/master/docs/flutter_overview.svg?sanitize=true) from the [Flutter engine wiki page](https://github.com/flutter/engine/wiki) looks correct.

**Comment by Sfshaza** [comment]
@jamesderlin , thanks for reporting this! I've fixed this on the new branch of the website, as we're not fixing issues on the current site.
