### ISSUE TITLE
Cleanup markdown headings and learn callout

### ISSUE THREAD

**Issue by chalin** [flutter/website#1342]
- [ ] "What's up?" / "What you’ll learn" should use `{{site.alert.secondary}} <h4 class="no_toc">What you’ll learn</h4> ... {{site.alert.end}}
- [ ] Headings with `<a id="...">` -> Kramdown `{#...}`
- [ ] There should be no headings of level 1.

**Comment by micpap25** [comment]
Working on this right now.

**Comment by parlough** [comment]
1. Verified that similar text is using secondary.
2. We make sure to use this for new headers.
3. Verified there are no extra `<h1>` headers.
