### ISSUE TITLE
IOWebSocketChannel documentation enhancement for SSL/TLS use  case

### ISSUE THREAD

**Issue by dimon777** [flutter/website#1346]
Proposing to expand
https://flutter.io/cookbook/networking/web-sockets/
with the SSL/TLS use case. It is unclear now how to use secured WebSockets: wss://

**Comment by brianegan** [comment]
I'm open to the idea of adding this, but I wonder if this is the type of thing that would be better documented on the WebSocketChannel library directly? I was hoping this recipe would point peeps in the right direction, but I don't know if it's a good idea to cover every possible use-case and then need to keep all of those recipes up-to-date with the original library.
