### ISSUE TITLE
Get Started pages: automate resync of next/prev link titles and paths

### ISSUE THREAD

**Issue by chalin** [flutter/website#1354]
Followup to #1322

**Comment by chalin** [comment]
A dart script was added via #2218. It could be generalized to support the Get Started pages (though it will be a little trickier to figure out the intended page ordering). Maybe we would limit the resync to the titles for these pages.

**Comment by parlough** [comment]
We rarely update the Get Started flow and it's not super clear an automatic order could be chosen. I think it's not worth spending the time on this for now.
