### ISSUE TITLE
Issue from website page Writing custom platform-specific code with platform channels

### ISSUE THREAD

**Issue by emmanuelchucks** [flutter/website#1356]
From URL: https://flutter.io/platform-channels/

This webpage is not displaying properly on Chrome for Android on my phone. The left part of the page cuts out one or two characters of the first word on each line.

**Comment by Sfshaza** [comment]
Not sure exactly, @emmanuelchucks, but hopefully well before end of year.

**Comment by Sfshaza** [comment]
Since this is fixed on the new website, closing.
