### ISSUE TITLE
[dash] Get started: simplify titles and add breadcrumbs

### ISSUE THREAD

**Issue by chalin** [flutter/website#1369]
- [x] Simplify **Get started** page titles: drop "Get started" prefix - #1372
- [x] Add breadcrumbs - #1391

---

Some of the **Get started** pages have compound titles like:

- [Get Started: Configure Editor](https://flutter-io-staging-1.firebaseapp.com/get-started/editor)
- "Get Started: Install"
- "Get Started: Learn More", ...

Note that **we omit the "Get Started" prefix** from the link text in the **sidenav** and the **next/prev** buttons. Can we drop the "Get Started" prefix from the page titles too? On wide displays the sidenav provides the necessary context.

Maybe on narrow displays (and possibly wide displays too, though that may make the page look too busy) we could implement breadcrumbs. It isn't clear what the result will be given that we also have next/prev buttons at the top of the page.

Thoughts?

---

Here is what [breadcrumbs look like on site-www](https://www.dartlang.org/tools/pub/cmd/pub-run):

<img width="620" alt="screen shot 2018-09-27 at 14 50 21" src="https://user-images.githubusercontent.com/4140793/46167784-b987c100-c264-11e8-894f-25d33b4fa37d.png">

**Comment by Sfshaza** [comment]
Yes, let's simplify Get Started menus and YES, let's add optional breadcrumbs!

Also good for the cookbook.
