### ISSUE TITLE
Add next/prev links to cookbook pages

### ISSUE THREAD

**Issue by chalin** [flutter/website#1370]
@Sfshaza is the order of the entries in the Cookbook significant? If they were presented in alphabetical order would that be ok? /cc @filiph

**Comment by Sfshaza** [comment]
Are you talking about alphabetizing the sections themselves, and then the entries within the sections? That might not be optimal.

@brianegan, what do you think?

**Comment by chalin** [comment]
> Are you talking about alphabetizing the sections themselves, and then the entries within the sections? 

Right: I'm asking if it would be ok to alphabetically sort:

- Groups (like "Design basics", "Images") based on the group title
- Group items within a group, based on the item titles

**Comment by brianegan** [comment]
Hey there -- sorry, somehow missed this notification!

  > That might not be optimal.

Agreed.

In general, I try to keep each recipe independent of the others, but that doesn't work for all topics, such as Forms and Testing. In those cases, I present the recipes in a specific order. 

I think it would be better for users if the articles could appear in such a curated order, rather than in a forced Alphabetical order.

**Comment by brianegan** [comment]
Hrm, it's a good question. 

I've generally tried to order those from "Basics" to "More Advanced," e.g. "Design Basics" comes before "Testing" -- and I think that makes good sense :) But as you said -- lists vs Animations? That ordering is quite subjective.

**Comment by chalin** [comment]
> e.g. "Design Basics" comes before "Testing" 

That respects an alphabetical ordering :). Btw, here are the topics in alphabetical order:

- Animation
- Design
- Forms
- Gestures
- Images
- Lists
- Maintenance
- Navigation
- Networking
- Persistence
- Testing

> But as you said -- lists vs Animations? That ordering is quite subjective.

There are a lot of recipes (and more are likely to come) so I'm exploring schemes for the autogeneration of next/prev links between recipes -- I'd like to avoid having to manually setup (and then maintain) such next/prev links.

Let's see if we can find a win-win solution concerning the ordering of recipe groups (we'll address intra-group recipe ordering afterwards).

The cookbook's opening paragraph reads (emphasis mine):

> This cookbook contains recipes that demonstrate how to solve common problems while writing Flutter apps. **Each recipe is self-contained** and can be used as a reference to help you build up an app.

IMHO this supports the most common use case of a cookbook: search for keywords (e.g., "sockets") and look at the article hits (which reminds me that we could implement a dynamic filter for the cookbook TOC -- like the [API filter we have for webdev](https://webdev.dartlang.org/api) -- but that's a topic for another thread).

Is the alphabetical order of topics given above acceptable? 

With the next/prev autogeneration scheme I have in mind, I could accommodate one-off ordering, but I'd like to avoid imposing an arbitrary order on _all_ recipe groups when that ordering isn't in support of the main cookbook use case. 

One solution is to go with the alphabetical order of groups, but to add a note after the opening paragraph suggesting a particular ordering for readers who do want to walk through the cookbook: e.g., "If you are browsing through the Cookbook, we suggest starting with "Design" recipes." 

Thoughts?

**Comment by brianegan** [comment]
> That respects an alphabetical ordering :)

  > Is the alphabetical order of topics given above acceptable?

Haha, sure -- it was just an example to demonstrate a case where curated ordering can be handy. Overall, the list you've shown looks good to me. My original point: I can imagine a world in which the curated ordering and alphabetical ordering don't line up, but maybe we shouldn't worry about it :) Would love to hear @Sfshaza thoughts, since I it feels like a cost / benefit analysis: comparing the benefit to users of curated ordering vs the maintenance costs of such a decision.

  > This cookbook contains recipes that demonstrate how to solve common problems while writing Flutter apps. Each recipe is self-contained and can be used as a reference to help you build up an app.

That's a funny one -- I almost wonder if we should change that language a bit. Now that I've written a lot more content, I've found that it makes sense for recipes to reference one another to keep each recipe focused on the topic at hand. E.g. I didn't want to introduce how to create ListViews in a Recipe for "Swipe to Dismiss." In many ways, they're still self-contained since they focus on a specific topic, but if you're missing some basics you might need to read a related recipe.

Overall, I'm fine with the alphabetical ordering of groups, but happy to hear other thoughts just to make sure I'm not forgetting anything!

**Comment by Sfshaza** [comment]
I am also fine with alphabetic ordering for lists, but I think that, within
a list, the topics should be ordered with intention.

So, I agree with Brian.  :D

**Comment by chalin** [comment]
Now, let's discuss **recipe order within a group**.

I believe that the same points apply here as well. Order is unimportant: as we just discussed, a reader can start from any given recipe because each recipe is self-contained and, when necessary, the reader is given references to other resources (including recipes).

@brianegan: thoughts?

**Comment by brianegan** [comment]
Hrm, I get what you're saying. From a logical perspective, your assumption and conclusion make sense, but I do think it will result in some sections that "feel" out of order. 

E.g. in Widget testing, "Finding Widgets in a Widget Test" will come before "Introduction to Widget testing."

Again, I'm not sure what the cost of maintaining that kind curation would be, but I think it would read more naturally.

**Comment by chalin** [comment]
I'm trying to identify how many recipes _actually_ need to be presented in a specific order. Let's take it case by case.

For the Testing recipes. IMHO, "Introduction to ..." isn't the name of a recipe. Maybe it should be "Basics" -- remember that this recipe would be found under  **Cookbook > Testing > Widget tests > Basics**. (Similarly for unit and integration test "intro" pages.) How about that?

**Comment by brianegan** [comment]
> I'm trying to identify how many recipes actually need to be presented in a specific order. Let's take it case by case.

Sections where I think curated ordering makes more sense:

  1. Lists
  2. Images
  2. Handling Gestures
  3. Navigation
  4. Testing

In some of these cases, alphabetical ordering will be fine. In other cases, it will result in what I would subjectively call an "oddly ordered list," placing introductory material after advanced material.

  > For the Testing recipes. IMHO, "Introduction to ..." isn't the name of a recipe. Maybe it should be "Basics" -- remember that this recipe would be found under Cookbook > Testing > Widget tests > Basics. (Similarly for unit and integration test "intro" pages.) How about that?

I'm fine with that particular change, but I don't know if we can apply that same trick to all sections. 

Would it be possible to have a simple "weighting" mechanism? E.g. Sort alphabetically, then move pages with specific weights to the correct position. If two pages have the same weight, sort those two alphabetically.

That might be an easy way to apply Alphabetical by default, but allow for some curation without too much maintenance.

**Comment by chalin** [comment]
> I'm fine with that particular change,

Ok, good.

> but I don't know if we can apply that same trick to all sections.

Agreed.

> Would it be possible to ... Sort alphabetically, then move pages ... to the correct position.

Yes, that is what I had in mind -- though not using a weight.

> That might be an easy way to apply Alphabetical by default, but allow for some curation without too much maintenance.

Agreed! Ok, I'll do that, and then you can chime in when comes time to tweak the ordering. How does that sound?

**Comment by brianegan** [comment]
I dig it. Let me know when you'd like me to change that up!
