### ISSUE TITLE
Issue from website page Fetch data from the internet

### ISSUE THREAD

**Issue by DanTup** [flutter/website#1381]
From URL: https://flutter.io/cookbook/networking/fetch-data/

I *think* this example is incorrectly creating futures from inside its build method (it calls `fetchPost` from inside the build method). The docs for FutureBuilder say the future "must not be created during the State.build or StatelessWidget.build method call".

(cc @brianegan)

**Comment by brianegan** [comment]
Yep, I was trying to save too many characters and demonstrated a bad practice 📦 

Fixed here against the new website: https://github.com/flutter/website/pull/1311#event-1866393732

**Comment by DanTup** [comment]
Aha, thanks! Is there a preview of that site anywhere? (I think someone is doing this in an issue I'm CC'd on, so directing them to the new info may help them).

**Comment by brianegan** [comment]
Hrm, some PRs build a staging version of the site to make things easier for the reviewers, but I've only been following the instructions in the README and been building it locally :/

I'd have to defer to @Sfshaza if there's a stable staging URL folks can check out.

**Comment by DanTup** [comment]
It's not a big deal if not - if this is the user the person is having I can describe in text and point them at this PR; it just would've been convenient if there was one. Thanks!
