### ISSUE TITLE
broken link in Technical Overview

### ISSUE THREAD

**Issue by Twinber** [flutter/website#1388]
in "For an example of managing state, see the MyApp template that’s created with each new Flutter project."

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/create/lib/main.dart.tmpl
return 404

**Comment by Twinber** [comment]
@Sfshaza @chalin 
Please
Can you tell me what would be the correct link?
We need it for flutter-es.io travis build

**Comment by chalin** [comment]
Closed by #1411

**Comment by chalin** [comment]
Our master build is green again: https://travis-ci.org/flutter/website/builds/439029977. If if you pickup the latest from master, that should do the trick for you too.
