### ISSUE TITLE
[dash] Style breadcrumbs

### ISSUE THREAD

**Issue by chalin** [flutter/website#1392]
Breadcrumbs support has been added. They currently use the default BS styling and look like this:

> <img width="1088" alt="screen shot 2018-10-05 at 10 58 16" src="https://user-images.githubusercontent.com/4140793/46543078-fe77ad00-c88d-11e8-8f0b-6fc80be3bdfa.png">

We'll probably want something more discrete like the styling used on site-www:

> <img width="802" alt="screen shot 2018-10-05 at 11 25 50" src="https://user-images.githubusercontent.com/4140793/46544407-7a272900-c891-11e8-9f53-e71afd06a236.png">

Notice the use of the chevron as separator, and that the crumb for the current page is in gray.

cc @Sfshaza

**Comment by fertolg** [comment]
This was addressed in #1453
