### ISSUE TITLE
[dash] Flutter SDK Archive doesn't appear in sidenav

### ISSUE THREAD

**Issue by chalin** [flutter/website#1397]
The current **Flutter SDK Archive** page is here: https://flutter.io/sdk-archive/

Under dash, it is here: https://flutter-io-staging-1.firebaseapp.com/development/tools/sdk/archive

But there is no "SDK" entry (let alone "SDK > Archive") under **Development > Tools**. Should extra entries be added?

cc @filiph @fertolg

**Comment by Sfshaza** [comment]
Yes, I think having it under Dev -> Tools makes a lot of sense.

**Comment by chalin** [comment]
Which of the following:

- Development
  - Tools
    - SDK Archive

Or


- Development
  - Tools
    - SDK
      - Archive

If the latter, then we need to figure what content will be shown for the SDK page.

**Comment by Sfshaza** [comment]
I think the former. We don't need this to be deeper than necessary. Unless, of course, we want a Tools > SDK page, but we have that for www.dartlang.

**Comment by galeyang** [comment]
I didn't have a clear idea about the version management at this point. @InMatrix Do you have any ideas about this?

**Comment by InMatrix** [comment]
The current SDK Archive is linked out of the installation page for each platform, e.g., https://flutter.io/setup-macos/

I think the SDK Archive belongs to the Installation user journey, so it should stay there as it is.

**Comment by chalin** [comment]
> The current SDK Archive is linked out of the installation page

Right, but the issue being discussed here is: where should the **SDK archive** page appear in the sidenav.

> ... so it should stay there as it is

There is no **SDK archive** entry in the IA atm. If you are proposing that it be added to the **Get started** entry group, then where exactly?

cc @filiph

**Comment by Sfshaza** [comment]
I'd propose Development -> Tools

**Comment by InMatrix** [comment]
I'm not sure how important it is to add an entry for the SDK archive page in the left navigation. It's pretty rare that people would want to download an older version of Flutter. My suggestion is to do exactly what the current site does: providing a link to that page in the installation instructions but no entry in the left navigation.
