### ISSUE TITLE
[dash] left nav's default expand/collapse status

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1398]
- [x] From UX research, we suggested to expand the "Development" and "APIs & References" because these are frequent used sections - #1426

- [ ] Also we initially suggested to collapse all sub-menu items to avoid information overload. For example, when users expand the menu "Development", they will first see "User interface, Data & backend, Accessibility & Internationalization, etc" without expanding the sub entries.

**Comment by Sfshaza** [comment]
Ooooh, I like that! It currently expands everything - level 2 and level 3. This is a bit overwhelming.
