### ISSUE TITLE
[dash] Include Github and Community link on the top nav

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1400]
We suggest to put the Github and Community links back to the top nav. These two links are the top links that new users want to learn more about.

**Comment by chalin** [comment]
- The Community link is add via #1401.
- There is already a GitHub link on every page:

  <img width="788" alt="screen shot 2018-10-08 at 15 13 56" src="https://user-images.githubusercontent.com/4140793/46628810-dfd31980-cb0c-11e8-809e-49fd1b6f09ff.png">

  Do you still want a GitHub menu entry added to the main nav?

cc @Sfshaza @filiph

**Comment by chalin** [comment]
Oh, and I forgot to mention, every page footer already has a GitHub link:

> <img width="660" alt="screen shot 2018-10-08 at 15 17 33" src="https://user-images.githubusercontent.com/4140793/46628979-4f490900-cb0d-11e8-86ec-e4fb8d2d901e.png">

Do you still want it in the main nav as well?

**Comment by Sfshaza** [comment]
I am comfortable having the GitHub link NOT in the header. There is also one in the footer.

(Patrice just posted the same thing.) JINX!

**Comment by chalin** [comment]
I suppose that if we add it to the main nav, we can drop it from the footer, right?

**Comment by chalin** [comment]
Maybe we can hav the GitHub link in the main nav but only for the homepage, since every other page has the GitHub **Edit page** icon.

WDYT?

**Comment by Sfshaza** [comment]
The link of Octokitty on each page links to the source *for that page*. The link in the footer links to the Flutter repos on GitHub. A very different thing. Also, some ppl will likely search the page for "GitHub" and at least the footer will be found. Octokitty could be missed.

So, I prefer to have it in the header or footer (don't need both) in addition to the Octokitty icon. I slightly prefer the footer over the header.

HOWEVER, there was talk about having a CONTRIBUTE link in the header that would go to a page on how to contribute. That's a different thing.  :)

**Comment by chalin** [comment]
I've put something together, inspired by other sites. PTAL at #1407.

**Comment by galeyang** [comment]
**Short answer: yes, I think having a GitHub menu entry on the main nav is helpful.**

The GitHub link on every page links to flutter/website Github repository (not the actual Flutter repository) so the purpose for those links are different.

From the study, some developers (who are new to Flutter) didn't read through the entire landing page. They clicked on the Github link in the header because (1) some of them want to get passed the marketing content, (2) have a tendency to jump to the Github source code, and (3) want to evaluate the activeness of this toolkit by checking the frequency of commits and the date of last commit.

I'm less certain about the discoverability of putting the Github link in the footer, because none of the participants chose the footer links as the TOP interesting places to learn more. 

--
_Thanks for adding back the Community (previous Support) menu!_
