### ISSUE TITLE
[dash] Consider to add "What's New in Docs" on the Docs' landing page

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1402]
From UX research, returning website users/existing developers found it's easy to keep informed with new product features via blog posts or social media, but it's hard to know what's new or updated in the documentation on Flutter.io. 

Suggestion: consider to add "What's New in Docs" section on the Docs' landing page.

**Comment by chalin** [comment]
Where would you like that to appear? Before or after the cards that are currently at the top of the page?

**Comment by Sfshaza** [comment]
I'd want it below the cards. But this begs another question. Do we archive the history of changes? My guess it that we'd be expected to.

**Comment by chalin** [comment]
Also, what will the first entry(ies) be? Can someone provide prose (and links if there happens to be associated links)?

**Comment by Sfshaza** [comment]
I could do that. I'd start with a "Welcome to our new website!", and make it clear that we don't have entries before this site. I used to do this for the Java Tutorial all the time.  ;)

**Comment by Sfshaza** [comment]
Here's the page I used to edit for TJT:
https://docs.oracle.com/javase/tutorial/information/history.html

**Comment by chalin** [comment]
Ah, like the webdev [Changelog](https://webdev.dartlang.org/changelog)!

So is this issue about adding a Changelog page or only a few elements in the "What's new section" of the docs page (or both :).

**Comment by Sfshaza** [comment]
Right now, it's just for adding "What's new." I have a PR almost ready.

It's a bit different than the changelog, I think. It doesn't talk about changes to s/w per se, but only about changes to flutter.io.

**Comment by chalin** [comment]
An initial version landed via #1406
