### ISSUE TITLE
[dash] Enable external link checking

### ISSUE THREAD

**Issue by chalin** [flutter/website#1412]
Although we might want to wait for a fix to https://github.com/filiph/linkcheck/issues/27

cc @filiph

**Comment by chalin** [comment]
We might want to enable external link checking in the daily cron job only, so as to not slow down every PR build.

**Comment by Sfshaza** [comment]
Yes, please!

**Comment by sfshaza2** [comment]
If we had more time, I'd make this a P0.  ;)

**Comment by chalin** [comment]
@filiph - do you think that you'll have time to look into https://github.com/filiph/linkcheck/issues/27?

**Comment by filiph** [comment]
Please see https://github.com/filiph/linkcheck/issues/27#issuecomment-435655007

**Comment by chalin** [comment]
@filiph - could you also look into https://github.com/filiph/linkcheck/issues/29?

(Thanks for having looked into https://github.com/filiph/linkcheck/issues/27. I'm unsure why it was failing before but it working now.)
