### ISSUE TITLE
[dash] Keep GitHub and Twitter button in mobile main nav

### ISSUE THREAD

**Issue by chalin** [flutter/website#1416]
Currently the main nav looks like this:

> <img width="781" alt="screen shot 2018-10-09 at 09 28 30" src="https://user-images.githubusercontent.com/4140793/46673265-63d9df80-cba7-11e8-9792-05fcf9b67cc6.png">

And on mobile, the main nav looks like this:

> <img width="330" alt="screen shot 2018-10-09 at 09 37 25" src="https://user-images.githubusercontent.com/4140793/46673077-f928a400-cba6-11e8-8ca1-67d182002599.png">

I'd like to suggest that we keep the GitHub and Twitter buttons:

> <img width="338" alt="screen shot 2018-10-09 at 09 29 27" src="https://user-images.githubusercontent.com/4140793/46672913-a0f1a200-cba6-11e8-825a-750458b7554a.png">

We have the real estate, and keeping them there means that they don't need to be in the nav under the hamburger (they are now, but that is broken).

**Comment by galeyang** [comment]
The header mockup I got, especially the logo part, is longer (with "by Google"). If this is still the case, I'm not sure whether these two icons can fit in the remaining space.

![image](https://user-images.githubusercontent.com/5102864/46700793-a6fd7800-cbd2-11e8-824f-05c09185c91b.png)

**Comment by chalin** [comment]
Closed by some recent commits :)
