### ISSUE TITLE
Hint text in Search box is distracting

### ISSUE THREAD

**Issue by jamesderlin** [flutter/website#1422]
If I go to https://docs.flutter.io/ and start typing in the Search box, the search box apparently tries to autocomplete what I'm typing inline with banner text.  However, the positioning and size of the autocompleted text doesn't exactly align with the text I'm typing, so it ends up looking like a double-vision-like mess.  Personally I don't think we should bother autocompleting inline.

Chrome 69.0.3497.100 x64 on Linux:
![flutter-search-chrome](https://user-images.githubusercontent.com/17391434/46705956-d4542100-cbe6-11e8-8c22-9370ad02b126.png)

Firefox 62.0.3 x64 on Linux:
![flutter-search-firefox](https://user-images.githubusercontent.com/17391434/46705959-d6b67b00-cbe6-11e8-9c93-0b4b1bf9cdb5.png)

Chrome looks a little better, but they both look terrible.

**Comment by Sfshaza** [comment]
Hi, @jamesderlin! Can you re-file this issue on the flutter/flutter repo? It won't get fixed over here.

thx!
