### ISSUE TITLE
[dash][IA] Widget catalogue appears in two places

### ISSUE THREAD

**Issue by chalin** [flutter/website#1425]
In the current IA, the **Widget catalogue** appears in two places:

- Development
  - User interface
    - Widget catalog

and

- APIs & references
  - Widget catalog

Questions:

- [ ] Where (at which URL) should the page reside?
- [ ] When a user visits the **Widget catalogue** page, which of the two entries above do you want to be shown as active (and hence fully expanded)?

cc @filiph @Sfshaza @fertolg

**Comment by chalin** [comment]
Maybe the **Development > User interface > Widget catalog** entry should be dropped in favor of keeping it under **APIs & references > Widget catalog**?

**Comment by Sfshaza** [comment]
I agree with that suggestion, @chalin

**Comment by galeyang** [comment]
We intentionally display _Widget catalog_ in two places because of the study result. Is it possible to have one url (/development/ui/widgets) and keep the two places? That's, when a user visits either of them, it will highlight/expand its direct parent entry.

**Comment by galeyang** [comment]
Would it be possible to "save extra state to indicate which parent was intended"? Ideally, we'd suggest have an entrance in both places without losing the context (where a user click to visit this page).

**Comment by Sfshaza** [comment]
I agree with Patrice. To make it do the correct thing (saving the parent
info), is more work than this feature is worth. We almost never include a
link in two places, unless it's an external link. This isn't an issue with
an external link.

So, I agree with Patrice. The physical file belongs in resources.

**Comment by chalin** [comment]
How about this: leave the **Development > User interface > Widget catalog** where it is, but move the index so we get **APIs & references > Widget index**?

**Comment by galeyang** [comment]
> How about this: leave the **Development > User interface > Widget catalog** where it is, but move the index so we get **APIs & references > Widget index**?

Sounds like a good idea!
