### ISSUE TITLE
External links should be visually distinctive

### ISSUE THREAD

**Issue by chalin** [flutter/website#1428]
Www postfixes external links with an icon. For example, see https://www.dartlang.org/guides/libraries:

> <img width="419" alt="screen shot 2018-10-10 at 09 59 22" src="https://user-images.githubusercontent.com/4140793/46741564-496d3800-cc73-11e8-9ca7-9557852c04fc.png">

cc @filiph @fertolg

**Comment by galeyang** [comment]
Yes! I also noticed it but have not filed the issue. Can we open external links in a new tab (<a target="_blank") and add the same icon shown in your screenshot?

**Comment by chalin** [comment]
#1429 implements the "external link" icon for sidenav entries. PTAL

> Can we open external links in a new tab

Surely. In that case I'd suggest using `target="_blank" rel="noopener"`.

**Comment by Sfshaza** [comment]
Yes, I had noticed the lack of icons for external links (but hadn't filed either) and am glad to see them back!

**Comment by galeyang** [comment]
From the staged site, it seemed to be solved.

**Comment by chalin** [comment]
We have external-link icons for the navs only, not in-page links.

**Comment by sfshaza2** [comment]
Definitely fixed in the sidenav.
