### ISSUE TITLE
[dash] Styling followup for active main-nav entries

### ISSUE THREAD

**Issue by chalin** [flutter/website#1435]
From https://github.com/flutter/website/pull/1434#discussion_r224178372:

> make the "hover" and "active" design look like https://material.io/develop

**Comment by fertolg** [comment]
@chalin The mobile nav doesn't show the get started button because the button is not present in desktop. Should the button always be present in mobile? Currently the liquid template is set to add or remove the button markup entirely depending on the `show-nav-get-started-button` button property.

**Comment by chalin** [comment]
> Should the button always be present in mobile?

I guess that that is a question for stakeholders.

**Comment by Sfshaza** [comment]
I do not have strong feelings on this, but I do like the Get started button at the bottom of the docs page.  @maguinis, do you have a strong opinion?

**Comment by fertolg** [comment]
@chalin there were some updates last week while I was gone with regards to the Get Started button. It seems now on desktop the 'get started' button is shown on all pages. But in mobile it has disappeared completely from all pages, is this intentional? cc @sfshaza2

**Comment by sfshaza2** [comment]
It was intentional to add it to all pages on the web. I don't recall
talking about removing it from all pages on mobile, but that sounds like a
mistake.

**Comment by chalin** [comment]
> @chalin there were some updates last week while I was gone with regards to the Get Started button. It seems now on desktop the 'get started' button is shown on all pages. 

Right.

> But in mobile it has disappeared completely from all pages, is this intentional?

Sorry, I had meant to open an issue about that. I wasn't sure whether we still wanted the Get started button on mobile, and if so, where it should appear. Can you look into that @fertolg?
