### ISSUE TITLE
Issue from website page Working with WebSockets

### ISSUE THREAD

**Issue by harshaIOT** [flutter/website#1442]
From URL: https://flutter.io/cookbook/networking/web-sockets/

We can just connect to a server what if you want to fetch data from different channels. Say for suppose we have server and backend team to emit data or to add data into different channels in that server then we can only connect to server as per this example how to get connected to different channels...

**Comment by Sfshaza** [comment]
@brianegan

**Comment by brianegan** [comment]
Oh, interesting! I haven't had to handle this particular use-case myself, so I don't think I could offer the best advice. I've only created apps that talk to a couple different websocket servers myself :/
