### ISSUE TITLE
Identify featured case in showcases.yml file

### ISSUE THREAD

**Issue by chalin** [flutter/website#1443]
The objective is to avoid duplicating (and hard coding) data from `showcases.yml` in `src/showcase/index.md` by identifying the hero case.

Context: https://github.com/flutter/website/pull/1439#discussion_r224326789

**Comment by atsansone** [comment]
@kkboateng : Is this still an issue for the docs or for flutter.dev?

**Comment by parlough** [comment]
This issue is very specific to the old situation where marketing material was on this site. Now it's handling in the CMS which has functionality to feature stories.
