### ISSUE TITLE
[dash] Sidenav design: should "Development" and "APIs & References" be open by default?

### ISSUE THREAD

**Issue by chalin** [flutter/website#1452]
This is a followup to #1398. There is a feeling by members of the team that having "Development" and "APIs & References" be open by default just makes the site look broken. We should consider other solutions.

Thoughts?

cc @Sfshaza @fertolg @filiph

**Comment by Sfshaza** [comment]
It's better now that it only shows 2nd level headings (it used to show 2nd and 3rd), but I don't like it. I prefer to see all of the 1st level categories and expanding Developer pushes down the others, so I have to scroll. I prefer to control what is shown or not shown. There is also concern that it will look like a bug.

**Comment by galeyang** [comment]
I see the concern. It seems reasonable to let users control the expand/collapse status. 

To make the frequent used sections easily accessible, can we use cookie to store where they were from the last session?

**Comment by chalin** [comment]
> I see the concern. It seems reasonable to let users control the expand/collapse status.

Ok, so we won't be opening "Development" and "APIs & References" by default anymore, right?

> To make the frequent used sections easily accessible, can we use cookie to store where they were from the last session?

Sure, but that is a separate issue, and I'm not aware that we have such a feature for any other of our sites.

**Comment by galeyang** [comment]
> Ok, so we won't be opening "Development" and "APIs & References" by default anymore, right?

Yes.

> > To make the frequent used sections easily accessible, can we use cookie to store where they were from the last session?
> 
> Sure, but that is a separate issue, and I'm not aware that we have such a feature for any other of our sites.

Agreed. This is a separate issue that is open for discussion.
