### ISSUE TITLE
[dash] Main nav entry usability: add hover styling, make clickable region larger

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1456]
1. Add a hover design, e.g. make the font color black
2. Make the clickable space larger

Current
![image](https://user-images.githubusercontent.com/5102864/46835849-31c1ac80-cd64-11e8-9678-c92ef2b5a8f6.png)
Ideal
![image](https://user-images.githubusercontent.com/5102864/46835984-9bda5180-cd64-11e8-945a-484d89c5f2f4.png)

**Comment by sfshaza2** [comment]
I'm OK with how this works. I'm closing. Re-open if it's still an issue, @galeyang

**Comment by galeyang** [comment]
Okay. I can come back to it later if users have problems with the clickable region.
