### ISSUE TITLE
[dash] Docs active-highlighter missing when viewing docs pages other than `/docs`

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1457]
The active highlighter (blue bottom line) on the top nav works when a user visit the Docs landing page, but it's missing in all docs content pages.

Correct
![image](https://user-images.githubusercontent.com/5102864/46836241-8e719700-cd65-11e8-819c-b4a17a24750c.png)

The blue underline is missing when a user visits all docs content pages.
![image](https://user-images.githubusercontent.com/5102864/46836298-cb3d8e00-cd65-11e8-8464-aad4df8a45dd.png)

**Comment by galeyang** [comment]
I'm only aware of those three at this point. 

Infrastructure setup? FYI: we may have more in the future.

**Comment by chalin** [comment]
> I'm only aware of those three at this point. ... FYI: we may have more in the future.

The simplest way to make the (currently virtual) "Docs" structure obvious to site users is to **actualize it in the site navigation**. This is what the Firebase site does:

> <img width="714" alt="screen shot 2018-10-12 at 05 42 15" src="https://user-images.githubusercontent.com/4140793/46862229-6d9b5700-cde2-11e8-89b4-a7de8a8c4b6e.png">

But then again, the Firebase main nav has more entries and the site navigation is organized accordingly.

If we do the same here then we'd update the navigation structure like this:

  - `/get-started` would become `/docs/get-started/...`
  - `/development/ui/...` -> `/docs/development/ui/...`
  - etc.

WDYT? @filiph @Sfshaza, care to chime in as well? cc @fertolg

**Comment by Sfshaza** [comment]
Yes, this is a pickle. We know up front that we eventually want other docs on this site, for example docs aimed at designers. If we place the docs UNDER /docs, would it affect the left nav? I'm not keen on adding another level. We are already pushing it because the IA goes 4 levels deep but the left nav goes 3.

**Comment by chalin** [comment]
It would not add another level to the sidenav.

**Comment by Sfshaza** [comment]
Then I'm fine with it. 😁

**Comment by Sfshaza** [comment]
I plan to fix this next week.
