### ISSUE TITLE
[dash] Set a maximum width to avoid the unbearable line length in the docs

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1458]
The line length can be unbearable when the window is maximized.

![image](https://user-images.githubusercontent.com/5102864/46837253-74d24e80-cd69-11e8-9a43-2952ecd883fa.png)

The best practice from the readability standpoint is 45-75 (or up to 85) characters. Even on a 15-inch laptop, we can sometime get up to 148 characters per line.

----
**Suggestion**

- **Option 1: set a `max-width` only to the text content. That is, code blocks and images can still make the best use of the space.**

Example: [Bootstrap](https://getbootstrap.com/docs/4.1/layout/grid/) sets a max-width only to the text/paragraph html tag.

![image](https://user-images.githubusercontent.com/5102864/46837916-d5628b00-cd6b-11e8-92cf-5691a8199d66.png)
![image](https://user-images.githubusercontent.com/5102864/46838128-bb757800-cd6c-11e8-979b-d2325434e8f1.png)

- **Option 2: set a `max-width` to the entire center panel**

 Example: [Material.io](https://material.io/design/motion/choreography.html) sets a max-width to the center container 

![image](https://user-images.githubusercontent.com/5102864/46837746-64bb6e80-cd6b-11e8-9550-4f8905003576.png)

**Comment by fertolg** [comment]
This was fixed in #1459

**Comment by sfshaza2** [comment]
@fertolg, there's a followup request to make the box smaller
