### ISSUE TITLE
[dash] Use of caret for 2nd level sidenav entries looks too busy

### ISSUE THREAD

**Issue by chalin** [flutter/website#1461]
This is a followup to https://github.com/flutter/website/pull/1454#issuecomment-429090797.

Here is an example:

> <img width="259" alt="screen shot 2018-10-12 at 06 06 23" src="https://user-images.githubusercontent.com/4140793/46863294-08953080-cde5-11e8-8310-735d9339ff92.png">

As an alternative, developers (such as [Web](https://developers.google.com/web/fundamentals/) uses a triangle, for example:

> <img width="254" alt="screen shot 2018-10-12 at 05 42 44" src="https://user-images.githubusercontent.com/4140793/46863344-2e223a00-cde5-11e8-8aa4-1dd0aeffb970.png">
> <img width="257" alt="screen shot 2018-10-12 at 05 33 54" src="https://user-images.githubusercontent.com/4140793/46863350-337f8480-cde5-11e8-8a6f-b5d1484ca6d0.png">

cc @filiph @Sfshaza @fertolg

**Comment by galeyang** [comment]
Looks better for me!

**Comment by filiph** [comment]
LGTM, too. I'm not a designer, though. Should we ask Nicholas?

**Comment by galeyang** [comment]
It would be great to have the designer in this discussion. They also expressed some concerns about being visually crowded.

**Comment by Sfshaza** [comment]
I like this solution better, too. Let's see if Daniel blesses it or has a
better idea.
