### ISSUE TITLE
[dash] Windows displays unicode missing characters

### ISSUE THREAD

**Issue by fertolg** [flutter/website#1462]
From a stakeholder review:

> seeing a number of these Unicode placeholders (NB These are not visible on Mac)

![lsxyttdbrbe](https://user-images.githubusercontent.com/2965170/46897802-d530c100-ce39-11e8-9ce9-b572a038e224.png)

**Comment by sfshaza2** [comment]
Duplicate of bug filed by @Hixie.

**Comment by fertolg** [comment]
Fixed in #1594
