### ISSUE TITLE
File path is not specified

### ISSUE THREAD

**Issue by dsingh06** [flutter/website#1466]
Can't move past the second screen of 'Creating new flutter project' as SDK path is not loaded. Can;t find where android studio shows this path to the SDK after installing it

**Comment by Sfshaza** [comment]
@dsingh06, did you download the Flutter SDK? That is a separate step from downloading Android Studio.

**Comment by Sfshaza** [comment]
On the new site, I've added text to clarify this scenario. (Two people reported it, so there must be others.)

**Comment by Sfshaza** [comment]
Closing. Please reopen if needed.
