### ISSUE TITLE
Issue from website page Flutter for React Native Developers

### ISSUE THREAD

**Issue by palaniraja** [flutter/website#1468]
From URL: https://flutter.io/flutter-for-react-native/

[DartPad link](https://dartpad.dartlang.org/b68eb981456c5eec03daa3c05ee59486) for Asynchronous programming is throwing error.

```
Error compiling to JavaScript:
main.dart:11:13:
Error: Getter not found: 'JSON'.

Error: Compilation failed.
```

fix is to replace `JSON.` to `json.` line # 11

Link to [Updated & working DartPad snippet](https://dartpad.dartlang.org/663b7053a2597886c29a6f3204abfe6b)

The same goes for `async` & `await` as well.

**Comment by sfshaza2** [comment]
This has been fixed. Closing.
