### ISSUE TITLE
Issue from website page Flutter for React Native Developers

### ISSUE THREAD

**Issue by palaniraja** [flutter/website#1469]
From URL: https://flutter.io/flutter-for-react-native/#how-do-i-install-packages-and-package-plugins

Though it is technically correct, I guess the right `import` statement in this section should be below:

`import 'package:google_sign_in/google_sign_in.dart';`

**Comment by micpap25** [comment]
I think we can close this now that it's fixed.

**Comment by sfshaza2** [comment]
Thanks! Closing.
