### ISSUE TITLE
Issue from website page Internationalizing Flutter Apps

### ISSUE THREAD

**Issue by haarts** [flutter/website#1471]
From URL: https://flutter.io/tutorials/internationalization/

Under the header "Loading and retrieving localized values" it is mentioned that each delegate should define an `async` `load` method.
Under the header "Defining a class for the app’s localized resources" there is defined an example. This example doesn't use `async`, it uses a `Future`. 
While this isn't quite incorrect it is inconsistent.

**Comment by Sfshaza** [comment]
@haarts, I understand your confusion. There are two ways to write an asynchronous method. One way is to mark the method with the `async` tag and use `await` inside the method. The other way is to use the Future API and `then()` inside the method. In both cases, the asynchronous method returns a Future. The method you point to uses that approach, which you can learn more about in [Futures and Error Handling](https://www.dartlang.org/guides/libraries/futures-error-handling).

**Comment by haarts** [comment]
Yes, I'm aware they are in essence the same (I should have stated that more clearly). 
I was merely pointing out that the word 'async' implies the usage of the keyword 'async'. Writing the full word 'asynchronous' would, IMO, be better. 
This is a small nitpick, feel free to ignore and close, I just thought it could be a bit better.

**Comment by Sfshaza** [comment]
Thanks, @haarts. After emailing you, I did add some text to clarify this on the new site. We are no longer fixing issues on master, unless a P0.  Thanks for pointing out the confusing text. The "async `load()`" text only code-fonted the `load()` function (not async), but that's pretty subtle.
