### ISSUE TITLE
Issue from website page Internationalizing Flutter Apps

### ISSUE THREAD

**Issue by haarts** [flutter/website#1473]
From URL: https://flutter.io/tutorials/internationalization/

Under the header "Specifying the app’s supportedLocales parameter" there is this sentence: "In terms of the previous DemoApp example, the app only accepts the US English or French Canadian locales, and it substitutes US English (the first locale in the list) for anything else." The referenced DemoApp supports US English and Spanish, not French: https://github.com/flutter/website/blob/master/src/_includes/code/internationalization/intl/main.dart#L108-L109

**Comment by micpap25** [comment]
I think this can be closed now @sfshaza2
