### ISSUE TITLE
Search results should not open in a new tab

### ISSUE THREAD

**Issue by jamesderlin** [flutter/website#1483]
From URL: https://flutter.io/search/

If doing a search from https://flutter.io/, clicking on each search search result opens that result in a new browser tab.  I think that this is very annoying, particularly because it is not expected.  This is not how https://docs.flutter.io/ behaves nor how Google searches normally behave.

If a user wants to open a new tab, they can choose to do that themselves via a number of means; we should not forcing that choice on them.

**Comment by Sfshaza** [comment]
@jamesderlin, Hmmmm.... Search doesn't open a new tab for me. What platform/browser are you using? (I'm using Chrome on a Mac.)

**Comment by jamesderlin** [comment]
This happens to me with Chrome 70.0.3538.67 64-bit and with Firefox 62.0.3 64-bit on Linux.

**Comment by jamesderlin** [comment]
Using Firefox to inspect the generated HTML of the search results (e.g. for https://flutter.io/search/?cx=007067728241810524621%3Agm6vraqlc8c&ie=UTF-8&hl=en&q=Widget ), I see:

    <a class="gs-title" href="..." target="_blank" ...><b>Widgets</b> Catalog - Flutter</a>`

And `target="_blank"` will open a new tab.

**Comment by sfshaza2** [comment]
It absolutely doesn't do this for me on a Mac and using Google Chrome is up to date
Version 70.0.3538.77 (Official Build) (64-bit). I wonder if it's only true on Linux or Windows?

I'm leaving this open to see if others have this issue.

**Comment by jamesderlin** [comment]
I just tested this with Chrome 70.0.3538.77 (Official Build) (64-bit) (same as you) on my macOS 10.13.6 machine, and the search results open in a new tab there as well.  I also tried it with a guest profile to ensure that it wasn't caused by some extension.

Feel free to come by my desk and see if I'm doing something differently than you are.

**Comment by sfshaza2** [comment]
You are talking about flutter.io and not docs.flutter.io, right?

**Comment by jamesderlin** [comment]
Correct; I'm talking about the search box in the upper-right corner of flutter.io.  The search box from docs.flutter.io works fine.

**Comment by sfshaza2** [comment]
I asked the guys implementing the new website what they saw:

When you guys do a search on flutter.io, does it open a new tab or use the
current tab?
8 mins
[image: Fernando Guerrero (fguerrero@google.com)]
current tab










Are any colleagues seeing what you're seeing? I'm wondering if you have
some advanced preference set in Chrome.

Seriously stumped.

**Comment by sfshaza2** [comment]
@fertolg, @chalin, could one of you take a look? Do you have other ideas why he might be seeing this?

**Comment by jamesderlin** [comment]
One point of clarification: the new tab appears when I click on a search *result*, not when performing the search itself.  It's not obvious which Fernando was referring to.

**Comment by sfshaza2** [comment]
Ohhhhhh! That was never clear to me.

@galeyang, do you have an opinion here? I actually like opening it in a new tab, but if the UX team thinks no, then we'll undo it.

**Comment by sfshaza2** [comment]
This is literally the first time I've seen a complaint about it.

**Comment by sfshaza2** [comment]
OK, I've asked the website infrastructure dude to weigh in. He said that opening a result in a new tab is default behavior for Google's search widget. (It's also how it works on all 3 Dart websites.) But he's found a way to turn it off and agrees that it's bad practice.

**Comment by galeyang** [comment]
Agreed. For the custom search, it would be great to let user be in control of the interface.

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/1606 on the new website. (We aren't fixing issues on the current site unless a P0.)
