### ISSUE TITLE
Widget catalog pages should have better hyperlinks

### ISSUE THREAD

**Issue by jamesderlin** [flutter/website#1485]
From URL: https://flutter.io/widgets/basics/

All of the widget catalog pages list widgets with the following structure:

> [Image]
> *Widget Name*
> *Description*
> Documentation

Only the "Documentation" link navigates anywhere.  The image and widget name are not hyperlinks despite being bigger and more intuitive click targets.  Meanwhile all the "Documentation" links are not great for accessibility since they all have the same name.

At a minimum, the image should be a hyperlink to the documentation page.  I also think that we should remove the "Documentation" links and make the widget names hyperlinks instead.

**Comment by chalin** [comment]
Thanks for bringing that up. Yes, we've been discussing precisely the change you suggest. cc @Sfshaza

**Comment by Sfshaza** [comment]
I agree. The image should be clickable, too.
