### ISSUE TITLE
[dash] Adjust h3 and h4 styles

### ISSUE THREAD

**Issue by chalin** [flutter/website#1486]
As things stand \<h3> heading text is smaller than \<h4> heading text:

> <img width="479" alt="screen shot 2018-10-17 at 07 23 59" src="https://user-images.githubusercontent.com/4140793/47083418-7fb03780-d1de-11e8-8f9e-56acae0fca1b.png">

(Screenshot taken from the https://flutter-io-staging-1.firebaseapp.com/testing/ui-performance page.)

As compared to \<h2> styling, IMHO the \<h3> font size is too small. Maybe the \<h4> size and/or margins and padding need to be adjusted too.

**Comment by Sfshaza** [comment]
Yes, please fix!
