### ISSUE TITLE
Potential typo in Animation docs?

### ISSUE THREAD

**Issue by sethladd** [flutter/website#149]
Hi,

I was reading through Animation doc (https://flutter.io/animations/), and I saw this statement: "The first, AnimatedComponent, is most useful for otherwise stateless components. "

But, AnimatedComponent extends from StatefulComponent. (http://docs.flutter.io/flutter/widgets/AnimatedComponent-class.html)

Should the doc say "otherwise stateful components" ?

**Comment by sethladd** [comment]
cc @abarth

**Comment by Hixie** [comment]
It means that it's useful for use by stateless components.

**Comment by sethladd** [comment]
Ah, thanks. "for otherwise" was interpreted as "instead of".

How does "The first, AnimatedComponent, is most useful for stateless components that want to animate a widget in their build tree." sound?

**Comment by abarth** [comment]
What I meant was "when you don't have any state other than the animation".  The relevant point is that the build function is on the widget rather than the state object, which means there's nothing for you to call setState on.

**Comment by krisgiesing** [comment]
I thought the wording was fine on first read, but after thinking about it, I do find it somewhat confusing to have a StatefulComponent where the build function is on the widget and not the state. People already get somewhat confused about that.  I'm not sure what to do about it though.

**Comment by abarth** [comment]
> I do find it somewhat confusing to have a StatefulComponent where the build function is on the widget and not the state.

We could make StatelessComponent inherit from StatefulComponent and make that the normal thing.  We just optimize away the extra object in our current implementation of StatelessComponent.
