### ISSUE TITLE
[dash] Custom search for flutter.io

### ISSUE THREAD

**Issue by Sfshaza** [flutter/website#1490]
Right now, the search feature doesn't work at all (perhaps staging needs to be whitelisted?), but we would like a better custom search. [See the Dart search](https://www.dartlang.org/search?cx=011220921317074318178%3A_yy-tmb5t_i&ie=UTF-8&hl=en&q=mixin) for an idea of what we'd like.

**Comment by Sfshaza** [comment]
Fixing the current search is a P0. Implementing a new custom search is a  P1.

**Comment by chalin** [comment]
@Sfshaza - could we get the staging server whitelisted. I'd rather not wait until the day we deploy to the main site to find out that this is still broken.

**Comment by sfshaza2** [comment]
Yes, do you know how we do that?

**Comment by chalin** [comment]
No but maybe @kwalrath knows (or would know who to ask).

**Comment by sfshaza2** [comment]
It turns out the problem is not about whitelisting. There's broken jekyll code.  @fertold is fixing.

**Comment by fertolg** [comment]
Reopening the issue since I only fixed the search results, but there's no custom search results yet.

**Comment by fertolg** [comment]
@sfshaza2 Downgrading custom search to p2 given that it's a considerable effort. We should probably discuss this in more detail with the designers.

**Comment by kwalrath** [comment]
I'd love to have the search return only results from flutter.dev, like we do on dart.dev. I'd be happy to help with this.

**Comment by sfshaza2** [comment]
SGTM!

**Comment by sfshaza2** [comment]
An update:

When I just now searched for "pump" (a method in WidgetTester) on flutter.dev, it first found the relevant API docs. Okaaaayyy. Then it found references from Google groups about cars and sump pumps. Then, FINALLY, after a bunch of those links, it found the page I wanted it to find, "An introduction to widget testing" on flutter.dev. I'm hoping that we can either eliminate Google groups, or at least filter it to Flutter-specific groups. Also, I prefer that the flutter.dev results appear before the API results
