### ISSUE TITLE
[dash] Issues for new website

### ISSUE THREAD

**Issue by Sfshaza** [flutter/website#1491]
* [ ] Finish reviewing all pages and fixing issues
* [ ] Add a TOC back to pages containing tabs
* [ ] Run site through accessibility testing/review
* [ ] UX testing of new site
* [ ] Custom search - open issue
* [ ] Deprecated/watermark format option
* [ ] Add descriptions to each page
* [ ] Redirects
* [ ] Finalize landing page
* [ ] Finalize showcase page
* [ ] A new 404 page
* [ ] Complete styling for widget catalog
* [ ] More new content (by Flutter Live)
* [x] Sitemap - #1512

**Comment by chalin** [comment]
Hey Shams, can this be closed?

**Comment by sfshaza2** [comment]
Yes, closing this.
