### ISSUE TITLE
Limit height of widget index cards

### ISSUE THREAD

**Issue by chalin** [flutter/website#1495]
Widget index cards:

- [ ] Use ellipses and hide excess description.
- [x] Make the image a link too. Related: #1485
- [x] With the image and card header as links, consider dropping the "Documentation" link - #5685

@Sfshaza - what do you think?

---

This is what the current site looks like (on Chrome):

> <img width="961" alt="screen shot 2018-10-18 at 09 01 44" src="https://user-images.githubusercontent.com/4140793/47157962-8dd28680-d2b8-11e8-9b63-efb700a5676e.png">

And these are our new cards:

> <img width="924" alt="screen shot 2018-10-18 at 09 02 03" src="https://user-images.githubusercontent.com/4140793/47157987-96c35800-d2b8-11e8-9fb7-4c89102500d0.png">

**Comment by chalin** [comment]
Interesting ideas. We could also use Liquid to simply trim the text. How about that?

**Comment by fertolg** [comment]
I like that better than the CSS approach TBH, because it would also trim it for screen readers. Can liquid insert an ellipsis into the actual text?

**Comment by chalin** [comment]
Yes, we can add ellipses too. I can take over this issue if you'd like.

@sfshaza2 - what is the priority on this issue?

**Comment by sfshaza2** [comment]
Yes, I like the idea of making the image clickable, removing the documentation link, and adding ellipses to shorten the text via liquid/jekyll. I'd say this is a P1 or P2.

**Comment by micpap25** [comment]
@sfshaza2 Unless minds have been changed on this subject, I can make a PR for this.

**Comment by sfshaza2** [comment]
Sure, that sounds good, @micpap25.

**Comment by micpap25** [comment]
I'm making a PR to remove the Documentation footer right now. I don't know Jekyll well enough to cut off the description at a certain point, so someone else will have to follow up to finish this.

**Comment by chalin** [comment]
Closed by mistake. For context, see https://github.com/flutter/website/pull/5685#issuecomment-827584764.
