### ISSUE TITLE
[dash] What to do with pages appearing in two places?

### ISSUE THREAD

**Issue by chalin** [flutter/website#1496]
We've already resolved the [specific case of the widget catalog & widget index](https://github.com/flutter/website/issues/1425) via #1455, but that case was special.

I've noticed that there are other pages with two homes such as:

- [x] Sidenav: widget inspector page appears twice #1550
- [x] Sidenav: navigation-basics page appears twice #1528

---

Original details for widget inspector page:

> **Development > User interface > Inspect an app's UI**

which is just a link to

> **Development > Tools > Widget inspector**.

How do you want to deal with pages that appear in two sidenav locations? I see two main options:

 1. Host the same page at two URLs.

    Pros: avoids user confusion navigation-wise
    Cons: it might give folks the impression that there are two distinct pages

 2. Choose one page as the canonical base, and have both link to it.

    Pros: it make it obvious that there is only one page source
    Cons: a user can loose context during navigation; e.g., s/he clicks on **Development > User interface > Inspect an app's UI** but ends up at **Development > Tools > Widget inspector**

Thoughts?

**Comment by galeyang** [comment]
My initial thought was to separate the tutorial and tool docs so ideally they are two different docs. 

- Development > User interface > Inspect an app's UI (tutorial - a how-to guide)
- Development > Tools > Widget inspector (an introduction of the tool)

The current doc is more a tool intro that belongs to "Development > Tools".
And we can create with a new how-to doc (in the future) if needed .

**Comment by chalin** [comment]
Ok, in the meantime, #1498 redirects the UI URL to the tool page. Is that ok? If so, can you create a separate issue to track the creation of a new how-to doc?

**Comment by galeyang** [comment]
@Sfshaza, If we link the existing inspector doc to "Development > Tools > Widget inspector (an introduction of the tool)", do we have any upcoming content (or future plan) for "Inspect an app's UI" tutorial?

Ideally, I'd like to avoid the redirection which can make a user lose context.

**Comment by chalin** [comment]
@galeyang - other than the two pages listed in the (edited) original comment, are you aware of any other pages that are referenced from two distinct sidenav entries?

**Comment by galeyang** [comment]
I wasn't aware of any other pages at this point.

**Comment by sfshaza2** [comment]
Update: the how-to won't be happening in the immediate future. Unless Tao writes it.  ;) So definitely remove that from the sidenav for now.

Jacob R (@jacobr on GitHub) will update the tool page between Nov 1 and Nov 5.  Yay! I told Jacob that it was the cringiest page for me on the new site, because the tool has changed substantially.

**Comment by sfshaza2** [comment]
@chalin fixed the navigation docs by adding a landing page.

Do we have other instances to solve, or can this be closed?

**Comment by chalin** [comment]
It can be closed for now.
