### ISSUE TITLE
[dash] Accessibility page path doesn't match IA

### ISSUE THREAD

**Issue by chalin** [flutter/website#1497]
According to the IA, the Accessibility page is found under **Development > Accessibility & Localization > Accessibility**, but the path to the page is just [/accessibility](https://flutter-io-staging-1.firebaseapp.com/accessibility).

Is it that this page was simply not relocated, or is there a reason to have the IA and path not agree?

cc @filiph @fertolg

**Comment by Sfshaza** [comment]
Oops. Really? That's definitely an oops.

**Comment by chalin** [comment]
Ok, then I'll relocate it as part of #1498.

**Comment by chalin** [comment]
Closed by #1498
