### ISSUE TITLE
[dash] The image on "Expressive and Flexible UI" card seems to be clickable.

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1506]
From the study, participants mistakenly clicked on the static image because they looked clickable. We suggest to update the design (if they are actually static images)

![image](https://user-images.githubusercontent.com/5102864/47189510-cb9fd100-d2f1-11e8-83b1-71be6894716f.png)

**Comment by sfshaza2** [comment]
@maguinis, please weigh in.

**Comment by chalin** [comment]
Ping. Any feedback on this? cc @fertolg

**Comment by fertolg** [comment]
This will get closed when the new animations make it in, which will happen before launch so I'm upgrading to p0

**Comment by fertolg** [comment]
This is a different animation now, closing this ticket.
