### ISSUE TITLE
[dash] Rename "APIs & references" to just "References"

### ISSUE THREAD

**Issue by chalin** [flutter/website#1511]
How about renaming **APIs & references**:

> <img width="238" alt="screen shot 2018-10-19 at 12 36 11" src="https://user-images.githubusercontent.com/4140793/47231755-d151f100-d39b-11e8-8236-e11b71a86ac6.png">

Rename it to just **References** (or like the Firebase docs, the singular "Reference"):

> <img width="709" alt="screen shot 2018-10-19 at 12 40 18" src="https://user-images.githubusercontent.com/4140793/47231953-5a692800-d39c-11e8-96ea-f028dbe90c9e.png">

Related: #1510

**Comment by Sfshaza** [comment]
You mean src/reference?  Yes, that's fine.  :)

**Comment by Sfshaza** [comment]
Shorter name is fine. Though, if someone searches the page for API, they won't find it...

**Comment by galeyang** [comment]
> Shorter name is fine. Though, if someone searches the page for API, they won't find it...

Agreed. I like the shorter name but I'm not sure how frequent users will scan for the word "API.
