### ISSUE TITLE
Fetch data from the internet should use a StatefulWidget for FutureBuilder

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#1517]
From URL: https://flutter.io/cookbook/networking/fetch-data/

From the  FutureBuilder documentation:

> The [future] must have been obtained earlier, e.g. during [State.initState],
> [State.didUpdateConfig], or [State.didChangeDependencies]. It must not be
> created during the [State.build] or [StatelessWidget.build] method call when
> constructing the [FutureBuilder]. If the [future] is created at the same
> time as the [FutureBuilder], then every time the [FutureBuilder]'s parent is
> rebuilt, the asynchronous task will be restarted.
> 
> A general guideline is to assume that every `build` method could get called
> every frame, and to treat omitted calls as an optimization.

This leads me to think that the example should be a stateful widget that stores the future returned by fetchPost() as a field on State<MyApp>

**Comment by brianegan** [comment]
Now fixed
