### ISSUE TITLE
Issue from website page Flutter Widget Index

### ISSUE THREAD

**Issue by deven98** [flutter/website#1519]
From URL: https://flutter.io/widgets/widgetindex/

"Transform" widget repeated twice in widget index.

**Comment by sfshaza2** [comment]
Won't fix in master, but check to see if it's also true on the new site.

**Comment by NMateu** [comment]
Transform is still duplicated https://i.imgur.com/EjTNQEi.png
Simillar issue https://github.com/flutter/website/issues/1157 and https://github.com/flutter/website/issues/1231

**Comment by micpap25** [comment]
All the linked issues are resolved, and I just did a quick scan and verified that no widgets were duplicated. This can be closed.

**Comment by sfshaza2** [comment]
Thanks, @micpap25! Closing
