### ISSUE TITLE
[dash] Create a separate page for "Navigation & routing"

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1528]
> Development > UI > **Navigation & routing**

This link currently links to the "/cookbook/navigation/navigation-basics" so it has the redirect issue which can make a user lose the context.

Before we have more dedicated content, we can have a landing page that lists relevant links.

**Comment by chalin** [comment]
Which links would you like to have? The same page links as those listed under "Navigation" on the main cookbook page?

> <img width="281" alt="screen shot 2018-10-25 at 15 02 25" src="https://user-images.githubusercontent.com/4140793/47523839-09a77280-d867-11e8-8e49-4f65631620b2.png">

**Comment by galeyang** [comment]
cc @Sfshaza

**Comment by sfshaza2** [comment]
Yes, if you have multiple navigation/routing links, add those to the page. Thanks!
