### ISSUE TITLE
[dash] The size of the screenshots in some cookbook pages are too large

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1529]
I randomly visited a few cookbook pages. The screenshots in the bottom page are too large. From my impression, there are three different sizes. It would great to make them consistent. 

 The following paths are the examples: 

- /cookbook/navigation/navigation-basics
- /cookbook/design/themes
- /cookbook/images/network-image

![image](https://user-images.githubusercontent.com/5102864/47392103-6e7c9480-d6d0-11e8-8c0a-b71712f0852d.png)

**Comment by chalin** [comment]
Thanks for reporting this. FYI, the cookbook pages haven't been revisited yet, so it is to be expected that you might find issues like these.

**Comment by galeyang** [comment]
Okay. Thanks for letting me know!

**Comment by sfshaza2** [comment]
Patrice, I went through every page of the cookbook. Some images were fine, some were too big and I created a PR with smaller versions. But I was unable to resize the animated GIF files that were too large. Here's a list:

/images/cookbook/fading-in-images.gif
/images/cookbook/horizontal-list.gif
/images/cookbook/long-lists.gif
/images/cookbook/handling-taps.gif
/images/cookbook/ripples.gif
/images/cookbook/dismissible.gif
/images/cookbook/navigation-basics.gif
/images/cookbook/passing-data.gif
/images/cookbook/returning-data.gif
/images/cookbook/web-sockets.gif

We either need to make these smaller, or the site should pay attention to "width=318" when rendering an image. OR, maybe there's another image style available. I defer to you.  :)

**Comment by sfshaza2** [comment]
Oh, for the sake of keeping our site trim, I'd vote for resizing the animated GIFs, as I did with the static GIFs.

**Comment by chalin** [comment]
Thanks for making a first pass Shams. I'll wait for #1616 to be rebased, reviewed and merged before moving ahead further with this.

**Comment by chalin** [comment]
> for the sake of keeping our site trim, I'd vote for resizing the animated GIFs, as I did with the static GIFs.

I'm unsure how much work that would be, but for immediate results, I'd suggest simply limiting the width like we were doing before. (I can address that in my PR.)
