### ISSUE TITLE
[dash] Update some "Learn more" links and labels in the Showcase page

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1530]
From the study, users expected a case study when they clicked on "Learn more"  for a showcase app.

![image](https://user-images.githubusercontent.com/5102864/47392494-a46e4880-d6d1-11e8-91f3-cc2dabce2636.png)

We suggest to link "Learn more" to a case study whenever we have. 
- Alibaba: https://www.youtube.com/watch?v=jtYk3gWRSw0
- Reflectly: https://medium.com/reflectly-engineering/reflectly-from-react-native-to-flutter-2e3dffced2ea

cc: @maguinis for the links

For those we don't have a case study at this point, I'd suggest to rename it from "learn more" to "Developer website" (or something more descriptive).

**Comment by sfshaza2** [comment]
Assigning to @fertolg as he owns the Showcase page. However, he's also received specific instructions from Martin, so I hope these don't conflict.

**Comment by galeyang** [comment]
Feel free to let me know if this doesn't work or any other concerns. :)

**Comment by fertolg** [comment]
Martin did provide a [sheet](https://docs.google.com/document/u/0/?q=flutter&tgif=d) for me with all the data, so I would adhere to that, however I've commented on the sheet to see what he thinks. @galeyang can you follow up with Martin via the google sheet?
