### ISSUE TITLE
Add the sample code UI in selected tutorials

### ISSUE THREAD

**Issue by jayoung-lee** [flutter/website#1540]
We can test the new sample codes UI in the upcoming user study. Below are the tutorials frequently visited tutorials by the participants. Can we implement the new UI in these two pages?
- [https://flutter.io/tutorials/layout/](https://flutter.io/tutorials/layout/)
- [https://flutter.io/tutorials/interactive/](https://flutter.io/tutorials/interactive/)

Cc: @gspencergoog @InMatrix @galeyang

**Comment by sfshaza2** [comment]
What do you mean by the new UI? If you mean just update those two pages to the new site, no. But you can share with them another URL. Contact me offlist for that info.

**Comment by sfshaza2** [comment]
Had an offline chat with UX Researchers. They are hoping to have a new UI available for code snippets for testing. Greg has worked on a new version in the API docs. We can't get to this before launching the new site. Also, I'd like them to be relatively sure of the UI before we implement it. I'm not sure for how much longer I will have the help from the infrastructure folks.

In other words, this is a no in the short term. In the longer term, we can talk and evaluate resources and impact with the new site.

@InMatrix  @galeyang  @jayoung-lee

**Comment by gspencergoog** [comment]
OK, I'm going to just convert a few more methods to use the new UI for the API docs, and they will link to those instead in their study.  That way I don't have to touch the website.

**Comment by galeyang** [comment]
Thanks for the notes. I'll start a discussion for the potential longer term plan.

**Comment by sfshaza2** [comment]
Yes, touching the website now is not recommended, given that we are in a
mad rush to launch the new site very soon.

Thanks for understanding, Greg (and all!)

**Comment by InMatrix** [comment]
Thanks @Sfshaza for checking in with the infra team! The tabbed UI on the Dart site looks close to what we need.

Just to clarify, this request is never intended to add new features to the new site upon its launch. What we're looking for is a way to create a local prototype with a tabbed UI for showing sample code we can show in a study setting. If the UI changes prove to be useful through user study, we'll go through the appropriate process to introduce it through future updates to the website. This experiment is completely de-coupled with the new website launch.

**Comment by jayoung-lee** [comment]
+1 to @InMatrix . I should have been more clear about the purpose of this issue. It was to prototype the new UI in the context of these two tutorials (separately from the actual website), so that we can iterate on the design and find a good potential UI to suggest for the future website. 

For the user studies planned for Nov, we'll focus on the UI on API docs.

**Comment by chalin** [comment]
Since this is no longer a website issue/feature, can we close this issue?

**Comment by jayoung-lee** [comment]
Closed! I will follow up later on.

**Comment by sfshaza2** [comment]
Thank you, all! I think we are all on the same page now.
