### ISSUE TITLE
Change placeholder for Dart API Doc search

### ISSUE THREAD

**Issue by jayoung-lee** [flutter/website#1541]
From the recent user study sessions I've seen people using two different searches interchangeably (i.e., flutter.io search and API doc search) without knowing the difference between the two. Because the search box is on the upper right corner of the webpage in both cases and look very similar, it takes effort to understand the context of the search box (e.g., Will this search return an API doc for a class or a comprehensive result from Flutter website?).  

I think a quick fix to reduce the confusion would be changing the placeholder (grey text in the search box) "Search" in the API doc search to "Search API Doc". Can we make this fix? (Ideally, in the future, we might want to integrate the two searches and give an option to search within the API doc.)

Cc: @InMatrix @galeyang

**Comment by InMatrix** [comment]
Cc: @gspencergoog
Is this something easy to do? Does it require changes to DartDoc itself?

**Comment by gspencergoog** [comment]
It may require a change to dartdoc, but that seems like a reasonable thing to be able to configure, and the change should be small.

**Comment by gspencergoog** [comment]
@jcollins-g , would it be acceptable to just change the default string from "Search" to "Search API Documentation" or "Search API Docs"?  Seems like this would be a reasonable (and clearer) string for all dartdoc customers.

**Comment by sfshaza2** [comment]
API doc bugs should be filed in the flutter/flutter repo. Engineering owns the API docs and do not look here.
