### ISSUE TITLE
In “AnimatedList” doc, clearly mention both command line and IDE instructions

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1542]
In the latest round of the "Build a Simple UI" study, a participant created a starter project in an IDE and then followed  “[AnimatedList](https://flutter-io-staging-1.firebaseapp.com/catalog/samples/animated-list)” doc. she thought that she was asked to create a new project with `flutter create` in the IDE and became confused.

![image](https://user-images.githubusercontent.com/5102864/47462209-89fea280-d797-11e8-9b43-da79500503c9.png)

The problem is that users who started Flutter in an IDE might not be familiar with `flutter create`. We should mention both the command line option and the IDE option for the same action.

cc: @InMatrix, @jayoung-lee, @Sfshaza

**Comment by sfshaza2** [comment]
We no longer support these examples. They are still on the site. but nothing links to them. Closing.
