### ISSUE TITLE
JSON serialization code example outdated

### ISSUE THREAD

**Issue by Twinber** [flutter/website#1545]
https://flutter.io/json/#serializing-json-using-code-generation-libraries

The current version of json_serializable does not use Mixins

https://pub.dartlang.org/documentation/json_serializable/latest/

**Comment by chalin** [comment]
Thanks for the issue. This is a duplicate of #1255, which has been fixed by #1531.

cc @kevmoo @sfshaza2

**Comment by Twinber** [comment]
Ok, but only in dash branch

**Comment by chalin** [comment]
Ok, I'll make this change on master too.

**Comment by chalin** [comment]
Cf. @kevmoo's comment https://github.com/flutter/website/issues/1255#issuecomment-433076862

**Comment by sfshaza2** [comment]
@chalin, can this be closed?

**Comment by chalin** [comment]
Yes, it was closed by #1554.
