### ISSUE TITLE
[dash] Sidenav: navigation-basics page appears twice

### ISSUE THREAD

**Issue by chalin** [flutter/website#1551]
For context, see the parent issue: #1496

@galeyang @sfshaza2 - what do you suggest that we do in this case?

**Comment by galeyang** [comment]
> For now, please comment the inspector out of the development>UI section. The page that we do have is woefully out of date and won't be updated before launch. --- From @sfshaza2 

I think commenting out "Inspect an app's UI" under the UI section works for now.

**Comment by chalin** [comment]
That comment was for the widget inspector entry. This issue concerns the navigation-basics page that appears under:

- **Development > User interface > Navigation & routing**, and
- **Samples & codelabs > Cookbook**

**Comment by galeyang** [comment]
Oh sorry. For the navigation-basics page, early this week @sfshaza2 and filed a issue here #1528.

**Comment by chalin** [comment]
Dup of #1528.
