### ISSUE TITLE
Deployment to Firebase from Travis is failing - HTTP 410, Unknown Error

### ISSUE THREAD

**Issue by chalin** [flutter/website#1553]
E.g., see https://travis-ci.org/flutter/website/jobs/446245933:

```nocode
Deploying to Firebase project: dash
=== Deploying to 'flutter-io-staging-1'...
i  deploying hosting
i  hosting: preparing _site directory for upload...
i  Progress: [
Error: HTTP Error: 410, Unknown Error
Script failed with status 1
failed to deploy
```

**Comment by sfshaza2** [comment]
This branch is not permitted?!  What changed, I wonder.

**Comment by chalin** [comment]
Maybe some credentials were associated with your old id? Maybe @gspencergoog or @Hixie know what's going on? (It might help to look at the fb console and associated logs.)

**Comment by gspencergoog** [comment]
It sounds like it somehow can't find the site.  A 410 means: “the server returns this response when the requested resource has been permanently removed. It is similar to a 404 (Not found) code, but is sometimes used in the place of a 404 for resources that used to exist but no longer do.”

Not sure what it really means from a Firebase perspective.

**Comment by chalin** [comment]
Closed by #1557, #1558

**Comment by kwalrath** [comment]
I'm applying a similar fix to site-www.

**Comment by chalin** [comment]
> I'm applying a similar fix to site-www.

How's this coming along? FYI, I'm applying the fix to site-webdev.
