### ISSUE TITLE
Issue from website page Taps, drags, and other gestures in Flutter

### ISSUE THREAD

**Issue by ariedov** [flutter/website#1562]
From URL: https://flutter.io/gestures/

There is no `onPanStart`, `onPanUpdate`, `onPanEnd` events, which makes it confusing to understand what to do when the user needs to combine Vertical and Horizontal events.

**Comment by sfshaza2** [comment]
Excellent feedback.

**Comment by ariedov** [comment]
#1709

**Comment by ariedov** [comment]
Fired #1709 to fix this. Thanks for your attention to the issue!
