### ISSUE TITLE
Issue from website page Using Themes to share colors and font styles

### ISSUE THREAD

**Issue by gggustafson** [flutter/website#1570]
From URL: https://flutter.io/cookbook/design/themes/

The title of the referenced page promises to discuss "Using Themes to share colors and font styles". But there is no discussion of font styles! Since I find myself using 

```
Text('some text',
  style: TextStyle(
    color: Colors.blue,
    fontWeight: FontWeight.bold,
    fontSize: 24.0,
  ),
),
```

repeatedly, I thought a page theme (derived from the default theme) would be useful. But I cannot find out how.

Thoughts?

**Comment by brianegan** [comment]
Thanks for the report, and apologies for the delay -- busy work travel times!

Good call. I'll add a section that relates to Text Styles specifically!
