### ISSUE TITLE
Wide scroll on mobile in pages with images examples within it

### ISSUE THREAD

**Issue by c-machado** [flutter/website#1577]
1. Go to https://flutter-io-staging-1.firebaseapp.com/
2. Tap on 'Community' on the hamburger menu
3. Scroll to bottom of the page. Observe the image is creating a wide scroll in the page.

![screen shot 2018-10-29 at 10 29 33 am](https://user-images.githubusercontent.com/33238142/47662824-b9cbf280-db69-11e8-9836-42a2ca2f02c1.png)

This is also happening in other pages, for instance:
Docs -> Testing and optimization -> Using OEM debuggers -> Section 'Dart Debugger'

![screen shot 2018-10-29 at 12 03 14 pm](https://user-images.githubusercontent.com/33238142/47666893-abce9f80-db72-11e8-98a9-dab37541d4f5.png)

Reproducible in iOS and Android

**Comment by chalin** [comment]
The community page has been redesigned, and this problem is no longer present so I'll close this issue. We'll track the resolution of this problem for other pages via #1951.
