### ISSUE TITLE
Accessibility on Android

### ISSUE THREAD

**Issue by c-machado** [flutter/website#1592]
Navigating with the TalkBack the menu options are being announced when the menu is not expanded.
![screen shot 2018-10-29 at 3 31 51 pm](https://user-images.githubusercontent.com/33238142/47678545-17733580-db90-11e8-97ff-71b2a2a94809.png)

Add naming in the Social link options in the header: 
![screen shot 2018-10-29 at 3 33 53 pm](https://user-images.githubusercontent.com/33238142/47678561-1cd08000-db90-11e8-9f2f-187069c25761.png)

Hero carousel: Description in the hero module is not a being announced as a unique paragraph. 
![screen shot 2018-10-29 at 3 35 24 pm](https://user-images.githubusercontent.com/33238142/47678712-69b45680-db90-11e8-980c-2759b2964d09.png)

Hero Carousel: image is being announced with additional data, same as images in cards in the Showcase page.

![screen shot 2018-10-29 at 3 41 02 pm](https://user-images.githubusercontent.com/33238142/47678983-11ca1f80-db91-11e8-8249-a9568a7b56be.png)

Showcase Page -> Hero Carousel: the time interval for changing the content is a bit small, so the user can select the "Learn more" / "Watch the video" buttons from the next slide.
![screen shot 2018-10-29 at 4 31 42 pm](https://user-images.githubusercontent.com/33238142/47681697-278f1300-db98-11e8-80ea-1eb13b7954b8.png)

**Comment by amanv8060** [comment]
@sfshaza2 this could be closed
