### ISSUE TITLE
[dash] Where are the tutorials?

### ISSUE THREAD

**Issue by chalin** [flutter/website#1608]
The [Building Layouts in Flutter tutorial](https://flutter.io/tutorials/layout/) is one of the popular pages from the current site.

I'm not seeing the tutorial pages in the IA, nor as part of the current version of the new site. Have the tutorials been dropped?

**Comment by sfshaza2** [comment]
Both are under /docs/development/ui.

(We are trying to move away from a doc-based IA and use a task-based one. But we can add a landing page for the tutorials.)

**Comment by chalin** [comment]
Oops, found them! (They just aren't grouped under a /tutorials folder.)

**Comment by sfshaza2** [comment]
Right, that would make them docs-based.  ;)

**Comment by sfshaza2** [comment]
What are your thoughts, @galeyang? Should I create a landing page for /resources that lists the tutorials? I wouldn't move them.

**Comment by sfshaza2** [comment]
I've asked Patrice to set up a redirect. We already have a landing page.
