### ISSUE TITLE
[dash] Migrate GA and other analytical tools

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1611]
We'd like to ensure Google Analytics and other analytical tools (if any) work on the new website.

We have some customized tags/goals in GA but I'm not sure if we need extra manual settings on the new website. Also, do we have any other tracker (e.g. for search)?

@mit-mit @filiph Could you help confirm this or direct this to the right person? Thank you!

**Comment by filiph** [comment]
FWIW, I don't know about any special analytics setup.

**Comment by mit-mit** [comment]
Sorry, I did not configure analytics on the current site. I suspect @jayoung-lee or @InMatrix might know?

**Comment by galeyang** [comment]
Also cc @maguinis Do you know any special setup done by the developer marketing team?

**Comment by InMatrix** [comment]
Let's take this discussion internal, since some information we need to talk about might not be public.
