### ISSUE TITLE
landing page feedback

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#1625]
1) Can you speed the carousel up a tad?
2) As the text changes, can the background pic also change? 
3) The white text is hard to see against the background, particularly "Productive". Can we use black or a different (blue?) color for the text?

@maguinis also looked at the page last night and agreed with my comments. He asked me to pass this feedback along.

**Comment by chalin** [comment]
Totally agree with these points. E.g., here you see that "Productive" ends up being white over white:
<img width="1040" alt="screen shot 2018-10-31 at 12 22 25" src="https://user-images.githubusercontent.com/4140793/47803329-97bca680-dd08-11e8-8ad3-310fa2eba69d.png">

**Comment by maguinis** [comment]
I've pinged Daniel and Fernando; the new 4 we were going to go with are: 
Design beautiful apps
Create fast apps
Productively build apps
Publish iOS and Android apps

We also want the carousel to speed up a bit more

**Comment by fertolg** [comment]
The backgrounds can be adjusted so they line up with the text better, but I don't want to make those adjustments until I have the actual backgrounds we are going to use, or I'll just have to do it again. I can speed the carousel up no problem.

**Comment by sfshaza2** [comment]
Totally reasonable, Fernando.
