### ISSUE TITLE
[dash] Sidenav doesn't contain an entry for the design-principles page

### ISSUE THREAD

**Issue by chalin** [flutter/website#1626]
This is the page: https://flutter-io-staging-1.firebaseapp.com/docs/resources/design-principles

Should there be a corresponding entry in the sidenav?

**Comment by sfshaza2** [comment]
Yes, indeedy. Not sure how that got left off.

**Comment by galeyang** [comment]
Is this related to Contributing?

**Comment by sfshaza2** [comment]
Nope.

**Comment by sfshaza2** [comment]
It's now a non-issue. @Hixie is migrating this page to the Flutter wiki.
But we should put an auto-direct from its old location to the wiki

**Comment by chalin** [comment]
Right, we'll be tracking the followup to issue via #1634.
