### ISSUE TITLE
Material Components widgets: SliverAppBar is missing

### ISSUE THREAD

**Issue by davidwparker** [flutter/website#1627]
From URL: https://flutter.io/widgets/material/

I was watching the widget of the week video (https://www.youtube.com/watch?v=R9C5KMJKluE) and SliverAppBar is on there.

Is there a reason it's not on the Material Components widget page?

The docs have it under flutter/material:
https://docs.flutter.io/flutter/material/SliverAppBar-class.html

What's the best way to discover widgets if they're not all in the widget catalog?

Thanks, great project!

**Comment by sfshaza2** [comment]
Hi, @davidwparker! Yes, we are behind. Right now we are working on a revamped website and hopefully we can get to updating this page soon. Though, I'm the only Flutter writer, so I gladly accept PRs.  ;) . If you want to add anything, please file a PR on the dash branch, where the new site is being developed.

**Comment by davidwparker** [comment]
Sounds great, thanks @sfshaza2 !
