### ISSUE TITLE
[dash] Sidenav doesn't contain an entry for the bug-reports page

### ISSUE THREAD

**Issue by chalin** [flutter/website#1628]
This is the page: https://flutter-io-staging-1.firebaseapp.com/docs/resources/bug-reports

Should there be a corresponding entry in the sidenav?

**Comment by galeyang** [comment]
@Sfshaza Do you know if we have a few Contributing related pages like this? Maybe we need a place for all Contributing docs, like [React](https://reactjs.org/docs/getting-started.html).

**Comment by sfshaza2** [comment]
This is a good page and I'd forgotten about it. I'd like to see this in the footer. File an issue, right in the footer. But if it has to go in the sidenav, I'd put it in resources. 

In any case, it should be linked to from the community page, perhaps.

No, @galeyang, we have the contributing page, which is not displayed on the website, and the community page, which Daniel is working on.

**Comment by galeyang** [comment]
I see. Thanks for the clarification!

**Comment by chalin** [comment]
> This is a good page and I'd forgotten about it. I'd like to see this in the footer. File an issue, right in the footer.

We already have a page-specific "file an issue" button in the top-left corner of every page.

> But if it has to go in the sidenav, I'd put it in resources.

Actually, come to think of it, we could place the page under /community, as in /community/bug-reports. We don't have to have the page appear in the sidenav, but it should be part of some nav (side- or main-nav).

Thoughts?

**Comment by sfshaza2** [comment]
I like the idea of adding it to /community.

**Comment by sfshaza2** [comment]
Still not there.

**Comment by galeyang** [comment]
We can probably add a link about the bug-report page to the community page where we invite people to request new features or report bugs.
![image](https://user-images.githubusercontent.com/5102864/64657774-d5d72c00-d3e9-11e9-8f6f-f0aaf0b37e05.png)

**Comment by parlough** [comment]
A link to this page in the sidenav was added under resources in https://github.com/flutter/website/pull/4378
