### ISSUE TITLE
[dash] The white words on the front page blend into the background

### ISSUE THREAD

**Issue by Hixie** [flutter/website#1631]
![productive](https://user-images.githubusercontent.com/551196/47821782-17ee0680-dd1f-11e8-942b-b9087b8c2d1c.png)

**Comment by sfshaza2** [comment]
Yup, I filed this too. It will be fixed by launch.

**Comment by chalin** [comment]
@sfshaza2 - where is the other issue that mentioned this (I can't seem to find it)?

**Comment by chalin** [comment]
Found it: #1625. This issue was fixed by #1636.
