### ISSUE TITLE
flutter-announce mailing list isn't mentioned

### ISSUE THREAD

**Issue by Hixie** [flutter/website#1633]
I only found one mention of our mailing lists, on this page:
https://flutter-io-staging-1.firebaseapp.com/docs/development/tools/sdk/upgrading
...which seems like an odd place for it.

I would expect to see more prominent placement for the flutter-announce and flutter-dev lists.

**Comment by sfshaza2** [comment]
Those will go on our community page. We are waiting for the designer to provide that design.
