### ISSUE TITLE
[dash] slivers page seems empty

### ISSUE THREAD

**Issue by Hixie** [flutter/website#1635]
This page probably can be removed for now:
https://flutter-io-staging-1.firebaseapp.com/docs/development/ui/advanced/slivers

**Comment by sfshaza2** [comment]
I call that a placeholder page.  :)  It's not quite empty - it has links to the videos and article we've published. I added the minimal page so that folks could search our site and find *something* about slivers. Eventually, I'd like more docs on our site.

**Comment by sfshaza2** [comment]
Closing.
