### ISSUE TITLE
[dash] Learn More doesn't mention the API docs or the docs on the Web site

### ISSUE THREAD

**Issue by Hixie** [flutter/website#1638]
https://flutter-io-staging-1.firebaseapp.com/docs/get-started/learn-more

Seems like that page should list the API docs (a huge source of information) and the Web site itself, which has a lot of content.

**Comment by sfshaza2** [comment]
Good point.

**Comment by InMatrix** [comment]
+1 

I'd like to add the widget catalog on the "Learn More" page as well.
