### ISSUE TITLE
Issue from website page Create a horizontal list

### ISSUE THREAD

**Issue by RRP12** [flutter/website#1640]
From URL: https://flutter.io/cookbook/lists/horizontal-list/

i am getting error in vs code 
like one required argument required but o found

**Comment by sfshaza2** [comment]
Hmmm... @brianegan, can you take a look?

**Comment by brianegan** [comment]
Thanks @Sfshaza! My apologies for the delay -- Wrapped up some work travel / conference talks!

@RRP12 -- Could you please paste the error you're receiving? I've reviewed the Snippet of code as well as the Full Example, and I didn't spot any errors myself.

Thanks!

**Comment by brianegan** [comment]
Hi @RRP12 -- Are you still seeing that error? If so, please paste the error in this issue and I'll take a look :)

**Comment by sfshaza2** [comment]
I'm closing this. @RRP12, if you have more info, please reopen.
