### ISSUE TITLE
[dash] make the white box less long on the homepage where the "Made by Google" text is in

### ISSUE THREAD

**Issue by maguinis** [flutter/website#1660]
The first white box under the carousel extends very long and makes users have to scroll to get to our three pillars. Let's make it less long so it's the minimal length needed to include the Made by Google, sub tagline, and Get Started / Watch Video (we could even put watch video to the right of Get Started to make it even less long).

**Comment by fertolg** [comment]
@maguinis I've tried my best to reduce the size of the card but it looks a bit awkward, I wanted to show you before merging so you can approve/comment. Here is what I currently have:

![oamu2k4bfuv](https://user-images.githubusercontent.com/2965170/47935224-eef08180-de96-11e8-8817-79ca3affa663.png)

I also took the liberty to try to condense the information into just that 1 card, to see what it would look like. This is not only a style change, but a content change, however from a design standpoint this seems way cleaner (to me, at least) so I also wanted to share to see if you'd like to go with something like this:

![2xvetdv8hzn](https://user-images.githubusercontent.com/2965170/47935281-15162180-de97-11e8-8b38-fac925feedf2.png)

Let me know if you have a preference, I can 1. go with what I currently have, 2. go with the alternative suggestion (but it's changing the content a bit) or 3. brainstorm it further with Daniel or a designer to see what we can do to condense this.

**Comment by maguinis** [comment]
Wow -- it looks much cleaner / clear. I wonder where we can place the additional content about free and open source, works with existing code, partnership with community which is all important. I'm tempted to go with 2 though. 

@Sfshaza WDYT?

**Comment by maguinis** [comment]
Going with option 2.
