### ISSUE TITLE
[dash] change copy of "Help us improve Flutter! Take our survey (open until Nov 12)."

### ISSUE THREAD

**Issue by maguinis** [flutter/website#1662]
"Help us improve Flutter! Take our survey (open until Nov 12)" does not sound ok. 

Please update to this: 

"Have you tried Flutter? We'd love to hear your thoughts by taking our survey (open until Nov 12)"

**Comment by sfshaza2** [comment]
This makes the banner longer, which is not idea. Are you sure, @maguinis?

**Comment by kwalrath** [comment]
"hear your thoughts by taking our survey" isn't grammatically correct, so we shouldn't use those words exactly.

**Comment by kwalrath** [comment]
How about:

Have you tried Flutter? Please take our survey!

(We could perhaps leave off the "(open until Nov 12)" for now, putting that info in the survey intro and mentioning it in the banner when the date is closer.)

**Comment by maguinis** [comment]
Have you tried Flutter? Please take our survey! works!

**Comment by sfshaza2** [comment]
Another banner update from @timsneath 

To clarify the CTA, can we change the banner from "Join us for *Flutter Live* on December 4th for a celebration of Flutter. Stay tuned for updates!" to simply "*Join us for Flutter Live* on December 4th for a celebration of Flutter." with the hyperlink broadened?
