### ISSUE TITLE
Reflectly graphic is not properly centered on phone frame.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/website#1663]
It's a little too low, and a little too wide:
![image](https://user-images.githubusercontent.com/8867023/47931122-1fcab980-de8b-11e8-8d89-1316e96cdf0a.png)

**Comment by chalin** [comment]
AFAIK, this image is going to be changed, right @sfshaza2 @fertolg?

**Comment by sfshaza2** [comment]
I'm not sure.

**Comment by sfshaza2** [comment]
We've switched from GIFs to icons.
