### ISSUE TITLE
The 2 phones in Native Performance are both iOS :)

### ISSUE THREAD

**Issue by xster** [flutter/website#1666]
I think the intent was to show that Flutter runs natively on Android and iOS but they're both showing the same iOS content with a notch drawn in the bezel for the second phone. Android would have a different status bar. Material Design on Android would also draw the app bar back button with a different icon and the title left aligned.

**Comment by sfshaza2** [comment]
I thought there were plans to fix this, @fertolg?

**Comment by fertolg** [comment]
The new animations are in, so this is fixed now.
