### ISSUE TITLE
[dash] Add carousel indicators to homepage

### ISSUE THREAD

**Issue by chalin** [flutter/website#1689]
Might it be possible to get carousel indicators on the homepage too -- like those added by #1685?

**Comment by fertolg** [comment]
I'm not 100% convinced the indicators make sense on the homepage. I think the carousel purpose is different. On Showcase, it's meant to cycle through featured case studies, each of which has info and links to go to, but on the homepage, the carousel is just a looping animation, not necessarily meant to display information or take the user somewhere else.

I think adding the indicators on homepage would make it obvious it's a carousel (as opposed to just an animation), without providing real value (it's not important for users to be able to skip a slide or go back to a previous one).

WDYT?

**Comment by chalin** [comment]
I don't have a strong opinion. If no one else feels the need for indicators (that allow the user to control the carousel), then feel free to close this.

@sfshaza2 - any thoughts?

**Comment by sfshaza2** [comment]
I'm OK with not having these indicators.
