### ISSUE TITLE
Changes to JD on the showcase card

### ISSUE THREAD

**Issue by maguinis** [flutter/website#1710]
Please make the following changes:

-change JD.com -> JD Finance (this will be more accurate)
-JD iOS app on Flutter has not been published yet and will be scheduled to submit to app store next week. For now, can we change the download link to: https://m.jr.jd.com/spe/downloadApp/index.html?id=1024

**Comment by maguinis** [comment]
Please change "iOS" text to "Android" on the download section of JD Finance. The link for now only points to Android.

**Comment by fertolg** [comment]
Text has been changed to Android now.

**Comment by jijiah** [comment]
the iOS app is updated and could you please update the iOS app link to: https://itunes.apple.com/cn/app/id895682747

**Comment by chalin** [comment]
Oh, you had opened another issue for this (#1877). Closed by #1890.
