### ISSUE TITLE
getting started page has weird highlighting of anchor

### ISSUE THREAD

**Issue by gspencergoog** [flutter/website#1712]
When I went to the "getting-started" pages (https://flutter.io/docs/get-started/install/macos#get-the-flutter-sdk), I get some weird highlights on the anchor location:

![image](https://user-images.githubusercontent.com/8867023/48148783-72331e00-e26f-11e8-8173-4cfef838ca36.png)

(click on the link and then scroll up a bit).

I have Chrome Linux: 70.0.3538.77 (Official Build) (64-bit)

**Comment by sfshaza2** [comment]
Still true, even on a Mac (w/ Chrome).

**Comment by chalin** [comment]
Yeah, but it'll be tricky to fix unless we completely change the way we handle navigating to -- and the associated scroll adjustment of -- in-page anchors. Maybe @fertolg might have some insights.

**Comment by chalin** [comment]
(I'd say this is a p3)

**Comment by micpap25** [comment]
As a Chrome Windows user I don't have this problem, so maybe it was fixed at some point?

**Comment by chalin** [comment]
Interesting, I'm not seeing the problem either -- Chrome 84.x under macOS:
> ![image](https://user-images.githubusercontent.com/4140793/89695280-690e2f80-d8e1-11ea-9d2e-636729221bfc.png)

Yep, it must have been fixed.
