### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Twinber** [flutter/website#1713]
- [x] ./_site/animations/overview.html
  * External link https://docs.flutter.io/flutter/scheduler/SchedulerBinding-class.html failed: 404 No error
- [x] ./_site/flutter-for-react-native/index.html
  *  External link https://docs.flutter.io/flutter/widgets/SingleTickerProviderStateMixin-class.html failed: 404 No error
  *  External link https://docs.flutter.io/flutter/widgets/TickerProviderStateMixin-class.html failed: 404 No error
- [ ] ./_site/tutorials/interactive/index.html
  *  External link https://raw.githubusercontent.com/flutter/website/master/src/_includes/code/layout/tapbox-a/main.dart failed: 404 No error
  *  External link https://raw.githubusercontent.com/flutter/website/master/src/_includes/code/layout/tapbox-b/main.dart failed: 404 No error
  *  External link https://raw.githubusercontent.com/flutter/website/master/src/_includes/code/layout/tapbox-c/main.dart failed: 404 No error

**Comment by Twinber** [comment]
I correct the urls to its new version of the web, but the links are still broken

- https://flutter.io/docs/development/ui/animations/overview
  *  External link https://docs.flutter.io/flutter/scheduler/SchedulerBinding-class.html failed: 404 No error
- https://flutter.io/docs/get-started/flutter-for/react-native-devs
  *  External link https://docs.flutter.io/flutter/widgets/SingleTickerProviderStateMixin-class.html failed: 404 No error
  *  External link https://docs.flutter.io/flutter/widgets/TickerProviderStateMixin-class.html failed: 404 No error
- https://flutter.io/docs/development/ui/interactive
  *  External link https://raw.githubusercontent.com/flutter/website/master/src/_includes/code/layout/tapbox-a/main.dart failed: 404 No error
  *  External link https://raw.githubusercontent.com/flutter/website/master/src/_includes/code/layout/tapbox-b/main.dart failed: 404 No error
  *  External link https://raw.githubusercontent.com/flutter/website/master/src/_includes/code/layout/tapbox-c/main.dart failed: 404 No error

**Comment by chalin** [comment]
Thanks again for the detailed issue. The first two items were closed by #1740.
