### ISSUE TITLE
Missing redirects for /setup/

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1714]
There is no redirects for this URL: https://flutter.io/setup/

FYI: one of the entry points is on API docs' landing page --- install (https://flutter.io/setup/)

**Comment by kwalrath** [comment]
/setup/ is the #1 404, by far.

**Comment by chalin** [comment]
Closed by #1722. Thanks again Kathy!

(For the record, `/setup/` wasn't in the list of URLs I was given as a base to create the redirect rules from.)
