### ISSUE TITLE
Highlight official Google Groups instead of meetups in the Community page

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#1716]
Since both the flutter-dev and flutter-announce Google Groups are official means to communicate with Flutter users, I'd like them to be easier to find. Can we have them swap places with the meet-ups section? I'm not sure how many users can actually find a meet-up near them.

**Comment by sfshaza2** [comment]
Still true. This might require some design work.

**Comment by chalin** [comment]
Should be relatively easy to do. The main "challenge" is coming up with a pretty image to accompany the entry. How about of of these screenshots (of course, I can remove the border):

<img width="1108" alt="screen shot 2019-01-30 at 10 43 59" src="https://user-images.githubusercontent.com/4140793/51993140-41344500-247c-11e9-9ceb-f0d32d084063.png">

<img width="1108" alt="screen shot 2019-01-30 at 10 44 25" src="https://user-images.githubusercontent.com/4140793/51993139-41344500-247c-11e9-8830-a56b172d6e1a.png">

**Comment by sfshaza2** [comment]
I'm OK with that, theoretically, though I'm not sure we should show real people's names.

**Comment by chalin** [comment]
Actually, it might be nicer to put something nicer together using the Google logo and just a screenshot of the list on a phone.

Anyhow, I would say this is a p2. WDYT?

**Comment by sfshaza2** [comment]
SGTM

**Comment by InMatrix** [comment]
How about showing the landing page of Google Groups? 

![image](https://user-images.githubusercontent.com/348942/51999847-8bafc480-2470-11e9-998a-f9533387f8d4.png)

**Comment by sfshaza2** [comment]
I like it!
