### ISSUE TITLE
'Introduction to Widget testing' should document `flutter run` and `flutter test`

### ISSUE THREAD

**Issue by jamesderlin** [flutter/website#1721]
Page URL: https://flutter.io/docs/cookbook/testing/widget/
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/widget/index.md

1. https://flutter.io/docs/cookbook/testing/widget doesn't provide explicit instructions about how to run the test. (People who've read https://flutter.io/docs/cookbook/testing/unit should know, but I think it would be good to explicitly reiterate it here.)

2. It might not be obvious (especially to newbies like me) that widget tests can be run in an emulator via `flutter run test/FILE.dart`to observe what the test is doing, and it allows people to use hot-restart to do iterative test development.

**Comment by brianegan** [comment]
Yah, good point. I was surprised that you could run tests via `flutter run` when I first saw that!

Makes sense... I'll add these in.

**Comment by brianegan** [comment]
Heya @jamesderlin -- I've pushed a fix for this. Please let me know if that looks like a good introduction!

I didn't quite want to put all of the same instructions for running tests in an IDE, but let me know if you think that's necessary.

**Comment by brianegan** [comment]
As a heads up, I'm going to avoid merging that info until this issue is resolved: https://github.com/flutter/flutter/issues/24650

**Comment by jonahwilliams** [comment]
For the time being, I would count on my comment being the recommended approach. It certainly will never stop working, even when we fix this.

**Comment by brianegan** [comment]
Closing due to fix landing. Looks like a bug with the commit message that did not close this automatically.
