### ISSUE TITLE
Download and Archive pages make assumptions about beta being preferred channel

### ISSUE THREAD

**Issue by DanTup** [flutter/website#1723]
There are some assumptions in the code about `beta` being the most stable channel.

**Download Pages:**
https://flutter.io/docs/get-started/install/windows etc.
These use the `beta` branch to populate the version number on the download button:
https://github.com/flutter/website/blob/ec921b4c7314ed35164fdccffe7e764c03eb0e03/src/_assets/js/archive.js#L65

**Archive Page:**
https://flutter.io/docs/development/tools/sdk/archive
This page expects to find DOM elements with the channel names (though there's no release nodes)
https://github.com/flutter/website/blob/ec921b4c7314ed35164fdccffe7e764c03eb0e03/src/_assets/js/archive.js#L28

These should be updated in a way that works today but will automatically use the stable (`release`?) channel when it exists.

@chalin I don't mind looking at this, though it may make sense to wait until https://github.com/flutter/website/pull/1704 lands if it's imminent to avoid dealing with conflicts with the tweaks on those pages.

**Comment by sfshaza2** [comment]
I think that's a good solution, @chalin.

**Comment by DanTup** [comment]
That's definitely a simpler solution if someone can make the change at the right time. My main worry was that the archive page code may fail if not updated which would mean if there's a delay or people have the JS cached, it might break (I haven't actually confirmed that though - it may depend on whether any of the jQuery operations being performed would fail on an empty set).

**Comment by chalin** [comment]
> That's definitely a simpler solution if someone can make the change at the right time.

Yes, timing will be of the essence. I can handle that.

> page code may fail  ... if ... JS [is] cached

The site's assets are "fingerprinted" so a change in the JS will create a `main-<hash>.js` file with a new hash value (and hence a new file name), so folks visiting the archive page will be picking up the new JS.

**Comment by DanTup** [comment]
Ok cool. Let me know if you want me to look at any of this, otherwise I'll assume you've got it covered :-)

**Comment by chalin** [comment]
Yes, thanks, we should be good for now.

**Comment by chalin** [comment]
We're on stable and AFAICT all is well :). Closing
