### ISSUE TITLE
Jumping viewport when using leftnav

### ISSUE THREAD

**Issue by mit-mit** [flutter/website#1728]
When navigating to new pages in the leftnav, the view port jumps around. I'd prefer if the top banner would stay hidden, when navigating from a state where it was already scrolled out of view.

![jumpingviewport](https://user-images.githubusercontent.com/13644170/48428259-e8052100-e76a-11e8-92c0-3e930578bdf0.gif)

**Comment by sfshaza2** [comment]
@parlough, this seems like a very special use case (that doesn't bother me) and I'm thinking of closing this issue. What say you?

**Comment by parlough** [comment]
I think that's fine. Looks like https://github.com/flutter/website/issues/1667 is a better long-term solution.
