### ISSUE TITLE
Some alert boxes don't work

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#1735]
I tried to create a secondary alert box, like so:

{{site.alert-secondary.note}}
blah blah blah
{{site.alert.end}}

It didn't work. Then I tried all of the alert options listed in _config and only alert.note worked.

**Comment by chalin** [comment]
The `secondary` kind should only be used for callouts like "What's the point". If you want a Note, then use: `{{site.alert.note}}` at the start.

**Comment by chalin** [comment]
Then use {{site.alert.secondary}}.

**Comment by sfshaza2** [comment]
It works. Closing.
