### ISSUE TITLE
Drop `.html` suffix from canonical page link

### ISSUE THREAD

**Issue by chalin** [flutter/website#1738]
Firebase for the new website is configured to redirect to **clean URLs** (w/o `.html` suffices) and URLs with **no trailing suffixes**, canonical page URLs should be updated to reflect this. E.g.:

- https://flutter.io/docs/get-started/install is currently set to
  `<link rel="canonical" href="https://flutter.io/docs/get-started/install/">`
- https://flutter.io/docs/get-started/learn-more is currently set to
  `<link rel="canonical" href="https://flutter.io/docs/get-started/learn-more.html">`

This change will impact analytics, but it is best that we do this as early as possible (since the new site hasn't been put through its paces that much yet).

Are you ok with such a change @sfshaza2?

**Comment by sfshaza2** [comment]
Yes, as you said, earlier is better than later.
