### ISSUE TITLE
Add UI examples to the carousels

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1745]
From recent studies, participants wanted to see how UI of Flutter Showcase apps look like. However, the carousels shown below was not as informative as they expected.

![image](https://user-images.githubusercontent.com/5102864/48638323-2118dd80-e985-11e8-97e0-f5263c750fad.png)

The desire for visual UI examples on Showcase page was also mentioned in the previous study. This is a request (with @maguinis 's approval) to add an animated GIF (like the Reflectly GIF on the landing page) OR adding good-looking and clear screenshots to the top featured apps.

Just for inspiration, this is a random [showcase example](http://codeytech.com/site-templates/applify/demo-mobile-app-2.html) I found online that includes lots of screenshots.

**Comment by sfshaza2** [comment]
We no longer use that carousel and we avoid screenshots on the showcase page. Closing. Please reopen (and clarify) if it's still an issue.
