### ISSUE TITLE
Stretched/Squeezed Logos

### ISSUE THREAD

**Issue by nathfreder** [flutter/website#1750]
The new website is awesome, however I noticed that the "Who's using Flutter?" section has stretched logos. The AdWords and Google logos are the most noticeable as I see them daily. <img width="1308" alt="screen shot 2018-11-18 at 11 31 47 am" src="https://user-images.githubusercontent.com/40307305/48674705-8f94a180-eb25-11e8-8f79-6e209aee831d.png">

**Comment by nathfreder** [comment]
I have screenshotted the contents of `about:support` in Firefox.
<img width="1360" alt="screen shot 2018-11-18 at 5 44 54 pm" src="https://user-images.githubusercontent.com/40307305/48678437-c2f12380-eb59-11e8-8869-0d06f980d7ec.png">
<img width="1360" alt="screen shot 2018-11-18 at 5 44 42 pm" src="https://user-images.githubusercontent.com/40307305/48678438-c2f12380-eb59-11e8-9a5a-91b771867177.png">

**Comment by nathfreder** [comment]
@chalin

**Comment by chalin** [comment]
Yes, thanks. @fertolg should have a look shortly.

**Comment by nathfreder** [comment]
Fantastic!

**Comment by chalin** [comment]
@fertolg - could you take a look? I can confirm the behavior in FF, but it seems beyond my CSS fu :) /cc @kwalrath

**Comment by Cretezy** [comment]
Simply wrapping the images in a `div.col-4` instead of putting `col-4` directly on the images fixes this. Will open PR shortly with a fix!

**Comment by fertolg** [comment]
The fix in #2466 made the images overflow their containers, I'm reverting that change and reopening this issue.

Screenshot for reference:
![o0kmupkZ1qV](https://user-images.githubusercontent.com/2965170/54308565-7e1b4d80-458b-11e9-85e6-5c335878ca1d.png)

**Comment by nathfreder** [comment]
I noticed that too...

**Comment by micpap25** [comment]
It looks like this has been replaced on https://flutter.dev/showcase. This section no longer exists, so neither does this issue. This can be closed.

**Comment by sfshaza2** [comment]
Thanks, @micpap25!
