### ISSUE TITLE
'Preparing an iOS App for Release' page issue

### ISSUE THREAD

**Issue by beardo01** [flutter/website#1754]
Page URL: https://flutter.io/docs/deployment/ios.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/ios.md

` Upload to App Store…` button has now become `Distribute App`.

**Comment by micpap25** [comment]
This has been fixed. I think this issue can be closed.
`After the archive has been successfully validated, click Distribute App. You can follow the status of your build in the Activities tab of your app’s details page on App Store Connect.`

**Comment by beardo01** [comment]
Cheers @micpap25.
