### ISSUE TITLE
Add orientation lock instructions to 'Updating the UI based on orientation' page

### ISSUE THREAD

**Issue by feinstein** [flutter/website#1757]
Page URL: https://flutter.io/docs/cookbook/design/orientation.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/orientation.md

This page should also inform how to block the app from responding from screen orientation changes.

**Comment by brianegan** [comment]
Thanks for writing in! Just to be 100% clear so I know what to write: do you mean locking the app to landscape or portrait mode so the UI is not redrawn as the user rotates their device?

**Comment by feinstein** [comment]
Yes, perfect.

**Comment by brianegan** [comment]
Thanks! I'll add that info.

**Comment by feinstein** [comment]
PS: I really enjoyed your presentation on State Management. As soon as I have some spare time will dig into your state management examples.

**Comment by brianegan** [comment]
Woohoo! Thanks so much, that's wonderful to hear :)

**Comment by sfshaza2** [comment]
This hasn't been added yet.

**Comment by sfshaza2** [comment]
Please take a look, @miquelbeltran

**Comment by miquelbeltran** [comment]
The solution to define the preferred orientations supported by the app is fairly straightforward (e.g. in the `main()` method):

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);
  runApp(const MyApp());
}
```

However, this method does not appear to be used anywhere in the flutter.dev documentation, so it is probably a good idea to add an example somewhere, can be this recipe or another page.

In case we want to add it to this cookbook recipe, a note detailing that you can use this method, accompanied with the above short code example, should be enough to guide readers.

**Comment by miquelbeltran** [comment]
I will add an explanation on how to do this at the end of https://docs.flutter.dev/cookbook/design/orientation as a section.

**Comment by feinstein** [comment]
Thanks!
