### ISSUE TITLE
update the debugging page

### ISSUE THREAD

**Issue by devoncarew** [flutter/website#1763]
We should update the debugging page:

    https://flutter.io/docs/testing/debugging

- it doesn't mention source level debugging in IntelliJ, Android Studio, or VS Code; we should add info about it - currently, a reader of that page may assume that Flutter IDE don't support debugging
- it mentions the Observatory as one of the first debugging tools to try; we should instead list of further down in the page
- it doesn't mention the Inspector, but instead points people to using the command line to debug widget and render tree issues. We should instead reference the Inspector docs, and mention CLI options as also available

**Comment by devoncarew** [comment]
cc @Sfshaza

**Comment by sfshaza2** [comment]
Oy vey, still out of date.

**Comment by sfshaza2** [comment]
This has been fixed. I moved the DevTools docs to flutter.dev, and updated the debugging, profiling, inspector, etc pages.  PR https://github.com/flutter/website/pull/2796
