### ISSUE TITLE
'MacOS install' page issue-Deploying to physical iOS device

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#1776]
Page URL: https://flutter.io/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Specifically on 
https://flutter.io/docs/get-started/install/macos#deploy-to-ios-devices
it mentions  The following two steps are a temporary workaround to https://github.com/flutter/flutter/issues/22595
yet when i go there, the issue is closed.
**"temporary workaround" is not good for new people to see evaluating flutter if avoidable**
and 1.0 is so close...

thanks

**Comment by tvolkert** [comment]
The real fix here is to have usbmuxd update their homebrew formula to list `1.1.0` as stable.  Until they do, we need to tell users to install usbmuxd at HEAD.

**Comment by tvolkert** [comment]
We should update the website to say it's a workaround to https://github.com/Homebrew/homebrew-core/issues/34601 instead of flutter/flutter#22595
