### ISSUE TITLE
Add explanation about the comments in the default template to the Test Drive page

### ISSUE THREAD

**Issue by galeyang** [flutter/website#1803]
Page URL: https://flutter.io/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Description: 
In a recent user study, a participant at first didn't realize the comments in the default template has basic introduction of the code. She was looking for explanation in the docs. 

Can we add explanation about the comments in the default template? For example, at the end of "Create the app" section, add message like _The comments in the `main.dart` explain at a higher level of what each code block is trying to do._  (or something similar)

cc: @jayoung-lee @InMatrix

**Comment by chalin** [comment]
Hi all, PTAL at #1806 (and the link to the staging server).

**Comment by chalin** [comment]
I've merged, but let me know if you'd like any changes.
