### ISSUE TITLE
Adding "copied" feedback to Sample Code UI on API doc

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1817]
@galeyang commented on [Fri Nov 30 2018](https://github.com/flutter/flutter/issues/24886)

In recent study, on master channel's API doc (e.g. [actions](https://master-docs-flutter-io.firebaseapp.com/flutter/material/AppBar/actions.html)) we observed that participant was unsure if the sample code was successfully copied to clipboard --- after clicking on the copy all sample code button, she pressed ctrl + C again.

To further improve the usability of Sample code UI, we suggest this change: after clicking on it, show the message: "_Successfully copied to clipboard_". A brief messages popping up at the bottom of the screen (i.e. toast/[snackbar](https://material.io/design/components/snackbars.html#usage) in material design) should be enough.

cc: @jayoung-lee @gspencergoog @InMatrix

**Comment by chalin** [comment]
This repo doesn't house any infrastructure related to the generation of API docs. Where should this issue be transferred to @gspencergoog @galeyang? cc @sfshaza2

**Comment by galeyang** [comment]
@zoechi I think this issue is about API docs site [master channel], so I filed it under `flutter/flutter` instead of `flutter/website`. Could we move it back to https://github.com/flutter/flutter/issues/24886?

**Comment by gspencergoog** [comment]
Yes, it doesn't belong here: where Gale had it originally is probably the best place.  However, if the website is also going to implement the "copy this sample" button for the samples that appear on the website (as opposed to in the API docs), then they'll probably want this snackbar functionality too.

**Comment by zoechi** [comment]
Ok, I'll undo the move then. 
Didn't know this is not part of `website`.
