### ISSUE TITLE
'Working with long lists' page issue : "[...] display each String on it is own line."

### ISSUE THREAD

**Issue by NatoBoram** [flutter/website#1819]
Page URL: https://flutter.io/docs/cookbook/lists/long-lists.html
Page source: https://github.com/flutter/website/blob/master/src/docs/cookbook/lists/long-lists.md#2-convert-the-data-source-into-widgets

Description:

> This is where the ListView.builder will come into play. In our case, we’ll display each String on it's own line.

**Comment by chalin** [comment]
What is the issue exactly?

**Comment by NatoBoram** [comment]
It's means "it is". The sentence reads "we’ll display each String on it is own line". The correct word is "its", not "it is".

**Comment by chalin** [comment]
Right. Good catch, thanks!
