### ISSUE TITLE
docs.flutter.io missing open search description (doesn't tab-search in chrome)

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1823]
@eseidelGoogle commented on [Thu Oct 20 2016](https://github.com/flutter/flutter/issues/6412)

https://www.chromium.org/tab-to-search

Maybe this is a dartdoc bug?  Donno.  @sethladd 

---

@eseidelGoogle commented on [Wed Feb 08 2017](https://github.com/flutter/flutter/issues/6412#issuecomment-278482184)

This is likely an easy fix?

**Comment by chalin** [comment]
@sfshaza2 - is this repo the best place for API doc issues?

**Comment by sfshaza2** [comment]
No, Patrice. API doc bugs are filed in the SDK repo, as they are part of
the source docs and generated from the source docs.

**Comment by zoechi** [comment]
Ok, moving back to flutter/flutter.

**Comment by zoechi** [comment]
@sfshaza2 I'm working though [1. PRs with none of the classification labels](https://github.com/flutter/flutter/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+-label%3Aframework+-label%3Aengine+-label%3Atool+-label%3Aplugin+-label%3A%22d%3A+examples%22+-label%3A%22will+need+additional+triage%22+-label%3Ateam+-label%3A%22a%3A+tests%22+sort%3Aupdated-asc+) (from https://github.com/flutter/flutter/wiki/Triage) and I am struggling a bit which of these issues should be moved to flutter/website

> Bugs relating to the website should be moved to the `flutter/website` repo.

I would appreciate any feedback if it makes sense to move all issues with the labels `d: website - content` or `d: website - infra` to `flutter/website`.
Perhaps you could have a look at a few of them and provide some feedback why they would not belong to `flutter/website`.

Please also check the few issues in https://github.com/flutter/flutter/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22will+need+additional+triage%22++label%3A%22d%3A+website+-+content%22+

**Comment by sfshaza2** [comment]
@zoechi, I understand. This has been confused for awhile. Doc bugs against flutter.io (whether content or infrastructure) should be filed against flutter/website. Doc bugs again API docs OR wiki docs, should be filed against flutter/flutter.

Some people just use both tags, not really understanding the difference. Some ppl use the wrong tag. Some people use both tags, meaning that both doc sets need updating. In that case, there should be a bug filed against each repo. 

For example, this applies to both. We should have a lot more links to the cookbook, both from the API docs AND the website.  https://github.com/flutter/flutter/issues/17811 .  By the same token, we should have links from the API docs to relevant tutorials or videos. We should have links from the API docs to relevant widget videos.  For example.

Does this seem more clear?
