### ISSUE TITLE
'Flutter for Android developers' page issue

### ISSUE THREAD

**Issue by srkeshri-srk** [flutter/website#1825]
Page URL: https://flutter.io/docs/get-started/flutter-for/android-devs.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/flutter-for/android-devs.md

Description:

**Comment by chalin** [comment]
Thanks for filing an issue, but I’m going to close it for lack of a description. Feel free to reopen the issue once you have details to add.
