### ISSUE TITLE
Example code for adding an image doesn't actually show the image

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1826]
@goderbauer commented on [Tue May 09 2017](https://github.com/flutter/flutter/issues/9901)

I just learnt how to add an image to my app from https://flutter.io/assets-and-images/.

After pasting the example code from the "Loading images" section into my app, the app didn't actually show an image (I think I now understand why that is). It might be more useful/satisfying to include code in the example that actually shows the image when copied to get people started quicker. I ended up using `new Image.asset('assets/sunset.jpg')` to verify that the image would actually load in my app.

---

@goderbauer commented on [Tue May 09 2017](https://github.com/flutter/flutter/issues/9901#issuecomment-300005879)

This is what my `build` method looks like:

```dart
  @override
  Widget build(BuildContext context) {
    return new Image.asset('assets/sunset2.jpg');
  }
```

---

@HansMuller commented on [Tue May 09 2017](https://github.com/flutter/flutter/issues/9901#issuecomment-300241679)

Perhaps if the assets-and-images section pointed at a small working "sample app" in addition to providing code fragments, you'd have had less trouble (https://github.com/flutter/flutter/pull/9912).

---

@LarkAscending commented on [Sat Jun 03 2017](https://github.com/flutter/flutter/issues/9901#issuecomment-305940625)

Talking w/ @goderbauer root cause is the parent of the Image widget needs to actually have a size in order to display the image. So the code snippet for the build() method needs to include a parent-with-size.

---

@Hixie commented on [Sun Jun 04 2017](https://github.com/flutter/flutter/issues/9901#issuecomment-306016141)

The `Image` widget should size itself to the size of the image by default.

**Comment by micpap25** [comment]
Can this be closed? I'm pretty sure the merged PR fixes this.
