### ISSUE TITLE
People are confused when they search and find a webpage hosted on a staging server

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1827]
@sethladd commented on [Tue Nov 28 2017](https://github.com/flutter/flutter/issues/13227)

When PRs are submitted to Flutter's website, they often trigger a "staging server" to deploy the PR. Sometimes, search engines find these staging servers and return those results to users. This confuses the user, as they think they are looking at canonical docs but instead are looking at staging/test docs.

Strawman proposal:

* add robots.txt to every staging server (any server that is NOT flutter.io)
* add some JS that detects the user is NOT looking at flutter.io and puts up a banner of some sort

---

@sethladd commented on [Tue Nov 28 2017](https://github.com/flutter/flutter/issues/13227#issuecomment-347631257)

cc @mjohnsullivan @filiph

**Comment by chalin** [comment]
This shouldn't be an issue anymore. We disallow all robots (except our in-house link checker) on all staging servers. E.g., https://flutter-io-staging-1.firebaseapp.com/robots.txt cc @sfshaza2 

If it is still an issue, feel free to reopen.

**Comment by sfshaza2** [comment]
Definitely shouldn't be an issue anymore
