### ISSUE TITLE
Some black backgrounds in the website gif

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1828]
@xster commented on [Tue May 16 2017](https://github.com/flutter/flutter/issues/10119)

May need some more transparency masking

![screen shot 2017-05-16 at 11 25 36 am](https://cloud.githubusercontent.com/assets/156888/26121854/77f52f20-3a2a-11e7-8921-874061059228.png)

---

@sethladd commented on [Tue May 16 2017](https://github.com/flutter/flutter/issues/10119#issuecomment-301878080)

Thanks for filing! I'm not exactly sure how to get rid of this for an animated gif. Help wanted :)

---

@xster commented on [Tue May 16 2017](https://github.com/flutter/flutter/issues/10119#issuecomment-301883755)

There's a bunch of stuff we can do in post process http://www.imagemagick.org/Usage/anim_basics/ but it's probably easier to try to do it in the tool used to capture the screen since there's some blending already in the gif

**Comment by sfshaza2** [comment]
I know this is old, @xster, but is this still valid? If so, can you provide a link? (This was filed before the website rework.)

**Comment by xster** [comment]
Nop. The problematic asset has been changed on the website already.

**Comment by sfshaza2** [comment]
Thanks, @xster! Closing.
