### ISSUE TITLE
See if we can lint the firebase configs during Travis builds of website

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1829]
@sethladd commented on [Mon Oct 31 2016](https://github.com/flutter/flutter/issues/6597)

Right now, the Travis builds do not attempt to deploy the website or lint the config. This means that the firebase bits of the process ONLY trigger when Travis is ready to actually do the deploy.

We should look to see if we can lint the firebase config, to catch any errors during the PR process.

---

@eseidelGoogle commented on [Tue Nov 01 2016](https://github.com/flutter/flutter/issues/6597#issuecomment-257576031)

I don't see anyway to do that with the `firebase` tool.  It doesn't seem to have a dry-run option on `deploy` nor does it have any sort of linter.  Maybe there are some tricks to perform with the migrate command?
    tools:migrate [options]                    ensure your firebase.json format is up to date

**Comment by chalin** [comment]
Has this really been an issue? Or one that has happened frequently? 

Another solution would be to (smoke?) test flutter.io.

I'd suggest closing this issue for now. @sfshaza2 et all, any objections?

**Comment by sfshaza2** [comment]
That's fine.
