### ISSUE TITLE
Travis is slow when pushing commits to website

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1830]
@Sfshaza commented on [Wed Mar 29 2017](https://github.com/flutter/flutter/issues/9084)

My understanding from Seth is that Flutter pays Travis for parallel processing, but it doesn't seem to be used when pushing a commit to the website. It's sloooooow.

Can the site make use of parallel processing to speed it up?

---

@sethladd commented on [Wed Mar 29 2017](https://github.com/flutter/flutter/issues/9084#issuecomment-290174892)

There's a variety of things we can do. Agree that figuring out how to make a parallel website build is useful, and probably fairly straight forward.

We'll also want to profile the Travis website job, to see where the time is spent. For example, we spin up the analyzer quite a lot.

---

@LarkAscending commented on [Thu Dec 21 2017](https://github.com/flutter/flutter/issues/9084#issuecomment-353475176)

@Sfshaza After https://github.com/flutter/website/pull/659 is this still an issue? If not please close!

**Comment by chalin** [comment]
Travis take about 5-6 min. No seems to have been complaining recently :). Closing for now.
