### ISSUE TITLE
Could we auto-detect the user's OS and suggest which setup instructions they might want?

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1831]
@sethladd commented on [Fri Mar 31 2017](https://github.com/flutter/flutter/issues/9112)

If we detect the user is on Mac, we can auto-select "Mac" as the default choice of the green button, for the install instructions. The user can change the button's choice, of course, but it's a nice gesture to say "hey, you're on a mac (or windows, or linux), you might want the Mac instructions".

---

@eseidelGoogle commented on [Fri Mar 31 2017](https://github.com/flutter/flutter/issues/9112#issuecomment-290590191)

Does this conflict with the idea of wanting to make our instructions search engine discoverable?

---

@sethladd commented on [Fri Mar 31 2017](https://github.com/flutter/flutter/issues/9112#issuecomment-290604220)

I don't think so. Also, I realize my original description was less than ideal :) I'll update it. tldr: the intention is the default the green button to the user's OS.

Similar to these buttons here:

![capture](https://cloud.githubusercontent.com/assets/5479/24534834/3dcc7336-1585-11e7-9512-84c260fe7a33.PNG)

On this page: https://www.dartlang.org/install/archive

A nice select drop-down, but default to the user's OS.

**Comment by sampathbalivada** [comment]
Hey is it the instructions at [Flutter Docs](https://flutter.dev/docs/get-started/install) that we are talking about?
