### ISSUE TITLE
Clarify website contribution workflow.

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1832]
@sethladd commented on [Wed Feb 15 2017](https://github.com/flutter/flutter/issues/8187)

We realized we don't have the contribution workflow written down for the website. Let's add a CONTRIBUTING.md guide to make it clear and friendly.

Some of this content is in the README, but let's centralize it and flush it out.

---

@zoechi commented on [Mon Dec 03 2018](https://github.com/flutter/flutter/issues/8187#issuecomment-443783312)

Seems to be done https://github.com/flutter/website/blob/master/CONTRIBUTING.md
not sure though if there is still something to be done about "workflow"

**Comment by chalin** [comment]
Closed by #1605
