### ISSUE TITLE
The current 404 page for the website isn't helpful

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1833]
@danafergan commented on [Thu Jan 05 2017](https://github.com/flutter/flutter/issues/7359)

The current 404 page is a Firebase Page Not Found with directions for the host to replace it. Adding a 404.html page to the root would make it friendlier and give users a link back to an index usable page.

---

@sethladd commented on [Fri Jan 06 2017](https://github.com/flutter/flutter/issues/7359#issuecomment-270786427)

Great idea! Patches most welcome.

(is this for the docs or the website?)

**Comment by kwalrath** [comment]
The 404 page has been reimplemented in the new site, as you can see from https://flutter.io/404. Closing, but we welcome feedback on the new page.
