### ISSUE TITLE
Our website doesn't have a way to publish news

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1835]
@sethladd commented on [Sat Dec 10 2016](https://github.com/flutter/flutter/issues/7229)

We'd like to publish news every once in awhile. We'd like to publish news with a Flutter branded site/page of some sort. Examples of news might be updates to our dev cycle, updates to our IntelliJ plugins, big new features, etc.

These would be items bigger than a tweet, and more timely/announcement than a pure document.

---

@Hixie commented on [Sat Dec 10 2016](https://github.com/flutter/flutter/issues/7229#issuecomment-266157077)

From past experience one thing I'd be wary of with this is that you end up with pages that are stale. e.g. don't publish news for 2 months and now it looks like you've been out to lunch for 2 months.

---

@sethladd commented on [Sat Dec 10 2016](https://github.com/flutter/flutter/issues/7229#issuecomment-266157097)

We don't necessarily want to set up a whole blog: not sure how often we'll publish, and not excited to manage yet another site.

Perhaps we can use flutter.io's existing infrastructure, and add a "/news" subdirectory.

---

@sethladd commented on [Sat Dec 10 2016](https://github.com/flutter/flutter/issues/7229#issuecomment-266157405)

> don't publish news for 2 months and now it looks like you've been out to lunch for 2 months

Agreed. We need to ensure we can publish at some reasonable schedule.

An idea for a solution is to just email the mailing list whenever we have something to say.

---

@sethladd commented on [Sat Dec 10 2016](https://github.com/flutter/flutter/issues/7229#issuecomment-266157412)

cc @mit-mit 

---

@mit-mit commented on [Tue Dec 13 2016](https://github.com/flutter/flutter/issues/7229#issuecomment-266673682)

> An idea for a solution is to just email the mailing list

How many subscribers are there of that list?

---

@sethladd commented on [Thu Dec 15 2016](https://github.com/flutter/flutter/issues/7229#issuecomment-267464235)

361 members

**Comment by chalin** [comment]
We've been using the site banner to publish hot topics (e.g., Flutter Live announcement). There is also a place for "news" items on the main page. Closing for now. If that we have as part of the new website design isn't enough, feel free to reopen. cc @sfshaza2
