### ISSUE TITLE
Website infra: Document our use of lavish bootstrap and how to re-generate it

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1836]
@sethladd commented on [Wed Apr 26 2017](https://github.com/flutter/flutter/issues/9610)

Specifically:

* what is the file
* where did it come from
* what color scheme did we use
* what version of bootstrap is it based on ?
* how do we regenerate it?

---

@sethladd commented on [Mon May 15 2017](https://github.com/flutter/flutter/issues/9610#issuecomment-301350152)

Better yet, eliminate the need for lavish-bootstrap

---

@LarkAscending commented on [Fri Jun 09 2017](https://github.com/flutter/flutter/issues/9610#issuecomment-307252776)

It seems to be a [customized, unmaintained version of bootstrap CSS](http://www.lavishbootstrap.com/). It says "compatible with 3.3.4" but that doesn't mean that's the version it's based on. The original goal was to help you generate a theme based on the colors in a (hero) image.

We added it to flutter/website in [this commit](https://github.com/flutter/website/commit/48cff44fd56f7bba36122ef47b94b6e28d34725b). 

* Known dependencies (partial list):
   * size of the banner at the top of every page (the app bar)
   * margin for the left nav panel
   * font size
   * some icons (github?)
   * the dropdown button for setup.md

If we can refactor so we don't need it, we can link to the CDN for vanilla bootstrap in _includes/head.html.

Having one up-to-date version of bootstrap classes would help the Sample Catalog effort. [These classes in particular](https://getbootstrap.com/components/#media) aren't behaving as documented, since they're out of date.

The current version of (vanilla) bootstrap is 3.3.7. They're working on a [V4 alpha](https://v4-alpha.getbootstrap.com/). Maybe that would be a good goal...

---

@sethladd commented on [Fri Jun 09 2017](https://github.com/flutter/flutter/issues/9610#issuecomment-307448501)

> Having one up-to-date version of bootstrap classes would help the Sample Catalog effort

Sounds great. I fully support going to vanilla bootstrap. Thanks for looking into this!

**Comment by chalin** [comment]
We aren't using Lavish BS anymore. cc @sfshaza2

**Comment by sfshaza2** [comment]
I didn't even know that Lavish Bootstrap was a thing.
