### ISSUE TITLE
Easy to lose track of which section of an article a user is looking at

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1837]
@xster commented on [Mon May 08 2017](https://github.com/flutter/flutter/issues/9873)

Would be nice to have some floating outline/navigation bar for https://flutter.io/tutorials/layout since each section is often longer than a screen height tall. It's easy to lose track of which section I'm looking at and where it situates in the context of all sections. 

Would be nice to have the outline of the page follow you around as you scroll or have some pattern for secondary navigation

---

@sethladd commented on [Mon May 08 2017](https://github.com/flutter/flutter/issues/9873#issuecomment-299911564)

Not a bad idea. Can you link/screenshot me to a page that does what you're looking for?

---

@xster commented on [Tue May 09 2017](https://github.com/flutter/flutter/issues/9873#issuecomment-300025817)

Here's an example
https://developer.xamarin.com/guides/ios/getting_started/installation/device_provisioning/

---

@sethladd commented on [Tue May 09 2017](https://github.com/flutter/flutter/issues/9873#issuecomment-300054416)

The dartlang.org site does a good job of this: https://www.dartlang.org/guides/language/sound-dart

---

@xster commented on [Tue May 09 2017](https://github.com/flutter/flutter/issues/9873#issuecomment-300068916)

Oh ya, you're right. That one's totally great too

---

@Sfshaza commented on [Sat Oct 21 2017](https://github.com/flutter/flutter/issues/9873#issuecomment-338390596)

What about borrowing the solution from www.dartlang?

https://www.dartlang.org/guides/language/language-tour

**Comment by chalin** [comment]
Flutter/website now has a TOC on the right side of the page (which the view is wide enough). There are still some known issues (#1795), but those are being tracked separately. cc @sfshaza2
