### ISSUE TITLE
Decide on and author and accessibility guide for the website

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1838]
@sethladd commented on [Fri Mar 03 2017](https://github.com/flutter/flutter/issues/8546)

We should add to the README or CONTRIBUTING what our accessibility guidelines are for the website. How accessible should we make it?

* color contrast rules
* font size rules
* what tools we can use to check
* your_idea_here

**Comment by atsansone** [comment]
The remedy to this issue will come from https://github.com/flutter/website/pull/10054 and https://github.com/flutter/website/issues/9495. The color and contrast issues were resolved with https://github.com/flutter/website/issues/9531 and https://github.com/flutter/website/issues/9427.

Closing this as duplicate.
