### ISSUE TITLE
Author a style guide for the website snippets

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1839]
@sethladd commented on [Wed Mar 01 2017](https://github.com/flutter/flutter/issues/8497)

Snippets and examples on the website are authored for slightly different purposes that SDK code. However, snippets and examples should show best practices.

Some rules for website's code style:

* use dartfmt
* use trailing commas
* don't include inline comments (except ______ and ______)
* use var when you can infer the type via initialization
* use type annotations on the API
* use strong-mode

Updated:

* Don't mandate `@override`
* Don't mandate a return type on `createState()`

Maybe we can apply a "diff" from the SDK's style guide, and otherwise defer to the SDK style guide?

**Comment by MiraMarshall** [comment]
Closing because this issue has been addressed. https://github.com/dart-lang/site-shared/blob/main/doc/code-excerpts.md
