### ISSUE TITLE
Website HTML/CSS style guide

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1842]
@sethladd commented on [Wed May 31 2017](https://github.com/flutter/flutter/issues/10417)

For contributors from our community, we'd like to point them to an HTML/CSS authoring style guide.

This could be a Wiki on the flutter/website, if that's easy enough.

---

@eseidelGoogle commented on [Thu Jun 01 2017](https://github.com/flutter/flutter/issues/10417#issuecomment-305332049)

Perhaps https://google.github.io/styleguide/htmlcssguide.html?

**Comment by sfshaza2** [comment]
Wouldn't a markdown style guide be more useful?

**Comment by Dattax** [comment]
I'm happy to put this together with someone if there is general agreement over what the style guide should be. I can also look at the styles from the flutter website itself if that's a good way to get started.

**Comment by sfshaza2** [comment]
Do you mean coding style? Writing style? It's not clear to me.

**Comment by Dattax** [comment]
I assume that a style guide is meant to address the colors, look and feel (CSS), font-sizes, font-families...to create standardization as volunteers contribute to the overall project. If this is the case, happy to put something together. If this is not the case, no worries!
