### ISSUE TITLE
doc the packages/ references style in the assets section of the pubsepc

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1843]
@devoncarew commented on [Wed Jan 03 2018](https://github.com/flutter/flutter/issues/13874)

We should document the `packages/foo_package/asset_name` style in the asset docs at https://flutter.io/assets-and-images/. There's one example that uses a `packages/` reference, but we should make it clearer that this can be used to reference assets from other packages.

---

@zoechi commented on [Mon Dec 03 2018](https://github.com/flutter/flutter/issues/13874#issuecomment-443795321)

Is https://flutter.io/docs/development/ui/assets-and-images#bundling-of-package-assets enough?

**Comment by devoncarew** [comment]
Yes, I think so.
