### ISSUE TITLE
Website repository doesn't analyze intended dart code section

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1849]
@goderbauer commented on [Mon Apr 02 2018](https://github.com/flutter/flutter/issues/16158)

https://github.com/flutter/website/blob/master/tool/extract.dart doesn't analyze dart code sections which are intended, e.g. if you have the following in a markdown file, it will not be analyzed:

```markdown
* Some important bullet point illustrated with code:
  ```dart
  print("Hello World")
  ``
```

/cc @devoncarew

**Comment by chalin** [comment]
Hmm, I vaguely recall fixing this, but I'll have to double check.

**Comment by parlough** [comment]
Closing this since the old snippet extraction functionality is no longer used: https://github.com/flutter/website/issues/2233
