### ISSUE TITLE
add documentation for how to use the Flutter Inspector

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1851]
@devoncarew commented on [Mon Feb 05 2018](https://github.com/flutter/flutter/issues/14464)

We should update flutter.io to include docs about how to start and use the Flutter Inspector. This could be as part of the existing https://flutter.io/using-ide/ page, or a new top-level page, similar to https://flutter.io/hot-reload/.

Potential topics to cover:
- how to access / open  it
- how to use it - use cases and larger features
- additional useful items, like toggling the fps display or platform rendering from the inspector toolbar

/cc @mit-mit @Sfshaza @jacob314 

---

@devoncarew commented on [Mon Feb 05 2018](https://github.com/flutter/flutter/issues/14464#issuecomment-363155099)

(see also https://github.com/flutter/flutter-intellij/issues/1718)

**Comment by jacob314** [comment]
https://flutter.github.io/devtools/inspector
Now has up to date documentation.
