### ISSUE TITLE
AnimatedList Sample screenshot should be animated

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1859]
@goderbauer commented on [Fri May 04 2018](https://github.com/flutter/flutter/issues/17294)

I was staring at the screenshot on https://flutter.io/catalog/samples/animated-list/ for minutes waiting for it to move and show me the awesome animation of animated lists. Turns out, the screenshot is static 😞. It should really by an animation to show of what an *Animated*List looks like. 😀 

/cc @mit-mit @gspencergoog  

---

@Sfshaza commented on [Fri May 18 2018](https://github.com/flutter/flutter/issues/17294#issuecomment-390341114)

@HansMuller

**Comment by sfshaza2** [comment]
This page is deprecated, though your general point is valid. Closing.
