### ISSUE TITLE
'Preparing an iOS App for Release' page issue

### ISSUE THREAD

**Issue by tameemsafi** [flutter/website#1870]
Page URL: https://flutter.io/docs/deployment/ios.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/ios.md

Description: Image is overflowing.

![image](https://user-images.githubusercontent.com/15384037/49472019-4d967b80-f806-11e8-8610-2b0bb2a488e3.png)

You can add "max-width: 100%" to image tag and it should stop it from overflowing.

![image](https://user-images.githubusercontent.com/15384037/49472058-66069600-f806-11e8-81e7-b0a33190a620.png)

**Comment by chalin** [comment]
Yes, thanks for filing an issue. We've started a sweep of the site to address these issues.

**Comment by tameemsafi** [comment]
@chalin No problem, I submitted a pull request to fix it

**Comment by micpap25** [comment]
On my computer the issue is fixed. It looks like this should be closed.
