### ISSUE TITLE
Problems with translation on flutter's official website

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1876]
@shifeng1993 commented on [Wed Dec 05 2018](https://github.com/flutter/flutter/issues/24962)

![flutter io](https://user-images.githubusercontent.com/20181287/49485867-6db25300-f877-11e8-858b-66b85a187d8a.png)

Flutter is out.

what？

In China, the word means to be eliminated.

---

@MeowStone commented on [Wed Dec 05 2018](https://github.com/flutter/flutter/issues/24962#issuecomment-444335008)

分手吧，下一题

---

@39499740 commented on [Wed Dec 05 2018](https://github.com/flutter/flutter/issues/24962#issuecomment-444337831)

爱过，下一题

---

@chengenzhao commented on [Wed Dec 05 2018](https://github.com/flutter/flutter/issues/24962#issuecomment-444338866)

用过，下一题

**Comment by chalin** [comment]
@sfshaza2 @kwalrath - who can I assign such issues to? Also, is there a GH repo for the Chinese version of the site? If so, we should probably move the issue to that repo.

**Comment by zoechi** [comment]
If you don't know it's probably the same as https://github.com/flutter/flutter/issues/23754
I wasn't sure about the current status.

**Comment by kwalrath** [comment]
cc @mjohnsullivan @InMatrix @xster 

On site-www, I'm marking bugs like these with the [localization label](https://github.com/dart-lang/site-www/issues?q=is%3Aissue+is%3Aopen+label%3Alocalization), but this seems much more urgent!

**Comment by InMatrix** [comment]
Who can update the CN site? The correct translation should be "Flutter 1.0已经发布了！“

**Comment by kwalrath** [comment]
I have a name of someone who can do it. Emailing him now...

**Comment by kwalrath** [comment]
Where does this bad translation appear, @shifeng1993? It isn't on the site we point to, which is https://flutter-io.cn.

**Comment by shifeng1993** [comment]
@kwalrath  Yes, please forgive me for sleeping last night。The problem does arise in the automatic translation of flutter.io into Chinese.

**Comment by kwalrath** [comment]
Thanks for the report @shifeng1993. You are forgiven for sleeping. :)
