### ISSUE TITLE
JD Finance iOS app download link update

### ISSUE THREAD

**Issue by jijiah** [flutter/website#1877]
JD Finance showcase (https://flutter.io/showcase) iOS app download link has been ready, please help to update to https://itunes.apple.com/cn/app/id895682747

**Comment by chalin** [comment]
As you can see from this [recent Travis log](https://travis-ci.org/flutter/website/jobs/464932484), the link you gave now results in a 404:

```
https://itunes.apple.com/cn/app/id895682747 (HTTP 404)
```

So I'll remove the link to the App Store. Once you have an updated link, please post it here.

**Comment by chalin** [comment]
cc @kwalrath @sfshaza2

**Comment by jijiah** [comment]
It seems it is available in China (app store ), as screenshot enclosed.

**Comment by chalin** [comment]
You are correct, the link works now. I'll add it back (but also include it in the skip list). cc @kwalrath

**Comment by chalin** [comment]
Closed by #1944
