### ISSUE TITLE
The search form should not be listed in search results for "search"

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1881]
@zoechi commented on [Mon Jul 09 2018](https://github.com/flutter/flutter/issues/19170)

I was looking for a search widget and got

![image](https://user-images.githubusercontent.com/405837/42465775-4026a592-83ad-11e8-84a5-8c925ae3bb32.png)

which I found quite confusing

**Comment by chalin** [comment]
I'm not sure that it is worth the effort to handle this as a special case. The same page shows up in a regular (non-site specific) Google search. I'm closing this for now. If you feel strongly about it, please reopen. cc @sfshaza2
