### ISSUE TITLE
We need screenshots on the framework tour page

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1882]
@Hixie commented on [Fri Oct 21 2016](https://github.com/flutter/flutter/issues/6446)

---

@sethladd commented on [Fri Mar 17 2017](https://github.com/flutter/flutter/issues/6446#issuecomment-287475073)

What problem are we addressing?  (just want to ensure we put the correct screenshots on there :)

---

@sethladd commented on [Wed Mar 29 2017](https://github.com/flutter/flutter/issues/6446#issuecomment-289932639)

@Hixie do you remember what this was intended to help improve? Not sure how to help deliver sufficiency, given the title. Thanks for any background!

---

@Hixie commented on [Wed Mar 29 2017](https://github.com/flutter/flutter/issues/6446#issuecomment-289933553)

I think this was just about having ANY screenshots on this page:
   https://flutter.io/widgets-intro/
...to orient the reader and show them various widgets.

---

@sethladd commented on [Wed Mar 29 2017](https://github.com/flutter/flutter/issues/6446#issuecomment-289933620)

Ah, that we can do! :)

---

@sethladd commented on [Tue May 09 2017](https://github.com/flutter/flutter/issues/6446#issuecomment-300281107)

Unlikely to do in time for M2, sorry. If someone wants to grab this, great!

---

@Sfshaza commented on [Wed Jul 11 2018](https://github.com/flutter/flutter/issues/6446#issuecomment-404059627)

I'd like to use @gspencergoog's s/w to do this, if we can.

**Comment by MiraMarshall** [comment]
Closing because this issue has been addressed.
