### ISSUE TITLE
Change guide for Get Started: Install on Linux to install Android SDK and not Android Studio

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1883]
@lascarayf commented on [Tue Apr 10 2018](https://github.com/flutter/flutter/issues/16404)

From URL: https://docs.flutter.dev/get-started/install/linux

Add instructions to install Android SDK and not a full IDE like Android Studio.

Flutter would have to be tool agnostic.

**Comment by atsansone** [comment]
At this time, the full Android Studio install along with the SDK and Emulator is required. Closing this issue.
