### ISSUE TITLE
'Cookbook' page feature request

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#1891]
Page URL: https://flutter.io/docs/cookbook/
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/index.md

Description:
I think the recipes and flutter.io documentation are awesome.. Also - I propose a more common/real-world cookbook recipe for fetch+json to compare apples-to-apples with
https://facebook.github.io/react-native/docs/network

Thanks for the great work!

--
PS I'm so sorry you got three bugs with no issue/details. thank you so much for giving us an easy way to file requests at the top of each page, I really appreciate it.

**Comment by brianegan** [comment]
Hey there, thanks for writing in. Could you please describe in a bit more detail which additional info / recipes you'd like to see?

Right now, we have four different recipes on networking that go over much of the same content as found on the react native site, such as making http requests, parsing json, showing a loading spinner while the results are loading and then displaying the results when the http call competes, and working with web sockets. Therefore, it'd be helpful to hear specifically what you think we're missing or perhaps a problem you've run into and would like to see a recipe for. 

Thanks!

**Comment by sfshaza2** [comment]
I defer to @brianegan on this. I don't believe we need to demonstrate every
possible combination of features, but maybe there's some bit here that we
can demonstrate, if it makes sense..

**Comment by petermichaux** [comment]
I agree that more Networking documentation is a good idea but this issue is too vague. I think this issue can be closed. @brianegan @sfshaza2

**Comment by sfshaza2** [comment]
SG!
