### ISSUE TITLE
Clean up `_data/catalog/widgets.json` and `index.json`

### ISSUE THREAD

**Issue by chalin** [flutter/website#1897]
For example, the `image` field should be a URL to an image, not an image element. In cases where we'd like to use an embedded SVG, that should be assigned to field other than `image` (maybe `svg` :).

Also, we should consider at least partly generating the data used in this list.

**Comment by chalin** [comment]
@Hixie - any comments about this?

**Comment by micpap25** [comment]
Hi @chalin ,
I can definitely work on this; is this still something that should be done?
