### ISSUE TITLE
Project: Copy edit pass

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#1898]
I could do a site survey and use analytics to help us determine what work to do and how to prioritize it.

**Comment by sfshaza2** [comment]
@kwalrath, what did you have in mind here? I'm tempted to close this issue.

**Comment by kwalrath** [comment]
Or... I could do the analytics and have our new editor work on improving the most visible pages when we don't have other work.

**Comment by sfshaza2** [comment]
Oh, I see. That is an interesting idea!

**Comment by kwalrath** [comment]
I'm looking at analytics today anyway, so I'll do a first pass and then give it to you, so you can prioritize.
