### ISSUE TITLE
Pages w/o TOCs still leave room for a TOC

### ISSUE THREAD

**Issue by chalin** [flutter/website#1901]
Pages w/o TOCs still leave room for a TOC when the page is wider than or as wide as 1440px. E.g., see https://flutter.io/docs/reference/tutorials:

## Width > 1440px

> <img width="1443" alt="screen shot 2018-12-05 at 15 34 24" src="https://user-images.githubusercontent.com/4140793/49542447-9a7c5f80-f8a3-11e8-8d27-767cfb8f8a95.png">

## Width < 1440px

> <img width="1438" alt="screen shot 2018-12-05 at 15 38 50" src="https://user-images.githubusercontent.com/4140793/49542544-e8916300-f8a3-11e8-8fd5-521c72616c43.png">

---

Most likely a breakpoint that is using the wrong key.

**Comment by chalin** [comment]
Btw, pages that actually have TOCs (like the [codelab](http://localhost:4002/docs/get-started/codelab)), aren't affected by the 1440px breakpoint.

**Comment by sfshaza2** [comment]
This has been fixed.
