### ISSUE TITLE
'Using packages' page issue

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#1906]
Page URL: https://flutter.io/docs/development/packages-and-plugins/using-packages.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/packages-and-plugins/using-packages.md

Description:
When I have an issue with cocoapods missing but try to use platform plugins and run on iOS simulator it says
```
Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
  For more info, see https://flutter.io/platform-plugin
```
this link https://flutter.io/platform-plugins redirects to the top of this page, which is confusing.
It should redirect to somewhere more directly useful and helpful related to plugins

on a related note - doing a control-f for find on this page for "plugin" shows the usage a bit fuzzy - the term plugin and package are used interchangeably at certain points.

I realize this is low priority, but just a point with a little room for clarification, especially in a case where packages work on both iOS and Android and plugins work only on Android in the case of an Android developer trying flutter that hasn't setup an iOS toolchair, or, if i understand correctly, any flutter dev with Windows or Linux or Chrome?

thanks

**Comment by neiljaywarner** [comment]
see https://github.com/flutter/flutter/issues/24875

**Comment by sfshaza2** [comment]
I've had similar issues.
