### ISSUE TITLE
Match IDE-created plugin template with code in 'Writing custom platform-specific code' page

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1913]
@InMatrix commented on [Fri Feb 16 2018](https://github.com/flutter/flutter/issues/14739)

## Steps to Reproduce

When I created a plugin project using Android Studio's project wizard, the resulting code is quite different from starting from a default Flutter project used in [the platform channel doc](https://docs.flutter.dev/platform-integration/platform-channels?tab=type-mappings-java-tab). As someone who's learning to write a plugin for the first-time, I felt the doc was less useful when I started my flow from the plugin template offered by the IDE. Can we update the doc to reflect the plugin authoring flow in the IDE? Since Android Studio is necessary to write Android-side of things, it seems that starting from a CLI-based flow is not really useful.

Cc: @mit-mit 

---

@mit-mit commented on [Fri Feb 16 2018](https://github.com/flutter/flutter/issues/14739#issuecomment-366210504)

The platform channel docs were written with the assumption that the channel code is being added to an app, not a plugin, see 'Step 1: Create a new app project':
https://flutter.io/platform-channels/#example-project

The docs for creating a plugin are:
https://flutter.io/developing-packages/

But I agree that this is getting confusing, and would benefit from being cleaned up. I personally unfortunately do not have bandwidth for this at the moment.

---

@InMatrix commented on [Sun Feb 18 2018](https://github.com/flutter/flutter/issues/14739#issuecomment-366486850)

I see. Related to this, [the plugin doc](https://flutter.io/developing-packages/#step-2d-connect-the-api-and-the-platform-code) refers to the platform channels doc for adding platform specific code:

![image](https://user-images.githubusercontent.com/348942/36347079-f99884f2-1402-11e8-8724-3f9fb6a896dd.png)

Yet, the platform channels doc starts from an app template instead of a plugin template. 

---

@Sfshaza commented on [Mon Jun 11 2018](https://github.com/flutter/flutter/issues/14739#issuecomment-396099370)

@InMatrix, can we close this?

---

@InMatrix commented on [Mon Jun 11 2018](https://github.com/flutter/flutter/issues/14739#issuecomment-396379429)

I think the confusion still exists. The main problem here is that the Plugins doc sends the user to the Platform Channels doc at Step 2d, where the user will have created the plugin template already. But the example in Platform Channels doc has a quite different boilerplate, so the user needs to figure out how to proceed on their own. 

---

@Sfshaza commented on [Sat Jul 21 2018](https://github.com/flutter/flutter/issues/14739#issuecomment-406809388)

Yup, needs to be fixed.

**Comment by atsansone** [comment]
This page has been updated multiple times in the past 5.5 years. The issue as described can no longer be identified. Closing this issue. If this issue is still a concern, please file a new issue indicating the current pages and sections that apply and need remediation. Thanks!
