### ISSUE TITLE
Issue from website page Get Started: Install on Windows

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1914]
@u2arejust2cute commented on [Tue Jul 17 2018](https://github.com/flutter/flutter/issues/19479)

From URL: https://flutter.io/setup-windows/

For the international users, it is very helpful to know that "Control Panel > ..." means "In Windows, go to Control Panel". This could be anywhere.

Secondarily, it should mention somewhere to use the 'flutter config' command to set the sdk path in case it was already installed.

Not related to these issues: I am not sure how legal it is to make users accept agreements they can't read fully because the flutter command line can't show all of their text.

---

@u2arejust2cute commented on [Tue Jul 17 2018](https://github.com/flutter/flutter/issues/19479#issuecomment-405710693)

And while I am at it: Is or isn't ANDORID_HOME depreciated? Because it shows up in the flutter doctor and on the website and it is supposedly no longer used.

---

@xster commented on [Wed Jul 25 2018](https://github.com/flutter/flutter/issues/19479#issuecomment-407614079)

We may need to multiplex these instructions with various Windows versions too. For instance "Control Panel > User Accounts > User Accounts > Change my environment variables" may not exist in the newest version of Windows.

**Comment by MiraMarshall** [comment]
Closing because this issue is out of date.
