### ISSUE TITLE
Make Flutter Docs Microsoft Edge Friendly

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1915]
@bramvbilsen commented on [Sat Apr 21 2018](https://github.com/flutter/flutter/issues/16849)

Currently, the documentation website for Flutter([https://docs.flutter.io/](https://docs.flutter.io/)) does not work well on Microsoft Edge. Call me crazy, but I actually really enjoy Edge as a web browser. And it is inconvenient that I have to have two web browsers open just to browse the docs.
Anyways, whether you like Edge or not, searching in the docs (via the search bar) leads to the following error page:
![capture](https://user-images.githubusercontent.com/16825392/39088535-33eaf896-45b4-11e8-8de8-59706d8b13ff.PNG)
This should not happen.

---

@Hixie commented on [Sun Apr 22 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-383358977)

Probably a bug in Edge?

---

@bramvbilsen commented on [Sun Apr 22 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-383359216)

I can't think of any other website that has this behavior on Edge.

---

@miyoyo commented on [Sun Apr 22 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-383408538)

This URL doesn't work on chrome either.

Your url is https://docs.flutter.io/flutter/widgets/widgets/Text-class.html , whereas it should be https://docs.flutter.io/flutter/widgets/Text-class.html

---

@bramvbilsen commented on [Mon Apr 23 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-383420160)

Didn't even notice that! I guess that is the problem then, the search URL doesn't get created properly on Edge 😪

---

@miyoyo commented on [Mon Apr 23 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-383574026)

Behaviour is caused because of this
![applicationframehost_2018-04-23_15-12-53](https://user-images.githubusercontent.com/3525610/39128730-d840bd04-4708-11e8-868e-aa781551f2f5.png)
Which calls a script (script.js) which does this:
![Script](https://i.imgur.com/FL7QxWM.png)

I'm not sure why chrome keeps the "/flutter/" and cuts everything else after that, but edge just changes the top level element

So either edge implements it correctly and chrome is wrong, both are wrong or there is some javascript magic I'm not aware of that keeps the "/flutter/" in the URL

EDIT:
I forgot to say that chrome has the same values as edge in the javascript
![Chrome](https://i.imgur.com/XQeJAU5.png)

---

@Hixie commented on [Mon Apr 23 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-383676251)

Edge is wrong. 

Setting `window.location` goes through this: https://html.spec.whatwg.org/#dom-location-href
This refers to the base URL set here: https://html.spec.whatwg.org/#script-settings-for-window-objects
...which, if you follow it through, is the document's URL.

So setting window.location should parse the URL relative to the document's URL, which means the
`/widgets/` should remain.

---

@bramvbilsen commented on [Fri Apr 27 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-385081058)

Not sure why "widgets" was in the url twice, but I tried searching again and it generated this url: [https://docs.flutter.io/flutter/widgets/foundation/Listenable-class.html](url)
I'm getting the same error page.

---

@bramvbilsen commented on [Fri Apr 27 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-385083502)

I did some more testing and noticed the following behavior:

- Searching `Listenable` from [https://docs.flutter.io/](https://docs.flutter.io/) leads me to [https://docs.flutter.io/foundation/Listenable-class.html](https://docs.flutter.io/foundation/Listenable-class.html)
- Searching from [https://docs.flutter.io/flutter/widgets/Text-class.html](https://docs.flutter.io/flutter/widgets/Text-class.html) leads me to [https://docs.flutter.io/flutter/widgets/foundation/Listenable-class.html](https://docs.flutter.io/flutter/widgets/foundation/Listenable-class.html)

---

@Hixie commented on [Tue May 01 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-385589383)

On Edge, or in every browser?

---

@bramvbilsen commented on [Tue May 01 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-385647279)

Just Edge 😥

---

@escamoteur commented on [Fri May 04 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-386572456)

Even if Edge is wrong this throws a bad light on Flutter if user use Edge

---

@bramvbilsen commented on [Fri May 04 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-386590131)

Exactly, the user shouldn't have to worry about the browser (s)he uses.

---

@Hixie commented on [Sat May 05 2018](https://github.com/flutter/flutter/issues/16849#issuecomment-386755234)

Sure, I'm just trying to figure out what kind of issue we should be looking for though when fixing it.

**Comment by kwalrath** [comment]
Is this still an issue in the new website?

**Comment by miyoyo** [comment]
[Yes, still fails](https://i.imgur.com/DC9u5NW.gifv)

However, microsoft is replacing edge with [Project Anaheim](https://bit.ly/2PnW8Xo), so is this still a major bug?

**Comment by kwalrath** [comment]
Thanks for the info, @miyoyo! I just checked analytics, and only a tiny percentage of our readers use Edge. Considering that Edge seems to be on its way out, I'm going to close this issue.
