### ISSUE TITLE
Building Layouts in Flutter: label in image in unclear/wrong

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1917]
@gggustafson commented on [Sun Jul 29 2018](https://github.com/flutter/flutter/issues/19956)

From URL: https://flutter.io/tutorials/layout/

In the second figure, the caption to the right that reads "Column" should read "Rows"

---

@zoechi commented on [Thu Dec 06 2018](https://github.com/flutter/flutter/issues/19956#issuecomment-444870497)

I assume you mean the "Column" to the left of 

![image](https://user-images.githubusercontent.com/405837/49595080-89048780-f977-11e8-8c8e-78fbba4fc3dd.png)

**Comment by gggustafson** [comment]
No. I mean the word "column" to the left of the figure. I believe that it should read "Rows"

**Comment by zoechi** [comment]
Thanks for the hint. I updated the screenshot to make it more clear. The yellow highlighted word was just because I had searched the page for `column` before.

**Comment by chalin** [comment]
As possible fixes I propose to either:

- Remove the mention of "Column" in the figure, since the entire figure is the column. Or, 
-Change the label to read "Column elements"

Thoughts? cc @sfshaza2 @kwalrath

**Comment by gggustafson** [comment]
@chalin I like removing option.
