### ISSUE TITLE
Flutter Widget Framework Tour: add images of the resulting UI

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1918]
@ernestsaunders commented on [Tue May 22 2018](https://github.com/flutter/flutter/issues/17810)

From URL: https://flutter.io/widgets-intro/

As a first time user of Flutter, I think that this page describing the Widget Framework could be even better if visuals of the resulting UI were included for each code sample.  I'd like to see at a quick glance what the code will do without having to go through each code sample.  Seeing a visual would let me say "yeah! That's really similar to the structure that I want to build!  I'm gonna read more!".

**Comment by MiraMarshall** [comment]
Closing because this issue has been fixed. There is a run button where users can view the executed code. 
![Screen Shot 2022-06-09 at 11 47 58 AM](https://user-images.githubusercontent.com/23406866/172901327-73a656a7-8ef3-4252-ac20-8c09a4696d7d.png)
