### ISSUE TITLE
Add CupertinoPopupSurface to widget catalog

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1920]
@matthew-carroll commented on [Wed Aug 15 2018](https://github.com/flutter/flutter/issues/20651)

Add CupertinoPopupSurface to widget catalog after merging #20397

**Comment by chalin** [comment]
While https://github.com/flutter/flutter/issues/20397 isn't closed, I don't think that we need to wait because:

- https://docs.flutter.io/flutter/cupertino/CupertinoDialog-class.html has been deprecated
- https://docs.flutter.io/flutter/cupertino/CupertinoPopupSurface-class.html exists
