### ISSUE TITLE
Issue from website page Writing custom platform-specific code with platform channels

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1921]
@NickoftheSouth commented on [Wed Aug 15 2018](https://github.com/flutter/flutter/issues/20612)

From URL: https://flutter.io/platform-channels/

My issue with this is it seems to be missing any details of calling method channels from the native side.

For example if you wanted to receive updates from push notifications and then pass them back into dart.

There doesn't seem to be any easy to find, clear, examples on how to do this for all platforms.
If there is another article which details this it should be linked here.

**Comment by MiraMarshall** [comment]
Closing because this issue has been addressed. https://docs.flutter.dev/development/platform-integration/platform-channels#example
