### ISSUE TITLE
Add Flutter to existing apps - missing switch statement in main.dart

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1922]
@clearpath commented on [Tue Aug 14 2018](https://github.com/flutter/flutter/issues/20567)

Page https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps says

> Above we use the string "route1" to tell the Dart code which widget to display in the Flutter view. The lib/main.dart file of the Flutter module project template contains a switch on the provided route string.

There is no such switch in `main.dart` file when module is generated.

**Comment by chalin** [comment]
@zoechi - this is a flutter/wiki issue. Closing this issue (but I'll let you reopen the original).

**Comment by zoechi** [comment]
You are right of course. Time for a break!

**Comment by chalin** [comment]
👍 Thanks for your tireless efforts!
