### ISSUE TITLE
Update the Google Adwords logo to Google Ads

### ISSUE THREAD

**Issue by maguinis** [flutter/website#1927]
Proper images can be found here -> https://sites.google.com/corp/google.com/ads-platforms-brand-standards/google-ads/logos?authuser=0

Please change the current logo on "Who uses Flutter" in the homepage since it's no longer called AdWords to the product logo image in that first link. 

Thanks!

**Comment by chalin** [comment]
Thanks Martin. The following table (taken from [here](https://designguidelines.withgoogle.com/ads-branding/google-ads/logos.html)) suggests we should be using (B):

> ![ads-logo_table](https://user-images.githubusercontent.com/4140793/49608395-8fd6ce80-f966-11e8-83f6-703cdad8b62c.png)

What is your final call?

**Comment by chalin** [comment]
#1931 uses the image you added earlier.

Here is what it would look like using (B):

<img width="1289" alt="screen shot 2018-12-06 at 15 30 12" src="https://user-images.githubusercontent.com/4140793/49610199-dda20580-f96b-11e8-9021-692df0283322.png">

cc @kwalrath

**Comment by maguinis** [comment]
Ok, B works. Good catch, thanks!
