### ISSUE TITLE
"Creating a new project from existing source code" guidance is not valid anymore

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1928]
@zoechi commented on [Thu Dec 06 2018](https://github.com/flutter/flutter-intellij/issues/2923)

@haqqi commented on [Fri May 18 2018](https://github.com/flutter/flutter/issues/17707)

From URL: https://flutter.io/using-ide/

Because the recent Flutter plugin for Android Studio, the guide for importing existing code is not valid anymore. I cannot find any menu of creating Flutter using existing code. If i try to create new Flutter app, it will show error if the existing folder exists.

Any idea how to import existing project properly in Android Studio?

![image](https://user-images.githubusercontent.com/831763/40207686-0669ba2c-5a60-11e8-9e67-5e13547a6740.png)

---

@skota commented on [Fri May 18 2018](https://github.com/flutter/flutter/issues/17707#issuecomment-390091569)

Hmm!....i just clicked 'open an existing android studio project'.

Disclaimer: I am an absolute beginner with flutter. Pls ignore if my answer above is not relevant.

---

@zoechi commented on [Fri May 18 2018](https://github.com/flutter/flutter/issues/17707#issuecomment-390111645)

Please add the output of `flutter doctor`

---

@haqqi commented on [Fri May 18 2018](https://github.com/flutter/flutter/issues/17707#issuecomment-390259574)

```
PS C:\Users\Haqqi> flutter doctor -v
[√] Flutter (Channel beta, v0.3.2, on Microsoft Windows [Version 10.0.17134.48], locale en-US)
    • Flutter version 0.3.2 at D:\development\flutter
    • Framework revision 44b7e7d3f4 (4 weeks ago), 2018-04-20 01:02:44 -0700
    • Engine revision 09d05a3891
    • Dart version 2.0.0-dev.48.0.flutter-fe606f890b

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at D:\development\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = D:\development\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 24.2.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] Connected devices (1 available)
    • ONEPLUS A3003 • 192.168.1.8:5555 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

NB: i did not say that `Open an existing Android Studio project` does not work. It works, but not perfectly just like when i created a new project of Flutter. For example, the project file browser is not displaying correct list.

So, what i did to continue existing project is:

1. Create new Flutter project, then close the Android Studio
2. Copy-Paste and replace my existing project to the new project
3. Open Android Studio again.

In the end, this issue is addressed to the both of guide page, and maybe flutter plugin for Intellij.

---

@zoechi commented on [Thu Dec 06 2018](https://github.com/flutter/flutter-intellij/issues/2923#issuecomment-444877403)

Not sure which one should be fixed - website or functionality

---

@stevemessick commented on [Thu Dec 06 2018](https://github.com/flutter/flutter-intellij/issues/2923#issuecomment-444967748)

Is this a problem with 1.0? If not, then this issue can be closed. Project format got an overhaul in the run-up to 1.0.

---

@zoechi commented on [Thu Dec 06 2018](https://github.com/flutter/flutter-intellij/issues/2923#issuecomment-444970144)

@stevemessick no, the original issue is from May 2018. I just moved it over here.
Then I'll move it to flutter/website to get the instructions updated.
So creating a project from existing source is not supported anymore like explained in https://flutter.io/using-ide/ ?

---

@stevemessick commented on [Thu Dec 06 2018](https://github.com/flutter/flutter-intellij/issues/2923#issuecomment-444976943)

In the screenshot posted by the OP the third option is how you open an existing project in Android Studio. So, if you used `flutter create` to create a project, that's what you'd want. I think the web instructions may have been written for IntelliJ, because Android Studio doesn't have that option. @pq, does this sound familiar?

**Comment by zoechi** [comment]
It seems (checked on my system) this section https://flutter.io/docs/development/tools/android-studio#creating-a-new-project-from-existing-source-code is for IntelliJ only but not for AS.
Might be worth adding a hint to avoid confusion.

**Comment by admarwick** [comment]
We users of Android Studio would be very happy if we could create a working flutter project from github without having to create a virgin project and copy in source files by hand.

**Comment by atsansone** [comment]
@anderdobo : Would this still be a needed change?

**Comment by stevemessick** [comment]
@atsansone The instructions are incorrect. If you have a Flutter app (or any project) and you want to open it in Android Studio:
- From the Welcome screen (when no other project is open), click `Open` at the top
- From an existing project window, use the menu `File > Open...`

**Comment by anderdobo** [comment]
@atsansone yes, we need updates here.
I don't know what the page  said in 2018, however I see two separate issues discussed here and that I see on the [Android Studio/IntelliJ page](https://docs.flutter.dev/tools/android-studio) today:

1. Opening an existing project

- The section currently titled "Creating a new project from existing source code" should be re-titled to "Opening a project from existing source code" similar to on the VS Code page [here](https://docs.flutter.dev/tools/vs-code#opening-a-project-from-existing-source-code).
- The instructions are incorrect and should be about opening a project not creating a new project.

2. The steps for creating a new project are slightly different between IntelliJ and Android Studio. We should lay the steps out separately for each of these IDEs.
