### ISSUE TITLE
Add app highlight reel to our flutter.io/showcase page

### ISSUE THREAD

**Issue by maguinis** [flutter/website#1929]
Either via a button or a new card - would be great to have this video accessible on flutter.io/showcase -> https://youtu.be/REJDzio_h7o

**Comment by chalin** [comment]
PTAL at #1942. Note that I went with the simplest solution to start off with. I'm not sure adding a card (with an embedded image of the video), would be good. Such an image would fight for attention with the carousel. cc @kwalrath

**Comment by maguinis** [comment]
Can we make it have a card that pops up and auto-plays the video when the text is clicked? Similar to how we do the "watch the video" on our homepage next to get started? Right now it redirects to youtube.com and I prefer keeping users in our website. @chalin
