### ISSUE TITLE
Codelab uses 'new' and left-hand-side type annotations

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1936]
@sethladd commented on [Mon Jun 25 2018](https://github.com/flutter/flutter/issues/18809)

For https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/index.html?index=..%2F..%2Findex#5

Now that we're using Dart 2, we can simplify the code in these codelabs:

* remove `new`
* remove type annotations

For example, instead of `final TextStyle _biggerFont = const TextStyle(fontSize: 18.0); ` we can say `final _biggerFont = const TextStyle(fontSize: 18.0);`

**Comment by chalin** [comment]
@sfshaza2 or @kwalrath - can you edit the developers.google.com codelab?

**Comment by kwalrath** [comment]
Also (as of 2.1), instead of `18.0`, we could say `18`.

I'll see whether I have edit permission for this file.

**Comment by kwalrath** [comment]
On second thought, I should probably consult @sfshaza2 before making any changes to the codelab.

**Comment by sfshaza2** [comment]
This was fixed some time ago. Closing.
