### ISSUE TITLE
'Write your first Flutter app, part 1' page issue

### ISSUE THREAD

**Issue by cgbrucezjy** [flutter/website#1947]
Page URL: https://flutter.io/docs/get-started/codelab.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab.md

Description:
Step 4: Create an infinite scrolling ListView
4.Update the build method for RandomWordsState to use _buildSuggestions(), rather than directly calling the word generation library. (Scaffold implements the basic Material Design visual layout.)
`class RandomWordsState extends State<RandomWords> {
  ...
  @override
  Widget build(BuildContext context) {
    final wordPair = WordPair.random(); // Delete these two lines.
    **return Text(wordPair.asPascalCase);**
    return Scaffold (
      appBar: AppBar(
        title: Text('Startup Name Generator'),
      ),
      body: _buildSuggestions(),
    );
  }
  ...
}`

extra return statement?

**Comment by sfshaza2** [comment]
I don't see an extra return statement. This must have been fixed. Closing.
