### ISSUE TITLE
Flutter community issue with Slack workspace

### ISSUE THREAD

**Issue by labermt** [flutter/website#1954]
Page URL: https://flutter.io/community

Description:

https://flutter.io/community

Sent me to:

https://flutterstudygroup.slack.com/

When I clicked on how "Learn More" link.

However there is no information on how to join. No information on how to get invited, ... nothing. 

I can't tell if the link shouldn't be removed since it is a private community or if I can join. If I can join, there needs to be information at the "Learn More" link on how to join.

**Comment by chalin** [comment]
Good points thanks.

**Comment by 6heads** [comment]
Will anyone look into this?

**Comment by chalin** [comment]
Yes, eventually (it is a question of relative priorities). cc @sfshaza2 @maguinis

**Comment by sfshaza2** [comment]
We should possibly link to [sign up](https://stackoverflow.com/users/signup) and Learn More can continue to link to the Flutter Q&As.

**Comment by chalin** [comment]
There is this flutter-dev thread that is related: https://groups.google.com/d/msg/flutter-dev/wop8OSq7pVU/ez7W8mAHBAAJ. It ends with:

> ... Tbh the Slack room is pretty inactive anyway. I'd be tempted to suggest removing from the flutter.io/community page, as it doesn't even go to that Slack channel anyway (the one it does go to doesn't seem to work).

**Comment by filiph** [comment]
I just reached out to Simon (founder of the Slack community) on Twitter. If we can get a nicer link destination, let's keep the link.

**Comment by slightfoot** [comment]
Hi everyone, We are setting up an invite page. I'll update this conversation and PR the updated link soon.

**Comment by Taym95** [comment]
I would like to join!

**Comment by workerbee22** [comment]
All other channels on the Community page of Flutter.io seem to be open to all.

**Comment by bradyt** [comment]
Why not remove the link till it works?

**Comment by filleduchaos** [comment]
I'm a bit curious as to why it's listed in the first place if it's not readily accessible to the community. To be honest all I've ever seen it cause is confusion.

**Comment by filiph** [comment]
I agree with the sentiment. Yesterday I got an email from someone asking for invite. 

@slightfoot, unless you're very close to a solution, I propose we take down the link, at least temporarily.

**Comment by ScottS2017** [comment]
> I'm a bit curious as to why it's listed in the first place if it's not readily accessible to the community. To be honest all I've ever seen it cause is confusion.

Short version, we weren't clear with Google that it was private so when they did something nice for us by posting the link, we were caught flat-footed. We've been juggling ideas about what to do since, but it's come to a head this week so there's going to be action on this within 72 hours.

Exactly what, I'm not sure. That's this morning's hot discussion of the moment.
