### ISSUE TITLE
Improve state management docs

### ISSUE THREAD

**Issue by nklayman** [flutter/website#1960]
Currently, the state management docs just link to community-created articles/videos. While these articles and videos are great resources, there should be an official guide on state management. State management is one the of the most important parts of an app, and also one of the most complex. The amount of information linked can be overwhelming to new users, along with the different options. While having multiple methods of state management is great, a recommendation for starting users would be helpful, along with an official guide.

**Comment by sfshaza2** [comment]
Yes, we have some docs for this in-progress. Stay tuned!

**Comment by filiph** [comment]
Slightly improved by https://github.com/flutter/website/pull/2332. 

New pages start here: https://flutter.io/docs/development/data-and-backend/state-mgmt/intro

I would love your opinion on this, @nklayman. If you find that the current doc is still lacking (and it probably is), please don't hesitate to file a new bug with concrete suggestions.
