### ISSUE TITLE
Does Flutter Run on the web? FAQ entry could link to Dart alternatives

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1963]
@eseidelGoogle commented on [Fri Aug 10 2018](https://github.com/flutter/flutter/issues/20442)

Might want to link to other Dart projects, e.g. Angular from:
https://flutter.io/faq/#does-flutter-run-on-the-web
FYI @kevmoo @mit-mit 

---

@mit-mit commented on [Sun Aug 12 2018](https://github.com/flutter/flutter/issues/20442#issuecomment-412339762)

@kevmoo you wanna grab this one?

**Comment by sfshaza2** [comment]
I think this covers the issue for now. Closing.
