### ISSUE TITLE
No documentation for the Stack widget

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1964]
@vinicentus commented on [Sat Jun 30 2018](https://github.com/flutter/flutter/issues/18967)

There doesn't seem to bee any documentation on the page https://docs.flutter.io/flutter/widgets/Stack-class.html, in fact the whole page doesn't seem to be working as intended. The search box just says "Loading search...".

---

@bounty-torn commented on [Sat Jun 30 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-401549933)

It's working fine for me in Chrome and Ffox - try a different browser.

---

@vinicentus commented on [Sat Jun 30 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-401562662)

I tried both chrome and brave desktop and Google webview mobile (chrome) but nothing seems to work.
EDIT: Also tried edge.

---

@zoechi commented on [Mon Jul 02 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-401694399)

Works for me as well in Safari and Chrome.
Other pages are working?

---

@vinicentus commented on [Sun Jul 08 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-403299122)

All the other pages I've been on so far are working... I tried comparing the html of working pages as well, but couldn't find anything interesting (except for that much of the content and scripts that are used on the other pages aren't being loaded). Nothing in the developer tools console (brave). have no idea why it is this way, and others get it to work. https://web.archive.org/web/20180611071000/https://docs.flutter.io/flutter/widgets/Stack-class.html works...

---

@zoechi commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-416489969)

Do you still see this?
It doesn't look like others encountered this as well.

---

@vinicentus commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-416573149)

Yes, I still see this. If I use a VPN (to for example USA or Sweden), it works as expected (tested on chrome mobile). FYI I am in Finland, but I can't see why that would be a problem. Someone should probably do some digging to find out what the problem is, it's just that I seem to be the only one experiencing this.

---

@zoechi commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-416579847)

I don't think "some digging" would help if one can't reproduce.
If someone can reproduce it's probably easy. As nobody else seems to have encountered that problem it's likely that your network causes that and I don't see how anybody could do anything about that.

---

@vinicentus commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-416582320)

I have tried with different networks, so this really seems strange. I have currently only tried on a couple of mobile network operators but this shouldn't have anything to do with it. Any ideas on what I could do to troubleshoot, cause I'm out of ideas?

---

@zoechi commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-416585486)

> only tried on a couple of mobile network operators

With or without the VPN? Did it work with all/some/none of them?

---

@vinicentus commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-416592876)

Without the VPN of course, and it works with none of them...

---

@zoechi commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-416612229)

Ok, then we know it's not related to the network operators and the VPN.
Can you reproduce on different devices?

---

@vinicentus commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-416632487)

Could you try a Finnish or Estonian VPN? I have tried some and it didn't work over those (used OpenVPN Servers android app to find servers). Some other countries I tested work, so it's probably something to do with network configuration.

And yes I can reproduce in any browser on any device it seems.

---

@zoechi commented on [Tue Aug 28 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-416639049)

Only when you use VPN or without VPN as well. I still have troubles to see a pattern here.

---

@vinicentus commented on [Wed Aug 29 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-416831050)

> Only when you use VPN or without VPN as well. I still have troubles to see a pattern here.

When I don't use VPN, and apparently when I used a Finnish or an Estonian VPN server.

---

@zoechi commented on [Wed Aug 29 2018](https://github.com/flutter/flutter/issues/18967#issuecomment-416834955)

Sorry, but I have no idea what could cause that.

**Comment by chalin** [comment]
We've encountered similar weirdness with Firebase servers in the past. @vinicentus are you still having this issue? If so, could you include a screenshot? Does the problem occur for other pages? cc @kwalrath

**Comment by chalin** [comment]
Thanks for confirming. We used to see intermittent failures as well, as might be the case here too. If this problem arises again, please let us know (e.g., you can reopen this issue).
