### ISSUE TITLE
Document optimizations - const vs new

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1965]
@p30arena commented on [Fri Sep 07 2018](https://github.com/flutter/flutter/issues/21536)

Prefetch Text Layout in RecyclerView

https://medium.com/androiddevelopers/prefetch-text-layout-in-recyclerview-4acf9103f438

in the above article, they're using a method that reduces render time by 95%
is this how we use "const Text" instead of "new Text"?

---

@zoechi commented on [Fri Sep 07 2018](https://github.com/flutter/flutter/issues/21536#issuecomment-419359484)

That's not related at all. Creating an instance of `Text` doesn't render the text.
The difference between `new` and `const` here is that with `new` a new instance of `Text` is created every time the code is executed, while with `const Text('foo')` a `Text` instance with the parameter `'foo'` is created at compile time and reused every time `const Text('foo')` is executed anywhere in your app.
`const` also limits calculation that can be done when an instance is created.  
`const` constructors in Dart classes can't have a body and expressions in initializer lists need to be const as well. This doesn't leave much that can be done on initialization.

So, this is a pure Dart language feature.

Rendering text would be the job of the engine (libtxt, Skia, ...)

Interesting read though!

---

@p30arena commented on [Fri Sep 07 2018](https://github.com/flutter/flutter/issues/21536#issuecomment-419364868)

Hi @zoechi 
Then why the docs say:
> Use const widgets where possible. (This is equivalent to caching a widget and re-using it.)

https://docs.flutter.io/flutter/widgets/StatefulWidget-class.html

How can I actually cache a widget?
Using Key? or GlobalKey?

---

@zoechi commented on [Fri Sep 07 2018](https://github.com/flutter/flutter/issues/21536#issuecomment-419382466)

Flutter is able to do optimizations down the line if widgets are const.
Caching a widget instance (in a field) and returning the same instance for every call to `build()` would have a similar effect.
The optimizations is based on recognizing if the new instance is identical (object identity) with the previous one.

> How can I actually cache a widget?

Depends on the purpose. 

---

@p30arena commented on [Fri Sep 07 2018](https://github.com/flutter/flutter/issues/21536#issuecomment-419383360)

@zoechi 
we need a doc specifically concentrated on optimizations.

**Comment by chalin** [comment]
@zoechi - how about if we changed the issue title to "Document optimizations"? cc @kwalrath

**Comment by zoechi** [comment]
Sounds good

**Comment by sfshaza2** [comment]
I'm not sure where we would put this. Maybe in the faq?

**Comment by chalin** [comment]
How about under "Testing & Optimization"?

**Comment by sfshaza2** [comment]
If we have enough for a whole page, yes. I'm not sure that we do.

**Comment by parlough** [comment]
There is now a document about [Performance best practices](https://docs.flutter.dev/perf/best-practices#control-build-cost) which also mentions using `const` where possible with some context and pointing to the recommended linter set which contains lints for encouraging this further.
