### ISSUE TITLE
Thumb up screenshot missing thumbs

### ISSUE THREAD

**Issue by mit-mit** [flutter/website#1966]
The GitHub section here encourages 'thumbs up' votes on issues, however the screenshot shows a but with no thumbs up votes on it. The "old one" we had had lots of votes making it clear we meant by 'thumbs up'.

https://flutter.io/community

**Comment by chalin** [comment]
I see two obvious solutions:

 1. Add a thumbs up emoticon with some arbitrary count (say 10) to the existing issue image.
 2. Change the issue. For example:

    > <img width="996" alt="screen shot 2018-12-10 at 15 04 31" src="https://user-images.githubusercontent.com/4140793/49758555-48658080-fc8d-11e8-8797-83b3c0fcbf74.png">

    Or might that be a little too confusing given that there are so many reactions on this issue?

Do you have a preference?

cc @kwalrath

**Comment by mit-mit** [comment]
Maybe grab one like this that has fewer emojis on it? https://github.com/flutter/flutter/issues/14050

**Comment by chalin** [comment]
Thanks for finding that issue. It is a good candidate.
