### ISSUE TITLE
Link code snippets to the GitHub page

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1967]
@jayoung-lee commented on [Fri Sep 14 2018](https://github.com/flutter/flutter/issues/21892)

Flutter.io's tutorial pages (e.g. [Building Layouts in Flutter](https://flutter.io/tutorials/layout/)) have multiple code snippets to explain different parts of an app, but it is hard to see each snippet in the context of a complete app. 

Can we link each snippet to its full app on GitHub, with highlights on the snippet's location (line #)?

**Comment by chalin** [comment]
The apps in the first part of the tutorial have been created via #2164.

**Comment by parlough** [comment]
Giving this some thought, I generally don't think we want to link to the snippet excerpts automatically, as they often are not created as full samples and the snippets are made to be seen in isolated. In cases where a full link is needed, we can manually add the links and a few pages have done so.

If anyone reading this feels a specific page is hard to understand from the snippets, please open a specific issue for that page or those snippets. Thanks!
