### ISSUE TITLE
Enhance UI for sample codes

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1968]
@jayoung-lee commented on [Fri Sep 14 2018](https://github.com/flutter/flutter/issues/21891)

For the sample codes in flutter.io, I'd like to suggest adding a unique UI:

1. On hover, highlight a block of code, starting from the line under a mouse pointer to the end of the widget, variable, or child (closing bracket, end of line, etc.) 
2. When highlighted, show a copy button on the corner of the highlighted block so that the user can copy the whole block without worrying about finding a matching closing bracket
3. Highlight goes away on click so that the user can copy custom parts of the sample

It can be particularly useful for users going through the tutorials such as: 
https://flutter.io/tutorials/layout/

**Comment by chalin** [comment]
The solution that we've opted for is what is used on other Dart sites as well as https://developers.google.com: code excerpts now have a copy-code button (#2184). See https://flutter.io/docs/development/ui/layout#step-3-implement-the-button-row for examples.

I'll close this for now assuming that it gives the core functionality of what you are asking for.

Closed by #2184
