### ISSUE TITLE
Improve "system requirements" in installation docs

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1971]
@zoechi commented on [Mon Oct 08 2018](https://github.com/flutter/flutter/issues/22808)

https://flutter.io/setup-macos/#system-requirements

Does not tell how to install the tools.
Even if there is no single approved way, it would be great to have one concrete suggestion, for example using Homebrew (https://apple.stackexchange.com/a/149088/238346)

![image](https://user-images.githubusercontent.com/405837/46613597-eb760e80-cb13-11e8-9b5e-de24591ea09e.png)

**Comment by chalin** [comment]
> Does not tell how to install the tools.

Which tools specifically?

**Comment by zoechi** [comment]
Good question. Should have been more clear:

Android SDK tools.

Flutter assumes Android Studio installation, but Android SDK can also be installed separately.
This caused several support requests, but not recent weeks anymore. Perhaps Flutter tools became smarter about finding the SDK.

We could close until I run into this again.

**Comment by chalin** [comment]
> ... but not recent weeks anymore. ... We could close until I run into this again.

SGTM :)
