### ISSUE TITLE
Add offline docs instructions.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/website#1975]
We now have offline docs available, both as a zip archive of the website, and as a Dash/Zeal docset.  We should document how to use them on the website.

Here's the information I sent out to flutter-dev about it:

If you work offline, or have poor connectivity, you might wish to check out Zeal (free) for Linux and Windows, or Dash (a small fee) for macOS. These are simple browsers for offline API docs, and Flutter's build now produces offline docsets for these that you can subscribe to.

The Flutter 1.0 (stable) docset feed URL: is https://docs.flutter.io/offline/flutter.xml
The Flutter master channel (cutting edge) docset feed URL is: https://master-docs.flutter.io/offline/flutter.xml

Follow the user documentation for these offline browsers to see how to add a docset feed to them.  There is an IntelliJ Dash plugin (that works for Zeal too) that will search for the symbol under the cursor at the touch of a key.

You can also download (if you don't want to use Zeal or Dash) a ZIP file of the HTML for the website:

stable: https://docs.flutter.io/offline/flutter.docs.zip
master: https://master-docs.flutter.io/offline/flutter.docs.zip

**Comment by kwalrath** [comment]
Where should these be documented on flutter.io? One option is to add a sidenav link either to the flutter-dev post or to a [new?] flutter.io page/section that's devoted to the offline API docs:

Reference
  ...
  [API reference](docs.flutter.io) ([offline](https://groups.google.com/d/msg/flutter-dev/zWKHQXbdEvw/u18eUJqxBgAJ))

/cc @InMatrix @galeyang @sfshaza2 

(I don't know flutter.io well enough to know if it already has a page/section devoted to the API reference.)

**Comment by chalin** [comment]
>  if it already has a page/section devoted to the API reference

AFAIK, we only have a link in the sidenav to the external https://docs.flutter.io. We do not have an API page (like we do for webdev).

**Comment by bbugh** [comment]
The stable feed link doesn't work, and everywhere I can find reference to it is the same link. I wasn't able to find anything in all of the doc sites or an Internet search. This seems to be the only related task that is still open.

Is there a fixed URL for https://docs.flutter.io/offline/flutter.xml? It redirects to https://api.flutter.dev/offline/flutter.xml and is a 404. The master XML URL seems to be working fine.

**Comment by atsansone** [comment]
@gspencergoog : The offline docs appear to be missing at this time. 

@parlough : Any insight as to where these could have gone?

**Comment by parlough** [comment]
The links have just moved to the new api.flutter.dev links. You can find them at https://api.flutter.dev/#offline-documentation

Offline HTML documentation ZIP bundles:

`stable`: [https://api.flutter.dev/offline/flutter.docs.zip](https://api.flutter.dev/offline/flutter.docs.zip)
`master: [https://master-api.flutter.dev/offline/flutter.docs.zip](https://master-api.flutter.dev/offline/flutter.docs.zip)

Zeal XML configurations:

`stable` channel Zeal XML configuration: [api.flutter.dev/offline/flutter.xml](https://api.flutter.dev/offline/flutter.xml)
`master` channel Zeal XML configuration: [master-api.flutter.dev/offline/flutter.xml](https://master-api.flutter.dev/offline/flutter.xml)

**Comment by mauricepoirrier** [comment]
@parlough it's seems that zeal XML stable is not working

**Comment by parlough** [comment]
What are you getting when using the Zeal XML link?

It looks to correctly be an XML file which Zeal knows how to load:

```
<entry>
  <version>3.10.1-0.0.pre.6</version>
  <url>https://api.flutter.dev/offline/flutter.docset.tar.gz</url>
</entry>
```

You could technically download the https://api.flutter.dev/offline/flutter.docset.tar.gz directly but I'm not sure it's of use without Zeal.

**Comment by atsansone** [comment]
@parlough : This is only the API documentation. @gspencergoog : Was this issue for the docs at docs.flutter.dev or api.flutter.dev?

**Comment by gspencergoog** [comment]
The issue is to add instructions to the docs at docs.flutter.dev for using the offline docs. The API documentation site doesn't have any web pages that aren't autogenerated from the code, so there's no place to put this kind of documentation there.

**Comment by sfshaza2** [comment]
I don't believe I've ever seen this issue. At any rate, it does seem like we should document this on the website, at least when Zeal stable works.

**Comment by atsansone** [comment]
We link to the API docs in multiple prominent places in the public docs and the offline download is featured on the API docs' home page. I don't think this needs to have a direct link from the public docs. Closing this issue.
