### ISSUE TITLE
Codelab: Indentation strange

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1977]
@goderbauer commented on [Wed Aug 02 2017](https://github.com/flutter/flutter/issues/11466)

Many code snippets have a strange indentation.

Example: in the snippet below, the lines marked with arrows should have the same indentation.

![image](https://user-images.githubusercontent.com/1227763/28849376-99a62d08-76cb-11e7-87f3-36d3db60d6cf.png)

@LarkAscending 

---

@LarkAscending commented on [Wed Aug 02 2017](https://github.com/flutter/flutter/issues/11466#issuecomment-319534232)

Much experimentation w/IntelliJ settings. IntelliJ docs no help. Much searching for others w/this issue - none found. 
This happens when pasting to Gmail as well as Google Docs...
Have asked Dart DevRel team for advice.

---

@Sfshaza commented on [Tue Jul 24 2018](https://github.com/flutter/flutter/issues/11466#issuecomment-407467535)

@goderbauer, could you tell me where you saw strange indentation?

---

@goderbauer commented on [Tue Jul 24 2018](https://github.com/flutter/flutter/issues/11466#issuecomment-407469471)

On https://codelabs.developers.google.com/codelabs/flutter/#7 search for "Modify the _buildTextComposer method." to find the example above.

**Comment by sfshaza2** [comment]
This codelab is out of date. It still uses new, the code should be checked. We should update or retire.

**Comment by sfshaza2** [comment]
Thanks, @goderbauer! I've been updating the codelab and its code. The indentation has been fixed via dartfmt. Closing.
