### ISSUE TITLE
Making The www effective

### ISSUE THREAD

**Issue by pedromorgan** [flutter/website#1981]
So here are some issues from experience...

## snags. are auto linking.....

The site runs on jekyll, on github = no plugins (gitLAB allows plugins etc)
.
we want to autolink any text that says `dart:*`
to the dart lang...
we can either do this the hard way... in markdown (ta aron)
eg see [dart convert](https://api.dartlang.org/stable/2.1.0/dart-convert/dart-convert-library.html)

or we do someting clever such as.
using some scss+magic to autoling stuff..
eg
See the `dart:convert.` module, and the `package:math` for more info..

Do the `dart:convert`
is "transformed"  into <a href="dartland.... /convert">,,, etc etc..

also some css anchor to` http://dart`.. to make it green or pink.. like here
http://revel.github.io/manual/validation.html
or here
http://ts2.github.io/

The dnag we got is that we cant add plugins to compile stuff...
such as graphviz etc.. which is a pain..

Intentional for  future is accepting other translations

**Comment by pedromorgan** [comment]
taking the Your and I out...
eg
```
How do you modify your app to make it react to user input? In this tutorial, you’ll add interactivity to an app that contains only non-interactive widgets. Specifically, you’ll modify an icon to make it tappable by creating a custom stateful widget that manages two stateless widgets.
```
after
```
Lets modify the app to react to user input? 
This tutorial add interactivity to an app that contains only non-interactive widgets. 

Specifically, modify an icon to make it tappable by creating a custom stateful widget that manages two stateless widgets.
```

**Comment by sfshaza2** [comment]
Sorry, not a priority. Closing.
