### ISSUE TITLE
Getting Started guide should explain pubspec.yaml uses-material-design option better

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1984]
@Hixie commented on [Wed Jun 21 2017](https://github.com/flutter/flutter/issues/10878)

From https://github.com/flutter/flutter/issues/10827:
>We were under the impression that it meant that the uses-material-design option meant that it wouldn't load the icon font (and other dependent resources, essentially) and we were using it with the intention to save space because we weren't using the Icon class at all. We still wanted to use the other classes though. So, [we set "uses-material-design: false" because we wanted to not incur any app size costs associated with using material in the form of icon fonts].
>
> In hindsight, it makes perfect sense that other things in the material package depend on that font/flag being set to true and that setting the flag to false wont actually stop you from using material, but just disable the specifics of the platform if you choose not to use it.

> Ideally that would explain that if you want to use the material package then you should set that value to true. If you don't want to use it, set it to false. I think we read too much into that flag ultimately.
>
> If that flag is meant to represent "use material, but not the icon font" then the package should work without the font in my opinion. If it is a flag that specifies the intent to never use material, then it works :)

---

@sethladd commented on [Wed Jun 21 2017](https://github.com/flutter/flutter/issues/10878#issuecomment-310133290)

Do we also need to update the comments in the pubspec.yaml template that is used to generate the starter template?

---

@Sfshaza commented on [Wed Jul 11 2018](https://github.com/flutter/flutter/issues/10878#issuecomment-404059242)

@willlarche, can you comment?

---

@willlarche commented on [Wed Jul 11 2018](https://github.com/flutter/flutter/issues/10878#issuecomment-404304121)

So, does the Material package work without the font? I actually don't know.

---

@Hixie commented on [Thu Jul 12 2018](https://github.com/flutter/flutter/issues/10878#issuecomment-404610017)

The icons will be broken, but it'll "work" other than that.

---

@Sfshaza commented on [Wed Jul 18 2018](https://github.com/flutter/flutter/issues/10878#issuecomment-405957336)

@Hixie, say you set uses-material-design to true, but don't use the icon font in your code. When you build a release version of the app, would tree shaking remove the icon font?

---

@Hixie commented on [Thu Jul 19 2018](https://github.com/flutter/flutter/issues/10878#issuecomment-406326664)

No.

---

@Sfshaza commented on [Sat Jul 21 2018](https://github.com/flutter/flutter/issues/10878#issuecomment-406809412)

It was worth a shot, @Hixie.  ;)

**Comment by sfshaza2** [comment]
There's some good info here.
