### ISSUE TITLE
Need docs for how to best handle global state

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1992]
@mit-mit commented on [Fri Dec 08 2017](https://github.com/flutter/flutter/issues/13444)

Its' not clear from flutter.io how to best handle global state (such as logged in user, preferences, etc.).

---

@kondasoft commented on [Fri Apr 27 2018](https://github.com/flutter/flutter/issues/13444#issuecomment-384928291)

Well, were are the docs guys?

**Comment by rubensdemelo** [comment]
State management docs since 1.2 suggest scoped_model

**Comment by sfshaza2** [comment]
We now recommend Provider, though ScopedModel can still be used. Our State Management docs have been rewritten and now have advice.  See:   https://flutter.dev/docs/development/data-and-backend/state-mgmt/intro and particularly:  https://flutter.dev/docs/development/data-and-backend/state-mgmt/options
