### ISSUE TITLE
Explain where the app startup code is located

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1994]
@eseidelGoogle commented on [Mon Nov 28 2016](https://github.com/flutter/flutter/issues/7047)

@sethladd asked me to file.  I would like some guidance from the docs on where to put my startup/initialization code.  Presumably part of some larger lifecycle documentation?

Example lifecycle events we could/should document (or provide examples for):
- Where startup code goes
- Application about to background
- application resume from background
- application about to quit

Maybe more?

Examples from iOS:
https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/TheAppLifeCycle/TheAppLifeCycle.html

And Android:
https://developer.android.com/training/basics/activity-lifecycle/index.html

**Comment by sfshaza2** [comment]
Sorry @zoechi, it took less than 6 years. But oy.
