### ISSUE TITLE
Doc Request: How to style text

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1995]
@sethladd commented on [Thu Oct 27 2016](https://github.com/flutter/flutter/issues/6559)

Would love to learn how to:

- [x] change fonts - https://github.com/flutter/website/pull/307
- [x] change styles for text
- [x] use themes across text
- [ ] best practices for cascading these styles throughout the app

Tactical things:

- [x] how to make text bold?
- [x] how to make text italic?
- [x] how to control opacity of text?
- [x] how to control size of text?
- [x] how to control line height?

---

@sethladd commented on [Tue Nov 01 2016](https://github.com/flutter/flutter/issues/6559#issuecomment-257699275)

Partially addressed by https://github.com/flutter/website/pull/307

---

@sethladd commented on [Fri Mar 10 2017](https://github.com/flutter/flutter/issues/6559#issuecomment-285795587)

After conversation today, we should look to see if we can answer all of these by adding comments and snippets to https://docs.flutter.io/flutter/widgets/RichText-class.html

and probably update the link to RichText from https://docs.flutter.io/flutter/widgets/Text-class.html to explain why you should See Also RichText.

We may also want to add a link to flutter_markdown, which may be an easier way to write styled text: https://docs.flutter.io/flutter/flutter_markdown/flutter_markdown-library.html

---

@Hixie commented on [Tue Jun 13 2017](https://github.com/flutter/flutter/issues/6559#issuecomment-308027664)

Not sure what to do for bullets 2-4. I have a patch for the "tactical things".

---

@sethladd commented on [Tue Jun 13 2017](https://github.com/flutter/flutter/issues/6559#issuecomment-308157169)

I think 2-4 could be an article that covers rich text in general. Perhaps by updating and broadening the focus of https://flutter.io/custom-fonts/

Thanks for the upcoming patch!

---

@Hixie commented on [Tue Jun 13 2017](https://github.com/flutter/flutter/issues/6559#issuecomment-308176834)

Ok, I've removed the API label then since I've done the API docs part of it.

**Comment by pedromorgan** [comment]
We still; need a Flutter for css designers, etc

**Comment by rubensdemelo** [comment]
@pedromorgan https://flutter.dev/docs/get-started/flutter-for/web-devs This isnt helpul ?

**Comment by sfshaza2** [comment]
Except for best practices, these topics are covered in the cookbook:  https://flutter.dev/docs/cookbook#design

**Comment by atsansone** [comment]
This all exists in the cookbook. Closing.
