### ISSUE TITLE
Developers would like guidance on how to log from their app

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1998]
@sethladd commented on [Fri Dec 02 2016](https://github.com/flutter/flutter/issues/7138)

A question from a current Flutter developer: "It would be useful to have information on logging and debugging".

---

@eseidelGoogle commented on [Sat Dec 03 2016](https://github.com/flutter/flutter/issues/7138#issuecomment-264649984)

I think we have some debugging info: https://flutter.io/debugging/
Logging may be covered in part by https://pub.dartlang.org/packages/logging

---

@Hixie commented on [Wed Nov 29 2017](https://github.com/flutter/flutter/issues/7138#issuecomment-347709708)

Moving out of m3 since this doesn't fit our current priorities.

**Comment by atsansone** [comment]
This was fixed in https://github.com/flutter/website/pull/2796. Closing this issue.
