### ISSUE TITLE
Add all debug flags to debugging.md

### ISSUE THREAD

**Issue by zoechi** [flutter/website#1999]
@xster commented on [Sat Feb 18 2017](https://github.com/flutter/flutter/issues/8260)

May already exist. Otherwise, would be nice to document all the various UI debug flags in a centralized place like 
debugShowMaterialGrid
and checkerboardRasterCacheImages etc etc

---

@abarth commented on [Sat Feb 18 2017](https://github.com/flutter/flutter/issues/8260#issuecomment-280795663)

https://flutter.io/debugging/ is an attempt

---

@xster commented on [Sat Feb 18 2017](https://github.com/flutter/flutter/issues/8260#issuecomment-280796747)

Perhaps one step could be to gather the various loose globals into one global debug container?

---

@abarth commented on [Sat Feb 18 2017](https://github.com/flutter/flutter/issues/8260#issuecomment-280797810)

The trouble is that these flags exist at several layers of the stack (e.g., some are in widgets, some are in rendering, and some are in painting).  In C++, we could put them all in a common namespace, but in Dart I don't think you can define a class that spans more than one library.

**Comment by sfshaza2** [comment]
The debugShowMaterialGrid is documented, but not checkerboardRasterCacheImages.

**Comment by atsansone** [comment]
These flags are covered in [Debug flags: performance](https://docs.flutter.dev/testing/code-debugging#debug-flags-performance) in the [Debugging Flutter apps programmatically](https://docs.flutter.dev/testing/code-debugging) page.

Closing.
