### ISSUE TITLE
Cross links for performance debugging

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2002]
@Hixie commented on [Wed Jan 17 2018](https://github.com/flutter/flutter/issues/14144)

FAQ should link to debugging.md and testing.md
testing.md should link to debugging.md

---

@Hixie commented on [Thu May 24 2018](https://github.com/flutter/flutter/issues/14144#issuecomment-391802525)

cc @Sfshaza 

---

@Sfshaza commented on [Tue Jun 12 2018](https://github.com/flutter/flutter/issues/14144#issuecomment-396511620)

I hesitate to do that just now, as I will be moving files around. But I will keep this open for when I've done that.

**Comment by sfshaza2** [comment]
The website is done. We should check that this cross links are in place.
