### ISSUE TITLE
Would like instructions on how to implement onSaveInstanceState

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2004]
@eseidelGoogle commented on [Fri Apr 20 2018](https://github.com/flutter/flutter/issues/16799)

https://twitter.com/championswimmer/status/987327881960357889

My understanding is that FlutterView will handle the config change if AndroidManifest.xml contains:
`android:configChanges="orientation|screenSize"`
https://developer.android.com/guide/topics/resources/runtime-changes.html

But I'm not sure that we've written that down anywhere in our docs.  I believe some of our sample are locked to portrait for historical reasons too?

---

@eseidelGoogle commented on [Fri Apr 20 2018](https://github.com/flutter/flutter/issues/16799#issuecomment-383132776)

I'm aware of at least one bug reported with Flutter's rotation code: https://github.com/flutter/flutter/issues/16322 there may be others.

---

@championswimmer commented on [Fri Apr 20 2018](https://github.com/flutter/flutter/issues/16799#issuecomment-383141694)

There needs to be documentation regarding how `onSaveInstanceState` is to be implented in Flutter as well. 

---

@championswimmer commented on [Fri Apr 20 2018](https://github.com/flutter/flutter/issues/16799#issuecomment-383141904)

Also pertinent : https://github.com/flutter/flutter/issues/6827
And dupe: https://github.com/flutter/flutter/issues/3427 

---

@Sfshaza commented on [Sat May 19 2018](https://github.com/flutter/flutter/issues/16799#issuecomment-390346373)

Yes, added to doc content plan.

---

@Sfshaza commented on [Thu May 31 2018](https://github.com/flutter/flutter/issues/16799#issuecomment-393663392)

OK, PR  https://github.com/flutter/website/pull/1037 handles documenting how to configure landscape view, and also that android should not restart a Flutter app.

The onSaveInstanceState doc is not yet written.

---

@mzgreen commented on [Wed Jun 27 2018](https://github.com/flutter/flutter/issues/16799#issuecomment-400606590)

Please note that `onSaveInstanceState` is not only about persisting state during config changes. More important part is that it's used it to persist transient app state when OS kills the app.
https://developer.android.com/topic/libraries/architecture/saving-states#system_initiated_ui_state_dismissal

**Comment by sfshaza2** [comment]
Still true.

**Comment by championswimmer** [comment]
This is best addressed with documentation head on. We do not want truckloads of users knee deep into Flutter codebase, realising after almost shipping their app that they have no idea about the lifecycle of Android activities.
