### ISSUE TITLE
Not clear what Flutter provides automatically for platform adaptations

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2007]
@MatzeKing commented on [Thu Mar 09 2017](https://github.com/flutter/flutter/issues/8672)

There is no list of UI components which adapt to the target platform automatically. 

E.g. The default "Back arrow" is different for Android and iOS and Flutter is changing it automatically depending the device the app is running on. Same goes for the position of the tab bar, but this has to be done by the developer himself.

An overview of auto adapting components would help.

---

@sethladd commented on [Tue Apr 18 2017](https://github.com/flutter/flutter/issues/8672#issuecomment-294947493)

See also https://github.com/flutter/flutter/issues/8726#issuecomment-294939504

---

@Hixie commented on [Wed Dec 06 2017](https://github.com/flutter/flutter/issues/8672#issuecomment-349489833)

This is not on our immediate list of priorities, moving to next milestone.

---

@Sfshaza commented on [Tue Jul 03 2018](https://github.com/flutter/flutter/issues/8672#issuecomment-402091112)

Is it fair to say, @Hixie, that any widget in the material or cupertino library would auto-adapt? Or is that too simplistic?

**Comment by sfshaza2** [comment]
We now have a doc:  https://flutter.dev/docs/resources/platform-adaptations

Closing.
