### ISSUE TITLE
Would like a slightly more optimized "first hour" for new contributors to flutter

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2008]
@eseidelGoogle commented on [Fri Mar 16 2018](https://github.com/flutter/flutter/issues/15619)

@timsneath and I were brainstorming today about successes in other projects at fostering community growth.  There are many great open source examples.

I would like to think that Flutter has done the fundamentals of open source pretty well (happy/healthy community, fully open development, good docs, tests, etc.) but I suspect we could throw out the red carpet a bit more than we do and make our "first hour" be a bit more welcoming.

If I'm new to Flutter from flutter.io or github.com/flutter/flutter where do I?
* Learn how to contribute?
* Learn how to help (other than just maybe coding)?
* Get suggestions on places to help and/or starter bugs?

I don't think we need a lot here.  But I didn't see anything obvious in flutter.io and 
https://github.com/flutter/flutter/blob/master/CONTRIBUTING.md
seemed to be mostly technical focused if that's our "come help with Flutter" page?

Thoughts?  I would love comments from others pointing to great "come help!" or "getting started" pages from other OSS projects.

---

@escamoteur commented on [Sat Mar 17 2018](https://github.com/flutter/flutter/issues/15619#issuecomment-373920456)

In ReactiveUI we have easy issues marked as for first time contributors.

---

@xqwzts commented on [Sat Mar 17 2018](https://github.com/flutter/flutter/issues/15619#issuecomment-373936286)

FWIW the [easy fix](https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22easy+fix%22) label exists and is used here.

Maybe it could get more visibility if CONTRIBUTING.md suggested that people look at issues under that label if they're interested in diving in?

---

@xqwzts commented on [Sat Mar 17 2018](https://github.com/flutter/flutter/issues/15619#issuecomment-373938519)

>  I would love comments from others pointing to great "come help!" or "getting started" pages from other OSS projects.

I'm a fan of Django's [contributing docs](https://docs.djangoproject.com/en/dev/internals/contributing/). Particularly the [guidelines for new contributors](https://docs.djangoproject.com/en/dev/internals/contributing/new-contributors/#guidelines).

They even have a walkthrough tutorial on [writing your first patch for Django](https://docs.djangoproject.com/en/dev/intro/contributing/).

---

@InMatrix commented on [Sun Mar 18 2018](https://github.com/flutter/flutter/issues/15619#issuecomment-373974036)

We've previously discussed linking to source code on Github from API docs to lower the barrier to making small improvements (e.g., fixing typos or adding a usage sample), since such changes can be made via the Github Web editor. The tracking bugs are https://github.com/dart-lang/dartdoc/issues/1454 and https://github.com/flutter/flutter/issues/10416.

We did something similar for flutter.io pages by adding a link to edit the source of each page, which I've seen being used by contributors. 

Cc: @jcollins-g 

---

@irrigator commented on [Mon Mar 19 2018](https://github.com/flutter/flutter/issues/15619#issuecomment-374224971)

[React has a pretty good "how to contribute" documentation.](https://reactjs.org/docs/how-to-contribute.html).

1. It writes clearly on how to contribute.
2. It has a detailed overview of the code base and some details.

---

@Hixie commented on [Wed Jun 13 2018](https://github.com/flutter/flutter/issues/15619#issuecomment-396770132)

cc @Sfshaza @RedBrogdon @mjohnsullivan 

---

@Sfshaza commented on [Wed Jul 11 2018](https://github.com/flutter/flutter/issues/15619#issuecomment-404058547)

More suggestions that can impact the IA, @InMatrix.

---

@InMatrix commented on [Wed Jul 11 2018](https://github.com/flutter/flutter/issues/15619#issuecomment-404233563)

We'll consider where a How to Contribute section should go. Cc: @galeyang

---

@Sfshaza commented on [Wed Jul 18 2018](https://github.com/flutter/flutter/issues/15619#issuecomment-405974058)

Making a note to myself that I should take a look (and probably update) the website README.

---

@Sfshaza commented on [Fri Jul 20 2018](https://github.com/flutter/flutter/issues/15619#issuecomment-406717333)

Talked to @InMatrix. For the short term, we'll probably change the GitHub link on the front page to Contribute, and link to the Contribution page on the repo. I should probably check that page and make sure it's sufficient.

---

@galeyang commented on [Fri Oct 19 2018](https://github.com/flutter/flutter/issues/15619#issuecomment-431189578)

**Update**: from the study, we suggested to retain the Github link on the top nav. The reason is that some developers who are new to Flutter have a good interest to visit Github. They want to get a sense of full features available and the update frequency (which means the team's commitment and activeness of community).

For the short term, we can consider **adding an external link (to the current Contribution page on Github) both in the footer and on the Community page.** 

In the future, if we have more detailed content (like the above examples from React), we may consider adding a new section to the Doc's side nav.

What do you think @Sfshaza ?

**Comment by galeyang** [comment]
https://github.com/flutter/website/issues/1628 (bug-reports page) seems be relevant.

**Comment by Piinks** [comment]
cc @Piinks 
I recently spoke with the community about writing code samples for API docs as a good first contribution opportunity... There seemed to be some good reception to it. I'll start documenting feedback as this progresses. :)

**Comment by Hixie** [comment]
https://github.com/flutter/website/pull/5155, https://github.com/flutter/website/pull/5156.
