### ISSUE TITLE
Request a video intro to key concepts in the Flutter framework

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2009]
@InMatrix commented on [Mon Oct 22 2018](https://github.com/flutter/flutter/issues/23383)

In our recent UX studies, we've observed a lot of initial difficulty for developers who came from other frameworks to realize UI programing in Flutter was reactive and UI changes should be done by changing the state of the UI instead of manipulating UI elements directly. Those developers could have benefited from a quick but upfront introduction to the key aspects of the framework, so they don't attempt to apply their existing UI programming knowledge inapplicable to Flutter. 

Here is my request: can we turn [A Tour of the Flutter Framework](https://flutter.io/widgets-intro/) into a short video and feature it prominently on our website? It could pair nicely with the more marketing-oriented [Introducing Flutter](https://www.youtube.com/watch?v=fq4N0hgOWzU) video.

Cc: @RedBrogdon, @galeyang, @jayoung-lee, @Sfshaza 

---

@RedBrogdon commented on [Tue Oct 23 2018](https://github.com/flutter/flutter/issues/23383#issuecomment-432270743)

Hmm. I'm not sure how short a video could be and still cover all of these topics:

* Introduction
* Hello World
* Basic widgets
* Using Material Components
* Handling gestures
* Changing widgets in response to input
* Bringing it all together
* Responding to widget lifecycle events
* Keys
* Global Keys

We do have videos in the pipeline for Stateful/Stateless/Inherited and Keys, which will go over some of this content.

If this is your primary concern:

> programing in Flutter [is] reactive and UI changes should be done by changing the state of the UI instead of manipulating UI elements directly

We could totally create a short video on that. I've done two recent conference talks about how the widget/element/render trees relate to one another and the motivation behind the way things work. They could probably be distilled into something short and straightforward. Would that help here?

---

@InMatrix commented on [Wed Oct 24 2018](https://github.com/flutter/flutter/issues/23383#issuecomment-432505712)

> We could totally create a short video on that. I've done two recent conference talks about how the widget/element/render trees relate to one another and the motivation behind the way things work. They could probably be distilled into something short and straightforward. Would that help here?

Yes, totally. It doesn't even need to touch the three trees, IMO. The primary goal of this video is to quickly point out paradigm shifts to developers not familiar with reactive UI frameworks but otherwise proficient in programming, so they can make an informed decision on when they can learn by trial and error and when they do need to pause and read stuff. 

The research question, if I may frame it that way, is this: what is the minimum amount of upfront learning required to get an experienced developer started on Flutter and continue with on-demand learning? We can start with something simple and iterate on that using the study sessions scheduled in November. What do you think?

**Comment by RedBrogdon** [comment]
Our Widgets 101 series is now published, and covers some of this material:

https://www.youtube.com/watch?v=CXedqMlLo7M&list=PLOU2XLYxmsIJyiwUPCou_OVTpRIn_8UMd

Now that Flutter Live is behind us and I have time to think, what other resources are needed here? We've got some guides that touch on the imperative-versus-reactive content:

* https://flutter.io/docs/get-started/flutter-for/android-devs
* https://flutter.io/docs/get-started/flutter-for/declarative

Are you still looking for a video that would do this as well?

**Comment by RedBrogdon** [comment]
I'm directing these questions at @InMatrix, I should mention. 😄

**Comment by InMatrix** [comment]
Thanks for the pointers. The first 2 episodes of Widgets 101 are great intro materials every Flutter dev should go through. I suggest we link/embed them in https://flutter.io/docs#new-to-flutter. @galeyang might have some thoughts on where we show them as well.

> https://flutter.io/docs/get-started/flutter-for/declarative

This page is useful for people who come from an imperative UI framework. Where is it linked from?

**Comment by joeythomaschaske** [comment]
I watched the 101 videos. They were ok. I'm appreciative of them, but the Inherited Widget one could have been better.

At [3:00](https://youtu.be/Zbm3hjPjQMk?t=180) he talks about how Inherited Widgets are immutable and doesn't go much deeper and important concepts [like wrapping  inherited widgets with a stateful container](https://flutterbyexample.com/set-up-inherited-widget-app-state/).

I am really struggling with this to be honest. State management is a pain point for me.

[I've managed to get a decent architecture setup using Inherited Widgets and custom routing. I really wish this was included in a video for beginners.](https://gist.github.com/joeythomaschaske/8f3d2894b7394f1d2c2dfbdde2c28cd0)

**Comment by sfshaza2** [comment]
We have some docs in process, @joeythomaschaske, that should help with this.

**Comment by InMatrix** [comment]
I think we've added some concept docs/videos, especially https://flutter.dev/docs/get-started/flutter-for/declarative.

Do we want to consider this issue fixed?

**Comment by efortuna** [comment]
Martin is currently working on a video for the overview I think folks are looking for. But if you want we can close this; we're not using this particular bug to track progress for that.

**Comment by maguinis** [comment]
I'm working on something along these lines at the moment, as Emily stated.

**Comment by sfshaza2** [comment]
We can close this now or wait for Martin's video to go live. I defer to Tao.

**Comment by efortuna** [comment]
Martin's video is now live! https://www.youtube.com/watch?v=l-YO9CmaSUM Do we want to feature it somewhere on our website?

**Comment by maguinis** [comment]
Emily! We added it under https://flutter.dev/docs if you scroll down :)

Martin Aguinis | Developer Marketing | Flutter

**Comment by InMatrix** [comment]
This looks great. Do we have a way to track how many people view this video from that embed?

**Comment by efortuna** [comment]
Unfortunately no... YouTube doesn't distinguish between views from embedded vs direct. :-(

**Comment by InMatrix** [comment]
Got it. @galeyang, maybe you could consider using your GA Tag Manager to figure out how many users see the this video and how many clicked on it? Not sure if the latter is possible though. The docs landing page is getting longer, so I'm curious about engagement with the content below the fold.

**Comment by efortuna** [comment]
Tao, also, actually I just talked to GDS and they do have a way of getting that information. I'm waiting to hear back on stats and how to do that.

**Comment by InMatrix** [comment]
Great, thanks!

**Comment by galeyang** [comment]
I will also take a look on my side about how many users see/scroll on this page!
