### ISSUE TITLE
Hint text in API documentation Search box in distracting

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2010]
@jamesderlin commented on [Thu Oct 11 2018](https://github.com/flutter/flutter/issues/22967)

See https://github.com/flutter/website/issues/1422

---

@InMatrix commented on [Tue Oct 30 2018](https://github.com/flutter/flutter/issues/22967#issuecomment-434442451)

I'm not seeing the issue in your screenshots on my Chrome for Mac OS X. It could be a browser/OS specific bug. 

Cc: @gspencergoog @jcollins-g 

---

@jcollins-g commented on [Tue Oct 30 2018](https://github.com/flutter/flutter/issues/22967#issuecomment-434450617)

I'm seeing it on Chrome for Linux.  But it only appears to be a thing on the flutter site, not pub.dartlang.org or other dartdoc sites.  It might have something to do with the custom CSS for Flutter.

---

@jcollins-g commented on [Tue Oct 30 2018](https://github.com/flutter/flutter/issues/22967#issuecomment-434454734)

Poking around in the inspector, disabling overrides.css `#searchbox` css for border, border radius, font family, and padding seems to make the issue go away.  However I don't know if that would make things worse on other platforms.

**Comment by gspencergoog** [comment]
@zoechi, Sorry, this is not a "website" issue, it's an API docs issue.  The API docs are all generated by dartdoc as part of the build process, and the website folks don't have anything to do with that part.
