### ISSUE TITLE
Document that Swift increases app size significantly

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2011]
@hariprasadiit commented on [Tue Sep 25 2018](https://github.com/flutter/flutter/issues/22270)

With current beta `0.8.2` and latest `dev`, `flutter build ios --release` produces app which is 5 times the size of the app built with `0.7.2`.

with `0.7.2` the size was around `22mb`
with `0.8.2` the size is around `100mb`

I've tested with basic flutter app by creating new flutter app and building it. Even basic app size is around `61mb`

## Steps to Reproduce
1. Create new flutter app.
2. Run `flutter build ios --release`
3. Check the size of the app

## Images for reference
**`aot` and `app` size**

<img width="629" alt="screen shot 2018-09-25 at 10 08 37 pm" src="https://user-images.githubusercontent.com/1260204/46030076-c5636e00-c112-11e8-9862-32a8bfcd0f90.png">

**contents of the `app`**

<img width="619" alt="screen shot 2018-09-25 at 10 09 53 pm" src="https://user-images.githubusercontent.com/1260204/46030083-c98f8b80-c112-11e8-8dc3-dc60cbd0f88d.png">

## Logs

```
[✓] Flutter (Channel dev, v0.9.2, on Mac OS X 10.13.2 17C88, locale en-IN)
    • Flutter version 0.9.2 at /Users/hari/development/flutter
    • Framework revision 85b4670b2a (6 days ago), 2018-09-19 14:59:23 -0700
    • Engine revision 2e8e96fad1
    • Dart version 2.1.0-dev.4.0.flutter-4eb879133a

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/hari/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[!] Connected devices
    ! No devices available

! Doctor found issues in 1 category.
```

---

@kf6gpe commented on [Thu Oct 18 2018](https://github.com/flutter/flutter/issues/22270#issuecomment-431082011)

@goderbauer Any thoughts in how this might be related to your work? 

---

@goderbauer commented on [Fri Oct 19 2018](https://github.com/flutter/flutter/issues/22270#issuecomment-431291047)

This doesn't reproduce for me on the latest master (see below). Can you tell me what exactly you measured the size of?

```
~/dev/ $ flutter create size_test
<output omitted>
~/dev $ cd size_test/
~/dev/size_test $ flutter build ios --release
Building com.example.sizeTest for device (ios-release)...
Signing iOS app for device deployment using developer identity: "iPhone Developer: Micharl Goderbauer (KY4Q2ZN4ME)"
Starting Xcode build...                                          
 ├─Building Dart code...                             18.6s
 ├─Generating dSYM file...                            0.8s
 ├─Stripping debug symbols...                         0.0s
 ├─Assembling Flutter resources...                    1.3s
 └─Compiling, linking and signing...                 10.5s
 
Xcode build done.                                           32.8s
Built /Users/goderbauer/dev/size_test/build/ios/iphoneos/Runner.app.
~/dev/size_test $ du -hs /Users/goderbauer/dev/size_test/build/ios/iphoneos/Runner.app
 24M	/Users/goderbauer/dev/size_test/build/ios/iphoneos/Runner.app
```

The produces app has a size of 24 MB, which seems about right.

Note: The size of Runner.app does not tell you anything about the download size your app will have on the store or the size it is going to occupy on user's devices. When downloaded from the store, Apple applies a process called app thinning that removes all artifacts and architectures from the app that are not needed for the target device. The inly way to determine the true app size is to upload the app to app store connect and see what numbers apple reports there. 

---

@hariprasadiit commented on [Fri Oct 19 2018](https://github.com/flutter/flutter/issues/22270#issuecomment-431313297)

@goderbauer sorry my bad. The app size is `~27mb` for me with `objc` and `~59mb` with `swift`. In screenshot above, swift libraries contribution was about half of the app size.

Would it be useful for anyone who is new to iOS, if we mention about swift effect on final app size somewhere in the flutter website?

thanks for the help

---

@goderbauer commented on [Fri Oct 19 2018](https://github.com/flutter/flutter/issues/22270#issuecomment-431315156)

Yes, Swift apps are known to be bigger because they currently have to ship their own Swift runtime - this effect is unrelated to Flutter.

I'll turn this bug into a request to update documentation to mention that fact for Flutter as well.

---

@swingywc commented on [Sat Oct 27 2018](https://github.com/flutter/flutter/issues/22270#issuecomment-433579705)

Hi @hariprasadiit , thanks for referencing me to this issue :)
Does it mean there is nothing to do for the release build for iOS?
May I know the estimated size of the app that user will download at last? Thank you.

---

@hariprasadiit commented on [Wed Oct 31 2018](https://github.com/flutter/flutter/issues/22270#issuecomment-434609592)

@swingywc if you can switch to `objective-c` you can reduce your app size by almost `50%`. App store also compresses your app before sending it to the target device, also it does app thinning to reduce the bytes downloaded on to the device. The size seems to be normal for `swift` apps. 

  for me, generated IPA file is around `100mb` but the download size from the app store is around `45mb`, this is a fat binary which supports both 32 and 64 bits.  If you can upload different IPAs for different architecture, which is possible, then the download size can further be reduced by about `35%` to `40%`. These numbers are based on my app sizes.

**Comment by jmagman** [comment]
Docs: https://developer.apple.com/documentation/xcode-release-notes/swift-5-release-notes-for-xcode-10_2

**Comment by jmagman** [comment]
> Swift apps no longer include dynamically linked libraries for the Swift standard library and Swift SDK overlays in build variants for devices running iOS 12.2, watchOS 5.2, and tvOS 12.2. As a result, Swift apps can be smaller when they’re shipped in the App Store, deployed for testing using TestFlight, or thinned in an app archive for local development distribution.

That means your app will only be larger for your customers running iOS 12.2 or earlier.  On devices running later versions, your app will not include the Swift runtime and will be smaller.  This is true for any app that includes Swift, not just Flutter.  

I'm going to close this as at this point I don't think it's worth documenting considering iOS 12.2 came out in March 2019, and iOS adoption is pretty aggressive.  According to Apple, only 4% of all devices are on versions lower than iOS 14.
<img width="324" alt="Screen Shot 2022-08-17 at 7 17 12 PM" src="https://user-images.githubusercontent.com/682784/185278211-94035e88-d462-47bb-82ca-c1e965816ae0.png">
