### ISSUE TITLE
[Doc] [cookbook] reading-writing-files useless async keyword

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2013]
@sgon00 commented on [Wed Nov 14 2018](https://github.com/flutter/flutter/issues/24331)

In the url https://flutter.io/docs/cookbook/persistence/reading-writing-files, 

It has the function:

```dart
Future<File> _incrementCounter() async {
    setState(() {
      _counter++;
    });

    // write the variable as a string to the file
    return widget.storage.writeCounter(_counter);
  }
```

(1) Since there is no `await` here, why do we have `async` keyword? Removing the keyword doesn't harm anything. 
(2) Why do we return a File here? It's kinda useless. but whatever, not very important. 

---

@zoechi commented on [Wed Nov 14 2018](https://github.com/flutter/flutter/issues/24331#issuecomment-438588598)

It in step Complete example https://flutter.io/docs/cookbook/persistence/reading-writing-files#complete-example

---

@sgon00 commented on [Wed Nov 14 2018](https://github.com/flutter/flutter/issues/24331#issuecomment-438589823)

@zoechi sorry, I don't get what you mean. Step 3 is about `writeCounter` function, But I am talking about `_incrementCounter`. `async` is useless here. There is also no need to return anything. 

---

@zoechi commented on [Wed Nov 14 2018](https://github.com/flutter/flutter/issues/24331#issuecomment-438591513)

Uh! You're right - fixed my comment above.

---

@sgon00 commented on [Wed Nov 14 2018](https://github.com/flutter/flutter/issues/24331#issuecomment-438609456)

@zoechi thanks for the reply. Since you said "fixed", should I close this issue now? I don't see any updates in that url yet. Btw, should I open doc issue here? or in flutter/website? thanks. 

---

@zoechi commented on [Wed Nov 14 2018](https://github.com/flutter/flutter/issues/24331#issuecomment-438615267)

Sorry again, I just tried to make the issue more clear but I messed up quite a bit here :-/
I meant I fixed my comment.
Thanks for reporting the issue!

---

@sgon00 commented on [Wed Nov 14 2018](https://github.com/flutter/flutter/issues/24331#issuecomment-438616624)

@zoechi no worries. get it. cheers. :)

---

@zoechi commented on [Tue Dec 11 2018](https://github.com/flutter/flutter/issues/24331#issuecomment-446299204)

this one

![image](https://user-images.githubusercontent.com/405837/49819876-bb96f180-fd76-11e8-8ade-1fd785e35412.png)

**Comment by sfshaza2** [comment]
@brianegan

**Comment by brianegan** [comment]
Thanks, I'll patch it up!
