### ISSUE TITLE
Drop "Next step" heading and text from "Get started" pages

### ISSUE THREAD

**Issue by chalin** [flutter/website#2015]
As part of the new site's redesign, we added **next/prev links** to the **[Get started](https://flutter.io/docs/get-started)** pages, for example:

> <img width="601" alt="screen shot 2018-12-11 at 16 08 32" src="https://user-images.githubusercontent.com/4140793/49830398-0c9aeb80-fd5f-11e8-9e90-1222818b3d68.png">

These pages still have legacy **Next step** sections, but these seem quite redundant, and risk falling out-of-step when page tiles are updated. E.g., from the [Install > Windows](https://flutter.io/docs/get-started/install/windows) page:

> <img width="637" alt="screen shot 2018-12-11 at 16 05 13 copy" src="https://user-images.githubusercontent.com/4140793/49830475-423fd480-fd5f-11e8-98e2-82351be0c90b.png">

**Note:** that the next step prose has an old (outdated) page title.

I'd suggest dropping the **Next step** sections since we now have next/prev links.

Thoughts @sfshaza2 @kwalrath @galeyang @InMatrix

**Comment by galeyang** [comment]
It looks fine for me to drop it on "Set up an editor" and "Test drive" pages. A semi-related question: do we have a clear label for screen readers indicating those links are next/prev links?

**Comment by chalin** [comment]
> do we have a clear label for screen readers indicating those links are next/prev links?

No. What would you like the text to read? Simply "Link to next page" and "Link to previous page"?

**Comment by galeyang** [comment]
I'm not clear about the best practice for the screen reader. Let me check it later and file a follow up issue if needed. Thanks!

**Comment by chalin** [comment]
SG, thanks!

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/4448.
