### ISSUE TITLE
'Flutter for React Native developers' page issue

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#2019]
Page URL: https://flutter.io/docs/get-started/flutter-for/react-native-devs.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/flutter-for/react-native-devs.md

Description: 
There is a compile-time error in the dart and dartpad code in the async/await section
```
 String ip = JSON.decode(request.responseText)['origin'];
```
should be
```
    String ip = jsonDecode(request.responseText)['origin'];
```
(thanks for your hard work though, other than that it looks awesome so far)

**Comment by chalin** [comment]
Thanks for the issue! Just to be clear, the error you are seeing is in DartPad, right?

**Comment by neiljaywarner** [comment]
Both dartpad and the website

**Comment by chalin** [comment]
I'm not seeing any instances of `JSON` (allcaps) in the website code, are you? If so, can you include a screenshot?

**Comment by neiljaywarner** [comment]
hmmh. ok, so there's no bug anymore, and this isn't for this ticket anymore, but a lower case const that is not a method is a bit hard to get used to.

**Comment by neiljaywarner** [comment]
@chalin  thanks for the reply.  is there any reasoning for that or guiding philosophy link that i could review.  it is really a "huh" to see it without at least a uppercase first letter - since it's lowercase a dev will tend to look for it in the same file as a local variable.

i'm not completely understanding the "part" keyword in dart yet either...  thanks again for great work

**Comment by chalin** [comment]
For naming conventions for constants, see: https://www.dartlang.org/guides/language/effective-dart/style#prefer-using-lowercamelcase-for-constant-names, in particular the Note at the end of that section.

Where are you seeing the `part` keyword? For more information about `part`, see https://www.dartlang.org/guides/libraries/create-library-packages#organizing-a-library-package

> thanks again for great work

Thanks!
