### ISSUE TITLE
Update ANDROID_HOME references to ANDROID_SDK_ROOT

### ISSUE THREAD

**Issue by DanTup** [flutter/website#2023]
The `ANDROID_HOME` env variable is considered deprecated by the SDK:

https://developer.android.com/studio/command-line/variables

> *ANDROID_HOME*, which also points to the SDK installation directory, is deprecated

I have a PR to update Flutter to also read `ANDROID_SDK_ROOT` (though like the SDK, it will still use `ANDROID_HOME` first if it exists) to resolve https://github.com/flutter/flutter/issues/15114:

https://github.com/flutter/flutter/pull/25221

Once that change makes the stable branch, it would make sense to update the site to match, recommend setting `ANDROID_SDK_ROOT` instead. There are at least a couple of pages that reference `ANDROID_HOME`:

https://flutter.io/docs/get-started/install/macos
https://flutter.io/docs/get-started/install/linux
https://flutter.io/docs/deployment/fastlane-cd
https://flutter.io/docs/get-started/install/windows

**Comment by chalin** [comment]
SG and thanks for the heads up. Could you ping us once your PR makes it into stable?

**Comment by DanTup** [comment]
Sure, will do. It may take a while (I have some questions about testing it before landing, and then it depends on the release schedule), but I'll set a reminder to ping back here. Thanks!

**Comment by DanTup** [comment]
@chalin ping!

Flutter v1.2 is live now, and includes the change to support ANDRIOD_SDK_ROOT.

**Comment by kwalrath** [comment]
Thanks for the ping. @chalin is taking a well-earned break. @sfshaza2 can you handle this?

**Comment by DanTup** [comment]
@kwalrath FWIW, this isn't urgent - Flutter supports both variables now. This is just about recommending the new/preferred one (just changing any instance of `ANDROID_HOME` to `ANDROID_SDK_ROOT`).

**Comment by sfshaza2** [comment]
Yes, I can take care of this,

**Comment by micpap25** [comment]
Seems like the change was made, this can be closed.

**Comment by DanTup** [comment]
Yep, looks like it was done in #4246.
