### ISSUE TITLE
Doc improvement Continuous Delivery wrong link

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2024]
@HerrNiklasRaab commented on [Sat Nov 17 2018](https://github.com/flutter/flutter/issues/24471)

On this site: https://flutter.io/docs/deployment/fastlane-cd
The link in chapter "Cloud build and deploy setup" point 3 is linked to the page itself

**Comment by HerrNiklasRaab** [comment]
I mean the link " fastlane CI documentation"! Just to make it clear.

**Comment by zoechi** [comment]
![image](https://user-images.githubusercontent.com/405837/49876887-8e088180-fe24-11e8-8124-aaee94990dd7.png)

**Comment by chalin** [comment]
Thanks! A fix is on the way.
