### ISSUE TITLE
'Widget catalog' page issue

### ISSUE THREAD

**Issue by Thomaslay7** [flutter/website#2029]
Page URL: https://flutter.io/docs/development/ui/widgets/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/widgets/index.md

Description:
the image can not showed

**Comment by chalin** [comment]
Hi, could you clarify which image you are referring to, and ideally also include a screenshot?

**Comment by chalin** [comment]
If by "image not shown" you mean that the Flutter logo is displayed instead, then that is expected. Not all entries have their own images. If that isn't what you meant, please add a screenshot. I'm going to close this issue for now, but we'll reopen it once you provide more information. Thanks.
