### ISSUE TITLE
Misleading step in the firebase for flutter tutorial

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2034]
@shia86 commented on [Sat Nov 24 2018](https://github.com/flutter/flutter/issues/24693)

There was a misleading in the step 5 of [firebase for flutter](https://codelabs.developers.google.com/codelabs/flutter-firebase/#4).

> Save the file, then hot-reload your app.
 You should see the following app

The application won't shown up and will crash. Firebase needs to be setup according to the step 6-7.

**Comment by sfshaza2** [comment]
@ditman, can we close this one, too?

**Comment by ditman** [comment]
Step 5 of the tutorial doesn't use Firebase yet. I don't understand why this is crashing, unless some steps were performed out of order.

I remember going through this codelab and not having issues in step 5 (with the mock data added). Can anybody else confirm?

**Comment by sfshaza2** [comment]
We can no longer reproduce this. Closing.
