### ISSUE TITLE
Document that a CupertinoApp isn't necessary for an iOS app

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2035]
@xster commented on [Tue Nov 27 2018](https://github.com/flutter/flutter/issues/24766)

From https://medium.com/asos-techblog/flutter-vs-react-native-for-ios-android-app-development-c41b4e038db9 it wasn't clear that CupertinoApp wasn't necessary to build an iOS app. Document and add an example.

**Comment by xster** [comment]
Sorry, I meant for this to be documented in the API docs
