### ISSUE TITLE
Flutter FAQ is not prominently visible

### ISSUE THREAD

**Issue by jamesderlin** [flutter/website#2047]
Page URL: https://flutter.io/docs/
Page source: https://github.com/flutter/website/tree/master/src/docs/index.md

Description:
I think that the Flutter FAQ is a bit hard to find now in the site design. The link to it is buried in the "Resources" section of flutter.io/docs, which is collapsed by default.

Doing in-page searches of the  flutter.io home page and of flutter.io/docs/ for "FAQ" or "Frequent" find no matches.

Using the site's Search box with "FAQ" does find https://flutter.io/docs/resources/faq, but that requires prior knowledge that the FAQ exists.

Recommendation:
Add an explicit "Frequently asked questions (FAQ)" link to the content area of the flutter.io/docs page (probably under the "New to Flutter?" section).  I think that linking to it from somewhere on the home page would be nice too.

**Comment by chalin** [comment]
@InMatrix @galeyang @sfshaza2 - thoughts? cc @kwalrath

**Comment by galeyang** [comment]
I agree. At some point, we had a quick conversation on the discoverability of FAQ but didn't make any changes. I support the idea of adding FAQ to flutter.io/docs page.
