### ISSUE TITLE
'Animations tutorial' page issue

### ISSUE THREAD

**Issue by RaviKavaiya** [flutter/website#2051]
Page URL: https://flutter.io/docs/development/ui/animations/tutorial#refactoring-with-animatedbuilder
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/animations/tutorial.md

Description:

Here, before the widget tree, a link to source code is provided, which is "animate5". But, to match with the widget tree given, "animate4" should be there....

**"animate5"** is the file for multi tweens....

**Comment by mjohnsullivan** [comment]
Link before the widget tree now correctly points to animate4
