### ISSUE TITLE
'Write your first Flutter app, part 1' page issue

### ISSUE THREAD

**Issue by tulkuras** [flutter/website#2057]
Page URL: https://flutter.io/docs/get-started/codelab.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab.md

Description: in step 1, said "Replace with the following code, which displays “Hello World” in the center of the screen." This code will throw an error, thus the functions used are not defined.

In this URL: https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/index.html?index=..%2F..index#2. The code will work because they add the "new" in each statement. 
Please, change the code website so new developers will not get frustated.

**Comment by chalin** [comment]
> This code will throw an error, thus the functions used are not defined

Which functions are undefined (it would help if you shared the exact error messages that you are getting, by either copying the text or using a screenshot).

**Comment by tulkuras** [comment]
E/flutter (26771): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (26771): NoSuchMethodError: Attempted to use type 'MyApp' as a function. Since types do not define a method 'call', this is not possible. Did you intend to call the MyApp constructor and forget the 'new' operator?
E/flutter (26771): Receiver: MyApp
E/flutter (26771): Tried calling: MyApp()

I remember, in the beta testing, the code had "new" in each statement.

**Comment by chalin** [comment]
Are you still getting this error when using Flutter 1.0?

**Comment by tulkuras** [comment]
> Are you still getting this error when using Flutter 1.0?

I was using Flutter 0.1.6, I thought that I had the latest update. Thank you, chalin, for helping me, have a nice day.

**Comment by chalin** [comment]
Ok, thanks for clarifying. Closing for now; if you still have the problem, please reopen this issue.
