### ISSUE TITLE
'Layout widgets' page issue

### ISSUE THREAD

**Issue by xiaoowuu** [flutter/website#2058]
Page URL: https://flutter.io/docs/development/ui/widgets/layout.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/widgets/layout.md

Description:
"Expanded" widget is in the wrong category,it can contain only one child widget.

**Comment by micpap25** [comment]
As of right now, it looks like "Expanded" is in the single-child section. I think this issue can be closed safely.

**Comment by micpap25** [comment]
Just bumping this, @sfshaza2

**Comment by MiraMarshall** [comment]
Closing. Expanded is under Single-child layout widgets.
