### ISSUE TITLE
Java developers can be confused by Dart Null behavior

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2061]
@eseidelGoogle commented on [Tue Jun 05 2018](https://github.com/flutter/flutter/issues/18207)

http://cogitas.net/5-lessons-learned-flutter/

"""
Don’t let your print statements crash your app
While working on new code, I often litter it with print statements, so if it doesn’t work  as expected when I run it, I can find out from the logs why. Well, sometimes, the print statements were the reason for the problem!

It turns out that `print("Step 1" + expectedStringInstance.toString())`  will run fine if `expectedStringInstance` is `null` but `print("Step 1" + expectedStringInstance)` will throw an `ArgumentError` exception.

As a Java developer, it’s one of the few counter intuitive things I have found in Dart and I keep being caught out! (I’m guessing it is because null is an instance of the class Null)
"""

Seems like something we should add to our "Flutter for Android Devs" doc?
https://flutter.io/flutter-for-android/

Thoughts @Sfshaza @mjohnsullivan?  Not at all urgent. :)

---

@jacob314 commented on [Tue Jun 05 2018](https://github.com/flutter/flutter/issues/18207#issuecomment-394790786)

As some background: 
In Dart if you want to format debug messages you should use string interpolation instead of string concat. String + is designed to be strict to help developers catch bugs early and only allows adding strings to strings not arbitrary objects.
This avoids bugs like showing `Username: undefined` or `Destination: [[Object]]` in their UI because an object was concat with a String.

**Comment by sfshaza2** [comment]
@kwalrath, thoughts?  I'd like to either incorporate or close this issue. :)

**Comment by kwalrath** [comment]
I can do that, but first I want to make sure we aren't going to change it.

@leafpetersen?

**Comment by leafpetersen** [comment]
In null safe code, `print("Step 1" + expectedStringInstance)` will be a static error if `expectedStringInstance` has type `String?`.  If `expectedStringInstance` has type `String`, then it can never be null (at least if the whole app is migrated to null safety).

In the full null safety world, the only way you can get an error there is if `expectedStringInstance` has type `dynamic`, in which case there is a cast to `String` implied there which can fail.

Does that answer the question?

**Comment by parlough** [comment]
I think now that we are in a (mostly) null safe world and this will be a static error, this situation should be identifiable with the output from the analyzer and compilers, and understanding should be covered by general null safe discussion in learning material. Thanks all.
