### ISSUE TITLE
Update screenshots on homepage with new iOS demo

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2062]
@sethladd commented on [Mon Dec 11 2017](https://github.com/flutter/flutter/issues/13494)

There's a very cool Cupertino Navigation demo in the gallery. We'd like to show it on flutter.io homepage.

---

@zoechi commented on [Mon Dec 03 2018](https://github.com/flutter/flutter/issues/13494#issuecomment-443711642)

Is this covered by 

![image](https://user-images.githubusercontent.com/405837/49376739-95cf7400-f708-11e8-9cad-e91f25bbc1dd.png)

?

**Comment by sfshaza2** [comment]
We've since redone the site. Closing.
