### ISSUE TITLE
Explain how to write/run a performance test for a Flutter app

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2065]
@eseidelGoogle commented on [Tue Jan 23 2018](https://github.com/flutter/flutter/issues/14237)

We have our own performance tests (which are public), but we don't really have a good example for developers to use themselves for testing the performance of their app.

One example would be to show an example of replicating the Flutter Gallery missed frames benchmark with a simpler sample app.

Another example could be showing how to benchmark some piece of business logic just like @mraleph showed in his Talk at DartConf.

This bug may be too general to track here, but wanted to write this down for our medium-term docs/examples planning.  FYI @mjohnsullivan 

---

@zoechi commented on [Tue Dec 04 2018](https://github.com/flutter/flutter/issues/14237#issuecomment-444120348)

Is this covered by 
https://flutter.io/docs/testing/ui-performance
https://flutter.io/docs/cookbook/testing/integration/profiling
?

**Comment by sfshaza2** [comment]
I started writing a codelab on this, but other priorities took precedence.

**Comment by humblerookie** [comment]
@sfshaza2 Is the codelab available? Could I get some mock code if not or something reference.

**Comment by atsansone** [comment]
This exists on the [Performance Profiling page](https://docs.flutter.dev/cookbook/testing/integration/profiling).
