### ISSUE TITLE
Document how to get a trace

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2067]
@sethladd commented on [Fri Jul 15 2016](https://github.com/flutter/flutter/issues/4934)

@dragostis and I couldn't find simple docs on how to capture a trace, using Flutter and Observatory.

It's straightforward, once you know how to do it. I think we can add a few documented steps to https://flutter.io/debugging/

---

@eseidelGoogle commented on [Fri Jul 15 2016](https://github.com/flutter/flutter/issues/4934#issuecomment-233073279)

The observatory timeline exposes tracing, there also used to be a `flutter trace` command which could be used to start/stop tracing it may still work.

---

@sethladd commented on [Fri Jul 15 2016](https://github.com/flutter/flutter/issues/4934#issuecomment-233073615)

cc @qchong 

---

@eseidelGoogle commented on [Tue Nov 08 2016](https://github.com/flutter/flutter/issues/4934#issuecomment-259252641)

This also likely relates some to https://github.com/flutter/flutter/issues/5550.

---

@Hixie commented on [Tue Jan 31 2017](https://github.com/flutter/flutter/issues/4934#issuecomment-276291253)

cc @chinmaygarde who mentioned writing a document about performance

---

@Hixie commented on [Mon Sep 18 2017](https://github.com/flutter/flutter/issues/4934#issuecomment-330356166)

We definitely need to document how to take a trace, how to use the trace viewer, how to interpret the results...

---

@eseidelGoogle commented on [Thu Dec 06 2018](https://github.com/flutter/flutter/issues/4934#issuecomment-444699671)

We really need to solve this. :(  If for no other reason than to have it written down for all the many folks joining the Flutter team.  @chinmaygarde @cbracken @Hixie any of you want to take a stab?  Even something quick and short and in a doc or wiki? :)

(This is not actually urgent, clearly.  Just silly that we still don't have this written down anywhere.)

**Comment by robsonfingo** [comment]
Has the article been published? Is there a way to get the trace programmatically from inside the app?

**Comment by cbracken** [comment]
@robsonfingo yes. @chinmaygarde published [Profiling Flutter Applications Using the Timeline](https://medium.com/flutter-io/profiling-flutter-applications-using-the-timeline-a1a434964af3) on Medium.

**Comment by sfshaza2** [comment]
Closing. (This is much easier in Dart DevTools, btw.)
