### ISSUE TITLE
Issue from website page Write Your First Flutter App

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2068]
@kozarbohdan commented on [Sat Jul 14 2018](https://github.com/flutter/flutter/issues/19373)

From URL: https://flutter.io/get-started/codelab/

When using this code:
```dart
import 'package:flutter/material.dart';
import 'package:english_words/english_words.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'Welcome to Flutter',
      home: new Scaffold(
        appBar: new AppBar(
          title: new Text('Welcome to Flutter'),
        ),
        body: new Center(
          child: new RandomWords(),
        ),
      ),
    );
  }
}

class RandomWords extends StatefulWidget {
  @override
  createState() => new RandomWordsState();
}

class RandomWordsState extends State<RandomWords> {
  @override
  Widget build(BuildContext context) {
    final wordPair = new WordPair.random();
    return (new Text(wordPair.asPascalCase));
  }
}
```

I have an issue. The app loads to device, but it is the standard widget with title "Welcome To Flutter" and text "Hello World" in the middle of the screen.

First I thought that i have missed something, but after copying the source, problem remained.

---

@joshuaalm commented on [Thu Jul 19 2018](https://github.com/flutter/flutter/issues/19373#issuecomment-406107287)

A similar issue is seen when later we are told to "remove the Scaffold and AppBar references from MyApp" because the title and Scaffold are returned as part of Widget object from the build function.

**Comment by sfshaza2** [comment]
@chalin, just checking to see if this is still true.

**Comment by chalin** [comment]
The codelab has been reworked since last July. If you still have this issue with the updated codelab, let us know.

**Comment by lyntree** [comment]
Can someone please look into this as now its almost 2 years later in 2021 and still having the same issue? Same code but does not want to work
