### ISSUE TITLE
Recipe page doesn't link to other recipes or cookbook, hard to tell what I'm looking at

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2070]
@sethladd commented on [Sat Apr 21 2018](https://github.com/flutter/flutter/issues/16828)

We're now linking to recipes from #FlutterFriday tweets. Yay! But, when you view the recipe, especially on mobile, it's not clear what you're looking at, and it's not clear how to find the other recipes.

Suggestion: add a link to the Cookbook homepage (maybe at the top, near the title), making it clear that "this is a recipe" and "there's a whole bunch of other recipes" :)

---

@sethladd commented on [Sat Apr 21 2018](https://github.com/flutter/flutter/issues/16828#issuecomment-383246026)

cc @brianegan 

---

@brianegan commented on [Tue Apr 24 2018](https://github.com/flutter/flutter/issues/16828#issuecomment-383864445)

Thanks for the heads up, Seth! Sorry about the delay -- unfortunately caught a cold right as the weather is getting nice and feeling a bit rough :(

I'll try a couple options to see how we can work this in!

---

@zoechi commented on [Tue Jul 17 2018](https://github.com/flutter/flutter/issues/16828#issuecomment-405536737)

Is this still an issue?

---

@brianegan commented on [Tue Jul 17 2018](https://github.com/flutter/flutter/issues/16828#issuecomment-405539233)

@zoechi It is! I've talked with the Flutter team and they mentioned they're working on some redesigns of the documentation pages and so I've held off on adding anything like this manually. 

That said, perhaps I can add a "Breadcrumb" module for Jekyll see if it works for this purpose.

---

@Sfshaza commented on [Mon Aug 06 2018](https://github.com/flutter/flutter/issues/16828#issuecomment-410826342)

I like the idea of a breadcrumb for the cookbook. But, yes, given that we are reworking the website, I want to avoid setting up links that will have to be changed in the near future.

---

@zoechi commented on [Thu Dec 06 2018](https://github.com/flutter/flutter/issues/16828#issuecomment-444886496)

@Sfshaza 

>  given that we are reworking the website

Is this still wip or is this completed already?

**Comment by chalin** [comment]
Yes, it is WIP, we have partial breadcrumbs. I'm going to close this issue in favor of tracking the individual features:

- Add next/prev links to cookbook pages #1370
- Add breadcrumbs to cookbook pages #1371

If @sethladd or anyone else feels that these two issues don't fully cover it, please feel free to reopen.
