### ISSUE TITLE
Document conventions for accessing and checking MethodCall arguments on Java

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2077]
@mravn-google commented on [Sat Apr 07 2018](https://github.com/flutter/flutter/issues/16327)

Cf https://github.com/flutter/plugins/pull/466#discussion_r179887667

---

@xster commented on [Sat Apr 07 2018](https://github.com/flutter/flutter/issues/16327#issuecomment-379408477)

Document the preferred way of handling exceptions between `result.error(...)`, `throw new IllegalArgumentException`, `result.notImplemented` etc on Java. 

`@throw`, `result([FlutterError...`,  `result(FlutterMethodNotImplemented)` on iOS. 

---

@Sfshaza commented on [Mon May 21 2018](https://github.com/flutter/flutter/issues/16327#issuecomment-390788873)

The referred issue is fixed and landed. Presumably this is ready to address.

**Comment by atsansone** [comment]
This was fixed in https://github.com/flutter/website/pull/3438. Closing this issue.
