### ISSUE TITLE
Flutter codelab link to a doc is broken

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2078]
@atn832 commented on [Wed Nov 14 2018](https://github.com/flutter/flutter/issues/24351)

https://codelabs.developers.google.com/codelabs/flutter/#6
has a link to the documentation for TickerProviderStateMixin, but it returns error 404:
https://docs.flutter.io/flutter/widgets/TickerProviderStateMixin-class.html

---

@dnfield commented on [Wed Nov 14 2018](https://github.com/flutter/flutter/issues/24351#issuecomment-438830081)

The correct link is now https://docs.flutter.io/flutter/widgets/TickerProviderStateMixin-mixin.html

@sfshaza2 - do you know where this content lives?

---

@dnfield commented on [Wed Nov 14 2018](https://github.com/flutter/flutter/issues/24351#issuecomment-438841010)

For more context - we refactored several mixin-like abstract classes to use a new syntax in Dart.  Apparently this means the API doc links for all of those has changed.  Some more details are in the linked issue.

Also @atn832 - I originally pasted the wrong link above, I've corrected it.

Thanks for the report!

**Comment by sfshaza2** [comment]
Fixed. Closing.
