### ISSUE TITLE
Flutter.io should provide a link to the Flutter Gallery page on the Play Store

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2079]
@InMatrix commented on [Mon May 07 2018](https://github.com/flutter/flutter/issues/17352)

It seems that we don't currently link to Flutter Gallery on the Play Store from flutter.io?

Cc: @maguinis

**Comment by sfshaza2** [comment]
This is still true, though it's not clear where we would link it. Flutter Gallery is not on the showcase wall (but maybe it used to be). Here's the link on play store:
https://play.google.com/store/apps/details?id=io.flutter.demo.gallery

**Comment by InMatrix** [comment]
How about the "Expressive Beautiful UIs" section of the landing page? What's a little inconvenient is that we don't have Flutter Gallery on the iOS app store. 

![image](https://user-images.githubusercontent.com/348942/51947166-bcdcb600-23d8-11e9-8ba8-6f7e0e4d7022.png)

**Comment by sfshaza2** [comment]
Yes, linking to the new page would be nice.

**Comment by parlough** [comment]
Now that the web based Flutter gallery as well as samples index are linked on the sidenav and elsewhere on the site, I think that's sufficient, as they are more easily accessible. The Play store entry doesn't seem updated anymore anyway.
