### ISSUE TITLE
Accessibility Docs

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2081]
@eseidelGoogle commented on [Wed Feb 28 2018](https://github.com/flutter/flutter/issues/14973)

I think our only docs on accessibility are here:
https://docs.flutter.dev/ui/widgets/accessibility

We presumably will want a doc sometime in the medium term about making ones Flutter app awesomely accessible.

FYI @goderbauer 

---

@zoechi commented on [Tue Dec 04 2018](https://github.com/flutter/flutter/issues/14973#issuecomment-444104876)

There is https://flutter.io/docs/development/accessibility-and-localization/accessibility

---

@zoechi commented on [Tue Dec 04 2018](https://github.com/flutter/flutter/issues/14973#issuecomment-444105374)

Some additional information about how to implement Semantics in custom components would be interesting.

**Comment by sfshaza2** [comment]
Hey, community! Please vote! Thumbs up this issue if you think it's important.

**Comment by atsansone** [comment]
A guide to accessibility in Flutter exists. Closing this issue.
