### ISSUE TITLE
friendly_chat is not aware of the iPhone X

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2082]
@eseidelGoogle commented on [Thu Dec 14 2017](https://github.com/flutter/flutter/issues/13569)

https://10clouds.com/blog/flutter-cross-platform-apps/

Shows a picture of friendly_chat on a iphone X, seems like it's not respecting the safe area enough?

@collinjackson @cbracken Maybe this is already fixed?

---

@sethladd commented on [Thu Dec 14 2017](https://github.com/flutter/flutter/issues/13569#issuecomment-351762834)

Good catch.

---

@collinjackson commented on [Thu Dec 14 2017](https://github.com/flutter/flutter/issues/13569#issuecomment-351784069)

I think `_buildTextComposer`'s `Container` should have a `padding: new EdgeInsets.only(bottom: MediaQuery.of(context).padding.bottom)`. This will start to matter in step 3 of the UI codelab and needs to be propagated forward.

/cc @LarkAscending 

---

@cbracken commented on [Fri Dec 15 2017](https://github.com/flutter/flutter/issues/13569#issuecomment-351908476)

Arguably, introducing [`SafeArea`](https://docs.flutter.io/flutter/widgets/SafeArea-class.html) is pretty valuable in teaching new developers how easy it is to account for system insets. I'm happy to make the code change, but we'll definitely want to update the docs to explain what's going on here.

---

@cbracken commented on [Wed Jan 03 2018](https://github.com/flutter/flutter/issues/13569#issuecomment-355131603)

@LarkAscending I scheduled a quick catchup to run over the changes for this.

---

@dexcell commented on [Sun Apr 01 2018](https://github.com/flutter/flutter/issues/13569#issuecomment-377786596)

Sorry for out of topic, i also found when trying the example, that the keyboard is not automatically dismissed when scrolling, any idea how to achieve this? Kind of `tableView.keyboardDismissMode = .onDrag` in ios environment.

**Comment by kwalrath** [comment]
See also: #2083. We aren't planning to update the codelab right now, but if @cbracken updates the code, we should update the text.

**Comment by sfshaza2** [comment]
I've rewritten this codelab. (It's currently in review.) This is no longer an issue. Closing.
