### ISSUE TITLE
FAQ: document Flutter's fixed memory cost

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2085]
@xster commented on [Wed Dec 06 2017](https://github.com/flutter/flutter/issues/13393)

https://flutter.io/faq/#how-big-is-the-flutter-engine should include a blank run memory cost too

---

@sethladd commented on [Thu Dec 07 2017](https://github.com/flutter/flutter/issues/13393#issuecomment-349813467)

Can someone can suggest a way to do this, which is easily repeatable?

---

@xster commented on [Thu Dec 07 2017](https://github.com/flutter/flutter/issues/13393#issuecomment-349834187)

If easy were a relative term, I'll run through it once to test. 
My methodology will basically be flutter create, delete everything in pubspec, delete everything in main.dart and build release in flutter tools then run it in xcode and android studio. Use native instrumentation tools to measure memory.

---

@xster commented on [Thu Dec 07 2017](https://github.com/flutter/flutter/issues/13393#issuecomment-349840676)

Ran it a few times on a blank app. 

iOS: 
22mb
24mb
22mb

For comparison, the stock calculator app takes 18mb

Total heap allocation is 2.67mb.

Android:
65mb
56mb
64mb

It's almost entirely consumed by graphics buffers. 

Total heap allocation is 4.04mb.

---

@xster commented on [Thu Dec 07 2017](https://github.com/flutter/flutter/issues/13393#issuecomment-350075479)

Also caveat: Android was tested on a Nexus 5X. Each Android OEM OS can choose an arbitrary number as an opener for initial heap allocation as far as I remember based on that device's RAM size. 

---

@Hixie commented on [Fri Dec 08 2017](https://github.com/flutter/flutter/issues/13393#issuecomment-350122068)

Probably worth including a `MaterialApp` and a call to `runApp` in these calculations, because we position the framework as a big part of the offering and the framework is bound to use up a lot of RAM too.

**Comment by atsansone** [comment]
The update on the page is as of March 2021, 3 years after this issue was filed. Considering this complete. Closing.
