### ISSUE TITLE
Document direct CocoaPods in native code more

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2086]
@xster commented on [Tue Nov 21 2017](https://github.com/flutter/flutter/issues/13130)

Currently, our optimized flow involves using cocoapods transiently by consuming entire plugins that includes dart and their corresponding native code. 

There will be edge cases where the user doesn't use any plugins and just writes custom native iOS code and just want to bring in another custom native iOS cocoapod dependency (unrelated to flutter). Document that in that case, they'd have to follow standard iOS development patterns and create a Podfile and run pod install manually.

**Comment by leighajarett** [comment]
Hmm I am not entirely sure. I haven't heard this come up as an issue so let's close it for now.
