### ISSUE TITLE
Deal with this week's biggest 404s

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#2089]
Consider providing redirects for these:

* /images/intellij/hot-reload.gif: Did this recently go away, or was it a bad URL to start with? We have a variety of referrers trying to load it. (They really shouldn't load an image that's on another website, though.) https://note.mu/najeira/n/n8924408dd07b is the biggest referrer. It doesn't embed the image, but does link to it. I don't know what it should redirect to.
* /docs/development/ui/widgets/widgetindex: It has almost as many referrers, from a wide variety of sites. Maybe we should redirect it to https://flutter.io/docs/reference/widgets.

**Comment by chalin** [comment]
> /images/intellij/hot-reload.gif: Did this recently go away

It was a recent change. As I update pages, I've been progressively migrating images to be under asset management. Migrated image file names have a fingerprint, which makes redirecting to the same image (via flutter.io), potentially difficult to maintain.

As you point out, they shouldn't be referring to the image in this way. That being said, I could redirect that URL to https://raw.githubusercontent.com/flutter/website/master/src/_assets/image/tools/android-studio/hot-reload.gif.

> /docs/development/ui/widgets/widgetindex: It has almost as many referrers, from a wide variety of sites. Maybe we should redirect it to https://flutter.io/docs/reference/widgets.

Yes.
