### ISSUE TITLE
'Internationalizing Flutter Apps' page issue

### ISSUE THREAD

**Issue by virtualli** [flutter/website#2096]
Page URL: https://flutter.io/docs/development/accessibility-and-localization/internationalization.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

Description:
```
localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate, 
      ],
      supportedLocales: [
        const Locale('zh', 'CN'), 
      ],
```

call fun showMyDatePicker, need _kDatePickerHeaderPortraitHeight+10, show ok. else warning need Flexible

**Comment by kwalrath** [comment]
Sorry, we don't understand the problem. Could you please explain further?

**Comment by virtualli** [comment]
code:
localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate, 
      ],
      supportedLocales: [
        const Locale('zh', 'CN'), 
      ],

 then: _selectDate = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(2016),
      lastDate: DateTime(2022),
    );
run code in android：
![image](https://user-images.githubusercontent.com/3785055/50408729-078e6f80-0828-11e9-890d-22c7a655130d.png)

**Comment by parlough** [comment]
Thanks for opening an issue!

This page has been updated quite a lot since then and has a new example using `CalendarDatePicker` instead, so I'm going to close this. Let us know if you have any more issues. Thanks again!
