### ISSUE TITLE
Would like testing docs to include discussion of golden tests

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2100]
@eseidelGoogle commented on [Wed Oct 10 2018](https://github.com/flutter/flutter/issues/22909)

This was brought up in a customer discussion.  @filiph was there.

The customer in question seems to have figured them out (so addressing this is not urgent), just recording the desire.

---

@eseidelGoogle commented on [Wed Oct 10 2018](https://github.com/flutter/flutter/issues/22909#issuecomment-428618098)

Notes I took to myself:
* Why don't golden tests work on Mac/Linux shared / Should we update the docs to talk about this?
* What other testing solutions should we recommend? (e.g. reference tests)
* What other caveats should we put in the golden docs?

---

@zoechi commented on [Wed Oct 10 2018](https://github.com/flutter/flutter/issues/22909#issuecomment-428634997)

https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package%3Aflutter provides some information but focused on adding them to the Flutter repo itself.

**Comment by filiph** [comment]
First step, I'll make double sure this is the expected behavior, and why.

If it's expected, I'll take care of the docs.

**Comment by zoechi** [comment]
@filiph 

> this is the expected behavior, and why.

Do you mean 

> Why don't golden tests work on Mac/Linux shared / Should we update the docs to talk about this?

See also https://github.com/flutter/flutter/issues/17483

**Comment by atsansone** [comment]
This duplicates https://github.com/flutter/website/issues/4855. Closing this issue.
