### ISSUE TITLE
Redundant Code in getting started

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2102]
@Isfaaq commented on [Thu Dec 20 2018](https://github.com/flutter/flutter/issues/25625)

Hi all. Please see the attached capture. I believe that the modified line 10 in the diff is redundant. I am willing to change it, if someone could indicate the directory in which the docs are located.
![screenshot from 2018-12-20 20-22-51](https://user-images.githubusercontent.com/17203172/50296995-26da7500-0495-11e9-986a-12551336c7f5.png)

---

@zoechi commented on [Thu Dec 20 2018](https://github.com/flutter/flutter/issues/25625#issuecomment-449075626)

What do you mean by redundant?
This diff shows the code before (red) and after (green) the change.
The line 10 was replaced by the first green line.

---

@Isfaaq commented on [Thu Dec 20 2018](https://github.com/flutter/flutter/issues/25625#issuecomment-449088010)

@zoechi The line 10 which is in green may be replaced without affecting the final application, hence it is redundant.

---

@zoechi commented on [Thu Dec 20 2018](https://github.com/flutter/flutter/issues/25625#issuecomment-449088408)

You mean because there is no AppBar to show it?

**Comment by Isfaaq** [comment]
I will try to make myself as clear as possible. I am just getting started with Flutter and followed [this codelab](https://flutter.io/docs/get-started/codelab). When I managed to replicate the codes and have them work correctly, I started experimenting. One thing I noticed was the similarity between the codes on line 10 and 23(see the ![capture](https://user-images.githubusercontent.com/17203172/50303526-c6ecca00-04a6-11e9-8bcc-8a269f2b6e4e.png)).Removing line 10 seemed to have no effect on the final rendition of the application and this is what prompted me to open this issue.

**Comment by Isfaaq** [comment]
If this is worth correcting, I would like to "give back" and contribute. Can I go ahead with it?

**Comment by chalin** [comment]
Thanks for the issue. While those `title` arguments have the same value, they serve distinct purposes. For example, see the [MaterialApp.title](https://docs.flutter.io/flutter/material/MaterialApp/title.html) API description:

> On Android the titles appear above the task manager's app snapshots which are displayed when the user presses the "recent apps" button. On iOS this value cannot be used. CFBundleDisplayName from the app's Info.plist is referred to instead whenever present, CFBundleName otherwise.

Note that you have the same string repetition in the code of step 1 (and again, they serve distinct purposes):

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter', // <=======================
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'), // <=======================
        ),
        body: Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}
```

I hope that this helps. /cc @sfshaza2
