### ISSUE TITLE
Update lifecycle events `inactive` state on 'Flutter for Android developers' page

### ISSUE THREAD

**Issue by PermutoDev** [flutter/website#2105]
Page URL: https://docs.flutter.dev/get-started/flutter-for/android-devs
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/flutter-for/android-devs.md

Description:

Section: How do I listen to Android activity lifecycle events?

> inactive — The application is in an inactive state and is not receiving user input. This event only works on iOS, as there is no equivalent event to map to on Android

But in documentation: (https://api.flutter.dev/flutter/dart-ui/AppLifecycleState.html)

> inactive → const AppLifecycleState
> (...) On Android, this corresponds to an app or the Flutter host view running in the foreground inactive state. Apps transition to this state when another activity is focused, such as a split-screen app, a phone call, a picture-in-picture app, a system dialog, or another window.
Apps in this state should assume that they may be paused at any time.

Please clarify this discrapency

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/5541. Closing.
