### ISSUE TITLE
Add screenshots in step 2-5 on 'Building Layouts' page

### ISSUE THREAD

**Issue by galeyang** [flutter/website#2108]
Page URL: https://docs.flutter.dev/ui/layout/tutorial
Page source: https://github.com/flutter/website/blob/master/src/docs/development/ui/layout/tutorial.md

Description:
In a recent study, participants had to scroll up and down to compare the image on the top of the page and the code samples in each step. One participant suggested putting relevant screenshots close to (above) the UI code samples to set the context.

For example -- 

### Step 2: Implement the title row
![image](https://user-images.githubusercontent.com/5102864/50358518-78731600-050e-11e9-84fd-cb283b5cef49.png)
First, you’ll build the left column [...]

### Step 3: Implement the button row
![image](https://user-images.githubusercontent.com/5102864/50358578-b1ab8600-050e-11e9-86f6-ea4f86961a9b.png)
The button section contains 3 columns [...]

cc: @jayoung-lee @sfshaza2

**Comment by chalin** [comment]
The tutorial is now setup so that each step is a full app, so it should be easy to get the screenshots once we have the basic screen capture tooling in place. cc @RedBrogdon

**Comment by atsansone** [comment]
Related to https://github.com/flutter/website/issues/8922 and https://github.com/flutter/website/issues/3056.

**Comment by parlough** [comment]
Reopening since the change was reverted in https://github.com/flutter/website/pull/9927
