### ISSUE TITLE
'Test drive' page: add a description about code formatting, inspector, outline

### ISSUE THREAD

**Issue by galeyang** [flutter/website#2109]
Page URL: https://flutter.io/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Description: 
(Move website issue in https://github.com/flutter/flutter-intellij/issues/2926 to this repo)

From a recent user study, we found that users could not discover the useful IDE features that come with Flutter plugin such as Outline or Inspector, while exploring Flutter for an hour.

In Test Drive page, we can add a short description/tip about code formatting, inspector, outline in this page that links to a more detailed page.

cc: @jayoung-lee @InMatrix @sfshaza2

**Comment by sfshaza2** [comment]
This material is covered in the "Your first Flutter app" codelab, which is immediately after this page. Closing.
