### ISSUE TITLE
Left nav: make tutorials more easily discoverable

### ISSUE THREAD

**Issue by galeyang** [flutter/website#2110]
From a recent new user study, some participants wanted to see more tutorials after "Get started". They didn't immediately find the tutorials under "Development" and tutorials index under "Reference". Hence, we would like to make tutorials more easily discoverable. 

Can we consider:
1. renaming "Samples & Codelabs" to **"Samples & Tutorials"** and also
2. moving the [Flutter Tutorials index](https://flutter.io/docs/reference/tutorials) page under this group?

cc: @jayoung-lee @InMatrix @sfshaza2

**Comment by chalin** [comment]
Sounds like a good idea. How about naming it "Tutorials & samples"?

**Comment by galeyang** [comment]
I'm slightly in favor of "Samples & tutorials" because tutorials are still available under other menu and this is the only place for sample apps. I'd love to hear other thoughts on this.

**Comment by chalin** [comment]
Remember that we don't want a page to appear in two places in the IA (unless we accept that only one of the places will be the canonical destination regardless of which entry is clicked in the sidenav).

**Comment by galeyang** [comment]
Yes! The actual tutorials page live under each topic. We just offer an index/list of links here.

**Comment by chalin** [comment]
> The actual tutorial pages live under each topic. We just offer an index/list of links here.

So you want to duplicate the index pages? I thought that we had agreed to avoid duplicate pages (e.g., for SEO).

**Comment by galeyang** [comment]
No. This request is about moving that index page from "Reference" to "Samples & tutorials", so we don't have to worry about adding duplicate pages.

**Comment by chalin** [comment]
Thanks for the clarification.
