### ISSUE TITLE
'Widget catalog' page: rework widget catalog

### ISSUE THREAD

**Issue by galeyang** [flutter/website#2113]
Page URL: https://flutter.io/docs/development/ui/widgets/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/widgets/index.md

Description:
This is a potential future project.

From a recent new user study, we found participants had a hard time using the widget catalog, because they did not have previous knowledge on which one is where (e.g., Card widget is under Material Component, rather than Layout). We can consider redesigning this catalog. One potential idea is to list all widgets and support filters.

We would need to further discuss solutions and to identify resources for implementation.

cc: @jayoung-lee @InMatrix @sfshaza2

**Comment by chalin** [comment]
Maybe you'd like something link the webdev API filter: https://webdev.dartlang.org/api?query=app. As you type in the search box (which is initialized to "app" by the previous URL), it shows relevant entries under each category.

**Comment by sfshaza2** [comment]
@InMatrix, do you think this is still a relevant/important issue? I've changed the priority to P3, as I think we have more important issues to address, but I welcome your feedback.

**Comment by InMatrix** [comment]
We can probably close it for now. The widget index is a workaround to not knowing the precise category of each widget. We can revisit it once we have more design resource on the team.
