### ISSUE TITLE
Explain why there are 2`title: 'Startup Name Generator'` lines in the codelab

### ISSUE THREAD

**Issue by joaowd** [flutter/website#2117]
Page URL: https://flutter.io/docs/get-started/codelab.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab.md

Description:

[In the step 4 ](https://flutter.io/docs/get-started/codelab#step-4-create-an-infinite-scrolling-listview)

At the 5th point, says to add the title: 'Startup Name Generator', but since we already add that in the RandomWordsState Widget build, there is no need to do it again.

**Comment by chalin** [comment]
Hi @joaowd, thanks for the issue. There are two titles with the same string in the app code, that is because those titles serve distinct purposes.

@sfshaza2, maybe we should add a note to that effect in the docs?
