### ISSUE TITLE
'Return data from a screen' page issue

### ISSUE THREAD

**Issue by dansunhappy** [flutter/website#2124]
Page URL: https://flutter.io/docs/cookbook/navigation/returning-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/returning-data.md

Description:Return data from a screen with a gesture ?

**Comment by sfshaza2** [comment]
@dansunhappy, are you suggesting a rename of the page? Is it so unclear?

**Comment by sfshaza2** [comment]
Closing.
