### ISSUE TITLE
Document outgoing events on platform channels page

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2129]
@xster commented on [Tue Jul 11 2017](https://github.com/flutter/flutter/issues/11146)

https://flutter.io/platform-channels is great for polling the platform but the push event receiving part with EventChannel doesn't seem documented yet. 

---

@goderbauer commented on [Fri Dec 28 2018](https://github.com/flutter/flutter/issues/11146#issuecomment-450293040)

@zoechi I think this should be moved to the website repo.

BTW, how do you move issues? Do you use an external tool?

---

@zoechi commented on [Fri Dec 28 2018](https://github.com/flutter/flutter/issues/11146#issuecomment-450311281)

@goderbauer if you're admin in the GitHub repo then GitHub provides a feature to move from one repo to another. 
I'm not, so I use ZenHub browser extension that adds a button to copy issues from one repo to another.

**Comment by atsansone** [comment]
This duplicates https://github.com/flutter/website/issues/8098. Closing.
