### ISSUE TITLE
Remove mention of git clone on 'Linux install' and 'macOS install' pages

### ISSUE THREAD

**Issue by geoffpike** [flutter/website#2131]
Page URL: https://docs.flutter.dev/get-started/install/linux
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/linux.md

Description: This text is the first occurrence of "clone" on the page:
"Add the following line and change [PATH_TO_FLUTTER_GIT_DIRECTORY] to be the path where you cloned Flutter’s git repo:".

I have not cloned anything at this point; I've downloaded and untarred a .tar.xz file.

**Comment by rubensdemelo** [comment]
same on macos page

https://flutter.dev/docs/get-started/install/macos

**Comment by atsansone** [comment]
Conflicts with https://github.com/flutter/website/issues/2529.
