### ISSUE TITLE
Simplify I18n page

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2132]
### Page URL

https://docs.flutter.dev/accessibility-and-localization/internationalization

@goderbauer commented on [Tue Feb 27 2018](https://github.com/flutter/flutter/issues/14926)

Developer feedback from Hackathon:

https://flutter.io/tutorials/internationalization/ looks scary and complicated compared to the Android flow, maybe needs a shorter summary on top? Put example of how to get a localized screen front and center? (instead of sending devs to the the sample to see usage)

---

@goderbauer commented on [Fri Dec 28 2018](https://github.com/flutter/flutter/issues/14926#issuecomment-450425680)

@zochi I think this one should go into the flutter/website repo?

**Comment by atsansone** [comment]
This duplicates https://github.com/flutter/website/issues/2280. Closing this issue.
