### ISSUE TITLE
'Building Layouts' page issue

### ISSUE THREAD

**Issue by jffiorillo** [flutter/website#2142]
Page URL: https://flutter.io/docs/development/ui/layout/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/layout/index.md

Description: The code in the sample is incomplete:

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    //...

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),

    //...
} 
```

The  `);` is missing to close `MaterialApp(....);` construction.

**Comment by chalin** [comment]
The elipses (`...`) means that there is more code there that isn't shown. I think that we should leave this as is for now. (@sfshaza2 - also because I've started working on integrating code-excerpts for this page; WDYT).

**Comment by sfshaza2** [comment]
I agree, @chalin.  Closing.

**Comment by jffiorillo** [comment]
I agree that (`...`) means more code there that isn't shown but more code not related to the expression shown as example.
Also without the `,);` the single expression shown as example isn't complete.
```
    MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
```
The idea is to add the closing <pre><b> ); </b></pre> to finish the expression as shown:

<pre><code>MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ), <b>);</b>
</code></pre>

**Comment by jffiorillo** [comment]
Great, thanks for the update @chalin . That sounds fair!

**Comment by chalin** [comment]
👍

Btw, here is a first PR for those updates: #2164 (with a link to the staging server preview).
