### ISSUE TITLE
Adding the Full ext like .html or /index.html

### ISSUE THREAD

**Issue by chenglu** [flutter/website#2148]
Hi team:

If I built the docs site and deployed to the file system service like GCS (not Firebase hosting or gh-pages, etc.), I will get a 404 page if I visit the page like 

> /docs/get-started/install/windows

since the file system service like GCS always didn't have the feature that could find the URL.html or URL/index.html and return to users, I was wondering if we could have a switch in our tools so we could add the full ext when we generate the URLs.

Thanks!

**Comment by chenglu** [comment]
Inspired by this post [Hosting a Static Website with Kubernetes and Google Cloud Storage](https://zihao.me/post/hosting-static-website-with-kubernetes-and-google-cloud-storage/), I will use a NGINX server in the front with the idea & .conf file on that post.

**Comment by chalin** [comment]
I'm glad that you found a solution.

**Comment by chenglu** [comment]
Thanks a lot, @chalin !
