### ISSUE TITLE
Are we supposed to check "Contain encryption” in the app store?

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2149]
@dark-chocolate commented on [Tue Jan 01 2019](https://github.com/flutter/flutter/issues/25935)

Does flutter app requires to use `Contain encryption` when uploading the app to the app store, sorry if this questions sounds dumb. I am new on the app store, and not sure if flutter does some `https://,` sort of work behind the scene.  

PS: Let's assume the app built is just plain hello world. 

---

@MichaelPriebe commented on [Tue Jan 01 2019](https://github.com/flutter/flutter/issues/25935#issuecomment-450747055)

I did not even know that is an option, but I have never checked it for any of my apps.

---

@dark-chocolate commented on [Wed Jan 02 2019](https://github.com/flutter/flutter/issues/25935#issuecomment-450801838)

@MichaelPriebe  When you hit `Submit for review` button then they ask you to fill this option, otherwise on the app store connect page, it is not visible. 

---

@zoechi commented on [Wed Jan 02 2019](https://github.com/flutter/flutter/issues/25935#issuecomment-450802781)

Related to https://flutter.io/docs/deployment/android

See also https://stackoverflow.com/questions/2135081/does-my-application-contain-encryption

> Using HTTPS is now exempt from the ERN as of late September, 2016]

So if you don't add a dependency for cryptography yourself you should be safe.

**Comment by zoechi** [comment]
Should the docs mention this?

**Comment by sfshaza2** [comment]
Yes, we should add this info.

**Comment by masteradit** [comment]
Hey! Any updates on this? I haven't seen anything related to this in Flutter docs.

**Comment by sfshaza2** [comment]
@cbracken, it sounds like if a developer uses a cryptography package in their app, that they should then check the "Contains encryption" box when releasing to the app store. [It sounds like including http calls is not considered encryption](https://stackoverflow.com/questions/2135081/does-my-application-contain-encryption) but, is that true? Where is the line between compliance and non-compliance?

@blasten, [from my googling](https://stackoverflow.com/questions/59002850/android-getting-rid-of-your-app-contains-unsafe-cryptographic-encryption-patte), there seems to be the same issue for the Play store. What advice should we give?

**Comment by MichaelPriebe** [comment]
If anyone is wondering I have never checked this option and have not had a problem. Doesn't seem like it does anything at all.

**Comment by atsansone** [comment]
@cbracken : Does this require a docs update or not?

**Comment by cbracken** [comment]
Personally I fall on the side of not documenting it in our own docs, but ensuring we link to Apple's [App Store Connect docs](https://developer.apple.com/help/app-store-connect/manage-app-information/overview-of-export-compliance), which have a section covering the topic. We already [do so](https://docs.flutter.dev/deployment/macos#register-your-app-on-app-store-connect) on the macOS page (and I assume iOS page too).

This is one of many possible bits of documentation that App Store Connect might require (others include tax category, privacy info, age rating, ...) so I'm not sure it warrants any special call-out on its own, just the link we already have.
