### ISSUE TITLE
Add sub-tag under the 'Resources' section for "Official brand logos"

### ISSUE THREAD

**Issue by maguinis** [flutter/website#2150]
Add sub-tag under the 'Resources' section titled "Official brand logos"

That directs users to this page with our assets: 
https://drive.google.com/drive/folders/1KXNtO9My2AMpDOF9A9Y_4aj4_BcgmDDT

This can help people gain access to the logos they should use. 

Unless there is a suggestion for a better place to place this...

**Comment by sfshaza2** [comment]
Great! We can also link from brand, perhaps. But I think it makes sense to call this out specifically.
