### ISSUE TITLE
'Flutter Module' description issue

### ISSUE THREAD

**Issue by domnulserj** [flutter/website#2151]
Page URL: https://startup.google.com/tools/build-product/

Description:

"Flutter is a mobile UI framework that provides the fastest, most expressive way to build high-quality NAIVE apps that ship to iOS and Android."

Change "naive" to "native".

![naive](https://user-images.githubusercontent.com/46329925/50611501-53ec4600-0edf-11e9-8446-762ef267886a.jpg)

**Comment by chalin** [comment]
Lol, good catch, thanks!

**Comment by chalin** [comment]
@sfshaza2, assigning to you. I'm not sure where the sources are for this.

**Comment by sfshaza2** [comment]
I have sent numerous emails to that team to fix. They responded today that it can be fixed after 1/31. (The site is frozen atm.)

**Comment by sfshaza2** [comment]
Fixed.
