### ISSUE TITLE
Can't click on annotations in docs to see what they mean.

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2153]
@alanrussian commented on [Mon Jul 02 2018](https://github.com/flutter/flutter/issues/19001)

Example: https://docs.flutter.io/flutter/widgets/NavigatorState/push.html

```
@optionalTypeArgs
Future<T> push <T extends Object>(
    Route<T> route
)
```

`optionalTypeArgs` is a symbol, but it's not possible to tap on it to find out what it means. I can search for it though: https://docs.flutter.io/flutter/meta/optionalTypeArgs-constant.html

---

@zoechi commented on [Mon Aug 27 2018](https://github.com/flutter/flutter/issues/19001#issuecomment-416162937)

Should this be moved to https://github.com/dart-lang/dartdoc ?

---

@goderbauer commented on [Wed Jan 02 2019](https://github.com/flutter/flutter/issues/19001#issuecomment-450970338)

@zoechi Yes, can you move it? Thanks.

**Comment by sfshaza2** [comment]
Yes, this bug shouldn't be filed against the flutter.io repo.

**Comment by sfshaza2** [comment]
Moved to:  https://github.com/dart-lang/dartdoc/issues/1912

Closing.
