### ISSUE TITLE
What's the default unit of measurement in flutter?

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2156]
@vanshu commented on [Fri Dec 28 2018](https://github.com/flutter/flutter/issues/25833)

## Steps to Reproduce

I am using AppBar class to set App bar of the page, there is an attribute called [elevation](https://docs.flutter.io/flutter/material/AppBar-class.html)
```The z-coordinate at which to place this app bar. This controls the size of the shadow below the app bar.```
The document hasn't figured out what's the default unit measurement of elevation, in Android We use dp,px
so how about flutter?

---

@timsneath commented on [Wed Jan 02 2019](https://github.com/flutter/flutter/issues/25833#issuecomment-450793220)

Hi @vanshu, it is measured in pixels, as described here: https://docs.flutter.io/flutter/material/Material-class.html. We could clarify this in the docs. 

---

@xster commented on [Thu Jan 03 2019](https://github.com/flutter/flutter/issues/25833#issuecomment-451027713)

I think this should add an FAQ entry for this. We're fairly web-y in our terminology which tends to mainly focus on logical pixels but Android and iOS developers tend to be very specific about whether they meant logical pixels (points, dp/sp) or physical pixels (px, pixels). Us using just 'pixels' when we meant logical pixels is doubly confusing since 'pixels' typically mean physical pixels on Android and iOS.

**Comment by sfshaza2** [comment]
Good idea.

**Comment by koalaylj** [comment]
I think that pixel is logic pixel (referred to as dp)
[devicePixelRatio](https://api.flutter.dev/flutter/dart-ui/Window/devicePixelRatio.html)

```
The number of device pixels for each logical pixel. This number might not be a power of two. Indeed, it might not even be an integer. For example, the Nexus 6 has a device pixel ratio of 3.5.

Device pixels are also referred to as physical pixels. Logical pixels are also referred to as device-independent or resolution-independent pixels.

By definition, there are roughly 38 logical pixels per centimeter, or about 96 logical pixels per inch, of the physical display. The value returned by devicePixelRatio is ultimately obtained either from the hardware itself, the device drivers, or a hard-coded value stored in the operating system or firmware, and may be inaccurate, sometimes by a significant margin.

The Flutter framework operates in logical pixels, so it is rarely necessary to directly deal with this property.

When this changes, onMetricsChanged is called.
```
