### ISSUE TITLE
'MacOS install' page issue

### ISSUE THREAD

**Issue by mattlaver** [flutter/website#2157]
Page URL: https://docs.flutter.dev/get-started/install/macos
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Description:

This line failed with permission issues for me:

```brew install --HEAD usbmuxd```

The error was:

```Error: The following directories are not writable by your user: /usr/local/include```

It may be worth putting a note to rectify to make it easier to onboard - I used this:

```sudo chown -R $(whoami) $(brew --prefix)/*```

**Comment by sfshaza2** [comment]
Good suggestion. I get that, too.

**Comment by atsansone** [comment]
A solution can be found on [TutsPlanet](https://www.tutsplanet.com/snippets/nodejs-brew-link-node-command-gives-usr-local-include-node-is-not-writable-error-in-mac-os/). However, brew installation is not offered or supported for Flutter. Closing this issue.
