### ISSUE TITLE
'Using custom fonts' page issue

### ISSUE THREAD

**Issue by VLEIX** [flutter/website#2160]
Page URL: https://flutter.io/docs/cookbook/design/fonts.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/fonts.md

Description:
https://flutter.io/docs/cookbook/design/fonts#pubspecyaml-option-definitions
- "specfies" poorly written.

**Comment by VLEIX** [comment]
PR created https://github.com/flutter/website/pull/2401

**Comment by brianegan** [comment]
Fixed!
