### ISSUE TITLE
'Navigate to a new screen and back' page issue

### ISSUE THREAD

**Issue by Daniel-BD** [flutter/website#2169]
Page URL: https://flutter.io/docs/cookbook/navigation/navigation-basics.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/navigation-basics.md

Description: The GIF in the bottom of the page displays a listview for a split second after navigating back from the second screen to the first. It also looks very laggy. The GIF should be updated.

**Comment by sfshaza2** [comment]
@brianegan
