### ISSUE TITLE
'Building Layouts' page issue

### ISSUE THREAD

**Issue by feinstein** [flutter/website#2172]
Page URL: https://flutter.io/docs/development/ui/layout/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/layout/index.md

Description:

The text on step 3:

>Since the code for building each row is almost identical,

Should be:

>Since the code for building each column is almost identical

Also:

>calling the function and passing the Icon and text specific to that column

Should be:

>calling the function and passing the Icon, color and text specific to that column

Since the function created takes 3 arguments

**Comment by sfshaza2** [comment]
Did you address this in your recent PR, @chalin?

**Comment by chalin** [comment]
No, but it is now fixed by #2305.
