### ISSUE TITLE
Archive page no longer defaults to your platform

### ISSUE THREAD

**Issue by DanTup** [flutter/website#2173]
The archive page (https://flutter.io/docs/development/tools/sdk/archive) used to default to your OS ([based on user agent sniffing](https://github.com/flutter/website/blob/2f8781a59dd87b8bfc10dc132256d53f439cd478/js/tabs.js#L61)) before the update but it doesn't seem to anymore. It does persist your selected tab but if I clear all site data and hit the URL above from Chrome macOS it always seems to show the Windows section.

**Comment by chalin** [comment]
(There might be another issue related to this, but I don't have time to look it up now. I'll check later.)

**Comment by DanTup** [comment]
I did spot #1886 but it didn't seem to mention this. Feel free to roll it in there if it makes sense though.

**Comment by chalin** [comment]
(It might have been only in my local to-do list. Thanks for the reference to #1886.)
