### ISSUE TITLE
debugging.md: Add a discussion of tracing to the debugging docs

### ISSUE THREAD

**Issue by Hixie** [flutter/website#2181]
how to start/stop a trace, how to view and interpret the trace, how to add things to the trace

**Comment by rubensdemelo** [comment]
What about this article by @chinmaygarde  https://medium.com/flutter-io/profiling-flutter-applications-using-the-timeline-a1a434964af3 ? Would be good to reference in debugging page ?

**Comment by atsansone** [comment]
@chinmaygarde : Does your blog post cover what we should add or not?

**Comment by atsansone** [comment]
@Hixie : Considering the age of this issue, I would hope that [this change](https://docs.flutter.dev/testing/debugging#tracing-dart-code) covers your needs. Please advise.

**Comment by Hixie** [comment]
sounds good!
