### ISSUE TITLE
'Making authenticated requests' page issue (authenticated http requests)

### ISSUE THREAD

**Issue by hatemelmougy** [flutter/website#2186]
Page URL: https://flutter.io/docs/cookbook/networking/authenticated-requests.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/authenticated-requests.md

Description:
Hello Flutter team, 
I have been trying to make an authenticated http request but it needs a dart:_http import and when I use that I get this error "Compiler message:
lib/challenges.dart:1:8: Error: Can't access platform private library.
import 'dart:_http';"
or it might just be me i don't know.

**Comment by brianegan** [comment]
Oh dang, sorry I missed this one :/ Looks like I need to update this recipe. 

Flutter used to ship the `http` library, but it no longer does so. To fix the problem, please add the `http` dependency to your `pubspec.yaml` and then import the `http` client using the following line:

```
import 'package:http/http.dart' as http;
```

**Comment by brianegan** [comment]
Fixed as part of another set of changes, but commit message bug didn't close this out!
