### ISSUE TITLE
'MacOS install' page issue - update path

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#2196]
Page URL: https://flutter.io/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Description:
It is awesome that you are doing such specific docs so people will not get stuck and easier onboarding for people of different backgrounds. thanks!  however.
Typo in line for .bash_profile
```
 export PATH=$PATH:[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin
```
should be
```
 export PATH=$PATH:[PATH_TO_FLUTTER_GIT_DIRECTORY]/bin
```
e.g. if user has downloaded flutter into ~/flutter, then [PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin would be ~/flutter/flutter/bin, which would be incorrect.

Thank you.

**Comment by kangwang1988** [comment]
@neiljaywarner 
Thanks for your contribution.
I would recommend you to file a PR to edit this page.

**Comment by neiljaywarner** [comment]
https://github.com/flutter/website/pull/2212

**Comment by kangwang1988** [comment]
As this issue will be tracked at: https://github.com/flutter/website/pull/2212
Closing issue: #2196 now.
