### ISSUE TITLE
'Flutter SDK archive' page issue

### ISSUE THREAD

**Issue by JieJiejjjjjjjj** [flutter/website#2200]
Page URL: https://flutter.io/docs/development/tools/sdk/archive.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/archive.md

Description:

**Comment by chalin** [comment]
Thanks for filing an issue, but I’m going to close it for lack of a description. If you add a comment with details, we’ll reopen the issue.
