### ISSUE TITLE
Split the "Building Layouts" into multiple pages

### ISSUE THREAD

**Issue by chalin** [flutter/website#2202]
The [Building Layouts](https://flutter.io/docs/development/ui/layout) is awfully long. I think that we should split it up into multiple pages, one page per top-level of the TOC (except maybe for Resources, that could be merged into another page?):

<img width="415" alt="screen shot 2019-01-11 at 18 04 54" src="https://user-images.githubusercontent.com/4140793/51063989-6cd5b500-15cb-11e9-9097-be84f5a1eb70.png">

The pages could all go under the (new) "Building Layouts" group in the sidenav.

WDYT @sfshaza2?

**Comment by sfshaza2** [comment]
Yeah, that's how I first created it. I was ordered to put it together in a single page. Searching is easier if it's one page. I'd ask the UX folk, which we didn't have back when I wrote it.  @galeyang?  @InMatrix? Please weigh in.

**Comment by InMatrix** [comment]
I'm not concerned about the length of the page, since the table of contents on the right hand side helps users navigate the doc. However, if it takes too long to load the whole doc at once (not from my computer), we should consider breaking it up.

**Comment by sfshaza2** [comment]
As I said, engineering had very strong feelings about keeping it together
in one page. Easier to search.

**Comment by chalin** [comment]
Long pages are a bit of a pain to deal with on mobile, but that isn't our core audience (most devs consult the docs from desktop). Ok, thanks for the feedback, I'll close this for now.

**Comment by galeyang** [comment]
I think about this earlier but don't feel strong enough to file a change yet. Here are more thoughts on this.

**Feedback about the length of the page and ToC:**
I do get some feedback suggesting that this page is very long and could be break down better (maybe splitting the tutorial and common layout intro? not sure about it). 

From a study with new users, we observed a few participants were not able to immediately find the those common layout widgets (e.g. Card) that were displayed at the very end of the page. Some ToC are below the fold (e.g. in the below screenshot, you cannot see "Card" in the TOC). Therefore, users might not know what exists in this page at the first glance and decide to leave the page. 
![image](https://user-images.githubusercontent.com/5102864/51130707-7e44da00-17e2-11e9-92db-fa867fb14d0c.png)

**Feedback about in-page search:**
Yes, in-page search was frequently used by participants in the study! Hence, if we really want to split this page, we need to ensure that proper keywords and cross-reference links are available.

**Comment by chalin** [comment]
At least splitting it in two would make sense.

**Comment by sfshaza2** [comment]
OK, we have the blessing of two of our UX researchers and the main detractor has gone to another team.

Let's do it!  (Meaning, if you want to do it, Patrice, go right ahead.  :) )
