### ISSUE TITLE
cached_network_image library should not be referenced as the way to work with cached images.

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2206]
@lifenautjoe commented on [Sat Jan 12 2019](https://github.com/flutter/flutter/issues/26463)

The library [flutter_cached_network_image](https://github.com/renefloor/flutter_cached_network_image) employed in [the website tutorial on cached network images](https://flutter.io/docs/cookbook/images/cached-images) is semi-abandoned with [tons of bugs & missing features](https://github.com/renefloor/flutter_cached_network_image/issues?page=2&q=is%3Aissue+is%3Aopen) to work out.

Using it as part of the official flutter documentation is leading users straight into frustration and disappointment over Flutter.

Please explore alternative and reliable ways to showcase this behaviour or sponsoring the development of this much valued library.

**Comment by sfshaza2** [comment]
Do we have a better solution for this, @Hixie!

**Comment by zoechi** [comment]
I only know of https://docs.flutter.io/flutter/widgets/precacheImage.html

See also https://github.com/flutter/flutter/issues/16592, https://github.com/flutter/flutter/issues/27227

**Comment by lifenautjoe** [comment]
Hi everyone, I've found this library https://pub.dartlang.org/packages/flutter_advanced_networkimage which does a much better job and the maintainer @mchome is actively developing it regardless of his Github status.

**Comment by sfshaza2** [comment]
@brianegan, can you address this? It's referencing the cached images page in the cookbook.

**Comment by brianegan** [comment]
Ack, sorry I missed this one :/

My initial thoughts: it might be time to remove the recipe until a proper solution is in place. Sounds like there is a newer version that solves a lot of the problems from the original library, but I feel like it might make sense to give that library some time to mature and stabilize before resurrecting this recipe.

**Comment by sfshaza2** [comment]
@khanhnwin, can you review this issue? I looked, and cached_network_image still has quite a few open bugs. However, just one year ago, you made a video promoting this package and it has *many* likes on pub.dev. I would normally take that to mean that it's a good solution. But, in 2019, @brianegan felt that maybe we should pull this recipe.

Opinions?

**Comment by atsansone** [comment]
This has been replaced with `[cached_network_image]()https://pub.dev/packages/cached_network_image)` in 2019. Closing this issue.

**Comment by atsansone** [comment]
This has been replaced with `[cached_network_image]()https://pub.dev/packages/cached_network_image)` in 2019. Closing this issue.
