### ISSUE TITLE
'Hot reload' page issue - example says 2.7seconds; should say under 1 second.

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#2207]
Page URL: https://flutter.io/docs/development/tools/hot-reload.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/hot-reload.md

Description:
it says "Reloaded 1 of 448 libraries in 2,777ms." in this page as an example situation.

I see this article where 3 seconds or so was the max he could get it to even with stress test, and 700ms-1000ms seems normal.'
https://medium.com/flutter-io/that-flutters-reload-is-so-hot-right-now-371b3ad0fc94
Since flutter.io main page says "sub-second reload times" i propose you use an example for this closer to 700ms or 900ms.

thank you.

**Comment by mjohnsullivan** [comment]
Updated to reflect what I normally get on my dev laptop

**Comment by mjohnsullivan** [comment]
PR fix: https://github.com/flutter/website/pull/2329
