### ISSUE TITLE
Make 'Adding Interactivity to Your Flutter App' page responsive

### ISSUE THREAD

**Issue by feinstein** [flutter/website#2213]
Page URL: https://docs.flutter.dev/ui/interactive
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/interactive/index.md

Description:

Make this page mobile friendly

**Comment by chalin** [comment]
Related to #1951

**Comment by atsansone** [comment]
This page renders responsively. If there is something more specific that you feel needs attention, please [file a new issue](https://github.com/flutter/website/issues/new?assignees=&labels=&projects=&template=1_page_issue.yml) with additional information. Thanks!

![image](https://github.com/flutter/website/assets/706219/e7f36495-91be-461c-b845-72f49dc840a5)
