### ISSUE TITLE
Document how to get slow SkPictures and use the Skia debugger to figure them out

### ISSUE THREAD

**Issue by Hixie** [flutter/website#2214]
We should add instructions for how to do this to https://docs.flutter.dev/testing/debugging

cc @chinmaygarde

**Comment by atsansone** [comment]
@Hixie : Is this still a going concern? I don't see any update in the page at this time. Is this something we can document easily? Could we just note that if the `SkPictures` have a performance issue, that they should look to https://skia.org/docs/dev/tools/debugger/?

**Comment by Hixie** [comment]
Well, with the move to Impeller we probably need entirely different documentation. I'm not sure how you debug a slow frame with Impeller. But we still need to say how to do it.

**Comment by chinmaygarde** [comment]
Post the iOS stable, we were discussing the prioritization of capturing frame sequences using archivist with Impeller. We have used the SKP traces to send bug reports to Skia in the absence of a reduced test case in the form of code. I suspect the initial run of the Impeller trace captures will be similar.

**Comment by atsansone** [comment]
@chinmaygarde : Could you open a new issue to document debugging Impeller when you're ready? Thanks!

**Comment by atsansone** [comment]
Impeller requires a different page. Closing this issue.
