### ISSUE TITLE
APK Expansion file usage

### ISSUE THREAD

**Issue by leifcr** [flutter/website#2215]
Please provide info on using APK expansion files in flutter.

**Comment by AnNEDoMini** [comment]
Any update here? Some guidelines for both platforms

**Comment by sfshaza2** [comment]
@leifcr, I've asked the relevant engineers, who aren't sure. We welcome input from those who know.

**Comment by leifcr** [comment]
@sfshaza2  Really blank here, as I tried hacking it together, but ended up downloading resources outside of play store (not ideal), but solved the problem until there is an official way to do this in flutter.

**Comment by pascalfriedrich** [comment]
Any updates on this?

**Comment by sfshaza2** [comment]
@tvolkert, who might be able to shed light on this?

**Comment by tvolkert** [comment]
Users should just use app bundles these days.

**Comment by pascalfriedrich** [comment]
@tvolkert 
And what if even the app bundle is larger then 150mb? In my case, the app has a huge amount of assets/soundfiles and there is no way to stay below 150mb.

**Comment by tvolkert** [comment]
@blasten do you know the guidance here?

**Comment by blasten** [comment]
It sounds like to properly support this feature, we would need to provide control over what goes in the APK/AAB file and what goes in the obb files. Then, a mechanism for unzipping and consuming these files in the embedding.

**Comment by blasten** [comment]
@pascalfriedrich are you able to lazily load the sound files and other heavy assets over the network from your Flutter app?

**Comment by Sun3** [comment]
What is the status of this issue? I also have have an app that the app bundle is greater than 150 MB because of proprietary assets and the option to download from internet is not an option.

How would you submit the app to Google Play since it does not allow the files size more than 150 MB? 

Thanks.

**Comment by pascalfriedrich** [comment]
@blasten Sure, but the owner does not have a server where the data can be loaded. We are talking about 1000 users with 250mb assets (soundfiles) each. I will see what I can do. Sooner or later the way over the expansionfiles would be the better one.

**Comment by WallyHale** [comment]
I'm surprised it's so quiet in here .. we are moving all our apps to Flutter, however a few of them are quite large with assets (AR, audio and image bundles), but at the moment it doesn't seem we have the OBB / Expansion file option that we do with native Android? It seems like quite an oversight for Flutter, if we are restricted to the very low modern standard upload limits of 100Mb for APK and 150Mb for app bundle!

**Comment by ollydixon** [comment]
I have this issue too except my app is over 150mb with just essential libraries. Nice one Google; why can’t they just take the Apple route and allow us to upload large Apps, not like they are poor. 150mb in 2020 is ridiculous.

On a side note, why is this closed? There was no solution.

**Comment by WallyHale** [comment]
> I have this issue too except my app is over 150mb with just essential libraries, not including assets. Nice one Google; why can’t they just take the Apple route and allow us to upload large Apps, not like they are poor. 150mb in 2020 is ridiculous.
> 
> On a side note, why is this closed? There was no solution.

It's not closed, the thread that mentioned this one (and is therefore visibly linked) is closed.

I agree, in this day and age, 150mb is nothing! APK size is only 100 mind you! I'm not holding my breath on them increasing it, it's unusual that Apple is ahead of the curve, and I can only hope that we get expansion file support, as it will be a more long term solution.

I'm flabbergasted that it isn't already included or being prioritised and shouted about!

**Comment by ollydixon** [comment]
> > I have this issue too except my app is over 150mb with just essential libraries, not including assets. Nice one Google; why can’t they just take the Apple route and allow us to upload large Apps, not like they are poor. 150mb in 2020 is ridiculous.
> > On a side note, why is this closed? There was no solution.
> 
> It's not closed, the thread that mentioned this one (and is therefore visibly linked) is closed.
> 
> I agree, in this day and age, 150mb is nothing! APK size is only 100 mind you! I'm not holding my breath on them increasing it, it's unusual that Apple is ahead of the curve, and I can only hope that we get expansion file support, as it will be a more long term solution.
> 
> I'm flabbergasted that it isn't already included or being prioritised and shouted about!

Yes, well i feel Apple is always ahead of the curve. We spend so much more time faffing around with Android dev than anything else 😎 I mean subscriptions is 27 steps to get a token, Apple is 3.

If are both are closed with no solutions should I make a new ticket?

**Comment by sfshaza2** [comment]
After escalating to engineering, I've opened a new issue in the flutter/flutter repo, https://github.com/flutter/flutter/issues/51522. Please upvote that issue if this is important to you.

**Comment by xster** [comment]
I'm commenting here so the thread can get notification but please respond and follow along on https://github.com/flutter/flutter/issues/51522. 

To help us understand this challenge a bit more, can people share a bit more context on the circumstances involved in running into this issue?

Anonymized screenshots of the APK analyzer breakdown in Android Studio is the most useful. Otherwise, it would be very helpful to get the breakdown of 

- Total size of assets per DPI breakdown
- Whether you're shipping APKs or app bundles
- How much of the size are from dex files
- Sizes of the native libraries in the app and the ABIs breakdown
- Whether you had an existing Android app that's already using the PlayCore API and dynamic feature modules
