### ISSUE TITLE
FAQ: "Can I build a framework/library with Flutter?"

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/website#2222]
We have a few different flavors of this question floating around.

1. Can I build a product framework with Flutter.  e.g. https://twitter.com/sekhar_das/status/1085430161770635266 . The answer is likely "not recommended" due to Flutter's 4mb runtime overhead.  It's unlikely that a product would want to bundle the Flutter engine with their framework (although such *should be* possible).  Another downside is that with this method if you embedded multiple products written this way you might end up with multiple copies of the Flutter runtime.  A technical equivalency to draw would be to ask the question if it made sense to build a product library and include a copy of WebKit with it, or Unity.

An alternative answer is to build a Flutter package.  But that then requires anyone consuming said package to already have Flutter embedded in their app.  This again follows the WebKit/Unity model of you'd build something for the web or for unity and depend on the consumer of such to bring their own copy of WebKit or Unity.

2. Another flavor of this question comes up in the context of add2app.  i.e. How can I make it so that in my large development team, most contributors don't know that part of it is written in Flutter?  Can I just bundle the Flutter parts via a library of some form?  https://github.com/flutter/flutter/issues/25979 covers this.

Unclear what docs we should write on this now that I've written this up.  The first question might warrant an FAQ entry, but we'd need to work on the language some.

**Comment by sfshaza2** [comment]
I rated this e2 mostly because the required docs aren't clear.

**Comment by atsansone** [comment]
This appears to be a dead issue without comment for four years. Closing this issue.
