### ISSUE TITLE
'Animations overview': Ticker section needs rewrites

### ISSUE THREAD

**Issue by feinstein** [flutter/website#2228]
Page URL: https://flutter.io/docs/development/ui/animations/overview.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/animations/overview.md

Description:

The Ticker section should be rewriten, it's complicated to read, confusing and there are some grammar mistakes, for example, in some places there's an `at` missing.

**Comment by sfshaza2** [comment]
I think he means the "Ticker" section.  :)

**Comment by feinstein** [comment]
🙈
