### ISSUE TITLE
'MacOS install' page issue

### ISSUE THREAD

**Issue by gitrid** [flutter/website#2229]
Page URL: https://flutter.io/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Description: Example in point number 3 in the section "Update your path" should be updated doesn't include required quotation marks in the example. 

So instead of:
export PATH=$PATH:[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin

it should be:
export PATH=$PATH:"[PATH_TO_FLUTTER_GIT_DIRECTORY]"/flutter/bin

For example:
export PATH=$PATH:"/Users/danielsworkmac/flutter/bin"

**Comment by kangwang1988** [comment]
File a pr to flutter/website.
@gitrid

**Comment by chalin** [comment]
The quotes aren't necessary, unless you have an unescaped space in your `PATH_TO_FLUTTER_GIT_DIRECTORY`, but it is certainly more inclusive of edge cases like those to add quotes around the entire expression. I'll tackle it, thanks.
