### ISSUE TITLE
Revise 'Animations overview' page for screenshot, typos, other small changes

### ISSUE THREAD

**Issue by feinstein** [flutter/website#2237]
Page URL: https://docs.flutter.dev/ui/animations/overview
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/animations/overview.md

Description:

>The AnimationController is stateful Animation<double> that uses a Ticker to give itself life

There's a `a` missing

**Comment by feinstein** [comment]
Actually that whole section should be revised.

**Comment by chalin** [comment]
Missing "a" added via #2282.

**Comment by chalin** [comment]
@feinstein - any broad comments in terms of what you think needs to be addressed?

**Comment by feinstein** [comment]
There's an `At` missing in:

>Each tick, it takes the time elapsed since it was started and passes it to a Simulation to obtain a value.

**Comment by feinstein** [comment]
I also think there should be a mention to `vsync` since it's an important part.

On the other tutorials there are references to `vsync` but nowhere there's an explanation of how it works with the mixins we are supposed to add.

At least the mixins docs do explain how they work, but it would be nice to see it on the tutorials as well.

I also think the animations overview could use an image that explains how the whole animations architecture work, showing the ticks getting into a controller, being modified by a tween and a curve and etc... This could be made very visual and simply the whole learning curve

**Comment by sfshaza2** [comment]
I've fixed the grammatical errors, but the section should still be expanded with info on vsync.

**Comment by feinstein** [comment]
Would you like that I create a separate issue about `vsync` or will you rather reopen this one?

**Comment by sfshaza2** [comment]
I can go either way. I guess I didn't realize it had closed.

**Comment by feinstein** [comment]
I thought so, could you reopen this one then? Its a bit easier I guess and there's history already.

**Comment by viralkachhadiya** [comment]
Can you give me some details for this issue??
So I can help to solve it

**Comment by viralkachhadiya** [comment]
@sfshaza2

**Comment by atsansone** [comment]
Moved vsync content to new issue: #8927. Closing this issue.
