### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by LyalinDotCom** [flutter/website#2240]
Page URL: https://flutter.io/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description: When unzipping flutter_windows_v...zip on Windows it is not clear in the instructions that you need to ensure the hidden folders/files (as-in .git folder) needs to be extracted from the zip to avoid the "The Flutter Directory Is Not A Clone of GitHub Project" error message you otherwise get later when trying to run command-line.

Maybe add a note about this in that instruction section? thanks!

**Comment by chalin** [comment]
Hi. I wasn't aware that you could unzip a package without getting hidden files. Are you sure that it isn't because you copied the folder?

**Comment by chalin** [comment]
I'm going to assume it was a file/folder copy issue. If it was not, feel free to add a comment here with more information and we'll reopen the issue.
