### ISSUE TITLE
'Windows install': add example of Path change

### ISSUE THREAD

**Issue by jotisa** [flutter/website#2241]
Page URL: https://flutter.io/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description:
It reads in the webpage:
"If the entry does exist, append the full path to flutter\bin using ; as a separator from existing values."
While this is acceptable in other OS's and some might make a sense of it for introductory purposes it should read:
If the entry does exist, append the full path to flutter\bin using ; as a separator from existing values.  As in this example:
;C:\src\flutter\bin;

Thanks in advance,
Jonatan Tisnado

**Comment by chalin** [comment]
I find the existing text clear enough. @sfshaza2 - any opinion about this?

**Comment by sfshaza2** [comment]
As a multi-decade Unix user, I don't have strong opinions on this, though including examples is never a bad idea.  :)

**Comment by chalin** [comment]
I'm trying to find a balance. We don't add examples for all of the steps, and the prose seems quite straightforward in this case.

**Comment by timsneath** [comment]
This has actually changed in recent Windows 10 releases; there is now a dialog box for adding multiple values to the PATH environment variable. 
![image](https://user-images.githubusercontent.com/2319867/78952817-a5449700-7a8b-11ea-8f84-0202c73bebfb.png)

If we were to make a change, I'd argue that we should if anything be less prescriptive on the steps here. It would be better for a user to Google for help on this topic than for us to try and keep up with these UI changes. I'm going to close this issue for now.
