### ISSUE TITLE
Use a more real-world JSON structure for tutorial

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2260]
@troyibm commented on [Thu Apr 12 2018](https://github.com/flutter/flutter/issues/16533)

From URL: https://docs.flutter.dev/data-and-backend/json

1% of JSON is just a flat `key:value` structure, most have objects within the JSON.  While the example is easily understood, it could be more useful if the JSON structure you use for the example has a more structure to it.

Please revamp the tutorial to have JSON structure like
```json
{
  "name": "John Smith",
  "email": "john@example.com",
  "address": {
     "city": "Austin",
     "state": "Texas",
     "street": "106 Burnet Road"
   }
}
```

Also providing dart classes for standard JSON structures would help, but these could be available as I haven't looked around at all.

---

@toteto commented on [Mon Apr 16 2018](https://github.com/flutter/flutter/issues/16533#issuecomment-381711243)

The sample you provided is also fairly simple, it will require just:
```
final address = Address.fromJson(jsonMap["address"]);
return new Person(name, email, address);
```
In addition to this, i would like to see in the example added:
1. List of complex objects. Maybe one `Person` can have multiple `Address` properties.
2. Property that can be mapped to `enum`. Maybe employment status.

**Comment by sfshaza2** [comment]
Seems reasonable to at least include a more complex example.

**Comment by atsansone** [comment]
This was added to the [guide](https://docs.flutter.dev/data-and-backend/json#generating-code-for-nested-classes) with https://github.com/flutter/website/pull/2875. Closing this issue.
