### ISSUE TITLE
Networking page should include an example of a test

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2263]
@jonahwilliams commented on [Wed Apr 04 2018](https://github.com/flutter/flutter/issues/16233)
https://docs.flutter.dev/cookbook/networking/fetch-data includes an example of how to make an `HttpClientRequest` using the `dart:io` package, but doesn't include any example of a test using `HttpOverrides`.  We have some mocks inside of the flutter repo which are really the only examples.

---

@jonahwilliams commented on [Wed Apr 04 2018](https://github.com/flutter/flutter/issues/16233#issuecomment-378714755)

We should consider either shipping code in flutter_test to help with this, or creating another package for testing.

---

@adchang commented on [Thu Apr 05 2018](https://github.com/flutter/flutter/issues/16233#issuecomment-378824729)

An app in the sdk's examples would be super useful as well!

---

@Sfshaza commented on [Wed Jul 11 2018](https://github.com/flutter/flutter/issues/16233#issuecomment-404057467)

@brianegan, would this be a good candidate for the cookbook?

---

@brianegan commented on [Thu Jul 12 2018](https://github.com/flutter/flutter/issues/16233#issuecomment-404497912)

Ah, that's actually another great candidate for the Cookbook, especially when testing Widgets that display Images. 

We've actually got a recipe on how to test this functionality using Mockito + `http` package now, but for Image Widgets overriding the HttpClient can be a great way to avoid making full-on network calls in tests.

---

@zoechi commented on [Fri Jul 20 2018](https://github.com/flutter/flutter/issues/16233#issuecomment-406502772)

Dup of #13792 ?

**Comment by zoechi** [comment]
> Dup of #13792 ?


Might be a dup of #1846

**Comment by atsansone** [comment]
The test is documented on https://docs.flutter.dev/cookbook/testing/unit/mocking via a link on https://docs.flutter.dev/cookbook/networking/fetch-data#testing. Closing this issue.
