### ISSUE TITLE
'Flutter widget index' page issue

### ISSUE THREAD

**Issue by JoakimLiu** [flutter/website#2270]
Page URL: https://flutter.io/docs/reference/widgets.html
Page source: https://github.com/flutter/website/tree/master/src/docs/reference/widgets.md

Description:
Some images are not displayed in Page URL, like: AbsorbPointer etc.

**Comment by chalin** [comment]
Hi, thanks for filing an issue. What do you mean by "images are not displayed"? If by this you mean that the Flutter logo is displayed instead, then that is expected. Not all entries have their own images. If that isn't what you meant, could you include a screenshot? Thanks.

**Comment by chalin** [comment]
I'm going to close this issue for now, but we'll reopen it once you provide more information. Thanks.
