### ISSUE TITLE
docs.flutter.io mobile issue 

### ISSUE THREAD

**Issue by feinstein** [flutter/website#2274]
Page URL: https://docs.flutter.io/flutter/widgets/LocalizationsDelegate-class.html

Description:

The docs are not rendering perfectly on a mobile device. 

I am not sure if this is the right repo to report it actually

**Comment by chalin** [comment]
Here's a screenshot:
<img width="503" alt="screen shot 2019-01-25 at 10 57 54" src="https://user-images.githubusercontent.com/4140793/51756971-3b132280-2090-11e9-983d-d9fd840acab0.png">
@jcollins-g @filiph @Hixie /cc @sfshaza2 @kwalrath

**Comment by jcollins-g** [comment]
Have you tried https://master-docs-flutter-io.firebaseapp.com/ ?   I fixed several critical mobile-blocking bugs since the last stable release.

**Comment by jcollins-g** [comment]
dartdoc omnibus mobile fix PR: https://github.com/dart-lang/dartdoc/pull/1873
Push to Flutter:  https://github.com/flutter/flutter/pull/26041

**Comment by feinstein** [comment]
https://master-docs-flutter-io.firebaseapp.com/ has the same error

**Comment by jcollins-g** [comment]
I was able to reproduce this in simulator and with a real device.

This seems to be some artifact of how dartdoc is doing scrolling.  If you attempt to swipe the entire page to the left in a particular way, the doc page can get stuck there.  Worse, the stickiness seems to be persistent and reloads of the page don't seem to help.

A workaround is to manually swipe the page back to the right, but that only works on https://master-docs-flutter-io.firebaseapp.com/.  docs.flutter.io is stuck for good when this happens.

**Comment by jcollins-g** [comment]
This issue was moved to dart-lang/dartdoc#1911
