### ISSUE TITLE
CupertinoSliverRefreshControl should be in the cupertino catalog

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2290]
@xster commented on [Sat Jan 26 2019](https://github.com/flutter/flutter/issues/27117)

**Comment by sfshaza2** [comment]
Related to:  https://github.com/flutter/website/issues/2292

If we autogenerated the catalog, it wouldn't fall out of date.

**Comment by sfshaza2** [comment]
I'm closing this issue but added this widget to the umbrella issue: https://github.com/flutter/website/issues/8739
