### ISSUE TITLE
'Fetch data from the internet' page issue

### ISSUE THREAD

**Issue by gautamsawala** [flutter/website#2291]
Page URL: https://flutter.io/docs/cookbook/networking/fetch-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/fetch-data.md

Description:
There is a problem with the FutureBuilder call. The `future: post` call in below code is not working. It should be `future: fetchPost()`. 

```
body: Center(
           child: FutureBuilder<Post>(
            future: post,
            builder: (context, snapshot) {
              if (snapshot.hasData) {
                return Text(snapshot.data.title);
              } else if (snapshot.hasError) {
                return Text("${snapshot.error}");
              }

              // By default, show a loading spinner
              return CircularProgressIndicator();
            },
```

**Comment by kangwang1988** [comment]
It works fine in my side.
I checked the code and don't think this issue is valid.

@gautamsawala 
Feel free to comment if you think this is an issue.
