### ISSUE TITLE
Cookbook should have example about passing arguments to named route

### ISSUE THREAD

**Issue by goderbauer** [flutter/website#2296]
Once https://github.com/flutter/flutter/pull/27058 lands, we should have an example in https://flutter.io/docs/cookbook#navigation for pushing arguments to a named route.

It should show:
* pushing a route with arguments (https://github.com/flutter/flutter/pull/27058/files#diff-b4db74ec348d48e72da369c2bc858c7bR266)
* retrieving arguments from route settings in `MaterialApp`'s onGenerateRoute (https://github.com/flutter/flutter/pull/27058/files#diff-3dce29bc9fe4645a415193a989325ce9R88)
* retrieving them via `ModalRoute.of(context).settings.arguments` from within a route.

/cc @brianegan

**Comment by sfshaza2** [comment]
Thanks for the heads up, @goderbauer!

**Comment by brianegan** [comment]
Definitely, thanks @goderbauer :)

**Comment by yanir-edri** [comment]
RouteSettings has no variable arguments
![error](https://user-images.githubusercontent.com/26008614/54866014-918e9b80-4d77-11e9-85d7-239776d0d469.png)

**Comment by goderbauer** [comment]
@yanir-edri you may beed to upgrade your flutter version to see this.
