### ISSUE TITLE
Instructions for debugging Android engine with breakpoints

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2298]
@xster commented on [Mon Jul 23 2018](https://github.com/flutter/flutter/issues/19689)

Standard debugging approaches with Xcode and breakpoint work ok for debugging iOS engine. Describe how it can be done in Android Studio with breakpoints for Android engine. 

@jason-simmons pointed out some instructions with GDB for now https://github.com/flutter/engine/blob/6bc4e7e9e452b2ca299e699e6bef64c0dada1e5e/sky/tools/flutter_gdb

---

@kangwang1988 commented on [Sun Jul 29 2018](https://github.com/flutter/flutter/issues/19689#issuecomment-408648171)

@xster
Now, I am able to debug the engine product in android(libflutter.so) using flutter_gdb.
Thanks.

**Comment by sfshaza2** [comment]
@bkonyi, you're an engine kind of guy :D, how does one debug the Flutter engine? I can't find "flutter_gdb", at least not in the standard Flutter tools.

**Comment by bkonyi** [comment]
I debug with print statements when I touch the engine (which is rare these days), so I'm probably not the best person to ask... 🙃

Maybe one of @dnfield @chinmaygarde @jason-simmons @zanderso will know more.

**Comment by jason-simmons** [comment]
The flutter_gdb script is still maintained (see https://github.com/flutter/engine/blob/main/sky/tools/flutter_gdb)

It provides a way to use GDB to remotely debug the Flutter engine running within an Android app process.

**Comment by sfshaza2** [comment]
Thanks, @bkonyi and @jason-simmons, this is very helpful!
