### ISSUE TITLE
'Sample App Catalog' page issue

### ISSUE THREAD

**Issue by fikermaryame** [flutter/website#2303]
Page URL: https://flutter.io/docs/catalog/samples/
Page source: https://github.com/flutter/website/tree/master/src/docs/catalog/samples/index.md

Description:dev/bots/docs.sh

**Comment by kangwang1988** [comment]
Thanks for filing an issue, but I’m going to close it for lack of a description. If you add a comment with details, we’ll reopen the issue.
@fikermaryame
