### ISSUE TITLE
'Background processes' page is too hard to understand.

### ISSUE THREAD

**Issue by korkis** [flutter/website#2312]
Page URL: https://flutter.io/docs/development/packages-and-plugins/background-processes.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/packages-and-plugins/background-processes.md

Description:
This example is too complicated. I have no even door in my home.
Isn't there any simple example I can understand?

**Comment by sfshaza2** [comment]
This would be a good candidate for the website.

**Comment by jepperaskdk** [comment]
Can someone tag Ben Konyi here? Is he an active developer of background processing in flutter?

**Comment by atsansone** [comment]
This duplicates https://github.com/flutter/website/issues/3104. Closing this issue.
