### ISSUE TITLE
'Developing packages 

### ISSUE THREAD

**Issue by pouledodue** [flutter/website#2333]
Page URL: https://flutter.io/docs/development/packages-and-plugins/developing-packages.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/packages-and-plugins/developing-packages.md

The vast majority of people developing packages who include an `example/` include a Material example.
Every day I find myself asking them in github issues "Do you have a Cupertino example somewhere for your package?" and the answer is nearly always "no" or "later". 

So, it would be great if the package best practices regarding `examples/` would be to create two subdirs `examples/material` and `examples/cupertino` by default to incite developers to include two examples instead of one.

On the packages page, adding a note inciting developers to add the two examples instead of one would be great

**Comment by sfshaza2** [comment]
This is a good idea. But we should also include this info on the pub site.
