### ISSUE TITLE
'Using Flutter in China' page issue

### ISSUE THREAD

**Issue by csloz** [flutter/website#2337]
Page URL: https://flutter.io/community/china.html
Page source: https://github.com/flutter/website/tree/master/src/community/china.md

"The Flutter community has made a Mandarin version" ->
"The Flutter community has made a Simplified Chinese version"

Mandarin refers to the spoken language.  If you refer to writing, then the written language has 2 forms - Simplified Chinese, and Traditional Chinese.

**Comment by sfshaza2** [comment]
Thanks for that info, @csloz!

**Comment by xster** [comment]
Looks like this issue can be closed?

**Comment by legalcodes** [comment]
Confirmed this change is in.
