### ISSUE TITLE
Website Localization in Japanese 

### ISSUE THREAD

**Issue by rnitta** [flutter/website#2341]
There are very few informations about Flutter in Japanese, 
so I'm thinking about forking and unofficially translating this repository into Japanese.
However I don't know if it is legitimate/acceptable. 
And I think the best is that flutter officially make a project to translate docs.

Now, the questions are
- Is there any plans to officially localize docs?
- As grass-roots, can I translate the forked repository into Japanese and deploy to somewhere?

**Comment by kangwang1988** [comment]
@rnitta 
> * Is there any plans to officially localize docs?

You can have a look at flutter's roadmap: https://github.com/flutter/flutter/wiki/Roadmap

> * As grass-roots, can I translate the forked repository into Japanese and deploy to somewhere?

Of course you can, we will appreciate your contributions to the community a lot.

**Comment by inari-sushio** [comment]
Hi, all.

Flutter is getting more and more popular in Japan recently and from what I see, Japanese localization is in very high demand.
I am planning to kick off a localization project, but before I step into it, I wanted to check if @rnitta san's plan is still on the move.

Also, could anyone kindly let me know if any other Japanese localization project going on for this website?
Not that I know of, from browsing through the internet including this repo, but if there are..., just to make sure.

Thank you!
