### ISSUE TITLE
'Mock dependencies using Mockito' page issue

### ISSUE THREAD

**Issue by VLEIX** [flutter/website#2342]
Page URL: https://flutter.io/docs/cookbook/testing/unit/mocking.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/unit/mocking.md

Description:
https://flutter.io/docs/cookbook/testing/unit/mocking#5-run-the-tests
The correct command is `flutter test test/fetch_post_test.dart`

**Comment by kangwang1988** [comment]
cc @chalin
