### ISSUE TITLE
Typo in Survey

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2367]
Survey from 
![image](https://user-images.githubusercontent.com/405837/52561824-cca6c200-2dfc-11e9-953d-ae11de332c52.png)

https://google.qualtrics.com/jfe/form/SV_bfowrKmM2DjD5tj?Source=Website
(2nd page)

![image](https://user-images.githubusercontent.com/405837/52561793-b26ce400-2dfc-11e9-9395-a0a2fe260d89.png)

`Disgree` instead of `Disagree`

**Comment by sfshaza2** [comment]
@jayoung-lee, this reports a typo in your survey.

**Comment by jayoung-lee** [comment]
@Sfshaza OMG thanks! It's fixed now.
