### ISSUE TITLE
'Parsing JSON in the background' page issue

### ISSUE THREAD

**Issue by giorodri0584** [flutter/website#2370]
Page URL: https://flutter.io/docs/cookbook/networking/background-parsing.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/background-parsing.md

Description:  final parsed = json.decode(responseBody).cast<Map<String, dynamic>>();
this line of code is giving an exception.
NoSuchMethodError: Class '_InternalLinkedHashMap<String, dynamic>' has no instance method 'cast' with matching arguments.

**Comment by brianegan** [comment]
Hey there @giorodri0584 -- could you please provide your Flutter version? I've just verified this example works on the `stable` branch and was not able to reproduce the error.

**Comment by sfshaza2** [comment]
@brianegan

**Comment by brianegan** [comment]
Hey @giorodri0584 -- did you happen to have any more information on this one? I'd like to make sure we don't have any errors like this on the cookbook, but I wasn't able to reproduce the problem.

Please let us know!

**Comment by brianegan** [comment]
Gonna close this one out for now due to inactivity. Please reopen if ya need more help :)
