### ISSUE TITLE
Broken link to internationalization example.

### ISSUE THREAD

**Issue by gspencergoog** [flutter/website#2373]
Reported on flutter-dev by Grzegorz Antoniak:

Just want to report a broken link in the documentation (it leads to GitHub's error 404).

URL: https://flutter.io/docs/development/accessibility-and-localization/internationalization

Section "Defining a class for the app’s localized resources",

Paragraph "Complete source code for this example app.",

Broken link: https://github.com/flutter/flutter/tree/master/examples/internationalization/intl_example

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/2371
