### ISSUE TITLE
document the widget reload indicators

### ISSUE THREAD

**Issue by devoncarew** [flutter/website#2374]
We shipped the widget reload indicators (both the in-editor ones, and the UI showing the table of rebuilt widgets). We should update the IntelliJ (and performance) docs to mention these.

@jacob314 @sfshaza2 

Here's an example of the feature: https://github.com/flutter/flutter-intellij/pull/2855#issuecomment-440473380

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/2403
