### ISSUE TITLE
Document the Minimum Android support version

### ISSUE THREAD

**Issue by SV27** [flutter/website#2377]
Hi.. I tried to find the minimum Android  platform version supported by Flutter and did not find any reference. It would be helpful, if we have those information in Flutter documentation.

**Comment by sfshaza2** [comment]
Good idea, @SV27. @Hixie, any idea where we can find this info?

**Comment by Hixie** [comment]
https://flutter.io/docs/resources/faq#what-devices-and-os-versions-does-flutter-run-on

**Comment by sfshaza2** [comment]
D'OH. @SV27, the info you need is at that link.

**Comment by SV27** [comment]
Thanks @sfshaza2 @Hixie
