### ISSUE TITLE
'Layouts in Flutter' page issue

### ISSUE THREAD

**Issue by LinXiaoTao** [flutter/website#2378]
Page URL: https://flutter.io/docs/development/ui/layout/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/layout/index.md

Description:
<img width="637" alt="qq20190213-165853 2x" src="https://user-images.githubusercontent.com/19836925/52699454-b8a3c180-2fb0-11e9-80bd-df3ef5a2fb56.png">

**Comment by sfshaza2** [comment]
@LinXiaoTao, can you explain the problem?  Thx

**Comment by LinXiaoTao** [comment]
@sfshaza2 Markdown syntax rendering error.
see **App Source**
