### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by abilkhaiyr** [flutter/website#2381]
Page URL: https://flutter.io/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description:
Hi! There is a bug in Get the Flutter SDK section. The button under "1. Download the following installation bundle to get the latest stable release of the Flutter SDK:" keeps saying "failed" after "loading" 
![image](https://user-images.githubusercontent.com/6446399/52759293-81c3bf00-3035-11e9-9b66-77fd32b353f1.png)

**Comment by kangwang1988** [comment]
Probably a network issue.

**Comment by abilkhaiyr** [comment]
Thanks! Was able to clone it from github
