### ISSUE TITLE
Fix references to the flutter logo

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#2391]
This past week, the top 404 was for `/images/flutter-mark-square-100.png`, which led me down a rabbit hole of logos. The summary:

* Someone should update the Flutter logo+text image on Wikipedia to be a new one.
* We should redirect /images/flutter-mark-square-100.png to a good logo-only file, presumably PNG and 100x100 pixels and with a transparent background. Or we could add back the file.

  * Redirect to https://storage.googleapis.com/cms-storage-bucket/0dbfcc7a59cd1cf16282.png

* For a link to the Flutter and Dart logo assets, https://flutter.dev/brand.

More details:

* A web search found references (but not links) to files named `flutter-mark-square-100.png` in https://github.com/flutter/flutter/issues/24814 & https://pub.dartlang.org/packages/fit_image.
* An actual link to it is in https://commons.wikimedia.org/wiki/File:Google-flutter-logo.png, which claims that it's the source (dated 30/09/2018) of the Flutter icon+text displayed on the page, which doesn't make sense because the displayed image isn't square.
* [Going to the Wayback Machine](https://web.archive.org/web/20181001111422/https://flutter.io/images/flutter-mark-square-100.png), I see that the file shows only the Flutter icon, not the text:
  ![image](https://user-images.githubusercontent.com/2164483/52890370-44485a00-3139-11e9-88da-9b81e1f251bc.png)
* The Flutter logos in [Google's onebox](https://g.co/kgs/BdpGe7) and [Wikipedia's Flutter page](https://en.wikipedia.org/wiki/Flutter_(software)) are old. The font is too light, and you can see a difference in color where the bottom of the "F" logo passes underneath the lower bar.

/cc @maguinis

**Comment by kwalrath** [comment]
This is still the top 404 on flutter.dev. It hurts me...

**Comment by kwalrath** [comment]
Still one of the top 404s. Maybe we should just add it back?

**Comment by sfshaza2** [comment]
SGTM

**Comment by micpap25** [comment]
What's the plan here? Add this image back into the site?

**Comment by kwalrath** [comment]
The good/bad news is that, since we switched infrastructures, this is now only the 20th most common 404.

#6313 describes the cause of many of the new top 20.

**Comment by atsansone** [comment]
The Flutter logo has been replaced on the site and in Wikipedia. Closing this issue.
