### ISSUE TITLE
'Preparing an Android App for Release' page issue

### ISSUE THREAD

**Issue by timsneath** [flutter/website#2394]
Page URL: https://flutter.io/docs/deployment/android.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/android.md

Description of issue:
https://flutter.io/docs/deployment/android#review-the-app-manifest talks about removing the INTERNET permission from `AndroidManifest.xml` if you don't need it. This permission has moved (the rationale isn't clear to me), as per https://github.com/flutter/flutter/pull/22139, so the instructions are no longer accurate.

@Hixie, interested in your thoughts here. The default template now creates a `debug/` and `profile/` subdirectory, but no `release/` subdirectory, so this is potentially a mogul for new developers building their first release build, since if I understand it correctly the default is that Debug has internet permission and Release doesn't. I don't personally think this difference between build types is intuitive, nor is it immediately obvious whether you can just add a `release/AndroidManifest.xml` and have it picked up by Gradle.

**Comment by sfshaza2** [comment]
@Hixie, please weigh in!

**Comment by sfshaza2** [comment]
I've updated this page this week, as per release 1.7.4.  Closing.
