### ISSUE TITLE
'Preparing an iOS App for Release' page issue

### ISSUE THREAD

**Issue by linhengu** [flutter/website#2396]
Page URL: https://flutter.io/docs/deployment/ios.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/ios.md

Reporting a TYPO? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by sfshaza2** [comment]
I don't see an issue reported. Closing.
