### ISSUE TITLE
[Suggestion about the site] Copy button in code snippets

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2397]
@jdamacena commented on [Tue Mar 27 2018](https://github.com/flutter/flutter/issues/15978)

I would like to have a Copy button close to code snippets on the site, like we've seen in several site out there, it's great to copy easily, especialy those great Complete Examples.

---

@Sfshaza commented on [Wed Jul 11 2018](https://github.com/flutter/flutter/issues/15978#issuecomment-404057885)

@InMatrix, a good suggestion for the new site.

---

@InMatrix commented on [Wed Jul 11 2018](https://github.com/flutter/flutter/issues/15978#issuecomment-404233878)

Cc: @filiph it would be nice to implement this on flutter.io.

---

@Sfshaza commented on [Mon Oct 15 2018](https://github.com/flutter/flutter/issues/15978#issuecomment-429750164)

@fertolg @chalin, would this be hard?

---

@chalin commented on [Mon Oct 15 2018](https://github.com/flutter/flutter/issues/15978#issuecomment-429824785)

No. This is something that had come up during early dash discussions. @fertolg: is there a standard implementation used for other sites that we could use here too?

---

@InMatrix commented on [Wed Oct 17 2018](https://github.com/flutter/flutter/issues/15978#issuecomment-430723886)

Cc: @gspencergoog DartDoc probably can use the same implementation for copying code snippets once the website has it. 

---

@gspencergoog commented on [Wed Oct 17 2018](https://github.com/flutter/flutter/issues/15978#issuecomment-430738545)

This is not hard.  "clipboard.js" is the magic package for this, and it's pretty trivial to hook up.

**Comment by zoechi** [comment]
Looks done, but I copied it here anyway to let you decide and close.

**Comment by sfshaza2** [comment]
I believe it is done. Closing.
