### ISSUE TITLE
A new resource to learn Flutter based on latest Flutter docs

### ISSUE THREAD

**Issue by smartherd** [flutter/website#2412]
This [course on youtube](https://www.youtube.com/watch?v=fmPmrJGbb6w&list=PLlxmoA0rQ-Lw6tAs2fGFuXGP13-dWdKsB) provides Flutter learning resource for beginners. The course quality is premium. You can run QA and peer review. The author is Sriyank Siddhartha who creates Android courses for Pluralsight. 

If you like it, kindly post it on your [technical videos page](https://flutter.io/docs/resources/videos).

**Comment by atsansone** [comment]
This request now links to a 4 year old course. This would not cover current functionality. Closing this issue.
