### ISSUE TITLE
'Write your first Flutter app, part 1 & 2': Consistent snippet guide style

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/website#2414]
Page URL: https://flutter.io/docs/get-started/codelab.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab.md

Description of issue:
Most of our snippets include all parent scopes leading to the patch line, for example,
```
  class RandomWordsState extends State<RandomWords> { // Good to know which class the change is in
    [!final _suggestions = <WordPair>[];!]
    [!final _biggerFont = const TextStyle(fontSize: 18.0);!]
    // ···
  }
```

Although most snippets keep this clear and intuitive format, some snippets don't, for example,
```
// <- Which class? Should I add it to global?
  Widget _buildSuggestions() {
    return ListView.builder(
        padding: const EdgeInsets.all(16.0),
        itemBuilder: /*1*/ (context, i) {
          if (i.isOdd) return Divider(); /*2*/

          final index = i ~/ 2; /*3*/
          if (index >= _suggestions.length) {
            _suggestions.addAll(generateWordPairs().take(10)); /*4*/
          }
          return _buildRow(_suggestions[index]);
        });
  }
```

Although the sentence right before this snippet says which class it's from, I suggest we keep the same format for all snippets for clarity and consistency.

The affected ones:
- [ ] Part 1 Step 4
  - [ ] section 2
  - [ ] section 3
  - [ ] section 4 
- [ ] Part 2 
  - [ ] Step 4, snippet 2 & 3
  - [ ] Step 5, snippet 1
  - [ ] Step 6, snippet 2 and forward

**Comment by sfshaza2** [comment]
While this sounds good in theory, @dkwingsmt, the issue isn't so easy, particularly on flutter.dev. I have recently updated both codelabs, and I tried to make sure that this is as clear as possible.
