### ISSUE TITLE
"Write your first Flutter app, part 2" - Clarify description of step

### ISSUE THREAD

**Issue by shihaohong** [flutter/website#2419]
URL of codelab: https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#5

Currently, the step describes `Add horizontal dividers, as shown below:`, when it should be `Add tiles with horizontal dividers, as shown below:`

<img width="776" alt="screen shot 2019-02-21 at 2 26 55 pm" src="https://user-images.githubusercontent.com/27032613/53206030-c24aac00-35e4-11e9-8132-420b9bdb3475.png">

**Comment by sfshaza2** [comment]
This wording is no longer used.
