### ISSUE TITLE
'Flutter SDK archive' page issue

### ISSUE THREAD

**Issue by JiDoc1234** [flutter/website#2435]
Page URL: https://flutter.dev/docs/development/tools/sdk/archive.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/archive.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by JiDoc1234** [comment]
three different browsers all show - loading for all platforms, cannot download flutter sdk

**Comment by sfshaza2** [comment]
Hi, @JiDoc1234! Are you still having problems? I can download it now and I'm wondering if this might have been related to the change yesterday from flutter.io to flutter.dev. Please try again and let me know.

**Comment by sfshaza2** [comment]
Closing.
