### ISSUE TITLE
'MacOS install' page issue

### ISSUE THREAD

**Issue by JiDoc1234** [flutter/website#2436]
Page URL: https://flutter.dev/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

![image](https://user-images.githubusercontent.com/810134/53274348-daa6ed80-36ee-11e9-9a10-3b5a1f162f46.png)

**Comment by sfshaza2** [comment]
Need to see if we can replicate...

**Comment by sfshaza2** [comment]
I left a comment on the other bug you filed, @JiDoc1234. Is this still happening for you?

**Comment by sfshaza2** [comment]
Duplicate of https://github.com/flutter/website/issues/2460

Closing
