### ISSUE TITLE
'Flutter's build modes' page issue

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#2437]
Page URL: https://flutter.dev/docs/testing/build-modes.html
Page source: https://github.com/flutter/website/tree/master/src/docs/testing/build-modes.md

Description of issue:
It says release mode corresponds to the Android Studio bug icon, and debug mode corresponds to the regular icon. That can't be right...

"The command flutter run --release compiles to release mode. Your IDE also supports these modes. Android Studio, for example, provides a Run > Run… menu option, as well as a green bug icon overlayed with a small triangle on the project page. (The menu item shows a pic of the corresponding icon.)"
(and the reverse)

**Comment by sfshaza2** [comment]
Fixed.
