### ISSUE TITLE
'MacOS install' page issue

### ISSUE THREAD

**Issue by darrencole** [flutter/website#2441]
Page URL: https://flutter.dev/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
In the section on deploying to an iOS device, could you please indicate to users that the active scheme should be set to the device. After successfully deploying to a simulator and closing the simulator, I proceeded to deploy to a device but the active scheme was still set to the simulator. This resulted in a rather ambiguous error in Xcode (relating to provisioning keys) which took me hours to figure out.

Thanks much!

**Comment by sfshaza2** [comment]
This has been fixed at some point. On this page, under the "deploy" section, it states:

```
Select the device you intend to deploy to in the device drop-down menu next to the run button.
```

Closing.
