### ISSUE TITLE
Incorrect instructions for Android in "Continuous Delivery using fastlane with Flutter"

### ISSUE THREAD

**Issue by atsu85** [flutter/website#2458]
This is related to #2382, pointing out another issue on that page:

Currently under Fastlane [Local setup](https://flutter.dev/docs/deployment/fastlane-cd#local-setup) there is:
> 4. Edit the Appfiles to ensure they have adequate metadata for your app. 
> Check that package_name in [project]/android/Appfile matches your package in **pubspec.yaml**.

but instead of pubspec.yaml it should point to **applicationId in android/app/build.gradle**, otherwise uploading to play store would fail, as fastlane can't find the application

**Comment by sfshaza2** [comment]
Can you confirm, @xster?

**Comment by atsu85** [comment]
@sfshaza2, @xster, i updated my initial post where instead of 
> applicationId in android/app/build.gradle

i had
> AndroidManifest.xml

, because even tough applicationId in android/app/build.gradle is often the same as package in AndroidManifest.xml (for example after generating new flutter project), but they don't need to match. And if they don't match, you still need to provide value from applicationId of android/app/build.gradle.

**Comment by xster** [comment]
You're correct. Thanks for pointing out. It should indeed reference AndroidManifest.xml's package name or iOS's Info.plist's bundle identifier. 

I'll make the correction

**Comment by atsu85** [comment]
@xster, looks like you didn't notice my previous comment when [you changed](https://github.com/flutter/website/pull/2474/files) instructions to use `package name in AndroidManifest.xml`, but it should be `applicationId in android/app/build.gradle` instead, as they may be different and that is when it matters.
