### ISSUE TITLE
Simplify install instructions on `macOS install` page

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#2461]
Concrete propositions.
1. Move system requirements to the bottom of the screen or to a pop-up - make the blue "get sdk" closer to the top
2. Consider two different audiences - audiences that want hello world to work with no IDE, and audiences that prefer they not use a terminal ever, and make it as easy as possible for those audiences to find what they are looking for - e.g. if you have Intellij and install flutter plugin, how many of the commandline steps will you ever need to do.
3. Load the flutter version number server side rather than clientside in javascript - then the "loading" button will work without having firewall issues and the commandline can be exactly up to date instead of flutter_macos_vX.X.X-stable.zip 

Reason:
* Flutter is reaching a broad base of users. Some are very comfortable with commandline, and some are not.
* Flutter is growing so rapidly that the zero-hour experience continues to be important. (Thanks for having that tag)

awesome job with flutter documentation

**Comment by sfshaza2** [comment]
Excellent suggestions.

**Comment by sfshaza2** [comment]
We are planning to overhaul our install/get started instructions. I'm lowering the priority of this issue to P2.
