### ISSUE TITLE
'Navigate to a new screen and back' page issue

### ISSUE THREAD

**Issue by jeongjoonl** [flutter/website#2462]
Page URL: https://flutter.dev/docs/cookbook/navigation/navigation-basics.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/navigation-basics.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

The gif image on the bottom of the page seems not right.
Maybe we can have a better gif image.

Thanks for the great tutorial by the way.

**Comment by sfshaza2** [comment]
Thanks, @jeongjoonl!  

@brianegan, can you take a look at this one, too?

**Comment by brianegan** [comment]
Thanks for the report! I've pushed a PR with a smoother and complete gif.
