### ISSUE TITLE
'Navigate with named routes' page issue

### ISSUE THREAD

**Issue by jeongjoonl** [flutter/website#2463]
Page URL: https://flutter.dev/docs/cookbook/navigation/named-routes.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/named-routes.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

The gif image on the bottom of the page seems not right.

**Comment by sfshaza2** [comment]
The gif does seem a bit jerky. Is that what you mean, @jeongjoonl?

@brianegan, can you take a look?

**Comment by brianegan** [comment]
Thanks, all! This is also fixed as part of #2467, since both recipes produce the same visual output!
