### ISSUE TITLE
Add irc to community page

### ISSUE THREAD

**Issue by bradyt** [flutter/website#2465]
There is a #flutter page on freenode. That will be convenient for people communicating from machines with less RAM, etc. Let's add it to the community page?

**Comment by sfshaza2** [comment]
Thanks for letting us know, @bradyt!

**Comment by Hixie** [comment]
Since we have plenty of links already, this is probably not critical to add. There's a growing number of places for Flutter developers to hang out with each other and it would be impractical to list them all at this point.
