### ISSUE TITLE
'MacOS install' page issue

### ISSUE THREAD

**Issue by weitieda** [flutter/website#2477]
Page URL: https://flutter.dev/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

It should be `macOS` instead of `MacOS`

**Comment by aromalanil** [comment]
I checked the page and couldn't find any occurrence of ``MacOS``, I suggest this issue can be closed.

**Comment by weitieda** [comment]
Yes... it's a really old ticket...

l just closed it.
