### ISSUE TITLE
Image overflow on home page

### ISSUE THREAD

**Issue by Piinks** [flutter/website#2480]
Some images seem to be overflowing on the homepage of [flutter.dev](https://flutter.dev/)
It is happening in the "Who's using Flutter?" section. See images from desktop and mobile below.

**Desktop using Chrome:**
<img width="800" alt="desktop image of website error" src="https://user-images.githubusercontent.com/16964204/53920856-5ecc6f80-4023-11e9-9a6f-3415bf3e5672.PNG">

**Mobile using Safari:**
<img width="400" alt="mobile image of website error" src="https://user-images.githubusercontent.com/16964204/53920863-6429ba00-4023-11e9-9269-b6fd5d8f1296.PNG">

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/2510
