### ISSUE TITLE
Minor mistake in cassowary plugin priority documentation

### ISSUE THREAD

**Issue by dresserm** [flutter/website#2482]
Line 14 in the priority.dart file, part of the cassowary plugin, says that the maximum Priority level is 1000000000 but it is actually 1001001000.0.

**Comment by sfshaza2** [comment]
@dresserm, do you mean you found a s/w bug here?  https://pub.dartlang.org/packages/cassowary

The relevant person will never see a plugin bug filed on the Flutter website. Can you file a bug here?
https://github.com/google/cassowary.dart/issues

I will close this bug. Thanks!
