### ISSUE TITLE
'Dentro de Flutter' page issue

### ISSUE THREAD

**Issue by alvaromashiro** [flutter/website#2484]
Page URL: https://flutter-es.io/docs/resources/inside-flutter.html
Page source: https://github.com/flutter/website/tree/master/src_es/docs/resources/inside-flutter.md

Hay un error en el titulo del link en el menu dice _"Dento"_ en lugar de _"Dentro"_

**Comment by Twinber** [comment]
Gracias Alvaro, pero estas poniendo el issue en el repositorio de la web en ingles, tomo nota en la nuestra.

**Comment by alvaromashiro** [comment]
Disculpa, no sabia como hacerlo. Se puede mover el issue?

**Comment by Twinber** [comment]
Ya está resuelto .
Please @sfshaza2 close this issue

**Comment by sfshaza2** [comment]
Thanks, @Twinber!
