### ISSUE TITLE
Images in home page of Spanish site

### ISSUE THREAD

**Issue by mglriosr** [flutter/website#2485]
![Screen Shot 2019-03-08 at 2 23 21 PM](https://user-images.githubusercontent.com/25510181/54050818-2d33df80-41ae-11e9-99ea-6d0e45025ad9.png)

**Comment by Twinber** [comment]
Esto ya está reportado en #2480
El error es del repo original 
Los issues relacionados con el sitio en español por favor en https://github.com/flutter-es/website

**Comment by Twinber** [comment]
@Sfshaza please close this.
