### ISSUE TITLE
Please add Chrome search feture on flutter.dev

### ISSUE THREAD

**Issue by the4thfloor** [flutter/website#2502]
I'm sorry but I don't know to call this feature, I try to describe what I mean ;-)

When I enter `flutter.io` followed by a `<space>` in the address bar of Chrome, it changes to a search field and I can search something on `flutter.io`.

This doesn't happen with `flutter.dev`

**Comment by sfshaza2** [comment]
Good catch, @the4thfloor!

**Comment by sfshaza2** [comment]
It’s there now! Closing..
