### ISSUE TITLE
Consider adding document on how to use FlutterDartProject

### ISSUE THREAD

**Issue by jkmathew** [flutter/website#2509]
In flutter framework Could see an initialiser for `FlutterEngine` as  
`- (instancetype)initWithName:(NSString*)labelPrefix project:(FlutterDartProject*)projectOrNil;`.  
 From the `FlutterDartProject` header its clear that `FlutterDartProject` can be initialised with a precompiled dart bundle(correct me if I am wrong). But I couldn't find a document describing how to compile flutter in to a bundle and use that bundle with `FlutterDartProject`.

What I am trying to achieve is, use multiple components created with flutter in same native project. Each components are independent, so it cannot be used with different entry points or routes for FlutterViewController.

How to compile flutter module to a bundle and use it with `FlutterDartProject` to initialise a `FlutterEngine`?

I could see other issues similar to this, but I believe if I can find a way to figure out this, will be able to figure out way for them also. 

My SO question: https://stackoverflow.com/questions/55127464/how-to-use-flutterdartproject
Couldn't find an answer from there :(

**Comment by sfshaza2** [comment]
Hi @jkmatthew! This kind of information is beyond the scope of flutter.dev. Generally, we put engineering info like this on the relevant GitHub repo, such as https://github.com/flutter/engine. Perhaps you could file an issue there and/or post your question to the flutter-dev Google group:  https://groups.google.com/forum/#!forum/flutter-dev

I’m sorry this isn’t more helpful..
