### ISSUE TITLE
It would be very glad to add fish-redux to show in flutter official website

### ISSUE THREAD

**Issue by zjuwjf** [flutter/website#2516]
[Fish Redux](https://github.com/alibaba/fish-redux) is an assembled flutter application framework based on Redux.

**Comment by sfshaza2** [comment]
@filiph

**Comment by filiph** [comment]
In my opinion, the best place to have this is https://flutter.dev/docs/development/data-and-backend/state-mgmt/options. Please feel free to create a Pull Request on https://github.com/flutter/website/blob/master/src/docs/development/data-and-backend/state-mgmt/options.md and cc me.

**Comment by rubensdemelo** [comment]
@filiph done. Should I add more comments or improve description?

**Comment by filiph** [comment]
Change merged, thank you!
