### ISSUE TITLE
'Pass arguments to a named route' page issue

### ISSUE THREAD

**Issue by Twinber** [flutter/website#2518]
Page URL: https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/navigate-with-arguments.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

// If you push the the PassArguments route ¿?

**Comment by sfshaza2** [comment]
@brianegan, just remove the double "the the" . :)

**Comment by rubensdemelo** [comment]
@sfshaza2 done.
