### ISSUE TITLE
'List of state management approaches' page issue

### ISSUE THREAD

**Issue by Sun3** [flutter/website#2519]
Page URL: https://flutter.dev/docs/development/data-and-backend/state-mgmt/options.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/state-mgmt/options.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: In the BLoC / Rx section the link to the page "State Management Using BLoC pattern in Flutter, by Saowen" [State Management Using BLoC pattern in Flutter, by Saowen](https://hk.saowen.com/a/fbb6e484de022173fe85248875286060ce40d069c97420bc0be49d838e19e372) is broken.

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/2512
