### ISSUE TITLE
Include option to get Flutter by cloning repository

### ISSUE THREAD

**Issue by rubensdemelo** [flutter/website#2529]
Would be nice refer another option to get flutter is cloning the repository.

https://github.com/flutter/website/edit/master/src/docs/get-started/install/_get-sdk.md

**Comment by atsansone** [comment]
This was added to the macOS page, but it muddles the guide. Considering refactoring page to include this across all dev platforms.

**Comment by atsansone** [comment]
Conflicts with #2131
