### ISSUE TITLE
Consider including some "Persistence" details in "Data & backend" pages.

### ISSUE THREAD

**Issue by ShivamSinghania** [flutter/website#2531]
Page URL: https://flutter.dev/docs/development/data-and-backend/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/index.md
Description of issue: Some flutter users are newbies like me who have never built any app. When I read through the [data & backend page](https://flutter.dev/docs/development/data-and-backend), I kind of formed this impression that state management is all I need to do for my app's backend. I was expecting scoped model to take care of the data even when my app is not running. Lack of persistence related code(or even comments) in the scoped model [example](https://github.com/filiph/samples/tree/scoped-model-shopper/model_shopper) only solidified this impression. When my app lost all user data on every restart, I realized I was doing something wrong. [Scoped model sample](https://github.com/brianegan/flutter_architecture_samples/tree/master/scoped_model) showed me I was missing data storage. Then flutter's gitter channel pointed me to https://flutter.dev/docs/cookbook/persistence. I didn't even know app data storage is called "persistence" but it makes sense now.

1. It would be much more clear if some details from [Persistence](https://flutter.dev/docs/cookbook/persistence) are included in [Data & backend](https://flutter.dev/docs/development/data-and-backend/), or at least it contains a link to it. 
2. Comments like `//ADD PERSISTENCE CODE HERE: Use firebase or even local storage` in the example apps can also help point out the obvious.

**Comment by sfshaza2** [comment]
@filiph
