### ISSUE TITLE
Add token-based auth examples

### ISSUE THREAD

**Issue by joeythomaschaske** [flutter/website#2533]
There needs to be examples for token based authentication. It is difficult to know how to store tokens for persistent authentication and even more difficult when there is no clear(opinionated) solution for app state.

Things that would be cool to see:

- Loading tokens from local storage
- Dynamic route to show Login page when user is unauthenticated and Home/requested page when user is authenticated
- reading tokens in different parts of your app when you do requests to authenticated endpoints
- updating tokens in the app when tokens expire

**Comment by sfshaza2** [comment]
@filiph

**Comment by atsansone** [comment]
There are a [great number of token authentication packages](https://pub.dev/packages?q=authentication+token) from Firebase to Okta to Azure. This would be a large project that would be very difficult to maintain. Recommend reviewing the documentation for those packages first. Closing this issue.
