### ISSUE TITLE
[flutter-es] new look 4x more bandwidth

### ISSUE THREAD

**Issue by Twinber** [flutter/website#2534]
![excesodeconsumo](https://user-images.githubusercontent.com/5513621/54525893-78e84500-4975-11e9-998c-1a8c4aec7680.jpg)

**Comment by Twinber** [comment]
The increase in bandwidth consumption does not correspond to an increase in visits to the web.
Have you experienced this since the change to the new design?

**Comment by kwalrath** [comment]
We haven't noticed this, in general, but I believe the homepage has a lot more data due to its animation. If you remove the animation or you omit the homepage from the data, what happens?

**Comment by Twinber** [comment]
Yes.. is the homepage
