### ISSUE TITLE
'Write your first Flutter app, part 1' page issue

### ISSUE THREAD

**Issue by travisbhartwell** [flutter/website#2539]
Page URL: https://flutter.dev/docs/get-started/codelab.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab.md

Description of issue:

I did part 1 of the CodeLab from this page. However, it appears that this is different to the version that is [on Google Codelabs](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#0).

* [This is the finished Part 1 code from the version on Google Codelabs](https://gist.githubusercontent.com/Sfshaza/d6f9460a04d3a429eb6ac0b0f07da564/raw/6c4c0b476fd5d584fe0704314703653eff8eca2d/main.dart)
* [This is the finished Part 1 code from the version directly on flutter.dev](https://raw.githubusercontent.com/flutter/codelabs/master/startup_namer/step4_infinite_list/lib/main.dart)

I'm guessing that the version on flutter.dev is using a newer version of Dart, as I see it omits the use of `new` and does not declare the type of variables.

This is a problem then as I try to move to [Part 2](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/) and the code I'm working from is not the same as what Part 2 is building up, and as I'm just now learning Dart, it's not obvious how to fix it.

Is there an updated version of the Codelab somewhere? Or is the version on Google Codelabs the latest version and the flutter.dev version is out of date?

**Comment by sfshaza2** [comment]
This was an issue before Google I/O 2019, but the 2nd lab has been updated.

Closing.
