### ISSUE TITLE
'Working with WebSockets' page issue

### ISSUE THREAD

**Issue by ValiantCat** [flutter/website#2540]
Page URL: https://flutter.dev/docs/cookbook/networking/web-sockets.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/web-sockets.md

Description of issue:

TextEditingController need dispose  when _MyHomePageState dispose.

**Comment by parlough** [comment]
Thanks for filing an issue!

Fixed by https://github.com/flutter/website/pull/6647
