### ISSUE TITLE
place holder isn't working in CacherNetworkImage

### ISSUE THREAD

**Issue by saidbendrioue** [flutter/website#2550]
Page URL: https://flutter.dev/docs/cookbook/images/cached-images.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/images/cached-images.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by sfshaza2** [comment]
Closing for lack of info.
