### ISSUE TITLE
Add notes to 'Using Flutter in China' page about publishing and Google Accounts

### ISSUE THREAD

**Issue by jonasfj** [flutter/website#2556]
Page URL: https://docs.flutter.dev/community/china
Page source: https://github.com/flutter/website/tree/master/src/community/china.md

I'm not sure exactly how to phrase this... But could we mention that `flutter packages publish` will not work when using `export PUB_HOSTED_URL=https://pub.flutter-io.cn`.

----
Publishing packages also requires a Google account, so I'm not sure Chinese users will find that easy to do.

**Comment by Realank** [comment]
Hi jonasfj:

Here is my verbose log when publish my package using Chinese mirror pub:
Looks great! Are you ready to upload your package (y/n)? y
FINE: Loading OAuth2 credentials.
FINE: Saving OAuth2 credentials.
IO  : Writing 377 characters to text file /Users/realank/.pub-cache/credentials.json.
MSG : Uploading...
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 2.1.1-dev.2.0.flutter-2e5453ddb4
IO  : HTTP error:
    | SocketException: OS Error: Operation timed out, errno = 60, address = accounts.google.com, port = 49602
    | 
    | dart:_http                                _HttpClient.openUrl
    | package:http/src/io_client.dart 33:36     IOClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart  ThrottleClient.send
    | package:http/src/base_client.dart 169:38  BaseClient._sendUnstreamed
    | ===== asynchronous gap ===========================
    | dart:async                                Future.then
    | package:pub/src/oauth2.dart 83:28         withClient
    | package:pub/src/command/lish.dart 67:13   LishCommand._publish
    | dart:async                                _AsyncAwaitCompleter.start
    | package:pub/src/command/lish.dart 64:18   LishCommand._publish
    | package:pub/src/command/lish.dart 143:13  LishCommand.run
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:pub/src/command/lish.dart         LishCommand.run
    | package:args/command_runner.dart 194:27   CommandRunner.runCommand
IO  : Retry #1 for POST https://accounts.google.com/o/oauth2/token...
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 2.1.1-dev.2.0.flutter-2e5453ddb4

it seems that,  https://accounts.google.com/o/oauth2/token can't be visited in China

**Comment by Realank** [comment]
Hi jonasfj:

I have done some tests with @chenglu just now, and we don't think this is the problem of CN mirror.
Most CN devs using the HTTP(s)/SOCK5 proxy, but the Terminal seems didn't always have the proxy setup, so when the OAuth process happened next to “Google prompts user for consent” --Exchange authorization code for refresh and access tokens, the Terminal need connect to https://accounts.google.com/o/oauth2/token, so the process stuck here.
Since we have tested:

1. CN Mirror enable, VPN enable, no credentials.json(no accessToken/refreshToken), authorized in browser, refresh token success in console, publish package success

2. CN Mirror enable, VPN disable, Shadowsocks disable, has credentials.json(valid accessToken/refreshToken), no necessary to authorize again, no necessary to refresh token, publish package success

3. CN Mirror enable, Shadowsocks enable, no credentials.json(no accessToken/refreshToken), authorized in browser, refresh token time out in console, publish package failed:

Looks great! Are you ready to upload your package (y/n)? y
FINE: Loading OAuth2 credentials.
MSG : Pub needs your authorization to upload packages on your behalf.
    | In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A62530&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
    | Then click "Allow access".
    | 
    | Waiting for your authorization...
MSG : Authorization received, processing...
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 2.1.1-dev.2.0.flutter-2e5453ddb4
IO  : HTTP error:
    | SocketException: OS Error: Operation timed out, errno = 60, address = accounts.google.com, port = 62623
    | 
    | dart:_http                                _HttpClient.openUrl
    | package:http/src/io_client.dart 33:36     IOClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart  ThrottleClient.send
    | package:http/src/base_client.dart 169:38  BaseClient._sendUnstreamed
    | ===== asynchronous gap ===========================
    | dart:async                                StreamView.listen
    | package:shelf/shelf_io.dart 64:14         serveRequests.<fn>
    | package:shelf/src/util.dart 24:20         catchTopLevelErrors
    | package:shelf/shelf_io.dart 63:3          serveRequests
    | package:pub/src/oauth2.dart 185:5         _authorize.<fn>
    | dart:async                                _completeOnAsyncReturn
    | package:pub/src/io.dart                   bindServer
    | ===== asynchronous gap ===========================
    | dart:async                                Future.then
    | package:pub/src/oauth2.dart 184:30        _authorize
    | package:pub/src/oauth2.dart 114:41        _getClient
    | dart:async                                _AsyncAwaitCompleter.start
    | package:pub/src/oauth2.dart 112:26        _getClient
    | package:pub/src/oauth2.dart 83:10         withClient
    | package:pub/src/command/lish.dart 67:13   LishCommand._publish
    | dart:async                                _AsyncAwaitCompleter.start
    | package:pub/src/command/lish.dart 64:18   LishCommand._publish
    | package:pub/src/command/lish.dart 143:13  LishCommand.run
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:pub/src/command/lish.dart         LishCommand.run
    | package:args/command_runner.dart 194:27   CommandRunner.runCommand
IO  : Retry #1 for POST https://accounts.google.com/o/oauth2/token...
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 2.1.1-dev.2.0.flutter-2e5453ddb4
IO  : HTTP error:
    | SocketException: OS Error: Operation timed out, errno = 60, address = accounts.google.com, port = 62976
    | 
    | dart:_http                                _HttpClient.openUrl
    | package:http/src/io_client.dart 33:36     IOClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:http_retry/http_retry.dart        RetryClient.send
    | package:pub/src/http.dart 194:43          _ThrowingClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart  ThrottleClient.send
    | package:http/src/base_client.dart 169:38  BaseClient._sendUnstreamed
    | ===== asynchronous gap ===========================
    | dart:async                                StreamView.listen
    | package:shelf/shelf_io.dart 64:14         serveRequests.<fn>
    | package:shelf/src/util.dart 24:20         catchTopLevelErrors
    | package:shelf/shelf_io.dart 63:3          serveRequests
    | package:pub/src/oauth2.dart 185:5         _authorize.<fn>
    | dart:async                                _completeOnAsyncReturn
    | package:pub/src/io.dart                   bindServer
    | ===== asynchronous gap ===========================
    | dart:async                                Future.then
    | package:pub/src/oauth2.dart 184:30        _authorize
    | package:pub/src/oauth2.dart 114:41        _getClient
    | dart:async                                _AsyncAwaitCompleter.start
    | package:pub/src/oauth2.dart 112:26        _getClient
    | package:pub/src/oauth2.dart 83:10         withClient
    | package:pub/src/command/lish.dart 67:13   LishCommand._publish
    | dart:async                                _AsyncAwaitCompleter.start
    | package:pub/src/command/lish.dart 64:18   LishCommand._publish
    | package:pub/src/command/lish.dart 143:13  LishCommand.run
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:pub/src/command/lish.dart         LishCommand.run
    | package:args/command_runner.dart 194:27   CommandRunner.runCommand
IO  : Retry #2 for POST https://accounts.google.com/o/oauth2/token...
IO  : HTTP POST https://accounts.google.com/o/oauth2/token
    | content-type: application/x-www-form-urlencoded; charset=utf-8
    | user-agent: Dart pub 2.1.1-dev.2.0.flutter-2e5453ddb4
IO  : HTTP error:
    | SocketException: OS Error: Operation timed out, errno = 60, address = accounts.google.com, port = 63369
    | 
    | dart:_http                                _HttpClient.openUrl
    | package:http/src/io_client.dart 33:36     IOClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:http_retry/http_retry.dart        RetryClient.send
    | package:pub/src/http.dart 194:43          _ThrowingClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart  ThrottleClient.send
    | package:http/src/base_client.dart 169:38  BaseClient._sendUnstreamed
    | ===== asynchronous gap ===========================
    | dart:async                                StreamView.listen
    | package:shelf/shelf_io.dart 64:14         serveRequests.<fn>
    | package:shelf/src/util.dart 24:20         catchTopLevelErrors
    | package:shelf/shelf_io.dart 63:3          serveRequests
    | package:pub/src/oauth2.dart 185:5         _authorize.<fn>
    | dart:async                                _completeOnAsyncReturn
    | package:pub/src/io.dart                   bindServer
    | ===== asynchronous gap ===========================
    | dart:async                                Future.then
    | package:pub/src/oauth2.dart 184:30        _authorize
    | package:pub/src/oauth2.dart 114:41        _getClient
    | dart:async                                _AsyncAwaitCompleter.start
    | package:pub/src/oauth2.dart 112:26        _getClient
    | package:pub/src/oauth2.dart 83:10         withClient
    | package:pub/src/command/li

and in test 3, when we enable shadowsocks, we can't ping accounts.google.com in Terminal, but can  access this url in browser

**Comment by chenglu** [comment]
Great thanks to @Realank for your time!
@jonasfj please ignore my Email of adding the whitelist ;-)

**Comment by jonasfj** [comment]
If you're behind a proxy you'll probably have to setup environment variables for `pub` to use said proxy, see: https://www.dartlang.org/tools/pub/troubleshoot#pub-get-fails-from-behind-a-corporate-firewall

**Comment by chenglu** [comment]
@jensjoha is this the same way to change the proxy setting in the whole Terminal?
@Realank could you please try to set the proxy with the document and shut down VPN which controlled the all traffic, using CN mirror, and try to publish the package?

**Comment by jensjoha** [comment]
I guess the above should have been @jonasfj ?

**Comment by chenglu** [comment]
Sorry to @jensjoha! 
Yes, I am trying to mention @jonasfj.

**Comment by jonasfj** [comment]
> is this the same way to change the proxy setting in the whole Terminal?

I think setting `http_proxy` and `https_proxy` environment variables is the convention for how you tell CLI programs how to use a proxy. If there is some other means by which we could detect a proxy to use, I'm open to considering those.

But `dart:io` will use `http_proxy` and `https_proxy` environment variables, if they are defined.
