### ISSUE TITLE
Fix 404: /docs/get-started/install.

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#2558]
Since 3/25, we've started getting 404s for `https://flutter.dev/docs/get-started/install.` (note the added `.`, which makes the otherwise OK URL break).

We could either redirect this or hunt down the offender and (if possible) fix it. Maybe both.

I see no commits to this site on 3/25, so presumably the offender is external.

**Comment by cneilmon** [comment]
hey! look at the comment here: https://github.com/flutter/website/issues/2595
seems its already working fine

**Comment by sfshaza2** [comment]
As @cneilmon mentioned, it seems to be fixed now. Closing.
