### ISSUE TITLE
Consider compressing your PNGS

### ISSUE THREAD

**Issue by kevmoo** [flutter/website#2567]
bytes to save: 12,943,491

```
> find . -name '*.png' -print0 | xargs -0 -P8 -L1 pngquant --ext .png --force --speed 1 --skip-if-larger
```

**Comment by kevmoo** [comment]
CC @gspencergoog

**Comment by sfshaza2** [comment]
I thought that compressing PNGs happened automatically.

**Comment by kevmoo** [comment]
I worked through this with @gspencergoog – perhaps `pngquant` does a better job?

**Comment by chalin** [comment]
@sfshaza2 - After  #4336 and #4337 are merged (since they add / tweaks some images), I can run the image-compression script if you'd like.

**Comment by sfshaza2** [comment]
That would be great, @chalin! I've merged both PRs.

**Comment by chalin** [comment]
Done, see #4339
