### ISSUE TITLE
HSTS security error on website

### ISSUE THREAD

**Issue by atilkan** [flutter/website#2572]
@chalin @mit-mit @sethladd
Can't visit website on some countries. Chrome, Firefox, Opera. I have to use VPN for a simple site. Turkey is the country. I am sure there are others. 
![Screen Shot 2019-04-04 at 16 42 02](https://user-images.githubusercontent.com/1254613/55560300-98fb6080-56f8-11e9-8813-27a360a5cf52.png)

![Screen Shot 2019-04-04 at 16 40 25](https://user-images.githubusercontent.com/1254613/55560248-83863680-56f8-11e9-872b-71f08e8f9d7c.png)
![Screen Shot 2019-04-04 at 16 40 35](https://user-images.githubusercontent.com/1254613/55560251-841ecd00-56f8-11e9-8557-32162cd4801d.png)

**Comment by atilkan** [comment]
This is the explanation after clicking Advanced button.
![Screen Shot 2019-04-20 at 00 25 20](https://user-images.githubusercontent.com/1254613/56444778-d23fed00-6302-11e9-84ec-98a018d72422.png)

**Comment by mit-mit** [comment]
cc @kf6gpe

**Comment by atilkan** [comment]
I was able to solve this by this. 
https://superuser.com/questions/1413402/i-cant-visit-websites-that-have-dev-domain
