### ISSUE TITLE
Codelab documentation needs update - Write Your First Flutter App, part 2

### ISSUE THREAD

**Issue by RDuuke** [flutter/website#2573]
There is an error in[ step number 4,](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#3) in the line 
`final bool alreadySaved = _saved.contains (pair); // Add this line.`

When I run, it generates an error:

> NoSuchMethodError: The Method 'contains' was called on null.
> Receiver: null
> Tried calling: contains (Instance of 'WordPair');

**Comment by sfshaza2** [comment]
This should be fixed. Please reopen if you find that's not the case.
