### ISSUE TITLE
'Android Studio / IntelliJ' page issue

### ISSUE THREAD

**Issue by VarolOkan** [flutter/website#2574]
Page URL: https://flutter.dev/docs/development/tools/android-studio.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/android-studio.md

Description of issue:
So Android Studios top menu has only [File][Edit][View][Navigate][Build][Run][Tools][VCS][Window][Help]
There is NO [Check for Updates]

The proper path is 
[Android Studio] -> [Settings] -> [Appearances and behaviour] -> [Updates]

**Comment by sfshaza2** [comment]
Hi, @VarolOkan! Which platform are you on? I am on a Mac and my top menu is:

[Android Studio] [File][Edit][View][Navigate][Code][Analyze][Refactor][Build][Run][Tools][VCS][Windows][Help]

For me, it's definitely
[Android Studio] -> [Check for updates...]

But, if you tell me your platform, I can add that info.

Thanks!

**Comment by sfshaza2** [comment]
Closed due to lack of info.
