### ISSUE TITLE
Release Mode - Get Started Documentation

### ISSUE THREAD

**Issue by alistairsykes** [flutter/website#2578]
I’d really recommend adding a nod to release mode in your “Get started” section of the docs.

My task was to work out whether, as a company, we need to be considering Flutter. Given the agency nature of our work, I was only able to spend a couple of days exploring. This meant I didn’t get as far as the “Testing & optimization” section. Even then, my experience in native development would never lead me to think there would be a “high performance” setting.

Given the connotations cross-platform comes with, I’d say Flutter needs to impress in those first impressions. So telling people about release mode earlier might benefit you guys alot.

Adding a link and one short sentence would probably do the trick.

Maybe here - https://flutter.dev/docs/get-started/codelab#next-steps
Something like - "Try deploying with [release mode](https://flutter.dev/docs/testing/build-modes) to see the performance you can get from flutter"

**Comment by tvolkert** [comment]
@Sfshaza we've had other people report this feedback informally as well.

**Comment by tvolkert** [comment]
Correct user handle: @sfshaza2

**Comment by sfshaza2** [comment]
Fixed.

**Comment by alistairsykes** [comment]
Nice change. This should help make things much clearer for people just trying Flutter out.
