### ISSUE TITLE
Remove duplicate from macOS install 'Test drive' page

### ISSUE THREAD

**Issue by nfortescue** [flutter/website#2591]
Page URL: https://flutter.dev/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Description of issue:
When working through the getting started exercises, the very first thing you do is try out flutter via "flutter create my_app".

Then in the very next section (this page) you are told to create a project again using IntelliJ / AndroidStudio. It might have been nice to have had the option to import the project you created in step 1.

**Comment by atsansone** [comment]
Remove [this section](https://docs.flutter.dev/get-started/install/macos#create-and-run-a-simple-flutter-app) from macOS install page.
