### ISSUE TITLE
Add MediaQuery widget to 'Navigate to a new screen and back' page example

### ISSUE THREAD

**Issue by vijayvedula** [flutter/website#2592]
Page URL: https://flutter.dev/docs/cookbook/navigation/navigation-basics.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/navigation-basics.md

Description of issue: While running this demo, Media Query object is required to be created.

**Comment by atsansone** [comment]
MediaQuery is not needed for a route cookbook example. Closing.
