### ISSUE TITLE
Remove `cached_network_image` from 'Working with cached images' page

### ISSUE THREAD

**Issue by marcosgallardo** [flutter/website#2593]
### Page URL

https://docs.flutter.dev/cookbook/images/cached-images/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/images/cached-images.md

### Description of issue:

The plugin [`cached_network_image`](https://pub.dartlang.org/packages/cached_network_image#-readme-tab-) has being updated and the code no longer works with the latest version.

**Comment by bus710** [comment]
Found the same one.

**Comment by atsansone** [comment]
Duplicates https://github.com/flutter/website/issues/8324. Closing.
