### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by cneilmon** [flutter/website#2595]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:

Download of Flutter SDK unavailable.

**Comment by sfshaza2** [comment]
@cneilmon, are you still having problems? I just went to that page and am able to download the Flutter SDK, though I am on a Mac and can't run it. If it's still happening to you, please paste the output of "flutter doctor" in a comment.

**Comment by cneilmon** [comment]
@sfshaza2, just checked it now, and its already fixed, though haven't tried it before using Mac because i'm using Windows and Linux and both of them shows (failed). Nevertheless, seems fine now.

**Comment by sfshaza2** [comment]
Also see https://github.com/flutter/website/issues/3982
