### ISSUE TITLE
Missing link for "Issue 18494" at /docs/deployment/android.md

### ISSUE THREAD

**Issue by medvedev** [flutter/website#2596]
Link "Issue 18494" is empty at https://github.com/flutter/website/blob/master/src/docs/deployment/android.md
Probably, it should point to https://github.com/flutter/flutter/issues/18494

**Comment by legalcodes** [comment]
Thanks! Fixed here: https://github.com/flutter/website/commit/4938a8c7bba0a6440420c2d3fd1371ce7f1801a0
