### ISSUE TITLE
flutter logo is png inside an svg :)

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/website#2601]
https://flutter.dev/assets/flutter-lockup-4cb0ee072ab312e59784d9fbf4fb7ad42688a7fdaea1270ccf6bbf4f34b7e03f.svg

The twitters complained:
https://twitter.com/flyin1501/status/1119170219157536768

**Comment by eseidelGoogle** [comment]
FYI @Sfshaza @kwalrath  :)

**Comment by jamesderlin** [comment]
I think this is https://github.com/flutter/website/issues/1755 ?

**Comment by maguinis** [comment]
Strange.. our logos can be found here: https://drive.google.com/corp/drive/folders/1NWJGmv_j9f0HEVWYi0NAEUPzu2l0Verp

We have a .png version on that folder that should clean this up. If it doesn't, I can create a new one.

**Comment by legalcodes** [comment]
I've raised https://github.com/flutter/website/pull/3540 that uses the .png version
