### ISSUE TITLE
'Place a floating app bar above a list' page issue

### ISSUE THREAD

**Issue by Krishnaflutter** [flutter/website#2606]
Page URL: https://flutter.dev/docs/cookbook/lists/floating-app-bar.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/lists/floating-app-bar.md

Description of issue:

**Comment by sfshaza2** [comment]
@Krishnaflutter, can you describe the problem?

**Comment by sfshaza2** [comment]
Closed due to lack of info.
