### ISSUE TITLE
'Firebase' page issue

### ISSUE THREAD

**Issue by merarischroeder** [flutter/website#2607]
Page URL: https://flutter.dev/docs/development/data-and-backend/firebase.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/firebase.md

Description of issue:

This page needs to clearly state that the firebase/flutter libraries are NOT complete nor production ready. 

It says: 

"Firebase is a Backend-as-a-Service (BaaS) app development platform that provides hosted backend services such as a realtime database, cloud storage, authentication, crash reporting, machine learning, remote configuration, and hosting for your static files." ... "Firebase supports Flutter."

This is misleading. 

On the referenced plugin page [https://github.com/flutter/plugins/blob/master/FlutterFire.md] it states "The plugins are still under development, and some APIs might not be available yet". I count only 4 out of 14 are >= 1.0

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/2763
