### ISSUE TITLE
Include Cupertino examples in 'Navigate to a new screen and back' page

### ISSUE THREAD

**Issue by xster** [flutter/website#2616]
Add some Cupertino concepts in there. Maybe in various parts of the page, have side by side columns when they behave differently.

**Comment by sfshaza2** [comment]
@miquelbeltran, please review

**Comment by miquelbeltran** [comment]
A page showcasing different Cupertino style widgets exist https://docs.flutter.dev/ui/widgets/cupertino and there is this codelab: https://codelabs.developers.google.com/codelabs/flutter-cupertino#0, but as far as I can see, there is no cookbook recipe that shows how to create a Cupertino style app.

So I think creating at least a cookbook recipe that shows how to build a Cupertino (iOS style) app under the Design category would be good.

I think that the coobook recipe should specially show things like `CupertinoAlertDialog`, `showCupertinoDialog`, `CupertinoActionSheet`, etc.

Another option is creating a whole section dedicated to CupertinoApp under https://docs.flutter.dev/ui/design just as Material Design has one.

**Comment by miquelbeltran** [comment]
Regarding specifically the "Navigate to a new screen and back" recipe: https://docs.flutter.dev/cookbook/navigation/navigation-basics

Yes, I think that adding a second example at the end of the recipe showing how to do it for Cupertino apps would be beneficial. I will submit a PR with a proposal.

**Comment by miquelbeltran** [comment]
With #9202 we can mark this as resolved
