### ISSUE TITLE
Fix JS function syntax in 'Flutter for React Native Developers' page

### ISSUE THREAD

**Issue by mirkancal** [flutter/website#2620]
relevant part of the article: [async and await](https://docs.flutter.dev/get-started/flutter-for/react-native-devs#async-and-await)

There is a JavaScript function example in this section:

```javascript
// JavaScript
async _getIPAddress() {
  const url="https://httpbin.org/ip";
  const response = await fetch(url);
  const json = await response.json();
  const data = await json.origin;
  console.log(data);
}
```

I'm not JavaScript expert but I couldn't run it on chrome, babeljs.io, jsbin.

I think these are the correct ways to go

```javascript
let _getIPAddress = async () => {
  const url="https://httpbin.org/ip";
  const response = await fetch(url);
  const json = await response.json();
  const data = await json.origin;
  console.log(data);
}
```

or 

```javascript
async function _getIPAddress() {
  const url="https://httpbin.org/ip";
  const response = await fetch(url);
  const json = await response.json();
  const data = await json.origin;
  console.log(data);
}
```

**Comment by micpap25** [comment]
Looks like this was fixed with the second option, it can be closed.

**Comment by atsansone** [comment]
This was fixed in:
- https://github.com/flutter/website/pull/2624
- https://github.com/flutter/website/pull/2979
- https://github.com/flutter/website/pull/4070

Closing this issue.
