### ISSUE TITLE
Search on flutter.dev shows flutter.io links

### ISSUE THREAD

**Issue by filiph** [flutter/website#2622]
Search on flutter.dev finds articles on flutter.io. (Try https://flutter.dev/search?q=routes.)

<img width="498" alt="Screen Shot 2019-04-30 at 12 28 35 PM" src="https://user-images.githubusercontent.com/919717/56987881-7fa4d300-6b43-11e9-8228-65bc745ef0dc.png">

This is mostly a cosmetic issue since these links correctly redirect back to .dev.

cc @sfshaza2

**Comment by sfshaza2** [comment]
Fixed the custom search list. (Not in a PR.)
