### ISSUE TITLE
'Windows install' page issueflutter' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by Apoorva-Singh-110** [flutter/website#2633]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by sfshaza2** [comment]
Closed for lack of description.
