### ISSUE TITLE
'Write your first Flutter app, part 1' page issue

### ISSUE THREAD

**Issue by badjem79** [flutter/website#2638]
Page URL: https://flutter.dev/docs/get-started/codelab.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

in the first copy paste example I had to add "new" in front of MaterialApp, Scaffold, AppBar and Text, as the sintax highligter marked em as wrong without "new"

**Comment by JosephineAkello** [comment]
@badjem79  kindly redescribe the above issue once more, cause as much as I know adding  the **new** keyword before constructors is optional according to Dart 2, so placing **new** or not the **new** keyword placing the code will still execute successfully. Kindly refer to [https://dart.dev/guides/language/effective-dart/usage#dont-use-new](url)

**Comment by sfshaza2** [comment]
@badjem79, @JosephineAkello is correct. Adding "new" (and sometimes "const") is optional in Dart 2. This suggests that you haven't upgraded your Flutter version. I'm going to close this issue, but please reopen after you've upgraded and you're still seeing the issue.
