### ISSUE TITLE
mistake in codelab 'Building a Cupertino app with Flutter'

### ISSUE THREAD

**Issue by yueban** [flutter/website#2660]
There is a mistake in codelab ['Building a Cupertino app with Flutter' step 4](https://codelabs.developers.google.com/codelabs/flutter-cupertino/index.html?index=..%2F..index#4). As I highlight with red rect below:
![image](https://user-images.githubusercontent.com/5647837/57583895-e80e8f80-7507-11e9-882e-28f7de5c9d0f.png)

It will cause build failed, and it should be `builder: (context) => AppStateModel()..loadProducts(),` as the [source code](https://github.com/googlecodelabs/flutter-cupertino-store/blob/master/step-01/lib/main.dart#L30) shows.

**Comment by sfshaza2** [comment]
Subsumed by https://github.com/flutter/website/issues/4026
