### ISSUE TITLE
Step 2b: Add Android platform code (.java/.kt)

### ISSUE THREAD

**Issue by j3g** [flutter/website#2662]
Page URL: https://flutter.dev/docs/development/packages-and-plugins/developing-packages.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/packages-and-plugins/developing-packages.md

Description of issue:
In Section "Step 2b: Add Android platform code (.java/.kt)" please change the following:

"Before editing the Android platform code in Android Studio..."
This step is not necessary anymore. .idea folder and other artifacts are generated by flutter create command.

"2. Select 'Import project' "
I receive an error when trying to import from the build.gradle file. I states "Cannot Import Project, The project file specified already exists. Instead you just open the project from that build.gradle file. "open existing project" 

These steps can be produced by simply running:
1. $ flutter create --org com.example --template=plugin hello
2. "open existing project" in Android Studio from .hello/example/android/build.gradle

**Comment by micpap25** [comment]
Fixing this right now, although just want to note that at least for me with the newest version of Flutter (1.20.2) you have to add `--platforms android` to your first step to reproduce this.
