### ISSUE TITLE
'Return data from a screen' page issue

### ISSUE THREAD

**Issue by javiermrz** [flutter/website#2663]
Page URL: https://flutter.dev/docs/cookbook/navigation/returning-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/returning-data.md

Description of issue: I think the GIF example at the end of the page is quite bugged. It gets stucked in Navigator.pop and doesn't show the snackbar at any moment.

**Comment by sfshaza2** [comment]
Yes, this does look wrong.

**Comment by brianegan** [comment]
Oh boy, not sure how these Navigation gifs got all out of sorts! I've just submitted a fixed gif.
