### ISSUE TITLE
Homepage Hero Animation: Change text and icon

### ISSUE THREAD

**Issue by maguinis** [flutter/website#2672]
2 things...

1) Change text from "Publish iOS and Android apps" on the fourth carousel to "Publish mobile, web, and desktop apps"

2) The "Productively build apps" carousel has app building in 2000+ milliseconds in the background image. Change that to something like 347 milliseconds.

**Comment by maguinis** [comment]
I have created the new milisecond image here: 

![slide_2-layer_1-e3ae5249f3b2dc28e7c8cb92737ec97ad4754870b97805f4872f72ea9e85a18c_v2](https://user-images.githubusercontent.com/9119454/58061237-2f110c00-7b2a-11e9-938d-a45949c9b3f2.png)

Can you please help update it, Shams. the old one is called "slide_2-layer_1-e3ae5249f3b2dc28e7c8cb92737ec97ad4754870b97805f4872f72ea9e85a18c"

**Comment by sfshaza2** [comment]
OMG, @maguinis, such a fetching nane.  ;)   Sure.

**Comment by sfshaza2** [comment]
PR:  https://github.com/flutter/website/pull/2696

**Comment by sfshaza2** [comment]
Fixed: https://github.com/flutter/website/pull/2696
