### ISSUE TITLE
'Debugging Flutter apps' page issue

### ISSUE THREAD

**Issue by JosephineAkello** [flutter/website#2673]
Page URL: https://flutter.dev/docs/testing/debugging.html
Page source: https://github.com/flutter/website/tree/master/src/docs/testing/debugging.md

Description of issue: Under **measuring app startup time,** that helps to gather information about the time one's app takes to start, with command  **flutter run --trace-startup --profile**. If your running your application on an emulator it outputs an error with " **Profile mode is not supported for emulators**". I think this issue should be sorted so that it captures all scenarios with various devices connected.

![Screenshot from 2019-05-16 10-22-00](https://user-images.githubusercontent.com/39112051/57834729-998e1900-77c5-11e9-9402-2e0c4008445a.png)

**Comment by sfshaza2** [comment]
Hi @JosephineAkello. Yes, it would be nice to be able to run Profile mode in the emulator/simulator, but the behavior is very different than a physical device. There are no plans to change that but, if you want to register your opinion, please open a bug on the flutter/flutter repo.
