### ISSUE TITLE
Translate Flutter.dev into Korean

### ISSUE THREAD

**Issue by techhtml** [flutter/website#2676]
Hi There,
This is Eun from South Korea (and I am Google Developers Experts on Web Technology)

I start to translate flutter.dev into Korean.
https://flutter-ko.dev/docs

This issue is for if someone wants to join the translation,
Tell me and I will add you to the repository.
https://github.com/techhtml/website

Thank you!

**Comment by sfshaza2** [comment]
This is great, @techhtml!

**Comment by TroyTae** [comment]
@sfshaza2 
I created similar issue in the past.
And I thought that flutter website team has plan to support multilanguage. (https://github.com/flutter/website/issues/1186#issuecomment-415633676)
Maybe I'm misunderstood? 😱

**Comment by techhtml** [comment]
Hi @TroyTae, This is Eun from maintaining Korean site and I already saw your last Issues.
As far as I know, the Flutter team have many problems there own, I know It is perfect that Site will fully support multiple languages.

But I think the Flutter team is now busy :( , but I want to the Korean version.
So I just start to translate Flutter site into Korean. 

If they will support multiple languages,
I will integrate my repository to Flutter's repository.

**Comment by TroyTae** [comment]
Oh I see, I worried that the code would continue to be committed while we translated.
So I waited supporting multilanguage...
But if there are many people who wants korean version, I want to participate in too!
Especially user interface section :)

**Comment by TroyTae** [comment]
Hello @techhtml , I worried that the code would continue to be committed while we translated.
So I waited supporting multilanguage...
But if there are many people who wants korean version, I want to participate in too!
Especially user interface section :)

**Comment by techhtml** [comment]
Great! @TroyTae 

You can see the repository in this link:
https://github.com/techhtml/website

You pick up issues and translate it!
Good luck!

**Comment by sfshaza2** [comment]
So glad to see the community working together! No, we do not (currently) have plans for a multi-language Flutter site.

**Comment by booiljung** [comment]
I am happy to have a Korean repository for flutter. These are the documents I have translated. I will upload it. https://booiljung.github.io/technical_articles/flutter/

**Comment by sfshaza2** [comment]
Fabulous, @booiljung!

**Comment by TroyTae** [comment]
Change Log:
Repository is moved from https://github.com/techhtml/website to https://github.com/flutter-ko/website

**Comment by bro-jo** [comment]
#2725
