### ISSUE TITLE
'An introduction to unit testing' page issue

### ISSUE THREAD

**Issue by timsneath** [flutter/website#2683]
Page URL: https://flutter.dev/docs/cookbook/testing/unit/introduction.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/unit/introduction.md

Description of issue:
This article caused me some confusion, since it makes some assumptions about unit testing in Flutter. 

It's written in the context of a file that contains no Flutter dependencies, so it focuses on `package:test`. Unfortunately that causes various challenges in a Flutter project -- since the default dependency is on `flutter_test`. At least for my own code, importing `package:test` alone was problematic because my class relies on access to the Flutter SDK. 

See https://github.com/timsneath/cambridge/blob/master/spectrum/test/fuse_z80_opcode_test.dart for an example of a set of tests that require `flutter_test`.

**Comment by brianegan** [comment]
Hi @timsneath -- thanks for the report! Ah, this is an interesting one!

There was a brief time when the `flutter_test` package was undergoing changes and did not export all of the same functionality as the `test` package itself. It seems like those issues have now been resolved!

In fact, if you look at the file history, we used to have this paragraph in the first step:

```
If you're working on a package that will only be used for Flutter apps, or if
we need to write Widget tests, depend on the `flutter_test` package instead.
It includes everything from the `test` package, as well as
additional utilities for testing Widgets.

    dev_dependencies:
      flutter_test:
      sdk: flutter
```

Do you think we should add that paragraph back in, or is it a bigger issue with the page?

**Comment by sfshaza2** [comment]
@timsneath, ancient history, but what do you think of @brianegan's suggestion?

**Comment by timsneath** [comment]
We took it offline, I think. Just pinged you the history.

**Comment by sfshaza2** [comment]
Great! Closing this.
