### ISSUE TITLE
'Using Themes to share colors and font styles' page issue

### ISSUE THREAD

**Issue by jithinlal** [flutter/website#2688]
Page URL: https://flutter.dev/docs/cookbook/design/themes.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/themes.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
Seems like the code is wrong. The yellow floatingactionbutton doesn't work

**Comment by nadavkaner** [comment]
We can close this ticket
