### ISSUE TITLE
Suggestion: move package interdependencies conflict resolution section to page on using packages

### ISSUE THREAD

**Issue by MaikuB** [flutter/website#2689]
Currently there is a page that deals with handling conflicts within various packages [here](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#conflict-resolution). Whilst some of the content there may be applicable to package developers, the content is likely more relevant to consumers of packages. The [using packages](https://flutter.dev/docs/development/packages-and-plugins/using-packages) page doesn't have a section that would provide that kind of guidance to such developers. One suggestion would be that the conflict resolution could be moved to the using packages page, or the using packages page could include a section and link that would take the user to https://flutter.dev/docs/development/packages-and-plugins/developing-packages#conflict-resolution

I'd be happy to submit a PR for this but wanted to start a discussion to get some thoughts on this beforehand

**Comment by sfshaza2** [comment]
@MaikuB, this is an excellent suggestion. I just reviewed the using-packages page, and it's a bit rough, in general. If you'd like to file a PR to move the conflict info to using-packages, that would be great.

**Comment by sfshaza2** [comment]
Thanks, again, @MaikuB!

**Comment by MaikuB** [comment]
No worries though I noticed an issue as part of my amendments. This should be addressed as part of a new PR I've created [here](https://github.com/flutter/website/pull/2698). Apologies about that.
