### ISSUE TITLE
Support multiple languages

### ISSUE THREAD

**Issue by techhtml** [flutter/website#2694]
Hi There,
This is Eun from South Korea.

As far as I know, the Flutter team is now considering to support multiple languages on the sites, But I didn't find an issue.

Does anybody know about this plan?
If the Flutter team don't have a plan yet, I will help you to build a multiple language version.

Thank you.

**Comment by sfshaza2** [comment]
Hi, @techhtml! A multiple language site is not in our plans for now. The way it stands is that community members are creating and sharing translated versions of the site, hosted elsewhere. I'm aware of a Chinese version (Mandarin, I think), and a Spanish version. It would be great to have a Korean version, too!
