### ISSUE TITLE
'List of state management approaches' page issue

### ISSUE THREAD

**Issue by kevmoo** [flutter/website#2697]
Page URL: https://flutter.dev/docs/development/data-and-backend/state-mgmt/options.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/state-mgmt/options.md

We tell folks to use `package:provider`, but doing a CMD-F on the page for `provider` yields...nothing.

Shouldn't we link to the package? Maybe the @mjohnsullivan & @filiph I/O talk?

**Comment by filiph** [comment]
Good point, I'm taking this.

**Comment by sfshaza2** [comment]
Filip has fixed this. Closing.
