### ISSUE TITLE
Continuous delivery options

### ISSUE THREAD

**Issue by MaikuB** [flutter/website#2699]
The deployment section has a page on doing [continuous delivery with fastlane](https://flutter.dev/docs/deployment/fastlane-cd). There are other options that listed at https://flutter.dev/docs/testing#continuous-integration-services that readers may not think to check when looking for options and jump straight to the fastlane guide.

Could potentially rename the continuous delivery page to omit fastlane from the title and change the structure to be as follows

```
fastlane
--- Local setup
--- Running deployment locally
--- Cloud build and deploy setup
--- Reference

Other services
```

The `Other services` section would have the some of the bullet points from https://flutter.dev/docs/testing#continuous-integration-services in that it would list Gitlab CI/CD, Codemagic and Bitrise.

Thoughts on that?

**Comment by sfshaza2** [comment]
Makes sense.

**Comment by MaikuB** [comment]
Closing this since the PR for these changes have been merged
