### ISSUE TITLE
Typo in `Flutter for Xamarin.Forms devs`

### ISSUE THREAD

**Issue by garyng** [flutter/website#2701]
Page URL: https://flutter.dev/docs/get-started/flutter-for/xamarin-forms-devs.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/flutter-for/xamarin-forms-devs.md

Description of issue:

Under [How do I navigate between pages?](https://flutter.dev/docs/get-started/flutter-for/xamarin-forms-devs#how-do-i-navigate-between-pages)

> In Xamarin.Forms, you navigate between pages normally through a, you can use a `NavigationPage` that manages the stack of pages to display.

... normally through a _what_ :rofl: ?

**Comment by sfshaza2** [comment]
LOL. I don't know!

**Comment by sfshaza2** [comment]
Fixed in this PR:  https://github.com/flutter/website/pull/2744
