### ISSUE TITLE
Document how add-to-app affects Android deployment model

### ISSUE THREAD

**Issue by tvolkert** [flutter/website#2704]
https://flutter.dev/docs/deployment/android will need to be updated per our work on https://github.com/flutter/flutter/issues/31922 and https://github.com/flutter/flutter/issues/18494.

Specific questions that we should answer:

* [X] When do I use `flutter build appbundle` versus `flutter build apk —target-platform android-arm,android-arm64`?
* [X] How do I sign the app bundle created by `flutter build appbundle`?
* [ ] Are there any special considerations with add-to-app?
* [X] How do I use this from within Android Studio?
* [X] What are the supported architectures (e.g. android-arm, android-arm64, x86, x86_64)?

**Comment by tvolkert** [comment]
/cc @blasten @sfshaza2 

FYI @xster @matthew-carroll

**Comment by sfshaza2** [comment]
@tvolkert @blasten @xster @matthew-carroll, I'm happy to tackle this, but where are these questions answered?

**Comment by angel1st** [comment]
@tvolkert - re the above questions, what about adding this one as well "How to provide a fat apk file?". I guess this should include a final summary of [flutter build apk` should include libflutter.so for both 32bit and 64bit architectures](https://github.com/flutter/flutter/issues/18494) when it is closed...

**Comment by xster** [comment]
@blasten, are you drafting a change on flutter/website for shams to review?

**Comment by tvolkert** [comment]
@blasten and I met with @sfshaza2 last Friday to go over these answers in person.  @sfshaza2 is going to send a draft for review.

**Comment by sfshaza2** [comment]
I've updated this page. It now answers all questions, except for add to app. We're not ready to address that one yet.

PR https://github.com/flutter/website/pull/2754

**Comment by angel1st** [comment]
@sfshaza2 - I would definitely touch `versionCode` topic when it comes to [Build APK case](https://sz-flutter.firebaseapp.com/docs/deployment/android#build-an-apk). Looking at [the explanation](https://github.com/flutter/flutter/issues/18494#issuecomment-501591593) it shouldn't be much of a work to be added.

**Comment by sfshaza2** [comment]
@xster, can we answer the add-2-app question now? I'm happy to update the page.

**Comment by sfshaza2** [comment]
@tvolkert, I've been reading some issues and am not sure. Do we still need to touch on versionCode?

**Comment by tvolkert** [comment]
@sfshaza2, @xster has been OOO but is coming back online over the next few weeks.  I defer to him on whether there's any more update needed here.

**Comment by xster** [comment]
Nothing left to do here. All 32/64 bit support are already done on the way in during the add-to-app integration steps of the project setup. We haven't heard of any issues from our users currently. We can clarify more based on user feedback as needed.
