### ISSUE TITLE
Flutter channel youtube

### ISSUE THREAD

**Issue by Medpy** [flutter/website#2717]
Hey brother's I want update this serie [•] on my channel and translate it but I want send request to flutter developper if i can do it !  
[•]https://www.youtube.com/playlist?list=PLjxrf2q8roU23XGwz3Km7sQZFTdB996iG

**Comment by RedBrogdon** [comment]
That's a great suggestion, but our process with the Google Developer Studio isn't set up for moving content to other channels.

Don't let that stop you if you're interested in creating content in your language to help other flutter developers, though! You can get a screencasting tool like Camtasia, record your own videos, and create your own Widget of the Week series. Pawan Kumar (whom you may have seen as a guest on the Boring Show) does some in Hindi, for example:

https://www.youtube.com/watch?v=smMiyjRm208&list=PLR2qQy0Zxs_VgLsyzACFg-NPsxu8CCWzZ

**Comment by Medpy** [comment]
ok i will do i,  thank you Sir

‫في الاثنين، 10 يونيو 2019 في 6:53 م تمت كتابة ما يلي بواسطة ‪Andrew
Brogdon‬‏ <‪notifications@github.com‬‏>:‬
