### ISSUE TITLE
'Linux install' page issue

### ISSUE THREAD

**Issue by SquatchRage** [flutter/website#2723]
Page URL: https://flutter.dev/docs/get-started/install/linux.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/linux.md

Description of issue:

There is no link to download SDK.  It states the button is loading, then lists it as "Failed"
If you click on it, it does nothing.

**Comment by sfshaza2** [comment]
Hi, @SquatchRage! This is definitely not something we're seeing here. Can you tell us more about your environment? For example:

- What platform are you using?
- What version of that platform?
- Which browser?
- Are you behind a firewall?

If you are behind a firewall, can you try it while not behind that firewall? Include the output from `flutter doctor` and let's see if we can figure out what's going on. (Also, do you still see the problem?)

**Comment by sfshaza2** [comment]
Closing due to lack of info. If you see this again, please re-open the bug and provide more info.
