### ISSUE TITLE
Link to samples from 'Flutter for web' page

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#2730]
Page URL: https://flutter.dev/web.html
Page source: https://github.com/flutter/website/tree/master/src/web.md

Description of issue:

I was looking for a link to https://flutter.github.io/samples/ on this page but couldn't find one. I ended up doing a Google search. Could we put a link to the web samples in this page? Thanks!

**Comment by sfshaza2** [comment]
PR https://github.com/flutter/website/pull/2742
