### ISSUE TITLE
'Layouts in Flutter' page issue

### ISSUE THREAD

**Issue by JosephineAkello** [flutter/website#2731]
Page URL: https://flutter.dev/docs/development/ui/layout/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/layout/index.md

Description of issue:
The grid view example in layouts in Flutter Section has its documentation wrote with "//" double slashes which is against ***Effective Dart*** lint rules that recommend the use of "///" or "/** ... */" when providing documentation example in Dart/Flutter. [https://dart.dev/guides/language/effective-dart/documentation](url) [https://dart-lang.github.io/linter/lints/slash_for_doc_comments.html](url)

**Comment by sfshaza2** [comment]
Hi, @JosephineAkello! Actually, both '//' and '///' are legal comments. The difference is, say you are writing a package that others will use. For comments that you want included in the generated doc, such as describing a method, class, or field, use the '///' form. This tells the dartdoc tool to add this comment when it generates the docs. Use the '//' form for other comments.

This code is not created as part of a package or library, so it uses the '//' form.

Closing.
