### ISSUE TITLE
flutter-announce should be more aggressively mentioned

### ISSUE THREAD

**Issue by Hixie** [flutter/website#2732]
I couldn't find a mention of the flutter-announce mailing list anywhere on the Web site.

We really should be pushing this more aggressively since it's where we post our breaking change announcements. Right now there's only ~300 subscribers.

**Comment by sfshaza2** [comment]
Good point. I added a Flutter Friday tip about this.

**Comment by sfshaza2** [comment]
I did add a Flutter Friday tip about this, which caused a small surge in membership. I've also added a note to the /docs and Docs archive pages.

https://github.com/flutter/website/pull/2763
