### ISSUE TITLE
'Test drive' page issue

### ISSUE THREAD

**Issue by datafoya** [flutter/website#2743]
Page URL: https://flutter.dev/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Description of issue:

I'm following the instructions for Write Your First Flutter App, Part 1 and came across a step not mentioned in the process. 

In the section Create the App, step 4 directs users to enter "a project name (for example, myapp)" and then  click "Next."

Step 5 then directs users to click finish, thus enabling Android Studio to install the Flutter SDK?I'm not sure if this step is referring to step 3. However, in Android Studio, I had the option to set the package name by entering a company domain and package name. Because the instructions at the above link don't mention this option, I just clicked finish. 

Is entering a company domain and package name optional? Should there be an additional step or issue covering this option in Android Studio? 

I'd be happy to write something about this option soon, once I learn more about Flutter and its processes. 

**Update:** I found entering a company domain is an option some Flutter IDE plugins ask users (depends on if the app is going to be released). Anyway, I'll be editing this page after writing my first app; I think many new users, not just to creating apps, but to coding/programming as well, will be confused here. And I think the answers to my earlier questions should be on this page with these steps.

**Comment by micpap25** [comment]
Looks like this has been resolved with a note under the instructions, this can be closed.

**Comment by parlough** [comment]
Thanks for opening an issue!

A note explaining the package name and some related suggestions has been added to the page in https://github.com/flutter/website/pull/2951
