### ISSUE TITLE
'MacOS install' page issue

### ISSUE THREAD

**Issue by larsroettig** [flutter/website#2745]
Page URL: https://flutter.dev/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Description of issue:

For the most developer, it is better to have an ``wget`` or ``curl`` command to download and unzip 

**Like:** 

1. Download the following installation bundle to get the latest stable release of the Flutter SDK:
```
cd ~/workspace 
wget https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_latest.zip
unzip flutter_macos_latest.zip
```

or :

```
cd ~/workspace 
curl -O https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_latest.zip
unzip flutter_macos_latest.zip
```

**Comment by larsroettig** [comment]
Hi @sfshaza2, 
it will be okay if am open for that a Pull request or this will be also closed?

**Comment by micpap25** [comment]
It seems that the process to install Flutter has changed significantly since this issue was created.
I think it can be closed on the merit that it no longer applies unless I'm mistaken.

**Comment by sfshaza2** [comment]
Good catch, @micpap25! Closing.
