### ISSUE TITLE
'Add a Drawer to a screen' page issue

### ISSUE THREAD

**Issue by Ransaka** [flutter/website#2756]
Page URL: https://flutter.dev/docs/cookbook/design/drawer.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/drawer.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by sfshaza2** [comment]
Closed for lack of info.
