### ISSUE TITLE
'Set up an editor' page issue

### ISSUE THREAD

**Issue by LabGecko** [flutter/website#2759]
Page URL: https://flutter.dev/docs/get-started/editor.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/editor.md

Description of issue:
Instructions in section "Install the Flutter and Dart plugins" is worded oddly. The OS should be listed first, then steps for that OS.

**Comment by sfshaza2** [comment]
Hi, @LabGecko! The previous page ( https://flutter.dev/docs/get-started/install ) and titled "Step 1: Install", has information on how to install for your OS. This page, "Step 2: Set up an editor" has info on how to set up Android Studio/IntelliJ and VS Code, if you want to use those.

So, your comment confuses me. The OS is installed first. Can you clarify?

**Comment by LabGecko** [comment]
Section: "Install the Flutter and Dart plugins"

Currently #2 reads:
2. Open plugin preferences (Preferences > Plugins on macOS, File > Settings > Plugins on Windows & Linux).

It should read:
2. Open plugin preferences (on MacOS go to Preferences > Plugins; on Windows & Linux go to File > Settings > Plugins ).
