### ISSUE TITLE
'Write your first Flutter app, part 1' page issue

### ISSUE THREAD

**Issue by LabGecko** [flutter/website#2762]
Page URL: https://flutter.dev/docs/get-started/codelab.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab.md

Description of issue:
Adding code in Step 3 is confusing, inserting a logically separate step (RandomWords) between two logically similar steps (RandomWordsState).

**Comment by sfshaza2** [comment]
Fixed.
