### ISSUE TITLE
Slightly different syntax for _suggestions / _biggerFont variables from Part 1 to Part 2

### ISSUE THREAD

**Issue by sammartinez** [flutter/website#2771]
In part one of the guide under [Create an infinite scrolling ListView](https://flutter.dev/docs/get-started/codelab#step-4-create-an-infinite-scrolling-listview), I am seeing the `_suggestions` / `_biggerFont` is written slightly different than in [part two](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#3). It's not causing any breaking changes going through the tutorial but I can see it confusing someone down the way going from part one to part two.

**Comment by parlough** [comment]
This codelab has been superseded by [Your first Flutter app](https://codelabs.developers.google.com/codelabs/flutter-codelab-first) which shouldn't have this issue due to not having separate parts.

Thanks for opening the issue!
