### ISSUE TITLE
Work with WebSockets article needs a url update

### ISSUE THREAD

**Issue by mirkancal** [flutter/website#2780]
ws://echo.websocket.org should be wss://echo.websocket.org in the article in order to Complete Example to work.

https://flutter.dev/docs/cookbook/networking/web-sockets#complete-example

**Comment by brianegan** [comment]
Hey there -- just tested the example on a new Flutter project and it seems to be working as intended. Is the example failing on your end?

**Comment by sfshaza2** [comment]
Closing.
