### ISSUE TITLE
'Test drive' page issue

### ISSUE THREAD

**Issue by devpikachu** [flutter/website#2786]
Page URL: https://flutter.dev/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Description of issue:
Add a reference to https://github.com/flutter/flutter/issues/33050 mentioning that hot reload doesn't work on Android API 29, to avoid panic and confusion.

**Comment by sfshaza2** [comment]
@tvolkert, this issue has been fixed. Do you feel we still need a note in the test drive page?

**Comment by tvolkert** [comment]
Nope
