### ISSUE TITLE
'Developing packages create command line doesnt work on kotlin with androidX

### ISSUE THREAD

**Issue by monmonja** [flutter/website#2791]
Page URL: https://flutter.dev/docs/development/packages-and-plugins/developing-packages.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/packages-and-plugins/developing-packages.md

Description of issue: if you are creating a plugin with kotlin and androidX, the create plugin command line like
`flutter create --org com.example --template=plugin -i swift -a kotlin logger` doesnt seem to work.
Just start that command line and import it on your main project and just run it without modifying anything and it would shows
`To determine what is calling variant.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.`
turns out this is due to kotlin version by default it uses ext.kotlin_version = '1.2.71'
i fixed it by using ext.kotlin_version = '1.3.31'

**Comment by sfshaza2** [comment]
@tvokert, can you confirm?

**Comment by sfshaza2** [comment]
@tvolkert, can you confirm? I spelled your login wrong before.

**Comment by tvolkert** [comment]
@amirh @matthew-carroll

**Comment by amirh** [comment]
I tried to reproduce this by creating a Kotlin app that's using Kotlin 1.3.31, migrate it to AndroidX, and have it depend on a plugin that uses Kotlin 1.2.71 but nothing broke. Not sure what am I missing.

Can you share a minimal project that reproduces the breakage, ideally just `flutter create --template=plugin -a kotlin repro` and get the example app to break by upgrading it's Kotlin version? it will make it easier for us if you make one commit with the plugin template and another commit with the minimal changes needed to get it to break and post it on GitHub.

**Comment by sfshaza2** [comment]
Closing.
