### ISSUE TITLE
'Fetch data from the internet' page issue

### ISSUE THREAD

**Issue by plaporte** [flutter/website#2793]
Page URL: https://flutter.dev/docs/cookbook/networking/fetch-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/fetch-data.md

Description of issue: The full example doesn't work. Just displays a continuous loading icon with no data rendering.

**Comment by petermichaux** [comment]
I just tested the current full example by copying and pasting it exactly. It works as expected.

@sfshaza2 This issue can be closed.

**Comment by sfshaza2** [comment]
Thanks!
