### ISSUE TITLE
'Work with WebSockets' page issue

### ISSUE THREAD

**Issue by ashanc** [flutter/website#2795]
Page URL: https://flutter.dev/docs/cookbook/networking/web-sockets.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/web-sockets.md

Description of issue: Complete example not working
web socket url should be wss://echo.websocket.org/ then it works fine

**Comment by xpat** [comment]
> web socket url should be wss://echo.websocket.org/ then it works fine

@ashanc I couldn't get the example to work on Chrome with for Flutter web chrome, even after changing from ws to wss.  Interesting, without making the change, that is leaving it as it is in the docs with ws, it works if I run it as a Linux desktop app.

The error message I get when I run it as a Flutter web app on Chrome is as follows:

> Unsupported operation: Platform._version
> See also: 
> https://flutter.dev/docs/testing/errors

**Comment by atsansone** [comment]
URLs in [Step 1](https://docs.flutter.dev/cookbook/networking/web-sockets#1-connect-to-a-websocket-server) and [Complete example](https://docs.flutter.dev/cookbook/networking/web-sockets#complete-example) use `wss://`.

Closing issue as fixed.
