### ISSUE TITLE
'Simple app state management' page issue

### ISSUE THREAD

**Issue by udithv** [flutter/website#2808]
Page URL: https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/state-mgmt/simple.md

Description of issue:

provider package has been updated to 3.0.0 please take care

**Comment by sfshaza2** [comment]
Is the behavior of the example affected? Otherwise, the page appears to be fine, even for 3.0.

@filiph

**Comment by filiph** [comment]
I will update the example.

**Comment by filiph** [comment]
PR with fix: https://github.com/flutter/website/pull/2810

**Comment by sfshaza2** [comment]
Filip fixed this issue. Closing..
