### ISSUE TITLE
Redirect or fix links to /fastlane-cd

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#2809]
One of the top 2 404s for flutter.dev is /fastlane-cd/, which presumably should go to https://flutter.dev/docs/deployment/cd. According to https://github.com/flutter/website/issues/2382, the path used to be /docs/deployment/fastlane-cd.html.

If the links are coming from flutter.dev, then we might not need a redirect.

**Comment by MaikuB** [comment]
Note that the path was changed as part of my PR #2751. Don't believe I missed anything though as I did a search through the rest of the site and didn't any more references to the old path when making the change and ran the script that validates the site links as well. I'm guessing you are the 404s reported through analytics? I have noticed that it looks like https://flutter.dev/docs/deployment/fastlane-cd will redirect to https://flutter.dev/docs/deployment/cd. Perhaps it's already been addressed then?

**Comment by kwalrath** [comment]
There might be external links to https://flutter.dev/fastlane-cd. Whatever the cause, it is a big source of 404s.

**Comment by MaikuB** [comment]
Ah sorry, I see what you mean now

**Comment by MaikuB** [comment]
Created a PR for this. Apologies for the inconvenience that was caused

**Comment by kwalrath** [comment]
> Created a PR for this. Apologies for the inconvenience that was caused by the path change

I’m not sure it was your fault! But thanks for the PR.
