### ISSUE TITLE
'Creating flavors for Flutter' page issue

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/website#2811]
Page URL: https://flutter.dev/docs/deployment/flavors.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/flavors.md

Description of issue:

We've received feedback that the linked tutorials are out of date (at least for iOS):
https://twitter.com/inryaa/status/1147263187726884865
Suggestion #1. Flavouring iOS seems fiddly and Flutter doesn't have any official documentation but rather points to some outdated tutorials. https://flutter.dev/docs/deployment/flavors …. Moreover, there seems to be a bug with iOS flavours, which is still open since last year.

https://twitter.com/inryaa/status/1147432038066245633
Has anyone managed to have flavors on iOS? After the 5th tutorial out there that doesn't work, I'm thinking something is really wrong if it's so difficult to have something as basic. @r_FlutterDev @FlutterComm @FlutterLDN

**Comment by sfshaza2** [comment]
@xster, can you comment?

**Comment by xster** [comment]
I agree we should likely write our own official flavors guide. This is likely more of a full-app tooling concern (cc @zanderso). There are some add-to-app work currently planned but it's likely simpler since platform concerns (where flavors concerns arise) and flutter concerns are a bit more decoupled.

**Comment by zanderso** [comment]
I believe this should happen as part of @jonahwilliams' 'flutter assemble' effort: https://github.com/flutter/flutter/projects/35

**Comment by leighajarett** [comment]
We're investigating writing up our own official flavors guide as part of this issue, so going to close this one out 

https://github.com/flutter/website/issues/7364

**Comment by sfshaza2** [comment]
I don't understand why this issue was closed. This page will (ultimately) be replaced by @MiraMarshall's updated page. This bug should remain open until then.

**Comment by leighajarett** [comment]
Sorry I meant to close it as not planned (i.e. duplicate), since they were discussing the same ask. I thought it was easier to just have one open issue to track, but if you think it makes sense to keep them all open that's fine with me.

**Comment by sfshaza2** [comment]
Oh yes! In that case, we mark it as "duplicate" and add the URL of the
other (left open) bug. We definitely don't want multiple open bugs that are
the same, but we like to include the URL of the open bug so we can track
that info.

**Comment by parlough** [comment]
Our docs and guidelines around Flavors have been expanded with https://github.com/flutter/website/pull/7867. Going to close this as a result. Thanks all!

If anyone would like to see further documentation around flavors, please open a new issue with a more specific request.
