### ISSUE TITLE
Please link to the code of conduct more prominently on flutter.dev

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/website#2817]
Maybe in the footer?

https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md is the one we appear to have so far.

As the community grows I think it's good for us to continue to be intentional about fostering a kind, supportive community as much as we can.  The code of conduct is a small, but I think important, part of such.

I thought of this when I went looking for Fuchsia's this evening after seeing some negative behavior in a fuchsia-associated community.  My goal is to encourage Flutter-affiliated communities to see that the Flutter community at/around Google values supporting an inclusive/supportive community.

FWIW both Fuchsia and Flutter's code of conducts are easily findable with google.com.

Thoughts @Hixie @timsneath?

Python links from their (massive) nav-footer for example: https://www.python.org/, Ubuntu puts it under the "community" header: https://ubuntu.com/#community

**Comment by sfshaza2** [comment]
SG!

**Comment by timsneath** [comment]
Yeah, I'm good with that -- thanks for the suggestion. Although of course,
really where it needs to be is on the GitHub issue page, which we obviously
don't control. That's where I see the most behavior that edges up to the
line ("you are all dumb if you don't do XXXX").

**Comment by Hixie** [comment]
"you are all dumb if you don't do XXXX" is wildly past the line of our code of conduct (our CoC is stricter than most). Please notify me promptly if you see such behavior.

**Comment by kwalrath** [comment]
I just noticed (prepping for this morning's Humpday Q&A) that https://flutter.dev/community has no link to https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md. I'd expected to find it in the top paragraph, and can add it there if you like.

Currently it says:

> Below you'll find ways to get involved in the Flutter developer community as well as links to resources that can help answer your questions. If you're in China, read Using Flutter in China.

Maybe it should be something like this:

> Below you'll find ways to get involved in the Flutter developer community as well as links to resources that can help answer your questions. We expect all community spaces to be welcoming and respectful, as described in the [Flutter code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md).
> 
> If you're in China, read ...

**Comment by sfshaza2** [comment]
This is covered on our high-level page: https://flutter.dev/culture
