### ISSUE TITLE
cannot access website on mac osx (SEA - PH)

### ISSUE THREAD

**Issue by shierro** [flutter/website#2834]
Hi,

I'm new to flutter and i can't access the website. Can anyone help?

<img width="1136" alt="Screen Shot 2019-07-16 at 3 09 39 PM" src="https://user-images.githubusercontent.com/12129589/61273387-f7e27280-a7db-11e9-8918-3e0a7674a1c7.png">

**Comment by dejaime** [comment]
Hi, what is your DNS server? are you sure it is working? 

PS: looks like that date is wrong.

**Comment by shierro** [comment]
@dejaime yes thanks for noticing the date issue.

my original DNS is 8.8.8.8, 4.4.4.4
then i also tried removing it(so that ISP will provide)

both didn't work. Can you suggest a better DNS for me?

**Comment by sfshaza2** [comment]
I’m not sure what to suggest. We don’t seem to be having this problem elsewhere.

**Comment by shierro** [comment]
quite weird since my phone, connected to the same router can access the site. there's something going on with my laptop

**Comment by sfshaza2** [comment]
Closing.

**Comment by shierro** [comment]
for anyone that got here, here's how to do the trick:

- Go to /etc/resolver folder
- Remove file called dev
- done

source:
https://stackoverflow.com/questions/55375467/cant-access-flutter-dev-mac-os
