### ISSUE TITLE
'Fetch data from the internet' page issue, Post is a bad example class name for an HTTP example

### ISSUE THREAD

**Issue by dejaime** [flutter/website#2836]
Page URL: https://flutter.dev/docs/cookbook/networking/fetch-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/fetch-data.md

Hi,
I got pretty confused while reading the docs, with it doing post and get requests, until I realized post was actually  referring to a blog post or similar, not an HTTP post request. It was partially my fault for skipping a small portion of the page, but also due to the confusing name of the "Post" class.

Take the following code from the http example: 
```
FutureBuilder<Post>(
  future: fetchPost(),
  builder: (context, snapshot) {
    if (snapshot.hasData) {
      return Text(snapshot.data.title);
    } else if (snapshot.hasError) {
      return Text("${snapshot.error}");
    }

    // By default, show a loading spinner.
    return CircularProgressIndicator();
  },
);
```

Reading this, a beginner like me would assume this is doing a **post** request, due to `FutureBuilder<Post>` and `fetchPost()` (although fetch+Post did sound kind of weird). Still, `fetchPost` actually executes a **get** request.

I'd propose renaming Post to something like BlogPost, to make it a tad more clear. The example would then read something like this:
```
FutureBuilder<BlogPost>(
  future: fetchBlogPost(),
  builder: (context, snapshot) {
    [...]
  },
);
```

Thank you for your time!

**Comment by petermichaux** [comment]
I agree this is confusing. It should be called "Article".

Unfortunately, the API uses "posts".

https://jsonplaceholder.typicode.com/posts/1

Also I think that inside `_MyAppState` the member named `post` should be called `_futurePost`. It references a `Future<Post>` object. It does not reference a `Post` object. (If the change to "Article" is possible then it should be `_futureArticle`.

**Comment by sfshaza2** [comment]
Ugh, yes, this is unfortunate. @petermichaux, are you suggesting that, instead of fetching blog posts that we fetch photo albums? I am definitely ok with that. PR me!

**Comment by petermichaux** [comment]
@sfshaza2 yes that's what I'm suggesting. It will help with the POST/PUT/DELETE recipes I've proposed.

**Comment by sfshaza2** [comment]
I like it.

**Comment by dejaime** [comment]
For some reason, I thought my July 2019 commit dc3f567 had already gone through.

**Comment by sfshaza2** [comment]
Was that commit attached to a PR?

**Comment by petermichaux** [comment]
"blogPost" is certainly an improvement. I think switching to something that doesn't include "post" will be even better. Also, a form for an "Album" will be just one field for title and therefore a little simpler in examples.

**Comment by petermichaux** [comment]
@hemanthrajv is a star!

@sfshaza2 Can you merge Hemanth's pull request? That will help prepare for #3679.
