### ISSUE TITLE
Update "Getting Started" path setup to support zsh shell (macOS Catalina support)

### ISSUE THREAD

**Issue by christopherfujino** [flutter/website#2856]
macOS Catalina is changing the default terminal shell to zsh. [this documentation](https://github.com/flutter/website/blob/master/src/docs/get-started/install/_path-mac-linux.md) shows a flutter developer how to add the flutter binary to their path, but it assumes they are using bash.

To add flutter to my path on Catalina, I did the following command:

`echo 'export PATH="[PATH_TO_FLUTTER_GIT_DIRECTORY]/bin:$PATH"' >> $HOME/.zshrc`

I'm not sure if Apple is going to set up zsh to automatically source bash config files, but on the beta it did not.

**Comment by sfshaza2** [comment]
We should probably show both approaches, for now.

**Comment by tamangsuresh** [comment]
Anyone have solution for this because i have gone to doc and google it. But i haven't found any solution yet. @christopherfujino  i try it but failed too.

**Comment by christopherfujino** [comment]
@tamangsuresh I'm not exactly sure what your situation is. Can you give me details of what you tried and what the results were? Thanks.

**Comment by tamangsuresh** [comment]
@christopherfujino thank you for replay. But i have found solution for it.

**Comment by ashvinstech** [comment]
Please help me i have tried everything but not able to set path

**Comment by christopherfujino** [comment]
@ashvinstech how exactly to set your path is dependent on your operating system and your shell.

If you're using bash or zsh (to determine which, `echo $SHELL`), first I would troubleshoot via:

1. `type flutter`, if this returns a path, then flutter is on your path, your finished.
1. Next, inspect what your path is currently set as, via `echo $PATH`. Your goal is to get the path to your flutter binaries (something like `/Users/fujino/flutter/bin`) onto this variable.
1. Find your user-specific shell config file. bash is user-configured via `$HOME/.bash_profile` on macOS and (usually) `$HOME/.bashrc` on linux and zsh is user-configured via `$HOME/.zshrc`. If you're using a unix-like shell on windows, there are many ways to get that (e.g. git bash, mingw, bash for windows), so you will have to check the documentation on how to configure your shell.
1. Add a line to your shell config file: `export PATH="<path_to_flutter_bins>:$PATH"

**Comment by kevin2-cyber** [comment]
Please I want to add to path on macOS Monterrey I've tried everything but it's not working
