### ISSUE TITLE
'Simple app state management' page isn't mobile friendly

### ISSUE THREAD

**Issue by chalin** [flutter/website#2860]
Page URL: https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/state-mgmt/simple.md

Related: #1951 

## Screenshot

  - > ![IMG_1084](https://user-images.githubusercontent.com/4140793/61803827-e2cf9a00-ae00-11e9-96f8-c963a235cef1.PNG)

**Comment by sfshaza2** [comment]
I just checked on my Pixel 6 and it looks great now!!
