### ISSUE TITLE
List products for sale

### ISSUE THREAD

**Issue by choohy** [flutter/website#2864]
Following code generates an exception.

             SliverSafeArea(      // BEGINNING OF NEW CONTENT
               top: false,
               minimum: const EdgeInsets.only(top: 8),
               sliver: SliverList(
                 delegate: SliverChildBuilderDelegate(
                   (context, index) {
                     if (index < products.length) {
                       return ProductRowItem(
                         index: index,
                         product: products[index],
                         lastItem: index == products.length - 1,
                       );
                     }
                     return null;
                   },
                 ),
               ),
             )                  // END OF NEW CONTENT

**Comment by sfshaza2** [comment]
@choohy, I can't find this code in our website repo. Can you tell me where you saw it?

**Comment by choohy** [comment]
https://codelabs.developers.google.com/codelabs/flutter-cupertino/#5

**Comment by sfshaza2** [comment]
Subsumed by https://github.com/flutter/website/issues/4026

**Comment by domesticmouse** [comment]
I'm confused about this bug. I've updated the [codelab repo](https://github.com/googlecodelabs/flutter-cupertino-store) and I'm not seeing exceptions. We are in the process of updating the codelab itself and we should get it published soon. Please monitor #4026 for when we have published. When that is up, I'd like your help in understanding where and how it is breaking for you, if I haven't fixed it in the update sweep.

**Comment by domesticmouse** [comment]
The [Building a Cupertino app with Flutter](https://codelabs.developers.google.com/codelabs/flutter-cupertino/index.html#0) codelab has been updated. Can you please attempt to reproduce this bug with the new code?

**Comment by sfshaza2** [comment]
Closing. Please reopen if you can recreate this issue with the updated codelab.
