### ISSUE TITLE
'Preparing an Android app for release' page issue

### ISSUE THREAD

**Issue by CongLeVN** [flutter/website#2868]
Page URL: https://flutter.dev/docs/deployment/android.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/android.md

Description of issue:
"flutter build appbundle" command not work any more

**Comment by sfshaza2** [comment]
@CongLeVN, do you this you might be hitting this issue?  https://github.com/flutter/flutter/issues/34308

There's a workaround in the bug.

**Comment by sfshaza2** [comment]
No response. Closing.
