### ISSUE TITLE
'Preparing an iOS app for release' page issue

### ISSUE THREAD

**Issue by MJEWalker** [flutter/website#2880]
Page URL: https://flutter.dev/docs/deployment/ios.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/ios.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by sfshaza2** [comment]
Closed due to lack of info..
