### ISSUE TITLE
MobX article link leads to 404

### ISSUE THREAD

**Issue by MaikuB** [flutter/website#2882]
Page: https://flutter.dev/docs/development/data-and-backend/state-mgmt/options

The link _[Flutter: State Management with Mobx](https://developer.school/posts/flutter-state-management-with-mobx/) by Paul Halliday_ listed under MobX leads to a 404. Said article no longer seems to exist on https://developer.school as well. The link should probably be removed since it no longer leads to an article

**Comment by eldraco19** [comment]
It is fixed now @MaikuB

**Comment by MaikuB** [comment]
Thanks, I was aware of the video. Thought I'd raise this in case the article ends up coming back. Will close this anyway
