### ISSUE TITLE
'Focus and text fields' page issue

### ISSUE THREAD

**Issue by feinstein** [flutter/website#2887]
Page URL: https://flutter.dev/docs/cookbook/forms/focus.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/forms/focus.md

Description of issue:

Is it there a reason for the text to use `FocusScope.of(context).requestFocus(myFocusNode)` instead of `myFocusNode.requestFocus()`?

**Comment by micpap25** [comment]
It looks like this has been fixed, this can be closed.

**Comment by feinstein** [comment]
Agreed.
