### ISSUE TITLE
'Preparing an iOS app for release' page issue

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/website#2891]
Page URL: https://flutter.dev/docs/deployment/ios.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/ios.md

Description of issue:
`Open the App IDs page of your developer account.` liks to the wrong url
it currently goes to certificates -> https://developer.apple.com/account/resources/certificates/list
and it should go to identifiers -> https://developer.apple.com/account/resources/identifiers/list

**Comment by legalcodes** [comment]
`Open the App IDs page of your developer account.` current links to https://developer.apple.com/account/ios/identifier/bundle which looks correct. Have I missed something @vanlooverenkoen ?

**Comment by sfshaza2** [comment]
Closing.
