### ISSUE TITLE
'MacOS install' page issue

### ISSUE THREAD

**Issue by iampeters** [flutter/website#2897]
Page URL: https://flutter.dev/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Description of issue:

After trying several times to add flutter/bin to my PATH on MacOS Mojave with no avail, i found this simple step to add flutter to PATH on macOS

Open up Terminal.
Run the following command:

<code> sudo nano /etc/paths </code>
Enter your password, when prompted.
Go to the bottom of the file, and enter the path you wish to add.

Hit <code> control + o </code> and hit <code> enter</code> to save the modified buffer.  Hit <code>  control + x  </code> to quit.
That’s it!  To test it, in new terminal window, type:

<code> echo $PATH </code>

**Comment by sfshaza2** [comment]
@iampeters, how odd that editing the ~/.bashrc file didn't work. Are you using the standard Mac terminal, which defaults to Bash on Mojave? (As of Catalina, the terminal uses Z shell.)

Editing the /etc/paths file directly seems like a dangerous suggestion for some.  :)

**Comment by iampeters** [comment]
That's true. But that was what worked for me as the instructions on the website did not help.
