### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by da7om85** [flutter/website#2898]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:
no downloading link

**Comment by sfshaza2** [comment]
@da7om85, for the Windows install, we've removed the download link. This is because the 7-Zip app on Windows wasn't unpacking hidden directories and was resulting in broken builds. That is why we now provide "git clone" instructions.
