### ISSUE TITLE
'Technical Overview' page issue

### ISSUE THREAD

**Issue by joeriddles** [flutter/website#2899]
Page URL: https://flutter.dev/docs/resources/technical-overview.html
Page source: https://github.com/flutter/website/tree/master/src/docs/resources/technical-overview.md

Description of issue: Under the `What is Flutter` section, the iOS screenshot showcasing an app with a teapot displays the wrong overflow icon in the top-right corner. The dots are vertically stacked when https://flutter.dev/docs/resources/platform-adaptations#iconography shows they should be stacked horizontally.

**Comment by micpap25** [comment]
It doesn't look like this page exists anymore. I think this can be closed on that merit. 
The "What is Flutter?" section in the FAQ doesn't have an image at all, by the way.

**Comment by MiraMarshall** [comment]
Closing because the screenshot is no longer on the mentioned page.
