### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by ChineduAnusi** [flutter/website#2900]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue: can't  find the download link

**Comment by sfshaza2** [comment]
@ChineduAnusi, for Windows install, we've removed the zip file download and replaced it with "git clone". This was because the 7-Zip app on Windows wasn't unpacking hidden directories. This resulted in broken builds.
