### ISSUE TITLE
'MacOS install' page issue

### ISSUE THREAD

**Issue by meritus** [flutter/website#2917]
Page URL: https://flutter.dev/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Description of issue:

"Launch Android Studio > Tools > Android > AVD Manager and select Create Virtual Device. (The Android submenu is only present when inside an Android project.) "

Does not work until the project finished building the first time. (This should be noted)

**Comment by rkishan516** [comment]
@meritus and @sfshaza2 I think it's not required to build a project for the first time for avd manager, you can create Virtual Device without open a project.
