### ISSUE TITLE
Add missing return statement to example on 'Pass arguments to a named route' page

### ISSUE THREAD

**Issue by naveenaa** [flutter/website#2927]
Description of issue: Missing Return Statement - Fix Example code. Screenshot Attached
https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments

**Comment by naveenaa** [comment]
<img width="835" alt="MissingReturnStatement-ExampleCode" src="https://user-images.githubusercontent.com/8305626/63413935-67213700-c418-11e9-82c1-b41c36c2e827.png">

**Comment by naveenaa** [comment]
Good example! for Routes. Useful.

Will be good to have A graceful code example. Thank you, Naveena

**Comment by piedcipher** [comment]
This seems fixed! I can see a return statement with `return null;` at the end.

**Comment by atsansone** [comment]
Example was updated with correct return value. Closing this issue.
