### ISSUE TITLE
'Developing packages 

### ISSUE THREAD

**Issue by nuzelac** [flutter/website#2934]
Page URL: https://flutter.dev/docs/development/packages-and-plugins/developing-packages.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/packages-and-plugins/developing-packages.md

Description of issue:
<img width="988" alt="image" src="https://user-images.githubusercontent.com/195299/63649180-d78ec780-c73a-11e9-8b16-31cba45617ba.png">
flutter/flutter#33302 has been resolved

**Comment by MaikuB** [comment]
The PR (https://github.com/flutter/flutter/pull/38490) that fixes the issue hasn't landed on stable yet. Looking at the list PRs merged between 1.7 and 1.9.1 would show that it's not there as well
