### ISSUE TITLE
Add C interop page

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#2941]
The FFI docs (see https://github.com/dart-lang/site-www/pull/1849) should point to flutter.dev for Flutter-specific issues.

In the first go-round, dart.dev will point to https://github.com/flutter/flutter/wiki/Binding-to-native-code-via-FFI. But we'd love to transfer that doc to flutter.dev and link to that.

**Comment by mit-mit** [comment]
fyi @sjindel-google

**Comment by sfshaza2** [comment]
@kwalrath, the Flutter. ffi info is now on flutter.dev:
https://flutter.dev/docs/development/platform-integration/c-interop

**Comment by kwalrath** [comment]
Thanks, @sfshaza2, I'll link to your page.

It's a little strange that your page says C/C++ and ours says just C. (Ours used to say C++, but we removed that.) Do you know why yours says C++?

/cc @mjohnsullivan

**Comment by sjindel-google** [comment]
Can we please leave the wiki page for a while? I've definitely pasted that link a bunch of places...

**Comment by kwalrath** [comment]
PR is up: dart-lang/site-www#1954

**Comment by sjindel-google** [comment]
Also, I don't know whether it should say "C" or "C/C++", but the point is that the FFI can bind to a C *interface*, regardless of whether that interface is implemented by C, C++, Swift, Objective-C, Rust or even Gol

**Comment by kwalrath** [comment]
> Also, I don't know whether it should say "C" or "C/C++", but the point is that the FFI can bind to a C _interface_, regardless of whether that interface is implemented by C, C++, Swift, Objective-C, Rust or even Gol

We should be clearer about this, somehow.

**Comment by mit-mit** [comment]
I suggest we just use 'C interop' everywhere
