### ISSUE TITLE
Need Dark Theme

### ISSUE THREAD

**Issue by apravint** [flutter/website#2952]
Please create a dark theme for flutter website, I really like to see how it looks in dark mode.

**Comment by legalcodes** [comment]
@apravint Folding this issue into https://github.com/flutter/website/issues/3632 which was recently migrated from flutter/flutter to flutter/website. LMK if you see any problems with this!

**Comment by apravint** [comment]
Thank you :)

**Comment by apravint** [comment]
Thanks for adding the dark theme.
