### ISSUE TITLE
TextField docs don't show how to read the value

### ISSUE THREAD

**Issue by Hixie** [flutter/website#2953]
There's various examples of TextField on the web site, e.g. https://flutter.dev/docs/cookbook/forms/text-input, but they don't show how you actually get the value from the user, which is probably the most important thing you can do with a text field.

**Comment by Hixie** [comment]
There's a recipe using an input controller, though (a) it isn't linked to the doc above as far as I can tell, and (b) it is way more complicated than just using onChanged: https://master-api.flutter.dev/flutter/material/TextField/onChanged.html

**Comment by johnpryan** [comment]
I think the next article in the sequence should be https://flutter.dev/docs/cookbook/forms/text-field-changes since it shows onChanged. Right now the next article is "Focus and text fields".

@sfshaza2 what do you think?

**Comment by sfshaza2** [comment]
I'm good with that, @johnpryan!
