### ISSUE TITLE
'Preparing an Android app for release' page issue

### ISSUE THREAD

**Issue by samskivert** [flutter/website#2969]
Page URL: https://flutter.dev/docs/deployment/android.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/android.md

Description of issue:
The instructions for creating a keystore assume that `keytool` is from Java version 8 or earlier, which defaults to a keystore type of `JKS`. `keytool` on Java 9 and newer default to a keystore type of `PKS12` which _does not_ work with the other instructions provided for signing the app.

The instructions should likely be amended to include `-storetype JKS` in the command that creates the keystore and signing key. This will work correctly regardless of which version of Java provides the `keytool` tool.

**Comment by sfshaza2** [comment]
Good catch!
