### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by eliezerbiny** [flutter/website#2972]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue: there is no download button for the flutter sdk

**Comment by sfshaza2** [comment]
It was removed for awhile, due to a bug. We replaced it with instructions on how to download and unpack the release using the command line. But the bug has been fixed and the button has been reinstated.  Closing.
