### ISSUE TITLE
Fix print styles

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#2974]
Way too much is displayed when you print a flutter.dev page. I'm willing to fix this, unless someone else gets to it first. I did some similar work on dart.dev in https://github.com/dart-lang/site-www/pull/1625/files#diff-2f9b732d7e4f85168803a352c230300d.

We need to at least remove the left nav and the right-top icons. Also, I think lines are cut off. We also need to make sure that the TOC is handled properly. (It seems OK in the following screenshot, but it might not be OK for all pages.) The TOC should probably be displayed in full (rather than on the right or cut off), like in this screenshot. 

![image](https://user-images.githubusercontent.com/2164483/64466681-05bfc000-d0c8-11e9-9031-f3293f731244.png)

**Comment by micpap25** [comment]
Looks like this has been done. I think this can be closed. 
![image](https://user-images.githubusercontent.com/34077605/92411267-24aac500-f115-11ea-9ce3-fa7a2a3137af.png)

**Comment by kwalrath** [comment]
Yes, you're right. I think I might've fixed this a long time ago!

**Comment by kwalrath** [comment]
Oops, no, the problem is still there.

![image](https://user-images.githubusercontent.com/2164483/92503100-99cdd700-f1b5-11ea-98d6-5e87ad7b9783.png)

**Comment by micpap25** [comment]
hmm, that's strange. 
I'm using Windows 10, Google Chrome, newest version:
Version 85.0.4183.102 (Official Build) (64-bit)
Hopefully, that helps.

**Comment by kwalrath** [comment]
Strange! I tried the same page as you showed (https://flutter.dev/docs/development/accessibility-and-localization/internationalization) at various window widths (just in case), and I still see the left sidenav.

I'm using MacOS and tried Chrome Canary and 2 versions of Chrome stable:
Version 87.0.4258.2 (Official Build) canary (x86_64)
Version 85.0.4183.83 (Official Build) (64-bit)
Version 85.0.4183.102 (Official Build) (64-bit)

So... sounds like a Windows thing? That's really weird.

![image](https://user-images.githubusercontent.com/2164483/92534692-4cb82800-f1ea-11ea-84da-f7bb2cb9d372.png)
