### ISSUE TITLE
'can't type in Textfield' page issue

### ISSUE THREAD

**Issue by mahmoudsalah37** [flutter/website#2980]
Page URL: https://flutter.dev/web.html
Page source: https://github.com/flutter/website/tree/master/src/web.md

Description of issue:
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.950], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter\flutter
    • Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\flutter\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\flutter\sdk
    • Java binary at: C:\flutter\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\flutter\android-studio
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[√] VS Code (version 1.38.0)
    • VS Code at C:\Users\Mahmoud salah eldin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

//Code
`import 'package:flutter_web/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController textEditingController = TextEditingController();
  @override
  Widget build(BuildContext context) {
    textEditingController.text = 'vdfjkvndfjkv';
    return Scaffold(
      appBar: AppBar(
        title: Text('title'),
      ),
      body: Container(
        child: TextFormField(
          decoration: InputDecoration(labelText: 'Enter your username'),
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

**Comment by mahmoudsalah37** [comment]
if i make copy or cut  from Textfield and paste in any editor text i can see what i did write it but in TextField nothing show

**Comment by sfshaza2** [comment]
Hi, @mahmoudsalah37! Are you trying this on the web? (The page URL suggests that you might be trying this on the web.)

If you need help with debugging this issue, please check out the Discord list:  https://discord.gg/N7Yshp4 . The server has many different categoories, and you can ask on the #web discussion, if this is specific to web.  Thanks!  (Closing this as we don't do tech support on the website  repo.)
