### ISSUE TITLE
Code debugging webpage does not match MD file

### ISSUE THREAD

**Issue by maks** [flutter/website#2981]
The url on the website:
https://flutter.dev/docs/testing/code-debugging#showing-network-traffic

does not point to a valid section because the webpage is missing the section on showing network traffic, yet its in the markdown file at: 

https://github.com/flutter/website/blob/7ba5437f9a30a97715c4dc0cc9d02b2098ecb793/src/docs/testing/code-debugging.md#showing-network-traffic

not sure what is going on? 

Here is what the webpage looks like at the moment:
![Screenshot from 2019-09-10 09-16-41](https://user-images.githubusercontent.com/71999/64572701-c802b600-d3ab-11e9-8c72-ae552819356a.png)

**Comment by sfshaza2** [comment]
Hi, @maks! That section has been removed. Engineering asked me to remove it. You aren't looking at the master branch. If you go to that page in the master branch, the content is gone. I have also removed the broken link.  Closing
