### ISSUE TITLE
Layout codelab not accurately demonstrating mainAxisSize behavior

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/website#2988]
(This issue was pointed out to us by someone commenting on a flutter/flutter issue: https://github.com/flutter/flutter/issues/4566)

The main axis size section of the layout basics codelab includes a code exercise that's not explaining things correctly:

https://flutter.dev/docs/codelabs/layout-basics#example-modifying-axis-size

When the main axis size is set to max, the Row fills the entire width and its children are left-aligned. No problem there. However, when it's set to min, because of the way the test code is structured, the row becomes centered within its parent as it shrinks. This could confuse some codelab users into thinking that the Row itself is centering its children, which it's not.

The test result message unfortunately reinforces this message:

```
Row lays out the BlueBox widgets without extra space, and the BlueBox widgets are positioned at the middle of Row's main axis.
```

While technically true (they occupy the entire main axis space of the Row and are therefore centered in it by default), someone unfamiliar with Flutter is likely to miss the subtle moment when the Row's empty space (marked with a dark grey color) disappears. As a result, they could process the new UI as a Row that takes up the same amount of width and has simply centered its children.

The test code and the test result for this exercise should be updated to make the true effect of MainAxisSize.min clear.

**Comment by sfshaza2** [comment]
To do this, we'll have to make a new copy of the gist file. (As Daniel owns the original files.)
