### ISSUE TITLE
'Fetch data from the internet' page issue

### ISSUE THREAD

**Issue by Varuni-Punchihewa** [flutter/website#2998]
Page URL: https://flutter.dev/docs/cookbook/networking/fetch-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/fetch-data.md

**Description of issue:**
You need to import the http package as 'http' in order to use **http.get('url')** mentioned in the [2. Make a network request](https://flutter.dev/docs/cookbook/networking/fetch-data#2-make-a-network-request)

**Comment by sfshaza2** [comment]
Fixed:  https://github.com/flutter/website/pull/2999
