### ISSUE TITLE
'macOS install' page issue

### ISSUE THREAD

**Issue by kjmj** [flutter/website#3019]
Page URL: https://flutter.dev/docs/get-started/install/macos#update-your-path
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/_path-mac.md

Description of issue:
I am on macOS Mojave and had trouble following this guide to permanently update my flutter path. The guide tells me to edit the file $HOME/.bashrc to set my flutter path. This did not work for me, and I ended up having to edit $HOME/.bash_profile in order to set my flutter path.

A note might help save future readers some time and trouble when they are setting up flutter  😄

**Comment by micpap25** [comment]
Looks like this has been resolved, this can be closed.
