### ISSUE TITLE
'Internation­alizing Flutter apps' page issue

### ISSUE THREAD

**Issue by jecolon** [flutter/website#3028]
Page URL: https://flutter.dev/docs/development/accessibility-and-localization/internationalization.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

Description of issue:
The process for Internationalization described on this page works for Android, but for iOS it only works if the following procedure is done:

"Solution:
You can just add Localizations if you have a mac and XCode installed. You have to open the flutter iOS part in xcode. Click on your project in the file list. There you habe to click on the Info tab. One Section will be "Localizations". There you have to add the languages you want to have in your project as well so that the iOS part can return the expected language as well."

This should be added to this documentation page. This was posted by tomkastek on Jun 5, 2018 as a solution to issue #14128.

**Comment by jecolon** [comment]
My bad. I know see it was added as an appendix at the end.

**Comment by sfshaza2** [comment]
This page needs some reorg. See https://github.com/flutter/website/issues/2611

I'm closing this issue.
