### ISSUE TITLE
'Flutter's build modes' page issue

### ISSUE THREAD

**Issue by kondasoft** [flutter/website#3038]
Page URL: https://flutter.dev/docs/testing/build-modes.html
Page source: https://github.com/flutter/website/tree/master/src/docs/testing/build-modes.md

This command is not available, im I wrong?!
`flutter build --release.`

**Comment by sfshaza2** [comment]
You are correct! You can specify one of the following to "flutter build":

  aar         Build a repository containing an AAR and a POM file.
  aot         Build an ahead-of-time compiled snapshot of your app's Dart
              code.
  apk         Build an Android APK file from your app.
  appbundle   Build an Android App Bundle file from your app.
  bundle      Build the Flutter assets directory from your app.
  ios         Build an iOS application bundle (Mac OS X host only).
  web         build a web application bundle.
