### ISSUE TITLE
'Technical overview' page issue

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#3046]
Page URL: https://flutter.dev/docs/resources/technical-overview#layer-cakes-are-delicious
Page source: https://github.com/flutter/website/tree/master/src/docs/resources/technical-overview.md

The SVG layer cake image uses title case; it should use sentence case. ~~But since it's SVG, it should be easy to fix!~~ I thought the text would be easily editable in the image source, but it isn't.

I noticed this because something else I've been editing reused this figure.

**Comment by kwalrath** [comment]
Image source: https://github.com/flutter/website/tree/master/src//images/whatisflutter/diagram-layercake.svg

**Comment by sfshaza2** [comment]
FYI:
- I downloaded Inkscape from the internal app place, and it won't launch on my Mac.
- Tried to fix this in the raw file - but no strings appear. They must use Unicode values or something.
- Tried to fix this in Omnigraffle - it wouldn't let me change the text.

**Comment by sfshaza2** [comment]
OK, Ian took a look at the SVG file and says that the text is pre-vectorized, so it's not really text, it's shapes. This image needs to be recreated.

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/3067
