### ISSUE TITLE
'Preparing an iOS app for release' page issue

### ISSUE THREAD

**Issue by Tomucha** [flutter/website#3054]
Page URL: https://flutter.dev/docs/deployment/ios.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/ios.md

Description of issue:

Running "flutter build ios" ends up with lot of different errors IF my xcode is open. Shutting down xcode and running "flutter build ios" works just fine. Im not sure what is happening under the hood, but maybe it should be mentioned here. Shut down your xcode before "flutter build ios".

**Comment by sfshaza2** [comment]
@cbracken, is this correct and intentional?

**Comment by cbracken** [comment]
That sounds surprising to me. I run `flutter build ios` with Xcode open pretty frequently and haven't run into this. The templated apps should built out of the box using Xcode's built-in Build command from the IDE itself (which is just delegating to `flutter build [...]` commands under the hood.

Would you mind filing a bug in the flutter/flutter repo with reproduction instructions and CC @zra, who can triage to the appropriate person on the team to take a look.

**Comment by sfshaza2** [comment]
Would you mind filing a bug on the flutter/flutter repo, @Tomucha?

**Comment by Tomucha** [comment]
@Tomucha will definitely try it again, but it happened on a quite large project, so it might be tricky to reproduce ... Unfortunately @Tomucha has a lot to do these days, so he cannot promise any deadline :-/

**Comment by sfshaza2** [comment]
OK, thanks for that update!

**Comment by sfshaza2** [comment]
Closing.
