### ISSUE TITLE
Building a Cupertino app with Flutter, add customer info issue

### ISSUE THREAD

**Issue by jaimealv994** [flutter/website#3058]
On page [Building a Cupertino app with Flutter](https://codelabs.developers.google.com/codelabs/flutter-cupertino/#7) section 8 (Add customer info) asks to update a build method in the _SearchTabState class, but the the class which has to be updated is _ShoppingCartTabState.

![image](https://user-images.githubusercontent.com/36939361/66250644-b12d5600-e702-11e9-82cd-7f5fa31b7eac.png)

**Comment by jaimealv994** [comment]
Where is the repo for this codelab? I have found several issues related to this codelab.
I could fix them and open a PR

**Comment by domesticmouse** [comment]
The underlying code behind the codelab is at: [googlecodelabs/flutter-cupertino-store](https://github.com/googlecodelabs/flutter-cupertino-store) However, that isn't the source for the codelab itself.

/cc @sfshaza2

**Comment by jaimealv994** [comment]
Yeah, I found that repo thought that the code for the codelab would be there but it isn't. Anyways, I will be checking this issue for future update.

**Comment by sfshaza2** [comment]
Subsumed by https://github.com/flutter/website/issues/4026
