### ISSUE TITLE
'Set up an editor' page issue

### ISSUE THREAD

**Issue by amin2009** [flutter/website#3061]
Page URL: https://flutter.dev/docs/get-started/editor.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/editor.md

Description of issue:

> Select Browse repositories, select the Flutter plugin and click Install.

I think, this line should be changed to: 

> Select "Marketplace", search for "Flutter" and click Install.

**Comment by sfshaza2** [comment]
You are correct! I checked both IntelliJ and Android Studio and both have changed to use Marketplace.

**Comment by sfshaza2** [comment]
Fixed in PR linked above.
