### ISSUE TITLE
Guide on 5. Add State Management

### ISSUE THREAD

**Issue by ievren** [flutter/website#3063]
https://codelabs.developers.google.com/codelabs/flutter-cupertino/#4,

There is something missing:
> Update lib/main.dart.
> In the main()method, initialize the model. Add the lines marked with NEW.

maybe an old code?

```
return runApp(
   ChangeNotifierProvider<AppStateModel>(        // NEW
     model: model,                               // NEW
     child: CupertinoStoreApp(),                 // NEW
   ),
 );
```
with your solution it will work 
> flutter-cupertino-store/step-01/lib/main.dart
```
return runApp(
    ChangeNotifierProvider<AppStateModel>(
      builder: (context) => AppStateModel()..loadProducts(),
      child: CupertinoStoreApp(),
    ),
  );
```

**Comment by sfshaza2** [comment]
Subsumed by https://github.com/flutter/website/issues/4026
