### ISSUE TITLE
Revert or simplify recent change in Animation tutorial code

### ISSUE THREAD

**Issue by chalin** [flutter/website#3073]
Hey @Piinks! This is a followup to #2842, in which you addressed a problem reported by https://github.com/flutter/flutter/issues/32772.

How were you able to reproduce the problem originally reported by https://github.com/flutter/flutter/issues/32772? I can't get the flutter analyzer to report an issue with the original code. I'm using the latest stable flutter (Flutter 1.9.1+hotfix.4 • channel stable).

The code updates of #2842, consisted in adding a cast:

```dart
final Animation<double> animation = listenable as Animation<double>;
```

The main point that I wanted to raise is that, IMHO, we don't need _both_ the cast and the type declaration, either should suffice by itself. So I was curious how you managed to get the analyzer to report an issue on the original code, which didn't have the cast.

The person who filed https://github.com/flutter/flutter/issues/32772 was using a beta version of flutter. Could the analyzer issue have only been transient (specific to that beta version), and so no longer be present in stable?

If we can't reproduce the problem with a stable version of flutter, then I suggest that we revert #2842. If we can reproduce the problem, then I suggest that we drop the LHS type declaration since type inference should kick in (given that the variable is `final`).

Thanks!

@legalcodes @johnpryan @sfshaza2: thoughts?

(Btw, I noticed this issue after manually running the code refresh script.)

**Comment by Piinks** [comment]
Hi @chalin!
Thank for opening this! It may be that this analyzer issue was transient. I would definitely check against master and consider that the source of truth. The master branch is the future stable, so if it is not reproducing there, then reverting SGTM!

**Comment by sfshaza2** [comment]
I defer to @Piinks and her advice to test against master.
