### ISSUE TITLE
Building a Cupertino app with Flutter, ChangeNotifierProvider initialiser mistake

### ISSUE THREAD

**Issue by louisdeb** [flutter/website#3083]
The [code snippet](https://codelabs.developers.google.com/codelabs/flutter-cupertino/#4) creates a `ChangeNotifierProvider` using the `model` parameter, as follows:

```dart
ChangeNotifierProvider<AppStateModel>(        // NEW
     model: model,                                                 // NEW
     child: CupertinoStoreApp(),                           // NEW
)
```

but the [current initialiser](https://pub.dev/documentation/provider/latest/provider/ChangeNotifierProvider-class.html) uses `builder` or `value`

**Comment by louisdeb** [comment]
Furthermore, the value passed, `model`, is not defined in the scope

**Comment by louisdeb** [comment]
However, the actual code [on GitHub](https://github.com/googlecodelabs/flutter-cupertino-store/blob/master/step-01/lib/main.dart) is correct.

**Comment by domesticmouse** [comment]
I believe this has been fixed by the updated [Building a Cupertino app with Flutter](https://codelabs.developers.google.com/codelabs/flutter-cupertino/#4)codelab. Thanks for the report!
