### ISSUE TITLE
Set up a page for listing Flutter books and other resources

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#3085]
Similar to the page on Dart's site:
https://dart.dev/resources/books

We need the infrastructure to be set up.

**Comment by legalcodes** [comment]
I've raised https://github.com/flutter/website/pull/3162.

TODO before merging this PR:
- [ ] add more books w/ cover images
- [ ] discuss `/resources` page, see dart.dev/resources

**Comment by sfshaza2** [comment]
I'd rather not have two resource pages/sections to the website.

**Comment by parlough** [comment]
There's a good amount of books in https://docs.flutter.dev/resources/books now and a process for adding new ones, closing.
