### ISSUE TITLE
'Basic Flutter layout concepts' page issue

### ISSUE THREAD

**Issue by ericleiva** [flutter/website#3091]
Page URL: https://flutter.dev/docs/codelabs/layout-basics.html
Page source: https://github.com/flutter/website/tree/master/src/docs/codelabs/layout-basics.md

Description of issue: Page takes forever to load, and the code editor is not showing up nor is the Run button, DartPad may be running all the examples on page load. Using Chrome for Mac.

**Comment by galeyang** [comment]
Same as https://github.com/flutter/website/issues/3098

**Comment by sfshaza2** [comment]
Closing as duplicate. @johnpryan is looking at this.
