### ISSUE TITLE
'Basic Flutter layout concepts' page issue :p0-critical:

### ISSUE THREAD

**Issue by RileyMShea** [flutter/website#3098]
Page URL: https://flutter.dev/docs/codelabs/layout-basics
Page source: https://github.com/flutter/website/blob/master/src/docs/codelabs/layout-basics.md

Description of issue:
[Basic Flutter Layouts](https://flutter.dev/docs/codelabs/layout-basics) appears to be embedding a copy of itself inside the iframes where dartpad should be embedded.

It appears to be recursive and continues to embed copies of itself in nested iframes.  This causes massive memory usage and eventually, the page crashes or the entire OS locks-up.

Tested on Ubuntu 19.04 with current releases of Chrome, Chromium, and Firefox using no extensions.  Same issue across browsers.

**Comment by galeyang** [comment]
@RedBrogdon @johnpryan 

I also had problems opening this page. All embeds didn't work and presented me with wrong iframe content. The page and browser crashed or locks-up as well. 
![image](https://user-images.githubusercontent.com/5102864/66781887-52e23f00-ee89-11e9-9648-cc880275e86f.png)

Tested on macOS Mojave with latest Chrome - Version 77.0.3865.120 (Official Build) (64-bit).

**Comment by sfshaza2** [comment]
Thanks, @johnpryan!
