### ISSUE TITLE
'Basic Flutter layout concepts' page issue

### ISSUE THREAD

**Issue by DanielJaramillo94** [flutter/website#3099]
Page URL: https://flutter.dev/docs/codelabs/layout-basics.html
Page source: https://github.com/flutter/website/tree/master/src/docs/codelabs/layout-basics.md

This page is not loading right! It never finishes!
I have tried in Chrome and Firefox. Something is wrong, maybe some js code?
Thanks!

**Comment by davidelettieri** [comment]
I have the same issue

**Comment by galeyang** [comment]
Same as https://github.com/flutter/website/issues/3098

**Comment by sfshaza2** [comment]
Closing as a duplicate.
