### ISSUE TITLE
'Fetch data from the internet' spawns the network request during build

### ISSUE THREAD

**Issue by Hixie** [flutter/website#3106]
Page URL: https://flutter.dev/docs/cookbook/networking/fetch-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/fetch-data.md

Step 4 does this:
```dart
FutureBuilder<Post>(
  future: fetchPost(),
  builder: (context, snapshot) {
    if (snapshot.hasData) {
      return Text(snapshot.data.title);
    } else if (snapshot.hasError) {
      return Text("${snapshot.error}");
    }

    // By default, show a loading spinner.
    return CircularProgressIndicator();
  },
);
```

This is bad, because it means that every time this widget rebuilds (e.g. when you rotate the phone, or when any nearby widget rebuilds), it'll trigger a new network request.

The network request should be done in `initState`.

**Comment by Hixie** [comment]
People are using this code, e.g. https://www.reddit.com/r/FlutterDev/comments/dhrtmz/future_futurebuilder_im_struggling_just_a_bit/

**Comment by sfshaza2** [comment]
Ack! @johnpryan, can you fix this?

**Comment by johnpryan** [comment]
yep!

**Comment by johnpryan** [comment]
Step 5 explains why this is a bad practice. We could combine steps 4 and 5 to avoid showing this code snippet altogether, but I think this article is OK as-is.

**Comment by Hixie** [comment]
I think we should flip it around so we show the good code, and only mention the "be careful" story in a sidebar or something. Seeing people copy this code is not good news for us.
