### ISSUE TITLE
Don't commit pubspec.lock files for tools and examples

### ISSUE THREAD

**Issue by chalin** [flutter/website#3107]
From: https://github.com/flutter/website/pull/2938/files#r335132003
> Hi @legalcodes @johnpryan et all. Why was it decided that we'd start committing the `pubspec.lock` files contained in the repo? 

I feel that having to maintain and commit the `pubspec.lock` files for this website repo introduces unnecessary churn. It usually makes sense to commit lock files for libraries. I'm not so sure that it is necessary for the tools and examples of this repo. Let me know what you think.

**Comment by johnpryan** [comment]
Sounds good to me. When breakages are caused by a package upgrade it's better to pin the version in pubspec.yaml IMO (instead of updating the lockfile.)

**Comment by chalin** [comment]
@legalcodes?

**Comment by legalcodes** [comment]
Sure, I'm fine with it, thanks Patrice!
Best,
Jon

**Comment by sfshaza2** [comment]
Can this be closed?

**Comment by johnpryan** [comment]
Not yet, the fix will be to remove the lockfiles
