### ISSUE TITLE
'Write your first Flutter app, part 1': usage of Divider is not promoting best practice

### ISSUE THREAD

**Issue by fabb** [flutter/website#3111]
```
  Widget _buildSuggestions() {
    return ListView.builder(
        padding: const EdgeInsets.all(16.0),
        itemBuilder: /*1*/ (context, i) {
          if (i.isOdd) return Divider(); /*2*/

          final index = i ~/ 2; /*3*/
          if (index >= _suggestions.length) {
            _suggestions.addAll(generateWordPairs().take(10)); /*4*/
          }
          return _buildRow(_suggestions[index]);
        });
  }
```

The part with the `Divider` used as every second list item is not best practice, and I suggest it should be removed. If dividers are needed, `ListView.separated` should be used, but it needs an `itemCount`, so it does not fit to the infinite scrolling example. So I'd suggest to just remove the separator, or pull it into the cell.

I.e. replace
```
        itemBuilder: /*1*/ (context, i) {
          if (i.isOdd) return Divider(); /*2*/

          final index = i ~/ 2; /*3*/
```
with
```
        itemBuilder: /*1*/ (context, index) {
```

**Comment by jishantmed** [comment]
Hey I am new to flutter. I have checked in some tutorials in ListView.builder they have to pass length as well. But in this they are not passing length, so how they are calculating rows.? If anybody know please explain.

**Comment by filiph** [comment]
Hi, thanks for the suggestion! The reason we made the example like this is to drive the point that Flutter UI is built in code. You can literally do anything in the build method. This is not obvious to newcomers. In most mobile frameworks, you have a very limited way of expressing what you want to build (an XML file, for instance, with maybe some templating functionality). It's easy to stay in this mindset, missing out on one of the main features of the framework this way.

I agree that this is not the best use of this property of Flutter. Having an itemBuilder create a column with a divider at the bottom most probably makes more sense. But I'm hesitant to remove the piece of logic in there without some kind of substitute that makes the point mentioned above.

I'm also hesitant to add a comment there that explains all this, detracting from the point of the example. But I'm open to discussion, of course.

**Comment by sfshaza2** [comment]
Closing.
