### ISSUE TITLE
'Technical overview' page issue

### ISSUE THREAD

**Issue by henryxie2093** [flutter/website#3126]
Page URL: https://flutter.dev/docs/resources/technical-overview.html
Page source: https://github.com/flutter/website/tree/master/src/docs/resources/technical-overview.md

Description of issue:
![pic](https://flutter.dev/assets/resources/diagram-layercake-73512ded89f7df8301f622c66178633f04f91187822daf1ddff0d54b2d2676dc.png)

Here is an issue that I found in this page.
The Embedder layers has three same "Render surface setup",
I don't understand the meaning of the picture, and I can't get enough information through the article below the picture.

**Comment by micpap25** [comment]
This page no longer exists, and regardless I think the page this now refers to,
https://flutter.dev/docs/resources/architectural-overview#:~:text=Flutter%20is%20a%20cross%2Dplatform,directly%20with%20underlying%20platform%20services. ,
has had this problem fixed. as it doesn't look like "Render surface step" doesn't show up more than once in any image on the page.
I think this can be closed.

**Comment by parlough** [comment]
Yep, this article has been replaced by the [Architectural overview](https://docs.flutter.dev/resources/architectural-overview) page which has a lot of new details. Check it out!

Thanks again for opening the issue! If you find any issues with the new page, please open a new issue.
