### ISSUE TITLE
CI: cron builds shouldn't trigger site deploys

### ISSUE THREAD

**Issue by chalin** [flutter/website#3127]
IMHO only "push" type builds over master should trigger site deploys, not cron builds because these will more often than not simply cause unnecessary site content "churn" (site content is unlikely to change because of a cron build, and yet, as things stand, the site is redeployed every day nonetheless).

Thoughts @johnpryan @filiph @legalcodes @sfshaza2?

Related: #3079

**Comment by johnpryan** [comment]
I'm not sure I have the full context, but does running a cron job each day reduce the risk that the site would be out of date? (e.g. if the build triggered by a merge fails for some reason?)

**Comment by chalin** [comment]
> ... e.g. if the build triggered by a merge fails for some reason?

Almost always, a build failure requires developer intervention -- so in that sense an cron build is unlikely to "fix" anything on its own. A developer who pushes a commit to master (possibly as the result of a merged PR) should monitor the build status (which includes the site deploy status) and fix the build ASAP if it fails. If a "push" build fails, there is a very slim chance that a subsequent cron build will fix the build (and result in a successful deploy).

As far as I know (someone please correct me if I'm wrong), there is no static site content that depends on time (other than, say, sitemap page timestamps -- which might actually be a another reason _not_ to deploy via cron builds). AFAIK, static site content depends on the repo's content only.

> but does running a cron job each day reduce the risk that the site would be out of date?

Yes, but it has nothing to do with the ability of a cron job to deploy a(n unchanged) rebuilt copy of the site.

Running a cron job is useful because, e.g., example code analysis and testing might fail over time because, e.g., "pub" might fetch newer versions of packages or a newer version of flutter. But that won't (shouldn't) affect static site content; a build failure is a sign to developers that example code needs to be checked. Similarly, external link checking might differ over time, but again, that's all being checked against the same static site content.

Does that make sense?

cc @kwalrath, in case she has some feedback on this.

**Comment by johnpryan** [comment]
Sounds reasonable, thanks for the detailed response.
