### ISSUE TITLE
'An introduction to unit testing' page issue

### ISSUE THREAD

**Issue by workerbee22** [flutter/website#3145]
Page URL: https://flutter.dev/docs/cookbook/testing/unit/introduction.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/unit/introduction.md

Description of issue: This para is contradictory: 

If you’re working on a Dart package that does **not** depend on Flutter, you can import the test package. The test package provides the core functionality for writing tests in Dart. This is the best approach when writing packages consumed by web, server, and **Flutter** apps.

So for Flutter apps do I or don't I use test? And where does <latest version> come from? Needs a link to pub.dev.

**Comment by rkishan516** [comment]
Yes, you can use the [test package](https://pub.dev/packages/test) for dart .
