### ISSUE TITLE
Add boilerplate questions for new PRs

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3148]
Each PR we raise against flutter/website should contain a minimum amount of context provided by answering a set of boilerplate questions, e.g. :

(1) Is this PR related to an existing issue? (2) Is this PR directly related to any other open PRs? (3) Can you provide a brief description of the changes in this PR, and their goal? etc.

**Comment by sfshaza2** [comment]
This is OK for code PRs, but I'd prefer we not add it to doc-only PRs.

**Comment by legalcodes** [comment]
Ah, I see now what you meant @sfshaza2 . I didn't include this info in my original issue, but I definitely envisioned posing a parallel proposal here: 

For non-code PRs (i.e. writing edits) we could also include a checklist for common conventions, issues, grammar tics, etc. to watch out for.

**Comment by sfshaza2** [comment]
SG

**Comment by legalcodes** [comment]
Raised https://github.com/flutter/website/pull/3450/ per https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by parlough** [comment]
A pull request template was added in https://github.com/flutter/website/commit/4c0afcad68539bffefc4effedf54e4af91c9961b
