### ISSUE TITLE
'Display a snackbar' page issue

### ISSUE THREAD

**Issue by Yoonwoojae** [flutter/website#3160]
Page URL: https://flutter-kr.io/docs/cookbook/design/snackbars.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/snackbars.md

Description of issue: The source currently doesn't work. You must use the GlobalKey or use the Builder widget. Please review.

**Comment by rkishan516** [comment]
@Yoonwoojae I guess this source code is working fine. We can use GlobalKey but without that, it also works.

**Comment by sfshaza2** [comment]
Soo.... it does work as it is. GlobalKey is optional. I'm closing.
