### ISSUE TITLE
Diff view for code excerpts is not copy/paste friendly

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3163]
Diff view currently creates `+` and `-` characters that make it cumbersome for users to copy/paste changes from diff view into a DartPad editor (or their own IDE or text editor).

Ideally users can quickly copy + paste changes presented in diff view without having to manage diff-view-specific characters like `+` and `-`.

@galeyang

**Comment by miquelbeltran** [comment]
An example of this can be seen in https://docs.flutter.dev/ui/layout/tutorial in the sample in the Step 2.

Selecting the code snippet text also selects the - and +

**Comment by atsansone** [comment]
Possible to add a repeat of the new code block that _is_ copyable directly under the existing `diff` block.

Only 11 files would need modification: https://github.com/search?q=repo%3Aflutter%2Fwebsite+%60%60%60diff&type=code

**Comment by atsansone** [comment]
The intent is to call out what is being changed with visual clarity. Closing this issue.
