### ISSUE TITLE
Track ratio of Cupertino / Material examples in docs

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3164]
We should increase our visibility on this ratio moving forward to help guide use of examples in new docs.

@galeyang

**Comment by sfshaza2** [comment]
@legalcodes, was this a UX researcher request? If so, please add the ux-research label.

**Comment by legalcodes** [comment]
@sfshaza2 thanks for the tip -- this isn't a UX request. I'd like to raise this issue (if it isn't already being tracked somewhere else) so that we can use data to help guide our choice of new examples.

**Comment by atsansone** [comment]
At present, Docs lacks the tooling, time, and process to launch such a large endeavor. This being the case, this issue will be closed and revisited later.
