### ISSUE TITLE
Create a section for the publicly shared proposals.

### ISSUE THREAD

**Issue by GregorySech** [flutter/website#3180]
I really love seeing the publicly shared proposals that are shared on Docs however I can only get the links from the website's firebase.json file.

Can we get a section to browse that list? Or a mailing list for when a new document is added to the /go/ links?

**Comment by sfshaza2** [comment]
This is a good idea, but to ensure that the list remains current, it should be autogenerated. This requires some website infrastructure.

**Comment by sfshaza2** [comment]
I wonder if there is sufficient interest to post to flutter_announce when a go link is added. However, it would be best if we don't add more process to the engineering team...

**Comment by GregorySech** [comment]
I'm not much of a web developer but if I can help in some way I'd be happy to.

The tool to generate this section could also handle the update of firebase.json unless we want it to simply select the links that start with /go/ and have the section generation be transparent to whomever adds those links. 

In my free time I could start working on it however I will need some specification of what the most desirable workflow is.

**Comment by sfshaza2** [comment]
@GregorySech, if you want to take a stab at it, I'm game! We lack general website infrastructure support at the moment.

**Comment by parlough** [comment]
There is now a page listing the [Design documents](https://docs.flutter.dev/resources/design-docs), and there is discussion about a more formal process with more details either here or on Discord (https://github.com/flutter/website/issues/8749). I'll close this issue in favor of that expansion. Thanks!
