### ISSUE TITLE
CI: use a custom docker container

### ISSUE THREAD

**Issue by chalin** [flutter/website#3184]
During our last meeting (@johnpryan, @legalcodes & @chalin) we discussed the possible use of a docker container with the Flutter SDK (among other bundles) installed as part of Travis CI. This may be worth exploring if it can still be easy and quick to update any given bundle (e.g., to the latest Flutter SDK for any given channel, or Ruby or Node version) so that we don't always have to wait for a container update.

**Comment by johnpryan** [comment]
@domesticmouse is working on the same thing for DartPad, but no updates yet.

**Comment by parlough** [comment]
I'm going to close this as our setup has changed quite a lot since this issue was created and we're currently using a Docker based development setup. 

If anyone wants more work done here, please open a new issue. Thanks!
