### ISSUE TITLE
Refactor and cleanup build scripts: drop Cirrus-only scripts, etc

### ISSUE THREAD

**Issue by chalin** [flutter/website#3186]
As discussed in 2019/10/24 meeting with @johnpryan @legalcodes: refactor & cleanup build scripts:

- ./tool/setup.sh				Cirrus-only
- ./tool/build_check_deploy.sh		Created for Cirrus, but reused under Travis
- ./tool/docker/docker_build.sh		Cirrus-only
- ./tool/docker/docker_push.sh		Cirrus-only
- ./tool/docker/docker_login.sh		Cirrus-only

Delete the Cirrus-only scripts and split up the monolithic `build_check_deploy.sh` script back into its constituent parts.

**Comment by parlough** [comment]
With the new, singular Docker-based infrastructure as of https://github.com/flutter/website/pull/6188, all of this cleanup has been completed.
