### ISSUE TITLE
Add more flutter create options to 'Test drive' page

### ISSUE THREAD

**Issue by davidgaspardev** [flutter/website#3195]
Page URL: https://flutter.dev/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Description of issue: The page does not explain additional parameters in command line, such as "--org" or "--project-name".

**Comment by micpap25** [comment]
Is it really necessary to include this info in the test drive page? I feel like that goes a bit too in-depth for the "Get Started" section.
Maybe it could just tell people to run `flutter help create` for more info?

**Comment by atsansone** [comment]
This would be outside the bounds of a Getting Started guide. Get started covers the basics. If the reader wants more, that information is provided elsewhere.
