### ISSUE TITLE
'Internation­alizing Flutter apps' page issue

### ISSUE THREAD

**Issue by jsroest** [flutter/website#3198]
Page URL: https://flutter.dev/docs/development/accessibility-and-localization/internationalization.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

Description of issue:
It is unclear what the package 'flutter_cupertino_localizations' is needed for. The only explanation that is given:
> If you want your app to work smoothly on iOS then you have to add the package ‘flutter_cupertino_localizations’ as well.

This package has a total score of 59, with a health score of 0, which in my opinion not good enough for a package recommended by google.

And the package only supports two locales: 'en' and 'zh'.............

If this package is needed for 'smooth' localization, please explain why and support the author of the package by adding more locales and improve the code/score.

**Comment by sfshaza2** [comment]
@xster, any insight?

**Comment by xster** [comment]
cc @HansMuller unfortunately I dropped the ball on this one. I switched project right after finishing the cupertino localization. Since Flutter's first party flutter_localization supports Cupertino localization, we should have updated the website rather than merging https://github.com/flutter/website/pull/2804.

**Comment by xster** [comment]
@Sfshaza2 we should revert #2804 in the meantime.

**Comment by sfshaza2** [comment]
Yes! I'm not sure how to do that. (Never had to revert a change before...)

**Comment by andreidiaconu** [comment]
@sfshaza2 I created PR https://github.com/flutter/website/pull/3737 for solving this and the duplicate issue https://github.com/flutter/website/issues/3736

Could someone please approve it?

**Comment by mono0926** [comment]
Added by #2804 and fixed by #3737, so this can be closed.
