### ISSUE TITLE
'Writing custom platform-specific code' page issue

### ISSUE THREAD

**Issue by zhengger** [flutter/website#3200]
Page URL: https://flutter.dev/docs/development/platform-integration/platform-channels.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/platform-channels.md

Description of issue:
It's outdated. For the latest flutter SDK(v1.9.1), there is no MainActivity.java file created but just MainActivity.kt when executing 'flutter create batterylevel' command. Please update this article for the latest flutter SDK.

**Comment by sfshaza2** [comment]
I don't know when this was fixed, but it's fixed. Closing.
