### ISSUE TITLE
'macOS install' page issue

### ISSUE THREAD

**Issue by chonghorizons** [flutter/website#3201]
Page URL: https://flutter.dev/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Description of issue:

Wrong path for the bash config file. In osx, it is`~/.bash_profile` and not `~/.bashrc`, at least in 10.14 osx.

ORIGINAL
> Open (or create) the rc file for your shell. For example, macOS Mojave (and earlier) uses the Bash shell by default, so edit $HOME/.bashrc. macOS Catalina uses the Z shell by default, so edit $HOME/.zshrc. If you are using a different shell, the file path and filename will be different on your machine.

**Comment by chonghorizons** [comment]
Duplicate of Issue #3019

**Comment by sfshaza2** [comment]
As this is a duplicate, and they cross reference each other, I'm closing.
