### ISSUE TITLE
Clarify 'Dealing with box constraints' page

### ISSUE THREAD

**Issue by dmvvilela** [flutter/website#3203]
Page URL: https://flutter.dev/docs/development/ui/layout/box-constraints.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/layout/box-constraints.md

Description of issue:

It is not actually an issue, but i think this documentations should be better.

Sorry if i misunderstood something. But for me there is a thing that i quite did not understand and other which i think should be improved.

The first one: It says if you nest a list view inside of another, it will have a problem with unbounded constraints.. The thing is: it says it it is nested with different kinds: vertical and horizontal scrolling. I don't understand this. If i have a column, why the cross axis (so width) would be infinite? It is not the height, which is the direction of scrolling that is infinite? It seems to me that the problem would exist if i have a column inside a column and a row inside a row and not the mixing of it. I probably got it wrong, but i think it should be better explained since till now i don't understand it. And also.. it has a height and a width (on the screen at least, which "maybe" it coud be passed to the child row/column).. even if the scroll is infinite.. So i always have a problem with this which leads to the seconds problem:

How to fix it? The doc just says "you cannot do it" but i don't believe so.. So it should say how can i fix it! For example.. Maybe calculating by hand the size of the widgets so that you can fix a width and height for them.. But i think this is not the best solution.. so this is actually how i am fixing this issue for now (size of viewport - size of the widgets = size i want).. but i trully don't think this is the best answer to the problem.

**Comment by atsansone** [comment]
Closing this issue and handling these concerns in https://github.com/flutter/website/issues/7701.
