### ISSUE TITLE
'Basic Flutter layout concepts' page issue

### ISSUE THREAD

**Issue by kdftechiz** [flutter/website#3210]
Page URL: https://flutter.dev/docs/codelabs/layout-basics.html
Page source: https://github.com/flutter/website/tree/master/src/docs/codelabs/layout-basics.md

Description of issue:
**Documentation does not comply with the code behaviour**

Article:
**crossAxisAlignment property**
The crossAxisAlignment property determines how Row and Column can position their children on their cross axes. A Row’s cross axis is vertical, and a Column’s cross axis is horizontal. **Most of the crossAxisAlignment property’s values only work with the Row class**........

CrossAxisAlignment.start(Row only)
CrossAxisAlignment.end(Row only)
CrossAxisAlignment.center(Row only)

**But I was able to use above properties with Column also in the dartpad provided on the page**

**Comment by chonghorizons** [comment]
I agree with @kdftechiz.

 I'm just a community member, but I proposed a fix for these. @kdftechiz, please review my pull request (fix) and link post there if you agree.

Thanks... it seems like this is so new that a lot of the docs need tweaks.
 
> CrossAxisAlignment.start(Row only)
> CrossAxisAlignment.end(Row only)
> CrossAxisAlignment.center(Row only)

**Comment by sfshaza2** [comment]
Thanks for providing a fix, @chonghorizons! Closing

**Comment by chonghorizons** [comment]
You betcha. I'm very excited to use more of Flutter and happy for my first accepted documentation pull request accepted.

**Comment by sfshaza2** [comment]
:D
