### ISSUE TITLE
DartPad picker generating errors in console

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/website#3213]
It looks like the DartPad picker script is kicking out some errors, at least in Chrome. Loading the front page (https://flutter.dev) causes two of these messages to appear in the console:

```
dartpad_picker_main.dart.js:329 Uncaught TypeError: "type": type 'minified:an' is not a subtype of type 'int'
    at Object.d (dartpad_picker_main.dart.js:137)
    at Object.j (dartpad_picker_main.dart.js:329)
    at x.j (dartpad_picker_main.dart.js:1328)
    at Object.ba (dartpad_picker_main.dart.js:722)
    at bn.$1 (dartpad_picker_main.dart.js:2251)
    at fo (dartpad_picker_main.dart.js:208)
    at dartpad_picker_main.dart.js:216
```

CC: @legalcodes @johnpryan

**Comment by johnpryan** [comment]
AFAICT this doesn't affect users?

**Comment by RedBrogdon** [comment]
Not that I could tell.

I wouldn't make this a priority, but it's something that would be good to check out and clean up.

**Comment by sfshaza2** [comment]
@RedBrogdon, can you close this issue and open one on the DartPad repo?

**Comment by RedBrogdon** [comment]
It's not with DartPad itself (at least as far as I can tell), but with the dropdown that allows the user to choose a sample.
