### ISSUE TITLE
Books page issues: isn't mobile friendly, and ToC issues

### ISSUE THREAD

**Issue by chalin** [flutter/website#3218]
The current books page was migrated from site-www, which was recently identified has having some issues, for details see [Books page: ToC links don't work, covers have external link icons, not mobile friendly #2060](https://github.com/dart-lang/site-www/issues/2060).

Consider bringing over the site-www fix, [Books page: fix ToC links, drop image external-link icon, make page mobile friendly #2062](https://github.com/dart-lang/site-www/pull/2062).

Specifically, the issues that we have with the flutter/web books page are:

- [ ] Page isn't mobile friendly -- see the screenshot bellow.
- [ ] Authors show up in ToC (we probably don't want that).
- [ ] Although this is difficult (but not impossible) to test at the moment, ToC entry links won't work.

#### Screenshot

> <img src="https://user-images.githubusercontent.com/4140793/68209218-e1d20b00-ffa0-11e9-9119-8ba71fc3a316.png" width=250>

**Comment by sfshaza2** [comment]
@legalcodes
