### ISSUE TITLE
Update "Add state management" from "Building a Cupertino app with Flutter" to use provider package

### ISSUE THREAD

**Issue by ofury** [flutter/website#3221]
https://codelabs.developers.google.com/codelabs/flutter-cupertino/#4

**1.** In part:

> 5. Add state management
> 
> The app has some common data that needs to be shared across multiple screens, so you need a simple way to flow the data to each of the objects that need it. The scoped_model package provides an easy way to do that. In scoped_model, you define the data model used to pass data from the parent widget to its descendants. Wrapping the model in a ScopedModel widget makes the model available to all descendant widgets. The ScopedModelDescendant widget finds the correct ScopedModel in the widget tree.

But [lib/model/app_state_model.dart](https://github.com/googlecodelabs/flutter-cupertino-store/blob/master/step-01/lib/model/app_state_model.dart) and instructions were updated to use provider with ChangeNotifier.

**2.**  In part
> Update lib/main.dart.
> In the main()method, initialize the model. Add the lines marked with NEW.
> 
> ```
> import 'package:flutter/cupertino.dart';
> import 'package:flutter/services.dart';
> import 'package:provider/provider.dart';         // NEW
> 
> import 'app.dart';
> import 'model/app_state_model.dart';             // NEW
> 
> void main() {
>  SystemChrome.setPreferredOrientations(
>      [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);
> 
>  return runApp(
>    ChangeNotifierProvider<AppStateModel>(        // NEW
>      model: model,                               // NEW
>      child: CupertinoStoreApp(),                 // NEW
>    ),
>  );
> }
> ```
Update code to:

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';         // NEW

import 'app.dart';
import 'model/app_state_model.dart';             // NEW

void main() {
 SystemChrome.setPreferredOrientations(
     [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown]);

 return runApp(
   ChangeNotifierProvider<AppStateModel>(        // NEW
     builder: (context) => AppStateModel()..loadProducts(),                               // NEW
     child: CupertinoStoreApp(),                 // NEW
   ),
 );
}
```

**Comment by sfshaza2** [comment]
Subsumed by https://github.com/flutter/website/issues/4026
