### ISSUE TITLE
'Simple app state management' page issue

### ISSUE THREAD

**Issue by snios** [flutter/website#3222]
Page URL: https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/state-mgmt/simple.md

Description of issue: Tutorial claims to have a screen called "login prompt". This screen does not exist in the github repo linked by this tutorial.

**Comment by legalcodes** [comment]
Fixed in https://github.com/flutter/website/pull/3225.
