### ISSUE TITLE
'JSON and serialization' page issue

### ISSUE THREAD

**Issue by ianwith** [flutter/website#3228]
Page URL: https://flutter.dev/docs/development/data-and-backend/json#serializing-json-using-code-generation-libraries
Page Source: https://github.com/flutter/website/blob/master/src/docs/development/data-and-backend/json.md

Description of issue:
In the 'Creating model classes the json_serializable way' section, according to `json_serializable` library,
`_$UserFromMappedJson(json)` should be `_$UserFromJson(json)`
Although this method actually takes a Map instead of a json, the `json_serializable` library does not recognize the name `_$UserFromMappedJson`.

Poof of the issue:
I tried the code `_$UserFromMappedJson(json)` in the documentation with `json_serializable 3.2.0`, the result is: generated method in `user.g.dart` file is still `_$UserFromJson`:
```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

User _$UserFromJson(Map<String, dynamic> json) {
  return User(
    json['firstName'] as String,
    json['address'] == null
        ? null
        : Address.fromJson(json['address'] as Map<String, dynamic>),
  );
}

Map<String, dynamic> _$UserToJson(User instance) => <String, dynamic>{
      'firstName': instance.firstName,
      'address': instance.address?.toJson(),
    };
``` 

related issue: https://github.com/flutter/website/issues/2961
related pr: https://github.com/flutter/website/pull/3144

**Comment by rkishan516** [comment]
@ianwith I agree with you but this is just an example.

**Comment by rkishan516** [comment]
@ianwith you can close this issue if you agree with me otherwise please leave your suggestion.

**Comment by ianwith** [comment]
We can close this now because it was fixed by this PR:
https://github.com/flutter/website/pull/3230
