### ISSUE TITLE
Update Navigation article in cookbook

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#3245]
#3211 addressed an issue where the text of the article didn't match the complete example. As pointed out by @chonghorizons, there are some other pieces that don't match:

- The reference in step 4 should be "push()", not "pushNamed()"
- There's no `routes` defined in the complete sample (step 3)

The complete sample should reflect what the user sees after going through the steps.

**Comment by includecmath** [comment]
Looks like I fixed it: 
https://github.com/flutter/website/pull/3293
https://github.com/flutter/website/pull/3296

**Comment by johnpryan** [comment]
yep, this looks fixed. Thanks @includecmath!
