### ISSUE TITLE
Move TODO comments to GitHub Issues

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3270]
There are plenty of comments in flutter/website source code marking items as TODO:
https://github.com/flutter/website/search?utf8=%E2%9C%93&q=TODO&type=
Let's get these into GitHub issues where we have a process for tracking / prioritizing work that needs to be done.

- [ ] #9309
- [ ] #9310
- [x] #9314
- [ ] #9311
- [ ] #9312
- [ ] #9313
- [ ] https://github.com/flutter/website/issues/8249

**Comment by sfshaza2** [comment]
Please leave the TODOs in the PRs, unless they have been done.  :)

**Comment by legalcodes** [comment]
Can you clarify "leave the TODOs in the PRs" ? Did you mean leave the TODOs in the source code?

**Comment by sfshaza2** [comment]
Yes, that's what I meant.

**Comment by legalcodes** [comment]
FWIW, ["TODO" is a permanent exception w/ pedantic ](https://pub.dev/packages/pedantic):
```
Here is how static analysis is used internally at Google:

By default we disallow checking in code with any errors, warnings, or hints.
The TODO hint is a permanent exception.
```

**Comment by atsansone** [comment]
TODOs have been left and the issues created. Closing this issue.
