### ISSUE TITLE
'Animations tutorial' page issue

### ISSUE THREAD

**Issue by feinstein** [flutter/website#3284]
Page URL: https://flutter.dev/docs/development/ui/animations/tutorial.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/animations/tutorial.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

The text suggests:

> Dispose of the controller when the animation is finished to prevent memory leaks.

But AFAICS, `controller.dispose();` is being called inside the `StatefulWidget` `dispose()` method, so this won't be called when the animation finishes, but just when the `State` object itself is discarded.

**Comment by MiraMarshall** [comment]
Closing. The issue has been fixed.
