### ISSUE TITLE
Add Curves examples

### ISSUE THREAD

**Issue by feinstein** [flutter/website#3306]
Please add a page with several curves animations, so we can see them in action and decide which one we want to use.

[here](https://api.flutter.dev/flutter/animation/Curves/fastOutSlowIn-constant.html) I can see one curve, but I can't find a page where there's a Curve Catalog.

**Comment by legalcodes** [comment]
@feinstein is this what you're looking for? https://api.flutter.dev/flutter/animation/Curves-class.html

**Comment by feinstein** [comment]
Yes! Thanks... Maybe the text should say explicitly that the Class docs includes a visual catalog?

**Comment by legalcodes** [comment]
No problem! Is there a specific page you were using or referring to that was missing this link?

**Comment by feinstein** [comment]
I was looking the animations tutorial.

**Comment by legalcodes** [comment]
Sure, opened separate issue for your recommendation: https://github.com/flutter/website/issues/3311.

Closing this one unless there's something we missed!

**Comment by feinstein** [comment]
Ok, no problem, thanks.
