### ISSUE TITLE
Add DraggableScrollableSheet to 'Widget catalog'

### ISSUE THREAD

**Issue by IchordeDionysos** [flutter/website#3307]
Page URL: https://flutter.dev/docs/development/ui/widgets/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/widgets/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: `DraggableScrollableSheet` is missing from the widget catalog.

https://www.youtube.com/watch?v=Hgw819mL_78
https://api.flutter.dev/flutter/widgets/DraggableScrollableSheet-class.html

**Comment by piedcipher** [comment]
DraggableScrollableSheet is present under https://docs.flutter.dev/development/ui/widgets/scrolling.
This seems fixed!

**Comment by sfshaza2** [comment]
It sure is!
