### ISSUE TITLE
'Performance best practices' page issue

### ISSUE THREAD

**Issue by sampkme** [flutter/website#3319]
Page URL: https://flutter.dev/docs/perf/rendering/best-practices.html
Page source: https://github.com/flutter/website/tree/master/src/docs/perf/rendering/best-practices.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by legalcodes** [comment]
HI @sampkme thanks for raising this issue -- did you find an error on the best-practices page? I don't see a description of this issue.

**Comment by sfshaza2** [comment]
Nothing described. Closing.
