### ISSUE TITLE
'Material Components widgets' page issue

### ISSUE THREAD

**Issue by feinstein** [flutter/website#3320]
Page URL: https://docs.flutter.dev/ui/widgets/material
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/widgets/material.md

Description of issue:

- [ ] [`MaterialBanner`](https://master-api.flutter.dev/flutter/material/MaterialBanner-class.html) is missing
- [ ] [`NavigationRail`](https://master-api.flutter.dev/flutter/material/NavigationRail-class.html) is missing

**Comment by micpap25** [comment]
@sfshaza2 what category would this fall into? Alerts, information displays, etc...

**Comment by guidezpl** [comment]
I wonder if we should rather deprecate this page in favor using [Dartdoc categories/images](https://pub.dev/packages/dartdoc#categories) to improve https://api.flutter.dev/flutter/material/material-library.html?

One less place to keep components in sync (the other being flutter/gallery).

**Comment by atsansone** [comment]
The Widget Catalog for Material3 has been updated and is in sync with the Material3 documentation. Navigation Rail is present but Material Banner is not. See https://github.com/flutter/website/pull/8574. Closing this issue as complete.
