### ISSUE TITLE
adding "cloud_firestore: ^0.11.0+1" in pubspec.yaml without using feature causes Android errors

### ISSUE THREAD

**Issue by naveenaa** [flutter/website#3321]
1. Create a new flutter project and add cloud_firestore: ^0.11.0+1" in pubspec.yaml
executing the newly created sample main.dart flutter example,
causes the following errors:
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'android.arch.lifecycle:runtime' has different version for the compile (1.0.0) and runtime (1.1.1) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

2. rerun code with #cloud_firestore: ^0.11.0+1, compiles and generates APK
<img width="348" alt="Screen Shot 2019-11-29 at 10 01 35 AM" src="https://user-images.githubusercontent.com/8305626/69843844-32cadb80-128f-11ea-957c-fb9260fb4b10.png">

Issue: if the example main.dart does not use cloud_firestore, irrespective of enabling the cloud_firestore plugin, apk generation should not result in errors!

Please fix the issue. Thanks, Naveena

**Comment by legalcodes** [comment]
Hi @naveenaa thanks for raising this issue! It sounds like you're proposing a change to source code, as opposed to documentation. Is that right?

**Comment by sfshaza2** [comment]
Just to weigh in, @naveenaa, if you are filing this because you think the software should behave differently, or better, please file a bug on the flutter/flutter repo. This repo is for issues with the documentation on the flutter.dev website. Thanks!

**Comment by sfshaza2** [comment]
Closing.
