### ISSUE TITLE
Proposal: for pages that contain many links, separate links by category (internal links, page links, and external links)

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3322]
## Proposal

Let's consider using the following distinctions to separate long lists of links at the bottom of `.md` pages:

**Internal links:** links to content on the same page (using named anchors)

**Site links:** flutter.dev URLs that are not on the same page

**External links:** links to other pages, e.g. site-api, youtube, etc.

## Goals
- Make it easy to decide whether enough links to internal and external content have been provided for a given page (e.g. this is a page about implicit animations, does it include all the relevant internal / external links for implicit animations?
- Enable writers to quickly scan the breakdown of links within a `.md` page by category, i.e. answer the following question quickly: how many internal, site, and external links does this page already contain?
- Help writers form judgments more quickly about whether a page is lacking relevant links to site or external content that is helpful to readers.
## Scope
- All `.md` site content pages that contain longs lists of links (~15 links may be a good starting threshold)

## 

Example:
In the following list of links, the reader can quickly determine that there are only a few internal/site links in this page, but there are many external links. Depending on the page, this information might guide the aid the writer in forming a course of action for improving the links provided by this page: perhaps more internal links would help the reader, or there could be more site links that are missing from this page.

```
{% comment %} Internal {% endcomment %}

[Fade-in text effect]: /docs/codelabs/implicit-animations#example-fade-in-text-effect
[fade-in starter code]: /docs/codelabs/implicit-animations#fade-in-starter-code
[fade-in complete]: /docs/codelabs/implicit-animations#fade-in-finished-code

[Shape-shifting effect]: /docs/codelabs/implicit-animations#example-shape-shifting-effect
[shape-shifting starter code]: /docs/codelabs/implicit-animations#shape-shifting-starter-code
[shape-shifting complete]: /docs/codelabs/implicit-animations#shape-shifting-finished-code

{% comment %} Flutter.dev {% endcomment %}

[stateful widgets]: /docs/development/ui/interactive#stateful-and-stateless-widgets
[staggered animations]: /docs/development/ui/animations/staggered-animations
[hero animations]: /docs/development/ui/animations/hero-animations
[animations tutorial]: /docs/development/ui/animations/tutorial
[codelab]: /docs/codelabs

{% comment %} External {% endcomment %}

[list of common implicitly animated widgets]: {{site.api}}/flutter/widgets/ImplicitlyAnimatedWidget-class.html
[ImplicitlyAnimatedWidget]: {{site.api}}/flutter/widgets/ImplicitlyAnimatedWidget-class.html
[linear animation curve]: {{site.api}}/flutter/animation/Curves/linear-constant.html
[animation library]: {{site.api}}/flutter/animation/animation-library.html
[easeInOutBack]: {{site.api}}/flutter/animation/Curves/easeInOutBack-constant.html
[duration]: {{site.api}}/flutter/widgets/ImplicitlyAnimatedWidget/duration.html
[AnimatedContainer]: {{site.api}}/flutter/widgets/AnimatedContainer-class.html
[DartPad troubleshooting page]: {{site.dart-site}}/tools/dartpad/troubleshoot
[list of curve constants]: {{site.api}}/flutter/animation/Curves-class.html
[linear curve]: {{site.api}}/flutter/animation/Curves/linear-constant.html
[AnimatedOpacity]: {{site.api}}/flutter/widgets/AnimatedOpacity-class.html
[make a Flutter app]: {{site.codelabs}}/codelabs/first-flutter-app-pt1/
[Material App]: {{site.api}}/flutter/material/MaterialApp-class.html
[curve]: {{site.api}}/flutter/animation/Curve-class.html
[DartPad]: {{site.dartpad}}
```

Compare with un-categorized current approach:

It's harder to form a sense for what links are included and not included with a single glance, and therefore there's a higher barrier to forming a judgment about whether this page needs more internal, site, or external links:

```
[Animation]: {{site.api}}/flutter/animation/Animation-class.html
[animation controllers]: {{site.api}}/flutter/animation/AnimationController-class.html
[animation library]: {{site.api}}/flutter/animation/animation-library.html
[Animations landing page]: /docs/development/ui/animations
[AnimationController]: {{site.api}}/flutter/animation/AnimationController-class.html
[AnimatedBuilder]: {{site.api}}/flutter/widgets/AnimatedBuilder-class.html
[Animations in Flutter tutorial]: /docs/development/ui/animations/tutorial
[basic_staggered_animation]: {{site.github}}/flutter/website/tree/master/examples/_animation/basic_staggered_animation
[Building Layouts in Flutter]: /docs/development/ui/layout
[staggered_pic_selection]: {{site.github}}/flutter/website/tree/master/examples/_animation/staggered_pic_selection
[CurvedAnimation]: {{site.api}}/flutter/animation/CurvedAnimation-class.html
[Curves]: {{site.api}}/flutter/animation/Curves-class.html
[Flutter API documentation]: {{site.api}}
[Flutter Gallery]: ({{site.github}}/flutter/flutter/tree/master/examples/flutter_gallery
[flutter_sequence_animation]: {{site.pub}}/packages/flutter_sequence_animation
[Full code for basic_staggered_animation's main.dart]: {{site.repo.this}}/tree/{{site.branch}}/examples/_animation/basic_staggered_animation/main.dart
[Interval]: {{site.api}}/flutter/animation/Interval-class.html
[Material motion spec]: {{site.material}}/guidelines/motion/
[pub.dev]: {{site.pub}}/packages
[Shrine demo]: {{site.github}}/flutter/flutter/tree/master/examples/flutter_gallery/lib/demo/shrine
[Tween]: {{site.api}}/flutter/animation/Tween-class.html
```

**Comment by sfshaza2** [comment]
So, I've mulled this proposal over for awhile. Honestly, it does not seem particularly useful to me. I don't think of a docs in terms of "are there enough links?" For me, the links should flow from the narrative. Also, your examples show an improper use of internal links. The correct usage is:

[Fade-in text effect]: #example-fade-in-text-effect

Finally, codelabs, in particular, need to be careful of over-usage of links. Ideally, the user doesn't find it necessary to jump out of the lab much, if at all. It *is* tricky to strike the right balance -- enough info to accomplish the lab, but not too much that overwhelms. You want to avoid distracting the user from the goal at hand, and too many links can do just that. Ideally they will go through the lab and then, at the end, look up topics of interest. This is another reason we often put links at the end, and not so much in the middle.

@kwalrath, what do you think of this proposal? I'm willing to be convinced that I'm wrong.

**Comment by kwalrath** [comment]
I don't understand the reason for this proposal, but I'd be happy to talk about it in person. I agree that we want to avoid distracting links.

**Comment by sfshaza2** [comment]
Since we talked about this in our meeting yesterday, any reason we can't close this?

**Comment by legalcodes** [comment]
No problem
