### ISSUE TITLE
"404 not found" while looking for example of ".gitlab-ci.yml"

### ISSUE THREAD

**Issue by mordivgor** [flutter/website#3328]
Page URL: https://flutter.dev/docs/testing/
Page source: https://github.com/flutter/website/tree/master/src/docs/testing/index.md

Description of issue:
"404 not found" after clicking example of ".gitlab-ci.yml".
Specifically, fourth point in section:
https://flutter.dev/docs/testing#continuous-integration-services

**Comment by sfshaza2** [comment]
@brianegan, the 4th bullet in the list has 2 links to your repo and both are broken, as well as the GitLab list. Can you shed any light on this?

**Comment by brianegan** [comment]
Hi @Sfshaza -- I wasn't aware those were being linked to from that page. I actually moved that project from Gitlab to Github almost 2 years ago, so I wouldn't recommend linking to it as an example of how to work with Gitlab.

**Comment by sfshaza2** [comment]
Thanks!
