### ISSUE TITLE
IMPORTANT: version mismatch and incompatibility 'Firebase' page issue

### ISSUE THREAD

**Issue by naveenaa** [flutter/website#3333]
Page URL: https://flutter.dev/docs/development/data-and-backend/firebase.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/firebase.md

PLEASE DEFINE FOR FLUTTER APP, VERSIONS TO USE IF firebase_auth credential verification has to be executed. THANKS! 
firebase_core: ^0.4.0+9
  firebase_auth: ^0.8.0
  cloud_firestore: ^0.7.0+1 

Description of issue:
Versioning incompatible errors:
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.8.0
  cloud_firestore: ^0.7.0+1

depends on cloud_firestore ^0.7.0+1 which depends on firebase_core ^0.2.2, firebase_core ^0.2.2 is required.
So, because programApp depends on firebase_core ^0.4.0+9, version solving failed.
pub get failed (1)
Process finished with exit code 1

Tried changing to:
based on https://codelabs.developers.google.com/codelabs/flutter-firebase/#3
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.11.0+1     # new

And observe more errors:
-------------------------
Because firebase_auth >=0.8.0+1 <0.10.0 depends on firebase_core ^0.3.0 and no versions of firebase_auth match >0.8.0 <=0.8.0, firebase_auth >0.8.0 <0.10.0 requires firebase_core ^0.3.0.
And because firebase_auth 0.8.0 depends on firebase_core ^0.2.5+1, firebase_auth >=0.8.0 <0.10.0 requires firebase_core ^0.2.5+1 or ^0.3.0.
So, because programApp depends on both firebase_core ^0.4.0+9 and firebase_auth ^0.8.0, version solving failed.
pub get failed (1)
Process finished with exit code 1

**Comment by naveenaa** [comment]
When version numbers are further changed:
firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5

Running "flutter pub get" in programApp..                                0.6s
Process finished with exit code 0

But run into following execution errors that fails to build APK file
Launching lib/main.dart on Redmi Note 6 Pro in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'android.arch.lifecycle:runtime' has different version for the compile (1.1.0) and runtime (1.1.1) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Finished with error: Gradle task assembleDebug failed with exit code 1

Any ways to fix this issue, please help!
Thank you,

**Comment by naveenaa** [comment]
firebase_auth: ^0.15.0+1
cloud_firestore: ^0.12.9+5

removed firebase_core
observe following errors
Launching lib/main.dart on Redmi Note 6 Pro in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'android.arch.lifecycle:runtime' has different version for the compile (1.1.0) and runtime (1.1.1) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Finished with error: Gradle task assembleDebug failed with exit code 1

If the version number changed to:
firebase_auth: 0.11.1+12

observe code errors of the plugin
final PhoneVerificationCompleted verificationCompleted =
        (AuthCredential phoneAuthCredential) async {

      AuthResult authResult = await _auth.signInWithCredential(phoneAuthCredential);
<img width="658" alt="Screen Shot 2019-12-03 at 3 10 14 PM" src="https://user-images.githubusercontent.com/8305626/70038870-fffe4b80-15de-11ea-8501-650ad8e1e975.png">

**Comment by kroikie** [comment]
@naveenaa I would try this again with the latest versions of the plugins. They are compatible.

**Comment by sfshaza2** [comment]
Hi, @naveenaa! My colleague on the Firebase team tells me that the incompatibility issues between core, analytics, and firebase have been resolved. Can you grab the latest versions of these plugins and let us know if you are still seeing problems?

**Comment by sfshaza2** [comment]
Closing..
