### ISSUE TITLE
'Books about Flutter' page issue

### ISSUE THREAD

**Issue by caviroski** [flutter/website#3334]
Page URL: https://flutter.dev/docs/resources/books.html
Page source: https://github.com/flutter/website/tree/master/src/docs/resources/books.md

Description of issue:

You can add this book: https://www.amazon.de/dp/1484249712/ref=pd_sbs_14_2/257-8975610-0364811?_encoding=UTF8&pd_rd_i=1484249712&pd_rd_r=c6cae9fa-021d-49bc-89a4-d1e9372add0e&pd_rd_w=mjuMu&pd_rd_wg=nFQEV&pf_rd_p=184816e4-edb5-4587-8faf-776e0027d8d1&pf_rd_r=CPKKDAZ8RJCWZGTM4XJC&psc=1&refRID=CPKKDAZ8RJCWZGTM4XJC

**Comment by joshvocal** [comment]
Would I be able to work on this issue and add this book into the resources?

**Comment by legalcodes** [comment]
@joshvocal Thanks for the recommendation! Not letting this issue slide, just need some extra time. Will be in touch in ~1-2 weeks, would that be alright?

**Comment by joshvocal** [comment]
@legalcodes For sure! Thanks for letting me know.
