### ISSUE TITLE
'Preparing an Android app for release' page issue

### ISSUE THREAD

**Issue by nicolascav** [flutter/website#3335]
Page URL: https://flutter.dev/docs/deployment/android.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/android.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

My app crash on start!

**Comment by legalcodes** [comment]
@nicolascav Thanks for raising this issue. Can you provide the steps needed to duplicate this issue?
