### ISSUE TITLE
'Preparing a web app for release' page issue

### ISSUE THREAD

**Issue by ksilz** [flutter/website#3368]
Page URL: https://flutter.dev/docs/deployment/web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/web.md

Description of issue:

The page is called "Build and release a web app" in the table of content on the left, not "Preparing a web app for release".

**Comment by sfshaza2** [comment]
We sometimes do shorten the name to better fit on the sidenav.

**Comment by ksilz** [comment]
@sfshaza2 I find this confusing. My mental model is that of a book with a table of contents and headings. I expect the headings in the table of content to match the actual headings. And in this particular case, you're saving just 4 characters (31 vs 27).  

I link to the page in an upcoming blog post. To clear up the confusion, I include both titles in my article and also state that, yes, they are different. So you're saving, I'm adding. 😁

**Comment by sfshaza2** [comment]
Oh, I do plan to fix these. I'll use the sidebar titles. Anything to avoid
confusion. :-)

**Comment by legalcodes** [comment]
+1, fwiw I think user expectation is that these should match.
