### ISSUE TITLE
built_value vs json_serializable

### ISSUE THREAD

**Issue by shouichi** [flutter/website#3380]
`built_value` or `json_serializable` can generate json serialization code. The former is marked as "flutter favorite" and the latter is not. [JSON and serialization](https://flutter.dev/docs/development/data-and-backend/json) page describes the usage of `json_serializable` instead of `built_value`. Are there any reasons to choose `json_serializable` over `built_value`? It would be great if the page describes when to choose which.

**Comment by sfshaza2** [comment]
@johnpryan, can you shed light on whether `json_serializable` or `built_value` is preferred and why?

@shouichi, if you have questions specifically about Flutter Favorites, send an email to the chair of the Flutter Ecosystem Committee (as described in that page).

**Comment by johnpryan** [comment]
This is good feedback. The short answer is that json_serializable is focused specifically on JSON serialization / deserialization, and built_value uses immutable data types (and also supports JSON).

I think both packages are marked as Flutter Favorites now.

**Comment by shouichi** [comment]
It would be great if there is a guideline when to choose which. We migrated from `json_serializable` to `built_value` to generate methods such as `==` and `hashCode`. We found `build_value` was better but a little bit more verbose when generating JSON.

**Comment by sfshaza2** [comment]
@johnpryan, if you have specific advice, I'm happy to add it for you! (Or you can.  :D )

**Comment by johnpryan** [comment]
In the "[Using Code Generation Libraries"](https://flutter.dev/docs/development/data-and-backend/json#serializing-json-using-code-generation-libraries)section, we could add a sentence or two saying that `built_value` is another option if you are interested in immutable data types.

**Comment by sfshaza2** [comment]
It's being addressed in this PR:  https://github.com/flutter/website/pull/3439

**Comment by sfshaza2** [comment]
Thanks for raising this issue, @shouichi! The issue is fixed in the above PR.

**Comment by shouichi** [comment]
Thanks :smile:
