### ISSUE TITLE
Validate firebase.json

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3383]
We're beginning to see builds break due to the fact that we do not run any checks against our firebase.json file.

**Comment by sfshaza2** [comment]
I'm lowering the priority because people can no longer directly edit to master.

**Comment by legalcodes** [comment]
SG

**Comment by legalcodes** [comment]
See https://github.com/flutter/website/pull/3574#pullrequestreview-346968081

**Comment by legalcodes** [comment]
See https://github.com/flutter/website/pull/3558#pullrequestreview-344907309

**Comment by legalcodes** [comment]
See https://github.com/flutter/website/pull/3324/files
