### ISSUE TITLE
Potential updates to "Writing for Flutter and Dart" conventions

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3392]
1. Remove use of forward slash in titles
  - e.g. https://flutter.dev/docs/development/tools/android-studio
2.  Remove use of gerunds in titles
  - e.g. https://flutter.dev/docs/development/tools/android-studio#running-and-debugging

**Comment by sfshaza2** [comment]
Why? We definitely use gerunds in our titles. There is no prohibition about that in the Google Dev Style Guide. Neither is there a prohibition on slashes in headings, though I agree it's not ideal. (Though I don't object to it for "Android Studio / IntelliJ".

@kwalrath, can you weigh in?

**Comment by legalcodes** [comment]
For context: 

<img width="662" alt="comment 1" src="https://user-images.githubusercontent.com/5550175/70858158-fd3e0900-1eb0-11ea-9243-fef20f7d7012.png">
<img width="661" alt="comment 2" src="https://user-images.githubusercontent.com/5550175/70858159-ff07cc80-1eb0-11ea-84b1-e834c3e6c631.png">

**Comment by sfshaza2** [comment]
The slash is not that common in Flutter docs. Just trying to save a few chars. I can be talked out of it.  :)

**Comment by kwalrath** [comment]
I'm not opposed to gerunds anywhere. I'm just pro consistency in lists, whether they be lists of page titles, lists of second-level headings, bulleted lists... So I think legislating gerunds is not a good idea. We should just apply good sense to the titles/headings/list items we use.

In the case of the slash, that's an actual Google style thing. I think a slash might sometimes be the best choice, but we should avoid it where possible. It looks unprofessional (especially with spaces around it) and can be confusing.

**Comment by sfshaza2** [comment]
I first created it without the spaces, but then later added the spaces. This just shows how unconvinced I was.  :D. I agree, let's not legislate gerunds, only consistency.  :D

**Comment by legalcodes** [comment]
I'm all onboard with consistency, which is why I still lack clarity on how we're handling this. Originally, we suggested that I remove the gerund from the analogous section in /desktop :

![Screen Shot 2019-12-16 at 11 16 23 AM](https://user-images.githubusercontent.com/5550175/70935733-b6a5f700-1ff5-11ea-9e34-4730c757ef48.png)

Similarly, we removed the forward slash from the analogous section in /desktop :
![Screen Shot 2019-12-16 at 11 18 35 AM](https://user-images.githubusercontent.com/5550175/70935776-d2a99880-1ff5-11ea-83e4-26af3fbedb88.png)

Doesn't this leave us with inconsistency across pages where there *should* be consistency?

**Comment by legalcodes** [comment]
In this case, it appears to me that If we want to be consistent across pages as well as within pages, then we need to pick one: gerunds in titles, or no gerunds in titles. On the other hand, if we don't care about consistency across pages then we merely evaluate consistency within a page. LMK if I've missed other options here.

**Comment by legalcodes** [comment]
Addressed in https://github.com/flutter/website/pull/3445

Plenty of AIs from this fruitful discussion! Will continue such threads elsewhere (not in GitHub issues)
