### ISSUE TITLE
'Desktop support for Flutter' page issue

### ISSUE THREAD

**Issue by tirth-aubergine** [flutter/website#3404]
Page URL: https://flutter.dev/desktop.html
Page source: https://github.com/flutter/website/tree/master/src/desktop.md

Description of issue:
Clicking on Flutter Gallery link under https://flutter.dev/desktop#samples shows 404

**Comment by tirth-aubergine** [comment]
<img src="https://imgur.com/lHihJBi.png" />

**Comment by sfshaza2** [comment]
Yes, this link goes to a deprecated directory, which is (evidently) now private. Can you fix, @legalcodes?

**Comment by timsneath** [comment]
This should now go to https://github.com/flutter/samples/tree/master/gallery/gallery, I think, now the new gallery has been completed and merged.

**Comment by legalcodes** [comment]
Sure, will fix. Thanks!
