### ISSUE TITLE
'Desktop support for Flutter' page issue

### ISSUE THREAD

**Issue by ksilz** [flutter/website#3407]
Page URL: https://flutter.dev/desktop.html
Page source: https://github.com/flutter/website/tree/master/src/desktop.md

According to the [**1.12** release notes](https://medium.com/flutter/announcing-flutter-1-12-what-a-year-22c256ba525d), Flutter for Mac is in Alpha with that release. So the second paragraph is wrong &mdash; it mentions **1.13**.

**Comment by domesticmouse** [comment]
Desktop support is available in the master and dev flutter channels. Flutter master channel is currently version 1.13.1-pre. This is what we mean by desktop being available as alpha in Flutter 1.13. Sorry for the confusion.

**Comment by sfshaza2** [comment]
Yes, @domesticmouse is right, but I agree that this is confusing. I have edited the Medium article to say "the master and dev channels of 1.13." 

Closing.
