### ISSUE TITLE
'Basic Flutter layout concepts' page issue

### ISSUE THREAD

**Issue by chas-dev** [flutter/website#3408]
Page URL: https://flutter.dev/docs/codelabs/layout-basics.html
Page source: https://github.com/flutter/website/tree/master/src/docs/codelabs/layout-basics.md

Description of issue:
I've cut and pasted the source code and when I click "Run" I get an error message "Error Compiling to javascript".
As I'm a newbie I'm not sure what to do to resolve it
![Error](https://user-images.githubusercontent.com/50042386/70729116-8c2a1480-1d3d-11ea-81f7-ffdae3191932.png)

**Comment by sfshaza2** [comment]
Hi, @chas-dev! This appears to be the first code example on the layout basics page. You don't have to copy/paste the code. It's already in the DartPad, so all you have to do is to click the **Run** button.

Please let me know if I am not understanding your issue.

**Comment by sfshaza2** [comment]
Closing due to lack of info.
