### ISSUE TITLE
This guide is confusing and incorrect due to breaking changes in new Flutter!

### ISSUE THREAD

**Issue by dkashkin** [flutter/website#3412]
Page URL: https://flutter.dev/docs/development/platform-integration/platform-channels.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/platform-channels.md

Description of issue:

io.flutter.app.FlutterActivity is no longer used. The latest Flutter imports io.flutter.embedding.android.FlutterActivity with completely different API, so the code from the Guide no longer works :(

**Comment by sfshaza2** [comment]
@gaaclarke, can you weigh in?

**Comment by gaaclarke** [comment]
There is a new API for FlutterActivity at `io.flutter.embedding.android.FlutterActivity`.  The old API still works though and will be continue to be supported.  We should update this document and maybe sunset this version of it.  cc @xster @matthew-carroll 

I will say that the subject of the article, platform channels, hasn't changed, just the contextual code around them is on the old version.

**Comment by xster** [comment]
Also https://github.com/flutter/flutter/issues/46855. We should update the website.

**Comment by sfshaza2** [comment]
Thanks for weighing in, guys! I will look at this..
