### ISSUE TITLE
'Supporting the new Android plugins APIs' page issue

### ISSUE THREAD

**Issue by timsneath** [flutter/website#3416]
Page URL: https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/packages-and-plugins/plugin-api-migration.md

Description of issue:
The following URL isn't being correctly converted to a hyperlink. It looks fine on GitHub, so I'm wondering if this might be a `dartdoc` issue? (Is it because of the parentheses, I wonder?)
![image](https://user-images.githubusercontent.com/2319867/70842645-255b3880-1ddb-11ea-96d8-1f2210be329e.png)

**Comment by sfshaza2** [comment]
Nope, it's because I used the wrong macro.  Thanks for pointing it out!
