### ISSUE TITLE
'Take a picture using the camera' startup error

### ISSUE THREAD

**Issue by markowanga** [flutter/website#3417]
Page URL: https://flutter.dev/docs/cookbook/plugins/picture-using-camera.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/plugins/picture-using-camera.md

Description of issue:
E/flutter (17924): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (17924): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (17924): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (17924): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
E/flutter (17924): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
E/flutter (17924): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter (17924): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
E/flutter (17924): #4      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:335:40)
E/flutter (17924): #5      availableCameras (package:camera/camera.dart:81:10)
E/flutter (17924): #6      getFrontCamera (package:aow_eye/main.dart:10:25)
E/flutter (17924): #7      main (package:aow_eye/main.dart:19:29)
E/flutter (17924): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter (17924): #9      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (17924): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (17924): #11     _runZoned (dart:async/zone.dart:1518:10)
E/flutter (17924): #12     runZoned (dart:async/zone.dart:1502:12)
E/flutter (17924): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter (17924): #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter (17924): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter (17924): 

On: Nexus 5X

**Comment by sfshaza2** [comment]
@johnpryan, can you take a look?
