### ISSUE TITLE
Building a Cupertino app with Flutter, Step 10, missing definition of ShoppingCartItem class

### ISSUE THREAD

**Issue by andynovak12** [flutter/website#3420]
The last code sample in step 10 of codelab "Building a Cupertino app with Flutter" uses "ShoppingCartItem", but the class definition for ShoppingCartItem is not part of the codelab instructions. It is in the linked `lib/shopping_cart_tab.dart` file at the end of step though.

**Comment by sfshaza2** [comment]
Subsumed by Building a Cupertino app with Flutter, Step 10, missing definition of ShoppingCartItem class
