### ISSUE TITLE
'Building layouts' page issue

### ISSUE THREAD

**Issue by BilalAlam173** [flutter/website#3422]
Page URL: https://flutter.dev/docs/development/ui/layout/tutorial.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/layout/tutorial.md

Description of issue:
While learning layout in flutter i found a mistake in the docs.
In step 2, We have created a row, Inside an expandable column, and after that there is an Icon and a text, but both icon and text that comes in the last are not wrapped in a column that is why they don't display aligned with the first column (screenshot attached)

![image](https://user-images.githubusercontent.com/19489574/70884615-4e0c4980-1ff8-11ea-8803-5a7e8f616c97.png)

**main.dart**
````
class TitleSction extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new Container(
      padding: const EdgeInsets.all(32),
      child: Row(
        children: [
          Expanded(
            /*1*/
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                /*2*/
                Container(
                  padding: const EdgeInsets.only(bottom: 8),
                  child: Text(
                    'Oeschinen Lake Campground',
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
                Text(
                  'Kandersteg, Switzerland',
                  style: TextStyle(
                    color: Colors.grey[500],
                  ),
                ),
              ],
            ),
          ),
          /*3*/
          Icon(
            Icons.star,
            color: Colors.red[500],
          ),
          Text('41'),
        ],
      ),
    );
  }
}
````

**Comment by BilalAlam173** [comment]
PR that fixes the issue 
https://github.com/flutter/website/pull/3423

**Comment by sfshaza2** [comment]
Thanks for catching *and* fixing, @BilalAlam173!! Can you sign the CLA so I can merge?

**Comment by BilalAlam173** [comment]
Done! @sfshaza2

**Comment by sfshaza2** [comment]
PR is merged. Closing.
