### ISSUE TITLE
'Write your first Flutter app on the web' page issue

### ISSUE THREAD

**Issue by getgoh** [flutter/website#3427]
Page URL: https://flutter.dev/docs/get-started/codelab-web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab-web.md

Description of issue: 
Sample codes that supposedly shows as bold just shows the actual bold tags: 

* \<b>text\</b>
![image](https://user-images.githubusercontent.com/22161412/70937615-933d7500-2012-11ea-9aae-3fc2dc935c6d.png)

* \*\*text\*\*
![image](https://user-images.githubusercontent.com/22161412/70937640-a05a6400-2012-11ea-9914-0f39c092adc8.png)

**Comment by sfshaza2** [comment]
Oops! Thanks, @getgoh

**Comment by sfshaza2** [comment]
Fixed.
