### ISSUE TITLE
Flutter API website sidebar

### ISSUE THREAD

**Issue by mingsai** [flutter/website#3435]
First I just want to say thanks for the quick response to the API website mentioned earlier (in #3362). I live in these docs, and the quick action on the requests are welcome. 

When selecting a document to view the sidebar always resets to the top. This is a bit of a hassle if one is going through the docs sequentially. Better behavior might be to have the sidebar scroll to the currently selected topic area. Love that little link back to code by the way. That rocks and helps one comprehend many of these new ideas.

**Comment by sfshaza2** [comment]
I totally agree, @mingsai!!! Unfortunately, we don't have infrastructure support atm, so PRs welcome.  :D

**Comment by shivam15** [comment]
@sfshaza2 Can i pick this?

**Comment by sfshaza2** [comment]
Absolutely, @shivam15, I've assigned it to you!  :)
