### ISSUE TITLE
More heading differences between table of contents and pages

### ISSUE THREAD

**Issue by ksilz** [flutter/website#3457]
I submitted #3366, #3367, and #3368 where the table of contents had a different heading than the page. That was fixed yesterday. 

Here are some more of these occurrences. The heading in the table of content is named first, then the one from the page. Differences are highlighted in **bold**.
- https://flutter.dev/docs/get-started/codelab: "Write your first app" vs "Write your first Flutter app **, part 1**"
- https://flutter.dev/docs/get-started/flutter-for/android-devs: "Flutter for Android devs" vs "Flutter for Android **developers**"
- https://flutter.dev/docs/get-started/flutter-for/ios-devs: "Flutter for iOS devs" vs "Flutter for iOS **developers**"
- https://flutter.dev/docs/get-started/flutter-for/react-native-devs: "Flutter for React Native devs" vs "Flutter for React Native **developers**"
- https://flutter.dev/docs/get-started/flutter-for/web-devs: "Flutter for web devs" vs "Flutter for web **developers**"
- https://flutter.dev/docs/get-started/flutter-for/xamarin-forms-devs: "Flutter for Xamarin.Forms devs" vs "Flutter for Xamarin.Forms **developers**"
- https://www.dart.dev/guides/language: "Dart language overview" vs "**Overview: the Dart language**"
- https://flutter.dev/docs/get-started/web: "Building a web app" vs "Building a web **application with Flutter**"
- https://flutter.dev/docs/development/ui/layout/tutorial: "Tutorial" vs "Building layouts"
- https://flutter.dev/docs/development/ui/layout/box-constraints: "Box constraints" vs "**Dealing with** box constraints"
- https://flutter.dev/docs/development/ui/interactive: "Adding interactivity" vs "Adding interactivity **to your Flutter app**"
- https://flutter.dev/docs/development/ui/assets-and-images: "Assets and images" vs "**Adding** assets and images"
- https://flutter.dev/docs/development/ui/animations: "Introduction" vs "Introduction **to animations**"
- https://flutter.dev/docs/development/ui/animations/overview: "Overview" vs "**Animations** overview"
- https://flutter.dev/docs/development/ui/animations/tutorial: "Tutorial" vs "**Animations** tutorial"
- https://flutter.dev/docs/development/ui/animations/hero-animations: "Hero animations" vs "Hero Animations" (uppercase "A")
- https://flutter.dev/docs/development/ui/animations/staggered-animations: "Staggered animations" vs "Staggered Animations" (uppercase "A")
- https://flutter.dev/docs/development/ui/advanced/gestures: "Gestures" vs "**Taps, drags, and other** gestures"
- https://flutter.dev/docs/development/data-and-backend/state-mgmt/intro: "Introduction" vs "**State management**"
- https://flutter.dev/docs/development/data-and-backend/state-mgmt/declarative: "Think declaratively" vs "**Start thinking** declaratively"
- https://flutter.dev/docs/development/data-and-backend/state-mgmt/ephemeral-vs-app: "Ephemeral vs app state" vs "**Differentiate between** ephemeral **state and** app state"
- https://flutter.dev/docs/development/data-and-backend/state-mgmt/options: "Options" vs "**List of state management approaches**"
- https://flutter.dev/docs/development/accessibility-and-localization/internationalization: "Internation­alization" vs "Internation­aliz**ing Flutter apps**"
- https://flutter.dev/docs/development/platform-integration/c-interop: "C and C++ interop" vs "**Binding to native code using dart:ffi**"
- https://flutter.dev/docs/development/platform-integration/platform-channels: "Writing platform-specific code" vs "Writing **custom** platform-specific code"
- https://flutter.dev/docs/development/packages-and-plugins/favorites: "Flutter Favorite**s** program" vs "Flutter Favorite program"
- https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration: "Android plugin upgrade" vs "**Supporting the new Android plugins APIs**"
- https://flutter.dev/docs/development/add-to-app: "Introduction" vs "**Add Flutter to existing app**"
- https://flutter.dev/docs/development/add-to-app/android/project-setup: "Project setup" vs "**Integrate a Flutter module into your Android project**"
- https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen: "Adding a single Flutter screen" vs "Adding **a Flutter** screen **to an Android app**"
- https://flutter.dev/docs/development/add-to-app/android/add-flutter-fragment: "Adding a Flutter Fragment" vs "Adding a Flutter Fragment **to an Android app**"
- https://flutter.dev/docs/development/add-to-app/android/add-splash-screen: "Adding a Splash Screen" vs "Adding a **s**plash **s**creen **and launch screen to an Android app**"
- https://flutter.dev/docs/development/add-to-app/ios/project-setup: "Project setup" vs "**Integrate a Flutter module into your iOS project**"
- https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen: "Add a single Flutter screen" vs "Add**ing** **a Flutter** screen **to an iOS app**"
- https://flutter.dev/docs/development/add-to-app/debugging: "Running, debugging, & hot reload" vs "Running, debugging, **and** hot reload"
- https://flutter.dev/docs/development/add-to-app/performance: "Loading sequence and memory" vs "**Load sequence, performance,** and memory"
- https://flutter.dev/docs/development/tools/android-studio: "Android Studio / IntelliJ" vs "Android Studio **and** IntelliJ"
- https://flutter.dev/docs/development/tools/devtools/overview: "Overview" vs "**DevTools**"
- https://flutter.dev/docs/development/tools/devtools/android-studio: "Install from Android Studio / IntelliJ" vs "Install **and run DevTools** from Android **Studio**"
- https://flutter.dev/docs/development/tools/devtools/vscode: "Install from VS Code" vs "Install **and run DevTools** from VS Code"
- https://flutter.dev/docs/development/tools/devtools/cli: "Install from command line" vs "Install **and run DevTools** from **the** command line"
- https://flutter.dev/docs/development/tools/devtools/inspector: "Flutter inspector" vs "**Using the** Flutter inspector"
- https://flutter.dev/docs/development/tools/devtools/timeline: "Timeline view" vs "**Using the** Timeline view"
- https://flutter.dev/docs/development/tools/devtools/memory: "Memory view" vs "**Using the** Memory view"
- https://flutter.dev/docs/development/tools/devtools/performance: "Performance view" vs "**Using the** Performance view"
- https://flutter.dev/docs/development/tools/devtools/debugger: "Debugger" vs "**Using the d**ebugger"
- https://flutter.dev/docs/development/tools/devtools/logging: "Logging view" vs "**Using the** Logging view"
- https://flutter.dev/docs/development/tools/sdk/upgrading: "Upgrading" vs "Upgrading **Flutter**"
- https://flutter.dev/docs/development/tools/sdk/releases?tab=windows: "Releases" vs "**Flutter SDK r**eleases"
- https://flutter.dev/docs/development/tools/sdk/release-notes: "Release notes" vs "**Flutter r**elease notes"
- https://flutter.dev/docs/development/androidx-migration: "AndroidX migration" vs "AndroidX **M**igration" (uppercase "M")
- https://flutter.dev/docs/testing/debugging: "Debugging tools" vs "Debugging **Flutter apps**"
- https://flutter.dev/docs/testing/code-debugging: "Debugging apps programmatically" vs "Debugging **Flutter** apps programmatically"
- https://flutter.dev/docs/testing/errors: "Handling errors" vs "Handling errors **in Flutter**"
- https://flutter.dev/docs/testing: "Testing" vs "Testing **Flutter apps**"
- https://flutter.dev/docs/perf: "Overview" vs "**Performance**"
- https://flutter.dev/docs/perf/app-size: "App size" vs "**Measuring your a**pp **'s** size"
- https://flutter.dev/docs/perf/rendering: "Overview" vs "**Improving rendering performance**"
- https://flutter.dev/docs/perf/rendering/ui-performance: "Performance profiling" vs "**Flutter p**erformance profiling"
- https://flutter.dev/docs/deployment/cd: "Continuous deployment" vs "Continuous **delivery with Flutter**"
- https://flutter.dev/docs/resources/bootstrap-into-dart: "Dart resources" vs "**Bootstrap into Dart**"
- https://flutter.dev/docs/resources/compatibility: "Compatibility policy" vs "**Flutter c**ompatibility policy"
- https://flutter.dev/docs/resources/platform-adaptations: "Platform adaptations" vs "Platform **specific behaviors and** adaptations"
- https://flutter.dev/docs/resources/books: "Books" vs "Books **about Flutter**"
- https://flutter.dev/docs/reference/widgets: "Widget index" vs "**Flutter w**idget index"

**Comment by legalcodes** [comment]
+1, thanks @ksilz for pointing this out.

**Comment by sfshaza2** [comment]
I'm closing this for now. (We intentionally do make the names shorter in the sidenav and don't necessarily want to change the corresponding name in the doc, unless it's somehow misleading.)
