### ISSUE TITLE
"Performance & optimization" section: Table of content out of sync when browsing

### ISSUE THREAD

**Issue by ksilz** [flutter/website#3458]
The table of contents doesn't sync with the actual navigation in the "Performance & optimization" section, apart from the "Overview" section. If you select any other page, then that page shows &mdash; but the table of contents jumps back to "Overview". 

Below you can see the "Rendering performance / Performance best practices" section shown, but only "Overview" is highlighted on the page:

![Flutter doc page navigation out of sync](https://user-images.githubusercontent.com/1061209/71166732-41336400-224b-11ea-9df4-728368fb73f8.png)

I recorded a [video of this behavior](https://www.screencast.com/users/KarstenSilz/folders/Default/media/a6aa63c7-f316-4209-a2a3-1a2cd849a8ea).

The error shows in macOS Catalina 10.15.2 with Safari 13.0.4, Chrome 79.0.3945.88, and Firefox 71.

**Comment by sfshaza2** [comment]
OK, that is strange!!! Thanks for recording that, @ksilz! I created that section fairly recently and must have missed something in the setup.

**Comment by legalcodes** [comment]
There may also be some nav behavior that's broken apart from "Performance best practices" -- a general click through of the sidenav revealed (at least) the following:

1. Inconsistent highlighted sidenav menu items

Click on: 
Tools & techniques > Flutter SDK > Upgrading ("Upgrading" IS highlighted in blue)
Tools & techniques > Flutter SDK > Releases ("Releases is NOT highlighted in blue)
Tools & techniques > Flutter SDK > Breaking changes ("Breaking changes" IS highlighted in blue)

2. Inconsistent collapsing behavior

Click on: 
Performance & optimization > Rendering performance > Overview ("Rendering performance" submenu collapses)
Performance & optimization > Rendering performance > Performance best practices ("Rendering performance" submenu collapses)
Performance & optimization > Rendering performance > Performance profiling ("Rendering performance" submenu collapses)

Compare this behavior to all the other submenus, which do not collapse when a submenu item is clicked.

**Comment by legalcodes** [comment]
See also https://github.com/flutter/website/issues/2678

**Comment by micpap25** [comment]
Personally I don't experience this issue, Windows 10 Google Chrome.
I think this can be closed unless someone else is having this problem.

**Comment by sfshaza2** [comment]
Thanks, @micpap25! I will close, but reopen if this pops up again.
