### ISSUE TITLE
Move crash reporting page to docs

### ISSUE THREAD

**Issue by timsneath** [flutter/website#3459]
Looking at the first-run experience, the screen below sends Flutter users to [this wiki page](https://github.com/flutter/flutter/wiki/Flutter-CLI-crash-reporting):
![image](https://user-images.githubusercontent.com/2319867/71191277-f4e02800-223a-11ea-9357-a2e9c5e096d8.png)

We should move that page to the docs, as part of the general goal to not have non-contributors relying on the wiki for core experiences.

**Comment by sfshaza2** [comment]
Yes, indeed! Once we add the page, eng will need to point to it, so it will need another bug filed on the flutter/flutter repo.

**Comment by sfshaza2** [comment]
Tim, did you want to also move the "Welcome to Flutter" page itself?

**Comment by timsneath** [comment]
The page itself? Sorry: which page did you mean?
