### ISSUE TITLE
'Continuous delivery with Flutter' page issue

### ISSUE THREAD

**Issue by Squalex** [flutter/website#3464]
Page URL: https://flutter.dev/docs/deployment/cd.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/cd.md

Description of issue:
The link https://raw.githubusercontent.com/brianegan/flutter_redux/master/.gitlab-ci.yml is broken.

**Comment by sfshaza2** [comment]
Grumble. You are correct, @Squalex! I thought I submitted a PR in December to remove that link. @brianegan migrated that repo.
