### ISSUE TITLE
'Adding a splash screen and launch screen to an Android app' page issue

### ISSUE THREAD

**Issue by kRadius** [flutter/website#3471]
Page URL: https://flutter.dev/docs/development/add-to-app/android/add-splash-screen.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/add-to-app/android/add-splash-screen.md

Description of issue:
It seems like the language is Java. if that is true, we should call `onTransitionComplete.run()` rather than `onTransitionComplete()`
![1577100355986-image](https://user-images.githubusercontent.com/8802501/71356116-331f7380-25bc-11ea-8158-7c5c35f21a3f.png)

**Comment by sfshaza2** [comment]
Can you confirm, @gaaclarke?

**Comment by gaaclarke** [comment]
Yes, `onTransitionComplete.run()` is kosher.  There may be a situation where `.run()` could be omitted, maybe with a later version of Java.  I couldn't find any reference to it existing though.  So, `onTransitionComplete.run()` is correct and it should be changed.

**Comment by sfshaza2** [comment]
Thanks, @gaaclarke! I, therefore, LGTM this change.

**Comment by sfshaza2** [comment]
Oops, it's not a PR.  :D

**Comment by sfshaza2** [comment]
Thanks, @gaaclarke, for fixing!
