### ISSUE TITLE
Mistake in step 8 of Building a Cupertino app with Flutter: wrong method name

### ISSUE THREAD

**Issue by Kepa357** [flutter/website#3476]
https://codelabs.developers.google.com/codelabs/flutter-cupertino/#7

"Update the build() method in the _SearchTabState class." 
should be 
"Update the build() method in the _ShoppingCartTabState class."

**Comment by sfshaza2** [comment]
Ooh, another good catch, @Kepa357! Thanks!

**Comment by sfshaza2** [comment]
Subsumed by https://github.com/flutter/website/issues/4026
