### ISSUE TITLE
'Implicit animations' codelab DartPad issues

### ISSUE THREAD

**Issue by maganap** [flutter/website#3481]
Page URL: https://flutter.dev/docs/codelabs/implicit-animations.html
Page source: https://github.com/flutter/website/tree/master/src/docs/codelabs/implicit-animations.md

**Description of issue:**
DatPad examples don't seem to be working properly for this codelab. When hitting the Run button, an error is reported to the console.

```
Error compiling to JavaScript:
DetailedApiRequestError(status: 400, message: Error: Could not resolve the package 'flutter_web' in 'package:flutter_web/material.dart'.
Error: Could not resolve the package 'flutter_web_test' in 'package:flutter_web_test/flutter_web_test.dart'.
Error: Could not resolve the package 'flutter_web_ui' in 'package:flutter_web_ui/ui.dart'.
```

I can run other DartPad examples on this website without issues though. The troubleshooting page doesn't seem to help on this.

@ Google Chrome Version 79.0.3945.88, MacOS Catalina 10.15.2

![Screenshot 2019-12-27 at 19 43 16](https://user-images.githubusercontent.com/6942131/71528883-4e52f180-28e2-11ea-800f-634329417d1d.png)

**Comment by legalcodes** [comment]
Thanks @maganap I will look into this.
