### ISSUE TITLE
'Persist data with SQLite' page issue

### ISSUE THREAD

**Issue by AntoineHo6** [flutter/website#3482]
Page URL: https://flutter.dev/docs/cookbook/persistence/sqlite.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/persistence/sqlite.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

The example doesn't seem to run properly. The prints don't show up.

**Comment by FabioPagano** [comment]
See here if it can help: https://github.com/flutter/website/issues/3498
