### ISSUE TITLE
'Flutter SDK releases' page issue

### ISSUE THREAD

**Issue by godslave05** [flutter/website#3485]
Page URL: https://flutter.dev/docs/development/tools/sdk/releases.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/releases.md

Description of issue: 
I can not see the versions . It only shows loading. From developer option I found this

storage.googleapis.com/flutter_infra/releases/releases_windows.json:1 Failed to load resource: net::ERR_TIMED_OUT
storage.googleapis.com/flutter_infra/releases/releases_macos.json:1 Failed to load resource: net::ERR_TIMED_OUT
storage.googleapis.com/flutter_infra/releases/releases_linux.json:1 Failed to load resource: net::ERR_TIMED_OUT

**Comment by sfshaza2** [comment]
I don't reproduce this issue, @godslave05. Can you still reproduce it? If so, please let us know what your environment is: computer, OS, browser, etc. Please paste the results of `flutter doctor` into this bug.  Thanks!

**Comment by godslave05** [comment]
It seems [storage.googleapis.com](url) CDN was blocked in my region for sometime. It's ok now. I can access FLutter SDK releases and also update my pub.dev packages. 

Do you still  need  the result of` flutter doctor` ?

**Comment by sfshaza2** [comment]
No, that's fine, we don't need output of `flutter doctor`. I see, so it was physically prohibited in your area. Interesting.

**Comment by sfshaza2** [comment]
Closing.
