### ISSUE TITLE
'Performance best practices' page issue

### ISSUE THREAD

**Issue by Vadaski** [flutter/website#3486]
Page URL: https://flutter.dev/docs/perf/rendering/best-practices.html
Page source: https://github.com/flutter/website/tree/master/src/docs/perf/rendering/best-practices.md

Description of issue:

The sidebar highlighting is abnormal due to indentation errors in the Rendering performance section of the md document sidebar.

- title: Rendering performance
      permalink: /docs/perf/rendering
      children:
      - title: Overview
        permalink: /docs/perf/rendering
        match-page-url-exactly: true
      - title: Performance best practices
        permalink: /docs/perf/rendering/best-practices
      - title: Performance profiling
        permalink: /docs/perf/rendering/ui-performance

=>

- title: Rendering performance
      permalink: /docs/perf/rendering
      children:
        - title: Overview
          permalink: /docs/perf/rendering
          match-page-url-exactly: true
        - title: Performance best practices
          permalink: /docs/perf/rendering/best-practices
        - title: Performance profiling
          permalink: /docs/perf/rendering/ui-performance

**Comment by Vadaski** [comment]
link：
https://github.com/flutter/website/blob/master/src/_data/sidenav.yml

**Comment by micpap25** [comment]
Personally on Windows 10 Google Chrome I no longer seem to have this issue, I think it can be closed.

**Comment by parlough** [comment]
This section was reworked in https://github.com/flutter/website/pull/6977 so this is no longer relevant. Thanks for opening an issue!
