### ISSUE TITLE
Validate Jekyll frontmatter

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3489]
We've recently encountered some problems due to the fact that we don't validate frontmatter:

https://github.com/flutter/website/issues/3262
https://github.com/flutter/website/issues/3488
https://github.com/flutter/website/pull/3700
https://github.com/flutter/website/issues/3727 - check for required description
https://github.com/flutter/website/pull/3783/files#diff-c805d22f83241a8d8112f62b01d6b511L4 - invalid frontmatter in `container-color.md`

To prevent issues like these in the future, we should consider passing the following flags in `serve.sh` and `build_check_deploy.sh`

`bundle exec jekyll build --strict_front_matter`
or
`bundle exec jekyll serve --strict_front_matter`

**Comment by sfshaza2** [comment]
This sounds like a good idea. @legalcodes, does this perceptively slow down the build? Also, can it give us any false positives?

**Comment by legalcodes** [comment]
Great questions! Let's be sure to investigate both if we decide to take this up.
