### ISSUE TITLE
'Persist data with SQLite' page issue

### ISSUE THREAD

**Issue by arbaazaj** [flutter/website#3498]
Page URL: https://flutter.dev/docs/cookbook/persistence/sqlite.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/persistence/sqlite.md

Description of issue: Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.

**Solution:** Adding this line **"WidgetsFlutterBinding.ensureInitialized();"** without quotes in **main()** function fixes the issue please add this line in the main code.

**Comment by sfshaza2** [comment]
Good catch, thanks!

**Comment by JuYeong0413** [comment]
Fixed in #4099

**Comment by sfshaza2** [comment]
Closing.
