### ISSUE TITLE
Remove onCreate from docs

### ISSUE THREAD

**Issue by bradyt** [flutter/website#3499]
There is still `onCreate` at https://github.com/flutter/website/blob/13d8aab863d205d3eba2a126cbaa98fca4198669/src/docs/development/platform-integration/platform-channels.md. Removing it would seem to be consistent with changes at https://github.com/flutter/website/pull/3494.

Docs page is at https://flutter.dev/docs/development/platform-integration/platform-channels?tab=android-channel-kotlin-tab#step-3-add-an-android-platform-specific-implementation.

**Comment by sfshaza2** [comment]
Hi, @bradyt! I've searched the platforms-channels page, both the generated URL and the source code. I see no instances of onCreate(). Are you still seeing this?

**Comment by sfshaza2** [comment]
Confirms that it's gone. Closing.
