### ISSUE TITLE
'Adding a Flutter screen to an Android app' page issue

### ISSUE THREAD

**Issue by TheHemantKaushik** [flutter/website#3507]
Page URL: https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/add-to-app/android/add-flutter-screen.md

**System details:**
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (4 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

**Description of issue:**
`FlutterActivity.BackgroundMode.transparent` is not available and `FlutterActivityLaunchConfigs.BackgroundMode.transparent` is not working because `FlutterActivityLaunchConfigs` is package private.

**Comment by TheHemantKaushik** [comment]
For now I'm using a workaround. It is declare `<item name="android:windowIsTranslucent">true</item>` in `AndroidManifest.xml` under style declared for flutter activity.

**Comment by sfshaza2** [comment]
@xster, can you confirm?

**Comment by xster** [comment]
Confirmed. But merging into https://github.com/flutter/flutter/issues/45747
