### ISSUE TITLE
'TalkBack on Windows' issue

### ISSUE THREAD

**Issue by yama3nomori** [flutter/website#3509]
Simple application made by 'flutter create' command occured following:

When TalkBack is on, application crashed that user touch bottom of display on Android device.
Application doesn't crash that user touch side and top of display.

When TalkBack is off, it's no problem.

**Comment by legalcodes** [comment]
Thanks @yama3nomori for raising this issue! It looks like this issue relates to output from the `flutter create` command -- if so, I believe this should be an issue in https://github.com/flutter/flutter. Let me know if that helps!

**Comment by yama3nomori** [comment]
Thanks for your advice.
I'll send it to that page again.
