### ISSUE TITLE
'Scrolling widgets' page issue

### ISSUE THREAD

**Issue by anandmohan211** [flutter/website#3512]
Page URL: https://flutter.dev/docs/development/ui/widgets/scrolling.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/widgets/scrolling.md

Description of issue:
the scrolling effect of this page is not smooth

**Comment by sfshaza2** [comment]
The page scrolls perfectly for me. I'm assuming this is an ironic joke.  :). Please re-open, with more info (such as platform, maybe a videos showing the behavior), if not.
