### ISSUE TITLE
Add `FocusScopeNode` to the cookbook chapter about Forms

### ISSUE THREAD

**Issue by escamoteur** [flutter/website#3522]
Hi,

I stumbled about this awesome new class by pure chance. It make the whole focus handling a breeze.
I thin we should add this ASAP because its such a common functionality

Cheers
Thomas

**Comment by atsansone** [comment]
This was added to a [Focus page](https://docs.flutter.dev/ui/advanced/focus#focusnode-and-focusscopenode) with https://github.com/flutter/website/pull/6243. Closing this issue.
