### ISSUE TITLE
'AppBar Basics' page issue

### ISSUE THREAD

**Issue by Diaa-Abdelfadeel** [flutter/website#3532]
Page URL: https://flutter.dev/docs/catalog/samples/basic-app-bar.html
Page source: https://github.com/flutter/website/tree/master/src/docs/catalog/samples/basic-app-bar.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by legalcodes** [comment]
Thanks for raising this issue @Diaa-Abdelfadeel -- I don't see a description of the issue yet. Did you mean to add one?

**Comment by sfshaza2** [comment]
No issue provided. Closing.
