### ISSUE TITLE
Consider redirecting scrollable_alert_dialog to scrollable-alert-dialog

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#3554]
#3516 moved /docs/release/breaking-changes/scrollable_alert_dialog to /docs/release/breaking-changes/scrollable-alert-dialog, and we're getting a fair number of 404s for the underscore version of the name.

(This is the 3rd item on this week's 404 report.)

**Comment by sfshaza2** [comment]
Actually, I'd prefer to add it to our redirect list.  :D
