### ISSUE TITLE
Investigate and document hot reload limitations when using state management packages

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#3566]
This is a request for Flutter DevRel with implications to the website. Feel free to move it to a more appropriate tracker. 

In the Q4 2019 user survey, there are multiple reports about hot reload not working as intended when using certain statement management packages/techniques.  For example:

Survey Question: What are some of the reasons you know of that would cause hot reload to not work as expected?

Answers:
- "State changes (the BLoC architecture, for example, makes it hard to go back to the previous state after a hot reload)"
- "Bloc library doesn't always like hot reload"
- "Provider will not sync after modifications required Hot restart"
- "As we work with redux, and redux loads its dependencies on app startup, hot reload only reloads the current widget tree, so thats the main reason it doesn't work for us when we change business logic as it's mainly stored in the redux flow." 

It would be useful to better understand those limitations and teach developers of those packages how to write their code in a way to maximize reloadability.

Cc: @filiph @Sfshaza

**Comment by InMatrix** [comment]
Hi @filiph, I wonder if you are aware of any _gotchas_ about doing hot reload when a statement management package (e.g., provider) is used? I'm trying to substantiate the user feedback cited in the issue. So far, I found this issue: https://stackoverflow.com/questions/56580988/flutter-state-is-lost-on-hot-reload-when-using-provider. Should we talk about such issues in the hot reload doc?

**Comment by InMatrix** [comment]
#3964 doesn't appear to address this issue. I'd be fine if DevRel decides to close this issue due to lack of information, but  #3964 should not be the reason to close it.

**Comment by atsansone** [comment]
#3964 covered two state-related special cases:
- https://docs.flutter.dev/tools/hot-reload#previous-state-is-combined-with-new-code
- https://docs.flutter.dev/tools/hot-reload#recent-code-change-is-included-but-app-state-is-excluded

If you have other conditions that you would like to see covered, please provide more complete use cases. Then, @johnpryan , @craiglabenz , @khanhnwin , or @domesticmouse would need to chime in. 

I'm closing this for now as it's three years old as well.

**Comment by domesticmouse** [comment]
The path forward here is probably raise bugs on the state management libraries to incorporate hot reload. 

The `flutter_animate` package is brilliant in this regard, restarting all animations when a hot reload is triggered.
