### ISSUE TITLE
'Continuous delivery with Flutter' Replace APK by App Bundle

### ISSUE THREAD

**Issue by woprandi** [flutter/website#3571]
Page URL: https://flutter.dev/docs/deployment/cd.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/cd.md

The Android tutorial specify how to upload APK using Fastlane but it should be modified for App bundles since it's the recommended format to push to the Play Store. 
Fastlane is now compatible with the App bundle format : https://github.com/fastlane/fastlane/issues/15053

**Comment by sfshaza2** [comment]
Yes, this makes sense (and PRs are welcome). :) Thx

**Comment by woprandi** [comment]
Done. I hope it helps 
https://github.com/flutter/website/pull/3572

**Comment by woprandi** [comment]
The PR has been merged
