### ISSUE TITLE
'Animate a page route transition' page issue

### ISSUE THREAD

**Issue by vstyler96** [flutter/website#3573]
Page URL: https://flutter.dev/docs/cookbook/animation/page-route-animation.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/animation/page-route-animation.md

Description of issue:
Dart SDK is not working for preview

**Comment by legalcodes** [comment]
Thanks @vstyler96 for raising this! I wasn't able to identify the page issue -- the embedded DartPad example seems to be running fine (in Chrome and Firefox). Can you be more specific about the steps to reproduce the problem you observed?

**Comment by sfshaza2** [comment]
I'm wondering what's up. We got this bug yesterday:  https://github.com/flutter/website/issues/3567

But, so far, can't reproduce it without more info.

**Comment by sfshaza2** [comment]
Closing.
