### ISSUE TITLE
Supply a new callBack onValidate(String val){}

### ISSUE THREAD

**Issue by Joseph-Nathan** [flutter/website#3578]
Page URL: https://flutter.dev/docs/cookbook/forms/text-field-changes.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/forms/text-field-changes.md

Description of issue:
if you can supply this callback which return <String> value when Validate && <String>null when inValidate ;

**Comment by sfshaza2** [comment]
@Joseph-Nathan, it's not clear what you are asking for. Can you provide more detail?

**Comment by sfshaza2** [comment]
Closing.
