### ISSUE TITLE
'Persist data with SQLite' page issue

### ISSUE THREAD

**Issue by faisalCoding** [flutter/website#3583]
Page URL: https://flutter.dev/docs/cookbook/persistence/sqlite.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/persistence/sqlite.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by legalcodes** [comment]
Hi @faisalCoding thanks for raising the issue. Did you mean to include a "Description of issue" section?

**Comment by sfshaza2** [comment]
Closing.
