### ISSUE TITLE
docs.flutter.io should focus the search box on page load

### ISSUE THREAD

**Issue by tvolkert** [flutter/website#3586]
Users that want to click around won't be affected, but those that want to search will rejoice 😄 

/cc @sethladd

**Comment by parlough** [comment]
There are some [accessibility concerns](https://www.a11yproject.com/checklist/#avoid-using-the-autofocus-attribute) with auto focus, however we can implement focus of the search bar with a `/` keybinding similar to other sites, including dart.dev and dartdoc (api.dart.dev/api.flutter.dev).

I opened https://github.com/flutter/website/issues/8996 to track this work.
