### ISSUE TITLE
Add documentation about internet permissions

### ISSUE THREAD

**Issue by natebosch** [flutter/website#3592]
Users get confused when code that works in debug mode stops working in release mode. A few of them end up looking for help in the `package:http` repo (likely since it has a google-able name) but that repo is not flutter specific.

https://github.com/dart-lang/http/issues/185
https://github.com/dart-lang/http/issues/258
https://github.com/dart-lang/http/issues/254

We can [add some documentation](https://github.com/dart-lang/http/pull/261) in that repo - but since flutter owns the behavior of `flutter create` it would be better to point to some documentation here than to make concrete statements that could be invalidated.

Does any such documentation exist already? Can we add some?

I'm not sure if `android.permission.INTERNET` or `android:usesCleartextTraffic` or both are relevant.

**Comment by natebosch** [comment]
Looks like there may also be things to document about flutter on desktop. It could also be worth documenting or linking to documentation about various restrictions like CORS that authors may hit when working with flutter web and how that may be different from desktop or mobile.

Still hoping for some canonical flutter documentation on this to point to. We get a lot of questions about this in the `package:http` issue tracker.

**Comment by singhabhijeet13** [comment]
i am facing http issue with Andriod R, code is working fine in simulated Andriod R device but i am getting http timeout in Andriod device. i have already added the permission android.permission.INTERNET.

**Comment by hamzaehsansatti** [comment]
@singhabhijeet13  first of connect your mobile to your computer then after that  open xampp/or other and connect to server after that open project in studio and run the project. It will work it work for me

**Comment by atsansone** [comment]
@johnpryan : Would you have any insight here? Not sure what I could add nor where I would add it.

**Comment by johnpryan** [comment]
This page has some info: https://docs.flutter.dev/data-and-backend/networking

**Comment by johnpryan** [comment]
I'm going to close this, please comment if the docs on the [networking](https://docs.flutter.dev/data-and-backend/networking) page need more details.
