### ISSUE TITLE
Add information how to use dart without flutter

### ISSUE THREAD

**Issue by rowild** [flutter/website#3593]
## Use case

In order to learn flutter properly, everyone will sooner or later come into the situation, where she/he has to setup a pure Dart project. If there is only flutter installed, the paths to the included `dart` and `pub` programs are not automatically defined. Therefore I would suggest to add a little more info in the setup section that explains how to setup Dart and pub.

## Proposal for the setup on a Mac (sorry, I do not have Windows)

If you need to work with Dart alone, you can use the included `Dart` and `pub` programs, which reside in the `[path-to-your-flutter-parent-directory]/flutter/bin/cache/dart-sdk/bin` folder. For easy access on the terminal, create an alias for each in your `.bash_profile`:
```
alias dart=[path-to-your-flutter-parent-directory]/flutter/bin/cache/dart-sdk/bin/dart
alias pub=[path-to-your-flutter-parent-directory]/flutter/bin/cache/dart-sdk/bin/pub
```
If you need `stagehand`(which is needed to create web projects with flutter), you must also ad the `[path-to-your-flutter-parent-directory]/flutter/bin/cache/dart-sdk/bin` to your $PATH variable:
```
export PATH="$PATH:[path-to-your-flutter-parent-directory]/flutter/bin/cache/dart-sdk/bin"
```

**Comment by thosakwe** [comment]
From an outsider's perspective, I think it's fair to say that there is already a lot of information on how to use Dart without Flutter - the entire https://dart.dev site. I also think it's fair to expect users to read the documentation in entirety - [this page](https://flutter.dev/docs/resources/bootstrap-into-dart) in the Flutter docs has many links to the main Dart page.

**Comment by rowild** [comment]
The problem back then arose that it was totally unclear whether dart had to be installed separately alongside flutter or not. It was my assumption that it had to be installed, because it nowhere mentioned that flutter installs its own version of dart.

This was only made clear in the first answer to this issue. And according to that answer this whole issue's topic should be renamed to "Is it necessary to install dart alongside flutter?" - Answer: "No. Flutter comes packaged with Dart."

That would be clear like blue sky and should be (/ have been? [ don't know: is it in the meantime?]) mentioned it in the docu. That way no misunderstanding can arise.
