### ISSUE TITLE
Move "How to Collect and Read Timeline Traces" into flutter.dev

### ISSUE THREAD

**Issue by liyuqian** [flutter/website#3595]
Move the section [How to Collect and Read Timeline Traces](https://medium.com/flutter/profiling-flutter-applications-using-the-timeline-a1a434964af3) in the Medium article [Profiling Flutter applications](https://medium.com/flutter/profiling-flutter-applications-using-the-timeline-a1a434964af3) to our website [flutter.dev](https://flutter.dev).

Simplify it a little bit (e.g., separate it into two parts, Collect and Read), so developers can quickly figure out how to collect traces for performance issue reporting.

Also remember to add `--trace-skia` to it!

Finally update our performance issue template to reference our website instead of the Medium article.

**Comment by atsansone** [comment]
As DevTools replaced Observatory, this information is now available in https://docs.flutter.dev/perf/shader. This was fixed in https://github.com/flutter/website/pull/4430. Closing issue.
