### ISSUE TITLE
Adaptations page contains incorrect text for iconography

### ISSUE THREAD

**Issue by WolfgangSenff** [flutter/website#3598]
At this link:
https://flutter.dev/docs/resources/platform-adaptations#iconography

It says Android has horizontal overflow dots, but the image shown has vertical. Given my Android device presently has vertical, my guess is the text is wrong, but it's possible the image is.

**Comment by micpap25** [comment]
This issue is fixed on the link, and should be closed.

**Comment by aromalanil** [comment]
@sfshaza2 This issue can be closed.
