### ISSUE TITLE
Creating the flutter docs via the docs.sh script on a windows os

### ISSUE THREAD

**Issue by md-weber** [flutter/website#3601]
I can't create the documentation of flutter locally on my windows machine to test my documentation changes.

If I try to run docs.sh after I run flutter doctor I get the error message that it cannot find pub file. 
![image](https://user-images.githubusercontent.com/8026644/61586488-8fbfd200-abc9-11e9-94fc-ab2b5bd3a622.png)
![image](https://user-images.githubusercontent.com/8026644/61586500-f644f000-abc9-11e9-94e1-28fefcb89b7d.png)

I change the pub file to pub.bat it crashes later in the dartdoc.dart where I found the following snippet.
```Dart
/// This will only work on UNIX systems, not Windows. It requires that 'git' be
/// in your path. It requires that 'flutter' has been run previously. It uses
/// the version of Dart downloaded by the 'flutter' tool in this repository and
/// will crash if that is absent.
```

![image](https://user-images.githubusercontent.com/8026644/61586495-d6adc780-abc9-11e9-90cc-dc78a7fc3b56.png)

So it seems that currently on Windows OS it is not possible to create the docs.

**Comment by sfshaza2** [comment]
@md-weber, let me make sure I understand correctly. You are trying to create Dart docs for your code using the dartdoc tool? For example:

```
pub global activate dartdoc
dartdoc
```
And the source for the docs that you want to generate is located in /lib?  (Code in /lib/src is private and won't be generated unless exported from files in /lib.)

It should work in Windows. You might find [this page useful](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#api-documentation).

**Comment by md-weber** [comment]
Hi @sfshaza2,
unfortunatly I changed my OS in the meantime so I cannot try it anymore for windows.

If no one else has this problem, I think we can close this issue.
