### ISSUE TITLE
Wrong instructions in Write Your First Flutter App, part 1

### ISSUE THREAD

**Issue by j-m-hoffmann** [flutter/website#3603]
The instructions say:
```dart
class RandomWords extends StatefulWidget {
  @override
  RandomWordsState createState() => RandomWordsState();
}
```

but it needs to be:

```dart
class RandomWords extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => RandomWordsState();
}
```

or:

```dart
class RandomWords extends StatefulWidget {
  @override
  createState() => RandomWordsState();
}
```

**Comment by arps18** [comment]
@kf6gpe @sfshaza2 @legalcodes I would like to work on the issue!

**Comment by sfshaza2** [comment]
Hi, @j-m-hoffmann! How did you know that my very next task is to update the getting started codelabs?! But, if you would like to fix this, I will hold off.  :)

**Comment by sfshaza2** [comment]
The linter complains if no return type is specified, so I replace with `State<RandomWords> `.

**Comment by sfshaza2** [comment]
Fixed.
