### ISSUE TITLE
Document how to use pump to test animations

### ISSUE THREAD

**Issue by tarobins** [flutter/website#3604]
I have, after being stuck and learning myself from @Hixie, had to inform several people that when testing animations it's often necessary to use the pattern

```
tester.pump();
tester.pump(Duration(...));
```

to get the animation to start before 'running' the animation for some time.

I think this pattern should be somewhere in the testing cookbooks.

**Comment by legalcodes** [comment]
Thanks @tarobins for raising this issue!

For reference when we take this up:
https://flutter.dev/docs/cookbook/testing/widget/introduction#note

**Comment by sfshaza2** [comment]
@legalcodes, are you suggesting that this is already covered? It's not clear from your comment.

**Comment by legalcodes** [comment]
@sfshaza2 I have the same question -- is this doc falling short in any of the following areas?

1. Poorly surfaced and/or hard to find (perhaps it needs to be linked from our animations docs more prominently
2. Needs more examples 
3. Should have its own dedicated section (currently it appears in a "Note" subsection)

All thoughts welcome @tarobins @sfshaza2

**Comment by micpap25** [comment]
It looks like @sfshaza2 fixed this on April 14th, I think this can be closed now.

**Comment by sfshaza2** [comment]
Thx!
