### ISSUE TITLE
Writing custom platform-specific code documentation is outdated

### ISSUE THREAD

**Issue by mm44m6** [flutter/website#3610]
Hi!

I was following the tutorial in the [Writing custom platform-specific code](https://flutter.dev/docs/development/platform-integration/platform-channels) documentation page and I noticed it is outdated. The following code is not working:

```
 let controller : FlutterViewController = window?.rootViewController as! FlutterViewController
 let batteryChannel = FlutterMethodChannel(name: "samples.flutter.dev/battery",
                                              binaryMessenger: controller.bynaryMessenger)
```

Xcode throws the following error

`Value of type 'FlutterViewController' has no member 'bynaryMessage'`

And it's due to the fact that neither FlutterViewController or FlutterBinaryMessenger have this method. I changed the binaryMessenger value to FlutterViewController (or, in this case, controller) and it started working. Maybe this method was excluded from the latter version of the Flutter SDK?

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/3843. Closing.
