### ISSUE TITLE
write your first app Part1. `const` keyword are disappearing between subparts 3 and 4

### ISSUE THREAD

**Issue by ngouy** [flutter/website#3612]
Here https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#2

We are told to copy-paste some code into our main.dart including :
```dart
        appBar: AppBar(
          title: const Text('Welcome to Flutter'),
        ),
        body: const Center(
          child: const Text('Hello World'),
        ),
```

On the next page, we are asking to paste new lines and update some others, but on line we don't have to touch, the `const` kw is disappearing from appBar title and body
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3

our old pice of code became : 
```dart
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          //child: Text('Hello World'),   // Replace this text...
          child: Text(wordPair.asPascalCase),  // With this text.
        ),
```

As a noob in Dart, I was a bit lost because I manually updated my code as following : 
```dart
   final wordPair = WordPair.random();
   //...
   child: const Text('Hello World'),        // from
   child: const Text(wordPair.asPascalCase) // to
```
and it's not working (for some reason I don't yet understand precisely but can guess, as wordPair is holding a "final" variable)

We have to remove both `const` from `body` and `child`, yet it's not indicated (at least for the `body`) nor explained, + it's also removed from appBar.title

**Comment by ngouy** [comment]
Actually the bug is only on the google code lab site, not on the flutter site

https://flutter.dev/docs/get-started/codelab OK
codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#2 KO

I've been looking everywhere to see where its hoster amoung https://github.com/googlecodelabs but no way to find out.

**Comment by sfshaza2** [comment]
Thanks for pointing this out, @ngouy. The keywords "const" and "new" used to be required by Dart, but that is no longer true. I'm removing const in both codelabs.

**Comment by ngouy** [comment]
Hi @sfshaza2, thank you.
I'm really curious to understand how to do that, I tried to find the place where modifications should land but I was unable to find out where to do that.

**Comment by sfshaza2** [comment]
Yeah, @ngouy, it's a bit convoluted. The source code for this codelab lives in a shared repo: flutter/codelabs. The source for the codelabs that live on codelabs.developer.google.com are in a Google Doc that you can't access. So I have to fix it in several places.  :)

**Comment by sfshaza2** [comment]
Fixed

**Comment by ngouy** [comment]
Haha gotcha. I guess the idea is to keep this that lands on google.com private

Thank you @sfshaza2
