### ISSUE TITLE
Google Codelabs: Build a Photo Sharing app with Google Photos and Flutter - refactoring to Androidx not possible

### ISSUE THREAD

**Issue by StelzenPieper** [flutter/website#3613]
Hi,
I cannot migrate the source code or final source code to androidx.
Everytime I runt he refactor in AS it shows me the message "no usages found in project".
I have tried only refactoring the Android folder, I have changed SDK to 28 and I have checked if Androidx is set to true but still no androidx refactoring possible. 
Could someone provide me the refactored code or rather tell me what else I can try to get this tutorial up and running?

Thanks in advance!!
[photos-sharing-master.zip](https://github.com/flutter/flutter/files/3985514/photos-sharing-master.zip)

**Comment by sfshaza2** [comment]
@jfschmakeit, can you comment?

**Comment by jfschmakeit** [comment]
Apologies for not replying earlier. The codelab has been updated use Android X, so you should no longer see a warning message when running the application. 

(See this commit if you are curious about the change: https://github.com/googlecodelabs/photos-sharing/commit/cc909390da5385648fc77a19dbbdf3ff984f3b20 )

@sfshaza2  Please close this issue :-)

**Comment by sfshaza2** [comment]
Thanks, @jfschmakeit! Closing.
