### ISSUE TITLE
'Persist data with SQLite' page issue

### ISSUE THREAD

**Issue by ghost** [flutter/website#3616]
Page URL: https://flutter.dev/docs/cookbook/persistence/sqlite.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/persistence/sqlite.md

Description of issue:

The demo is not runnable with latest Flutter version. Either code should be fixed or note which flutter version to use. Fix is to add `WidgetsFlutterBinding.ensureInitialized();` add the beginning of `main()`.

Flutter 1.12.13+hotfix.7 • channel stable

**Comment by JuYeong0413** [comment]
Fixed in #4099

**Comment by danagbemava-nc** [comment]
Closing, this has been long since been fixed
