### ISSUE TITLE
'Rendering in Flutter' page issue

### ISSUE THREAD

**Issue by xzec** [flutter/website#3620]
Page URL: https://flutter.dev/docs/resources/rendering.html
Page source: https://github.com/flutter/website/tree/master/src/docs/resources/rendering.md

Description of issue: This page is missing some content, there is also a TODO reminder in it.

**Comment by Roshan13046** [comment]
> Page URL: https://flutter.dev/docs/resources/rendering.html
> Page source: https://github.com/flutter/website/tree/master/src/docs/resources/rendering.md
> 
> Description of issue: This page is missing some content, there is also a TODO reminder in it.

both the URL links not working.

**Comment by parlough** [comment]
This page no longer exists, see the newer [Flutter architectural overview](https://docs.flutter.dev/resources/architectural-overview) and its section on [Rendering and layout](https://docs.flutter.dev/resources/architectural-overview#rendering-and-layout) for its covered information and more :D

Thanks for opening the issue!
