### ISSUE TITLE
Update hot reload documentation once Flutter commit #5881102 is released to dev

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/website#3625]
In https://github.com/flutter/flutter/pull/48932 I've removed the limitation requiring a hot restart when switching between stateless and stateful widgets. We should probably tell developers about this once the commit makes it to dev - giving it a version and making sure we don't need to rollback.

Perhaps the limitations section of https://flutter.dev/docs/development/tools/hot-reload#limitations should call out prior to this version that this feature isn't supported?

**Comment by sfshaza2** [comment]
According to my sleuthing, this is valid as of SDK 1.17.
