### ISSUE TITLE
Objective-C docs needs some SEO

### ISSUE THREAD

**Issue by xster** [flutter/website#3631]
For instance, FlutterBinaryCodec isn't searcheable. https://www.google.com/search?q=flutterbinarycodec

Wonder if it being a frame in a page makes it worse.

**Comment by sfshaza2** [comment]
@xster, I agree 100% and  this is one of my pet peeves about the API docs. But bugs against the API docs (which are maintained by eng), belong on the flutter/flutter repo. Can you file this there and close this here?

**Comment by sfshaza2** [comment]
Filed. https://github.com/flutter/flutter/issues/50356

Closing
