### ISSUE TITLE
Update `MethodChannel` Kotlin call on 'Writing custom platform-specific code' page

### ISSUE THREAD

**Issue by andro-GT2** [flutter/website#3634]
Page URL: https://docs.flutter.dev/platform-integration/platform-channels
Page source: https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/platform-channels.md

Description of issue:

I'm trying to implement calling methodchannel on android (kotlin) from flutter, with this code:

```kotlin
class MainActivity: FlutterActivity() {
    final val CHANNEL = "com.example/messages"

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor, CHANNEL)
                .setMethodCallHandler { call, result ->
                    {
                        try {
                            if (call.method == "getMessage") {
                                val msg = getMessage();
                                result.success(msg);
                            } else {
                                result.notImplemented();
                            }
                        } catch (e: Exception) {
                            result.error("error", e.message, null)
                        }
                    }
                }
    }

    fun getMessage(): String {
        return "Hello World"
    }
}
```

I tried to use: 
```kotlin
MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL)
```

but binaryMessenger is not found in my local DartExecutor class, so I used only dartExecutor since it implements BinaryMessenger.

The flutter call to 
final String result = await channel.invokeMethod("getMessage");
does not return anything.

Is this a bug on the documentation? 

pubspec.yaml

```yaml
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
```

```terminal
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale
    en_PH.UTF-8)
 
[!] Android toolchain - develop for Android devices (Android SDK version
    29.0.2)
    ✗ Android licenses not accepted.  To resolve this, run: flutter
      doctor --android-licenses
[✓] Android Studio (version 3.3)
[!] Android Studio (version 3.1)
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 3.0)
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 2.2)
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 3.2)
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2019.2)
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Proxy Configuration
[✓] Connected device (1 available)
```

**Comment by EmmanuelAmodu** [comment]
Hi @andro-GT2 take a look at the solution here and see if it helps https://github.com/flutter/website/issues/3308#issuecomment-581065174.

I also already created a pull request hope it get approved and merged. https://github.com/flutter/website/pull/3643/files

**Comment by andro-GT2** [comment]
Thanks @EmmanuelAmodu  for the reply.

Anyway, this worked for me:

class MainActivity: FlutterActivity(), MethodChannel.MethodCallHandler {
    val CHANNEL = "com.example/messages"

    lateinit var methodChannel: MethodChannel

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine)
        methodChannel = MethodChannel(flutterEngine.getDartExecutor(), CHANNEL)
        methodChannel.setMethodCallHandler(this)
    }

    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
       //code here
    }

**Comment by sfshaza2** [comment]
Great news! I have pinged an engineer to review that PR.

**Comment by atsansone** [comment]
@johnpryan : It appears you could not replicate this issue. If that's the case, can we close this issue?

**Comment by johnpryan** [comment]
You're right, this looks like it's stale, let's close it. @andro-GT2 could you comment or file a new issue if you are still unable to get this working with the latest docs?
