### ISSUE TITLE
'Adding a splash screen and launch screen to an Android app' page issue

### ISSUE THREAD

**Issue by mike7ang1rdz** [flutter/website#3644]
Page URL: https://flutter.dev/docs/development/ui/splash-screen/android-splash-screen.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/splash-screen/android-splash-screen.md

Description of issue:

I cant find the styles.xml  file

**Comment by sfshaza2** [comment]
Good point. The file is in:  ./android/app/src/main/res/values/styles.xml

But the page should be updated to say this;
