### ISSUE TITLE
I want to add my article to state management approaches segment

### ISSUE THREAD

**Issue by bardiarastin** [flutter/website#3663]
Hi, Recently I've published an article about how to manage Flutter applications state using Flutter Redux
https://medium.com/@bardiarastin/flutter-meets-redux-the-redux-way-of-managing-flutter-applications-state-f60ef693b509

I would like to add this to the "List of state management approaches" page, on the Redux segment, can I make a PR, please?!

![image](https://user-images.githubusercontent.com/20615964/73958789-b226fc00-491d-11ea-8bef-3a5762bd8eb0.png)

**Comment by sfshaza2** [comment]
Absolutely! It would happen faster if you could file a PR.  :)

**Comment by bardiarastin** [comment]
@Sfshaza Hold my beer and wait a few minutes... <3

**Comment by sfshaza2** [comment]
:D. Will do! I hate beer, so it's safe with me.

**Comment by bardiarastin** [comment]
@Sfshaza so much thanks, https://github.com/flutter/website/pull/3664 there you go!
