### ISSUE TITLE
'Hero Animations' page issue

### ISSUE THREAD

**Issue by feinstein** [flutter/website#3683]
Page URL: https://flutter.dev/docs/development/ui/animations/hero-animations.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/animations/hero-animations.md

Description of issue:

Google shows this page with a `{site.alert.secondary}}` appended:

![image](https://user-images.githubusercontent.com/8120472/74200629-3c38d280-4c46-11ea-91d2-8623bca4d32c.png)

**Comment by sfshaza2** [comment]
@feinstein, can you tell me what browser/platform you are using?

**Comment by feinstein** [comment]
Firefox, Windows 10 x64, but this problem seems to be gone (I think it's related to an update in the Google search results HTML) so I will close it, thanks @sfshaza2.
