### ISSUE TITLE
Consider changing codefont styles

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3686]
We may be using codefont less than we can due its jarring styles:

![Screen Shot 2020-02-11 at 1 49 06 PM](https://user-images.githubusercontent.com/5550175/74283123-37236400-4cd6-11ea-9039-9f1bde6ab96b.png)
![Screen Shot 2020-02-11 at 1 49 15 PM](https://user-images.githubusercontent.com/5550175/74283128-38ed2780-4cd6-11ea-96e3-6eb6e3c4bf3d.png)

Updating codefont style may enable us to use codefont more often than we do currently, which would help alleviate some auto translation issues. See https://github.com/dart-lang/site-www/issues/2269

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/9432.
