### ISSUE TITLE
import error `android.support.annotation.NonNull`

### ISSUE THREAD

**Issue by matthieucoisne** [flutter/website#3689]
#### Description of issue:
<img width="1120" alt="Screen Shot 2020-02-12 at 9 38 41 PM" src="https://user-images.githubusercontent.com/7368710/74399738-c8372f80-4de9-11ea-9bae-23f4b8e3c10b.png">

If you open `MainActivity.kt` in the android folder of a new Flutter project, you will see errors.
1- `import android.support.annotation.NonNull`
2- `(@NonNull flutterEngine: FlutterEngine)`

Since Kotlin handles nullability, why do we need to import and use `NonNull` ?
Also, some lines of code in `MainActivity.kt` have a `;` at the end, which is not needed in Kotlin

Clicking "Open for editing in Android Studio" will open a new Android Studio window, where I don't see the errors. (Suggestion: Would be super useful in the getting-started website to explain the difference between the 2 modes?)
I expect to not see errors when opening the Flutter project in Android Studio, especially when all looks fine when opening the android folder in Android Studio (but maybe I should open the Flutter project using VSCode and only open Xcode or Android Studio when I have specific things to do in each platform?)

#### Steps to reproduce:
1- Follow all steps in this page: https://flutter.dev/docs/get-started/install/macos.html
2- Open Android Studio
3- Create a new flutter project
4- Add the path to the Flutter SDK, give a name to the project and click Finish
5- Once the project has been created, navigate to:
flutter_app > android > app > src > main > kotlin > com > package > MainActivity.kt

#### Additional info:
Mac OS X - 10.15.2 - Catalina
Android Studio 3.5.3
Flutter SDK: `flutter_macos_v1.12.13+hotfix.8-stable` (also happening with `v1.12.13+hotfix-7-stable` and with v1.11.+). It works fine with `v1.10.0` but the code in `MainActivity.kt` is not the same.

**Comment by sfshaza2** [comment]
It seems to me that there are several issues embedded here. As for nullability, null safety is [coming to Dart/Flutter](https://medium.com/dartlang/dart-2-7-a3710ec54e97). If you want to engage folks in a discussion about this, you might check out the Discord channel on our [community page](https://flutter.dev/community). Many of our Flutter engineers read and respond there.

Specifics on doc updates are welcome.

**Comment by atsansone** [comment]
This issue does not appear to exist as of Flutter 3.10.

![image](https://github.com/flutter/website/assets/706219/c38cc98c-7ad0-43d8-a8b6-38009001ce39)

Closing issue. If you experience this again, please file a new issue.
