### ISSUE TITLE
Missing some books on the books list page

### ISSUE THREAD

**Issue by rapPayne** [flutter/website#3691]
The books page should be updated to include some Flutter books that have been published recently.

**Comment by rapPayne** [comment]
To add the new books, you can add these to the database in the site.data.books collection. You'll have to permanently store the cover images and add that URL to the "cover" property for each.

```json
[
{
  "title": "Beginning App Development with Flutter",
  "cover":"",
  "link":"https://www.amazon.com/Beginning-App-Development-Flutter-Cross-Platform/dp/1484251806",
  "authors":["Rap Payne"],
  "desc":"Easy to understand starter book. Currently the best-selling and highest rated Flutter book on Amazon."
},
{
  "title": "Flutter for Beginners",
  "cover":"",
  "link":"https://www.amazon.com/Flutter-Beginners-introductory-cross-platform-applications/dp/1788996089",
  "authors":["Alessandro Biessek"],
  "desc":"A step-by-step guide to learning Flutter and Dart 2 for creating Android and iOS mobile applications"
},
{
  "title": "Flutter in Action",
  "cover":"",
  "link":"https://www.amazon.com/Flutter-Action-Eric-Windmill/dp/1617269147",
  "authors":["Eric Windmill"],
  "desc":"Flutter in Action teaches you to build professional-quality mobile applications using the Flutter SDK and the Dart programming language."
},
{
  "title": "Learn Google Flutter Fast",
  "cover":"",
  "link":"https://www.amazon.com/Learn-Google-Flutter-Fast-Example/dp/1092297375",
  "authors":["Mark Clow"],
  "desc":"Learn Google Flutter by example. Over 65 example mini-apps"
}
]
```
And here are cover images:

![image](https://user-images.githubusercontent.com/1122906/74462322-a8d5ec00-4e55-11ea-8a8c-f83501e3b4af.png)

![image](https://user-images.githubusercontent.com/1122906/74462263-8d6ae100-4e55-11ea-8fd3-23f5a986e4ec.png)

![image](https://user-images.githubusercontent.com/1122906/74462396-c7d47e00-4e55-11ea-893f-31a165ab96f3.png)

![image](https://user-images.githubusercontent.com/1122906/74462468-e470b600-4e55-11ea-8f8a-8a92fba00129.png)

**Comment by sfshaza2** [comment]
@rapPayne, the fastest way to get these added is to create a PR!  :D

**Comment by rapPayne** [comment]
Thank you @Sfshaza. I was headed that direction; I forked it and branched it and then found that the source of that page doesn't need changing. We just need to add records to whatever DB (Firestore?) is feeding the page. I tried to make it as easy as possible by doing the research, grabbing the data and putting it in JSON format.

Happy to do more, though! Is there a way I can create a PR for DB entries? Can you teach me how?

**Comment by sfshaza2** [comment]
Hi, @rapPayne! Yes, we should do a better job of documenting how to do this!

In your branch of the repo, add new books to src/_data/books.yml.
Add the images to /src/_assets/image/cover. I can stage the updated page to make sure all is well.

Thanks so much!

**Comment by rapPayne** [comment]
I'm on it, Shams. Thanks for the instructions!
