### ISSUE TITLE
Web codelab markdown issue

### ISSUE THREAD

**Issue by stepanzalis** [flutter/website#3698]
In web codelab, there are added some markdown tags by mistake. 
https://flutter.dev/docs/get-started/codelab-web

<img width="592" alt="markdown_issue" src="https://user-images.githubusercontent.com/44142488/74549024-2f222900-4f4f-11ea-8878-088f36393656.png">

**Comment by AjayThakur12** [comment]
@sfshaza2  i think this issue is fixed 
![Screenshot 2020-03-14 at 5 08 29 AM](https://user-images.githubusercontent.com/29337604/76690827-4cd7d080-666a-11ea-88b8-c7521234cfe4.png)

**Comment by sfshaza2** [comment]
Thx!
