### ISSUE TITLE
The links in internationalization are broken

### ISSUE THREAD

**Issue by suztomo** [flutter/website#3703]
https://flutter.dev/docs/development/accessibility-and-localization/internationalization

<img width="1198" alt="Screen Shot 2020-02-15 at 9 30 07 AM" src="https://user-images.githubusercontent.com/28604/74589795-7d2e3f80-4fd6-11ea-899a-4b80e0a5580a.png">

I tried a bit, but could not figure out which part is broken.

**Comment by suztomo** [comment]
I highly recommend to run automation to confirm links are not broken in Flutter documentation.

**Comment by sfshaza2** [comment]
@suztomo, can you tell me which links are broken?

**Comment by suztomo** [comment]
In the screenshot, everything after "intl_example" are broken.

**Comment by sfshaza2** [comment]
Hi, @suztomo. I am not seeing the same issue here. Can you tell me what browser and platform you are using?

**Comment by suztomo** [comment]
I see #3704 fixed this issue. Thank you. Closing this.

Still, I highly recommend to run automation to confirm links are not broken in Flutter documentation.

**Comment by sfshaza2** [comment]
@suztomo, we do run a link checker. The build fails if there are internal broken links. We get warnings for external broken links. I'm not sure why we didn't see a broken build when that problem was introduced.

**Comment by suztomo** [comment]
I don’t think the checker is working (or used) as you expect, because I find many broken links in Flutter document.

For example, this is from Accessibility page, a sibling of Internationalization page.

![4077A7C9-D4AC-4644-867E-2A5BDC843858](https://user-images.githubusercontent.com/28604/74800653-26f52100-52a2-11ea-9fb6-a9b51eaa4d1b.jpeg)

(I’m not going to create issues for them; it’s like a trying to remove water from a boat that has a hole in the bottom)
