### ISSUE TITLE
Fix malformed links

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#3717]
Reopening due to 3 remaining issues:

```
$ fgrep -Rl "][]" _site/docs
_site/docs/release/breaking-changes/template.html
_site/docs/cookbook/testing/unit/introduction.html
_site/docs/cookbook/testing/integration/scrolling.html
```
----------
OLD:

I'm pretty sure we have some other badly formatted links, but they aren't as easy to search for as these empty ones. (Not all of these "bad links" are visible in the page, btw. E.g. in https://flutter.dev/docs/development/ui/layout/box-constraints, the bad links are in the description metadata... which probably can't have HTML anyway.)

```
$ fgrep -Rl "][]" docs
docs/development/ui/layout/box-constraints.html
docs/development/ui/animations/hero-animations.html
docs/development/ui/widgets/index.html
docs/development/ui/assets-and-images.html
docs/development/accessibility-and-localization/accessibility.html
docs/resources/rendering.html
docs/release/breaking-changes/forgetchild-call-super
docs/release/breaking-changes/template.html
docs/cookbook/design/tabs.html
docs/cookbook/design/drawer.html
docs/cookbook/design/package-fonts.html
docs/cookbook/forms/text-input.html
docs/cookbook/lists/horizontal-list.html
docs/cookbook/lists/long-lists.html
docs/cookbook/lists/grid-lists.html
docs/cookbook/lists/basic-list.html
docs/cookbook/images/cached-images.html
docs/cookbook/images/fading-in-images.html
docs/cookbook/images/network-image.html
docs/cookbook/plugins/picture-using-camera.html
docs/cookbook/plugins/play-video.html
docs/cookbook/networking/web-sockets.html
docs/cookbook/networking/authenticated-requests.html
docs/cookbook/navigation/navigate-with-arguments.html
docs/cookbook/navigation/named-routes.html
docs/cookbook/navigation/hero-animations.html
docs/cookbook/animation/page-route-animation.html
docs/cookbook/animation/animated-container.html
docs/cookbook/animation/opacity-animation.html
docs/cookbook/testing/unit/introduction.html
docs/cookbook/testing/integration/scrolling.html
docs/cookbook/gestures/handling-taps.html
docs/cookbook/gestures/ripples.html
docs/cookbook/gestures/dismissible.html
docs/cookbook/persistence/reading-writing-files.html
docs/cookbook/persistence/key-value.html
docs/testing/debugging.html
docs/deployment/ios.html
docs/get-started/codelab.html
```

**Comment by D3105** [comment]
[Adding a splash screen and launch screen to an Android app](https://flutter.dev/docs/development/ui/splash-screen/android-splash-screen) page have 2 links in
first note section that redirects to the same page:
 
> Note: Strategies are available to minimize wait time related to Flutter initialization. Consider pre-warming a FlutterEngine and re-using a FlutterEngine throughout your app to avoid most wait time.

**Comment by sfshaza2** [comment]
Good idea to search on the generated site!

**Comment by sfshaza2** [comment]
Verrrrrrrry interesting! I see that, when a "description" tag is missing from the YML matter, the site generation code grabs the first paragraph, which often includes links. Links don't work when in the front matter.

**Comment by sfshaza2** [comment]
@D3105, we don't seem to have specific docs on reusing an engine, so I'm deleting that link.

**Comment by kwalrath** [comment]
Reopening (see the top comment).
