### ISSUE TITLE
The search function on the API site is inefficient

### ISSUE THREAD

**Issue by rrousselGit** [flutter/website#3723]
Consider the situation where you want to search `setState` on api.flutter.dev

Logically, it should bring `State.setState` as the first result, since this is the only class that implements the method.
The others just inherit from it.

The reality is different:

<img width="488" alt="Screenshot 2020-02-21 at 14 42 23" src="https://user-images.githubusercontent.com/20165741/75043692-609f7500-54b8-11ea-9d0c-f3f3ee74b956.png">

The search result is polluted by all the stateful widgets in the framework.
In the end, we don't even see `State.setState` because there are too many results.

**Comment by sfshaza2** [comment]
I so agree, @rrousselGit. However, this issue is filed on the wrong repo. It should be filed on the flutter/flutter repo, which is owned by engineering.

**Comment by rrousselGit** [comment]
Closing this one since I opened it on flutter/flutter https://github.com/flutter/flutter/issues/51325
