### ISSUE TITLE
'Mock dependencies using Mockito' page issue

### ISSUE THREAD

**Issue by zjasonshen** [flutter/website#3725]
Page URL: https://flutter.dev/docs/cookbook/testing/unit/mocking.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/unit/mocking.md

Description of issue:

Step 4:
TypeMatcher is deprecated. What should that line of code be changed to?

**Comment by sfshaza2** [comment]
@zjasonshen, I googled around and it looks like you should use TypeMatcher<T> instead.

https://github.com/dart-lang/matcher/pull/88

**Comment by sfshaza2** [comment]
No response. Closing. Re-open if you have further information.
