### ISSUE TITLE
how to add  a new card containing a textfield and a dropdownbutton to my listview each time i press a plus button

### ISSUE THREAD

**Issue by ONUOHA** [flutter/website#3730]
![Screenshot (16)](https://user-images.githubusercontent.com/24981612/75115494-58356e80-565f-11ea-92da-508ce7cbe35e.png)
![Screenshot (18)](https://user-images.githubusercontent.com/24981612/75115496-59ff3200-565f-11ea-93b4-3e1572503269.png)

**Comment by sfshaza2** [comment]
Hi, @ONUOHA! It sounds like you are asking how to add a card to your list each time you press a button. Is that correct? For getting answers to your tech questions, you should check out one of the platforms/forums listed on our [community page](https://flutter.dev/community), such as StackOverflow or Discord. Use this link for filing issues or bugs that you find in the flutter.dev documentation. I'm closing this, but thanks!
