### ISSUE TITLE
Link to slack community doesn't work

### ISSUE THREAD

**Issue by dh--** [flutter/website#3732]
On this page: https://flutter.dev/community

There's a "Learn more" link that takes you to the slack community page.

href="https://fluttercommunity.dev/joinslack"
which redirects to: https://fluttercommunity.slack.com/join/shared_invite/<some_really_long_code>

Unfortunately, it looks like this is a short term link. Visiting the URL routes you to an error page that says "This invite link is no longer active. Please check with the person who shared it with you to see if there's a new link available."

I'm not sure what the URL should be. Right now, it's effectively a 404 for new users.

**Comment by puremana** [comment]
Seems to be fixed for me now

**Comment by dh--** [comment]
Agreed. This appears to be resolved.
