### ISSUE TITLE
Document migration steps for migrating Xcode project to not explicitly link or embed on App.framework and Flutter.framework

### ISSUE THREAD

**Issue by jmagman** [flutter/website#3741]
https://github.com/flutter/flutter/pull/51453 will introduce a change to try to automatically migrate the Xcode project to mitigate https://github.com/flutter/flutter/issues/50568.  Document the steps needed in case the migration fails.  Link to be included in the error message.

**Comment by jmagman** [comment]
@sfshaza2 Is this more appropriate for the website or wiki?

**Comment by sfshaza2** [comment]
It sounds like this could apply to general iOS developers, not just folks who contribute to the Flutter framework, or folks who use experimental features. In the first case, it should be on flutter.dev. In the latter case, it should be on the wiki.

**Comment by sfshaza2** [comment]
Thanks for asking!

**Comment by jmagman** [comment]
It applies to general Flutter iOS developers, not contributors.  Do you have any examples of documentation like this for specific errors/bugs on the website?  Or a suggestion of what directory to plop this in?  It will probably be titled something like "Supporting Xcode 11.4".

I see https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration but this shouldn't be as prominent.

**Comment by sfshaza2** [comment]
Yes, you've found one of our precedents for this. Others are the box constraints page:  https://flutter.dev/docs/development/ui/layout/box-constraints
and the AndroidX migration page:
https://flutter.dev/docs/development/androidx-migration

It sounds like this error occurs (if at all) when updating your Xcode version, yes? 

So, I'm of two minds at the moment. Right now, the AndroidX migration (which is similar to your doc), is located at src/docs/development, right at the highest level. I don't actually want that there. I'm thinking that we could add a "Migration notes" folder under src/docs/development and put both the AndroidX and XCode pages there. The primary downside to that, is that the development directory is so full already.

A second option would be to add a "Migration notes" folder under src/docs/resources, and put both files there. I could make an argument for either approach, but putting it under Development seems more correct.

When you create the PR, please add a note similar to the other notes stating that the framework might take you to this page. Also, feel free to move the AndroidX doc to the new location, but don't feel that you must. I'm happy to do it in another PR and then set up a redirect.

**Comment by jmagman** [comment]
Side note: documenting this change will be very critical, it looks like the migrator missed removing App.framework in complex_layout because https://github.com/flutter/flutter/pull/8974 followed migration instructions in https://github.com/flutter/flutter/pull/8971, which had people manually add the framework, and thus we don't know those framework identifier references...
