### ISSUE TITLE
Update definitions of unit and integration tests on 'Testing Flutter apps' page

### ISSUE THREAD

**Issue by ronnybubkemoia** [flutter/website#3747]
Page URL: https://docs.flutter.dev/testing
Page source: https://github.com/flutter/website/tree/main/src/testing/index.md

Description of issue:
Your definition of unit and integration test is wrong.
The correct description would be:

An unit test verifies a behaviour of an application not the functionality of an implementation detail. Here all external dependencies are mocked. For instance the http layer is mocked and the test makes assumptions how these layer work. A unit test shouldn't change if the internal core logic is refactored.

An integration test is a unit test but it tests also an external dependency. This verifies that the external dependency is really doing what was actually assumed by the unit tests. The amount of integration tests is smaller because it just need to cover all accessors (API) methods of the dependency.

Have a look here:
https://medium.com/@kentbeck_7670/programmer-test-principles-d01c064d7934
https://www.youtube.com/results?search_query=tdd+went+wrong

**Comment by micpap25** [comment]
@sfshaza2 , what's your take on this? I'm pretty sure there isn't an issue here but if you think something needs to be changed just let me know. 

Re-defining "unit test" and "widget test" would require complete reworks of multiple pages on the site, and I'm not really sure what evidence there is to support that the current definitions are "incorrect".

**Comment by sfshaza2** [comment]
@domesticmouse, please weigh in

**Comment by domesticmouse** [comment]
Starting with the following statement:

> A unit test verifies a behaviour of an application not the functionality of an implementation detail. Here all external dependencies are mocked. For instance the http layer is mocked and the test makes assumptions how these layer work. A unit test shouldn't change if the internal core logic is refactored.

Let's pull out the infamous reference that is [Wikipedia](https://en.wikipedia.org/wiki/Unit_testing), we get the following:

> Unit tests are typically automated tests written and run by software developers to ensure that a section of an application (known as the "unit") meets its design and behaves as intended.[2][] In procedural programming, a unit could be an entire module, but it is more commonly an individual function or procedure. In object-oriented programming, a unit is often an entire interface, such as a class, but could be an individual method.[3][] By writing tests first for the smallest testable units, then the compound behaviors between those, one can build up comprehensive tests for complex applications.

  [2]: https://books.google.com/books?id=2ksvdhhnWQsC&printsec=frontcover
  [3]: http://people.engr.ncsu.edu/txie/publications/ast07-diffut.pdf

My experience with Unit testing (mainly Java with JUnit) has been mainly of the testing of methods and classes, with integration testing being testing of APIs with databases wired in. 

With that said, testing for a Flutter app is different to testing a monolithic API server written in Java, and I'd argue unit tests for Flutter would frequently be at the level of testing individual Widgets, as that is the primary unit of composition in a Flutter app.

I agree with what Kent Beck wrote, and don't see how it disagrees with our currently published definition of unit testing, especially given how SmallTalkers use and abuse SUnit in a method by method iterative development fashion. I don't have time to review the whole YouTube query result set that you linked.

**Comment by atsansone** [comment]
The definitions provided on this page are correct. A unit test validates a single part of an app. An integration test validates that all of those units work together. 

See [Circle CI explanation](https://circleci.com/blog/unit-testing-vs-integration-testing).

Closing as won't do.
