### ISSUE TITLE
Bad URL: Redirect /docs/release/breaking-changes/fab_accent_dependency

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#3750]
The top flutter.dev 404 last week was to docs/release/breaking-changes/fab_accent_dependency, which needs to redirect to this go link: https://flutter.dev/go/remove-fab-accent-theme-dependency.

The source might be this line:

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/floating_action_button.dart#L439

It looks like @HansMuller added this line in https://github.com/flutter/flutter/pull/48435 (the description of which refers to the correct URL). Maybe Hans can get someone to fix it in the source code, too?

Here's the context for the link:

```
      if (theme.accentIconTheme.color != defaultAccentIconThemeColor) {
        debugPrint(
          'Warning: '
          'The support for configuring the foreground color of '
          'FloatingActionButtons using ThemeData.accentIconTheme '
          'has been deprecated. Please use ThemeData.floatingActionButtonTheme '
          'instead. See '
          'https://flutter.dev/docs/release/breaking-changes/fab_accent_dependency. '
          'This feature was deprecated after v1.13.2.'
        );
      }
```

**Comment by HansMuller** [comment]
I've talked with Hans about this. Will fix the error tomorrow.
