### ISSUE TITLE
'Search' page issue

### ISSUE THREAD

**Issue by twoneis** [flutter/website#3751]
Page URL: https://flutter.dev/search.html
Page source: https://github.com/flutter/website/tree/master/src/search.html

Description of issue:

no search results showing on latest firefox

**Comment by sfshaza2** [comment]
@twoneis, is this still happening? Can you give me an example of a search you tried that failed?

**Comment by twoneis** [comment]
I still have the issue, but I concluded that it has to be something on my side since it is only on my pc and I can't reach any other google sites either.
