### ISSUE TITLE
'Measuring your app's size' page issue

### ISSUE THREAD

**Issue by shell32** [flutter/website#3757]
Page URL: https://flutter.dev/docs/perf/app-size.html
Page source: https://github.com/flutter/website/tree/master/src/docs/perf/app-size.md

Description of issue:

Flutter version 1.12.13+hotfix.8
Dart version 2.7.0
minimum apk size:
√ Built build\app\outputs\apk\release\app-armeabi-v7a-release.apk (5.3MB).
√ Built build\app\outputs\apk\release\app-arm64-v8a-release.apk (5.6MB).
√ Built build\app\outputs\apk\release\app-x86_64-release.apk (5.8MB).

**Comment by sfshaza2** [comment]
@shell32, can you describe your issue?

**Comment by sfshaza2** [comment]
Closing.
