### ISSUE TITLE
Update 'Persist data with SQLite' page with fix for code insertion

### ISSUE THREAD

**Issue by bergamin** [flutter/website#3758]
Page URL: https://docs.flutter.dev/cookbook/persistence/sqlite
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/persistence/sqlite.md

This page is a little confusing. It doesn't explain where to add the following code:

```dart
// Open the database and store the reference.
final Future<Database> database = openDatabase(
  // Set the path to the database. Note: Using the `join` function from the
  // `path` package is best practice to ensure the path is correctly
  // constructed for each platform.
  join(await getDatabasesPath(), 'doggie_database.db'),
);
```

Also, wherever I put this block of code, Android Studio doesn't like the word `await`.  I have all three imports in the file:

```dart
import 'package:path/path.dart';
import 'package:sqflite/sqflite.dart';
import 'dart:async';
```

Where I tried to add the code:

* As an attribute of my "Dog" (not dog in my case, but keeping the example)
* As an attribute of my "HomeWidgetState", which is the state of the home widget called from the MaterialApp in main.dart and where I expect to use add/remove/update the data from the database

Should I create a new file/class for the database?

Edit: looking forward in the document, there are other blocks of code that aren't clear where they should be placed

**Comment by micpap25** [comment]
At the end of the file, there's a large finished version of the cookbook. That should resolve any of the issues that you are having. I think this can be closed.

**Comment by atsansone** [comment]
Issue resolved. Closing.
