### ISSUE TITLE
alibaba playstore link broken on /showcase

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3759]
current link: https://play.google.com/store/apps/details?id=com.taobao.idlefish&e=-EnableAppDetailsPageRedesign

**Comment by AjayThakur12** [comment]
@Sfshaza @leafpetersen can i work on this issue

**Comment by sfshaza2** [comment]
I'm not @leafpetersen, but I'd love to see a correct link!  @maguinis, do you know?

**Comment by AjayThakur12** [comment]
@Sfshaza  I think idle fish no longer available in play store I am not able to find it

**Comment by sfshaza2** [comment]
Thanks, @AjayThakur12, I am looking into it with their partner PM.

**Comment by sfshaza2** [comment]
Fixed with PR https://github.com/flutter/website/pull/3821

**Comment by sfshaza2** [comment]
(Also, the update is that they pulled it from the store while they are doing a significant update. It should be back soon.)
