### ISSUE TITLE
Join Flutter's showcase

### ISSUE THREAD

**Issue by bfarkas-sully** [flutter/website#3764]
Hi everyone,
We are currently working on a Flutter based application and we would like to be integrated to the showcase.
Does anyone know how to do that ?
Thanks

**Comment by sfshaza2** [comment]
Hi, @bfarkas-sully! That call is made by the marketing folk. There's no formal process for requesting to be featured. I suspect posting on Twitter, with hashtags, can raise the visibility of your project. Sorry I can't be more help!
