### ISSUE TITLE
'Basic Flutter layout concepts' page issue

### ISSUE THREAD

**Issue by trantrongthanhtam** [flutter/website#3775]
Page URL: https://flutter.dev/docs/codelabs/layout-basics.html
Page source: https://github.com/flutter/website/tree/master/src/docs/codelabs/layout-basics.md

Description of issue:

I'm not sure it's from my browser or the page itself that all the codelab environment shows nothing, feel like all the code is shifted to the left. I really want to dig in to some Dart code but this is kind of frustrated.

![Annotation 2020-03-08 093440](https://user-images.githubusercontent.com/49970372/76155552-11944980-6120-11ea-986c-57f3536e5a0d.png)

**Comment by legalcodes** [comment]
Hi @trantrongthanhtam thanks for raising this issue! I'm not able to reproduce this. Can you let me know what browser / OS you are using?

**Comment by trantrongthanhtam** [comment]
hi @legalcodes, I did try it on firefox, works just fine, only Google Chrome browser seems to be the problem. Chrome in both Ubuntu and Windows 10 have the same problem. My Chrome version is Version 80.0.3987.100 (Official Build) (64-bit). Hope this helps!

**Comment by micpap25** [comment]
Using the latest version of Google Chrome and Windows 10 and it works for me. 
Version 85.0.4183.121 (Official Build) (64-bit) to be specific. @trantrongthanhtam , do you still have this issue?
![image](https://user-images.githubusercontent.com/34077605/93842568-608d7080-fc65-11ea-9efa-99e7e6b6a21b.png)

**Comment by trantrongthanhtam** [comment]
Latest version of Chrome works fine now. Thank you for your responses!
