### ISSUE TITLE
'Inside Flutter' page issue

### ISSUE THREAD

**Issue by kaboc** [flutter/website#3777]
Page URL: https://flutter.dev/docs/resources/inside-flutter.html
Page source: https://github.com/flutter/website/tree/master/src/docs/resources/inside-flutter.md

There are eight footnotes, but 5 - 8 do not seem to be linked from anywhere in the body of the page.

I have no idea whether necessary links are missing or the latter half of the footnotes can be removed, so I file the issue here rather than make a PR.

---

Additionally, I think adding backlinks from footnotes will be helpful for readers.

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/3786
