### ISSUE TITLE
'/docs/release/breaking-changes/container-color.html' page issue

### ISSUE THREAD

**Issue by kaboc** [flutter/website#3784]
Page URL: https://flutter.dev/docs/release/breaking-changes/container-color.html
Page source: https://github.com/flutter/website/tree/master/src/docs/release/breaking-changes/container-color.md

Pages linked from `ColoredBox` and `Colored box and container optimization #50979` in the `References` section at the bottom are not found.

**Comment by kaboc** [comment]
As for the latter, I noticed the link was just broken, and made a PR (#3785).

**Comment by sfshaza2** [comment]
Thanks for fixing the link to the PR! I've fixed the other links, which should link to the *master* API docs, not the stable API docs. (Unless the fix lands in stable..)

**Comment by micpap25** [comment]
Fixed, looks like this should be closed
