### ISSUE TITLE
Fix typo for JSON and serialization page

### ISSUE THREAD

**Issue by ram231** [flutter/website#3791]
I just want to point out a mistake in grammar(sorry!) and want to submit a pull request. but due to tedious work of reading the docs on how to get started with the repo and with my potato laptop and slow internet connection. It's better if someone could contribute it and fix the typo [here](https://flutter.dev/docs/development/data-and-backend/json#use-manual-serialization-for-smaller-projects).
> Manual decoding does not perform well when your project becomes bigger. Writing decoding logic by hand can become hard to manage and error-prone. If you have a typo when accessing /**an nonexistent**/ JSON field, your code throws an error during runtime.

Thank you Flutter Team and its contributors!

**Comment by micpap25** [comment]
It seems that this was fixed, this issue should be closed.

**Comment by sfshaza2** [comment]
Yay!
