### ISSUE TITLE
'Build and release an iOS app' page issue

### ISSUE THREAD

**Issue by syonip** [flutter/website#3800]
Page URL: https://flutter.dev/docs/deployment/ios.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/ios.md

Description of issue:

The part about verifying the `Display Name` setting in xcode is misleading.
Changing the Display Name to anything else than `Runner` will cause the app to not run with flutter tools, as described here https://github.com/flutter/flutter/issues/41793

**Comment by micpap25** [comment]
Looks like this is fixed, can be closed.
