### ISSUE TITLE
add shorter devtools urls, and have them re-direct to the devtools pages

### ISSUE THREAD

**Issue by devoncarew** [flutter/website#3811]
We'd like to have slightly shorter urls for the devtools documentation (in order to have terse urls to display in the app).

Instead of the current urls:

```
https://flutter.dev/docs/development/tools/devtools/inspector
```

it would be great to have a url like:

```
https://flutter.dev/devtools/inspector
```

I think this would be easiest if flutter.dev had some re-directs - something like `https://flutter.dev/devtools/`* ==> `https://flutter.dev/docs/development/tools/devtools/*`.

cc @sfshaza2

**Comment by sfshaza2** [comment]
Yes, this is achievable by editing the firebase.json file. PRs accepted!  :)
