### ISSUE TITLE
'Layout widgets' page issue

### ISSUE THREAD

**Issue by feinstein** [flutter/website#3813]
Page URL: https://flutter.dev/docs/development/ui/widgets/layout.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/widgets/layout.md

Description of issue:

Could you add a category with all the Sliver types? I often forget all my options and finding them isn't so easy... `SliverList`, `SliverFixedExtentList`, `SliverGrid`, `SliverPadding`, `SliverAppBar` and etc...

**Comment by sfshaza2** [comment]
A good idea.

**Comment by micpap25** [comment]
Hi, @sfshaza2 , I'm currently working on this issue. Do you think Layouts is the right place for this new section to go? I'm bringing this up because CustomScrollBar is already in Scrolling while SliverAppBar is in Material Design.

**Comment by micpap25** [comment]
Unless anyone has any objections I'm going to go ahead with putting everything in Layouts and moving both CustomScrollBar and SliverAppBar over there. I'll mention where they went.
