### ISSUE TITLE
interactive examples are not working for any cookbook examples

### ISSUE THREAD

**Issue by vaimikpatel2908** [flutter/website#3830]

**Comment by sfshaza2** [comment]
@johnpryan, can you look into this?

**Comment by johnpryan** [comment]
@vaimikpatel2908 I can't reproduce this. Can you open the chrome devtools and paste any output that you see in the console?

**Comment by vaimikpatel2908** [comment]
![image](https://user-images.githubusercontent.com/45857340/77365697-f125db00-6d2c-11ea-87ec-c2fcd616e4b6.png)

**Comment by johnpryan** [comment]
@vaimikpatel2908 can you check that you're not running any ad blockers? You can also checkout the [troubleshooting guide](https://dart.dev/tools/dartpad/troubleshoot) for other issues.

**Comment by vaimikpatel2908** [comment]
yes I had ad blocker but now i disabled it but still not working but working on edge so problem might be browser specific for my machine. thanks for your support.
