### ISSUE TITLE
Add info on "Flutter plugin not installed"? ('Windows install' page issue)

### ISSUE THREAD

**Issue by JPhilipp** [flutter/website#3831]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

It might make sense to include one line of what to do when flutter doctor returns "Flutter plugin not installed" (i.e. to open Android Studio, click Configure > Settings > Plugins and install Flutter). It gets mentioned on the Next page after this one, but if you're like me and already had Android Studio installed but not Flutter/ Dart, it can result in additional googling -- as the instructions specifically say to first fix any Flutter Doctor messages. Thanks!

**Comment by sfshaza2** [comment]
Good point!
