### ISSUE TITLE
Finish the OEM debugger iOS section

### ISSUE THREAD

**Issue by xster** [flutter/website#3847]
https://flutter.dev/docs/testing/oem-debuggers#debugging-with-xcode-ios is pending (but useful) :)

**Comment by sfshaza2** [comment]
Yes, @xster, I wasn't able to get it working, so the doc ended there. This can definitely be revisited.

**Comment by lukaskurz** [comment]
Hi there,
Any updates/information, when this will be done ? Looks kinda odd to have a `[Pending]` inside the docs for one of the core development processes (Debugging). Is this missing because iOS debugging is just not possible yet or are we just missing the documentation ?

**Comment by sfshaza2** [comment]
@jmagman, what do you think? Can we revisit this?

**Comment by jmagman** [comment]
This would essentially be, open `ios/Runner.xcworkspace` in your Flutter app in Xcode, run it as a normal app in Xcode, then `Flutter Attach` in the Flutter IDE.  Alternatively, run the app from the Flutter IDE, then open `ios/Runner.xcworkspace in Xcode, `Debug -> Attach to Process` and choose the running app.

**Comment by atsansone** [comment]
@leighajarett : This section literally says `[PENDING]`. We should get something on that page. Could you recommend any content?
