### ISSUE TITLE
'Set up an editor' page issue : Steps are impossible to reproduce.

### ISSUE THREAD

**Issue by NatoBoram** [flutter/website#3853]
Page URL: https://flutter.dev/docs/get-started/editor.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/editor.md

Description of issue:

In the following text : 

> ## Install the Flutter and Dart plugins
> 
> To install these:
> 
>  1. Start Android Studio.
>  1. Open plugin preferences (**Preferences > Plugins** on macOS,
>     **File > Settings > Plugins** on Windows & Linux).
>  1. Select **Marketplace**,  select the Flutter plugin and click
>     **Install**.
>  1. Click **Yes** when prompted to install the Dart plugin.
>  1. Click **Restart** when prompted.

The steps are impossible to achieve in Android Studio 3.6.1. More precisely, this step.

>  2. Open plugin preferences (**Preferences > Plugins** on macOS,
>     **File > Settings > Plugins** on Windows & Linux).

![image](https://user-images.githubusercontent.com/10495562/77591091-9f648880-6ec5-11ea-84ad-cdaedb69c060.png)

There is no **File**.

**Comment by sfshaza2** [comment]
@NatoBoram, which platform are you using? I verified that this works as indicated on macOS.

@legalcodes, can you try verify this on Windows and/or Linux?

**Comment by NatoBoram** [comment]
Screenshot was taken on Windows 10

**Comment by sfshaza2** [comment]
@NatoBoram, I have no access to Windows or Linux, but the **File** menu should be at the top of the window or screen, not inside the window.

**Comment by NatoBoram** [comment]
Issue was fixed in v3.6.3.0, which brought back the **⚙️ Configure** menu, but there's still no *File* menu anywhere on the screen.

![image](https://user-images.githubusercontent.com/10495562/79767626-95cd1580-82f7-11ea-960b-6d83dff5b3ca.png)

I think the correct path is now *⚙️ Configure > Plugins*.

**Comment by sfshaza2** [comment]
@NatoBoram, it took me a bit, but now I get what you're saying.  :). I've confirmed and have opened a PR. Thanks!
