### ISSUE TITLE
Incorrect type for `controller` on 'Staggered Animations' page issue

### ISSUE THREAD

**Issue by xcoderreal** [flutter/website#3865]
Page URL: https://flutter.dev/docs/development/ui/animations/staggered-animations.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/animations/staggered-animations.md

Description of issue:

`controller` should be of type `AnimationController` instead of `Animation<double>` (although technically speaking the former is a subclass of a latter class so it should be OK...), which might be less confusing?

**Comment by sfshaza2** [comment]
@legalcodes, can you take a look?

**Comment by legalcodes** [comment]
I've added the animations label, we have a pretty large queue of these, so I'll try to move in order of priority.
