### ISSUE TITLE
'Adding a Flutter screen to an Android app' page issue

### ISSUE THREAD

**Issue by Akash35pasupathi** [flutter/website#3870]
Page URL: https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/add-to-app/android/add-flutter-screen.md

Description of issue: how can i create and add Flutter Actvitiy

**Comment by sfshaza2** [comment]
Hi, @Akash35pasupathi! I'm sorry that you are finding the docs confusing. The page that you referenced should contain the information you need. If it's still not enough, I suggest that you reach out to the [Flutter community](https://flutter.dev/community). Particularly on Discord, which many of the Flutter SWEs read and respond to.

If you have specific suggestions on how we can improve the docs, please open a new issue!
