### ISSUE TITLE
Update TextTheme Widget properties in the website. 

### ISSUE THREAD

**Issue by faizanmohiuddin482** [flutter/website#3871]
unable to use Body1 property in android studio with the following pubspec.yaml 
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
Android Studio suggests to use bodyText1 instead of body1.

**Comment by sfshaza2** [comment]
Hi, @faizanmohiuddin482! Are you using the master channel or the dev channel? Some of the Material properties are being renamed in 1.16. Stable is currently 1.12, so the docs are correct as for that. The analyzer is pretty good at telling you what needs to be updated if you are using a newer release.

**Comment by faizanmohiuddin482** [comment]
> Hi, @faizanmohiuddin482! Are you using the master channel or the dev channel? Some of the Material properties are being renamed in 1.16. Stable is currently 1.12, so the docs are correct for stable (for now). The analyzer is pretty good at telling you what needs to be updated if you are using a newer release.

![Annotation 2020-04-03 213049](https://user-images.githubusercontent.com/37860867/78381088-78f3cb00-75f2-11ea-828c-b95397e346b2.png)
Currently using the above version.

**Comment by sfshaza2** [comment]
For the record, [here's the PR](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_theme.dart) that has the old and new naming.

@gspencergoog, does 1.15 use the old or new naming? This has caused some build problems with the website.

**Comment by sfshaza2** [comment]
Travis evaluates the website code using stable, which is currently 1.12. These renamed fields aren't yet available on stable. Trying to change them now would break the build.

**Comment by gspencergoog** [comment]
I don't think that's the PR you're looking for. :-) That one of mine is for converting `Diagnosticable` to a mixin.  The one I think you're looking for is https://github.com/flutter/flutter/pull/48547, which was authored by Mr. @HansMuller.

I believe the earliest dev release Hans' PR landed in was v1.14.6.

**Comment by gspencergoog** [comment]
Actually, in the change, it says the old names were deprecated after v1.13.8.

**Comment by HansMuller** [comment]
@gspencergoog is correct about #48547 and probably correct about what version of Flutter the PR actually landed in.

**Comment by micpap25** [comment]
I think this can be closed if it's a deprecation issue.
