### ISSUE TITLE
Code checker can crash

### ISSUE THREAD

**Issue by dcharkes** [flutter/website#3873]
https://github.com/flutter/website/blob/2d94357aeb1e3ebbbf13a555f95427b278faecfe/tool/extract.dart#L59-L61

This line [crashes](https://travis-ci.org/github/flutter/website/jobs/669764877?utm_medium=notification&utm_source=github_status) if there is no closing tag.

cc @sfshaza2 @dnfield

**Comment by sfshaza2** [comment]
Daco and I filed this at the same time. Closing this one.

https://github.com/flutter/website/issues/3873

**Comment by sfshaza2** [comment]
Oops. Closed the wrong one.

**Comment by dnfield** [comment]
Probably should assert that it occurs before we hit a newline and before we hit the end of the array.

**Comment by dnfield** [comment]
To be clear - it will still have to crash, because it's invalid markup - but it could at least crash with a clearer error message.
