### ISSUE TITLE
'Set up an editor' page issue: can't see VS code setup instructions

### ISSUE THREAD

**Issue by trevordunn** [flutter/website#3875]
Page URL: https://flutter.dev/docs/get-started/editor.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/editor.md

Description of issue:
Clicking the "Visual Studio Code" tab beside "Android Studio and IntelliJ" does nothing (except change the url hash).

Testing on macOS 10.15.3, Chrome 80.0.3987.149

**Comment by sfshaza2** [comment]
Fixed. Thanks!
