### ISSUE TITLE
Visual Studio Code's tab is not working!

### ISSUE THREAD

**Issue by mobiteapp** [flutter/website#3880]
Page URL: https://flutter.dev/docs/get-started/editor.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/editor.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
I try to learn flutter and in this page Visual Studio Code's tab is not working!
I refreshed the page many times but it's still not working.
I use Google Chrome.

**Comment by sfshaza2** [comment]
Fixed.
