### ISSUE TITLE
Explain how to avoid error on 'Persist data with SQLite' page

### ISSUE THREAD

**Issue by GokulDas027** [flutter/website#3884]
Page URL: https://docs.flutter.dev/cookbook/persistence/sqlite
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/persistence/sqlite.md

It's confusing to see an error on a code snippet that is mentioned everywhere..

Description of issue:
```dart
join(await getDatabasesPath(), 'doggie_database.db'),
error: Argument type Future<String> can't be assigned to parameter type String. 
```

**Comment by piedcipher** [comment]
I'm unable to reproduce this issue.

**Comment by GokulDas027** [comment]
Hi, I couldn't recall much details, but I wasn't able to fix this issue and moved on to a different database..
All the code for doing this were from the docs

**Comment by atsansone** [comment]
Reporter has dropped issue. Closing.
