### ISSUE TITLE
The Getting Started section missing from left nav

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#3886]
When I go to https://flutter.dev/docs, I can't find any Getting Started docs in the left nav:

![image](https://user-images.githubusercontent.com/348942/78307109-0acbdd00-74fa-11ea-8b8d-5d401569a202.png)

However, this section would show up if I specifically go into https://flutter.dev/docs/get-started/install using the 'Get Started' button on the top nav. 

I think having the Getting Started section generally visible in the left nav is useful, since this section covers much much more than installation.

**Comment by sfshaza2** [comment]
That's weird. It's in the left nav for me! Are you sure the left nav hadn't scrolled? What browser are you using?

**Comment by InMatrix** [comment]
The Getting Started section showed up in the left nav for me now. I must have run into a browser issue. 😔
