### ISSUE TITLE
'Test drive' page issue

### ISSUE THREAD

**Issue by khaiql** [flutter/website#3890]
Page URL: https://flutter.dev/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Description of issue:

Clicking on other tabs doesn't switch to the other tab and show relevant content. 

Browser: Firefox, Chrome

**Comment by Zenahr** [comment]
To put the issue into words:
-----------------------------------------------------------------------------------
When visiting the flutter **getting started** section ---> **test drive** and clicking on either "Visual Studio Code" or "Terminal & editor" nothing happenes and the page doesn't change to the corresponding docs.
Screenshot attached.
![image](https://user-images.githubusercontent.com/47085752/78384766-1511d800-75db-11ea-83ca-35a920e0d57a.png)

**Comment by sfshaza2** [comment]
Fixed by PR https://github.com/flutter/website/pull/3893
