### ISSUE TITLE
'Test drive' page issue

### ISSUE THREAD

**Issue by m0r1n0** [flutter/website#3895]
Page URL: https://flutter.dev/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

Visual Studio Code and Terminal & editor links with problems.

**Comment by sfshaza2** [comment]
Fixed by https://github.com/flutter/website/pull/3893
