### ISSUE TITLE
Presence of banner should not impact tab behavior

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3897]
We should investigate why the presence of the banner impacts how nav-tabs function, see https://github.com/flutter/website/issues/3889 and https://github.com/flutter/website/pull/3893.

**Comment by sfshaza2** [comment]
Yes, we've had a banner for so long, that we didn't realize this was an issue. I turned off the banner (using show_banner=false in the _config.yml file) and tabs broke because of the math involved in computing which tab had been clicked. At least that's what it looks like.

**Comment by sfshaza2** [comment]
Our workaround, for now, is to always keep a banner up.
