### ISSUE TITLE
Remove <-- skip --> from get-started/codelab-web.md

### ISSUE THREAD

**Issue by legalcodes** [flutter/website#3898]
We skipped a few checks to unblock the build in https://github.com/flutter/website/pull/3893/files but we still need to investigate the root cause of the failure. See also https://github.com/flutter/website/issues/3889.

**Comment by sfshaza2** [comment]
It looks like we may have to wait for the next stable release to fix this. Some Material properties have been renamed and renaming to the new properties breaks our build, which tests again 1.12 stable. The changes were after that.

**Comment by sfshaza2** [comment]
Yes, this is definitely a stable/master issue that will be fixed soon. Closing.
