### ISSUE TITLE
'Create lists with different types of items' page issue

### ISSUE THREAD

**Issue by pektinasen** [flutter/website#3904]
Page URL: https://flutter.dev/docs/cookbook/lists/mixed-list.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/lists/mixed-list.md

Description of issue:
Excerpt:

    This example uses the is keyword to check the type of item. It’s fast, and automatically casts each item to the appropriate type. 

Am I missing something, but I can't find a reference to which example this sentence refers to.

**Comment by sfshaza2** [comment]
You're right! It makes no sense to me, either. That tidbit should be deleted.
