### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by nissan997** [flutter/website#3909]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue: The download button on the windows zip download keeps loading until it's failed. Trying to download flutter for a week now

**Comment by sfshaza2** [comment]
@legalcodes, would you mind trying this on our windows machine?

**Comment by nissan997** [comment]
I tried it on my Thinkpad T450 running the latest version of Windows 10. I also found that this website loads just fine in my friends home computer ..

**Comment by sfshaza2** [comment]
OK, going to close this, as it sounds like a notepad device.
