### ISSUE TITLE
widgets reference rendering incorrect on iPhone 5C

### ISSUE THREAD

**Issue by gaaclarke** [flutter/website#3910]
originally filed at flutter/flutter: https://github.com/flutter/flutter/issues/26292

**Comment by sfshaza2** [comment]
Apparently the flutter.dev website doesn't display properly on an iPhone 5C, which is an older phone. I've marked this as an infrastructure bug, but it's worth noting that we have no infrastructure support at the moment. PRs welcome.

**Comment by atsansone** [comment]
Apple no longer supports the 5C. Closing this. issue.
