### ISSUE TITLE
Problem in Step 5 of Cupertino codelab

### ISSUE THREAD

**Issue by zeddevelopers** [flutter/website#3911]
After the following line
ChangeNotifierProvider<AppStateModel>
the documentation says that have to write
model: model
![image](https://user-images.githubusercontent.com/25787554/78631982-3f9fb180-78b7-11ea-9de7-f5236143ee27.png)
but that is not working.

Code from following link is working fine
https://github.com/googlecodelabs/flutter-cupertino-store/blob/master/step-01/lib/main.dart
![image](https://user-images.githubusercontent.com/25787554/78632022-56460880-78b7-11ea-9502-adde91e9773b.png)

Step 5 page needs to be updated

**Comment by sfshaza2** [comment]
@zeddevelopers, can you please clarify on what page is this error?

**Comment by zeddevelopers** [comment]
On step no 5 page, it is suppose to be "builder" instead of "create". I fixed my code but following strict codelabs steps is causing error.

**Comment by sfshaza2** [comment]
@domesticmouse

**Comment by domesticmouse** [comment]
I suspect the issue is the changing api of `package:provider`. I'd suggest setting the minimum version of `provider` to 4 and then follow the instructions listed here for [migrating from v3 to v4](https://pub.dev/packages/provider#migration-from-v3x0-to-v400).

**Comment by sfshaza2** [comment]
@domesticmouse, this refers to the Cupertino codelab.

**Comment by sfshaza2** [comment]
Nvm, I see that you did see this, @domesticmouse. :D

**Comment by domesticmouse** [comment]
I’ll do a sweep through my codelabs soon 😁

**Comment by sfshaza2** [comment]
Subsumed by issue https://github.com/flutter/website/issues/4026
