### ISSUE TITLE
'Write your first Flutter app on the web' page issue

### ISSUE THREAD

**Issue by jmslxblack** [flutter/website#3915]
Page URL: https://flutter.dev/docs/get-started/codelab-web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab-web.md

Description of issue:

The finished code and the last code are not the same. this is confusing because using the first snippet doesn't match up with the instructions. What makes it even more confusing is there are missing instructions, eg add '/welcome': (context) => WelcomeScreen(), as a route to the app class. If i hadn't looked at the finished code, i'd never have worked this out.

This needs going over and updating where the tutorial is missing steps, or assumes you would know what to do because of the finished product.

**Comment by sfshaza2** [comment]
Fixed.
