### ISSUE TITLE
'Test drive' page issue

### ISSUE THREAD

**Issue by 01abhishekjain** [flutter/website#3922]
Page URL: https://flutter.dev/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Description of issue:
It _could_ be mentioned somewhere that if you already have VS Code running during the initial flutter setup, you might need to restart it for the Flutter plugin to be able to detect Flutter SDK automatically.

**Comment by MiraMarshall** [comment]
Closing. This issue has been resolved. https://docs.flutter.dev/get-started/test-drive?tab=vscode
