### ISSUE TITLE
SplashScreen documentation needs more clarity

### ISSUE THREAD

**Issue by emme1444** [flutter/website#3938]
On the _[Adding a splash screen to your mobile app](https://flutter.dev/docs/development/ui/advanced/splash-screen)_ page, under the section _[Creating a custom SplashScreen](https://flutter.dev/docs/development/ui/advanced/splash-screen#creating-a-custom-splashscreen)_, I feel there are things missing. I have tempered around with things, but can't seem to figure out what to do. Specifically, what to do with the SplashScreen implementation I just created. 

What I'm trying to say is that there would be nice with some extra documentation on what to do with the classes that implement `SplashScreen`. 

I'm not super familiar with Android native development. Or iOS, for that matter. Talking Android, so far I've tried to add my custom `SplashScreen` implementation as a `meta-data` tag in the  (see below) but the screen is just black, no matter the content of `onDraw`. I simply just can't figure it out. 

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
package="com.example.app">
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="app"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme" />
            <!--<meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />-->
            <meta-data
                android:name="com.example.app.CustomSplashScreen"
                android:value="test"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    <!-- Don't delete the meta-data below.
                 This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
    <meta-data
        android:name="flutterEmbedding"
        android:value="2" />
    </application>
</manifest>
```

If this information actually exists, then sorry for the inconvenience and please point me in the right direction! 

Thanks for understanding!

**Comment by sfshaza2** [comment]
@xster

**Comment by emme1444** [comment]
@sfshaza2, @xster any updates?

**Comment by sfshaza2** [comment]
@emme1444, I can't speak for @xster, but I have no updates. If you are seeking support, I suggest that you ask on one of our community platforms, such as Discord. Many of our engineers participate in the Discord channel. You can learn about other options on the [community page](https://flutter.dev/community).

**Comment by emme1444** [comment]
Okay, I see. Thank you for your directions @sfshaza2! Should I close this? For me, feel free to do so.

**Comment by laurentVRL2T** [comment]
100% true @emme1444 
**The Flutter splash screen section** need more clarity.
android view, FlutterFragment

**Comment by sfshaza2** [comment]
No, I'll leave this open, @laurentVRL2T, as it seems we do need to improve the docs. Thanks!

**Comment by darwin-morocho** [comment]
@sfshaza2 Any update for this?

**Comment by sfshaza2** [comment]
@johnpryan @domesticmouse, @RedBrogdon, can one of you take a look? Or suggest a SWE who can help? I believe that Matt C owned this area but he left us about a year ago.

**Comment by camsim99** [comment]
The method for adding a splash screen no longer involves implementing the splash screen interface and the section referenced seems to have been removed.
