### ISSUE TITLE
Update 'JSON and serialization' page to include JSON Mapper

### ISSUE THREAD

**Issue by k-paxian** [flutter/website#3948]
Page URL: https://docs.flutter.dev/data-and-backend/json
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/json.md

Description of issue:

> Is there a GSON/Jackson/Moshi equivalent in Flutter?
> The simple answer is no.

This is no longer an objective truth.
Here is the real and working alternative based on reflection approach.
https://github.com/k-paxian/dart-json-mapper

**Comment by micpap25** [comment]
Could I get a second opinion on this from someone? Is this something that should be included in the Flutter docs?

**Comment by atsansone** [comment]
Flutter explicitly doesn't use reflection for the reasons listed on this page. Closing this issue.
