### ISSUE TITLE
flutter.dev/setup/#android-setup page not available

### ISSUE THREAD

**Issue by jayoung-lee** [flutter/website#3950]
`flutter doctor` told me to visit https://flutter.dev/setup/#android-setup for detailed instruction, but the page does not exist. See below for the message I got. 

```
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.0)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/Users/jayounglee/Library/Android/sdk/tools/bin/sdkmanager" "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.dev/setup/#android-setup for detailed instructions.
```

**Comment by sfshaza2** [comment]
Ah. I was not aware that the tooling referred to this page. We need to set up a redirect. The correct URL is:  https://flutter.dev/docs/get-started/editor?tab=androidstudio

**Comment by sfshaza2** [comment]
@jayoung-lee, can you confirm? I cannot reproduce this. When I go directly to that URL, it redirects me to the general install page. It would be better to go to the "Set up an editor" page with Android Studio selected., but I do not get a 404.

**Comment by jayoung-lee** [comment]
Yes, it sends me to the general install page too. 

Could you make it go to the page you linked above (https://flutter.dev/docs/get-started/editor?tab=androidstudio)? That page works for me.

**Comment by sfshaza2** [comment]
I have tried, but the forwarding mechanism is being stubborn. But at least it's no 404.

**Comment by sfshaza2** [comment]
Ideally, we need a bug filed against "flutter doctor" to use the correct URL.

**Comment by jayoung-lee** [comment]
I will do so!
