### ISSUE TITLE
'Introduction to animations' page issue

### ISSUE THREAD

**Issue by mobiteapp** [flutter/website#3951]
Page URL: https://flutter.dev/docs/development/ui/animations/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/animations/index.md

Description of issue:
At Flutter Gallery section in the Physics-based animation, The hyperlink of 'Grid' has error 404.

**Comment by sfshaza2** [comment]
Yes, good catch. The Flutter Gallery has been rewritten and that particular demo seems to be gone. However, we do have a physics animation example in the cookbooik:  https://flutter.dev/docs/cookbook/animation/physics-simulation

We need to update the page to reflect that.

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/3968
