### ISSUE TITLE
Update code example on 'Mock dependencies using Mockito' page

### ISSUE THREAD

**Issue by ajonno** [flutter/website#3952]
Page URL: https://docs.flutter.dev/cookbook/testing/unit/mocking
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/unit/mocking.md

Description of issue:
this line of code no longer works (test always fails) in the test example as ```TypeMatcher``` is deprecated. please fix, thanks.

```expect(await fetchPost(client), const TypeMatcher<Post>());```

**Comment by sfshaza2** [comment]
@ajonno, can you tell me which version of the Flutter sdk you are using?

**Comment by ajonno** [comment]
Flutter 1.12.13+hotfix.8

**Comment by sfshaza2** [comment]
Thanks, @ajonno! @filiph, as you used this very recently, can you confirm? He is using the current stable version.

**Comment by samisnotinsane** [comment]
What should be passed into `expect` instead of `TypeMatcher<Post>()`? Please update as I'm using the cookbook to learn Flutter and deprecated code in official documentation is just poor.

**Comment by samisnotinsane** [comment]
Found the solution using official API docs for class [isA](https://api.flutter.dev/flutter/package-matcher_matcher/isA.html).

So change the line **from**:
`expect(await fetchPost(client), const TypeMatcher<Post>());`
**to**:
`expect(await fetchPost(client), isA<Post>());`

**Comment by micpap25** [comment]
@samisnotinsane Hi, it seems like you pushed these commits but never actually made a PR for them. Do you plan to do that, and if not, can I copy your commits on to my branch and make a PR? Thanks.

**Comment by samisnotinsane** [comment]
@micpap25 Hey, thanks for your comment. I believe I did raise PR #4155 which solves this issue and it was subsequently merged. Let me know if it isn't checking out. ![image](https://user-images.githubusercontent.com/11885489/94531361-60c4d780-0234-11eb-9146-a6272a2b45bc.png)

**Comment by micpap25** [comment]
Ah, so in that case it looks like this issue can be closed.

**Comment by atsansone** [comment]
This issue no longer exists on the page. Closing this issue.
