### ISSUE TITLE
'Build and release an iOS app' page issue

### ISSUE THREAD

**Issue by rubensdemelo** [flutter/website#3953]
Page URL: https://flutter.dev/docs/deployment/ios.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/ios.md

Display Name
Runner
Changing the display name to anything other than Runner causes the app not to run with the Flutter tools. For more information, see Issue 41793.

But image shows Display Name = "My App"

**Comment by sfshaza2** [comment]
Yup. PRs welcome with an updated screenshot.  :D
