### ISSUE TITLE
Update the state management "options" page to focus on setState + provider

### ISSUE THREAD

**Issue by csells** [flutter/website#3954]
We definitely want to maintain a list of other Flutter state management options (with the possible exception of "scoped provider," which seems to have been completely superseded by provider) but we'd like people that land on this page to know that they should be setState for widget-specific state and provider for shared state, at least to start.

I'm thinking sections like:

Widget-specific State
(use setState)

State shared between widgets
(use provider)
(watch this talk from IO 2019)

Other state management options
inheritedwidget
bloc
redux
mobx
etc

**Comment by sfshaza2** [comment]
@filiph, please weigh in

**Comment by filiph** [comment]
This is on my list. We talked about this with @csells today. Thanks for filing the bug, Chris!
