### ISSUE TITLE
What is the rule of Flutter version name?

### ISSUE THREAD

**Issue by shirakiya** [flutter/website#3955]
I think Flutter is useful and nice product!

I can see the release version of Flutter from the follow page.
https://flutter.dev/docs/development/tools/sdk/releases?tab=linux

It can be seen...

- 1.16 or less  =>   "v" prefix added
- 1.17 or more  =>  "v" prefix not added

Is it correct? Do you have fixed rules of Flutter version name?

Best regards.

**Comment by jonahwilliams** [comment]
@tvolkert  @pcsosinski do we have wiki documentation for the new versioning scheme?

**Comment by pcsosinski** [comment]
https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

**Comment by shirakiya** [comment]
It looks above document you show doesn't mention "v" prefix.

**Comment by sfshaza2** [comment]
My understanding is that we are no longer using the "v" prefix, @shirakiya.

**Comment by shirakiya** [comment]
"no longer using" means ver. 1.17 or more, doesn't it? For now, I have interpreted it is continue to add "v" prefix to ver. 1.16 or less if you need to upgrade versions for example patch. @sfshaza2

**Comment by sfshaza2** [comment]
That's my understanding, yes. Though @tvolkert can say with more authority.

**Comment by shirakiya** [comment]
I'm so looking forward to it.

**Comment by tvolkert** [comment]
Yep, that's correct - as of 1.17+, we dropped the "v" prefix.

**Comment by sfshaza2** [comment]
Thanks, @tvolkert! Closing.

**Comment by shirakiya** [comment]
I understand it. Thank you for answering!
