### ISSUE TITLE
'Flutter SDK releases' page issue

### ISSUE THREAD

**Issue by tahmid56** [flutter/website#3966]
Page URL: https://flutter.dev/docs/development/tools/sdk/releases.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/releases.md

Description of issue:The download link does not load.I cant download it.Even BITS service is not working.What can i do?

**Comment by tahmid56** [comment]
![image](https://user-images.githubusercontent.com/57156326/79410271-b4fb3880-7fc1-11ea-9822-7c30815cc5de.png)

**Comment by sfshaza2** [comment]
Hi, @tahmid56! I'm sorry to hear that you are having problems! Something is wrong with your setup and I don't know what that might be. I googled and found [issue 27276](https://github.com/flutter/flutter/issues/27276) which has some guidance. If you still have problems, I suggest you check out the Flutter Discord channel, which is described on our [community page](https://flutter.dev/community). Unfortunately, we can't help with tech support here.
