### ISSUE TITLE
'Introduction to animations' page issue: broken link to Flutter Gallery

### ISSUE THREAD

**Issue by soulbliss** [flutter/website#3967]
Page URL: https://flutter.dev/docs/development/ui/animations/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/animations/index.md

Description of issue:
There are various places where the **Flutter Gallery** link is broken and points to a 404 not found page on github.

The links should point to this 
https://github.com/flutter/gallery/tree/master/ 
instead of 
https://github.com/flutter/flutter/tree/master/examples/flutter_gallery

**Comment by soulbliss** [comment]
Created PR #3968 to fix it.

**Comment by sfshaza2** [comment]
Thanks! I was just about to fix this yesterday in another PR, but you've saved me the effort!
