### ISSUE TITLE
'Linux install' page issue

### ISSUE THREAD

**Issue by mh0s41n** [flutter/website#3970]
Page URL: https://flutter.dev/docs/get-started/install/linux.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/linux.md

Description of issue:
Download button seems not working. It's showing (failed). The button is linked to "#". See the following image.

![flutter](https://user-images.githubusercontent.com/34894685/79524340-c25f0400-804f-11ea-9a70-5351cf4111d2.png)

**Comment by sfshaza2** [comment]
@tvolkert, I have no trouble downloading the Linux flavor of Flutter on my macOS. I have recently seen some people having this issue, and I wonder if it's related to VPN or similar. Do we have info on this?

**Comment by mh0s41n** [comment]
I'm using no VPN, nor any kind of modified network configuration. As I can't access the download button, I cloned flutter from github. But I can't download Dart SDK. Here is the output of `$ flutter doctor` and `$ flutter precache`:
```Downloading Dart SDK from Flutter engine af51afceb8886cc11e25047523c4e0c7e1f5d408...                
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443 

Failed to retrieve the Dart SDK from: https://storage.googleapis.com/flutter_infra/flutter/af51afceb8886cc11e25047523c4e0c7e1f5d408/dart-sdk-linux-x64.zip
If you're located in China, please see this page:
  https://flutter.dev/community/china
```
Note that, I tried this from two linux distro (Ubuntu 18.04 and Kali Linux).
I can access the above link via Tor Browser, but tor is too slow, 200 MB will take 3-4 hours to download.

I'm not in China, nor any service of Google is blocked in my region.

**Comment by mh0s41n** [comment]
Seems it was a network issue from my ISP. Closing.

**Comment by apieceofbart** [comment]
This still a problem no matter if you're on linux or windows - you have a CORS issue on your website
![Uploading image.png…]()
