### ISSUE TITLE
'Write your first Flutter app on the web' page issue

### ISSUE THREAD

**Issue by kamidox** [flutter/website#3971]
Page URL: https://flutter.dev/docs/get-started/codelab-web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab-web.md

Description of issue:

Page URL: https://flutter.dev/docs/get-started/codelab-web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab-web.md

Description of issue:

Step 1: Show the Welcome screen: missing to add an route item '/welcome' in LoginApp class as show below:

```dart
class LoginApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        '/': (context) => LoginScreen(),
        '/welcome': (context) => WelcomeScreen(),    // <= This item was missing in the specific step, although it shows in the complete example in the end.
      },
    );
  }
}
```

Without this item, click on the "Sign up" button will not show the welcome screen. Also, the VSCode will complaint that it cannot create the route.

**Comment by sfshaza2** [comment]
Fixed
