### ISSUE TITLE
'Write your first Flutter app on the web' page issue

### ISSUE THREAD

**Issue by perelin** [flutter/website#3974]
Page URL: https://flutter.dev/docs/get-started/codelab-web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab-web.md

Description of issue:

The "Write your first Flutter app on the web" (https://flutter.dev/docs/get-started/codelab-web) is missing some steps. 

1. To conclude "Step 1: Show the Welcome screen" one needs to add the route to '/welcome' to the LoginApp class build() method. 

2. The starter app code from the dart pad in "Step 0: Get the starter web app" is using the terminology "LoginApp/Screen/Form/XXX" but the rest of the tutorial uses "SignupApp/Screen/Form/XXX".

**Comment by sfshaza2** [comment]
Fixed
