### ISSUE TITLE
Use caret constraints in dependency examples

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#3990]
Page URL: https://flutter.dev/docs/development/packages-and-plugins/using-packages.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/packages-and-plugins/using-packages.md

We shouldn't show depending on a package without a version constraint. Also, we should probably show caret notation (e.g. `^1.0.3`) instead of range notation, unless the latter is really justified.

More details: https://github.com/dart-lang/site-www/issues/2207#issuecomment-573013719

**Comment by sfshaza2** [comment]
Makes sense.
