### ISSUE TITLE
'Writing custom platform-specific code' page issue

### ISSUE THREAD

**Issue by nylonW** [flutter/website#4004]
Page URL: https://flutter.dev/docs/development/platform-integration/platform-channels.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/platform-channels.md

Description of issue: I had to add `super.configureFlutterEngine(flutterEngine)` in `override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine)` method to keep other platform channels from other pubs working

**Comment by OgulcanCelik** [comment]
Had same issue. probably with the new Flutter update, if you don't call super `configureFlutterEngine` method on java and if you have custom java code, camera plugin crashes.
