### ISSUE TITLE
'Pass arguments to a named route' page issue

### ISSUE THREAD

**Issue by NazarKalytiuk** [flutter/website#4014]
Page URL: https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/navigate-with-arguments.md

Description of issue:
An example not working
![image](https://user-images.githubusercontent.com/16141974/80656267-6ce01980-8a89-11ea-9209-1d66d1c42244.png)

**Comment by sfshaza2** [comment]
I am able to reproduce this issue. Can you look at this, @johnpryan?

**Comment by RedBrogdon** [comment]
Thanks for letting us know. @domesticmouse is investigating.

**Comment by domesticmouse** [comment]
Looks like running DartPad's Flutter on the Beta channel fixes this issue.

@timsneath and @zoeyfan looks like I need to move DartPad to running Flutter channel beta to better reflect the API documentation it is embedded in.

**Comment by domesticmouse** [comment]
I believe this is now fixed. Thanks for the report @NazarKalytiuk!
