### ISSUE TITLE
Code excerpt header boxes regression

### ISSUE THREAD

**Issue by xster** [flutter/website#4018]
Our specified header box titles are now missing

was:
<img width="751" alt="78847846-e1f98b00-79c4-11ea-9892-c56d8a3d8146" src="https://user-images.githubusercontent.com/156888/80749730-beb18f80-8adb-11ea-9045-a816f6c3879e.png">

now:
<img width="749" alt="78847860-eaea5c80-79c4-11ea-8e51-269531edbd73" src="https://user-images.githubusercontent.com/156888/80749743-c6713400-8adb-11ea-8d8b-f81da5fa6a9d.png">

Seems to have been removed by https://github.com/flutter/website/pull/3773. The headers used to describe the files to edit are very useful in project setup type instructions where the user has to edit multiple files.

**Comment by micpap25** [comment]
@sfshaza2 I can help out with this. Do you know off the top of your head what file the code excerpt headers are controlled by? I can hunt around the files if you don't.

**Comment by aadarshadhakalg** [comment]
I have #5026 pull reqquest on this.

**Comment by sfshaza2** [comment]
@khanhnwin, is this still a valid issue or can we close?

**Comment by parlough** [comment]
As far as I can tell, this functionality is still missing for snippets without code excerpts, since it was tied to that tool.

**Comment by sfshaza2** [comment]
Ah. Do we care?

**Comment by parlough** [comment]
I’d like to track this, but not enough for it to be p1, as the information can be portrayed other ways. Demoting to p3.
