### ISSUE TITLE
'Write your first Flutter app on the web' page issue

### ISSUE THREAD

**Issue by Tensa-K** [flutter/website#4031]
Page URL: https://flutter.dev/docs/get-started/codelab-web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab-web.md

Description of issue:

In the Step 1 chapter, a sub-step is missing : it is necessary to add the WelcomeScreen widget in the routes property of MaterialApp at the beginning with `'/welcome': (context) => WelcomeScreen()`.

**Comment by sfshaza2** [comment]
Thanks, @Tensa-K!

**Comment by arps18** [comment]
@Sfshaza Can I make the necessary changes?

**Comment by sfshaza2** [comment]
Yes, of course, @arps18!

**Comment by arps18** [comment]
@Sfshaza The issue seems already solved. I can't reproduce it!

**Comment by sfshaza2** [comment]
!! Well, thanks anyway, @Tensa-K! Closing this issue.
