### ISSUE TITLE
'Install' page issue

### ISSUE THREAD

**Issue by akabosdeke** [flutter/website#4034]
Page URL: https://flutter.dev/docs/get-started/install/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/index.md

Description of issue:

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
unable to resolve license issue

**Comment by sfshaza2** [comment]
Hi, @akabosdeke! I wonder if you are experiencing [issue xxx](https://github.com/flutter/flutter/issues/51712).  If so, can you weigh in on that bug?  There are potential workarounds in that issue, as well as links to other places that have workarounds. If you find any problems that should be mentioned in the docs, please add that info here.

**Comment by sfshaza2** [comment]
Closing.
