### ISSUE TITLE
'Flutter SDK releases' page issue

### ISSUE THREAD

**Issue by tibmartSynergy** [flutter/website#4061]
Page URL: https://flutter.dev/docs/development/tools/sdk/releases.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/releases.md

Description of issue:

The link for the new MacOS version has a typo in the URL. (1.17* instead of v.17*)

Expected:
https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v.17.0-stable.zip

Existing:
https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_1.17.0-stable.zip

**Comment by sfshaza2** [comment]
Hi, @tibmartSynergy! I was able to successfully download the macOS stable 1.17 release just now. Is this still happening for you?

**Comment by pcsosinski** [comment]
we removed the "v" from our versioning scheme starting with this release.

**Comment by sfshaza2** [comment]
Thanks, @pcsosinski, for weighing in!  @tibmartSynergy, we announced this change in our Medium publication. See the [Spring 2020 Updates](https://medium.com/flutter/flutter-spring-2020-update-f723d898d7af) post.

Closing.
