### ISSUE TITLE
Shouldn't showcases logo have a link to the company?

### ISSUE THREAD

**Issue by jeffque** [flutter/website#4069]
I got to the showcase page for driven by curiosity, as I've seen the baf2acf9c8eb4e9c70f893f1c66f7830fa4d43c5 commit. There, the only text file edited was [`/src/_data/showcases.yml`](https://github.com/flutter/website/blob/baf2acf9c8eb4e9c70f893f1c66f7830fa4d43c5/src/_data/showcases.yml). This got me curious about what was being shown on the showcases page, so I accessed https://flutter.dev/showcase. There I couldn't see the uploaded card. But, bellow the cards, I've seen the logo from NuBank. Then, it wasn't clickable.

> After sometime I've found it in the testimonials section, but not my point here

Shouldn't the list of organizations have some way to link to the organization itself? It just ]contains logo, name and a alt-text](https://github.com/flutter/website/blob/baf2acf9c8eb4e9c70f893f1c66f7830fa4d43c5/src/_data/company_logos.yml) for each listed company.

Maybe adding a homepage property in that [`/src/_data/company_logos.yml`](https://github.com/flutter/website/blob/baf2acf9c8eb4e9c70f893f1c66f7830fa4d43c5/src/_data/company_logos.yml) and also some rendering in [these lines](https://github.com/flutter/website/blob/baf2acf9c8eb4e9c70f893f1c66f7830fa4d43c5/src/showcase/index.html#L72-L76) to have a hyperlink?

Perharps this bellow?

```html
            {% for logo in site.data.company_logos %}
                <li class="logo-item col-6 col-md-3 mb-8 mb-lg-10">
                    <a href = "{{ logo.homepage }}">
                    {% asset '{{ logo.logo_src  }}' class="logo-image" alt="{{ logo.alt_text }}"%}
                     </a>
                </li>
            {% endfor %}
```

**Comment by sfshaza2** [comment]
@maguinis, thoughts?

**Comment by maguinis** [comment]
seems like you can make the best decision on this, Shams :) go for it -- if you think this works

**Comment by sfshaza2** [comment]
I'd rather not open this can of fish. But thanks for your feedback, @jeffque.
