### ISSUE TITLE
i am trying yo make web app but found many error 

### ISSUE THREAD

**Issue by akhileshsagarignite** [flutter/website#4073]
I am trying to make a web app but found a lot of errors. please help me

**Comment by sfshaza2** [comment]
Hi, @akhileshsagarignite! I'm sorry to hear that you are having problems. Have you tried using the [Write your first Flutter app on the web](https://flutter.dev/docs/get-started/codelab-web) codelab?

Unfortunately, we can't offer support on the repo. Please see our [Community](https://flutter.dev/community) page. There are lots of avenues for help and support from the community! Good luck!
