### ISSUE TITLE
Document the new Network tab in DevTools

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#4078]
I first became aware of it when editing the [1.17 release notes](https://medium.com/flutter/announcing-flutter-1-17-4182d8af7f8e). We need a page on [flutter.dev/docs/development/tools/devtools](https://flutter.dev/docs/development/tools/devtools).

@bkonyi

**Comment by parlough** [comment]
This was added in https://github.com/flutter/website/commit/fab855caf2097036c3fbd6c46c77e60b4f2bade0#diff-640ea675251d1f8222c6c170855e13ba41506b3f79b21c1283835d74f7b16267 and expanded in https://github.com/flutter/website/commit/49b92e9e74c36cb4c2fa916cdac1797b1f31b4b8#diff-640ea675251d1f8222c6c170855e13ba41506b3f79b21c1283835d74f7b16267
