### ISSUE TITLE
'Building a web application with Flutter' uses the beta channel unnecessarily

### ISSUE THREAD

**Issue by theturboturnip** [flutter/website#4082]
Page URL: https://flutter.dev/docs/get-started/web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/web.md

Description of issue:
The install pages and 'Building a web application with Flutter' tell the user to switch to the beta channel for web support. This is no longer necessary and can expose users to unnecessary bugs such as [Issue #53367](https://github.com/flutter/flutter/issues/53367) which are fixed on the master branch but not in the beta branch.

**Comment by sfshaza2** [comment]
@theturboturnip, which release are you using? I just switched to the stable channel and updated everything. `flutter devices` doesn't list chrome and I'm unable to run the counter app on the web.

**Comment by theturboturnip** [comment]
It looks like I got confused, sorry! I switched to master channel for some small fixes that beta doesn't have, and I didn't realize that master and stable were different. 

Knowing this, I don't think the site needs to be changed. Sorry for opening the issue unnecessarily!

**Comment by sfshaza2** [comment]
No problem! Thanks for clarifying.  :)
