### ISSUE TITLE
'Flutter widget index' page issue

### ISSUE THREAD

**Issue by ajerni** [flutter/website#4089]
Page URL: https://flutter.dev/docs/reference/widgets.html
Page source: https://github.com/flutter/website/tree/master/src/docs/reference/widgets.md

Description of issue:
looks like the AnimatedAlign widget is not listed in the index nor can I find a documentation of it.

**Comment by sfshaza2** [comment]
You are correct! Note to self: the API doc is here, [AnimationAlign](https://api.flutter.dev/flutter/widgets/AnimatedAlign-class.html).
