### ISSUE TITLE
Add dark mode for the website

### ISSUE THREAD

**Issue by nnhhiilliisstt** [flutter/website#4095]

**Comment by apravint** [comment]
#3632 is already open for this.. :)

**Comment by apravint** [comment]
Duplicate of #3632

**Comment by nnhhiilliisstt** [comment]
#3632 is about adding dark mode to the flutter documentation, this one is about adding dark mode to the website itself

**Comment by apravint** [comment]
#2952 for the dark mode to the website. please take a look.

**Comment by sfshaza2** [comment]
https://github.com/flutter/website/issues/3632 is most definitely asking for dark mode on the flutter.dev website, so this is a dupe. Closing.

(To file a request for dark mode on the api.flutter.dev docs, file an issue on the flutter/flutter repo.)
