### ISSUE TITLE
Address top 404s

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#4096]
Two 404s are now at least as common as the /images/flutter-mark-square-100.png 404 (#2391):

~~1. /go/remove-fab-accent-theme-dependency. (with the period)~~
2. /docs/resources/rendering
~~3. /flutter/material~~

/go/remove-fab-accent-theme-dependency. has existed for a long time but has gotten more prevalent lately. We should probably just redirect it.

I think /docs/resources/rendering used to exist and needs to be redirected to the new location: docs/perf/rendering? (If I do a google search for "flutter.dev/docs/resources/rendering", I get a few hits, including #3620.)

I wonder if /flutter/material (down to number 5 as of 6/5/2020) is due to people guessing the path. We might want to redirect it to /docs/development/ui/widgets/material or https://api.flutter.dev/flutter/material/material-library.html.

**Comment by sfshaza2** [comment]
I have zero, and I mean ZERO recollection of a rendering page! A complete rewrite of the Flutter Architectural Overview page is in process and will be released soon-ish. It has a great section on rendering. Until then, I'd recommend linking to this [video](https://www.youtube.com/watch?v=996ZgFRENMs).

I'd redirect the material page to the API page. which is more up to date Thx!

**Comment by kwalrath** [comment]
> You know, @kwalrath, because you labeled this bug, I never saw it!

Although you did of course... :) But I'll remember not to label flutter/website bugs!

**Comment by parlough** [comment]
The first link works now due to a regex based redirect added to redirect URLs with an extra . to the actual destination.

As for the rendering doc, now that the architectural overview is out, I've added a redirect in https://github.com/flutter/website/pull/8047
