### ISSUE TITLE
Create recipe for a collapsing ToolBar within a SliverAppBar

### ISSUE THREAD

**Issue by feinstein** [flutter/website#4097]
Page URL: https://flutter.dev/docs/cookbook/design/tabs.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/tabs.md

Description of issue:

We also need a cookbook about a collapsing ToolBar within a SliverAppBar.

There are articles like [this](https://medium.com/@diegoveloper/flutter-collapsing-toolbar-sliver-app-bar-14b858e87abe), but such a common use case should have an official cookbook as well IMO.

The docs on the [`NestedScrollView`](https://api.flutter.dev/flutter/widgets/NestedScrollView-class.html) already have a good example on this.

**Comment by sfshaza2** [comment]
Good idea!

**Comment by feinstein** [comment]
Unfortunately a collapsing ToolBar within a SliverAppBar is a bit buggy: https://github.com/flutter/flutter/issues/17518, so the article should mention it for the time being.

**Comment by sfshaza2** [comment]
@miquelbeltran, please weigh in. Does this work better now?

**Comment by miquelbeltran** [comment]
I think this example is well covered in https://docs.flutter.dev/cookbook/lists/floating-app-bar and for more advanced examples there is also https://docs.flutter.dev/ui/layout/scrolling/slivers

**Comment by feinstein** [comment]
I disagree, in this issue I am suggesting the creation of a **cookbook for collapsing Toolbar**, which deals with **Tabs**, the cookbook you pointed out covers only a collapsing App Bar, there are **no tabs there**.

I think it's not productive to point out the official docs, that cover how to use the widget, when I am suggesting cookbooks. I know the docs, my cookbook suggestions are for the new devs joining Flutter, not for me.
