### ISSUE TITLE
'Books about Flutter' page issue

### ISSUE THREAD

**Issue by dcarreroc** [flutter/website#4100]
Page URL: https://flutter.dev/docs/resources/books.html
Page source: https://github.com/flutter/website/tree/master/src/docs/resources/books.md

Description of issue:

The link to "Programming Flutter" ebook is wrong, must be https://pragprog.com/book/czflutr/programming-flutter

**Comment by sfshaza2** [comment]
@dcarreroc, the link you provided is a broken link.

**Comment by rdenhof** [comment]
From my point of view link used in https://github.com/flutter/website/blob/master/src/_data/books.yml is working (only missing last url segment /programming-flutter).

**Comment by sfshaza2** [comment]
@dcarreroc, there seems to be a redirect in place. When I go to the URL in the yaml file, https://pragprog.com/book/czflutr ,
it goes straight to the correct page.

**Comment by sfshaza2** [comment]
Closing.
