### ISSUE TITLE
'Building a web application with Flutter' page issue

### ISSUE THREAD

**Issue by lautaropaske** [flutter/website#4109]
Page URL: https://flutter.dev/docs/get-started/web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/web.md

Description of issue:

*You can install [Android Studio][], [IntelliJ IDEA][], or [Visual Studio Code][]* <= Missing links for IDEs, markdown error.

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/4108.
