### ISSUE TITLE
Cannot download Android Studio: This site can't be reached

### ISSUE THREAD

**Issue by RomanKornev** [flutter/website#4124]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:
First step in **Install Android Studio**
Cannot download Android Studio as "This site can't be reached"
https://redirector.gvt1.com/edgedl/android/studio/install/3.6.3.0/android-studio-ide-192.6392135-windows.exe
![image](https://user-images.githubusercontent.com/5807561/82738019-89483c80-9d3d-11ea-84e2-a9c98e1c3811.png)

Any other way to install it without Android Studio?

**Comment by sampathbalivada** [comment]
I have no issues with the given link and the Android Studio site is perfectly fine. It's a possibility that the issue is fixed now. Can you try again and give more info if possible, like if you are using an Ad Blocker, a custom DNS or something else.

**Comment by RomanKornev** [comment]
Thanks for confirming that it works for you! I finally solved it: it was a misconfigured `hosts` file.

**Comment by Argyrokastritis** [comment]
I'm having the same issue I tried to pause me adblocker but the problem insisted. I even tried to reset the dns cache.I'm sure my mac has the problem as from my windows pc it downloaded the file without any problem.
