### ISSUE TITLE
'Implicit animations' page; what is reason for Future<void> main() async ?

### ISSUE THREAD

**Issue by dev-aentgs** [flutter/website#4128]
Page URL: https://flutter.dev/docs/codelabs/implicit-animations.html
Page source: https://github.com/flutter/website/tree/master/src/docs/codelabs/implicit-animations.md

Description of issue:
In this codelab, why is `Future<void> main() async` used instead of `void main()` ?
The code works even if the main method is synchronous as `void main()`. 
Could not find any parts that require asynchronous operation. 
Is it because `NetworkImage` is used?
Is it part of best practices when working with animations in flutter?

**Comment by sfshaza2** [comment]
Good question!  @goderbauer, do you have any insight?

**Comment by goderbauer** [comment]
There's no good reason. AFAIK, it doesn't really hurt to have it there, but it also doesn't serve a purpose. We should simplify it.
