### ISSUE TITLE
Building a Cupertino app with Flutter codelab typo

### ISSUE THREAD

**Issue by dev-aentgs** [flutter/website#4133]
In [6. List products for sale](https://codelabs.developers.google.com/codelabs/flutter-cupertino/#5), There is a small typo just below 
> lib/product_list_tab.dart

`ProductListTab` is mentioned as `ProductRowTab`

>  In the build() method for ProductRowTab, get the product list and the number of products. Add the new lines indicated below:

**Comment by sfshaza2** [comment]
@domesticmouse

**Comment by domesticmouse** [comment]
Fixed, and production publish requested. This should be out in the next five minutes or so.
