### ISSUE TITLE
Building a Cupertino app with Flutter issue

### ISSUE THREAD

**Issue by dev-aentgs** [flutter/website#4134]
In `ProductListTab`, the code given on codelab page has `builder: (context, child, model)` .
This gives error.
`Error: The method 'getProducts' isn't defined for the class 'Widget'`
`final products = model.getProducts();`
`Try correcting the name to the name of an existing method, or defining a method named 'getProducts'`

The [github product_list_tab.dart](https://github.com/googlecodelabs/flutter-cupertino-store/blob/master/step-02/lib/product_list_tab.dart ) at the bottom of the page has `builder: (context, model, child)` .
This works.

Please update the code sections on codelab page.

**Comment by sfshaza2** [comment]
@domesticmouse

**Comment by domesticmouse** [comment]
Updated, and publish to production queued. 

Oh, what I'd do for code in the codelabs to be automatically snippeted from GitHub repos with some form of marker. =)

Thanks for digging into the codelabs @dev-aentgs, it's much appreciated!

**Comment by sfshaza2** [comment]
I think we can close this now.  :).

**Comment by dev-aentgs** [comment]
Thank you @sfshaza2  and @domesticmouse
