### ISSUE TITLE
'Web FAQ' page issue

### ISSUE THREAD

**Issue by Tawmess** [flutter/website#4135]
Page URL: https://flutter.dev/docs/development/platform-integration/web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/web.md

Description of issue:

This listed FAQ seems wrong -- the "hot reload" works for web -- on both AS and VS IDE's...
FAQ) Does hot reload work with a web app?
A) No, but you can use hot restart.

FYI -- I'm completely new -- so, I hesitate to fix this, myself

**Comment by sfshaza2** [comment]
Actually, the FAQ is correct. When running on the web, the "r" command performs a hot restart, not a hot reload. If running from the command line, you will see this note:

```
🔥  To hot restart changes while running, press "r" or "R".
```
