### ISSUE TITLE
'Play and pause a video' page issue

### ISSUE THREAD

**Issue by surya-theCoder** [flutter/website#4147]
Page URL: https://flutter.dev/docs/cookbook/plugins/play-video.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/plugins/play-video.md

Description of issue: E/ExoPlayerImplInternal( 6911): Source error.
I/flutter ( 6911): PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4, null)

**Comment by sfshaza2** [comment]
I'm guessing that this cookbook recipe isn't working. @johnpryan, could you take a quick look?

**Comment by lucalves** [comment]
I believe it is working normally. Did you even include the permissions in AndroidManifest.xml?

**Comment by johnpryan** [comment]
Yes I believe these instructions are up to date. @surya-theCoder can you double check that you followed step 2 correctly?

**Comment by johnpryan** [comment]
I'm going to consider this issue as stale. @surya-theCoder please comment if you think this is still a problem with our docs. Thanks!
