### ISSUE TITLE
'Visual Studio Code' page issue

### ISSUE THREAD

**Issue by mthan160** [flutter/website#4150]
Page URL: https://flutter.dev/docs/development/tools/vs-code.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/vs-code.md

Description of issue:
Can we add in details of how to target different flutter build modes in VS Code - debug / release / profile on this page. I couldn't find specific documentation - though it is mentioned briefly here: https://flutter.dev/docs/perf/rendering/ui-performance#run-in-profile-mode

**Comment by sfshaza2** [comment]
Good idea. It looks like this is done in the launch.json file, by editing the `flutterMode` field in `configurations`.

**Comment by mthan160** [comment]
Yeah - I only find the options listed at https://github.com/Dart-Code/Dart-Code/blob/05f13bd1a835872cb3dfb86d0cf3da3446a8cdd0/package.json#L1708

Along with all the other launch.json parameters.

**Comment by sfshaza2** [comment]
Very resourceful! If you want to submit a PR, I'd welcome that.  :)

**Comment by mthan160** [comment]
Hm OK - it'll be my first pull request - let me see what I can do!

**Comment by micpap25** [comment]
Hi @mthan160 , are you working on this PR? Just let me know because I'm also interested in fixing this.

**Comment by mthan160** [comment]
Oh please - if you'd like to do a PR for it do go ahead. This is info that
desperately needs to go in.

TBH I'm quite new to Github and have never done a PR yet perhaps you'd be
better qualified to do it.

Regards,

mthan160
