### ISSUE TITLE
'User interface' page issue

### ISSUE THREAD

**Issue by dev-aentgs** [flutter/website#4151]
Page URL: https://flutter.dev/docs/development/ui/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/index.md

Description of issue:
The below point in the list has no link attached.
- Platform-specific theming

**Comment by sfshaza2** [comment]
Wow, interesting. The only platform-specific info we currently have along these lines is:

* [Platform-specific behaviors and adaptations](https://flutter.dev/docs/resources/platform-adaptations)

Apparently, this was a placeholder in the side nav, and should be removed.
