### ISSUE TITLE
Update obfuscation page to note Linux/Windows support --obfuscate now

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/website#4154]
https://flutter.dev/docs/deployment/obfuscate

Support for both has landed in master, the page should be updated on a dev release gives us a new version number.

**Comment by sfshaza2** [comment]
@jonahwilliams, can you provide a link to the PR where this landed?

**Comment by jonahwilliams** [comment]
For windows: https://github.com/flutter/flutter/pull/57749
For linux: https://github.com/flutter/flutter/pull/58372 (should land shortly)

**Comment by sfshaza2** [comment]
Related: @xster [created a PR](https://github.com/flutter/website/pull/4171) that updated this text.
