### ISSUE TITLE
'Flutter Favorite program' page issue

### ISSUE THREAD

**Issue by kodadasi04** [flutter/website#4163]
Page URL: https://flutter.dev/docs/development/packages-and-plugins/favorites.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/packages-and-plugins/favorites.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by sfshaza2** [comment]
No issue listed. Closing.
