### ISSUE TITLE
Update info about formatting code in Android Studio and IntelliJ

### ISSUE THREAD

**Issue by alexander-doroshko** [flutter/website#4168]
Page: https://flutter.dev/docs/development/tools/formatting#automatically-formatting-code-in-android-studio-and-intellij

Source: https://github.com/flutter/website/blob/master/src/docs/development/tools/formatting.md#automatically-formatting-code-in-android-studio-and-intellij

'Reformat Code with dartfmt' action is still there but there's no more need in it. Standard 'Reformat Code' action now invokes dartfmt. Standard shortcut is `Cmd+Alt+L` on Mac or `Ctrl+Alt+L` on Windows and Linux.

Also, there's a check box `Format code on save` on the Flutter page in Preferences (Mac) / Settings (Windows, Linux).

**Comment by sfshaza2** [comment]
Nice additions!

**Comment by EmperorYP7** [comment]
Linked a PR to resolve this issue. I'd be glad if someone reviews it!

**Comment by sfshaza2** [comment]
Fixed! Thanks, @alexander-doroshko!

**Comment by alexander-doroshko** [comment]
Thanks! Sorry for being a bit late. Added some comments to the PR.
