### ISSUE TITLE
Fix contradiction between main section and asset variants section on 'Adding assets and images' page

### ISSUE THREAD

**Issue by dev-aentgs** [flutter/website#4175]
Page URL: https://docs.flutter.dev/ui/assets-and-images
Page source: https://github.com/flutter/website/tree/main/src/ui/assets-and-images.md

Description of issue:

>  Note: Only files located directly in the directory are included. To add files located in subdirectories, create an entry per directory.

The above note contradicts [asset variants](https://docs.flutter.dev/ui/assets-and-images#asset-variants) ending section.

> If, on the other hand, the graphics directory is specified:

```yaml
flutter:
  assets:
    - graphics/
```

> Then the graphics/my_icon.png, graphics/background.png and graphics/dark/background.png files are also included.

For  `graphics/dark/background.png` , sub-directory entry in `pubspec.yaml` would be necessary.

**Comment by atsansone** [comment]
This note now states:

> Note: Only files located directly in the directory are included unless there are files with the same name inside a subdirectory (see [Asset Variants](https://docs.flutter.dev/ui/assets-and-images#asset-variants)). To add files located in subdirectories, create an entry per directory.

This removes the contradiction. Closing this issue.
