### ISSUE TITLE
'Send data to a new screen' page issue

### ISSUE THREAD

**Issue by dev-aentgs** [flutter/website#4190]
Page URL: https://flutter.dev/docs/cookbook/navigation/passing-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/passing-data.md

Description of issue:
Creation of `TodoScreen` is not mentioned in the steps until [interactive-example-section](https://flutter.dev/docs/cookbook/navigation/passing-data#interactive-example).
It would be helpful to add `TodoScreen` creation similar to `DetailScreen`.

**Comment by sfshaza2** [comment]
Good idea!

**Comment by EmperorYP7** [comment]
I'd like to work on it.

**Comment by EmperorYP7** [comment]
Tried to modify the specific file in my PR. I hope it'll be reviewed soon! :smiley:

**Comment by dev-aentgs** [comment]
#4198 fixed this issue.
