### ISSUE TITLE
Gallery has been removed from flutter/example

### ISSUE THREAD

**Issue by CareF** [flutter/website#4191]
https://flutter.dev/docs/perf/rendering/ui-performance#programmatically (https://github.com/flutter/website/blob/master/src/docs/perf/rendering/ui-performance.md#programmatically) Gallery has been removed from flutter/example. And I can't see the "show overlay" option when I compile gallery in profile mode, not sure but it seems the feature is also removed.

**Comment by JuYeong0413** [comment]
Seems like this issue is fixed. #4225
