### ISSUE TITLE
Add Windows-specific info on finding path issues

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#4193]
The pages under https://flutter.dev/docs/get-started/install have a note aimed at helping people who've downloaded both the Flutter & Dart SDKs to avoid path issues. This note features the `which` command, which works on all the platforms except Windows.

**Can anyone give us the equivalent text and commands for the Windows platform?** (Alternatively, if you know of a site that covers this, we'd love to see it. Just add a comment to this issue.)

If you create a PR  that fixes this, we'd be forever grateful. You'd need to do the following:

1. Make a copy of the contents of [dart-tool.md](https://github.com/flutter/website/blob/master/src/_includes/dart-tool.md).
1. Edit your copy, so its contents are correct for Windows.
1. Edit [_get-sdk-win.md](https://github.com/flutter/website/blob/master/src/docs/get-started/install/_get-sdk-win.md) (which you can do using the GitHub interface), changing the following line to instead have your Windows-specific contents:

```
{% include dart-tool.md %}
```

**Comment by mit-mit** [comment]
Windows has a `WHERE` command which is roughly equivalent.

**Comment by kwalrath** [comment]
We do mention the `where` command, but we weren't sure it was everywhere or what examples to give for using it.
