### ISSUE TITLE
List pre-reqs up top in Getting Started

### ISSUE THREAD

**Issue by sethladd** [flutter/website#42]
e.g. do I need a phone? What kind, and version(s)? What OS and what version(s)? Any cables? Do I need other software like XCode?

maybe even show a picture to illustrate the setup.

**Comment by abarth** [comment]
Yeah, good point.  At this point you need an Android phone, a Mac or Linux host.  A USB cable to connect them.

**Comment by sethladd** [comment]
Happy to make the addition. Will send PR

**Comment by FlutterIssues** [comment]
This issue was moved to flutter/flutter#1448
