### ISSUE TITLE
'Internationalizing Flutter apps' page issue

### ISSUE THREAD

**Issue by frolovpv** [flutter/website#4201]
Page URL: https://flutter.dev/docs/development/accessibility-and-localization/internationalization.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: what is this? [https://ibb.co/mhwRxGD](screen)

**Comment by sfshaza2** [comment]
Nothing listed. Closing.
