### ISSUE TITLE
Consider moving general widget rebuild information to UI performance page

### ISSUE THREAD

**Issue by guidezpl** [flutter/website#4206]
There is information in https://flutter.dev/docs/development/tools/android-studio#show-performance-data that is very useful but also not specific to Android Studio/IntelliJ. It would be useful to surface in the [article](https://flutter.dev/docs/perf/rendering/ui-performance#viewing-the-widget-rebuild-profiler) which links to this section.

That article's section could then be called something like "Checking for excessive widget rebuilds".

**Comment by sfshaza2** [comment]
An excellent idea!

**Comment by atsansone** [comment]
This appears to be found on the [Performance view page](https://docs.flutter.dev/tools/devtools/performance#track-widget-builds) now. This was committed in https://github.com/flutter/website/pull/6866. Closing this issue.
