### ISSUE TITLE
'윈도우에서 설치' page issue

### ISSUE THREAD

**Issue by soonkuk** [flutter/website#4211]
Page URL: https://flutter-kr.io/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

There is a typo in korean language.

https://flutter-ko.dev/docs/get-started/install/windows#android-%EC%84%A4%EC%A0%95

Flutter는 Android 플랫폼에  **종속정인  --> 종속적인**  부분이 있기 때문에 Android 스튜디오를 전부 설치해야 합니다.

https://flutter-ko.dev/docs/get-started/install/windows#android-%EC%97%90%EB%AE%AC%EB%A0%88%EC%9D%B4%ED%84%B0-%EC%84%A4%EC%A0%95

4. Flutter에 **안드로이기 --> 안드로이드** 기기가 연결됐는지 확인하기 위해 터미널에서 flutter devices 명령을 실행하세요. 기본적으로, Flutter는 adb 도구에 연결된 버전의 Android SDK를 사용합니다.

**Comment by sfshaza2** [comment]
Thanks for filing this error, however the Korean Flutter website is community maintained. I'm not even sure where their repo is. Can you report this there?
