### ISSUE TITLE
'Hero animations' page issue 

### ISSUE THREAD

**Issue by dev-aentgs** [flutter/website#4214]
Page URL: https://flutter.dev/docs/development/ui/animations/hero-animations.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/animations/hero-animations.md

Description of issue:
In [Standard hero animations - What’s going on?](https://flutter.dev/docs/development/ui/animations/hero-animations#whats-going-on) section, the link to [Material Design motion spec](https://material.io/guidelines/motion/movement.html) redirects to [material.io design page](https://material.io/design) .

**Comment by sfshaza2** [comment]
It looks like things moved around since I wrote this. The correct link should be:  https://material.io/design/motion/understanding-motion.html

**Comment by dev-aentgs** [comment]
#4218 fixed this issue.
