### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by Rifat-Alam521** [flutter/website#4220]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:I cant download flutter sdk its loadin and says failed.

**Comment by sfshaza2** [comment]
Hi @Rifat-Alam521! I'm sorry to hear that. It sounds like you may have a VPN issue or something similar. Please look to the [Flutter community](https://flutter.dev/community) for support and file a bug if you have specific suggestions to improve the docs. Thanks!
