### ISSUE TITLE
'Visual Studio Code' page issue

### ISSUE THREAD

**Issue by xgqfrms** [flutter/website#4226]
Page URL: https://flutter.dev/docs/development/tools/vs-code.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/vs-code.md

Description of issue:

***

# error description

https://flutter.dev/docs/development/tools/vs-code#hot-reload-vs-hot-restart

![image](https://user-images.githubusercontent.com/7291672/84617665-53444580-af02-11ea-81c6-9e08fe0794ab.png)

> not exist the command `Flutter: Hot Restart ` in the vscode

![image](https://user-images.githubusercontent.com/7291672/84617772-956d8700-af02-11ea-9380-be7f9550ec5f.png)

![image](https://user-images.githubusercontent.com/7291672/84617788-a3230c80-af02-11ea-9585-17209e50286c.png)

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/84617872-f301d380-af02-11ea-92ce-a4a7fecafdea.png)

```code
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:http/http.dart' as http;
import 'dart:convert';

```

import 'package:http/http.dart' as http;

Target of URI doesn't exist: 'package:http/http.dart'.
Try creating the file referenced by the URI, or Try using a URI for a file that does exist.darturi_does_not_exist

**Comment by xgqfrms** [comment]
https://flutter.dev/docs/cookbook/networking/fetch-data

# pubspec.yaml

https://stackoverflow.com/questions/53462488/flutter-how-to-resolve-error-importing-packagehttp-http-dart

![image](https://user-images.githubusercontent.com/7291672/84617973-4411c780-af03-11ea-92e6-9cda5cb2aed0.png)

## flutter packages get

![image](https://user-images.githubusercontent.com/7291672/84618012-58ee5b00-af03-11ea-9683-0b0eb16c66ac.png)

```sh
# pub
$ pub get

# Flutter:
$ flutter packages get

```

https://stackoverflow.com/questions/53744989/flutter-http-package-does-not-exist

**Comment by xgqfrms** [comment]
# @flutter_ignore_below_line

> 不存在 pubspec.yaml bug

![image](https://user-images.githubusercontent.com/7291672/84618258-3dd01b00-af04-11ea-9ed1-b0edf0da0d52.png)

**Comment by xgqfrms** [comment]
# flutter ignore warning


https://dart.dev/guides/language/analysis-options

https://stackoverflow.com/questions/35969619/suppress-hint-about-use-of-protected-member

https://github.com/dart-lang/sdk/issues/12490

https://pub.dev/packages/linter

**Comment by sfshaza2** [comment]
Yes, most of our instructions assume Android Studio or IntelliJ. We appreciate feedback on the VS code IDE!

**Comment by micpap25** [comment]
Could someone verify if this is still an issue, and if the Ctrl+F5 shortcut Hot Restarts? This is going to lead to a lot of changes in both this page and https://flutter.dev/docs/development/tools/hot-reload to fully resolve.

**Comment by atsansone** [comment]
This should no longer be an issue. Image is from VSCode 1.71.1 with the [Flutter v3.60.0 plugin](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) on Windows 11, last updated on 10 May 2023 at 12:54:12.

![image](https://github.com/flutter/website/assets/706219/dd685a16-2f5c-46b3-9ff1-590060cea280)
