### ISSUE TITLE
'Staggered animations' page question

### ISSUE THREAD

**Issue by dev-aentgs** [flutter/website#4227]
Page URL: https://flutter.dev/docs/development/ui/animations/staggered-animations.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/animations/staggered-animations.md

Question: 
In the [basic staggered animation](https://github.com/flutter/website/blob/master/examples/_animation/basic_staggered_animation/main.dart) code, why is variable initialization part before variable declaration in `StaggerAnimation`?

**Comment by sfshaza2** [comment]
@HansMuller

**Comment by HansMuller** [comment]
Our style is to declare the variables first.

**Comment by sfshaza2** [comment]
Closing.
