### ISSUE TITLE
Bytedance Android link is not working.

### ISSUE THREAD

**Issue by zoeyfan** [flutter/website#4234]
Repro:
1. go to flutter/dev/showcase
2. find bytedance, click Android in the dropdown menu
3. Notice that it takes you to a "URL not found" page. 

Suggested fix: please replace the current link with: https://play.google.com/store/apps/details?id=com.ss.android.article.news

Please ping me when you are going to look into this so I can learn how to submit a PR to flutter.dev. Thanks!
@johnpryan

**Comment by zoeyfan** [comment]
wow, thanks so much for fixing this quickly! I was originally planning to learn how to submit a PR and fix it myself, haha~ I will get in touch with Shams quickly just to learn about the process for my own education purpose then. Thank you again!

**Comment by sfshaza2** [comment]
Hi, @zoeyfan, I'd be happy to teach you after Flutter Day!

**Comment by zoeyfan** [comment]
@sfshaza2 thank you! I will schedule some time after Flutter Day then!
