### ISSUE TITLE
'Build and release an Android app' page issue

### ISSUE THREAD

**Issue by bestkid1234** [flutter/website#4237]
Page URL: https://flutter.dev/docs/deployment/android.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/android.md

Description of issue: Is missing a detail for a successful build -> You need to specify the ```buildToolsVersion``` in build.gradle.

**Comment by sfshaza2** [comment]
@bestkid1234, is there a way to initiate this from the pubspec file? As it works in https://github.com/flutter/website/issues/4236?

**Comment by bestkid1234** [comment]
Hi!
No, you shoud do it "manually" by introducing the build tool version in android/gradle.build
Ovidiu Uşvat

Sent from Yahoo Mail on Android 
 
  On Wed, Jun 17, 2020 at 21:58, Shams Zakhour (ignore Sfshaza)<notifications@github.com> wrote:   


@bestkid1234, is there a way to initiate this from the pubspec file? As it works in #4236?

**Comment by sfshaza2** [comment]
That's what I was afraid of. Thx!
