### ISSUE TITLE
'Flutter SDK releases' page issue

### ISSUE THREAD

**Issue by yikwing** [flutter/website#4242]
Page URL: https://flutter.dev/docs/development/tools/sdk/releases.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/releases.md

Description of issue:
flutter 1.17.4, New projects, the device will not be found, adb devices and flutter devices is ok.but idea and android studio tool bar error flutter run: No connected devices.

**Comment by sfshaza2** [comment]
@yikwing, can you elaborate a bit more? I don't understand the issue.
