### ISSUE TITLE
Broken sample - Missing concrete implementation of 'StatelessWidget.build'

### ISSUE THREAD

**Issue by domesticmouse** [flutter/website#4248]
From https://github.com/dart-lang/dart-pad/issues/1579

The [codelab](https://codelabs.developers.google.com/codelabs/flutter/#3) contains a link to the gist [99243efc05f92cd541af5e279c012050](https://gist.github.com/sfshaza2/99243efc05f92cd541af5e279c012050)

This gist is missing a `{` on [line 26](https://gist.github.com/sfshaza2/99243efc05f92cd541af5e279c012050#file-main-dart-L26).

**Comment by sfshaza2** [comment]
Thanks! Fixed.
