### ISSUE TITLE
Widget_test problem 

### ISSUE THREAD

**Issue by acendre** [flutter/website#4250]
I was doing the tutorial for the cupertino AppStore when errors appears and don't know how to resolve it. I just copied code from GitHub file but it's doesn't work. I'm on Mac and using [VScode.
![Capture d’écran 2020-06-21 à 23 34 56](https://user-images.githubusercontent.com/63961762/85235805-39ca5e80-b418-11ea-828f-640879138616.png)
Thank in advance

**Comment by sfshaza2** [comment]
@domesticmouse

**Comment by domesticmouse** [comment]
Looks like VSCode has failed to correctly check out dependencies. I'd shutdown VSCode, confirm the code works from the command line with `flutter run` and then open up VSCode again on the specific step you are interested in.

I've found VSCode can be a bit iffy with checkouts that contain multiple flutter projects.

**Comment by DanTup** [comment]
I'm not familiar with the project mentioned here - is there a repo/document I can try out to see if I can repro?

Generally when opening a new project that has no `.packages` file, there should be a prompt to run `pub get` like this:

<img width="535" alt="Screenshot 2020-06-23 at 09 28 02" src="https://user-images.githubusercontent.com/1078012/85379616-e0efe880-b533-11ea-88c1-a741dce9fad1.png">

VS Code will collapse these notifications after some time (10 seconds?) though (something we can't control) so if you miss it, you'll have issues like this until you manually run **Dart: Get Packages** from the VS Code Command prompt or click the bell icon in the bottom right corner and run it from the collapsed notification.

If you modify the `pubspec.yaml`, `pub get` should be run automatically by default.

If you see situations where any of this might not be working reliably, do file issues at https://github.com/Dart-Code/Dart-Code with as much info as you can that might help reproduce it. Thanks!

**Comment by domesticmouse** [comment]
@DanTup the repository in question is https://github.com/googlecodelabs/flutter-cupertino-store 

I just tried it myself against VSCode Version: 1.46.1 with Flutter 3.11.0 and it indeed shows the Get packages pop up. The various projects show as red until `flutter pub get` has been run by VSCode in each step sub directory.

@acendre can you replicate?

**Comment by acendre** [comment]
Hello ! 
Thanks for answering so fast. I did what you suggested but it didn't work.

I will detail what I have and what I did to have this.

**Comment by acendre** [comment]
Sorry if I'm not that familiar with Git process but I'm new to it.
VScode Version: 1.46.1
Where did you see Flutter version ? It's recent

I just downloaded the project, put it in my developement repository where flutter repo is. Then launch VScode and open the project cupertino_store. Then I did flutter pub get or/and package get. It didn't change errors that much. (PS : I already achieve to create the app "start_up").

**Comment by DanTup** [comment]
@acendre if you run `flutter analyze` from the terminal in the same folder, do you see the same errors reported?

**Comment by acendre** [comment]
Yes exactly the same ... 

flutter pub get and packages get are the same command ?

**Comment by DanTup** [comment]
Yep, they're the same command. For the project (or one of the projects) that are showing errors like this, is there a `.packages` file in the root of the project? Does it contain a line for `flutter_test`?

**Comment by acendre** [comment]
Yes, there is file .packages : 
![Capture d’écran 2020-06-30 à 16 38 16](https://user-images.githubusercontent.com/63961762/86139654-4b82c480-baf0-11ea-9a2e-9dd4c5abe4da.png)

**Comment by DanTup** [comment]
@acendre can you check you have this in your `pubspec.yaml`?

```yaml
dev_dependencies:
  flutter_test:
    sdk: flutter
```

I think it's probably missing. It should be in the default `pubpsec.yaml` created by the **Flutter: New Project** command.

**Comment by acendre** [comment]
Ok thank you, it's good now. Does it exist processes to follow into avoiding that manipulation when we open an existing project ?

**Comment by DanTup** [comment]
@acendre I'm not sure how you ended up without that dependency. It's included automatically when you create a project with `flutter create` or **Flutter: New Project**. Is it possible you accidentally removed it while modifying the `pubspec.yaml`? Or did you build the project manually from following some instructions? (in which case, maybe they are missing this?).

**Comment by domesticmouse** [comment]
Closing this out as the debugging conversation appears to have gone stale.
