### ISSUE TITLE
"Write Your First Flutter App, part 2" - Step 6 - Incorrect line of code and missing semicolon

### ISSUE THREAD

**Issue by anthonymoretti** [flutter/website#4256]
Hi. There is a problem with the last line of code and there is a missing semicolon in this codelab section:

Write Your First Flutter App, part 2
Step 6: Navigate to a new screen

It should be:
```
    body: _buildSuggestions(),
);
```

![image](https://user-images.githubusercontent.com/3210808/85346215-a0e42380-b4a9-11ea-9db6-bcded3bde2f2.png)
@domesticmouse

**Comment by sfshaza2** [comment]
I believe this has been fixed.

**Comment by kwalrath** [comment]
It looks like the [flutter/sample file](https://github.com/flutter/codelabs/blob/master/startup_namer/step6_add_interactivity/lib/main.dart) is fixed, but not the doc (or published codelab), which still has `home: RandomWords(),`.

**Comment by kwalrath** [comment]
OK, I've fixed the published codelab.
