### ISSUE TITLE
'Create lists with different types of items' page issue

### ISSUE THREAD

**Issue by MToheed** [flutter/website#4257]
Page URL: https://flutter.dev/docs/cookbook/lists/mixed-list.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/lists/mixed-list.md

Description of issue:
In Interactive example portion, why there is use of foundation library.

**Comment by sfshaza2** [comment]
Hi, @MToheed! You are quite right. The foundation library doesn't need to be explicitly imported in this example. We should remove it.

Sometimes the foundation library is explicitly imported when the code uses the `@required` annotation, which is defined in that library.
