### ISSUE TITLE
'Code formatting' page issue

### ISSUE THREAD

**Issue by peRF0rmAncEb00st** [flutter/website#4259]
Page URL: https://flutter.dev/docs/development/tools/formatting.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/formatting.md

Description of issue:

The content of the page is wrong. It says that on Android studio I have a checkbox that says `Format code on save` when I open the settings for dart (Setting -> Editor -> Code style -> Dart). However, such option is missing.
(The only option I have with checkbox is the `Use the dartfmt tool` one.)

I'm using Android studio 3.6.3.

**Comment by JuYeong0413** [comment]
I'm using Android Studio 4.0.1. 
<img width="1109" alt="Screen Shot 2020-07-26 at 10 21 57 PM" src="https://user-images.githubusercontent.com/33684401/88480056-a04e1980-cf8e-11ea-8d89-9eea63155f22.png">
There is `Format code on save` on the Flutter page in Preferences on Mac as the docs mentioned. (Preferences -> Language & Frameworks -> Flutter)
Seems like you're looking at the wrong section. You should open the settings for `Flutter`, not `Dart`.

**Comment by aromalanil** [comment]
@sfshaza2 Hope this issue can be closed
