### ISSUE TITLE
Document AOT size reduction via DWARF stack traces

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#4260]
See dart-lang/site-www#2360 for details.

/cc @mit-mit

**Comment by mit-mit** [comment]
The core point is this; we should talk about it as a perf tool: https://github.com/dart-lang/site-www/issues/2360#issuecomment-618354147

**Comment by mit-mit** [comment]
@Sfshaza looks like this was documented here now, so I'll close this

https://flutter.dev/docs/perf/app-size#reducing-app-size
