### ISSUE TITLE
iOS build issue in the Firebase for Flutter codelab

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#4266]
After completing step 5.1: https://codelabs.developers.google.com/codelabs/flutter-firebase/#4. Running the app threw an error and it never finished building for the iOS Simulator. 
![image](https://user-images.githubusercontent.com/348942/85805985-abe5c080-b702-11ea-8815-aa9d58170a24.png)

Removing the cloud_firestore dependency added in the previous step fixed the issue. Another way that resolved the issue for me was to complete the step 7 [Platform-specific Firebase configuration](https://codelabs.developers.google.com/codelabs/flutter-firebase/#6)

So maybe the step about adding cloud_firestore to pubspec should be introduced later in the codelab? 

Flutter doctor output

[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.4 at /Users/taodong/Development/flutter/flutter
    • Framework revision 1ad9baa8b9 (8 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/taodong/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone 11 • 06B12438-29DD-44BA-91BA-5D38B56A90B6 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

**Comment by ditman** [comment]
I'll give this a try, that part of the codelab is a few years old, and things might have changed in the firebase packages since then!

**Comment by domesticmouse** [comment]
The `flutter-firebase` codelab has been replaced by the [Get to know Firebase for Flutter](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#0) codelab. Thanks for the report!
