### ISSUE TITLE
[Suggestion] 'Understanding constraints' page, text background color on dartpad

### ISSUE THREAD

**Issue by katisari** [flutter/website#4267]
Page URL: https://flutter.dev/docs/development/ui/layout/constraints.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/layout/constraints.md

Description of suggestion:

The explanation part of each example on the dartpad is difficult to read with the grey background color.
we may be able to improve readability by replacing the color on line 148 on the dartpad with a lighter color like
Colors.white or Colors.grey[50]

**Comment by sfshaza2** [comment]
Very good call, @katisari!

**Comment by aayushbisen** [comment]
Can I work on this issue? 😃

**Comment by sfshaza2** [comment]
Sure!!
