### ISSUE TITLE
No Link To Creating Useful Bug Reports In Table of Contents

### ISSUE THREAD

**Issue by mjordan56** [flutter/website#4268]
There's no link in the Flutter website's Table of Contents for the "Creating useful bug reports" page. The URL for this page (https://flutter.dev/docs/resources/bug-reports) indicates that it is organized under the Resources section but there isn't link under the Resources section of the TOC for the bug reports page. Having a link in the TOC would make finding and accessing the page much easier for users.

**Comment by sfshaza2** [comment]
Good catch, @mjordan56!
