### ISSUE TITLE
Index page not responsive on mobile browser

### ISSUE THREAD

**Issue by AsaoluElijah** [flutter/website#4269]
The index page - https://flutter.dev/ is not responsive on mobile browsers.
### Screenshot:
![Screenshot_20200626-223136](https://user-images.githubusercontent.com/34748637/85902972-285cca00-b7fd-11ea-987a-59b9800df2f7.png)

**Comment by parlough** [comment]
The new marketing site index page (at [flutter.dev](https://flutter.dev)) and the docs site one (at [docs.flutter.dev](https://docs.flutter.dev)) both seem to be filling the viewport properly for me with the latest changes.

If you see more issues, let us know. Thanks!
