### ISSUE TITLE
Add new codelabs to flutter.dev/docs/codelabs page

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#4272]
As is says.  :)

**Comment by micpap25** [comment]
Hi @sfshaza2 , The only Flutter codelab that isn't on the page is `Intro to Dart for Java Developers`, which arguably isn't really a Flutter codelab and shouldn't have that label on the Google Codelabs site. (If there's somewhere for me to file an issue, please lmk)

I think this can be closed, but I am going to revise the page so capitalization and grammar among the different sections is consistent.

**Comment by sfshaza2** [comment]
Sg!
