### ISSUE TITLE
'Building layouts' page issue

### ISSUE THREAD

**Issue by medhasutaria** [flutter/website#4274]
Page URL: https://flutter.dev/docs/development/ui/layout/tutorial.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/layout/tutorial.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
The line saying -
`Create an images directory at the top of the project.`

Should be -
`Create an assets/images directory at the top of the project.`

**Comment by JuYeong0413** [comment]
My app works fine following the tutorial, with creating an images directory at the top of the project.
I think this is not an error so it doesn't need to be fixed.

By the way, changing to `assets/images directory` would also affect these changes:
1. pubspec.yaml
```yaml
assets:
   - assets/images/lake.jpg
```
2. referencing the image in main.dart
```dart
Image.asset(
  'assets/images/lake.jpg',
  width: 600,
  height: 240,
  fit: BoxFit.cover,
),
```

**Comment by johnpryan** [comment]
@JuYeong0413 's answer is correct, assets don't *need* to be in a directory called `assets/`
