### ISSUE TITLE
'Write your first Flutter app on the web' page issue

### ISSUE THREAD

**Issue by mhmmtkls** [flutter/website#4275]
Page URL: https://flutter.dev/docs/get-started/codelab-web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab-web.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: at step 3 it says one-third and two-thirds but real values are 0.15625 and 0.5117177963256836

**Comment by johnpryan** [comment]
You're right, since it's using an `easeIn` curve, the actual value of the LinearProgressIndicator won't be exactly one-third of the way across.
