### ISSUE TITLE
'Sample App Catalog' page issue

### ISSUE THREAD

**Issue by Ycmelon** [flutter/website#4282]
Page URL: https://flutter.dev/docs/catalog/samples/
Page source: https://github.com/flutter/website/tree/master/src/docs/catalog/samples/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: The hyperlink is broken; I can't find the file "INDEX.md" in flutter/samples either?

**Comment by kwalrath** [comment]
Fixed by #4288. Thanks for making sure we knew about it!
