### ISSUE TITLE
'Sample App Catalog' page issue

### ISSUE THREAD

**Issue by pw2512** [flutter/website#4283]
Page URL: https://flutter.dev/docs/catalog/samples/
Page source: https://github.com/flutter/website/tree/master/src/docs/catalog/samples/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: Link directs to a 404 page

**Comment by kwalrath** [comment]
Looks like it should link to https://flutter.github.io/samples/#

**Comment by kwalrath** [comment]
Thanks for the bug report!
