### ISSUE TITLE
'Test drive' page issue

### ISSUE THREAD

**Issue by albertviilik** [flutter/website#4284]
Page URL: https://flutter.dev/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: I am unable to access the terminal-tab and the vscode-tab. For some reason when I click on them it updates the url of the page to the according "https://flutter.dev/docs/get-started/test-drive#vscode" or "https://flutter.dev/docs/get-started/test-drive#terminal" respectfully but the view does not change. I was able to reproduce the issue on Chrome, Firefox and Safari. User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

**Comment by kwalrath** [comment]
Should be fixed by #4287.

**Comment by kwalrath** [comment]
Fixed by #4287. Thanks for making sure we knew about it!
