### ISSUE TITLE
'Set up an editor' page issue

### ISSUE THREAD

**Issue by sestegra** [flutter/website#4285]
Page URL: https://flutter.dev/docs/get-started/editor.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/editor.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
When clicking on VS Code or Emacs, the respective tab pane isn't activated.

**Comment by kwalrath** [comment]
Should be fixed by #4287.

**Comment by sestegra** [comment]
Fixed
