### ISSUE TITLE
'Test drive' page issue

### ISSUE THREAD

**Issue by mhofner** [flutter/website#4286]
Page URL: https://flutter.dev/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: tabs for visual studio and terminal & editor are not working

**Comment by kwalrath** [comment]
I think this is the result of removing the banner.

**Comment by kwalrath** [comment]
Fixed by #4287. Thanks for making sure we knew about it!
