### ISSUE TITLE
'Test drive' page issue On setup your IDE it the tabs don't change data when you click on VsCode and Terminal&editor

### ISSUE THREAD

**Issue by kapilguptacr7** [flutter/website#4290]
Page URL: https://flutter.dev/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by kwalrath** [comment]
Fixed by #4287. Thanks for making sure we knew about it!
