### ISSUE TITLE
'Windows install' page issue: wrong requirement for disc space

### ISSUE THREAD

**Issue by Oscheibe** [flutter/website#4298]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:

As mentioned in #2995 and fixed in #3011 not only was the Mac install disk space requirement wrong, but the Windows version, too. 
The .zip file is 700 MB and the unzipped package is [1.32 GB](https://i.imgur.com/Pc1UQy7.png) (version 'flutter_windows_1.17.5-stable'). Therefore I would recommend to change the information to the following: 

`- **Disk Space**: 1.32 GB (does not include disk space for IDE/tools).`

**Comment by johnpryan** [comment]
Interestingly, when I download the 1.17.5 Windows SDK on my mac the ZIP is 624.2MB and the unzipped directory is 1.44 GB
