### ISSUE TITLE
'Samples' button redirects to 'Page not found'

### ISSUE THREAD

**Issue by leonardopaffi** [flutter/website#4307]
Steps to reproduce:
- https://flutter.dev/docs
- Click on 'Samples' button
- Redirects to [https://github.com/flutter/samples/blob/master/INDEX.md](https://github.com/flutter/samples/blob/master/INDEX.md)
- 404 Page not found

This is the button:
```
<a class="card" href="https://github.com/flutter/samples/blob/master/INDEX.md">
      <div class="card-body">
        <header class="card-title">Samples</header>
        <p class="card-text">Check out the Flutter examples.</p>
      </div>
</a>
```

**Comment by kwalrath** [comment]
To summarize the discussion (mostly just me talking to myself :) in #4308:

* Links to https://github.com/flutter/samples/blob/master/INDEX.md should change to be to https://flutter.github.io/samples.
* As a rule, we shouldn't link to the flutter/samples repo unless we're linking to individual samples.
* The following files have links to the samples:
  * Files that correctly link to flutter.github.io/samples:
    * src/docs/development/tools/sdk/release-notes/release-notes-1.7.8.md
    * src/docs/catalog/samples/index.md
    * src/docs/whats-new-archive.md
    * src/web.md
    * src/_data/sidenav.yml
  * Files that (incorrectly) link to https://github.com/flutter/samples/blob/master/INDEX.md:
    * [ ] src/404.html
    * [ ] src/docs/codelabs/layout-basics.md
    * [ ] src/docs/resources/technical-overview.md
    * [ ] src/docs/get-started/learn-more.md
    * [ ] src/_data/docs_cards.yml
