### ISSUE TITLE
Update flutter.dev for the new `flutter create -t plugin --platforms` command`

### ISSUE THREAD

**Issue by cyanglaz** [flutter/website#4319]
Update https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
so it is in sync with the new behavior of `flutter create -t plugin --platforms`.

**Comment by JuYeong0413** [comment]
Seems like this issue is fixed. #4344

**Comment by micpap25** [comment]
@sfshaza2 Since this is fixed I think it can be closed.
