### ISSUE TITLE
Publish "Flutter Release Note" on multiple platforms to contrast geoblocking

### ISSUE THREAD

**Issue by iassal** [flutter/website#4320]
Hello,

Medium.com is blocked in Egypt. Is it possible to make release notes available somewhere else as a fallback in the future? I am pretty sure a lot of developers in Egypt wouldn't be able to access the release notes for flutter.

Here is the link that I'm referencing https://medium.com/flutter/announcing-flutter-1-17-4182d8af7f8e

**Comment by micpap25** [comment]
Could probably put the content of the article on the top of the "release notes and changes" page in flutter.dev.

**Comment by atsansone** [comment]
This information is available at https://docs.flutter.dev/release/whats-new. Closing this issue as fixed.
