### ISSUE TITLE
'Integrate a Flutter module into your iOS project' page issue: Is aside about Release mode not working in Simulator now incorrect, since the Sim is now 64-bit?

### ISSUE THREAD

**Issue by jeremy-w** [flutter/website#4322]
Page URL: https://flutter.dev/docs/development/add-to-app/ios/project-setup#embed-the-flutter-module-in-your-existing-application
Page source: https://github.com/flutter/website/tree/master/src/docs/development/add-to-app/ios/project-setup.md

Description of issue:

There is an aside with this warning:

>  Note: Your app does not run on a simulator in Release mode because Flutter does not yet support output x86 ahead-of-time (AOT) binaries for your Dart code. You can run in Debug mode on a simulator or a real device, and Release on a real device.

Is this now factually incorrect for recent Xcode releases? macOS Catalina dropped 32-bit support, and all Simulator app binaries are x86_64. (And, well, probably arm64 on Apple Silicon under Big Sur.)

I'm not sure when the Simulator went 64-bit, but most iOS devs would only have access to a 64-bit Simulator at this point.

**Comment by sfshaza2** [comment]
@xster

**Comment by sfshaza2** [comment]
@tvolkert, xster seems to be out. Can you weigh in (or delegate)?

**Comment by tvolkert** [comment]
@gaaclarke

**Comment by xster** [comment]
Well we're probably splitting hairs here :)

"x86" would be the ISA family which is a generic term. "x86-86" would be one of the 30 or so extensions on the generic x86 ISA family along with "IA-32" which would denote "x86" in 32 bits. But we can retweak the wording to make it clearer.

**Comment by gaaclarke** [comment]
Yea, I suspect the same as xster.  I don't think the Dart team implemented AOT on x64 and not on i386.  I don't think there would be a good justification for such an investment.

However, it's a problem that will disappear once mac's transition to ARM.  You should be able to run release builds on the simulator then.
