### ISSUE TITLE
'Use a custom font' page issue

### ISSUE THREAD

**Issue by agubha** [flutter/website#4331]
Page URL: https://flutter.dev/docs/cookbook/design/fonts.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/fonts.md

Description of issue:
`flutter:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
`
Its ignore by flutter so declaring this way is not a valid option for those who want to use custom fontfamit with various  font propeties

**Comment by JuYeong0413** [comment]
Hi @agubha, can you provide more information about the issue?
When I followed the cookbook example, using Raleway & RobotoMono worked fine, it's not ignored by flutter.

This is my sample app output:
<img src="https://user-images.githubusercontent.com/33684401/87875682-ef83cf80-ca0d-11ea-8034-6762826e8521.png" width="40%">

**Comment by sfshaza2** [comment]
Thanks for your testing, @JuYeong0413!

**Comment by TheBiirb** [comment]
Can we close this since everything is working @sfshaza2 ?

**Comment by sfshaza2** [comment]
Great!
