### ISSUE TITLE
Embedded; 'Flutter documentation' page issue

### ISSUE THREAD

**Issue by taereesa** [flutter/website#4335]
Page URL: https://flutter.dev/docs/
Page source: https://github.com/flutter/website/tree/master/src/docs/index.md

Description of issue:

```
const { app, Menu } = require('electron')

const dockMenu = Menu.buildFromTemplate([
  {
    label: 'New Window',
    click () { console.log('New Window') }
  }, {
    label: 'New Window with Settings',
    submenu: [
      { label: 'Basic' },
      { label: 'Pro' }
    ]
  },
  { label: 'New Command...' }
])

app.dock.setMenu(dockMenu)
```

**Comment by sfshaza2** [comment]
@taereesa, can you explain the issue here? This code doesn't appear on the main docs page.  thx

**Comment by sfshaza2** [comment]
@taereesa, I'm going to close this issue, as there doesn't seem to be any action I need to take on the website. If you are describing a bug in Flutter itself, please file an issue on the flutter/flutter repo.
