### ISSUE TITLE
'Adding assets and images' page issue

### ISSUE THREAD

**Issue by khalidperwira** [flutter/website#4343]
Page URL: https://flutter.dev/docs/development/ui/assets-and-images.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/assets-and-images.md

Description of issue:
**I found image overflow in documentation adding assets and images page.**

![flutter image documentation overflow](https://user-images.githubusercontent.com/31671952/87448462-16b15a00-c626-11ea-8b85-8f13a129daea.png)

**Comment by sfshaza2** [comment]
Yup, this is easily fixed by restricting the image size to 100%. Thanks for pointing this out!
