### ISSUE TITLE
Design doc isn't shared

### ISSUE THREAD

**Issue by mono0926** [flutter/website#4360]
https://docs.google.com/document/d/1GppFbc3rk__XiogKEfk_taw-cucqu_VYpsRuJKeTABI was added at #4340, but it isn't publicly shared.

<img width="671" alt="image" src="https://user-images.githubusercontent.com/1255062/87747996-bd1c7b80-c82f-11ea-8518-1289aee8d487.png">

@godofredoc 

Could you change sharing setting of the document?

**Comment by godofredoc** [comment]
Thanks for letting me know I'll fix the link tomorrow morning.

**Comment by godofredoc** [comment]
PR to update the link is in review:

https://github.com/flutter/website/pull/4362

**Comment by sfshaza2** [comment]
Fixed! Thanks for reporting, @mono0926!
