### ISSUE TITLE
Update images of code snippets in Codelabs doc for first-flutter-app

### ISSUE THREAD

**Issue by Pragya007** [flutter/website#4361]
Image needs to be updated which are attached in [3.](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3) : Because [Here](https://github.com/flutter/codelabs/blob/b3293b5bb0c0187bdbe8112f7759f4d75f4c040a/startup_namer/step1_base/lib/main.dart) `const` is not there but image is displaying it. 

This will solve [this](https://github.com/flutter/flutter/issues/53375) issue.

**Comment by Pragya007** [comment]
If team approves this, I can work upon it.

**Comment by Pragya007** [comment]
[#60361](https://github.com/flutter/flutter/issues/60361) is also similar, image of code snippet needs to be change.

**Comment by domesticmouse** [comment]
Sorry, the codelabs are not open sourced at this point in time. Sorry!
