### ISSUE TITLE
[Write your first Flutter app codelab] Remove const isn't mentioned 

### ISSUE THREAD

**Issue by jshrek** [flutter/website#4369]
On the following page of tutorial, I found the following issues:
https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3

PROBLEM flutter/flutter#1
Following these steps, on this page, gives the following error:
Compiler message: 
```dart
lib/main.dart:17:23: Error: Not a constant expression. 
          child: Text(wordPair.asPascalCase),
```

The issue is that you need to change this line:
`body: const Center(`

To this line (remove const):
`body: Center( // remove const`

Please add this to turorial.

PROBLEM flutter/flutter#2
After correcting the above error, I then get this error:
Compiler message:
```bash
lib/main.dart:17:32: Error: The getter 'asPascalCase' isn't defined for the class 'String'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'asPascalCase'.
          child: Text(wordPair.asPascalCase),
                               ^^^^^^^^^^^^
```
Apparently it does not recognise asPascalCase by default. To fix it, I changed .asPascalCase to .asString. 

But need to add instructions to tutorial on how to make asPascalCase work.
Thanks

**Comment by tafa-mustafa** [comment]
remove const in the body it will work

**Comment by tafa-mustafa** [comment]
body: **const** Center(
          child: Text(wordPair.asPascalCase),
        ),

==> body: Center(
          child: Text(wordPair.asPascalCase),
        ),

**Comment by domesticmouse** [comment]
Looking at https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#3 the issue with the errant `const` seems to be resolved.
