### ISSUE TITLE
Change `AnimatedWidgetBaseState` to `ImplicitlyAnimatedWidget` on 'Animation and motion widgets' page

### ISSUE THREAD

**Issue by Sunbreak** [flutter/website#4372]
Page URL: https://flutter.dev/docs/development/ui/widgets/animation.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/widgets/animation.md

Description of issue:

**`AnimatedWidgetBaseState` is state, not widget**

**Comment by sfshaza2** [comment]
Hi, @Sunbreak! Can you clarify? The page doesn't say that `AnimatedWidgetBaseState` is a widget. It says that it's a base class for widgets.

**Comment by Sunbreak** [comment]
> Hi, @Sunbreak! Can you clarify? The page doesn't say that `AnimatedWidgetBaseState` is a widget. It says that it's a base class for widgets.

Every item listed in https://flutter.dev/docs/development/ui/widgets/animation is a widget, except to `AnimatedWidgetBaseState `

**Comment by sfshaza2** [comment]
Ahh, I see. Hmmm. Thanks for that report.

**Comment by micpap25** [comment]
I do find it a bit concerning that the API docs list it as a widget, then. 
Should `AnimatedWidgetBaseState` be removed from the page and the API docs be adjusted? If so, where should it be listed instead?
