### ISSUE TITLE
'Networking cookbook' page navigation issue

### ISSUE THREAD

**Issue by dev-aentgs** [flutter/website#4373]
Page URL: https://flutter.dev/docs/cookbook/networking/delete-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/delete-data.md

Description of issue: 
While using the top navigation links, [Delete data on the internet](https://flutter.dev/docs/cookbook/networking/delete-data.html) and [Update data over the internet](https://flutter.dev/docs/cookbook/networking/update-data.html) pages get excluded. 

If we click on [Delete data on the internet](https://flutter.dev/docs/cookbook/networking/delete-data.html) from [Networking cookbook](https://flutter.dev/docs/cookbook#networking) and select [Make authenticated requests](https://flutter.dev/docs/cookbook/networking/authenticated-requests) from top right
![image](https://user-images.githubusercontent.com/65178249/88015517-feb66a80-cb3e-11ea-9389-eee9d887fae8.png)

The [Make authenticated requests](https://flutter.dev/docs/cookbook/networking/authenticated-requests) page does not link back to [Delete data on the internet](https://flutter.dev/docs/cookbook/networking/delete-data.html) page
![image](https://user-images.githubusercontent.com/65178249/88015734-88fece80-cb3f-11ea-9621-d3aef6ad70cf.png)

**Comment by JuYeong0413** [comment]
I think the top navigation links(previous/next pages) should follow the [cookbook contents list](https://flutter.dev/docs/cookbook#networking):
<img width="40%" src="https://user-images.githubusercontent.com/33684401/88062875-55a25b00-cba4-11ea-9426-8c6dc8d7a90a.png">

Not only the [Delete data on the internet](https://flutter.dev/docs/cookbook/networking/delete-data) but also the top navigation links in other networking recipe pages are mixed up.

**Comment by dev-aentgs** [comment]
@JuYeong0413 yes

**Comment by sfshaza2** [comment]
Oops! That can happen when we manually maintain these links.

**Comment by dev-aentgs** [comment]
Also, I think the order should be different then the one mentioned here. It should be according to their inter-dependencies.
 

> I think the top navigation links(previous/next pages) should follow the [cookbook contents list](https://flutter.dev/docs/cookbook#networking):
> <img alt="" width="40%" src="https://user-images.githubusercontent.com/33684401/88062875-55a25b00-cba4-11ea-9426-8c6dc8d7a90a.png">
> 
> Not only the [Delete data on the internet](https://flutter.dev/docs/cookbook/networking/delete-data) but also the top navigation links in other networking recipe pages are mixed up.

**Comment by JuYeong0413** [comment]
I agree that reordering the pages would be better as @dev-aentgs mentioned.

However, it seems that all the cookbook TOC are listed in alphabetical order and the top navigation links of individual pages correspond to it.
So @sfshaza2, should networking section be reordered unlike other pages? or will it be okay to leave it in alphabetical order and just fix the top navigation links?
