### ISSUE TITLE
Windows system requirements need to mention x86-64

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/website#4381]
Per flutter/flutter#53120, Flutter currently doesn't work on ARM-based Windows 10 machines (e.g., the Yoga C630). Currently our system requirements for Windows just say "Windows 7 SP1 or later (64-bit)"; these machine meet those requirements, but won't actually allow Flutter development.

**Comment by kf6gpe** [comment]
Per @stuartmorgan's comment, moving to the website repo.
