### ISSUE TITLE
'Linux install' Snap does not install Dart CLI

### ISSUE THREAD

**Issue by MateusAmin** [flutter/website#4382]
Page URL: https://flutter.dev/docs/get-started/install/linux.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/linux.md

Description of issue:

Installation of Flutter >1.20 using Snap does not install Dart CLI

**Comment by sfshaza2** [comment]
@csells

**Comment by johnpryan** [comment]
@domesticmouse

**Comment by csells** [comment]
@kenvandine fyi

**Comment by aadarshadhakalg** [comment]
@MateusAmin You should add dark tools to path explicitly to use them. Which is generally located at 

```
$HOME/snap/flutter/common/flutter/bin/cache/dart-sdk/bin
```

Adding this line at the end of .bashrc file should work.

```
export PATH="$PATH:$HOME/snap/flutter/common/flutter/bin/cache/dart-sdk/bin"
```

**Comment by MateusAmin** [comment]
Thanks @aadarshadhakalg !
