### ISSUE TITLE
'Books about Flutter' page issue

### ISSUE THREAD

**Issue by ashfaq92** [flutter/website#4391]
Page URL: https://flutter.dev/docs/resources/books.html
Page source: https://github.com/flutter/website/tree/master/src/docs/resources/books.md

Description of issue:
Books should not be in alphabetic order. Instead, books should be according to the learning curve so that developer may pick an appropriate book for him. For example, you can categorize books in beginner, medium and advance categories. Please check this [link](https://stackoverflow.com/questions/388242/the-definitive-c-book-guide-and-list) where C++ books are categorized in a fantastic way. Same idea would be appreciated

**Comment by sfshaza2** [comment]
@ashfaq92, thanks for your suggestion. It does make sense. However, this is a list of *available books* on Flutter, it's not a curated list. I have *none* of these books, so I can't evaluate them on those merits. We are happy to list available books as a service to our community, but that's about all we can do.
