### ISSUE TITLE
Update flutter.dev/docs/null-safety

### ISSUE THREAD

**Issue by kevmoo** [flutter/website#4396]
Related to https://dart.dev/null-safety

We need a page to link to from https://dart.dev/null-safety

In the short term:
- which channels support null safety
- how to enable it for a project
- how to give feedback
- migration tooling, etc

**Comment by jonahwilliams** [comment]
My best guesses:

> which channels support null safety

I think there won't be any channel restriction, but I haven't heard about this one yet.

> how to enable it for a project

--enable-experiment=non-nullable passed to the command line, analysis_options.yaml edit for analyzer

> how to give feedback

Bugs are good

> migration tooling, etc

IIRC the dartdev tool is disabled for release right now, so whenever that is turned back on it will be available.

**Comment by sfshaza2** [comment]
Great idea!

**Comment by kwalrath** [comment]
I'll create a placeholder, and unassign myself once that's up.

**Comment by kevmoo** [comment]
Fodder for content here: https://github.com/flutter/flutter/wiki/Experimenting-with-null-safety-in-Flutter

**Comment by kwalrath** [comment]
https://flutter.dev/docs/null-safety links to that page as of #4908.

**Comment by kevmoo** [comment]
> https://flutter.dev/docs/null-safety links to that page as of #4908.

Yup – but thinking that `/docs/null-safety` would be a better longer-term home for such content.

**Comment by kevmoo** [comment]
Are we "done" here @kwalrath ?

**Comment by kwalrath** [comment]
Yes, I think we're "done" (although there's always room for improvement!)
