### ISSUE TITLE
'Slivers' page issue

### ISSUE THREAD

**Issue by vivekumar190** [flutter/website#4413]
Page URL: https://flutter.dev/docs/development/ui/advanced/slivers.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/advanced/slivers.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by sfshaza2** [comment]
Nothing described. Closing..
