### ISSUE TITLE
widget_test error, can someone help me. i follow step by step and did not touch code for widget_test.

### ISSUE THREAD

**Issue by SyedLuqmanHakim** [flutter/website#4423]

**Comment by SyedLuqmanHakim** [comment]
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:cupertinostore/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(CupertinoStoreApp());

    // Verify that our counter starts at 0.
    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);

    // Tap the '+' icon and trigger a frame.
    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();

    // Verify that our counter has incremented.
    expect(find.text('0'), findsNothing);
    expect(find.text('1'), findsOneWidget);
  });
}

**Comment by sfshaza2** [comment]
Hi, @SyedLuqmanHakim. What is the context for this error? What instructions were you following? What page were you on? Thx

**Comment by sfshaza2** [comment]
@SyedLuqmanHakim, I'm closing this. If you can point to a page on flutter.dev that is misleading or incorrect, please re-open. A better place to find support is one of the channels listed on our [community page](https://flutter.dev/community).
