### ISSUE TITLE
Consider copying SkSL warm-up wiki to flutter.dev website

### ISSUE THREAD

**Issue by liyuqian** [flutter/website#4428]
The wiki is in https://github.com/flutter/flutter/wiki/Reduce-shader-compilation-jank-using-SkSL-warm-up.

The wiki is up to date as of today. Having it on flutter.dev website gives a better presentation at a maintenance cost: we need to make sure that any update to it need to be reflected both on Github wiki and on flutter.dev.

**Comment by sfshaza2** [comment]
This is addressed in PR https://github.com/flutter/website/pull/4431.

**Comment by tvolkert** [comment]
It looks like https://github.com/flutter/website/pull/4431 is unrelated?

**Comment by sfshaza2** [comment]
Oops, you're right. It was a different PR.

**Comment by liyuqian** [comment]
Fixed by https://github.com/flutter/website/pull/4430
