### ISSUE TITLE
'Free Flutter course from the App Brewery' page issue

### ISSUE THREAD

**Issue by TharVid** [flutter/website#4429]
Page URL: https://flutter.dev/freecourse.html
Page source: https://github.com/flutter/website/tree/master/src/freecourse.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
This course is no longer available for free. Please remove this page.

**Comment by sfshaza2** [comment]
Thanks so much for PR https://github.com/flutter/website/pull/4433, @TharVid! To avoid a broken link, that PR should be sufficient for now.
