### ISSUE TITLE
Using same widgets for TabBarView and TabBar in 'Work with tabs' page is confusing

### ISSUE THREAD

**Issue by bryanoltman** [flutter/website#4437]
Page URL: https://flutter.dev/docs/cookbook/design/tabs.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/tabs.md

Description of issue:

In the [Interactive Example](https://flutter.dev/docs/cookbook/design/tabs#interactive-example), the TabBarView and the TabBar use the exact same Icon widgets for their content, making it more difficult for newcomers to discern which Widget is which.

**Comment by atsansone** [comment]
This is the point of the example. If the icon in the TabBar matches the one in the TabBarView, you know you clicked the right tab. Closing this issue.
