### ISSUE TITLE
Rearrange Video Links on Main Documentation Page

### ISSUE THREAD

**Issue by micpap25** [flutter/website#4438]
Page URL: https://flutter.dev/docs
Page Source: https://github.com/flutter/website/blob/master/src/docs/index.md

Issue: In the "Videos" section of the docs main page, we see this line:
`We also have some helpful videos on our Flutter YouTube channel! In particular, check out the Flutter in Focus series, and learn about other series on our videos page.`
However, `Flutter in Focus` is not a link.

Later on, in the middle of a series of videos, we see this:
`Flutter in Focus: Learn Flutter features in 10 minutes or less.
Flutter in Focus playlist`
Flutter in Focus playlist is a link, but it interrupts the flow of the videos and looks inconsistent.

I believe the latter section should be removed, and the link should be integrated into the former section.

**Comment by sfshaza2** [comment]
That sounds reasonable.  To be honest, I think the text mentions Flutter in Focus too much.

**Comment by believeInJha** [comment]
Hey @micpap25 Thank you for giving a great insight into the issue. Can I make a pull request for this issue, this will be my first contribution to the flutter website repository!

**Comment by believeInJha** [comment]
hey @sfshaza2 I have made the changes, kindly take a look into it.

**Comment by believeInJha** [comment]
Thanking @micpap25  and @sfshaza2 for giving such a great insight into the issue.
