### ISSUE TITLE
Preselect OS that we're running on for install page

### ISSUE THREAD

**Issue by timsneath** [flutter/website#4446]
Page URL: https://flutter.dev/docs/get-started/install/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/index.md

Description of issue:
Right now, if you click on "Get Started" from the title bar, you get to this page:
https://flutter.dev/docs/get-started/install

I like the visual strength, but this adds another click to the process compared to the old experience. Studies show that every click has a significant impact in funnel completion. We should be able to detect the OS of the user agent and start there, even if we also offer the other options as an easy click. 

See for example how streamlined [VSCode](https://code.visualstudio.com/) have made their experience:
![image](https://user-images.githubusercontent.com/2319867/89435343-97311b00-d6f9-11ea-9a8e-7af6c5fc7ff3.png)
(and obviously, you see a different button if you visit that page from Windows or Linux).

**Comment by sfshaza2** [comment]
This flow hasn't changed recently, so I am a bit confused by your comment, "this adds another click to the process compared to the old experience".  This change would require some infrastructure expertise.

**Comment by timsneath** [comment]
Oh, you're right! It's not one more click after all. The page has [changed in the last couple of months](https://web.archive.org/web/20200616041720/https://flutter.dev/docs/get-started/install), but only for the better. 

Nevertheless, I still think the main point remains -- we can remove an unnecessary click by getting the user straight to install instructions for their current machine, and give them the opportunity to pick a different platform if they need to.

**Comment by sfshaza2** [comment]
Oh, I don't disagree with that.  :). I was just confused by the assertion that it had changed. Yes, the last change was from Patrice (our former infrastructure guy) who improved the Linux option.

I'm definitely leaving this open, but we don't have infrastructure support at the moment.

**Comment by atsansone** [comment]
@parlough : FYI per prior discussions.

\cc: @InMatrix
