### ISSUE TITLE
SSL Certificate not working

### ISSUE THREAD

**Issue by crydotsnake** [flutter/website#4461]
Hello, 

i just would like to let you know that the SSL Certificate for https://flutter.dev isnt working.

![Bildschirmfoto 2020-08-08 um 18 29 45](https://user-images.githubusercontent.com/39345336/89715324-32015200-d9a5-11ea-8a9d-7ee849b96833.png)

**Comment by sfshaza2** [comment]
@johnpryan, @domesticmouse, can one of you take a look?

**Comment by domesticmouse** [comment]
Flutter.dev's SSL certificate looks sane to me:

<img width="470" alt="Screen Shot 2020-08-11 at 6 36 19 am" src="https://user-images.githubusercontent.com/30503/89828890-0cd73400-db9d-11ea-8e63-c5ce235046dc.png">

I'm curious if @crydotsnake can supply more information on why this certificate is failing. I don't speak german, but I assume one of those two buttons is the moral equivalent of "More information"...

**Comment by crydotsnake** [comment]
Good Evening!.

Sorry, for the bad issue description.

I have the issue on Firefox, Brave, and Safari.

If i klick on More Information it says follwoing:

flutter.dev usually protects your data by encryption. When Brave tried to connect to flutter.dev this time, the site returned unusual and incorrect login information. Either an attacker attempted to impersonate flutter.dev, or the connection was interrupted by a wireless login page. Because Brave broke the connection before exchanging data, your information is still secure.

You cannot currently view flutter.dev because the Web site is using HSTS. Network errors and attacks are usually temporary, so the site will probably work again later.


I didnt change the SSL/HTTPS Settings in my Browser Settings or anything like that.

**Comment by crydotsnake** [comment]
I try it with a fresh installation of the Google Chrome Browser (To make sure it is not an issue with the browser settings, because i didnt touch them). Also didnt work.

**Comment by crydotsnake** [comment]
Interesting... it uses not the ssl certificate from flutter.dev, instead it uses a ssl certificate from my local project.

**Comment by crydotsnake** [comment]
![Bildschirmfoto 2020-08-10 um 23 03 09](https://user-images.githubusercontent.com/39345336/89831181-ada5ff00-db5d-11ea-8893-d06947d1ff08.png)

Translated Version:
Websites confirm their identity by means of certificates. Firefox does not trust this website because the certificate used by the website does not apply to flutter.dev. The certificate is only valid for the following names: craftapp.dev, *.craftapp.dev

**Comment by crydotsnake** [comment]
Okay, it works now.

Issue was, i use Laravel Valet for my local projects, and i use .dev for my local projects domain. So this was the conflict... i think Valet thought, flutter.dev would be a local project of me. So i changed it to use .test instead .dev and now, it is working ! :)).

**Comment by crydotsnake** [comment]
Thanks anyway!! :).

**Comment by domesticmouse** [comment]
Quick suggestion, use .local for your local domains. 😇

**Comment by crydotsnake** [comment]
Good Idea ! 🙈
