### ISSUE TITLE
'Codelabs' page issue

### ISSUE THREAD

**Issue by etoherrera** [flutter/website#4467]
Page URL: https://flutter.dev/docs/codelabs/
Page source: https://github.com/flutter/website/tree/master/src/docs/codelabs/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
This links is broken:
https://codelabs.developers.google.com/com/codelabs/web-url-launcher

**Comment by sfshaza2** [comment]
Fixed
