### ISSUE TITLE
"Pass Argument to a Named Route" is confusing

### ISSUE THREAD

**Issue by mcavazotti** [flutter/website#4471]
[This](https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments) cookbook is a bit confusing and seems overcomplicated. I suggest a simpler option (in my opinion, better suited for a beginner):

**1. Create the Widget that accepts arguments as a Map**

```dart
class MyWidget extends StatelessWidget {

  static final String routeName = '/myWidget';

  final String title;
  final String description;
  final DateTime endDate;
  final DateTime startDate;

  MyWidget(Map<String, dynamic> args)
      : title = args['title'],
        description = args['description'],
        endDate = args['endDate'],
        startDate = args['startDate'];

  @override
  Widget build(BuildContext context) {
  // some stuff
  }
}
```
**2. Define the Routes**

```dart
Map<String,WidgetBuilder> routes = <String,WidgetBuilder> {
  MyWidget.routeName : (BuildContext context) => MyWidget(ModalRoute.of(context).settings.arguments),
  // other routes
}
```

**3. Navigate to the widget**

```dart
Navigator.of(context).pushNamed(MyWidget.routeName, arguments: <String,dynamic>{
    'title': 'Flutter is Awesome',
    'description': 'Just a description',
    'startDate': DateTime(2020,08,01),
    'endDate': DateTime(2020,08,15)
});
```

**Comment by sfshaza2** [comment]
@johnpryan, can you weigh in? Or, since [Navigation 2.0](https://flutter.dev/docs/release/breaking-changes/route-navigator-refactoring) is coming, should we just wait?

**Comment by Roshan13046** [comment]
Is this issue active. Can I work on it?

**Comment by sfshaza2** [comment]
@johnpryan, can you weigh in here?  (@Roshan13046, John is on vacation until the new year.)

**Comment by johnpryan** [comment]
@mcavazotti can you clarify why a `Map` is more beginner friendly than the `ScreenArguments` class currently used in the article?

**Comment by mcavazotti** [comment]
@johnpryan I had the opportunity to teach Flutter to some people in the company where I used to work. People who are new to Flutter usually have a hard time trying to grasp this whole "widget" concept, although it's pretty simple once you get it.

When I was a beginner in Flutter, I also found it hard to understand **why** I had to use an intermediate class to pass arguments to a route. Using a `Map` instead of `ScreenArguments` seems simpler and more direct.

**Comment by johnpryan** [comment]
What do you think about adding comment that says that since the type is `dynamic`, it can be any object, like a Map?

**Comment by sfshaza2** [comment]
@domesticmouse, John is out for the next couple of days. What do you think about this issue? Can we close it?

**Comment by domesticmouse** [comment]
I understand why an untyped Map may appear simpler to JS developers who are used to untyped arguments being passed around, but Dart is a strongly typed language and Flutter uses types to have more informative and helpful editor interactions, that hopefully help users in the medium term.

Undertstanding that typed object arguments is a useful part of an API is part of the path to becoming proficient in Flutter.
