### ISSUE TITLE
'List of state management approaches' Add new one please

### ISSUE THREAD

**Issue by stefandevo** [flutter/website#4478]
Page URL: https://flutter.dev/docs/development/data-and-backend/state-mgmt/options.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/state-mgmt/options.md

Could you please add GetX?
With more than 900 likes on https://pub.dev/packages/get I think it is worth adding.

Some links you can include:
https://github.com/jonataslaw/getx
https://github.com/jonataslaw/get/blob/master/docs/en_US/state_management.md
https://www.youtube.com/watch?v=CNpXbeI_slw

**Comment by sfshaza2** [comment]
@filiph, what about adding GetX to our state management docs?

**Comment by filiph** [comment]
Sure! @stefandevo, do you want to make a pull request for it? This is a simple change, so all that's needed is opening https://github.com/flutter/website/blob/master/src/docs/development/data-and-backend/state-mgmt/options.md and clicking Edit to propose the change.

**Comment by filiph** [comment]
Thanks @stefandevo!
