### ISSUE TITLE
'What's new archive' page issue

### ISSUE THREAD

**Issue by nicekiwi** [flutter/website#4493]
Page URL: https://flutter.dev/docs/whats-new-archive.html
Page source: https://github.com/flutter/website/tree/master/src/docs/whats-new-archive.md

Description of issue:
the link to the "Flutter and Desktop apps" article links to the article above it, not an article about flutter and desktop apps.

**Comment by sfshaza2** [comment]
Oops! Thx! Will fix. Do you find the "What's new" info useful? (I sometimes have my doubts.)

**Comment by nicekiwi** [comment]
@sfshaza2 I'm pretty new to flutter and I find it useful and encouraging to see news about it too. 😃

**Comment by nicekiwi** [comment]
@sfshaza2 the link to "Flutter Performance Updates in 2019" is also wrong <3

**Comment by sfshaza2** [comment]
D'OH
