### ISSUE TITLE
DevTools memory usage needs better explanation

### ISSUE THREAD

**Issue by AAverin** [flutter/website#4501]
https://docs.flutter.dev/tools/devtools/memory

My first question is if this page was updated to the latest DevTools release already
https://github.com/flutter/website/blob/master/src/docs/development/tools/devtools/memory.md

I couldn't find any explanation about how snapshots work, what is the difference between different "Group By" settings.
It is also unclear which objects is my class still referencing and how to debug leaks using this memory view.
For example, even though my Widget class seems to be still in memory (at least when I group by class), it is not shown if my widget still holding references to other widgets it have built.

I have also posted a question on SO more related to my specific memory problem (https://stackoverflow.com/questions/63433828/understanding-flutter-memory-view), but it also indicated that memory view needs some better explanation, maybe even worth making a detailed video showing how to use it and how to debug memory leaks.

**Comment by atsansone** [comment]
@polina-c : Can you sanity check that our current page meets this request?

**Comment by polina-c** [comment]
Yes, the page is up-to-date now. Closing.
