### ISSUE TITLE
Typo in codelab "Firebase for Flutter", step #5

### ISSUE THREAD

**Issue by westwoodra2** [flutter/website#4504]
In a codelab "Firebase for Flutter", in a step 5 "Add user interface" there is a tiny error in a code snippet that contains description of UI for the app.

![image](https://user-images.githubusercontent.com/2959922/90564820-3cda9480-e1a6-11ea-9187-29f546a25741.png)

It should be a method call "snapshot.data()". The error is trivial, but still prevents the build and might confuse newcomers to Dart and Flutter.

Page URL: https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html?index=..%2F..index#4
Page source: Unfortunately I couldn't locate it

**Comment by domesticmouse** [comment]
The `flutter-firebase` codelab has been replaced by the [Get to know Firebase for Flutter](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#0) codelab. Thanks for the report!
