### ISSUE TITLE
'Persist data with SQLite' page issue

### ISSUE THREAD

**Issue by sbaglivi** [flutter/website#4505]
Page URL: https://flutter.dev/docs/cookbook/persistence/sqlite.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/persistence/sqlite.md

Description of issue: 
In step 3 we create a database reference through `final Future<Database> database`, in the full code example this gets changed to `final database`. I had wrote the code step by step and it would not print out the correct output until I made that change.

**Comment by aromalanil** [comment]
I have created a pull request ( #4536 )  to fix this issue.
