### ISSUE TITLE
'Building a web application with Flutter' page issue

### ISSUE THREAD

**Issue by satriahrh** [flutter/website#4520]
Page URL: https://flutter.dev/docs/get-started/web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/web.md

Description of issue: 

Hi, I am new to flutter. So I try to build a mini project.  It was great when I can test on iOS simulator, very neat.

Then I was curious that I can run on flutter app from web browser, and got to this page.

Asking user to `flutter channel beta` without caution is a big mistake, especially for some of us that have problem with Internet connection issue. I was stumbled upon this kind of condition when knowing this answer on [so](https://stackoverflow.com/questions/61556268/flutter-how-to-switch-flutter-channel-without-downloading-flutter-dart-sdk-e), `flutter channel <something>` will remove previous selected channel and force download selected channel, every time.

Hoping that we can do something to notice the user of the side effect on switching flutter channel.

**Comment by aromalanil** [comment]
I also think that flutter team should add a way to cache the SDK from the previous channel during a  channel switching. This will save the user time and internet data.

**Comment by sfshaza2** [comment]
I think you have a very good point. Please file a request on the flutter/flutter repo, as SWEs don't generally read this one. (But first search the issues - it wouldn't surprise me if someone has already requested this. Then you can upvote and add your voice.)

**Comment by aromalanil** [comment]
@sfshaza2 Sure, I'll do that. As of now I have added a pull request which adds a warning about switching the channel. I request you to take a look into it #4547

**Comment by aromalanil** [comment]
@sfshaza2 I have created an [issue](https://github.com/flutter/flutter/issues/64822) in `flutter/flutter` as I couldn't find any similar issues.

**Comment by aromalanil** [comment]
@sfshaza2 This issue is solved, so I think this can be closed.

**Comment by parlough** [comment]
The SDK issue is being tracked there and there is now a warning on the site as of https://github.com/flutter/website/pull/4547. Thanks everyone :)
