### ISSUE TITLE
'Tabbed AppBar' page issue

### ISSUE THREAD

**Issue by vmudigal** [flutter/website#4525]
Page URL: https://flutter.dev/docs/catalog/samples/tabbed-app-bar.html
Page source: https://github.com/flutter/website/tree/master/src/docs/catalog/samples/tabbed-app-bar.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: Android screenshot does not load.

**Comment by mohak852** [comment]
Can you describe the issue more precisely

**Comment by vmudigal** [comment]
Obselete, the issue no longer holds true.
