### ISSUE TITLE
'Adding assets and images' page issue

### ISSUE THREAD

**Issue by hlemcke** [flutter/website#4528]
Page URL: https://flutter.dev/docs/development/ui/assets-and-images.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/assets-and-images.md

Description of issue:

The description is inconsistent. **Either**
"Note: Only files located directly in the directory are included. To add files located in subdirectories, create an entry per directory."
is true **or**
"Then both graphics/background.png and graphics/dark/background.png are included in your asset bundle."
is true
**OR** there is some quite different handling in the background?!?
Sorry, I cannot fix it by myself since this handling is still not completely clear for me.

Regards
Hajo

**Comment by sfshaza2** [comment]
@johnpryan, can you weigh in?

**Comment by TheBiirb** [comment]
It is mentioned 

> When an asset’s path is specified in the assets section of pubspec.yaml, the build process looks for any **files with the same name** in adjacent subdirectories. Such files are then included in the asset bundle along with the specified asset.

I am not sure what the issue here is?

**Comment by aromalanil** [comment]
I looked into this issue, and as @TheBiirb mentioned, it is clearly mentioned in the page why this happens.  I also don't see any issue in the docs.

**Comment by hlemcke** [comment]
You are absolutely correct. Nevertheless the note says: "Only files located directly in the directory are included". From my point of view I recommend to rephrase the note to something like: "Files with the same name are included from subdirectories. Files with other names must be included explicitly"

**Comment by johnpryan** [comment]
You could also rephrase the note to be: "Only files located directly in the directory are included _unless there are files with the same name in subdirectories (see the Asset Variants section below)._ To add files located in subdirectories, create an entry per directory."

**Comment by aromalanil** [comment]
I have made a PR fixing this issue.
