### ISSUE TITLE
update codelab 

### ISSUE THREAD

**Issue by Aman9026** [flutter/website#4530]
There are several issues like #62282 in the flutter repo related to https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#5 

I've cross checked all the contents in the repo containing that page, all the issues are already corrected.
Please trigger an update for that codelab page.

**Comment by sfshaza2** [comment]
Hi @Aman9026, I have tried (just now, multiple times) to retrigger publication, but it's not (apparently) working. I've sent email to the codelabs staff.

Meanwhile, please move all codelabs-related issues to this repo. I'll go ahead and move that one.  Thx

**Comment by domesticmouse** [comment]
Closing this issue out as the fix should be live soon.
