### ISSUE TITLE
Is "Building beautiful UIs with Flutter" open sourced?

### ISSUE THREAD

**Issue by Aman9026** [flutter/website#4531]
There are several issues related to https://codelabs.developers.google.com/codelabs/flutter/#4 which I want to fix. 
I am unable to find the repo containing it. Is that page not open sourced?

**Comment by JuYeong0413** [comment]
Yup. The source for the codelabs on codelabs.google.developer.com are not accessible to external people.

**Comment by sfshaza2** [comment]
Yeah, sorry about that, @Aman9026. The codelabs are pretty much the only Flutter docs that non-Googlers can't access.
