### ISSUE TITLE
link anchors to pub.dev broken 

### ISSUE THREAD

**Issue by zvikarp** [flutter/website#4538]
Hi,

When pub.dev did the (awsome) makeover for their website, it seems like they have removed the tab anchors with sub-routes, so `https://pub.dev/packages/http#-installing-tab-` is now `https://pub.dev/packages/http/install`.

This leaves Flutters website with a few misleading links. For example, read the first paragraph at https://flutter.dev/docs/development/packages-and-plugins/using-packages#package-versions, the last link ([url_launcher versions](https://pub.dev/packages/url_launcher#-versions-tab-)) goes to the package homepage instead of the versions.

I searched the issues and PR's but didn't find one that addresses this issue, would it be possible to contribute and fix all the broken links?

**Comment by sfshaza2** [comment]
@zvikarp, good catch! I had missed this when they updated the site.

**Comment by sfshaza2** [comment]
I did not know about this change or I would have fixed it.  :) Thanks for the PR!

**Comment by zvikarp** [comment]
@sfshaza2 sure! This is my first contribution to an open source, and although it is just fixing some links - I'm happy I was able to help ✌️
