### ISSUE TITLE
typos in the tutorial

### ISSUE THREAD

**Issue by Omer1Yuval1** [flutter/website#4542]
In steps 4 and 5 of the tutortial (https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1/#5), the same name is sometimes referred to as _RandomWordState and sometimes as _RandomWordsState

**Comment by micpap25** [comment]
The issue is still there for me, once on 5) and once on 6).
I think it would be helpful to mark this with `codelab-external` as well.

**Comment by saumya66** [comment]
Can someone tell me where is this page in the repo - [](https://codelabs.developers.google.com/codelabs/write-flutter-plugin/#3)

**Comment by micpap25** [comment]
I don't believe codelabs aren't directly in the repo, that's why they're generally marked "external". 
It's infuriating because this is a really easy fix, lol. 
There's https://github.com/flutter/codelabs but it doesn't seem to be open-source.

**Comment by saumya66** [comment]
Ya right

**Comment by domesticmouse** [comment]
I've changed `_RandomWordState` to `_RandomWordsState` in the source doc. Once @sfshaza2 lgtm's the change, it'll be up on the site.
