### ISSUE TITLE
Recommendation for adding Redux Saga Middleware for Dart and Flutter to recommendation list of approaches

### ISSUE THREAD

**Issue by bilal-uslu** [flutter/website#4543]
Page URL: https://flutter.dev/docs/development/data-and-backend/state-mgmt/options.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/state-mgmt/options.md

Description of issue: 

I would like to make a Redux Saga Middleware recommendation to add this page. It is popular at javascript world, now it is dart and flutter compatible and ready to use. It makes easy to handle concurrency and state management. 
Documentation, examples and unit tests are completed. Please check it on pub.dev and github. Thanks,

https://pub.dev/packages/redux_saga
https://github.com/reduxsaga/redux_saga

Redux Saga Middleware Dart and Flutter

Redux Saga Middleware for Dart and Flutter is a library that aims to make application side effects (i.e. asynchronous things like data fetching and impure things like accessing the browser cache) easier to manage, more efficient to execute, easy to test, and better at handling failures.

**Comment by sfshaza2** [comment]
Hi, @bilal-uslu! This sounds fine and PRs are welcome. Just make sure that the new text doesn't sound too "advertise-y".  @filiph

**Comment by aromalanil** [comment]
I would like to work on this.

**Comment by bilal-uslu** [comment]
Hi @sfshaza2, 

Thanks,

Hi @aromalanil, 

Thank you for work,

Can you please add "by Bilal Uslu" at the end like the following

* [Redux Saga Middleware Dart and Flutter][], by Bilal Uslu

Thanks,

**Comment by aromalanil** [comment]
@bilal-uslu Sorry for that. I'll add it right away

**Comment by bilal-uslu** [comment]
Is there anything I should do about pr or else...?

**Comment by bilal-uslu** [comment]
Thanks everybody
