### ISSUE TITLE
Command update required in codelabs write-flutter-plugin tutorial

### ISSUE THREAD

**Issue by shreyaskapale** [flutter/website#4544]
_Current_
`flutter create --template=plugin --ios-language=objc --android-language=java PluginCodelab`

**Platform flag missing**
without the platform flag it won't generate the folder structure for android / ios.

_Should be converted into_

`flutter create --org com.example --template=plugin --platforms=android,ios -a java PluginCodelab`

**Comment by JuYeong0413** [comment]
Seems like this issue is about codelabs: https://codelabs.developers.google.com/codelabs/write-flutter-plugin/#2

**Comment by shreyaskapale** [comment]
> Seems like this issue is about codelabs: https://codelabs.developers.google.com/codelabs/write-flutter-plugin
yes

**Comment by 9JIMIN** [comment]
Package name should be all lowercase, with underscores to separate words.[https://dart.dev/tools/pub/pubspec#name](https://dart.dev/tools/pub/pubspec#name)
`plugin_codelab`, not `PluginCodelab`.

so, command should be.. 
`flutter create --org com.example --template=plugin --platforms=android,ios -a java plugin_codelab`

**Comment by shreyaskapale** [comment]
https://codelabs.developers.google.com/codelabs/write-flutter-plugin#2 has been patched.
