### ISSUE TITLE
"español" link in footer doesn't work.

### ISSUE THREAD

**Issue by micpap25** [flutter/website#4549]
Issue: The "español" link in the footer of the website does not go to a Spanish flutter website, but instead a domain purchasing site. 

Should this link be removed? Or should some other action be taken?

**Comment by aromalanil** [comment]
I can work on this, should I remove the link?
Here is the line with the issue [footer](https://github.com/flutter/website/blob/bcd1a9bcf8f27f5e03408d0bea75e4947a911d84/src/_includes/footer.html#L15)

**Comment by aromalanil** [comment]
@sfshaza2 I think this is an issue to be solved quickly, please take a look.

**Comment by sfshaza2** [comment]
Yup, it looks like they let the domain go. Too bad.

**Comment by aromalanil** [comment]
I'm working on it.

**Comment by Arkangel12** [comment]
link for Flutter documentation in Spanish was change and now is up and running `https://esflutter.dev/` if you could put this back Flutter Spanish Community will appreciate it. 

Thanks!

**Comment by aromalanil** [comment]
@sfshaza2 I can add the link back, but is there any procedures before that? Should a new issue be added (Since this issue is closed).

I am new to opensource, so I am not clear about this.

**Comment by sfshaza2** [comment]
Yay! Either way is fine, @aromalanil, but the full process would be to create a new issue.  :)

**Comment by Arkangel12** [comment]
> @sfshaza2 I can add the link back, but is there any procedures before that? Should a new issue be added (Since this issue is closed).
> 
> I am new to opensource, so I am not clear about this.

you are right it was already closed, i create a new one

**Comment by sfshaza2** [comment]
@micpap25, can you contact me directly? My ldap is s-h-a-z-a and you can guess the @company.  :D

**Comment by micpap25** [comment]
Hi @sfshaza2 , 
While I would be very excited to speak with you directly, I have never used LDAP before. 
I've been working for the last hour or so on figuring out how to connect to this LDAP server, but I'm a bit stuck. Both Apache Directory Studio and Softerra LDAP Browser require a hostname, and any variation of `s-h-a-z-a`, `shaza`, `s-h-a-z-a@...`, etc. don't seem to work for me. 
Again, it would be great to contact you directly, but I think I'd need some sort of guidance to contact you over this method. This seems like a very interesting technology and I'd be eager to learn it.

**Comment by sfshaza2** [comment]
So sorry, @micpap25! All I meant was your email address. Mine is @google.com.
