### ISSUE TITLE
'Binding to native code using dart:ffi' page issue

### ISSUE THREAD

**Issue by krolaw** [flutter/website#4551]
https://flutter.dev/docs/development/platform-integration/c-interop

Step two fails because ios and android directories do not exist.
It appears to be missing:
```bash
flutter create -t plugin --platforms android .
flutter create -t plugin --platforms ios .
```
after step one and before step two.

**Comment by aromalanil** [comment]
I would like to work on it. Will the issue be solved if I add these commands to [Step 1](https://flutter.dev/docs/development/platform-integration/c-interop#step-1-create-a-plugin)

**Comment by krolaw** [comment]
Worked for me. I added them and was able to complete the tutorial.
