### ISSUE TITLE
Firebase for Flutter Codelab with outdated Tutorials

### ISSUE THREAD

**Issue by silas96** [flutter/website#4563]
I'm having trouble with the Firebase codelab tutorial because there are some outdated tutorials there. The 'Create your Cloud Firestore database' it's been the most problematic one for me now. The site now is quite different from the tutorial's instructions and images.

**Comment by sfshaza2** [comment]
@silas96, do you mean [this codelab](https://codelabs.developers.google.com/codelabs/firestore-web/#0)?

If so, this is the wrong place to file an issue, as we maintain the Flutter docs and Flutter codelabs. On the lower-left corner of the codelab pages, there is a "report a mistake" link. Follow that link to report a problem.

CC: @kroikie

**Comment by sfshaza2** [comment]
@silas96, I am assuming that this meant to file an issue with the Firebase codelab (not Flutter). I'm closing this. If I'm wrong, please reopen and clarify. Thx!
