### ISSUE TITLE
'Use a custom font' page issue - Webpage displays broken links 

### ISSUE THREAD

**Issue by roshanrahman** [flutter/website#4564]
Page URL: https://flutter.dev/docs/cookbook/design/fonts.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/fonts.md

Description of issue:

Webpage displays broken links (see image below)
![custom-fonts-issue](https://user-images.githubusercontent.com/24898148/91900778-d16fe700-ecbc-11ea-9c81-241011f7a5fc.png)

Instead of an interactive link, the page has empty text like `Check out the [google_fonts][] package for direct access to almost 1000 open-sourced font families`

**Comment by aromalanil** [comment]
Every link in this page is broken. Also, the link references are visible at the bottom of the page, I am looking for a solution.
