### ISSUE TITLE
Flutter performance profiling page suggestions

### ISSUE THREAD

**Issue by liyuqian** [flutter/website#4565]
1. `[Flutter inspector talk][], presented at DartConf 2018` seems to have a broken link
2. It would be nice to add a section about "How to export a timeline trace file" so we can reference it in Github performance issues.

The 2nd item should now be easy thanks to DevTools. CC @kenzieschmoll

**Comment by liyuqian** [comment]
CC @Sfshaza

**Comment by sfshaza2** [comment]
Thanks for fixing issue #1, @aromalanil! Reopening because this doesn't address issue #2.

**Comment by liyuqian** [comment]
@Sfshaza : I just realized that https://flutter.dev/docs/development/tools/devtools/timeline covers the timeline import/export. Maybe some cross references would be sufficient? It may also be nice to cross reference some other performance tools provided by DevTools such as memory and app size.

**Comment by micpap25** [comment]
https://flutter.dev/docs/perf/rendering/ui-performance#launch-devtools links to both the Timeline page and the list of all DevTools. 
I think there's a good amount of cross-referencing, unless we add more of the possible DevTools functions to that section. 
Personally, though, I think the issue has been resolved.

**Comment by liyuqian** [comment]
Agree. Closing this issue now.
