### ISSUE TITLE
Selected document isn't reflected correctly on navbar.

### ISSUE THREAD

**Issue by DamienKusters** [flutter/website#4571]
Page URL: https://flutter.dev/docs/perf/app-size.html
Page source: https://github.com/flutter/website/tree/master/src/docs/perf/app-size.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
The section: "Performance & optimization" in the navbar on the left, doesn't reflect the currently open page within that section. Page 'Overview' will stay highlighted.

**Comment by JuYeong0413** [comment]
Also for `Rendering performance` section, `Overview` stays highlighted.

**Comment by aromalanil** [comment]
I found that these [lines](https://github.com/flutter/website/blob/920cb76f1f24ddcf8e7f0b3c13666f9823557d02/src/_data/sidenav.yml#L281-L284) are commented in sidenav.yml. Is this what causing this issue. Why is there code commented in production?

**Comment by aromalanil** [comment]
This issue was caused because of the overview page getting matched with all pages including `docs/perf/app-size`, `docs/perf/rendering/best-practices` etc. The overview page was only supposed to match with the exam page URL: `docs/perf/`.
