### ISSUE TITLE
Flutter Firebase Codelab @7. Platform-specific Firebase configuration error

### ISSUE THREAD

**Issue by chernhaw** [flutter/website#4579]
Hi, 

I not sure if I have missed out something when I tried out the https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html?index=..%2F..index#6

I got stuck here at step 12 with  issue,  I cannot find buildscript tag in my build.gradle file.

below is my build.gradle file:

 def localProperties = new Properties()
 def localPropertiesFile = rootProject.file('local.properties')
 If (localPropertiesFile.exists()) {
     localPropertiesFile.withReader('UTF-8') { reader ->
         localProperties.load(reader)
     }
 }

 def flutterRoot = localProperties.getProperty('flutter.sdk')
 if (flutterRoot == null) {
     throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
 }

 def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
 if (flutterVersionCode == null) {
     flutterVersionCode = '1'
 }

 def flutterVersionName = localProperties.getProperty('flutter.versionName')
 if (flutterVersionName == null) {
     flutterVersionName = '1.0'
 }

 apply plugin: 'com.android.application'
 apply plugin: 'kotlin-android'
 apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

 android {
     compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        multiDexEnabled true
        applicationId "com.tongchernhaw.hammynames"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

 dependencies {
     implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
     testImplementation 'junit:junit:4.12'
     androidTestImplementation 'androidx.test:runner:1.1.1'
     androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
     implementation 'androidx.multidex:multidex:2.0.1'
     //classpath 'com.google.gms:google-services:4.3.3'
 }
 apply plugin: 'com.google.gms.google-services'

**Comment by aromalanil** [comment]
@chernhaw The path to the `build.gradle` you are looking for is `android/build.gradle`. What you have posted here is `build.gradle` from `android/app/build.gradle`.

**Comment by sfshaza2** [comment]
Thanks, @chernhaw! I take it we can close this issue?

**Comment by chernhaw** [comment]
Yes, please close this issue.
Thanks.

Regards,
Chern Haw



Sent from Outlook<http://aka.ms/weboutlook>

________________________________
