### ISSUE TITLE
'AppBar Basics' page issue

### ISSUE THREAD

**Issue by Nikhil-Wagh** [flutter/website#4583]
Page URL: https://flutter.dev/docs/catalog/samples/basic-app-bar.html
Page source: https://github.com/flutter/website/tree/master/src/docs/catalog/samples/basic-app-bar.md

Description of issue:
The image won't load. When opened in another tab, the page says the bucket doesn't exist. 

This is the URL https://storage.googleapis.com/flutter-catalog/cb4a54db8fb3726bf4293b9cc5cb12ce16883803/basic_app_bar_small.png

**Comment by aromalanil** [comment]
When I visit the page I got a popup saying `This page is deprecated and its content may be out of date.` 
Maybe that's why the image is not present.
![image](https://user-images.githubusercontent.com/49222186/92330966-968cfb00-f090-11ea-9efa-974b760ac539.png)

**Comment by sfshaza2** [comment]
Hmmm. This is not the first page that has been affected.
