### ISSUE TITLE
'Windows install' page issue - Use where command instead of which

### ISSUE THREAD

**Issue by pavi2410** [flutter/website#4586]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:
Under the ["Update your path"](https://flutter.dev/docs/get-started/install/windows#update-your-path) header, there is a note which tells us to run this command `which flutter dart` which is not available on Windows. I request you to change that to use the `where` command built into Windows. This will avoid confusion among Windows users.

**Comment by TheBiirb** [comment]
It is pretty clear in the documentation:

> The following command (### on macOS, linux, and chrome OS), tells you whether the flutter and dart commands originate from the same bin directory and are therefore compatible. (**Some versions of Windows support a similar where command**.)

**Comment by sfshaza2** [comment]
Thanks for that info, @pavi2410! PRs welcome, by the way.  :D

**Comment by micpap25** [comment]
Just going to add that the section @pavi2410 is referring to is part of a file in _includes that is shared between the Install page for Windows, Mac, and Linux.
I also agree that it is pretty clear unless we were to make a completely separate version of this section for Windows. Is that a good idea? If so I think the title of this issue should be changed to reflect that, and also the time to resolve might need to be increased.

**Comment by sfshaza2** [comment]
I'm closing this issue. The doc does mention using "where" on Windows.
