### ISSUE TITLE
Flutter site broken

### ISSUE THREAD

**Issue by karthickramanathan95** [flutter/website#4589]
See image

![image](https://user-images.githubusercontent.com/30870272/92505825-22825c80-f222-11ea-9d8c-64e57a40c485.png)

**Comment by JuYeong0413** [comment]
Similar issue of https://github.com/flutter/website/issues/4477
Could you please provide more information like browser/os version/locale/output from `flutter doctor`?
It would be helpful for the flutter team to solve this issue. :)

**Comment by sfshaza2** [comment]
Yes, we have had others report this problem, who are also from remote locales. I'm going to add this info to the other issue but, as of yet, we don't know what's going on. Having more info about your environment, locale, etc, would help.

**Comment by karthickramanathan95** [comment]
Browser: Version 87.0.4259.3 (Official Build) dev (64-bit)
OS: Windows 10 Enterprise v1903
Locale: English

Flutter not installed
