### ISSUE TITLE
'ExpansionTile' page issue

### ISSUE THREAD

**Issue by Scienticious** [flutter/website#4591]
Page URL: https://flutter.dev/docs/catalog/samples/expansion-tile-sample.html
Page source: https://github.com/flutter/website/tree/master/src/docs/catalog/samples/expansion-tile-sample.md

Screenshot not showing of Expansion Tile

Description of issue:
Expansion tile screenshot, image is not showing

**Comment by JuYeong0413** [comment]
That page is deprecated, that's probably why the image is not showing.
<img width="563" alt="Screen Shot 2020-09-09 at 5 36 25 PM" src="https://user-images.githubusercontent.com/33684401/92575268-15697a00-f2c3-11ea-827d-a0aa02907b2f.png">
