### ISSUE TITLE
'Obfuscating Dart code' page issue

### ISSUE THREAD

**Issue by PixelToast** [flutter/website#4608]
Page URL: https://flutter.dev/docs/deployment/obfuscate.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/obfuscate.md

## Description

This page uses absolute paths for split-debug-info and symbolize samples:

`flutter build apk --obfuscate --split-debug-info=/<project-name>/<directory>`
`flutter symbolize -i <stack trace file> -d /out/android/app.android-arm64.symbols`

On Linux this example can result in some confusing permission denied error messages due to the fact that your project isn't directly in root: https://pastebin.com/6ULu00Az (courtesy of @Amanv8060)

The tooling could also probably make this less confusing, cc @jonahwilliams

**Comment by sfshaza2** [comment]
This is a good point. @jonahwilliams, is there any reason that we can't make this command more general, and just specify `<directory>` instead of `/out...`? And the same for `flutter symbolize`?

(I noticed, @amanv8060, that your PR only addresses the `flutter build apk...` command, but it applies equally to the `flutter symbolize` command.)

**Comment by jonahwilliams** [comment]
The `valueHelp` field is supposed to look like real data, i.e. if it accepted numbers valueHelp might be `2`. So if we specified `<directory>` in the value help it might not be obvious what it should be

**Comment by sfshaza2** [comment]
@jonahwilliams, at the very least, we could remove the leading `/`, right? As that assumes the root directory which won't be true for most.

**Comment by jonahwilliams** [comment]
yes, we definitely should

**Comment by amanv8060** [comment]
Wouldn't that just create the entire path of folders inside the app , which
in some cases would be unnecessary , foe eg split debug info
