### ISSUE TITLE
Small Fix in Sample Code for Baby Names example

### ISSUE THREAD

**Issue by shi2rs** [flutter/website#4618]
The named constructor in Record class .fromSnapshot should refer to snapshot.data() function call to return a map
 Record.fromSnapshot(DocumentSnapshot snapshot)
     : this.fromMap(**snapshot.data**, reference: snapshot.reference);

[Tutorial location](https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html)

**Comment by lucalves** [comment]
The same as #4504.

**Comment by domesticmouse** [comment]
The `flutter-firebase` codelab has been replaced by the [Get to know Firebase for Flutter](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#0) codelab. Thanks for the report!
