### ISSUE TITLE
Typo in Flutter Testing Codelab

### ISSUE THREAD

**Issue by kishanhitk** [flutter/website#4625]
There is a typo in the [4th step](https://codelabs.developers.google.com/codelabs/flutter-app-testing/#3) of this Codelab.
In the 3rd section named "**_Add the Favorites page in lib/screens/favorites.dart_**", the tutorial says to create a new file named **home.dart**, but it should be **favorites.dart**. 

@abd99
@domesticmouse

**Comment by abd99** [comment]
Thanks for filing an issue @kishanhitk!

@domesticmouse, I've made the changes in the Google Doc. Please take a look.

**Comment by domesticmouse** [comment]
Codelab re-published =)
