### ISSUE TITLE
Unclear/incorrect wording in 'Using the Performance view', profile-granularity

### ISSUE THREAD

**Issue by miDeb** [flutter/website#4633]
Page URL: https://flutter.dev/docs/development/tools/devtools/performance#profile-granularity
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/devtools/performance.md

Description of issue:
> The sampling rates for low, medium, and high granularity are 1 / 50 μs, 1 / 250 μs, and 1 / 1000 μs, respectively.

I think this should be the opposite way around (low is a sample every 1000 μs, high is one every 50 µs) and could be clearer (like saying _every_ x μs).

**Comment by aromalanil** [comment]
Now I am having the same doubt. Should'nt this be the other way around 🤔?

**Comment by sfshaza2** [comment]
@filiph ?  @liyuqian ?  Can one of you verify?

**Comment by liyuqian** [comment]
That sounds about right. Defer the final confirmation to @kenzieschmoll

**Comment by kenzieschmoll** [comment]
yes that is correct - high and low are switched in the current state
