### ISSUE TITLE
Mention Timeline utilities in https://flutter.dev/docs/perf

### ISSUE THREAD

**Issue by miDeb** [flutter/website#4634]
I was looking for https://api.dart.dev/stable/2.9.3/dart-developer/Timeline-class.html, but couldn't remember how it was called (I was looking up "profiler markers"). It looks like they're nowhere mentioned in https://flutter.dev/docs/perf, only in https://flutter.dev/docs/testing/code-debugging#tracing-dart-code-performance, which I didn't look at initially. It really took me some time to find that api, and I think it would be nice to include a reference to it somewhere in the performance section.

**Comment by sfshaza2** [comment]
Great idea!

**Comment by parlough** [comment]
I'm going to close this as these are now referenced in the relevant performance page and timeline documentation (https://docs.flutter.dev/development/tools/devtools/performance#timeline-events-chart) with https://github.com/flutter/website/pull/5142. The other reference in code-debugging is also being updated with https://github.com/flutter/website/pull/8046.

Thanks for opening the issue and let us know if you think there are other improvements to be made in this area :)
