### ISSUE TITLE
Wrong filename in write-flutter-plugin codelab

### ISSUE THREAD

**Issue by toki2612** [flutter/website#4647]
In the 4th step (the last code box) of the codelab 'How to write a Flutter plugin' there is an ios filename instead of android: 

<img width="795" alt="Screenshot 2020-09-23 at 15 14 31" src="https://user-images.githubusercontent.com/16033629/94017732-0e0c9b00-fdb0-11ea-87bb-bffabb076c93.png">

**Comment by vimalverma558** [comment]
Page URL: https://codelabs.developers.google.com/codelabs/write-flutter-plugin/#3

**Comment by saumya66** [comment]
Rather this should be the name right ?? :
`android/src/main/java/com/example/PluginCodelab/PluginCodelabPlugin.java`

**Comment by domesticmouse** [comment]
By the looks of https://codelabs.developers.google.com/codelabs/write-flutter-plugin/#3 this issue has been fixed. Thanks for the report!
