### ISSUE TITLE
'Desktop support for Flutter' page issue

### ISSUE THREAD

**Issue by a2fStart** [flutter/website#4652]
Page URL: https://flutter.dev/desktop.html
Page source: https://github.com/flutter/website/tree/master/src/desktop.md

Description of issue: Could you change the windows status from under development to the alpha?

**Comment by aromalanil** [comment]
![image](https://user-images.githubusercontent.com/49222186/94096584-19100b80-fe42-11ea-993a-966bd4ba3321.png)
The page already contains a warning msg saying it is in Alpha

**Comment by sfshaza2** [comment]
Good point! I (and my reviewers) missed that one.

**Comment by sfshaza2** [comment]
Wait, I take it back. I don't see where it says on the page that Windows support is "under development".

**Comment by a2fStart** [comment]
> 
> 
> Wait, I take it back. I don't see where it says on the page that Windows support is "under development".

I am sure, when I wrote the message there is text "under development".
