### ISSUE TITLE
Define the differences between "packages" and "plugins"

### ISSUE THREAD

**Issue by jmagman** [flutter/website#4661]
Plugins and packages are used interchangeably in the "Using packages" guide, but I don't see a definition between the two terms.
https://flutter.dev/docs/development/packages-and-plugins/using-packages

**Comment by sfshaza2** [comment]
Yes, this page should be clarified, though the info is on the [developing packages](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#types) page. Though, again, it could be made more clear.

**Comment by jmagman** [comment]
That's exactly what I was looking for!  Maybe https://flutter.dev/docs/development/packages-and-plugins/using-packages just needs a link to that.

**Comment by jmagman** [comment]
I was trying to define it for using plugins in an app, not developing them, so I didn't look on the developing packages page.

**Comment by Roshan13046** [comment]
> That's exactly what I was looking for! Maybe https://flutter.dev/docs/development/packages-and-plugins/using-packages just needs a link to that.

I would like to work on this issue.
so, should I add a link or define difference between packages and plugins?

**Comment by sfshaza2** [comment]
Go for it! I would like to see a section added to the beginning of the page defining the difference. Then we can link to that text from other pages, as needed.

**Comment by parlough** [comment]
This has been expanded on in https://github.com/flutter/website/pull/5287 :)
