### ISSUE TITLE
The method '+' was called on null. Receiver: null Tried calling: +(50.0)

### ISSUE THREAD

**Issue by SainathPatil001** [flutter/website#4664]
Page URL: https://flutter.dev/docs/testing/errors.html
Page source: https://github.com/flutter/website/tree/master/src/docs/testing/errors.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by sfshaza2** [comment]
@SainathPatil001, can you give us more info? (More than the title.). thx

**Comment by SainathPatil001** [comment]
I/le.rolling_Dic(26572): Starting profile saver IsSaveProfileNow end.
E/flutter (26572): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'findAncestorStateOfType' was called on null.
E/flutter (26572): Receiver: null
E/flutter (26572): Tried calling: findAncestorStateOfType<NavigatorState>()
E/flutter (26572): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
E/flutter (26572): #1      Navigator.of 
package:flutter/…/widgets/navigator.dart:2218
E/flutter (26572): #2      _SplashScreenState.onDoneLoading 
package:rolling_Dice/splash.dart:24
E/flutter (26572): #3      _rootRun  (dart:async/zone.dart:1182:47)
E/flutter (26572): #4      _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (26572): #5      _CustomZone.runGuarded  (dart:async/zone.dart:997:7)
E/flutter (26572): #6      _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)
E/flutter (26572): #7      _rootRun  (dart:async/zone.dart:1190:13)
E/flutter (26572): #8      _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (26572): #9      _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:1021:23)
E/flutter (26572): #10     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:18:15)
E/flutter (26572): #11     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (26572): #12     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (26572): #13     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by SainathPatil001** [comment]
Sorry I have sorted that error but this in new error

**Comment by sfshaza2** [comment]
Hi, @SainathPatil001. What code are you running? Is this error from one of our examples?

If this is coming from your own code, then it sounds like you are asking for help. This repo is where to report documentation errors, not ask for support. For that, use one of the resources listed on our flutter.dev/community page.

Good luck!

**Comment by SainathPatil001** [comment]
Thank you..!
