### ISSUE TITLE
'Flutter performance profiling' page issue

### ISSUE THREAD

**Issue by admarwick** [flutter/website#4668]
Page URL: https://flutter.dev/docs/perf/rendering/ui-performance.html
Page source: https://github.com/flutter/website/tree/master/src/docs/perf/rendering/ui-performance.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
There's a "Pending" note in the section at https://flutter.dev/docs/perf/rendering/ui-performance#identifying-problems-in-the-ui-graph which doesn't seem to belong in production content.

**Comment by pranjaljain0** [comment]
Can I do it?

**Comment by sfshaza2** [comment]
A PR I merged this morning removed this note.
