### ISSUE TITLE
App preview not displaying and says Missing browser features

### ISSUE THREAD

**Issue by purezen** [flutter/website#4673]
Throughout the site, I am unable to see the app preview ( so I concur )

Says 'Missing browser features
DartPad requires localStorage to be enabled. For more information, visit dart.dev/tools/dartpad/troubleshoot.'

I am using Brave browser

![Screenshot 2020-09-26 185253](https://user-images.githubusercontent.com/3036093/94341749-88941f80-0029-11eb-8e15-b58dc5cd162f.jpg)

**Comment by sfshaza2** [comment]
@johnpryan, is this a known issue on Blaze?

**Comment by pranjaljain0** [comment]
<img width="1440" alt="Screenshot 2020-09-30 at 1 22 36 AM" src="https://user-images.githubusercontent.com/53955200/94608727-703b3380-02bb-11eb-9deb-480bd2d5fc6c.png">
I am using the same page on brave,
Doesn't seem like a browser issue.
@Sfshaza

**Comment by sfshaza2** [comment]
It may be, @pranjaljain0, as both you and @purezen are using the Brave browser and I don't know if DartPad is well supported. I'll let @johnpryan weigh in. Thanks for reporting this!

**Comment by xxwassyxx** [comment]
This is because of braves shield that blocks things it deems as bad. Disable it for the flutter page and things work as expected

**Comment by sfshaza2** [comment]
Thanks for this explanation, @xxwassyxx!

@purezen and @pranjaljain0, can you confirm that this fixes your issue?

@RedBrogdon, @domesticmouse, @johnpryan, did you know that Brave doesn't work with DartPad unless the specific page is manually unblocked? I wonder if a note can be added to DartPad itself in this case.

**Comment by pranjaljain0** [comment]
> I am using the same page on brave, Doesn't seem like a browser issue. @Sfshaza

**Comment by johnpryan** [comment]
We don't support the Brave browser, since it disables required features. See the [troubleshooting](https://dart.dev/tools/dartpad/troubleshoot) page for more info and a list of our [supported browsers](https://dart.dev/faq#q-what-browsers-do-you-support-as-javascript-compilation-targets)

**Comment by sahir-jaman** [comment]
I also had the same problem. That's why i changed my browser. And then i was able to use the dartpad

**Comment by sahir-jaman** [comment]
Solution is here :✌✔✨❤

https://www.youtube.com/watch?v=6vAHAce5LLY&t=2s
