### ISSUE TITLE
Offer Flutter install as rpm and deb package on 'Linux install' page

### ISSUE THREAD

**Issue by SchoolGuy** [flutter/website#4677]
Page URL: https://flutter.dev/docs/get-started/install/linux.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/linux.md

Description of issue: Native packaging formats like deb and rpm missing?

I was reading the installation instructions and I am a fan of having native packages like deb or rpm. Is that something which was discarded by design or has just no one worked on this yet? If it is desired I should be able to help at least with RPM based packages.

**Comment by sfshaza2** [comment]
@johnpryan, do you know?

**Comment by johnpryan** [comment]
Right now the docs assume which package manager you are using. Are there examples of other projects that include instructions for multiple distros / package managers? It can be confusing for users who are using distro X when the instructions are for distro Y.

**Comment by sfshaza2** [comment]
My understanding is that we will add more info as the alpha gets further along. However, based on PR https://github.com/flutter/website/pull/4812, I'm not quite sure how we expect to proceed.

**Comment by johnpryan** [comment]
We can't cover all package managers, but we probably want to be consistent with #4812.

**Comment by SchoolGuy** [comment]
May I suggest leaving packaging to downstream? That may lead to outdated packages in some cases, in my eyes the advantage is that you spare yourself the load of this work. The only thing you need to provide is offline building instructions in my eyes to support airgapped build environments. Services like the openSUSE Build Service is able to build for a lot of distributions and reduce the total amount of work. Documentation for the different package managers could also be contributed by downstream.

**Comment by atsansone** [comment]
This is being discussed in https://github.com/flutter/flutter/issues/108681. 

@Piinks : Were there any thoughts on distributing Flutter as an rpm or deb package?

**Comment by Piinks** [comment]
> Were there any thoughts on distributing Flutter as an rpm or deb package?

Not that I am aware of, but I am not involved in those decisions.

**Comment by atsansone** [comment]
This issue needs to be resolved as a Flutter feature first before we can document. When and if this feature is complete, we will document at that time. Closing this issue.
