### ISSUE TITLE
'Add Flutter to existing app' page issue

### ISSUE THREAD

**Issue by Alfaesal23** [flutter/website#4680]
Page URL: https://flutter.dev/docs/development/add-to-app/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/add-to-app/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by sfshaza2** [comment]
Nothing described. Closing.
