### ISSUE TITLE
Navigation Bar Responsiveness

### ISSUE THREAD

**Issue by Niranjan215** [flutter/website#4709]
Navigation need to be set for responsive screen for smaller screen size by using some CSS properties.

**Comment by ayaankhan98** [comment]
top navigation bar seems responsive to me for all screen widths. can you please explain your point a bit clearly?

**Comment by parlough** [comment]
Currently the top navigation bar and side menu now appear responsive to different screen widths. I'm going to close this, but if anyone has any further issues, please let us know by creating a new issue. Thanks so much!
