### ISSUE TITLE
Codelab code not working 

### ISSUE THREAD

**Issue by tango4567** [flutter/website#4783]
[Using a plugin with a Flutter web app](https://codelabs.developers.google.com/codelabs/web-url-launcher/index.html?index=..%2F..index#9) 

The following **Codelab** code is not working 
```
onPressed: () => launch(
  '/#/privacypolicy',                // <--------Not Working 
  enableJavaScript: true,
  enableDomStorage: true,
),
```

After this change code is working fine
```
onPressed: () => launch(
 '/privacy_policy.html',     //<--------------Change Required
 enableJavaScript: true,
 enableDomStorage: true,
),
```
I cross-check these pieces of code multiple times and then I'm writing this issue. 
If I'm missing anything please let me know.
Thanks In Advance.

**Comment by aromalanil** [comment]
@sfshaza2 I couldn't find the code for any of the codelabs issues I have come across. Where exactly is these issue being fixed?

**Comment by sfshaza2** [comment]
Hi @aromalanil! Unfortunately the source for the codelabs published to codelabs.google.developers.com is not available externally. It's an internal process.

**Comment by aromalanil** [comment]
@Oh! Okay 👍🏻

**Comment by domesticmouse** [comment]
By the look of https://codelabs.developers.google.com/codelabs/web-url-launcher/#9 this issue has been fixed. Thanks for the report!
