### ISSUE TITLE
'New CupertinoIcons has icon glyph changes' page issue

### ISSUE THREAD

**Issue by deandreamatias** [flutter/website#4791]
Page URL: https://flutter.dev/docs/release/breaking-changes/cupertino-icons-1.0.0.html
Page source: https://github.com/flutter/website/tree/master/src/docs/release/breaking-changes/cupertino-icons-1.0.0.md

Description of issue:
In Timeline section say:
Landed in: 1.22.0-10.0.pre.65
In stable release: not yet

But with new release, maybe will be say
Landed in: 1.22.0
In stable release: yes (?)

**Comment by sfshaza2** [comment]
Yup, I need to go through and update the breaking changes docs.

**Comment by aromalanil** [comment]
@sfshaza2 I would like to help. Is this the only change needed on this page?

**Comment by sfshaza2** [comment]
Sorry, @aromalanil, I spent a chunk of today going through the breaking change docs and updating them. I have a PR in flight. There are numerous things I do for this. But thanks for that offer!

**Comment by aromalanil** [comment]
@sfshaza2 Okay. Cool 😄

**Comment by deandreamatias** [comment]
Solved by PR #4806
