### ISSUE TITLE
'Desktop support for Flutter' page issue

### ISSUE THREAD

**Issue by AllanDaemon** [flutter/website#4805]
Page URL: https://flutter.dev/desktop.html
Page source: https://github.com/flutter/website/tree/master/src/desktop.md

Description of issue: Add the command for dnf package manager

In the session [#additional-linux-requirements](https://flutter.dev/desktop#additional-linux-requirements), there is a command for installing it manually for Linux. The command is using APT, that is only for Debian-based distros. It should change from:

> If snapd is unavailable on the Linux distro you’re using, you might use the following command:

for something like:

> If snapd is unavailable on the Linux distro you’re using, you might use the following command for distros that use APT (Debian, Ubuntu, Mint):

Also, you could add the Fedora version of the command, that is the main point of this issue, that is this one:

`dnf install clang cmake ninja-build pkg-config gtk3-devel libblkid-devel`

**Comment by sfshaza2** [comment]
Yes, we do plan to augment this info soon. Thx

**Comment by atsansone** [comment]
This page no longer exists as indicated. Closing.
