### ISSUE TITLE
out of the room

### ISSUE THREAD

**Issue by haiderajmal** [flutter/website#4822]
the picture side is out of the room at which widget I should use wrap widget to resolve the issue 
![Screenshot (54)](https://user-images.githubusercontent.com/67483723/95110562-a3684180-0757-11eb-801e-2841f56299a7.png)

**Comment by sfshaza2** [comment]
Hi, @haiderajmal, this UI is definitely not a responsive design. Unfortunately, this is not where to get support. Please refer to the channels on flutter.dev/community.
