### ISSUE TITLE
Flutter firebase codelab issue step #9

### ISSUE THREAD

**Issue by slashwhatever** [flutter/website#4830]
[Codelab page](https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#8)

After pasting the `_buildBody` method into `main.dart`, you will be prompted that there are 2 problems in the file:

```
'Firestore' is deprecated and shouldn't be used. Class Firestore is deprecated, use 'FirebaseFirestore' instead..
Try replacing the use of the deprecated member with the replacement.
```

Performing this change does result in the problem being cleared.

```
'documents' is deprecated and shouldn't be used. Deprecated in favor of `.docs`.
Try replacing the use of the deprecated member with the **replacement.**
```

Performing this change does result in the problem being cleared.

**Comment by maheshmnj** [comment]
Hi @slashwhatever, Thanks for filing the issue, the link shared in the description is broken could you please point to the proper link in order for this issue to be actionable.

Thank you.

**Comment by maheshmnj** [comment]
Is this the codelab you are referring to https://codelabs.flutter-io.cn/codelabs/flutter-firebase/index.html#8

**Comment by slashwhatever** [comment]
It's been a while since I looked and it seems the original pages have been moved. @maheshmnj it does look like the issue I was referring to but I haven't had time to re-verify.
