### ISSUE TITLE
Flutter firebase codelabs fails

### ISSUE THREAD

**Issue by slashwhatever** [flutter/website#4831]
After completing all the code in the codelab, the Android emulator generates this error:

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following FirebaseException was thrown building MyHomePage(dirty, state: _MyHomePageState#8b377):
[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

```

Replacing the `MyApp` class with the following should work:

```
import 'package:firebase_core/firebase_core.dart';

class MyApp extends StatelessWidget {
  final Future<FirebaseApp> _initialization = Firebase.initializeApp();

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      // Initialize FlutterFire:
      future: _initialization,
      builder: (context, snapshot) {
          return MaterialApp(
            title: 'Baby Names',
            home: MyHomePage(),
          );
      },
    );
  }
}

```

**Comment by sfshaza2** [comment]
@domesticmouse, we received a recent spate of issues filed against this codelab. Could you take a look?

**Comment by TahaTesser** [comment]
Hi @slashwhatever 
Thanks for filing the issue, the Firebase Codelab is updated in [step 4](https://firebase.google.com/codelabs/firebase-get-to-know-flutter#4) with instructions to [initialize Firebase](https://firebase.flutter.dev/docs/overview/#initializing-flutterfire) in your dart code, which will get rid of this error

Closing as fixed
