### ISSUE TITLE
Use the characters package in cookbook pages about text processing

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#4834]
The characters package has been integrated into the Flutter framework and is now the recommended way to handle user-entered text from widgets such as TextField. The API docs have been updated in this recent PR (https://github.com/flutter/flutter/pull/67361). It would be really helpful to use the characters package in the following cookbook pages as well:

- https://flutter.dev/docs/cookbook/forms/text-field-changes
- https://flutter.dev/docs/cookbook/forms/retrieve-input

**Comment by atsansone** [comment]
@justinmc : Could you let us know when you could get to this? Thanks!

**Comment by atsansone** [comment]
@justinmc : Sounds reasonable. May be a solid update.

**Comment by sfshaza2** [comment]
@miquelbeltran, I like the idea of adding the characters package as Justin described above. Please weigh in.

**Comment by justinmc** [comment]
Thanks, that plan sounds great to me!
