### ISSUE TITLE
'Building a web application with Flutter' page issue

### ISSUE THREAD

**Issue by carpiodanielj** [flutter/website#4836]
Page URL: https://flutter.dev/docs/get-started/web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/web.md

Description of issue:

** Please add this last step when setting up web development: **flutter update-packages**
See this link [https://github.com/flutter/flutter/issues/58110#issuecomment-634940055](url)

**Comment by sfshaza2** [comment]
Actual link:   https://github.com/flutter/flutter/issues/58110

**Comment by parlough** [comment]
This shouldn't be an issue now that web is stable and `flutter update-packages` is not meant for users but Flutter maintainers. 

Let us know if you have any more issues setting up web support. Thanks!
