### ISSUE TITLE
Fix Firebase for Flutter Codelab step 7

### ISSUE THREAD

**Issue by yashwanth-ravula** [flutter/website#4841]
In the last line, the link to **FlutterFire GitHub page** should be updated. The current link is directing us to an empty Github page.
The FlutterFire family of plugins has moved to the FirebaseExtended organization on GitHub.

**Comment by maheshmnj** [comment]
I can see that the code lab is pointing to the readme at [flutter/plugins](https://github.com/flutter/plugins/blob/master/FlutterFire.md) which then points to the flutterfire repo

Code lab: https://codelabs.flutter-io.cn/codelabs/flutter-firebase/index.html#6

The FlutterFire Github is moved here: https://github.com/flutter/plugins/blob/master/FlutterFire.md

**Comment by atsansone** [comment]
This codelab runs on the community China mirror. The original codelab has been deprecated. Closing this issue.
