### ISSUE TITLE
Fix Firebase for Flutter Codelab step 9

### ISSUE THREAD

**Issue by yashwanth-ravula** [flutter/website#4843]
The following error showed up.
```terminal
No firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
```

solution:
All Firebase versions have been updated and now you have to call `Firebase.initializeApp()` before using any Firebase product, for example:

**Comment by maheshmnj** [comment]
codelab: https://codelabs.flutter-io.cn/codelabs/flutter-firebase/index.html#8

The codelab in step 9 before trying to fetch the data from the collection should initialize the firebase app as in the [official example](https://pub.dev/packages/cloud_firestore/example) on pub.dev, Other wise this would result in error.

```
 await Firebase.initializeApp();
```

**Comment by atsansone** [comment]
This codelab runs on the community China mirror. The original codelab has been deprecated. Closing this issue.
