### ISSUE TITLE
Update iOS deployment docs with `flutter build ipa` command

### ISSUE THREAD

**Issue by jmagman** [flutter/website#4852]
https://github.com/flutter/flutter/pull/67598 and https://github.com/flutter/flutter/pull/67781 introduces a new `flutter build ipa` command.
Reference in the [iOS deployment docs](https://flutter.dev/docs/deployment/ios#create-a-build-archive).

1. Remove the `flutter build ios` instructions.
1. Replace 
> 1. Select Product > Archive to produce a build archive
> 1. In the sidebar of the Xcode Organizer window, select your iOS app, then select the build archive you just produced.

with something like:
> 1. Run `flutter build ipa`
> 2. Open the archive in`build/ios/archive` in Xcode by running `open -a Xcode build/ios/archive/YourApp.xcarchive` or locating it in Finder and opening it.

Keep the "Click the Validate App button." next step.

Add something about `flutter build ipa` with hints for how to populate the optional `--export-options-plist` file.

**Comment by NTA-trongpq** [comment]
@jmagman Sorry if I disturb you. Does this command `flutter build ipa` run a clean build iOS (In Xcode, Product -> Clean build folder)?

**Comment by jmagman** [comment]
> @jmagman Sorry if I disturb you. Does this command `flutter build ipa` run a clean build iOS (In Xcode, Product -> Clean build folder)?

No, neither does `flutter run` or `build`.  You can run `flutter clean`.

**Comment by r-dev-limited** [comment]
how can get non signed archive....someone mentioned that build ipa does not sign...but thats not true.

**Comment by jmagman** [comment]
> how can get non signed archive....someone mentioned that build ipa does not sign...but thats not true.

See https://github.com/flutter/flutter/issues/101765
