### ISSUE TITLE
Add article to state management approach

### ISSUE THREAD

**Issue by d3xt3r2909** [flutter/website#4854]
Hi guys & girls

is it possible to add this [article](https://medium.com/upday-devs/reduce-duplication-achieve-flexibility-means-success-for-the-flutter-app-e5e432839e61)  to the state management [recco page](https://flutter.dev/docs/development/data-and-backend/state-mgmt/options)? 

- It's about the usage of redux in combination with redux_epics. 

Of course, if you say yes (and please say), I would create PR.

Thanks

**Comment by sfshaza2** [comment]
Sure! Create the PR.  :)

**Comment by d3xt3r2909** [comment]
Hi @sfshaza2, 

thanks for review it. I've created [PR](https://github.com/flutter/website/pull/4896). 

See you

**Comment by micpap25** [comment]
Since the PR was merged, I think this can be closed.
