### ISSUE TITLE
'Upgrading Flutter' page issue

### ISSUE THREAD

**Issue by JeanDesenvolvedo32322313** [flutter/website#4856]
Page URL: https://flutter.dev/docs/development/tools/sdk/upgrading.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/upgrading.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by Abhishek01039** [comment]
Hi @JeanDesenvolvedo32322313 
can you please elaborate in more detail please that what problem are you facing?
Thanks

**Comment by sfshaza2** [comment]
Nothing described. Closing.
