### ISSUE TITLE
Change build to use `dart` tool

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#4864]
A writer attempting to run `install.sh` got this message:

```
Dart SDK appears to be installed: dart is <some-path>/flutter/bin/dart
Dart SDK version: 2.11.0-207.0.dev (dev) (Fri Oct 9 09:16:09 2020 -0700) on "macos_x64"
./tool/before-install.sh: line 29: pub: command not found
```

If we switch to the new `dart` tool (e.g. `dart pub`), then you should be able to build the site whether or not you separately download the Dart SDK and have it in your path.

/cc @johnpryan @RedBrogdon

**Comment by parlough** [comment]
This has been fixed with the rearchitecture which uses the `dart` and `flutter` tools instead of `pub` directly.

Primarily:
https://github.com/flutter/website/blob/main/Dockerfile#L62
