### ISSUE TITLE
Fix duplication of setting PATH on 'macOS install' page

### ISSUE THREAD

**Issue by MuhammadimYusoff** [flutter/website#4878]
Page URL: https://docs.flutter.dev/get-started/install/macos
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Description of issue:

Guys please, at this section:
https://flutter.dev/docs/get-started/install/macos#update-your-path

Number/Step 3, why do I need to include "/flutter/bin"?
FUCKING WORKING AFTER I HAVE REMOVE IT! REMOVE IT!

Please, edit this page, I have been in HELL figuring out what the fuck is wrong with the path you guys given!

Regards.

**Comment by sfshaza2** [comment]
@MuhammadimYusoff, can you provide your actual path? And what platform/version are you using? These instructions work for me, so I would like to narrow it down.

**Comment by atsansone** [comment]
This results from having already set the PATH in Step 3 of https://docs.flutter.dev/get-started/install/macos#get-sdk. As that was already set, this section addition caused an issue. We will refactor this to fix the issue.

**Comment by sfshaza2** [comment]
Actually, the instructions are correct. However, I've updated the text to (hopefully) make it more clear. The first time, it tells you how to update the path for the current terminal session. But when you open a new terminal session, the path reverts to the previous value. The second set of instructions (in Update your path), explain how to permanently update the path.

**Comment by atsansone** [comment]
Step 3 could use `echo $PATH` with a result after it to make it clear what the user should see. This would be consistent with GAR requirements.

Something like:

```terminal
$ export PATH="$PATH:`pwd`/flutter/bin"
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/user/development/flutter/bin:/home/user/development/dart-sdk/bin:/snap/bin
```
