### ISSUE TITLE
Flutter tutorial Building beautiful UIs with Flutter - Step 4

### ISSUE THREAD

**Issue by harrybou** [flutter/website#4881]
In section 5 Add a UI for composing messages/Add a responsive Send button/Wrap the TextField inside a Flexible: the instruction says Select Row.  But, to reproduce the code following it seems that you have to select TextField.
So, I suspect that either the first line is incorrect or the following code is incorrect.

**Comment by parlough** [comment]
This codelab has been replaced by [Take your Flutter app from boring to beautiful](https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful). 

I'll close this as the original codelab referenced here is no longer available. Thanks for opening an issue!
