### ISSUE TITLE
Flutter web: Named route in stateful widget keeps changing

### ISSUE THREAD

**Issue by Gbolly007** [flutter/website#4894]
In my Flutter web project, I happen to use Named routes for navigations. For pages that are stateless widget, the url contains the name of the route but for pages that are stateful widget, the name of the route is shown for few seconds alongside the url when the user navigates to the page after this, it removes the name of the route from the url. Does anyone have an idea what could be wrong, I have been battling the issue for two days and I have tried different solutions such as using plugins but still no changes.

**Comment by sfshaza2** [comment]
@Gbolly007, hi! I'm sorry to hear you are having frustrations with named routes. Unfortunately, this is not a place to get support. Can you direct it to one of the channels listed on our [community page](https://flutter.dev/community)?  If you find an error or missing info in the flutter.dev site, file that here. If you find an error in the SDK's behavior, file that on the flutter/flutter repo.

Good luck! I don't know the answer to your question or I'd help.

**Comment by Gbolly007** [comment]
Thank you very much
