### ISSUE TITLE
'Display a snackbar' page requires an update

### ISSUE THREAD

**Issue by ramanathanp** [flutter/website#4920]
[Display a snackbar](https://flutter.dev/docs/cookbook/design/snackbars) page needs to be updated because `Scaffold.of(context).showSnackBar()` method is deprecated and instead `ScaffoldMessenger.of(context).showSnackBar()` must be used.

P.S. - Thanks to Flutter team for maintaining a wonderful UI framework.

**Comment by piedcipher** [comment]
I think this one is fixed. Good to close?

**Comment by parlough** [comment]
Fixed by https://github.com/flutter/website/pull/5386. Thanks again for reporting this!
