### ISSUE TITLE
'Upgrading Flutter' page issue

### ISSUE THREAD

**Issue by miniBloq** [flutter/website#4935]
Page URL: https://flutter.dev/docs/development/tools/sdk/upgrading.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/upgrading.md

Description of issue: Tried the `flutter version` command and did not work. Plus, `flutter -h` seems to do not list it anymore.

**Comment by micpap25** [comment]
Yep, `flutter version` is outdated. I'll update it to the modern equivalent `flutter --version`.
