### ISSUE TITLE
'Flutter documentation' page issue

### ISSUE THREAD

**Issue by giapdong** [flutter/website#4939]
![Screenshot_20201031-230114](https://user-images.githubusercontent.com/43102628/97783874-19cc5800-1bcd-11eb-8cb6-f0679c23e8fa.png)
Page URL: https://flutter.dev/docs/
Page source: https://github.com/flutter/website/tree/master/src/docs/index.md

When i try access to document via Chrome latest version and have bad UI for it. Please fix it!

**Comment by sfshaza2** [comment]
@giapdong, can you be more specific? I just tried every video link on that page and it works fine for me. I'm also on the latest Chrome.

**Comment by cazci** [comment]
Hi, I guess he's referring to the mobile view UI. The two videos **how is flutter different for app development** and **how stateful widgets are used best** don't auto-scale to the media width, Thanks :)

**Comment by cazci** [comment]
Please ignore the 1st PR (closed one), I updated the file directly within the browser and accidentally made a PR to my forked repo
