### ISSUE TITLE
Provide guidance on alternative to  ‘Android Studio Setup Wizard’ on 'Windows install' page

### ISSUE THREAD

**Issue by waded** [flutter/website#4941]
Page URL: https://docs.flutter.dev/get-started/install/windows
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue: This page suggests there are two steps to installing Android Studio to provide Android platform dependencies: 1) download and install Studio and then 2) "Start Android Studio, and go through the ‘Android Studio Setup Wizard’"

I've downloaded and installed Android Studio 4.1, and IIRC 3.3. before it, and couldn't figure out how to get to anything called "Setup Wizard" as a discrete step. I didn't see it as an option on the "Welcome to Android Studio" screen, for example.  Can this Windows install page be more specific as to where to go? It seems just installing Android Studio is not enough, as `flutter doctor` still points me back to the Windows install page:

![image](https://user-images.githubusercontent.com/1535656/97817864-411e3600-1c5c-11eb-9029-0c584d20eaa3.png)

**Comment by waded** [comment]
(It appears in my case I had SDK 28 installed, and older BuildTools, probably from prior install of Android Studio. If there is something called "Setup Wizard" that's supposed to trigger on its own, perhaps that's why it didn't. Perhaps, then it would be helpful here to mention that Configure->SDK Manager can be used from the "Welcome to Android Studio" screen in case "Setup Wizard" doesn't trigger. I'm quite familiar with SDK Manager... I knew what to do... but perhaps others would fall through the cracks here, expecting to see a way to get to "Setup Wizard", which is why I filed the bug.)

**Comment by sfshaza2** [comment]
Sorry for the confusion! Yup, this makes sense.
