### ISSUE TITLE
Show platform support status overview

### ISSUE THREAD

**Issue by KotlinIsland** [flutter/website#4950]
It would be useful to view platform support status, I would expect to see:
- platform support: iOS, Android, web etc
- support level: experimental, alpha, ... stable
- supported version: Minimum android sdk, maximum android sdk

**Comment by sfshaza2** [comment]
I like this idea, though it might be a real pain to keep up to date.

**Comment by atsansone** [comment]
This was added in https://github.com/flutter/website/pull/5180. Closing this issue.
