### ISSUE TITLE
'Books about Flutter' page issue -

### ISSUE THREAD

**Issue by Sun3** [flutter/website#4951]
Page URL: https://flutter.dev/docs/resources/books.html
Page source: https://github.com/flutter/website/tree/master/src/docs/resources/books.md

Description of issue: 
I noticed that all of the books are in Alphabetical order except for the book Flutter Complete Reference which has been placed in first place for better exposure. Why was this decision made and why is that book more important than the other books, why does it receive special favor? It does not seem fair or right. It needs to be corrected and placed in the correct Alphabetical order to be fair to everyone else.

Thank you.

**Comment by sfshaza2** [comment]
I agree, @Sun3. Feel free to submit a PR to fix it.

**Comment by Sun3** [comment]
I created the PR [4963](https://github.com/flutter/website/pull/4963)

Thanks.

**Comment by sfshaza2** [comment]
Fixed by PR 4963.
