### ISSUE TITLE
Slack Community Link doesn't work 

### ISSUE THREAD

**Issue by FlutterTutorial** [flutter/website#4952]
On this page: https://flutter.dev/community

There's a "Learn more" link that takes you to the slack community page.

href="https://fluttercommunity.dev/joinslack"
which redirects to: https://fluttercommunity.slack.com/join/shared_invite/<some_really_long_code>

Unfortunately, it looks like this is a short term link. Visiting the URL routes you to an error page that says "This invite link is no longer active. Please check with the person who shared it with you to see if there's a new link available."

**Comment by sfshaza2** [comment]
@filiph, you provided me with the correct link last time. Who can update this?

**Comment by slightfoot** [comment]
Link has been renewed: https://fluttercommunity.dev/joinslack will now work.
Slack expires the links after 30 days now, and after X people use it.

I am looking into an automated solution so we can renew the invite link every 2 weeks.

**Comment by RedBrogdon** [comment]
I'm no longer getting an expired invite notification when clicking on the link in flutter.dev/community, so this is fixed AFAICT.

Thanks for the help, Simon!
