### ISSUE TITLE
Add loading images from file on 'Adding assets and images' page with best practices

### ISSUE THREAD

**Issue by omatt** [flutter/website#4958]
Page URL: https://docs.flutter.dev/ui/assets-and-images
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/assets-and-images.md

Provide official guide on loading images from device storage with best practices.

**Comment by sfshaza2** [comment]
@omatt, can you give me an example of what you are looking for?

**Comment by omatt** [comment]
I've tried creating an app that imitates an image gallery using `Image.file()` and `GridView`. The app works fine when only few images are displayed, but I'm getting out of memory errors if I'm trying to display a lot i.e. > 100 images

When I've checked the [image_picker](https://pub.dev/packages/image_picker) plugin, fetching of images seems to be done on their native platforms. I'm curious if displaying tons of images from storage can be done using Flutter.

**Comment by johnpryan** [comment]
> I'm curious if displaying tons of images from storage can be done using Flutter.

That's an interesting question, I think this could be done by combining [Read and write files](https://flutter.dev/docs/cookbook/persistence/reading-writing-files) guide along with the [Image.file](https://api.flutter.dev/flutter/widgets/Image/Image.file.html) constructor.

**Comment by atsansone** [comment]
@johnpryan : Would you have an example I could use to update this page per this request?

**Comment by johnpryan** [comment]
I don't have any sample code, @omatt were you able to figure this out?
