### ISSUE TITLE
Stop posting on medium

### ISSUE THREAD

**Issue by jpkontreras** [flutter/website#4964]
Hi FlutterTeam 
Im learning the new navigator in this page https://flutter.dev/docs/development/ui/navigation, which has this link https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade  
The issue is that medium implemented a paywall and devs cant see the content of the new navigator api

How can we devs learn about the new features if theres a paywall ? 
Is this a planned decision ?

Thx

**Comment by sfshaza2** [comment]
And just to be clear. ALL of the content posted on the Flutter publication on Medium is free, and not behind the metered paywall.

**Comment by jpkontreras** [comment]
then how do you explain images not loading 

<img width="723" alt="Captura de Pantalla 2020-11-06 a la(s) 12 40 58" src="https://user-images.githubusercontent.com/7862089/98385117-6381cc00-202d-11eb-968b-5180935a7508.png">
<img width="727" alt="Captura de Pantalla 2020-11-06 a la(s) 12 41 02" src="https://user-images.githubusercontent.com/7862089/98385123-65e42600-202d-11eb-803d-e0d5531a3608.png">
<img width="745" alt="Captura de Pantalla 2020-11-06 a la(s) 12 41 09" src="https://user-images.githubusercontent.com/7862089/98385128-667cbc80-202d-11eb-85f0-7e2fefdfd0a6.png">

**Comment by sfshaza2** [comment]
@jpkontreras, images not loading is a different issue than the paywall. If it were behind the paywall, and you'd reached your limit of 3 free articles for the month, it would invite you to subscribe.

@johnpryan, any idea why your images aren't loading? I can see them, even when I open in an incognito window.

**Comment by johnpryan** [comment]
@jpkontreras Can you check which browser you are using and whether you're using an ad blocker?  The page is working for me.

**Comment by johnpryan** [comment]
The images are hosted on Medium, so I'm not sure why they wouldn't be working.

**Comment by jpkontreras** [comment]
> @jpkontreras Can you check which browser you are using and whether you're using an ad blocker?  The page is working for me.

Chrome latest versión 
Im using adblocker

**Comment by sfshaza2** [comment]
Maybe turn adblocker off? Or try another browser that doesn't have an adblocker?

**Comment by jpkontreras** [comment]
Solvencia
