### ISSUE TITLE
'Test drive' page issue

### ISSUE THREAD

**Issue by bibhas2** [flutter/website#4968]
Page URL: https://flutter.dev/docs/get-started/test-drive?tab=vscode
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Description of issue:

In **Run the app** section, a iOS Simulator must be running for it to show up in the VS Code status bar. So this needs to be started prior using the command:

```
open -a Simulator
```

Also "click No Devices and launch a simulator" is misleading. If you click **No Devices** the only option shown is to create an Android simulator.

**Comment by JuYeong0413** [comment]
> Also "click No Devices and launch a simulator" is misleading. If you click No Devices the only option shown is to create an Android simulator.

For me, when I click **No Device** at the bottom, three options are shown:
<img width="615" alt="Screen Shot 2020-11-09 at 2 32 43 AM" src="https://user-images.githubusercontent.com/33684401/98472076-e5dbdd00-2233-11eb-85f4-a30ddfe47fc4.png">
The second one(Pixel 2 API 28) is the latest Android simulator I used, and I see both **Create Android emulator** and **Start iOS simulator**.

**Comment by aadarshadhakalg** [comment]
Hopefully, #5132  fixes this
