### ISSUE TITLE
Website not loading

### ISSUE THREAD

**Issue by yahu1031** [flutter/website#4970]
I have good internet connection. IDK why I can't load only flutter website [Flutter](https://flutter.dev) and also [API Docs](https://api.flutter.dev/).

Here are some images I can provide regarding the issue

* **Image 1**
  This shows the ping of the website and the result of my web page.
  <img src="https://cdn.discordapp.com/attachments/420324994703163404/775059357296492584/unknown.png" width=500/>

* **Image 2**
  This shows my network speed.
  <img src="https://cdn.discordapp.com/attachments/756903745241088011/775071187523993600/unknown.png" width=200/>

* **Image 3**
  This shows windows Network Diagnostics.
  <img src="https://cdn.discordapp.com/attachments/420324994703163404/775060095733858354/unknown.png" width=300/>

Please do look at this issue 😭 .

**Comment by yahu1031** [comment]
Everything related to flutter aren't opening, even [Flutterfire](https://firebase.flutter.dev/docs/overview/) too 😭 only [Pub](https://pub.dev) is working and all other flutter related things aren't working and I'm clueless.

**Comment by csor-dev** [comment]
Even I'm not able to access flutter website from past 2 or 3 days

**Comment by yahu1031** [comment]
I'm closing this cause it got resolved suddenly. @csor-dev if you still have any issue you can continue.

**Comment by csor-dev** [comment]
@yahu1031 Flutter website is working but [Flutterfire](https://firebase.flutter.dev/docs/overview/) is still not working

**Comment by csor-dev** [comment]
Oops it worked now after a long loading time(for about more than a minute). Everytime it's the same thing

**Comment by yahu1031** [comment]
Both works for me 😁

**Comment by csor-dev** [comment]
Both working fine now

**Comment by kwalrath** [comment]
This sounds like it might've been due to Firebase's issues in India. Although they still have a banner on their [dashboard](https://status.firebase.google.com/) warning about "issues to Firebase Hosting and Realtime Database from some locations in India."
