### ISSUE TITLE
Change example to use `kDebugMode` on 'Report errors to a service' page

### ISSUE THREAD

**Issue by ghenry** [flutter/website#4976]
Page URL: https://docs.flutter.dev/cookbook/maintenance/error-reporting
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/maintenance/error-reporting.md

Description of issue:

Do we need this any more as there is `kDebugMode` in `flutter/foundation.dart`

```dart
bool get isInDebugMode {
  // Assume you're in production mode.
  bool inDebugMode = false;

  // Assert expressions are only evaluated during development. They are ignored
  // in production. Therefore, this code only sets `inDebugMode` to true
  // in a development environment.
  assert(inDebugMode = true);

  return inDebugMode;
}
```

and in https://github.com/flutter/crashy/blob/cf40e4723a698010103c5aaf2b40ce8750d092a0/lib/main.dart#L50

Thanks.

**Comment by sfshaza2** [comment]
That makes sense to me!  @domesticmouse, can you take this?

**Comment by atsansone** [comment]
Consider other related issues: https://github.com/flutter/website/issues/2315 and https://github.com/flutter/website/issues/5055.

**Comment by domesticmouse** [comment]
I'm confused. The referenced `flutter/crashy` github project is a 404. And I don't see `isInDebugMode` referenced on https://docs.flutter.dev/cookbook/maintenance/error-reporting

Perchance this two year old bug report is stale?

**Comment by domesticmouse** [comment]
Closing this as stale.
