### ISSUE TITLE
Verify that template file is created per iOS FFI C Interop instructions on 'Binding to native iOS code using dart:ffi' page

### ISSUE THREAD

**Issue by krolaw** [flutter/website#4993]
As per: https://docs.flutter.dev/platform-integration/ios/c-interop

> For example, to create a C++ file named ios/Classes/native_add.cpp, use the following instructions. **(Note that the template has already created this file for you.)**

Yet:
```bash
% flutter create --platforms=android,ios --template=plugin native_add
...
% cd native_add
% ls ios/Classes
NativeAddPlugin.h               NativeAddPlugin.m               SwiftNativeAddPlugin.swift
```

**Comment by atsansone** [comment]
@stuartmorgan : Can you validate that this issue still occurs or not?

**Comment by stuartmorgan** [comment]
The template definitely does not make that file; I don't know why that line was added. Re-assigning to @dcharkes who added it.

**Comment by dcharkes** [comment]
> `--template=plugin`

This documentation is from before we introduced `--template=plugin_ffi`, which is what should be used for FFI now. So this whole docs page is outdated. I can take a stab at updating it.

**Comment by dcharkes** [comment]
I have taken a stab at updating the documentation for both iOS and Android:

* https://github.com/flutter/website/pull/8828
* https://github.com/flutter/website/pull/8829
