### ISSUE TITLE
Incorrect Android Platform View code

### ISSUE THREAD

**Issue by nwparker** [flutter/website#4996]
https://flutter.dev/docs/development/platform-integration/platform-views?tab=android-platform-views-java-tab

The documentation (Java/Kotlin) creates a new instance of the `NativeViewFactory` using the following code:
```dart
new NativeViewFactory()
```

However, `NativeViewFactory` takes 2 arguments. It's not described where/how to get these two arguments.

Further, an extra line must be called for app to function:
`GeneratedPluginRegistrant.registerWith(flutterEngine);`

The almost complete working example (from my understanding) should be this instead (Java):
```dart
package dev.flutter.example;

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
        flutterEngine
            .getPlatformViewsController()
            .getRegistry()
            .registerViewFactory("<platform-view-type>", new NativeViewFactory(flutterEngine.getDartExecutor().getBinaryMessenger(), ???));
    }
}
```
"???" inserted above since I'm unsure how to retrieve the view (and in my case, I don't happen to care 😉)

**Comment by mbcode64** [comment]
I posted corrected code at https://stackoverflow.com/questions/65207626/hosting-native-android-and-ios-views-in-your-flutter-app-with-platform-views/65264459#65264459.

You also need to call super.configureFlutterEngine(flutterEngine) in the overrided method in MainActivity.

**Comment by atsansone** [comment]
This duplicates https://github.com/flutter/website/issues/5408. Closing this issue.
