### ISSUE TITLE
Add how to use local packages in flutter to docs

### ISSUE THREAD

**Issue by zjiekai** [flutter/website#5011]
https://github.com/flutter/website/blob/master/src/docs/development/packages-and-plugins/using-packages.md

The document has information for using packages from pub.dev.  It would be great if there would be instructions about using local packages (eg. packages in local file system).

https://stackoverflow.com/q/51238420/264442

This seems to be a common scenario.

**Comment by atsansone** [comment]
@johnpryan : Is this a common scenario?

**Comment by johnpryan** [comment]
This is already covered in the [Dependencies on unpublished packages](https://github.com/flutter/website/blob/archived-master/src/docs/development/packages-and-plugins/using-packages.md#dependencies-on-unpublished-packages) section, so I think we can close this issue now.
