### ISSUE TITLE
Use the latest version of Swift and XCode in the 'Adding a Flutter screen to an iOS app' tutorial

### ISSUE THREAD

**Issue by ching7** [flutter/website#5014]
Page URL: https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/add-to-app/ios/add-flutter-screen.md

Description of issue:

In ios14, xcode12.2, Swift version 5.3.1, the code in this tutorial is no longer applicable, especially in the tutorial of embedding ios application in flutter single page. Because now ios app development uses the brand new swift5.3 syntax, but this tutorial still uses the old version of OC and swift.
Please update the latest version of the tutorial as soon as possible

**Comment by sfshaza2** [comment]
@xster, @jmagman, can you weigh in?

**Comment by xster** [comment]
What specific changes would you like to see? Did you mean having the template be based around scenes rather than just the storyboard?

**Comment by ching7** [comment]
> What specific changes would you like to see? Did you mean having the template be based around scenes rather than just the storyboard?

Yes, I hope the examples on the official website can use the latest version of swift and Xcode. If not, I hope to mark the tool version used in the tutorial

**Comment by sfshaza2** [comment]
This has been fixed. Closing.
