### ISSUE TITLE
Change API used on 'SnackBars managed by the ScaffoldMessenger' page

### ISSUE THREAD

**Issue by Klievan** [flutter/website#5018]
Page URL: https://flutter.dev/docs/release/breaking-changes/scaffold-messenger.html
Page source: https://github.com/flutter/website/tree/master/src/docs/release/breaking-changes/scaffold-messenger.md

Description of issue:
The examples uses the deprecated API Scaffold.of(context).showSnackBar()

**Comment by sfshaza2** [comment]
This will be deprecated on our next stable release. We generally document stable on flutter.dev.

**Comment by atsansone** [comment]
This was corrected in https://github.com/flutter/website/pull/4527. This page shows the change between the Widgets. Closing this issue.
