### ISSUE TITLE
Add other option to sync project on 'AndroidX Migration' page

### ISSUE THREAD

**Issue by kamleshwebtech** [flutter/website#5020]
Page URL: https://docs.flutter.dev/release/breaking-changes/androidx-migration
Page source: https://github.com/flutter/website/tree/master/src/docs/development/androidx-migration.md

Description of issue:

i am using android studio - 3.5 version but there is no "Sync Project with Gradle Files from the File menu", suggested on androidx migration google documentation page. Please suggest how can we migrate app to androidx in case of not having "Sync Project with Gradle Files from the File menu" option in android studio. Thanks a lot.

**Comment by sfshaza2** [comment]
@blasten, can you weigh in?

**Comment by atsansone** [comment]
This was fixed in https://github.com/flutter/website/pull/7246.

The option is found at https://docs.flutter.dev/release/breaking-changes/androidx-migration#what-if-i-cant-use-android-studio
