### ISSUE TITLE
'macOS install' page issue

### ISSUE THREAD

**Issue by MisterRog85** [flutter/website#5022]
Page URL: https://flutter.dev/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Description of issue: The method describing how to permanently add flutter to the path does not work ! It should show how to update the /etc/paths file instead which worked for me.

**Comment by sfshaza2** [comment]
@MisterRog85, can you tell me what platform you are using? (Including which shell.)

**Comment by MiraMarshall** [comment]
Closing because this issue has been resolved.

**Comment by sfshaza2** [comment]
@MisterRog85, you should definitely *not* need to modify /etc/paths. I see you are on a Mac, but what shell are you using? You need to update the dot file for your shell. For `bash`, for example, that's `.bashrc`. Or you might use `zsh`, which is `.zshrc`. I'm glad that /etc/paths worked for you, but it's a rather large club to use.
