### ISSUE TITLE
CupertinoSearchTextField isn't on stable yet

### ISSUE THREAD

**Issue by theswerd** [flutter/website#5025]
When clicking to view the docs for **CupertinoSearchTextField** there are none. It is also not on the current stable branch.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/38309438/100568653-9c097400-3280-11eb-9816-b8ba79f6ec76.gif)

**Comment by xster** [comment]
Sorry, it's not on stable yet. You can try the widget on the dev branch. It should roll onto stable in a few months.

**Comment by theswerd** [comment]
Thank you
