### ISSUE TITLE
Repurpose provided adaptive UI content for website

### ISSUE THREAD

**Issue by csells** [flutter/website#5029]
https://aloisdeniel.com/#/posts/adaptative-ui

**Comment by sfshaza2** [comment]
Doesn't this imply that the website uses Flutter? (Which it doesn't.)

**Comment by sfshaza2** [comment]
The adaptive docs have been completely rewritten for the Q3 2024 release. Closing this.

**Comment by csells** [comment]
now I'm super curious; are [these](CITY OF KING CITY, 15300 SW 116TH AVE KING CITY, OR 97224) the new docs?

**Comment by sfshaza2** [comment]
@csells, ???

**Comment by csells** [comment]
ha. apparently I had the wrong thing in my clipboard. : )
