### ISSUE TITLE
Internationalization page feedback

### ISSUE THREAD

**Issue by asashour** [flutter/website#5032]
In [internationalization](https://flutter.dev/docs/development/accessibility-and-localization/internationalization), there are two hints:

1. `#6`

        To test the localization tool, run your application. You should see generated files in ${FLUTTER_PROJECT}/flutter_gen/gen_l10n.

  should be in ${FLUTTER_PROJECT}/`.dart_tool`/flutter_gen/gen_l10n instead

2. One must add 

          localizationsDelegates: [
            AppLocalizations.delegate, // add this

**Comment by sfshaza2** [comment]
The second issue was fixed by #5051...

**Comment by asashour** [comment]
Thanks for feedback. Windows 10.

**Comment by Roshan13046** [comment]
> The second issue was fixed by #5051... The first issue needs verification on different platforms. What platform are you on @asashour?

I would like to work on this issue.

**Comment by sfshaza2** [comment]
Go for it!

**Comment by MrBirb** [comment]
@sfshaza2 This looks like it has been fixed.

**Comment by sfshaza2** [comment]
Thanks! Closing.
