### ISSUE TITLE
Add information about const Widget() into Rendering best practices

### ISSUE THREAD

**Issue by nstrelow** [flutter/website#5054]
#### Especially in Widget trees, where additional `const` keywords can make it harder to read the code.

Are there already docs I cannot find? The [Flutter Performance best practices](https://flutter.dev/docs/perf/rendering/best-practices) does not mention `const`.

Defining `const` helps the DartVM optimizing certain parts of the code. In a constant context `const` is implicit and the keyword `const` does not have to be used. (https://dart.dev/dart-2)

There are multiple linters helping adding const:

- http://dart-lang.github.io/linter/lints/prefer_const_constructors.html
- http://dart-lang.github.io/linter/lints/prefer_const_declarations.html
- http://dart-lang.github.io/linter/lints/prefer_const_literals_to_create_immutables.html

And removing const, when the DartVM knows the context is constant:

- http://dart-lang.github.io/linter/lints/unnecessary_const.html

In the [chewie codebase](https://github.com/brianegan/chewie) there are 105 places the lint `prefer_const_constructors` detects `const` could be used since the DartVM cannot assume it is a constant context.

Searching for input on this there are different claims about when to use and not, probably also due to some changes along the way.

[Here](https://stackoverflow.com/questions/53492705/does-using-const-in-the-widget-tree-improve-performance/62825321#62825321) one person conducted a test and saw differences in how often the garbage collector runs.

https://github.com/passsy/dart-lint/issues/22: Issue where I (probably wrongly) questioned using the `prefer_const_constructors`.

#### What I am missing is at what point it is clearly recommended to use `const` for performance reason and at what point is it just premature optimization?

**Comment by filiph** [comment]
Sorry this took so long. I agree with the plan to put a bullet point into https://flutter.dev/docs/perf/rendering/best-practices#controlling-build-cost.

Pull requests welcome! Otherwise, I'll get to it as soon as possible.

**Comment by atsansone** [comment]
This is in the [best practices](https://docs.flutter.dev/perf/best-practices#control-build-cost) now., fixed in https://github.com/flutter/website/pull/6977.
