### ISSUE TITLE
'Install' page issue

### ISSUE THREAD

**Issue by orbit88** [flutter/website#5059]
Page URL: https://flutter.dev/docs/get-started/install/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/index.md

Description of issue:

**Comment by orbit88** [comment]
Sighted bug upon installing``

**Comment by sfshaza2** [comment]
Sighted bug? Can you explain what this means?

**Comment by sfshaza2** [comment]
No additional info. Closing. If you have additional info, please reopen and provide it here.
