### ISSUE TITLE
change package:integration_test imports to use SDK imports when added to the SDK

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#5060]
The `integration_test` will soon be part of the SDK, so `pubpsec.yaml` files importing it as a Pub package should use an SDK import instead. See [this comment](https://github.com/flutter/website/pull/5050#discussion_r537891839) for an example.

**Comment by johnpryan** [comment]
This is just waiting to land in the stable channel

**Comment by atsansone** [comment]
Displayed as fixed on the [correct page](https://docs.flutter.dev/testing/integration-tests). Closing this issue.
