### ISSUE TITLE
[i18n] Documentation issues with "adding your own localizations" section

### ISSUE THREAD

**Issue by drekka** [flutter/website#5062]
Page URL: https://flutter.dev/docs/development/accessibility-and-localization/internationalization.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

Description of issue:

Hi guys, I've been trying to follow this page for several days and it appears that the Intl package no longer works as described in this page. Specifically, it no longer generates any files to support internationalisation as described.

**Comment by sfshaza2** [comment]
@shihaohong, have these changes reached stable?

**Comment by drekka** [comment]
Actually can close this. It turns out that the Flutter docs are out of date and the files are actually generated into the `.dart_tool/flutter_gen/gen_l10n` directory.

**Comment by shihaohong** [comment]
Hey @drekka, sorry about the delay with getting back to this. Could you share which part of the Flutter docs are out of date? I'd like to go and sort that out if that's still a problem. If it's something we can fix on the framework side of things, file an issue at [flutter/flutter](https://github.com/flutter/flutter/issues/new/choose) and cc/ me in on it!

**Comment by drekka** [comment]
A couple of places on https://flutter.dev/docs/development/accessibility-and-localization/internationalization

First, second code example under setup which looks like this:

```dart
import 'package:flutter_localizations/flutter_localizations.dart';

// ...

MaterialApp(
 localizationsDelegates: [
   // ... app-specific localization delegate[s] here
   AppLocalizations.delegate,
   GlobalMaterialLocalizations.delegate,
   GlobalWidgetsLocalizations.delegate,
   GlobalCupertinoLocalizations.delegate,
 ],
 supportedLocales: [
    const Locale('en', ''), // English, no country code
    const Locale('ar', ''), // Arabic, no country code
    const Locale.fromSubtags(languageCode: 'zh'), // Chinese *See Advanced Locales below*
    // ... other locales the app supports
  ],
  // ...
)
```

Should be something like this:

```dart
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

// ...

@override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      onGenerateTitle: (context) => AppLocalizations.of(context).#localised-app-key#,
      home: // ...
      );
  }
```

Basically to import the generated flutter package and use it's prebuilt arrays which include all the entries in the original code plus the generated localisation code. Also A good idea (I think) to include the `onGenerateTitle` as I had to hunt around for that one.

Next in step 6 of adding the localisation to your app it mentions `${FLUTTER_PROJECT}/flutter_gen/gen_l10n` as the directory where the files are generated into. It's now changed to `${FLUTTER_PROJECT}/.dart_tool/flutter_gen/gen_l10n`. That had be going for a while thinking it wasn't working.

Finally in step 7 it indicates to import `'package:flutter_localizations/flutter_localizations.dart';` as well as `'package:flutter_gen/gen_l10n/app_localizations.dart';`. I've not found that to be necessary.

**Comment by drekka** [comment]
Oh, one last thing. The bottom of the dock talks about the `intl_translation` package for reading and writing to *.arb files. I'm using intl 0.17.0-nullsafety.2 and `flutter pub get` throughs version conflicts if I try to include `intl_translation`. As the language darts files are being generated without it, I'm assuming it's no longer needed? Which would possibly change that whole section?

**Comment by sfshaza2** [comment]
Thanks so much for this additional info, @drekka!

**Comment by drekka** [comment]
And it just keeps on giving ... :-) I've realised that some material widgets aren't honouring the locale (looking at date picker for example - known issue) so it looks like there needs to be some additional code in the material app setup in the `localeListResolutionCallback: (locales, supportedLocales) {...}` argument. Still looking at this and trying to understand what needs to be done.

**Comment by shihaohong** [comment]
I'll try to address these bit by bit: 

> First, second code example under setup which looks like this:
```dart
import 'package:flutter_localizations/flutter_localizations.dart';

// ...

MaterialApp(
 localizationsDelegates: [
   // ... app-specific localization delegate[s] here
   AppLocalizations.delegate,
   GlobalMaterialLocalizations.delegate,
   GlobalWidgetsLocalizations.delegate,
   GlobalCupertinoLocalizations.delegate,
 ],
 supportedLocales: [
    const Locale('en', ''), // English, no country code
    const Locale('ar', ''), // Arabic, no country code
    const Locale.fromSubtags(languageCode: 'zh'), // Chinese *See Advanced Locales below*
    // ... other locales the app supports
  ],
  // ...
)
```
> Should be something like this:
```dart
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

// ...

@override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      onGenerateTitle: (context) => AppLocalizations.of(context).#localised-app-key#,
      home: // ...
      );
  }
```
> Basically to import the generated flutter package and use it's prebuilt arrays which include all the entries in the original code plus the generated localisation code. Also A good idea (I think) to include the onGenerateTitle as I had to hunt around for that one.

Nice! Thanks for catching these, I'll address them in an upcoming PR.

> Next in step 6 of adding the localization to your app it mentions ${FLUTTER_PROJECT}/flutter_gen/gen_l10n as the directory where the files are generated into. It's now changed to ${FLUTTER_PROJECT}/.dart_tool/flutter_gen/gen_l10n. That had be going for a while thinking it wasn't working.

Looks like this was already fixed :)

> Finally in step 7 it indicates to import 'package:flutter_localizations/flutter_localizations.dart'; as well as 'package:flutter_gen/gen_l10n/app_localizations.dart';. I've not found that to be necessary.

Ahh I see, you're right. This is because the helper supportedLocales and localizationsDelegates arrays provide these. It's only necessary if you need to make direct use of stuff like `GlobalMaterialLocalizations.delegate` in the app. I'll remove this line as well.

> I've realised that some material widgets aren't honouring the locale (looking at date picker for example - known issue) so it looks like there needs to be some additional code in the material app setup in the localeListResolutionCallback: (locales, supportedLocales) {...} argument. Still looking at this and trying to understand what needs to be done.

For this one, once you have more information about the issue, could you file an issue to flutter/flutter? That seems more like a framework bug than requiring you to do work to get that working. Thank you! 

All in all, thanks for being so detailed with your report. I'll submit a PR shortly for the website fixes that need to be made.
