### ISSUE TITLE
Add HTMLElementView page + sample

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#5063]
One of the [solutions for resolving CORS issues](https://github.com/flutter/website/pull/5061) with images is to use an HTMLElementView. We currently don't have any sample code for using it. 

https://api.flutter.dev/flutter/widgets/HtmlElementView-class.html

[this issue + comment](https://github.com/flutter/flutter/issues/71619#issuecomment-740810200) has a sample that uses an ImageElement to display an image with the Google Books API to work around CORS issues with the CanvasKit renderer

**Comment by atsansone** [comment]
Add this information to this section: https://docs.flutter.dev/platform-integration/web/web-images#cross-origin-images

**Comment by feinstein** [comment]
A page about `HtmlElementView` should also explain how it can be used to embed normal websites inside Flutter, not only for images.

**Comment by ditman** [comment]
A bunch of new documentation has just landed in the `main` branch API docs:

* https://main-api.flutter.dev/flutter/widgets/HtmlElementView-class.html

**Comment by johnpryan** [comment]
Now that we have docs for HtmlElementView I think we can close this. It doesn't seem to be the best solution for fixing CORS issues for Flutter apps.
