### ISSUE TITLE
'Return data from a screen' page issue

### ISSUE THREAD

**Issue by 349989153** [flutter/website#5074]
Page URL: https://flutter.dev/docs/cookbook/navigation/returning-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/returning-data.md

Description of issue:
I try to follow the guide but get the error: `The method 'ElevatedButton' isn't defined for the type 'SelectionButton'`.

And the version is :
```
flutter --version
Flutter 1.17.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8af6b2f038 (5 months ago) • 2020-06-30 12:53:55 -0700
Engine • revision ee76268252
Tools • Dart 2.8.4
```

So I do some extra search and find that **To use ElevatedButton without warnings or errors, you should update to Flutter 1.22.0 or newer versions. The simplest way to do that is to run this command: flutter upgrade**

**But what really bother me is I can't get that impotant INFO ABOUT VERSION on either https://api.flutter.dev/flutter/material/ElevatedButton-class.html or https://flutter.dev/docs/cookbook/navigation/returning-data, I think it's not convenient for developers. Can you optimize the doc, please?**

**Comment by VarunSAthreya** [comment]
If the issue is still open I would like to work on it.
