### ISSUE TITLE
Update 'Simple app state management' page for consistency

### ISSUE THREAD

**Issue by noamraph** [flutter/website#5076]
Page URL: https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/state-mgmt/simple.md

Description of issue:

I suggest to update the page to use context.watch<>(). This is what the example is using, and it's much easier than creating another widget.

**Comment by Roshan13046** [comment]
> context.watch

Can you please describe more about this issue on what exact changes are needed?
I am a new contributor.

**Comment by noamraph** [comment]
@Roshan13046 I think that if you are a new contributor, you should not document areas that you are not familiar with.

**Comment by Roshan13046** [comment]
> @Roshan13046 I think that if you are a new contributor, you should not document areas that you are not familiar with.

But, if you suggest me the edits I can do it properly. 
Please, suggest the required changes.

**Comment by noamraph** [comment]
I'm sorry, I don't have time to suggest the edits. I notified about the
document needing an update. Those who are familiar with the matter should
know how to fix it.

Thanks,
Noam

**Comment by atsansone** [comment]
This page has since been updated and no longer uses `context.watch`. Closing this issue.
