### ISSUE TITLE
Add a link to the r/FlutterDev discord in the Contributing page

### ISSUE THREAD

**Issue by micpap25** [flutter/website#5083]
If it's possible, we could add this link for even easier access to the community Discord.

**Comment by sfshaza2** [comment]
I'm definitely ok with that.

**Comment by Roshan13046** [comment]
> I'm definitely ok with that.

I would like to work on this issue.

**Comment by micpap25** [comment]
My PR that you referenced linked to the current community page on the Flutter website. This PR is referring to the r/FlutterDev discord server.
