### ISSUE TITLE
byType is not a valid method

### ISSUE THREAD

**Issue by elcolie** [flutter/website#5084]
https://codelabs.developers.google.com/codelabs/flutter-app-testing/#6
`  final listFinder = find.byType('ListView');`

![image](https://user-images.githubusercontent.com/18206728/102014443-8ae45b00-3d88-11eb-914e-3ff4c679bbc3.png)

I can't find `byType` method

**Comment by sfshaza2** [comment]
Hi @elcolie! This is not a good place for getting support. For that, check out the various venues on our [community page](https://flutter.dev/community). But I did find this:  https://api.flutter.dev/flutter/flutter_test/CommonFinders/byType.html
