### ISSUE TITLE
Icons.close is not shown in the app, but it can be tested

### ISSUE THREAD

**Issue by elcolie** [flutter/website#5085]
I don't see `Icons.close` in the emulator.

```dart
      var totalItems = tester.widgetList(find.byIcon(Icons.close)).length;
```
https://codelabs.developers.google.com/codelabs/flutter-app-testing/#5

**Comment by sfshaza2** [comment]
I believe this codelab needs updating now that the integration_test package is available.  @domesticmouse

**Comment by elcolie** [comment]
I looked on the wrong app page. What a newbie 🤦🏻‍♂️
