### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by JieBin-Li** [flutter/website#5101]
Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out,
errno = 60, address = clients2.google.com, port = 51611
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot open file, path =
'/Users/jayj/flutter_dome/flutter_app01/android/local.properties' (OS Error: Permission denied,
errno = 13)".
 
A crash report has been written to                               
/var/folders/5v/y8n9d0rx4q321bj7cz2mq22w0000gn/T/flutter_tools.nrSgIb/flutter_01.log.

**Comment by sfshaza2** [comment]
@JieBin-Li, this is not the place to file an issue like this. You can create an issue on the flutter/flutter repo, but it will need more explanation and a reproducible case. Thx
