### ISSUE TITLE
How can I be notified that the local notification has been sent?

### ISSUE THREAD

**Issue by draxex** [flutter/website#5103]
Hi,

I am using flutter_local_notifications to send users notifications. In my application, there is only one button, when people click it, they can set an alarm for a specific time.  At the same time, if the alarm has been set, the button text will be "cancel alarm" and the user can cancel the alarm by clicking on it.

My problem is how can I know when the alarm has been sent while the application screen is on. I want to turn the "cancel alarm" text to "create an alarm" again, while that screen is on and at the same time the alarm has been sent.

Is there any notification sent listener? Thanks.

**Comment by sfshaza2** [comment]
Hi, @draxex! This is not the place to get support. Please refer to one of the avenues on the Flutter [community page](https://flutter.dev/community).
