### ISSUE TITLE
Update tutorial on 'Take a picture using the camera' page

### ISSUE THREAD

**Issue by devabhishekpal** [flutter/website#5109]
Page URL: https://flutter.dev/docs/cookbook/plugins/picture-using-camera.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/plugins/picture-using-camera.md

Description of issue:

I think the tutorial isn't updated with the latest version of the Camera Plugin, since the _controller.takePicture(path) gives an error for **path** argument telling that it takes 0 arguments. Also there have been a few changes in the newer version.
Kindly do check.

**Comment by sfshaza2** [comment]
@johnpryan, can you check or delegate?

**Comment by johnpryan** [comment]
This is correct, [`takePicture`](https://pub.dev/documentation/camera/latest/camera/CameraController/takePicture.html) no longer takes a path, so this needs to be fixed.

**Comment by VarunSAthreya** [comment]
If the issue is still open I would like to work on it.

**Comment by piedcipher** [comment]
Docs are already fixed! Good to close?

**Comment by atsansone** [comment]
Fixed. Closing.
