### ISSUE TITLE
Change phrasing for 'Configure signing in gradle' on 'Build and release an Android app' page

### ISSUE THREAD

**Issue by Bookie164** [flutter/website#5110]
Page URL: https://docs.flutter.dev/deployment/android#configure-signing-in-gradle
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/android.md

Description of issue:
This page used to show how to configure Gradle by showing two code blocks. One code block would replace another so the usage of replace "code1" with "code2" was ok. Like in the attached screenshot.
<img width="778" alt="Screenshot 2020-12-19 at 12 02 32 PM" src="https://user-images.githubusercontent.com/47698050/102682781-1e3ae780-41f2-11eb-9aaf-21674f9d2eed.png">

Now it tells you to add code instead of replace yet in the second code block it reads as if you are replacing the initial code. It's a minor change but replace...with makes sense add...with does not. Makes for better readability.

**Comment by atsansone** [comment]
Investigate at the same time as https://github.com/flutter/website/issues/5110.
