### ISSUE TITLE
java.lang.NoClassDefFoundError: Class not found using the boot class loader

### ISSUE THREAD

**Issue by AkshayDilod** [flutter/website#5116]
Launching lib\main.dart on YU5010A in debug mode...
lib\main.dart:1
Parameter format not correct -
**√ Built build\app\outputs\flutter-apk\app-debug.apk.**
E/AndroidRuntime(20267): FATAL EXCEPTION: main
E/AndroidRuntime(20267): Process: com.example.fluttertest, PID: 20267
E/AndroidRuntime(20267): java.lang.RuntimeException: Unable to instantiate application android.support.multidex.MultiDexApplication.FlutterApplication: java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication.FlutterApplication" on path: DexPathList[[zip file "/data/app/com.example.fluttertest-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.fluttertest-2/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(20267): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:563)
E/AndroidRuntime(20267): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4540)
E/AndroidRuntime(20267): 	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
E/AndroidRuntime(20267): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)
E/AndroidRuntime(20267): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(20267): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(20267): 	at android.app.ActivityThread.main(ActivityThread.java:5268)
E/AndroidRuntime(20267): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20267): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(20267): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
E/AndroidRuntime(20267): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
E/AndroidRuntime(20267): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.multidex.MultiDexApplication.FlutterApplication" on path: DexPathList[[zip file "/data/app/com.example.fluttertest-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.fluttertest-2/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(20267): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(20267): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(20267): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(20267): 	at android.app.Instrumentation.newApplication(Instrumentation.java:980)
E/AndroidRuntime(20267): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
E/AndroidRuntime(20267): 	... 10 more
E/AndroidRuntime(20267): 	Suppressed: java.lang.ClassNotFoundException: android.support.multidex.MultiDexApplication.FlutterApplication
E/AndroidRuntime(20267): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(20267): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(20267): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)

`<manifest 
> xmlns:android="http://schemas.android.com/apk/res/android"

    package="com.example.fluttertest">
    
    <application
        android:name="android.support.multidex.MultiDexApplication"
        android:label="fluttertest"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
              <meta-data
                android:name="com.google.firebase.messaging.default_notification_channel_id"
                android:value="default_channel_id"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>`

gradle.properties

org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true

app/build.gradle

......
 defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.fluttertest"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }
......
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3'
    //implementation 'androidx.multidex:multidex:2.0.1'
}

nothing shows on the device
Gradle version 4.0.1
Gradle-6.1.1-all-zip.

**Comment by sfshaza2** [comment]
@AkshayDilod, this is not the venue for support. Please refer to one of the avenues listed on the Flutter [community page](https://flutter.dev/community).
