### ISSUE TITLE
'Integration testing' page issue

### ISSUE THREAD

**Issue by zmeggyesi** [flutter/website#5128]
Page URL: https://flutter.dev/docs/testing/integration-tests/
Page source: https://github.com/flutter/website/tree/master/src/docs/testing/integration-tests/index.md

Description of issue:

I'm trying to follow the instructions to migrating away from using `flutter_driver` directly, in favor of using `integration_test`, as well as running my tests on Firebase Test Lab.

While running on a physical device using `flutter drive  --driver=test_driver/integration_test.dart  --target=integration_test/foo_test.dart` works just fine, running on Firebase Test Lab "hangs", then passes (actually, it times out) without running any of the test cases. The logs show this is because Driver cannot connect to the application running on the device:

```
12-24 14:32:09.187: E/flutter(25870): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: DriverError: Could not determine URL to connect to application.
12-24 14:32:09.187: E/flutter(25870): Either the VM_SERVICE_URL environment variable should be set, or an explicit URL should be provided to the FlutterDriver.connect() method.
12-24 14:32:09.187: E/flutter(25870): #0      VMServiceFlutterDriver.connect (package:flutter_driver/src/driver/vmservice_driver.dart:86:7)
12-24 14:32:09.187: E/flutter(25870): #1      FlutterDriver.connect (package:flutter_driver/src/driver/driver.dart:157:35)
12-24 14:32:09.187: E/flutter(25870): #2      integrationDriver (package:integration_test/integration_test_driver.dart:70:52)
```

Since the VM Observatory URL usually includes an auth token, I'm not sure how I could wire this up ahead-of-time, no knowing said token.

Any help would be appreciated, especially amending the article.

**Comment by sfshaza2** [comment]
@johnpryan, any insight?

**Comment by johnpryan** [comment]
It looks like you're running Flutter Driver on Firebase TestLab. The correct way is to upload the APKs created in the [Android Device Testing](https://pub.dev/packages/integration_test#android-device-testing) (or [iOS Device Testing](https://pub.dev/packages/integration_test#ios-device-testing)) sections of the README.

On this page we say:

> Tests written with the integration_test package can:
>
> 1. Run directly on the target device, allowing you to test on multiple Android or iOS devices using Firebase Test Lab.
> 2. Run using flutter_driver.
> 3. Use flutter_test APIs, making integration tests more like writing widget tests.

Can you add more details about what steps you are taking? Maybe there is a warning we could add to the Firebase TestLab section.

**Comment by zmeggyesi** [comment]
@johnpryan That is correct, I'm following the steps outlined [here](https://flutter.dev/docs/testing/integration-tests/) and [here](https://flutter.dev/docs/testing/integration-tests#uploading-an-android-apk). 

I'm attaching an [example `app_test.dart` file](https://github.com/flutter/website/files/5785258/test.dart.txt) here (`.txt` extension mandated by GitHub), as well as [the excerpt from my `.gitlab-ci.yml` file](https://github.com/flutter/website/files/5785257/build.yml.txt) that builds the APKs. I also tried specifying the _other_ file in the documentation, which has `Future<void> main() => integrationDriver()` as its content, but that just got stuck on the _Test starting..._ screen in Firebase, until the test timed out and was destroyed.

Let me  know if you need any additional information, I'm happy to help!

**Comment by johnpryan** [comment]
> I also tried specifying the other file in the documentation, which has Future<void> main() => integrationDriver() as its content, but that just got stuck on the Test starting... screen in Firebase, until the test timed out and was destroyed.

That's not correct - this file is meant to be run by Flutter Driver

Are you able to [run the APK](https://developer.android.com/studio/run/emulator#installadd) that was created when you ran  `flutter build apk`?

**Comment by johnpryan** [comment]
Closing until we hear back from @zmeggyesi
