### ISSUE TITLE
Camera example code doesn't pass analysis

### ISSUE THREAD

**Issue by miksen** [flutter/website#5130]
This page has a full example of using the camera plugin:
https://flutter.dev/docs/cookbook/plugins/picture-using-camera#complete-example

This code doesn't work with the most recent version of the camera plugin (`0.6.2+1`), as it doesn't pass analysis:

```
Too many positional arguments: 0 expected, but 1 found.
Try removing the extra arguments.
```

The following line is the one that triggers this:

```dart
            // Attempt to take a picture and log where it's been saved.
            await _controller.takePicture(path);
```

**Comment by miksen** [comment]
From the changelog, it appears that `takePicture` no longer takes a path:
https://pub.dev/packages/camera/changelog#060

**Comment by sfshaza2** [comment]
It appears that this cookbook recipe needs updating. PRs welcome.

**Comment by sfshaza2** [comment]
Dupe of https://github.com/flutter/website/issues/5109. Closing.
