### ISSUE TITLE
Correct text around `InkFeature` on 'Debugging Flutter apps programmatically' page

### ISSUE THREAD

**Issue by toly1994328** [flutter/website#5133]
### Page URL

https://docs.flutter.dev/testing/code-debugging

### Description

![image](https://user-images.githubusercontent.com/26687012/103164162-8cab2580-4842-11eb-9db3-45a75a130d32.png)

The `InkFeature` should be `_InkFeature`.  Because  `_InkFeature` is an implementation detail of the `Material` widget.
 
![image](https://user-images.githubusercontent.com/26687012/103164180-d431b180-4842-11eb-872f-6847497b085b.png)

`_InkFeature` is a Widget ，`InkFeature` is not ，it's just a `class`.

**Comment by sfshaza2** [comment]
@toly1994328, where is this page? Can you provide a URL?

**Comment by toly1994328** [comment]
> @toly1994328, where is this page? Can you provide a URL?

https://github.com/flutter/website/blob/master/src/docs/testing/code-debugging.md

**Comment by atsansone** [comment]
See this API doc: https://api.flutter.dev/flutter/material/InkFeature-class.html
