### ISSUE TITLE
Fix bad example on 'Work with WebSockets' page

### ISSUE THREAD

**Issue by finnjohnsen** [flutter/website#5134]
Page URL: https://flutter.dev/docs/cookbook/networking/web-sockets.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/web-sockets.md

Description of issue:
By following this example of web-sockets by copy&paste; 
- On Android Emulator I get  'Bad state: Insecure HTTP is not allowed by platform:' 
- In Chrome / flutter web I get 'Unsupported operation: Platform._version'.
- iOS I've not tested and things may work for all I know.

I'm new to flutter so I'm sorry for not contributing with solution or suggested edit to the help pages. Not sure how to fix it.

**Comment by finnjohnsen** [comment]
I made progress for Android, by changing three things:

1.
In profile/Manifest.xml I added this to <application>
            android:networkSecurityConfig="@xml/network_security_config"

2. res/xml/network_security_config.xml I added 
```
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">ngrok.io</domain>
    </domain-config>
</network-security-config>
```
3. I changed the url to begin with wss:// instead of ws://, which seemed to go back to http.

**Comment by atsansone** [comment]
This change has been made. See https://github.com/flutter/website/issues/2795. Closing.
