### ISSUE TITLE
Update example with correct filename on 'Integration testing' page

### ISSUE THREAD

**Issue by Rob-Pitt** [flutter/website#5137]
https://docs.flutter.dev/testing/integration-tests#running-in-a-browser

**Says:**

Create file test_driver/integration_test_driver.dart

**But then says:**

```terminal
flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/foo_test.dart \
  -d <DEVICE_ID>
```
This runs the tests in foo_test.dart via the adapter in test_driver/integration_test.dart.

**Expected:**
_test_driver/integration_test.dart_ and _test_driver/integration_test_driver.dart_ to match.

**Comment by Abhishek01039** [comment]
I have created this PR https://github.com/flutter/website/pull/5265 and it merged.

please close this issue @sfshaza2

**Comment by atsansone** [comment]
Flutter Driver has been deprecated. See the [migration guide](https://docs.flutter.dev/release/breaking-changes/flutter-driver-migration). Closing this issue.
