### ISSUE TITLE
'macOS install' page issue

### ISSUE THREAD

**Issue by mprogers** [flutter/website#5143]
Page URL: https://docs.flutter.dev/get-started/install/macos
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Description of issue:

The instructions failed to mention what to do if **flutter run** gives this output:

```terminal
Running Xcode build...                                                  
 └─Compiling, linking and signing...                         3.6s
Xcode build done.                                            7.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    /Users/me/Desktop/my_app/build/ios/Debug-iphonesimulator/Runner.app:
    resource fork, Finder information, or similar detritus not allowed
    Command CodeSign failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
```

This was a bug/issue that was reported in [January of 2020](https://github.com/flutter/flutter/issues/49290)

The solution that worked for me was:

```terminal
cd my_app/build/ios/Debug-iphonesimulator
xattr -cr ./Runner.app
```

I would imagine that if this happens for me, it happens for lots of people, and mentioning it in the documentation would be good, as the installation / getting started will be people's first experience using Flutter.

**Comment by atsansone** [comment]
Per https://github.com/flutter/flutter/pull/81435, the `xattr` flags were removed from the entire flutter app directory. This should not reoccur. Closing issue.

cc: @jmagman
