### ISSUE TITLE
Check that `ElevatedButton` works on 'Update data over the internet' page

### ISSUE THREAD

**Issue by srosti** [flutter/website#5144]
Page URL: https://flutter.dev/docs/cookbook/networking/update-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/update-data.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
ElevatedButton doesn't work... "FlatButton" works.

With this example, I see:
The method 'ElevatedButton' isn't defined for the class '_MyAppState'.

**Comment by VarunSAthreya** [comment]
@srosti I guess the widget `ElevatedButton` was introduced in version 1.22.0

**Comment by Abhishek01039** [comment]
These docs follow the latest stable version of flutter.

**Comment by piedcipher** [comment]
I think this issue is outdated now. Good to close?

**Comment by atsansone** [comment]
This issue applies to a version of Flutter almost 3 years old. This issue no longer occurs. Closing issue.
