### ISSUE TITLE
Update 'Report errors to a service' page to work with Sentry 4.0.1

### ISSUE THREAD

**Issue by Spodeopieter2** [flutter/website#5157]
Page URL: https://docs.flutter.dev/cookbook/maintenance/error-reporting
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/maintenance/error-reporting.md

The code examples seem to be a little out of date, here are some fixes I had to do in order to get it working on Sentry 4.0.1

```dart
final SentryClient _sentry = SentryClient(new SentryOptions(
    dsn:
        "https://XYZ "));
```

```dart
 _sentry.captureException(
      error,
      stackTrace: stackTrace,
```

**Comment by piedcipher** [comment]
I think flutter-doc's sentry page seems up-to-date. Good to close? Here is the sentry doc for comparison - https://docs.sentry.io/platforms/flutter/#configure

**Comment by atsansone** [comment]
The examples on the Flutter page match those of Sentry 7.6+: https://docs.sentry.io/platforms/flutter/#configure

Closing issue.
