### ISSUE TITLE
'Use a custom font' page issue

### ISSUE THREAD

**Issue by em-azhar** [flutter/website#5158]
Page URL: https://flutter.dev/docs/cookbook/design/fonts.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/fonts.md

Description of issue: 
![Screen Shot 2021-01-06 at 10 37 26 PM](https://user-images.githubusercontent.com/70394391/103797216-4a6abb00-5070-11eb-9106-cdd965935bc0.png)
![Screen Shot 2021-01-06 at 10 37 41 PM](https://user-images.githubusercontent.com/70394391/103797232-4d65ab80-5070-11eb-8cb2-567004559628.png)

Expected update in the documentation.

![Screen Shot 2021-01-06 at 10 58 03 PM](https://user-images.githubusercontent.com/70394391/103799258-f57c7400-5072-11eb-856d-080a19310014.png)

as shown above, '-' sign is missing in the documentation.

**Comment by micpap25** [comment]
Can you try indenting `fonts:` forward so it exactly matches the documentation? If this is a real issue then it will require a lot of changes over a lot of Flutter sites.

**Comment by parlough** [comment]
The dash (`-`) is indicating new items in a YAML list, but that `fonts` entry is meant to be part of the same yaml map as the `family: Raleway` entry. So if `fonts` lines up with `family` it should then work.

Thanks for opening the issue and if you are still having issues, let us know :)
