### ISSUE TITLE
'Take a picture using the camera' page issue

### ISSUE THREAD

**Issue by PeterKazimir** [flutter/website#5161]
Page URL: https://flutter.dev/docs/cookbook/plugins/picture-using-camera.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/plugins/picture-using-camera.md

Description of issue:

When I copy the final code, I get an error at 
l. 110 await _controller.takePicture(path);

"Too many positional arguments: 0 expected, but 1 found. "

As a result, the photo is not saved on a specified location, but rather with a random name.

**Comment by piedcipher** [comment]
Perhaps this seems to be fixed in this commit: https://github.com/flutter/website/commit/6a81164e1259fd819efc205df298e9e4f6af9156#diff-723ff10e7d8ef4a1937730d13dac84dad5ba01f30f97d3d528ac02c9c2c46d76

**Comment by piedcipher** [comment]
I think this one is fixed. Good to close?

**Comment by atsansone** [comment]
Duplicates https://github.com/flutter/website/issues/5109. Fixed. Closing.
