### ISSUE TITLE
'Report errors to a service' page issue

### ISSUE THREAD

**Issue by debasiskoley** [flutter/website#5163]
Page URL: https://flutter.dev/docs/cookbook/maintenance/error-reporting.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/maintenance/error-reporting.md

Description of issue: Please update the doc.

**Comment by sfshaza2** [comment]
@johnpryan, are you aware of updates that this page requires?

**Comment by johnpryan** [comment]
No, I'm not sure what this refers to.

**Comment by sfshaza2** [comment]
OK, @debasiskoley, I am closing this issue. Please re-open if you have a list of specific issues that need to be addressed. Thanks!
