### ISSUE TITLE
Clarify location on assets on 'Adding assets and images' page

### ISSUE THREAD

**Issue by kuyaC** [flutter/website#5169]
Page URL: https://docs.flutter.dev/ui/assets-and-images
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/assets-and-images.md

Description of issue:

I think this part of the page is outdated/false:

> If, on the other hand, the graphics directory is specified:
> 
> ```yaml
> flutter:
>   assets:
>     - graphics/
> ```
> 
> Then the graphics/my_icon.png, graphics/background.png and graphics/dark/background.png files are also included.

I have pictures in a folder like this: assets/country_flags/...

If I use:

```yaml
flutter:
  assets:
    - assets/
```

it doesn't work, I get errors while trying to load the assets during runtime.
(but it should, according to the part of the page i quoted)

If I use:

```yaml
flutter:
  assets:
    - assets/country_flags/
```

it works.
(indentations are good in my project, they might look wrong here bc of copy/paste, also no typos)

Btw, my versions:
Flutter 1.23.0-8.0.pre.74
Dart 2.11.0
Android Studio 4.1.1

Thanks for reading ;)

**Comment by atsansone** [comment]
This page has been updated to reflect the current and correct state. Closing this issue.

See also: https://github.com/flutter/website/issues/4175
