### ISSUE TITLE
'Write your first Flutter app, part 1' page issue

### ISSUE THREAD

**Issue by rollas** [flutter/website#5170]
Page URL: https://flutter.dev/docs/get-started/codelab.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab.md

Description of issue:
Codes in Step 2 & 3 missing AppBar things. I couldn't run the code without it.

**Comment by sfshaza2** [comment]
I just checked and this appears to be fixed. I'm closing, but re-open if I am incorrect.
