### ISSUE TITLE
Exception has occurred. MissingPluginException (MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core))

### ISSUE THREAD

**Issue by joshuajennysibbu** [flutter/website#5171]
I get this exception....... i try many ways but I cannot solve.....

![Screenshot from 2021-01-11 19-11-41](https://user-images.githubusercontent.com/59843233/104190378-085fc180-5442-11eb-9c78-95eb011459be.png)

**Comment by imrishuroy** [comment]
Initialize Firebase first before using it in your app. Check this page - https://firebase.flutter.dev/docs/overview

**Comment by joshuajennysibbu** [comment]
> Initialize Firebase first before using it in your app. Check this page - https://firebase.flutter.dev/docs/overview

I try this but still getting that exception.........

``

**Comment by sfshaza2** [comment]
Please file this in the GitHub repo for firebase.flutter. There's a link from the source page.
