### ISSUE TITLE
'Advanced UI' page issue

### ISSUE THREAD

**Issue by richardhaven** [flutter/website#5183]
Page URL: https://flutter.dev/docs/development/ui/advanced/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/advanced/index.md

Description of issue: Focus handling system is not yet implemented

Either create a page for it (oh please, oh please) or remove the title

**Comment by micpap25** [comment]
From what I can tell... it looks like it may have been lost?
![image](https://user-images.githubusercontent.com/34077605/105439270-8b4afe00-5c32-11eb-816e-c2f11364d7b4.png)
I'd change the title to directly say "Implement the 'Focus handling system' page" or something. I'm shocked there isn't an issue open on this. Good catch!

**Comment by sfshaza2** [comment]
@richardhaven, I'm sorry that this side nav item taunted you. I dimly recall that we did have such a page at one time, but it no longer exists (if I'm even remembering correctly). I've removed it from the sidenav. When I googled "Flutter focus handling", there were quite a few hits. Maybe someone else has published something useful. If you have specific questions about focus, please open an issue and list your specific questions.

**Comment by MrBirb** [comment]
@sfshaza2 Shams I believe you fixed this but it didn’t get closed.
