### ISSUE TITLE
'Animations tutorial' page issue

### ISSUE THREAD

**Issue by ehabelnahas** [flutter/website#5186]
Page URL: https://flutter.dev/docs/development/ui/animations/tutorial.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/animations/tutorial.md

I think the last 3 lines (line number 44,45 and 46)  should be removed from the following tutorial example:

  | @@ -32,7 +32,15 @@
-- | --
     32 | void initState() {
     33 | super.initState();
     34 | controller =
     35 | AnimationController(duration: const Duration(seconds: 2), vsync: this);
     36 | -     animation = Tween<double>(begin: 0, end: 300).animate(controller);
     36 | +     animation = Tween<double>(begin: 0, end: 300).animate(controller)
     37 | +       ..addStatusListener((status) {
     38 | +         if (status == AnimationStatus.completed) {
     39 | +           controller.reverse();
     40 | +         } else if (status == AnimationStatus.dismissed) {
     41 | +           controller.forward();
     42 | +         }
     43 | +       })
     44 | +       ..addStatusListener((state) => print('$state'));
     45 | controller.forward();
     46 | }

**Comment by micpap25** [comment]
Do you have any specific reason why? The point of the tutorial is to teach users how to use `addStatusListener()`. I'd like to hear your logic for removing this section.

**Comment by sfshaza2** [comment]
Closing.
