### ISSUE TITLE
Missing Diagram in the FAQ

### ISSUE THREAD

**Issue by TekExplorer** [flutter/website#5187]
there appears to be a missing link in the ["What technology is Flutter built with?"](https://flutter.dev/docs/resources/faq#what-technology-is-flutter-built-with) section of the FAQ:
[`src/docs/resources/faq.md`](https://github.com/flutter/website/blob/master/src/docs/resources/faq.md) line [`161`](https://github.com/flutter/website/blame/master/src/docs/resources/faq.md#L161) < Links included

![Screenshot_20210114_140718](https://user-images.githubusercontent.com/30291302/104636887-07ad7200-5672-11eb-8515-b8488ad77eed.png)

**Comment by micpap25** [comment]
I found the past commit that accidentally changed `[architecture diagram]` to just `[diagram]` which broke this. Making a PR now.

**Comment by TekExplorer** [comment]
glad to help!
