### ISSUE TITLE
'Take a picture using the camera' page issue

### ISSUE THREAD

**Issue by unsalatasoy** [flutter/website#5194]
Page URL: https://flutter.dev/docs/cookbook/plugins/picture-using-camera.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/plugins/picture-using-camera.md

Description of issue:

takePicture method doesn't take any argument and return XFile. 

// Attempt to take a picture and log where it's been saved.
            await _controller.takePicture(path);

**Comment by sfshaza2** [comment]
This has been fixed. Closing.
