### ISSUE TITLE
'Take a picture using the camera' page issue

### ISSUE THREAD

**Issue by andzejsw** [flutter/website#5197]
Page URL: https://flutter.dev/docs/cookbook/plugins/picture-using-camera.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/plugins/picture-using-camera.md

Description of issue: "takePicture" method uses file path, while in latest version "0.6.4+5" there is no parameters for this method! So documentation is outdated!

**Comment by sfshaza2** [comment]
This has been fixed. Closing.
