### ISSUE TITLE
auto close app when run flutter for web 

### ISSUE THREAD

**Issue by tampro9x92** [flutter/website#5217]
i'm using popOS 20.10 and browser is brave
I have code like this 
https://paste.ofcode.org/37CrLRGVMycUFN8LAiCddRk
I run it on the browser sometime my website it just auto close it after it finish and send me no error

**Comment by micpap25** [comment]
I think you might be in the wrong place. This is the GitHub for the Flutter documentation website. 
If you are trying to report an error with the Flutter language itself, please go to the [flutter/flutter repository](https://github.com/flutter/flutter)
However, it looks like you're asking about errors in your code. I would recommend instead going to [StackOverflow](https://stackoverflow.com/)

**Comment by sfshaza2** [comment]
Excellent advice, @micpap25. This is not the place to get Flutter support. Closing.
