### ISSUE TITLE
Explain changes to integration testing: `waitFor` vs `pump`

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#5223]
[this section](https://flutter.dev/docs/testing/integration-tests#migrating-from-flutter_driver) of the integration testing page  needs more detail around the waitFor vs pump* APIs.

- Why waitFor / waitForAbsent are deprecated
    - (performance + accuracy
    - introduces extra work that can throw off benchmarks
    - can make tests more flaky,
- How to use pump APIs
    - pump can drive to specific animation frames 
    - pumpAndSettle can drive to the end of an animation
- How to upgrade a test from waitFor to pump*

**Comment by miquelbeltran** [comment]
Once https://github.com/flutter/website/pull/6514 lands I will extend that guide to include this.

**Comment by atsansone** [comment]
This should be covered in the [migration guide](https://docs.flutter.dev/release/breaking-changes/flutter-driver-migration). Closing this issue.
