### ISSUE TITLE
'Mock dependencies using Mockito' page issue

### ISSUE THREAD

**Issue by domesticmouse** [flutter/website#5229]
Page URL: https://flutter.dev/docs/cookbook/testing/unit/mocking.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/unit/mocking.md

Description of issue: This page needs to be updated for null safety. See Mockito's [NULL_SAFETY_README.md](https://github.com/dart-lang/mockito/blob/master/NULL_SAFETY_README.md) for details

**Comment by sfshaza2** [comment]
@miquelbeltran, can you add this to the spreadsheet?

**Comment by miquelbeltran** [comment]
It's in row 170 in the "flutter.dev" sheet. I can add that to my TODO if you want!

**Comment by sfshaza2** [comment]
Yes, please. And thx!

**Comment by miquelbeltran** [comment]
This can be closed now :)

**Comment by domesticmouse** [comment]
Thanks @miquelbeltran!
