### ISSUE TITLE
Update imports in example on 'Writing custom platform-specific code' page

### ISSUE THREAD

**Issue by guillempuche** [flutter/website#5237]
### Page URL

https://docs.flutter.dev/platform-integration/platform-channels

### Page source

https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/platform-channels.md

### Description of issue
Error when building the Android example.

**Solution:**
The code in `MainActivity.java` needs these libraries:
```java
import androidx.annotation.NonNull;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugin.common.MethodChannel;
```

**Comment by MrBirb** [comment]
@guillempuche They are already there though?

**Comment by atsansone** [comment]
This is fixed on this page. Closing this issue.
