### ISSUE TITLE
Offline saved page doesn't show properly

### ISSUE THREAD

**Issue by HasanElHefnawy** [flutter/website#5238]
1- open any webpage whose URL starts with [https://flutter.dev](https://flutter.dev)
2- press (CTRL + s) to save the page
3- open the offline saved page. It doesn't show properly.

Note: the issue doesn't exist in webpages whose URL start with [https://api.flutter.dev/](https://api.flutter.dev/)

**Comment by sfshaza2** [comment]
Hi, @HasanElHefnawy. Yes, that doesn't work well at all.

I use a Mac and, when I need to do this, I "print" the page and then select "save as PDF". Then you can view/print the PDF. I'm not sure how this works on Windows.

Meanwhile, I will leave this open as an infrastructure bug.

**Comment by parlough** [comment]
Thanks for the issue. However, I don't think we'll have the time to support this use case. This year we landed improvements to "Print to PDF" that should result in a more readable page and should fulfill the offline use-case better.

If others feel strongly about better supporting this use case or are willing to contribute to improve it, let us know, and we'll happily reopen this issue. Thanks!
