### ISSUE TITLE
'DeTarget of URI doesn't exist: 'package:english_words/english_words.dart'. Try creating the file referenced by the URI, or Try using a URI for a file that does exist.vTools' page issue

### ISSUE THREAD

**Issue by chaluy007** [flutter/website#5260]
Page URL: https://flutter.dev/docs/development/tools/devtools/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/devtools/index.md

**Comment by sfshaza2** [comment]
This has been fixed. Closing.
