### ISSUE TITLE
'Take a picture using the camera' page issue

### ISSUE THREAD

**Issue by alexhenriquepv** [flutter/website#5269]
Page URL: https://flutter.dev/docs/cookbook/plugins/picture-using-camera.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/plugins/picture-using-camera.md

Description of issue:

The `takePicture()` method does not accepts positional arguments anymore.
To use him, return a XFile, ex: `final XFile picture = await _cameraCtrl.takePicture();`

**Comment by sfshaza2** [comment]
This has been fixed. Closing.
