### ISSUE TITLE
flutter sdk

### ISSUE THREAD

**Issue by staggone-ill** [flutter/website#5277]
Page URL: https://flutter.dev/docs/get-started/install/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by Abhishek01039** [comment]
@staggone-ill 
where you have found typo?

**Comment by staggone-ill** [comment]
Hello i am not able to /flutter creat app/

**Comment by Abhishek01039** [comment]
try ```flutter doctor``` in your terminal 
Please refer to this https://flutter.dev/docs/get-started/install/windows if you have windows
or https://flutter.dev/docs/get-started/install/macos if you have mac or 
https://flutter.dev/docs/get-started/install/linux if you have linux
Thanks

**Comment by staggone-ill** [comment]
Bro i've but am getting error for no flutter sdk found

**Comment by Abhishek01039** [comment]
have you set the path for flutter?

**Comment by staggone-ill** [comment]
That is my proble no.2 i've done every step correctly but all the paths
i've tried on Android Studio are not accept

**Comment by staggone-ill** [comment]
![IMG_20210211_174610.jpg](https://user-images.githubusercontent.com/49114483/107651924-16973c80-6c91-11eb-8dd1-c58b21ffc5b1.jpg)

**Comment by sfshaza2** [comment]
@staggone-ill, I am very sorry you are having this issue! @Abhishek01039, thanks so much for helping!

@staggone-ill, this is not a support channel. It's a channel for reporting bugs (typos, errors, feature requests) on flutter.dev. I'm really the only person who reads these issues (except for kind community members like Abhishek, and I don't monitor it daily. There are numerous places where you can get great support from the community and they are listed on the [community page](https://flutter.dev/community). Maybe you are part of [#30DaysOfFlutter](https://medium.com/flutter/join-us-for-30daysofflutter-9993e3ec847b), which is running the month of February, and they have a dedicated Discord channel where lots of community members are available to help.

Good luck! I'm closing this.
