### ISSUE TITLE
'Adopt a Widget' page issue

### ISSUE THREAD

**Issue by sidrao2006** [flutter/website#5286]
Page URL: https://flutter.dev/adoptawidget/
Page source: https://github.com/flutter/website/tree/master/src/adoptawidget/index.md

Description of issue: Update Adopt a Widget contribution list. Several PRs were created and merged after the last update of the list which is needed to be added.

**Comment by micpap25** [comment]
Hi, can you be more specific so I can solve this issue? What exactly is wrong with the contribution list?

**Comment by sidrao2006** [comment]
@micpap25 thanks for asking, I have updated the description
