### ISSUE TITLE
'Take a picture using the camera' page issue

### ISSUE THREAD

**Issue by bortnikov** [flutter/website#5291]
Page URL: https://flutter.dev/docs/cookbook/plugins/picture-using-camera.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/plugins/picture-using-camera.md

Description of issue:
```
lib/main.dart:100:56: Error: Too few positional arguments: 1 required, 0 given.
            final image = await _controller.takePicture();
                                                       ^
```

**Comment by sfshaza2** [comment]
Hi there. You must have been using master, beta, or dev channel. The website tests against the latest stable channel. As of Flutter 2, this has been fixed. Thx
