### ISSUE TITLE
Hi Taha and luohaohaha,

### ISSUE THREAD

**Issue by HaggaNaggaQuyre** [flutter/website#5292]
Hi Taha and luohaohaha, 

Do you know the solution?

May I know the solution for the above issue as I also face the same issue and am struggling for last few days. 
Appreciate your help on this

_Originally posted by @geeraj in https://github.com/flutter/flutter/issues/63763#issuecomment-755773121_

**Comment by sfshaza2** [comment]
Hi! This repo is for issues on the flutter.dev website. As the issue on flutter/flutter says, this is for a 3rd party dependency. Closing.
