### ISSUE TITLE
'Build a form with validation' page issue

### ISSUE THREAD

**Issue by keymistress** [flutter/website#5293]
Page URL: https://flutter.dev/docs/cookbook/forms/validation.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/forms/validation.md

Description of issue:
Not exactly an issue but in the interactive example source code, line 64 still uses legacy code
`Scaffold.of(context)
  .showSnackBar(SnackBar(content: Text('Processing Data')));`
even though that is now managed by [ScaffoldMessenger](https://flutter.dev/docs/release/breaking-changes/scaffold-messenger).

Thanks to Joe Muller for the [solution](https://stackoverflow.com/a/65906839/13422373).

**Comment by sfshaza2** [comment]
Yes, the flutter.dev repo reflects the latest stable release, and you must have been using master, dev, or beta. With the release of Flutter 2, this has been fixed.
