### ISSUE TITLE
'Building beautiful UIs with Flutter' page issue

### ISSUE THREAD

**Issue by keymistress** [flutter/website#5295]
Page URL: https://codelabs.developers.google.com/codelabs/flutter#4

Under **Wrap the TextField inside a Flexible:**
The first step says Select **Row** when it should be **Textfield**.

Apologies in advance if this was a mistake, I was just following the tutorial and get stuck for ages trying to wrap the Textfield by wrapping Row.

**Comment by parlough** [comment]
This codelab has been replaced by [Take your Flutter app from boring to beautiful](https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful). 

I'll close this as the original codelab referenced here is no longer available. Thanks for opening an issue!
