### ISSUE TITLE
'Deep linking' page dead link issue

### ISSUE THREAD

**Issue by Gurjot95** [flutter/website#5299]
Page URL: https://flutter.dev/docs/development/ui/navigation/deep-linking.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/navigation/deep-linking.md

Culprit URL: https://github.com/flutter/samples/blob/master/navigation_and_routing/lib/nav_2/router.dart

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: Router Widget Sample link is dead and throws 404 error.

**Comment by JuYeong0413** [comment]
Hey @Gurjot95, thanks for filing the issue.
The correct url is https://github.com/flutter/samples/blob/master/navigation_and_routing/lib/router/router.dart
I've created a pull request, hope it will be fixed soon. :-)
