### ISSUE TITLE
'Take a picture using the camera' page issue

### ISSUE THREAD

**Issue by mcp10** [flutter/website#5307]
Page URL: https://flutter.dev/docs/cookbook/plugins/picture-using-camera.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/plugins/picture-using-camera.md

Description of issue:
`_controller.takePicture();` missing `path` argument

**Comment by sfshaza2** [comment]
As of version 0.6.0 of the `camera` plugin, [`takePicture` no longer takes a `path` parameter](https://pub.dev/packages/camera/changelog).
