### ISSUE TITLE
Performance profiling IA doesn't clearly signpost key article

### ISSUE THREAD

**Issue by timsneath** [flutter/website#5310]
https://flutter.dev/docs/perf/rendering/ui-performance is our main section on perf profiling. But https://flutter.dev/docs/development/tools/devtools/performance is our best document on perf profiling, and it's in a different part of the tree. It's hard to find this page, because it's deep in the tools hierarchy, as @eseidelGoogle discovered today.

We need to figure out how we can connect these more clearly, so you can think "performance problem" and get at all the content we have to offer.

**Comment by sfshaza2** [comment]
Geez, how did this languish for so long?! (Just mad at myself.)
