### ISSUE TITLE
'Use a custom font' page issue

### ISSUE THREAD

**Issue by feinstein** [flutter/website#5319]
Page URL: https://flutter.dev/docs/cookbook/design/fonts.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/fonts.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

We need a place that documents what kind of fonts formats Flutter accepts, like: ttf, otf, woff, woff2 etc.

**Comment by micpap25** [comment]
We can do this at https://flutter.dev/docs/cookbook/design/fonts#1-import-the-font-files . Additional information can be found at https://github.com/flutter/flutter/issues/13823 . 

I'm going to work on this right now.

**Comment by feinstein** [comment]
That was fast :) thanks!
