### ISSUE TITLE
flutter.dev/web should link to gallery.flutter.dev

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/website#5329]
I discovered this afternoon that gallery.flutter.dev is not crawled by Google.  I think that's because it's never linked to from flutter.dev?

https://flutter.dev/web should probably link to gallery.flutter.dev.

Thanks!  FYI @mariamhas

**Comment by mariamhas** [comment]
I assume you mean have a gallery.flutter.dev link included in the flutter.dev/web page somewhere, and not have flutter.dev/web redirect to gallery demo. Right?

**Comment by eseidelGoogle** [comment]
Correct.  I just was noticing that flutter.dev/web didn't link to gallery.flutter.dev anywhere.  It doesn't need to redirect, just have a link since we've invested so much in making gallery.flutter.dev useful might as well link to it from other pages. :)

**Comment by mariamhas** [comment]
agreed, already have an update for it so ill assign this to myself and close once its published :)

**Comment by sfshaza2** [comment]
I checked and this has been fixed. Thanks, @mariamhas!
