### ISSUE TITLE
'Codelabs' page issue

### ISSUE THREAD

**Issue by krishil85** [flutter/website#5331]
Page URL: https://flutter.dev/docs/codelabs/
Page source: https://github.com/flutter/website/tree/master/src/docs/codelabs/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: Get to know Firebase for Flutter is throwing a 404 error. Please fix. I want to complete the tutorial

**Comment by anurag940948** [comment]
@krishil85  This issue has been fixed and you can close this issue. Thanks.
