### ISSUE TITLE
'Linux install' page issue

### ISSUE THREAD

**Issue by elnimr** [flutter/website#5356]
Page URL: https://flutter.dev/docs/get-started/install/linux.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/linux.md

Description of issue:
there is no space between $ sign and "sudo snap install flutter --classic" the whole page have spaces between $ sign and code which is not acceptable on Ubuntu.

**Comment by micpap25** [comment]
Hi, most documentation websites generally put a space between the $ and the command for the sake of readability. Additionally, at least for my installation of Cygwin, that space is already there, and even if I were to add another space commands would still work. 

All the shell / terminal segments on the Flutter docs space out that section, and to show this isn't specifically a Flutter issue, here's another documentation page that spaces out their shell commands:
https://devcenter.heroku.com/articles/heroku-cli

You can close this issue if this answers your problem.

**Comment by sfshaza2** [comment]
Thanks, @micpap25. Closing.

**Comment by MrCsabaToth** [comment]
The difference between the Heroku example and the Flutter page is that on Heroku the $ has a different color and it is not selectable. I want to see the markup of what they use there.

**Comment by MrCsabaToth** [comment]
Semi relevant discussions in theme and other repositories:
https://github.com/theme-next/hexo-theme-next/issues/448
https://github.com/updownpress/markdown-lint/blob/master/rules/014-commands-show-output.md
Maybe $ is not even needed if the code is just a singe shell command, or all lines are shell commands? https://cirosantilli.com/markdown-style-guide/#dollar-signs-in-shell-code
