### ISSUE TITLE
Spelling mistake fails the test in How to test a Flutter app || Codelab

### ISSUE THREAD

**Issue by zyllus17** [flutter/website#5358]
The instruction says to create a `favourites_test.dart` file but the codelabs works with `favorites_test.dart`. The `favorites` is without a `u`.

![image](https://user-images.githubusercontent.com/50977126/109151029-a78d0e00-778f-11eb-84fd-d5d16a7bdf47.png)

This throws an error when using the command given below

🔴  Error -
```
00:00 +0 -1: loading D:\FlutterProjects\testing_app\test\models\favorites_test.dart [E]
Failed to load "D:\FlutterProjects\testing_app\test\models\favorites_test.dart": Does not exist.
00:00 +0 -1: Some tests failed.
```

![image](https://user-images.githubusercontent.com/50977126/109151447-3437cc00-7790-11eb-8909-27af117fea7a.png)

🟢  Solution - Fix the spelling of `favourites_test.dart` by removing the `u`

**Comment by zyllus17** [comment]
Link to the Codelab [How to test a Flutter app](https://codelabs.developers.google.com/codelabs/flutter-app-testing#4)

**Comment by domesticmouse** [comment]
By the look of https://codelabs.developers.google.com/codelabs/flutter-app-testing#4 this mis-spelling has been corrected. Thanks for the report!
