### ISSUE TITLE
'Install and run DevTools from Android Studio' page issue

### ISSUE THREAD

**Issue by dhameliyamilan** [flutter/website#5366]
Page URL: https://flutter.dev/docs/development/tools/devtools/android-studio.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/devtools/android-studio.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by sfshaza2** [comment]
Closing.
