### ISSUE TITLE
Typo in Flutter Fonts page https://flutter.dev/docs/cookbook/design/fonts (#76855)

### ISSUE THREAD

**Issue by devmgs** [flutter/website#5367]
Under heading Supported font formats

its written

Flutter supports the following font formats:

.tff
.otf

the .tff should be .ttf

**Comment by micpap25** [comment]
haha, thanks. this was my push, I can't believe I misspelled that.

**Comment by micpap25** [comment]
@Sfshaza issue was fixed, if you could close this that would be great.

**Comment by sfshaza2** [comment]
Thx! Closing.
