### ISSUE TITLE
Clarify relationship between `flutter_test` and `test` packages on 'An introduction to unit testing' page

### ISSUE THREAD

**Issue by hk6an6** [flutter/website#5371]
Page URL: https://docs.flutter.dev/cookbook/testing/unit/introduction
Page source: https://github.com/flutter/website/blob/main/src/cookbook/testing/unit/introduction.md

Description of issue:

Lines 18 to 19 are misleading. To clarify, the page should state:

```markdown
You need the [`flutter_test`](https://pub.dev/packages/test).
It contains the [`test`](https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html)
package and provides utilities for testing widgets.
```

**Comment by atsansone** [comment]
This is a duplicate of https://github.com/flutter/website/issues/5372. Closing.
