### ISSUE TITLE
'Visual Studio Code' page issue

### ISSUE THREAD

**Issue by fahaddi** [flutter/website#5373]
Page URL: https://flutter.dev/docs/development/tools/vs-code.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/vs-code.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by micpap25** [comment]
Hi @fahaddi , you might have forgotten to describe your issue. Could you add your description so I can solve your problem?

**Comment by micpap25** [comment]
@Sfshaza since there's been no response for a week, I think this can be closed.

**Comment by sfshaza2** [comment]
Closing.

**Comment by fahaddi** [comment]
Hi
في خميس، 11 مارس، 2021 في 2:20 ص، كتب Shams Zakhour (ignore Sfshaza) <
notifications@github.com>:
