### ISSUE TITLE
Add `export` command to `.zprofile` to macOS install page for Mac Catalina or higher

### ISSUE THREAD

**Issue by danielhrc** [flutter/website#5374]
## The problem
I had a problem installing flutter at my Macbook Air 2017 (OS version = Big Sur).

## Step by step to reproduce
- After doing exactly equal as the installing documentation, I restarted the computer
- tried to run `flutter doctor`
- Terminal was logging `command not found ` 

## The Solution
- I googled some solutions and I found that Mac Catalina or Higher requires Full Disk access to Terminal to get Flutter working, but I have no evidence it works (Anyway, I allowed this in preferences).
- I found out that Mac Catalina or higher uses `zsh` with a `.zprofile` (not `.zshrc` nor `.zshenv` etc).
Then I added this to the `.zprofile`: 
`export PATH=$HOME/FLUTTER_DIR/flutter/bin:$PATH`

AND..... IT WORKS! 

## Proposal

Consider adding a note at Get Started Documentation.

Best regards.

**Comment by sfshaza2** [comment]
@danielhrc, the [macos install page](https://flutter.dev/docs/get-started/install/macos) mentions editing the .zshrc file. That didn't work for you?

**Comment by danielhrc** [comment]
@sfshaza2 it didn't work - then I tried editing every `.z` file and restarting the notebook after every edit. 
The only that worked was `.zprofile`
