### ISSUE TITLE
Feature request for the "writing a plugin" codelab

### ISSUE THREAD

**Issue by nerdybunz** [flutter/website#5381]
It would be nice if the flutter plugin codelab 

https://codelabs.developers.google.com/codelabs/write-flutter-plugin#0

could somehow allow us users/readers to toggle between obj-c/swift... and java/kotlin.

Though I suppose that creates four possible combinations/repos which may not be feasible... or maybe take a poll?  I feel like more people know swift than objc.

Maybe the plugin could be reduced to a much simpler (hello world) example to make it less cumbersome to accomodate all four languages.

**Comment by sfshaza2** [comment]
@gaaclarke, thoughts?

**Comment by sfshaza2** [comment]
I'd also love to see this code lab expand to also covering web, now that it's reached stable.  :)

**Comment by gaaclarke** [comment]
Dear Nerdybunz, 

That's a good idea.  When this codelab was authored we were just transitioning the default languages to swift/kotlin.  I don't know when someone will get the chance to update the codelab, but in the meantime you can see a simple hello world example by using `flutter create -t plugin`.  That will create a swift/kotlin plugin you can run immediately that will do "hello world" between the plugin and Flutter.  Between that and reading over the codelab, glossing over the objc and java bits if you have to, hopefully the gist of plugins will be clear.  Half of the doc is written in Dart.

**Comment by gaaclarke** [comment]
> I'd also love to see this code lab expand to also covering web, now that it's reached stable. :)

That's an interesting idea.  I'm no expert on web development, especially when getting access to an audio callback.  I would certainly be learning if I wrote it.

**Comment by sfshaza2** [comment]
Thanks for your quick response, @gaaclarke!
