### ISSUE TITLE
'Pass arguments to a named route' page issue

### ISSUE THREAD

**Issue by jonasjuni** [flutter/website#5385]
Page URL: https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/navigate-with-arguments.md

Description of issue:
Missing type cast on `ModalRoute.of(context).settings.arguments`

I have a suggestion for fixing it over here:
https://github.com/flutter/website/compare/master...jonasjuni:patch-1

![image](https://user-images.githubusercontent.com/12734070/109825951-1697b600-7c19-11eb-8388-82dd247a8d66.png)

I'm still learning, sorry for any inconvenience !

**Comment by sfshaza2** [comment]
@johnpryan, can you take a look?

**Comment by tirth-stasis** [comment]
I don't see this issue in embedded dartpad.

**Comment by johnpryan** [comment]
I can't reproduce this either - this could have been a result of upgrading the SDK in dart-services. @jonasjuni are you still seeing this?

**Comment by jonasjuni** [comment]
Now I understand why it was happening, If you enable null safety and then switch it back, it changes dart sdk version.... I think this issue should be closed, anyway it will be fixed when updating this tutorial to null safety
