### ISSUE TITLE
'Internationalizing Flutter apps' AppLocalizations.of(context) nullable

### ISSUE THREAD

**Issue by MaximilianFrick** [flutter/website#5405]
Page URL: https://flutter.dev/docs/development/accessibility-and-localization/internationalization.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

Description of issue:

When using the new Flutter 2.0, you need to add a null-check (!) for `AppLocalizations.of(context)`.

**Comment by sfshaza2** [comment]
@miquelbeltran, and add this, too.  :)

**Comment by miquelbeltran** [comment]
Fixed in https://github.com/flutter/website/pull/5414 this can be closed

**Comment by sfshaza2** [comment]
Thanks! Closing.
