### ISSUE TITLE
Clarify why `NativeFactoryView()` is called without parameters on 'Hosting native Android views in your Flutter app with Platform Views' page

### ISSUE THREAD

**Issue by omelchenkovadym** [flutter/website#5408]
Page URL: https://docs.flutter.dev/platform-integration/android/platform-views
Page source: https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/platform-views.md

Description of issue:

I am looking at the NativeViewFactory constructor it has two arguments, and I don't understand why in PlatformViewPlugin we use "new NativeViewFactory()" without arguments.
![1](https://user-images.githubusercontent.com/47543710/110052172-d2fb9400-7d5f-11eb-8b85-8d2be06b0a80.jpg)
![2](https://user-images.githubusercontent.com/47543710/110052302-0e965e00-7d60-11eb-91db-760604dd7355.jpg)

**Comment by atsansone** [comment]
@blasten Would you have any insight into why this code was implemented as it was here? I have no issue updating the docs, but I'm unclear as to what the answer would be.

**Comment by atsansone** [comment]
Check [this comment](https://github.com/flutter/website/issues/4996#issuecomment-744584742) for a possible solution.

**Comment by stuartmorgan** [comment]
This issue is two years old, and the second screenshot no longer reflects the page content; closing as obsolete.
