### ISSUE TITLE
Updates on breaking changes pages and sub pages after release of Flutter 2.0.0

### ISSUE THREAD

**Issue by JigneshPatel23** [flutter/website#5411]
As we have this section on website where developers normally look for any breaking changes on latest released version.
[Breaking Changes](https://flutter.dev/docs/release/breaking-changes)

I have sent few pull requests(PRs) on the sub pages where I am sure those are landed on stable release as a part of Flutter 2.0.0

I am not sure if everything on the section [`Not yet released to stable`](https://flutter.dev/docs/release/breaking-changes#not-yet-released-to-stable) are released to latest stable Flutter 2.0.0 release.

Any thoughts?

**Comment by sfshaza2** [comment]
Thanks, @JigneshPatel23! This is something I address after a stable release. The work is a bit complex as I also remove master-api links and replace with standard API links, check the format and grammar. I fixed this in PR https://github.com/flutter/website/pull/5441 and PR https://github.com/flutter/website/pull/5448.

**Comment by JigneshPatel23** [comment]
Thanks for the updates @sfshaza2 🎉
