### ISSUE TITLE
'Desktop support for Flutter' page: Strange macOS version number

### ISSUE THREAD

**Issue by Atalanttore** [flutter/website#5412]
Page URL: https://flutter.dev/desktop.html
Page source: https://github.com/flutter/website/tree/master/src/desktop.md

The 'macOS' section says the following:

> However, as of **macOS 14.5** you need to notarize your macOS application before distributing it outside of the macOS App Store.

The latest version of macOS is major version 11. What is **macOS 14.5** all about?

**Comment by micpap25** [comment]
@Sfshaza This issue was fixed, the page now correctly says "macOS 10.14.5". This can be resolved.

**Comment by sfshaza2** [comment]
Thanks, @micpap25!
