### ISSUE TITLE
'Adding a splash screen to your mobile app' page issue

### ISSUE THREAD

**Issue by rhalff** [flutter/website#5431]
Page URL: https://flutter.dev/docs/development/ui/advanced/splash-screen.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/advanced/splash-screen.md

Description of issue:

The Sample code link at the bottom of the page directs to: https://github.com/flutter/flutter/tree/master/dev/integration_tests/android_splash_screens

This code is not present anymore in master and was removed during this commit:
https://github.com/flutter/flutter/commit/d69e2f10d82cf89c6a5595624bc19c1917626f85

The removed code probably did contain some very useful examples.

**Comment by sfshaza2** [comment]
The broken link has been removed. Closing.
