### ISSUE TITLE
'Install' page issue

### ISSUE THREAD

**Issue by behnamkhaniofficial** [flutter/website#5439]
Page URL: https://flutter.dev/docs/get-started/install/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/index.md

Build a variety of applications Participate in a complete content building platform Build your own repository
http://flutter.de
**[Behnam Khani](http://aparat.com/behnamkhanitabriz)** _ Engineer and designer of systematic scientific program and knowledge of network and Internet information technology

Description of issue: behnam khani my website market (http://aparatfilm.wordpress.com )

**Comment by sfshaza2** [comment]
flutter.de seems to be a German-language Flutter site. But this seems to be spam. Closing.
