### ISSUE TITLE
integration_test package

### ISSUE THREAD

**Issue by edgfowler** [flutter/website#5445]
Please update integration test chapter to reflect usage of integration_test package.

**Comment by sfshaza2** [comment]
@johnpryan

**Comment by johnpryan** [comment]
@edgfowler Are you referring to the [integration testing Cookbook article](https://flutter.dev/docs/cookbook/testing/integration/introduction)?

**Comment by johnpryan** [comment]
I think this referring to the cookbook, so I'm going to close this and track that work in this issue instead: https://github.com/flutter/website/issues/5889
