### ISSUE TITLE
Request: Animation Docs Update

### ISSUE THREAD

**Issue by marcosmko** [flutter/website#5456]
Hello all!

I would like to request an update on the animations tutorial, considering null safety.
https://flutter.dev/docs/development/ui/animations/tutorial

Thank you very much!

**Comment by sfshaza2** [comment]
@miquelbeltran, we can add this to the spreadsheet.

**Comment by miquelbeltran** [comment]
It's already there, row 88 on Sheet "Flutter.dev"
