### ISSUE TITLE
'Visual Studio Code' page issue - 'Flutter: New Project' command is no longer used

### ISSUE THREAD

**Issue by Kazuchanfl** [flutter/website#5471]
Page URL: https://flutter.dev/docs/development/tools/vs-code.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/vs-code.md

Description of issue:
For the development of flutter project with VSCode, this site has tools guide that instructs the Installation and setup steps. 

In the page I described above, it is said that we can create a new project using the command `Flutter: New Project`. However, I couldn't find that command, while I could find `Flutter: New Application Project.`.

Like as [this page](https://flutter.dev/docs/get-started/test-drive?tab=vscode), I suggest using the newer command `Flutter: New Application Project.`

**Comment by sfshaza2** [comment]
Fixed! Closing.
