### ISSUE TITLE
'Breaking changes' page issue

### ISSUE THREAD

**Issue by mprostock** [flutter/website#5484]
Page URL: https://flutter.dev/docs/release/breaking-changes/
Page source: https://github.com/flutter/website/tree/master/src/docs/release/breaking-changes/index.md

Description of issue:
Not sure this is the right place to mention this. But I found a breaking change in my code after just upgrading from 1.22.6 to 2.0.2:

The `Theme.of(context, shadowThemeOnly: true)` "`shadowThemeOnly`" parameter seems to have been removed but there is no mention of this anywhere in the docs and there is no "migration guide" as "promised" elsewhere for breaking changes and this also does not get picked up in `dart fix`. Currently my code simply breaks because of an underlying libraries problem.

This issue in the library is documented here (by others):
https://github.com/Realank/flutter_datetime_picker/issues/204

A related PR to flutter master seems to be this: (?!)
https://github.com/flutter/flutter/pull/69050
and this
https://github.com/flutter/flutter/pull/68922

It would be great if this issue could be put on the page (and mentioned elsewhere), kind of strange to completely drop a parameter without it being marked as deprecated before (maybe I missed that?) and not mention it anywhere. Or am I getting something wrong here?
Thanks.

**Comment by sfshaza2** [comment]
@goderbauer, it looks like we need an additional breaking change doc for Flutter 2. Can you submit a PR or delegate?

Thanks for bringing this to our attention, @mprostock!

**Comment by goderbauer** [comment]
This wasn't a breaking change per our breaking change policy posted here: https://github.com/flutter/flutter/wiki/Tree-hygiene#1-determine-if-your-change-is-a-breaking-change. Therefore, no breaking change guide has been posted. Please feel free to contribute the tests of your package to https://github.com/flutter/tests to ensure that Flutter doesn't break you unknowingly in the future.

Having said that, the PR you linked to shows how we migrated the code within the framework away from `shadowThemeOnly`. Those can be used as a blueprint to migrate your own code. In particular, the changes in `bottom_sheet.dart` are pretty canonical: https://github.com/flutter/flutter/pull/69050/files#diff-89f99a1415c93b2ce9493851c5f7f115752b7af86fa3a414428afccbff660fbaR675

**Comment by sfshaza2** [comment]
Thanks for that info, @goderbauer!  So, you are saying that changing the API such that compiling code that uses that API and the compile fails isn't a breaking change? That seems very counterintuitive to me. What makes this _not_ a breaking change?

**Comment by sfshaza2** [comment]
Also looping in @Piinks. I am trying to better understand what is and is not a breaking change.

**Comment by Piinks** [comment]
Hey @sfshaza2 according to the breaking change policy (@goderbauer linked above), a change is considered breaking if it breaks a customer test. Technically, *any* change can be considered breaking, so this is the metric @Hixie has developed for identifying breaks. Customer tests can be contributed by anyone to https://github.com/flutter/tests so their tests can be run against changes in flutter/flutter.

**Comment by sfshaza2** [comment]
I see. Thanks for explaining, @Piinks. The metric of breaking tests seems odd to me, but I guess you had to draw the line somewhere. At least it should quickly be solvable because it complains about the API and looking up the method signature should immediately make the change clear.

I'm closing this.

**Comment by Hixie** [comment]
It would be very valuable to have web site code be part of our contributed test suite, that would prevent this kind of problem in the future.

cc @RedBrogdon
