### ISSUE TITLE
"Flutter for Android Devs" and AppLifecycleState docs conflict

### ISSUE THREAD

**Issue by sumanthratna** [flutter/website#5493]
- [the "Flutter for Android Devs" docs](https://github.com/flutter/website/blob/master/src/docs/get-started/flutter-for/android-devs.md)
- [the `AppLifecycleState` docs](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html)

differences between the above 2 documents:
- according to `AppLifecycleState`, `suspending` does not exist
- according to `AppLifecycleState`, `inactive` _does_ work on Android
- according to `AppLifecycleState`, `detached` exists

**Comment by sfshaza2** [comment]
Yes, the Flutter for Android doc is out of date. The API doc is the source of truth. Not sure when we can get to this. PRs are most welcome!
