### ISSUE TITLE
'Write your first Flutter app, part 1' page issue

### ISSUE THREAD

**Issue by rinoldsimon** [flutter/website#5507]
Page URL: https://flutter.dev/docs/get-started/codelab.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab.md

Description of issue:

Upgrade package **english_words** from **3.1.5** to **4.0.0-nullsafety.0** to opt null-safety

```
Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

Package Name   Current  Upgradable  Resolvable           Latest               

direct dependencies:
english_words  ✗3.1.5   ✗3.1.5      ✓4.0.0-nullsafety.0  ✓4.0.0-nullsafety.0  
```

Commands to update:
```
dart pub outdated --mode=null-safety
dart pub upgrade --null-safety
```

**Comment by sfshaza2** [comment]
@miquelbeltran, I thought we had done this?

**Comment by miquelbeltran** [comment]
The fixed version is under https://flutter.dev/docs/get-started/codelab_migrated

**Comment by MrBirb** [comment]
@miquelbeltran 404

**Comment by miquelbeltran** [comment]
The page has been moved already and replaced the original codelab. This ticket can be closed @sfshaza2 ;)
