### ISSUE TITLE
'Mock dependencies using Mockito' page issue

### ISSUE THREAD

**Issue by bgoktugozdemir** [flutter/website#5509]
Page URL: https://flutter.dev/docs/cookbook/testing/unit/mocking.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/unit/mocking.md

Description of issue:
**2. Create a function to test**
**http.get()** method takes **Uri** parameter normally, but in the cookbook, it is taking String parameter instead of Uri. Possibly, it hasn't updated, yet.

You can find the code in the cookbook below.
`final response =
      await client.get('https://jsonplaceholder.typicode.com/posts/1');`

**4. Write a test for each condition**
The same problem with Section 2.

`when(client.get('https://jsonplaceholder.typicode.com/posts/1'))
          .thenAnswer((_) async => http.Response('{"title": "Test"}', 200));`
`when(client.get('https://jsonplaceholder.typicode.com/posts/1'))
          .thenAnswer((_) async => http.Response('Not Found', 404));`

Current versions:
Flutter Stable 2.0.2
http: 0.13.0

I will fix this problem with a PR.

**Comment by bgoktugozdemir** [comment]
When I checked the source code of the website, I saw that it is already updated. But the website is not updated yet.

**Comment by sfshaza2** [comment]
@bgoktugozdemir, I just [landed that PR](https://github.com/flutter/website/pull/5492/files) a couple of hours ago.  It looks updated to me. Could it be a browser caching issue?

cc @miquelbeltran

**Comment by bgoktugozdemir** [comment]
> @bgoktugozdemir, I just [landed that PR](https://github.com/flutter/website/pull/5492/files) a couple of hours ago. It looks updated to me. Could it be a browser caching issue?
> 
> cc @miquelbeltran

Yes, it is updated. I saw the PR after the issue. Thanks for your reply.
