### ISSUE TITLE
'Adding a Flutter screen to an Android app' page issue

### ISSUE THREAD

**Issue by yivan4** [flutter/website#5511]
Page URL: https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/add-to-app/android/add-flutter-screen.md

Description of issue:
The layout and code snippets are broken and confusing on "Step 2: Launch FlutterActivity" and onward.

**Comment by sfshaza2** [comment]
Goodness, this generated page is something of a mess. I _believe_ that that first note to import the Android embedding file should be the extent of the note, but the rest of the page is included in that note. This page has the complication that it uses code excerpts _and_ tabs for the Java/Kotlin versions.

@miquelbeltran, can you take a look at this?

**Comment by miquelbeltran** [comment]
oh there's definitely something broken, I will take a look!

**Comment by yivan4** [comment]
Oh yay, thanks @miquelbeltran for fixing! I'll close this issue now.
