### ISSUE TITLE
'Hero animations' page issue

### ISSUE THREAD

**Issue by Daynight-Himmat** [flutter/website#5512]
Page URL: https://flutter.dev/docs/development/ui/animations/hero-animations.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/animations/hero-animations.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by sfshaza2** [comment]
Nothing listed. Closing.
