### ISSUE TITLE
'Integration testing' page issue: incomplete configuration

### ISSUE THREAD

**Issue by Ahmadre** [flutter/website#5525]
Page URL: https://flutter.dev/docs/testing/integration-tests/
Page source: https://github.com/flutter/website/tree/master/src/docs/testing/integration-tests/index.md

Description of issue:

I started a new project and I couldn't run the tests on test lab and they were always skipped.

After I found this very good tutorial: https://blog.codemagic.io/codemagic-flutter-integration-tests-firebase-test-lab/

it's more clear and I wished I knew this earlier on flutter.dev. The Android configuration steps are missing in gradle and MainActivityTest

**Comment by sfshaza2** [comment]
Hm. Is this your area of expertise, @blasten?

**Comment by Ahmadre** [comment]
@sfshaza2 by the way I found the same configuration here: https://pub.dev/packages/integration_test#android-device-testing

**Comment by Ahmadre** [comment]
They're listed here: https://flutter.dev/docs/testing/integration-tests#android-setup

Solved :)
