### ISSUE TITLE
Document which directories to cache on CI for faster builds

### ISSUE THREAD

**Issue by shouichi** [flutter/website#5526]
Hi,

It would be nice if there is documentation describes which directories to cache on CI for faster builds. It is not obvious which directories to cache because there are many candidates such as `~/.pub-cache`, `build`, `ios/Pods`.

Thanks!

**Comment by sfshaza2** [comment]
Interesting question. @goderbauer, who might have this expertise?

**Comment by goderbauer** [comment]
I believe it is a good idea to cache `.pub-chache` - we do that on our CI as well. Not sure about any other directories. Maybe @jonahwilliams or @xster know?

**Comment by jonahwilliams** [comment]
We actually stopped caching .pub-cache as far as I could tell, because the cost of uploading it to CI and then downloading it again was slower than only downloading it from pub.dev. YMMV based on network cost and data center location

**Comment by sfshaza2** [comment]
@shouichi, since there doesn't seem to be any iron clad advice here (and it may vary for different environments), I'm going to close this.  Thx!

**Comment by shouichi** [comment]
Thanks for the confirmation. Just mentioning that the recommended way does not exist may help. Anyway, thanks again!
