### ISSUE TITLE
'Visual Studio Code' page issue

### ISSUE THREAD

**Issue by RandalSchwartz** [flutter/website#5534]
Page URL: https://flutter.dev/docs/development/tools/vs-code.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/vs-code.md

Description of issue:

Doesn't seem to mention Flutter Desktop yet.  I know, mere days after #flutterengage. :)

**Comment by sfshaza2** [comment]
Yup! Also, the web note is now wrong. You no longer have to enable web, you just get it. As always, PRs welcome.  ;)
