### ISSUE TITLE
[typo] Fix typo in React Native to Flutter widgets comparison table

### ISSUE THREAD

**Issue by diosney** [flutter/website#5535]
(At https://flutter.dev/docs/get-started/flutter-for/react-native-devs)

The `LinearProgressIndicator`'s description states that is 

> A widget that shows progress along a circle.

 and should be:

> A widget that shows progress along a line.

or something similar.

![image](https://user-images.githubusercontent.com/1340074/112237538-42ef9280-8c19-11eb-9bab-b10287bb0e55.png)

**Comment by Tapaswi846580** [comment]
It’s fixed, you can check and can close this issue.
