### ISSUE TITLE
'Integration testing' page issue

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#5552]
Page URL: https://flutter.dev/docs/testing/integration-tests/
Page source: https://github.com/flutter/website/tree/master/src/docs/testing/integration-tests/index.md

Feature Request
Since widget and integration tests have the same API now, how do we make a directory of shared code? Seems like this would be a common request? Or maybe it's too simple, but still, documentation is so good..
https://stackoverflow.com/questions/66824928/how-do-i-make-a-shared-directory-to-share-code-in-flutter-between-integration-te

**Comment by sfshaza2** [comment]
@johnpryan, can you address this?  Thx!

**Comment by johnpryan** [comment]
Hi @neiljaywarner, yes you can share code that uses `package:flutter_test`. 

You could add a file somewhere in your package (e.g. `lib/my_shared_test_code.dart`) and write helper functions:

```dart
import 'package:flutter_test/flutter_test.dart';

void checkForLocationString(WidgetTester tester) {
    await tester.pumpAndSettle();
    expect(find.text('Getting location...'), findsOneWidget);
}
```

Then you could import that file in your widget test file and integration test file using a `import 'package:my_app/my_shared_test_code.dart'`.

Hope this helps!

**Comment by neiljaywarner** [comment]
It kinda feels like you are modifying the SUT.
But I guess it works...

Does the release build process "just work" to keep it out of the final ipa and apk

**Comment by johnpryan** [comment]
Yes, any unused code will be tree shaken at build time. You could move the shared test code into different package if you prefer.

**Comment by neiljaywarner** [comment]
@johnpryan  @sfshaza2 thank you
