### ISSUE TITLE
Examples on webpage (e.g. in cookbook) need to be migrated to null safety

### ISSUE THREAD

**Issue by goderbauer** [flutter/website#5569]
In https://github.com/flutter/flutter/issues/79376 it was mentioned that this example is not null safe yet: https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments#interactive-example

There are probably more that need to be migrated.

**Comment by sfshaza2** [comment]
Yup, we are working on that, @goderbauer.  Thx! 

cc @miquelbeltran

**Comment by miquelbeltran** [comment]
On it :)
