### ISSUE TITLE
Add macOS code to 'Writing custom platform-specific code' page

### ISSUE THREAD

**Issue by RoddeRodRod** [flutter/website#5571]
Page URL: https://docs.flutter.dev/platform-integration/platform-channels
Page source: https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/platform-channels.md

Description of issue:
Please add a description how to write custom platform-specific code for macOS.

Page: https://flutter.dev/docs/development/platform-integration/platform-channels#step-4-add-an-ios-platform-specific-implementation

**Comment by sfshaza2** [comment]
Our desktop docs are definitely not fully fleshed out yet.

**Comment by atsansone** [comment]
This was fixed in https://github.com/flutter/website/pull/8489. Closing.
