### ISSUE TITLE
Add Flutter to existing Web App

### ISSUE THREAD

**Issue by Gene-Dana** [flutter/website#5573]
Hi there everyone ! I see that we already have a couple documents about [adding Flutter](https://flutter.dev/docs/development/add-to-app) to existing Android and iOS apps, and one of the questions I hear the most is 'How can we add Flutter to an existing Web App?' or vice versa.

Before Vue became very popular, I remember that this capability really convinced me to invest the time and energy to learn and understand Vue. With it's popularity now, it seems like I was not the only one ! 

I did a little investigation and I'm not sure if this is even possible ! If it is, I would like to know how ! Whether that means adding in a script directly to the index.html or perhaps editing the built main.dart.js, I think it would really help convince users to adopt Flutter Web as real contender in the web framework scene.

And.. of course, adding this into the docs ! 

Anything I can do to help, please let me know. I would love to extend our value proposition of flexibility into this domain !

**Comment by sfshaza2** [comment]
I don't know the answer. @mariamhas @johnpryan, can you weigh in?

**Comment by johnpryan** [comment]
This isn't a workflow we support through our tools right now, but you can use an `<iframe>` element that points to the Flutter app.

**Comment by sfshaza2** [comment]
That's a good point, @johnpryan. @Gene-Dana, if this is an important feature for you, file an issue on the flutter/flutter repo, or perhaps someone already has and you can upvote it. Also, we do pay attention to our quarterly user satisfaction surveys to see what features are most important to our devs.

I'm closing this issue.

**Comment by Gene-Dana** [comment]
> This isn't a workflow we support through our tools right now, but you can use an `<iframe>` element that points to the Flutter app.

Perhaps this is a document that we can add to the site?

**Comment by johnpryan** [comment]
> Perhaps this is a document that we can add to the site? Or, since it is unsupported this is not something that would be appropriate there?

I was going to suggest we add it to the web FAQ, but [it looks like we already have](https://flutter.dev/docs/development/platform-integration/web#how-do-i-embed-a-flutter-web-app-in-a-web-page)

**Comment by Gene-Dana** [comment]
Wow awesome thank you!
