### ISSUE TITLE
'Test drive' update page

### ISSUE THREAD

**Issue by GustavoFenilli** [flutter/website#5579]
Flutter's web page has a message:
> Do you want to run your Flutter app on the web? The web version of Flutter is available on the beta channel. To try it out, check out the Write your first Flutter app for the web codelab.

I think this should be updated, as flutter for web is inside the stable channel meaning those steps are not needed anymore.

**Comment by sfshaza2** [comment]
Agreed! @GustavoFenilli, can you tell us which page this was?

**Comment by GustavoFenilli** [comment]
its on [get started/test drive](https://flutter.dev/docs/get-started/test-drive?tab=vscode) page.
