### ISSUE TITLE
'Delete data on the internet' page issue

### ISSUE THREAD

**Issue by Lettuce222** [flutter/website#5583]
Page URL: https://flutter.dev/docs/cookbook/networking/delete-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/delete-data.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
This page shows an example that uses `http.gets` `http.delete`.
In that example, the first argument of these is String 'https://jsonplaceholder.typicode.com/albums/1'.

But it should be Uri Object.
So example should be fixed like below
```
http.get(Uri.parse('https://jsonplaceholder.typicode.com/albums/1'));

final http.Response response = await http.delete(
  Uri.parse('https://jsonplaceholder.typicode.com/albums/$id'),
  headers: <String, String>{
    'Content-Type': 'application/json; charset=UTF-8',
  },
);
```

**Comment by piedcipher** [comment]
https://flutter.dev/docs/cookbook/networking/authenticated-requests
https://flutter.dev/docs/cookbook/networking/update-data

Also, There 2 pages are using String instead of Uri.

Shall I add these changes in my PR?
