### ISSUE TITLE
Add warning about web platform target on 'Read and write files' page

### ISSUE THREAD

**Issue by piedcipher** [flutter/website#5596]
Page URL: https://docs.flutter.dev/cookbook/persistence/reading-writing-files
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/persistence/reading-writing-files.md

Description of issue:

This page should mention that this guide is for non-web apps because `dart:io` isn't supported for the web platform. path_provider plugin has no support for the web as of now.

**Comment by sfshaza2** [comment]
Great point. Maybe we should expand this page to cover web. @johnpryan, what say you?

**Comment by johnpryan** [comment]
Yeah we should add a note / warning at the top of this page - it's mobile / desktop only.

For web apps, we should recommend that apps use a backend like Firebase or the [shared_preferences](https://pub.dev/packages/shared_preferences) package for small amounts of data.

**Comment by piedcipher** [comment]
dart:html might be used to do r/w Files.

**Comment by johnpryan** [comment]
Maybe, but it's a different File class:

- [dart:io File](https://api.dart.dev/stable/2.12.2/dart-io/File-class.html)
- [dart:html File](https://api.dart.dev/stable/2.12.2/dart-html/File-class.html)
