### ISSUE TITLE
Fix multiple responsiveness issues

### ISSUE THREAD

**Issue by ishandeveloper** [flutter/website#5605]
Navigation bar content overflows at different breakpoints, and shows different behavior in different browsers. 

#### Issue 1 (Microsoft Edge) - Details 

The navigation bar content, mainly the 'Get Started' button gets cropped when viewed at 788px width
<pre>
Browser : Microsoft Edge (Chromium) Version 89.0.774.68
Resolution : 778px x 855px
</pre>
<img src="https://user-images.githubusercontent.com/54989142/114244677-89c8e080-99ac-11eb-9f91-6c184e7a2373.png" width="80%" >

#### Issue 2 (Google Chrome) - Details 

The navigation bar content overflows, when viewed at 768px width, and causes a horizontal scroll in the page
<pre>
Browser : Google Chrome Version 89.0.4389.114
Resolution : 768px x 847px
</pre>
<img src="https://user-images.githubusercontent.com/54989142/114245429-1aec8700-99ae-11eb-91a4-ad195677ed53.png" width="80%" >

#### Issue 3 (Google Chrome) - Details

On mobile screens, for all devices having viewport width of less than 398px , the hero images overflows and causes a horizontal scroll
<pre>
Browser : Google Chrome Version 89.0.4389.114
Resolution : 398px x 847px
</pre>
<img src="https://user-images.githubusercontent.com/54989142/114245688-93534800-99ae-11eb-8485-94650299b660.png" width="50%">

All these are some media-query css issues and can be fixed with ease. I'd love to work on this issue, if someone can assign it to me.

**Comment by sfshaza2** [comment]
Go for it, @ishandeveloper!

**Comment by ishandeveloper** [comment]
@sfshaza2 I was able to resolve the third issue listed here with the 'hero images' in the repository.

But, for the navbar issues, it seems like the styling for that is enclosed in a submodule, which is a part of ([dart-lang/site-shared](https://github.com/dart-lang/site-shared)) . 

Also, I found that this bug was introduced after we added 'Flutter Engage' as a navigation item in the header. Seems like originally the css for navigation header was written to support a maximum of 3 navigation items (Docs, Showcase & Community)

One workaround for this is to use inline css styling for all the nav-items, and that should fix this issue without introducing any additional changes in the submodule. But, that seems doesn't seem like a good way to maintain the code-quality in long run.

So, how should we proceed?

**Comment by parlough** [comment]
Thanks everyone. The old home page which had many of these problems no longer exists and "Flutter engage" was removed from the header. As a result, I can't reproduce any of these issues currently on multiple browsers.

If anyone notices similar issues again, please open a new issue for those specific cases. Thanks again!
