### ISSUE TITLE
Make 'Flutter architectural overview' page available as PDF

### ISSUE THREAD

**Issue by xiaoxiaohaozi** [flutter/website#5622]
Page URL: https://flutter.dev/docs/resources/architectural-overview.html
Page source: https://github.com/flutter/website/tree/master/src/docs/resources/architectural-overview.md

Description of issue:
    My Dear Editors, Can you publish the flutter official  article in format of PDF. I study flutter to take notes when something I don't know. PDF is very useful for this, but web html is not.
    I hope to you can publish the article in format of PDF.
   Best Regards.

**Comment by sfshaza2** [comment]
Hi, @xiaoxiaohaozi! I know it's not perfect, but here is a PDF of that page. I created it on my Mac by selecting "print" and then "save as PDF". I am leaving this issue open as we do get requests for converting pages to PDF and that would be nice the next time we rework the website. I couldn't see a way to remove the side navigation panel, but maybe you could physically cut it off and glue the rest of the page to a new white piece of paper for notes. OR, perhaps you have the ability to edit PDF files but, sadly, I do not.

[FlutterArchitecturalOverview.pdf](https://github.com/flutter/website/files/6312604/FlutterArchitecturalOverview.pdf)

**Comment by atsansone** [comment]
This could be done as @sfshaza2 outlined and attached. Closing issue as fixed.
