### ISSUE TITLE
'Debugging your add-to-app module' page issue

### ISSUE THREAD

**Issue by WunGCQ** [flutter/website#5632]
Page URL: https://flutter.dev/docs/development/add-to-app/debugging.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/add-to-app/debugging.md

the following part of document is out of date, after the PR [#63336](https://github.com/flutter/flutter/pull/63336) was merged.

[debugging-specific-instances-of-flutter](https://flutter.dev/docs/development/add-to-app/debugging#debugging-specific-instances-of-flutter)

lets see how to deal with this part.
maybe remove it will be the best choice, and just looking for new solution.

**Comment by sfshaza2** [comment]
Can you comment, @xster? I'm happy to remove the section.

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/5633
