### ISSUE TITLE
Split Android and iOS plugin capabilities in note on 'Writing custom platform-specific code' page

### ISSUE THREAD

**Issue by mvanbeusekom** [flutter/website#5636]
### Page URL

https://docs.flutter.dev/platform-integration/platform-channels

### Page source

https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/platform-channels.md

### Description of issue

The article "Writing custom platform-specific code" contains the following note:

>Note: If desired, method calls can also be sent in the reverse direction, with the platform acting as client to methods implemented in Dart. A concrete example of this is the [quick_actions](https://pub.dev/packages/quick_actions) plugin.

The quick_action plugin however only uses method channels in a reverse direction on iOS. On Android this technique is not utilised which causes disappointed people looking for an Android example (see issue flutter/flutter#65595). 

The camera plugin has a great isolated Android example (see [DartMessenger.java](https://github.com/flutter/plugins/blob/master/packages/camera/camera/android/src/main/java/io/flutter/plugins/camera/DartMessenger.java)) which can be used by developers to learn how to use this technique. 

Maybe this specific note can be extended to mention the camera plugin for an Android example and refer to the quick_action plugin for the iOS example?

**Comment by sfshaza2** [comment]
Excellent feedback! Thanks for this info and this issue.
