### ISSUE TITLE
Create guidance page for Flutter + Google APIs

### ISSUE THREAD

**Issue by kevmoo** [flutter/website#5637]
- [x] https://pub.dev/packages/google_sign_in
  - example here - https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/example/lib/main.dart
  - Work with @kevmoo to get the right demo
  - Make sure documentation about registering application is correct
- [x] https://pub.dev/packages/googleapis
- [ ] Add link to go/google-apis

**Comment by sfshaza2** [comment]
Discussed this offline with @kevmoo and we decided that it belongs under /docs/development/data&backend, right after the Firebase entry.
