### ISSUE TITLE
'Hosting native Android and iOS views in your Flutter app with Platform Views' page issue

### ISSUE THREAD

**Issue by cooftechdev** [flutter/website#5646]
Page URL: https://flutter.dev/docs/development/platform-integration/platform-views.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/platform-views.md

Description of issue:
not contructor NativeViewFactory

**Comment by sfshaza2** [comment]
@cooftechdev, the page does have a suggested implementation for NativeViewFactory. Can you explain the issue?

**Comment by sfshaza2** [comment]
I'm closing this issue. Please re-open when/if you have more info. Thx
