### ISSUE TITLE
'Adding Flutter to Android' page issue

### ISSUE THREAD

**Issue by bat216** [flutter/website#5649]
Page URL: https://flutter.dev/docs/development/add-to-app/android/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/add-to-app/android/index.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by micpap25** [comment]
Hi @bat216 , it looks like you forgot to describe your problem. Could you add a description so we can solve your issue?

**Comment by sfshaza2** [comment]
Nothing listed. Closing.
