### ISSUE TITLE
'Write your first Flutter app on the web' page issue on step 3

### ISSUE THREAD

**Issue by j-vasil** [flutter/website#5666]
Page URL: https://flutter.dev/docs/get-started/codelab-web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab-web.md

Description of issue:
In step 3.1, the instructions say to add this code:
```
  AnimatedProgressIndicator({
    @required this.value,
  });
```
This causes an error message in VSCode (related to the default for 'value' being null.  The 'Complete sample' code at the bottom of the page removes the ampersand:
```
  AnimatedProgressIndicator({
    required this.value,
  }); 
```
Without the ampersand, this builds and runs correctly.  

p.s. I suspect this is just a typo but I'm still too much of a Flutter/Dart newbie to be comfortable changing the page myself. Especially after I saw discussion about this being related to 'required' becoming a keyword sometime before October of last year ([https://github.com/flutter/flutter/issues/67366](url)).

**Comment by JuYeong0413** [comment]
Seems like the codes are not migrated to null safety.
If you are using null safe Dart(Dart SDK higher than 2.12), `required` is correct.
For Dart SDK lower than 2.12, `@required` should be used.

**Comment by sfshaza2** [comment]
@JuYeong0413 is correct. We are migrating the flutter.dev website to use null safety, which is what we recommend as of Flutter 2 (launched on 3/3).  Closing.
