### ISSUE TITLE
change variable's name from `Name`  to `name` at Lab Building a Cupertino app with Flutter 

### ISSUE THREAD

**Issue by AhmadLpsn** [flutter/website#5669]
[at 8. Add customer info](https://codelabs.developers.google.com/codelabs/flutter-cupertino?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F#7)
`class _ShoppingCartTabState extends State<ShoppingCartTab> {`
`  String? Name;    // ADD FROM HERE` 🤺
`  String? email;`
`  String? location;`
`  String? pin;`
`  DateTime dateTime = DateTime.now();`

**Comment by sfshaza2** [comment]
@domesticmouse, FYI.

**Comment by domesticmouse** [comment]
Thanks for the report @AhmadLpsn. The fix is in process.
