### ISSUE TITLE
'Navigation and routing' page suggestion

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/website#5688]
Page URL: https://flutter.dev/docs/development/ui/navigation/
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/navigation/index.md

Description of suggestion: This [article](https://aliyazdi75.medium.com/lets-make-the-flutter-navigator-2-bc5953251c3e) is really helpful for flutter developers in implementing navigation 2 and [suggested](https://github.com/aliyazdi75/gallery/discussions/5#discussion-3307053) by one of the flutter maintainer. It will be a good idea if you add this here.

**Comment by sfshaza2** [comment]
Hi, @aliyazdi75! Thanks for submitting this. I ran it past our nav 2 guru and discovered that there are plans for some router docs in the works. Closing.

**Comment by aliyazdi75** [comment]
Hi, @sfshaza2,
Ok, thanks.
