### ISSUE TITLE
Include instructions to uninstall Flutter

### ISSUE THREAD

**Issue by Sameerkash** [flutter/website#5695]
Some individuals wanted to uninstall flutter and its folders completely. 
We should include instructions to delete the folders of the flutter installation and the .pub_cache folders 

related to flutter/flutter#30014 and flutter/flutter#29278

**Comment by Sameerkash** [comment]
cc @Sfshaza, 

I'll take this up if you can suggest where this should go. I was thinking the same page as install flutter, as it shouldn't take up too much space.

**Comment by sfshaza2** [comment]
I think this is a great idea, @Sameerkash, but I also think it needs to be a new page. And it could be tricky to write. For example, it should probably cover:

- How to uninstall Flutter, but keep Dart (if that's what they want to do). I've [filed an issue](https://github.com/dart-lang/site-www/issues/3187) on the dart.dev repo about adding similar info for Dart. This page can then link to that.
- How to uninstall Android Studio, (if that's what they want to do)? (There is probably info on the Android Studio site about how to uninstall. We can link to that.)
- Any instructions specific to the various platforms (Ubuntu, Mac, Linux, Windows)?
- How might the instructions look if they installed with snap, or git clone, or some unofficial homebrew recipe?
- If they've reconfigured the PUB_CACHE environment variable, they'll need to remove the cache from that location
- Not critical, but they might want to update their PATH.

Finally, I'd want a friendly "Come back all, y'hear?" sort of message at the end.

I'd add the new page here:  https://flutter.dev/docs/development/tools/sdk/uninstall. It would also need to be added to the side nav (/src/_data/sidenav.yml).

Are you willing to take a stab at this new page? I'm willing to review, etc.

**Comment by Sameerkash** [comment]
@sfshaza2 sure thing! I've been trying to write for dart - site, 
So I'd love to write a page for flutter as well. 

Should I open a WIP PR? Or would you like to review a Google doc ( as kevmoo preferred this) ? And then I can paste the content to the repo. 

I'll start asap whichever way you suggest.

**Comment by sfshaza2** [comment]
I definitely prefer a Google doc! Thanks for asking!

**Comment by sfshaza2** [comment]
Also, @parlough had [some great input on the issue](https://github.com/dart-lang/site-www/issues/3187) I filed on dart.dev.

**Comment by sfshaza2** [comment]
Also, when you are ready for me to take a look, share the doc with shaza@ and you can guess the rest.  ;)

**Comment by Sameerkash** [comment]
> Also, @parlough had [some great input on the issue](https://github.com/dart-lang/site-www/issues/3187) I filed on dart.dev.

Surely will keep this in mind! Sounds most appropriate for the dart install. 

Will consider flutter specific like snap store and others for this case. 

Will send a doc link soon.

**Comment by Sameerkash** [comment]
@sfshaza2 I've sent an initial draft, please check your inbox for the doc link

**Comment by Sameerkash** [comment]
@Sfshaza Shall I make a PR with the changes you suggested?

**Comment by sfshaza2** [comment]
Sure! I am sure I will have more edits, but let's get it going!

**Comment by atsansone** [comment]
Add this change at the same time: https://github.com/flutter/website/issues/5750
