### ISSUE TITLE
FAQ/section on switching back

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#5699]
Switching back to stable version from beta is a bit confusing.
Perhaps some directions/guidance around that; switching to beta to get features/ dependencies you expect will be in stable "in time" might be common.

**Comment by micpap25** [comment]
Does this guide not work for you? https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels
This is included in the "Flutter SDK releases" page. 
I just followed it and had no issue switching from `stable` to `beta` and back again.

**Comment by sfshaza2** [comment]
And, more critically, does this [flutter.dev page](https://flutter.dev/docs/development/tools/sdk/upgrading#switching-flutter-channels) not have the info you need? We could add a link to the wiki page if needed, but it would help to know what specific issues you had. We could also beef up the instructions on this page, if needed.

**Comment by neiljaywarner** [comment]
Thanks for that point
The main page you linked makes it sound like you can't go back that you can
only upgrade

Tbh I forgot you could go to stable channel and go back..

I probably should have tried getting a certain tag or something but didn't
get around to it
Tbh I was discouraged by the unidentified dev bug but I'm happy it was
fixed so fast

In other words you can't "un upgrade" but you can downgrade sorta by
picking a more stable channel

It could be a little confusing bc of course the stable channel would be the
current one not the one you left

I guess we need to pin versions more with flutterw by passy and or pubspec

Maybe you can link to some directions like that some day.

I would think the use case of wanting all devs and ci/cd servers - even
those without cache - to be on the same version would be very common



....sent from my phone

**Comment by atsansone** [comment]
The [Upgrading Flutter page](https://docs.flutter.dev/release/upgrade#switching-flutter-channels) does cover this issue. Closing this issue.

**Comment by neiljaywarner** [comment]
We need a downgrading or reverting page 🙂

....sent from my phone
