### ISSUE TITLE
behnam khani

### ISSUE THREAD

**Issue by behnamkhaniofficial** [flutter/website#5706]
# برنامه نویسی رایانه‌
برنامه‌سازی رایانه‌ای یا برنامه‌نویسی رایانه‌ای (به انگلیسی: computer programming) همان فرایند طراحی و ساخت یک برنامه رایانه‌ای اجراپذیر برای به‌دست‌آوردن یک نتیجه رایانشی خاص، یا انجام یک عمل خاص است. برنامه‌نویسی شامل عمل‌هایی مثل: تحلیل، ایجاد الگوریتم‌ها، رخ‌نمانگاری دقت الگوریتم‌ها و مصرف منابع، و پیاده‌سازی آن الگوریتم‌ها به یک زبان برنامه‌نویسی انتخاب شده است که معمولاً به آن کدگذاری (کدینگ) گفته می‌شود کد منبع یک برنامه به یک یا بیشتر زبان نوشته می‌شود که این زبان برای «برنامه‌نویس» قابل فهم است (به جای کد ماشین که به صورت مستقیم توسط واحد پردازش مرکزی اجرا می‌شود). هدف از برنامه‌نویسی، پیداکردن ترتیبی از دستورالعمل ها است که انجام یک عمل را در یک رایانه، معمولاً برای حل‌کردن یک برنامه داده شده، خودکارسازی می کند (که می تواند تا حد یک سیستم‌عامل پیچیده باشد). بنابراین، یک برنامه‌نویسی حرفه‌ای نیاز به مهارت در چندین موضوع متفاوت دارد، که شامل دانش دامنه کاربردی، الگوریتم‌های خاص، و منطق صوری است.
________________________________________________________________________________________________________________

> **
> به تیم متنوعی از طراحان
> >  و مهندسان نرم افزار ، کیفیت و خوشبختی بپیوندید.
> > در تقاطع بازاریابی ، طراحی و مهندسی نقشی استراتژیک و فنی داشته باشید.
> > نقشی اساسی در استراتژی و تحقق یکی از اهداف اصلی ما برای سال 2021 بازی کنید: باز کردن قفل رشد کاربران جذاب در برنامه های Android و iOS 
> > برای بهبود فعال سازی ، تعامل و حفظ برنامه های تلفن همراه خود ، فرصت هایی را بیابید و ابتکاراتی را رهبری کنید.
> >
> ** 
[ANDROID]( https://Android.com)

![LogoMaker_۲۸۰۴۲۰۲۱_۰۸۰۱۱۹](https://user-images.githubusercontent.com/76747901/116460267-1c59f280-a87c-11eb-99df-66901c7f348e.png)
# behnam khani
Page URL: https://flutter.dev/docs/get-started/learn-more.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/learn-more.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

<a class="twitter-follow-button"
  href="https://twitter.com/behnamofficials">
Follow @behnamkhaniofficial Twitter Dev</a>
<a class="instagram-follow-button"
  href="https://instagram.com/behnamkhaniofficial">
Follow @behnamkhaniofficial instagram Dev</a>
<a class="Facebook-follow-button"
  href="https://Facebook.com/behnamkhaniofficials">
Follow @behnamkhaniofficial Facebook Dev</a>
<a class="behnamkhanitabriz-follow-button"
  href="http://aparat.com/behnamkhanitabriz">
Follow #5705 behnamkhanitabriz FILMNO Videos </a>

Description of issue:

**Comment by sfshaza2** [comment]
Spam. Closing.
