### ISSUE TITLE
Show Dart SDK versions along with the Flutter SDK versions

### ISSUE THREAD

**Issue by jayoung-lee** [flutter/website#5710]
Users from the Q1 survey asked to make it easier to see what Dart SDK is included with a particular Flutter version. 

Can we add a column to the table shown in the image below (on the [download page](https://flutter.dev/docs/development/tools/sdk/releases))? Please also suggest other areas where this information might be helpful. 

![image](https://user-images.githubusercontent.com/11873270/116521478-e111f080-a888-11eb-884a-d061cd114f24.png)

**Comment by micpap25** [comment]
Based on https://github.com/flutter/website/blob/20a4f9214bb0580fdaba3439c35b26daa13071e7/src/docs/development/tools/sdk/_os.md and https://github.com/flutter/website/blob/20a4f9214bb0580fdaba3439c35b26daa13071e7/src/_assets/js/archive.js : 

In this segment:
```
var fetchFlutterReleases = function (os, callback, errorCallback) {
  // OS: windows, macos, linux
  var url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_" + os + ".json";
  $.ajax({
    type: "GET",
    url: url,
    dataType: "json",
    success: function (data) { callback(data, os); },
    error: function (xhr, textStatus, errorThrown) {
      if (errorCallback) errorCallback(os);
    }
  })
}
```

You can see that the information is being fetched from a JSON file. Based on https://storage.googleapis.com/flutter_infra/releases/releases_windows.json , it seems this JSON file doesn't contain the Dart SDK version. To address the issue, this needs to be added to the JSON first.

**Comment by parlough** [comment]
Implemented by https://github.com/flutter/website/pull/6736
