### ISSUE TITLE
Expand documentation for creating custom engine embedders

### ISSUE THREAD

**Issue by zanderso** [flutter/website#5715]
This is an issue to track creation of a new page at `https://flutter.dev/embedded` that lists resources and documentation needed to create a custom embedding of the Engine. Here's the list that we discussed over chat:
* https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedders
* Doc comments in https://github.com/flutter/engine/blob/master/shell/platform/embedder/embedder.h
* https://flutter.dev/docs/resources/architectural-overview
* Small self-contained example in https://github.com/flutter/engine/tree/master/examples/glfw

@chinmaygarde @cbracken @RedBrogdon @domesticmouse @eseidelGoogle

**Comment by zanderso** [comment]
I also found this issue with some possibly helpful info from @chinmaygarde: https://github.com/flutter/flutter/issues/31043

**Comment by sfshaza2** [comment]
Published a new page. It's a start!  https://github.com/flutter/website/pull/5770
