### ISSUE TITLE
'Integration testing' page issue

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#5725]
Page URL: https://flutter.dev/docs/testing/integration-tests/

Description of issue:
Extended options has a broken link
eg go to https://github.com/flutter/flutter/tree/master/packages/integration_test#driver-entrypoint
(by going to https://flutter.dev/docs/testing/integration-tests#directory-structure and using "See integration_test_usage link)

see teh sentence "You can also use different driver scripts to customize the behavior of the app under test. For example, FlutterDriver can also be parameterized with different options. See the extended driver for an example."
the extended drive link is broken (and api.flutter.dev has a UI/UX "newbies beware" "vibe" to it compared to flutter.dev) - not that it's bad, it's just less amazing than flutter.dev :)

**Comment by micpap25** [comment]
Looks like @TNorbury fixed this with https://github.com/flutter/flutter/pull/81565#issue-627985907 .
Can you confirm that the link works for you @neiljaywarner ?
Thanks.

**Comment by neiljaywarner** [comment]
@sfshaza2 @micpap25 this can be closed; thank you .
