### ISSUE TITLE
'An introduction to integration testing' page issue

### ISSUE THREAD

**Issue by niccord** [flutter/website#5727]
Page URL: https://flutter.dev/docs/cookbook/testing/integration/introduction.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/integration/introduction.md

Description of issue: \
On point 5 Write the tests, you declare a `FlutterDriver driver` variable which is a non-nullable reference. \
Since an initializer expression can not be given, this returns a compile error.

Here's a screenshot of my IDE:
![image](https://user-images.githubusercontent.com/2854279/116982556-373bc500-acc9-11eb-9d45-ca3aa32f5e4b.png)

A fix can be provided by setting the variable as nullable.

**Comment by sfshaza2** [comment]
@miquelbeltran has been converting all cookbook recipes to null safety (and also to use the code excerpt form of analysis). I may have to close your PR, depending on its status.

**Comment by miquelbeltran** [comment]
Unfortunately the change in the PR is not enough, the code in the page needs to be extracted and copied over to a project to be migrated to null safety. That page is on my TODO list.

**Comment by sfshaza2** [comment]
That's what I thought. Thanks for your PR, @niccord, but I am closing this PR.
