### ISSUE TITLE
Explain how to prevent the Android License acceptance error on 'Getting Started' pages

### ISSUE THREAD

**Issue by deive** [flutter/website#5735]
Page URL: https://docs.flutter.dev/get-started/install/linux
Page source: https://github.com/flutter/website/tree/master/src/desktop.md

Description of issue:

Missing a required dependency of the Android SDK Command-line tools. See: https://stackoverflow.com/questions/64708446/flutter-doctor-android-licenses-exception-in-thread-main-java-lang-noclass

**Comment by sfshaza2** [comment]
@domesticmouse, FYI
