### ISSUE TITLE
Add an exit survey to the "Uninstall Flutter" page

### ISSUE THREAD

**Issue by jayoung-lee** [flutter/website#5750]
Asking users why they're uninstalling Flutter. Details/discussions to follow.

**Comment by atsansone** [comment]
@jayoung-lee : Do you have a set of survey questions prepared?

**Comment by jayoung-lee** [comment]
We don't have one yet. We can create a survey if anyone's interested in helping and following up on the results. 

cc: @InMatrix

**Comment by InMatrix** [comment]
The blocker here is we don't know where and when to show that survey unless we provide an Uninstall Flutter guide or tool first. As an alternative, the new just-in-time survey tool can potentially serve a survey to users who become inactive for sometime but still have Flutter installed.

**Comment by atsansone** [comment]
@jayoung-lee : Is this still a concern? I have the Uninstall PR in motion. https://github.com/flutter/website/pull/10038
