### ISSUE TITLE
Explain, link `group` function on 'An introduction to unit testing' page

### ISSUE THREAD

**Issue by RonyBrosh** [flutter/website#5761]
Page URL: https://docs.flutter.dev/cookbook/testing/unit/introduction
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/unit/introduction.md

Description of issue:
It's not really clear (at least for me) what is the use case of group keyword.
In the example, Counter is being initiated for each test so how those test are related if they don't share the same Counter instance?
I don't understand the benefit of grouping the tests by reading this document.

Also, What I would like to find on this page (and eventually found by digging the source code) is the setUp and tearDown functions.

As most Android users will have experience with those functions it worth mentioning them.
Hope it makes sense :)

**Comment by atsansone** [comment]
Link to the [group function](https://api.flutter.dev/flutter/flutter_test/group.html). Explain what it means in context.
