### ISSUE TITLE
'Add Material touch ripples' page issue

### ISSUE THREAD

**Issue by NachiketGohil** [flutter/website#5768]
Page URL: https://flutter.dev/docs/cookbook/gestures/ripples.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/gestures/ripples.md

Description of issue:

This method shown here using InkWell doesn't work...

**Comment by micpap25** [comment]
Can you explain further?
Can you share your code? Are you getting any errors? What about it isn't working?

**Comment by sfshaza2** [comment]
Yes, thanks, @micpap25! @NachiketGohil, can you provide more info?

**Comment by TahaTesser** [comment]
Closing as no information is provided, please file a new issue with all information if the problem persists
