### ISSUE TITLE
Update Information Architecture

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#5777]
Since Flutter launched 1.0, the IA hasn't scaled well and I'd like to update it. Note that the IA doesn't have to reflect the directory structure.

One thing I'd like to do is to move the release notes, which don't really belong under docs/development/tools. When I do find/grep, it's unpleasant to include those.

**Comment by parlough** [comment]
I'm going to close this in favor of the more specific issues, particularly since the specific concern listed here has been addressed.
