### ISSUE TITLE
flutter.dev/docs/resources/bug-report - link results in 404 error

### ISSUE THREAD

**Issue by leemke** [flutter/website#5780]
In filing a bug report  for flutter, I tried to follow the instructions in
in the initial text of the bug form.  It pointed to a web site:

https://flutter.dev/docs/resources/bug-report

I copied that URL and pasted it into a new tab in my browser.

I received a 404 ERROR - page not found. 

please fix this.

![Screenshot 2021-05-12 20 55 03](https://user-images.githubusercontent.com/5303630/118143489-05191a00-b3d1-11eb-968d-76a87c2f3361.png)

**Comment by micpap25** [comment]
> In filing a bug report for flutter, I tried to follow the instructions in in the initial text of the bug form.

Can you link the bug form? All official sources that I could find recommend opening an issue on the flutter/flutter repository.

**Comment by leemke** [comment]
I was filing a new flutter bug report.
In the form it listed the url for more information on what to place in the
form.
The url was https://flutter.dev/docs/resources/bug-report.
I copied that URL and pasted it into a new browser tab and
received a 404 error message.

I tried to file a bug report in flutter to note this error.
The flutter team said this is not a flutter problem.
It is a flutter website problem. Therefore I am
trying to file this bug report with what I assume
is the group that supports the flutter web site.

If you want to see the form, file a flutter bug-report.
Read the included documentation. In it you will
find the referenced url. You can just key in the
url into a browser and receive the 404 error message.

**Comment by leemke** [comment]
I guessed the problem. The url has "bug-report" and it should be
"bug-reports".

This was my copy error. my copy did not include the "s".

Thanks for your help
Larry

**Comment by leemke** [comment]
I might suggest that you change the format for the URL into a link
rather than regular text. But then again maybe not body really reads
or tries to use that reference.

**Comment by sfshaza2** [comment]
@leemke, where was the page that used the broken link? It's true that the correct link is:
https://flutter.dev/docs/resources/bug-reports
But I am unclear as to where you are seeing the incorrect link.

**Comment by leemke** [comment]
I started from the android studio.
Open my p1 project - a version of the default application ( comments
removed - it runs correctly).
menu: help/submit feedback.
Received browser page opened to:

https://issuetracker.google.com/issues/new?component=192708&template=840533&description=Build:%20AI-202.7660.26.42.7351085,%20202105101744,%20%0A%0AAI-202.7660.26.42.7351085,%20JRE%2011.0.8%2B0-b944-P17168821x64%20JetBrains%20s.r.o,%20OS%20Linux(amd64)%20v5.4.109-26059-gc7455b8ce0e0,%20screens%201187x667%0A%0AAS:%204.2.1;%20Kotlin%20plugin:%20202-1.5.0-release-764-AS8194.7;%20Android%20Gradle%20Plugin:%20(plugin%20information%20not%20found);%20Gradle:%20(gradle%20version%20information%20not%20found);%20NDK:%20from%20local.properties:%20(not%20specified),%20latest%20from%20SDK:%20(not%20found);%20LLDB:%20pinned%20revision%203.1%20not%20found,%20latest%20from%20SDK:%20(package%20not%20found);%20CMake:%20from%20local.properties:%20(not%20specified),%20latest%20from%20SDK:%20(not%20found),%20from%20PATH:%20(not%20found)%0A%0AIMPORTANT:%20Please%20read%20https:%2F%2Fdeveloper.android.com%2Fstudio%2Freport-bugs.html%20carefully%20and%20supply%20all%20required%20information
.

In the body of the page where you include your details is a paragraph
labeled:
IMPORTANT: Please read https://developer.android.com/studio/report-bugs.html
.

I copied the URL but  did not include "s.html" This resulted in a   404
errror
when I pasted it into another browser tab.

Please replace the URL with the link to the correct age

**Comment by micpap25** [comment]
Thank you @leemke 
That clarifies the issue. It seems the Android Studio plugin for Flutter is out of date. Unfortunately we cannot resolve the issue on this repository as this is not a website issue. Please file this under https://github.com/flutter/plugins .

**Comment by sfshaza2** [comment]
You are SO on top of this, @micpap25!  Michael is correct, this must be filed on that repo. Thanks for letting us know, but I am closing.
