### ISSUE TITLE
GitHub Actions CI seems to be missing for null_safety_examples folder using stable channel

### ISSUE THREAD

**Issue by hrishikesh-kadam** [flutter/website#5782]
In the [build.yml][] file, GitHub Actions CI seems to be missing for the null_safety_examples folder using stable channel.

This might be affecting many examples in the null_safety_example folder because the Action is turned off for [dev][] and [beta][] channels.

In [fetch-data][] example, [Line No 49][] of main.dart line will fail the `flutter analyze` command.

[build.yml]: https://github.com/flutter/website/blob/bb121250da3f9936e70169cbae28c2e757341897/.github/workflows/build.yml
[fetch-data]: https://github.com/flutter/website/tree/7ecd9c854491e9265038e7aaa7d90f5c431cc8f1/null_safety_examples/cookbook/networking/fetch_data
[Line No 49]: https://github.com/flutter/website/blob/7ecd9c854491e9265038e7aaa7d90f5c431cc8f1/null_safety_examples/cookbook/networking/fetch_data/lib/main.dart#L49
[dev]: https://github.com/flutter/website/pull/5463
[beta]: https://github.com/flutter/website/pull/5467

**Comment by sfshaza2** [comment]
@miquelbeltran, can you weigh in?

**Comment by hrishikesh-kadam** [comment]
@sfshaza2 @miquelbeltran I think I can solve this issue. I'll give it a try.

**Comment by miquelbeltran** [comment]
yes, I agree, something was missing because I found some errors on existing code that should have been caught by CI

Probably something missing from when we did the migration to GH Actions.

I am going to take a look as well.

**Comment by sfshaza2** [comment]
@hrishikesh-kadam, @miquelbeltran, you two ROCK.

**Comment by miquelbeltran** [comment]
thanks a lot @hrishikesh-kadam
