### ISSUE TITLE
Codelab "Using a plugin with Flutter web app" uses a FlatButton

### ISSUE THREAD

**Issue by guidezpl** [flutter/website#5801]
Step 7 uses a FlatButton for a link to the privacy policy, which is deprecated.

We should do a sweep of the codelabs for such deprecations

**Comment by domesticmouse** [comment]
Blocked on https://github.com/googlecodelabs/tools/issues/575

**Comment by domesticmouse** [comment]
Hey @guidezpl, can you point me at the file that contains a FlatButton? Looking at https://codelabs.developers.google.com/codelabs/web-url-launcher#6 only shows me a TextButton, and that's been true since approximately [March 10th](https://github.com/flutter/codelabs/pull/77).

**Comment by guidezpl** [comment]
You're right, closing
