### ISSUE TITLE
'Internationalizing Flutter apps' page issue

### ISSUE THREAD

**Issue by Reksa97** [flutter/website#5821]
Page URL: https://flutter.dev/docs/development/accessibility-and-localization/internationalization.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

Description of issue:

The links to 'Sample internationalized apps' are not working:
Minimal internationalization
https://github.com/flutter/website/tree/master/examples/internationalization/minimal
Internationalization based on the intl package
https://github.com/flutter/website/tree/master/examples/internationalization/intl_example

**Comment by piedcipher** [comment]
They are under `null_safety_examples`.

https://github.com/flutter/website/tree/master/null_safety_examples/internationalization/minimal
https://github.com/flutter/website/tree/master/null_safety_examples/internationalization/intl_example
