### ISSUE TITLE
'Internationalizing Flutter apps' page issue

### ISSUE THREAD

**Issue by mnarsely** [flutter/website#5822]
Page URL: https://flutter.dev/docs/development/accessibility-and-localization/internationalization.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: Adding an unsupported locale to Flutter is not working properly to NumberFormat and DateFormat symbols and patterns.

I am getting the following error whenever I refresh my app after changing to a newly supported language

`The following ArgumentError was thrown building:
Invalid argument(s): Invalid locale "en_US"

When the exception was thrown, this was the stack
#0      _throwLocaleError
package:intl/src/intl_helpers.dart:177
#1      verifiedLocale
package:intl/src/intl_helpers.dart:171
#2      verifiedLocale
package:intl/src/intl_helpers.dart:156
#3      new DateFormat
package:intl/…/intl/date_format.dart:266
#4      new DateFormat.yMEd
package:intl/…/intl/date_format.dart:478`

**Comment by micpap25** [comment]
Hi @mnarsely,
Can you be more specific on what the website is missing or how the website is incorrect?
If this is a personal issue, you might find more help on a site like StackOverflow. Then, if you feel like something on the website was lacking, you can let us know here.

**Comment by mnarsely** [comment]
My bad, I am taking this issue somewhere else, thank you @micpap25
