### ISSUE TITLE
'Internationalizing Flutter apps' page issue

### ISSUE THREAD

**Issue by himanshu717171** [flutter/website#5835]
Page URL: https://flutter.dev/docs/development/accessibility-and-localization/internationalization.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

Description of issue:
Because test_app depends on flutter_localizations any which doesn't exist (could not find package flutter_localizations at https://pub.dartlang.org), version solving failed.

What should I use in place of flutter_localizations?

**Comment by micpap25** [comment]
Hi, @himanshu717171,
Generally, the issues on the website's repository are used to report issues with the website itself, or things you think are incorrect on the website.
With that said, have you tried the recommendations on this GitHub issue?
https://github.com/flutter/flutter/issues/49931
Specifically, have you tried updating Flutter and Dart, and have the exact correct dependency?

**Comment by sfshaza2** [comment]
It appears, from looking at the resources that @micpap25 linked to, that this happens for one of two reasons:
1. The package needs to be imported
2. Make sure you are on the correct (latest) version of the Flutter SDK.

I'm closing this but please do reopen if you have specific suggestions for improving the docs on flutter.dev.
