### ISSUE TITLE
'Use a custom font' page issue

### ISSUE THREAD

**Issue by xinoip** [flutter/website#5836]
Page URL: https://flutter.dev/docs/cookbook/design/fonts.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/design/fonts.md

## Description

This part of cookbook is incorrect: [#pubspecyaml-option-definitions](https://flutter.dev/docs/cookbook/design/fonts.html#pubspecyaml-option-definitions)

> A single font can reference many different files with different outline weights and styles:
> 
> The weight property specifies the weight of the outlines in the file as an integer multiple of 100, between 100 and 900. These values correspond to the FontWeight and can be used in the fontWeight property of a TextStyle object.
> 
> The style property specifies whether the outlines in the file are italic or normal. These values correspond to the FontStyle and can be used in the fontStyle property of a TextStyle object.

Actually, it seems like flutter ignore these style and weight descriptor and use the meta data inside the font file.

## Reproduce

Use a font in your pubspec.yml with custom weight value:

```yaml
- family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
          weight: 100
```

Try to use it inside app:

```dart
Text(
        'This text should show as Raleway-Bold but it does not',
        style: TextStyle(
          fontFamily: 'Raleway',
          fontWeight: FontWeight.w100,
        ),
);
```

Cookbook makes you think, these style descriptors are overriding the flutter engines selection process but they don't.

**Comment by micpap25** [comment]
Hi @xinoip,
It seems you are using a font weight of 100 but want a bold font. A smaller font weight leads to a thinner font, not a thicker one, as shown here: https://api.flutter.dev/flutter/dart-ui/FontWeight-class.html

![image](https://user-images.githubusercontent.com/34077605/119136801-189a3580-ba0e-11eb-95ab-87a4540d5bc3.png)

Can you test this with a font weight of 700 or greater?

**Comment by xinoip** [comment]
> Hi @xinoip,
> It seems you are using a font weight of 100 but want a bold font. A smaller font weight leads to a thinner font, not a thicker one, as shown here: https://api.flutter.dev/flutter/dart-ui/FontWeight-class.html
> 
> ![image](https://user-images.githubusercontent.com/34077605/119136801-189a3580-ba0e-11eb-95ab-87a4540d5bc3.png)
> 
> Can you test this with a font weight of 700 or greater?

Thanks for the quick response @micpap25 !

Yes, I know that w700 means bold and w100 means thin. It was just for showing that flutter does not care about what you specify as the weight. It only cares about what is inside the font files meta data.

**Comment by micpap25** [comment]
Got it, I think I understand your issue now. 
I agree that one might think, based on this description, that defining the weight would override the weight defined by the font's data. 
I can't think of a better explanation off the top of my head, but I'll try to put together something better today.
