### ISSUE TITLE
Include pub get permission error(on Windows) fixes as a troubleshooting information

### ISSUE THREAD

**Issue by atapas** [flutter/website#5840]
For many of us who are using flutter on Windows, facing this issue is very common.

https://github.com/dart-lang/pub/issues/1798

However, there are no proper solutions found to address the issue. Different solutions worked for different people. For example, this solution worked for me: https://github.com/dart-lang/pub/issues/1798#issuecomment-846512815

It would be great to provide the troubleshooting steps as documentation on the flutter website: https://flutter.dev/docs.

**Comment by sfshaza2** [comment]
According to https://github.com/dart-lang/pub/issues/1798, this seems to be fixed.
