### ISSUE TITLE
Replace Medium; Banned/Not-Working in some Countries

### ISSUE THREAD

**Issue by ghost** [flutter/website#5850]
First of all, I am not sure if that's the right place for this question. so sorry about that :)

Can flutter move its official announcements from Medium and replace it with other websites that's accessable to all developers  (maybe in flutter.dev itself)

Medium is banned in some countries and (not working) in others. E.g: Egypt where i am from.
Having to open a vpn just to read the announcement and what's new in flutter v2.2.0 shouldn't be necessary, so why not just write the article in flutter.dev itself ?

Thank you.

**Comment by sfshaza2** [comment]
cc @timsneath @csells

**Comment by timsneath** [comment]
Closing this one for now as unplanned. It looks like the Egyptian government has occasionally blocked certain sites, based on cursory research. While we could create our own blogging host, the work to do so would take resources away from our primary goal of providing high-quality content. Medium isn't perfect, but it does save us from having to create separate infrastructure for managing a blog pipeline.
