### ISSUE TITLE
'Retrieve the value of a text field' page issue

### ISSUE THREAD

**Issue by MavaniVijay** [flutter/website#5854]
Page URL: https://flutter.dev/docs/cookbook/forms/retrieve-input.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/forms/retrieve-input.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by piedcipher** [comment]
What is the issue?

**Comment by darshankawar** [comment]
@MavaniVijay 
You didn't fill `description of issue`, so we don't know what exactly are the issue you facing on the page url. Please provide the details so that we can properly address this issue.
