### ISSUE TITLE
Correct transparency method on 'Adding a Flutter Fragment to an Android app' page

### ISSUE THREAD

**Issue by nxcco** [flutter/website#5855]
Page URL: https://docs.flutter.dev/add-to-app/android/add-flutter-fragment
Page source: https://github.com/flutter/website/tree/master/src/docs/development/add-to-app/android/add-flutter-fragment.md

Description of issue:
Regarding [this](https://flutter.dev/docs/development/add-to-app/android/add-flutter-fragment?tab=launch-with-transparency-kotlin-tab#display-a-flutterfragment-with-transparency) section. The concerned piece is:
```kotlin
// Using a new FlutterEngine.
val flutterFragment = FlutterFragment.withNewEngine()
    .transparencyMode(FlutterView.TransparencyMode.transparent)
    .build()

// Using a cached FlutterEngine.
val flutterFragment = FlutterFragment.withCachedEngine("my_engine_id")
    .transparencyMode(FlutterView.TransparencyMode.transparent)
    .build()
```
The `FlutterView.TransparencyMode.transparent` does not work. Should be replaced with `TransparencyMode.transparent`.

Also the following `build()` is not working anymore. Should be replaced with `build<FlutterFragment>()`.

**Comment by atsansone** [comment]
This was fixed in https://github.com/flutter/website/pull/3238. Closing this issue.
