### ISSUE TITLE
'Simple app state management' page issue

### ISSUE THREAD

**Issue by ebukaodini** [flutter/website#5858]
Page URL: https://flutter.dev/docs/development/data-and-backend/state-mgmt/simple.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/state-mgmt/simple.md

Description of issue: Please update the `provider: ^4.3.3` to `provider: ^5.0.0`. I had dependency issue using the former

**Comment by sfshaza2** [comment]
cc @filiph

**Comment by micpap25** [comment]
Looking at https://pub.dev/packages/provider, it seems that this page doesn't use `provider` in a way that is affected by null safety, and it doesn't look like any other page on the site uses `provider`. I think this is as simple as just changing the version number.
