### ISSUE TITLE
2-minute introductory video for Flutter

### ISSUE THREAD

**Issue by jmewes** [flutter/website#5872]
Hi there,

I have started to create a Flutter workshop for high-school students, i.e. people new to programming. Just now I worked on a section "What is Flutter and why do we need it?". To get hints for the answer to that question I went to the start page of "flutter.dev". I was happy to find a 2-minute video there which give an introduction to Flutter ([What's new in Flutter 2019](https://www.youtube.com/watch?v=5VbAwhBBHsg)).

However, the video is - from my point of view - not targeted at people who hear about Flutter for the first time, but rather trying to convince professional Android and iOS developers that they should eventually give Flutter a try after they heard about it already many times. This is already shining through in the video title which is "What's new in Flutter 2019". Then in the video, many advanced topics are scratched which make the video unsuited for my use case.

From the Firebase videos, I am used to nice introductory videos for complex topics, e.g. [Introducing Firebase Realtime Database](https://www.youtube.com/watch?v=U5aeM5dvUpA). Maybe you could create such a beginner-friendly video for Flutter and link to it at the place of the current introductory video.

**Comment by jmewes** [comment]
By the way, here is how I would introduce Flutter to high-school students.

-----

There is a [plethora](https://www.tiobe.com/tiobe-index/) of programming languages available on the market. Each one of them either enables to write programs for a certain domain or makes it more convenient than others, depending on the context and personal preferences. They also have their respective ecosystem with libraries and frameworks which try to make it quick and easy to develop applications with it.

Dart is a [general-purpose](https://en.wikipedia.org/wiki/General-purpose_programming_language) programming language that is optimized for the development of user interfaces like interactive websites and mobile apps. It has similarities with many other languages, e.g. JavaScript, Java, and Kotlin. One advantage of Dart programs is that they can be executed on every major platform, i.e. on Windows, Linux, macOS, iOS, Android, and the web.

Flutter is a framework for building user interfaces. Since it is built with Dart, it can run on any platform which Dart supports.
So, by learning Flutter you can build apps for any platform without learning another technology stack first.

**Comment by sfshaza2** [comment]
Hi there! Yes, we do need a good, up-to-date, introductory video. I talked about it with my team and they agreed. I was surprised that the first link went to that video. It's not right at all. I've removed that link from the page for now.

**Comment by sfshaza2** [comment]
So, I'm not the one who produces or writes the videos, but the team that is has this on their list.

**Comment by parlough** [comment]
I just wanted to note that there is an amazing 90 second video showing some of the strengths of Flutter by @khanhnwin at https://www.youtube.com/watch?v=ZnufaryH43s

**Comment by atsansone** [comment]
This video is displayed on the [Flutter docs homepage](https://docs.flutter.dev/). Closing as completed.
