### ISSUE TITLE
'Configuring the URL strategy on the web' page issue

### ISSUE THREAD

**Issue by kaliosek** [flutter/website#5875]
Page URL: https://flutter.dev/docs/development/ui/navigation/url-strategies.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/navigation/url-strategies.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
flutter_web_plugins is not available on pub dev:
depends on flutter_web_plugins any which doesn't exist (could not find package flutter_web_plugins at https://pub.dartlang.org), version solving failed.

**Comment by darshankawar** [comment]
@kaliosek 
As the document says, it need to be added as a package and not a plugin, like below:

<img width="206" alt="Screenshot 2021-07-27 at 5 03 03 PM" src="https://user-images.githubusercontent.com/67046386/127146863-7b54c9c5-4a06-4ffc-b317-616c2c9de614.png">

And then running `flutter pub get` works properly without throwing any error. Then you can add the `setUrlStrategy(PathUrlStrategy());` method which will prompt you to import the said library `import 'package:flutter_web_plugins/flutter_web_plugins.dart';`

I was able to add the package followed by the method including the library import as above. You can try this and confirm.
I am going ahead and closing this as not an issue. If you disagree, write in comments and I'll reopen it.
