### ISSUE TITLE
'Handle scrolling' page issue

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#5883]
Page URL: https://flutter.dev/docs/cookbook/testing/integration/scrolling.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/integration/scrolling.md

How do you do migrate scrollUntilVisible to integration_test plugin?
thanks

**Comment by johnpryan** [comment]
Here's what the testing_app sample does: https://github.com/flutter/samples/blob/master/testing_app/test/home_test.dart#L34

I created https://github.com/flutter/website/issues/5889 to track the cookbook articles so I'm going to close this. Thanks for filing an issue.

**Comment by neiljaywarner** [comment]
@johnpryan thank you for the response. i *did* actually see that but that is _much_ less straightforward than scrollUntilVisible, and in most test situations you want to create helper classes anyway

a usable tap method really should include scrollUntilVisible then tap.
anyway, thanks for creating something to update the cookbook articles
