### ISSUE TITLE
'Take a picture using the camera' step 4 refers to missing Future code

### ISSUE THREAD

**Issue by amm-catapult** [flutter/website#5887]
### Page URL

https://docs.flutter.dev/cookbook/plugins/picture-using-camera#4-use-a-camerapreview-to-display-the-cameras-feed

### Page source

https://github.com/flutter/website/tree/master/src/docs/cookbook/plugins/picture-using-camera.md

### Description of issue

Step 4 has an alert statement that refers to code or a step that does not exist.

The statement is:
> You must wait until the controller has finished
> initializing before working with the camera. Therefore,
> you must wait for the `_initializeControllerFuture()` created
>  in the previous step...

(found [here](https://github.com/flutter/website/blame/master/src/docs/cookbook/plugins/picture-using-camera.md#L152-L154))

However, `_initializeControllerFuture` is absent from the whole page (except for the complete example code at the end, e.g. [here](https://github.com/flutter/website/blob/c575270b6dd4d2c0e7c13dfe19bb3e8574456327/null_safety_examples/cookbook/plugins/picture_using_camera/lib/main_step5.dart#L45)).

It does appear that the relevant code was [deleted in the latest (`c575270b`) commit](https://github.com/flutter/website/commit/c575270b6dd4d2c0e7c13dfe19bb3e8574456327#diff-723ff10e7d8ef4a1937730d13dac84dad5ba01f30f97d3d528ac02c9c2c46d76L124), maybe to make way for an extra step between 3 and 4, but that was never completed...?

**Comment by sfshaza2** [comment]
@miquelbeltran, not sure if you have any hours left, but this would would be for you, if there was.  :D

**Comment by darshankawar** [comment]
Probably need to declare `_initializeControllerFuture` in step 3 as:

```
class TakePictureScreenState extends State<TakePictureScreen> {
  late CameraController _controller;
  late Future<void> _initializeControllerFuture;
```

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/6351. Closing this issue.
