### ISSUE TITLE
Update cookbook articles to use package:integration_test

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#5889]
We should update the cookbook articles to use package:integration_test. The [testing_app](https://github.com/flutter/samples/blob/master/testing_app) sample in flutter/samples and the [Integration testing](https://flutter.dev/docs/testing/integration-tests) pages are good references.

The pages to update are in the [src/docs/cookbook/testing/integration](https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/integration) directory.

See also:
- https://github.com/flutter/website/issues/5883
- https://github.com/flutter/website/issues/5445

**Comment by neiljaywarner** [comment]
@johnpryan  also didn't flutter driver support screenshots? Whats' the recommended way to get screenshots with integration-test plugin please?

**Comment by johnpryan** [comment]
@neiljaywarner There is a [takeScreenshot](https://api.flutter.dev/flutter/package-integration_test_integration_test/IntegrationTestWidgetsFlutterBinding/takeScreenshot.html) method available on the IntegrationTestWidgetsFlutterBinding class.
