### ISSUE TITLE
'Free Flutter course from the App Brewery' page issue

### ISSUE THREAD

**Issue by cmsenjaliya** [flutter/website#5892]
Page URL: https://flutter.dev/freecourse.html
Page source: https://github.com/flutter/website/tree/master/src/freecourse.md

Description of issue:

**Comment by cmsenjaliya** [comment]
I learn flutter which plateform is best

**Comment by micpap25** [comment]
Hi @cmsenjaliya , do you have an issue you want to bring up with the site?

**Comment by sfshaza2** [comment]
I believe that @cmsenjaliya is asking how to learn Flutter. That free course page you found is no longer available. However, for $10, you can sign up for the more in-depth course, [The Complete Flutter Bootcamp with Dart](https://www.appbrewery.co/p/flutter-development-bootcamp-with-dart). I will add this info to the page for anyone who stumbles upon it.
