### ISSUE TITLE
Fix the build

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#5907]
I believe that we need to run `tool/refresh-code-excerpts.sh` to get the changes from https://github.com/flutter/codelabs/pull/134 into src/docs/get-started/codelab.md.

However, when I did that, I wasn't sure that the changes were all good.

@domesticmouse can you fix this, pretty please? 

/cc @sfshaza2

**Comment by sfshaza2** [comment]
@domesticmouse, can you take a look at this?

**Comment by domesticmouse** [comment]
I'm currently internet-less so if this is time sensitive you might need to rope in @RedBrogdon or @johnpryan

**Comment by RedBrogdon** [comment]
On it.
