### ISSUE TITLE
license seems to be a BSD 3-Clause "New" or "Revised" License

### ISSUE THREAD

**Issue by al919** [flutter/website#5910]
It looks like that the license for Flutter website is a BSD 3-Clause "New" or "Revised" License. It might be better to show the license as such on both the home page and the specific license page. I think there is an option on Github that allows you to select this type of license and both the homepage and license file will immediately reflect such change.

**Comment by sfshaza2** [comment]
@kwalrath, do you have this issue on dart.dev?

**Comment by kwalrath** [comment]
The dart.dev license is silghtly different: https://github.com/dart-lang/site-www/blob/master/LICENSE. We might want to kick this one over to our open source legal people, to be sure to get it right.

**Comment by atsansone** [comment]
The license is CC3.0 and BSD. Closing this issue.

https://github.com/flutter/website/blob/main/LICENSE
