### ISSUE TITLE
<bug>: unwanted text copied

### ISSUE THREAD

**Issue by ayaankhan98** [flutter/website#5911]
If we click on the `copy` buttons highlighted below in the screenshot, it will copy all the text mention in black box. Which is not desirable. People need to only copy the shell commands so that they can paste those commands directly into their system shell not the output of commands. 

### Current behaviour
Copies all text that is command along with it's output.

### Expected behaviour
When someone clicks on copy button it should only copy the command not the addtional output text of the command.

![Screenshot_20210609_154656](https://user-images.githubusercontent.com/43348292/121337731-77323f80-c93a-11eb-852a-f61f3d0c4659.png)

**Comment by sfshaza2** [comment]
@ayaankhan98, thanks for this bug report. However, I am having trouble finding this specific page in the website.  Can you provide a URL? thx

**Comment by ayaankhan98** [comment]
> @ayaankhan98, thanks for this bug report. However, I am having trouble finding this specific page in the website. Can you provide a URL? thx

please refer to [this URL](https://flutter.dev/desktop)

**Comment by TahaTesser** [comment]
Hi @ayaankhan98 
The logs you're highlighting is not necessary to copy using button, these are just same logs
