### ISSUE TITLE
'Windows install' page issue

### ISSUE THREAD

**Issue by purezen** [flutter/website#5916]
Page URL: https://flutter.dev/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:
- Flutter doesn't recognize if android studio is installed by default. Was getting error saying 'Couldn't locate android studio' and 'No JDK found'. Had to explicitly mention using `flutter config --android-studio-dir`
- `flutter doctor --android-licenses` is not mentioned. Is it not required anymore?

**Comment by micpap25** [comment]
I did not have your first issue, but I agree with your second point. It is necessary and should be mentioned.
