### ISSUE TITLE
flutter.dev/security differs from flutter/flutter/SECURITY.md

### ISSUE THREAD

**Issue by dnfield** [flutter/website#5937]
Not sure if that's intentional, but it's slightly confusing :)

/cc @hixie @Sfshaza2

**Comment by Hixie** [comment]
lol I literally just noticed this and was submitting a PR to fix it: https://github.com/flutter/website/pull/5938

**Comment by TahaTesser** [comment]
Based on the above comment and since https://github.com/flutter/website/pull/5938 is merged
Closing as fixed
