### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by sm2017** [flutter/website#5949]
Open https://flutter.dev/docs/get-started/install/windows , there is a CORS error for https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json

> Access to XMLHttpRequest at 'https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json' from origin 'https://flutter.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by sm2017** [comment]
![image](https://user-images.githubusercontent.com/19644997/123041887-3abb1500-d40b-11eb-9b83-9b02ef5373b8.png)

**Comment by sm2017** [comment]
May be it's not a bug, Because When I open https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json I get 403 error (I am in Iran and due to sanctions it's a blocked page)

![image](https://user-images.githubusercontent.com/19644997/123042126-938aad80-d40b-11eb-8d0c-e1c35faa1a20.png)

**Comment by sfshaza2** [comment]
I'm sorry about that, @sm2017.

**Comment by sm2017** [comment]
@sfshaza2 no problem
