### ISSUE TITLE
'Fetch data from the internet' page issue

### ISSUE THREAD

**Issue by nickppbd** [flutter/website#5958]
Page URL: https://flutter.dev/docs/cookbook/networking/fetch-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/fetch-data.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

dependencies:
  http: <latest_version>

those code are not working.

**Comment by piedcipher** [comment]
You need to add a version where `<latest_version>` is written.

**Comment by nickppbd** [comment]
it would have been better if it had been written as you say.

**Comment by piedcipher** [comment]
You're right. Even if you write `http:` without any version it would fetch `any` version. You could write `http: any` as well or mention a specific version.

Usually `<>` angle brackets are used to indicate that you need to substitute something there.
