### ISSUE TITLE
'Flutter SDK releases' page issue

### ISSUE THREAD

**Issue by dldudtjr98** [flutter/website#5967]
Page URL: https://flutter-kr.io/docs/development/tools/sdk/releases.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/tools/sdk/releases.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: Cannot load all sdk refs in this page, regardless of the environments
![capture](https://user-images.githubusercontent.com/25276627/123596675-70a63200-d82d-11eb-914a-e32a4ab040f7.PNG)

**Comment by TahaTesser** [comment]
Hi @dldudtjr98 
The link you provided isn't a official website link
Please viisit https://flutter.dev/docs/development/tools/sdk/releases
Closing as invalid
