### ISSUE TITLE
'Test drive' page issue

### ISSUE THREAD

**Issue by Morgan-6Freedom** [flutter/website#5972]
Page URL: https://flutter.dev/docs/get-started/test-drive/
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/test-drive/index.md

Description of issue:

Tools> Android > AVD Manager does not exists

![image](https://user-images.githubusercontent.com/49686866/123753145-ce805b80-d8b9-11eb-8ecd-e2cad0084a7c.png)

**Comment by TahaTesser** [comment]
Hi @Morgan-6Freedom 
Thanks for filing the issue, it is indeed changed, it is now Tool > AVD Manager instead 
![image](https://user-images.githubusercontent.com/48603081/126495600-c606981e-c1df-4996-afff-959ac5a0cbf4.png)
