### ISSUE TITLE
Refactor the 'Create a download button' page to be more like a tutorial

### ISSUE THREAD

**Issue by JavierNoriega** [flutter/website#5975]
Page URL: https://flutter.dev/docs/cookbook/effects/download-button.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/effects/download-button.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: After finishing the tutorial step by step it is pretty much impossible to implement this without spending a good amount of time looking at the "Interactive Example" below... what is the point of a tutorial if it doesn't work?

**Comment by TahaTesser** [comment]
I can see the structure is not step by step but sort of implies to follow along anyway https://flutter.dev/docs/cookbook/effects/download-button

**Comment by atsansone** [comment]
Recipes cover specific parts of a complete guide but may not be a complete guide. These headings do feed into each other, so it should be possible to follow along. Works as designed. Closing.
