### ISSUE TITLE
architectural-overview page has incorrect/outdated FFI example

### ISSUE THREAD

**Issue by hitman-codehq** [flutter/website#5977]
Hello.

I was interested in following the Windows-specific FFI example on the architectural overview page here:

https://flutter.dev/docs/resources/architectural-overview#foreign-function-interface

However, it would seem that this page is either out of date or incorrect.  In the example of calling the Win32 MessageBox() function, the Utf16 type does not exist and neither does the toNativeUtf16() method call.

I did quite a bit of Googling and the Utf16 type doesn't seem to ever have existed in Flutter.  Or at least if it is there, I can't find it (and normally in Flutter, things like types are very easy to find with a quick Google).

Is the documentation simply out of date?  Or am I missing something very obvious here?

I am using Flutter 2.2.2 with null safety enabled.

**Comment by timsneath** [comment]
Hi there! This is just a code snippet, of course. For this to work, you'll need to import the `dart:ffi` library as well as add the [`ffi`](https://pub.dev/packages/ffi) package to your project. 

But you raise a good point -- this isn't self-evident. I'll submit a PR to make this more clear. 

In the meantime, you can find many more samples of Win32 interop as part of the [`win32`](https://pub.dev/packages/win32) package.
