### ISSUE TITLE
BSD license referenced in website

### ISSUE THREAD

**Issue by suli-hub** [flutter/website#5985]
Does the BSD license referenced in the footer.html refer to the one in the LICENSE file of this repository? https://github.com/flutter/website/blob/236a198812e691aae469eae9c54208b607f5ed03/src/_includes/footer.html#L26

**Comment by TahaTesser** [comment]
Hi @suli-hub 
I think it refers to this [license](https://github.com/flutter/website/blob/master/LICENSE)
Hope this answers your question
