### ISSUE TITLE
'Fetch data from the internet' page issue

### ISSUE THREAD

**Issue by Umbrum** [flutter/website#5987]
Page URL: https://flutter.dev/docs/cookbook/networking/fetch-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/networking/fetch-data.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
When i created the album class it shows the following part as wrong:
Album({
    required this.userId,
    required this.id,
    required this.title,
  });

**Comment by maheshmnj** [comment]
Hi @Umbrum, Could you please share what error did you face?

I verified the Album class and it looks correct to me. 

```
class Album {
  final int userId;
  final int id;
  final String title;

  Album({
    required this.userId,
    required this.id,
    required this.title,
  });

  factory Album.fromJson(Map<String, dynamic> json) {
    return Album(
      userId: json['userId'],
      id: json['id'],
      title: json['title'],
    );
  }
}
``` 

Let me know if I am missing anything.

Thank you.

**Comment by TahaTesser** [comment]
Closing as no information is provided, please file a new issue with all information if the problem persists
