### ISSUE TITLE
'Build and release an Android app' page issue

### ISSUE THREAD

**Issue by jepperaskdk** [flutter/website#5989]
Page URL: https://flutter.dev/docs/deployment/android.html
Page source: https://github.com/flutter/website/tree/master/src/docs/deployment/android.md

Description of issue: keyfile must be made with the binary from android-studio.
I spent a while trying to build my appbundle with a keystore, and I kept getting 
`Failed to read key upload from store "/path/to/upload-keystore.jks": Invalid keystore format`
Solution:
- Run `flutter doctor -v` and note `Java binary at: /usr/local/android-studio-ide-201.7199119-linux/android-studio/jre/bin/java`
- Create keystore with `keytool` from `/usr/local/android-studio-ide-201.7199119-linux/android-studio/jre/bin`
(From this thread: https://stackoverflow.com/questions/62988452/flutter-release-apk-invalid-keystore-format-with-linuxdeepin)

I don't know if possibly there could be a troubleshooting section, with "typical" errors? And then list this error/solution?

**Comment by maheshmnj** [comment]
Hi @jepperaskdk,
Thanks for filing the issue and I see that in [Upload the keystore](https://flutter.dev/docs/deployment/android#create-an-upload-keystore) section the first step navigates to 
```
Android Studio key generation steps
```
 which basically mentions about keystore generation.
So I am going to close this issue as invalid If you disagree feel free to comment and I will reopen it.

Thank you.
