### ISSUE TITLE
'Building layouts' page issue

### ISSUE THREAD

**Issue by SatyamGondhale** [flutter/website#5994]
Page URL: https://flutter.dev/docs/development/ui/layout/tutorial.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/layout/tutorial.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by micpap25** [comment]
Hi @SatyamGondhale , could you please explain your issue so it can be resolved? Thank you.

**Comment by darshankawar** [comment]
@SatyamGondhale 
You didn't fill in `Description of issue`, so we don't know what exactly the issue are you facing on Page URL: https://flutter.dev/docs/development/ui/layout/tutorial.html.

Please provide the description, so that we can properly address this issue.

**Comment by TahaTesser** [comment]
Closing as no information is provided, please file a new issue with all information if the problem persists
