### ISSUE TITLE
broken link to localisation example code on website

### ISSUE THREAD

**Issue by maks** [flutter/website#5998]
Currently on the localisation page: https://flutter.dev/docs/development/accessibility-and-localization/internationalization
the link to the "minimal" example app points to: https://github.com/flutter/website/tree/master/null_safety_examples/internationalization/minimal
which gives a 404, I think instead it should be to:
should be: https://github.com/flutter/website/tree/master/examples/internationalization/minimal

**Comment by piedcipher** [comment]
It's caused due to this PR: #5996

**Comment by RedBrogdon** [comment]
Nice catch, @maks. There are some other files that have the same issue. I'll put together a PR to get it fixed.
