### ISSUE TITLE
'Fade in images with a placeholder' page issue

### ISSUE THREAD

**Issue by sourav8256** [flutter/website#6015]
Page URL: https://flutter.dev/docs/cookbook/images/fading-in-images.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/images/fading-in-images.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

kTransparentImage is not initialized in code.

**Comment by DanJPerkins** [comment]
Can I be assigned to this issue?

**Comment by piedcipher** [comment]
You need to use transparent_image package. `kTransparentImage` is part of that package.

https://pub.dev/packages/transparent_image

**Comment by darshankawar** [comment]
@sourav8256 
As mentioned above, `kTransparentImage` belongs to `transparent_image` plugin. Adding that plugin in your code should resolve the issue. The same is implemented in the `complete example` section of the Page URL: https://flutter.dev/docs/cookbook/images/fading-in-images.html.  https://flutter.dev/docs/cookbook/images/fading-in-images#complete-example

Closing this not an issue.
