### ISSUE TITLE
Adb.exe not found…flutter doctor

### ISSUE THREAD

**Issue by Abdulrazak07** [flutter/website#6027]
After installing the flutter and run flutter doctor, it show adb.exe not found. After long search i checked adb.exe file in plateform tool. That adb file is named as adb only. So i renamed it like adb.exe. After that the error gone. This is happend only after recent update the flutter. Lot of people got struck like beginners. So rectify this error on next update. 
-![image](https://user-images.githubusercontent.com/87390631/125512069-808dca5e-9e33-4dbe-ae4c-e739ed897d96.jpeg)

Thank you...

**Comment by darshankawar** [comment]
@Abdulrazak07 
This issue doesn't belong to this repo, but in flutter/flutter repo instead. I see that you've already opened same bug there, https://github.com/flutter/flutter/issues/86371 for which our resolution was to follow-up in original issue https://github.com/flutter/flutter/issues/72101

Closing from here as invalid.
