### ISSUE TITLE
'Books about Flutter' link itself is broken (not 404)

### ISSUE THREAD

**Issue by timsneath** [flutter/website#6029]
Page URL: https://flutter.dev/docs/resources/books.html
Page source: https://github.com/flutter/website/tree/master/src/docs/resources/books.md

Description of issue:
The "Let us know" link on this page doesn't work. It's blue, but it doesn't link anywhere. Something borked with the `{:.help-instruction}` reference, @sfshaza2?

**Comment by sfshaza2** [comment]
The link wasn't actually broken. It just wasn't clear. "Let us know" went to the GitHub issues page for the repo, and assumed that folks would know to submit an issue. I've clarified it. 

But my PR also exposed another bug that Kathy has filed:  https://github.com/flutter/website/issues/6032
