### ISSUE TITLE
Fix book page click handling

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#6032]
As described in #6031, the links in the introduction don't respond for any part of the link that's above the right column. I think that column is interfering with mouse event detection (hover, click, ...) but I'm not a CSS expert. Help!

![image](https://user-images.githubusercontent.com/2164483/125691807-ebe799e4-f28a-4b6d-84e7-a93beb850a4f.png)

**Comment by kwalrath** [comment]
I suspect it's the heading/banner/anchor code that makes these use more vertical space than they need. (The code that makes the page scroll properly to include the heading when you follow a link to a section.) I also have a theory that changing the book titles from links (which is a little gross any) to not-links might help. Also, it's a little gross that these are h3s instead of h2s (if they need to be headings at all). 

Anyhoo, I'll play with it and let you know when happens.

**Comment by kwalrath** [comment]
#6036 mostly makes this issue moot, but it doesn't fix it. The Dart site does _not_ have this issue with the book page or with headings appearing to grab more space than they need.

This doesn't seem to be an issue elsewhere in flutter.dev. E.g. go to https://flutter.dev/docs/development/ui/layout#1-select-a-layout-widget. The `Center` link above **2. Create a visible widget** is responsive, even though the heading appears to be over that space. So... there's something weird about the Books page.

![image](https://user-images.githubusercontent.com/2164483/125856139-adb6ceaa-42d1-4b50-8baf-2306b0dd7aa1.png)

**Comment by parlough** [comment]
I believe this is likely the same issue that was fixed by https://github.com/dart-lang/site-www/pull/2231 on the Dart side and could likely be fixed in a similar fashion. What do you think?

**Comment by kwalrath** [comment]
Sounds good to me! Of course, we'll have to wait until flutter/website is unfrozen.

**Comment by atsansone** [comment]
This is a result of the `header-clearance` mixin in https://github.com/flutter/website/blob/main/src/_sass/components/_content.scss. As fixed in https://github.com/flutter/website/pull/6031, we should remove any reference to this mixin in this file.
