### ISSUE TITLE
'Developing for iOS 14' page issue - Update the page for IOS 14 and up 

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#6038]
Page URL: https://flutter.dev/docs/development/ios-14.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ios-14.md
ios 15 is in beta and pretty far along
Description of issue:

**Comment by TahaTesser** [comment]
Hi @neiljaywarner 
Do you have suggestions on what's needs to be added to this new page? Are there any IOS 15 breaking changes for Flutter, please provide some examples
Thank you

**Comment by sfshaza2** [comment]
@cbracken, will we need an iOS15-specific page?

**Comment by cbracken** [comment]
Sorry for spotting this today as I cleared out my notifications!

/cc @jmagman for answers on iOS 15

**Comment by jmagman** [comment]
I'm not aware of any...  Are you thinking of something specific, @neiljaywarner?

That page should be cleaned up to stop referencing old stables, and to make it clear it's for iOS 14 and up, not just for iOS 14.
Also Flutter doesn't even support Xcode 11.4 anymore (minimum is Xcode 12), we can probably remove https://flutter.dev/docs/development/ios-project-migration.

**Comment by neiljaywarner** [comment]
Calling it 14 and up would do it for me if it's accurate..

....sent from my phone

**Comment by jmagman** [comment]
This page no longer references iOS 14
https://docs.flutter.dev/development/platform-integration/ios/ios-debugging
