### ISSUE TITLE
'Introduction to widgets' page issue

### ISSUE THREAD

**Issue by Rahulku55** [flutter/website#6041]
Page URL: https://flutter.dev/docs/development/ui/widgets-intro.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/widgets-intro.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

**Comment by maheshmnj** [comment]
Hi @Rahulku55, Could you please describe what the issue is? The description is empty to make anything out of it.

**Comment by TahaTesser** [comment]
Closing as no information is provided, please file a new issue with all information if the problem persists
