### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by yousefelgoharyx** [flutter/website#6047]
When I visit flutter.dev, the browser keeps giving me this message: 
"Hmmm… can't reach this pageflutter.dev’s DNS address could not be found… diagnosing the problem now."
Every other website works just fine so I don't think its my problem
let alone the website worked back then

**Comment by maheshmnj** [comment]
Hi @yousefelgoharyx,
Can you try clearing the website data and try again? https://flutter.dev
If the problem persists  Please share what Platform and the browser that you are trying to access the flutter website in.

**Comment by TahaTesser** [comment]
Closing as no information is provided, please file a new issue with all information if the problem persists
