### ISSUE TITLE
'Return data from a screen' page issue

### ISSUE THREAD

**Issue by kamleshwebtech** [flutter/website#6065]
Page URL: https://flutter.dev/docs/cookbook/navigation/returning-data.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/navigation/returning-data.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

Getting error message in VS Code console: 

```console
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: <SnackBar Hero tag - Text("Yep!")>

Here is the subtree for one of the offending heroes: Hero
    tag: <SnackBar Hero tag - Text("Yep!")>
    state: _HeroState#f17f0
When the exception was thrown, this was the stack
#0      Hero._allHeroesFor.inviteHero.<anonymous closure>
package:flutter/…/widgets/heroes.dart:256
#1      Hero._allHeroesFor.inviteHero
package:flutter/…/widgets/heroes.dart:267
#2      Hero._allHeroesFor.visitor
package:flutter/…/widgets/heroes.dart:286
#3      ComponentElement.visitChildren
package:flutter/…/widgets/framework.dart:4549
#4      Hero._allHeroesFor.visitor
package:flutter/…/widgets/heroes.dart:301
```

Kindly suggest how can we fix it. Thanks a lot.

**Comment by kamleshwebtech** [comment]
I have NO `FloatingActionButton` in my entire project, but still getting error. Any suggestion will be highly appreciated. Thanks.

**Comment by TahaTesser** [comment]
Hi @kamleshwebtech 
I just tried a complete sample from  https://flutter.dev/docs/cookbook/navigation/returning-data.html on the latest Flutter `stable` channel and latest `master` channel,  no errors in the VS Code console

Can you please provide `flutter doctor -v` and try the  complete the sample?
