### ISSUE TITLE
'Write your first Flutter app on the web' page issue

### ISSUE THREAD

**Issue by kelanRoss** [flutter/website#6071]
Page URL: https://flutter.dev/docs/get-started/codelab-web.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/codelab-web.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

Hello, I'm getting the error 'The argument type 'JsObject' can't be assigned to the parameter type 'BuildContext' with the function:

```dart
void _showWelcomeScreen() {
  Navigator.of(context).pushNamed('/welcome');
}
```
Both in VSCode and the codelab DartPad.

Changing the function to 
```dart
void _showWelcomeScreen(context) {
  Navigator.of(context).pushNamed('/welcome');
}
```
and the button `onPressed` to
`onPressed: ()=> _showWelcomeScreen(context),`
gets the app to work but I'm not sure what is the best practice.

**Comment by kelanRoss** [comment]
By placing the _showWelcomeScreen function within the _SignUpFormState build method gets the app to work. The tutorial says to place it above so this is a bit unclear.

**Comment by TahaTesser** [comment]
Hi @kelanRoss 
Thanks for fling the issue,  `_showWelcomeScreen` should be above the `build` function as it says in the tutorial and you don't need to pass `context` to `_showWelcomeScreen` to navigate to the welcome screen.

![image](https://user-images.githubusercontent.com/48603081/127183694-f8f7d78d-a094-40a9-b9f7-94c32a0481d0.png)

After placing it above `build` function, you can simply call it in your build tree 
![image](https://user-images.githubusercontent.com/48603081/127183915-429bf020-83a3-4753-bc9d-def4ec302da2.png)

When running the code, locally or [dartpad ](https://flutter.dev/docs/get-started/codelab-web#complete-sample). i don't see  `JsObject` error


Hope this answers your doubts

**Comment by kelanRoss** [comment]
![image](https://user-images.githubusercontent.com/40218758/127197353-2faa9ee1-8b54-45af-b0b8-0ea59987c06d.png)

**Comment by kelanRoss** [comment]
![image](https://user-images.githubusercontent.com/40218758/127197454-0c9a94de-b7b1-480f-bd1a-9f82b65220ec.png)
I was still getting the issue but I realized dart:js imported itself, probably when I was fiddling with the context argument.
![image](https://user-images.githubusercontent.com/40218758/127197726-8d814f80-a21b-48b9-b03f-bad782b8ef91.png)
Without the import everything works fine. Thanks for the response.

**Comment by TahaTesser** [comment]
Hi @kelanRoss 
No worries, you remove that import, it is not required 
Closing as not an isue
