### ISSUE TITLE
misprint : https://codelabs.developers.google.com/codelabs/flutter-cupertino#5

### ISSUE THREAD

**Issue by JarvisHo** [flutter/website#6074]
In lib/product_list_tab.dart, first section, `builder: (context, child, model) {` should be `builder: (context, model, child) {`

**Comment by maheshmnj** [comment]
@JarvisHo, Thanks for filing the issue, This is a valid issue as per the [consumer docs](https://pub.dev/documentation/provider/latest/provider/Consumer/builder.html).

**Comment by sakshiisaxena** [comment]
Is this issue up for grab? @JarvisHo

**Comment by maheshmnj** [comment]
Heres the repo to contribute: https://github.com/flutter/codelabs/tree/master/cupertino_store

**Comment by micpap25** [comment]
I'd like to contribute, but I ran a VSCode search through that repository and I cannot find the code `(context, child, model)` at all. Does anyone know where these pages are?

**Comment by JarvisHo** [comment]
![image](https://user-images.githubusercontent.com/7737124/128609956-e9a7b5f6-ad53-4b1a-ab5b-814362906253.jpeg)

This picture might help

**Comment by maheshmnj** [comment]
This issue is a duplicate of a closed issue https://github.com/flutter/website/issues/3475, But I see the codelab is still not updated and the [source code](https://github.com/flutter/codelabs/blob/master/cupertino_store/step_01/lib/product_list_tab.dart) looks correct. 

cc: @domesticmouse

**Comment by domesticmouse** [comment]
Fix inbound.
