### ISSUE TITLE
'Build a form with validation' page issue

### ISSUE THREAD

**Issue by gridcellcoder** [flutter/website#6084]
Page URL: https://flutter.dev/docs/cookbook/forms/validation.html
Page source: https://github.com/flutter/website/tree/master/src/docs/cookbook/forms/validation.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

According to this https://github.com/flutter/flutter/issues/20042 the GlobalKey should be static so that it is not rebuilt, or should it be in the initState()? Otherwise the keyboard disappears the first time the field is focused into.

**Comment by TahaTesser** [comment]
Hi @gridcellcoder 
I just tried the code sample as it is, there is no keyboard issue.

Can you please provide your `flutter doctor -v`, a complete reproducible minimal code sample, and complete `flutter run --verbose` logs running the minimal code sample?
Thank you
