### ISSUE TITLE
Splash screen with custom transition - extend docs example

### ISSUE THREAD

**Issue by Mikilll94** [flutter/website#6093]
It would be nice to extend the example in the docs regarding how to create a splash screen with custom transition:
https://flutter.dev/docs/development/ui/advanced/splash-screen#implement-the-splashscreen-interface

It would be nice to show this example also in Kotlin and also add some example project. Right now I cannot make this example to work in Kotlin.

**Comment by Mikilll94** [comment]
That's right, it's a docs issue but I think this issue is more important than you think, because resolving it would resolve also this issue: https://github.com/flutter/flutter/issues/63156

**Comment by camsim99** [comment]
The method for adding a splash screen no longer involves implementing the splash screen interface and the section seems to have bene removed.
