### ISSUE TITLE
'Background processes' page issue

### ISSUE THREAD

**Issue by jepperaskdk** [flutter/website#6103]
Page URL: https://flutter.dev/docs/development/packages-and-plugins/background-processes.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/packages-and-plugins/background-processes.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: I think this page needs official documentation, rather than just a link to a medium article.
The article is fine if you want to build a geofencing app. But it fails to show requirements (e.g. does it require platform specific code, as in the article?), it doesn't start with a simple 'hello world' function being run in the background, etc. Look in the comments of the article - hundreds have the same questions.

**Comment by darshankawar** [comment]
@jepperaskdk 
There's a similar open issue describing your case, https://github.com/flutter/website/issues/3104.
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen it.

Also, another similar issue: https://github.com/flutter/website/issues/2312
