### ISSUE TITLE
[PAGE ISSUE]: 'ThemeData's accent properties have been deprecated'

### ISSUE THREAD

**Issue by StaffordInnovations** [flutter/website#6112]
### Page URL

https://flutter.dev/docs/release/breaking-changes/theme-data-accent-properties.html

### Page source

https://github.com/flutter/website/tree/master/src/docs/release/breaking-changes/theme-data-accent-properties.md

### Describe the problem

I am getting the notification that "accentColor" has been deprecated and shouldn't be used however it's still in ThemeData on flutter.dev and there doesn't seem to be a substitution for accentColor.  When I use the migrate tool it just deletes the accentColor instead of it becoming secondary or anything else.  

### Expected fix

AccentColor should be changed in the ThemeData and the migration tool should migrate to the new item instead of deleting the issue.  

### Additional context

I'm using multiple themes in my app and calling the different ThemeData's at one point.  This is a really unpleasant surprise.  It looks like this change requires us to set up the different themes in multiple places instead of keeping it neat and tidy.

**Comment by TahaTesser** [comment]
Hi @StaffordInnovations 

> When I use the migrate tool it just deletes the accentColor instead of it becoming secondary or anything else.

Migration guide suggest to remove  since `accentColor ` is deprecated, this is just a documentation

> AccentColor should be changed in the ThemeData and the migration tool should migrate to the new item instead of deleting the issue.

If you have a proposal for Flutter itself, please file a new issue flutter/flutter repository

**Comment by basieboots** [comment]
You've completely missed the point and haven't assisted at all.  You're depreciating something without providing a reasonable substitution or alteration.  That's a pretty significant problem.  I would appreciate if someone would address this issue.
