### ISSUE TITLE
Update recipe to use Firebase Test Lab on 'An introduction to integration testing' page

### ISSUE THREAD

**Issue by SpiegelSoft** [flutter/website#6115]
### Page URL

https://flutter.dev/docs/cookbook/testing/integration/introduction.html

### Page source

https://github.com/flutter/website/tree/master/src/docs/cookbook/testing/integration/introduction.md

### Describe the problem

This describes the legacy integration testing procedure, which is not compatible with Flutter Test Lab.

### Expected fix

Please upgrade the documentation to show the newer version of integration testing

**Comment by TahaTesser** [comment]
Hi @SpiegelSoft 
This cookbook is outdated, on top of the page you can see a note, please follow the [link](https://flutter.dev/docs/testing/integration-tests), there you can find update instructions and steps to run your test on Firebase Test Lab 

I can work on updating this cookbook

**Comment by TahaTesser** [comment]
@atsansone 
Unfortunately, i'm swamped in Flutter issues in the `flutter/flutter` repo, working on couple of big projects :) 
Feel free to assign anyone else.

**Comment by atsansone** [comment]
This will be resolved in https://github.com/flutter/website/pull/10563 as the Intro page will be stripped down and the actual procedures will be in the https://docs.flutter.dev/testing/integration-tests page.
