### ISSUE TITLE
Change format of Step 4 example to `diff` on 'Adding interactivity to your Flutter app' page

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#6116]
### Page URL

https://flutter.dev/docs/development/ui/interactive.html

### Page source

https://github.com/flutter/website/tree/master/src/docs/development/ui/interactive.md

### Describe the problem

The code that was refreshed in #6111 isn't formatted correctly: It's formatted as a diff, but doesn't have changes in it. I suspect that line number changes made this happen.

### Expected fix

Either the format or the include should be changed.

**Comment by TahaTesser** [comment]
@kwalrath 
Looks like https://github.com/flutter/website/pull/6096/files was reverted by this new PR for causing a build issue?
Thanks for filing the issue

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/6346. Closing this issue.
