### ISSUE TITLE
[PAGE ISSUE]: 'Use lists'

### ISSUE THREAD

**Issue by JDFiX** [flutter/website#6131]
### Page URL

https://flutter.dev/docs/cookbook/lists/basic-list.html

### Page source

https://github.com/flutter/website/tree/master/src/docs/cookbook/lists/basic-list.md

### Describe the problem

In "Interactive example" has 11 issues

**Comment by TahaTesser** [comment]
Hi @JDFiX 
Thanks for filing the issue, I can fix it tonight

**Comment by TahaTesser** [comment]
closing in favor of https://github.com/flutter/website/issues/6155
