### ISSUE TITLE
[PAGE ISSUE]: 'Internationalizing Flutter apps'

### ISSUE THREAD

**Issue by FrancescoPenasa** [flutter/website#6132]
### Page URL

https://flutter.dev/docs/development/accessibility-and-localization/internationalization.html

### Page source

https://github.com/flutter/website/tree/master/src/docs/development/accessibility-and-localization/internationalization.md

### Describe the problem

This page and his previous one 
( https://flutter.dev/docs/development/accessibility-and-localization )
show me an unexpected text 
`a11y &amp; i18n`
when it should show 
`accessibility & localization`

the same with the value
`i18n`
that should be shown as 
`localization`
![Cattura](https://user-images.githubusercontent.com/37983733/128989730-23b69c0a-a374-4cd7-9b83-2e9c6efd55cc.JPG)

### Expected fix

accessibility & localization

**Comment by TahaTesser** [comment]
Hi @FrancescoPenasa 
Thanks for filing the issue 

`Accessibility` has the correct text for the page but you're proposing a section text to be changed too
![image](https://user-images.githubusercontent.com/48603081/129053535-b1a2a9a5-c065-4efb-a106-7816ccc7415a.png)

but you navigate back, it already has those names (besides a lot of people use this acronym for readability across different software)
![image](https://user-images.githubusercontent.com/48603081/129054055-9e75231b-e706-4988-a720-3aa563fe0419.png)


Internationalizing Flutter apps doesn't and this worth fixing but I am not sure replacing `a11y &amp; i18n` and the page will repeat this text twice on screenshot above 
![image](https://user-images.githubusercontent.com/48603081/129053622-7d9a2172-2823-4b83-ad30-d812d4150f72.png)
