### ISSUE TITLE
GitHub "test" actions are running on forks

### ISSUE THREAD

**Issue by jmagman** [flutter/website#6136]
### Describe the problem

Website GitHub test actions are running on my fork: https://github.com/jmagman/website/actions/runs/1121154318

### Expected fix

I think the `test` job needs an `if` containing `github.repository == 'flutter/website'` as is already on `deploy`:
https://github.com/flutter/website/blob/bcff5ed248027237a763eeca772d725083bf0b1b/.github/workflows/build.yml#L136-L139

**Comment by parlough** [comment]
Fixed by https://github.com/flutter/website/pull/6454
