### ISSUE TITLE
Replace `CachedNetworkImage` with `Image.network` on 'Work with cached images' page

### ISSUE THREAD

**Issue by Wes1324** [flutter/website#6138]
### Page URL

https://docs.flutter.dev/cookbook/images/cached-images/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/images/cached-images.md

### Describe the problem

The page states that 'In some cases, it’s handy to cache images as they’re downloaded from the web, so they can be used offline. For this purpose, use the cached_network_image package.' However, the documentation for Image.network states that 'All network images are cached regardless of HTTP headers.'

So why is this cookbook suggesting the use of CachedNetworkImage if Image.network does the same thing?

[This StackOverflow thread](https://stackoverflow.com/questions/65261263/flutter-networkimage-vs-cached-network-image) asks the same question.The answer seems to be that CachedNetworkImage shows a placeholder while loading the image, but Image.network can also do this via its loadingBuilder parameter.

### Expected fix

Deprecation of the cookbook if it no longer applies or clarification as to why CachedNetworkImage should be used over Image.network

**Comment by TahaTesser** [comment]
Hi @Wes1324 
Thanks for filing the issue, I think instead of deprecating, this could be updated to showcase `image.network` as caching is an advance topic for many

**Comment by Wes1324** [comment]
Hey @TahaTesser, thanks for your reply. Yeh, sounds good to me. I think the cookbook should also explain the advantages and disadvantages of using one over the other, because it is not clear at the moment what advantages `CachedNetworkImage` provides over `image.network`

**Comment by TahaTesser** [comment]
Perhaps, both methods could be documented  if there are pros and cons using either methods

**Comment by Wes1324** [comment]
I agree, mentioning both methods in the cookbook along with the advantages and disadvantages of both sounds like the best solution. Thanks

**Comment by atsansone** [comment]
Duplicates https://github.com/flutter/website/issues/8324. Closing.
