### ISSUE TITLE
Update 'Device Segmentation' section in  'Building adaptive apps' page to improve web theming

### ISSUE THREAD

**Issue by domesticmouse** [flutter/website#6141]
### Page URL

https://docs.flutter.dev/ui/layout/building-adaptive-apps

### Page source

https://github.com/flutter/website/tree/master/src/ui/layout/building-adaptive-apps.md

### Describe the problem

In [Device segmentation](https://docs.flutter.dev/ui/layout/building-adaptive-apps#device-segmentation) we suggest using `kIsWeb`, `Platform.isIOS` and friends to theme the UI for an appropriate platform. This is fragile, because `Platform` isn't available on Flutter for Web.

The gskinner Team worked around this issue by creating [`universal_platform`](https://pub.dev/packages/universal_platform) as a work around for the fragility of calling `Platform.isIOS` and friends on code that may wind up on the web.

@jonahwilliams said the following in passing about this situation:

> Use Platform/kIsWeb when the logic absolutely must run for a given platform. For example, talking to a plugin that only works on iOS or displaying a widget that only conforms to Play Store policy and not App Store.
> 
> Use Theme.of(context).platform for themeing/design choices, like what kind of switches to show and general cupertino/material adaptions. Helps stuff to work on mobile web just as well.
>
> Use defaultTargetPlatform if you're implementing platform logic in flutter/widgets, or are otherwise trying to avoid a dependency on Flutter's theming classes - like parts of the Flutter SDK "below" the theme layers

I believe that replacing the Device Segmentation documentation with something based on Jonah's suggested usages would be a net improvement.

Thoughts?

**Comment by atsansone** [comment]
@kevmoo : Do you have an opinion about this?
