### ISSUE TITLE
Fix TapHandler in example on 'Simple app state management' page

### ISSUE THREAD

**Issue by hrishikesh-kadam** [flutter/website#6148]
### Page URL

https://docs.flutter.dev/data-and-backend/state-mgmt/simple

### Page source

https://github.com/flutter/website/tree/master/src/docs/development/data-and-backend/state-mgmt/simple.md

### Describe the problem

The following change is necessary to unbreak the tap handler used in the [example](https://github.com/flutter/website/tree/master/examples/state_mgmt/simple).

```diff
diff --git a/examples/state_mgmt/simple/lib/src/provider.dart b/examples/state_mgmt/simple/lib/src/provider.dart
index d3672b70..9d5a7ba7 100644
--- a/examples/state_mgmt/simple/lib/src/provider.dart
+++ b/examples/state_mgmt/simple/lib/src/provider.dart
@@ -114,7 +114,7 @@ class MyCatalogItem extends StatelessWidget {
   // #docregion myTapHandler
   // GOOD
   void myTapHandler(BuildContext context) {
-    var cartModel = somehowGetMyCartModel(context);
+    var cartModel = Provider.of<CartModel>(context, listen: false);
     cartModel.add(item);
   }
   // #enddocregion myTapHandler
```

### Expected fix

I could have made the PR but because `somehowGetMyCartModel(context)` method is referred before getting into the details of the `provider` package, it would be appropriate that someone from the Flutter Team update the explanation.

**Comment by TahaTesser** [comment]
Hi @hrishikesh-kadam 
I believe `somehowGetMyCartModel` is just there for easier understanding,  your suggested change is correct but that's not the intention for using `somehowGetMyCartModel` and  also`somehowGetMyCartWidget` is there, which has same intention

**Comment by hrishikesh-kadam** [comment]
Hi @TahaTesser 
This change would affect the explanation in the markdown as well because the snippet is referred to using the code_excerpt_updater tool.
So, if I make the necessary change then it would affect the explanation as well.
Maybe Filip Hracek can better understand what I mean to say.
It would be helpful if you could tag Filip.

**Comment by TahaTesser** [comment]
cc: @filiph

**Comment by atsansone** [comment]
This was fixed in https://github.com/flutter/website/pull/3568. Closing this issue.

**Comment by hrishikesh-kadam** [comment]
@atsansone This issue has not been fixed yet.
Please follow the below steps to reproduce the issue.

1. `git clone --depth=1 git@github.com:flutter/website.git`
2. `cd website/examples/state_mgmt/simple/`
3. `flutter create --no-overwrite ./`
4. `flutter run -d chrome`
5. Click on `/provider`
6. Click on any list item, for example, `Add A`
7. See logs for the Exception.
