### ISSUE TITLE
[PAGE ISSUE]: 'Install'

### ISSUE THREAD

**Issue by black71bd** [flutter/website#6150]
### Page URL

https://flutter.dev/docs/get-started/install/

### Page source

https://github.com/flutter/website/tree/master/src/docs/get-started/install/index.md

### Describe the problem

Up coming

### Expected fix

You tink prbolem issue 

### Additional context

okhe

**Comment by TahaTesser** [comment]
Hi @black71bd 

> Up coming


The description of the issue is not clear. please file a new issue with clear description
