### ISSUE TITLE
https://flutter.dev/docs left pane is improper

### ISSUE THREAD

**Issue by Rishaba-Jain** [flutter/website#6151]
### Describe the problem

keyboard_arrow_down is appearing in the left pane in the Documentation site https://flutter.dev/docs 
Similar thing like chevron_right, content_copy comes up
Checked in Firefox and Chrome
Inspect Element tool points to ::before and ::after
Checked on 15 Aug 2021

### Additional context

![flutter docs keyboard_arrow_down](https://user-images.githubusercontent.com/71686718/129470405-a54f5890-5a36-4d75-9d77-ade5206b86a3.JPG)
![flutter docs issue 6151](https://user-images.githubusercontent.com/71686718/129470553-2cc7f9fd-6545-4ab1-a2a2-e5f0d1d30f22.JPG)

**Comment by AlexV525** [comment]
This is caused by the icon font failed to load, you can check the "Network" tab to see whether any fonts from google fonts were blocked.

**Comment by TahaTesser** [comment]
Hi @Rishaba-Jain 
I can't reproduce this issue,  can you please follow the above comment?

**Comment by Rishaba-Jain** [comment]
Hi @AlexV525 and @TahaTesser 
Thanks for looking in !
I am not getting this issue now. The site looks normal. What @AlexV525 has said might be the reason for this issue. In case the issue occurs again, will check the "Network" tab.

**Comment by TahaTesser** [comment]
Hi @Rishaba-Jain 
Given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
