### ISSUE TITLE
[PAGE ISSUE]: 'Hosting native Android and iOS views in your Flutter app with Platform Views'

### ISSUE THREAD

**Issue by TahaTesser** [flutter/website#6152]
### Page URL

https://flutter.dev/docs/development/platform-integration/platform-views.html

### Page source

https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/platform-views.md

### Describe the problem

CurrentLY there is no mention of the minimum API requirement for Hybrid composition and Virtual display

### Expected fix

Add the minimum API requirement where each implementation is functioning

**Comment by puzhengwu** [comment]
Hello, has the problem been confirmed?

**Comment by TahaTesser** [comment]
Closing this as the docs have updated
