### ISSUE TITLE
I cannot see the source code from this demo although it is peeking out

### ISSUE THREAD

**Issue by nyck33** [flutter/website#6153]
## Use case

There is a runnable demo here: https://flutter.dev/docs/cookbook/gestures/handling-taps#interactive-example
I can see the left sliver of source code.  I would like to be able to see it all.

## Proposal

I am unsure but believe some of them (runnable demos) let you move the app window so the code is visible.

**Comment by nyck33** [comment]
I get it, just be a bit more active as @seanfreiburg says.  Thanks.

**Comment by nyck33** [comment]
Please wait as I will post a screenshot next time as I believe I moved on from that example already and cannot recall where it was.

**Comment by TahaTesser** [comment]
@nyck33 
Have you seen something like this? 
![image](https://user-images.githubusercontent.com/48603081/129638307-35950664-1c42-4ac1-8c97-2d439b85d8c9.png)

https://flutter.dev/docs/cookbook/design/themes#interactive-example
