### ISSUE TITLE
Error handling updates

### ISSUE THREAD

**Issue by nt4f04uNd** [flutter/website#6164]
### Page URL

https://flutter.dev/docs/testing/errors

### Page source

https://github.com/flutter/website/blob/cbb14c5419d137bb1115b63ff4933bbefae71c94/src/docs/testing/errors.md

### Describe the problem

There are a few subtle changes required: [`FlutterError.dumpErrorToConsole`](https://api.flutter.dev/flutter/foundation/FlutterError/dumpErrorToConsole.html) mentionings should be replaced with [`FlutterError.presentError`](https://api.flutter.dev/flutter/foundation/FlutterError/presentError.html) and a new section created warning that when setting a custom the [`FlutterError.onError`](https://api.flutter.dev/flutter/foundation/FlutterError/onError.html), developers should call `FlutterError.presentError`.

### Expected fix

Described above and have a patch ready to be opened on Aug 23 (as mentioned in the PR template)

**Comment by TahaTesser** [comment]
Hi @nt4f04uNd 
Thanks for filing the issue and future PR
