### ISSUE TITLE
[PAGE ISSUE]: 'Obfuscating Dart code' misses the "ipa" target for 

### ISSUE THREAD

**Issue by ksilz** [flutter/website#6167]
### Page URL

https://flutter.dev/docs/deployment/obfuscate.html

### Page source

https://github.com/flutter/website/tree/master/src/docs/deployment/obfuscate.md

### Describe the problem

In [this section](https://flutter.dev/docs/deployment/obfuscate#obfuscating-your-app), this sentence lists the targets that support obfuscation:

_The apk, appbundle, ios, and ios-framework targets are currently supported._

At least in Flutter 2.5.0-5.1.pre (Channel beta), the `ipa` target supports obfuscation, too. I believe `ipa` was added in Flutter 2.0. 

### Expected fix

Change the sentence to (highlights are mine):

_The apk, appbundle, ipa, **ios,** and ios-framework targets are currently supported._

**Comment by TahaTesser** [comment]
Hi @ksilz 
Thanks filing the issue!
