### ISSUE TITLE
[PAGE ISSUE]: 'Build and release an Android app' - Line break missing before 

### ISSUE THREAD

**Issue by ksilz** [flutter/website#6168]
### Page URL

https://flutter.dev/docs/deployment/android.html

### Page source

https://github.com/flutter/website/tree/master/src/docs/deployment/android.md

### Describe the problem

There should be a line break before `buildToolsVersion`:
![Line break missing](https://user-images.githubusercontent.com/1061209/129862282-1ba124c3-6471-4a9a-a697-5b2c9c9e19e3.png)

### Expected fix

Add a line break before `buildToolsVersion`.

**Comment by TahaTesser** [comment]
Hi @ksilz
Thanks for filing the issue!

**Comment by MiraMarshall** [comment]
Closed. The issue is fixed.
