### ISSUE TITLE
[PAGE ISSUE]: 'Integration testing'

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#6169]
### Page URL

https://flutter.dev/docs/testing/integration-tests/

### Page source

https://github.com/flutter/website/tree/master/src/docs/testing/integration-tests/index.md

### Describe the problem

Are tests still supposed to be written with flutter driver?
when i do, i get
flutter: Warning: integration_test plugin was not detected.

If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.

**Comment by TahaTesser** [comment]
Hi @neiljaywarner 
Please follow the docs, add all the dependencies required, and your test is located in the `integration_test` directory as mentioned. "In your project, create a new directory integration_test/ with a new file, <name>_test.dart:".  You need to provide for this location when executing `flutter drive` 

`foo_test.dart` is your test class for example 
```console
flutter drive \
  --driver=test_driver/integration_test.dart \
  --target=integration_test/foo_test.dart \ 
  -d <DEVICE_ID>
```

Closing. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by neiljaywarner** [comment]
1) i get flutter: Warning: integration_test plugin was not detected.

If you're running the tests with `flutter drive`, please make sure your tests
are in the `integration_test/` directory of your package and use
`flutter test $path_to_test` to run it instead.

with instructions similar to what you described.
i can try a github project soon i guess
but why is it suggesting i use 'flutter test. ...'  when your for example block in blue about doesn't have 'flutter test' anywhere in sight?

**Comment by neiljaywarner** [comment]
also curious 1) can/should these be run from intellij or vscode, can/should they be run as a suite, and what about firebase, what's the best way to avoid flutter: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
but that's a separate item i know
