### ISSUE TITLE
Clean up memory page

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#6170]
### Page URL

https://flutter.dev/docs/development/tools/devtools/memory

### Describe the problem

1. At least one image on this page is too wide
2. There's some random HTML that needs removing/fixing. (Search for `dl>` or `dd>`.)
3. Remove all the usage of "e.g.".
4. Fix spelling of `ObectWithUniqueId` to `ObjectWithUniqueId`.

**Comment by MiraMarshall** [comment]
Closing because this issue has been addressed.
