### ISSUE TITLE
Improve integration_test migration guide

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#6171]
### Page URL

https://flutter.dev/docs/testing/integration-tests#migrating-from-flutter_driver

### Page source

https://github.com/flutter/website/issues/new?template=1_page_issue.yml&title=[PAGE%20ISSUE]:%20%27Integration%20testing%27&page-url=https://flutter.dev/docs/testing/integration-tests/&page-source=https://github.com/flutter/website/tree/master/src/docs/testing/integration-tests/index.md

### Describe the problem

The "Migrating from flutter_driver" docs could be more descriptive, and provide more mappings from the old API to the new API.

**Comment by miquelbeltran** [comment]
Note to self, the page is now located here: https://github.com/flutter/website/blob/main/src/testing/integration-tests/index.md
