### ISSUE TITLE
Remove FlutterDay easter eggs

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#6172]
See https://github.com/dart-lang/site-www/issues/3503 for details.

**Comment by domesticmouse** [comment]
cl/392364641 will land a removal of an easter egg from "How to write a Flutter plugin" codelab.

**Comment by domesticmouse** [comment]
Easter eggs removed from:
 - How to write a Flutter plugin
 - Building beautiful UIs with Flutter

CLs in flight to remove Easter eggs from:
 - Multi-platform Firestore Flutter
 - Using a plugin with a Flutter web app

That's all the Easter eggs I could find in our gDoc based codelabs. Please ping if I've missed something.
