### ISSUE TITLE
'플랫폼 별 코드 작성' page issue

### ISSUE THREAD

**Issue by soharang** [flutter/website#6173]
Page URL: https://flutter-kr.io/docs/development/platform-integration/platform-channels.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/platform-channels.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:  
The link of view page source icon is wrong.
I was watching korean document and wanted to edit koeran one.
But source link in the page is the one in english, "https://github.com/flutter/website/tree/master/src/docs/development/platform-integration/platform-channels.md".
Actual one is "https://github.com/flutter-korea/website/edit/master-ko/src/docs/development/platform-integration/platform-channels.md"

Where can I correct the link?

**Comment by TahaTesser** [comment]
Hi @soharang 
Looks like you've filed the issue in an incorrect repository, https://github.com/flutter-korea/website is a fork, please file an issue on their repository. 

Closing, please write in the comments and I will reopen it.
Thank you
