### ISSUE TITLE
Command snippet cannot be selected 

### ISSUE THREAD

**Issue by Tomucha** [flutter/website#6174]
### Page URL

https://flutter.dev/docs/deployment/obfuscate.html

### Page source

https://github.com/flutter/website/tree/master/src/docs/deployment/obfuscate.md

### Describe the problem

Some of the command line examples have: user-select: none CSS property, so the reader cannot select fragment of the CLI and copy it. For example the line "flutter build apk --obfuscate --split-debug-info=/<project-name>/<directory>" can be copied only with the icon on the right side of the example.

It's possible that it is present on other doc pages too.

### Expected fix

Let me select and copy whatever part of the code I need. Remove user-select: none property.

**Comment by Tomucha** [comment]
Try to select "symbolize" in example here:
https://flutter.dev/docs/deployment/obfuscate#reading-an-obfuscated-stack-trace

There is something fishy about the code highlighter.

**Comment by sfshaza2** [comment]
Oh wow, this is bad and should be fixed.
