### ISSUE TITLE
Fix lint errors in DartPads on explicit animations page

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#6175]
### Page URL

https://flutter.dev/docs/codelabs/explicit-animations

### Describe the problem

This page (which is incomplete and not yet live), has several embedded DartPad instances. Most of them run (the last one didn't work for me), but they all complain about lint errors.

This page needs fixing and finishing so that it can be added to the sidenav.

**Comment by TahaTesser** [comment]
Hi @sfshaza2 
Thanks for filing the issue. 

I'm working and tracking lint issues for all interactive samples and snippets from the website in https://github.com/flutter/website/issues/6155., added the Codelab section in my issue.
I will send PRs when the website is ready to accept.

Closing in favor of https://github.com/flutter/website/issues/6155
