### ISSUE TITLE
Fix lint errors in implicit animations page

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#6176]
### Page URL

https://flutter.dev/docs/codelabs/implicit-animations

### Describe the problem

As it says, this page has several DartPads with numerous lint warnings.

**Comment by TahaTesser** [comment]
Hi @sfshaza2 
Thanks for filing the issue. 

I'm working and tracking lint issues for all interactive samples and snippets from the website in https://github.com/flutter/website/issues/6155., added the Codelab section in my issue.
I will send PRs when the website is ready to accept.

Closing in favor of https://github.com/flutter/website/issues/6155
