### ISSUE TITLE
Fix lint errors in layout basics page

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#6177]
### Page URL

https://flutter.dev/docs/codelabs/layout-basics

### Describe the problem

The lint errors in the DartPad.

**Comment by TahaTesser** [comment]
Thanks for filing the issue. 

I'm working and tracking lint issues for all interactive samples and snippets from the website in https://github.com/flutter/website/issues/6155., added the Codelab section in my issue.
I will send PRs when the website is ready to accept.

Closing in favor of https://github.com/flutter/website/issues/6155
