### ISSUE TITLE
Fix lint errors in embedded DartPads (umbrella bug)

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#6178]
### Page URLs

- https://flutter.dev/docs/cookbook/effects/download-button
- https://flutter.dev/docs/cookbook/effects/drag-a-widget
- https://flutter.dev/docs/cookbook/effects/expandable-fab
- https://flutter.dev/docs/cookbook/effects/nested-nav
- https://flutter.dev/docs/cookbook/effects/parallax-scrolling
- https://flutter.dev/docs/cookbook/effects/staggered-menu-animation
- https://flutter.dev/docs/get-started/codelab-web
- https://flutter.dev/docs/cookbook/navigation/navigation-basics
- https://flutter.dev/docs/cookbook/lists/horizontal-list
- https://flutter.dev/docs/cookbook/lists/grid-lists
- https://flutter.dev/docs/cookbook/lists/basic-list

### Describe the problem

The embedded DartPad runs but displays a lint error.

**Comment by TahaTesser** [comment]
Hi @sfshaza2 
Thanks for filing the issue. 

I'm working and tracking lint issues for all interactive samples and snippets from the website in https://github.com/flutter/website/issues/6155., added the Codelab section in my issue.
I will send PRs when the website is ready to accept.

Closing in favor of https://github.com/flutter/website/issues/6155
