### ISSUE TITLE
Incorrect header in 'Create and style a text field'

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#6179]
### Page URL

https://flutter.dev/docs/cookbook/forms/text-input

### Describe the problem

The last header says "Interactive example", but it's not. Either change the header to "Complete example" OR use an embedded DartPad (in which case it would be interactive).

**Comment by d-cryptic** [comment]
Can I take this issue?

**Comment by sfshaza2** [comment]
Absolutely!

**Comment by d-cryptic** [comment]
Ok, thanks, sorry for deleting the comment, I was to write it in better way

**Comment by piedcipher** [comment]
Is this fixed?

**Comment by sfshaza2** [comment]
Apparently. I just looked and it IS an interactive example. Closing.
