### ISSUE TITLE
[PAGE ISSUE]: 'Integrate a Flutter module into your iOS project'

### ISSUE THREAD

**Issue by farr64** [flutter/website#6180]
### Page URL

https://flutter.dev/docs/development/add-to-app/ios/project-setup.html

### Page source

https://github.com/flutter/website/tree/master/src/docs/development/add-to-app/ios/project-setup.md

### Describe the problem

**You recommend:**

In your target’s build settings, change the **Info.plist File** `(INFOPLIST_FILE)` setting path from `path/to/Info.plist` to `path/to/Info-$(CONFIGURATION).plist`.

**The macro `$(CONFIGURATION)` causes Xcode Version 12.5.1 (12E507) to complain loudly.**

This line for Debug.xcconfig with the macro `$(CONFIGURATION)` causes Xcode to complain:
`INFOPLIST_FILE = Runner/Info-$(CONFIGURATION).plist;`

This line for Release.xcconfig with the macro `$(CONFIGURATION)` causes Xcode to complain:
`INFOPLIST_FILE = Runner/Info-$(CONFIGURATION).plist;`

**Naming each file explicitly (without the macro) solved the problem.**

This line for Debug.xcconfig makes Xcode happy:
`INFOPLIST_FILE = Runner/Info-Debug.plist;`

This line for Release.xcconfig makes Xcode happy:
`INFOPLIST_FILE = Runner/Info-Release.plist;`

### Expected fix

Either fix the macro expansion or change the documentation to reflect the current reality (at least with this version of Xcode).

Thanks.

Alfredo

### Additional context

macOS Big Sur 11.5.2 (20G95)

![ps 2021-08-20 at 9 16 56 PM](https://user-images.githubusercontent.com/4096768/130308804-d8845041-4eff-41e9-8055-c7f01fca31de.jpg)

**Comment by TahaTesser** [comment]
Hi @farr64 

> INFOPLIST_FILE = Runner/Info-Release.plist;

This is hard corded



> You must also add $(PROJECT_DIR)/Flutter/$(CONFIGURATION) to the Framework Search Paths (FRAMEWORK_SEARCH_PATHS) build setting.

Have you tried this?

**Comment by farr64** [comment]
I haven't tried this **general** approach yet.

For now, the **hard-coded** approach works perfectly for me and I have some deadlines to meet. So, your suggested  **general** approach is in my TODO list.

The important thing is that my debug version of the App allows hot reload and my release version of the App doesn't contain the elements that would make Apple's App Store to complain.

So, I'm a happy camper.

Thanks for the tip, @TahaTesser.

**Comment by TahaTesser** [comment]
Hi @farr64 
I believe the documentation is correct, it is better to provide `$(CONFIGURATION)` so it can be dynamic, not hardcoded
Closing, thank you
