### ISSUE TITLE
Add scoop as an option to install Flutter on Windows

### ISSUE THREAD

**Issue by adnanegit** [flutter/website#6182]
### Page URL

https://flutter.dev/docs/get-started/install/windows

### Describe the problem

missing scoop command

## Scoop

if you have scoop installed run the following command from Windows Terminal
scoop install flutter

### Additional context

make sure java is installed

**Comment by TahaTesser** [comment]
Hi @adnanegit 
Can you please link the scoop Flutter documentation?

**Comment by adnanegit** [comment]
Hi Taha,
the scoop installation process is in
https://github.com/lukesampson/scoop-extras
here's the json
https://github.com/lukesampson/scoop-extras/blob/master/bucket/flutter.json
i actually ended up discarding that method & following the method on the
flutter docs :) so if you want to add it to the docs that's up to you.
scoop does install flutter but there are some env variables that need to be
fixed.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by TahaTesser** [comment]
Hi @adnanegit
Thanks for the details

**Comment by atsansone** [comment]
Installation of Flutter remains unmanaged by packages because of the difficulty in maintaining them. For this reason, this change will not be made. Closing this issue.
