### ISSUE TITLE
Can Dart Board be added to the state management page

### ISSUE THREAD

**Issue by ahammer** [flutter/website#6183]
## Dart Board

A modular feature management framework for flutter. It's designed to help encapsulate and isolate features. Includes examples/frameworks, small kernel and many ready to use decoupled features such as debugging, logging, auth, redux, locator, particle system and more.

* [Dart Board - Homepage + Demos][]
* [Dart Board - Core Package][]
* [Dart Board - Github][]
* [Dart Board - Getting Started][]
* [Dart Board - Features][]

[Dart Board - Homepage + Demos]: https://dart-board.io
[Dart Board - Core Package]: https://pub.dev/packages/dart_board_core
[Dart Board - Github]: https://github.com/ahammer/dart_board
[Dart Board - Getting Started]: https://github.com/ahammer/dart_board/blob/master/GETTING_STARTED.md
[Dart Board - Features]:  https://pub.dev/publishers/dart-board.io/packages

### How would you like us to fix this problem?

I've built this library (100% open source), including state management and architecture guidance for a flutter app, including examples and features, tests, documentation and tutorials. Information is above. Would love if this could be added to:

https://github.com/flutter/website/edit/master/src/docs/development/data-and-backend/state-mgmt/options.md

Thanks in advance.

**Comment by atsansone** [comment]
@sfshaza2 : Up to you if you want to add this as a resource.
