### ISSUE TITLE
Fix code error on 'Migrating Buttons With Custom Overlay Colors'  page

### ISSUE THREAD

**Issue by Swayam221** [flutter/website#6185]
### Page URL

https://flutter.dev/docs/release/breaking-changes/buttons#migrating-buttons-with-custom-overlay-colors

### Page source

https://github.com/flutter/website/blob/master/src/docs/release/breaking-changes/buttons.md

### Describe the problem

How to reproduce:

1. Create a new flutter project.
2. Add copy the code for the TextButton widget from https://flutter.dev/docs/release/breaking-changes/buttons#migrating-buttons-with-custom-overlay-colors , and it to the body of the default starting application for a new flutter project.

The error: The line return null is responsible for the error as the expected return type is a 'Color' . Shown in line number 31 in the following code snapshot.

![WhatsApp Image 2021-08-20 at 11 16 23 PM](https://user-images.githubusercontent.com/68892315/130475088-c2ddbe15-e642-4f08-a38e-9dc6d44e9bcc.jpeg)

### Expected fix

Can be fixed by replacing `MaterialStateProperty.resolveWith<Color>` with `MaterialStateProperty.resolveWith<Color?>` wherever necessary.

**Comment by TahaTesser** [comment]
Hi @Swayam221 
Thanks for filing the issue,

**Comment by Swayam221** [comment]
> Hi @Swayam221
> Thanks for filing the issue,

You're welcome.
I would like to work on this issue as well.

**Comment by Coronon** [comment]
Duplicate of #6333

And fixed in 6dbe0c52428c93f8b2cc55b30ba1ba170782343e

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/6333. Closing this issue.
