### ISSUE TITLE
[PAGE ISSUE]: Codelabs & workshops - Get to know Firebase for Flutter (workshop) youtube video plays only in 360p resolution.

### ISSUE THREAD

**Issue by hrishikesh-kadam** [flutter/website#6190]
### Page URL

https://flutter.dev/docs/codelabs

### Page source

https://github.com/flutter/website/tree/master/src/docs/codelabs/index.md

### Describe the problem

[Get to know Firebase for Flutter (workshop)](https://youtube.com/watch?v=4wunbF29Kkg) youtube video plays only in 360p resolution.
Other users have also commented on youtube about this issue.
Not a blocker for me, as there is an alternate [pre-recorded video](https://firebase.google.com/learn/codelabs/firebase-get-to-know-flutter) as well as [codelab](https://firebase.google.com/codelabs/firebase-get-to-know-flutter).
Just thought of reporting.

**Comment by RedBrogdon** [comment]
Thanks for catching this, @hrishikesh-kadam. I've reached out to the author of the video to see if something went wrong in the upload process.
