### ISSUE TITLE
[PAGE ISSUE]: 'Build and release an Android app' img tags syntax

### ISSUE THREAD

**Issue by Tommy-Elliott** [flutter/website#6207]
### Page URL

https://flutter.dev/docs/deployment/android/

### Page source

https://github.com/flutter/website/tree/main/src/docs/deployment/android.md

### Describe the problem

https://flutter.dev/docs/deployment/android#how-do-i-build-a-release-from-within-android-studio
In this section there appear to be two `<img>` elements that are incorrectly formed html (quotes might be mismatched?) which leads to the html tags being displayed as text instead of the actual desired html images being displayed.

### Expected fix

Resolve the HTML syntax for those two img tags.

### Additional context

![BadImgTags](https://user-images.githubusercontent.com/6034004/131150585-59a05959-fcd0-4b53-bcd4-0a1f87ee1cd0.png)

**Comment by TahaTesser** [comment]
Hi @Tommy-Elliott 
Thanks for filing the issue
