### ISSUE TITLE
ShortcutActivator not yet implemented in api.flutter.dev

### ISSUE THREAD

**Issue by Konradrundfunk** [flutter/website#6213]
### Page URL

https://api.flutter.dev/flutter/widgets/Shortcuts-class.html

### Page source
Down below is the affected codeblock.
```
  Widget build(BuildContext context) {
    return Shortcuts(
      shortcuts: <ShortcutActivator, Intent>{
        LogicalKeySet(LogicalKeyboardKey.arrowUp): const IncrementIntent(),
        LogicalKeySet(LogicalKeyboardKey.arrowDown): const DecrementIntent(),
      },
```

### Describe the problem

`ShortcutActivator` is used in the Shortcuts example page but its not yet implemented in the current dart runtime. I am currently viewing f4abaa0735 • HEAD (no branch) wich is the default when accessing the url mentioned above. 

### Expected fix

Use the `LogicalKeySet` keyword instead to cast the object.

### Additional context

The problem occurs in both examples.

**Comment by TahaTesser** [comment]
Hi @Konradrundfunk 
This belongs to the `flutter/flutter` issue, not the `flutter/website and the `ShortcutActivator` error is thrown Codelab run on stable channel so it is not an issue with API docs.
