### ISSUE TITLE
[PAGE ISSUE]: 'Supported platforms' Schrodinger's Cat issue for Android 19 & 22

### ISSUE THREAD

**Issue by timsneath** [flutter/website#6230]
### Page URL

https://flutter.dev/docs/development/tools/sdk/release-notes/supported-platforms/

### Page source

https://github.com/flutter/website/tree/main/src/docs/development/tools/sdk/release-notes/supported-platforms.md

### Describe the problem

These SDKs are both at both Google-tested and community-tested levels. Unlikely both can be true.

**Comment by parlough** [comment]
Fixed in https://github.com/flutter/website/commit/d795efebb1f8c8ed9f3a75750b831439c86695fa
