### ISSUE TITLE
[PAGE ISSUE]: 'Test drive'

### ISSUE THREAD

**Issue by irungentootoo** [flutter/website#6233]
### Page URL

https://flutter.dev/docs/get-started/test-drive/

### Page source

https://github.com/flutter/website/tree/main/src/docs/get-started/test-drive/index.md

### Describe the problem

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.IllegalAccessError: class org.gradle.internal.compiler.java.ClassNameCollector (in unnamed module @0x47d8071d) cannot access class com.sun.tools.javac.code.Symbol$TypeSymbol (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x47d8071d

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1

### Expected fix

how to fix stupid glide?

### Additional context

not everything is as instructed

same problem https://github.com/gradle/gradle/issues/16641 doesnt help for me

**Comment by TahaTesser** [comment]
Hi @irungentootoo 
This is an issue with Flutter website or it's sample, see https://github.com/flutter/flutter/issues/85915
