### ISSUE TITLE
Add another example to 'Understanding constraints'

### ISSUE THREAD

**Issue by nischandra** [flutter/website#6234]
### Page URL

https://docs.flutter.dev/ui/layout/constraints

### Page source

https://github.com/flutter/website/tree/main/src/docs/ui/layout/constraints.md

### Describe the problem

Hey, to all the examples given on this article, there's one possibility that can add too, and that is.
What if, Container with Screen as a parent, and has size too, and with child too, and child's also has as size.
Then the outcome will be : Will go with Container's Size and ignores child size, but can adapt child's color, if given.

Thanks to the flutter team, who is always there to support us ❤️.
Nishant here.

### Expected fix

Just add the another possibility 😉

### Additional context

No, but you can check the outcome on your own.

**Comment by atsansone** [comment]
@nischandra : Would you happen to have sample code for this example?
