### ISSUE TITLE
[PAGE ISSUE]: 'Google APIs'

### ISSUE THREAD

**Issue by avajiyo** [flutter/website#6261]
### Page URL

https://flutter.dev/docs/development/data-and-backend/google-apis/

### Page source

https://github.com/flutter/website/tree/main/src/docs/development/data-and-backend/google-apis.md

### Describe the problem

A couple of hyperlinks on the page were found to be no longer valid.

### Expected fix

URLs that need to change:

https://pub.dev/documentation/googleapis/latest/
=> https://pub.dev/packages/googleapis

https://pub.dev/documentation/googleapis/latest/youtube.v3/youtube.v3-library.html
=> https://pub.dev/packages/youtube_api_v3

**Comment by piedcipher** [comment]
Nice catch!

Issue is also being tracked here: https://github.com/google/googleapis.dart/issues/293

**Comment by Swastik2000** [comment]
Can I work on this issue?

**Comment by sfshaza2** [comment]
Yes, @Swastik2000.

**Comment by MiraMarshall** [comment]
Closing. All of the links on the page work.
