### ISSUE TITLE
[PAGE ISSUE]: 'Hosting native Android and iOS views in your Flutter app with Platform Views'

### ISSUE THREAD

**Issue by om-ha** [flutter/website#6265]
### Page URL

https://flutter.dev/docs/development/platform-integration/platform-views/

### Page source

https://github.com/flutter/website/tree/main/src/docs/development/platform-integration/platform-views.md

### Describe the problem

- The problem occurs in the [performance section ](https://flutter.dev/docs/development/platform-integration/platform-views#performance) of the page.

- The following  implies that in Android 10 or above, performance (FPS) is worse. Which is wrong:
> In Android 10 or above, the graphics memory is copied twice. **_As this copy happens per frame_**...

- Original Text:

> Prior to Android 10, Hybrid composition copies each Flutter frame out of the graphic memory into main memory, and then copies it back to a GPU texture. In Android 10 or above, the graphics memory is directly copied twice. As this copy happens per frame, the performance of the entire Flutter UI may be impacted.

### Expected fix

This is only an initial suggestion, feel free to modify and correct me if I'm wrong:

> Prior to Android 10, Hybrid composition copies each Flutter frame out of the graphic memory into main memory, and then copies it back to a GPU texture. As this copy happens per frame, the performance of the entire Flutter UI may be impacted. However in Android 10 or above, the graphics memory is copied twice, which is considerably better than the former case.

**Comment by parlough** [comment]
Thanks for opening an issue! Fixed by https://github.com/flutter/website/pull/7411
