### ISSUE TITLE
Fix inability to open 'Animations tutorial' page via search

### ISSUE THREAD

**Issue by admarwick** [flutter/website#6272]
### Page URL

https://flutter.dev/docs/development/ui/animations/tutorial/

### Page source

https://github.com/flutter/website/tree/main/src/docs/development/ui/animations/tutorial.md

### Describe the problem

In Google Search results instead of a description of this page there is grim statement: No information is available for this page.

This is because you prevent the Google crawler from  reading the page. Why? Only you can say but it seems like a bad idea to hide the content, don't you think?

### Expected fix

Allow the Google crawler to index the page

**Comment by darshankawar** [comment]
<img width="562" alt="Screenshot 2021-09-15 at 4 34 24 PM" src="https://user-images.githubusercontent.com/67046386/133422385-a999fb64-cb5d-40e1-afbb-13332b934aad.png">


Clicking on `Learn Why`:

<img width="718" alt="Screenshot 2021-09-15 at 4 34 44 PM" src="https://user-images.githubusercontent.com/67046386/133422504-c8a91493-6529-4bde-9cea-7120bb8b2133.png">

**Comment by atsansone** [comment]
This page can be opened from a Google search in the USA. 

![image](https://github.com/flutter/website/assets/706219/8baaa214-01e9-41c4-9e15-44036a2b6d0a)

![image](https://github.com/flutter/website/assets/706219/9506e55e-18fc-4a27-9e80-c783c487cf33)

The URL has changed and this may help, but this would not be a documentation issue. This would be a network routing or caching issue. Check with your local network support. 

Closing this issue.
