### ISSUE TITLE
[PAGE ISSUE]: 'Introduction to widgets' 

### ISSUE THREAD

**Issue by nickppbd** [flutter/website#6279]
### Page URL

https://flutter.dev/docs/development/ui/widgets-intro/

### Page source

https://github.com/flutter/website/tree/main/src/docs/development/ui/widgets-intro.md

### Describe the problem

No problem, just curious.

### Additional context

Who wrote this document?

**Comment by darshankawar** [comment]
@nickppbd 
Can we know what are you curious about the page ?
If there's no issues with it, is it ok to close this ?

**Comment by nickppbd** [comment]
Who wrote this document? asked again.

**Comment by darshankawar** [comment]
@nickppbd The repo is to track bugs and feature requests. Closing as there doesn't seem to be an issue with the page referred.

**Comment by nickppbd** [comment]
amazing stupid decision
