### ISSUE TITLE
[PAGE ISSUE]: 'Explicit animations' missing dispose

### ISSUE THREAD

**Issue by idkq** [flutter/website#6282]
### Page URL

https://flutter.dev/docs/codelabs/explicit-animations/

### Page source

https://github.com/flutter/website/tree/main/src/codelabs/explicit-animations.md

### Describe the problem

Missing dispose on code after this line "Run the following example to see this explicit animation in action!". I tried to fix but could not find the source code.

### Expected fix

```dart
  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
```

**Comment by darshankawar** [comment]
It may have something to do with below note in the page:

<img width="426" alt="Screenshot 2021-09-16 at 5 21 39 PM" src="https://user-images.githubusercontent.com/67046386/133607339-bab2c24f-7dfc-4e5e-ad21-0aa0c466abd8.png">

**Comment by domesticmouse** [comment]
This has been fixed. Thanks for the report!
