### ISSUE TITLE
[PAGE ISSUE]: 'Create a horizontal list'

### ISSUE THREAD

**Issue by ajeets1978** [flutter/website#6294]
### Page URL

https://flutter.dev/docs/cookbook/lists/horizontal-list/

### Page source

https://github.com/flutter/website/tree/main/src/docs/cookbook/lists/horizontal-list.md

### Describe the problem

The list in horizontal scroll mode doesn't scroll, when running on web. Though your sample on this page is also not scrolling.

**Comment by TahaTesser** [comment]
Hi @ajeets1978 
The drag to scroll on the desktop is disabled by default, please see https://flutter.dev/docs/release/breaking-changes/default-scroll-behavior-drag. you can scroll horizontally by holding the shift key

If you're Windows or Linux, it is shift+ scroll is currently broken Please see https://github.com/flutter/flutter/issues/75180#issuecomment-920200473

Closing as it is an issue with example itself
