### ISSUE TITLE
Verify and updated permanent PATH guide on 'macOS install' page

### ISSUE THREAD

**Issue by koiranos** [flutter/website#6295]
### Page URL

https://flutter.dev/docs/get-started/install/macos/

### Page source

https://github.com/flutter/website/tree/main/src/docs/get-started/install/macos.md

### Describe the problem

By following the [**Get the Flutter SDK**](https://flutter.dev/docs/get-started/install/macos#get-sdk) installation way, the provided zip `flutter_macos_2.5.1-stable.zip` file has not the necessary instructions to execute the `flutter` command. 

After adding flutter tool to path as it is suggested in [**Update Your Path**](https://flutter.dev/docs/get-started/install/macos#update-your-path) section and verifying that the paths for flutter and dart a correct, the execution of `flutter doctor` command returns `command not found: flutter`.

Steps for verification:

**Checking path for flutter and dart**
```
kostas@myMac ~ % which flutter dart
/Users/kostas/Documents/Projects/others/flutter/bin/flutter
/Users/kostas/Documents/Projects/others/flutter/bin/dart
```

**running flutter doctor**
```
kostas@myMac ~ % flutter doctor
zsh: command not found: flutter
```

The only viable way to be able to use the `flutter` command is by cloning the GitHub repository from the provided url `https://github.com/flutter/flutter.git`.

### Expected fix

There are two possible solutions for this issue:
1. Assuming that the path is exported as it should. The extraction location of the SDK should be a global one and not a desired one in order for the flutter tool to be identified from the system correctly. 
2. If the fist suggestion is not the case. Provide an updated version of the SDK zip file that helps in the same way.

**Comment by TahaTesser** [comment]
Hi @koiranos 
Instructions for path in  [**Get the Flutter SDK**](https://flutter.dev/docs/get-started/install/macos#get-sdk) are temporary  as mentioned in the last line
"This command sets your PATH variable for the current terminal window only. To permanently add Flutter to your path, see Update your path."

if you want a permanent path, you need to edit your path file as instructed in  [**Update Your Path**](https://flutter.dev/docs/get-started/install/macos#update-your-path)

**Comment by koiranos** [comment]
Hi @TahaTesser as you can see from my post I have mentioned the permanent path approach, which I followed as instructed. I edited the zshrc file and exported the required path. 

The issue here is that the [Get the Flutter SDK](https://flutter.dev/docs/get-started/install/macos#get-sdk) way is a little bit _problematic_ while the [Git Clone](https://flutter.dev/docs/get-started/install/macos#downloading-straight-from-github-instead-of-using-an-archive) approach is working as expected. I opened this ticket to inform you that there is an inconsistency in the instructions that need to be taken care.

**Comment by atsansone** [comment]
@koiranos : This issue was raised against a much older version of Flutter. It should be resolved due to subsequent changes to the docs and the Flutter SDK. Closing this issue.

If this is still a concern, please reopen this issue. Thanks!
