### ISSUE TITLE
Explain relationship between `Flexible` and `Expanded` widgets on 'Basic Flutter layout concepts' page

### ISSUE THREAD

**Issue by gazialankus** [flutter/website#6300]
### Page URL

https://docs.flutter.dev/codelabs/layout-basics

### Page source

https://github.com/flutter/website/tree/main/src/docs/codelabs/layout-basics.md

### Describe the problem

Under [Expanded widget](https://flutter.dev/docs/codelabs/layout-basics#expanded-widget), its relation to Flexible is not very clear. Right above this, Flexible(fit: FlexFit.tight) is used, but this is exactly the same as [Expanded](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/basic.dart#L5042) whereas Expanded is introduced as something different without mentioning that it's exactly the same as what we did in the last task. Also "What’s the difference between Flexible and Expanded" green box does not really answer the question but gives some suggestions that is not very clear. 

### Expected fix

I think Expanded should be introduced as a shorthand for Flexible(fit: FlexFit.tight), which we just saw in the previous example. 

Furthermore, some more clarity about FlexFit.loose would be nice, maybe a more intuitive explanation of what it's for. For example we could say "it makes the child squishable but not stretchable". The child is not always at its preferred size, when there's little space it is squished.

**Comment by TahaTesser** [comment]
Hi @gazialankus 
Thanks for filing the issue

**Comment by sfshaza2** [comment]
We are removing this codelab as per https://github.com/flutter/website/pull/9876.
