### ISSUE TITLE
[PAGE ISSUE]: Recipes section is empty in   'Testing Flutter apps' , `testing-toc.md` is defective with Jekyll upgrade

### ISSUE THREAD

**Issue by ChaserVasya** [flutter/website#6308]
### Page URL

https://flutter.dev/docs/testing/

### Page source

https://github.com/flutter/website/tree/main/src/docs/testing/index.md

### Describe the problem

"Recipes" are empty. 

![image](https://user-images.githubusercontent.com/74578917/134471872-ea35606a-fc4b-4fe3-b899-4c76037af844.png)

### Expected fix

Full them

**Comment by TahaTesser** [comment]
Hi @ChaserVasya 
Thanks for catching, looks like `docs/testing-toc.md ` is missing ([source ](https://github.com/flutter/website/blame/2a91dbf5c84f776aa74a70d3e94433472aa73b7e/src/docs/testing/index.md#L54))

**Comment by sfshaza2** [comment]
Hm. This page uses the correct include text:

```
{% include docs/testing-toc.md type='unit' %}

```

The include files are located in src/_includes and the testing-toc.md file is present under the `docs` directory, as it should be.

@johnpryan, can you take a look at this? And maybe include Khanh? (I don't know what her GitHub handle is -- it's not yet registered internally on the go page.)

**Comment by sfshaza2** [comment]
cc @RedBrogdon, in case you have an insight.

**Comment by sfshaza2** [comment]
A ha! She is @khanhnwin.

**Comment by RedBrogdon** [comment]
Looks like these were last altered in #6188. @btobin, can you take a look and see if one of the paths no longer lines up?

**Comment by btobin** [comment]
With the Jekyll upgrade, `site.pages[n].url` no longer includes the `.html` extension. We saw this same bug in `cookbook-toc.html` but we've missed this one. I'll update that logic in the include.
