### ISSUE TITLE
.html files are no longer forwarded

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#6313]
### Describe the problem

We used to forward URLs such as `https://flutter.dev/docs/cookbook/animation/page-route-animation.html` to their ".html"-less equivalents (in this case, https://flutter.dev/docs/cookbook/animation/page-route-animation).

Because this no longer happens, we're seeing a lot more 404s than before August 27. (The infrastructure was changed August 25, but due to a bug fixed in #6208, we don't have 404 info for 8/25 or 8/26.)

Maybe related: We're also seeing new 404s for pages ending in `.`. For example, the top 404 is `/go/android-plugin-migration.`, which should be https://flutter.dev/go/android-plugin-migration. 

### Expected fix

Maybe forward all `xyz.html` pages to `xyz`, and `xyz.` pages to `xyz`.

### Additional context

Of the top-10 404s from 8/27 - 9/23, **nine** end in either `.html` or `.`. The tenth one is `/images/catalog-widget-placeholder.png`. None of these was the cause of a 404 in the preceding 30 days.

**Comment by btobin** [comment]
@kwalrath Please see my above PR #6339. I cannot figure out a full proof way to redirect `xyz. -> xyz`. Open to suggestions/recommendations. I'm assuming these urls are being requested by bots?

**Comment by kwalrath** [comment]
Idk. @khanhnwin maybe you can help here?
