### ISSUE TITLE
[PAGE ISSUE]: 'Create a scrolling parallax effect'

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/website#6314]
### Page URL

https://flutter.dev/docs/cookbook/effects/parallax-scrolling/

### Page source

https://github.com/flutter/website/tree/main/src/docs/cookbook/effects/parallax-scrolling.md

### Describe the problem

The code on this page is not up to date with the source of truth in flutter/codelabs.

### Expected fix

We need to use code-excerpt tags pointing at the code in /examples/codelabs, rather than simple markdown code blocks.

**Comment by domesticmouse** [comment]
Hey @sfshaza2 and @khanhnwin,

I'm curious what the process is for updating the cookbook samples?  The 
[inline DartPad sample](https://flutter.dev/docs/cookbook/effects/parallax-scrolling#interactive-example)
is out of sync with the 
[code in the flutter/codelabs repo](https://github.com/flutter/codelabs/blob/master/cookbook/lib/examples/parallax.dart).

Halp?

**Comment by parlough** [comment]
Code excerpts were added and related updates were made in https://github.com/flutter/website/pull/6832. Closing.
