### ISSUE TITLE
[PAGE ISSUE]: Missing link to 'Building adaptive apps' in left nav

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#6317]
### Page URL

https://flutter.dev/docs/development/ui/layout/building-adaptive-apps/

### Page source

https://github.com/flutter/website/tree/main/src/docs/development/ui/layout/building-adaptive-apps.md

### Describe the problem

The page doesn't appear to have a link from the left navigation menu:

![image](https://user-images.githubusercontent.com/348942/134715988-73f2c80e-de51-4ec3-ab1e-a9a5110d38c1.png)

The only way to get to it, aside of using search, is to follow a link in the [Creating responsive and adaptive apps](https://flutter.dev/docs/development/ui/layout/adaptive-responsive) page: 

![image](https://user-images.githubusercontent.com/348942/134716064-aa30c7cb-1e41-4f75-8cd4-2c57cf999865.png)

### Expected fix

This page has a lot of good content. It might warrant surfacing it in the navigation menu? @sfshaza2 @csells

**Comment by TahaTesser** [comment]
Hi @InMatrix 
Thanks for filing the issue
