### ISSUE TITLE
[PAGE ISSUE]: 'Install'

### ISSUE THREAD

**Issue by kingpg77** [flutter/website#6320]
### Page URL

https://flutter.dev/docs/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/docs/get-started/install/index.md

### Describe the problem

![ashampoo](https://user-images.githubusercontent.com/91122773/134797210-9bdfb5d1-5f7a-409c-a39f-5a2708e5f3c2.png)
![ashampoo_blog](https://user-images.githubusercontent.com/91122773/134797212-68a712f4-e6f2-4232-bb02-59dfd07a5223.png)
![auxWindowBackground](https://user-images.githubusercontent.com/91122773/134797213-7087f882-ea78-4f5a-9485-49e2cbd724dd.png)
![auxWindowBackgroundAnalyticsPopup](https://user-images.githubusercontent.com/91122773/134797214-ef1f1a08-614e-4ce7-8d10-7f83c8e34cdb.png)
![auxWindowBackgroundNewUpdate](https://user-images.githubusercontent.com/91122773/134797215-11df5f58-1ba7-4c94-ad97-937264c69ef2.png)
![auxWindowBackgroundNoHead](https://user-images.githubusercontent.com/91122773/134797216-60133862-9460-4de6-b59e-6ef4c11ed6fb.png)
![auxWindowBackgroundNoHelp](https://user-images.githubusercontent.com/91122773/134797217-da1150be-807c-43c1-ac62-dda998321f4d.png)
![auxWindowBackgroundSmall](https://user-images.githubusercontent.com/91122773/134797218-5e42002f-7a89-4788-b9cd-026d9db6027f.png)
![auxWindowBackgroundSmallNoHead](https://user-images.githubusercontent.com/91122773/134797220-95e78f7a-21d7-4018-9a3b-c4044c34fd42.png)
![auxWindowBackgroundSmallNoHelp](https://user-images.githubusercontent.com/91122773/134797221-040eb438-5dcd-4802-94ae-441736243082.png)
![background](https://user-images.githubusercontent.com/91122773/134797223-ae6c7243-14ac-433d-83aa-79fa4f0e8a58.png)
![bg_button](https://user-images.githubusercontent.com/91122773/134797225-339885d8-79a9-4908-a6b0-322967f407fe.png)
![blog_small](https://user-images.githubusercontent.com/91122773/134797226-bc0a39e2-806a-4421-b733-2303dd0c506f.png)
![button_bg_disabled](https://user-images.githubusercontent.com/91122773/134797227-78e43fee-9536-4853-b7ff-9a4b868802f8.png)
![button_bg_down](https://user-images.githubusercontent.com/91122773/134797228-e48328c8-5eff-4d83-bc3e-6c8054199e70.png)
![button_bg_hover](https://user-images.githubusercontent.com/91122773/134797230-59fa6adc-f047-48ca-853c-d0d53c7976d9.png)
![button_bg_normal](https://user-images.githubusercontent.com/91122773/134797231-48cec159-1590-4a7b-817a-e9264ac842dc.png)
![button_dialog_disabled](https://user-images.githubusercontent.com/91122773/134797232-60cfc5f4-1a12-4fe8-8cab-933061e91636.png)
![button_dialog_down](https://user-images.githubusercontent.com/91122773/134797233-63a8230e-f5e2-47a0-9084-6da00e317928.png)
![button_dialog_hover](https://user-images.githubusercontent.com/91122773/134797234-e67ff1a7-2988-4194-a8b5-6fd454a2a7b1.png)
![button_dialog_normal](https://user-images.githubusercontent.com/91122773/134797235-900d9e16-c93f-41ec-be3f-8d41c6961369.png)
![button_dialog_purchase_down](https://user-images.githubusercontent.com/91122773/134797237-fe228c8b-1cff-44fe-b513-ee8b05178989.png)
![button_dialog_purchase_hover](https://user-images.githubusercontent.com/91122773/134797238-0a3b7fa2-db3a-4fdf-bb25-49690f032b34.png)
![button_fdb_disabled](https://user-images.githubusercontent.com/91122773/134797239-96b07066-77be-4a91-8853-8b15de697319.png)
![button_fdb_down](https://user-images.githubusercontent.com/91122773/134797240-8918e6fa-61a4-4f41-948d-d8fe7f7f5e04.png)
![button_fdb_hover](https://user-images.githubusercontent.com/91122773/134797241-06848b18-54b0-4b0c-b76b-8d6fb5b616e2.png)
![button_fdb_l_disabled](https://user-images.githubusercontent.com/91122773/134797243-93362347-390b-4f8e-bdd4-4dc1cd2255c4.png)
![button_fdb_l_down](https://user-images.githubusercontent.com/91122773/134797244-e2019b55-30ef-4eee-b5ca-d2a6e32619d7.png)
![button_fdb_l_hover](https://user-images.githubusercontent.com/91122773/134797245-ea811f0c-820c-4df1-ae29-4873002873fb.png)
![button_fdb_l_normal](https://user-images.githubusercontent.com/91122773/134797247-8ca1ed0b-beba-4e16-ae33-2c189639c3f8.png)
![button_fdb_normal](https://user-images.githubusercontent.com/91122773/134797248-4a55e508-47b0-4fe3-bd9e-9be5ed9a3de2.png)
![button_special_disabled](https://user-images.githubusercontent.com/91122773/134797249-83b78d04-bc4d-405e-a9d4-e1541ed5a526.png)
![button_special_down](https://user-images.githubusercontent.com/91122773/134797250-549664d3-4590-4d44-803b-21d35f11c37c.png)
![button_special_green_down](https://user-images.githubusercontent.com/91122773/134797251-d6acfed5-1335-4248-9b1f-0c1440d02372.png)
![button_special_green_hover](https://user-images.githubusercontent.com/91122773/134797252-3e940cc2-d52b-4167-ba8b-4c7b22b3bc74.png)
![button_special_green_normal](https://user-images.githubusercontent.com/91122773/134797253-523bcf43-55da-43c8-bdcf-ad32479af0bf.png)
![button_special_hover](https://user-images.githubusercontent.com/91122773/134797254-48c11ac5-bb1c-49e1-9a21-3c34411e595d.png)
![button_special_normal](https://user-images.githubusercontent.com/91122773/134797255-765e363b-c565-46a6-8688-7e41907b4db6.png)
![button_special_purchase_disabled](https://user-images.githubusercontent.com/91122773/134797256-3fcec425-1709-44dd-bc48-6ce93f91c4fb.png)
![button_special_purchase_down](https://user-images.githubusercontent.com/91122773/134797257-57a79e5f-8972-4652-b048-4773e4e976b6.png)
![button_special_purchase_hover](https://user-images.githubusercontent.com/91122773/134797258-4ab50cb5-8ee2-4c78-977a-418ee4e372d1.png)
![button_special_purchase_normal](https://user-images.githubusercontent.com/91122773/134797259-a19e27be-71db-4aca-8fb3-e16fabf92efb.png)
![checkbox_off_down](https://user-images.githubusercontent.com/91122773/134797260-187db5a9-037b-4677-bd87-d02f06e1569a.png)
![checkbox_off_hover](https://user-images.githubusercontent.com/91122773/134797261-fea4c598-db8f-4c6b-9483-90132dfc627a.png)
![checkbox_off_normal](https://user-images.githubusercontent.com/91122773/134797262-86e7bf6b-f473-4dfe-aeb4-44dccfd7d7c4.png)
![checkbox_on_down](https://user-images.githubusercontent.com/91122773/134797263-60cf6bc9-81fb-44d9-bd59-c5071f35e077.png)
![checkbox_on_hover](https://user-images.githubusercontent.com/91122773/134797264-03c568ae-c5fe-4b73-9d21-81fb7888d5c2.png)
![checkbox_on_normal](https://user-images.githubusercontent.com/91122773/134797265-0dc1eb8b-8ab3-4964-b623-e8367a2ce3e4.png)
![dialog_bg_recommend](https://user-images.githubusercontent.com/91122773/134797266-2f3294db-5ae5-4cf6-820d-498df0b11f61.png)
![DiscountButton](https://user-images.githubusercontent.com/91122773/134797268-2ad15c93-8e54-4bfb-9307-4fc3920ed45d.png)
![facebook](https://user-images.githubusercontent.com/91122773/134797270-cb1f82bd-f7f1-446e-9933-8df3c025a450.png)
![facebook_big](https://user-images.githubusercontent.com/91122773/134797274-a967e5e1-e301-4b64-a334-380b29082427.png)
![facebook_small](https://user-images.githubusercontent.com/91122773/134797276-ef07617c-3680-4d26-8f05-f969ced617fa.png)
![feedbackLogo](https://user-images.githubusercontent.com/91122773/134797277-3f0977cd-b063-4e1a-8188-12d0292cd966.png)
![footerBackground](https://user-images.githubusercontent.com/91122773/134797278-6567042f-312e-4c39-8f5a-4798a1f80152.png)
![google_add_big](https://user-images.githubusercontent.com/91122773/134797279-29d8bec1-936d-42fd-9f3d-0f8f9d8b0b11.png)
![google_plus](https://user-images.githubusercontent.com/91122773/134797280-a624b427-4bfa-4bb4-b639-083d11373eaf.png)
![google_plus_small](https://user-images.githubusercontent.com/91122773/134797281-c1d174cb-916a-47a5-94ca-ed4a399c4a1e.png)
![ImageEmpty](https://user-images.githubusercontent.com/91122773/134797282-0a9b919c-d744-4d26-9f24-eb8b1a8dc861.png)
![menu_1](https://user-images.githubusercontent.com/91122773/134797283-f7329d0a-df11-4b0c-8a2a-7b79d637d5a5.png)
![menu_2](https://user-images.githubusercontent.com/91122773/134797284-883ae245-dc00-4eb2-bb20-ca6894555772.png)
![menu_3](https://user-images.githubusercontent.com/91122773/134797285-016bf652-9000-4215-9f47-6a119b1f149f.png)
![menu_4](https://user-images.githubusercontent.com/91122773/134797286-64789613-13b9-4fe7-86b4-763bc60ae9d1.png)
![menu_5](https://user-images.githubusercontent.com/91122773/134797287-f0245b50-2198-4850-9e4c-780e36e49e93.png)
![menu_6](https://user-images.githubusercontent.com/91122773/134797289-c95c989e-15a1-4100-a1ee-4bdb9cbc167e.png)
![menu_7](https://user-images.githubusercontent.com/91122773/134797291-35f77982-ef2d-45af-93b5-c99a73dedd51.png)
![menu_8](https://user-images.githubusercontent.com/91122773/134797292-c3f97266-e07a-4139-a9bd-0375c683dfe7.png)
![menu_9](https://user-images.githubusercontent.com/91122773/134797293-8cc77dc3-fab1-4df9-901f-6bebefc53278.png)
![menu_10](https://user-images.githubusercontent.com/91122773/134797294-402f56ea-0c2d-474f-b3f8-484666b15d00.png)
![menu_11](https://user-images.githubusercontent.com/91122773/134797295-1acd9c98-2ae6-400c-b861-bd88291bf370.png)
![menu_12](https://user-images.githubusercontent.com/91122773/134797296-dd439120-e828-4714-b097-423aebcfefb9.png)
![menu_13](https://user-images.githubusercontent.com/91122773/134797297-d2eb086c-aec4-4636-ab08-c395e0a41002.png)
![menu_14](https://user-images.githubusercontent.com/91122773/134797298-1da6dfdf-ea8e-4e15-9de9-e741696b70e2.png)
![menu_15](https://user-images.githubusercontent.com/91122773/134797299-08757da2-ff91-454e-9f5a-b51fdf383f0d.png)
![menu_16](https://user-images.githubusercontent.com/91122773/134797300-af18a5a5-b844-48ca-b9f6-ba3106acb1ca.png)
![menu_17](https://user-images.githubusercontent.com/91122773/134797301-d6bf3e36-5b1d-4647-b0c2-57706d1b190e.png)
![menu_18](https://user-images.githubusercontent.com/91122773/134797302-4719b47d-ccbf-4d9f-a354-e4855dd82672.png)
![menu_19](https://user-images.githubusercontent.com/91122773/134797303-78465bad-4cda-4047-873b-75588a19e649.png)
![menu_22](https://user-images.githubusercontent.com/91122773/134797304-c80e7046-6721-42de-8280-d1b97d570411.png)
![miniHtmlBackground](https://user-images.githubusercontent.com/91122773/134797305-a8e80286-1666-4762-8c8a-da2c808f9f25.png)
![percent](https://user-images.githubusercontent.com/91122773/134797306-2ca42202-e5bd-4daf-9089-50d1c33c36ee.png)
![phaseInfo](https://user-images.githubusercontent.com/91122773/134797307-18f1d8d5-eecd-4524-953a-57dcbc199ad1.png)
![phaseInfo2](https://user-images.githubusercontent.com/91122773/134797308-ae484944-45ed-49a8-939f-8e69524e1504.png)
![phaseService](https://user-images.githubusercontent.com/91122773/134797310-4aa992d2-8a03-456a-a912-6b4d047dd53f.png)
![phaseSymbol32](https://user-images.githubusercontent.com/91122773/134797311-88675ec4-6abf-4c35-b9de-773ce7857526.png)
![recommend_mail_big](https://user-images.githubusercontent.com/91122773/134797313-5b71c04b-a547-4969-b469-b47870798bc5.png)
![seperator](https://user-images.githubusercontent.com/91122773/134797314-ca8d559c-7bf0-43bf-a22a-2b0c85d027be.png)
![shape](https://user-images.githubusercontent.com/91122773/134797317-1d29ba79-8966-462b-9096-f41cb3cdf990.png)
![shapeFeedback](https://user-images.githubusercontent.com/91122773/134797318-61585306-20b8-4f5d-a4d1-de5cebdb778e.png)
![shapeNoHelp](https://user-images.githubusercontent.com/91122773/134797319-29cad7ff-50e3-4c11-aa9b-affaf001505e.png)
![shapeSmall](https://user-images.githubusercontent.com/91122773/134797320-a5c1268a-b58b-448d-b9a1-0f343841a415.png)
![shapeSmallNoHelp](https://user-images.githubusercontent.com/91122773/134797322-1ac1d9f8-a22a-4f35-9eca-6cad9fbfceaf.png)
![softwarebox](https://user-images.githubusercontent.com/91122773/134797324-9a8690e8-cac3-4ea1-a0cb-cbc0360f3966.png)
![threeStepBuyCircle](https://user-images.githubusercontent.com/91122773/134797325-c8136f9c-dde9-4c8f-a58c-a741f9af361f.png)
![tweet_big](https://user-images.githubusercontent.com/91122773/134797326-879f3687-78f8-4a94-8bda-ae18b3c454eb.png)
![twitter](https://user-images.githubusercontent.com/91122773/134797329-809876c4-a84e-4b03-9d99-4e7673b5709c.png)
![twitter_small](https://user-images.githubusercontent.com/91122773/134797331-24cc54c9-061f-4f76-b9a8-08ac37f7e968.png)
![youtube](https://user-images.githubusercontent.com/91122773/134797333-5eb2d207-aca3-4981-86b7-301620ac408f.png)
![youtube_small](https://user-images.githubusercontent.com/91122773/134797334-8a631223-43ab-4127-b0c0-172a248b929a.png)

**Comment by TahaTesser** [comment]
Hi @kingpg77 
This doesn't look like an issue with Flutter website
