### ISSUE TITLE
flutter for strezlessmusick

### ISSUE THREAD

**Issue by StrezlessMusick** [flutter/website#6323]
dependencies {
    val core_version = "1.6.0"

    // Java language implementation
    implementation("androidx.core:core:$core_version")
    // Kotlin
    implementation("androidx.core:core-ktx:$core_version")

    // To use RoleManagerCompat
    implementation("androidx.core:core-role:1.0.0")

    // To use the Animator APIs
    implementation("androidx.core:core-animation:1.0.0-alpha02")
    // To test the Animator APIs
    androidTestImplementation("androidx.core:core-animation-testing:1.0.0-alpha02")

    // Optional - to use ShortcutManagerCompat to donate shortcuts to be used by Google
    implementation("androidx.core:core-google-shortcuts:1.0.0")

    // Optional - APIs for SplashScreen, including compatiblity helpers on devices prior Android 12
    implementation("androidx.core:core-splashscreen:1.0.0-alpha01")
}

**Comment by StrezlessMusick** [comment]
exit
exit.
- [ ]

**Comment by TahaTesser** [comment]
Hi @StrezlessMusick 
This doesn't look like an issue with the Flutter website

**Comment by StrezlessMusick** [comment]
Sorry
