### ISSUE TITLE
[PAGE ISSUE]: Duplicate releases in the tables in 'Flutter SDK releases'

### ISSUE THREAD

**Issue by aliasgarlabs** [flutter/website#6329]
### Page URL

https://flutter.dev/docs/development/tools/sdk/releases/

### Page source

https://github.com/flutter/website/tree/main/src/docs/development/tools/sdk/releases.md

### Describe the problem

The Flutter SDK versions list is shown twice. 

Reproduction steps:
1. Goto https://flutter.dev/docs/development/tools/sdk/releases/
2. Scroll the list of releases in the `Stable channel (Windows)` section 
3. Find the first release named `v1.0.0`. 
4. Notice the recent releases (currently `2.5.1`) show up again

### Expected fix

The Flutter SDK list should be shown just once

**Comment by TahaTesser** [comment]
Hi @aliasgarlabs 
Thanks for filing the issue
Look like, all three platforms releases are duplicated

I've checked the source, there is no duplication,  looks a duplication is happening in the table only
https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json

**Comment by TahaTesser** [comment]
cc: @Sfshaza2

**Comment by sfshaza2** [comment]
@khanhnwin, yes, it looks like it's running through (and printing) the list twice. Khanh, can you take a look?

cc @btobin

**Comment by piedcipher** [comment]
perhaps, It seems this issue has been fixed! I checked the page. Duplication is not there. good to close?!

**Comment by khanhnwin** [comment]
Yep, looks good to go! Thanks for catching @piedcipher! I'll close out this issue, but please shout if the issue reappears.
