### ISSUE TITLE
[PAGE ISSUE]: 'Take a picture using the camera'

### ISSUE THREAD

**Issue by camsim99** [flutter/website#6347]
### Page URL

https://flutter.dev/docs/cookbook/plugins/picture-using-camera/

### Page source

https://github.com/flutter/website/tree/main/src/docs/cookbook/plugins/picture-using-camera.md

### Describe the problem

Step 3.4 is "Create and initialize the controller in the initState() method." but this code is missing:
```
void initState() {
...
    // Next, initialize the controller. This returns a Future.
    _initializeControllerFuture = _controller.initialize(); // this line is missing on this page!
...
}
```

### Expected fix

Add the line of code that I included above.

**Comment by TahaTesser** [comment]
Hi @camsim99 
Thanks for filing the issue
