### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app on the web'

### ISSUE THREAD

**Issue by h-dhaliwal** [flutter/website#6348]
### Page URL

https://flutter.dev/docs/get-started/codelab-web/

### Page source

https://github.com/flutter/website/tree/main/src/docs/get-started/codelab-web.md

### Describe the problem

The codelab stills asks the user to switch to the beta channel whereas the web has been pushed into stable.

### Expected fix

Remove the steps to change to beta version of flutter

**Comment by TahaTesser** [comment]
Hi @h-dhaliwal 
Thanks for filing the issue

**Comment by domesticmouse** [comment]
This was fixed by #6716
