### ISSUE TITLE
[PAGE ISSUE]: Update 'Creating a new project` instructions for new Android Studio in  'Android Studio and IntelliJ'

### ISSUE THREAD

**Issue by ghost** [flutter/website#6356]
### Page URL

https://flutter.dev/docs/development/tools/android-studio/

### Page source

https://github.com/flutter/website/tree/main/src/docs/development/tools/android-studio.md

### Describe the problem

The steps that are described how to create a project from existing code are not correct for the "current" version of android studio + flutter plugin. They are different in such way that i'm unable to follow these steps.

**Versions**:
Android Studio: Arctic Fox | 2020.3.1 Patch 2
Flutter plugin: 61.2.2

### Expected fix

A set of steps that corresponds with the steps needed in the newer/newest version(s).

**Comment by TahaTesser** [comment]
Hi @XanderAtBackboneSystems 
There are have been UI changes in the addition of Android Studio, docs needs to be updated, thanks for catching this.

**Comment by Coronon** [comment]
The same is true for the VsCode instructions
