### ISSUE TITLE
Cupertino Icons Gallery Missing

### ISSUE THREAD

**Issue by deive** [flutter/website#6358]
### Page URL

https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html

### Describe the problem

Many pages, including the API docs link to a "Cupertino Icons Gallery" page that used to live at https://flutter.github.io/cupertino_icons - this 404s.
I can't seem to find this page (or a new version of it) on the flutter.dev site.

### Expected fix

The Cupertino Icons Gallery page needs to be re-added and links to it need updating.

**Comment by TahaTesser** [comment]
Hi @deive 
This is not an issue with `flutter/website`, this is a known issue being tracked in `flutter/flutter`, see https://github.com/flutter/flutter/issues/88754
