### ISSUE TITLE
Document python script

### ISSUE THREAD

**Issue by sfshaza2** [flutter/website#6377]
### Describe the problem

Due to some crossed wires, in PR https://github.com/flutter/website/pull/6374, changes were made to the python script. We had agreed not to make infrastructure changes at the moment. 

Also, the new script has zero documentation. If we want to keep it intact, it needs some docs.

@AlexV525, can you provide more info?  @btobin, can you weigh in on these changes? Should we revert them, or is it sufficient to document them?

thx

**Comment by AlexV525** [comment]
The script itself is quite simple, but I can add some comments for it.

**Comment by RedBrogdon** [comment]
Thanks @AlexV525. Just to make sure someone says it, this is not about anyone questioning the value of the contribution or the quality of the code. We're just making a push to have our testing infrastructure better documented and understood (some of it is years old).

**Comment by AlexV525** [comment]
Commenting the python script make the file increased from 47 lines to 80, but now it has a better readability for sure.
