### ISSUE TITLE
[PAGE ISSUE]: 'Work with WebSockets'

### ISSUE THREAD

**Issue by vibalijoshi** [flutter/website#6382]
### Page URL

https://flutter.dev/docs/cookbook/networking/web-sockets/

### Page source

https://github.com/flutter/website/tree/main/src/docs/cookbook/networking/web-sockets.md

### Describe the problem

The echo server URL given is no longer in service `ws://echo.websocket.org`

### Expected fix

One possible replacement is this URL `wss://ws.ifelse.io/`

### Additional context

The demo example given does not work due to this.

**Comment by sfshaza2** [comment]
Yes, you may submit a PR!

**Comment by danagbemava-nc** [comment]
Bumping the priority as there have been quite a number of duplicates of this issue

**Comment by ditman** [comment]
There may be an alternative available here:

* https://www.lob.com/blog/websocket-org-is-down-here-is-an-alternative

`wss://echo.websocket.events`

**Comment by sfshaza2** [comment]
Thanks, @ditman! @vibalijoshi and others, PRs are welcome!  :D

**Comment by ditman** [comment]
@sfshaza2 I've sent a PR here:

https://github.com/flutter/website/pull/6933

It's up to you people to decide if we want to have a link to this 3rd party service (quick fix) or we should stand-up our own echo service (more involved fix, but more "secure" I guess).

**Comment by sfshaza2** [comment]
Thanks again, @ditman!!!
