### ISSUE TITLE
[PAGE ISSUE]: 'An introduction to integration testing'

### ISSUE THREAD

**Issue by mustafamg** [flutter/website#6401]
### Page URL

https://flutter.dev/docs/cookbook/testing/integration/introduction/

### Page source

https://github.com/flutter/website/tree/main/src/docs/cookbook/testing/integration/introduction.md

### Describe the problem

The provided example is not enough. It doesn't show how we can test multiple scenarios per widget. Should the app be loading and closing after each test?

### Expected fix

Having example of multiple scenarios as follow
```
group('end-to-end test', () {
    testWidgets('tap on the floating action button, verify counter',
        (WidgetTester tester) async {
    ...
    });
    testWidgets('test case 2',
        (WidgetTester tester) async {
    ...
    });
  });
```

**Comment by chonghorizons** [comment]
There is another example in this codelab that has multiple tests:

https://codelabs.developers.google.com/codelabs/flutter-app-testing/#6

Unfortunately, I am getting an error running the sample code for the integration test. See #6508

**Comment by mustafamg** [comment]
@chonghorizons Thank you, that link was realy helpfull :)

**Comment by mustafamg** [comment]
Thanks a lot, that link was realy helpfull, particularily the policy update 
`binding.framePolicy = LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;`
