### ISSUE TITLE
[PAGE ISSUE]: 'Performance profiling'

### ISSUE THREAD

**Issue by mustafamg** [flutter/website#6402]
### Page URL

https://flutter.dev/docs/cookbook/testing/integration/profiling/

### Page source

https://github.com/flutter/website/tree/main/src/docs/cookbook/testing/integration/profiling.md

### Describe the problem

Flutter driver is deprecated, correct?
that page uses flutter driver, is that correct, or integration_test doesn't support perfomance profiling
`import 'package:flutter_driver/flutter_driver.dart';`

**Comment by parlough** [comment]
This cookbook was updated to use `integration_test` in https://github.com/flutter/website/pull/6519. 

Thanks for opening an issue!
