### ISSUE TITLE
Add links to Release Notes in SDK releases page

### ISSUE THREAD

**Issue by enzodanjour** [flutter/website#6406]
### Page URL

https://flutter.dev/docs/development/tools/sdk/releases

### Describe the problem

this can improve the experience if you have to choose a specific version, and if possible, I don't know if there is a possibility but do the same for beta versions.
We, as members of the community, could mobilize better, and even learn more.
![Screenshot from 2021-10-21 20-33-14](https://user-images.githubusercontent.com/35856303/138371150-a890e809-40c9-43ab-b35b-65bd49628df3.png)

### Expected fix

a column appears where there are links to the changes

![screen](https://user-images.githubusercontent.com/35856303/138371175-8452a231-1c51-42f7-8922-7a29da55f0ab.jpg)

can redirect to flutter website
![Screenshot from 2021-10-21 20-38-24](https://user-images.githubusercontent.com/35856303/138371236-d45c7070-42a4-40ff-9d32-3d3ce527b644.png)

or Can redirect to github
![Screenshot from 2021-10-21 20-38-12](https://user-images.githubusercontent.com/35856303/138371242-9948871d-fc4a-402e-8a67-df3e7bacb5d7.png)

**Comment by parlough** [comment]
Definitely a good idea! Tracking this feature request in https://github.com/flutter/website/issues/7764
