### ISSUE TITLE
Consider changing macOS install to use `brew` on 'macOS install' page

### ISSUE THREAD

**Issue by ahagiwara** [flutter/website#6408]
### Page URL

https://docs.flutter.dev/get-started/install/macos

### Page source

https://github.com/flutter/website/tree/main/src/docs/get-started/install/macos.md

### Describe the problem

This multistep process to install Flutter can be accomplished in one step via Homebrew. 

### Expected fix

Install Homebrew. Run `brew install flutter`

**Comment by mclarkedev** [comment]
Per https://formulae.brew.sh/cask/flutter, `brew install flutter` is now `brew install --cask flutter`.

**Comment by atsansone** [comment]
@jacob314 : I believe we discussed this, but we don't maintain this `cask`, so can we include it in the instructions?

**Comment by sfshaza2** [comment]
No. (Also, this is NOT an e0-minutes issue...) 

We don't officially support homebrew installation of Flutter. We used to list this info on our install page, but there are too many engineering issues that must first be resolved and it was removed by Chris Fujino and approved by Ian. You can read more about the engineering support needed on [this issue](https://github.com/flutter/flutter/issues/14050#issuecomment-646122824).

However, some folks do use homebrew to install Flutter using an externally maintained cask. If you google "install Flutter homebrew" you will find info on StackOverflow and elsewhere. Just be warned that you **will** encouter issues if using brew to install on a read-only system.

Closing this issue.
