### ISSUE TITLE
Fix path in Step 2b of 'Developing packages' page

### ISSUE THREAD

**Issue by noamraph** [flutter/website#6409]
### Page URL

https://docs.flutter.dev/packages-and-plugins/developing-packages#step-2b-add-android-platform-code-ktjava

### Page source

https://github.com/flutter/website/blame/main/src/packages-and-plugins/developing-packages.md

### Describe the problem

I tried to edit a plugin using android studio, and got a lot of problems. It took me a lot of time to realize that I should open the project from the "hello/example/android" directory and not from the "hello/android" directory.

### Expected fix

In step 2b, make the "example" in `hello/example/android/build.gradle` be bold. Add a sentence "Make sure to open the project from the *example* directory".

If you could make the IDE show a message saying that you should open the files using the "example" directory that would be awesome.

**Comment by atsansone** [comment]
Fixed as part of https://github.com/flutter/website/pull/3816. Closing.
