### ISSUE TITLE
Deprecated code in codelab

### ISSUE THREAD

**Issue by asavchuk** [flutter/website#6412]
In https://codelabs.developers.google.com/codelabs/flutter#4 suppose using of deprecated code
`data: IconThemeData(color: Theme.of(context).accentColor),`

**Comment by parlough** [comment]
The links to this old codelab have been removed and the link now redirects to the new [Boring to Beautiful codelab](https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful) which doesn't have this issue, so I'm going to close this, thanks again!
