### ISSUE TITLE
Link checker missed a broken link 

### ISSUE THREAD

**Issue by khanhnwin** [flutter/website#6418]
### Describe the problem

architectural-overview.md contained a broken link:
https://api.flutter.dev/flutter/flutter/widgets/BuildContext/dependOnInheritedWidgetOfExactType.html but the [link checker](https://github.com/flutter/website/blob/main/tool/check-links.sh) did not catch it. 

Correct link: https://api.flutter.dev/flutter/widgets/BuildContext/dependOnInheritedWidgetOfExactType.html

### Expected fix

Investigate/get RCA for why link checker missed the broken link

### Additional context

PR #6398

**Comment by parlough** [comment]
This is because the linkchecker is not currently setup to check external links. It is possible with linkchecker, and options for doing so are discussed in https://github.com/flutter/website/issues/3079
