### ISSUE TITLE
Cupertino Icons Gallery returns 404

### ISSUE THREAD

**Issue by janjoosse** [flutter/website#6429]
The very useful Flutter Cupertino Icons Gallery, found at https://flutter.github.io/cupertino_icons returns a 404.

**Comment by janjoosse** [comment]
Sorry to create a duplicate, I didn't find the original one.

**Comment by sfshaza2** [comment]
Sorry, @jmagman, but this issue is definitely outside my control and doesn't involve the flutter.dev website. Perhaps @jcollins-g can shed some light.

**Comment by jcollins-g** [comment]
Reading the comments on the other issue, it sounds like they just need to serve the CSS somewhere.  That doesn't sound too hard as long as a decision can be reached on where it should go?
