### ISSUE TITLE
[PAGE ISSUE]: 'Play and pause a video'

### ISSUE THREAD

**Issue by ReinisSprogis** [flutter/website#6434]
### Page URL

https://flutter.dev/docs/cookbook/plugins/play-video/

### Page source

https://github.com/flutter/website/tree/main/src/docs/cookbook/plugins/play-video.md

### Describe the problem

Loading video from assets causes an error because the file format is not capitalised in the file path. 

### Expected fix

Suppose it's expected behaviour, but not a very apparent mistake.
I would recommend adding a note to the documentation about this. 
or
Make it in a way that file format capitalisation doesn't matter. 
I would imagine it's the same for other asset types as well. 
.PNG or .png
.mp4 vs .MP4

### Additional context

I was trying to help some person who struggled with this and it was difficult to find the bug. https://www.reddit.com/r/flutterhelp/comments/qidr8o/flutter_videoplayercontrollerasset_does_not_play/

**Comment by danagbemava-nc** [comment]
Hi @ReinisSprogis, it sounds to me like you're suggesting a change in the behaviour of the `video_player` plugin. 

Is that correct?

**Comment by ReinisSprogis** [comment]
Hi. Thanks for a swift response.
 I suppose it would apply to all assets. But `video_player`  plugin is the one where I encountered a problem. I'm thinking of adding a note about capital letters in a file format would be worth in the [assets section](https://flutter.dev/docs/development/ui/assets-and-images) as well. But not sure what would be the best approach to solve this. If anything.

**Comment by danagbemava-nc** [comment]
The extensions don't really have to be capitalised for it to work. I confirmed this by creating a sample that has a video with extension `.mp4` and it worked just fine. 

I think there might have been a different issue going on. 
In which case I would suggest you file an issue on the main `flutter` repo with steps to reproduce. 

But generally so far as the right asset name is provided, the asset should work. 

See video for more info. 

<details>
<summary>video</summary>


https://user-images.githubusercontent.com/88313112/139822625-d31bcafb-e7b7-4761-8543-d073c1d393db.mp4



</details>

**Comment by ReinisSprogis** [comment]
Hi.
What's happening is that if the file extension is capitalised (.MP4 or
.PNG) and if the developer is expecting a lowercase extension (.mp4 or
.png) then It will cause errors and assets won't work. For example, video
from my Sony camera is saved with capitalised extension. This might be true
for some android devices as well. Real life example could be: "User using
an app that is asking for an mp4 file. The user is providing MP4 file, but
the app is crashing and user uninstalls the app."
The same could be true for PNG and JPG files.
[image: Inkederror file_LI.jpg][image: Inkedworks_LI.jpg]

**Comment by danagbemava-nc** [comment]
Unfortunately, that goes beyond the scope of this issue tracker, kindly file an issue with the main `flutter repo`, with exact steps to reproduce and any other information that might be relevant. This seems like a framework issue and filing it on the main flutter repo will help make the appropriate team act on it.

Closing as this isn't an actual issue with this page. 

Thank you
