### ISSUE TITLE
[PAGE ISSUE]: 'Start thinking declaratively'

### ISSUE THREAD

**Issue by sazzad-hsenid** [flutter/website#6451]
### Page URL

https://flutter.dev/docs/development/data-and-backend/state-mgmt/declarative/

### Page source

https://github.com/flutter/website/tree/main/src/docs/development/data-and-backend/state-mgmt/declarative.md

### Describe the problem

Many assumptions that you might have don’t apply to Flutter

should be

Many assumptions that you might have, don’t apply to Flutter

### Expected fix

Many assumptions that you might have, don’t apply to Flutter

**Comment by danagbemava-nc** [comment]
Hi @sazzad-hsm, the sentence structure as it is right now on the site is correct. The ',' is not necessary. 

You can check with the Grammarly grammar checker here.

https://www.grammarly.com/grammar-check
