### ISSUE TITLE
[PAGE ISSUE]: 'Read and write files'

### ISSUE THREAD

**Issue by PeperMarkreel** [flutter/website#6452]
### Page URL

https://flutter.dev/docs/cookbook/persistence/reading-writing-files/

### Page source

https://github.com/flutter/website/tree/main/src/docs/cookbook/persistence/reading-writing-files.md

### Describe the problem

Totally unnecessary use of await, future and async and splitting such a simple task in so much methods.

I don't want to use asynchronous programming and I have a very frustrating experience to make it work in my project. 

Also missing: an explanation how the plugin should be added to the project / pubspec.yaml

### Expected fix

When something can be simple, make it simple and present it simple. Don't make it more complicated than needed.

**Comment by kwalrath** [comment]
Related: https://github.com/dart-lang/site-www/issues/3670

**Comment by danagbemava-nc** [comment]
> splitting such a simple task into so many methods.

I believe the methods were broken into units so as to make it easier for them to be tested. I could be wrong, so don't take my word for it. 

> When something can be simple, make it simple and present it simply. Don't make it more complicated than needed.

@PeperMarkreel, how do you propose the current sample be simplified?
