### ISSUE TITLE
[PAGE ISSUE]: 'Build a form with validation'

### ISSUE THREAD

**Issue by Aubuga** [flutter/website#6455]
### Page URL

https://flutter.dev/docs/cookbook/forms/validation/

### Page source

https://github.com/flutter/website/tree/main/src/docs/cookbook/forms/validation.md

### Describe the problem

The code throws this error while running it on VScode or android studio

W/IInputConnectionWrapper(28349): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(28349): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(28349): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(28349): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(28349): endBatchEdit on inactive InputConnection

### Expected fix

An example that doesn't give errors, with the correct use of keys. Examples shouldn't be either too complex or throw errors

### Additional context

It seems that everyone its getting these errors

**Comment by danagbemava-nc** [comment]
Hi @Aubuga, this is an issue with `TextField` in flutter itself as evidenced by this issue https://github.com/flutter/flutter/issues/9471. 

There isn't anything that the website example can do to fix it unless it is fixed within flutter itself. 

FWIW, these errors aren't going to affect your project, it is an annoyance, but it won't stop your project from running properly. 

Closing as this is beyond the scope of the example. 

Thank you
