### ISSUE TITLE
[PAGE ISSUE]: 'Chrome OS install'

### ISSUE THREAD

**Issue by JarrodCColburn** [flutter/website#6461]
### Page URL

https://flutter.dev/docs/get-started/install/chromeos/

### Page source

https://github.com/flutter/website/tree/main/src/docs/get-started/install/chromeos.md

### Describe the problem

Under [Flutter & Chrome OS tips & tricks](https://flutter.dev/docs/get-started/install/chromeos#flutter--chrome-os-tips--tricks) section... the following line
`flutter pub global run devtools -p 8000`
devtools does not have `-p` flag. 

### Expected fix

change `-p` to `--port`

**Comment by danagbemava-nc** [comment]
I have no way of verifying this, labelling for further investigation.

**Comment by JarrodCColburn** [comment]
Sorry not sure what you mean
> I have no way of verifying this, labelling for further investigation.

To verify, 1st install devtools... 
`flutter pub global activate devtools`

Next attempt to run the original command (as stated in documentation)
`flutter pub global run devtools -p 8000`

This will result in an error: `Could not find an option or flag "-p".`

Looking at the devtools help...
`--port=<port>                     Port to serve DevTools on; specify 0 to automatically use any available port. (defaults to "9100")`
...docs author probably meant `--port` instead of `-p`

**Comment by danagbemava-nc** [comment]
> Sorry not sure what you mean

This was not entirely directed at you. 

> This does not need Chromebook/Crostini to replicate. Just Flutter.

I misjudged the issue considering it was on the `Chrome OS` page. Thanks for clarifying. 

> ...docs author probably meant --port instead of -p

You're right. thanks for the info.

**Comment by JarrodCColburn** [comment]
I recently came back to use this tutorial and saw not fixed. So create a PR
https://github.com/flutter/website/pull/7387
don't know why I didn't do that that back then.
