### ISSUE TITLE
[PAGE ISSUE]: 'Layouts in Flutter'

### ISSUE THREAD

**Issue by jaean123** [flutter/website#6463]
### Page URL

https://flutter.dev/docs/development/ui/layout/

### Page source

https://github.com/flutter/website/tree/main/src/docs/development/ui/layout/index.md

### Describe the problem

Link "grid_list_demo.dart" is broken
https://github.com/flutter/flutter/tree/main/dev/integration_tests/flutter_gallery/lib/demo/material/grid_list_demo.dart

Under Examples (Grid View): "Dart code: grid_list_demo.dart from the Flutter Gallery"

**Comment by danagbemava-nc** [comment]
@jaean123, thanks for catching that.
