### ISSUE TITLE
[PAGE ISSUE]: 'Desktop support for Flutter' : how to change app's name and icon on Windows

### ISSUE THREAD

**Issue by whiplashoo** [flutter/website#6465]
### Page URL

https://flutter.dev/desktop/

### Page source

https://github.com/flutter/website/tree/main/src/desktop.md

### Describe the problem

In the Distribution > Windows section, documentation is lacking on how to set the app's name and icon for Windows. 

### Expected fix

In my case, I followed instructions in [this](https://stackoverflow.com/questions/64800455/how-to-change-app-icon-and-app-name-for-flutter-desktop-application) and [this](https://stackoverflow.com/questions/64558578/how-to-change-desktop-windows-application-icon-for-flutter).

### Additional context

For other platforms, a relevant section is included in the documentation.

**Comment by csells** [comment]
@domesticmouse potential docs update for the Windows stable release?
