### ISSUE TITLE
[PAGE ISSUE]: 'Desktop support for Flutter': how to set app's version and build numbers

### ISSUE THREAD

**Issue by whiplashoo** [flutter/website#6466]
### Page URL

https://flutter.dev/desktop/

### Page source

https://github.com/flutter/website/tree/main/src/desktop.md

### Describe the problem

In the Distribution > Windows section, documentation is lacking on how to set the app's version and build numbers for Windows (e.g. "1.3.0+14").

### Expected fix

After searching around, I had to edit `windows/runner/Runner.rc `and change `VERSION_ _AS_ _NUMBER` and `VERSION_AS_STRING` to edit the version and build numbers of my app. 

### Additional context

It is useful to have this in the documentation, as it helps with app versioning and deployment. For other platforms, a relevant section is included in the documentation.

**Comment by csells** [comment]
@domesticmouse potential docs update for the Windows stable release?
