### ISSUE TITLE
 [PAGE ISSUE]: 'User interface' page is blank

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#6468]
### Page URL

https://docs.flutter.dev/development/ui/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/index.md

### Describe the problem

Although this page isn't in the sidenav, I found it by searching for *Monetization* (testing whether https://flutter.dev/monetization would show up yet).

It was confusing to see this (blank) page as the 3rd result.

### Expected fix

Redirect or flesh out this page.

### Additional context

Here's a screenshot of the search results:

![image](https://user-images.githubusercontent.com/2164483/141869426-f62fc5bb-1592-4a64-a876-2eb474e0567a.png)

**Comment by danagbemava-nc** [comment]
<details>
<summary>screenshot</summary>

![Screenshot 2021-11-16 at 10 28 25](https://user-images.githubusercontent.com/88313112/141968725-e93e7b52-6b0c-4fe5-a6e5-b6f34090811f.png)

</summary>

**Comment by parlough** [comment]
There's a bunch of pages like this around the website.

Almost every category and subcategory has an index, for example https://docs.flutter.dev/development/data-and-backend and https://docs.flutter.dev/development/ui/advanced also leading to empty pages.

It seems they previously would list the children destinations, but with recent changes those are gone. We should investigate at least adding those back.

<img width="445" alt="image" src="https://user-images.githubusercontent.com/18372958/145085530-1c18005b-0706-419d-a198-08fb124b9958.png">
