### ISSUE TITLE
Extra bottom spacing below footer (link added)

### ISSUE THREAD

**Issue by Farial-mahmod** [flutter/website#6470]
### Describe the problem

There is a huge unnecessary space below the footer on [url](https://docs.flutter.dev/cookbook/navigation/navigation-basics) tested on Firefox 94.0.1 (Windows 10) both the web & mobile inspected view.
I have attached two screenshots (web and mobile inspection) .

### Expected fix

Remove the unnecessary space below footer for better UX.

**Comment by Farial-mahmod** [comment]
I could not add the screenshots - kindly visit the link to view the issue.

**Comment by danagbemava-nc** [comment]
Hi @Farial-mahmod, below is what I see in my browser. Does that match what you're seeing on your end?

<details>
<summary>screenshots</summary>

`mobile`
<img width="1440" alt="Screenshot 2021-11-16 at 10 51 02" src="https://user-images.githubusercontent.com/88313112/141972713-1e49cd96-4c2c-407f-949d-ff4c2224986d.png">

`web`
<img width="1440" alt="Screenshot 2021-11-16 at 10 54 14" src="https://user-images.githubusercontent.com/88313112/141972675-86da90c7-a156-46fe-8bc6-bffb6ad29e74.png">

</details>

**Comment by Farial-mahmod** [comment]
![docs flutter dev - mobile bug](https://user-images.githubusercontent.com/60639522/142040793-c3439b7f-1bf1-44e9-95cb-291b683e1534.png
![docs flutter dev - css bug](https://user-images.githubusercontent.com/60639522/142040825-cf772ab6-f9e0-4afc-95a8-88a7712f4114.png)
)

**Comment by Farial-mahmod** [comment]
![docs flutter dev - mobile bug](https://user-images.githubusercontent.com/60639522/142040970-1c33c7db-a244-47b7-91c2-477411da3571.png)

**Comment by danagbemava-nc** [comment]
Do you see this with only `firefox`? 

Is that the only page you see this issue on?

I've tested on `Chrome`, `Safari` and `firefox` and I can't reproduce. That white space only comes when I overscroll but that is to be expected.  I see similar spaces on other websites when I overscroll.

**Comment by Farial-mahmod** [comment]
Could it be due to my browser's JavaScript version?

**Comment by danagbemava-nc** [comment]
I tested with a system with this same setup Firefox 94.0.1 (Windows 10) and it doesn't reproduce. 

Can you try with a different browser to see if you still reproduce it?
