### ISSUE TITLE
Flutter on Mobile page case studies cards are cropped

### ISSUE THREAD

**Issue by jmagman** [flutter/website#6474]
### Page URL

https://flutter.dev/multi-platform/mobile

### Describe the problem

Case studies cards are cropped. It doesn't seem to be a carousel, so I don't think this is on purpose.
Notice BMW card is cropped:
<img width="2162" alt="Screen Shot 2021-11-16 at 5 09 37 PM" src="https://user-images.githubusercontent.com/682784/142091107-1e1d0734-bbdd-45b5-aeb1-f99c5e9a1a03.png">

### Additional context

Seen on macOS in Chrome and Safari.

**Comment by parlough** [comment]
This element and carousel functionality has been improved on the marketing site. It is now a functional carousel on Chrome and Safari, with both arrows and scrolling.
