### ISSUE TITLE
Make video on 'Flutter for iOS developers' mobile friendly / responsive

### ISSUE THREAD

**Issue by Hamza-Imran75** [flutter/website#6475]
### Page URL

https://docs.flutter.dev/get-started/flutter-for/ios-devs/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/flutter-for/ios-devs.md

### Describe the problem

In mobile version the page goes out of view when trying to zoom out.
Mobile: OnePlus 7 Pro
Browser: Chrome
Platform: Android

Image:
![WhatsApp Image 2021-11-17 at 11 06 10 AM](https://user-images.githubusercontent.com/43512631/142144265-8763de4d-9cb5-4dfd-8371-7a7cfca62c4e.jpeg)

**Comment by danagbemava-nc** [comment]
I believe this is due to the size of the video on the page, as you can even notice this when you swipe right. 

Thanks for reporting this.

**Comment by Hamza-Imran75** [comment]
Yes, it's due to the youtube video, I tried reducing the width of the video, and the page then looked perfect. I'd love to contribute a fix, but I don't know how to make it responsive, any tips?

**Comment by parlough** [comment]
Fixed by https://github.com/flutter/website/commit/88fca48388015d987dccd61a3d548c4073053dbd
