### ISSUE TITLE
[PAGE ISSUE]:The brand page results in a 404 error

### ISSUE THREAD

**Issue by techstrix** [flutter/website#6476]
### Page URL

https://flutter.dev/brand

### Describe the problem

When you access the page it shows a 404 error.It suggests that the brand page doesnt  exist
![screencapture-flutter-dev-brand-2021-11-17-09_24_10](https://user-images.githubusercontent.com/91886864/142145950-1c2610df-31ae-4de8-bed2-0a3b855df7b3.png)

### Expected fix

Just correct the routing for the brand index.md page

**Comment by danagbemava-nc** [comment]
Hi @techstrix, thanks for reporting this. 

https://flutter.dev/brand does indeed return a 404.

https://docs.flutter.dev/brand seems to be the correct URL.

**Comment by micpap25** [comment]
Hi, which page are you getting this issue on? I cannot find any page that links to the brand guidelines which links to the wrong page. There is one comment which links to a wrong page. I am fixing that now.

**Comment by micpap25** [comment]
Turns out I cannot fix that. The comment issue is in flutter_logo.dart which is part of a package.

**Comment by techstrix** [comment]
I have opened a pull request with a fix
