### ISSUE TITLE
The 'Latest news' section on the home page is blank

### ISSUE THREAD

**Issue by devoncarew** [flutter/website#6481]
### Page URL

https://flutter.dev/

### Describe the problem

The 'Latest news' section of the home page is blank. I'm not sure if this is a bug or not. If we really just don't have news here, we should hide that section.

<img width="1345" alt="Screen Shot 2021-11-17 at 4 25 09 PM" src="https://user-images.githubusercontent.com/1269969/142311039-c86afe28-8742-4607-94f4-f800c58a89fe.png">

### Expected fix

Fix an issue which is causing that section to be empty, or if no ,issue, hide the section when there is no news.

**Comment by danagbemava-nc** [comment]
An error is being thrown when trying to fetch the news feed. 

```json
{
    "status": "error",
    "message": "Daily rate limit exceeded, please try again after 19 hours, or use an api key (https://rss2json.com/register)."
}
```
![Screenshot 2021-11-18 at 09 59 22](https://user-images.githubusercontent.com/88313112/142393640-a5588a4d-3400-4657-af1d-c38522af0c75.png)

/cc @sfshaza2

**Comment by danagbemava-nc** [comment]
I've been monitoring the latest news section for some time now and that page is no longer blank. 

Closing this as fixed.

**Comment by FMorschel** [comment]
> I've been monitoring the latest news section for some time now and that page is no longer blank.
> 
> Closing this as fixed.

Hi, @danagbemava-nc, found it again:

![image](https://user-images.githubusercontent.com/52160996/166728834-a9c0c20a-afe4-4502-acc0-51b20f77dc20.png)

**Comment by danagbemava-nc** [comment]
Hi @FMorschel, thanks for reporting this. 

It seems like a new issue has popped up on this page. The error message is different from the last one. Reopening this based on a recent report. 

```json
{
	"status":"error",
	"message":"Feed could not be converted, probably not a valid RSS feed."
}
```

![Screenshot 2022-05-05 at 06 31 51](https://user-images.githubusercontent.com/88313112/166872883-a796f7de-32ca-4058-bb0d-3e17cb272730.png)

**Comment by sfshaza2** [comment]
Yes, I brought this up when meeting with the website folks today. They pointed out that the RSS feed from medium appears to be broken. They are going to replace that with a manual solution tout de suite. @btobin

**Comment by sfshaza2** [comment]
This has been fixed. Closing.
