### ISSUE TITLE
[PAGE ISSUE]: 'Windows install'

### ISSUE THREAD

**Issue by mazenmoataz** [flutter/website#6485]
### Page URL

https://docs.flutter.dev/get-started/install/windows/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/windows.md

### Describe the problem

Hello, good work you've done on flutter, but the website really needs a dark theme because I don't wanna burn my eyes while I look at the docs.

### Expected fix

Adding a theme switch button on the website.

**Comment by danagbemava-nc** [comment]
Kindly see https://github.com/flutter/website/issues/3632 and https://github.com/flutter/website/issues/2404.

Closing as duplicate
