### ISSUE TITLE
Improve image format/sizing and caching

### ISSUE THREAD

**Issue by guidezpl** [flutter/website#6487]
### Describe the problem

The only major performance issue highlighted by Lighthouse regards images. Estimated savings for serving images in next-gen formats, efficiently encoding images, and properly sizing them are ~1.9s

Assets also all have a 1h cache policy, which seems quite short for static content.

### Expected fix
- [ ] use a better image format
- [ ] optimize/resize images
- [ ] increase cache policy for assets

**Comment by danagbemava-nc** [comment]
Screenshots of Lighthouse report for context.

<details>
<summary>screenshots</summary>

![Screenshot 2021-11-19 at 10 57 23](https://user-images.githubusercontent.com/88313112/142611911-08d8d9fd-c113-4ccd-b3c6-5a70c23e6318.png)


![Screenshot 2021-11-19 at 10 58 14](https://user-images.githubusercontent.com/88313112/142611907-0af8485c-acc3-43bd-ab75-8541dc53f4d1.png)



</details>

**Comment by guidezpl** [comment]
@parlough I believe I saw PRs from you that fixed this?
