### ISSUE TITLE
[PAGE ISSUE]: 'Install'

### ISSUE THREAD

**Issue by JRoCsTuDi0DeVandPr0** [flutter/website#6491]
### Page URL

https://docs.flutter.dev/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/index.md

### Describe the problem

My Samsung Galaxy A12 won't load the boot menu when I try to run recovery mode. It just takes me to the download screen and from that point when you click to proceed with the install, it will just say downloading until either the battery drains or remains what appears to be frozen on that inparticular screen.

### Expected fix

Is there any possible advice on how to restore this device as it appears to be running a corrupted version of Android 11..?

### Additional context

I can't seem to pull the boot menu so any help in that area would be absolutely amazing.

**Comment by danagbemava-nc** [comment]
Hi @JRoCsTuDi0DeVandPr0, do you care to explain how what you're describing is an issue with the "install" page?
