### ISSUE TITLE
[PAGE ISSUE]: 'Using the Flutter inspector'

### ISSUE THREAD

**Issue by ehsnaskri** [flutter/website#6496]
### Page URL

https://docs.flutter.dev/development/tools/devtools/inspector#fixed-size-layouts

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/devtools/inspector.md

### Describe the problem

The page is not responsive. The image overlaps the right-hand navigation menu (Content Menu) when the window is resized.
<img width="1208" alt="Screen Shot 1400-08-29 at 14 57 42" src="https://user-images.githubusercontent.com/46539678/142723096-a94404ae-9fc8-4566-b9ea-79d427fd0bc9.png">
 

### Additional context

_No response

_

**Comment by ehsnaskri** [comment]
<img width="1208" alt="Screenshot" src="https://user-images.githubusercontent.com/46539678/142723071-428ff543-4ee3-4c80-bc5e-9baff95099ca.png">

**Comment by ahmadrafidev** [comment]
I would love contribute in this issue
