### ISSUE TITLE
[Windows] flutter doctor fails with "The system cannot find the path specified"

### ISSUE THREAD

**Issue by gssln** [flutter/website#6506]
### Page URL

https://docs.flutter.dev/get-started/install/windows/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/windows.md

### Describe the problem

Command "flutter doctor" fails with "The system cannot find the path specified".

I downloaded the stable zip "flutter_windows_2.5.3-stable.zip", extracted to "C:\src\flutter" and added "C:\src\flutter\bin" to my user path.

I tried again by using git to get the latest version and that works properly.

Your zip might have an issue.

### Expected fix

Following the steps 1 and 2 should work.

### Additional context

Error message: The system cannot find the path specified
OS: Windows 10

**Comment by maheshmnj** [comment]
Hi @gssln, Thanks for filing the issue. Could you please share the complete path of where the flutter SDK is stored (`flutter/bin`) and the sdk path that has been added to the system environment variable `PATH`.

Additionally you may take a look at this [StackOverflow thread](https://stackoverflow.com/questions/59200693/flutter-doctor-the-system-cannot-find-the-path-specified-not-a-duplicate)

Thanks

**Comment by gssln** [comment]
As stated in the description of the issue: "zip extracted to "C:\src\flutter" and added "C:\src\flutter\bin" to my user path." 
The sdk path is stored in "C:\src\flutter\bin".

The same sdk location and path variable were used with git (skipping steps 1 and 2) with success.

**Comment by maheshmnj** [comment]
Oops sorry missed that detail. what does it say when you try these commands

```
flutter clean // run from within a project
flutter doctor -v
```
Please share the complete console output.

**Comment by gssln** [comment]
My problem has been fixed by using the git instructions instead of doing steps 1 and 2.
> git clone https://github.com/flutter/flutter.git -b stable

I was mostly reporting this issue I had with the zip file so that the flutter documentation can either be fixed or investigated, if case this is an issue that others developers are getting.
