### ISSUE TITLE
[PAGE ISSUE]: 'Ads support for Flutter'

### ISSUE THREAD

**Issue by zoeyfan** [flutter/website#6510]
### Page URL

https://docs.flutter.dev/ads/

### Page source

https://github.com/flutter/website/tree/main/src/ads/index.md

### Describe the problem

This page is outdated now.  All the latest information is available on [flutter.dev/monetization](https://flutter.dev/monetization). We can archive this page.

**Comment by zoeyfan** [comment]
Also, let's redirect flutter.dev/ads to flutter.dev/monetization once we remove the flutter.dev/ads page. Thanks!

**Comment by danagbemava-nc** [comment]
This issue has been addressed in https://github.com/flutter/website/pull/6545. 

Closing as fixed.
