### ISSUE TITLE
Add excellent video on Dart/C++ ffi to c-interop page

### ISSUE THREAD

**Issue by jhsware** [flutter/website#6511]
### Page URL

https://docs.flutter.dev/development/platform-integration/c-interop

### Page source

https://github.com/flutter/website/blob/main/src/development/platform-integration/c-interop.md

### Describe the problem

Impossible to find useful tutorials on Dart/C++ ffi.

### Expected fix

This video is amazing! Please embed or link to it from this docs page to save others from my pain.
https://www.youtube.com/watch?v=05Wn2oM_nWw

**Comment by danagbemava-nc** [comment]
Hi @jhsware, thanks for the suggestion.

**Comment by innos123** [comment]
> ### Page URL
> https://docs.flutter.dev/development/platform-integration/c-interop
> 
> ### Page source
> https://github.com/flutter/website/blob/main/src/development/platform-integration/c-interop.md
> 
> ### Describe the problem
> Impossible to find useful tutorials on Dart/C++ ffi.
> 
> ### Expected fix
> This video is amazing! Please embed or link to it from this docs page to save others from my pain. https://www.youtube.com/watch?v=05Wn2oM_nWw
> 
> ### Additional context
> _No response_

**Comment by atsansone** [comment]
Let's use the [Google I/O video](https://www.youtube.com/watch?v=2MMK7YoFgaA) instead.

**Comment by jhsware** [comment]
@atsansone I saw that one first, but the video I suggested was more helpful to me. Perhaps add both?
