### ISSUE TITLE
[PAGE ISSUE]: 'Internationalizing Flutter apps'

### ISSUE THREAD

**Issue by treyshotz** [flutter/website#6516]
### Page URL

https://docs.flutter.dev/development/accessibility-and-localization/internationalization/

### Page source

https://github.com/flutter/website/tree/main/src/development/accessibility-and-localization/internationalization.md

### Describe the problem

Should include the following command: flutter gen-l10n

### Expected fix

A field before step 6, where the command is included

**Comment by danagbemava-nc** [comment]
Hi @treyshotz, if you follow the instructions on the page, I don't believe the command should be necessary. 

This is what happened when I got to step 6 and run the app, after which I run the `flutter gen-l10n` command. 

```console
nexus@Daniels-MBP lcale % flutter gen-l10n
Because l10n.yaml exists, the options defined there will be used instead.
To use the command line arguments, delete the l10n.yaml file in the Flutter project.
```

**Comment by treyshotz** [comment]
Hmm how weird... I followed the tutorial step for step but it still doesn't seem to work for me. If this only affects me where certainly isn't necessary to add the field though. Perhaps i did something wrong during the setUp, but i really can't see the mistake to be frank.

Thanks for the reply btw!

**Comment by danagbemava-nc** [comment]
Hi @treyshotz, it would help if you could tell me what errors you're running into and where exactly you're running into them. 

The output of `flutter doctor -v` would also help

Thank you

**Comment by treyshotz** [comment]
Hi again!
I ended up deleting everything and doing it from the start again, and now it works. It seems I did something wrong the first time even though I couldn't figure out what. 
Anyways I appreciate the help!

**Comment by danagbemava-nc** [comment]
Closing based on https://github.com/flutter/website/issues/6516#issuecomment-983565073.
