### ISSUE TITLE
[PAGE ISSUE]: 'macOS install' - upgrade path

### ISSUE THREAD

**Issue by jedgrant** [flutter/website#6527]
### Page URL

https://docs.flutter.dev/get-started/install/macos/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/macos.md

### Describe the problem

The documentation current says you should use the following to update your path:
`export PATH="$PATH:[PATH_OF_FLUTTER_GIT_DIRECTORY]/bin"`

However, what actually worked for me using ZSH was that string without the quotes. For example: 
`export PATH=$PATH:~/development/flutter/bin`

Further, given that the guide suggests the path above, saying in the instruction "If you created a development folder and installed flutter there, you would add `export PATH=$PATH:~/development/flutter/bin` to you path file.

It would also be helpful to know how to 1) Know how to figure out what shell you are using `echo $SHELL` so that noobs like myself don't have to leave the site to figure out how to follow instruction. Same for how to actually edit the file for that shell in something like textEdit `open -a TextEdit ~/.zshrc` to make those changes, and finally how to reload it so that the changes take effect `source ~/.zshrc` - This was by far the most frustrating part of getting set up with flutter as someone who isn't a professional and is less familiar with command line tools.

### Expected fix

Update the documentation will all steps and strings that work.

### Additional context

Just my two cents, but I think it would make your guide more usable.

**Comment by danagbemava-nc** [comment]
Hi @jedgrant, thanks for filing this issue. 

>  Know how to figure out what shell you are using echo $SHELL

It looks like this is already captured in Step 2 in the `Update your path` section in the docs. 

```
Open (or create) the rc file for your shell. Typing echo $SHELL in your Terminal tells you which shell you’re using. If you’re using Bash, edit $HOME/.bash_profile or $HOME/.bashrc. If you’re using Z shell, edit $HOME/.zshrc. If you’re using a different shell, the file path and filename will be different on your machine.
```


> finally how to reload it so that the changes take effect

This is also captured in the `update your path` section, in step 4

```
 Run source $HOME/.<rc file> to refresh the current window, or open a new terminal window to automatically source the file.
```

Is there something about the way that it is in the documentation that wasn't clear to you? We'd like to know so that we can improve on this

**Comment by babtun123** [comment]
Thank you for posting this!
