### ISSUE TITLE
[PAGE ISSUE]: 'Background processes'

### ISSUE THREAD

**Issue by neco3coffee** [flutter/website#6530]
### Page URL

https://docs.flutter.dev/development/packages-and-plugins/background-processes/

### Page source

https://github.com/flutter/website/tree/main/src/development/packages-and-plugins/background-processes.md

### Describe the problem

At the moment, [workmanager](https://pub.dev/packages/workmanager) package isn't on this page

### Expected fix

The [workmanager](https://pub.dev/packages/workmanager) package should be listed on this page

**Comment by MiraMarshall** [comment]
Closing. This issue has been fixed.
