### ISSUE TITLE
[LINUX]: 'Install'

### ISSUE THREAD

**Issue by elimuhub7407** [flutter/website#6531]
### Page URL

https://docs.flutter.dev/get-started/install/linux 

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/index.md

### Describe the problem

@ianloic @
[Linux.md](https://github.com/flutter/website/issues/new?template=1_page_issue.yml&title=[PAGE%20ISSUE]:%20%27Linux%20install%27&page-url=https://docs.flutter.dev/get-started/install/linux/&page-source=https://github.com/flutter/website/tree/main/src/get-started/install/linux.md) 

### Expected fix

Installation of Linux desktop interface on Firefox android 

### Additional context

How to get started with installation of Linux on Android

**Comment by danagbemava-nc** [comment]
Hi @elimuhub7407, can you please provide more information as to what exactly it is the issue is? 

Your description isn't clear
