### ISSUE TITLE
'Flutter for web developers' page issue

### ISSUE THREAD

**Issue by YOOJAEYEONG** [flutter/website#6548]
Page URL: https://flutter-kr.io/docs/get-started/flutter-for/web-devs.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/flutter-for/web-devs.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: 
`깃허브에 있는 예제 앱` is 404 
( https://github.com/flutter/samples/blob/master/INDEX.md )

**Comment by danagbemava-nc** [comment]
Hi @YOOJAEYEONG, the flutter-kr.io site is community-maintained, as such, it is out of the scope of this issue tracker. 

Closing due to the above reason. 

Thank you
