### ISSUE TITLE
Can't run refresh-code-excerpts

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#6551]
### Describe the problem

Similar to #6281, I can't run `make refresh-code-excerpts`:

```
make refresh-code-excerpts
docker-compose run -d --rm site
WARNING: The DISABLE_TESTS variable is not set. Defaulting to a blank string.
WARNING: The FIREBASE_ALIAS variable is not set. Defaulting to a blank string.
WARNING: The FIREBASE_TOKEN variable is not set. Defaulting to a blank string.
Creating website_site_run ... done
website_site_run_83c1987c39c3
docker-compose exec site tool/refresh-code-excerpts.sh --keep-dart-tool
make: *** [refresh-code-excerpts] Error 1
```

If I try to run `./tool/refresh-code-excerpts.sh` without a docker container, I get another error:

```
./tool/refresh-code-excerpts.sh 
diffutils version >=3.6 required - your version: 2.8.1
```

FYI @btobin 

### Expected fix

It's not clear what the error is - maybe we could print the error?

**Comment by btobin** [comment]
@johnpryan as of the next wave of updates to the Docker infra/setup, I'll be removing these convenience Make commands in favor of dropping into the container interactively and just running those scripts directly. For now, I say avoid usage of those make commands and instead:

```bash
# Run the container interactively
docker compose run site bash

# Run the desired bash script directly
./tool/refresh-code-excerpts.sh
```

This way you will get the full output of the script you are running. 

Just a reminder that nothing in this repo will run locally without the correct OS setup (e.g. `brew install diffutils`). All dev work for testing examples, etc locally should be performed in the containers only. An additional solution would be a .devcontainer, which is another item we can add to the docket. 

I'll be setting up time with @RedBrogdon to address further updates to these methods, and adding additional documentation.
