### ISSUE TITLE
[PAGE ISSUE]: 'Advanced UI'  is blank

### ISSUE THREAD

**Issue by shah000** [flutter/website#6565]
### Page URL

https://docs.flutter.dev/development/ui/advanced/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/advanced/index.md

### Describe the problem

not show anything
![image](https://user-images.githubusercontent.com/48676720/145983155-f9e65507-0211-4923-ad97-23d6d97a196c.png)

**Comment by danagbemava-nc** [comment]
Related issues 
- #6526
- #6468

**Comment by danagbemava-nc** [comment]
Reopening this since the pr was reverted
