### ISSUE TITLE
[PAGE ISSUE]: 'Implicit animations'

### ISSUE THREAD

**Issue by webeasystep** [flutter/website#6575]
### Page URL

https://docs.flutter.dev/codelabs/implicit-animations/

### Page source

https://github.com/flutter/website/tree/main/src/codelabs/implicit-animations.md

### Describe the problem

line 3 • Prefer using lowerCamelCase for constant names.
info
line 6 • Annotate overridden members. 
info
line 15 • Prefer const with constant constructors.
info
line 17 • Prefer const with constant constructors. 
info
line 19 • Avoid returning null for void. 

### Expected fix

to not show these errors

**Comment by danagbemava-nc** [comment]
Looks like all the samples in the dartpads aren't passing the linter
/cc @domesticmouse

**Comment by domesticmouse** [comment]
Hey @khanhnwin, any ideas on how to update these code samples?

/cc @sfshaza2

**Comment by khanhnwin** [comment]
@domesticmouse Outside of fixing the errors themselves. Do you know if we're able to configure an `analysis_options.yaml` for Dartpad? I haven't done too much with Dartpad so I'd need to do some more research. 

Worst case we could ignore those linter errors with ignore_for_file, but that's really messy. Ex:`// ignore_for_file: constant_identifier_names, annotate_overrides, prefer_const_constructors, avoid_returning_null_for_void, avoid_unnecessary_containers, prefer_const_literals_to_create_immutables`

**Comment by domesticmouse** [comment]
We use a common analysis configuration for all DartPads. We don't have a way to configure on a per pad basis. 

/cc @srawlins and @RedBrogdon
