### ISSUE TITLE
Add: 'Flutter for Beginners' book

### ISSUE THREAD

**Issue by Elizabeth211998** [flutter/website#6587]
Please add the following book in your 'Books About Flutter' section on the official website.

[Flutter for beginners](https://www.amazon.com/Flutter-Beginners-introductory-cross-platform-applications/dp/1800565992/ref=sr_1_1?keywords=flutter+for+beginners&qid=1639751026&sr=8-1)

**Comment by timsneath** [comment]
Fixed in #7140
