### ISSUE TITLE
[PAGE ISSUE]: 'Flutter Brand Guidelines'

### ISSUE THREAD

**Issue by alexeyinkin** [flutter/website#6588]
### Page URL

https://docs.flutter.dev/brand/

### Page source

https://github.com/flutter/website/tree/main/src/brand/index.md

### Describe the problem

The guideline forbids to use Flutter a social media username.

But then it says
> You may use the Flutter trademarks as part of the name of a newsletter or related community content (e.g., Flutter training courses, Flutter community forums) whose purpose is to promote the use of the Flutter SDK by members of the developer community.

This means I can use "Flutter" in the title of a potential Medium publications series if I use a disclaimer. Say, I would name it "Flutter Senior" to publish tips to junior developers on more clear Flutter code.

What is unclear is whether I can use "flutter" as URL like `https://medium.com/flutter-senior`
This qualifies as social media username, and for that only geographic exception is given.

Also Flutter Community is a publication on Medium and some entity behind it. So referring to Flutter community is ambiguous in this guideline. Does any developer fall under these three exceptions in the bottom if they want to publish educational content? Or do they need to be affiliated with some community entity for that?

### Expected fix

1. Explicitly allow or disallow community usage of "flutter" in URLs of channels and profiles given they fall under the 2nd exception.
2. Explicitly state what Flutter community refers to.

**Comment by sfshaza2** [comment]
@timsneath, can you answer this question?

**Comment by timsneath** [comment]
Thanks for the question. We don't object to using `flutter` in a URL. But as per the second clause under "community exceptions", you should make it clear that a blog site like this is not affiliated with Google.
