### ISSUE TITLE
[PAGE ISSUE]: 'Fetch data from the internet'

### ISSUE THREAD

**Issue by Ishantcoders** [flutter/website#6601]
### Page URL

https://docs.flutter.dev/cookbook/networking/fetch-data/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/networking/fetch-data.md

### Describe the problem

My Site data not showing

**Comment by danagbemava-nc** [comment]
Hi @Ishantcoders, I tested the code on the page and it works as expected. 

It looks you're having issues with your personal code, kindly see https://flutter.dev/community#community-grid. 

You may find members of the community there to help you with your code. 

Closing as this is not the right place to ask for help with personal code.

Thank you
