### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by kaycebasques** [flutter/website#6608]
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

The page says the following:

> The main() method uses arrow (=>) notation. Use arrow notation for one-line functions or methods.

Yet the referenced code does not appear to actually use arrow notation.

**Comment by purezen** [comment]
Curious if there's a resolution for this. Seems straightforward.

**Comment by domesticmouse** [comment]
Fixed by #6707
