### ISSUE TITLE
[PAGE ISSUE]: 'Work with WebSockets'

### ISSUE THREAD

**Issue by WatchDogsDev** [flutter/website#6609]
### Page URL

https://docs.flutter.dev/cookbook/networking/web-sockets/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/networking/web-sockets.md

### Describe the problem

Why is this `TextEditingController` not disposed on widget dispose?

```
final TextEditingController _controller = TextEditingController();
  final _channel = WebSocketChannel.connect(
    Uri.parse('wss://echo.websocket.org'),
  );
```

```
@override
  void dispose() {
    _channel.sink.close();
    super.dispose();
  }
```

### Expected fix

Change dispose method to this :

```
@override
  void dispose() {
    _channel.sink.close();
    _controller.dispose();
    super.dispose();
  }
```

**Comment by danagbemava-nc** [comment]
Closing as the linked pr has been merged.
