### ISSUE TITLE
[PAGE ISSUE]: 'Flutter for Android developers': Broken Link

### ISSUE THREAD

**Issue by leventkantaroglu** [flutter/website#6615]
### Page URL

https://docs.flutter.dev/get-started/flutter-for/android-devs#how-do-i-listen-to-android-activity-lifecycle-events

### Page source

https://github.com/flutter/website/tree/main/src/get-started/flutter-for/android-devs.md

### Describe the problem

"AppLifecycleStatus documentation" link is broken.
It tries to redirect "https://api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html", but page is not exist.

> Page Not Found
> This file does not exist and there was no index.html found in the current directory or 404.html in the root directory.
>
> Why am I seeing this?
> You may have deployed the wrong directory for your application. Check your firebase.json and make sure the public directory is pointing to a directory that contains an index.html file.
>
> You can also add a 404.html in the root of your site to replace this page with a custom error page.

### Expected fix

I should redirect a valid content page.

### Additional context

Scrennshots:
<details>

<img width="1375" alt="Screen Shot 2021-12-29 at 11 52 26" src="https://user-images.githubusercontent.com/63751824/147644249-aa07cce7-60be-4da4-882b-c7fa513f7015.png">

</details>

<details>

<img width="1411" alt="Screen Shot 2021-12-29 at 11 52 50" src="https://user-images.githubusercontent.com/63751824/147644261-88b5cd82-4883-4b38-837a-3790b54ee63c.png">

</details>

**Comment by danagbemava-nc** [comment]
Hi @leventkantaroglu, thanks for reporting this. 

It looks like the actual content is over here https://api.flutter.dev/flutter/dart-ui/AppLifecycleState.html.

**Comment by tilltonystark** [comment]
Hi there!
Myself Satyam, I'm new to open source and willing to contribute more 😄 If this issue is still open can I work on this? @danagbemava-nc

**Comment by danagbemava-nc** [comment]
Hi @tilltonystark, this appears to still be an issue. 

Contributions are always welcome. Kindly see https://github.com/flutter/website/blob/main/CONTRIBUTING.md

**Comment by MrBirb** [comment]
@danagbemava-nc Looks like this was fixed
