### ISSUE TITLE
[PAGE ISSUE]: 'Flutter for iOS developers'

### ISSUE THREAD

**Issue by Tommy-Elliott** [flutter/website#6618]
### Page URL

https://docs.flutter.dev/get-started/flutter-for/ios-devs/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/flutter-for/ios-devs.md

### Describe the problem

The link for "`AppLifecycleState` documentation" is broken (line 1301 in the file referenced in the Page source link for this issue at the time of this issue's creation).  On the website, the link points to
https://api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html
which is a broken url.

The exact same issue also exists in the Flutter for Android developers page (same sentence, same link, same incorrect href value).

Separately, it also seems that the description of the observable lifecycle events might not all be correct on the iOS page (compared to what is on the Android page and the linked AppLifecycleState documentation).  `detached` isn't listed but should be, and `suspending` is listed but shouldn't be.

I'm also not sure but perhaps the text under `inactive` on the iOS page (in quotes after this sentence) should either be removed or also included on the Android page, depending on whether it is still correct or not.
"This event only works on iOS, as there is no equivalent event on Android."

### Expected fix

The intended url these links are meant to point to is:
https://api.flutter.dev/flutter/dart-ui/AppLifecycleState.html
(Note that the "-class" part near the end of the url is removed from what the page renders currently).  Please change each of these two pages so their link points to the correct url.

Also, please update the text in the section describing the states to be up to date and correct (on the iOS page).

**Comment by danagbemava-nc** [comment]
Hi @Tommy-Elliott, thanks for catching this. 

The broken link on the android page was reported in https://github.com/flutter/website/issues/6615 recently. 

It looks like the xamarin page also has this link. 

https://docs.flutter.dev/get-started/flutter-for/xamarin-forms-devs

**Comment by MrBirb** [comment]
@danagbemava-nc Looks like this was fixed
