### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app on the web'

### ISSUE THREAD

**Issue by Morteza-24** [flutter/website#6619]
### Page URL

https://docs.flutter.dev/get-started/codelab-web/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab-web.md

### Describe the problem

In [line 127](https://github.com/flutter/website/blob/b1306810a6799984e2bdd597509f8dfa7f75414b/src/get-started/codelab-web.md?plain=1#L127) _Web Server_ is said to be shown in the output of `flutter devices` command. But this option [has been removed](https://github.com/flutter/flutter/issues/75088#issuecomment-789253047) and is not shown in the output anymore.

### Expected fix

The output should be updated and then it should be followed by a _tip_ explaining how a flutter app could be run with `-d web-server` to host the app and load it from any browser.

**Comment by danagbemava-nc** [comment]
Hi @Morteza-24, thanks for reporting this. 

That whole codelab needs to be updated. It still mentions switching to the `beta` channel to enable web, but that has changed in recent versions of flutter. Although, that is being tracked in https://github.com/flutter/website/issues/6348. 

There are also a couple of lint errors in the dartpads.

**Comment by domesticmouse** [comment]
I believe the errors on the DartPads were fixed by https://github.com/flutter/website/pull/6629
