### ISSUE TITLE
flutter scaffold behaves wrong when I drag a flutter website from smaller screen to larger screen

### ISSUE THREAD

**Issue by poudelnarayan** [flutter/website#6624]
### Describe the problem

When testing a flutter website it runs smoothly on the laptop screen and when I drag that website to my secondary monitor screen the flutter UI completely changes. It does not take the full height and width of my secondary monitor screen as shown in 'Screenshot (4)_LI.

![Screenshot (3)](https://user-images.githubusercontent.com/39937902/147909342-a9cdba06-b534-4cdd-9923-86eb7301b859.png)
![Screenshot (4)_LI](https://user-images.githubusercontent.com/39937902/147909346-26270b19-b4fa-4fad-9929-5074545a9f5e.jpg)

**Comment by danagbemava-nc** [comment]
Hi @poudelnarayan, this is a core flutter issue and is being tracked in https://github.com/flutter/flutter/issues/77605. 

Closing from here as this isn't an issue with the website.
