### ISSUE TITLE
Typo on flutter website

### ISSUE THREAD

**Issue by MalcolmMielle** [flutter/website#6627]
I'm sorry if that's not where to write for those issue, but I have no idea where to go for it.

There is a typo in [this page](https://flutter.dev/multi-platform/desktop) where `involved` is spelled `invovled`. Where can I write to signal it?

**Comment by danagbemava-nc** [comment]
![Screenshot 2022-01-07 at 09 42 18](https://user-images.githubusercontent.com/88313112/148524910-e7b3019f-5126-496c-845d-d88e45f2ae4a.png)

This issue has since been fixed. See the screenshot above. 

Closing as fixed.
