### ISSUE TITLE
Missing semicolons at the "Building a Cupertino app with Flutter" codelab's snippet

### ISSUE THREAD

**Issue by maxeema** [flutter/website#6630]
Hello

At the codelab https://codelabs.developers.google.com/codelabs/flutter-cupertino#6 are missing semicolons at the code snippet with imports. You can see it in the screenshot below.

![missing_semicolons](https://user-images.githubusercontent.com/51894783/148137632-7de8787e-97e4-4913-9ce3-48836f2609af.png)

**Comment by maxeema** [comment]
![missing_semicolons_expanded](https://user-images.githubusercontent.com/51894783/148137943-18f18b3f-7750-4079-a931-449d82925cc4.png)

**Comment by danagbemava-nc** [comment]
The source that page is based on does have the semi-colons, I wonder why it isn't showing in the codelab. 
Link to source: https://github.com/flutter/codelabs/blob/master/cupertino_store/step_03/lib/search_tab.dart#L15

/cc @domesticmouse

**Comment by domesticmouse** [comment]
For googlers, the fix is in cl/420023498

**Comment by domesticmouse** [comment]
This is now fixed

**Comment by maxeema** [comment]
Thank you, guys!
Great job!
