### ISSUE TITLE
[PAGE ISSUE]: 'Flutter SDK releases' should display version numbers for Dart

### ISSUE THREAD

**Issue by jonasfj** [flutter/website#6631]
### Page URL

https://docs.flutter.dev/development/tools/sdk/releases/

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/sdk/releases.md

### Describe the problem

It would be extremely helpful to users if we displayed Flutter version and Dart version next to each other.

![image](https://user-images.githubusercontent.com/149732/148215616-3191e829-5ba6-4f04-978a-1329b18ceaf1.png)

As of Flutter 2.0, it's not possible to have an upper-bound constraint on the Flutter SDK in `environment.flutter` in `pubspec.yaml`.
But it is possible to have an upper-bound constraint on the Dart SDK, thus, it makes sense for package authors who needs it to just use the Dart SDK constraint. However, they currently don't have a way to see what Dart version is in a given Flutter release.

**Comment by mit-mit** [comment]
This page just renders the content from the release json files:
https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json

@zanderso  would it be a lot of work to add a "dart_version" tag to that?

**Comment by zanderso** [comment]
I'm sorry, I don't know much about the website, or how that json file is generated.

**Comment by mit-mit** [comment]
The json file is just read by the website, but otherwise unrelated to it. I believe that the file is updated by the Flutter release scripts? @gspencergoog I seem to recall you have some knowledge if releases.json?

**Comment by gspencergoog** [comment]
The JSON file is generated as part of the package generation script, and we'd just need to add a line in [prepare_package.dart](https://github.com/flutter/flutter/blob/45726a84581998de57eb1b20cf97b4a4c4e7483c/dev/bots/prepare_package.dart#L604)

Also, it shouldn't be hard, but the website would have to deal with older JSON files that don't contain that tag, since we wouldn't be republishing all the previous releases. It might be possible to hand-edit the historical files and update on the server, but that's risky (if we got it wrong, downloads could be broken on the live site).

**Comment by mit-mit** [comment]
It's totally fine if we only get this set for new releases; we can handle that in the website script which parses the file.

**Comment by gspencergoog** [comment]
Would you want the "whole" version string (e.g. "2.8.0 (build 2.8.0-dev.18.0 eea9717938)"), or would you just want the semver version numbers (e.g. "2.8.0")?

**Comment by mit-mit** [comment]
I think we'd want the `2.1.0-dev.8.0` part. This is similar to what we report in brackets under Dart for `flutter --version`:

```
Flutter 2.9.0-1.0.pre.47 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 9de8849905 (4 weeks ago) • 2021-12-12 20:54:15 -0500
Engine • revision f16c96c31f
Tools • Dart 2.16.0 (build 2.16.0-85.0.dev) • DevTools 2.9.1
```

I think maybe the regexp from here can be used?
https://github.com/flutter/flutter/pull/88743/files

**Comment by gspencergoog** [comment]
I suggest that I add the entire dart sdk version string to the JSON file, and the website can use that regexp, etc. to convert it to the right form.  That way, if the site decides to display the corresponding hash or something, then the information is there.

Here's a PR for doing exactly that:

**Comment by mit-mit** [comment]
sgtm

**Comment by gspencergoog** [comment]
No, it's possible.  They're just text (JSON) files on the server, and we could download each one, unpack it, check the version, and add that field to the existing metadata.  It would require writing a script to do the downloading/editing, and then running it on all previous releases.

**Comment by mit-mit** [comment]
Closing: this was completed a while back
