### ISSUE TITLE
[PAGE ISSUE]: 'Flutter SDK releases'

### ISSUE THREAD

**Issue by IAmBotmaker** [flutter/website#6643]
### Page URL

https://docs.flutter.dev/development/tools/sdk/releases/

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/sdk/releases.md

### Describe the problem

Stable channel (Windows):
Table of versions is duplicated twice - one duplicate inside the table - under the other one.

**Comment by IAmBotmaker** [comment]
The same bug for Stable channel (macOS & Linux)

**Comment by domesticmouse** [comment]
Screenshot showing the issue you are seeing would be helpful

**Comment by danagbemava-nc** [comment]
Duplicate of #6329
