### ISSUE TITLE
`docs.flutter.dev/desktop` isn't linked from the navigation sidebar

### ISSUE THREAD

**Issue by domesticmouse** [flutter/website#6649]
@khanhnwin do you know where docs.flutter.dev's sidebar is stored?

/cc @csells for visibility

**Comment by khanhnwin** [comment]
Hi! It looks like it's part of the Jekyll includes: `src > _includes > shared`

**Comment by domesticmouse** [comment]
In a shock twist, the sidenav configuration is actually in `src/_data/sidenav.yml` =)

**Comment by khanhnwin** [comment]
Oh sorry! Of course the content itself, not the sidebar code. 😅

**Comment by domesticmouse** [comment]
@sfshaza2 where in the sidebar heirarchy should I put the `/desktop` entry?
