### ISSUE TITLE
Remove mentions of "dev" once we remove "dev"

### ISSUE THREAD

**Issue by Hixie** [flutter/website#6656]
### Page URL

https://docs.flutter.dev/development/tools/sdk/upgrading/

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/sdk/upgrading.md

### Describe the problem

This page says "Flutter has four release channels: stable, beta, dev, and master. [...] Please note - dev channel has been deprecated." which seems self-contradictory, but is technically accurate right now.

Once we remove the "dev" channel for real, we should fix this text to not mention it any more.

**Comment by Hixie** [comment]
cc @khyati82

**Comment by MrBirb** [comment]
@Hixie I believe this was addressed

**Comment by Hixie** [comment]
thanks!
