### ISSUE TITLE
Typo in docs.flutter.dev about Explicit animations

### ISSUE THREAD

**Issue by broccolism** [flutter/website#6660]
Hello, I've been studying flutter's animation from documentations in flutter.dev.
I think I found some typo from the documentation here: https://docs.flutter.dev/codelabs/explicit-animations

![image](https://user-images.githubusercontent.com/45515332/148767296-c488c6aa-14c2-4e53-b0fb-5580ff96e0d9.png)

1. What does `PENDING: # image: a frame in Flutter` mean?
Since I'm not a native English user, I cannot guess the meaning of this sentence.
If it is written in mistake, I think it should be fixed and or not, I wish it was clearer so that everyone reading this documentation can easily understand it.

2. Even **this though** example doesn’t use Flutter’s animation library
I guess this sentence needs to be: Even **though this** example doesn’t use Flutter’s animation library

Thanks for nice documentation though!

**Comment by danagbemava-nc** [comment]
Hi @broccolism, 

Thanks for reporting this. 

>  PENDING: # image: a frame in Flutter

An image is supposed to be shown on that side

> Even this though example doesn’t use Flutter’s animation library

Thanks for pointing this out. 

![Screenshot 2022-01-11 at 12 05 23](https://user-images.githubusercontent.com/88313112/148939653-31534d49-efe1-4a67-aad6-74876a2986b0.png)

The codelab is not yet complete, so bear with us until it is.

**Comment by broccolism** [comment]
@darshankawar @danagbemava-nc Thanks for checking.
So I don't need to do anything but closing this issue since this page is still in progress, is it right?

**Comment by danagbemava-nc** [comment]
Let's leave it open, in case the typo was missed

**Comment by piedcipher** [comment]
Is codelab completed?

**Comment by danagbemava-nc** [comment]
The info section that states that this codelab is not yet complete is still on the page, so I assume it is not complete yet

**Comment by parlough** [comment]
Thanks for opening the issue and for the discussions!

I'm going to close this in favor of https://github.com/flutter/website/issues/8057 tracking finishing the codelab. Thanks again :)
