### ISSUE TITLE
Add link to web-images on 'Display images from the internet' page

### ISSUE THREAD

**Issue by YogitaPat** [flutter/website#6662]
### Page URL

https://docs.flutter.dev/cookbook/images/network-image/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/images/network-image.md

### Describe the problem

Hello Team,
I am facing Issue with while displaying network image in my flutter app. Please help me, Thank you 

The following ImageCodecException was thrown resolving an image codec:
Failed to decode image data.
Image source: http://localhost:52286/     

OR 

The following ImageCodecException was thrown resolving an image codec:
Failed to load network image.
Image URL: https://constructionadminwebapp.s3.ap-southeast-2.amazonaws.com/logo.jpg
![Screenshot (572)](https://user-images.githubusercontent.com/92594886/148925142-2bca92ef-bf4a-452f-b640-2de82ff39252.png)

**Comment by danagbemava-nc** [comment]
Hi @YogitaPat, kindly see https://docs.flutter.dev/development/platform-integration/web-images. 
Please note that the Page Issue template is to be used for issues you find on any of the website pages. It is not meant to be used for asking for help with personal code. 
In the future, kindly visit any of the communities in https://flutter.dev/community#community-grid for assistance with your code. 
If you do find a bug in flutter, kindly file that on the main flutter repo. 



That being said, I think it is a good idea to add a link to [web-images](https://docs.flutter.dev/development/platform-integration/web-images.) on this page, maybe in a troubleshooting section. 
I imagine if a beginner stumbles onto this page and they're not aware of the cors issue, they'll experience the same thing the author of this issue.

**Comment by atsansone** [comment]
This issue has been managed. Closing.
