### ISSUE TITLE
[PAGE ISSUE]: 'Displaying images on the web'

### ISSUE THREAD

**Issue by YogitaPat** [flutter/website#6673]
### Page URL

https://docs.flutter.dev/development/platform-integration/web-images/

### Page source

https://github.com/flutter/website/tree/main/src/development/platform-integration/web-images.md

### Describe the problem

Hello Team ,

Thank you for the immediate response. 

I am facing issue with while displaying using s3 storage URL binding of NetworkImage widget flutter web App please Help me out , Thank you .

Please check below Code snippet 

 Container(
                       height: 90,
                        width: 90,
                        decoration: BoxDecoration(
                          color: Colors.red,
                          image: DecorationImage(
                            image: NetworkImage("https://constructionadminwebapp.s3.ap-southeast-2.amazonaws.com/logo2.png"),
                            //whatever image you can put here
                            fit: BoxFit.cover,
                          ),

                        ),

                      ),
                      
                      
                      Or 
                      
                      
                       CachedNetworkImage(
                        imageUrl: "https://constructionadminwebapp.s3.ap-southeast-2.amazonaws.com/logo2.png",
                        placeholder: (context, url) => new CircularProgressIndicator(),
                        errorWidget: (context, url, error) => new Icon(Icons.error),
                      ),
                      
                     
![Screenshot (572)](https://user-images.githubusercontent.com/92594886/149077082-6e5c0984-fbaf-493c-bd74-b1148bd83aed.png)

**Comment by danagbemava-nc** [comment]
Hi @YogitaPat, 

Kindly see the [CORS section](https://docs.flutter.dev/development/platform-integration/web-images#cross-origin-resource-sharing-cors) for an explanation of what CORS is and [Cors Images](https://docs.flutter.dev/development/platform-integration/web-images#cross-origin-images) for how to solve it. 

Seeing as this isn't exactly an issue with the Page, I'm going to close this issue. 

Thank you

**Comment by YogitaPat** [comment]
Hello Team,

Thank you for your response.

Thanks
Yogita
