### ISSUE TITLE
Remove Video player for iOS simulator warning

### ISSUE THREAD

**Issue by jsgalarraga** [flutter/website#6674]
### Page URL

https://docs.flutter.dev/cookbook/plugins/play-video

### Describe the problem

At the end of step 2, on the iOS section it's said that "Warning: The video_player plugin doesn’t work on iOS simulators. You must test videos on real iOS devices."
However asset videos work perfectly

### Expected fix

Add to the warning which cases do and don't work for the video player. I found that network videos don't work but assets do. Don't know about other types.

**Comment by danagbemava-nc** [comment]
Hi @jsgalarraga, thanks for drawing attention to this. That warning is outdated and should be removed. 

The video_player plugin should be able to play network videos in the simulator and it can't, there's probably a bug that should be fixed. Feel free to file a bug with the relevant steps to reproduce on the main flutter repo.

**Comment by jsgalarraga** [comment]
Awesome @danagbemava-nc!
Thanks for the response, will file that issue.
