### ISSUE TITLE
Update banner and apprentice page

### ISSUE THREAD

**Issue by kwalrath** [flutter/website#6676]
### Page URL

https://docs.flutter.dev/apprentice-giveaway/

### Page source

https://github.com/flutter/website/tree/main/src/apprentice-giveaway/index.md

### Describe the problem

The giveaway is over, but you couldn't tell it from this page or the site banner.

### Expected fix

* https://docs.flutter.dev/apprentice-giveaway should be updated to indicate that the program is over.
* The site banner should be updated to something unrelated to the giveaway.

**Comment by sfshaza2** [comment]
This was fixed, long ago.
