### ISSUE TITLE
Forward old doc URL for adding desktop support to a project to new doc URL

### ISSUE THREAD

**Issue by cbracken** [flutter/website#6678]
Until https://github.com/flutter/flutter/pull/96559 landed yesterday, the flutter tool included an old URL in an error/help message that points to instructions on how to add desktop support to an existing flutter project. In the recent site re-vamp, the host name in that URL was updated from `flutter.dev` to `docs.flutter.dev`. 

The tool is now updated with the correct URL on master branch, but those running older versions of Flutter will be directed to the wrong page (see issue https://github.com/flutter/flutter/issues/94398). Could we get the old URL forwarded to the new one?

The old URL was:
https://flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app

This should be forwarded to the new URL:
https://docs.flutter.dev/desktop#add-desktop-support-to-an-existing-flutter-app

/cc @sfshaza2

**Comment by domesticmouse** [comment]
The Flutter.dev/desktop page contains desktop content, so we can't redirect wholesale.
