### ISSUE TITLE
Replace `i18n` and `a11y` in breadcrumbs for 'Accessibility' page

### ISSUE THREAD

**Issue by joostvhts** [flutter/website#6683]
### Page URL

https://docs.flutter.dev/development/accessibility-and-localization/accessibility/

### Page source

https://github.com/flutter/website/tree/main/src/development/accessibility-and-localization/accessibility.md

### Describe the problem

<img width="746" alt="image" src="https://user-images.githubusercontent.com/11671068/149516003-06b3f77d-66e4-46a0-9fa2-56d4a4197bbc.png">
the breadcrumbs on both the accessibility and internationalistion page seem to suffer from this cryptic labelling

### Expected fix

change cryptic stuff to Accessibility and Internationalization :3

### Additional context

The issue appears not only on [Accessibility](https://docs.flutter.dev/development/accessibility-and-localization/accessibility) but also [Internationalization](https://docs.flutter.dev/development/accessibility-and-localization/internationalization)

**Comment by danagbemava-nc** [comment]
Hi @joostvhts, the "cryptic" stuff you're seeing there are used as abbreviations for Accessibility(a11y) and Internationalization(i18n).  
I suppose we can add a note so that people who are not familiar may know what they mean.

**Comment by joostvhts** [comment]
My bad! Just noticed the same labels in some example code and suspected something. Labels might indeed prevent noob confusion :)

**Comment by atsansone** [comment]
These are common abbreviations for these terms, because they are very long words in English. (See [i18n](https://en.wikipedia.org/wiki/Internationalization_and_localization) and [a11y](https://www.a11yproject.com/).) Closing this issue.
