### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by nickppbd** [flutter/website#6695]
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

The main() method uses arrow (=>) notation. Use arrow notation for one-line functions or methods.

### Expected fix

should have removed

**Comment by danagbemava-nc** [comment]
Duplicate of #6608
