### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by yetiyoga123** [flutter/website#6699]
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

lib/main.dart:24:18: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.
          child: RandomWords(),
                 ^^^^^^^^^^^

### Expected fix

Removed const

**Comment by danagbemava-nc** [comment]
Duplicate of #6642
