### ISSUE TITLE
Unused sample code in `src/_packages/dartpad_picker`

### ISSUE THREAD

**Issue by domesticmouse** [flutter/website#6706]
It looks like it may not be used anymore after the [docs.flutter.dev switch over](https://github.com/flutter/website/commit/2dd7558712918cc97470c15efd2c153eac09f98a) which removed the old [index.html](https://github.com/flutter/website/blob/86e7cd49f10550780663c10aef7dc8d96797dcf7/src/index.html) where it was used.

If [these interactive samples](https://github.com/flutter/website/blob/main/src/_packages/dartpad_picker/web/dartpad_picker_main.dart#L34) or others are still desired, we could reintroduce this into the new https://docs.flutter.dev/ homepage in https://github.com/flutter/website/blob/main/src/index.md

_Originally posted by @parlough in https://github.com/flutter/website/issues/6702#issuecomment-1018112540_

**Comment by domesticmouse** [comment]
I'm happy to delete unused sample code.

**Comment by parlough** [comment]
This sample code is no longer used after https://github.com/flutter/website/pull/6738, closing.
