### ISSUE TITLE
[PAGE ISSUE]: 'Work with WebSockets'

### ISSUE THREAD

**Issue by AlbertDenizLevi** [flutter/website#6730]
### Page URL

https://docs.flutter.dev/cookbook/networking/web-sockets/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/networking/web-sockets.md

### Describe the problem

wss://echo.websocket.org is no longer available. You may check www.websocket.org for proof. This causes the whole program to be obsolete.

### Expected fix

I do not know any other echo services, sadly I cannot be much of a help in this case.

**Comment by danagbemava-nc** [comment]
Duplicate of #6382
