### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app on the web'

### ISSUE THREAD

**Issue by nickppbd** [flutter/website#6731]
### Page URL

https://docs.flutter.dev/get-started/codelab-web/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab-web.md

### Describe the problem

> 1. Set a breakpoint.
> Now that you have DevTools running, select the Debugger tab in the blue bar along the top. The debugger pane appears and, in the lower left, see a list of libraries used in the example. _Select signin/main.dart_ to display your Dart code in the center pane.

I can not Select signin/main.dart at DevTools. Where can I select the file?

**Comment by danagbemava-nc** [comment]
Hi @nickppbd, I think that may be a typo. 
You should click your `main.dart` file in the `lib` folder. So, that'll be `lib/main`. 

We do need to fix that typo. 

Thanks for reporting this
