### ISSUE TITLE
[PAGE ISSUE]: Building beautiful UIs with Flutter

### ISSUE THREAD

**Issue by nickppbd** [flutter/website#6742]
### Page URL

https://codelabs.developers.google.com/codelabs/flutter#3

### Describe the problem

Try the finished app on DartPad! ->https://dartpad.dev/?id=99243efc05f92cd541af5e279c012050

There are some errors in the code that doesn't make it work.

**Comment by danagbemava-nc** [comment]
It looks like the code in the dartpad hasn't been updated for to null-safety. 

/cc @domesticmouse

**Comment by domesticmouse** [comment]
Googlers: cl/443003773

**Comment by parlough** [comment]
The links to this old codelab have been removed and the link now redirects to the new [Boring to Beautiful codelab](https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful) which doesn't have this issue, so I'm going to close this, thanks again!
