### ISSUE TITLE
[PAGE ISSUE]: 'State management'

### ISSUE THREAD

**Issue by marc-x-andre** [flutter/website#6758]
### Page URL

https://docs.flutter.dev/development/data-and-backend/state-mgmt/

### Page source

https://github.com/flutter/website/tree/main/src/development/data-and-backend/state-mgmt/index.md

### Describe the problem

The page is empty, however there is a title and the breadcrumb.

**Comment by sfshaza2** [comment]
This is also true for [the data & backend index page](https://docs.flutter.dev/development/data-and-backend). The [Development index page doesn't](https://docs.flutter.dev/development) contain the proper links.

@khanhnwin @domesticmouse

**Comment by domesticmouse** [comment]
I don't know what to do here. Last time I tried to fix this by deleting the page and changing the sidebar, but that change was reverted.

**Comment by sfshaza2** [comment]
I remember that. Maybe @khanhnwin has some insight? If not, we will need to involve @btobin.

**Comment by khanhnwin** [comment]
Brett, when I staged the previous fix it seemed to still generate a link to an empty page, but with a different, more generic path. Let me take a look into why those pages are being generated. I think the best solution would be if we can prevent those pages and thus links from being generated at all?

**Comment by parlough** [comment]
The index generation (for this page and others) was fixed in https://github.com/flutter/website/pull/7197. Thanks again for opening the issue!
