### ISSUE TITLE
[Language Translation]

### ISSUE THREAD

**Issue by union93** [flutter/website#6762]
### What information is missing?

Hello. I am a Korean flutter user. Some pages support Korean translations, but most do not. The Korean Flutter community is looking for ways for users to contribute in this regard. Please let me know if there is any possible way

### How would you like us to fix this problem?

If you provide guidelines for word expression or grammar, we will provide translations as md files according to the guidelines.

**Comment by danagbemava-nc** [comment]
Hi @union93, thanks for filing this issue. 

I just want to confirm something, this is the main https://flutter.dev as well as https://docs.flutter.dev that you're referring to. 

Is that correct?

**Comment by union93** [comment]
May be this site https://flutter-ko.dev/

**Comment by danagbemava-nc** [comment]
Unfortunately, the https://flutter-ko.dev/ is community-maintained and we do not have any way of contacting the maintainers of that site. 

We appreciate your enthusiasm, but unfortunately, this is something we do not control. As such I'm going to close this issue. 

Thank you
