### ISSUE TITLE
Fix example on 'Parse JSON in the background' page

### ISSUE THREAD

**Issue by Whisper40** [flutter/website#6768]
## Steps to Reproduce

Just follow what is writed there : https://docs.flutter.dev/cookbook/networking/background-parsing

**Expected results:** 
The parsePhotos should not produce errors

**Actual results:** 
Actually this method is all in red. I tried with and without this : 
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

My code : 
```dart
import 'dart:convert';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import '../models/post_model.dart';

class HttpService {
  final String url = 'https://jsonplaceholder.typicode.com';
  final String postsURL = '/posts';
  final Map<String, String> headers = {
    'Content-Type': 'application/json'
  };



  List<Post> parsePosts(String responseBody) {
  final parsed = jsonDecode(responseBody).cast<Map<String, dynamic>>();

  return parsed.map<Post>((json) => Post.fromJson(json)).toList();
  }


  Future<List<Post>> fetchPosts() async {

    final http.Response response = await http.get(Uri.https(url, postsURL));

    if (response.statusCode == 200) {
      return compute(parsePosts,response.body);
    } else {
      throw Exception("Failed to load posts ${response.statusCode}");
    }
  }


}
```
![image](https://user-images.githubusercontent.com/30440458/118389735-8ff55100-b62b-11eb-823e-87189733aab0.png)
![image](https://user-images.githubusercontent.com/30440458/118389740-97b4f580-b62b-11eb-9da2-19f579adf4cc.png)

**Comment by atsansone** [comment]
This recipe appears to have [most of the changes suggested](https://github.com/flutter/website/pull/6049) in [your initial PR](https://github.com/flutter/website/pull/5798).  The example shown works. Closing this issue. If this is still a concern, please open a new issue and refer back to this one. Thanks!
