### ISSUE TITLE
Add more details about firebase hosting to 'Build and release a web app' page

### ISSUE THREAD

**Issue by kevmoo** [flutter/website#6770]
### Page URL

https://docs.flutter.dev/deployment/web/

### Page source

https://github.com/flutter/website/tree/main/src/deployment/web.md

### Describe the problem

The end of the page only briefly mentions using GitHub or Firebase for hosting. We should do more!

### Expected fix

Likely need a new page here. I started sketching out some content here – at least useful for inspiration - https://github.com/kevmoo/flutter_web_firebase_hosting/

**Comment by xster** [comment]
+1, it just drops people into a generic non-Flutter related Firebase page. Do we need to flutter web build first?

**Comment by ditman** [comment]
See also: #8043

**Comment by polina-c** [comment]
More automation for flutter hosting on web would help as well. May be it can become part of VSCode plugin. 
GitHub CI for publishing did not work for me at first shut.

It seems some UX research to make sure it is reliable and easy to use, would help.

**Comment by atsansone** [comment]
@johnpryan : Do you have any thoughts on this?

**Comment by johnpryan** [comment]
I think I'm going to work on this soon, we need a link we can point to when we get questions about hosting.

**Comment by ditman** [comment]
@johnpryan Firebase Hosting now is friendly with Flutter Web, here's some documentation over from Firebase that might be interesting to this task: https://firebase.google.com/docs/hosting/frameworks/flutter

**Comment by atsansone** [comment]
Let's look at adding the firebase docs (or parts thereof) to this Flutter page.
