### ISSUE TITLE
Join our newsletter

### ISSUE THREAD

**Issue by harsha-deep** [flutter/website#6772]
### Page URL

https://flutter.dev/community

### Describe the problem

![Screenshot 2022-02-03 at 20-26-44 Flutter - Build apps for any screen](https://user-images.githubusercontent.com/77527524/152367797-75d8b8a0-b9ee-4f35-93ce-da9c2ce1fd64.png)

Typo in 'enter' [ highlighted ] when the subscribe button is pressed without entering any input.

The typo can also be seen on the error message for the `Last name` text field. 

### Expected fix

Change 'entier' to 'enter'.

**Comment by btobin** [comment]
Thank you @harsha-deep, great find!

**Comment by micpap25** [comment]
I believe this is an external issue, because the flutter.dev website is maintained separately from docs.flutter.dev ?
@btobin @danagbemava-nc Could you please advise?

**Comment by danagbemava-nc** [comment]
@micpap25, while the main flutter.dev site is maintained separately, issues with the main flutter.dev site are supposed to be filed here. They are the issues that get the `marketing` label.

**Comment by MrBirb** [comment]
@danagbemava-nc Looks like this was fixed

**Comment by parlough** [comment]
Yep, this was fixed on the flutter.dev side. Thanks again for reporting the issue!
