### ISSUE TITLE
[PAGE ISSUE]: Building beautiful apps with Flutter

### ISSUE THREAD

**Issue by nickppbd** [flutter/website#6783]
### Page URL

https://docs.flutter.dev/codelabs/

### Page source

https://github.com/flutter/website/tree/main/src/codelabs/index.md

### Describe the problem

[Building beautiful UIs with Flutter](https://codelabs.developers.google.com/codelabs/flutter)

[9. Apply finishing touches](https://codelabs.developers.google.com/codelabs/flutter#8)

The last image(https://codelabs.developers.google.com/codelabs/flutter/img/4e2592b1d3f65312.png) is not shown after debugging on iOS 15.0 simulator. The AppBar color is orange on the iOS simulator.

Hot reload do not work well.
If I change _primarySwatch: Colors.orange_ to _primarySwatch: Colors.brown_ and save, then Hot reload occurs and does not change the color.

But add the below source code
_final ThemeData kIOSTheme2 = ThemeData(
  primarySwatch: Colors.yellow,
  primaryColor: Colors.grey[100],
  primaryColorBrightness: Brightness.light,
);_

Change from kIOSTheme to _kIOSTheme2_
theme: defaultTargetPlatform == TargetPlatform.iOS
          ? _kIOSTheme2_
          : kDefaultTheme,

Erase the below source code
_final ThemeData kIOSTheme = ThemeData(
  primarySwatch: Colors.brown,
  primaryColor: Colors.grey[100],
  primaryColorBrightness: Brightness.light,
);_

And save , then Hot reload occurs and change to yellow.

Add 
_final ThemeData kIOSTheme = ThemeData(
  primarySwatch: Colors.brown,
  primaryColor: Colors.grey[100],
  primaryColorBrightness: Brightness.light,
);_

Change from _kIOSTheme2_ to kIOSTheme
theme: defaultTargetPlatform == TargetPlatform.iOS
          ? _kIOSTheme_
          : kDefaultTheme,

And save , then Hot reload occurs and change to brown finally.

And Hot restart works without those steps.

**Comment by danagbemava-nc** [comment]
> The last image([codelabs.developers.google.com/codelabs/flutter/img/4e2592b1d3f65312.png](https://codelabs.developers.google.com/codelabs/flutter/img/4e2592b1d3f65312.png)) is not shown after debugging on iOS 15.0 simulator. The AppBar color is orange on the iOS simulator.

I'm guessing the image needs to be updated. 

/cc @domesticmouse

**Comment by sfshaza2** [comment]
@nickppbd, this codelab has been retired and removed from the codelabs site. (It was the very first codelab written for Flutter years ago and I rewrote it to update and include Android Studio instructions a year or so ago.)

I just filed a PR to remove this from the codelabs page.
