### ISSUE TITLE
bug: navigation buttons not working

### ISSUE THREAD

**Issue by 120EE0692** [flutter/website#6796]
### Page URL

https://flutter.dev/

### Describe the problem

The cards do not move when the forward button is clicked

<img width="942" alt="image" src="https://user-images.githubusercontent.com/83752052/153004864-2f9499f8-f3bd-4ee7-b532-7916fe42424e.png">
<img width="895" alt="image" src="https://user-images.githubusercontent.com/83752052/153004911-b269d0cd-9414-4724-af19-269da141e453.png">

### Additional context

When the card is at then end of the page and the the `back` button is active, clicking the `back` button takes the cards back to the start.

**Comment by 120EE0692** [comment]
@btobin can I solve this issue?

**Comment by parlough** [comment]
@120EE0692 Unfortunately the source for the flutter.dev website is not currently available. Thanks for the offer and reporting this though!

**Comment by btobin** [comment]
@120EE0692 You've done the right thing! Thanks again.

**Comment by parlough** [comment]
This has been fixed and deployed. Thanks again for catching and reporting this!
