### ISSUE TITLE
Dashatar isn't working

### ISSUE THREAD

**Issue by mika76** [flutter/website#6804]
I wasn't sure where to post this as there is no info on the actual app, but when I tried [dashatar](https://dashatar-creator.web.app/#/), the UI for creating the dashatar works fine, but as soon as I click on the run button I get "Something went wrong. Please try again." I've tried different combinations to see if it was that, but they all just give the same result. 

I'm using Chrome 98

![](file:///var/folders/d8/rfmf5v3j70s4jxtpw70c59k40000gn/T/TemporaryItems/NSIRD_screencaptureui_Lr6MJn/Screenshot%202022-02-10%20at%2008.24.58.png)

**Comment by danagbemava-nc** [comment]
I'm not entirely sure if this belongs here since most of the demos are done by partners. 

/cc @sfshaza2

**Comment by sfshaza2** [comment]
Thanks for the heads up, @mika76! I've brought this to the attention of the marketing and PM teams.

**Comment by sfshaza2** [comment]
A ha! The problem here is that the URL is wrong. The correct URL is [dashatar](https://dashatar-dev.web.app/#/). Can you tell me where you got that other link? If it's on any of the pages we own, we should update it.

**Comment by sfshaza2** [comment]
D'OH. I see it's using the wrong link on the showcase page! (I had looked at the Who is Dash page, which has the correct link.) I will alert marketing that they need to fix it.

**Comment by btobin** [comment]
@sfshaza2 This is fixed for next release!

**Comment by mika76** [comment]
Just an unrelated note here - when you want to share your dashatar it comes up with the following message: 

> My #Dashatar is excited for the #FlutterEngage event on March 3rd! Have you built yours yet? See you there! https://dashatar-dev.web.app/share/RGFzaGF0YXJfRGVzaWduZXJfT3Zlckl0X2NvbG9yX0RLX3NoYWRvdw==.png

I'm not sure what this March 3rd is referring to but I'm assuming it's not valid anymore? You might want to update that too 😊

**Comment by piedcipher** [comment]
this one is fixed I guess. I checked it.

![Screenshot at 2022-09-11 00-20-28](https://user-images.githubusercontent.com/13456345/189497615-632242f7-9119-4556-a9ca-8088bc027301.png)

> D'OH. I see it's using the wrong link on the showcase page! (I had looked at the Who is Dash page, which has the correct link.) I will alert marketing that they need to fix it.

**Comment by piedcipher** [comment]
> A ha! The problem here is that the URL is wrong. The correct URL is [dashatar](https://dashatar-dev.web.app/#/). Can you tell me where you got that other link? If it's on any of the pages we own, we should update it.

are these apps (dashatar-dev and dashatar-creator) owned by same entity?

**Comment by parlough** [comment]
This has been fixed. Thanks again for reporting the issue!
