### ISSUE TITLE
[PAGE ISSUE]: 'Desktop support for Flutter' windows missing as an option

### ISSUE THREAD

**Issue by JonathanDLowe** [flutter/website#6811]
### Page URL

https://docs.flutter.dev/desktop/

### Page source

https://github.com/flutter/website/tree/main/src/desktop/index.md

### Describe the problem

This line is missing windows as an option as windows is now in with 2.10
Where <platform> is macos, or linux:

### Expected fix

Change line to below or similar
Where <platform> is macos, linux, or windows:

### Additional context

The below works for allowing Windows to be selected in the project creation dialog.
`flutter config --enable-windows-desktop`

**Comment by JonathanDLowe** [comment]
Then perhaps my issue lies elsewhere and isn't a docs issue.

I set up a fresh install of flutter 2.10(flutter_windows_2.10.1-stable.zip)
having never installed it or any version of flutter before. When I followed
the Getting Started step Test Drive guide, the Windows checkbox remained
grayed out until I used  flutter config --enable-windows-desktop. After
that command and restarting Android Studio, I was able to select the
Windows checkbox in the new project dialog flow.

I had already installed Visual Studio 2022 as described under "Additional
Windows requirements" and restarted Android Studio to no effect.

**Comment by danagbemava-nc** [comment]
Hmmm, I think we can add that in case someone else runs into the same scenario you run into.

**Comment by timsneath** [comment]
This looks like a bug, potentially? I came across this also this week. I'm going to close this docs issue so we can track this at https://github.com/flutter/flutter-intellij/issues/6174, which is the issue repo for the Flutter plugin for Android Studio and IntelliJ. Thanks for flagging this, @JonathanDLowe!
