### ISSUE TITLE
[PAGE ISSUE]: 'Transition of platform channel test interfaces to flutter_test package'

### ISSUE THREAD

**Issue by Thomalexa** [flutter/website#6815]
### Page URL

https://docs.flutter.dev/release/breaking-changes/mock-platform-channels/

### Page source

https://github.com/flutter/website/tree/main/src/release/breaking-changes/mock-platform-channels.md

### Describe the problem

API documentation reference links are broken. 

[TestDefaultBinaryMessenger](https://master-api.flutter.dev/flutter/%5Blink_to_relevant_page%5D.html)
[TestDefaultBinaryMessengerBinding](https://master-api.flutter.dev/flutter/%5Blink_to_relevant_page%5D.html)

### Expected fix

Well, I'd expect the links to work. 

Also, the information on how to update the code isn't exactly intuitive for a new developer. I've wasted countless hours trying to fix this when previous versions of flutter didn't change the location or names of the methods and their operators.

**Comment by Thomalexa** [comment]
> 

Thank you for the updated URL's! I'm hoping I can understand the work and fix this issue on my app. We _really_ have a need to get a new version of our app published.

**Comment by MiraMarshall** [comment]
Closing, this issue has been fixed.
