### ISSUE TITLE
Distribution section still refers to Windows as not being stable and not ready for release.

### ISSUE THREAD

**Issue by longtimedeveloper** [flutter/website#6818]
### Page URL

https://docs.flutter.dev/desktop#distribution

### Describe the problem

Current text:  **We don’t recommend releasing a desktop application until desktop support is stable**, however, here is some information that you might still find useful.

### Expected fix

Remove the above text.

**Comment by danagbemava-nc** [comment]
@longtimedeveloper, thanks for reporting this. 

There needs to be some clarification on the `stable` status of windows on that page. Perhaps a change of wording.

**Comment by longtimedeveloper** [comment]
@danagbemava-nc not sure what you mean by _clarification_.  

Both @timsneath and @csells blogged about Flutter Windows being in the `stable` branch and ready for product application deployments.  

For this issue, removing the invalid text seems to be the correct resolution for this issue.

There are other items that need to be added to this page, but this issue is about removing no longer valid information.

Best regards,

Karl

**Comment by danagbemava-nc** [comment]
Hi @longtimedeveloper, the Distribution section isn't referring to only Windows, windows just happens to be the first section under that section. That statement is still valid considering macOS and linux desktop are not stable yet. 

I hope that's clear.

**Comment by longtimedeveloper** [comment]
@danagbemava-nc I understand you now.  Then the statement should then read (or something similar that calls out Windows as ready for production.):

Since Flutter version 2.1.0, Windows desktop is in the stable branch, and production applications can be released.  

**For macOS and Linux desktop applications we don’t recommend releasing a desktop application until desktop support is stable for the operating system.**  However, here is some information that you might still find useful.

@timsneath @csells

**Comment by timsneath** [comment]
Yeah, I agree that we could tidy this up a little. Thanks for the report!
