### ISSUE TITLE
[PAGE ISSUE]: 'Install' flutter for termux 

### ISSUE THREAD

**Issue by ExtinctDrift19** [flutter/website#6820]
### Page URL

https://docs.flutter.dev/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/index.md

### Describe the problem

flutter do not install on the termux 

### Expected fix

tools used termux-create-packege  for flutter 
link https://github.com/termux/termux-create-package

### Additional context

flutter new URL https://docs.flutter.dev/get-started/install/termux

**Comment by danagbemava-nc** [comment]
Hi @ExtinctDrift19, I'm not exactly sure what exactly your issue is. 

Are you requesting that we create a page that shows how to install flutter on `termux` or are you saying you were unable to install flutter after using `termux-create-package`?

**Comment by ExtinctDrift19** [comment]
developers flutter used termux-create-package

**Comment by danagbemava-nc** [comment]
Hi @ExtinctDrift19, the request in this issue is still not clear. 

Kindly provide a more accurate description of what exactly you want. 

Thank you

**Comment by mdHABIBURRAHMANHABIB1** [comment]
you can Install Flutter in Termux ,

check this out
https://github.com/bdloser404/Fluttermux
