### ISSUE TITLE
Flutter mobile page - typo in image

### ISSUE THREAD

**Issue by tsymalla** [flutter/website#6838]
### Page URL

https://flutter.dev/multi-platform/mobile

### Describe the problem

The image around the section „Do more with less“ shows a class extending from „StatelefulWidget“ - I think you guys meant „StatefulWidget“ here.

### Expected fix

Replace the image with one showing the correct source code.

**Comment by danagbemava-nc** [comment]
<img width="367" alt="Screenshot 2022-02-22 at 09 43 32" src="https://user-images.githubusercontent.com/88313112/155111897-b538eed0-6be3-455f-a613-e01fadaaa8b8.png">

**Comment by tsymalla** [comment]
Seems to be fixed?

**Comment by danagbemava-nc** [comment]
Yes, this has since been fixed. 

Closing as fixed.
