### ISSUE TITLE
[Codelab] Get to know Firebase for flutter:  Typo word "upi"

### ISSUE THREAD

**Issue by tamx** [flutter/website#6839]
[Get to know Firebase for Flutter](https://firebase.google.com/codelabs/firebase-get-to-know-flutter)
In the sction 6, I found the word "upi". I guess this word is typo.

**Comment by danagbemava-nc** [comment]
<img width="1219" alt="Screenshot 2022-02-22 at 10 14 08" src="https://user-images.githubusercontent.com/88313112/155111268-39e3f538-8223-496b-90b4-6d94591a18cb.png">

/cc @domesticmouse
