### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by suniel** [flutter/website#6840]
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

Typo on the page.
"wiget" instead of widget

**Comment by danagbemava-nc** [comment]
![Screenshot 2022-02-23 at 09 37 39](https://user-images.githubusercontent.com/88313112/155293729-5543fb4a-afc1-4de4-a7df-9b1922650e8c.png)

**Comment by danagbemava-nc** [comment]
Thanks for the heads up @micpap25. 

It looks like this got buried in my notifications. 

Closing as fixed
