### ISSUE TITLE
[PAGE ISSUE]: 'Set up an editor'

### ISSUE THREAD

**Issue by jacob314** [flutter/website#6843]
### Page URL

https://docs.flutter.dev/get-started/editor/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/editor.md

### Describe the problem

Recommended versions for IntelliJ and Android Studio are quite old (2017 and 3.0). VSCode notes makes it seem like support for VSCode is not as complete as IntelliJ support.

### Expected fix

 We should recommend 
Android Studio Arctic Fox 2020.3.1 (or newer)
IntelliJ 2021.2 or newer

VSCode Flutter support is now generally comparable to IntelliJ Flutter support so we should change the wording so we don't make it sound like the VSCode experience is more limited.

**Comment by micpap25** [comment]
I believe this can be closed, seeing as this specific issue has been resolved. I am opening an issue to deal with the "latest stable version" update proposed in #6860
