### ISSUE TITLE
[PAGE ISSUE]: 'Deferred components'

### ISSUE THREAD

**Issue by ibrahemahmad** [flutter/website#6844]
### Page URL

https://docs.flutter.dev/perf/deferred-components/

### Page source

https://github.com/flutter/website/tree/main/src/perf/deferred-components.md

### Describe the problem

**### Deferred for now it works with the web??**
 because I'm using with web and do effect, split main.dart.js into a separate file and reduce size.

**Comment by danagbemava-nc** [comment]
Hi @ibrahemahmad, at the moment Deferred Components are only available for android. The documentation will be updated if it becomes available for other platforms.

Closing as this is not an issue with the page. 

Thank you
