### ISSUE TITLE
[PAGE ISSUE]: 'Accessibility'

### ISSUE THREAD

**Issue by Doetheman** [flutter/website#6845]
### Page URL

https://docs.flutter.dev/development/accessibility-and-localization/accessibility/

### Page source

https://github.com/flutter/website/tree/main/src/development/accessibility-and-localization/accessibility.md

### Describe the problem

Misspelled work

[](https://docs.flutter.dev/development/accessibility-and-localization/accessibility#large-fonts)In Chrome, the “Elements” tab has a “Accessbility” sub-tab that can be used to inspect the data exported to semantics tree

### Expected fix

In Chrome, the “Elements” tab has a “Accessibility” sub-tab that can be used to inspect the data exported to semantics tree

**Comment by micpap25** [comment]
Good catch! Fixing right now
