### ISSUE TITLE
IOS showing error in build mode in M1 Mac

### ISSUE THREAD

**Issue by mmd-shanu** [flutter/website#6847]
### What information is missing?

Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x214632b90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107d7c2c8). One of the two will be used. Which one is undefined.
    objc[7810]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x214632be0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107d7c318). One of the two will be used. Which one is undefined

### How would you like us to fix this problem?

I want to know this how to resolve this error while in debug or release mode

**Comment by danagbemava-nc** [comment]
The message that you're seeing is from XCode and has nothing to do with flutter. If you are running into issues building your app, kindly file an issue on the main flutter repo and provide the necessary info to reproduce. 

I'll be closing this as this error is not related to flutter. 

Thank you
