### ISSUE TITLE
[PAGE ISSUE]: 'Desktop support for Flutter'

### ISSUE THREAD

**Issue by abhaysood** [flutter/website#6850]
### Page URL

https://docs.flutter.dev/desktop/

### Page source

https://github.com/flutter/website/tree/main/src/desktop/index.md

### Describe the problem

Link to the codelab in [Samples and codelabs](https://docs.flutter.dev/desktop#samples-and-codelabs) section gives a 404.

### Expected fix

Update the codelab link to the correct location.

**Comment by danagbemava-nc** [comment]
Hi @abhaysood, thanks for reporting this.
