### ISSUE TITLE
[PAGE ISSUE]: 'Work with WebSockets'

### ISSUE THREAD

**Issue by odegirmenci** [flutter/website#6864]
### Page URL

https://docs.flutter.dev/cookbook/networking/web-sockets/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/networking/web-sockets.md

### Describe the problem

http://www.websocket.org/ 

SERVICE NO LONGER AVAILABLE

**Comment by danagbemava-nc** [comment]
Duplicate of #6382
