### ISSUE TITLE
fast load flutter web

### ISSUE THREAD

**Issue by dehbozorgy** [flutter/website#6871]
### Page URL

flutter.dev

### Describe the problem

please fast load web flutter pllllllllllllllllllllllleeeeeeeeeeeeaaaaaaaaaaaassssssssssssseeeeeeee

**Comment by danagbemava-nc** [comment]
Hi @dehbozorgy, this repo is not the correct place to report an issue with your flutter app. 
FWIW: There's an existing issue that you can follow up on in https://github.com/flutter/flutter/issues/76009. 

Closing as this is not the correct repo for this issue.
