### ISSUE TITLE
Flutter Favorite program page should be updated with the new committee chair email

### ISSUE THREAD

**Issue by csells** [flutter/website#6877]
### Page URL

https://docs.flutter.dev/development/packages-and-plugins/favorites

### Describe the problem

Because email to csells@google.com bounces, I've now had people reaching out to me in other ways to nominate Flutter Favorite candidates.

### Expected fix

Can the email address for the "committee chair" link in the "Flutter Ecosystem Committee" section be updated?

Also, you'll want to remove me as a member of the committee.

Thanks!

**Comment by parlough** [comment]
@mit-mit It seems this list of committee members is outdated in other ways as well and could at least use a temporary alternative email, any suggestions?

**Comment by timsneath** [comment]
@itsjustkevin I thought we had a new group set up for this one? Did that not land? 

I wonder if you might be able to take this one to resolution for me?
