### ISSUE TITLE
errors in documentation "Write Your First Flutter App, part 2"

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [flutter/website#6879]
at page: https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#3

at the line "**In the _buildRow function, add a ...**"

there is no _buildRow function in source code (also looking at https://github.com/flutter/codelabs/blob/master/startup_namer/step5_add_icons/lib/main.dart), or if I misunderstood (please excuse me me, i'm new at Dart) maybe it must be explained differently?

thank you
Edoardo

**Comment by parlough** [comment]
Thanks for opening an issue :)

It seems as this was updated as the page no longer mentions `_buildRow`.
