### ISSUE TITLE
Typing indicator cookbook interactive example imports an unused file

### ISSUE THREAD

**Issue by mateusfccp** [flutter/website#6880]
### Page URL

https://docs.flutter.dev/cookbook/effects/typing-indicator

### Describe the problem

The typing indicator cookbook interactive example imports `package:flutter/rendering.dart`, which does not provide anything new compared to the other imports. Thus, the linter gently asks it to be removed.

<img width="928" alt="image" src="https://user-images.githubusercontent.com/4605213/157019510-9f317546-1a43-4e3f-82a7-b8a6e5d3c0c1.png">

### Expected fix

Remove the line that imports `package:flutter/rendering.dart` from the interactive example.

**Comment by MrBirb** [comment]
@danagbemava-nc Looks like this was fixed

**Comment by danagbemava-nc** [comment]
Thanks for the heads up @MrBirb. 

Closing as fixed.
