### ISSUE TITLE
Add Windows examples to 'Writing custom platform-specific code' page

### ISSUE THREAD

**Issue by dlewis2017** [flutter/website#6888]
### Page URL

https://docs.flutter.dev/development/platform-integration/platform-channels/

### Page source

https://github.com/flutter/website/tree/main/src/development/platform-integration/platform-channels.md

### Describe the problem

Windows support seems to be in production but I'm not seeing much on Windows documentation where equivalent Android/iOS platform specific code examples are given. When will this come out, if at all? Or should one use the C interlop since Win32 is based on that? Either way, some examples would be nice

### Expected fix

Windows examples for platform specific code, similar to how android and iOS have platform specific code examples

### Additional context

Similar issue here but focusing on a different page and also asks for Linux: https://github.com/flutter/website/issues/6419
_No response_

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/7328. Closing.
