### ISSUE TITLE
Code lab Out of Date, Building beautiful UIs with Flutter

### ISSUE THREAD

**Issue by HarryLudemann** [flutter/website#6901]
### Page URL

https://docs.flutter.dev/codelabs/

### Page source

https://github.com/flutter/website/tree/main/src/codelabs/index.md

### Describe the problem

[Building beautiful UIs with Flutter](https://codelabs.developers.google.com/codelabs/flutter)

Section 9 "Applying Finishing Touches" of the "Building beautiful UIs with Flutter" code lab, suggests adding the following theme:
```dart
final ThemeData kIOSTheme = ThemeData(
  primarySwatch: Colors.orange,
  primaryColor: Colors.grey[100],
  primaryColorBrightness: Brightness.light, // THIS ARGUMENT
);
```
The argument primaryColorBrightness has a blue warning label providing the following information:
> 'primaryColorBrightness' is deprecated and shouldn't be used. No longer used by the framework, please remove any reference to it. This feature was deprecated after v2.6.0-11.0.pre

**Comment by sfshaza2** [comment]
Yes, this codelab has been deprecated and removed from the codelabs site and now redirects to a new codelab that uses Material 3. I've filed a PR to remove references to this retired codelab. https://github.com/flutter/website/pull/7201
