### ISSUE TITLE
Mistake in the codelabs docs - 'Building beautiful UIs with Flutter'

### ISSUE THREAD

**Issue by afridsyed935** [flutter/website#6904]
[https://codelabs.developers.google.com/codelabs/flutter#4](https://codelabs.developers.google.com/codelabs/flutter#4)

![image](https://user-images.githubusercontent.com/44317774/157885294-6a779012-8abe-48cd-9dbe-05e91324e8f2.png)

It show be `TextField` instead of `Row`

**Comment by MiraMarshall** [comment]
Closing because this issue has been fixed.
