### ISSUE TITLE
Fix explanation for Android Studio on 'Integrate a Flutter module into your Android project' page

### ISSUE THREAD

**Issue by mivoligo** [flutter/website#6905]
### Page URL

https://docs.flutter.dev/add-to-app/android/project-setup

### Page source

https://github.com/flutter/website/tree/main/src/development/add-to-app/android/project-setup.md

### Describe the problem

In "Using Android Studio" section, there's description how to add a Flutter module to an Android app. I tried to repeat the steps but I don't see the option for that in my version of Android Studio.

Image from the documentation:

![](https://docs.flutter.dev/assets/images/docs/development/add-to-app/android/project-setup/ide-new-module.png)

Screenshot from Android Studio:
 
![Screenshot from 2022-03-11 17-03-00](https://user-images.githubusercontent.com/1629120/157913404-9f4b436d-c450-459d-81c3-3883960a762a.png)

As you can see they are completely different.

My version of Android Studio: 
Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 1, 2022

Version of Flutter plugin: 65.2.2

**Comment by danagbemava-nc** [comment]
Hi @mivoligo, kindly see https://github.com/flutter/flutter-intellij/issues/5914#issuecomment-1021358549. 
It looks like you have to do the manual integration for now. 

We probably need to add a reference to this issue while it is still open.

**Comment by mivoligo** [comment]
@danagbemava-nc thank you for your response. :+1:

**Comment by stevemessick** [comment]
@sfshaza2 We should update the Flutter docs to clarify that add-to-app module creation must be done using the `flutter` tool. It is not supported by Android Studio now.

**Comment by atsansone** [comment]
@stevemessick : Is using `flutter` to make this change still recommended? If so, how can the developer do so? I can't find the information elsewhere. We would also need to update the main and iOS pages.

**Comment by stevemessick** [comment]
@atsansone Yes, this should be done using the `flutter` tool.

Instructions:
- https://docs.flutter.dev/add-to-app/android/project-setup#manual-integration
- https://docs.flutter.dev/add-to-app/ios/project-setup

However, it is possible to create the basic Flutter module using Android Studio. It isn't possible to have Android Studio do all the linking it used to do, which is covered in the links above. There's a screen shot of the UI at this link: https://github.com/flutter/flutter-intellij/issues/5914#issuecomment-1418648728
