### ISSUE TITLE
Building beautiful UIs with Flutter - Page 7 - Broken link

### ISSUE THREAD

**Issue by racouster** [flutter/website#6910]
On the CodeLab - [Building beautiful UIs with Flutter](https://codelabs.developers.google.com/codelabs/flutter#6)

The link on the text CrossAxisAlignment.start goes to https://api.flutter.dev/flutter/rendering/CrossAxisAlignment-class.html
which has content:
Page Not Found...

**Comment by danagbemava-nc** [comment]
Hi @racouster, thanks for reporing this

**Comment by danagbemava-nc** [comment]
Hi @racouster, why was this closed?

**Comment by parlough** [comment]
The links to this old codelab have been removed and the old codelab now redirects to the [new one](https://codelabs.developers.google.com/codelabs/flutter-boring-to-beautiful) which doesn't have this issue, so I'm going to close this, thanks!
