### ISSUE TITLE
Unify flutter.dev and docs.flutter.dev nav bar / hamburger menus

### ISSUE THREAD

**Issue by guidezpl** [flutter/website#6915]
### Describe the problem

- on desktop, the nav bars display the same content but with different styles

flutter.dev | docs.flutter.dev
--- | ---
<img width="1216" alt="Screen Shot 2022-03-14 at 23 27 04" src="https://user-images.githubusercontent.com/6655696/158271275-65c5e598-1678-4a3e-83c2-08f7235b39db.png"> | <img width="1216" alt="Screen Shot 2022-03-14 at 23 27 11" src="https://user-images.githubusercontent.com/6655696/158271258-bf300de0-3b34-48ec-ae57-8bbc374a216b.png">

- on mobile, the equivalent hamburger menus show different content, with different styles

flutter.dev | docs.flutter.dev
--- | ---
<img width="541" alt="Screen Shot 2022-03-14 at 23 25 43" src="https://user-images.githubusercontent.com/6655696/158271142-c26d1c03-37a4-41df-8a9c-789884189fff.png"> | <img width="541" alt="Screen Shot 2022-03-14 at 23 25 54" src="https://user-images.githubusercontent.com/6655696/158271130-6c48c719-008e-4372-9cc4-43995546c2f5.png">

 

### Expected fix

Possible solutions:
- Adopt flutter.dev nav bar on docs.flutter.dev
OR
- Scrap the nav bar entirely, keep the existing hamburger menu on mobile
OR 
- Just scrap the Docs link on docs.flutter.dev, which is redundant with the left-hand nav bar

**Comment by guidezpl** [comment]
Additional problem with the Development tab specifically

flutter.dev | docs.flutter.dev
--- | ---
<img width="275" alt="image" src="https://github.com/flutter/website/assets/6655696/f17f5ca5-55c6-4293-887e-bbb409257cc1"> |  <img width="165" alt="image" src="https://github.com/flutter/website/assets/6655696/16d042e3-241f-473c-882c-ce2ab8393fe2">

- missing items and different link destinations (e.g. `Flutter favorites`)
- some links take to an external site
  - `Packages` and `Flutter favorites` feel like they should be under ecosystem, and indicate if they're external links

**Comment by ulisseshen** [comment]
That I know, the main site flutter.dev isn't open-sourced. How could this be unified?

**Comment by atsansone** [comment]
It can't. Two separate groups manage these sites. Unifying nav across both wouldn't serve the purpose of either site.

**Comment by atsansone** [comment]
It can't. Two separate groups manage these sites. Unifying nav across both wouldn't serve the purpose of either site.

**Comment by guidezpl** [comment]
I'll note this is shipping an org chart. As a user of the site, navigation between these two sites is unfortunately confusing for this reason and https://github.com/flutter/website/issues/8999.

**Comment by parlough** [comment]
What do you mean by "shipping an org chart"?

I have some redesign work planned for the docs site that will likely scrap this navbar and make it more clear this is a separate docs experience from the marketing site. I don't think I have a specific issue tracking this yet, but I'll update this comment with a link to that.
