### ISSUE TITLE
applicationId vs appid

### ISSUE THREAD

**Issue by asashour** [flutter/website#6920]
### Page URL

https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration

### Page source

https://github.com/flutter/website/blob/main/src/deployment/android.md

### Describe the problem

In "Under the defaultConfig block" section, there is

>Specify the final, unique (Application Id)[appid](https://developer.android.com/studio/build/application-id)

One can notice that:
1. There is no space between `)` and `appid`
2. I wonder where the name `appid` came from, since the page referenced by the link simply says `application ID`

### Expected fix

>Specify the final, unique [application ID](https://developer.android.com/studio/build/application-id).

**Comment by micpap25** [comment]
Seems to be a formatting error, making a fix right now.
