### ISSUE TITLE
[PAGE ISSUE]: 'Work with cached images'

### ISSUE THREAD

**Issue by tlassis** [flutter/website#6921]
### Page URL

https://docs.flutter.dev/cookbook/images/cached-images/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/images/cached-images.md

### Describe the problem

the package "'package:cached_network_image/cached_network_image.dart';" is no longer available

**Comment by micpap25** [comment]
I can confirm this is happening; would that mean the pub.dev is incorrect as well, then?
https://pub.dev/packages/cached_network_image/install

**Comment by danagbemava-nc** [comment]
Hi @micpap25 @tlassis, I can't seem to reproduce. The code sample works just fine for me.

<details>
<summary>screenshots</summary>

| vscode | simulator |
| -- | -- |
| <img alt="Screenshot 2022-03-16 at 12 01 50" src="https://user-images.githubusercontent.com/88313112/158586092-03769258-4a56-48d1-b426-e46a35a037c9.png"> | <img src="https://user-images.githubusercontent.com/88313112/158586095-98cfb65c-2fcd-44fe-99f7-f82f3ed0625c.png" width="200"/> | 

</details>

**Comment by micpap25** [comment]
Hmm... I'm getting this issue in DartPad, which might be the problem?
![image](https://user-images.githubusercontent.com/34077605/158601946-0ee4cb94-342d-4a2b-a500-e3f43856b192.png)

**Comment by tlassis** [comment]
This is the issue for me. I don't know why it happens.

![untitled](https://user-images.githubusercontent.com/69312754/158617399-0abea88b-a854-4798-9966-a4f224dd48e5.png)

This is the message shown after hovering the cursor in the import line:

![untitled](https://user-images.githubusercontent.com/69312754/158618040-275bbb12-4ab1-4afa-b014-677b529ca2aa.png)

**Comment by tlassis** [comment]
I just found a way to solve this issue.
I needed to activate the Win11 Developer Mode and was able to solve the dependencies.

**Comment by danagbemava-nc** [comment]
@micpap25, yes that sounds like a good idea. This should probably be added to the windows install page, so new users see it during the setup phase.
