### ISSUE TITLE
Change "Set up an editor" to recommend "latest stable" version

### ISSUE THREAD

**Issue by micpap25** [flutter/website#6934]
### Page URL

https://docs.flutter.dev/get-started/editor/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/editor.md

### Describe the problem

As recommended by @sfshaza2 in #6860 
The "Set up an editor" page currently lists specific versions of editors which can become outdated if the page is left untouched for too long.

### Expected fix

Update the page to recommend the "latest stable" version of Android Studio / VSCode rather than a specific version which could become outdated.
We can use this issue to discuss how this might be implemented.

**Comment by atsansone** [comment]
@mariamhas : Do you know if declaring that devs should use the latest stable version of Android Studio is acceptable, preferred, or both?

**Comment by atsansone** [comment]
Emacs was set to "latest stable" in https://github.com/flutter/website/pull/3963.
VSCode was set to "latest stable" in https://github.com/flutter/website/pull/7532.

**Comment by mariamhas** [comment]
it is acceptable and preferred to use latest stable version of Android Studio! thanks
