### ISSUE TITLE
Mistake in tutorial in Google code labs

### ISSUE THREAD

**Issue by Dasein-hub** [flutter/website#6944]
On the 4th step, in the 2nd part of "Get started" tutorial on https://docs.flutter.dev/get-started/codelab, it says: "In the _buildRow function, add an alreadySaved check to ensure that a word pairing has not already been added to favorites", but there is no such function. 

I thought, maybe i missed something and just decided to copy the working code from the link on the bottom of the step, but i couldn't find the function there ether. 

What i did find is that you supposed to add additional code in the already existing _RandomWordsState return value and then it's gonna work.

Please, correct it.

**Comment by danagbemava-nc** [comment]
We apologize for any inconvenience this has caused you. This issue has already been reported in https://github.com/flutter/website/issues/6879 and it is being worked on. Kindly follow up in #6879. 

Closing as duplicate. Once again, sorry for any inconvenience.
