### ISSUE TITLE
Typo in Google Code Labs tutorial for Flutter

### ISSUE THREAD

**Issue by aswinsanakan** [flutter/website#6945]
There is a minor mistake in "[Write Your First Flutter App, part 2](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/)" > Step 6: "Navigate to new screen".

A tip section is given that says,
> Tip: Some widget properties take a single widget (child), and other properties, such as `action`, take an array of widgets (children), as indicated by the square brackets ([]).

Here, the property should be `actions` instead of `action` for the AppBar widget shown.

**Comment by danagbemava-nc** [comment]
<details>
<summary>screenshot</summary>

![Screenshot 2022-03-22 at 10 22 54](https://user-images.githubusercontent.com/88313112/159459617-d16383bc-de51-47ae-a863-b12c7af39f13.png)

</details>

**Comment by piedcipher** [comment]
@danagbemava-nc do you have link of the repo where I fix this issue?

**Comment by danagbemava-nc** [comment]
I do not have the link for the codelab, it might be internal 
/cc @domesticmouse

**Comment by domesticmouse** [comment]
@piedcipher It’s in a google doc and published through a google3 pipeline. Sorry, this content isn’t open source.

**Comment by parlough** [comment]
This codelab has been replaced by a the newly written [Your first Flutter app](https://codelabs.developers.google.com/codelabs/flutter-codelab-first) which doesn't have this issue. Check it out and let us know what you think!

Thanks again for opening the issue!
