### ISSUE TITLE
[PAGE ISSUE] Header navigation search module partially exposes form input when not activated (desktop)

### ISSUE THREAD

**Issue by AkshayBhimani** [flutter/website#6954]
### Page URL

https://flutter.dev/

### Describe the problem

Browser : Firefox - 98.0.1
Os: MacOS Monterey

--------------------------

![image](https://user-images.githubusercontent.com/49568856/159629717-d51fc526-da99-4c83-b06f-c7906aa5a5b5.png)
![image](https://user-images.githubusercontent.com/49568856/159631281-4d10957c-dd74-455f-9c1b-0ac60e5013b4.png)

Unexpected "S" is showing up with search button.  
I have viewed source and found out that it is placeholder for Search field and S which is showing up is part of "Search..."  placeholder. 

### Expected fix

Search button without showing placeholder "Search..." or show whole placeholder.

**Comment by parlough** [comment]
Thanks for reporting the issue @AkshayBhimani, I was able to reproduce this as well.

The form element is still there in Chrome as well, resulting in the text cursor when hovered, and the following when clicked:

<img width="331" alt="Screen Shot 2022-03-23 at 1 02 24 AM" src="https://user-images.githubusercontent.com/18372958/159634149-5d2ce8a3-ffe2-4a6d-90a4-d87142046d62.png">

We likely should have the form/input be `display: none` when the search bar isn't open and then normal when open.
