### ISSUE TITLE
[PAGE ISSUE]: 'Flutter for React Native developers'

### ISSUE THREAD

**Issue by adriank** [flutter/website#6959]
### Page URL

https://docs.flutter.dev/get-started/flutter-for/react-native-devs/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/flutter-for/react-native-devs.md

### Describe the problem

This page is outdated. Examples opened with Dartpad show errors related to null safety.

### Expected fix

Update the docs to null safe Dart.

**Comment by sfshaza2** [comment]
@khanhnwin

**Comment by parlough** [comment]
Thanks for opening an issue! @khanhnwin added code excerpts and updated the snippets in https://github.com/flutter/website/pull/7347 :D
