### ISSUE TITLE
Memory page has grammar issues

### ISSUE THREAD

**Issue by srawlins** [flutter/website#6965]
### Page URL

https://docs.flutter.dev/development/tools/devtools/memory

### Page source

https://github.com/flutter/website/blob/main/src/development/tools/devtools/memory.md

### DevTools memory page

* [ ] "Anaylsis" is misspelled.
* [x] "Allocations to monitor and track [...]" is not a function; maybe something like "Monitoring and tracking allocations" (in order to keep a consistent tense with the first item in the list

### Charting memory statistics and events

* [x] "At the top-level, when the memory tab is selected memory statistics from the VM are collected." I believe the two verb phrases need to be separate by a comma.
* [x] "These statistics are displayed in the two overview charts (Dart memory and Android-only) the collection of general memory usage e.g., total heap used, external heap, maximum heap capacity, Resident Set Size (RSS)." This is not a sentence; I cannot even guess at what is intended here.
* [x] "As you interact with your application various events are detected" I think again the two verb phrases need a comma.
* [x] "(garabage collection),Flutter events," missing space after comma
* [x] "e.g.," - [Don't use e.g.](https://developers.google.com/style/word-list#letter-e).
* [x] "All of this collected statistics and events are displayed in charts see Memory anatomy." Another missing comma.

### Analysis and snapshots

* [x] "A Snapshot is a complete, the most complex and time consuming view of all objects in the Dart memory heap." Also not a sentence... not sure what we're going for here.
* [x] "For example, loading large assets for thumbnail-sized images inefficiently, memory usage can be improved by loading smaller assets or adjusting the cacheWidth/cacheHeight to decode an image to a smaller size reducing the memory usage of the ImageCache." This is very long. Some word is needed before "loading," maybe "when"?
* [x] "The analysis catches issues like this see Analysis tab." Missing comma.

### Allocations and tracking

* [ ] "Monitoring all allocations involes you directly interacting with DevTools and your application to isolate a short period of time that you are interested in knowing how many objects were allocated, how many bytes were allocated, or tracking all the places in your code where a particular class is allocated." Very long sentence. "Involves" is misspelled. Uses an extra passive verb, "[Doing X] involves you interacting [...]".
* [x] "the “Allocations” tab of Memory profiler" should include "of the Memory profiler".
* [x] "and his a fairly fast with less overhead than using a snapshot." A noun is missing after "fast."
* [x] "If you suspect your application is leaking memory or has other bugs relating to memory allocation." This is not a sentence.
* [x] "Additionally, the ability to track a few specific classes, too many may slow the running of your application." This is not a sentence.
* [x] "[...] at the time a class’ constructor (allocation) is called." Should be "class's". And "(allocation)" should follow the word "called," not "constructor."

### Expected fix

The above changes

**Comment by parlough** [comment]
@sfshaza2 Is doing a large writing overhaul of this page at https://github.com/flutter/website/pull/6949 if you want to take a look at those in progress changes.

**Comment by sfshaza2** [comment]
Hey, @srawlins! Thanks for this feedback. Yes, this page needs improvements and I figured I'd attack them in an iterative process.

**Comment by srawlins** [comment]
Thanks to both of you!

**Comment by srawlins** [comment]
That's eerie, @sfshaza2. You pre-empted almost every comment I made above 🤣 . I left two undone, but the "passive verb" issue is obviously up to you. This can be closed after the last misspelling.

**Comment by sfshaza2** [comment]
It IS strange, @srawlins! It also tells me that you are quite a good writer! Hmmm...... How is it you've never written a blog post for Medium?  :D
