### ISSUE TITLE
Provide workaround for DartPad example for mouse movement on 'Create a horizontal list' page

### ISSUE THREAD

**Issue by nrallakis** [flutter/website#6978]
### Page URL

https://docs.flutter.dev/cookbook/lists/horizontal-list/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/lists/horizontal-list.md

### Describe the problem

After the breaking [changes](https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag) regarding ScrollBehaviors, it is not allowed (by default) to drag a scrolling widget with mouse drag.
As consequence, all Dart pad examples that contain a list do not scroll with mouse drag.
This is ok for vertical Lists/Grids that show a scrolling bar and scroll using the mouse's scroller.
However for horizontal Lists/Grids/PageView there is no horizontal scrollbar and shift+scroll doesn't work.

### Expected fix

One fix is to add ScrollConfiguration with PointerDeviceKind mouse, as discussed in the [migration ](https://docs.flutter.dev/release/breaking-changes/default-scroll-behavior-drag)guide to allow mouse drag scrolling.

It should at least be noted somewhere inside the examples because it is confusing for new users.

**Comment by danagbemava-nc** [comment]
Hi @nrallakis, can you file a new issue on the main `flutter` repo to report the issue with the PageView sample? The code for that lives in the framework and is maintained separately from the website code. 

We can then repurpose this issue for the example on https://docs.flutter.dev/cookbook/lists/horizontal-list. 

Thank you

**Comment by nrallakis** [comment]
Hi @danagbemava-nc ,
Sure no problem, I opened a new issue: https://github.com/flutter/flutter/issues/101381

**Comment by atsansone** [comment]
This was remedied in #9960 . Closing
