### ISSUE TITLE
[PAGE ISSUE]: "Firebase for Flutter Codelab link leads to 404" 

### ISSUE THREAD

**Issue by Chandram-Dutta** [flutter/website#6987]
### Page URL

https://flutter.dev/learn

### Describe the problem

The [Firebase for Flutter Codelab](https://codelabs.developers.google.com/codelabs/flutter-firebase]) link in intermediate level leads to a 404 page. 

### Expected fix

The link should lead to a valid Codelab Page

**Comment by danagbemava-nc** [comment]
Hi @Chandram-Dutta, thanks for reporting this. 

(Triage note:) To see the link in question, switch to the `Intermediate` tab and move to the firebase section. 
The link is highlighted in the screenshot below. 

<details>
<summary>screenshot</summary>

<img src="https://user-images.githubusercontent.com/88313112/161538105-6842e568-62b5-46a0-bd22-374c0b10e61c.png" width="500" />
</details>

**Comment by craiglabenz** [comment]
@domesticmouse Can you confirm that the codelab this intends to point to is (now?) found at https://firebase.google.com/codelabs/firebase-get-to-know-flutter ?

**Comment by domesticmouse** [comment]
Yup. I'll organise a redirect for the old path to the new path.

**Comment by domesticmouse** [comment]
For googlers: cl/439743072

**Comment by domesticmouse** [comment]
This should resolve in the next ten minutes or so
