### ISSUE TITLE
[PAGE ISSUE]: 'Flutter Tools Engineer'

### ISSUE THREAD

**Issue by dhruvilp** [flutter/website#6989]
### Page URL

https://docs.flutter.dev/jobs/tools/

### Page source

https://github.com/flutter/website/tree/main/src/jobs/tools.html

### Describe the problem

"Please apply at the [Google Careers site](https://careers.google.com/jobs/results/122913957812806342-senior-software-engineer-platforms-and-ecosystem-flutter/) and mention this page/URL in the Cover letter/other notes section."

Here, "Google Careers Site" is pointing to an incorrect job posting.

### Expected fix

Update the Google Careers Site for this job posting

**Comment by danagbemava-nc** [comment]
@tvolkert same as #6990

**Comment by tvolkert** [comment]
Yep, it should point to flutter.dev/go/job as well.

**Comment by parlough** [comment]
I'm going to close this issue as the job listing has been removed. Thanks again for reporting this!
