### ISSUE TITLE
[PAGE ISSUE]: 'Flutter Web Engineer'

### ISSUE THREAD

**Issue by dhruvilp** [flutter/website#6990]
### Page URL

https://docs.flutter.dev/jobs/engine_web/

### Page source

https://github.com/flutter/website/tree/main/src/jobs/engine_web.html

### Describe the problem

Please apply at the [Google Careers site](https://careers.google.com/jobs/results/122913957812806342-senior-software-engineer-platforms-and-ecosystem-flutter/) and mention this page/URL in the Cover letter/other notes section.

Here, "Google Careers site" is pointing to the incorrect job posting page.

### Expected fix

Fix the url

**Comment by danagbemava-nc** [comment]
@tvolkert Is the link that the job post is pointing to the right link?

**Comment by dhruvilp** [comment]
@tvolkert Hi, should I fill out this form in the meanwhile https://flutter.dev/go/job. Is it actively being used by Flutter/Dart team?

**Comment by tvolkert** [comment]
Hi @dhruvilp yes, it should be updated to go to https://flutter.dev/go/job

**Comment by parlough** [comment]
I'm going to close this issue as the job listing has been removed. Thanks again for reporting this!
