### ISSUE TITLE
Document How to embed  flutter into an existing SwiftUI project 

### ISSUE THREAD

**Issue by kevin-zhaotk** [flutter/website#6998]
I already have a swiftUI project, how can i embed my flutter module into this SwiftUI project?

**Comment by jmagman** [comment]
There's an example of how to do this in 
https://github.com/flutter/put-flutter-to-work/blob/022208184ec2623af2d113d13d90e8e1ce722365/newsfeed_ios/newsfeedApp/EndlessList.swift#L49-L56
and
https://github.com/flutter/put-flutter-to-work/blob/2efd25f4c0c0152b5e9ae9017e70dba8d9842cd2/newsfeed_ios/newsfeedApp/NewsfeedApp.swift#L11-L16

@hellohuanlin you did the cleanup in https://github.com/flutter/put-flutter-to-work/pull/101, this would be a good issue to get familiar with website documentation 🙂

**Comment by hellohuanlin** [comment]
@kevin-zhaotk does the example github project help? 

@jmagman yeah i think it's good idea to write up a doc. Assigned to myself
