### ISSUE TITLE
[PAGE ISSUE]: 'Flutter SDK releases'

### ISSUE THREAD

**Issue by muhammadrafid2a** [flutter/website#7007]
### Page URL

https://docs.flutter.dev/development/tools/sdk/releases/

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/sdk/releases.md

### Describe the problem

always loading and there no link

**Comment by danagbemava-nc** [comment]
Hi @muhammadrafid2a, can you check your console to see if there are any errors in there? 

I opened that page on my machine and everything loaded just fine. See screenshot below. 

<details>
<summary>screenshot</summary>

![Screenshot 2022-04-11 at 13 05 04](https://user-images.githubusercontent.com/88313112/162745493-72ee0723-972c-4416-92c6-69abe3cf28ab.png)

</details>
