### ISSUE TITLE
Topic request: web initialization 

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#7031]
### What information is missing?

Flutter now gives developers more control over the initialization of their web app using the new `flutter.js` and `_flutter.loader` API.  

### How would you like us to fix this problem?

We need to add @ditman's [doc](https://docs.google.com/document/d/1hImwEZvXzDmqhSlt3mSlU3uOTb7T_8GszQPur9P_NEM/edit?resourcekey=0-yyoB2x-amb-37iCDPP6IJw#) somewhere, probably under [development/tools](https://docs.flutter.dev/development/tools) and linked by [/web](https://docs.flutter.dev/web).

**Comment by kevmoo** [comment]
This makes more sense under 'platform integration' no?

**Comment by johnpryan** [comment]
I think we are going to make a parent directory at https://docs.flutter.dev/development/tools/web for this page and the [web renderers](https://docs.flutter.dev/development/tools/web-renderers) page.

**Comment by kevmoo** [comment]
@johnpryan – this seems a better spot: https://docs.flutter.dev/development/platform-integration/web

maybe move the FAQ somewhere else?

**Comment by ditman** [comment]
This is fantastic, thanks all for adding this documentation; I'll start pointing people to it!
