### ISSUE TITLE
[PAGE ISSUE] - Building a Cupertino App with Flutter Codelab

### ISSUE THREAD

**Issue by workerbee22** [flutter/website#7048]
### Page URL 
https://codelabs.developers.google.com/codelabs/flutter-cupertino#0

### Page Source
N/A

### Describe the Problem

Some links on this page are broken. See https://github.com/flutter/website/issues/7048#issuecomment-1102544041

### Expected Fix

Update the links.

**Comment by danagbemava-nc** [comment]
Hi @workerbee22, can you provide the link for the codelab with the broken links?

**Comment by workerbee22** [comment]
'widget library' == https://docs.flutter.io/flutter/widgets/widgets-library.html
'Material widgets' == https://docs.flutter.io/flutter/material/material-library.html
'Cupertino widgets' == https://docs.flutter.io/flutter/cupertino/cupertino-library.html

**Comment by domesticmouse** [comment]
Googlers: cl/442922351

**Comment by sfshaza2** [comment]
Fixed! Thanks, @domesticmouse and thanks @workerbee22 for reporting the broken links!
