### ISSUE TITLE
[PAGE ISSUE]: 'Display a snackbar'

### ISSUE THREAD

**Issue by sag333ar** [flutter/website#7054]
### Page URL

https://docs.flutter.dev/cookbook/design/snackbars/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/design/snackbars.md

### Describe the problem

while writing code, it says it's deprecated. Please update the documentation.

**Comment by danagbemava-nc** [comment]
Hi @sag333ar, what method/property is stated as deprecated in your code? 

I looked at the complete sample on that page and I don't see a deprecation message in the code.

**Comment by sag333ar** [comment]
@danagbemava-nc here are the screen-shots

![https://i.imgur.com/jnLZ8px.png](https://i.imgur.com/jnLZ8px.png)

![https://i.imgur.com/htrX5d2.png](https://i.imgur.com/jnLZ8px.png)

**Comment by danagbemava-nc** [comment]
Hi @sag333ar, the codelab you linked does not use `Scaffold.of(context).showSnackBar(snackbar)`. It uses `ScaffoldMessenger.of(context).showSnackBar(snackbar)` which is the new way to show snackbars.  

This is an issue with your code and not the code in the codelab. 

Closing this. 

Thank you
