### ISSUE TITLE
[PAGE ISSUE]: Flutter Puzzle Hack Winner wrong mentioned in "Community Choice - 3"

### ISSUE THREAD

**Issue by pratikbutani** [flutter/website#7059]
### Page URL

https://flutter.dev/events/puzzle-hack#:~:text=Community%20Choice%20%2D%203rd%20place

### Describe the problem

I won the [Flutter Puzzle Hackathon ](https://devpost.com/software/puzzlemania-zg9tnl) in category of **Community Choice** 

But as I found on flutter.dev website's event page that **Community Choice - 3** having a wrong name & logo. It's opening a right website by clicking on it.

I think it happed just because we both having a same name with a difference of space only.

Can you please change it? I can send the pics of mail if required. 

Please help. 

### Expected fix

It should be fixed as "PuzzleMania by Pratik Butani".

**Comment by danagbemava-nc** [comment]
Hi @pratikbutani, thanks for reporting this and sorry for any convenience

**Comment by pratikbutani** [comment]
> Hi @pratikbutani, thanks for reporting this and sorry for any convenience

Thank you for your reply @danagbemava-nc 

Hope it will be updated soon :)

**Comment by pratikbutani** [comment]
Its resolved :)
