### ISSUE TITLE
Typo in dartpad example on homepage

### ISSUE THREAD

**Issue by AJJB1** [flutter/website#7092]
In line 64 it's now.month instead of now.minute in this example:
https://dartpad.dev/?id=e66e420f2f0201c772f73819711bf290
I'm getting there via the Flutter.dev page when I click "try it in dartpad".

**Comment by danagbemava-nc** [comment]
Hi @AJJB1, thanks for the info. 

The link to the dartpad sample can be found in https://github.com/flutter/website/issues/7092#issue-1224039811. 

Given the context of the code, using `now.month` doesn't fit. Below is a screenshot of the link location on the flutter.dev homepage. 

<img src="https://user-images.githubusercontent.com/88313112/166454936-c48d2a49-1935-4e5f-86f6-93c6dfae0805.png" width="300" />

**Comment by johnpryan** [comment]
Hi @AJJB1, the [gist](https://gist.github.com/flutterdevrelgists/e66e420f2f0201c772f73819711bf290) you point to doesn't use `month`, so I suspect they might be local edits?

**Comment by AJJB1** [comment]
Hi, it was fixed. In your link check out Revisions. Line 64. Line 62 in the original.
