### ISSUE TITLE
`.ttc` is missing as supported font format in Coobook

### ISSUE THREAD

**Issue by nilsreichardt** [flutter/website#7097]
### Page URL

https://docs.flutter.dev/cookbook/design/fonts#supported-font-formats

### Describe the problem

Regarding https://github.com/flutter/flutter/pull/77230#discussion_r587958649, Flutter supports also `.ttc` file formats.

### Expected fix

Add `.ttc` as supported file format

**Comment by nilsreichardt** [comment]
I can fix this, when PR are allowed again.

**Comment by micpap25** [comment]
It seems like @davidmigloz fixed the issue with this commit: https://github.com/flutter/website/commit/5a6bf7e996cedcbad5bc72fba3967becc59bd7d3

**Comment by nilsreichardt** [comment]
Yes, you are right, @micpap25.

Closing this ticket because it was implemented in #7109.
