### ISSUE TITLE
[PAGE ISSUE]: 'Set up an editor'

### ISSUE THREAD

**Issue by devalexd** [flutter/website#7102]
### Page URL

https://docs.flutter.dev/get-started/editor/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/editor.md

### Describe the problem

A typo found, under the section"Install the Flutter and Dart plugins" / "Linux or Windows"
Original:`WIndows`
Should be: `Windows`

### Expected fix

Inside the sentence: "Use the following instructions for Linux or WIndows:", change `WIndows` to `Windows`

**Comment by devalexd** [comment]
Expect a quick fix of this line: https://github.com/flutter/website/blob/main/src/get-started/editor.md?plain=1#L70

**Comment by micpap25** [comment]
It seems this has been fixed, this issue can be closed
