### ISSUE TITLE
Note that `path_provider` as no web support on 'Read and write files' page

### ISSUE THREAD

**Issue by isanecat** [flutter/website#7105]
### Page URL

https://docs.flutter.dev/cookbook/persistence/reading-writing-files/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/persistence/reading-writing-files.md

### Describe the problem

It is written on documents as follows: 

"The [path_provider](https://pub.dev/packages/path_provider) package provides a platform-agnostic way to access commonly used locations on the device’s file system."

but there is no web support.

**Comment by darshankawar** [comment]
may be related to https://github.com/flutter/website/issues/7072

**Comment by atsansone** [comment]
This duplicates https://github.com/flutter/website/issues/5596. Closing this issue.
