### ISSUE TITLE
[PAGE ISSUE]: 'Security'

### ISSUE THREAD

**Issue by TheLifeIsYours** [flutter/website#7110]
### Page URL

https://docs.flutter.dev/security/

### Page source

https://github.com/flutter/website/tree/main/src/security/index.md

### Describe the problem

Link to discord under [receiving security updates](https://docs.flutter.dev/security#receiving-security-updates) needs to be an invite link to the discord, instead of a direct url to the channel in question. I ended up just staying on an infinite loading screen in discord, either because that channel was deleted or possibly because you can't navigate directly to a channel without being a member of that server.

### Expected fix

Switch out the channel link <https://discord.com/channels/608014603317936148/608116355836805126> to be the discords invite link <https://discord.com/invite/N7Yshp4>

**Comment by micpap25** [comment]
On it!
