### ISSUE TITLE
Side Navigation Link Not Focusing

### ISSUE THREAD

**Issue by Bkohler93** [flutter/website#7115]
### Page URL

https://docs.flutter.dev/development/packages-and-plugins/happy-paths/recommended

### Describe the problem

When on the "Happy paths recommendations" page the "Happy paths project NEW" link is focused (colored blue) in the side navigation instead of the "Happy paths recommendations NEW" link.

### Expected fix

Set "Happy paths recommendations NEW" link to active when on its corresponding page.

**Comment by micpap25** [comment]
On it!

**Comment by micpap25** [comment]
So, I think fixing this issue will require migrating the content from `/happy-paths/recommended` to a URL that is outside of the `/happy-paths` path. Something like `/happy-paths-recommended`.

**Comment by Bkohler93** [comment]
The side navigation is now focusing on the correct link.
