### ISSUE TITLE
Fix use of BuildContext across async gaps on 'Return data from a screen' page

### ISSUE THREAD

**Issue by cnkygmr** [flutter/website#7134]
### Page URL

https://docs.flutter.dev/cookbook/navigation/returning-data/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/navigation/returning-data.md

### Describe the problem

line 53 • Do not use BuildContexts across async gaps.

**Comment by atsansone** [comment]
@cnkygmr : Could you provide more detail? Without context of a code example, we won't know what to change.
