### ISSUE TITLE
[PAGE ISSUE]: 'macOS install'

### ISSUE THREAD

**Issue by tomjdickson** [flutter/website#7137]
### Page URL

https://docs.flutter.dev/get-started/install/macos/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/macos.md

### Describe the problem

Docs are describing that MacOS M1 / ARM users require Rosetta however Flutter now provides stable release for amr64:
<img width="745" alt="image" src="https://user-images.githubusercontent.com/44155439/168505408-309c9fc0-b106-415c-af6c-fa4f10fb1c2b.png">

### Expected fix

Remove the notice.

**Comment by timsneath** [comment]
Per conversation in #7139, this is still necessary for some small ancillary tools.
