### ISSUE TITLE
Building Windows apps with Visual Studio

### ISSUE THREAD

**Issue by timsneath** [flutter/website#7138]
### What information is missing?

The documentation assumes that you're doing all Windows builds with `flutter build windows`. In a real, more complex project, you may be using `cmake` or opening the solution with Visual Studio to add additional files or edit the runner. We should document this. 

@sebastianhaberey brought this to our attention here: https://github.com/flutter/flutter/issues/103731 when he was struggling with successfully building from Visual Studio 2022. I agree with him: this isn't intuitive, with a number of CMake files and `.sln` or `.vcxproj` files floating around the generated directories.

### How would you like us to fix this problem?

I suspect we need a dedicated page for each of the main desktop platforms that covers the same ground as the "add to app" pages on iOS and Android, along with other special topics. The desktop page (https://docs.flutter.dev/desktop) probably needs to keep the initial material, but the later topics should be broken out into subpages, and then this material would be incorporated into the Windows page.

**Comment by sebastianhaberey** [comment]
Naturally, I agree with the need for more documentation here 🙂 When I started exploring the Windows side of Flutter, I followed the instructions [here](https://docs.flutter.dev/get-started/install/windows) and the page you mentioned above, but there is definitely a documentation gap from there to being able to run / debug the project in VS 2022.

**Comment by sebastianhaberey** [comment]
@timsneath sorry to bring this up again, but after I finished the windows side of things, I'm having exactly the same issue on linux now. I'm trying to open the folder `foo/example/linux` in VS Code and building / running it via CMake, but it fails. 

To be honest, I have no idea whether this is the right approach, but I couldn't find any documentation on this. Should I open an issue for this? Or did I just not look long enough?

**Comment by timsneath** [comment]
Hmm. @kenvandine might be the right person to comment here. 

Ken, we recently updated the docs with https://docs.flutter.dev/desktop/windows#compiling-with-visual-studio for Windows. I wonder if we need a similar section for https://docs.flutter.dev/desktop/linux?

**Comment by sebastianhaberey** [comment]
Thanks! I filed an [issue](https://github.com/flutter/flutter/issues/104581) where you can see what I'm trying to do.

**Comment by kenvandine** [comment]
> Hmm. @kenvandine might be the right person to comment here.
> 
> Ken, we recently updated the docs with https://docs.flutter.dev/desktop/windows#compiling-with-visual-studio for Windows. I wonder if we need a similar section for https://docs.flutter.dev/desktop/linux?

I see there's been some more discussion on the new issue that was created, if needed please feel free to tag me in there.
