### ISSUE TITLE
[PAGE ISSUE]: 'Customizing web app initialization'

### ISSUE THREAD

**Issue by pbx9959** [flutter/website#7142]
### Page URL

https://docs.flutter.dev/development/platform-integration/web/initialization/

### Page source

https://github.com/flutter/website/tree/main/src/development/platform-integration/web/initialization.md

### Describe the problem

says "by running flutter create"

### Expected fix

should explicitly state "by running flutter create <your project name>

**Comment by sfshaza2** [comment]
??? Can you clarify your meaning?

**Comment by pbx9959** [comment]
Hi, sorry I misread the statement and missed the "." which is there and was just trying "flutter create", I should have just used the Copy button :-(Regards Phil
flutter create .
    On Tuesday, 17 May 2022, 08:52:05 GMT+12, Shams Zakhour (ignore Sfshaza) ***@***.***> wrote:  
 
 


??? Can you clarify your meaning?
