### ISSUE TITLE
Combine or cross-link splash screen related pages

### ISSUE THREAD

**Issue by guidezpl** [flutter/website#7151]
### Page URL

https://docs.flutter.dev/development/ui/advanced/splash-screen

### Describe the problem

Should either move https://docs.flutter.dev/development/platform-integration/web/initialization to it, or link to it

**Comment by micpap25** [comment]
I can get to working on this; I think the best approach would be to create an `app-initialization` page at `/ui/advanced/app-initialization` which combines the content of the two pages. Then we would just delete the original two.

**Comment by guidezpl** [comment]
@sfshaza2 thoughts?

**Comment by sfshaza2** [comment]
Hi, @guidezpl! Actually, I don't see merging these two pages into one page. The web page is specifically for web. The splash screen page is specifically for iOS and Android. I'd prefer to update the web page to include the splash screen scenario. What are your thoughts, @johnpryan?

**Comment by guidezpl** [comment]
I had this idea because I was looking for information about splash screens for web and desktop platforms, and SEO got me to https://docs.flutter.dev/development/ui/advanced/splash-screen. It took me some time to find  https://docs.flutter.dev/development/platform-integration/web/initialization.

**Comment by sfshaza2** [comment]
Ahhh. Well, it sounds like we can add some useful tabs and also cross link these pages.

**Comment by camsim99** [comment]
Closing as this was fixed in the merged PR above.
