### ISSUE TITLE
[PAGE ISSUE]: 'Work with long lists'

### ISSUE THREAD

**Issue by derappelt** [flutter/website#7170]
### Page URL

https://docs.flutter.dev/cookbook/lists/long-lists/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/lists/long-lists.md

### Describe the problem

The whole Demo freezes when I try to use the scrollbar handle to scroll a decent amount.
I've the same problem in a Linux desktop app I'm building with flutter.  

### Additional context

UserAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36'

**Comment by danagbemava-nc** [comment]
Hi @derappelt, this seems like an issue for the main flutter repo. 

Kindly file a new issue on the main flutter repo and provide the relevant information required to reproduce this. 

Thank you
