### ISSUE TITLE
[PAGE ISSUE]: 'Adding Flutter to Android'

### ISSUE THREAD

**Issue by fhsbatista** [flutter/website#7172]
### Page URL

https://docs.flutter.dev/development/add-to-app/android/

### Page source

https://github.com/flutter/website/tree/main/src/development/add-to-app/android/index.md

### Describe the problem

The page is empty

**Comment by sfshaza2** [comment]
@khanhnwin, this page IS empty (as is the markdown file). Many of our index pages are auto-generated and this appears to be one of those. Can you take a look?

**Comment by khanhnwin** [comment]
Looking!

**Comment by khanhnwin** [comment]
Merged and Fixed!
