### ISSUE TITLE
"Friendly Chat" tutorial replaced with "Boring to Beautiful" on Codelabs

### ISSUE THREAD

**Issue by fentras** [flutter/website#7190]
### Page URL

https://codelabs.developers.google.com/codelabs/flutter

### Describe the problem

Yesterday I was working on a **Frendly Chat** tutorial located at [codelabs/flutter](https://codelabs.developers.google.com/codelabs/flutter). Today I wanted to continue working on it but was introduced to a completely new tutorial named **Boring to Beatuful**. There are still links that lead to the old tutorial at [codelabs/first-flutter-app-pt2#8](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#8) and [github/friendly_chat](https://github.com/flutter/codelabs/tree/master/friendly_chat).

### Expected fix

- Bring back the old tutorial on **Codelabs**
- Fix the description at [codelabs/first-flutter-app-pt2#8](https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2#8)
  - *…dive deeper into Flutter by creating ~~a simple chat application~~…*
- Add a link to the old tutorial at [github/friendly_chat](https://github.com/flutter/codelabs/tree/master/friendly_chat)

### Additional context

The new tutorial is way better, especially with the migration to _Material 3_ but it's also way harder than the previous one, so it would be good to still have the old tutorial on _Codelabs_.

**Comment by sfshaza2** [comment]
Yes, we have deprecated that codelab. It was the oldest codelab in our stable and had been completely rewritten (by me) once.

@khanhnwin, I'm raising this to your attention, in case you have thoughts or ideas.
