### ISSUE TITLE
[PAGE ISSUE]: 'Integrate a Flutter module into your Android project'

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#7196]
### Page URL

https://docs.flutter.dev/development/add-to-app/android/project-setup/

### Page source

https://github.com/flutter/website/tree/main/src/development/add-to-app/android/project-setup.md

### Describe the problem

Screenshots do not apply - New Module wizard looks completely different.

### Expected fix

Flutter module should be an option

### Additional context

I tried electric eel and chipmunk

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of #6905
