### ISSUE TITLE
'윈도우에서 설치' page issue

### ISSUE THREAD

**Issue by dlrbghdlrbgh** [flutter/website#7204]
Page URL: https://flutter-kr.io/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:

download flutter.zip link in flutter korean page does not work.

https://flutter-ko.dev/docs/get-started/install/windows#flutter-sdk-%EB%8B%A4%EC%9A%B4%EB%A1%9C%EB%93%9C
**please check this link**

**Comment by danagbemava-nc** [comment]
Hi @dlrbghdlrbgh, the flutter-kr site is community-maintained and we don't know which members of the community maintain it so unfortunately, we cannot do anything about this. 

Closing this as the site is community-maintained.
