### ISSUE TITLE
[PAGE ISSUE]: 'Build and release a macOS app'

### ISSUE THREAD

**Issue by mmattes** [flutter/website#7211]
### Page URL

https://docs.flutter.dev/deployment/macos/

### Page source

https://github.com/flutter/website/tree/main/src/deployment/macos.md

### Describe the problem

In Create a build archive with Codemagic CLI tools Point 13. Package the App the following code snipped is mentioned. But jq '.[0] only selects the first entry in the keychain which does not need to be the one with the common_name containing "Mac Developer Installer"

```
APP_NAME=$(find $(pwd) -name "*.app")
PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg
xcrun productbuild --component "$APP_NAME" /Applications/ unsigned.pkg

INSTALLER_CERT_NAME=$(keychain list-certificates \
          | jq '.[0]
            | select(.common_name
            | contains("Mac Developer Installer"))
            | .common_name' \
          | xargs)
xcrun productsign --sign "$INSTALLER_CERT_NAME" unsigned.pkg "$PACKAGE_NAME"
rm -f unsigned.pkg 
```

### Expected fix

Changing it to jq '.[] will iterate over the whole array and will find the right certificate no matter if it is the first or second. 

```
APP_NAME=$(find $(pwd) -name "*.app")
PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg
xcrun productbuild --component "$APP_NAME" /Applications/ unsigned.pkg

INSTALLER_CERT_NAME=$(keychain list-certificates \
          | jq '.[]
            | select(.common_name
            | contains("Mac Developer Installer"))
            | .common_name' \
          | xargs)
xcrun productsign --sign "$INSTALLER_CERT_NAME" unsigned.pkg "$PACKAGE_NAME"
rm -f unsigned.pkg 
```

**Comment by MiraMarshall** [comment]
Closing, this issue has been fixed.
