### ISSUE TITLE
Security and Flutter Output

### ISSUE THREAD

**Issue by timsneath** [flutter/website#7215]
### What information is missing?

We occasionally have customers probing us for information on the security of the generated Flutter app.

Our output includes mitigations against certain attack surfaces. For example: 

- We mark libraries produced with the NX flag (Dart does not need executable stacks): https://dart-review.googlesource.com/c/sdk/+/241540

Conversely, we see [false reports or confusion](https://github.com/flutter/flutter/issues/49801#issuecomment-627865908) about mitigations that are not applicable for Dart code. For example:

- Some developers see ask about things like stack canaries in AOT-compiled code, based off their experience with other languages. Unlike C++ we don't really have stack allocated arrays (primary source of stack smashing in C/C++). In general there are no stack allocated buffers in Dart code so stack canaries are not a meaningful mitigation. 
- Similarly, we've seen that some tools incorrectly report Dart AOT compiled code as "no-RELRO" due to very hacky ways of detection. In reality Dart AOT compiled code does not even use GOT/PLT.

Note that in general when you write pure Dart (and don't use dart:ffi) - you already have much stronger isolation guarantees than any C++ mitigation can provide - simply because pure Dart code is managed language, so things like buffer overruns do not exist.

### How would you like us to fix this problem?

Since this comes up occasionally it may be worth documenting it somewhere on [flutter.dev](http://flutter.dev/) or [dart.dev](http://dart.dev/). (Not in a defensive way, just as a "here are some examples of things we do for security, and here are some common errors that some tools make when inspecting Dart's output".)

**Comment by Hixie** [comment]
@sfshaza2 is landing a document for this on our web site which should be out next week.

**Comment by parlough** [comment]
https://docs.flutter.dev/resources/security-false-positives has landed and is linked to from the security page and sidebar. Let us know if there's something else that should be added.
