### ISSUE TITLE
[PAGE ISSUE]: 'Using Flutter in China'

### ISSUE THREAD

**Issue by cnmade** [flutter/website#7219]
### Page URL

https://docs.flutter.dev/community/china/

### Page source

https://github.com/flutter/website/tree/main/src/community/china.md

### Describe the problem

The current download link is still 1.0

### Expected fix

Change the link to the latest version of flutter.

**Comment by parlough** [comment]
These links aren't intended to be used to download Flutter, but rather as an example of what they will look like, as this is just a Windows download anyway. 

I've gone ahead and updated the example to use the modern version syntax and a recent stable version though: https://github.com/flutter/website/commit/2fc1763e371546f71a3eb212334ead5a8fa2de34

Thanks!
