### ISSUE TITLE
[PAGE ISSUE]: 'Flutter 3.0.0 release notes'

### ISSUE THREAD

**Issue by litang0908** [flutter/website#7222]
### Page URL

https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0/

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/sdk/release-notes/release-notes-3.0.0.md

### Describe the problem

```
[flutter_tool] Adds –enable-impeller flag to the run command by @zanderso in
```

The command should be ``` --enable-impeller ``` , not just lost one ``` - ``` , but the first ```-``` is wrong (```–```)

### Expected fix

```
[flutter_tool] Adds --enable-impeller flag to the run command by @zanderso in
```

**Comment by litang0908** [comment]
The wrong command in docs is:
—-enable-impeller 

But it should be:
--enable-impeller 

It's hard to find the difference in Markdown

**Comment by UsamaKarim** [comment]
It might look different to you on your computer but it's totally fine for me.

**Comment by danagbemava-nc** [comment]
I think this is an issue with the display of the double dash as the source the page displays it properly

![Screenshot 2022-06-03 at 11 39 59](https://user-images.githubusercontent.com/88313112/171846776-cae10ded-2acd-4a1e-8cb0-73ee8f28a536.png)
