### ISSUE TITLE
Mobile Navbar doc items overlaps with the Searchbar 

### ISSUE THREAD

**Issue by Paul-005** [flutter/website#7224]
### Describe the problem

In the responsive navbar when we toggle the menu items we can scroll the list. But when we toggle accordion eg Docs it lists down some items. But when we scroll those items it will overlap with the search bar.
 

### Expected fix

Make the search bar appear above the lists.

### Additional context

![Screenshot_20220603-224828_Trebuchet](https://user-images.githubusercontent.com/70139728/171914363-4d1f3f6c-e970-4e7a-a8f3-b9b26dbcdd33.png)

We can see that items go above the search bar.

**Comment by danagbemava-nc** [comment]
From triage: how to see the issue

https://user-images.githubusercontent.com/88313112/172164584-8c94f2a6-8d9a-4d69-b0f1-6e6b587933d3.MP4
