### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by johnaziz57** [flutter/website#7236]
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

In Step 4 Create an infinite scrolling ListView https://docs.flutter.dev/get-started/codelab#step-4-create-an-infinite-scrolling-listview 
It seems that the 2nd point starts a bit later than it should be

> 1. Add a _suggestions list to the _RandomWordsState (Adding suggestion)
>        Next, you’ll add a ListView widget to the _RandomWordsState 
> ..... ( a lot of description about how ListView will behave, all of this part of step 1 that doesn't make sense)
> 2.  Return a ListView widget from the build ... (The actual step to add the list view)

### Expected fix

> 1. Add a _suggestions list to the _RandomWordsState (Adding suggestion)
> 2. Next, you’ll add a ListView widget to the _RandomWordsState 

### Additional context

I assumed this is the logical order. I apologise in advance if this was intentional 🙇

**Comment by danagbemava-nc** [comment]
Hi @johnaziz57, I think the `Next` statement was adding an explanation of what the next step will be, so in that sense, this might be the right ordering of the steps. 

cc @domesticmouse for more insight on this

**Comment by domesticmouse** [comment]
Hi @parlough, do you have time to take a pass at this? I suspect the paragraphs need some re-ordering?
