### ISSUE TITLE
Provide detailed information on Firebase support for Flutter and a Crashlytics section on 'Firebase' page

### ISSUE THREAD

**Issue by kkboateng** [flutter/website#7238]
### Page URL

https://docs.flutter.dev/development/data-and-backend/firebase

### Describe the problem

Part of the partnership between Firebase and Flutter includes delivering world-class Firebase Crashlytics support for Flutter by enhancing critical user journeys, strengthening core functionality, and improving documentation.  

This is a request to revisit the firebase documentation page in an effort to give developers more relevant information on the ways that they can take advantage of the ways that Fluter and Firebase work together.

**Comment by atsansone** [comment]
Related to https://github.com/flutter/website/issues/2315.

**Comment by ericwindmill** [comment]
Similar to #2315, I don't think this is worth our time today or future maintenance load. Now that Flutter is officially supported by Firebase, there are thorough and top-notch docs available.
