### ISSUE TITLE
[PAGE ISSUE]: DARK MODE 

### ISSUE THREAD

**Issue by chanjamoka** [flutter/website#7251]
### Page URL

https://docs.flutter.dev/development/ui/widgets-intro/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/widgets-intro.md

### Describe the problem

Can you please introduce a dark mode

### Expected fix

Intoduce a dark mode widget

**Comment by danagbemava-nc** [comment]
Hi @chanjamoka, I'm not sure I understand what your request is. 

Can you provide a little bit more information as to what exactly you want? 

If you want widgets to use dark mode, you can do that by defining themes for dark mode.

**Comment by Zerotask** [comment]
I assume he wants to have a switch on the website to activate a dark mode (for either the complete website and / or code snippets) since the current website is pretty bright
