### ISSUE TITLE
Document how to build and distribute Flutter apps with Xcode Cloud continuous integration

### ISSUE THREAD

**Issue by see** [flutter/website#7259]
Please provide documentation on how to distribute Flutter apps using Xcode cloud

**Comment by jmagman** [comment]
Thanks for all the details @Diizzayy, I didn't realize installing Flutter in their CI was possible.

I transferred this issue to flutter/website, this would be a great addition to https://docs.flutter.dev/deployment/cd.

**Comment by Diizzayy** [comment]
> Thanks for all the details @Diizzayy, I didn't realize installing Flutter in their CI was possible.

No problem at all, it took me about about a hour to figure it all out so I’m happy to share.

> I transferred this issue to flutter/website, this would be a great addition to https://docs.flutter.dev/deployment/cd.

@jmagman That’s a great idea, I’ll improve upon the details and make the PR to have Xcode Cloud added to the continuous deployment docs

**Comment by domesticmouse** [comment]
> > Thanks for all the details @Diizzayy, I didn't realize installing Flutter in their CI was possible.
> 
> No problem at all, it took me about about a hour to figure it all out so I’m happy to share.
> 
> > I transferred this issue to flutter/website, this would be a great addition to https://docs.flutter.dev/deployment/cd.
> 
> @jmagman That’s a great idea, I’ll improve upon the details and make the PR to have Xcode Cloud added to the continuous deployment docs

Please tag me on the PR as I'll be initial review before @jmagman and @sfshaza2 =)

**Comment by esodot** [comment]
Tried out the documentation steps today. 
An important command in the **ci_post_clone.sh** file seems to be missing. 
Not running the **flutter build ios --no-codesign** will not respect the version number from the pubspec.yaml and fail to create a proper archive. 

Additional: 
flutter build ios --no-codesign

Also missing:

_# Set the -e flag to stop running the script in case a command returns
# a nonzero exit code.
set -e_

**Comment by jmagman** [comment]
@esodot can you file a new issue at https://github.com/flutter/flutter/issues/new/choose? That sounds like a bug with `flutter build ios` or the way your app is set up, not these instructions.  

It should use what's in the pubspec.  Generated.xcconfig should generate two build settings based on your pubspec version:

```
FLUTTER_BUILD_NAME=1.0.0
FLUTTER_BUILD_NUMBER=1
```
Which are used in the app's Info.plist:
<img width="593" alt="Screenshot 2022-12-22 at 11 57 48 AM" src="https://user-images.githubusercontent.com/682784/209216101-b519e937-4292-459d-a1c8-dfc4a1b35e52.png">

**Comment by esodot** [comment]
@jmagman thats sadly not the case. My app is set up properly and i can always build with "flutter build ios" to get the right version e.g 1.0.0 and the build number e.g 10. Using the workflow from xcode cloud the workflow not using the build number set by flutter at all. What happens is that only the xcode cloud internal build number (Under Appconnect -> Xcode cloud -> settings -> build number) will be used and increases with every build. Means i am currently completely ignore the pattern 1.0.0+10 in my pubspec.yaml and the build works with 1.0.0 (11), 1.0.0 (12) and so on.

**Comment by esodot** [comment]
@jmagman Regarding the documentation, as you mention the command "flutter build ios" is needed to set the values into the Info.plist of $(FLUTTER_BUILD_NAME) and $(FLUTTER_BUILD_NUMBER). But this command is not part of the documentation script file https://docs.flutter.dev/deployment/cd#post-clone-script.
So if someone will use it it will fail. Thank you

**Comment by jmagman** [comment]
> @jmagman Regarding the documentation, as you mention the command "flutter build ios" is needed to set the values into the Info.plist of FLUTTER_BUILD_NAME and FLUTTER_BUILD_NUMBER. But this command is not part of the documentation script file https://docs.flutter.dev/deployment/cd#post-clone-script.

`flutter pub get` would also generate those settings, which the script does include.

>  Using the workflow from xcode cloud the workflow is not using the build number set / generated by flutter (or set in Info.plist) at all. What happens is that only the xcode cloud internal build number (Under Appconnect -> Xcode cloud -> settings -> build number) will be used and increases with every build.

That sounds like a limitation of deploying with `xcode cloud internal build number` then, and would happen no matter what you had set in your Info.plist, whether or not it's a Flutter app.

Can you please file a new issue, even if you think it's a matter of improving the documentation?  Commenting in a close issue isn't a good way to keep track of this.

**Comment by esodot** [comment]
Yes sure thank you, i didn't want to open the new case too fast. 
Thanks very much for clarification on `flutter pub get`, i was not aware that this command also generates those settings. 
I have no issues with the documentation now. All fine. Cheers

**Comment by amrgetment** [comment]
@domesticmouse 
Create workflow is in Integrate Menu, not Product menu
<img width="213" alt="image" src="https://github.com/flutter/website/assets/149420647/6e87f0f1-9ee1-45d8-8cb2-409940751e5f">
<img width="734" alt="image" src="https://github.com/flutter/website/assets/149420647/1bbee46c-5a36-4896-869a-91ae21116650">

**Comment by lukehutch** [comment]
@Diizzayy I used your `ci_post_clone.sh` script (which is now in the Flutter official docs). However, Xcode Cloud builds fail with:

* Error: This bundle is invalid. The value for key CFBundleShortVersionString '$(FLUTTER_BUILD_NAME)' in the Info.plist file at 'Payload/Runner.app/Frameworks/App.framework' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring
* Error: This bundle is invalid. The value for key CFBundleVersion [$(FLUTTER_BUILD_NUMBER)] in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion
* Error: This bundle Payload/Runner.app/Frameworks/App.framework is invalid. The value for key CFBundleVersion [$(FLUTTER_BUILD_NUMBER)] in the Info.plist file must be no longer than 18 characters. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion

However `flutter run` works. So there seems to be some step missing, that is run by `flutter run` but not this script, to replace these variables with the actual correct values before the Xcode Cloud build is started.

**Comment by jmagman** [comment]
@lukehutch can you file a new issue, and include: 
1. when you `flutter run` locally can you see the right values in the app's Info.plist?
2. are you using flavors?

**Comment by najibkr** [comment]
Is there a way to **obfuscate Flutter iOS and MacOS apps** when building and deploying with **Xcode Cloud**?
My apps deploys just fine with Xcode Cloud CI, but I have not found a way to obfuscate my apps for MacOS and iOS.
