### ISSUE TITLE
[PAGE ISSUE]: 'Android v1 embedding app and plugin creation deprecation'

### ISSUE THREAD

**Issue by parvanovp** [flutter/website#7267]
### Page URL

https://docs.flutter.dev/release/breaking-changes/android-v1-embedding-create-deprecation/

### Page source

https://github.com/flutter/website/tree/main/src/release/breaking-changes/android-v1-embedding-create-deprecation.md

### Describe the problem

There's a link on the page, to a Migration guide from Android embedding v1 to v2, but the page the link points at is removed. And links to that same page still exist at many places, including the link that the last stable version of Android Studio shows when an issue with the deprecated v1 embedding arises.

### Expected fix

The Migration guide should be put back at the URL what many places point at, or at least there should be a link, pointing at its new address, in case it was moved or if there's some new development, concerning the case.

**Comment by danagbemava-nc** [comment]
The link in question is highlighted below.  The same link is found at the end of the page. 

<img src="https://user-images.githubusercontent.com/88313112/173823004-14289536-4c5c-403d-b6fb-2bdda57b944d.png" width="400"/>
