### ISSUE TITLE
Verify that examples on 'Pass arguments to a named route' page are null safe

### ISSUE THREAD

**Issue by cnmade** [flutter/website#7268]
### Page URL

https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/navigation/navigate-with-arguments.md

### Describe the problem

The document show example may be not null safety

### Expected fix

Add null safety check passing arguments.

**Comment by danagbemava-nc** [comment]
Hi @cnmade, what part of the cookbook do you think is not null safe?

**Comment by cnmade** [comment]
For real world app powered by flutter, we may have two scene
1. may pass arguments
2. may not pass arguments or pass null

My real world code looks like 

<img width="834" alt="image" src="https://user-images.githubusercontent.com/278153/173838919-7d9ec242-13b3-4634-a26e-73666c634b41.png">


If scene 1 , we pass arguments, then we can got args , and it has values.

If scene 2, we have null , args == null, we should using default value to display varaible.

**Comment by cnmade** [comment]
I thought the document should cover more real world. 
May the passing argument be null ? how can we handle with Null ?
Document should provided good example to show the power.

**Comment by danagbemava-nc** [comment]
I think I get your point, but for the record, the example is null-safe. 

Improving the example to show how to handle/deal with missing/null parameters may be good overall for beginners.

**Comment by cnmade** [comment]
The document told us:

```
1 + 1 = 2
```

The real world case:

![image](https://user-images.githubusercontent.com/278153/174085440-0518e2bc-1632-480f-840e-da2cf66e4908.png)

me be like:

![image](https://user-images.githubusercontent.com/278153/174085983-b05fa7c5-5ea1-4fd3-85eb-fd715009c2f1.png)

**Comment by atsansone** [comment]
These examples are null safe. Closing this issue.
