### ISSUE TITLE
[PAGE ISSUE]: 'Create an expandable FAB'

### ISSUE THREAD

**Issue by EnduringBeta** [flutter/website#7270]
### Page URL

https://docs.flutter.dev/cookbook/effects/expandable-fab/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/effects/expandable-fab.md

### Describe the problem

2 issues:

* The DartPad example has an info-level issue that covers the expanded FAB, so it's actually a bit disruptive.
* The action button icons are the same color as the action buttons themselves.

### Expected fix

* Fix the issue by removing the `_` before the state class name in all instances
* Change the icon color in the action buttons to use `onSecondary` instead of `secondary`, so they show up white on blue

### Additional context

I already have a branch with these changes. I updated the `*.md` file and the individual `*.dart` files. I haven't run any of the code myself except to confirm my changes work in the DartPad. This is my first contribution to this repo, so apologies if I get something wrong.

**Comment by MiraMarshall** [comment]
Closing because this issue has been addressed.
