### ISSUE TITLE
[PAGE ISSUE]: 'Flutter SDK releases'

### ISSUE THREAD

**Issue by VocsyJay** [flutter/website#7281]
### Page URL

https://docs.flutter.dev/development/tools/sdk/releases/

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/sdk/releases.md

### Describe the problem

latest version of sdk above 3.0.0 get many Warning for widget bindings

**Comment by danagbemava-nc** [comment]
This is a known issue that has been documented in https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#if-you-see-warnings-about-bindings. 

They are just warnings and should not impact your app. If it does, kindly file an issue on the main flutter repo.

Closing from here as this is not an issue with this page. 

Thank you
