### ISSUE TITLE
[PAGE ISSUE]: 'Flutter documentation'

### ISSUE THREAD

**Issue by nayeemtby** [flutter/website#7283]
### Page URL

https://docs.flutter.dev/

### Page source

https://github.com/flutter/website/tree/main/src/index.md

### Describe the problem

Add dark mode.

### Expected fix

A button to switch to darkmode.

### Additional context

Hard to read code snippets for color contrast in some screens. And too bright to read docs at night.

**Comment by danagbemava-nc** [comment]
Closing this as a duplicate of https://github.com/flutter/website/issues/3632
