### ISSUE TITLE
[PAGE ISSUE]: 'Animate a widget using a physics simulation'

### ISSUE THREAD

**Issue by afroditexekoukoulotaki** [flutter/website#7297]
### Page URL

https://docs.flutter.dev/cookbook/animation/physics-simulation/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/animation/physics-simulation.md

### Describe the problem

There is an error in line 32

### Expected fix

State<DraggableCard> createState() => _DraggableCardState();

This fixes the issue.

**Comment by domesticmouse** [comment]
Thanks for the report!

**Comment by khanhnwin** [comment]
Hey thanks for this! I've made the update, will include it in my upcoming excerpts PR for you to review @domesticmouse.
