### ISSUE TITLE
"Developing packages & plugins" links to a non existent page in "Testing your plugin"

### ISSUE THREAD

**Issue by mateusfccp** [flutter/website#7339]
### Page URL

https://docs.flutter.dev/development/packages-and-plugins/developing-packages#testing-your-plugin

### Describe the problem

[Developing packages#Testing your plugin](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#testing-your-plugin) has a broken link: https://docs.flutter.dev/development/package-integration/android/plugin-api-migration#testing-your-plugin.

### Expected fix

Provide the correct link: https://docs.flutter.dev/development/platform-integration/android/plugin-api-migration#testing-your-plugin

**Comment by MiraMarshall** [comment]
Closed. The links have been fixed.
