### ISSUE TITLE
Clarify how `primaryColor` can be used on 'Use themes to share colors and font styles' page

### ISSUE THREAD

**Issue by fluffy11lol** [flutter/website#7341]
### Page URL

https://docs.flutter.dev/cookbook/design/themes#interactive-example

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/design/themes.md

### Describe the problem

Hello, I found mistakeful code line in your example. https://docs.flutter.dev/cookbook/design/themes#interactive-example 
19 line(`primaryColor: Colors.lightBlue[800]`) does nothing. I tested it on my Phone, emulator, and your interactive example.  Any color parameters change nothing in UI.
![image](https://user-images.githubusercontent.com/90965954/177867868-6f46ee77-c644-494d-a2d5-a52d29246d79.png)
![image](https://user-images.githubusercontent.com/90965954/177867895-829d54cc-9b90-47d2-8d84-0b8e1edc2fc4.png)

### Expected fix

You should rebuild this example.

**Comment by danagbemava-nc** [comment]
That example looks like it hasn't been updated for a while, so we should update it.

**Comment by atsansone** [comment]
This works as written, but doesn't reference the correct color in the scheme.

Line 52 should read:
```dart
color: Theme.of(context).colorScheme.primary,
```

Then, if you change the `primaryColor`, the app will change. We can make this fix.
