### ISSUE TITLE
flutter.dev shares IP address with other domains that are likely to be blacklisted for security reasons

### ISSUE THREAD

**Issue by Markus43** [flutter/website#7353]
### Describe the problem

flutter.dev is resolved to the IP address 199.36.158.100 for me. The same IP address is also used for anything that is hosted via the domain web.app - and there are many "web apps" using this domain, being hosted from many different people.

Corporate IT departments might decide blocking access to web.app pages via IP address for security reasons - and in that case, flutter.dev ends up being blocked, too.

### Expected fix

Give flutter.dev a different IP address. Flutter is big enough to deserve its own IP address nowadays.

**Comment by atsansone** [comment]
@godofredoc : If this could be investigated at your earliest convenience, that would be very appreciated. I would hate to get thrown off the internet by a well-meaning security update.

**Comment by domesticmouse** [comment]
This is a problem for all of Google's infrastructure.
