### ISSUE TITLE
Update macOS minimum version documentation to 10.13

### ISSUE THREAD

**Issue by jmagman** [flutter/website#7371]
### Page URL

https://docs.flutter.dev/deployment/macos#review-xcode-project-settings

### Describe the problem

References to `Flutter supports macOS 10.11 and later.` should become `Flutter supports macOS 10.13 and later.`, etc.

This should wait until https://github.com/flutter/flutter/pull/107689 gets to a stable release.

See also pending iOS version of this request https://github.com/flutter/website/issues/7037.

**Comment by parlough** [comment]
Read this wrong and didn't mean to close it. Still waiting on the next stable release :)

**Comment by atsansone** [comment]
The [macOS requirements](https://docs.flutter.dev/get-started/install/macos) state 10.14. This issue is out of date. Closing.
