### ISSUE TITLE
flutter web can't handle url encodings on iOS devices

### ISSUE THREAD

**Issue by sirwes** [flutter/website#7372]
### Describe the problem

I have a flutter app enabled for android, iOS, and web. I have a link that sends users to the page on the web version (hosted by firebase) if they don't have the mobile app. The link works as expected for iOS and android and it redirects to the website as expected. 

The URL I redirect them to looks something like this: https://my.url/#/mypagename?myparameter=1234&mysecondparam=2345.
This URL works and brings me right to the page if I key it in exactly how you see it above.

But if I click the link on an iphone or imac (android and pc work fine) and the redirect happens, the URL changes to https://my.url/%23/mypagename?myparameter%3D1234%2Bmysecondparam%3D2345 and I'm brought to a blank web page.
This behavior also happens if I key the URLs in manually exactly as described - the first one brings me to the page and the second one brings me to a blank screen on iOS devices.

It seems that the URL encodings for special characters makes it so that the flutter web engine doesn't recognize where to go. At least that's my guess.
See the url encodings here: _https://www.eso.org/~ndelmott/url_encode.html_

### Expected fix

A URL with URL-encoded special characters should return the same webpage as the normal URL

### Additional context

The page the URL references isn't the default or "first" page and it has function parameter requirements.

**Comment by danagbemava-nc** [comment]
Hi @sirwes, this seems like an issue for the main flutter repo. 

Kindly file this issue over there and provide the relevant information required to reproduce this. 

Closing as this is beyond the scope of this repo. 

Thank you
