### ISSUE TITLE
Fix non-parallax example on 'Create a scrolling parallax effect' page

### ISSUE THREAD

**Issue by LangInteger** [flutter/website#7375]
### Page URL

https://docs.flutter.dev/cookbook/effects/parallax-scrolling/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/effects/parallax-scrolling.md

### Describe the problem

The comparison between non-parallax & parallax effects is not perfect because the code offered for non-parallax:

```dart
  Widget _buildParallaxBackground(BuildContext context) {
    return Image.network(
      imageUrl,
      fit: BoxFit.cover,
    );
  }
```

will create an image that does not fill the whole parent stack widget, see:

![image](https://user-images.githubusercontent.com/17768055/179404753-d09e202b-fe51-43a1-bde9-ffb2a4440cd6.png)

### Expected fix

To improve this, the code should be:

```dart
  Widget _buildParallaxBackground(BuildContext context) {
    return Positioned.fill(
        child: Image.network(
      imageUrl,
      fit: BoxFit.fill,
    ));
  }
```

Thus we can get the desired screen:

![image](https://user-images.githubusercontent.com/17768055/179404798-443ac475-e9a5-4cc7-b92e-c8c876af1984.png)

### Additional context

More appropriate usage example of Stack, as well as its child widgets, can give newbies a better understanding of flutter, and also can eliminate the time every developer spends to solve this corner case problem.

**Comment by danagbemava-nc** [comment]
Hi @LangInteger, you'll need to complete the cookbook first. At the end of the cookbook, the image fills the stack it is placed in. See the screenshot below. 

Considering the desired effect is achieved at the end of the cookbook, I think the sample should remain as is. 

/cc @domesticmouse for thoughts on this

<img width="500" alt="Screenshot 2022-07-19 at 12 24 29" src="https://user-images.githubusercontent.com/88313112/179749566-4566c36f-d04c-4ca0-920f-51a17a68e900.png">

**Comment by LangInteger** [comment]
Hi @danagbemava-nc, I know the picture will fill the parent fully with the parallax effect finally implemented in the Cookbook. But I think it is not the parallax effect that makes the `fill` takes effect (and we do not want to give developers a feeling of that, right?). So we'd better make the non-parallax version also fill the parent widget.

**Comment by atsansone** [comment]
The suggested change distorts the image. (That's [normal](https://api.flutter.dev/flutter/painting/BoxFit.html) for `BoxFit.fill`, but also why the current example uses `BoxFit.cover`.) 

To correct the display, the code should be:
```dart
  Widget _buildParallaxBackground(BuildContext context) {
    return Positioned.fill(
        child: Image.network(
      imageUrl,
      fit: BoxFit.cover,
    ));
  }
```
