### ISSUE TITLE
Flutter SDK Download Issue (in Korean Docs '맥OS에서 설치' page issue)

### ISSUE THREAD

**Issue by jaehong21** [flutter/website#7396]
Page URL: https://flutter-kr.io/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
In Korean docs (flutter-ko.dev) flutter SDK download doesn't work,
It seems to have CORS issues. 
because, the English docs have origin: flutter.dev
By the way, it is flutter-ko.dev which is different origin

**Comment by danagbemava-nc** [comment]
Hi @jaehong21, the flutter-ko.dev site is maintained by the community, not by the flutter team. 

Unfortunately, there's no way to contact the maintainers of that site so we cannot raise this issue with them. 

As such, I'll be closing this issue as the site is not maintained by the flutter team. 

Thank you
