### ISSUE TITLE
'맥OS에서 설치' page issue

### ISSUE THREAD

**Issue by Dohyun-Ko** [flutter/website#7398]
Page URL: https://flutter-kr.io/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: On the flutter-kr page, Flutter SDK download button doesn't work. It seems like a CORS error.

**Comment by danagbemava-nc** [comment]
See https://github.com/flutter/website/issues/7396#issuecomment-1198187189.

Closing.
