### ISSUE TITLE
[PAGE ISSUE]: 'Install'

### ISSUE THREAD

**Issue by claytongobeil** [flutter/website#7399]
### Page URL

https://docs.flutter.dev/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/index.md

### Describe the problem

glitchy not finishing actions

### Expected fix

smooth working

**Comment by danagbemava-nc** [comment]
Hi @claytongobeil, what exactly is the issue you're facing on this page?
