### ISSUE TITLE
Example on breaking change page should be updated to be null safe

### ISSUE THREAD

**Issue by abinvs-2019** [flutter/website#7400]
### Page URL

https://docs.flutter.dev/release/breaking-changes/parent-data-widget-generic-type/

### Page source

https://github.com/flutter/website/tree/main/src/release/breaking-changes/parent-data-widget-generic-type.md

### Describe the problem

@required was changed to required

### Expected fix

Change the @ symbol from @required to required

**Comment by danagbemava-nc** [comment]
Thanks for pointing that out. 

It appears the code sample on that page hasn't been updated for null-safety yet.

**Comment by sfshaza2** [comment]
@khanhnwin, fyi
