### ISSUE TITLE
[PAGE ISSUE]: 'Developing packages & plugins'

### ISSUE THREAD

**Issue by bryanoltman** [flutter/website#7402]
### Page URL

https://docs.flutter.dev/development/packages-and-plugins/developing-packages/

### Page source

https://github.com/flutter/website/tree/main/src/development/packages-and-plugins/developing-packages.md

### Describe the problem

This document covers a large breadth of information and use cases and would benefit from being broken up into smaller, more focused documents. Right now, it seems to target all of the following, each of which could be its own document:

1. Creating Dart packages
2. Creating Flutter packages
3. Creating Flutter plugins
4. Creating FFI plugins

A reader of this page is likely to only trying to do one of the above at any given time. Reducing the amount of irrelevant information the reader needs to wade through to find what they need (and thus removing the requirement that the reader constantly ask the question "is this section relevant?") would be a big improvement.

**Comment by sfshaza2** [comment]
Perhaps the page could be better organized. I wouldn't automatically break it into smaller pages.

**Comment by sfshaza2** [comment]
Closing.
