### ISSUE TITLE
[PAGE ISSUE]: 'macOS install'

### ISSUE THREAD

**Issue by Taroka** [flutter/website#7408]
### Page URL

https://docs.flutter.dev/get-started/install/macos/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/macos.md

### Describe the problem

copy function gives below result:
```
  $ sudo softwareupdate --install-rosetta --agree-to-license

```
the content includes additional $ and space/new line, which is not very handy for user to paste on their terminal

**Comment by MiraMarshall** [comment]
Closing because this issue has been fixed.
