### ISSUE TITLE
[PAGE ISSUE]: 'Take a picture using the camera'

### ISSUE THREAD

**Issue by SecondarySkyler** [flutter/website#7414]
### Page URL

https://docs.flutter.dev/cookbook/plugins/picture-using-camera/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/plugins/picture-using-camera.md

### Describe the problem

The example is not working for me, even if I copy and paste the exact same source code.
The application starts and then when I click on the Floating Button to take a picture the screen freeze.
If I click again on the Floating Button the console says:
```CameraException(Previous capture has not returned yet., takePicture was called before the previous capture returned.)```

I'm working with Flutter 3.0.5, Dart 2.17.6 and the camera plugin ^0.10.0

**Comment by danagbemava-nc** [comment]
Hi @SecondarySkyler, what device are you experiencing this issue on? 
I run on it on my physical device (Poco X3 NFC) and the code sample works as expected.

**Comment by SecondarySkyler** [comment]
Hi @danagbemava-nc i tried this on a virtual device, it is a Samsung Nexus S.

**Comment by danagbemava-nc** [comment]
Hi @SecondarySkyler, do you have any other device that you can test this on?

**Comment by SecondarySkyler** [comment]
@danagbemava-nc I tried on a Pixel 2 but I got the same result, I'll try on a physical device and i'll let you know

**Comment by danagbemava-nc** [comment]
Thanks

**Comment by SecondarySkyler** [comment]
I tried to use my physical device (huawei p10) but android studio does not detect it, so I'm unable to test the application on a physical device.
Anyway I've managed to solve my problem using the ```image_picker``` plugin.
Thanks for the support.
@danagbemava-nc
