### ISSUE TITLE
[PAGE ISSUE]: 'Install'

### ISSUE THREAD

**Issue by Jaineel-Mamtora** [flutter/website#7420]
### Page URL

https://docs.flutter.dev/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/index.md

### Describe the problem

Open and close dropdown button is not working as expected. Please check below video.

https://user-images.githubusercontent.com/38665793/182822712-912d5828-4641-46ad-b25d-2e903d54bbde.mp4

**Comment by danagbemava-nc** [comment]
https://user-images.githubusercontent.com/88313112/182832932-1529647e-b717-4248-94b4-2e41bc69421f.mov

Hi @Jaineel-Mamtora, do you see any errors in your console? The dropdowns work for me as expected. 
See the video above

**Comment by Jaineel-Mamtora** [comment]
No errors in the console. See below Video:

https://user-images.githubusercontent.com/38665793/182834274-78b095bd-672b-4293-b361-a63303de0421.mp4

Working fine in Microsoft edge:

https://user-images.githubusercontent.com/38665793/182834479-0c68aea3-55d2-4903-8aff-a5c94281dc00.mp4

**Comment by danagbemava-nc** [comment]
Hmm, I'm not sure there's anything we can do considering it works in Edge but not Chrome (I presume). I tested on my windows laptop as well, in chrome and the dropdown worked as expected. 

This may be due to an issue in your browser. Can you try clearing the cache to see if it works?

**Comment by Jaineel-Mamtora** [comment]
It is now working, It was some adblocker issue.
