### ISSUE TITLE
[PAGE ISSUE]: 'Use themes to share colors and font styles'

### ISSUE THREAD

**Issue by rakhalraj-celex** [flutter/website#7421]
### Page URL

https://docs.flutter.dev/cookbook/design/themes/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/design/themes.md

**Comment by rakhalraj-celex** [comment]
> ### Page URL
> https://docs.flutter.dev/cookbook/design/themes/
> 
> ### Page source
> https://github.com/flutter/website/tree/main/src/cookbook/design/themes.md
> 
> ### Describe the problem
> dsad
> 
> ### Expected fix
> dasdsa
> 
> ### Additional context
> dsadsa

**Comment by danagbemava-nc** [comment]
Closing this as no description has been provided.
