### ISSUE TITLE
[PAGE ISSUE]: 'Obfuscating Dart code'

### ISSUE THREAD

**Issue by fryette** [flutter/website#7430]
### Page URL

https://docs.flutter.dev/deployment/obfuscate/

### Page source

https://github.com/flutter/website/tree/main/src/deployment/obfuscate.md

### Describe the problem

I tried to obfuscate Linux apps and seems it's working. Would be nice to update the info.

### Expected fix

Update info for linux platform

### Additional context

All steps applicable to Linux platform

**Comment by sfshaza2** [comment]
Looks simple enough. Confirm and update the "Linux" field to say supported.

**Comment by parlough** [comment]
Closing as a duplicate of https://github.com/flutter/website/issues/7430. Thanks for opening an issue!
