### ISSUE TITLE
How to use Flutter in an iOS app extension

### ISSUE THREAD

**Issue by leighajarett** [flutter/website#7448]
### What information is missing?

Having a generic example of how to use Flutter for iOS app extensions https://developer.apple.com/app-extensions/

- [ ] #8220
- [x] Test App Clip on iOS 16 [flutter/flutter/#71098](https://github.com/flutter/flutter/issues/71098)
- [x] Document generic steps for using Flutter in iOS app extensions

**Comment by sfshaza2** [comment]
@leighajarett, who would the engineering contact be for this?
