### ISSUE TITLE
Add links to tie flutter with camera and firebase ml?

### ISSUE THREAD

**Issue by jotisa** [flutter/website#7452]
### What information is missing?

It isn't on flutter.dev even though you can find integration of flutter with machine learning on firebases' website, I would suggest a pointer of a happy path to learning Firebase ML for Flutter!

### How would you like us to fix this problem?

In the happy paths webpage https://docs.flutter.dev/development/packages-and-plugins/happy-paths I would like to see an entry to https://firebase.google.com/docs/ml/flutter/use-custom-models and/or https://pub.dev/packages/firebase_ml_custom as it would be nice to integrate these last two websites to the happy paths to write apps with flutter that could use the camera to do ML.  Thank you so much.

**Comment by sfshaza2** [comment]
@ericwindmill, do you have any suggestions?
