### ISSUE TITLE
[PAGE ISSUE]: 'Flutter and the pubspec file'. The reference is incomplete

### ISSUE THREAD

**Issue by alexeyinkin** [flutter/website#7456]
### Page URL

https://docs.flutter.dev/development/tools/pubspec/

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/pubspec.md

### Describe the problem

There is a possible `generate` key under `flutter` in pubspec.yaml, but it is not listed there.

It's only mentioned here: https://docs.flutter.dev/development/accessibility-and-localization/internationalization
without explanation of what it does and whether it can generate anything but the localizations.

There may be more keys that are supported but are not described here.

### Expected fix

Since this page is the first google result for "flutter pubspec.yaml", it should either be a complete reference of what is supported under "flutter", or should have a link to such reference at the bottom.

**Comment by sfshaza2** [comment]
Yes, we should add all the flags.
