### ISSUE TITLE
[PAGE ISSUE]: 'Work with WebSockets'

### ISSUE THREAD

**Issue by Whizzel** [flutter/website#7459]
### Page URL

https://docs.flutter.dev/cookbook/networking/web-sockets/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/networking/web-sockets.md

### Describe the problem

websocket.org is no longer available

**Comment by sfshaza2** [comment]
This seems to be true! @ditman, do you know what might replace that?

**Comment by piedcipher** [comment]
https://www.lob.com/blog/websocket-org-is-down-here-is-an-alternative

this might be a replacement?!

**Comment by ditman** [comment]
I'm having a big _déjà vu_ with this issue, I'd swear I've already sent a fix for this websockets example (months ago?)

**Comment by ditman** [comment]
Ah, I must have updated the code samples, but not the links to websockets.org

**Comment by ditman** [comment]
I've posted a PR but it said the repo is not accepting PRs at the time, I can circle back to this after September 1st to have it landed (or move the fix anywhere else, as needed)
