### ISSUE TITLE
"VM acceleration" link in _android-setup.md

### ISSUE THREAD

**Issue by MaryaBelanger** [flutter/website#7461]
### Page URL

https://docs.flutter.dev/get-started/install/macos#set-up-the-android-emulator

### Page source

https://github.com/flutter/website/blob/main/src/get-started/install/_android-setup.md?plain=1#L46

### Describe the problem

"Configure hardware acceleration for the Android Emulator" is a long page. If the anchor text on our page is accurate and only VM acceleration is required, then it should go straight to the "Configuring VM acceleration"

Top-of-the-page link caused me to absent-mindedly start working through the whole page, starting with "Configure graphics acceleration". It seems configuring graphics acceleration is not a prereq for just configuring VM acceleration though (correct me if I'm wrong), so we should help readers skip to the point.

### Expected fix

`    [VM acceleration]({{site.android-dev}}/studio/run/emulator-acceleration#accel-vm)
`

**Comment by sfshaza2** [comment]
Great idea!

**Comment by MaryaBelanger** [comment]
Actually... I'm not even sure about the instructions I changed it to. I won't do anything about this until I'm fully through successfully setting up

**Comment by sfshaza2** [comment]
Definitely! I just wanted to let you know.
