### ISSUE TITLE
By default show Swift code sample tab instead of Objective-C

### ISSUE THREAD

**Issue by jmagman** [flutter/website#7462]
### Page URL

All pages with `{% sample Objective-C %}` and `{% sample Swift %}` such as https://docs.flutter.dev/development/add-to-app/ios/add-flutter-screen?tab=entrypoint-library-objective-c-tab#create-a-flutterengine

### Describe the problem

Swift has been the default Flutter iOS native development language for a few years, and is the only option for macOS. Right now when there is both Objective-C and Swift example code, the Objective-C tab is shown by default.

Example:
![Screen Shot 2022-08-17 at 6 50 31 PM](https://user-images.githubusercontent.com/682784/185274524-8d39762a-d870-45a0-b6c7-aba2fe66c90a.png)
 

### Expected fix

Switch the order of the tabs so Swift is the default, and the user can switch to Objective-C if needed.

**Comment by jmagman** [comment]
Is this just a matter of swapping the order of the `samplecode`?
From
``````md
{% samplecode entrypoint-library %}
{% sample Objective-C %}
<!--code-excerpt "Objective-C" title-->
```objectivec
[flutterEngine runWithEntrypoint:@"myOtherEntrypoint" libraryURI:@"other_file.dart"];
```
{% sample Swift %}
<!--code-excerpt "Swift" title-->
```swift
flutterEngine.run(withEntrypoint: "myOtherEntrypoint", libraryURI: "other_file.dart")
```
{% endsamplecode %}
``````
to
``````md
{% samplecode entrypoint-library %}
{% sample Swift %}
<!--code-excerpt "Swift" title-->
```swift
flutterEngine.run(withEntrypoint: "myOtherEntrypoint", libraryURI: "other_file.dart")
```
{% sample Objective-C %}
<!--code-excerpt "Objective-C" title-->
```objectivec
[flutterEngine runWithEntrypoint:@"myOtherEntrypoint" libraryURI:@"other_file.dart"];
```
{% endsamplecode %}
``````
?

**Comment by jmagman** [comment]
cc @khanhnwin @leighajarett

**Comment by khanhnwin** [comment]
Thanks @MiraMarshall for picking up this issue!

**Comment by MiraMarshall** [comment]
Closing because this issue has been fixed.

**Comment by jmagman** [comment]
Thanks @MiraMarshall!
