### ISSUE TITLE
Provide Swift versions of all Objective-C example code in docs

### ISSUE THREAD

**Issue by jmagman** [flutter/website#7463]
### Page URL

`objectivec` code excerpts missing Swift versions, like https://docs.flutter.dev/development/add-to-app/ios/add-flutter-screen?tab=engine-objective-c-tab#using-the-flutterappdelegate

### Describe the problem

Some example code in the documentation is only provided in Objective-C. 

Example:
<img width="987" alt="Screen Shot 2022-08-17 at 7 27 52 PM" src="https://user-images.githubusercontent.com/682784/185279414-10751cb2-b3fd-4a49-adac-16c4086bc8c5.png">
 

### Expected fix

Add Swift versions of this documentation so the user can see either tab:
<img width="305" alt="Screen Shot 2022-08-17 at 7 28 13 PM" src="https://user-images.githubusercontent.com/682784/185279453-d9c1b0eb-ef45-413d-95be-eead10f8bb0c.png">

**Comment by jmagman** [comment]
@leighajarett

**Comment by ZaddyRichie** [comment]
I don't get it wella

**Comment by leighajarett** [comment]
I think that all the examples now have Swift references, so closing this
