### ISSUE TITLE
Slack community link has expired 

### ISSUE THREAD

**Issue by HugoCSWork** [flutter/website#7468]
### Page URL

https://flutter.dev/community

### Describe the problem

When clicking on the link to join the Flutter Slack community it initially takes you to [https://fluttercommunity.dev/joinslack](https://fluttercommunity.dev/joinslack) which then redirects to [https://fluttercommunity.slack.com/join/shared_invite/zt-14w4zzw8j-MyD3OlwQr_PUAaShyyupGA#/](https://fluttercommunity.slack.com/join/shared_invite/zt-14w4zzw8j-MyD3OlwQr_PUAaShyyupGA#/) which is an expired link. 

On the Slack URL we get the message -

"This link is no longer active"
To join this workspace, you’ll need to ask the person who originally invited you for a new link."

### Expected fix

New link generated for the redirect.

**Comment by slightfoot** [comment]
Fixed
