### ISSUE TITLE
[PAGE ISSUE]: 'Create a typing indicator'

### ISSUE THREAD

**Issue by wednesdei** [flutter/website#7482]
### Page URL

https://docs.flutter.dev/cookbook/effects/typing-indicator/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/effects/typing-indicator.md

### Describe the problem

Interactive example at bottom of page is broken, looks like the formatting for the embed was incorrectly applied.

### Expected fix

[Get it working in dartpad.](https://dartpad.dev/?id=93860a426e16496b868d0cceadd4453a)

### Additional context

Yeah, looks like you just need to get the dartpad embed working.

**Comment by piedcipher** [comment]
@danagbemava-nc this has been fixed! We can close #7482

**Comment by wednesdei** [comment]
Nice! Thanks!
