### ISSUE TITLE
Hyperlinks in markdowns don't work as intended

### ISSUE THREAD

**Issue by Biplab-Dutta** [flutter/website#7498]
I was checking different markdowns that are used in the development of flutter's website like `whats-new.md`, `/release-notes/index.md`, etc. There are many hyperlinks in the `md` files. When I clicked on one from within github, it was supposed to take me to another webpage but I got 404 error.

I have attached a video to clarify what I mean.

https://user-images.githubusercontent.com/63902683/188132686-1503b6cf-d6e0-4a95-9c2a-4588a92986d8.mp4

Also, I was planning on working on an app that would rely on these markdown files from github (to display them in a `WebView`). If I can't browse to other links by tapping on the hyperlinks present in the `md` files, it'd be useless for me.
The navigation to other links work fine when checked on the flutter's site. The issue is only seen when trying to navigate from within the github's markdown files.

**Comment by danagbemava-nc** [comment]
I think those links are supposed to be used on the website and not from the markdown pages, so that's probably why. 

Labeling for insight from the team

**Comment by Biplab-Dutta** [comment]
> I think those links are supposed to be used on the website and not from the markdown pages, so that's probably why. 
> 
> Labeling for insight from the team

Hi. And what if I want to use them in my app as WebView?

**Comment by sfshaza2** [comment]
Yes, you can't use the links from within GitHub. You must use the links from the website. The GitHub preview of the website is insufficient - it doesn't go through the entire build process with jekyll, etc. I'm afraid I don't know the answer to your WebView question. Perhaps ask in the Discord channel or on StackOverflow?

**Comment by Biplab-Dutta** [comment]
I found a breakthrough for the issue I had opened. The solution was to parse the HTML string so that WebView in Flutter could understand it. I am sharing the solution if anyone happens to face similar issue in the future.

[Check this file](https://github.com/Biplab-Dutta/now-in-dart-flutter/blob/master/lib/features/detail/core/data/detail_dto.dart) for the solution.

**Comment by sfshaza2** [comment]
@khanhnwin
