### ISSUE TITLE
[PAGE ISSUE]: 'Install'

### ISSUE THREAD

**Issue by sakib6g** [flutter/website#7506]
### Page URL

https://docs.flutter.dev/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/index.md

### Describe the problem

Sattka matka 

### Additional context

ST SATTKA MATKA

**Comment by sakib6g** [comment]
Sattka matka

**Comment by danagbemava-nc** [comment]
Closing as no relevant information has been provided.
