### ISSUE TITLE
[PAGE ISSUE]: 'Test drive'

### ISSUE THREAD

**Issue by stef-luo** [flutter/website#7517]
### Page URL

https://docs.flutter.dev/get-started/test-drive/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/test-drive/index.md

### Describe the problem

In the [Flutter Doc](https://docs.flutter.dev/get-started/test-drive?tab=vscode) Test Drive section --> under Visual Studio Code --> Run the App --> Step 2 yellow highlighted section, when clicking on the "Copy Code" icon on the upper right corner of the box, instead of copying only the code, it copies the entire thing including the $. 

### Expected fix

Remove the $ when clicking on the Copy Code icon.

**Comment by MiraMarshall** [comment]
Nice catch! @stef-luo

**Comment by MiraMarshall** [comment]
Closing. This issue has been fixed.
