### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by stef-luo** [flutter/website#7518]
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

In [Flutter Doc ](https://docs.flutter.dev/get-started/codelab) --> Step 2: Use an external package --> two black boxes with codes inside --> when clicking on the upper right corner to Copy Code, instead of only copying the codes, it copies everything including the explanation of the code. 

### Expected fix

When clicking on the Copy Code icon, only copy the codes and exclude the explanations.

**Comment by Hirdey-1999** [comment]
I have checked with the issue it is not copying the entire explanation it is just copying the code.

**Comment by MiraMarshall** [comment]
cc @khanhnwin

**Comment by MohamedMafaz** [comment]
Sir, Can you assign me. I'll fix this.

**Comment by MohamedMafaz** [comment]
I fixed it

**Comment by sfshaza2** [comment]
I also worked on this. :). Closing.
