### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by AMDphreak** [flutter/website#7533]
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

Source code and instructions for Step 2 (using external package) are out of date, and inconsistent with the Hello World code that the user is instructed to copy from Step 1.

- ![main dart before wordPair](https://user-images.githubusercontent.com/1058978/189240716-c3e26c4e-1ad8-4f33-b970-70492fc82ad1.png)

- Inserting the Step 2 code after the corresponding lines from the Step 1 code results in an error in the child field.
   ![main dart after wordPair](https://user-images.githubusercontent.com/1058978/189240722-c5e67eb3-05e3-4259-bb91-026842d5efb1.png)

**Comment by piedcipher** [comment]
Just remove `const` from `Center`. Since `Text` uses a value which is not a const.

![Screenshot at 2022-10-05 02-05-38](https://user-images.githubusercontent.com/13456345/193921818-0169f862-7df8-4da0-9cb1-50d2a105021d.png)

Step 2 doesn't have a `const` either at that line.
