### ISSUE TITLE
San Diego Flutter meetup

### ISSUE THREAD

**Issue by gisborne** [flutter/website#7537]
### What information is missing?

There is a new San Diego flutter meetup. I’d like it listed on https://flutter.dev/community and anywhere else appropriate.

You can put my email address if you need a contact: guyren@relevantlogic.com

### How would you like us to fix this problem?

Add the new meetup in relevant places.

**Comment by sfshaza2** [comment]
I've contacted the proper person within the team who will handle this.

**Comment by anelvro** [comment]
Hi! There is a process for a group to be added under the [Flutter Meetup Network](https://www.meetup.com/pro/flutter). I'll send the details to the email you provided.

**Comment by sfshaza2** [comment]
Thanks so much @anelvro! Closing this issue.
