### ISSUE TITLE
[PAGE ISSUE]: 'Codelabs Link' :link: 

### ISSUE THREAD

**Issue by piedcipher** [flutter/website#7539]
### Page URL

https://docs.flutter.dev/codelabs/

### Page source

https://github.com/flutter/website/tree/main/src/codelabs/index.md

### Describe the problem

Link for `Multi-platform Firestore Flutter` is `https://codelabs.developers.google.com/codelabs/friendlyeats-flutter` but it opens `https://firebase.google.com/codelabs/firebase-get-to-know-flutter`.

What should be the correct link?

### Expected fix

Correct link for `friendlyeats-flutter` codelab should be added.

**Comment by piedcipher** [comment]
https://user-images.githubusercontent.com/13456345/189500105-cd1aab65-9f47-409c-ba41-67fbc1afda8d.mp4

**Comment by sfshaza2** [comment]
@MiraMarshall, could you take this?

**Comment by MiraMarshall** [comment]
It looks like this redirect is happening on all the links that are supposed to go to `friendlyeats-flutter`. @domesticmouse is this intentional?

**Comment by sfshaza2** [comment]
@domesticmouse, have we retired this codelab? It was old.

**Comment by domesticmouse** [comment]
Yup, the Friendly Eats codelab was retired (it was unmaintained), and the codelab URL was redirected to the maintained getting started with Flutter and Firebase codelab. Please feel free to delete.

**Comment by sfshaza2** [comment]
Thanks! Feel free to delete, Shamira!

**Comment by sfshaza2** [comment]
@MiraMarshall, sorry if I wasn't clear. The description/name of the codelab on our index page is incorrect. It needs to be updated to reflect the codelab that it actually points to. If we already link to the newer codelab from our index page, then we should delete the second reference. I've re-opened, because this needs a PR.

**Comment by sfshaza2** [comment]
Fixed!
