### ISSUE TITLE
[PAGE ISSUE]: 'List of state management approaches > Provider'

### ISSUE THREAD

**Issue by jess-rod** [flutter/website#7568]
### Page URL

https://docs.flutter.dev/development/data-and-backend/state-mgmt/options#provider

### Page source

https://github.com/flutter/website/tree/main/src/development/data-and-backend/state-mgmt/options.md

### Describe the problem

1. [You might not need Redux: The Flutter edition](https://proandroiddev.com/you-might-not-need-redux-the-flutter-edition-9c11eba006d7) is outdated. Provider has evolved much since. Having this link may confuse the reader.
2. In [Making sense of all those Flutter Providers](https://medium.com/flutter-community/making-sense-all-of-those-flutter-providers-e842e18f45dd?sk=7859a73fac0ca414a0e911b0322e8589), this piece of code is found:
```
class MyButton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final myModel = Provider.of<MyModel>(context, listen: false);
    return RaisedButton(
      child: Text('Do something'),
      onPressed: () {
        myModel.doSomething();
      },
    );
  }
}
```
`Provider.of<MyModel>(context, listen: false)` is called inside a `build` method while the value is used only in `onPressed`. This is an antipattern according to [Remi Rousselet](https://github.com/rrousselGit) (Provider's creator):

> DON'T call [`read`](https://pub.dev/documentation/provider/latest/provider/ReadContext/read.html) inside build if the value is used only for events. 
> 
> [...]
> 
> While this code is not bugged in itself, this is an anti-pattern. It could easily lead to bugs in the future after refactoring the widget to use counter for other things, but forget to change [`read`](https://pub.dev/documentation/provider/latest/provider/ReadContext/read.html) into `watch`.
> 
> CONSIDER calling [`read`](https://pub.dev/documentation/provider/latest/provider/ReadContext/read.html) inside event handlers

For reference, see:
- https://github.com/rrousselGit/provider/issues/456#issuecomment-631288369
- https://github.com/rrousselGit/provider/blob/master/lib/src/provider.dart
- https://pub.dev/documentation/provider/latest/provider/ReadContext/read.html

### Expected fix

Replace the references to those articles with references to articles that are up-to-date and _good_ examples of _good_ use, mention the issues, or remove the references to those articles whatsoever.

### Additional context

`context.read<T>()` and `Provider.of<T>(context, listen: false)` are equivalent. The current implementation of `read` is indeed:
```
T read<T>() {
  return Provider.of<T>(this, listen: false);
}
```

**Comment by sfshaza2** [comment]
@domesticmouse, could you update this page?

**Comment by domesticmouse** [comment]
What should we be linking to? We don't own maintaining [Sugarch's Medium article](https://medium.com/flutter-community/making-sense-all-of-those-flutter-providers-e842e18f45dd), which appears to be the meat of this bug report.

**Comment by sfshaza2** [comment]
Both articles have been removed from the state management options page. Closing.
