### ISSUE TITLE
Create a page that maps Apple Kit's to workflows on Flutter

### ISSUE THREAD

**Issue by leighajarett** [flutter/website#7572]
### What information is missing?

Apple has several SDKs (for example: [MusicKit](https://developer.apple.com/musickit/)) that help with developing specific types of apps, or accomplish specific tasks when developing an app. For new Flutter developers that have experience working in the Apple ecosystem, it would be helpful for us to point them to specific code samples or packages that help them achieve the same thing that they would have done with X Apple Kit.

### How would you like us to fix this problem?

Maybe this is something that becomes a part of Happy Paths?

**Comment by sfshaza2** [comment]
@leighajarett, if you know of existing packages that do this, that would be great!
