### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by cobelu** [flutter/website#7586]
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

`english_words 4.0.0` should be `english_words: 4.0.0` under "Step 2: Use an external package" -> 1.

### Expected fix

`english_words 4.0.0` should be `english_words: 4.0.0` under "Step 2: Use an external package" -> 1.

**Comment by Hirdey-1999** [comment]
I will do it

**Comment by parlough** [comment]
This was fixed by https://github.com/flutter/website/pull/7591, but thanks for offering @Hirdey-1999!
