### ISSUE TITLE
[PAGE ISSUE]: 'Shader compilation jank'

### ISSUE THREAD

**Issue by haithemmihoubi** [flutter/website#7589]
### Page URL

https://docs.flutter.dev/perf/shader/

### Page source

https://github.com/flutter/website/tree/main/src/perf/shader.md

### Describe the problem

 Impeller on Android is being actively developed, but is not yet in developer preview
This line describe that the package is only developed in iOS, but now it's deployed in the pub.dev

**Comment by danagbemava-nc** [comment]
Hi @haithemmihoubi, can you provide a link to the package you're referring to? 

Impeller is being worked on in the flutter engine, it is unlikely that it will be published as a pub package.

**Comment by sfshaza2** [comment]
I think he means this package:  https://pub.dev/packages/impeller

But I have no idea what's up. I'll ask around.

**Comment by sfshaza2** [comment]
OK, this package is definitely NOT related to our Impeller implementation. (I didn't think so.) I've filed an issue with the pub.dev. Closing
