### ISSUE TITLE
[PAGE ISSUE]: 'Security'

### ISSUE THREAD

**Issue by Daynight-Himmat** [flutter/website#7597]
### Page URL

https://docs.flutter.dev/security/

### Page source

https://github.com/flutter/website/tree/main/src/security/index.md

### Describe the problem

Hello Flutter team
i am getting the issue in ioImage is not support in the flutter web.
i am unable to save image in the brower local directory to store the image or files for the communicate with the data response.
i am unable to give the functional on the flutter web

### Expected fix

Please 
create some of image plugin for the flutter web for the store image local direactory and provide the path of image or files in the web to store directly

**Comment by danagbemava-nc** [comment]
Kindly file an issue on the main flutter repo and provide enough information as to what exactly it is that you want. 

Closing as this is not an issue with the security page nor a website issue for that matter. 

Thank you
