### ISSUE TITLE
Add VS guide for 'Using OEM debugger'

### ISSUE THREAD

**Issue by dlewis2017** [flutter/website#7628]
### Page URL

https://docs.flutter.dev/get-started/editor/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/editor.md

### Describe the problem

More of a request than issue. Can we have Visual Studio setup instructions?

### Expected fix

More of a request than issue. Can we have Visual Studio setup instructions?

**Comment by atsansone** [comment]
@anderdobo : Any thoughts on adding this?

**Comment by loic-sharma** [comment]
Visual Studio is useful for [developing Windows plugins](https://docs.flutter.dev/packages-and-plugins/developing-packages#step-2f-add-windows-platform-code-hcpp) or debugging native code. However, it is not ideal for developing Dart code which is what the "Set up an editor" page targets.

I would update the native debugging guide to include Visual Studio for Windows app developers: https://docs.flutter.dev/testing/oem-debuggers

**Comment by anderdobo** [comment]
1. There are no Flutter and Dart extensions for Visual Studio, therefore we cannot add setup instructions to https://docs.flutter.dev/get-started/editor/  
2. I agree with @loic-sharma's suggestion to add Visual Studio to https://docs.flutter.dev/testing/oem-debuggers.

**Comment by loic-sharma** [comment]
FYI I wrote a guide for customers that might be useful when writing these docs: https://gist.github.com/loic-sharma/248f28b3ba4664dde08da68f46b312bd#load-the-engines-symbols

**Comment by atsansone** [comment]
Closing this issue as a duplicate of #7600.
