### ISSUE TITLE
Flutte documentation page footer bug

### ISSUE THREAD

**Issue by skillkrio** [flutter/website#7649]
### Page URL

https://api.flutter.dev/flutter/widgets/widgets-library.html

### Describe the problem

The footer of the page is placed at center after some seconds of loading. This cause the documentation hard to read. This bug occurs only in brave browser.

### Expected fix

Try to keep the footer at the bottom of the page instead of placing it in center.
![webbug](https://user-images.githubusercontent.com/30119763/195635948-3777dfc9-23db-4933-b5d5-a0f433931c15.png)

**Comment by jasimameen** [comment]
Mention down the browser and the machine where this error caused

**Comment by parlough** [comment]
@skillkrio It looks like there are some other issues with the styling in your screenshot and I cannot reproduce this. Does this persist if you disable your dark theme extension for the page?

**Comment by skillkrio** [comment]
This issue caused due to an extension called spade.
