### ISSUE TITLE
[PAGE ISSUE]: 'Navigate with named routes'

### ISSUE THREAD

**Issue by atrauzzi** [flutter/website#7655]
### Page URL

https://docs.flutter.dev/cookbook/navigation/named-routes/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/navigation/named-routes.md

### Describe the problem

This page doesn't contain any information about how to work with query string parameters.

### Expected fix

Advice on how to author routes that match, even when query string parameters are present.

**Comment by sfshaza2** [comment]
@johnpryan

**Comment by johnpryan** [comment]
Hi @atruzzi, thanks for filing an issue. I think this is covered in the [Pass arguments to a named route](https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments) article. 

Flutter doesn't provide a way to parse query string parameters with named routes, but you could use Router-based package such as go_router instead. Check out the [Navigation and routing](https://docs.flutter.dev/development/ui/navigation) page for details.
