### ISSUE TITLE
macOS SDKs list should alternative between x64 and arm64

### ISSUE THREAD

**Issue by jmagman** [flutter/website#7664]
### Page URL

https://docs.flutter.dev/development/tools/sdk/releases?tab=macos

### Describe the problem

macOS SDK includes x64 and arm64 SDKs, but the order is not stable.  Instead of alternating x64, arm64, x64, arm64, it's instead in random order.

![Screen Shot 2022-10-18 at 3 14 22 PM](https://user-images.githubusercontent.com/682784/196555129-2d4e3708-e12c-4580-a8fb-dd2e2077c35c.png)

### Expected fix

Alternative between x64 and arm64

Flutter version | Architecture | Ref | Release Date | Dart version
-- | -- | -- | -- | --
3.3.4 | x64 | eb6d86e | 10/5/2022 | 2.18.2
3.3.4 | arm64 | eb6d86e | 10/5/2022 | 2.18.2
3.3.3 | x64 | 18a827f | 9/28/2022 | 2.18.2
3.3.3 | arm64 | 18a827f | 9/28/2022 | 2.18.2
3.3.2 | x64 | e3c29ec | 9/14/2022 | 2.18.1
3.3.2 | arm64 | e3c29ec | 9/14/2022 | 2.18.1
3.3.1 | x64 | 4f9d92f | 9/7/2022 | 2.18.0
3.3.1 | arm64 | 4f9d92f | 9/7/2022 | 2.18.

**Comment by atsansone** [comment]
@jmagman : This list is generated from content built in [flutter/flutter](https://github.com/flutter/flutter/blob/main/packages/flutter_tools/lib/src/flutter_cache.dart). Any change would need to be made there. The docs tooling doesn't have the ability to sort by columns. Recommend an issue against flutter/flutter. Closing.
