### ISSUE TITLE
[PAGE ISSUE]: 'Displaying images on the web'

### ISSUE THREAD

**Issue by danPyk** [flutter/website#7671]
### Page URL

https://docs.flutter.dev/development/platform-integration/web/web-images/

### Page source

https://github.com/flutter/website/tree/main/src/development/platform-integration/web/web-images.md

### Describe the problem

There's no link for this page in the left side navigation menu.

### Expected fix

Add a link for this page in the left side navigation menu

**Comment by danagbemava-nc** [comment]
Thanks for pointing this out. 
There's also no entry for this under the Platform Integration topic for web.

<img src="https://user-images.githubusercontent.com/88313112/196700116-3680dd84-dc5e-45c4-bb04-1c47adc7b424.png" width="400" />

<img src="https://user-images.githubusercontent.com/88313112/196700134-5a67b53a-5510-44cf-b5e9-8e82e2ec5a50.png" width="400" />

**Comment by MiraMarshall** [comment]
Closing because this issue has been resolved. 
![Screen Shot 2022-10-24 at 9 53 46 AM](https://user-images.githubusercontent.com/23406866/197557000-42057762-ec15-46b7-8c23-d93ecbb5d110.png)
