### ISSUE TITLE
[PAGE ISSUE]: 'Animate a widget across screens'

### ISSUE THREAD

**Issue by ReallyVirtual** [flutter/website#7684]
### Page URL

https://docs.flutter.dev/cookbook/navigation/hero-animations/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/navigation/hero-animations.md

### Describe the problem

The URL https://picsum.photos/250?image=9 is blocked with an Access Denied, so the example is broken.

### Expected fix

Switch the URL from https://picsum.photos/250?image=9 to another image.

**Comment by ReallyVirtual** [comment]
Besides the inaccessible image (the link also doesn't work in the browser), there's a cross-domain restriction. Changing to https://docs.flutter.dev/assets/images/shared/brand/flutter/logo/flutter-lockup.png works.

**Comment by danagbemava-nc** [comment]
Hi @ReallyVirtual, I seem to be able to run the example just fine. It does take a while to load. Can you share any errors you get?

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/197530991-f8ee7869-92f2-412b-81da-d51f64048da9.mov
</details>
