### ISSUE TITLE
Revise example on 'Actions API revision' page

### ISSUE THREAD

**Issue by j796160836** [flutter/website#7691]
### Page URL

https://docs.flutter.dev/release/breaking-changes/actions-api-revision/

### Page source

https://github.com/flutter/website/tree/main/src/release/breaking-changes/actions-api-revision.md

### Describe the problem

[Custom Actions and Intents with arguments](https://docs.flutter.dev/release/breaking-changes/actions-api-revision#custom-actions-and-intents-with-arguments)

Code wrong
```dart
class MyIntent extends Intent {
  const MyIntent({this.argument});

  final int argument;
}

class MyAction extends Action<MyIntent> {
  @override
  int invoke(Intent intent) {
    // ...
    return intent.argument;
  }
}

```

### Expected fix

I think it should be

```dart
class MyIntent extends Intent {
  const MyIntent({this.argument});

  final int argument;
}

class MyAction extends Action<MyIntent> {
  @override
  Object? invoke(MyIntent intent) {
    // ...
    return intent.argument;
  }
}

```

**Comment by danagbemava-nc** [comment]
Thanks for pointing this out. 

The example hasn't been updated for null-safety.

**Comment by atsansone** [comment]
This was fixed in https://github.com/flutter/website/pull/3981. Closing this issue.
