### ISSUE TITLE
Merge 'Dealing with box constraints' page with 'Understanding constraints' page

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#7701]
### Page URL

https://docs.flutter.dev/development/ui/layout/box-constraints/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/layout/box-constraints.md

### Describe the problem

I'm not sure if the [Dealing with box constraints](https://docs.flutter.dev/development/ui/layout/box-constraints) page provides distinctive value over the [Understanding constraints](https://docs.flutter.dev/development/ui/layout/constraints) doc. Maybe the former can be dropped or merged with the latter?

**Comment by sfshaza2** [comment]
I actually agree. It would also need a redirect since tooling points to the older page. @Hixie, what do you say?

**Comment by Hixie** [comment]
I have no objection to merging them. We should make sure to update the URL in the tooling as well, so it's not pointing to the redirect.

**Comment by atsansone** [comment]
Per https://github.com/flutter/website/issues/3203, clean up this page as well.
