### ISSUE TITLE
[PAGE ISSUE]: 'Firebase'

### ISSUE THREAD

**Issue by Hixie** [flutter/website#7707]
### Page URL

https://docs.flutter.dev/development/data-and-backend/firebase/

### Page source

https://github.com/flutter/website/tree/main/src/development/data-and-backend/firebase.md

### Describe the problem

This refers to the FlutterFire site but the FlutterFire site says it's obsolete and to refer to https://firebase.google.com/docs/flutter/.

**Comment by MiraMarshall** [comment]
Closed. The link has been fixed.
