### ISSUE TITLE
[PAGE ISSUE]: 'Visual Studio Code'

### ISSUE THREAD

**Issue by samekard-dev** [flutter/website#7712]
### Page URL

https://docs.flutter.dev/development/tools/vs-code/

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/vs-code.md

### Describe the problem

https://docs.flutter.dev/development/tools/vs-code#run-app-without-breakpoints

This article says that Start Without Debugging changes the status bar to orange, but isn't it Start Debugging that changes the status bar to orange?

macOS 12.6.1
VS Code 1.72.2

### Expected fix

The statement that the status bar turns orange should be moved to Run app with breakpoints.

**Comment by danagbemava-nc** [comment]
I can confirm that debugging is what changes the status bar color. 

https://user-images.githubusercontent.com/88313112/199234224-e4a85832-4ec7-4048-ad42-409647e45600.mov
