### ISSUE TITLE
[PAGE ISSUE]: 'Fetch data from the internet'

### ISSUE THREAD

**Issue by RiRa12621** [flutter/website#7716]
### Page URL

https://docs.flutter.dev/cookbook/networking/fetch-data/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/networking/fetch-data.md

### Describe the problem

```
Future<Album> fetchAlbum() async {
  final response = await http
      .get(Uri.parse('https://jsonplaceholder.typicode.com/albums/1'));
```

in the final example is called as

```
        body: Center(
          child: FutureBuilder<Album>(
            future: futureAlbum,
            builder: (context, snapshot) {
```

### Expected fix

```
        body: Center(
          child: FutureBuilder<Album>(
            future: fetchAlbum,
            builder: (context, snapshot) {
            ```

**Comment by danagbemava-nc** [comment]
Hi @RiRa12621, the example is not wrong. 

In step 4 `futureAlbum` is assigned the value of `fetchAlbum`. See https://docs.flutter.dev/cookbook/networking/fetch-data#4-fetch-the-data

```dart
 late Future<Album> futureAlbum;

  @override
  void initState() {
    super.initState();
    futureAlbum = fetchAlbum();
  }
```

As such I'll be closing this issue. 

Thank you

**Comment by RiRa12621** [comment]
That's my bad, clearly.
Thanks for clarifying. Sorry for the noise.
