### ISSUE TITLE
[PAGE ISSUE]: 'Implicit animations' error word

### ISSUE THREAD

**Issue by nickppbd** [flutter/website#7720]
### Page URL

https://docs.flutter.dev/codelabs/implicit-animations/

### Page source

https://github.com/flutter/website/tree/main/src/codelabs/implicit-animations.md

### Describe the problem

"Change the **Container** widget to an AnimatedOpacity widget: "

### Expected fix

"Change the **Column** widget to an AnimatedOpacity widget: "

**Comment by danagbemava-nc** [comment]
The problematic line is in https://docs.flutter.dev/codelabs/implicit-animations#1-pick-a-widget-property-to-animate
