### ISSUE TITLE
[PAGE ISSUE]: 'Implicit animations' error word

### ISSUE THREAD

**Issue by nickppbd** [flutter/website#7721]
### Page URL

https://docs.flutter.dev/codelabs/implicit-animations/

### Page source

https://github.com/flutter/website/tree/main/src/codelabs/implicit-animations.md

### Describe the problem

To do this, change opacity state using the onPressed() handler for **TextlButton**

### Expected fix

To do this, change opacity state using the onPressed() handler for **TextButton**

**Comment by danagbemava-nc** [comment]
The error is in https://docs.flutter.dev/codelabs/implicit-animations#4-set-up-a-trigger-for-the-animation-and-choose-an-end-value
