### ISSUE TITLE
[PAGE ISSUE]: 'Take a picture using the camera'

### ISSUE THREAD

**Issue by alejop153** [flutter/website#7727]
### Page URL

https://docs.flutter.dev/cookbook/plugins/picture-using-camera/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/plugins/picture-using-camera.md

### Describe the problem

The documentation works for web while you are in debug mode, but when you build for web the permission to open camera is never asked. It doesn't work.

### Expected fix

I don't know how to fix it. I'm stucked.

### Additional context

Please complete the documentation for web developers

**Comment by danagbemava-nc** [comment]
Hi @alejop153, do you see any errors in your console? 

What version of flutter are you using and what version of camera are you using as well?
