### ISSUE TITLE
[PAGE ISSUE]: 'Animations tutorial' error word

### ISSUE THREAD

**Issue by nickppbd** [flutter/website#7733]
### Page URL

https://docs.flutter.dev/development/ui/animations/tutorial/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/animations/tutorial.md

### Describe the problem

The current value of the Animation object can be found in the .value **method**

### Expected fix

The current value of the Animation object can be found in the .value

### Additional context

I do not know well what it is supposed to be.

**Comment by danagbemava-nc** [comment]
Hi @nickppbd, can you point out the exact places in the documentation that is not clear to you?

Thank you

**Comment by nickppbd** [comment]
@danagbemava-nc 

https://docs.flutter.dev/development/ui/animations/tutorial#tween

A Tween object does not store any state. Instead, it provides the evaluate(Animation<double> animation) method that applies the mapping function to the current value of the animation. The current value of the Animation object can be found in the .value method

**Comment by danagbemava-nc** [comment]
Thanks for the clarification

**Comment by sfshaza2** [comment]
Perhaps it would be clearer if the text said "`Animation.value` method" and linked to its [API page](https://api.flutter.dev/flutter/animation/Animation/value.html).

**Comment by nickppbd** [comment]
@sfshaza2 I did not realize that .value is a method. I am sorry!

**Comment by sfshaza2** [comment]
no problem!
