### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by anoop-anilkumar** [flutter/website#7734]
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

The code is the page contains errors. When I tried to follow the tutorial on the step1 : Create the starter flutter App, the below mentioned error came. It was a code error. And i'm stuck at the first step . Hope for a fast reply
'super' can't be used as an identifier because it's a keyword.
Try renaming this to be an identifier that isn't a keyword.dart(expected_identifier_but_got_keyword)
Visual Studio Code is my IDE

### Additional context

```dart
// Copyright 2018 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Welcome to Flutter'),
        ),
        body: const Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}
```

**Comment by danagbemava-nc** [comment]
Hi @anoop-anilkumar, what version of flutter are you on? I tested the code sample and I do not get any errors from vscode.

**Comment by anoop-anilkumar** [comment]
I just downloaded the flutter sdk
I'm getting error on the 'super' .I run the application on browser.

**Comment by danagbemava-nc** [comment]
Hi @anoop-anilkumar, what version of flutter did you install?

**Comment by sfshaza2** [comment]
@anoop-anilkumar, I see the same thing as @danagbemava-nc. This code works. You can test it on [DartPad](https://dartpad.dev/?), our in-browser playground. I pasted the exact code you provided and clicked Run. It ran fine.

I suspect that you either don't have the latest stable version of Flutter/Dart OR your IDE doesn't have the Dart/Flutter plugins installed.

**Comment by matteo-bombelli** [comment]
hello error on the same page/code (updated just before this message):

![image](https://user-images.githubusercontent.com/15176885/201494149-38767c8e-096e-4e02-9f08-fe7210eacb6f.png)

Flutter 3.3.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 52b3dc25f6 (4 days ago) • 2022-11-09 12:09:26 +0800
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0

**Comment by matteo-bombelli** [comment]
vs code plugin v3.52.0

**Comment by danagbemava-nc** [comment]
Hi @matteo-bombelli, you need to remove the const from the `Center` widget.

**Comment by sfshaza2** [comment]
Thanks, @danagbemava-nc. Closing.
