### ISSUE TITLE
[PAGE ISSUE]: 'Widget catalog'

### ISSUE THREAD

**Issue by Piyaphartoi** [flutter/website#7735]
### Page URL

https://docs.flutter.dev/development/ui/widgets/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/widgets/index.md

### Describe the problem

https://docs.flutter.dev/development/ui/widgets/

### Expected fix

[PAGE ISSUE]: 'Widget catalog'

### Additional context

https://github.com/flutter/website/tree/main/src/development/ui/widgets/index.md

**Comment by danagbemava-nc** [comment]
Hi @Piyaphartoi, what exactly is the issue you're experiencing on this page?

**Comment by sfshaza2** [comment]
Yeah, no issues listed. Closing.
