### ISSUE TITLE
[PAGE ISSUE]: 'Example does not run in TabController.'

### ISSUE THREAD

**Issue by UserY1** [flutter/website#7738]
### Page URL

https://docs.flutter.dev/development/ui/widgets/material/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/widgets/material.md

### Describe the problem

Example does not run in TabController.
https://api.flutter.dev/flutter/material/TabController-class.html
"Error compiling to Javascript"

**Comment by danagbemava-nc** [comment]
Closing this in favor of https://github.com/flutter/flutter/issues/114795
