### ISSUE TITLE
Remove bitcode references

### ISSUE THREAD

**Issue by jmagman** [flutter/website#7748]
### Page URL

https://docs.flutter.dev/resources/faq#how-big-is-the-flutter-engine

### Describe the problem

Some notes that bitcode is being removed were added as part of https://github.com/flutter/website/pull/7623.  

### Expected fix

Remove references to bitcode once https://github.com/flutter/flutter/pull/112831 (available in 3.4.0-37.0.pre) is in stable.  Includes the "The release engine binary includes LLVM IR (bitcode)" paragraph in https://docs.flutter.dev/resources/faq#how-big-is-the-flutter-engine

### Additional context

Part of https://github.com/flutter/flutter/issues/107887

**Comment by sfshaza2** [comment]
Yes, bitcode is deprecated. In fact, the second-to-last paragraph ends with the following sentence: "Note bitcode has been deprecated and will be removed from Flutter in a future release." Assuming that it's ok with @jmagman, I'd be fine with deleting this paragraph, but maybe keeping the note. Though it should be put in an official liquid note format.

**Comment by jmagman** [comment]
> Yes, bitcode is deprecated. In fact, the second-to-last paragraph ends with the following sentence: "Note bitcode has been deprecated and will be removed from Flutter in a future release." 

I added that in https://github.com/flutter/website/pull/7623

> Assuming that it's ok with @jmagman, I'd be fine with deleting this paragraph, but maybe keeping the note. Though it should be put in an official liquid note format.

My suggestion was to wait until https://github.com/flutter/flutter/pull/112831 (available in 3.4.0-37.0.pre) is in stable.  Once that happens we don't even need the note.

**Comment by sfshaza2** [comment]
SG!

**Comment by jmagman** [comment]
This is complete, thanks @sfshaza2! https://github.com/flutter/website-private/pull/130
