### ISSUE TITLE
[PAGE ISSUE]: 'Test drive'

### ISSUE THREAD

**Issue by brettatoms** [flutter/website#7750]
### Page URL

https://docs.flutter.dev/get-started/test-drive/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/test-drive/index.md

### Describe the problem

On Firefox clicking on tabs changes the url hash but doesn't load the tab content.  Works ok on Chrome.

<img width="641" alt="Screen Shot 2022-11-10 at 6 30 25 PM" src="https://user-images.githubusercontent.com/332554/201227636-c13a2b1a-9616-4f4b-9331-82f4aba131a4.png">

**Comment by danagbemava-nc** [comment]
Hi @brettatoms, was the page fully loaded when you tried to navigate between the tabs? It works just fine for me on firefox. See the recording below

<detail>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/201330852-7c7dc334-a305-49fc-9acb-4915dfcae4af.mov
</details>

**Comment by brettatoms** [comment]
@danagbemava-nc Yes it was fully loaded and also the nav tree on the left wouldn't collapse/expand.  With that said it seems to be working fine now so I'm not sure what the problem was. 🤷
