### ISSUE TITLE
[PAGE ISSUE] `BoxShape enum` page Not Found

### ISSUE THREAD

**Issue by 321paranoiawhy** [flutter/website#7751]
### Page URL

https://docs.flutter.dev/get-started/flutter-for/web-devs#making-circles-and-ellipses

### Page source

https://api.flutter.dev/flutter/painting/BoxShape-class.html

### Describe the problem

Hey, I found that link to [BoxShape enum](https://api.flutter.dev/flutter/painting/BoxShape-class.html) page in [this page](https://docs.flutter.dev/get-started/flutter-for/web-devs#making-circles-and-ellipses) was not found. Is there something error or it has been moved to another url? Hope your reply.

### Expected fix

Please check it.

**Comment by danagbemava-nc** [comment]
The url is supposed to be https://api.flutter.dev/flutter/painting/BoxShape.html 

Thanks for pointing that out

**Comment by sfshaza2** [comment]
Yup, a very straightforward fix.

**Comment by danagbemava-nc** [comment]
Closing this since the link has been fixed in #7819
