### ISSUE TITLE
Flutter UI Succinctly

### ISSUE THREAD

**Issue by ed-freitas** [flutter/website#7752]
Hi friends, maybe you'd like to add **Flutter UI Succinctly** to the list of Flutter books. Cheers.

https://www.syncfusion.com/succinctly-free-ebooks/flutter-ui-succinctly

**Comment by sfshaza2** [comment]
PRs welcome

**Comment by piedcipher** [comment]
I think this issue can be closed as:

https://github.com/flutter/website/pull/8388#issuecomment-1467105321

**Comment by parlough** [comment]
Thanks for the cool book and the issue!

However, after taking a look, it is covering a version of Flutter before Flutter 2/3 and null safety, so we likely can't include it for now. If/once it's updated to a more recent version, we'd be happy to include it though :) 

Thanks again!
