### ISSUE TITLE
Add-to-app has no information about Flutter v2, and minimum Android version.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/website#7762]
Currently, the docs talk about Flutter v1.12, v1.17, and v1.26: https://flutter.dev/docs/development/add-to-app. This is all not relevant anymore. 

And there is no information about minimum Android version. Is it still APIv16? Add-to-app is kind of outside of "normal" Flutter use, so maybe there is a difference about minimum Android versions? I don't know. By talking about old Flutter versions the add-to-app docs don't seem up to date, so after reading those I am not feeling confident that's still APIv16 just because it doesn't say anything about it. I'd prefer the docs clearly stated that fact, if that's the case.

I propose:

* The docs should be updated to explain what is possible with Flutter v2, and remove all references to old Flutter versions. 
* In the add-to-app introduction, list the minimum Android version which is supported for add-to-app.

Also, here: https://flutter.dev/docs/development/add-to-app/android/project-setup the "abiFilters" link is broken.

**Comment by atsansone** [comment]
This information is current with no reference to Flutter 1 or 2. The link was also fixed. Closing this issue.
