### ISSUE TITLE
Feature request - link to release notes/changelog from the website

### ISSUE THREAD

**Issue by osaxma** [flutter/website#7764]
The Flutter Website [Release Note Section](https://flutter.dev/docs/development/tools/sdk/release-notes) refers to the following [Hotfixes to the Stable Channel](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel) for information about bug-fix releases. Though it appears the wiki-page hasn't been updated since January 26th. 

Please consider updating the wiki regularly. 

Or even better, please consider providing a hyperlink to the notes in the [Flutter SDK Releases tables](https://flutter.dev/docs/development/tools/sdk/releases) such as:

<img width="998" alt="Screen Shot 2021-03-13 at 11 57 45 AM" src="https://user-images.githubusercontent.com/46427323/111025203-b0b6e580-83f3-11eb-9f7b-a9a9ca84ca75.png">

**Comment by atsansone** [comment]
This work has been completed in #6406 . Closing issue.

**Comment by parlough** [comment]
This work hasn't been completed yet, that issue was closed as a duplicate to this one.

**Comment by atsansone** [comment]
It has been completed, because the Release Notes page does link out to breaking changes and the changelogs since 2022 and the [wiki page listed](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel) has been kept up to date as well. Closing issue.

**Comment by parlough** [comment]
@atsansone I introduced those links more as a stop gap, the most important of this issue is discussing linking from a specific release to its release notes in the archive. I still think that's important, worth tracking, and implementing.
