### ISSUE TITLE
Inconsistent code text color and wrong lines commented

### ISSUE THREAD

**Issue by KushalBeniwal** [flutter/website#7765]
Affected page: https://codelabs.developers.google.com/codelabs/first-flutter-app-pt1#5

![Screenshot (13)](https://user-images.githubusercontent.com/55043173/110784788-230eb500-8290-11eb-9b05-bdcedaf7e9e5.png)
![Screenshot (12)](https://user-images.githubusercontent.com/55043173/110784813-2a35c300-8290-11eb-8bb3-9bd4acd1bc6e.png)

**Comment by parlough** [comment]
The integer division operator does not seem to be breaking syntax highlighting on the codelab site anymore. I'm going to close this but if anyone experiences a similar issue, feel free to respond here. Thanks again for reporting this!
