### ISSUE TITLE
Showcase page of flutter.dev needs updating

### ISSUE THREAD

**Issue by workerbee22** [flutter/website#7766]
During the Flutter Engage Keynote on 3.3.2021, I noticed many Google apps were presented that are using Flutter. 

Stadia was one of these that is listed on the I noticed the https://flutter.dev/showcase page. But most of the others shown are not listed on https://flutter.dev/showcase page. 

I'm wondering how long has it been since this page content was refreshed, and therefore are other 'key' apps not listed?

**Comment by domesticmouse** [comment]
@atsansone Maybe this isn't the right repo for this issue. This repo doesn't contain the referenced URL and I believe that page has been updated since this issue was raised. I'd vote to just close out this bug.

**Comment by sfshaza2** [comment]
Let me chuck it to Kelvin. That's what we're supposed to do, since there is
no other way to file bugs publicly on the marketing repo.

**Comment by sfshaza2** [comment]
I discussed it with marketing. I was told that it should be closed.
