### ISSUE TITLE
Add some screenshots for how to run profile / release in IDEs

### ISSUE THREAD

**Issue by xster** [flutter/website#7768]
Could be in https://flutter.dev/docs/testing/build-modes.

Show the Android Studio Flutter module commands. Also show Android Studio's Android Build Variant pane and Xcode's build configuration drop down in the scheme editor.

**Comment by atsansone** [comment]
These screenshots exist on the [Android](https://docs.flutter.dev/deployment/android) and [iOS](https://docs.flutter.dev/deployment/ios) build and release pages. Another part of this issue is covered on the [Flavors](https://docs.flutter.dev/deployment/flavors) page. Closing this issue.
