### ISSUE TITLE
Official guidance on "prefer_const_constructors" lint

### ISSUE THREAD

**Issue by enetor** [flutter/website#7771]
This is a documentation/style guide request.

The existing lint rule `prefer_const_constructors` warns if `const` is not used to instantiate a const constructor when it can. The official [style guide](https://dart.dev/guides/language/effective-dart) does not specify this.

I may be missing something. Since many Flutter devs consider this a best practice, maybe it should be mentioned in the official style guide?

**Comment by sfshaza2** [comment]
I believe this belongs on the dart website repo. Moving.

**Comment by parlough** [comment]
Thanks for the issue and the discussion here. I'm going to close this as [Performance best practices](https://docs.flutter.dev/perf/best-practices#control-build-cost) now discusses using `const` and enabling this lint through the recommended `flutter_lints` linter rule set. Thanks again!
