### ISSUE TITLE
Document how to specify targets in add-to-app host apps

### ISSUE THREAD

**Issue by ngminhduong** [flutter/website#7772]
I tried to integrate flutter module into our existing project.
I have some update some file in .ios folder ex: podfile.
Sometime it was regenerate when i run flutter packages get. So that my configurations was override.
Have anyway to stop it?
Thanks,

**Comment by atsansone** [comment]
This has been [documented](https://docs.flutter.dev/add-to-app/ios/project-setup#option-a---embed-with-cocoapods-and-the-flutter-sdk). Closing this issue.
