### ISSUE TITLE
Explain that a grey screen on release means an error and how to find the error

### ISSUE THREAD

**Issue by pedro371** [flutter/website#7773]
Hello guys,

I have made an App which works on the simulator and also on my iPhone (connected with a cable) but when I upload the app via Xcode to appstoreconnect and install the app via TestFlight is the screen grey. 

I have made this experience with 2 Flutter apps.

#### App 1:

<img src="https://user-images.githubusercontent.com/46385595/77823286-3dd92f80-70fa-11ea-8244-6426f51b9673.PNG" width="50%">

#### App 2:

<img src="https://user-images.githubusercontent.com/46385595/77823294-49c4f180-70fa-11ea-8e07-7c349687d3d7.png" width="50%">

```terminal
Flutter doctor -v: 

[✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.15.3 19D76, locale
    de-DE)
    • Flutter version 1.16.3 at
      /Users/pp/Documents/workspace/flutter
    • Framework revision be3a4b37b3 (2 days ago), 2020-03-26 18:08:05
      -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/pp/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

 
[✓] Connected device (2 available)            
    • Chrome     • chrome     • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by Naaidrv** [comment]
What widgets are you using?
If you are using the "stack" widget sometimes causes that gray screen, I recommend you to change it or remove it.
Good luck! :D

**Comment by Naaidrv** [comment]
What widgets are you using?
If you are using the "stack" widget sometimes causes that gray screen, I recommend you to change it or remove it.
Good luck! :D

**Comment by raj457036** [comment]
We are also experiencing the same thing but logging in release mode is a bit no-no for us.

For local crash recording you can use **flutter_pipeline**.

You can try to use [flutter_pipeline](https://pub.dev/packages/flutter_pipeline) to record crashes even in release mode.

Good Day!

**Comment by mazud21** [comment]
> You know the red error screen that you get when developing? When you build in release mode flutter replaces that with a gray screen.

I'll noted it, thanks @lukepighetti
