### ISSUE TITLE
Flutter Web, there is no explanation for testing, README.md

### ISSUE THREAD

**Issue by icatalud** [flutter/website#7779]
Missing testing information in the README.md.

I can see that they use the flutter_web_test package in the flutter_web package, however when I try to use the same package in my tests, it fails from the start when using the command 'flutter test' because it complains about the missing the flutter_test (not web) dependency.

How can the tests in the flutter_web package be run?

**Comment by atsansone** [comment]
Flutter web testing is explained on the [integration testing page](https://docs.flutter.dev/cookbook/testing/integration/introduction#5b-web). Closing this issue.
