### ISSUE TITLE
Make integration via Android FlutterView easier

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/website#7785]
Publish a website guide that explains how to use Flutter with a FlutterView on Android.

FlutterView is the finest grained, and almost most tedious approach to including Flutter in an Android app.  There are some cases where a FlutterView is the only option, e.g., within a ListView or RecyclerView.  There may also be some other edge cases where a developer needs to place Flutter within the View hierarchy but cannot otherwise use a Fragment.  These are the cases for a FlutterView.

A FlutterView will require a number of signals forwarded from the Activity level, as well as many lifecycle calls that either originate at the Activity or Fragment level.

Please ensure that this guide is written against the newest version of the Android embedding.

**Comment by xster** [comment]
I think the docs are sufficient for now. Closing
