### ISSUE TITLE
Add Guide about adding Flutter to an app within a ListView or RecyclerView

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/website#7786]
Publish a website guide that explains how to use Flutter within a ListView and RecyclerView in Android.

This guide is essentially a specialization of the FlutterView guide (#21847).  You may choose to combine them, or draft them separately.  The fundamental integration of the FlutterView will be the same - the difference in the case of a ListView and RecyclerView is that developers must go one step further to place their FlutterView within a ListAdapter or RecyclerView.Adapter.

Please ensure that this guide is written against the newest version of the Android embedding.

**Comment by atsansone** [comment]
This issue is almost 5 years old and relevant to a version of Flutter no longer supported or documented. If this issue has not been resolved, please file a new issue with details consistent with the current docs site. Thanks!

Closing this issue.
