### ISSUE TITLE
Website Guide: Adding Flutter to an iOS app within a non-fullscreen ViewController

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/website#7787]
Publish a website guide that explains how to use Flutter with a non-fullscreen FlutterViewController on iOS.

The use of a FlutterViewController is generally the same as the fullscreen case (#21845) except that the developer will need to do some layout work in the parent ViewController, and will also need to register the FlutterViewController with its parent ViewController.

Please ensure that this guide is written against the newest version of the iOS embedding.

**Comment by atsansone** [comment]
This was completed in https://github.com/flutter/website/pull/3363. Closing this issue.
