### ISSUE TITLE
Website Guide: Adding Flutter to an iOS app within a UITableView

### ISSUE THREAD

**Issue by matthew-carroll** [flutter/website#7788]
Publish a website guide that explains how to use Flutter within a UITableView on iOS.

Like other integrations, integrating with a UITableView primarily comes down to utilizing a FlutterViewController.  The added wrinkle in this use-case is that the FlutterViewController needs to be embedded with a UITableViewCell.

Please ensure that this guide is written against the newest version of the iOS embedding.

**Comment by atsansone** [comment]
This issue is almost 5 years old and relevant to a version of Flutter no longer supported or documented. If this issue has not been resolved, please file a new issue with details consistent with the current docs site. Thanks!

Closing this issue.
