### ISSUE TITLE
Use more named and explicit imports in examples

### ISSUE THREAD

**Issue by alexkrolick** [flutter/website#7798]
As a Flutter newbie it's pretty confusing when APIs are called without being able to tell which library is providing them. It would be helpful to use more named and explicit imports in the examples:

```dart
import 'package:flutter/material.dart' show
  AppBar,
  MaterialApp,
  Scaffold,
  StatelessWidget;
```

**Comment by sfshaza2** [comment]
That sounds ok to me, but I would like @domesticmouse, @johnpryan, and/or @khanhnwin to weigh in.

**Comment by domesticmouse** [comment]
I concur with @miquelbeltran's plan

**Comment by miquelbeltran** [comment]
I've implemented the changes proposed in the samples and codelabs repos. Do you think we need more examples out there, or this would be enough?

**Comment by domesticmouse** [comment]
Closing this out for now. @alexkrolick feel free to comment if there is something else you'd like us to look at!
