### ISSUE TITLE
Link layout API docs to related animation API docs and tutorials 

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#7799]
As the Animation UX study shows, the knowledge about layout widgets are important to implement certain animation patterns. For example, knowing `Stack` and `Positioned` is important to implement an animation in which an object flies from one place to another. We need to better understand such interdependence between animation patterns and layout APIs, and cross-link them.

**Comment by atsansone** [comment]
@InMatrix : Do you have specific touchpoints that need updates?

**Comment by InMatrix** [comment]
This issue is likely to be stale at this point. The root problem was (and might still be) that our animation docs are more API-oriented than task-oriented. We can mitigate this problem once we expose the cookbook content in the left nav. However, I think the whole section needs to be refreshed to include some newer approaches such as using the [flutter_animate](https://pub.dev/packages/flutter_animate) package.

**Comment by atsansone** [comment]
@InMatrix : I'll close this issue, then. If we want to explore your broader changes, we should file a new issue.
