### ISSUE TITLE
[Website] `master-api.flutter.dev` uses `https://stable.api.dartpad.dev` cause exceptions

### ISSUE THREAD

**Issue by AlexV525** [flutter/website#7802]
## Step to reproduce

1. Visit https://master-api.flutter.dev/flutter/material/SelectionArea-class.html
2. Click "Run" in the dartpad example.
3. The request to `https://stable.api.dartpad.dev/api/dartservices/v2/compileDDC` returns 400 because `SelectionArea` is not defined in the stable branch.

**Comment by parlough** [comment]
Specifying the channel for DartPad was implemented in https://github.com/flutter/flutter/pull/115018
