### ISSUE TITLE
Doc on docs.flutter.io is incomplete

### ISSUE THREAD

**Issue by cphoenix-google** [flutter/website#7806]
The doc in docs.flutter.io seems to be copied, but with some pages missing, from pub.dartland.org.

https://docs.flutter.io/flutter/package-async_async/StreamQueue-class.html seems to be a copy of
https://pub.dartlang.org/documentation/async/latest/async/StreamQueue-class.html

However, neither page tells what 'import' statement is needed to use StreamQueue.

That information is on https://pub.dartlang.org/packages/async#-installing-tab-
But docs.flutter.io has no corresponding page.

IMO, any page with a code example should also include, on that same page (perhaps even within that same example) the import statements needed to use the code. Or at least, a very clear link to the needed information. (On the pub.dartlang.org site, the information is several non-obvious clicks away.)

**Comment by sfshaza2** [comment]
Rather than spend time on this, I'm going to close. These URL links aren't even valid anymore. If this problem still exists, please open a new issue and use current links.
