### ISSUE TITLE
Document how to run Travis scripts locally for testing/fixing build issues of Website

### ISSUE THREAD

**Issue by DanTup** [flutter/website#7808]
Recently there have been some website builds break as a result of changes in Flutter (eg. deprecating constants). Since the website doesn't rebuild on flutter changes but does pull flutter, this means the next push to the website will fail (and may not be related to the change made).

To debug these (for ex. flutter/flutter#16153) it'd be useful to be able to run the Travis script locally (since the build is slow, shotgun fixing by pushing to Travis is tedious) however when I tried to run it manually it seemed to fail:

```text
Running "flutter packages get" in animate1...                0.5s
Run flutter analyze on _includes/code/animation/animate1

ProcessException: No such file or directory
  Command: /usr/bin/xcodebuild -project /Users/dantup/Dev/Google/flutter-website/ios/Runner.xcodeproj -target Runner -showBuildSettings
```

I had a scan through the scripts, but I couldn't figure out where that ios folder was supposed to come from.

**Comment by khanhnwin** [comment]
Please correct me if I'm wrong, but I don't think this issue is relevant anymore. This Issue looks to have been filed against old infrastructure that's no longer being used (Travis).

**Comment by sfshaza2** [comment]
Oh, right. We definitely don't use Travis anymore. Closing.
