### ISSUE TITLE
Update documentation for DevTools > Memory

### ISSUE THREAD

**Issue by polina-c** [flutter/website#7830]
### What information is missing?

Documentation about memory concepts and new features is missing

### How would you like us to fix this problem?

The draft: http://go/using-memory-view-wording

**Comment by kenzieschmoll** [comment]
@sfshaza2 @atsansone  would it make sense to add a 'devtools-request' label that we could tag our docs requests with?

**Comment by sfshaza2** [comment]
Absolutely, if you find it useful!!

**Comment by polina-c** [comment]
PR: https://github.com/flutter/website/pull/7885

**Comment by polina-c** [comment]
Additional content to add after the previous PR merge: go/wording-for-memory-screen-target

**Comment by sfshaza2** [comment]
I _believe_ that this is fixed. Re-open if I'm wrong.

**Comment by polina-c** [comment]
yes, thank you!
