### ISSUE TITLE
[PAGE ISSUE]: 'Persist data with SQLite'

### ISSUE THREAD

**Issue by Severino** [flutter/website#7876]
### Page URL

https://docs.flutter.dev/cookbook/persistence/sqlite/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/persistence/sqlite.md

### Describe the problem

There are code examples but no explanation of which file to put them in.

### Expected fix

Add the default filenames for where the code examples belong.

**Comment by danagbemava-nc** [comment]
This example only uses a `main.dart` file so that should be enough, but it could be made clearer that the code goes into that file.

**Comment by Severino** [comment]
Thanks for the fast reply. In the end, I managed to figure out to put the dependencies in the 'pubspec.yaml' and the 'main.dart' files. I now saw that this approach is common with the flutter examples. For brand-new users, it's a bit confusing.
