### ISSUE TITLE
[PAGE ISSUE]: 'Send data to a new screen'

### ISSUE THREAD

**Issue by noodles** [flutter/website#7891]
### Page URL

https://docs.flutter.dev/cookbook/navigation/passing-data/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/navigation/passing-data.md

### Describe the problem

The [Interactive Example](https://docs.flutter.dev/cookbook/navigation/passing-data#interactive-example) is showing 451 issues and won't run. 

![Uploading Screenshot 2022-12-01 at 10.11.46 am.png…]()

### Expected fix

It looks like the SDK needs to be updated or relinked. Not really sure how the interactive example work but that's my guess.

**Comment by danagbemava-nc** [comment]
Hi @noodles, it looks like your screenshot wasn't uploaded. Can you share the errors you get? I just tried it and the example works, it took a while load, but it worked.


https://user-images.githubusercontent.com/88313112/205055398-997fede7-8a7d-40db-a03c-7c948f336bab.mov

**Comment by danagbemava-nc** [comment]
Hi @noodles, does the screenshot below show what you see on the site? 

I got this after I refreshed the page

<img src="https://user-images.githubusercontent.com/88313112/205058225-eb9fff7b-a376-4a55-bf44-d269e3e5ae5e.png" />

**Comment by noodles** [comment]
@danagbemava-nc 

> does the screenshot below show what you see on the site?

That's correct

**Comment by parlough** [comment]
Fixed by https://github.com/flutter/website/commit/eb2d692b4ee0a406f74c0d04b88fc529121d8f2a
