### ISSUE TITLE
Introduction to widget: [PAGE ISSUE]: 'Install'

### ISSUE THREAD

**Issue by anant510** [flutter/website#7892]
### Page URL

https://docs.flutter.dev/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/index.md

### Describe the problem

<span class="kwd">import</span><span class="pln"> </span><span class="str">'package:flutter/material.dart'</span><span class="pun">;</span><span class="pln">

</span><span class="kwd">void</span><span class="pln"> main</span><span class="pun">()</span><span class="pln"> </span><span class="pun">{</span><span class="pln">
  runApp</span><span class="pun">(</span><span class="pln">
    </span><span class="kwd">const</span><span class="pln"> </span><span class="typ">Center</span><span class="pun">(</span><span class="pln">
      child</span><span class="pun">:</span><span class="pln"> </span><span class="typ">Text</span><span class="pun">(</span><span class="pln">
        </span><span class="str">'Hello, world!'</span><span class="pun">,</span><span class="pln">
        textDirection</span><span class="pun">:</span><span class="pln"> </span><span class="typ">TextDirection</span><span class="pun">.</span><span class="pln">ltr</span><span class="pun">,</span><span class="pln">
      </span><span class="pun">),</span><span class="pln">
    </span><span class="pun">),</span><span class="pln">
  </span><span class="pun">);</span><span class="pln">
</span><span class="pun">}</span>

### Expected fix

show this error on running app platform. please solve the issue

**Comment by danagbemava-nc** [comment]
Hi @anant510, what error are you seeing? I tested the code sample you posted above and it works just fine. 

<img src="https://user-images.githubusercontent.com/88313112/205057238-3c7ad798-4609-4c64-870b-c6070e4c667e.png" width="350"/>

**Comment by anant510** [comment]
![Screenshot_2022-12-02-06-41-47-159_com android chrome](https://user-images.githubusercontent.com/45393436/205296960-9299567b-c49c-406d-83b2-7d6314d40404.jpg)

**Comment by anant510** [comment]
The code seems inappropriate

**Comment by danagbemava-nc** [comment]
This issue is being tracked in https://github.com/flutter/website/issues/7894. 

Closing from here as duplicate. 

Thank you
