### ISSUE TITLE
[PAGE ISSUE]: 'Using Actions and Shortcuts'

### ISSUE THREAD

**Issue by hootyjeremy** [flutter/website#7918]
### Page URL

https://docs.flutter.dev/development/ui/advanced/actions_and_shortcuts/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/advanced/actions_and_shortcuts.md

### Describe the problem

The example at the bottom of the page in the "putting it together" section seems to be bugged. The keyboard shortcuts seem to work but I cannot get the buttons to perform their operations. The `copy` button doesn't copy and the `select all` button doesn't select all.

**Comment by danagbemava-nc** [comment]
Hi @hootyjeremy, I just tested the example and it seems to work just fine. Is the issue that you do not see any visual indicator or that it doesn't do anything at all? If the latter, what version of flutter are you using? See the recording below

<details>
<summary>recording</summary>

https://user-images.githubusercontent.com/88313112/206459161-421eb06c-7b7d-4963-9e53-75a4b8b2fef3.mov
</details>

**Comment by hootyjeremy** [comment]
Ah ha. I think my confusion was that I was expecting the text to be selected as in a ctrl+a when you click the `select all` button. But I see that it works now. Thanks.
