### ISSUE TITLE
Images broken on the flutter.dev/community map

### ISSUE THREAD

**Issue by RedBrogdon** [flutter/website#7925]
### Page URL

https://flutter.dev/community#community-events

### Describe the problem

There's an iframed map of Flutter events on the flutter.dev/community page, and the marker images are currently broken:

![image](https://user-images.githubusercontent.com/969662/206559921-b87b32a2-9def-4877-bfd3-c1d352ddc6f9.png)

They're being loaded from this URL: 

https://events.flutter.dev/engage/assets/img/markers/map-marker-many@2x-1.png

which is currently redirecting to the https://flutter.dev/events page, resulting in a broken image.

### Expected fix

We need to find a better place to host the images, and get them linked into the map iframe properly.

**Comment by sfshaza2** [comment]
This has been passed off to marketing.

**Comment by parlough** [comment]
This has been fixed :)
