### ISSUE TITLE
[PAGE ISSUE]: 'Write your first Flutter app, part 1'

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#7932]
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

The code diff in Step 4.5 looks misaligned. For example, these two lines were deleted from line 30-21 and then added at line 54-55:
```dart
class RandomWords extends StatefulWidget
  const RandomWords({super.key});
```

These two lines didn't actually change between step 3 and step 4 as far as I can tell.

**Comment by exaby73** [comment]
I believe this issue can be fixed by moving the `State` class below the `StatefulWidget`. Labeling the issue
