### ISSUE TITLE
[PAGE ISSUE]: 'Use themes to share colors and font styles'

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#7937]
### Page URL

https://docs.flutter.dev/cookbook/design/themes/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/design/themes.md

### Describe the problem

this should include textTheme which woudl be a more common use case.
I tried and it did not work and i am stuck :(

```dart
const textTheme2 = const TextTheme(
  headline1: TextStyle(fontSize: 12.0, fontWeight: FontWeight.bold),
  headline6: TextStyle(fontSize: 2.0, fontStyle: FontStyle.normal),
  bodyText2: TextStyle(fontSize: 4.0, fontFamily: 'Hind'),
);

class MyHomePage extends StatelessWidget {
  final String title;

  const MyHomePage({super.key, required this.title});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Theme(
        data: Theme.of(context).copyWith(textTheme: textTheme2),
        child: Center(
          child: Container(
            color: Theme.of(context).colorScheme.primary,
            child: Text(
              'Text with a background color',
              style: Theme.of(context).textTheme.headline6,
            ),
          ),
        ),
      ),
    );
  }
}
```

See; https://stackoverflow.com/questions/74791767/how-do-i-override-scaffold-background-or-default-text-size-locally-in-flutter

**Comment by neiljaywarner** [comment]
`import 'package:flutter/material.dart';

void main() => runApp(MyApp());

const smallDefault = const TextTheme(bodyText2: TextStyle(fontSize: 15.0));
const bigDefault = const TextTheme(bodyText2: TextStyle(fontSize: 54.0));
var orangeBrown = ThemeData(scaffoldBackgroundColor: Colors.brown, textTheme: smallDefault, accentColor: Colors.orange);
var bluePink = ThemeData(scaffoldBackgroundColor: Colors.blue, textTheme: bigDefault, accentColor: Colors.pink);

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        title: 'Primary Text theme override',
        theme: orangeBrown,
        home: Scaffold(
            body: Center(
              child: Theme(
                data: bluePink,
                child: Text('?why small??'),
              ),
            ),
            floatingActionButton: Theme(
              data: bluePink,
              child: FloatingActionButton(
                onPressed: () {},
                child: const Icon(Icons.add),
              ),
            )),
      );
}`

**Comment by exaby73** [comment]
Hello @neiljaywarner. This is working as expected. The `context` you are using does not have the theme you applied. Change you code sample like this:

```dart
const textTheme2 = TextTheme(
  headline1: TextStyle(fontSize: 12.0, fontWeight: FontWeight.bold),
  headline6: TextStyle(fontSize: 2.0, fontStyle: FontStyle.normal),
  bodyText2: TextStyle(fontSize: 4.0, fontFamily: 'Hind'),
);

class MyHomePage extends StatelessWidget {
  final String title;

  const MyHomePage({super.key, required this.title});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Theme(
        data: Theme.of(context).copyWith(textTheme: textTheme2),
        child: Builder(builder: (context) {
          return Center(
            child: Container(
              color: Theme.of(context).colorScheme.primary,
              child: Text(
                'Text with a background color',
                style: Theme.of(context).textTheme.headline6,
              ),
            ),
          );
        }),
      ),
    );
  }
}
```

You can also extract to multiple widgets if you don't want to use the `Builder`. Basically, the problem here is that you are using a `context` above the `Theme`. By using `Builder`, the `context` you use is the `context` below the `Theme` and therefore you have access to that `ThemeData`. Hope this makes sense :)

If you have issues with you code, might I suggest doing a search on Stackoverflow or for asking questions like this, you can find resources on https://flutter.dev/community.

But since this is not an issue with the documentation or Flutter, I am closing this issue. Thank you
