### ISSUE TITLE
Fix GoogleProviderConfiguration requires clientID on '7. Multiplatform Google Auth Sign In' page

### ISSUE THREAD

**Issue by pmagnuson** [flutter/website#7938]
### Page URL

https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#6

### Describe the problem

In the section "Add Google sign-in button", the code example for auth_gate.dart includes a widget - GoogleProviderConfiguration(),

This is incorrect as the GoogleProviderConfiguration widget requires a clientID parameter.  

### Expected fix

Provide information on the GoogleProviderConfiguration clientID parameter.   In particular, reference the Firebase Console to understand where this value is obtained.

**Comment by exaby73** [comment]
According to the [docs](https://pub.dev/documentation/flutterfire_ui/latest/auth/GoogleProviderConfiguration-class.html), `clientId` is a required parameter. Labeling the issue

**Comment by pmagnuson** [comment]
as a followup, I found that clientID parameter should be set differently for Android vs IOS.  I am using the following code:

```dart
GoogleProviderConfiguration(
  clientId: Platform.isAndroid
    ? ''
    // CLIENT_ID in ios/Google-Service-Info.plist
    : 'xxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com')
```

To my knowledge, this is not documented anywhere.  I do not know the settings for other platforms (Web, OSX)

**Comment by ericwindmill** [comment]
This was fixed via: https://github.com/flutter/flutter/issues/132658#issuecomment-1759572673
