### ISSUE TITLE
Codelab uses flutterfire_ui which is deprecated.

### ISSUE THREAD

**Issue by JerryEsteban** [flutter/website#7948]
### Page URL

https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#2

### Describe the problem

The codelab uses flutterfire_ui which is deprecated. See https://pub.dev/packages/flutterfire_ui

### Expected fix

Update codelab to specify correct packages.

**Comment by exaby73** [comment]
Hello @JerryEsteban. Looks like it's using the correct package. It's `firebase_ui` that's deprecated, not `flutterfire_ui`

**Comment by JerryEsteban** [comment]
Hi, thanks @exaby73 . In the "Add Firebase packages to Flutter app" section, there's a command listed:


flutter pub add flutterfire_ui


However, on the Flutter UI package link I listed earlier (https://pub.dev/packages/flutterfire_ui), it says it's deprecated. The instructions show how to replace flutterfire_ui imports with:

flutter pub add firebase_ui_auth

And (for oauth)

flutter pub add firebase_ui_oauth
flutter pub add firebase_ui_oauth_google

To be sure, would you please confirm which packages should be marked as deprecated?

**Comment by exaby73** [comment]
Okay I see that. Sorry about that. Labelling this issue

**Comment by sfshaza2** [comment]
@domesticmouse

**Comment by atsansone** [comment]
This duplicates https://github.com/flutter/website/issues/8667. Closing this issue.
