### ISSUE TITLE
Material 3 updates page

### ISSUE THREAD

**Issue by MiraMarshall** [flutter/website#7977]
### Page URL

docs.flutter.dev/development/ui/material3-updates/

### Describe the problem

TODO:

- Material 3 introduces a new color theming tool. This is WAY cool and should be covered by more than a single sentence.

- I wish the information was more clear. Like "Introduced in Flutter 3.3", "Introduced in next stable release" listed on individual features. It's almost impossible to follow this info from the linked GitHub issue. Though once all of MD3 is implemented, it won't really matter anymore.

- This needs approval from Hans, but I'd also like to say what's NOT yet included. For example, "The next stable release won't yet include Material 3 updates for date/time picker or ListTile." Or something to that effect. I'd put it in a note.
- Combine new and updated widget section.

**Comment by sfshaza2** [comment]
I've rewritten this page. Closing.
