### ISSUE TITLE
Point out packages that share assets on add_to_app docs

### ISSUE THREAD

**Issue by leighajarett** [flutter/website#7997]
### What information is missing?

There are some packages that allow you to share images and fonts from the native application to your Flutter screen. 

- [native_font](https://pub.dev/packages/native_font)
- [ios_platform_images](https://pub.dev/packages/ios_platform_images)

### How would you like us to fix this problem?

It would be great to include these packages in the docs so that developers know they don't need to add the assets in two places.

**Comment by sfshaza2** [comment]
We don't need to add explanation, as each package has docs on how to use.
