### ISSUE TITLE
Broken link with invitation to Slack community

### ISSUE THREAD

**Issue by absoftware** [flutter/website#8004]
### Page URL

https://flutter.dev/community

### Describe the problem

Broken link to Slack community. Please update to new one:
https://join.slack.com/t/fluttercommunity/shared_invite/zt-1maxtck8l-7a_qhMlnbTjtdG~~UbGV2g 

It's generated by Randal Schwartz and I got this on Discord.

**Comment by RandalSchwartz** [comment]
In theory, that's a new permalink invite.  I have no way to verify that.  But Slack said so. :)

**Comment by darshankawar** [comment]
Probably related / similar: https://github.com/flutter/website/issues/7990

**Comment by mynote** [comment]
Seems like a bug from Slack. [Reddit Post](https://www.reddit.com/r/Slack/comments/cmj56t/invite_link_set_to_never_expire_expired/)

**Comment by slightfoot** [comment]
It expires every with X number of people joining and we cant use the Slack API to automate the refreshing of the link as we don't have a paid for account. Please make sure I am told about this and I can refresh it. All fixed now.
