### ISSUE TITLE
[PAGE ISSUE]: 'Flutter for iOS developers' TOC is broken

### ISSUE THREAD

**Issue by parlough** [flutter/website#8019]
### Page URL

https://docs.flutter.dev/get-started/flutter-for/ios-devs/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/flutter-for/ios-devs.md

### Describe the problem

With the addition of the SwiftUI tab, the TOC now includes contents for both the SwiftUI and UIKit TOC at all times, leaving entries for the other tab in the TOC unfunctional but still present. This is especially problematic for the UIKit tab since its entries are way at the bottom.

### Expected fix

We should either hide the TOC or split the page into two or three pages.

I prefer splitting into multiple pages, as it allows there to still be a TOC which is pretty useful, but also allows for potentially better search results.

We could roll a custom TOC solution depending on which tab is open, but this would likely require more work.

### Additional context

\cc @leighajarett @sfshaza2

**Comment by sfshaza2** [comment]
Yes, if you click a Swift link, it only works if the Swift tab is selected. Ditto for UIKit links. (As per your "unfunctional but present" comment.) I'm open to fixing the TOC (an infrastructure approach) but, I agree, it might be better to just split it into 2 or 3 pages.

**Comment by leighajarett** [comment]
Thanks for flagging! I'm fine splitting it up into two pages. I am a bit swamped with Flutter Forward at the moment but can revisit in a few weeks, or if anyone wants to open up a PR in the meantime that would be great :)
