### ISSUE TITLE
[PAGE ISSUE]: 'Codelabs 

### ISSUE THREAD

**Issue by MrKennethYip** [flutter/website#8024]
### Page URL

https://docs.flutter.dev/codelabs/

### Page source

https://github.com/flutter/website/tree/main/src/codelabs/index.md

### Describe the problem

The WebView Flutter tutorial is out-dated and doesn't work. 

[Adding WebView to your Flutter app](https://codelabs.developers.google.com/codelabs/flutter-webview)
With the WebView Flutter plugin you can add a WebView widget to your Android or iOS Flutter app.

### Expected fix

Please add a note that this is out-dated and not working so new developers don't spend hours on end trying to figure out why the tutorial doesn't work. Alternatively, please make a note of the specific versions of the libraries it needs to work with if there is a way to get it to work with the older versions. 

### Additional context

This is a very poor first experience with Flutter.

**Comment by danagbemava-nc** [comment]
Hi @MrKennethYip, this issue was reported in https://github.com/flutter/flutter/issues/117808 and is being fixed currently. Sorry for any inconvenience. 

Closing this in favor of https://github.com/flutter/flutter/issues/117808.

**Comment by domesticmouse** [comment]
Codelab has been updated.
