### ISSUE TITLE
Add replacement for `flutter sdk-path` to 'Linux install' page'

### ISSUE THREAD

**Issue by angelcervera** [flutter/website#8025]
### Page URL

https://docs.flutter.dev/get-started/install/linux/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/linux.md

### Describe the problem

Executing this command:
```shell
$ flutter sdk-path
```

Returns this error:
```shell
flutter sdk-path                   
Could not find a command named "sdk-path".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

### Expected fix

If `sdk-path` is no more and option, replace the documentation with the right command.

BTW, which one is the command to replace it? Let me know, and I will be happy to create a PR.

### Additional context

```shell
➜  ~ flutter --version
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (2 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```

**Comment by danagbemava-nc** [comment]
Hi @angelcervera, did you install flutter via `snap`?

**Comment by angelcervera** [comment]
Hi @danagbemava-nc Yes, I did. In fact:
```
which flutter
/home/<my_user_id>/snap/flutter/common/flutter/bin/flutter
```
