### ISSUE TITLE
[PAGE ISSUE]: 'Cupertino (iOS-style) widgets'

### ISSUE THREAD

**Issue by EngHussam23** [flutter/website#8034]
### Page URL

https://docs.flutter.dev/development/ui/widgets/cupertino/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/widgets/cupertino.md

### Describe the problem

the run results are not showing up it says javascript error

**Comment by danagbemava-nc** [comment]
Hi @EngHussam23, what page specifically has the issue you're referring to? The page you have linked above contains just a list of widgets. There's no run on the page
