### ISSUE TITLE
[PAGE ISSUE]: 'Creating flavors for Flutter'

### ISSUE THREAD

**Issue by hedgeye-jmyers** [flutter/website#8038]
### Page URL

https://docs.flutter.dev/deployment/flavors/

### Page source

https://github.com/flutter/website/tree/main/src/deployment/flavors.md

### Describe the problem

In the section for "Using flavors in Android" it says that you can change the applicationId. The example shows the key applicationId. However, the value provided looks very much like a suffix ".free"

### Expected fix

It is more likely that the documentation wants to use the key applicationIdSuffix instead of applicationId.

**Comment by danagbemava-nc** [comment]
Thanks for catching this
