### ISSUE TITLE
Missing steps to host Flutter web app in Firebase

### ISSUE THREAD

**Issue by polina-c** [flutter/website#8043]
### Page URL

https://docs.flutter.dev/get-started

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/index.md

### Describe the problem

as Firebase became an official host for Flutter web, it will make sense to publish official steps 

For example, instead of three options here, have just one with fast and easy to follow steps:
https://docs.flutter.dev/deployment/web#deploying-to-the-web

**Comment by danagbemava-nc** [comment]
Hi @polina-c, there's an existing issue for this being tracked in https://github.com/flutter/website/issues/6770.

Closing this in favor of the issue linked above. 

Thank you
