### ISSUE TITLE
New First Flutter app codelab follow-up adjustments

### ISSUE THREAD

**Issue by parlough** [flutter/website#8054]
### Page URL

https://docs.flutter.dev/get-started/codelab/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/codelab.md

### Describe the problem

Now that there is a new Flutter app as part of the get-started path, a few locations which use or reference the code created in the old one need to be updated.

- [ ] [Testing accessibility on mobile](https://docs.flutter.dev/development/accessibility-and-localization/accessibility#testing-accessibility-on-mobile) relying on and referencing the old, created app and the [Accessibility Guideline API](https://api.flutter.dev/flutter/flutter_test/AccessibilityGuideline-class.html)
- [ ] The [Building layouts (step 0)](https://docs.flutter.dev/development/ui/layout/tutorial#step-0-create-the-app-base-code) tutorial which links to and references the old code/codelab
- [ ] The [Adding interactivity (step 0)](https://docs.flutter.dev/development/ui/interactive#step-0-get-ready) which also links to and references the old code/codelab

### Expected fix

These occurrences should be likely be updated to not reference the codelab at all and work without referencing it. Not all users are guaranteed to have done it and it's likely easier to just include some inline instructions.

\cc @filiph

**Comment by domesticmouse** [comment]
Hey @filiph, if you have time, I'd love you to look at this issue. Thanks!

**Comment by filiph** [comment]
Ah, good catch, @parlough! I'm on it.

**Comment by khanhnwin** [comment]
+1 to removing the references the codelab! As a temporary hold over, does it make sense to remove just the excerpts for now while the doc gets redone?

**Comment by filiph** [comment]
I made 3 PR that should be accepted in this order:

1. https://github.com/flutter/codelabs/pull/1339
1. https://github.com/flutter/website/pull/8087 (can skip, since 8088 below is built on 8087)
1. https://github.com/flutter/website/pull/8088

Oh, and I guess there should be another PR sometime between 1. and 3. that upgrades the submodule dependency of this repo on flutter/codelabs to a version after PR 1339.
