### ISSUE TITLE
Finish or remove 'Explicit animations' codelab

### ISSUE THREAD

**Issue by parlough** [flutter/website#8057]
### Page URL

https://docs.flutter.dev/codelabs/explicit-animations/

### Page source

https://github.com/flutter/website/tree/main/src/codelabs/explicit-animations.md

### Describe the problem

The codelab has been sitting uncompleted for a long time.

### Expected fix

It should either be finished or removed.

**Comment by atsansone** [comment]
@parlough : Recommend prioritizing for this quarter or removing as it's three years without completion. Thoughts?

**Comment by parlough** [comment]
It would be nice to get done, but I probably won't have the time to finish it this quarter. Perhaps someone else?
