### ISSUE TITLE
'맥OS에서 설치' page issue

### ISSUE THREAD

**Issue by minjcho** [flutter/website#8080]
Page URL: https://flutter-kr.io/docs/get-started/install/macos.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/macos.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue: The Flutter SDK download link is invalid on Korean page.

**Comment by parlough** [comment]
Hey @minjcho, thanks for opening an issue!

The flutter-kr site is maintained by community members and it looks like a lot of content has not been updated/synced in a while, resulting in the error. I recommend opening an issue on their repository: https://github.com/flutter-korea/website

Until they update their version of the site, the [install pages](https://docs.flutter.dev/get-started/install) on the official site should work well. Let us know if you have any issues there.
