### ISSUE TITLE
[PAGE ISSUE] '윈도우에서 설치' 

### ISSUE THREAD

**Issue by yemsu** [flutter/website#8093]
Page URL: https://flutter-kr.io/docs/get-started/install/windows.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/windows.md

Description of issue:

In Korean Document, the Flutter SDK download button is not working.
Windows, macOS, and Linux pages are all the same.

![image](https://user-images.githubusercontent.com/42016626/211437647-345658ba-b781-4958-9ee1-c9b3e8e2ce4a.png)

![image](https://user-images.githubusercontent.com/42016626/211437662-2c9d2b2d-ec6a-4dec-8d38-3e549b0a8067.png)

**Comment by parlough** [comment]
Hey @yemsu , thanks for opening an issue!

The flutter-kr site is maintained by community members and it looks like a lot of content has not been updated/synced in a while, resulting in the error. I recommend opening an issue on their repository: https://github.com/flutter-korea/website

Until they update their version of the site, the [install pages](https://docs.flutter.dev/get-started/install) on the official site should work well. Let us know if you have any issues there.
