### ISSUE TITLE
[PAGE ISSUE]: 'Creating flavors for Flutter'

### ISSUE THREAD

**Issue by hungps** [flutter/website#8096]
### Page URL

https://docs.flutter.dev/deployment/flavors/

### Page source

https://github.com/flutter/website/tree/main/src/deployment/flavors.md

### Describe the problem

The property `flavor` in the example of [Using flavors in Android](https://docs.flutter.dev/deployment/flavors#using-flavors-in-android) section is incorrect according to [Android documentation](https://developer.android.com/studio/build/build-variants#product-flavors)

### Expected fix

1. Changing `flavor` to `productFlavors` 
2. Adding `flavorDimensions` to resolve `Error: All flavors must now belong to a named flavor dimension.`

For example:
```
flavorDimensions "version"

productFlavors {
    free {
        dimension "version"
        resValue "string", "app_name", "free flavor example"
        applicationSuffix ".free"
    }
}
```

**Comment by sfshaza2** [comment]
@parlough, can you take a look?
