### ISSUE TITLE
Move note about download from GitHub on Windows installation page

### ISSUE THREAD

**Issue by AugustDG** [flutter/website#8099]
### Page URL

https://docs.flutter.dev/get-started/install/windows

### Page source

https://github.com/flutter/website/blob/main/src/get-started/install/_get-sdk-win.md

### Describe the problem

I find putting the note about the Flutter SDK repo before the steps creates a better flow. Also, for people that read more line-by-line, they won't download the zip file before realizing there's another way.

### Expected fix

Created the modification on my fork, here's the [commit](https://github.com/flutter/website/commit/3dd682d0626e661a52274240bcc56d1698f03b4b).

**Comment by AugustDG** [comment]
As an added improvement, the Warning about downloading content from Google's servers and T&S agreement could be put higher on the page.

**Comment by atsansone** [comment]
This may be reintroduced depending on demand. Watching for now.
