### ISSUE TITLE
[PAGE ISSUE]: 'Windows install'

### ISSUE THREAD

**Issue by javad5684** [flutter/website#8100]
### Page URL

https://docs.flutter.dev/get-started/install/windows/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/windows.md

### Describe the problem

hi there
I have a problem with installation link there is no installation link and inested of wrote "failed"
and i have windows 7 in my laptop 
guid me pls

**Comment by danagbemava-nc** [comment]
Hi @javad5684, what `installation link` are you referring to?

At what point in the installation process are you stuck?

**Comment by javad5684** [comment]
I guess it's because of Sanctions remove the download link by the way
thanks for your response.

**Comment by danagbemava-nc** [comment]
Hi @javad5684, I'm not sure I understand. What sanctions are you referring to and what issue are you actually reporting here?
