### ISSUE TITLE
[PAGE ISSUE]: 'Using Flutter in China'

### ISSUE THREAD

**Issue by yangwenqiang** [flutter/website#8101]
### Page URL

https://docs.flutter.dev/community/china/

### Page source

https://github.com/flutter/website/tree/main/src/community/china.md

### Describe the problem

using flutter doctor to check and reported: HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host: Handshake error in client，it happends on windows platform!

**Comment by danagbemava-nc** [comment]
Hi @yangwenqiang, this seems like an issue with your network. Are you able to ping `cocoapods.org`?

**Comment by yangwenqiang** [comment]
Hi
&nbsp; &nbsp; &nbsp;Yes，I can&nbsp;access&nbsp;cocapods.org by chrome&nbsp;




杨文强
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月12日(星期四) 晚上8:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flutter/website] [PAGE ISSUE]: 'Using Flutter in China' (Issue #8101)





 
Hi @yangwenqiang, this seems like an issue with your network. Are you able to ping cocoapods.org?

**Comment by danagbemava-nc** [comment]
Kindly share your `flutter doctor -v` output. 

Thank you

**Comment by yangwenqiang** [comment]
C:\Users\Administrator\Desktop&gt;flutter doctor -v
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.3.10, on Microsoft Windows [版本 10.0.14393], locale zh-CN)
&nbsp; &nbsp; • Flutter version 3.3.10 on channel stable at D:\flutter
&nbsp; &nbsp; • Upstream repository https://github.com/flutter/flutter.git
&nbsp; &nbsp; • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
&nbsp; &nbsp; • Engine revision 3316dd8728
&nbsp; &nbsp; • Dart version 2.18.6
&nbsp; &nbsp; • DevTools version 2.15.0
&nbsp; &nbsp; • Pub download mirror https://pub.flutter-io.cn
&nbsp; &nbsp; • Flutter download mirror https://storage.flutter-io.cn


[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
&nbsp; &nbsp; • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
&nbsp; &nbsp; • Platform android-TiramisuPrivacySandbox, build-tools 33.0.1
&nbsp; &nbsp; • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
&nbsp; &nbsp; • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
&nbsp; &nbsp; • All Android licenses accepted.


[√] Chrome - develop for the web
&nbsp; &nbsp; • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe


[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.4.3)
&nbsp; &nbsp; • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
&nbsp; &nbsp; • Visual Studio Community 2022 version 17.4.33205.214
&nbsp; &nbsp; • Windows 10 SDK version 10.0.22000.0


[√] Android Studio (version 2021.3)
&nbsp; &nbsp; • Android Studio at C:\Program Files\Android\Android Studio
&nbsp; &nbsp; • Flutter plugin can be installed from:
&nbsp; &nbsp; &nbsp; &nbsp;https://plugins.jetbrains.com/plugin/9212-flutter
&nbsp; &nbsp; • Dart plugin can be installed from:
&nbsp; &nbsp; &nbsp; &nbsp;https://plugins.jetbrains.com/plugin/6351-dart
&nbsp; &nbsp; • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)


[√] Connected device (2 available)
&nbsp; &nbsp; • Windows (desktop) • windows • windows-x64&nbsp; &nbsp; • Microsoft Windows [版本 10.0.14393]
&nbsp; &nbsp; • Chrome (web)&nbsp; &nbsp; &nbsp; • chrome&nbsp; • web-javascript • Google Chrome 108.0.5359.125


[!] HTTP Host Availability
&nbsp; &nbsp; X HTTP host "https://cocoapods.org/" is not reachable. Reason: An error occurred while checking the HTTP host:
&nbsp; &nbsp; &nbsp; Handshake error in client


! Doctor found issues in 1 category.









杨文强
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 晚上9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flutter/website] [PAGE ISSUE]: 'Using Flutter in China' (Issue #8101)





 
Kindly share your flutter doctor -v output.
 
Thank you

**Comment by danagbemava-nc** [comment]
Hi @yangwenqiang, are you by any chance using a proxy?

**Comment by parlough** [comment]
@chenglu Is this an issue you've seen others experience? I'm curious if we need to document any exceptions/suggestions for cocoapods?

**Comment by yangwenqiang** [comment]
no, the problem is because of bad RubyGems (usr/bin problem) , I tried to install&nbsp;&nbsp;cocoapods by&nbsp;brew, I does not works.


杨文强
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月12日(星期天) 上午7:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flutter/website] [PAGE ISSUE]: 'Using Flutter in China' (Issue #8101)





 
This typically means you don't set the proxy to your terminal. Using a site mirror doesn't relate to CocoaPods, and CocoaPods will affect nothing on Windows since it's a package manager on macOS.

**Comment by yangwenqiang** [comment]
install cocoapods by pem with&nbsp; the following error:&nbsp;&nbsp;



$ sudo gem install -n /usr/local/bin cocoapods

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/rbconfig.rb:230: warning: Insecure world writable dir /Users/wenqiangy/development/flutter/bin in PATH, mode 040777

ERROR:&nbsp; While executing gem ... (Gem::FilePermissionError)

&nbsp; &nbsp; You don't have write permissions for the /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0 directory.

	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:712:in `verify_gem_home'

	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:902:in `pre_install_checks'

	/Library/Ruby/Site/2.6.0/rubygems/installer.rb:302:in `install'

	/Library/Ruby/Site/2.6.0/rubygems/resolver/specification.rb:104:in `install'

	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:194:in `block in install'

	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:182:in `each'

	/Library/Ruby/Site/2.6.0/rubygems/request_set.rb:182:in `install'

	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:214:in `install_gem'

	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:230:in `block in install_gems'

	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:223:in `each'

	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:223:in `install_gems'

	/Library/Ruby/Site/2.6.0/rubygems/commands/install_command.rb:169:in `execute'

	/Library/Ruby/Site/2.6.0/rubygems/command.rb:323:in `invoke_with_build_args'

	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:251:in `invoke_command'

	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:191:in `process_args'

	/Library/Ruby/Site/2.6.0/rubygems/command_manager.rb:149:in `run'

	/Library/Ruby/Site/2.6.0/rubygems/gem_runner.rb:51:in `run'

	/usr/bin/gem:21:in `<main&gt;'



杨文强
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter/website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月12日(星期天) 上午7:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flutter/website] [PAGE ISSUE]: 'Using Flutter in China' (Issue #8101)





 
This typically means you don't set the proxy to your terminal. Using a site mirror doesn't relate to CocoaPods, and CocoaPods will affect nothing on Windows since it's a package manager on macOS.

**Comment by AlexV525** [comment]
Please attach more related context as your title: Using Flutter in China, in a new issue. Thanks.
