### ISSUE TITLE
Rebuild images on DevTools memory docs images to improve readability

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/website#8109]
Example: https://docs.flutter.dev/development/tools/devtools/memory#diff-tab

These tables are a bit difficult to read. @polina-c

**Comment by polina-c** [comment]
@kenzieschmoll , can you point, which exactly images need to to be recreated?

**Comment by kenzieschmoll** [comment]
Looks like the diff screenshots have been updated, but the tracing allocations screenshots are pretty small. These should also be taken in dark mode for consistency: https://docs.flutter.dev/tools/devtools/memory#trace-instances-tab

**Comment by polina-c** [comment]
I got feedback from tech writers that white mode is easier to read for most people with vision issues.
So, I suggest to go with light mode for future image updates.

**Comment by polina-c** [comment]
@kenzieschmoll , this image is not intended for reading, but is intended to give impression of how the tab looks like.

If it is bad idea, let's remove the image at all, as it does not give any specific information.

**Comment by kenzieschmoll** [comment]
At the current size, it is tough to see what the content even is. For consistency, let's just increase the size of the existing screenshot on the website or take a new screenshot that is larger. I think images are very important for DevTools documentation - users like to be able to get a high level view without reading. The memory docs are already quite long, so images that can give the user context and understanding are a good thing.
