### ISSUE TITLE
[PAGE ISSUE]: 'Create a nested navigation flow'

### ISSUE THREAD

**Issue by eighty4** [flutter/website#8116]
### Page URL

https://docs.flutter.dev/cookbook/effects/nested-nav/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/effects/nested-nav.md

### Describe the problem

The nested navigation flow example does not update the URL or ModalRoute.settings.name when navigating between pages. The user story in this example does not really need deep-linking, but that is a typical use case.

I can't figure out how to sync or update the root navigator's path with nested navigation (or how to use MaterialApp without a navigator and have a navigator lower in the hierarchy control the URL or ModalRoute state).

**Comment by danagbemava-nc** [comment]
That sample is quite old iirc. It will probably be best to update it with either `Navigator 2.0` or `GoRouter`. 

/cc @domesticmouse  for thoughts on what to do with this codelab

**Comment by eighty4** [comment]
Navigator 2.0 == Pages and Router?

**Comment by danagbemava-nc** [comment]
> Navigator 2.0 == Pages and Router?

Yes

> Is it possible with those APIs to update the app URL from a nested navigator?

Yes, this should be possible. GoRouter is built on top of Navigator 2.0, and since this is possible with GoRouter, you should be able to implement this yourself with the apis available in Navigator 2.0

**Comment by domesticmouse** [comment]
PTAL @johnpryan

**Comment by johnpryan** [comment]
Yes, go_router supports this scenario, see the [go_router documentation](https://pub.dev/documentation/go_router/latest/topics/Configuration-topic.html) for details. 

We currently don't have plans to update the cookbook for Navigator 2.0 / go_router.

**Comment by eighty4** [comment]
😕 that's a weird choice.. I've used Flutter passively for several years and asking this question on a doc page's GH issues was the first I heard of a 2.0 nav.
