### ISSUE TITLE
broken Link to source code 

### ISSUE THREAD

**Issue by agavrel** [flutter/website#8129]
### Page URL

https://github.com/flutter/website/blob/main/src/cookbook/effects/shimmer-loading.md

### Describe the problem

At the very end of the read me there is this link to the source code: https://github.com/flutter/website/blob/main/src/cookbook/effects/%7B%7Bsite.github%7D%7D/flutter/codelabs

which return 404 

...while it should return the link to the sourcecode

### Expected fix

provide the right link to the readme. 

Btw: https://docs.flutter.dev/cookbook/effects/shimmer-loading at the very beginning after cardlistitem code there is:

"Your UI now renders itself differently depending on whether it’s loading or loaded. By temporarily commenting out the image URLs, you can see the two ways your UI renders."

But all I got was a lot of runtime errors. Hence why I went to check the example.

**Comment by agavrel** [comment]
It translates to https://github.com/flutter/website/blob/main/src/cookbook/effects/{{site.github}}/flutter/codelabs

So of course the environment variable was not uploaded.

**Comment by danagbemava-nc** [comment]
Hi @agavrel, which readme are you referring to?

**Comment by agavrel** [comment]
https://github.com/flutter/website/blob/main/src/cookbook/effects/shimmer-loading.md

**Comment by danagbemava-nc** [comment]
Hi @agavrel, the links don't work on GitHub because they're resolved by Jekyll on the website itself. 

The link to the source code in question is https://github.com/flutter/codelabs/blob/main/cookbook/lib/examples/ui_loading_animation.dart although the website page links to https://github.com/flutter/codelabs

**Comment by sfshaza2** [comment]
Yes, @agavrel, you must access the resolved links using the generated pages. In this case, the shimmer loading page:  https://docs.flutter.dev/cookbook/effects/shimmer-loading

Closing.
