### ISSUE TITLE
Mismatch between displayed Flutter version and actual documentation

### ISSUE THREAD

**Issue by TiffApps** [flutter/website#8134]
### Describe the problem

Hello,

The documentation content doesn't match the version displayed in the footer of https://api.flutter.dev/, instead it matches the pre-release version.

### Expected fix

The doc content should always match the version displayed in the footer, wether it's stable or pre-release version (Although, the stable version should be the logical choice to display there).

### Additional context

For example, [SnackBarThemeData.width](https://api.flutter.dev/flutter/material/SnackBar/width.html) is not included in the 3.3.10 version (version displayed on the docs right now), as the earliest trace is [this PR](https://github.com/flutter/flutter/pull/112636), so 3.5.0-1.0.pre is the first tag that includes `width`.

As @DanTup found out on Discord, the file at https://api.flutter.dev/offline/flutter.xml includes a different version number (3.7.0-2.0.pre.5), but we're not sure what this file is for.

**Comment by guidezpl** [comment]
Additionally @DanTup noted the displayed hash `135454af32` is from a commit (coincidentally, mine) from May 2022.

**Comment by danagbemava-nc** [comment]
Hi @TiffApps, this is being tracked in https://github.com/flutter/flutter/issues/118161. 

Feel free to share this information on the issue linked above.

Closing this in favor of the issue on the main flutter issue.
