### ISSUE TITLE
[PAGE ISSUE]: 'Simple app state management'

### ISSUE THREAD

**Issue by saborrie** [flutter/website#8135]
### Page URL

https://docs.flutter.dev/development/data-and-backend/state-mgmt/simple/

### Page source

https://github.com/flutter/website/tree/main/src/development/data-and-backend/state-mgmt/simple.md

### Describe the problem

The example unit test is not correct. It will pass even if cart.add is a no-op - if `notifyListeners()` is never called by the cart model, then the line `expect(cart.totalPrice, greaterThan(startingPrice));` will never be called, and this test will make 0 assertions, so it would still pass.

```dart
test('adding item increases total cost', () {
  final cart = CartModel();
  final startingPrice = cart.totalPrice;
  cart.addListener(() {
    expect(cart.totalPrice, greaterThan(startingPrice));
  });
  cart.add(Item('Dash'));
});
```

### Expected fix

Provide an example test which *does* verify the cart.add method - I'm very new to dart so I don't know the idiomatic way to do so.

**Comment by domesticmouse** [comment]
Fixed by https://github.com/flutter/website/pull/8207
