### ISSUE TITLE
Typo in `Add a user authentication flow to a Flutter app using FirebaseUI` codelab

### ISSUE THREAD

**Issue by ESkyTech** [flutter/website#8145]
### Describe the problem

There's an incorrect file path reference at the [Firebase Auth in Flutter Codelab](https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#2)

### Expected fix

At the "Add Firebase packages to Flutter app" section, it appears the root of the Flutter project as

Current                                                                        Expected
flutter-codelabs/firebase-emulator-suite/start -> flutter-codelabs/firebase-auth-flutterfire-ui/start

**Comment by danagbemava-nc** [comment]
![Screenshot 2023-01-25 at 12 29 21](https://user-images.githubusercontent.com/88313112/214563569-1ac6ef82-2982-4195-9581-62c193a6bf79.png)


/cc @domesticmouse

**Comment by domesticmouse** [comment]
FYI @miquelbeltran and @nohe427

**Comment by miquelbeltran** [comment]
Thanks, @ESkyTech, I can confirm the typo as well.

@domesticmouse I'll need access to the codelab doc if you can give it to me, repo folder only contains code: https://github.com/flutter/codelabs/tree/main/firebase-auth-flutterfire-ui

**Comment by atsansone** [comment]
Make this change while fixing this issue: https://github.com/flutter/website/issues/8667

**Comment by domesticmouse** [comment]
> Thanks, @ESkyTech, I can confirm the typo as well.
> 
> @domesticmouse I'll need access to the codelab doc if you can give it to me, repo folder only contains code: https://github.com/flutter/codelabs/tree/main/firebase-auth-flutterfire-ui

I don't have access to this gDoc, @ericwindmill may be able to get you access. It's a Firebase codelab, so it's a different team with different ACLs =)

**Comment by sfshaza2** [comment]
This has been fixed:  https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#2
