### ISSUE TITLE
[Page Isssue]: 'Flutter News Toolkit'

### ISSUE THREAD

**Issue by isaacadariku** [flutter/website#8161]
### Page URL

https://flutter.dev/news

### Describe the problem

The hyperlink for "Watch the intro video" is currently pointing to the doc URL.

### Expected fix

The hyperlink should point to the video URL - https://www.youtube.com/watch?v=dukRAS-OUMM

**Comment by sfshaza2** [comment]
This has been fixed. Thanks for reporting it! Closing.

**Comment by isaacadariku** [comment]
> This has been fixed. Thanks for reporting it! Closing.

Thanks, @sfshaza2 for the quick fix! I'm glad I could help.
