### ISSUE TITLE
Adding Additional Resources for DevTools

### ISSUE THREAD

**Issue by ashitaprasad** [flutter/website#8165]
### Page URL

https://docs.flutter.dev/development/tools/devtools/

### Describe the problem

I was a part of the Google's Road To GDE Class 4 where I wrote a series of 8 in-depth articles on DevTools under the guidance of Kamal Shree (Flutter GDE).

These articles are very detailed and provide step-by-step codelabs so that people can learn how to effectively use DevTools via real-world scenarios and examples (like Wonderous app, Mandelbrot, etc.). 

Link to all the articles:

- Series Introduction & Installation - [Link](https://medium.com/@fluttergems/mastering-dart-flutter-devtools-series-introduction-installation-part-1-of-8-4f703a8cfcc8)
- Flutter Inspector - [Link](https://medium.com/@fluttergems/mastering-dart-flutter-devtools-flutter-inspector-part-2-of-8-bbff40692fc7)
- App Size Tool - [Link](https://medium.com/@fluttergems/mastering-dart-flutter-devtools-app-size-tool-part-3-of-8-9be6e9ec42a2)
- Network View - [Link](https://medium.com/@fluttergems/mastering-dart-flutter-devtools-network-view-part-4-of-8-afce2463687c)
- Logging View - [Link](https://medium.com/@fluttergems/mastering-dart-flutter-devtools-logging-view-part-5-of-8-b634f3a3af26)
- CPU Profiler View - [Link](https://medium.com/@fluttergems/mastering-dart-flutter-devtools-cpu-profiler-view-part-6-of-8-31e24eae6bf8)
- Memory View - [Link](https://medium.com/@fluttergems/mastering-dart-flutter-devtools-memory-view-part-7-of-8-e7f5aaf07e15)
- Performance View - [Link](https://medium.com/@fluttergems/mastering-dart-flutter-devtools-performance-view-part-8-of-8-4ae762f91230)

Is it possible to add the links to these articles (or selected articles) to the relevant pages of the DevTools section as it would greatly help new Flutter developers who are getting started with DevTools. 

So far, the entire article series has been very well received and appreciated by the Flutter community ([Ref](https://twitter.com/timsneath/status/1608237932388962306?s=20&t=7xnQvYTUBEmFU6xJ_XcaFA)) and adding these articles can definitely help developers in regards to DevTools.

### Expected fix

Adding Aritcle Links to **Codelabs & Other resources** section.

**Comment by danagbemava-nc** [comment]
Thanks for the great in-depth articles. I believe adding them to the website should help out a lot. 

/cc @sfshaza2

**Comment by ashitaprasad** [comment]
Thanks @danagbemava-nc for reviewing this issue.
So how should I proceed from here. Should I send a PR with edits?

**Comment by danagbemava-nc** [comment]
Yes, you can go ahead and do that

**Comment by ashitaprasad** [comment]
Thanks @danagbemava-nc 
Done.
