### ISSUE TITLE
[PAGE ISSUE]: 'Material 3 updates'

### ISSUE THREAD

**Issue by guidezpl** [flutter/website#8167]
### Page URL

https://docs.flutter.dev/development/ui/material3-updates/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/material3-updates.md

### Describe the problem

Hey team, happy to see an M3 page! 

For maintainability reasons and to avoid duplicated work, I'd like to suggest the following:
- Rather than list out changes per release, leverage the Material 3 project views to give users a sense of what's planned, what's coming in the next stable, what was launched in version X, etc. The project is at https://github.com/orgs/flutter/projects/19/views/22
- Rather than list new and updated widgets (which will get out of date every few weeks), link to https://api.flutter.dev/flutter/material/ThemeData/useMaterial3.html, which is the comprehensive list and which we can update as you wish
- Remove https://material.io/blog/blog/blog/migrating-material-3, which concerns Android Views
- More prominently showcase https://m3.material.io/develop/flutter, or in a similar fashion, have this page act as a hub for resources

cc @MiraMarshall @sfshaza2

**Comment by sfshaza2** [comment]
I'm working on this, @guidezpl.
