### ISSUE TITLE
[PAGE ISSUE]: 'Use themes to share colors and font styles'

### ISSUE THREAD

**Issue by incidentist** [flutter/website#8171]
### Page URL

https://docs.flutter.dev/cookbook/design/themes/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/design/themes.md

### Describe the problem

Changing colors in the Interactive Example at the bottom does not change anything. It seems like this has not been updated to a recent Flutter version, so it is using deprecated themeData elements.

### Expected fix

I expect to be able to change the `primaryColor` in the theme to `Colors.orange` and to have some orange show up in the running app.

### Additional context

I'm updating my app from an old version of Flutter and am finding that my theme colors are not showing up. I am trying to find out what the current way to do a simple theme is, so I'm consulting the official documentation but this page seems to be out of date.

**Comment by danagbemava-nc** [comment]
Hi @incidentist, yes, the page hasn't been updated for a while. This is being tracked in https://github.com/flutter/website/issues/7341.

Closing from here as duplicate. 

Thank you
