### ISSUE TITLE
[PAGE ISSUE]: 'Flutter SDK releases'

### ISSUE THREAD

**Issue by badri001** [flutter/website#8181]
### Page URL

https://docs.flutter.dev/development/tools/sdk/releases/

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/sdk/releases.md

### Describe the problem

above stable channel there is an tabBar to switch the environments[windows,macOS,linux] which is not working now.

### Expected fix

Not sure but looks like an routing issue. 

### Additional context

only the url is getting changed but the page remaining as it is.

![image](https://user-images.githubusercontent.com/34916335/215687721-dcc257b0-f18f-4574-a755-de5ede3eaee8.png)

**Comment by parlough** [comment]
Thanks for the report and sorry about the inconvenience! I've pushed a fix and the tabs should work again :)
