### ISSUE TITLE
Update copy to match example on 'Create a photo filter carousel' page

### ISSUE THREAD

**Issue by Yang-Xijie** [flutter/website#8202]
### Page URL

https://docs.flutter.dev/cookbook/effects/photo-filter-carousel/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/effects/photo-filter-carousel.md

### Describe the problem

**The text explanation is different from the interactive example given at the end.**

In the text explanation, `PageView` is used to show the animation of the `Carousel`. However, in the interactive example, `Scrollable` with physics `PageScrollPhysics` and widget `Flow`are used to achieve the same thing.

From the Note part: 

> In cases where you need to customize the position of child widgets within a scrollable area, consider using a [Scrollable](https://api.flutter.dev/flutter/widgets/Scrollable-class.html) widget with a [viewportBuilder](https://api.flutter.dev/flutter/widgets/Scrollable/viewportBuilder.html), and place a [Flow](https://api.flutter.dev/flutter/widgets/Flow-class.html) widget inside the viewportBuilder. The Flow widget has a [delegate property](https://api.flutter.dev/flutter/widgets/Flow/delegate.html) that allows you to position child widgets wherever you want, based on the current viewportOffset.

It seemes that the given codes, instead of the text explanation, is a better choice.

### Expected fix

Update the text explanation to make it fit with the given interactive example.

**Comment by sfshaza2** [comment]
Usurped by https://github.com/flutter/website/issues/10774. Closing.
