### ISSUE TITLE
[PAGE ISSUE]: 'Performance'

### ISSUE THREAD

**Issue by james2doyle** [flutter/website#8221]
### Page URL

https://docs.flutter.dev/perf/

### Page source

https://github.com/flutter/website/tree/main/src/perf/index.md

### Describe the problem

The link on "[Using memory wisely](https://docs.flutter.dev/perf/memory)" goes nowhere.

### Expected fix

 Link to a viable page or remove the link.

**Comment by danagbemava-nc** [comment]
Thanks for reporting this.
