### ISSUE TITLE
[Page Issue]: 'Firebase for Flutter codelab'

### ISSUE THREAD

**Issue by isaacadariku** [flutter/website#8226]
### Page URL

https://flutter.dev/learn

### Describe the problem

The hyperlink for "Firebase for Flutter codelab" on the Intermediate tab is currently broken and showing 404.

### Expected fix

I think it should point to the tags for both Firebase and Flutter https://codelabs.developers.google.com/?product=firebase%2Cflutter. As there is no URL that shows only both.

**Comment by sfshaza2** [comment]
@domesticmouse

**Comment by sfshaza2** [comment]
I've contacted the marketing folks about this.

**Comment by sfshaza2** [comment]
This can only be fixed by the marketing folks, and I've let them know.

**Comment by sfshaza2** [comment]
The 404 is fixed. (Though the page still needs a major overhaul.)
