### ISSUE TITLE
[PAGE ISSUE]: 'Deep linking'

### ISSUE THREAD

**Issue by gisborne** [flutter/website#8234]
### Page URL

https://docs.flutter.dev/development/ui/navigation/deep-linking/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/navigation/deep-linking.md

### Describe the problem

The page is grossly inadequate, not remotely up to the usual standard for Flutter documentation.

I've wasted several days trying to get this seemingly simple thing working, without success so far. Even other online material I can find is inadequate, not discussing the back end file in any case, as just one example.

I have edited my Info.plists file, trying both a custom scheme and HTTP/HTTPS.

I today learned that I probably need to serve a file from the back end at the domain in question:

https://developer.apple.com/documentation/xcode/supporting-associated-domains?language=objc

However, this isn't being requested by the app.

The Flutter community could really use a good worked example of this. Including:
- how to do this in development, where I am not yet working with files at the actual production domain
- how to do both custom and HTTP/HTTPS URL schemes
- it seems I need to also create an associated domain in my iOS app. But maybe I don't need that with a custom URL scheme? Who knows?
- how to use a custom port

### Expected fix

Clear working examples of all the permutations of this.

**Comment by gisborne** [comment]
Also, use named routes to do this, but hey, we recommend not using named routes.

**Comment by sfshaza2** [comment]
@johnpryan @chunhtai

**Comment by sfshaza2** [comment]
@johnpryan, can you weigh in?

**Comment by chunhtai** [comment]
The page have been updated, it now contains more detail steps for both Android and iOS.

**Comment by sfshaza2** [comment]
Thanks! Closing.
