### ISSUE TITLE
[Page Issue]: 'Try the desktop codelab'

### ISSUE THREAD

**Issue by isaacadariku** [flutter/website#8244]
### Page URL

https://flutter.dev/learn

### Describe the problem

On the Advance tab, the hyperlink for "Try [the desktop codelab](https://codelabs.developers.google.com/codelabs/flutter-github-graphql-client#0)" is currently broken and showing 404.

### Expected fix

It should point to this URL for Flutter desktop codelab - https://codelabs.developers.google.com/codelabs/flutter-github-client

**Comment by parlough** [comment]
A fix has been made and will roll out shortly.

Thanks for reporting the issue!
