### ISSUE TITLE
Missing documentation for `flutter gen_l10n nullable-getter` flag

### ISSUE THREAD

**Issue by navaronbracke** [flutter/website#8254]
### Page URL

https://docs.flutter.dev/development/accessibility-and-localization/internationalization#configuring-the-l10nyaml-file

### Describe the problem

The parameter `nullable-getter`, which was added in https://github.com/flutter/flutter/pull/79263
does not show up in the options for configuring `flutter gen_l10n`.

### Expected fix

The parameter `nullable-getter` is documented in the list.

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/8263
