### ISSUE TITLE
[Page Issue]: 'Bind to native libraries'

### ISSUE THREAD

**Issue by isaacadariku** [flutter/website#8280]
### Page URL

https://flutter.dev/learn

### Describe the problem

On the Advance tab -> Bind to native libraries, the hyperlink for "[Flutter apps](https://flutter.dev/docs/development/platform-integration/c-interop)" is currently broken and showing 404.

### Expected fix

There is no specific URL for Flutter apps with FFI, it is all scattered within the various platforms. So here is a [search query](https://docs.flutter.dev/search?q=ffi) that shows all the FFI hyperlinks.

But this [codelab](https://codelabs.developers.google.com/codelabs/flutter-ffigen#0) is also a good source for it.

**Comment by exaby73** [comment]
## Triage report

I can reproduce this issue. The link points to https://docs.flutter.dev/development/platform-integration/c-interop which does not exist

**Comment by parlough** [comment]
This has been updated to point to a new location. Thanks for opening the issue!
