### ISSUE TITLE
[PAGE ISSUE]: 'Writing and using fragment shaders'

### ISSUE THREAD

**Issue by Hixie** [flutter/website#8281]
### Page URL

https://docs.flutter.dev/development/ui/advanced/shaders/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/advanced/shaders.md

### Describe the problem

The page skips over the step explaining how to get from a GLSL source file to the `.frag` asset, which I presume is compiled? It would be useful to have a set of steps that walks you from `flutter create` and a https://www.shadertoy.com/ example, and ends with a spinning green `Container` square being rendered with a shader, or some such

### Additional context

cc @jonahwilliams

**Comment by jonahwilliams** [comment]
.frag is the GLSL source file.

**Comment by Hixie** [comment]
So does putting a `.frag` file in the `shaders:` section imply that an asset of the same name, but containing compiled bytes, is included as an asset?

**Comment by jonahwilliams** [comment]
correct. the extension itself isn't really important, that is just the convention used for shaders authored in the engine. .frag for fragment shaders .vert for vertex shaders. Of course we don't support vertex shaders yet...

**Comment by Hixie** [comment]
k, i'll update the doc

**Comment by jonahwilliams** [comment]
I have been kicking around more of a codelab like walkthrough using gradients. (see https://github.com/jonahwilliams/awesome_gradients ). That might help clarify things because as it exists the current page is more of a brain dump of all of the terms and conditions.

**Comment by Hixie** [comment]
Fixed by https://github.com/flutter/website/pull/8282
