### ISSUE TITLE
[PAGE ISSUE]: 'Internationalizing Flutter apps'

### ISSUE THREAD

**Issue by harounhajem** [flutter/website#8302]
### Page URL

https://docs.flutter.dev/development/accessibility-and-localization/internationalization/

### Page source

https://github.com/flutter/website/tree/main/src/development/accessibility-and-localization/internationalization.md

### Describe the problem

This example of using AppLocalizations.of is not valid. Text(data: String.. ) requires a const value. 
```
appBar: AppBar(
  // The [AppBar] title text should update its message
  // according to the system locale of the target platform.
  // Switching between English and Spanish locales should
  // cause this text to update.
  title: Text(AppLocalizations.of(context)!.helloWorld),
),
```
The `AppLocalizations.of(context)` returns optional value which the compiler does not accept. 

Here is an example message of an error:
```
  lib/presentation/pages/search/search_page.dart:12:41: Error: Not a constant expression.
          child: Text(AppLocalizations.of(context)!.helloWorld)
                                          ^^^^^^^
  lib/presentation/pages/search/search_page.dart:12:38: Error: Method invocation is not a constant expression.
          child: Text(AppLocalizations.of(context)!.helloWorld)
```

**Comment by parlough** [comment]
Thanks for opening an issue @harounhajem!

`const` constructors, such as [`Text`](https://api.flutter.dev/flutter/widgets/Text/Text.html) can be used in a `const` context, but they don't need to be. 

In this case, it looks like you have a `const` higher up in the widget tree (before the `AppBar`) requiring everything within it to be `const`, but you can't use `AppLocalizations.of` in a `const` context. Try removing any `const` higher up in the widget tree.

Let us know if that doesn't solve your error! Thanks again :)
