### ISSUE TITLE
[PAGE ISSUE]: Android range on 'Supported platforms' is out of date

### ISSUE THREAD

**Issue by gnprice** [flutter/website#8314]
### Page URL

https://docs.flutter.dev/development/tools/sdk/release-notes/supported-platforms/

### Page source

https://github.com/flutter/website/tree/main/src/development/tools/sdk/release-notes/supported-platforms.md

### Describe the problem

The "Google-tested platforms" for Android are listed as "Android SDK 19–30". SDK 30 means Android 11, a couple of years older than the latest.

According to @reidbaker [in Discord](https://discord.com/channels/608014603317936148/846507907876257822/1079851673540903024), SDK 33 (aka Android 13, the latest) is also tested, and likely 31 and 32 as well.

At the other end of the range, apparently testing for SDK 19 stopped last month. So (given the footnote about 20) the range should start at 21.

### Expected fix

The range should read "Android SDK 21-33", provided that it's accurate that SDK 31 and 32 are tested.

The footnote about SDK 19 and SDK 20 can then be deleted.

The range for Android under "Best-effort platforms" should also be updated to reflect SDK 19 and SDK 20 moving there: it should read "Android SDK 16-20".

**Comment by gmackall** [comment]
Just updating that I am waiting to hear back confirmation that we do indeed test api 31 and 32, and then I will put up a PR and link here

**Comment by gmackall** [comment]
Updating with some more info:
https://flutter.googlesource.com/recipes/+/refs/heads/main/recipes/firebaselab/firebaselab.py#41
https://github.com/flutter/engine/blob/main/ci/firebase_testlab.py
These are firebase testlab setups (for framework and engine respectively) and it looks like we actually do not test 31-33 here.

The CI machines seem to be running 28 and 30
https://github.com/flutter/flutter/blob/master/dev/ci/docker_linux/Dockerfile#L96

Then finally we have the devicelab, which I am not sure about (still trying to determine).

**Comment by cbracken** [comment]
Looks like @gmackall got to you before I did! @reidbaker TLs the Android world so may have more of the gory details.

**Comment by sfshaza2** [comment]
Fixed in PR https://github.com/flutter/website/pull/8409.  Closing
