### ISSUE TITLE
Web support information in the installation guides is out of date

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#8322]
### Page URL

https://docs.flutter.dev/get-started/install/windows/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/windows.md

### Describe the problem

> Flutter has support for building web applications in the stable channel. Any app created in Flutter 2 automatically builds for the web. To add web support to an app created before web was in stable, follow the instructions on [Building a web application with Flutter](https://docs.flutter.dev/get-started/web) when you’ve completed the setup above.

Does web support just work out of the box now? This instruction still refers to Flutter 2, which we can probably drop or significantly simplify. 

Cc: @kevmoo

**Comment by kevmoo** [comment]
Thanks for flagging, @InMatrix !
