### ISSUE TITLE
Replace `CachedNetworkImage` with `Image.network` on 'Work with cached images' page

### ISSUE THREAD

**Issue by bryanoltman** [flutter/website#8324]
### Page URL

https://docs.flutter.dev/cookbook/images/cached-images/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/images/cached-images.md

### Describe the problem

This page recommends the CachedNetworkImage package, which I believe to be unnecessary now that the `Image.network` constructor exists and "All network images are cached regardless of HTTP headers".

### Expected fix

Recommend the built-in `Image.network` constructor instead of a third-party package.

**Comment by atsansone** [comment]
Escalated to P1 as it was found repeatedly over 4 years. This should get extra attention.

**Comment by domesticmouse** [comment]
Proposed actions:
1) Update https://github.com/flutter/website/blob/main/src/cookbook/images/network-image.md to remove the `Image.network` doesn't cache
2) Remove https://github.com/flutter/website/tree/main/src/cookbook/images/cached-images.md

sg?

**Comment by domesticmouse** [comment]
#9923 is blocked until we get confirmation that `Image.network` caches retrieved images on all six platforms.
