### ISSUE TITLE
Flutter install/doctor still doesn't work with spaces in Windows paths see https://github.com/flutter/flutter/issues/83195

### ISSUE THREAD

**Issue by kragil** [flutter/website#8340]
I couldn't reopen the issue, but it is not fixed!

flutter doctor and https://docs.flutter.dev/get-started/install/windows  are giving wrong advice:

you have to do:

flutter config --android-studio-dir="C:\Program Files\Android\Android Studio" without a \ at the end

and not 

flutter config --android-studio-dir <directory>

there has to be a = and no \ at the end.

Is everybody on a Mac and Linux or why are so basic problems still around?

More info on https://github.com/flutter/flutter/issues/83195

**Comment by danagbemava-nc** [comment]
Closing this in favor of https://github.com/flutter/website/issues/8341
