### ISSUE TITLE
Explain how to obtain build mode at runtime on 'Flutter's build modes' page

### ISSUE THREAD

**Issue by gisborne** [flutter/website#8350]
### Page URL

https://docs.flutter.dev/testing/build-modes/

### Page source

https://github.com/flutter/website/tree/main/src/testing/build-modes.md

### Describe the problem

No mention of how to obtain the current build mode at runtime.

### Expected fix

Describe how to obtain the current build mode at runtime.

**Comment by atsansone** [comment]
@domesticmouse : Do you have any insight here?

**Comment by domesticmouse** [comment]
Nope, I don't know how to detect build mode at run time. Time to find an engineer.

**Comment by domesticmouse** [comment]
Hey @gspencergoog any ideas which engineer to chat with about Flutter build modes?

**Comment by gspencergoog** [comment]
The build modes are available from three constants in [flutter/foundation](https://github.com/flutter/flutter/blob/dfb78f82466fc12f5725784757975398a5c6c039/packages/flutter/lib/src/foundation/constants.dart#L22).
[`kReleaseMode`](https://api.flutter.dev/flutter/foundation/kReleaseMode-constant.html), [`kProfileMode`](https://api.flutter.dev/flutter/foundation/kProfileMode-constant.html), [`kDebugMode`](https://api.flutter.dev/flutter/foundation/kDebugMode-constant.html).  They're `const bool`s, so they can be used to make a conditional block that will be removed at compile time if they are false.

**Comment by domesticmouse** [comment]
@atsansone how would you like to build this into the page? I'm guessing linking the build mode constants listed by Greg should be sufficient?
