### ISSUE TITLE
Link to DeepCollectionEquality from Selector class documentation is outdated

### ISSUE THREAD

**Issue by pianistrevor** [flutter/website#8364]
### Page URL

https://pub.dev/documentation/provider/latest/provider/Selector-class.html

### Describe the problem

In the third paragraph, there's a hyperlink to the `DeepCollectionEquality` class which returns a 404. If I replace "1.17.0" to "latest" it works just fine. Probably a stale API.

### Expected fix

The link goes to the latest documentation on the `DeepCollectionEquality` class.

**Comment by danagbemava-nc** [comment]
Hi @pianistrevor, this documentation is not from the flutter website. It's pub.dev displaying the documentation from the provider package. You may need to report this on either the `provider` package repo or the pub repo (in case it's pub not resolving the URL properly). I would suggest reporting this on the provider repo first.

Closing from here as this is not an issue from the flutter website repo. 

Thank you
