### ISSUE TITLE
support for dark mode 

### ISSUE THREAD

**Issue by samithe7** [flutter/website#8404]
### Page URL

https://flutter.dev/

### Describe the problem

we almost all developer  use dark  mode  . when  i go flutter website it is  too white  .

**Comment by parlough** [comment]
Thanks for opening an issue. This work is planned in https://github.com/flutter/website/issues/3632, but some other work is set to be complete first. Sorry about the delay.

Duplicate of https://github.com/flutter/website/issues/3632
