### ISSUE TITLE
[PAGE ISSUE]: 'Customizing web app initialization'

### ISSUE THREAD

**Issue by esDotDev** [flutter/website#8410]
### Page URL

https://docs.flutter.dev/development/platform-integration/web/initialization/

### Page source

https://github.com/flutter/website/tree/main/src/development/platform-integration/web/initialization.md

### Describe the problem

It is not obvious how to use the `JsFlutterConfiguration` object as there is no usage example. 

### Expected fix

Would be nice to see a snippet like:
```
// Configure the engine options
let engineOptions = new _flutter.JsFlutterConfiguration();
engineOptions.renderer = "canvaskit";

// Initialize the Flutter engine
let appRunner = await engineInitializer.initializeEngine(engineOptions);
```

### Additional context

We were trying to determine how to force canvaskit for a project, and the old method is deprecated (window.flutterWebRenderer = 'canvaskit'). The docs  say  "you can use the initializeEngine method to configure several run-time options of the Flutter web engine through a JsFlutterConfiguration object.", but they give no usage example. 

We get no code-hinting in the HTML files so it is not obvious how or where to set that.
 We had to turn to [stackoverflow](https://stackoverflow.com/a/75605625/463029), where it was explained

@domesticmouse

**Comment by domesticmouse** [comment]
PTAL @kevmoo

**Comment by ditman** [comment]
I'll add an example to this bit of the documentation:

https://docs.flutter.dev/development/platform-integration/web/initialization#initializing-the-engine

@esDotDev, so you don't have to wait for the docs to be published, the expected syntax should be something like:

```js
// Initialize the Flutter engine
let appRunner = await engineInitializer.initializeEngine({
  renderer: 'canvaskit'
});
```

**Comment by ditman** [comment]
I guess it's also confusing that we say that it expects an instance of the xyz object. When that object is more of an internal Dart artifact than an externally-facing constructor. I'll rewrite that too.
