### ISSUE TITLE
Update url_launcher example code and walkthrough in 'Using an OEM debugger' page

### ISSUE THREAD

**Issue by parlough** [flutter/website#8414]
### Page URL

https://docs.flutter.dev/testing/oem-debuggers/

### Page source

https://github.com/flutter/website/tree/main/src/testing/oem-debuggers.md

### Describe the problem

The code does not currently use code excerpts, and as a result is now in an outdated state, not supporting null safety.

### Expected fix

- [ ] Add the code to examples somewhere so we can use the code excerpt tool
- [ ] Use the latest `url_launcher` example: https://pub.dev/packages/url_launcher/example
- [ ] Update the code and later references to it on page, including screenshots

Extra:
- [x] Use `dart pub add` instead of manually adding dependencies to pubspec
- [x] Use markdown code blocks instead of prettify

**Comment by Mastersam07** [comment]
Hi @parlough i am not sure what was meant by 

> Add the code to examples somewhere so we can use the code excerpt tool

I am interested in picking this.
