### ISSUE TITLE
[PAGE ISSUE]: 'Google APIs'

### ISSUE THREAD

**Issue by the-wajahat** [flutter/website#8418]
### Page URL

https://docs.flutter.dev/development/data-and-backend/google-apis/

### Page source

https://github.com/flutter/website/tree/main/src/development/data-and-backend/google-apis.md

### Describe the problem

Link of page is not available in Navigation menu of Data & Backend tab.

**Comment by danagbemava-nc** [comment]
![Screenshot 2023-03-22 at 12 46 45](https://user-images.githubusercontent.com/88313112/226909014-05043dd8-2c43-4200-8fe9-74354196add0.png)
![Screenshot 2023-03-22 at 12 46 52](https://user-images.githubusercontent.com/88313112/226909022-20c1b4ca-09d5-43a4-8e8c-ce6d5ac31475.png)

**Comment by sfshaza2** [comment]
Fixed in above-mentioned PR. Closing.
