### ISSUE TITLE
Update the example in Step 1 of the 'An introduction to unit testing' page

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/website#8439]
https://docs.flutter.dev/cookbook/testing/unit/introduction#1-add-the-test-dependency currently says to add:
```yaml
dev_dependencies:
  test: <latest_version>
```

There's no guaranteed that the latest version is compatible with Flutter stable, so this can cause confusion (see https://github.com/flutter/flutter/issues/85560). We should instead show a version we know works, like `^1.16` (and optionally mention that people should put a newer version if they need newer functionality, but that's probably not especially common so we could skip it).

This would mean that the docs would become outdated if there's a major version change, but we can expect that to be a rare event.

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/8950. h/t @miquelbeltran
