### ISSUE TITLE
Provide info on race condition found on 'Add a drawer to a screen' page

### ISSUE THREAD

**Issue by al-muammar** [flutter/website#8440]
## Steps to Reproduce
In the following simple application

```dart
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        title: 'Drawer Demo',
        home: Scaffold(
          appBar: AppBar(),
          drawer: Drawer(
            child: Builder(
              builder: (context) => ElevatedButton(
                onPressed: () => Navigator.pop(context),
                child: const Text('Navigator.pop()'),
              ),
            ),
          ),
        ),
      );
}
```

one could observe the following behaviour: quickly clicking twice on the drawer will pop the scaffold and leave a black screen.  
Here is my minimal dart pad for testing: https://dartpad.dev/b532815b4858d36630ad524154904d9b?null_safety=true

**Explanation**: it seems that there is race condition between the drawer opening and pushing it to the navigator stack. One could easily reproduce the situation when a user could click a button on a drawer before it is pushed to the navigator stack.

**Expected behaviour**: Most of the modern applications don't allow clicking on the drawer content until it's fully opened. There might be other solutions.

**Comment by atsansone** [comment]
This behavior cannot be reproduced in the provided DartPad example. Can you provide another method to corroborate, like a video or animated image?
