### ISSUE TITLE
Provide specific supported test version or wider constraint/caret dependency for Unit testing

### ISSUE THREAD

**Issue by Mereep** [flutter/website#8441]
Testing cookbook should be more specific about supported test version, or suggest a wider constraint/caret dependency

I followed the official descriptions given here: https://flutter.dev/docs/cookbook/testing/unit/introduction

giving me:
```yaml
dev_dependencies:
  test: ^1.15.4
```

however, when using fetching the dependencies on a freshly installed framework (stable) it does not resolve:

```text
Because every version of flutter_test from sdk depends on test_api 0.2.17 and test >=1.15.3 <1.16.0-nullsafety depends on test_api 0.2.18, flutter_test from sdk is incompatible with test >=1.15.3 <1.16.0-nullsafety.
So, because wir_in_der_region depends on both test 1.15.4 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because project depends on both test 1.15.4 and flutter_test any from sdk, version solving failed.)
```

How can this be resolved? Is there a workaround?

Disclaimer: 
I already reported that issue here: https://github.com/dart-lang/test/issues/1349 but it immidiatly got closed without any useful solution or feedback.

**Comment by sfshaza2** [comment]
@miquelbeltran, please review

**Comment by miquelbeltran** [comment]
This should no longer be a problem, since the cookbook recipe now uses the ` flutter pub add dev:test` command instead of manually modifying the `pubspec.yaml` file and specifying the version, as the original content suggested.
