### ISSUE TITLE
wont open in Egypt

### ISSUE THREAD

**Issue by maxzod** [flutter/website#8446]
### Describe the problem

site is down for Egyptian users no one in Egypt can open https://flutter.dev/ 
i can access it with vpn only

### Expected fix

to acces it without any vpn

### Additional context

pub cli is also down

**Comment by bonaparta13** [comment]
Same here

**Comment by MostafaKhalile** [comment]
same for me too .

**Comment by mohamed352** [comment]
same for me

**Comment by AbdullahGaber** [comment]
same here

**Comment by shadysamir** [comment]
The issue has to do with an apparent blockage of some Google servers from Egypt. It affects firebase and some Google cloud platform services as well.

**Comment by ahmed2hamy** [comment]
Same here

**Comment by KhaledElmetwaly** [comment]
same here

**Comment by MostafaKhalile** [comment]
Now it's working for me

**Comment by mohamed-seiam** [comment]
Same here website not open

**Comment by ahmedwaleed3378** [comment]
Yes I got the same problem, hope they could find a solution soon

**Comment by MostafaElswefy** [comment]
same problem here

**Comment by abdullahehab** [comment]
Yes I got the same problem, hope they could find a solution soon

**Comment by moazelsawaf** [comment]
The issue has been solved and the website is normally accessible since a couple of hours.

**Comment by muhammadkamel** [comment]
Still facing the same issue.

**Comment by kirolosibrahim** [comment]
same

**Comment by danagbemava-nc** [comment]
Hi all, what errors do you get in your console? Can your try different ISPs to see if you're able to access the website?

**Comment by danagbemava-nc** [comment]
Hi all, what errors do you get in your console? Can your try different ISPs to see if you're able to access the website?

**Comment by maxzod** [comment]
@danagbemava-nc 
i tried difrrent  of ISP
- we
- vodafone
- orange
some times they work , some times don't

**Comment by danagbemava-nc** [comment]
Hi @maxzod, what errors do you get in your console if any?

**Comment by maxzod** [comment]
@danagbemava-nc  for now every thing seems to work just fine ,
if flutter web site is hosted in firebase hosting 
it would be the one cusing this issue during firebase blockage in Egypt 
but i't does not appear to solve broken pub CLI which works fine now !

**Comment by sfshaza2** [comment]
I don't know that there's anything we can do from here.

**Comment by parlough** [comment]
It sounds like certain ISPs in Egypt blocked Firebase hosting's IP intermittently. This happens sometimes since any site hosted on Firebase could (or does?) use the same IP, and ISPs may block that.

So unless we want to move away from Firebase hosting, there's not much we can do. We can monitor the situation and if it continues, identify or prepare some alternative suggestions for when it occurs.

**Comment by sfshaza2** [comment]
That's what I suspected. Closing.

**Comment by DevDabbagh** [comment]
I think the issue back again I tried for two days to load my packages but nothing work! : (
