### ISSUE TITLE
[PAGE ISSUE]: 'Windows install'

### ISSUE THREAD

**Issue by vidhu15** [flutter/website#8447]
### Page URL

https://docs.flutter.dev/get-started/install/windows/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/windows.md

### Describe the problem

virus detected. how to download flutter sdk nd exam is on 1 may,2023.

### Expected fix

please remove virus

**Comment by danagbemava-nc** [comment]
Hi @vidhu15, what antivirus are you using and what file is being flagged as a virus? 

Have you also tried downloading flutter using git?

**Comment by andrybicio** [comment]
@danagbemava-nc here you are. Same problem here
![image](https://user-images.githubusercontent.com/56033694/227945947-f307920e-ba28-47e8-b308-464cd2a08628.png)

**Comment by parlough** [comment]
Thanks for reporting the issue.

This was tracked in https://github.com/flutter/flutter/issues/123519 where it was determined to be a transient bug in Windows Defender. Check out the issue for more context.

If anyone experiences this again, please update us here or by creating a new issue. Thanks!
