### ISSUE TITLE
Dart, Flutter new book 2023

### ISSUE THREAD

**Issue by haytik** [flutter/website#8449]
Hello, I want the new version of Dart and the flutter Getx package, restFul API, nodejs MongoDb using Full Stack to publish the latest book for February-March 2023, and if it is published with the new book in every update published by the flutter team, it will be very clear, because Flutter is very a fast developing cross, we want all users to be aware of the innovations in every development and we would like to see their new net solutions in book form, as a teacher, I aim to teach my students clear stable structures

**Comment by danagbemava-nc** [comment]
Hi @haytik, I'm not sure what exactly it is you're requesting here. 

Is there a book you'd like to suggest or are you looking for a specific book?

**Comment by sfshaza2** [comment]
It's been 2 days without response, so I'm closing. @haytik, if you know of a book that we should list in our books page, please let us know!
