### ISSUE TITLE
[Stale data]: 'Supported deployment platforms'

### ISSUE THREAD

**Issue by fabiancrx** [flutter/website#8468]
### Page URL

https://docs.flutter.dev/reference/supported-platforms/

### Page source

https://github.com/flutter/website/tree/main/src/reference/supported-platforms.md

### Describe the problem

Lower number on most supported platforms eg:
Android until 30(android 11) when 33(android 13) is out and more important, supported by flutter.
Same with windows states 10 when latest is 11.
iOS, states 15, latest and supported 16. 
Linux etc.

As this is part of the official docs it may scare away potential developers evaluating Flutter, and seeing no support for the latest versions of the operating systems it target. I could sketch a PR updating this info is needed, provided I'm pointed to the latest data.

### Expected fix

The versions for each OS are properly updated.

**Comment by atsansone** [comment]
Fixed supported platforms in:
- https://github.com/flutter/website/pull/8409
- https://github.com/flutter/website/pull/8457
- https://github.com/flutter/website/pull/8669

Closing this issue.
