### ISSUE TITLE
[PAGE ISSUE]: 'Support for WebAssembly (Wasm)'

### ISSUE THREAD

**Issue by joelpinto** [flutter/website#8473]
### Page URL

https://docs.flutter.dev/development/platform-integration/web/wasm/

### Page source

https://github.com/flutter/website/tree/main/src/development/platform-integration/web/wasm.md

### Describe the problem

Cant find this page on the left side at `Platform integration->Web`.

**Comment by danagbemava-nc** [comment]
![Screenshot 2023-03-31 at 13 28 57](https://user-images.githubusercontent.com/88313112/229133233-246a219e-b6c8-4d9f-ba5c-017b494e4d6a.png)

**Comment by kevmoo** [comment]
This is by design. Since this feature is not available yet, we don't want to pollute the existing navigation hierarchy.
