### ISSUE TITLE
[PAGE ISSUE]: 'Flutter architectural overview' Dartpad example does not compile

### ISSUE THREAD

**Issue by fabiancrx** [flutter/website#8474]
### Page URL

https://docs.flutter.dev/resources/architectural-overview/

### Page source

https://github.com/flutter/website/tree/main/src/resources/architectural-overview.md

### Describe the problem

The example at https://dartpad.dev/?id=0f020197a5d4c980342d5c7d9e935cee  under the https://docs.flutter.dev/resources/architectural-overview#layout-and-rendering section does not compile with any version of flutter and dart. The code must be updated to null-safety. If I'm pointed to where the code is hosted I could perform the appropiate update 

### Expected fix

The code is migrated to null safety and  compiles correctly in dartpad.

**Comment by parlough** [comment]
Thanks for catching and reporting this!

The code is actually just a copy from an [example on the flutter/flutter repository](https://github.com/flutter/flutter/blob/master/examples/layers/rendering/src/sector_layout.dart) and it is currently stored [in a gist](https://gist.github.com/timsneath/0f020197a5d4c980342d5c7d9e935cee). The goal is to move away from the gist (https://github.com/flutter/website/issues/6912).

For now, while we're still using a gist for the example, we want to have control over it so we can edit it easily, but thanks for offering to fix it!

I copied the latest changes from the flutter repo and opened https://github.com/flutter/website/pull/8479. Thanks again!
