### ISSUE TITLE
復原你的 Apple ID - Apple (TW)

### ISSUE THREAD

**Issue by PushT10** [flutter/website#8477]
[Link removed]

**Comment by PushT10** [comment]
https://github.com/flutter/website/issues/8477

**Comment by parlough** [comment]
I'm not exactly sure what you're looking for, but this isn't the place to get help with your Apple ID. Consider [Apple Support](https://support.apple.com/). For help with Flutter, check out [Flutter focused communities](https://flutter.dev/community#community-grid).

This repository is for the Flutter documentation website, found at [docs.flutter.dev](https://docs.flutter.dev). If you have any issues with Flutter or its documentation, please feel free to open a new issue with some more information, thanks!
