### ISSUE TITLE
[PAGE ISSUE]: 'Introduction to widgets'

### ISSUE THREAD

**Issue by nevidomy** [flutter/website#8488]
### Page URL

https://docs.flutter.dev/development/ui/widgets-intro/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/widgets-intro.md

### Describe the problem

![Screenshot_20230405-011705](https://user-images.githubusercontent.com/335118/230023652-55dd3683-40f4-4abf-b902-879d2345b15b.png)

It basically doesn't work in Android browser. Is there a way to at least see the code? Otherwise it's pretty much useless. Please correct me if there is a way to get it work though

**Comment by nevidomy** [comment]
I stand corrected: it works in other browsers so maybe I just need to enable something, still useless though on the phone: 
![Screenshot_20230405-013038](https://user-images.githubusercontent.com/335118/230026359-a069b7d4-9213-46d4-95a1-fa3af951c700.png)

**Comment by danagbemava-nc** [comment]
Hi @nevidomy, what browser are you experiencing the issue with?

**Comment by danagbemava-nc** [comment]
I think you'll have to open it on desktop or open it with the desktop view on mobile. I'm not sure if there's a mobile mode for dartpad. 

I seem to be able to open the website on chrome on android just fine tho, with the latest version that is available to me. Do you by any chance have some privacy settings enabled?
