### ISSUE TITLE
Create a banner to help get webby votes for Wonderous

### ISSUE THREAD

**Issue by leighajarett** [flutter/website#8491]
### What information is missing?

It would be great to set up a banner on flutter.dev that asks people to vote for Wonderous in the Webby awards. Maybe something like, "Wonderous, our Flutter reference app, has been nominated for a Webby award! Help support Flutter by casting a vote here."

Here's the link --> [http://wbby.co/31745N](https://t.co/n3uRcDJ5GI)

**Comment by sfshaza2** [comment]
@timsneath, what do you think? I've held off because of the Android Studio Flamingo banner.
