### ISSUE TITLE
Fix section on gen_I10n on 'Internationalizing Flutter apps' page

### ISSUE THREAD

**Issue by moopat** [flutter/website#8503]
### Page URL

https://docs.flutter.dev/development/accessibility-and-localization/internationalization/

### Page source

https://github.com/flutter/website/tree/main/src/development/accessibility-and-localization/internationalization.md

### Describe the problem

In the section "Adding your own localized messages", item 6 says:

> Now, run **flutter gen-l10n** so that codegen takes place. You should see generated files in `${FLUTTER_PROJECT}/.dart_tool/flutter_gen/gen_l10n`. Alternatively, you can also run **flutter gen-l10n** to generate the same files without running the app.

### Expected fix

Replace the first mention of `flutter gen-l10n` with a command that runs the app as well as generates localizations (as is implied by the last sentence).

Alternatively, maybe just give the command `flutter gen-l10n` and mention in which case the localizations are generated automatically like so:

> Now, run `flutter gen-l10n` to generate the localization files. They are located in `${FLUTTER_PROJECT}/.dart_tool/flutter_gen/gen_l10n`. The same files are generated automatically when you [insert appropriate actions here].

**Comment by danagbemava-nc** [comment]
Thanks for spotting that

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/7435. Closing this issue.
