### ISSUE TITLE
Outdated commands?

### ISSUE THREAD

**Issue by aldoyh** [flutter/website#8558]
### Page URL

https://docs.flutter.dev/deployment/ios

### Describe the problem

I noticed many of the xcode* & app-store* do not exists, or I'd rather say not needed anymore, it's just I've managed to deploy without them!

It's a request to guide me or correct me if I'm wrong.

Thanks

**Comment by sfshaza2** [comment]
What do you mean, @aldoyh? How did you deploy your app on iOS?

**Comment by aldoyh** [comment]
My apologies for not pointing them out precisely, the 2 commands are `app-store-connect` and `keychain` which are from CodeMagic, located at 4# of the last section at the bottom. That's even after installing their CLI Tool.

Thanks.

**Comment by danagbemava-nc** [comment]
Hi @aldoyh, did you deploy your app using the codemagic-cli? If so, how did you do it without using the commands in the documentation?
