### ISSUE TITLE
[PAGE ISSUE]: 'Handling errors in Flutter'

### ISSUE THREAD

**Issue by Der-Stif-Meister** [flutter/website#8564]
### Page URL

https://docs.flutter.dev/testing/errors/

### Page source

https://github.com/flutter/website/tree/main/src/testing/errors.md

### Describe the problem

[core/no-app] No Firebawe App '[DEFAULT]' has been created -call Firebase.initializeApp()

### Expected fix

App to show and working.

**Comment by sfshaza2** [comment]
Hi, @Der-Stif-Meister! What, specifically, is the issue you found with that page?

**Comment by Der-Stif-Meister** [comment]
When I try to implement signInWithGoogle it gives me error message

**Comment by Der-Stif-Meister** [comment]
these are the problem i am facing.

**Comment by danagbemava-nc** [comment]
Hi @Der-Stif-Meister, the error you're facing is unrelated to this page.  You should make sure that you've followed the setup for firebase_auth properly. 

Closing as this issue not related to this page. 

Thank you
