### ISSUE TITLE
Audit websites pass through google internal accessibility rating

### ISSUE THREAD

**Issue by chunhtai** [flutter/website#8578]
### Describe the problem

This is the issue to track whether all the websites, doc.flutter.dev, flutter.dev, api.flutter.dev, have passed the internal accessibility standard. See [go/GAR](https://goto.google.com/GAR)

**Comment by chunhtai** [comment]
cc @RedBrogdon

**Comment by atsansone** [comment]
Should use [go/a11ytracker](https://goto.google.com/a11ytracker) to develop tests and run.

**Comment by atsansone** [comment]
This duplicates and is superceded by https://github.com/flutter/website/issues/9495. Closing this issue as duplicate.
