### ISSUE TITLE
Update Material Design links to Material 3

### ISSUE THREAD

**Issue by guidezpl** [flutter/website#8586]
1. Links. These can be typically be identified when `material.io` links end in `.html`. Almost every page should be updated to use `m3.material.io` links.

e.g. https://docs.flutter.dev/development/ui/layout#card links to https://material.io/design/components/cards.html but can now link to https://m3.material.io/components/cards

2. Assets. New assets can be provided

**Comment by rexthecoder** [comment]
@guidezpl I want to work on this

**Comment by rexthecoder** [comment]
@guidezpl I wanted to make PR but it seems the project is not accepting PR for now, so I will wait till 14th as instructed

**Comment by rexthecoder** [comment]
@guidezpl I have made the pr, I will list all the links I have updated so far, and you can go through I case I need to change any

**Comment by parlough** [comment]
Looks like the links were updated in https://github.com/flutter/website/pull/8706, thank you!

However, we still need to go through and audit images and other assets throughout the site to verify they were built with Material 3. It will likely be a larger undertaking that can happen across multiple pull requests.

**Comment by rexthecoder** [comment]
@guidezpl I will update my descriptions so that it does not confuse others. Meanwhile, I would like to work on this but it needs a little bit of draft to one which part we are working

**Comment by vj-codes** [comment]
I would like to work on it further @guidezpl

**Comment by atsansone** [comment]
This relates to https://github.com/flutter/website/issues/8834.

**Comment by rexthecoder** [comment]
@atsansone Where are we taking it from, I noticed you assigned it to someone earlier.

**Comment by atsansone** [comment]
@rexthecoder : You made the fix. Just giving you the credit.

**Comment by atsansone** [comment]
Closing this issue as complete and opening a new one to update assets.
