### ISSUE TITLE
[PAGE ISSUE]: 'Introduction to widgets'

### ISSUE THREAD

**Issue by yifan90** [flutter/website#8611]
### Page URL

https://docs.flutter.dev/development/ui/widgets-intro/

### Page source

https://github.com/flutter/website/tree/main/src/development/ui/widgets-intro.md

### Describe the problem

After click the run button on the examples, it shows some javascript compiling error. I understand this might be some transient issue, just want to report this.

**Comment by parlough** [comment]
Thanks for taking the time to report the issue! I've prepared a fix in https://github.com/dart-lang/dart-pad/pull/2495.

If you want to run an example in the browser in the meantime, consider copy and pasting code into the full [dartpad.dev](https://dartpad.dev) editor.
