### ISSUE TITLE
[PAGE ISSUE]: 'Add a drawer to a screen'

### ISSUE THREAD

**Issue by redouane59** [flutter/website#8612]
### Page URL

https://docs.flutter.dev/cookbook/design/drawer/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/design/drawer.md

### Describe the problem

Not able to run it
![image](https://user-images.githubusercontent.com/4500524/233795040-f873ca3c-e975-4821-9639-312081263988.png)

**Comment by parlough** [comment]
Thanks for opening an issue! I'm looking into making a fix now.

If you want to run the sample in your browser in the mean time, you can run it on the primary [dartpad.dev site](https://dartpad.dev).
