### ISSUE TITLE
帮忙删除一下，你转载的我的库

### ISSUE THREAD

**Issue by shenjianli** [flutter/website#8625]
### Page URL

https://github.com/ftc300/AndroidShoppingBase

### Page source

https://github.com/ftc300/AndroidShoppingBase

### Describe the problem

帮忙删除一下，你转载的我的库

公司要求的，谢谢！

### Expected fix

帮忙删除一下，你转载的我的库

公司要求的，谢谢！

### Additional context

帮忙删除一下，你转载的我的库

公司要求的，谢谢！

**Comment by danagbemava-nc** [comment]
Closing as this is not related to this project
