### ISSUE TITLE
Correct highlight in image on 'Layouts in Flutter' page 

### ISSUE THREAD

**Issue by sepastian** [flutter/website#8653]
### PAGE URL

https://docs.flutter.dev/ui/layout#nesting-rows-and-columns

The red box in the image below is too large.

The text accompanying the image talks about the first row only, i.e. "5 stars" and "170 reviews".

Source: https://github.com/flutter/website/blob/d9fd7eb9be3dd0ad9083d990c96fb9916656213f/src/ui/layout/index.md?plain=1#L496-L497

Image:

![](https://docs.flutter.dev/assets/images/docs/ui/layout/pavlova-large-annotated.png)

**Comment by atsansone** [comment]
The highlighted part of the image doesn't cover just the first code example but all code examples in the section. This works as designed. Closing.
