### ISSUE TITLE
Fix link to codelab on 'Casual Games Toolkit' page

### ISSUE THREAD

**Issue by Stef-GMS** [flutter/website#8663]
### Page URL

https://docs.flutter.dev/resources/games-toolkit/

### Page source

https://github.com/flutter/website/tree/main/src/resources/games-toolkit.md

### Describe the problem

The link to the codelab returns a 404 message. 

### Expected fix

Change the link to https://codelabs.developers.google.com/codelabs/flutter-flame-game

**Comment by parlough** [comment]
Thanks for the heads up!

Looks like the actual link is https://codelabs.developers.google.com/codelabs/flutter-flame-game. We'll make sure to get it updated once the site is unfrozen.

**Comment by Stef-GMS** [comment]
Thanks for the update.  I removed the `#0` from the URL in my issue.  I thought I'd done that before submitting.
