### ISSUE TITLE
Update Firebase Auth Codelab to use working packages

### ISSUE THREAD

**Issue by tulipandmills** [flutter/website#8667]
### Page URL

https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps

### Describe the problem

The tutorial is based on the deprecated firebase_ui
A working tutorial can be found here:
https://github.com/firebase/flutterfire/tree/master/packages/firebase_ui_auth/doc

### Expected fix

Link to
https://github.com/firebase/flutterfire/tree/master/packages/firebase_ui_auth
on the code lab page

**Comment by sfshaza2** [comment]
@puf or @ericwindmill , can you weigh in?

**Comment by ericwindmill-discovery** [comment]
Yes, this needs to be updated to the new package, and it's on my short list of things to do.

**Comment by parlough** [comment]
Thanks for opening an issue!

This was fixed by https://github.com/flutter/codelabs/commit/87e083c3675459f3e266f75aad6ce7089425ae40 and [the codelab](https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps) has been updated to `package:firebase_ui_auth` :)
