### ISSUE TITLE
Add a help page for installing Flutter

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#8677]
### What information is missing?

Flutter's installation pages don't currently point users to helpful information and resources when they got stuck. Users are on their own to search the web to find solutions. Though Flutter's communities have been helping newcomers resolve setup issues in a few online forums (e.g., StackOverflow, [r/flutterhelp](https://www.reddit.com/r/flutterhelp/), and [Discord](https://discord.com/channels/420324994703163402/825210392137433089)), new users wouldn't know their existence and could be easily discouraged by a blocker in the setup process.

### How would you like us to fix this problem?

I suggest we try the following:

- [x] Create a help page for installing Flutter, organized by the steps in the installation process. The initial content will be sourced from archived Q&A threads in relevant forums and nominated by community members who have helped new users setup Flutter.
- [x] From the help page, link to relevant online forums for asking setup-related questions.
- [ ] Add a help button/link to each section of installation pages. It will take the user to the relevant part of the help page. Click through rates of different help buttons will tell us which steps are more challenging than others. 

### Request for content suggestions

If anyone reading this issue is aware of common blockers in Flutter's setup process, please comment below. Better yet, include a suggested solution.

**Comment by atsansone** [comment]
@InMatrix : This may not be needed if the install pages are adjusted properly. I hope we can make that happen.

**Comment by InMatrix** [comment]
@atsansone Yes, I'd like to see visits to this page goes down after the install pages are revised. 

I'm reopening this issue since the last step, linking to the help page from install pages, haven't done yet. I plan on doing that later this month.

**Comment by parlough** [comment]
@atsansone Tao reopened this since the links to the troubleshooting page haven't been added yet. I think we should reopen this to track that work.
