### ISSUE TITLE
Add adaptation information for text fields

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#8678]
- [x] Publish a guide on flutter/uxr 
  - https://github.com/flutter/uxr/discussions/95
- [ ] Add a TL;DR to https://docs.flutter.dev/resources/platform-adaptations#ui-components

**Comment by atsansone** [comment]
@InMatrix : What did you have in mind for the TL;DR? I'm not 100% sure what the dev would need to do from https://github.com/flutter/uxr/discussions/95. Thanks!

**Comment by InMatrix** [comment]
@atsansone Thanks for the ping. Developers will be able to customize a Material TextField into an iOS-like TextField using the snippets from https://github.com/flutter/uxr/discussions/95.

I haven't got around to complete the second task on the list yet.

**Comment by leighajarett** [comment]
I can do it later this week
