### ISSUE TITLE
Update where `setSemanticsEnabled` is found on 'Accessibility' page

### ISSUE THREAD

**Issue by dmosdallas** [flutter/website#8686]
### Page URL

https://docs.flutter.dev/accessibility-and-localization/accessibility/

### Page source

https://github.com/flutter/website/tree/main/src/accessibility-and-localization/accessibility.md

### Describe the problem

Under Screen Readers --> Browser, this page states:

> Screen Readers users on web will need to toggle “Enable accessibility” button to build the semantics tree. Users can skip this step if you programmatically auto-enable accessibility for your app using this API:
> 
> RendererBinding.instance.setSemanticsEnabled(true)

However, it looks like the `setSemanticsEnabled` function is no longer a part of `RendererBinding` in flutter 3.10

### Expected fix

Guide should provide up-to-date details on how to programmatically auto-enable accessibility for an app.

**Comment by danagbemava-nc** [comment]
It looks like this was moved to the SemanticsBinding class instead. See https://github.com/flutter/flutter/pull/121289

Thanks for pointing this out

**Comment by aakashawalkar** [comment]
For Flutter 3.10.0, Replace `RendererBinding.instance.setSemanticsEnabled(true);` with `SemanticsBinding.instance.ensureSemantics();`
