### ISSUE TITLE
Remove JDK requirement in Android setup

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#8691]
### Page URL

https://docs.flutter.dev/get-started/install/windows#agree-to-android-licenses

### Page source

https://github.com/flutter/website/blob/main/src/get-started/install/_android-setup.md

### Describe the problem

In the "Agree to Android Licenses" section, 

> 1. Make sure that you have a version of Java 11 installed and that your JAVA_HOME environment variable is set to the JDK’s folder.
> 
> Android Studio versions 2.2 and higher come with a JDK, so this should already be done.

There's nothing we ask the user to do here. Since Android Studio was released [back in 2016](https://developer.android.com/studio/releases/past-releases/as-2-2-0-release-notes), it's very unlikely a new Flutter user is stuck with that version. 

### Expected fix

Remove the quoted lines. 

### Additional context

The issue was reported by a community member in the flutter discord server. Here's a [link to the OP](url).

**Comment by 0xj0hn** [comment]
I have the same issue.
Even if I change the environment variable "JAVA_HOME" to my Java directory, it doesn't change the java version

**Comment by parlough** [comment]
@0xj0hn Doesn't change the Java where? Would you mind opening a new issue with more information about the issue you are having and the output of `flutter doctor -v`? Thanks!
