### ISSUE TITLE
Support collapsible sections

### ISSUE THREAD

**Issue by InMatrix** [flutter/website#8697]
### Describe the problem

@atsansone and I were discussing the possibility to have users skip over some steps when installing Flutter based on their selected target platforms. For example, if someone is interested in building a Windows app only, they won't need the Android setup instructions. It could be useful to collapse that section entirely. What would be the best way to add that UI pattern to the website? 

@parlough you might have ideas? 🙂

**Comment by parlough** [comment]
This is definitely something we could do and we have some similar constructs already. Depending on the design and if different sections interact with each other, a custom Jekyll/Liquid tag(https://jekyllrb.com/docs/plugins/tags/) with a little JS should be sufficient.

**Comment by InMatrix** [comment]
Great. I think we need to be able to programmatically close and open sections based on user input (e.g., selecting a target platform from a list or checking off a step as "done"). Are there examples of doing that in Jekyll you can point me to?

**Comment by atsansone** [comment]
As this site uses GitHub flavored Markdown, it does support the `<detail>` and `<summary>` tags to create a simple accordion.

Closed
![Image](https://github.com/flutter/website/assets/706219/bc1b10b2-9531-4c2b-9a6d-5faf6ba80195)

Open
![Image](https://github.com/flutter/website/assets/706219/9bc50ccf-fc07-49f9-82b5-43898a0eb5c4)

It may need some styling, but it does work.

@InMatrix : If this meets your need, please close this issue.

**Comment by InMatrix** [comment]
Thanks for the suggestion. It looks like a good solution to start. If the revised workflow requires more sophisticated controls (e.g., pragmatically expanding and collapsing sections), we can open another issue.

**Comment by parlough** [comment]
Sorry I missed the last question. Tony used the collapsible sections in his latest OEM work and we can work with that for now.

Please open an issue or ping me if we need any specific functionality. It might be different depending on the specific problem and I'd be happy to help set that up that.
