### ISSUE TITLE
Fix image bottom overflow and const keyword warning in DartPad on 'Implicit animations' codelab

### ISSUE THREAD

**Issue by AKR-2803** [flutter/website#8728]
### Page URL

[Page URL](https://docs.flutter.dev/codelabs/implicit-animations)

### Page source

[Page Source](https://github.com/flutter/website/blob/main/src/codelabs/implicit-animations.md)

### Describe the problem

The Fade-in [starter code](https://docs.flutter.dev/codelabs/implicit-animations#fade-in-starter-code) and Fade-in [complete](https://docs.flutter.dev/codelabs/implicit-animations#fade-in-complete) code in iFrames need to be modified to remove the bottom pixels overflow due to the owl image. Moreover const keywords can be added where necessary (The const keyword warning can be seen in the iFrames of both these sections on the page)

Changes needed here: 
### Expected fix

Either of these fixes will work (for both sections): 

1. Wrapping the main column using SingleChildScrollView.

If the requirement is to display the output without any scroll.

2. Adjusting image height to 80% of the screen MediaQuery.

### Additional context

I can file a PR with the changes if permitted. Do let me know the status of the issue. 

Screenshots for reference : 

[Starter Code](https://docs.flutter.dev/codelabs/implicit-animations#fade-in-starter-code)
![Screenshot (205)](https://github.com/flutter/website/assets/109909231/062b1198-dfe6-4dd9-8920-af32255094c0)
<br/>
[Complete Code](https://docs.flutter.dev/codelabs/implicit-animations#fade-in-complete)
![Screenshot (206)](https://github.com/flutter/website/assets/109909231/14b2758c-5f6e-4d3f-a843-645631ea0206)

**Comment by danagbemava-nc** [comment]
Hi @AKR-2803, thanks for filing this. 

Which platform(s) do you see the overflow error on?

**Comment by atsansone** [comment]
@AKR-2803 : I'm seeing it too in Chrome. Go ahead and create a PR. Thanks!
