### ISSUE TITLE
Remove Android references on 'Hosting native iOS views in your Flutter app with Platform Views' page

### ISSUE THREAD

**Issue by timsneath** [flutter/website#8741]
### Page URL

https://docs.flutter.dev/development/platform-integration/ios/platform-views/

### Page source

https://github.com/flutter/website/tree/main/src/development/platform-integration/ios/platform-views.md

### Describe the problem

This iOS-focused page includes information on Android, which suggests it hasn't been fully reviewed with iOS in mind.

Specifically:

> Prior to Android 10, hybrid composition copied each Flutter frame out of the graphic memory into main memory, and then copied it back to a GPU texture. As this copy happens per frame, the performance of the entire Flutter UI might be impacted. In Android 10 or above, the graphics memory is copied only once.

### Expected fix

We should remove this paragraph, but it would also be great to check that the rest of this section is relevant to iOS developers.

### Additional context

/cc @leighajarett

**Comment by leighajarett** [comment]
@Tim Sneath ***@***.***> thanks for taking care of this! I
totally forgot 😅
