### ISSUE TITLE
Correct code example that returns error on 'Adding a Flutter screen to an iOS app' page

### ISSUE THREAD

**Issue by eKaramihov** [flutter/website#8756]
### Page URL

https://docs.flutter.dev/add-to-app/ios/add-flutter-screen/

### Page source

https://github.com/flutter/website/tree/main/src/add-to-app/ios/add-flutter-screen.md

### Describe the problem

The example below to run a flutter engine with entry route cause:

FlutterDefaultDartEntrypoint causes Xcode error: 
```terminal
Undefined symbol: _FlutterDefaultDartEntrypoint
```

Example:
```dart
let flutterEngine = FlutterEngine()
// FlutterDefaultDartEntrypoint is the same as nil, which will run main().
engine.run(
  withEntrypoint: FlutterDefaultDartEntrypoint, initialRoute: "/onboarding")
```

**Comment by leighajarett** [comment]
Yes this seems to be an issue I was able to replicate. @hellohuanlin it seems to work with specifying "main" as the entrypoint -- do you think that's okay to use in the example instead?

**Comment by hellohuanlin** [comment]
Im not familiar with this, but just from the comment, `FlutterDefaultDartEntrypoint` seems to be just a placeholder, if i read it right. Can you try if passing `nil` works?

**Comment by hellohuanlin** [comment]
@eKaramihov did you accidentally used `_FlutterDefaultDartEntrypoint` rather than `FlutterDefaultDartEntrypoint` in your code?

**Comment by leighajarett** [comment]
I tried both @hellohuanlin  - "main" worked so I think it's fine to leave
