### ISSUE TITLE
Provide IDE agnostic steps for 'Binding to native macOS code using dart:ffi' page

### ISSUE THREAD

**Issue by mpl** [flutter/website#8767]
### Page URL

https://docs.flutter.dev/platform-integration/macos/c-interop/

### Page source

https://github.com/flutter/website/tree/main/src/platform-integration/macos/c-interop.md

### Describe the problem

This doc completely relies on XCode.
None of the explanation actually tells what's actually happening under the scenes.
e.g. where the dynamic library files end up being copied? which file should be edited to specify that location? etc.
So it's quite useless for someone not using XCode.

### Expected fix

Actually explains the steps, and the project layout, for someone not relying on XCode.
I get that's a lot more work and information, but any additional tidbit would help...

Edit: for example, through additional external research, I've just found out that that I could disable sandboxing by editing macos/Runner/DebugProfile.entitlements , which I would have been happy to find out on that page.

**Comment by atsansone** [comment]
@leighajarett : Could you take a first look at this page to see what we could change?

**Comment by leighajarett** [comment]
I don't think I know enough to be useful here. @liamappelbe may be able to help

**Comment by dcharkes** [comment]
@mpl if you're in Flutter, and you have only source code (not prebuilt binaries), please use `flutter create --template=plugin_ffi --target=... <project-name>`. That sets up the build correctly.

For prebuilt binaries, you'll have to modify the (generated) podspec.

Modifying the generated native build files is far from a desirable state. It's different for the different OSes, CocoaPods/Gradle/CMake. And it requires knowledge of all these build systems. (Also, it doesn't work in Dart standalone.)
We're working on a new feature "Native assets" which will work in both Dart and Flutter without the need to modify CocoaPods/Gradle/CMake build files: https://github.com/dart-lang/sdk/issues/50565. Once that feature is complete hopefully all this pain will go away.

On your specific question for documentation, I'm not an expert either. The only way I figure this out is by committing all generated files, doing the change in XCode and seeing what changed. Feel free to make PRs to the mentioned documentation page to include how to do the steps without XCode. (I wouldn't say that the XCode file formats are particularly user friendly outside XCode, so maybe this is not the right work flow?)

**Comment by mpl** [comment]
Hi @dcharkes ,

As I said, at the time when I wrote that issue, my main problem was to find how to disable sandboxing for a macos app _without_ the use of XCode, which I eventually did figure out from somewhere else. Maybe if there had been more generic information about the structure of macos project on that documentation page (me being a newbie at coding native apps for macos) I would have figured it out earlier. Then again, maybe that kind of information does not belong within the flutter project itself, who knows.

Anyway, I have been able to keep going without XCode so far, so I'm good and knocking on wood.

If you think the tidbit about sandboxing can be useful, I sure can make a PR for it if you want.
Otherwise, please feel free to close the issue.

Thanks.
