### ISSUE TITLE
Add wasm to the sidenav

### ISSUE THREAD

**Issue by liudonghua123** [flutter/website#8773]
### Page URL

https://docs.flutter.dev/platform-integration/web/wasm

### Page source

https://github.com/flutter/website/blob/c419f60842e68113518b5731a0fdc7e9dc5d1e7c/src/platform-integration/web/wasm.md

### Describe the problem

The [sidenav.yml](https://github.com/flutter/website/blob/c419f60842e68113518b5731a0fdc7e9dc5d1e7c/src/_data/sidenav.yml#L222-L234) seems not synchronized while The [wasm](https://github.com/flutter/website/blob/c419f60842e68113518b5731a0fdc7e9dc5d1e7c/src/platform-integration/web/wasm.md) page and https://docs.flutter.dev/platform-integration/web/wasm is avaliable already.

The source code is not updated to the official docs.

https://github.com/flutter/website/blob/c419f60842e68113518b5731a0fdc7e9dc5d1e7c/src/_data/sidenav.yml#L222-L234

missing 

```yml
        - title: Support for WebAssembly (Wasm)
          permalink: /platform-integration/web/wasm
```

**Comment by kevmoo** [comment]
Ha! I need to put a comment in that file. Excluding wasm was/is intentional, since it's in preview.
