### ISSUE TITLE
Remove empty circle on image in 'Hot reload' page

### ISSUE THREAD

**Issue by DemX86** [flutter/website#8777]
### Page URL

https://docs.flutter.dev/tools/hot-reload/

### Page source

https://github.com/flutter/website/tree/main/src/tools/hot-reload.md

### Describe the problem

The image with Android Studio run controls has redundant graphics circle element:

![image](https://github.com/flutter/website/assets/30806939/805bcd98-5b92-4ab3-ae02-46637c0cfc05)

Image address: `/assets/images/docs/development/tools/android-studio-run-controls.png`

### Expected fix

Remove that empty circle element from the image

### Additional context

I can edit the image but I have no idea how to add it to the Flutter site

**Comment by sfshaza2** [comment]
Hi, @DemX86, why does the circle bother you so?

**Comment by DemX86** [comment]
> Hi, @DemX86, why does the circle bother you so?

I think a negligence (even by chance) is not what Flutter about

**Comment by camsim99** [comment]
Image to fix: https://github.com/flutter/website/blob/main/src/assets/images/docs/development/tools/android-studio-run-controls.png
