### ISSUE TITLE
Expand description of CanvasKit on 'Web renderers' page

### ISSUE THREAD

**Issue by 911432** [flutter/website#8783]
### Page URL

https://docs.flutter.dev/platform-integration/web/renderers/

### Page source

https://github.com/flutter/website/tree/main/src/platform-integration/web/renderers.md

### Describe the problem

CanvasKit renderer description is insufficient.

### Expected fix

CanvasKit renderer that uses WebAssembly and WebGL to render Skia paint commands to the browser canvas.

### Additional context

I don't know if [Support for WebAssembly (Wasm)](https://docs.flutter.dev/platform-integration/web/wasm)  is the same as CanvasKit renderer or different.

**Comment by sfshaza2** [comment]
@kevmoo @johnpryan, can you comment on this?

**Comment by johnpryan** [comment]
I added some more details here: https://github.com/flutter/website/pull/8844
