### ISSUE TITLE
Verify currency of 'Supported deployment platforms'

### ISSUE THREAD

**Issue by CBeening** [flutter/website#8787]
### Page URL

https://docs.flutter.dev/reference/supported-platforms/

### Page source

https://github.com/flutter/website/tree/main/src/reference/supported-platforms.md

### Describe the problem

Are the supported Android SDK versions still correct?
I would have expected Android 13 to be supported, therefore finding Android SDK 33 in the list.

**Comment by atsansone** [comment]
@CBeening , yes, these were checked ahead of Flutter 3.10 and merged in https://github.com/flutter/website/commit/167766d815566eaeddd6540d4dd46cfcfe6d8cca. Please let me know if you need more information, otherwise I'll close this ticket tomorrow.

**Comment by atsansone** [comment]
My understanding is that we support Android 21 to 30.

**Comment by atsansone** [comment]
Content is current as of Flutter 3.10. Closing issue.

**Comment by parlough** [comment]
Note that the "Supported" category just indicates a version is well tested but it doesn't exclude other/later versions from working well too.

However, it does seem 31 and 33 are both tested to various extents in flutter/flutter's ci as of 3.10 - https://github.com/flutter/flutter/blob/3.10.3/.ci.yaml

@reidbaker @camsim99 I just want to verify the following (from [Supported deployment platforms](https://docs.flutter.dev/reference/supported-platforms)) is correct as of Flutter 3.10?

Platform version | Supported | Best effort | Unsupported
-- | -- | -- | --
Android SDK | 21-30 | 19-20 | 18-

**Comment by camsim99** [comment]
@parlough I would say this is outdated. We support up to 31, and we are in the process of bumping that to 33.
