### ISSUE TITLE
Add Flutter Apps Development Book to 'Books' page

### ISSUE THREAD

**Issue by Eng-Mouaz-M-AlShahmeh** [flutter/website#8827]
[Flutter Apps Development](https://www.amazon.com/dp/B0C6BSMR7N)
by Mouaz M. Al-Shahmeh
Build Cross-Platform Flutter Apps with Trust (First Edition - June - 2023) (Flutter 3.10 - Dart 3)

**Comment by sfshaza2** [comment]
Congrats on the new book, @Eng-Mouaz-M-AlShahmeh!

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
> Congrats on the new book, @Eng-Mouaz-M-AlShahmeh!

Thanks
