### ISSUE TITLE
Improve links, status, mentions in 'Impeller rendering engine' page

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/website#8836]
### Page URL

https://docs.flutter.dev/perf/impeller/

### Page source

https://github.com/flutter/website/tree/main/src/perf/impeller.md

### Describe the problem

1) Please consider linking some info on how far along it is for android and ios in terms of what situations migth want us to enable/disable, migration path,etc. (eg svgs)

2) It's a bit confusing that this is a situation build and run don't work the same, maybe highlight that
3) flutter run --help, didn't mention, maybe consider that

thank you

**Comment by atsansone** [comment]
Includes:

- [ ] https://github.com/flutter/website/pull/9114
- [ ] https://github.com/flutter/website/pull/9019
- [ ] https://github.com/flutter/website/pull/8918
- [ ] https://github.com/flutter/website/pull/8607
- [ ] https://github.com/flutter/website/pull/8823
- [ ] https://github.com/flutter/website/pull/9810

**Comment by atsansone** [comment]
Project complete.
