### ISSUE TITLE
Add web section to "Add to App" documentation

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#8842]
The [Add Flutter to an existing app](https://docs.flutter.dev/add-to-app) page should have instructions for how to include a Flutter app in an existing web application

**Comment by sfshaza2** [comment]
John, is there more to it than using an iframe?  @johnpryan

**Comment by johnpryan** [comment]
Yes, there are two different ways:
- Use an iframe
- Specify a `hostElement` when the app is bootstrapped (This is already documented on the [Embedding a Flutter app into an HTML page
](https://docs.flutter.dev/deployment/web#embedding-a-flutter-app-into-an-html-page) page.)

**Comment by jmagman** [comment]
@ditman I believe you did this? https://docs.flutter.dev/platform-integration/web/embedding-flutter-web

**Comment by ditman** [comment]
Yes, I think this could be resolved. I added new docs on how to:

* Embed flutter on a web
* Embed web content on a flutter web app
* Linked from the Add-to-app section for people to discover how to embed.

**Comment by johnpryan** [comment]
Thanks for incorporating this in your new docs updated @ditman!
