### ISSUE TITLE
Fix reference to splash screen on 'Adding a splash screen to your iOS app' page

### ISSUE THREAD

**Issue by under3415** [flutter/website#8858]
### Page URL

https://docs.flutter.dev/platform-integration/ios/splash-screen/

### Page source

https://github.com/flutter/website/tree/main/src/platform-integration/ios/splash-screen.md

### Describe the problem

iOS "launch screen" is not the same as a splash screen.

`A launch screen isn’t an onboarding experience or a splash screen, and it isn’t an opportunity for artistic expression. A launch screen’s sole function is to enhance the perception of your experience as quick to launch and immediately ready to use.`
[Source](https://developer.apple.com/design/human-interface-guidelines/launching#Launch-screens)

I think they want devs to display an image of the app home screen to make it appear the app has loaded before it actually has :-D

Apple Guideline: `Design a launch screen that’s nearly identical to the first screen of your app.`

### Expected fix

Remove "Splash screens (also known as launch screens)" and replace with a quick explanation that iOS launch screen is conceptually different to Android and Windows splash screen and refer reader to Apple docs.

**Comment by atsansone** [comment]
@stuartmorgan : Would this change be appropriate?

**Comment by stuartmorgan** [comment]
Yes, we should use the relevant platform-specific terminology to describe this platform-specific behavior, and the Apple HIG is pretty explicit about "launch screen" being the term here.
