### ISSUE TITLE
[PAGE ISSUE]: 'Background processes'

### ISSUE THREAD

**Issue by muremer42** [flutter/website#8861]
### Page URL

https://docs.flutter.dev/packages-and-plugins/background-processes/

### Page source

https://github.com/flutter/website/tree/main/src/packages-and-plugins/background-processes.md

### Describe the problem

Nowhere teaching background code execute.
I have a ready stepcounter project 11 month ago,still I'm forcing
but I can't execute my step count code in background.

### Expected fix

make a clear background executable things.

**Comment by huycozy** [comment]
Thanks for the report! This is a known issue being tracked at #1986. Closing this issue as a duplicate, so please follow up on it for further updates.
