### ISSUE TITLE
Page menu covered when scrolling to the bottom on Android Firefox

### ISSUE THREAD

**Issue by kevlar700** [flutter/website#8900]
### Page URL

https://docs.flutter.dev/reference/flutter-cli

### Describe the problem

The footer covers the menu even when scrolling back up unless desktop mode is enabled.

### Expected fix

No Idea. I use Flutter to get away from these problems that even plague netflix and disney+. Perhaps the flutter site should be rewritten in Flutter!

p.s. I am not joking. Web tech really sucks. 😂

**Comment by atsansone** [comment]
@kevlar700 : Would you happen to have a screenshot you could share? Does this occur on a mobile device? Which device? Thanks for your help!

**Comment by kevlar700** [comment]
![Screenshot_20230615_200202_Firefox](https://github.com/flutter/website/assets/3075262/1ef54773-b0bd-46ce-981c-7b444c368ecb)
Samsung xcover5

To be fair, if you pull down on the actual footer, it does move down.

**Comment by parlough** [comment]
Thanks for the screenshot! Another fix I'm working on should solve this I hope. I'll respond here with a staging link once it's ready.
