### ISSUE TITLE
Fix Impeller key for iOS

### ISSUE THREAD

**Issue by leighajarett** [flutter/website#8907]
### Page URL

https://docs.flutter.dev/perf/impeller

### Describe the problem

This seems incorrect:

To disable Impeller on iOS when deploying your app, add the following tags under the top-level `<dict>` tag in your app’s `Info.plist` file.

```xml
  <key>FLTEnableImpeller</key>
  <false />
```

I would expect that this key enables Impeller, not disables it? 

@chinmaygarde can you confirm?

**Comment by darshankawar** [comment]
@leighajarett Hi,
Please check [this](https://github.com/flutter/website/issues/8672) and see if it helps to clarify.

**Comment by atsansone** [comment]
@leighajarett : Also, check out https://github.com/flutter/website/pull/8681.

**Comment by domesticmouse** [comment]
Hey @leighajarett, given the value of `false` this makes sense as a disable. If memory serves, we used to enable Impeller on iOS as follows:

```xml
  <key>FLTEnableImpeller</key>
  <true />
```

This means that what has changed is that the default value for `FLTEnableImpeller` has changed from `false` to `true`.

**Comment by chinmaygarde** [comment]
cc @jonahwilliams @cbracken Are we correctly reading the plist entry on macOS? I tried to scour through the commit logs but didn't find where we set this up.

@domesticmouse The default (whatever it is) only holds if the key is missing. The default is "on" on iOS and "off" on macOS today.

**Comment by leighajarett** [comment]
Sorry I misread it as enable!

**Comment by cbracken** [comment]
> Are we correctly reading the plist entry on macOS? I tried to scour through the commit logs but didn't find where we set this up.

@chinmaygarde - yep.
https://github.com/flutter/engine/blob/9babd40c04b16659d44fa2caa0d1c2cc653c47ca/shell/platform/darwin/macos/framework/Source/FlutterDartProject.mm#L62-L69
