### ISSUE TITLE
Add section on Impeller preview for macOS to 'Impeller' page

### ISSUE THREAD

**Issue by leighajarett** [flutter/website#8908]
### Page URL

https://docs.flutter.dev/perf/impeller.

### Describe the problem

In the next stable release Impeller will be available in preview for macOS. We should encourage mac developers to test it out and file issues, but also make it clear it may not be ready for production. 

### Expected fix

Add macOS section to https://docs.flutter.dev/perf/impeller. macOS uses the same enable impeller flag  / key as iOS.

**Comment by leighajarett** [comment]
Hi @domesticmouse - quick note about this, can we include some of the information Chinmay added here: https://docs.google.com/document/d/1ou4kH0UtlwS5ris1lZln0wIH79B2skfyPAr0fDG3E9k/edit?resourcekey=0-IjdiEcrEexLi5erPbBI3FA, to help customers with filing relevant issues for us :)

**Comment by atsansone** [comment]
Fixed by https://github.com/flutter/website/pull/9114
