### ISSUE TITLE
Fix code on Step 4 in 'Building layouts' page

### ISSUE THREAD

**Issue by nanselmo** [flutter/website#8922]
### Page URL

https://docs.flutter.dev/ui/layout/tutorial/

### Page source

https://github.com/flutter/website/tree/main/src/ui/layout/tutorial.md

### Describe the problem

In Step 4, the instructions indicate using a Container widget, but the sample code doesn't use a Container widget, and uses a Padding() widget instead. 

### Expected fix

Two choices
1. Update the instructions to indicate using a Padding widget
2. Update the code to use a Container widget

### Additional context

I don't know enough Flutter to know which widget choice is more common or adventageous. The Container widget can provide more properties, if more than just Container.padding is needed in the future.

**Comment by atsansone** [comment]
This was fixed in https://github.com/flutter/website/pull/9088. Closing.
