### ISSUE TITLE
Update bonjour services screenshot in Integrate a Flutter module into your iOS project

### ISSUE THREAD

**Issue by dafurman** [flutter/website#8967]
### Page URL

https://docs.flutter.dev/add-to-app/ios/project-setup#local-network-privacy-permissions

### Page source

https://github.com/flutter/website/tree/main/src/add-to-app/ios/project-setup.md

### Describe the problem

The written documentation says to use `_dartVmService._tcp` for `NSBonjourServices`, but the screenshot shows `_dartobservatory._tcp`.

Likely related to https://github.com/flutter/flutter/issues/126838

### Expected fix

I haven't had any success getting a local network prompt to show per the instructions, but it seems like the screenshot at least should be updated to say `_dartVmService._tcp`

**Comment by atsansone** [comment]
Fixed in https://github.com/flutter/website/pull/10699
