### ISSUE TITLE
Adjust 'Create gradient chat bubbles' for web support

### ISSUE THREAD

**Issue by parlough** [flutter/website#8971]
### Page URL

https://docs.flutter.dev/cookbook/effects/gradient-bubbles

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/effects/gradient-bubbles.md

### Describe the problem

The cookbook was created when the discussed APIs were not supported on web, so it mentions it won't work on web and doesn't have an interactive example.

### Expected fix

Now that they are, the mention of web's lack of support should be removed and the interactive example should be added as an embedded DartPad.

**Comment by parlough** [comment]
@miquelbeltran Would you have bandwidth to work on this?

**Comment by miquelbeltran** [comment]
yep! self-assigning
