### ISSUE TITLE
Update VSCode launch configuration file in 'Debug your add-to-app module'

### ISSUE THREAD

**Issue by Nikzed** [flutter/website#8989]
### Page URL

https://docs.flutter.dev/add-to-app/debugging/

### Page source

https://github.com/flutter/website/tree/main/src/add-to-app/debugging.md

### Describe the problem

Mistake in ```.vscode/launch.json``` formatting:
```
{
  name: "Flutter: Attach",
  request: "attach",
  type: "dart",
}
```

should be:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter: Attach",
            "request": "attach",
            "type": "dart",
        },
    ]
}
```

### Expected fix

Change the document

**Comment by danagbemava-nc** [comment]
Hi @Nikzed, the configuration isn't exactly wrong, but it could be improved. If you attempt to create a launch config in vscode, it generates all the additional information for you(ie, the version & configurations properties) so you can just copy and paste the configuration for flutter attach and you are good to go. If you do create it manually, then you will need to add the configuration & version properties. 

Thanks for drawing our attention to this.

**Comment by atsansone** [comment]
This can be fixed after https://github.com/flutter/website/pull/8964 is merged.

The process is:

1. Press Command + Shift + D

2. Click [create a launch.json file].
   VS Code generates and opens `launch.json`.

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "my_app",
            "request": "launch",
            "type": "dart"
        },
        {
            "name": "my_app (profile mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "profile"
        },
        {
            "name": "my_app (release mode)",
            "request": "launch",
            "type": "dart",
            "flutterMode": "release"
        }
    ]
}
```
