### ISSUE TITLE
Add additional instruction  in 'macOS install'

### ISSUE THREAD

**Issue by LBrian** [flutter/website#8990]
### Page URL

https://docs.flutter.dev/get-started/install/macos/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/macos.md

### Describe the problem

Last paragraph of step 3 in `Deploy to iOS devices`, accurately it is **General > VPN & Device Management** on `iPhone 7 + iOS 15.7.7`. Not a big deal but could potentially get confused

> Then, go to the Settings app on the iOS device, select General > Device Management and trust your Certificate. For first time users, you might need to select General > Profiles > Device Management instead.

### Expected fix

To avoid naming inconsistency over time due to iOS release new versions, maybe can add an additional instruction such as **Settings > Search "Developer"** as it will be the only/first result, quick and easy instead of trying to find it manually word by word

**Comment by atsansone** [comment]
This page had additional issues to resolve as it had the automatic signing of certs section and steps in the wrong part of the workflow. The PR resolves this issue. This would be a case of reading the entire page to see if everything flows correctly.
