### ISSUE TITLE
Improve sidebar hierarchy: resources & reference sections

### ISSUE THREAD

**Issue by guidezpl** [flutter/website#8998]
### Describe the problem

I think the bottom two sections of the sidebar (Resources and Reference) can be a bit overwhelming and serve as a catch-all for certain pages.

### Expected fix

I'm proposing (subjectively) simplification and consolidation:
- introducing a new top-level `Flutter` or `About Flutter` header
- move or remove links based on pertinence
- removing the `Resources - Concepts` and `Resources - General` subsections
- removing the `Reference` section
- removing the flutter CLI page because it duplicates `flutter help` and `flutter pub`

Detailed proposal | Possible end state
--- | ---
<img width="442" alt="Screenshot 2023-07-08 at 10 40 16" src="https://github.com/flutter/website/assets/6655696/3edcd45d-746c-4b92-a802-2edfa4fcdcd6"> |  <img width="442" alt="Screenshot 2023-07-08 at 10 40 16" src="https://github.com/flutter/website/assets/6655696/5d3325e7-dd3b-4d95-b561-0bdbf5188790">

**Comment by parlough** [comment]
@guidezpl I thought I responded already, but I wanted to say I really appreciate the ideas you proposed here.

We're working on some larger changes to the information architecture and will definitely incorporate some of these. In particular a new level "Flutter" category or similar which will also be great home for some other docs currently awkwardly placed.
