### ISSUE TITLE
Unify flutter.dev and docs.flutter.dev footers

### ISSUE THREAD

**Issue by guidezpl** [flutter/website#8999]
### Describe the problem

There is some duplication of navigation and inconsistencies between flutter.dev and docs.flutter.dev's footers.

flutter.dev | docs.flutter.dev
--- | ---
<img width="1719" alt="image" src="https://github.com/flutter/website/assets/6655696/587dafdb-b21f-47ce-b856-6ceab02e2a8a"> | <img width="1728" alt="image" src="https://github.com/flutter/website/assets/6655696/11e3bc56-0f1e-4e31-8aec-206e2f736661">

- flutter.dev: footer duplicates navigation from docs.flutter.dev (`Learn Flutter`) and itself (`Multi-platform`). (`About Flutter` duplicates from both)
- flutter.dev: footer includes social links, which are different from docs.flutter.dev's navigation bar
- docs.flutter.dev: footer mixes language and policies

### Expected fix

To reduce confusion about site structure, they should use the same footer. From the perspective of each site, that could mean:

- flutter.dev: Remove the `About Flutter`, `Learn Flutter`, and `Multi-platform` sections
- flutter.dev: Move the social icons to the nav bar to match docs.flutter.dev
- docs.flutter.dev: Adopt flutter.dev's way of aligning policies to the right

### Additional context

Related to https://github.com/flutter/website/issues/6915

**Comment by atsansone** [comment]
These sites serve different purposes. The difference in the footers helps identify which site the reader is viewing. Closing this issue.

cc: @FlutterJayChang
