### ISSUE TITLE
Add hover styles to TOC entries

### ISSUE THREAD

**Issue by parlough** [flutter/website#9016]
### Describe the problem

On hover, there is no indication which element in the TOC you are interacting with.

### Expected fix

Add hover styles, similar to how we did for the main sidenav.

**Comment by ulisseshen** [comment]
Not related to #9167, however I'm working in this context and if you prefer I can add this hover style if you haven't already started.

**Comment by parlough** [comment]
@ulisseshen If you'd like to work on this, that'd be great! Please open separate PRs for the work though.

I didn't start on this, but I did think using the [`$flutter-color-dark-blue` variable color](https://github.com/parlough/website/blob/feature/ia-combined/src/_sass/base/_variables.scss#L4) might be a good/easy choice for the hover state to match other areas on the site. There are other options to consider though. Whatever you think is best :)

**Comment by ulisseshen** [comment]
$flutter-color-blue-500: #1389FD;
