### ISSUE TITLE
Explain how to create drawables in 'Adding a splash screen to your Android app'

### ISSUE THREAD

**Issue by kari538** [flutter/website#9038]
### Page URL

https://docs.flutter.dev/platform-integration/android/splash-screen/

### Page source

https://github.com/flutter/website/tree/main/src/platform-integration/android/splash-screen.md

### Describe the problem

You are explaining very well how to add "the launch theme" to my AndroidManifest.xml and all... but you are not explaining how to make a launch theme!

I can make Flutter screens. I have no idea how to make "a drawable" to be displayed as a launch screen. Where do I find information on this?

**Comment by atsansone** [comment]
@vashworth : Do you have any insight here? Thanks!

**Comment by vashworth** [comment]
> @vashworth : Do you have any insight here? Thanks!

Unfortunately, my Android knowledge is limited (I'm on iOS team btw). Perhaps someone on the @reidbaker's team could take a look?
