### ISSUE TITLE
Add notice about supported platforms on  'Play and pause a video' page

### ISSUE THREAD

**Issue by daeta** [flutter/website#9050]
### Page URL

https://docs.flutter.dev/cookbook/plugins/play-video/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/plugins/play-video.md

### Describe the problem

Wasted hours trying to get video_player to work under MacOS X Desktop App (and learned many debug tools in the process) only to discover that it only works in iOS Simulator.
If I run it under MacOS X I get:
UnimplementedError (UnimplementedError: init() has not been implemented.)
at  _controller.initialize();

Please display a note that this Widget only supports iOS and Android. Unless this is a bug?

### Expected fix

Place warning: video_player is not supported on MacOS X Desktop. Please use iOS simulator.

**Comment by danagbemava-nc** [comment]
Hi @daeta, in future, it would be best to check the plugin page on pub.dev for supported platforms. You should do this in general for any package or plugin that you want to use. It takes some time to update the website content so it may not always have the latest information. 

If you check the plugin page, you'll see that it supports android/ios& web(with some caveats)
