### ISSUE TITLE
Refactor Plugin docs

### ISSUE THREAD

**Issue by mit-mit** [flutter/website#9072]
Our documentation for how to create plugins (i.e. packages with platform specific code) have grown over time as we added more and more technical capabilities. They are now spread out over two main pages:

* [Developing packages & plugins](https://docs.flutter.dev/packages-and-plugins/developing-packages)
* [Writing custom platform-specific code](https://docs.flutter.dev/platform-integration/platform-channels)

Each of these are in different places in the left menu, are each very long, and quite complicated.

I think it may be worthwhile to break this up into some smaller, more targeted pages, each handling just a single topic. For example:

1) method channels
2) Dart direct interop (FFI/JNIgen/etc.)
3) pigeon
4) package basics
5) plugins (i.e. packages with platform specific code)
6) federated plugin packages

**Comment by atsansone** [comment]
This duplicates https://github.com/flutter/website/issues/7123. Closing this issue and moving its details to #7123.
