### ISSUE TITLE
Fix linter issues in 'Sublinear algorithm' DartPad example

### ISSUE THREAD

**Issue by parlough** [flutter/website#9075]
The ['Sublinear algorithm' example](https://dartpad.dev/?id=e66e420f2f0201c772f73819711bf290) is linked to from the flutter.dev marketing homepage, but has linter diagnostics with the latest Flutter release. 

https://gist.github.com/flutterdevrelgists/e66e420f2f0201c772f73819711bf290

It should be updated to address the diagnostics. It also looks like it needs to be ran through `dart format` after.

**Comment by parlough** [comment]
@khanhnwin Do you have access to `flutterdevrelgists`? Would you mind updating this gist?

**Comment by parlough** [comment]
\cc @johnpryan Could you update this gist if you get a chance? I appreciate it :D

**Comment by johnpryan** [comment]
Updated, thanks for filing an issue 👍

**Comment by parlough** [comment]
Thank you!
