### ISSUE TITLE
Update the last screenshot on the 'Set up app links for Android' page

### ISSUE THREAD

**Issue by Raihanrizalf** [flutter/website#9094]
### Page URL

https://docs.flutter.dev/cookbook/navigation/set-up-app-links/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/navigation/set-up-app-links.md

### Problem

The last screenshot of this page should be displaying Details screen not Home screen

**Comment by atsansone** [comment]
@chunhtai : We should sync to update this codelab.
