### ISSUE TITLE
[PAGE ISSUE]: 'Install'

### ISSUE THREAD

**Issue by Sikhu295** [flutter/website#9100]
### Page URL

https://docs.flutter.dev/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/index.md

### Describe the problem

https://docs.flutter.dev/get-started/install/

### Expected fix

https://docs.flutter.dev/get-started/install/

### Additional context

https://docs.flutter.dev/get-started/install/

**Comment by parlough** [comment]
Hi @Sikhu295, thanks for opening an issue!

Is there a specific issue you had with the install page or installing Flutter?

**Comment by atsansone** [comment]
Lacking further details, closing this issue.
