### ISSUE TITLE
Fix double scrollbars on the 'Flutter for Xamarin.Forms developers' page

### ISSUE THREAD

**Issue by domesticmouse** [flutter/website#9105]
### Page URL

https://docs.flutter.dev/get-started/flutter-for/xamarin-forms-devs/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/flutter-for/xamarin-forms-devs.md

### Describe the problem

This page has a double scroll bar on desktop. Looks kludgey

**Comment by danagbemava-nc** [comment]
Hi @domesticmouse, which browser are you seeing this in? I don't see it in Arc(Chromium based) or Safari. 

Can you share a screenshot?

**Comment by domesticmouse** [comment]
Chrome version details:
<img width="614" alt="Screenshot 2023-09-01 at 7 55 20 am" src="https://github.com/flutter/website/assets/30503/644be142-5555-4d75-a926-ea535d6d766b">

Here's what I'm seeing, two scroll bars on the right of the page:
<img width="694" alt="Screenshot 2023-09-01 at 7 54 27 am" src="https://github.com/flutter/website/assets/30503/8fb6886d-8125-4d91-a47c-a664578fce3f">

I suspect this is isn't something that can be fixed easily.

**Comment by domesticmouse** [comment]
Hey @parlough, should I close this issue as infeasible?

**Comment by parlough** [comment]
Sorry, I missed the ping. Yeah it's likely to be fixed for now, but I'm tracking fixing it as part of some larger design work down the road. I'll get there eventually! :D
