### ISSUE TITLE
Google One - Expanded Cloud Storage & Automatic Phone Backup

### ISSUE THREAD

**Issue by MC-MAGA** [flutter/website#9115]
##### - [ ] _![Screenshot_20230722-131906_Chime.jpg](https://github.com/flutter/website/assets/139556786/4c7db85c-7f3f-4670-b0c2-21a412e10a3e)

![Uploading IMG_20230703_235044_406.jpg …]()

![Screenshot_20230718-070144_Microsoft Launcher.jpg](https://github.com/flutter/website/assets/139556786/219a47a2-36a2-4293-a6df-e3fa6ad88a39)

![I just earned.txt](https://github.com/flutter/website/files/12157893/I.just.earned.txt)

![I am sharing 'Median_Latency_by_Response_Code' with you.pdf](https://github.com/flutter/website/files/12157894/I.am.sharing.Median_Latency_by_Response_Code.with.you.pdf)

![sophia.jpg](https://github.com/flutter/website/assets/139556786/a7d2a83c-41ac-45c1-a409-321913817bab)

![bq-results-20230612-101133-1686564718524.csv](https://github.com/flutter/websiouite/files/12157896/bq-results-20230612-101133# -1686564718524.cs

![I just earned.txt](https://github.com/flutter/website/files/12157895/I.just.earned.txt)

![Open main menu.txt](https://github.com/flutter/website/files/12157897/Open.main.menu.txt)

_

**Comment by danagbemava-nc** [comment]
Closing this as unrelated to this repo.
