### ISSUE TITLE
Introduce and use `Padding` instead of `Container` when it makes sense in 'Building layouts'

### ISSUE THREAD

**Issue by parlough** [flutter/website#9118]
### Page URL

https://docs.flutter.dev/ui/layout/tutorial/

### Page source

https://github.com/flutter/website/tree/main/src/ui/layout/tutorial.md

### Describe the problem

`Container` is used in the tutorial when `Padding` would work well. 

### Expected fix

Add some text to introduce `Padding` and its relationship to `Container` then update the following steps to use it.

### Additional context

https://github.com/flutter/website/pull/9088#issuecomment-1649590379

**Comment by DemX86** [comment]
Just a side note to keep in mind and maybe to note in the tutorial.

As the documentation page [Padding class](https://api.flutter.dev/flutter/widgets/Padding-class.html) says in the `Design discussion` section, there is actually no difference between usage of dedicated `Padding` widget and of `Container` with `.padding` prorerty:

> Why use a [Padding](https://api.flutter.dev/flutter/widgets/Padding-class.html) widget rather than a [Container](https://api.flutter.dev/flutter/widgets/Container-class.html) with a [Container.padding](https://api.flutter.dev/flutter/widgets/Container/padding.html) property?
> There isn't really any difference between the two. If you supply a [Container.padding](https://api.flutter.dev/flutter/widgets/Container/padding.html) argument, [Container](https://api.flutter.dev/flutter/widgets/Container-class.html) builds a [Padding](https://api.flutter.dev/flutter/widgets/Padding-class.html) widget for you.

and

> If you find [Container](https://api.flutter.dev/flutter/widgets/Container-class.html) convenient, feel free to use it. If not, feel free to build these simpler widgets in whatever combination meets your needs.

**Comment by parlough** [comment]
Reopening since the change was reverted in https://github.com/flutter/website/pull/9927
