### ISSUE TITLE
Firebase deploy is failing due to not finding `default` project

### ISSUE THREAD

**Issue by parlough** [flutter/website#9123]
See https://github.com/flutter/website/actions/runs/5655493999/job/15321177864 for an example run with the failure.

`default` is an alias defined in our `.firebaserc` file: https://github.com/flutter/website/blob/main/.firebaserc#L3. So I'm not yet sure why it's not found.

**Comment by parlough** [comment]
This also seems to be happening with [site-www](https://github.com/dart-lang/site-www/actions/runs/5613794545/job/15336926331) which uses a service account rather than a token.

\cc @johnpryan

**Comment by khanhnwin** [comment]
I've checked Service Accountkeys for both site-www and flutter/website, both would've been expired over a week ago so I don't believe this is an expired/incorrect key issue

**Comment by khanhnwin** [comment]
This seems like it could have been the cause: https://status.firebase.google.com/incidents/5nu6YjMtzVyneeXke6yv `Some projects not loading intermittently due to inability to resolve GetProjectIdMapping reliably, south-east most affected`

**Comment by parlough** [comment]
Thanks @khanhnwin! Redeploying dart.dev worked.

`flutter/website` just failed again - https://github.com/flutter/website/actions/runs/5660437529/job/15342167180 - but I imagine they may still be recovering from the incident. So we could wait a bit and try again :)

**Comment by khanhnwin** [comment]
Np @parlough! Thanks for catching this. I'll go ahead and close #9131, but we should probably add "switch firebase deploy to auth with service account key instead of user token" to our todo list for the future!
