### ISSUE TITLE
Add embedded DartPad for complete example in 'Play and pause a video'

### ISSUE THREAD

**Issue by parlough** [flutter/website#9133]
### Page URL

https://docs.flutter.dev/cookbook/plugins/play-video/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/plugins/play-video.md

### Describe the problem

The sample is able to run on web, so we should just be able to make it an embeddable DartPad.

**Comment by parlough** [comment]
@domesticmouse It looks like DartPad is using an older version of `package:video_player` without the new `VideoPlayerController.networkUrl` method we're using on the site.

Would you mind updating the package versions, or I would be happy too as well. Is the `dart-pad` nested `dart-services` setup to deploy now?

**Comment by domesticmouse** [comment]
Hey @johnpryan, looks like the package dependencies need updating.
