### ISSUE TITLE
Correct 3 broken links on Assets & image (media) page

### ISSUE THREAD

**Issue by atsansone** [flutter/website#9138]
### Page URL

https://docs.flutter.dev/ui/assets-and-images

### Describe the problem

Three links on the Assets & image (media) page are invalid. They should be fixed.

| Bad URL                                                                      | Surrounding HTML                                                                                                                                                   |
|------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------|
| https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon | <a href="https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon" >Human Interface Guidelines</a>                                      |
| https://api.flutter.dev/flutter/dart-ui/Window/render.html                   | <a href="https://api.flutter.dev/flutter/dart-ui/Window/render.html" ><code class="language-plaintext highlighter-rouge">window.render()</code></a>         |
| https://api.flutter.dev/flutter/dart-ui/Window/onDrawFrame.html              | <a href="https://api.flutter.dev/flutter/dart-ui/Window/onDrawFrame.html" ><code class="language-plaintext highlighter-rouge">window.onDrawFrame</code></a> |

This page is moved with https://github.com/flutter/website/pull/9130. The new link would be https://docs.flutter.dev/ui/assets/assets-and-images

### Expected fix

Correct the link URLs.

**Comment by parlough** [comment]
@goderbauer Could you provide some insight into how to update the following text with the recent window changes or if it still makes sense at all? In the section of this assets page in [Updating the launch screen](https://docs.flutter.dev/ui/assets-and-images#updating-the-launch-screen), there is a note that says:

> This implies that if you don’t call [`runApp()`](https://api.flutter.dev/flutter/widgets/runApp.html) in the main() function of your app (or more specifically, if you don’t call [`window.render()`](https://api.flutter.dev/flutter/dart-ui/Window/render.html) in response to [`window.onDrawFrame`](https://api.flutter.dev/flutter/dart-ui/Window/onDrawFrame.html)), the launch screen persists forever.

Thanks for your insight!

**Comment by parlough** [comment]
Thank you!
