### ISSUE TITLE
Fix grammar in Step 3 of "Local development for your Flutter apps using the Firebase Emulator Suite" Codelab

### ISSUE THREAD

**Issue by max-torch** [flutter/website#9187]
### Page URL

https://firebase.google.com/codelabs/get-started-firebase-emulators-and-flutter#2

### Describe the problem

The page has this paragraph:

> The directory structure under flutter-codelabs/firebase-emulator-suite is a two Flutter projects. One is called complete, which you can refer to if you want to skip ahead, or cross-reference your own code. The other project is called start.

The first sentence exhibits incorrect grammar.

### Expected fix

Change the first sentence to:

> The directory structure under flutter-codelabs/firebase-emulator-suite consists of two Flutter projects.

Or an equivalent sentence that is grammatically correct.

### Additional context

Grammarly page on the usage of articles such as "a" and "an" in the English language
https://www.grammarly.com/blog/articles/

**Comment by ericwindmill** [comment]
Good catch, @max-torch. Thanks!

**Comment by domesticmouse** [comment]
> @domesticmouse, can you take care of this?

Nope, it's not a Flutter codelab. It's owned by Firebase. This issue's owner is @ericwindmill for a reason =)

**Comment by felipecastrosales** [comment]
@ericwindmill can you see this?

**Comment by ericwindmill** [comment]
Fixed with CL 634486659
