### ISSUE TITLE
Link to advanced version in first flutter app codespace is wrong

### ISSUE THREAD

**Issue by henkehedstrom** [flutter/website#9188]
### Page URL

https://codelabs.developers.google.com/codelabs/flutter-codelab-first#8

### Describe the problem

The last page in the "Your first Flutter app" tells you that you can check out the code for an advanced version of the app. The link points me to "https://dartpad.dev/e7076b40fb17a0fa899f9f7a154a02e8?" which just shows code for an example of how to use a for loop. 

![image](https://github.com/flutter/website/assets/36405465/3f518f19-d311-4f19-a6c4-69317e206002)

### Expected fix

A link to the correct sample or if that no longer exists, change/remove the text to avoid confusion.

**Comment by danagbemava-nc** [comment]
Hi @henkehedstrom, this is being tracked in https://github.com/flutter/flutter/issues/131300. See https://github.com/flutter/flutter/issues/131300#issuecomment-1651199357 for the correct link

Closing from here as duplicate. 

Thank you

**Comment by henkehedstrom** [comment]
> Hi @henkehedstrom, this is being tracked in [flutter/flutter#131300](https://github.com/flutter/flutter/issues/131300). See [flutter/flutter#131300 (comment)](https://github.com/flutter/flutter/issues/131300#issuecomment-1651199357) for the correct link
> 
> Closing from here as duplicate.
> 
> Thank you

Thanks, the link in the comment works :) 
However, the link in the codelab is still wrong. I guess you are still working on that, thanks again!

**Comment by danagbemava-nc** [comment]
Yes, it will be fixed. See https://github.com/flutter/flutter/issues/131300#issuecomment-1651222298
