### ISSUE TITLE
[PAGE ISSUE]: 'Navigate to a new screen and back'

### ISSUE THREAD

**Issue by imagochan** [flutter/website#9218]
### Page URL

https://docs.flutter.dev/cookbook/navigation/navigation-basics/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/navigation/navigation-basics.md

### Describe the problem

The dart code inside the interactive exampel section is wrong. As in it´s just HTML instead of real code.

### Expected fix

The interactive example code should be checked and replaced by the correct code intended for this section.

**Comment by parlough** [comment]
Thanks for opening an issue! If you hard refresh the page, the embedded DartPads should be working now.
