### ISSUE TITLE
[PAGE ISSUE]: 'Building user interfaces with Flutter'

### ISSUE THREAD

**Issue by arunFTip** [flutter/website#9224]
### Page URL

https://docs.flutter.dev/ui/

### Page source

https://github.com/flutter/website/tree/main/src/ui/index.md

### Describe the problem

![image](https://github.com/flutter/website/assets/65351685/4dbd6106-9848-4dd0-8185-051d94590bf4)

![image](https://github.com/flutter/website/assets/65351685/af793df6-ab62-4b16-966d-07fd95fc299c)

Content list is not visible in Windows 11 Chrome, but visible in iPad Chrome.

**Comment by parlough** [comment]
Thanks for opening an issue @arunFTip! On wider screens, the contents/TOC move to the right of the screen to allow accessing it no matter how far you are scrolled. Do you not see it to the right of your desktop screenshot? It should look similar to the following:

<img width="300" alt="UI intro right toc" src="https://github.com/flutter/website/assets/18372958/f8b78b56-611e-41a2-b5c6-361ebb343208">
