### ISSUE TITLE
Add the Code Excerpts refresh script in the Makefile

### ISSUE THREAD

**Issue by atsansone** [flutter/website#9233]
### Describe the problem

Finding that the build fails after you push changes can be frustrating.

It would help to not have to wait for the tests to run before finding out that code excerpts need updating.

### Expected fix

Consider adding a call to `tool/refresh-code-excerpts.sh` before the `docker` build is run. It can exit out if the refresh fails for any reason (code != 0).

**Comment by parlough** [comment]
I guess I'm not sure what you're asking for. The `tool/refresh-code-excerpts.sh` is set up to be ran in the docker container as it relies on Dart and NPM setup within it, so it needs to be ran after `make setup`.

If you want to run it locally, you can always run `make debug` then `tool/refresh-code-excerpts.sh`.

**Comment by atsansone** [comment]
This relies on staging via Docker either locally or remotely. If you don't stage, your code gets no other check and results in a test failure in GitHub. (The test flags the mistakes, but doesn't fix them.) There may be a better way to accomplish this locally. I'll check into that.

**Comment by parlough** [comment]
This work is going to instead be completed in https://github.com/flutter/website/issues/9745 to align with the Dart website. Closing in favor of that issue :)
