### ISSUE TITLE
Update creating Linux Snap application to include `snap install`

### ISSUE THREAD

**Issue by RickPoleshuck** [flutter/website#9246]
### Page URL

https://docs.flutter.dev/deployment/linux

### Describe the problem

Following these instructions on an Ubuntu 22.04 Desktop had a couple of problems.

1. The instructions should suggest trying it out locally with $ sudo snap install <pgrm.snap> --devmode before pushing to snap store.
2. The program runs with a large black border without a usable title bar after installation with --devmode. This border is only on the linux desktop with snapcraft running. It works correctly on another linux desktop.
 

### Expected fix

1. Add $ sudo snap install <pgrm.snap> --devmode  to the documentation.
2. Since it works correctly on another linux desktop, maybe only the documentation needs to be changed.

### Additional context

You can use the txtr_dsk project within https://github.com/RickPoleshuck/txtr to duplicate this problem.

**Comment by kenvandine** [comment]
I would recommend using core22 instead of core18.

**Comment by RickPoleshuck** [comment]
> I would recommend using core22 instead of core18.

"Extension 'flutter-stable' does not exist" when specifying core22

**Comment by kenvandine** [comment]
The usage is a little different for core22.  You can see https://snapcraft.io/docs/flutter-plugin

**Comment by RickPoleshuck** [comment]
> The usage is a little different for core22. You can see https://snapcraft.io/docs/flutter-plugin
core22 never finishes building on my ubuntu 22.04. It gets stuck at "Creating new instance from image 'core22' from remote 'craft-com.ubuntu.cloud-buildd' " 
Snapcraft and flutter seems fragile. My best guess is that core22 requires lxd and there is a problem with lxd on my version of linux. When I say 'my best guess', I mean a confidence of about 20% :-)

**Comment by RickPoleshuck** [comment]
> > The usage is a little different for core22. You can see https://snapcraft.io/docs/flutter-plugin
> > core22 never finishes building on my ubuntu 22.04. It gets stuck at "Creating new instance from image 'core22' from remote 'craft-com.ubuntu.cloud-buildd' "
> > Snapcraft and flutter seems fragile. My best guess is that core22 requires lxd and there is a problem with lxd on my version of linux. When I say 'my best guess', I mean a confidence of about 20% :-)

I am able to build the snap a brand new ubuntu virtual machine. I have configured lxd exactly the same way on both machines. Should I do a pull request to adjust the documentation to use core22 and mention testing with --devmode?
