### ISSUE TITLE
Update  'Animations overview' page name in `Animations & transitions` menu

### ISSUE THREAD

**Issue by HamzaAhmed147** [flutter/website#9262]
### Page URL

https://docs.flutter.dev/ui/animations/overview/

### Page source

https://github.com/flutter/website/tree/main/src/ui/animations/overview.md

### Describe the problem

wrong topic , it says api overview in the tab

### Expected fix

rename the tab to animations overview

### Additional context

self definitive

**Comment by atsansone** [comment]
@HamzaAhmed147 : The page has the wrong title. What is explained on the page is the Flutter API for animation. We can fix that.
