### ISSUE TITLE
appstate error

### ISSUE THREAD

**Issue by shaunmac** [flutter/website#9292]
### Page URL

https://codelabs.developers.google.com/codelabs/flutter-codelab-first#4

### Describe the problem

I've followed all the steps, but I'm stuck on 5. My render doesn't look like the example. Specifically the padding changes haven't rendered to the page. I've tried to rebuild, but no luck.  
In my code there's a red squiggly under appstate. On line 42. There's no other indication as to why it's not working. I'm really thinking flutters not for me.

**Comment by atsansone** [comment]
@shaunmac : Could you supply a screenshot or a short video that would show us your issue? Thanks!
