### ISSUE TITLE
Update integration testing with WebDriver versions

### ISSUE THREAD

**Issue by atsansone** [flutter/website#9312]
Per this [TODO](https://github.com/flutter/website/blob/main/src/content/testing/integration-tests/index.md?plain=1#L382-L395):

TODO(ryjohn): Add back after other WebDriver versions are supported:
https://github.com/flutter/flutter/issues/90158

**Comment by johnpryan** [comment]
This is still blocked by https://github.com/flutter/flutter/issues/90158. I'm going to close this until that issue is addressed.
