### ISSUE TITLE
DevTools release instructions should be updated for flutter/website standards

### ISSUE THREAD

**Issue by polina-c** [flutter/website#9335]
### Describe the problem

I created PR to create DevTools release notes: https://github.com/flutter/website/actions/runs/6027331355/job/16352304253

The [instruction](https://github.com/flutter/devtools/blob/master/packages/devtools_app/release_notes/README.md#testing-the-release-notes-in-devtools) states that I want to wait for bot to stage the changes to verify the changes look good.

However the job 'deploy' did not run because of error: 

<img width="1485" alt="Screenshot 2023-08-30 at 9 14 56 AM" src="https://github.com/flutter/website/assets/12115586/dbfaf923-90c8-430a-9819-948e7590a513">

```
   info • 'textScaleFactor' is deprecated and shouldn't be used. Use textScaler instead. Use of textScaleFactor was deprecated in preparation for the upcoming nonlinear text scaling support. This feature was deprecated after v3.12.0-2.0.pre • main.dart:113:17 • deprecated_member_use
```

### Expected fix

The error needs to be fixed, so that bot could stage the website.

**Comment by parlough** [comment]
The staging didn't work, not because of the error in the `beta` tests, but rather because the PR was opened from a branch not on `flutter/website`. For now, staging will only work from branches on this repository.

I'm preparing some other updates to the DevTools release notes process and docs, so I'll make sure to clarify that as well.

Thanks!

**Comment by polina-c** [comment]
> 



> The staging didn't work, not because of the error in the `beta` tests, but rather because the PR was opened from a branch not on `flutter/website`. For now, staging will only work from branches on this repository.
> 
> I'm preparing some other updates to the DevTools release notes process and docs, so I'll make sure to clarify that as well.
> 
> Thanks!

Good to know!
