### ISSUE TITLE
[PAGE ISSUE]: 'Install' - OS selection buttons on Install page do not allow clicking on the icons

### ISSUE THREAD

**Issue by DanTup** [flutter/website#9346]
### Page URL

https://docs.flutter.dev/get-started/install/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/index.md

### Describe the problem

The OS icons (the blue part) of these buttons is not clickable. You can click anywhere on the button outside of the icon, but not on the icon.

https://github.com/flutter/website/assets/1078012/4a81b333-a693-4757-b455-bd24e70bbb2f

### Expected fix

The whole area of the button should be clickable.

**Comment by parlough** [comment]
Thanks for reporting! Not sure how I missed this when testing the related change. Don't have access to a computer right now but I'll fix it tonight if someone else doesn't get it :)
