### ISSUE TITLE
Stable archive file for 'Windows install' returns CRC error

### ISSUE THREAD

**Issue by darkomenx** [flutter/website#9348]
### Page URL

https://docs.flutter.dev/get-started/install/windows/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/windows.md

### Describe the problem

The flutter archive file for Windows system is corrupted by CRC error.

I can't share what files cause that issue because it seems to be random each times I want to extract archive.

I re-downloaded many times the file but it the same result.

**Comment by danagbemava-nc** [comment]
Hi @darkomenx, which version of flutter are you trying to install? 

Can you try installing via git to see if that helps?

**Comment by darkomenx** [comment]
I try to install the version of flutter which present in the url that sharing (3.13.2-stable)

Issue is not to trying install a version of flutter (I already done) but telling you that the zip archive of the page is corrupted.

**Comment by itsjustkevin** [comment]
@danagbemava-nc I am not seeing this issue when I download the zip file from the get started page.

**Comment by danagbemava-nc** [comment]
Hi @darkomenx, what version of Windows are you experiencing this issue on?

**Comment by darkomenx** [comment]
I use Windows 11 Pro 22H2 build 22621.2134 (Windows Feature Experience Pack 1000.22659.1000.0)

I can view here those CRC errors (but it's random)

Test done just now (09-12-2023 15H00 GMT)

![image](https://github.com/flutter/website/assets/16452686/0440dd74-096f-470b-afe2-be8d73720971)

**Comment by atsansone** [comment]
@darkomenx : For my edification, what app are you using to extract?

**Comment by darkomenx** [comment]
Bandizip

**Comment by atsansone** [comment]
@darkomenx : This appears to be a localized issue. Consider trying another extraction application (WinZip, WinRAR, 7zip) or [use PowerShell](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-7.4).

When I tried testing this specific archive, I had no errors. 

```terminal
...
    testing: flutter/packages/integration_test/test/web_extension_test.dart   OK
    testing: flutter/packages/integration_test/test_fixes/   OK
    testing: flutter/packages/integration_test/test_fixes/.dartignore   OK
    testing: flutter/packages/integration_test/test_fixes/analysis_options.yaml   OK
    testing: flutter/packages/integration_test/test_fixes/integration_test/   OK
    testing: flutter/packages/integration_test/test_fixes/integration_test/binding/   OK
    testing: flutter/packages/integration_test/test_fixes/integration_test/binding/integration_test_widgets_flutter_binding.dart   OK
    testing: flutter/packages/integration_test/test_fixes/integration_test/binding/integration_test_widgets_flutter_binding.dart.expect   OK
    testing: flutter/PATENT_GRANT     OK
    testing: flutter/README.md        OK
    testing: flutter/TESTOWNERS       OK
    testing: flutter/version          OK
No errors detected in compressed data of flutter_windows_3.13.2-stable.zip.
```

Please try another extraction method and reopen this issue if this did not help.

Thanks for bringing this to our attention!
