### ISSUE TITLE
[PAGE ISSUE]: 'Windows install'

### ISSUE THREAD

**Issue by Panda0312** [flutter/website#9368]
### Page URL

https://docs.flutter.dev/get-started/install/windows/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/windows.md

### Describe the problem

I am setting up flutter env on windows. I installed the latest Android Stuido and run flutter doctor got this error.

[!] Android Studio (version unknown) X Unable to determine Android Studio version.

**Comment by danagbemava-nc** [comment]
Hi @Panda0312, what version of flutter do you have installed? 

What version of android studio did you install? Can you share the full output of `flutter doctor -v`?

Thank you

**Comment by gabrielontech** [comment]
Hi,
just to tell you that the image that you are trying to upload failed.
