### ISSUE TITLE
[PAGE ISSUE]: 'Windows install'

### ISSUE THREAD

**Issue by Bogan78** [flutter/website#9374]
### Page URL

https://docs.flutter.dev/get-started/install/windows/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/windows.md

### Describe the problem

 when i try to run flutter doctor on cmd its show the was unexpected at this time ill set the path perfectly and also reinstall for the 2-3 time still showing me the same problem

**Comment by danagbemava-nc** [comment]
Hi @Bogan78, what problem are you seeing?

**Comment by Bogan78** [comment]
The same problem is there which was I mention on the git page

**Comment by danagbemava-nc** [comment]
What git page are you refering to?
