### ISSUE TITLE
Change build command on 'Continuous delivery with Flutter' page

### ISSUE THREAD

**Issue by reiv** [flutter/website#9382]
### Page URL

https://docs.flutter.dev/deployment/cd/

### Page source

https://github.com/flutter/website/tree/main/src/deployment/cd.md

### Describe the problem

https://docs.flutter.dev/deployment/cd#cloud-build-and-deploy-setup

In step 3:
> Run flutter build appbundle or flutter build ios --release --no-codesign, depending on the platform.

Should this be `build ipa` instead of `build ios`? This matches the instructions for local setup and if the goal is to generate an xcarchive for Fastlane to sign, then `ipa` would be the command to do it.

**Comment by atsansone** [comment]
@leighajarett : Could you clarify which command should be used. This page needs some work.

**Comment by leighajarett** [comment]
I'm not actually sure on this one, @hellohuanlin do you know by chance?

**Comment by hellohuanlin** [comment]
CC @xster may know about it from git history.

**Comment by atsansone** [comment]
This was fixed in https://github.com/flutter/website/pull/7012. Closing.
