### ISSUE TITLE
 C:\dev\src\dart-sdk\bin\dart.exe not existing

### ISSUE THREAD

**Issue by gabrielontech** [flutter/website#9410]
### Page URL

https://docs.flutter.dev/get-started/install/windows

### Describe the problem

Hi there,

I came across this questioning issue where while I installed the bundle flutter_windows_3.13.4-stable.zip, after extracting I didn't get the dart.exe which where supposed to be inside of the bin folder.

this is what we are excepting to have as a result when running the command ```where flutter dart```

![web_flutter](https://github.com/flutter/website/assets/70663867/d9f0f47a-cedc-4c1d-9602-7ca15c807307)

this is what I got:

![powershell_flutter](https://github.com/flutter/website/assets/70663867/3529c63a-bcb9-4f0c-87d4-8525117a61a8)

the ```C:\dev\src\dart-sdk\bin\dart.exe``` is clearly missing here

I don't really know if this is in any way normal, I just wanted to let you know guys

**Comment by atsansone** [comment]
The block you sent as a screenshot doesn't explain that the path is an example.

With your second screenshot, your Dart executable should be at `C:\Users\Valgradien\flutter\bin\dart.exe`. I believe Windows is hiding the known extension for `.exe`. Try running `C:\Users\Valgradien\flutter\bin\dart.exe --version` and see if you get a response.

I hope this helps. If this works, please let us know.

**Comment by AlexV525** [comment]
You might need to run `flutter doctor` so it can download the corresponding `dart` (in case it's missing).

**Comment by gabrielontech** [comment]
than y'all

**Comment by gabrielontech** [comment]
Thank y'all for your support
