### ISSUE TITLE
Review books on 'Books about Flutter'

### ISSUE THREAD

**Issue by domesticmouse** [flutter/website#9433]
### Page URL

https://docs.flutter.dev/resources/books/

### Page source

https://github.com/flutter/website/tree/main/src/resources/books.md

### Describe the problem

I believe most of the books on this page are not up to date with Flutter 3.13. Some I have reviewed are pre null safety, others are just pre Material 3. 

We can review each book for suitability, or we could declare bankruptcy and delete this page as we don't have the resources to make sure books are kept up to date.

Preferences?

### Expected fix

Make a call on how to proceed with taking down books that contain code that no longer compiles on Flutter stable.

**Comment by sfshaza2** [comment]
Wow, I've been down this road before! (Primarily with Dart as it evolved.) What I'd suggest, in the short term, is adding a note that these books probably don't reflect Material 3 and that the purchaser should vet the books on their own.

We've NEVER vetted any book on this page. As you noted, we don't have time/resources. But we certainly can add a note to the top of the page. For example, there's a nice note on the dart.dev books page.
https://dart.dev/resources/books

**Comment by domesticmouse** [comment]
Yeah, I'm happy with a note saying something to effect that Flutter is a rapidly changing development environment and the reader should verify that the version of the book they are buying includes Null Safety and preferably Material 3.
