### ISSUE TITLE
Review link order in side menu for the testing pages

### ISSUE THREAD

**Issue by anasqadrei** [flutter/website#9434]
### Page URL

https://docs.flutter.dev/cookbook/testing/integration/introduction/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/testing/integration/introduction.md

### Describe the problem

The problem is in the left side menu (Beyond UI --> Testing & debugging --> Testing)

1. According to the testing overview, I think the order should be Unit testing, Widget testing then Integration testing
2. Links under Integration testing point to the wrong pages. "Introduction" points to "Integration testing" and "Write and run an integration test" points to "Introduction". They should be swapped

### Expected fix

That part of the menu should look like this:

- Beyond UI
  - Testing & debugging
    - Testing
      - Unit testing
        - ...
      - Widget testing
        - ...
      - Integration testing
        - Introduction (links to https://docs.flutter.dev/cookbook/testing/integration/introduction)
        - Write and run an integration test (links to https://docs.flutter.dev/testing/integration-tests)
        - ...

**Comment by No0b-master** [comment]
@danagbemava-nc, Can I take up on this issue?

**Comment by atsansone** [comment]
@No0b-master : Please do!
