### ISSUE TITLE
Fix link to blog post on 'Creating responsive and adaptive apps' page

### ISSUE THREAD

**Issue by MickaCapi** [flutter/website#9467]
### Page URL

https://docs.flutter.dev/ui/layout/responsive/adaptive-responsive/

### Page source

https://github.com/flutter/website/tree/main/src/ui/layout/responsive/adaptive-responsive.md

### Describe the problem

At the end of the page ("Other resources"), Aloïs Deniel blog post link is broken.

[Designing truly adaptive user interfaces](https://aloisdeniel.com/#/posts/adaptative-ui) a blog post and video by Aloïs Deniel, presented at this year’s FlutterViking conference.

### Expected fix

[Designing truly adaptive user interfaces](https://www.aloisdeniel.com/blog/designing-truly-adaptative-user-interfaces) a blog post and video by Aloïs Deniel, presented at Flutter Viking 2020 conference.

**Comment by atsansone** [comment]
Nice job!
