### ISSUE TITLE
[PAGE ISSUE]: 'Using the Flutter inspector'

### ISSUE THREAD

**Issue by ArtistQcK** [flutter/website#9479]
### Page URL

https://docs.flutter.dev/tools/devtools/inspector/

### Page source

https://github.com/flutter/website/tree/main/src/tools/devtools/inspector.md

### Describe the problem

Hello i have encountered some issue , in Android Studio while i click on widgets its not navigate through my code while in VSC its works just fine .. 

### Expected fix

it should navigate through code just like in vs code i guess ..

**Comment by danagbemava-nc** [comment]
Hi @ArtistQcK, kindly file an issue on the flutter-intellij repo and provide them with the necessary information required to investigate. 

Closing from here as this repo is only for issues related to the website documentation. 

Thank you
