### ISSUE TITLE
Update broken 'Flutter Interact' link on 'Who is Dash?' page

### ISSUE THREAD

**Issue by juliethangeldeveloper** [flutter/website#9497]
### Page URL

https://docs.flutter.dev/dash/

### Page source

https://github.com/flutter/website/tree/main/src/dash/index.md

### Describe the problem

[Flutter Interact](https://developers.google.com/events/flutter-interact) this page has a 404 

### Expected fix

I just want to see the page content

**Comment by parlough** [comment]
Hi, thanks for opening a issue! I've opened a fix at https://github.com/flutter/website/pull/9499.

However, the event page no longer exists. The best replacement is the youtube playlist of the sessions at the event: https://www.youtube.com/playlist?list=PLjxrf2q8roU0o0wKRJTjyN0pSUA6TI8lg
