### ISSUE TITLE
[PAGE ISSUE]: 'Windows install' I had to run cmd as an administrator for flutter doctor to work

### ISSUE THREAD

**Issue by Krazy-kungfu** [flutter/website#9513]
### Page URL

https://docs.flutter.dev/get-started/install/windows/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/windows.md

### Describe the problem

when I would write flutter doctor app in power shell it would tell me that the git is missing from 'PATH'. but when I would write git --version it would give me git version so I knew git is accessible from 'PATH'. 
For some reason I thought since git is present inside C:/Program Files/ and flutter must not exist in C:/Program Files as its said on the guide page, this must also be the case for git, hence I ran cmd/powershell as an administrator and voila ! the flutter doctor command runs fine. 

### Expected fix

I would recommend adding a message to the guide page as it wasted 40 minutes of my time in re installing git and flutter multiple times

**Comment by huycozy** [comment]
Hi @Krazy-kungfu 
Do you mean `flutter doctor` only can detect `git` on cmd with Admin privileges?

Could you please share the output of these commands?

```
git --version
```

```
flutter doctor -v
```

Also, does the issue only occur on PowerShell or does it also occur on Command Prompt?

**Comment by Krazy-kungfu** [comment]
while running cmd or power shell
git --version : git version 2.42.0.windows.2
flutter doctor -v : cmd crashes and power shell gives me 'Error: Unable to find git in your PATH.'

while running cmd or power shell as administrator 
git --version : git version 2.42.0.windows.2
flutter doctor -v :
![image](https://github.com/flutter/website/assets/40660881/1e326b3e-40a8-43f9-b868-c093cef4e655)

**Comment by huycozy** [comment]
Looks like you are hitting to `unsafe repository` issue. Could you check [this solution](https://stackoverflow.com/a/75511498/5921933) or [this](https://stackoverflow.com/a/76156928/5921933) to see if one of them works? 

If it can solve this issue, I think this should be updated on the page.
