### ISSUE TITLE
Correct the steps in `Validate your VS Code setup` section on 'Set up an editor' page

### ISSUE THREAD

**Issue by Wqsknijper** [flutter/website#9519]
### Page URL

https://docs.flutter.dev/get-started/editor/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/editor.md

### Describe the problem

At 'Validate your VS Code setup', first use of the extention 'flutter' wasn't available in the drop-down section of the output.

### Expected fix

Probably switching 1,2 and 3,4,5 would get less confusion

**Comment by huycozy** [comment]
Thanks for your report. I can see this issue on the page. The `flutter` item is only available on the upper right of the Output panel dropdown after running `flutter doctor`.

Also, `flutter` item will be selected automatically without selecting it manually while the current page states:

>In the dropdown on the upper right of the Output panel, select flutter (flutter).

We may improve this as well.

### Demo video of the issue

https://github.com/flutter/website/assets/104349824/8a23b37a-a0f3-41fe-a918-240cb4bc73fa
