### ISSUE TITLE
Fix empty links

### ISSUE THREAD

**Issue by atsansone** [flutter/website#9524]
Location anchors for the headings default to empty links. Consider remedies from this [StackOverflow article](https://stackoverflow.com/questions/50575083/tab-accessibility-within-a-hover-state).

https://amberwilson.co.uk/blog/are-your-anchor-links-accessible/

**Comment by parlough** [comment]
We rely on an external plugin for this and they don't allow configuration of this. The replacement I'm working on for dart.dev already has this fixed and improved, so I'd like to wait for that to land. Let me know if this needs to land immediately though.
