### ISSUE TITLE
Fix the Flutter logo image at the bottom of the 'Display images from the internet' page.

### ISSUE THREAD

**Issue by Arseny-Rise** [flutter/website#9661]
### Page URL

https://docs.flutter.dev/cookbook/images/network-image/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/images/network-image.md

### Describe the problem

Image url not working

### Expected fix

change url to https://docs.flutter.dev/assets/images/shared/brand/flutter/logo/flutter-mono-81x100.png

**Comment by huycozy** [comment]
Hi @Arseny-Rise 
I checked all the image urls there but they are still working:

- https://picsum.photos/250?image=9
- https://docs.flutter.dev/assets/images/dash/dash-fainting.gif

Could you point out the current image url not working?

**Comment by atsansone** [comment]
This image appears as expected. Closing this issue.



![Image](https://github.com/flutter/website/assets/706219/6f468f20-a84a-4425-a3bf-3434d20052eb)
