### ISSUE TITLE
Update the existing Games Toolkit page (Include adding links to new templates and removing old template)

### ISSUE THREAD

**Issue by atsansone** [flutter/website#9668]
Update the current [Casual Games Toolkit](https://docs.flutter.dev/resources/games-toolkit) page content including updating copy and links to new templates.

Fixed by #9780

**Comment by filiph** [comment]
Before I forget: apart from the new cookbook recipes, the page should also link to the [Adding in-app purchases](https://codelabs.developers.google.com/codelabs/flutter-in-app-purchases) codelab. When I started writing the cookbook recipe for in-app purchases, I realized it would just be a lower-quality copypasta of that fantastic codelab.
