### ISSUE TITLE
Add the Ads Recipe

### ISSUE THREAD

**Issue by atsansone** [flutter/website#9671]
Transfer the cookbook recipe from the [Google doc](https://docs.google.com/document/d/1lN2SdH6Shk5cK1PM5QWZD02wtdka6G30yJyyVTb5pls/edit#heading=h.wogef62fnza5) to the repo.

**Comment by parlough** [comment]
Is this recipe planned to be specific to games or any ad use case?

**Comment by filiph** [comment]
The recipe ([preview doc](https://docs.google.com/document/d/1lN2SdH6Shk5cK1PM5QWZD02wtdka6G30yJyyVTb5pls/edit)) is written for both apps and games. Do you folks want me to add it to `cookbook/plugins/` or to `cookbook/games/`? Or both?

**Comment by atsansone** [comment]
Fixed in #9730
