### ISSUE TITLE
Update pigeon docs/references for current platform support status

### ISSUE THREAD

**Issue by loic-sharma** [flutter/website#9672]
### Page URL

https://docs.flutter.dev/platform-integration/platform-channels/

### Page source

https://github.com/flutter/website/tree/main/src/platform-integration/platform-channels.md

### Describe the problem

The Pigeon section contains outdated information.

### Expected fix

Pigeon supports Windows and macOS now. Pigeon also supports C++ now.

See: https://github.com/flutter/packages/blob/main/packages/pigeon/example/README.md

**Comment by droidbg** [comment]
@parlough, @sfshaza2  I like to work on this, can I pick this up?

**Comment by parlough** [comment]
Of course @droidbg, thanks for offering :)
