### ISSUE TITLE
Fix Gradle sync issue on `Integrate a Flutter module into your Android project`

### ISSUE THREAD

**Issue by andrewkolos** [flutter/website#9674]
### Page URL

https://docs.flutter.dev/add-to-app/android/project-setup/

### Page source

https://github.com/flutter/website/tree/main/src/add-to-app/android/project-setup.md

### Describe the problem

When trying to set up a basic Add-to-app app. I run into issue with Gradle. I suspect these docs (and the instructions given by the Flutter CLI) are out of date.

Here are the steps I followed:

1. Create the host app in Android Studio (Flamingo | 2022.2.1 Patch 2). I used the Basic Views Activity template. I set the Language to Kotlin and the Minimum SDK to API 28: Android 9.0 (Pie).
2. Start following the steps in [Integrate your Flutter Module](https://docs.flutter.dev/add-to-app/android/project-setup?tab=without-android-studio), starting with `flutter create -t module --org com.example flutter_module`
3. Per the Java version requirement instruction, in MyApp/app/build.gradle, replace the `compileOptions` section with 
```
android {
  //...
  compileOptions {
    sourceCompatibility 11 # The minimum value
    targetCompatibility 11 # The minimum value
  }
}
```
4. In a terminal, navigate to to flutter_module (created in step 2) and build the Android archive with `flutter build aar`
5. Per both the documentation and the output of the previous command, add the following to app/build.gradle back in the host app project (your paths will be different):
```gradle
String storageUrl = System.env.FLUTTER_STORAGE_BASE_URL ?:
        "https://storage.googleapis.com"
repositories {
    maven {
        url '/Users/andrewkolos/Desktop/deleteme/add2apptest/flutter_module/build/host/outputs/repo'
    }
    maven {
        url "$storageUrl/download.flutter.io"
    }
}
```
then include the following lines in the `dependencies` section:
```
      debugImplementation 'com.example.flutter_module:flutter_debug:1.0'
      profileImplementation 'com.example.flutter_module:flutter_profile:1.0'
      releaseImplementation 'com.example.flutter_module:flutter_release:1.0'
```
and this in the `buildTypes` section:
```
        profile {
          initWith debug
        }
```
6. Before moving on to adding a [Add a single Flutter screen](https://docs.flutter.dev/add-to-app/android/add-flutter-screen?tab=cached-engine-with-initial-route-kotlin-tab), try performing a Gradle sync. Here, Gradle comes back with an error:
```
Build file '/Users/andrewkolos/Desktop/deleteme/add2apptest/MyApplication/app/build.gradle' line: 47

A problem occurred evaluating project ':app'.
> Build was configured to prefer settings repositories over project repositories but repository 'maven' was added by build file 'app/build.gradle'
``` 

## Workaround
Within the `dependencyResolutionManagement` section in settings.gradle, change `    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)` to `repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)`

Try syncing again; it should work.

Alternatively, you follow the instructions from step 6 but putting the contents into settings.gradle:
```gradle
String storageUrl = System.env.FLUTTER_STORAGE_BASE_URL ?:
        "https://storage.googleapis.com"
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            url '/Users/andrewkolos/Desktop/deleteme/add2apptest/flutter_module/build/host/outputs/repo'
        }
        maven {
            url "$storageUrl/download.flutter.io"
        }

    }
}
```

### Expected fix

Update the instructions to include one of the aforementioned workarounds. However, make sure the new instructions work for both new and older Android projects. I don't have the Android expertise to know if this issue is due to something changing in the Android ecosystem.

**Comment by huycozy** [comment]
Thanks for filing the issue. I can see this issue following the steps above.

This reminds me of a Flutter issue and a user also has found the same workaround at https://github.com/flutter/flutter/issues/95515#issuecomment-1002418876.

**Comment by parlough** [comment]
@atsansone Would you like to work on this since you were working on add to app docs recently?

**Comment by atsansone** [comment]
Sounds good.

**Comment by atsansone** [comment]
@camsim99 : Would you have any insights before I dig into this further?

**Comment by camsim99** [comment]
> @camsim99 : Would you have any insights before I dig into this further?

@gmackall I seem to recall there were changes made involving how `settings.gradle` is used but not sure if it's related. Do you possibly have any insight?

**Comment by gmackall** [comment]
The changes to to `settings.gradle` were mainly changes to move the application of the Flutter Gradle plugin to take place there (applying AGP was also moved there at the same time).

But also, it sounds like the `settings.gradle` in question that needed changing here is the one in the native Android app made by Android Studio. I would guess that Android Studio changed at some point to add `repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)` to the templates , and we need to instruct users to remove that line.
