### ISSUE TITLE
Fix CSS abs function error

### ISSUE THREAD

**Issue by atsansone** [flutter/website#9701]
### Describe the problem

The `abs()` function in CSS can no longer be used.

### Expected fix

According to the returned error:
```terminal
In the future, this will emit a CSS abs() function to be resolved by the browser. 
To preserve current behavior: math.abs(100%)
To emit a CSS abs() now: abs(#{100%})
More info: https://sass-lang.com/d/abs-percent
```

This should be changed to `abs(#{100%})` to remain consistent.

**Comment by parlough** [comment]
I believe this is not in our styles but rather Bootstrap 4's. Unless they release a hotfix version of Bootstrap 4, which I doubt, this is blocked by https://github.com/flutter/website/issues/8030.

**Comment by atsansone** [comment]
I saw the same thing. Closing.
