### ISSUE TITLE
[PAGE ISSUE]: 'Using Flutter in China'

### ISSUE THREAD

**Issue by Basil7181** [flutter/website#9704]
### Page URL

https://docs.flutter.dev/community/china/

### Page source

https://github.com/flutter/website/tree/main/src/community/china.md

**Comment by parlough** [comment]
Hi @Basil7181! Thanks for opening an issue :)

Could you provide some more details on what issue(s) you are having? Were you unable to setup Flutter in China?

**Comment by atsansone** [comment]
This issue is being addressed in #2556. Closing this as a duplicate.
