### ISSUE TITLE
Replace ` primarySwatch` with `ColorScheme.fromSeed` in the examples and cookbooks

### ISSUE THREAD

**Issue by TahaTesser** [flutter/website#9713]
### Page URL

All cookbooks and examples containing `primarySwatch`.

### Describe the problem

`primarySwatch` should no longer be used anywhere in the Flutter website cookbooks and code snippets. 
It's planned to be deprecated in https://github.com/flutter/flutter/issues/91772 as a result it also not used in the Flutter API samples. 

Flutter website examples & snippets should be using `ColorScheme.fromSeed` for Material 3.

### Expected fix

Remove all occurrences of `primarySwatch` and replace with `ColorScheme.fromSeed`

**Comment by huycozy** [comment]
Thanks for the report. Related (umbrella) issue: https://github.com/flutter/website/issues/8924.

**Comment by droidbg** [comment]
@atsansone I like to work on this, can I pick this up? 
And just to reconfirm, similar to these changes needs to be done in this issue right? 
<img width="723" alt="image" src="https://github.com/flutter/website/assets/41873024/b68683e9-8e3b-4d81-96cc-fc1f57ba9d0a">

**Comment by TahaTesser** [comment]
`Colors.deepPurple`  instead of `Colors.blue`

**Comment by droidbg** [comment]
@TahaTesser okay what about other colors instances present in code apart from blue like
`primarySwatch: Colors.lightGreen` they also need to be changed to `Colors.deepPurple` or any other mapping is there?

**Comment by TahaTesser** [comment]
If it uses green color for some reason, you can pass the same color using fromSeed. 
We should replace blue because it was a default primary color for M2, while M3 uses deep purple.

**Comment by droidbg** [comment]
okay thanks for resolving my questions, can I work on this issue?
