### ISSUE TITLE
Placeholder URL for new cookbook recipes 

### ISSUE THREAD

**Issue by zoeyfan** [flutter/website#9716]
### Describe the problem

Can we please create 3 placeholder URLs for a few new cookbook recipes? Once created, we will pass the URL to marketing team to embed in their website. 

The three cookbook recipes will be for:
1. Add ads to your mobile Flutter app or game
2. Add achievements and leaderboards to your mobile game
3. Add multiplayer support via Firestore 

cc @FlutterJayChang

**Comment by parlough** [comment]
@zoeyfan Would it be fine for this to be categorized under a "monetization" label? Also is only one cookbook recipe planned for now?

**Comment by zoeyfan** [comment]
please categorized this under "game" label, as this requests 3 URL placeholders for 3 recipes related to game development. Cc @atsansone

**Comment by parlough** [comment]
The following redirects have all been added. Currently they redirect to flutter.dev/games, but we will update them to point to the correct recipes as we land them.

1. https://docs.flutter.dev/cookbook/games/google-mobile-ads
2. https://docs.flutter.dev/cookbook/games/achievements-leaderboard
3. https://docs.flutter.dev/cookbook/games/firestore-multiplayer

Let me know if you'd like to see any of them updated or changed, thanks! :)
