### ISSUE TITLE
macOS platform integration page contains reference to non-existent Runner.xcworkspace

### ISSUE THREAD

**Issue by tvolkert** [flutter/website#9760]
Page: https://docs.flutter.dev/platform-integration/macos/c-interop

It says:

> In Xcode, open Runner.xcworkspace.

But if you've followed the steps up to that point, there is no "Runner.xcworkspace" folder in the macos folder.  There's one in the examples folder, but that's not what. the instructions are talking about.

**Comment by huycozy** [comment]
Hi @tvolkert 
This is a known issue being tracked at https://github.com/flutter/website/issues/8645. Closing this issue as a duplicate, so please follow up on it for further updates.
