### ISSUE TITLE
[PAGE ISSUE]: 'Flutter's build modes'

### ISSUE THREAD

**Issue by ecc521** [flutter/website#9815]
### Page URL

https://docs.flutter.dev/testing/build-modes/

### Page source

https://github.com/flutter/website/tree/main/src/testing/build-modes.md

### Describe the problem

The link to "Assertions" in "Assertions are enabled" goes to a page that does not mention assertions at all

### Expected fix

The link should be fixed

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
Thanks so much for catching this!

We recently split the targeted page into two separate ones and I guess redirected to the other one. 

I've opened https://github.com/flutter/website/pull/9816 to update the assert links. You can find the actual docs at https://dart.dev/language/error-handling#assert.

**Comment by ecc521** [comment]
Appreciate the link to the docs!
I'm considering switching over to Flutter, and the idea of integrated test cases is quite neat.

**Comment by parlough** [comment]
Glad to hear :) - Let us know if you find any other issues or if something isn't documented well.

You can also join us on the [FlutterDev Discord](https://discord.gg/rflutterdev) if that's your thing!
