### ISSUE TITLE
[PAGE ISSUE]: 'Common Flutter errors'

### ISSUE THREAD

**Issue by sarang030** [flutter/website#9832]
### Page URL

https://docs.flutter.dev/testing/common-errors/

### Page source

https://github.com/flutter/website/tree/main/src/testing/common-errors.md

### Describe the problem

_AssertionError ('package:flutter/src/rendering/stack.dart': Failed assertion: line 598 pos 12: 'size.isFinite': is not true.)

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by dam-ease** [comment]
Hi @sarang030. 
Thanks for filing this.

> _AssertionError ('package:flutter/src/rendering/stack.dart': Failed assertion: line 598 pos 12: 'size.isFinite': is not true.)

Do you run into this error when running your code and would like to report this to be solved or you are proposing for this to be added to the Common Flutter Errors Page?
Kindly help provide more details on this
