### ISSUE TITLE
Fix Link to PopInterface Documentation

### ISSUE THREAD

**Issue by NeariX67** [flutter/website#9836]
### Page URL

https://docs.flutter.dev/release/breaking-changes/android-predictive-back#references

### Describe the problem

Clicking `References`>`PopInterface` on [Android Predictive Back](https://docs.flutter.dev/release/breaking-changes/android-predictive-back) leads to a `Page Not Found`

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by dam-ease** [comment]
Thanks for filing this.
I can also see that the links to 
- [ModalRoute.registerPopInterface](https://api.flutter.dev/flutter/widgets/ModalRoute/registerPopInterface.html)
- [ModalRoute.unregisterPopInterface](https://api.flutter.dev/flutter/widgets/ModalRoute/unregisterPopInterface.html) 

returns 404/Page Not Found.

**Comment by sfshaza2** [comment]
Hmmm. Again, the link check didn't flag this, @parlough.

**Comment by sfshaza2** [comment]
Fixed as per above PR.
