### ISSUE TITLE
Update Google Auth step in Firebase Auth Codelab

### ISSUE THREAD

**Issue by frankpape** [flutter/website#9868]
### Page URL

https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#6

### Describe the problem

The Google Auth Sign In step says to run `flutter pub add google_sign_in`, which does not provide the `package:firebase_ui_oauth_google/firebase_ui_oauth_google.dart` that's used in this step. 

### Expected fix

Add instructions to also run `flutter pub add firebase_ui_oauth_google`.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by frankpape** [comment]
For the record, I'm going through the codelab for the first time myself, so I don't know whether `google_sign_in` is actually required or not, but `firebase_ui_oauth_google` certainly is, at least for the code as written.

**Comment by atsansone** [comment]
@ericwindmill : This appears to be a codelab change. Do you know where I should route this?

**Comment by ericwindmill** [comment]
@atsansone: I've created a CL to fix this.

CL# 586687912

**Comment by atsansone** [comment]
This will be changed in a different codebase.
