### ISSUE TITLE
[PAGE ISSUE]: 'Set up an editor'

### ISSUE THREAD

**Issue by asedilloglatt** [flutter/website#9882]
### Page URL

https://docs.flutter.dev/get-started/editor/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/editor.md

### Describe the problem

In the "Validate your VS Code setup", flutter didn't show up right away even after restarting. In particular, step 2 "In the dropdown on the upper right of the Output panel, select flutter (flutter).".

After doing step 3 and 4 and 5, then flutter did show up.

### Expected fix

 I suggest re-ording this so that step 3, 4, and 5 are done before steps 1 and 2.

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment]
Thanks for the report! 

This is a known issue being tracked at https://github.com/flutter/website/issues/9519. Closing this issue as a duplicate, so please follow up on it for further updates.
