### ISSUE TITLE
Add Large Screen content to adaptive apps page

### ISSUE THREAD

**Issue by tiwiz** [flutter/website#9896]
### Page URL

https://docs.flutter.dev/ui/layout/responsive/building-adaptive-apps

### Describe the problem

Hello there!

[This amazing blogpost](https://medium.com/flutter/developing-flutter-apps-for-large-screens-53b7b0e17f10) contains a lot of information related to large screens, could you add this info to the Large Screen documentation as well? Thank you so much!

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by mariamhas** [comment]
https://github.com/flutter/website/pull/10305
