### ISSUE TITLE
Migrate embedded DartPad editors away from multi-file

### ISSUE THREAD

**Issue by johnpryan** [flutter/website#9898]
### Describe the problem

We need to remove any content that uses DartPad's editable test code features so that they are ready to migrate to the new preview.dartpad.dev editor.

### Expected fix

Pages that use embedded DartPads:
- [Implicit animations codelab](https://docs.flutter.dev/codelabs/implicit-animations)
- [Flutter Cookbook](https://docs.flutter.dev/cookbook)
- [Write your first Flutter app on the web](https://docs.flutter.dev/get-started/codelab-web)
- [Building user interfaces with Flutter](https://docs.flutter.dev/ui)
- [Using Actions and Shortcuts](https://docs.flutter.dev/ui/interactivity/actions-and-shortcuts)
- [Understanding constraints](https://docs.flutter.dev/ui/layout/constraints)

Pages that mention DartPad workshops:
- [Codelabs & workshops](https://docs.flutter.dev/codelabs)
- [Using slivers to achieve fancy scrolling](https://docs.flutter.dev/ui/layout/scrolling/slivers)

### Additional context

See also: https://github.com/dart-lang/site-www/issues/5382

**Comment by atsansone** [comment]
@johnpryan : Could use some clarity for this issue. Do you want the embedded DartPad removed on these pages? If it appears on other pages, should we remove them there, too? With the pages that mention DartPad, we should remove the mention?

Thanks!

**Comment by parlough** [comment]
I think I've removed the remaining use cases of multi-file support already, but if someone wants to double check, please do so!

**Comment by atsansone** [comment]
That works. Thanks @johnpryan !
