### ISSUE TITLE
Fix broken links on `Google APIs` page

### ISSUE THREAD

**Issue by TravisSperry** [flutter/website#9910]
### Page URL

https://docs.flutter.dev/data-and-backend/google-apis/

### Page source

https://github.com/flutter/website/tree/main/src/data-and-backend/google-apis.md

### Describe the problem

404 given for the following link: https://pub.dev/documentation/googleapis/latest/gmail_v1/gmail_v1-library.html
> Examples of user-data APIs include [Calendar](https://pub.dev/documentation/googleapis/latest/calendar_v3/calendar_v3-library.html), [Gmail](https://pub.dev/documentation/googleapis/latest/gmail_v1/gmail_v1-library.html), [YouTube](https://pub.dev/documentation/googleapis/latest/youtube_v3/youtube_v3-library.html), and Firebase.

### Expected fix

Update the link to a valid resource.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment]
Thanks for the report. This was fixed one time at https://github.com/flutter/website/pull/8734 but it seems the valid links have been changed now.

**Comment by sfshaza2** [comment]
@jonasfj, the links for the Gmail google api are broken on pub.dev. I can only find the more general docs on https://developers.google.com/gmail/api/guides. This worked until recently. Can you shed some light here?

**Comment by sfshaza2** [comment]
Here's the content of the email I sent @kevmoo on Dec 7th, which has also been sent to the web and framework teams.

From: shams
Thu, Dec 7, 12:36 PM (6 days ago)
to Kevin, bcc: me

We have two cookbook recipes that kinda sorta don't play well together. One recommends using cached_network_image for caching images. The other suggests the Image.network constructor, which I gather was more recently added.

The thing is, it's not entirely clear what is supported on the web. I've been looking at both and trying to come up with a list of pros and cons, so we can make sensible recommendations.

Can you help elucidate?

**Image.network** 
pros:
- automatically caches image (web??)
- image constructors allow you to specify image decode size to save space when caching
- supports several types of image formats and downloading mechanisms
- supports animated GIFs
- provides loading progress

cons: 
- on web, specifying a decode size is only   supported when using a CanvasRenderer;  not supported for an HTMLRenderer

**cached_network_image package**
pros:
- supports "placeholder" images
- supports fading images in as they're loading

cons:
- it's a 3p package...

**Comment by kevmoo** [comment]
The link is fixed now. I think we just had an issue w/ `pub.dev` generation!

**Comment by sfshaza2** [comment]
Woot! Thanks!
