### ISSUE TITLE
Consider documenting `appFlavor` in the Create flavors of a Flutter app page

### ISSUE THREAD

**Issue by andrewkolos** [flutter/website#9913]
### Page URL

https://docs.flutter.dev/deployment/flavors

### Describe the problem

The Flutter services API exposes a top-level variable, [`appFlavor`](https://api.flutter.dev/flutter/services/appFlavor-constant.html) (introduced in version 3.16), which can be used by Flutter app code to determine the value of the `--flavor` option that the app was built/run with. This is a convenient feature for those who need to extend the capabilities of `--flavor` in their app. However, it's not easily discoverable. We should consider documenting it on the flavors page.

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by sfshaza2** [comment]
@andrewkolos, this is an excellent suggestion. Please do either file a PR, or indicate that someone else should.

**Comment by andrewkolos** [comment]
This is just an FYI that this is still a part of my planned work.
