### ISSUE TITLE
"Adding iOS app extensions" screenshots are distorted

### ISSUE THREAD

**Issue by jmagman** [flutter/website#9925]
### Page URL

https://docs.flutter.dev/platform-integration/ios/app-extensions

### Describe the problem

Some of the screenshots on the "iOS app extensions" page are distorted.
<img width="987" alt="Screenshot 2023-12-13 at 5 45 13 PM" src="https://github.com/flutter/website/assets/682784/c905722b-d7bc-4a27-a955-60ba69651b85">
<img width="928" alt="Screenshot 2023-12-13 at 5 45 04 PM" src="https://github.com/flutter/website/assets/682784/596be8c4-72ca-4e52-9339-d319257cd4b2">

### Expected fix

Set the width?

### Additional context

https://github.com/flutter/website/pull/8265

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by jmagman** [comment]
cc @leighajarett

**Comment by parlough** [comment]
Oh my gosh. This is embarrassing 🙈 

Thank you.
