### ISSUE TITLE
[PAGE ISSUE]: 'Use a native language debugger'

### ISSUE THREAD

**Issue by stuarta0** [flutter/website#9943]
### Page URL

https://docs.flutter.dev/testing/native-debugging/

### Page source

https://github.com/flutter/website/tree/main/src/testing/native-debugging.md

### Describe the problem

In the section #debug-dart-and-native-language-code-at-the-same-time onwards, the nav-tabs all have "Start debugging with X" followed by "Attach to the process with Y". Is that correct? Shouldn't the VS Code section contain "starting in VS Code" and "attaching in VS Code"?

e.g. the nav tab "Start with VS Code" has headings "Start debugging in VS Code" followed by "Attach to process in XCode". And vice-versa, "Start with XCode" has headings "Start debugging in XCode" followed by "Attach to process in VS Code".

### Additional context

Note: I'm just skimming the docs, I'm not a dart or flutter dev. If the content is as intended, disregard.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by dam-ease** [comment]
Thanks for filing this @stuarta0.
Closing this as this seems to be the intended content.
