### ISSUE TITLE
Navbar Items are not vertically Aligned

### ISSUE THREAD

**Issue by TartejBrothers** [flutter/website#9964]
### Describe the problem

- The navbar items are not center aligned with other buttons.

### Expected fix

These should come in one line, i.e. be vertically aligned with the rest of the items.

### On which browser(s) did you experience this issue?

- Google Chrome Version 120.0.6

### Additional context

![image](https://github.com/flutter/website/assets/112921727/5e7d610b-cbba-49fc-8417-6eb47706b1d1)

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by Ankitkj1999** [comment]
They are fine!

**Comment by TartejBrothers** [comment]
![image](https://github.com/flutter/website/assets/112921727/deaaab6c-eeeb-4fc8-99ad-f83a9d7bb90d)
- It is still not aligned on my device

**Comment by dam-ease** [comment]
Thanks for filing this @TartejBrothers.
Checking on Google Chrome Version 120.0.6099.129, it seems to be very aligned, are you able to check with other browsers on your device?

<img width="1440" alt="Screenshot 2023-12-29 at 15 33 11" src="https://github.com/flutter/website/assets/53122008/c053c8f7-d27c-4e15-ab60-d94a161a9840">
