### ISSUE TITLE
Actions and Shortcuts sample for LoggingActionDispatcher is outdated

### ISSUE THREAD

**Issue by navaronbracke** [flutter/website#9966]
### Page URL

https://docs.flutter.dev/ui/interactivity/actions-and-shortcuts

### Describe the problem

The documentation for shortcuts has a small issue with the code sample for the LoggingActionDispatcher.

It defines only an override of `invokeAction(...)`. But in practice, when setting up Actions, I found that `invokeActionIfEnabled(...)`
was invoked when I used the shortcuts, rather than `invokeAction()`.

### Expected fix

Update the code sample of the LoggingActionDispatcher to:

```dart
class LoggingActionsDispatcher extends ActionDispatcher {
  @override
  Object? invokeAction(
    covariant Action<Intent> action,
    covariant Intent intent, [
    BuildContext? context,
  ]) {
    print('invokeAction(): $action($intent) from $context');
    super.invokeAction(action, intent, context);

    return null;
  }

  @override
  (bool, Object?) invokeActionIfEnabled(
    covariant Action<Intent> action,
    covariant Intent intent, [
    BuildContext? context,
  ]) {
    print('invokeActionIfEnabled(): $action($intent) from $context');

    return super.invokeActionIfEnabled(action, intent, context);
  }
}
```

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by dam-ease** [comment]
Thanks for filing this @navaronbracke.
Testing with shortcuts, I see that `invokeActionIfEnabled()` is invoked instead of `invokeAction()`.

<details><summary>Logs</summary>
<p>

```
flutter: Action invoked: CopyAction#b1e80(CopyIntent#2c36d) from Builder(dependencies: [_ActionsScope])
flutter: Action invoked: SelectAllAction#35c7c(SelectAllIntent#c22e9) from Builder(dependencies: [_ActionsScope])
2
flutter: invokeActionIfEnabled(): _OverridableContextAction<CopySelectionTextIntent>#7038c(defaultAction: _CopySelectionAction#ad1d5)(CopySelectionTextIntent#3f7ae) from Focus(debugLabel: "EditableText", focusNode: FocusNode#3f894([PRIMARY FOCUS]), dependencies: [_ActionsScope, _ActionsScope, _FocusInheritedScope], state: _FocusState#7b57b)
``` 

</p>
</details>
