### ISSUE TITLE
Add Flutter PATH for macOS install pages

### ISSUE THREAD

**Issue by mintymac** [flutter/website#9983]
### Page URL

https://docs.flutter.dev/get-started/install/macos/web/

### Page source

https://github.com/flutter/website/tree/main/src/get-started/install/macos/web.md

### Describe the problem

Installation assumes flutter on terminal path and there is no step to accomplish this. 

### Expected fix

add export PATH="/Users/{USERNAME}/development/flutter/bin:$PATH" to ~/.zshrc  

### I would like to fix this problem.

- [X] I will try and fix this problem on docs.flutter.dev.

**Comment by huycozy** [comment]
Thanks for the report. I see this is missing on [`Start building Flutter native desktop apps on macOS`](https://docs.flutter.dev/get-started/install/macos/desktop?tab=download) page as well.

**Comment by atsansone** [comment]
This duplicates #9351. Closing this issue.
