### ISSUE TITLE
[PAGE ISSUE]: 'Add ads to your mobile Flutter app or game'

### ISSUE THREAD

**Issue by strength0179** [flutter/website#9990]
### Page URL

https://docs.flutter.dev/cookbook/plugins/google-mobile-ads/

### Page source

https://github.com/flutter/website/tree/main/src/cookbook/plugins/google-mobile-ads.md

### Describe the problem

The Android version is not working.
No contents about how to setting gradle

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by zoeyfan** [comment]
@filiph FYI on this.
