### ISSUE TITLE
Slack invite link is broken again

### ISSUE THREAD

**Issue by jsloop42** [flutter/website#9991]
### Page URL

https://fluttercommunity.dev/joinslack

### Describe the problem

The link from the flutter community dev site to join Slack channel is broken again.

https://fluttercommunity.slack.com/join/shared_invite/zt-26vgzjpw2-C8xWpIK0hJnTNCa3FIj_1Q#/shared-invite/error

### Expected fix

Link should enable joining Flutter Slack community.

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by parlough** [comment]
\cc @slightfoot Could you update the redirect at https://fluttercommunity.dev/joinslack?

Thank you!

**Comment by slightfoot** [comment]
done

**Comment by parlough** [comment]
Thank you @slightfoot, and thank you @jsloop42 for the issue!
