### ISSUE TITLE
[Feature Request]: Add Tiled as a resource on the 'Casual Games Toolkit' page

### ISSUE THREAD

**Issue by zoeyfan** [flutter/website#9998]
### Page URL

https://docs.flutter.dev/resources/games-toolkit/

### Page source

https://github.com/flutter/website/tree/main/src/resources/games-toolkit.md

### Describe the problem

<img width="984" alt="image" src="https://github.com/flutter/website/assets/52673903/648519ea-a5a7-4312-bd66-8f3dfd6c4c2a">
In the resources section, can we add another resource?

Tiled: https://www.mapeditor.org/ 
It is a free and open source level editor, and they also support Flame. 

### Expected fix

In the "Other resources" section,
under "Feature", add "Level editor", 
under "Resources", add "Tiled" with a hyperlink https://www.mapeditor.org/ 

### I would like to fix this problem.

- [ ] I will try and fix this problem on docs.flutter.dev.

**Comment by ghanghavmayur** [comment]
# #10003
I've submitted a pull request that addresses issue #9998.Please review my PR #10003 and provide feedback.

**Comment by ghanghavmayur** [comment]
# #10013
## I've submitted a pull request(#10013) that addresses issue #9998.
